# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mk import card, insert, check, progress

C = []

C.append(card(1196, 'Vijftig Bunder', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Bos &amp; heiderestant \u00b7 verdeelde markegrond', 'list 33 \u00b7 no. 165'],
 loc='\U0001f4cd Bij Rolde / Grolloo \u00b7 Bos- en heideterrein \u00b7 Middelgroot',
 desc='<b>Vijftig Bunder</b> draagt, net als De Twintig Bunders verderop, zijn ontstaansgeschiedenis in de naam: vijftig bunder \u2014 ongeveer vijftig hectare \u2014 was de maat van het perceel dat na de <b>Markenwet van 1886</b> als \u00e9\u00e9n blok uit de gemeenschappelijke heide werd gesneden. Dat de Drenten hun nieuwe percelen simpelweg naar hun oppervlakte noemden zegt iets over hoe abrupt die verdeling ging: eeuwenoude veldnamen maakten plaats voor boekhoudkundige aanduidingen. Het blok werd beplant met <b>grove den</b>, en dat bos staat er nog, inmiddels als volwassen opstand met zware stammen. Aan de randen en op enkele open plekken is de <b>oorspronkelijke heide</b> bewaard of teruggehaald door plaggen. Het beheer werkt aan meer variatie: <b>dunnen, loofhoutinbreng en dood hout laten liggen</b>. Dat levert een bos op waar <b>zwarte specht, havik en boommarter</b> zich thuis voelen, met op de open heidedelen levendbarende hagedis en heivlinder.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013mei (zang en baltsende havik), aug (heide), okt\u2013nov (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 specht en havik zijn dan het actiefst.',
 why=['Naam als <b>boekhoudkundig relict</b> van de Markenwet van 1886.',
      'Volwassen <b>grovedennenopstand</b> met zware stammen.',
      'Teruggeplagde <b>heiderestanten</b> aan de randen.',
      '<b>Havik, zwarte specht en boommarter</b> in het bos.'],
 phen=['<span class="months">Feb\u2013Apr</span> \U0001f985 <b>Havik</b> baltst boven het kronendak.',
       '<span class="months">Apr\u2013Mei</span> \U0001fab5 <b>Zwarte specht</b> roffelt op dode dennen.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Struikhei</b> bloeit op de open plekken.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Paddenstoelen</b> onder de dennen.'],
 wild=['\U0001f985 Havik', '\U0001fab5 Zwarte specht', '\U0001f43f\ufe0f Boommarter', '\U0001f98e Levendbarende hagedis', '\U0001f333 Grove den \u00b7 Struikhei \u00b7 Bochtige smele'],
 trail=['Parkeren bij <b>Rolde</b> of Grolloo; zandwegen doorkruisen het bos.',
        'Rustig gebied \u2014 goed te combineren met het <b>Ballo\u00ebrveld</b> of Gemeentebos Rolde.',
        'Beheer: <b>Staatsbosbeheer</b>.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Naamniveau-kaart \u2014 beperkte publieke documentatie'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Woodland &amp; heath remnant \u00b7 divided common land', 'list 33 \u00b7 no. 165'],
 loc='\U0001f4cd Near Rolde / Grolloo \u00b7 Woodland and heath \u00b7 Medium-sized',
 desc='<b>Vijftig Bunder</b>, like De Twintig Bunders further on, carries its origin in its name: fifty bunder \u2014 about fifty hectares \u2014 was the size of the parcel cut as a single block from the common heath after the <b>Marken Act of 1886</b>. That the people of Drenthe simply named their new parcels after their acreage says something about how abrupt that division was: centuries-old field names gave way to bookkeeping labels. The block was planted with <b>Scots pine</b>, and that wood still stands, now a mature stand with heavy trunks. Along the edges and in a few clearings the <b>original heath</b> has been preserved or brought back by sod cutting. Management works towards more variety: <b>thinning, introducing broadleaf and leaving dead wood</b>. The result is a wood in which <b>black woodpecker, goshawk and pine marten</b> are at home, with viviparous lizard and grayling on the open heath.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013May (song and displaying goshawk), Aug (heather), Oct\u2013Nov (fungi)<br>\n    <b>Best time of day:</b> Early morning \u2014 woodpecker and goshawk are then most active.',
 why=['A name that is a <b>bookkeeping relic</b> of the 1886 Marken Act.',
      'A mature <b>Scots pine stand</b> with heavy trunks.',
      'Restored <b>heath remnants</b> along the margins.',
      '<b>Goshawk, black woodpecker and pine marten</b> in the wood.'],
 phen=['<span class="months">Feb\u2013Apr</span> \U0001f985 <b>Goshawk</b> displays above the canopy.',
       '<span class="months">Apr\u2013May</span> \U0001fab5 <b>Black woodpecker</b> drums on dead pines.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Ling</b> flowers in the clearings.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Fungi</b> beneath the pines.'],
 wild=['\U0001f985 Northern goshawk', '\U0001fab5 Black woodpecker', '\U0001f43f\ufe0f Pine marten', '\U0001f98e Viviparous lizard', '\U0001f333 Scots pine \u00b7 Ling \u00b7 Wavy hair-grass'],
 trail=['Park at <b>Rolde</b> or Grolloo; sandy tracks cross the wood.',
        'A quiet area \u2014 easily combined with the <b>Ballo\u00ebrveld</b> or Gemeentebos Rolde.',
        'Managed by <b>Staatsbosbeheer</b>.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Name-level entry \u2014 limited public documentation')))

C.append(card(1197, 'Ter Borghbos', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Landgoedbos \u00b7 oude lanen en beukenopstanden', 'list 33 \u00b7 no. 166'],
 loc='\U0001f4cd Bij Schipborg, aansluitend op het Evertsbos \u00b7 Loof- en gemengd bos \u00b7 Middelgroot',
 desc='Het <b>Ter Borghbos</b> bij Schipborg hoort bij het landgoed waaraan ook het Pinetum ter Borgh zijn naam ontleent, en is daarmee een van de weinige <b>landgoedbossen</b> op de noordelijke Hondsrug. Anders dan de zakelijke boswachterijen van Staatsbosbeheer is dit bos <b>ontworpen</b>: er lopen rechte <b>beukenlanen</b> doorheen die zichtlijnen vormen naar het huis en de omliggende velden, en de opstanden zijn afwisselend van soort en leeftijd omdat opeenvolgende eigenaren hun eigen voorkeuren aanplantten. Dat maakt het ecologisch waardevol: <b>oude beuken met holtes</b> naast jonge eik en es, dood hout dat blijft liggen, en een gevarieerde ondergroei met hulst, hazelaar en lijsterbes. In het voorjaar bloeit onder de lanen een bescheiden <b>stinzenflora</b>, een erfenis van het landgoedbeheer. De vogelbevolking is die van oud loofbos: <b>bosuil, glanskop, boomklever, appelvink</b> en spechten die de zachte beukenstammen graag uithakken.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013mei (voorjaarsflora en zang), okt\u2013nov (beukenlanen in herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Ochtend \u2014 licht door de lanen, spechten actief.',
 why=['<b>Ontworpen landgoedbos</b> met rechte beukenlanen en zichtlijnen.',
      'Gemengde opstanden van <b>verschillende leeftijden en soorten</b>.',
      'Oude beuken met <b>holtes en dood hout</b> voor uilen en vleermuizen.',
      'Bescheiden <b>stinzenflora</b> onder de lanen.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f33c <b>Stinzenflora</b> bloeit langs de lanen.',
       '<span class="months">Apr\u2013Mei</span> \U0001f426 <b>Appelvink en glanskop</b> in het kronendak.',
       '<span class="months">Aug\u2013Sep</span> \U0001f330 <b>Beukennootjes</b> \u2014 mastjaar trekt gaaien en eekhoorns.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Beukenlanen</b> in koperkleur.'],
 wild=['\U0001f989 Bosuil', '\U0001f426 Appelvink', '\U0001f426 Boomklever', '\U0001f987 Rosse vleermuis', '\U0001f333 Beuk \u00b7 Zomereik \u00b7 Hulst'],
 trail=['Parkeren bij <b>Schipborg</b>; het bos sluit aan op het Evertsbos.',
        'Combineer met het <b>Pinetum ter Borgh</b> en het beekdal van de Drentsche Aa.',
        'Deels <b>particulier landgoed</b>: blijf op de opengestelde paden.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Deels particulier landgoed \u2014 respecteer de afsluitingen'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Estate woodland \u00b7 old avenues and beech stands', 'list 33 \u00b7 no. 166'],
 loc='\U0001f4cd Near Schipborg, adjoining the Evertsbos \u00b7 Broadleaf and mixed woodland \u00b7 Medium-sized',
 desc='The <b>Ter Borghbos</b> near Schipborg belongs to the estate from which the Pinetum ter Borgh also takes its name, making it one of the few <b>estate woods</b> on the northern Hondsrug. Unlike the businesslike state forestry plantations this wood was <b>designed</b>: straight <b>beech avenues</b> run through it forming sight lines towards the house and the surrounding fields, and the stands vary in species and age because successive owners planted their own preferences. That makes it ecologically valuable: <b>old beeches with cavities</b> beside young oak and ash, dead wood left where it falls, and a varied understorey of holly, hazel and rowan. In spring a modest <b>stinzen flora</b> flowers beneath the avenues, a legacy of estate management. The bird community is that of old broadleaf woodland: <b>tawny owl, marsh tit, nuthatch, hawfinch</b> and woodpeckers that readily excavate the soft beech trunks.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013May (spring flora and song), Oct\u2013Nov (beech avenues in autumn colour)<br>\n    <b>Best time of day:</b> Morning \u2014 light down the avenues, woodpeckers active.',
 why=['A <b>designed estate wood</b> with straight beech avenues and sight lines.',
      'Mixed stands of <b>differing ages and species</b>.',
      'Old beeches with <b>cavities and dead wood</b> for owls and bats.',
      'A modest <b>stinzen flora</b> beneath the avenues.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f33c <b>Stinzen flora</b> flowers along the avenues.',
       '<span class="months">Apr\u2013May</span> \U0001f426 <b>Hawfinch and marsh tit</b> in the canopy.',
       '<span class="months">Aug\u2013Sep</span> \U0001f330 <b>Beech mast</b> \u2014 a mast year draws jays and squirrels.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Beech avenues</b> in copper.'],
 wild=['\U0001f989 Tawny owl', '\U0001f426 Hawfinch', '\U0001f426 Nuthatch', '\U0001f987 Noctule bat', '\U0001f333 Beech \u00b7 Pedunculate oak \u00b7 Holly'],
 trail=['Park at <b>Schipborg</b>; the wood adjoins the Evertsbos.',
        'Combine with the <b>Pinetum ter Borgh</b> and the Drentsche Aa valley.',
        'Partly a <b>private estate</b>: keep to the paths open to the public.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Partly private estate \u2014 respect closures'),
 card_class='card estate'))

C.append(card(1198, 'Hondsrug Noord', dict(
 tags=['Drenthe / Groningen \u00b7 Aa en Hunze \u00b7 Tynaarlo', 'Keileemrug \u00b7 UNESCO Global Geopark', 'list 33 \u00b7 no. 167'],
 loc='\U0001f4cd Van Groningen via Zuidlaren en Anloo tot Gieten \u00b7 Landschappelijke rug \u00b7 Zeer groot gebied',
 desc='De <b>Hondsrug</b> is de meest karakteristieke landvorm van Noordoost-Nederland: een <b>keileemrug</b> van ruim zeventig kilometer die als een langgerekte golf van Emmen naar de stad Groningen loopt. Hij ontstond in de <b>voorlaatste ijstijd</b>, toen het landijs vanuit Scandinavi\u00eb over dit gebied schoof en de ondergrond in evenwijdige ruggen en laagten kneedde \u2014 een proces dat geologen <b>megaflutes</b> noemen en dat in deze vorm in Europa uniek is. Om die reden is het gebied sinds <b>2013 UNESCO Global Geopark</b>. Het noordelijke deel, tussen Gieten en Groningen, is de smalste en scherpst afgetekende sectie: aan weerszijden vallen de flanken af naar het <b>Hunzedal</b> in het oosten en het <b>Drentsche Aa-dal</b> in het westen. Op de rug liggen de esdorpen \u2014 Anloo, Annen, Zuidlaren \u2014 met hun bolle essen, en de <b>hunebedden</b>, want de zwerfkeien die het ijs meebracht leverden de bouwstenen. Landschappelijk rijg je hier heide, strubben, bos en beekdal aan \u00e9\u00e9n lijn.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013mei (voorjaar op de flanken), aug (heide), okt\u2013nov (herfst en mist in de dalen)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 mist in de dalen laat de rug als eiland uitsteken.',
 why=['Unieke <b>megaflute-ruggen</b> uit de voorlaatste ijstijd.',
      '<b>UNESCO Global Geopark</b> sinds 2013.',
      'Reeks <b>esdorpen en hunebedden</b> op de rug.',
      'Scherpe flanken naar <b>Hunzedal</b> en <b>Drentsche Aa</b>.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Voorjaarsbloei</b> in de houtwallen op de flanken.',
       '<span class="months">Jun\u2013Jul</span> \U0001f989 <b>Nachtzwaluw</b> op de heidevelden van de rug.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Heidebloei</b> op Ballo\u00ebrveld en Groote Veld.',
       '<span class="months">Okt\u2013Nov</span> \U0001f32b\ufe0f <b>Ochtendmist</b> in de flankdalen \u2014 de rug steekt eruit.'],
 wild=['\U0001f9a1 Das', '\U0001f985 Havik', '\U0001f426 Geelgors', '\U0001f98c Ree', '\U0001f333 Zomereik \u00b7 Jeneverbes \u00b7 Struikhei'],
 trail=['Startpunten in <b>Zuidlaren, Anloo, Annen en Gieten</b>; het Hondsrugpad volgt de rug.',
        'Het <b>Hunebedcentrum in Borger</b> is het informatiepunt van het Geopark.',
        'Zeer uitgestrekt \u2014 kies vooraf een deeltraject.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f30d UNESCO Global Geopark de Hondsrug'),
 dict(
 tags=['Drenthe / Groningen \u00b7 Aa en Hunze \u00b7 Tynaarlo', 'Boulder-clay ridge \u00b7 UNESCO Global Geopark', 'list 33 \u00b7 no. 167'],
 loc='\U0001f4cd From Groningen via Zuidlaren and Anloo to Gieten \u00b7 Landscape ridge \u00b7 Very large area',
 desc='The <b>Hondsrug</b> is the most characteristic landform of the northeastern Netherlands: a <b>boulder-clay ridge</b> more than seventy kilometres long running like a drawn-out wave from Emmen to the city of Groningen. It formed in the <b>penultimate glaciation</b>, when the ice sheet pushed from Scandinavia across this area and kneaded the subsoil into parallel ridges and hollows \u2014 a process geologists call <b>megaflutes</b>, unique in Europe in this form. For that reason the area has been a <b>UNESCO Global Geopark since 2013</b>. The northern part, between Gieten and Groningen, is the narrowest and most sharply defined section: on either side the flanks drop away to the <b>Hunze valley</b> in the east and the <b>Drentsche Aa valley</b> in the west. On the ridge lie the esdorpen \u2014 Anloo, Annen, Zuidlaren \u2014 with their domed fields, and the <b>dolmens</b>, for the erratic boulders the ice carried supplied the building blocks. Here you can string heath, strubben, woodland and brook valley along a single line.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013May (spring on the flanks), Aug (heather), Oct\u2013Nov (autumn and mist in the valleys)<br>\n    <b>Best time of day:</b> Early morning \u2014 mist in the valleys makes the ridge stand out like an island.',
 why=['Unique <b>megaflute ridges</b> from the penultimate glaciation.',
      'A <b>UNESCO Global Geopark</b> since 2013.',
      'A chain of <b>esdorpen and dolmens</b> along the ridge.',
      'Sharp flanks down to the <b>Hunze valley</b> and the <b>Drentsche Aa</b>.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f338 <b>Spring blossom</b> in the hedgebanks on the flanks.',
       '<span class="months">Jun\u2013Jul</span> \U0001f989 <b>Nightjar</b> on the ridge heaths.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Heather bloom</b> on the Ballo\u00ebrveld and Groote Veld.',
       '<span class="months">Oct\u2013Nov</span> \U0001f32b\ufe0f <b>Morning mist</b> in the flanking valleys \u2014 the ridge stands clear.'],
 wild=['\U0001f9a1 Badger', '\U0001f985 Northern goshawk', '\U0001f426 Yellowhammer', '\U0001f98c Roe deer', '\U0001f333 Pedunculate oak \u00b7 Juniper \u00b7 Ling'],
 trail=['Starting points at <b>Zuidlaren, Anloo, Annen and Gieten</b>; the Hondsrug path follows the ridge.',
        'The <b>Hunebedcentrum at Borger</b> is the Geopark information point.',
        'Very extensive \u2014 choose a section in advance.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f30d UNESCO Global Geopark de Hondsrug')))

C.append(card(1199, "'t Ruige Veld", dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Heide, ven &amp; bos \u00b7 natuurontwikkeling', 'list 33 \u00b7 no. 168'],
 loc='\U0001f4cd Bij Rolde en Grolloo \u00b7 Heide- en bosterrein met vennen \u00b7 Middelgroot',
 desc="<b>'t Ruige Veld</b> bij Rolde is een gevarieerd terrein waar Het Drentse Landschap in de afgelopen decennia landbouwgrond heeft omgevormd tot natuur. De naam is ouder dan het project: <i>ruig</i> betekende in het Drents onontgonnen, onbewerkt \u2014 het veld dat te schraal of te nat was om te ploegen. In de twintigste eeuw werd het toch ontgonnen, en nu is die ingreep deels teruggedraaid. Door de <b>voedselrijke bouwvoor af te graven</b> kwam de oorspronkelijke schrale zandbodem weer bloot, en daarop vestigde zich in enkele jaren opnieuw <b>heide, buntgras en pioniervegetatie</b>. In de laagten zijn <b>vennen uitgegraven</b> die zich vulden met regenwater en waar nu heikikker, kleine watersalamander en libellen zich voortplanten. Rondom staat gemengd bos. Het terrein is een goed voorbeeld van hoe snel schrale natuur zich herstelt als je letterlijk de bovenlaag van een halve eeuw bemesting weghaalt \u2014 en hoeveel geduld de rest vraagt.",
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013sep</b>; apr (amfibie\u00ebn), jun\u2013aug (libellen), aug (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend voor vogels; warme middag voor libellen bij de vennen.',
 why=['Geslaagde <b>natuurontwikkeling</b> door afgraven van de bouwvoor.',
      'Nieuwe <b>vennen</b> met heikikker, salamanders en libellen.',
      'Snel herstelde <b>heide en pioniervegetatie</b> op schraal zand.',
      "Naam <i>ruig</i> als herinnering aan het onontgonnen veld."],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f438 <b>Heikikkers</b> planten zich voort in de nieuwe vennen.',
       '<span class="months">Mei\u2013Jun</span> \U0001f33e <b>Buntgras en pionierflora</b> op het afgegraven zand.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Libellen</b> koloniseren de vennen in hoog tempo.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Jonge heide</b> bloeit voor het eerst op de nieuwe delen.'],
 wild=['\U0001f438 Heikikker', '\U0001f98b Zwarte heidelibel', '\U0001f426 Roodborsttapuit', '\U0001f98e Levendbarende hagedis', '\U0001f33f Struikhei \u00b7 Buntgras \u00b7 Pilzegge'],
 trail=['Parkeren bij <b>Rolde</b> of Grolloo; gemarkeerde routes door het terrein.',
        'Jonge natuur \u2014 <b>vegetatie is kwetsbaar</b>, blijf op de paden.',
        'Beheer: <b>Het Drentse Landschap</b>.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Jonge natuurontwikkeling \u2014 vegetatie kwetsbaar'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Heath, pools &amp; woodland \u00b7 nature development', 'list 33 \u00b7 no. 168'],
 loc='\U0001f4cd Near Rolde and Grolloo \u00b7 Heath and woodland with pools \u00b7 Medium-sized',
 desc="<b>'t Ruige Veld</b> near Rolde is a varied site where Het Drentse Landschap has converted farmland into nature over recent decades. The name is older than the project: in the Drenthe dialect <i>ruig</i> meant unreclaimed, unworked \u2014 the field too poor or too wet to plough. In the twentieth century it was reclaimed after all, and now that intervention has partly been undone. By <b>stripping off the nutrient-rich topsoil</b> the original poor sandy ground was exposed again, and within a few years <b>heather, grey hair-grass and pioneer vegetation</b> established themselves on it. In the hollows <b>pools have been dug</b> that filled with rainwater and where moor frog, smooth newt and dragonflies now breed. Mixed woodland surrounds it. The site is a good example of how quickly poor-soil nature recovers when you literally remove the top layer of half a century of fertilising \u2014 and how much patience the rest demands.",
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b>; Apr (amphibians), Jun\u2013Aug (dragonflies), Aug (heather bloom)<br>\n    <b>Best time of day:</b> Morning for birds; warm midday for dragonflies at the pools.',
 why=['Successful <b>nature development</b> by stripping the topsoil.',
      'New <b>pools</b> with moor frog, newts and dragonflies.',
      'Rapidly recovered <b>heath and pioneer vegetation</b> on poor sand.',
      'The name <i>ruig</i> recalling the unreclaimed common.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f438 <b>Moor frogs</b> breed in the new pools.',
       '<span class="months">May\u2013Jun</span> \U0001f33e <b>Grey hair-grass and pioneer flora</b> on the stripped sand.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Dragonflies</b> colonise the pools rapidly.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Young heather</b> flowers for the first time on the new parts.'],
 wild=['\U0001f438 Moor frog', '\U0001f98b Black darter', '\U0001f426 Stonechat', '\U0001f98e Viviparous lizard', '\U0001f33f Ling \u00b7 Grey hair-grass \u00b7 Pill sedge'],
 trail=['Park at <b>Rolde</b> or Grolloo; waymarked routes cross the site.',
        'Young nature \u2014 the <b>vegetation is fragile</b>, keep to the paths.',
        'Managed by <b>Het Drentse Landschap</b>.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Young nature development \u2014 fragile vegetation')))

C.append(card(1200, 'Gemeentebos Rolde', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Gemeentelijk bos \u00b7 recreatie en natuur', 'list 33 \u00b7 no. 169'],
 loc='\U0001f4cd Bij Rolde \u00b7 Gemengd bos \u00b7 Middelgroot',
 desc='Het <b>Gemeentebos van Rolde</b> is een van die bossen die niet door een natuurorganisatie maar door de <b>gemeente</b> werden aangelegd \u2014 in de vroege twintigste eeuw een gebruikelijke investering, deels als werkverschaffing tijdens de crisisjaren, deels om brandhout en mijnhout te leveren, en deels omdat een dorp met een eigen bos aanzien had. Dat gemengde motief zie je terug in de opzet: <b>rechte paden in een regelmatig grid</b>, opstanden van grove den en lariks, en her en der een beukenlaan die het geheel wat allure moest geven. Inmiddels is het bos een eeuw oud en is het beheer verschoven naar natuur en recreatie: er wordt <b>omgevormd naar loofhout</b>, dood hout blijft liggen en er zijn open plekken gemaakt. Voor Rolde is het het dagelijkse ommetje-bos, met ruiterpaden en een <b>speelbos</b>, maar ecologisch doet het meer dan je zou verwachten: <b>ree, boommarter, havik en zwarte specht</b> zijn er vaste bewoners, en in de herfst is het een uitstekende paddenstoelenplek.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013mei (zang), sep\u2013nov (paddenstoelen), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 dan is het stil en zijn ree en specht actief.',
 why=['<b>Gemeentelijk werkverschaffingsbos</b> uit de vroege twintigste eeuw.',
      'Kenmerkend <b>grid van rechte paden</b> met een beukenlaan als allure.',
      'Omvorming naar <b>loofhout</b> en meer dood hout.',
      'Uitstekende <b>paddenstoelenplek</b> in de herfst.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f985 <b>Havik</b> baltst boven het bos.',
       '<span class="months">Apr\u2013Mei</span> \U0001fab5 <b>Zwarte specht</b> en boomklever in de oudere opstanden.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Paddenstoelen</b> in grote soortenrijkdom.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Beukenlaan</b> en lariks in herfstkleur.'],
 wild=['\U0001f985 Havik', '\U0001fab5 Zwarte specht', '\U0001f43f\ufe0f Boommarter', '\U0001f98c Ree', '\U0001f333 Grove den \u00b7 Lariks \u00b7 Beuk'],
 trail=['Parkeren in <b>Rolde</b>; het bos ligt direct aan het dorp.',
        'Ook <b>ruiterpaden en een speelbos</b> \u2014 geschikt voor gezinnen.',
        'Beheer: <b>gemeente Aa en Hunze</b>.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f6b8 Speelbos en ruiterpaden aanwezig'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Municipal woodland \u00b7 recreation and nature', 'list 33 \u00b7 no. 169'],
 loc='\U0001f4cd Near Rolde \u00b7 Mixed woodland \u00b7 Medium-sized',
 desc='The <b>Gemeentebos of Rolde</b> is one of those woods laid out not by a conservation body but by the <b>municipality</b> \u2014 in the early twentieth century a common investment, partly as job creation during the depression years, partly to supply firewood and pit props, and partly because a village with its own wood had standing. That mixed motive shows in the layout: <b>straight paths in a regular grid</b>, stands of Scots pine and larch, and here and there a beech avenue meant to lend the whole some grandeur. The wood is now a century old and management has shifted towards nature and recreation: it is being <b>converted to broadleaf</b>, dead wood is left lying and clearings have been created. For Rolde it is the everyday walking wood, with bridle paths and a <b>play forest</b>, but ecologically it does more than you might expect: <b>roe deer, pine marten, goshawk and black woodpecker</b> are permanent residents, and in autumn it is an excellent fungus site.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013May (song), Sep\u2013Nov (fungi), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Early morning \u2014 quiet, with roe deer and woodpeckers active.',
 why=['A <b>municipal job-creation wood</b> from the early twentieth century.',
      'A characteristic <b>grid of straight paths</b> with a beech avenue for grandeur.',
      'Conversion towards <b>broadleaf</b> and more dead wood.',
      'An excellent <b>fungus site</b> in autumn.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f985 <b>Goshawk</b> displays above the wood.',
       '<span class="months">Apr\u2013May</span> \U0001fab5 <b>Black woodpecker</b> and nuthatch in the older stands.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Fungi</b> in great variety.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Beech avenue</b> and larch in autumn colour.'],
 wild=['\U0001f985 Northern goshawk', '\U0001fab5 Black woodpecker', '\U0001f43f\ufe0f Pine marten', '\U0001f98c Roe deer', '\U0001f333 Scots pine \u00b7 Larch \u00b7 Beech'],
 trail=['Park in <b>Rolde</b>; the wood adjoins the village directly.',
        'Also <b>bridle paths and a play forest</b> \u2014 suitable for families.',
        'Managed by the <b>municipality of Aa en Hunze</b>.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f6b8 Play forest and bridle paths present')))

C.append(card(1201, 'Boerbos', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Boerenbosje \u00b7 hakhout en houtwallen', 'list 33 \u00b7 no. 170'],
 loc='\U0001f4cd Bij Grolloo / Schoonloo \u00b7 Klein bosperceel \u00b7 Klein terrein',
 desc='Het <b>Boerbos</b> is precies wat de naam zegt: een <b>boerenbosje</b>, een klein bosperceel dat bij een boerderij hoorde en dat in het esdorpsysteem een concrete functie had. Hier werd het <b>geriefhout</b> gehaald \u2014 het hout waarmee de boer zijn erf draaiende hield: stelen voor gereedschap, palen voor hekwerk, tenen voor manden, brandhout voor de kachel en bonenstaken voor de moestuin. Zulke bosjes werden als <b>hakhout</b> beheerd: elke acht tot vijftien jaar werd de hele opstand tot op de stobbe afgezet, waarna de eiken, elzen en essen weer uitliepen met meerdere stammen. Die cyclus is eeuwenlang volgehouden en heeft <b>meerstammige stobben</b> opgeleverd die soms honderden jaren oud zijn, ook al lijkt het hout jong. Ecologisch zijn deze bosjes goud waard in het open boerenland: ze bieden dekking en nestgelegenheid aan <b>das, ree, geelgors en steenuil</b>, en de regelmatige verjonging houdt een lichtrijke bodemflora in stand.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (bodemflora en zang), okt\u2013nov (herfstkleur), winter (hakhoutbeheer zichtbaar)<br>\n    <b>Beste tijd van de dag:</b> Avondschemer \u2014 das, steenuil en ree komen dan tevoorschijn.',
 why=['Klassiek <b>geriefhoutbosje</b> uit het esdorpsysteem.',
      '<b>Meerstammige hakhoutstobben</b>, mogelijk eeuwenoud.',
      'Dekking en nestplek voor <b>das, geelgors en steenuil</b>.',
      'Lichtrijke <b>bodemflora</b> dankzij de hakhoutcyclus.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f33c <b>Speenkruid en bosanemoon</b> op de bosbodem.',
       '<span class="months">Mei\u2013Jun</span> \U0001f426 <b>Geelgors en zwartkop</b> zingen vanaf de randen.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Herfstkleur</b> in eik en es.',
       '<span class="months">Dec\u2013Feb</span> \U0001fa93 <b>Hakhout wordt afgezet</b> \u2014 de oude cyclus in bedrijf.'],
 wild=['\U0001f9a1 Das', '\U0001f989 Steenuil', '\U0001f426 Geelgors', '\U0001f98c Ree', '\U0001f333 Zomereik \u00b7 Zwarte els \u00b7 Hazelaar'],
 trail=['Parkeren bij <b>Grolloo</b> of Schoonloo; het bosje ligt aan een landweg.',
        'Klein object \u2014 combineer met <b>Vijftig Bunder</b> of het Ruige Veld.',
        'Vaak <b>particulier bezit</b>: blijf op de openbare weg en paden.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Vaak particulier \u2014 beperkte publieke documentatie'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Farm copse \u00b7 coppice and hedgebanks', 'list 33 \u00b7 no. 170'],
 loc='\U0001f4cd Near Grolloo / Schoonloo \u00b7 Small woodland parcel \u00b7 Small site',
 desc='The <b>Boerbos</b> is exactly what the name says: a <b>farm copse</b>, a small parcel of woodland belonging to a farm and serving a concrete function in the esdorp system. This is where the <b>utility wood</b> came from \u2014 the timber that kept the farmyard running: handles for tools, posts for fencing, withies for baskets, firewood for the stove and bean poles for the kitchen garden. Such copses were managed as <b>coppice</b>: every eight to fifteen years the whole stand was cut back to the stool, after which the oaks, alders and ashes resprouted with several stems. That cycle was kept up for centuries and produced <b>multi-stemmed stools</b> that can be hundreds of years old even though the wood looks young. Ecologically these copses are worth their weight in gold in open farmland: they give cover and nest sites to <b>badger, roe deer, yellowhammer and little owl</b>, and the regular rejuvenation maintains a light-demanding ground flora.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (ground flora and song), Oct\u2013Nov (autumn colour), winter (coppicing visible)<br>\n    <b>Best time of day:</b> Dusk \u2014 badger, little owl and roe deer emerge.',
 why=['A classic <b>utility-wood copse</b> from the esdorp system.',
      '<b>Multi-stemmed coppice stools</b>, possibly centuries old.',
      'Cover and nest sites for <b>badger, yellowhammer and little owl</b>.',
      'A light-rich <b>ground flora</b> maintained by the coppice cycle.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f33c <b>Celandine and wood anemone</b> on the woodland floor.',
       '<span class="months">May\u2013Jun</span> \U0001f426 <b>Yellowhammer and blackcap</b> sing from the margins.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Autumn colour</b> in oak and ash.',
       '<span class="months">Dec\u2013Feb</span> \U0001fa93 <b>Coppice is cut</b> \u2014 the old cycle at work.'],
 wild=['\U0001f9a1 Badger', '\U0001f989 Little owl', '\U0001f426 Yellowhammer', '\U0001f98c Roe deer', '\U0001f333 Pedunculate oak \u00b7 Black alder \u00b7 Hazel'],
 trail=['Park at <b>Grolloo</b> or Schoonloo; the copse lies along a country lane.',
        'A small site \u2014 combine with <b>Vijftig Bunder</b> or the Ruige Veld.',
        'Often <b>private property</b>: keep to the public road and paths.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Often private \u2014 limited public documentation')))

C.append(card(1202, 'Amerdiep en Geelbroek', dict(
 tags=['Drenthe \u00b7 Aa en Hunze \u00b7 Assen', 'Beekdal &amp; broekbos \u00b7 natte natuurherstel', 'list 33 \u00b7 no. 171'],
 loc='\U0001f4cd Tussen Assen, Rolde en Ekehaar \u00b7 Beekdal met broekbos en hooilanden \u00b7 Groot gebied',
 desc='Het <b>Amerdiep</b> is een bovenloop van het Drentsche Aa-systeem, en het <b>Geelbroek</b> is de brede natte laagte waarin die beek zijn water verzamelt. Samen vormen ze een van de meest succesvolle <b>natte natuurherstelprojecten</b> van Midden-Drenthe. Het Geelbroek was eeuwenlang een <b>broekbos</b> met hooilandjes \u2014 broek betekent moerassig laagland \u2014 maar werd in de twintigste eeuw ontwaterd voor de landbouw. Sinds de jaren 2010 is de waterhuishouding omgekeerd: <b>sloten zijn gedempt, de beek is hermeanderd en landbouwgrond is afgegraven</b>, waardoor het kwelwater dat vanuit de zandruggen toestroomt weer aan de oppervlakte komt. Het resultaat is een mozaek van <b>elzenbroekbos, zeggenmoeras en bloemrijk hooiland</b>. Botanisch komt hier het bijzondere terug: <b>waterdrieblad, holpijp, dotterbloem en diverse orchidee\u00ebn</b>. En met het water kwamen de dieren: <b>otter, bever, ijsvogel, waterral</b> en in het broekbos de zeldzame kleine bonte specht.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (dotterbloem, zang), mei\u2013jun (orchidee\u00ebn), nov\u2013feb (watervogels)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 otter, ijsvogel en waterral zijn dan actief.',
 why=['Geslaagd <b>nat natuurherstel</b> met hermeandering en vernatting.',
      'Herstelde <b>kwelstroom</b> voedt waterdrieblad en holpijp.',
      'Mozaek van <b>elzenbroek, zeggenmoeras en hooiland</b>.',
      '<b>Otter, bever en ijsvogel</b> keerden terug met het water.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f338 <b>Dotterbloem</b> kleurt de natte laagten geel.',
       '<span class="months">Apr\u2013Mei</span> \U0001f426 <b>Waterral</b> gilt in het zeggenmoeras.',
       '<span class="months">Mei\u2013Jun</span> \U0001f33a <b>Orchidee\u00ebn</b> in de herstelde hooilanden.',
       '<span class="months">Nov\u2013Feb</span> \U0001f9a2 <b>Watervogels</b> op de plas-drasdelen.'],
 wild=['\U0001f9a6 Otter', '\U0001f9ab Bever', '\U0001f426 IJsvogel', '\U0001f426 Waterral', '\U0001f33a Waterdrieblad \u00b7 Holpijp \u00b7 Dotterbloem'],
 trail=['Parkeren bij <b>Ekehaar</b>, Rolde of aan de rand van Assen.',
        'Natte paden \u2014 <b>laarzen aanbevolen</b>, vooral in winter en voorjaar.',
        'Beheer: <b>Staatsbosbeheer</b> en waterschap; binnen NP Drentsche Aa.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f97e Natte, deels overstroomde paden'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze \u00b7 Assen', 'Brook valley &amp; carr woodland \u00b7 wetland restoration', 'list 33 \u00b7 no. 171'],
 loc='\U0001f4cd Between Assen, Rolde and Ekehaar \u00b7 Brook valley with carr and hay meadows \u00b7 Large area',
 desc='The <b>Amerdiep</b> is a headwater of the Drentsche Aa system, and the <b>Geelbroek</b> is the broad wet hollow in which that brook gathers its water. Together they form one of the most successful <b>wetland restoration projects</b> in central Drenthe. The Geelbroek was for centuries a <b>carr woodland</b> with small hay meadows \u2014 broek means marshy lowland \u2014 but was drained for agriculture in the twentieth century. Since the 2010s the water regime has been reversed: <b>ditches filled, the brook remeandered and farmland stripped</b>, so that seepage water flowing in from the sand ridges reaches the surface again. The result is a mosaic of <b>alder carr, sedge marsh and flower-rich hay meadow</b>. Botanically the special things are returning: <b>bogbean, marsh horsetail, marsh marigold and several orchids</b>. And with the water came the animals: <b>otter, beaver, kingfisher, water rail</b> and, in the carr, the scarce lesser spotted woodpecker.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (marsh marigold, song), May\u2013Jun (orchids), Nov\u2013Feb (waterfowl)<br>\n    <b>Best time of day:</b> Early morning \u2014 otter, kingfisher and water rail are then active.',
 why=['Successful <b>wetland restoration</b> with remeandering and rewetting.',
      'Restored <b>seepage flow</b> feeding bogbean and marsh horsetail.',
      'A mosaic of <b>alder carr, sedge marsh and hay meadow</b>.',
      '<b>Otter, beaver and kingfisher</b> returned with the water.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f338 <b>Marsh marigold</b> turns the wet hollows yellow.',
       '<span class="months">Apr\u2013May</span> \U0001f426 <b>Water rail</b> squeals in the sedge marsh.',
       '<span class="months">May\u2013Jun</span> \U0001f33a <b>Orchids</b> in the restored hay meadows.',
       '<span class="months">Nov\u2013Feb</span> \U0001f9a2 <b>Waterfowl</b> on the shallow-flooded parts.'],
 wild=['\U0001f9a6 Otter', '\U0001f9ab Beaver', '\U0001f426 Kingfisher', '\U0001f426 Water rail', '\U0001f33a Bogbean \u00b7 Marsh horsetail \u00b7 Marsh marigold'],
 trail=['Park at <b>Ekehaar</b>, Rolde or on the edge of Assen.',
        'Wet paths \u2014 <b>boots recommended</b>, especially in winter and spring.',
        'Managed by <b>Staatsbosbeheer</b> and the water board; within Drentsche Aa NP.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f97e Wet, partly flooded paths'),
 card_class='card water',
 n2k='Drentsche Aa-gebied (gebied nr. 25) \u2014 Habitatrichtlijn',
 n2k_en='Drentsche Aa area (site no. 25) \u2014 Habitats Directive'))

C.append(card(1203, 'Papenvoort', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Esgehucht &amp; beekdalrand \u00b7 houtwallen', 'list 33 \u00b7 no. 172'],
 loc='\U0001f4cd Bij Rolde en Grolloo, aan het Amerdiep \u00b7 Gehucht met omringend landschap \u00b7 Middelgroot',
 desc='<b>Papenvoort</b> is een klein esgehucht tussen Rolde en Grolloo, en de naam vertelt een verhaal: een <b>voorde</b> was een doorwaadbare plaats in een beek, en <i>papen</i> verwijst naar geestelijken \u2014 dit was vermoedelijk de plek waar de weg van de geestelijkheid het <b>Amerdiep</b> kruiste, in de tijd dat bruggen zeldzaam waren en elke beek te voet of te paard genomen moest worden. Zulke voordennamen markeren de <b>oudste wegen</b> van Drenthe. Het gehucht zelf is klein gebleven: een handvol boerderijen rond een miniatuurbrink, met de bolle es ertegenaan en daaromheen een fijn netwerk van <b>houtwallen en singels</b>. Aan de noordzijde loopt het land af naar het beekdal, waar de vochtige graslanden overgaan in het herstelde natte gebied rond het Amerdiep. Die gradi\u00ebnt van droge es naar nat beekdal, over een afstand van enkele honderden meters, maakt het gebied rijk aan soorten: <b>das, geelgors, ree, steenuil</b> en langs de beek de ijsvogel.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (houtwalbloei), mei\u2013jun (zang), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Avondschemer \u2014 das en steenuil langs de houtwallen.',
 why=['Naam <b>Papenvoort</b> als spoor van een middeleeuwse doorwaadplaats.',
      'Gaaf klein <b>esgehucht</b> met miniatuurbrink en bolle es.',
      'Fijnmazig netwerk van <b>houtwallen en singels</b>.',
      'Korte <b>gradi\u00ebnt</b> van droge es naar nat beekdal.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Meidoorn en sleedoorn</b> bloeien in de houtwallen.',
       '<span class="months">Mei\u2013Jun</span> \U0001f426 <b>Geelgors</b> zingt vanaf de wallen; steenuil roept in de schemer.',
       '<span class="months">Aug\u2013Sep</span> \U0001f347 <b>Bessen en bramen</b> in de singels.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Houtwallen</b> in herfstkleur; paddenstoelen op de wallen.'],
 wild=['\U0001f9a1 Das', '\U0001f989 Steenuil', '\U0001f426 Geelgors', '\U0001f426 IJsvogel', '\U0001f333 Meidoorn \u00b7 Zomereik \u00b7 Sleedoorn'],
 trail=['Parkeren bij <b>Rolde</b> of Grolloo; landwegen en ommetjes verbinden het gehucht.',
        'Combineer met het <b>Amerdiep en Geelbroek</b> direct ten noorden.',
        'Grotendeels <b>particulier boerenland</b>: blijf op de openbare paden.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Deels particulier agrarisch land'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Field hamlet &amp; valley edge \u00b7 hedgebanks', 'list 33 \u00b7 no. 172'],
 loc='\U0001f4cd Near Rolde and Grolloo, on the Amerdiep \u00b7 Hamlet with surrounding landscape \u00b7 Medium-sized',
 desc='<b>Papenvoort</b> is a small field hamlet between Rolde and Grolloo, and the name tells a story: a <b>voorde</b> was a ford across a brook, and <i>papen</i> refers to clergy \u2014 this was probably where the priests\u2019 road crossed the <b>Amerdiep</b>, in an age when bridges were rare and every brook had to be taken on foot or on horseback. Such ford names mark the <b>oldest roads</b> of Drenthe. The hamlet itself has stayed small: a handful of farms around a miniature green, with the domed arable field against it and around that a fine network of <b>hedgebanks and shelterbelts</b>. On the north side the land falls away to the brook valley, where damp grasslands merge into the restored wetland around the Amerdiep. That gradient from dry field to wet valley, over a few hundred metres, makes the area rich in species: <b>badger, yellowhammer, roe deer, little owl</b> and, along the brook, the kingfisher.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (hedgebank blossom), May\u2013Jun (song), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Dusk \u2014 badger and little owl along the hedgebanks.',
 why=['The name <b>Papenvoort</b> as a trace of a medieval ford.',
      'An intact small <b>field hamlet</b> with miniature green and domed field.',
      'A fine-meshed network of <b>hedgebanks and shelterbelts</b>.',
      'A short <b>gradient</b> from dry field to wet brook valley.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f338 <b>Hawthorn and blackthorn</b> flower in the hedgebanks.',
       '<span class="months">May\u2013Jun</span> \U0001f426 <b>Yellowhammer</b> sings from the banks; little owl calls at dusk.',
       '<span class="months">Aug\u2013Sep</span> \U0001f347 <b>Berries and brambles</b> in the shelterbelts.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Hedgebanks</b> in autumn colour; fungi on the banks.'],
 wild=['\U0001f9a1 Badger', '\U0001f989 Little owl', '\U0001f426 Yellowhammer', '\U0001f426 Kingfisher', '\U0001f333 Hawthorn \u00b7 Pedunculate oak \u00b7 Blackthorn'],
 trail=['Park at <b>Rolde</b> or Grolloo; country lanes and short loops link the hamlet.',
        'Combine with the <b>Amerdiep and Geelbroek</b> immediately to the north.',
        'Largely <b>private farmland</b>: keep to the public paths.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Partly private farmland'),
 card_class='card estate'))

C.append(card(1204, 'Gieten', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Esdorp op de Hondsrug \u00b7 brink, bos en vennen', 'list 33 \u00b7 no. 173'],
 loc='\U0001f4cd Gieten, op de Hondsrug tussen Gasselte en Annen \u00b7 Esdorp met omringend landschap \u00b7 Groot gebied',
 desc='<b>Gieten</b> ligt precies op de kam van de Hondsrug, en dat bepaalt alles aan het dorp. Het is een klassiek <b>esdorp</b> met een <b>brink</b>, eeuwenoude zomereiken en boerderijen die met hun voorgevel naar de open ruimte staan gekeerd. De <b>essen</b> liggen op de rug ten zuiden en westen van het dorp, en de laagtes aan weerszijden \u2014 richting het Hunzedal in het oosten, richting de Drentsche Aa in het westen \u2014 waren de <b>madelanden</b> en het gemeenschappelijke veld. In de bossen rond het dorp ligt het <b>Zwanemeer</b>, de grote pingoru\u00efne, en verderop het Slotveen. Gieten was in de negentiende eeuw een knooppunt van veenwegen naar de Groninger veenkoloni\u00ebn, en de doorgaande route over de rug bracht welvaart. Het omringende landschap is een dwarsdoorsnede van de Hondsrug: <b>es, brink, houtwal, bos, ven en beekdalrand</b> binnen enkele kilometers, met grafheuvels en de restanten van oude karrensporen ertussen.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013mei (voorjaar op de brink en in het bos), aug (heide), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 het dorp is stil en de vennen dampen.',
 why=['Klassiek <b>esdorp op de kam</b> van de Hondsrug.',
      '<b>Brink met eeuwenoude zomereiken</b> als sociaal hart.',
      'Het <b>Zwanemeer</b> en Slotveen in de bossen rondom.',
      'Complete <b>Hondsrug-dwarsdoorsnede</b> binnen enkele kilometers.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f33f <b>Voorjaarsgroen</b> op de brink en in de bossen.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Libellen</b> boven het Zwanemeer.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Heidebloei</b> op de heiderestanten rond het dorp.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Brinkeiken</b> in herfstkleur; mist in de flankdalen.'],
 wild=['\U0001f426 Boomklever', '\U0001f989 Bosuil', '\U0001f98c Ree', '\U0001f426 Dodaars (Zwanemeer)', '\U0001f333 Zomereik \u00b7 Beuk \u00b7 Grove den'],
 trail=['Parkeren aan de <b>brink van Gieten</b>; routes leiden naar het Zwanemeer en de bossen.',
        'Het <b>Hondsrugpad</b> loopt door het dorp \u2014 goed startpunt voor een dagtocht.',
        'De essen zijn <b>particulier akkerland</b>: blijf op de paden.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f30d Binnen UNESCO Geopark de Hondsrug'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Esdorp on the Hondsrug \u00b7 green, woods and pools', 'list 33 \u00b7 no. 173'],
 loc='\U0001f4cd Gieten, on the Hondsrug between Gasselte and Annen \u00b7 Esdorp with surrounding landscape \u00b7 Large area',
 desc='<b>Gieten</b> lies exactly on the crest of the Hondsrug, and that determines everything about the village. It is a classic <b>esdorp</b> with a <b>brink</b> (village green), centuries-old pedunculate oaks and farmhouses whose fronts face the open space. The <b>arable fields</b> lie on the ridge south and west of the village, and the hollows on either side \u2014 towards the Hunze valley in the east, towards the Drentsche Aa in the west \u2014 were the <b>hay meadows</b> and the common. In the woods around the village lies the <b>Zwanemeer</b>, the great pingo scar, and further on the Slotveen. In the nineteenth century Gieten was a junction of peat roads to the Groningen peat colonies, and the through route along the ridge brought prosperity. The surrounding landscape is a cross-section of the Hondsrug: <b>field, green, hedgebank, wood, pool and valley edge</b> within a few kilometres, with burial mounds and the remains of old cart tracks between them.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013May (spring on the green and in the woods), Aug (heather), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Early morning \u2014 the village is quiet and the pools steam.',
 why=['A classic <b>esdorp on the crest</b> of the Hondsrug.',
      'A <b>green with centuries-old oaks</b> as the social heart.',
      'The <b>Zwanemeer</b> and Slotveen in the woods around.',
      'A complete <b>Hondsrug cross-section</b> within a few kilometres.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f33f <b>Spring green</b> on the village green and in the woods.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Dragonflies</b> above the Zwanemeer.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Heather bloom</b> on the heath remnants around the village.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Green oaks</b> in autumn colour; mist in the flanking valleys.'],
 wild=['\U0001f426 Nuthatch', '\U0001f989 Tawny owl', '\U0001f98c Roe deer', '\U0001f426 Little grebe (Zwanemeer)', '\U0001f333 Pedunculate oak \u00b7 Beech \u00b7 Scots pine'],
 trail=['Park on the <b>green at Gieten</b>; routes lead to the Zwanemeer and the woods.',
        'The <b>Hondsrug path</b> runs through the village \u2014 a good start for a day walk.',
        'The arable fields are <b>private farmland</b>: keep to the paths.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f30d Within UNESCO Geopark de Hondsrug'),
 card_class='card estate'))

C.append(card(1205, 'Sekmeer', dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Ven &amp; natte heide \u00b7 pingoru\u00efne', 'list 33 \u00b7 no. 174'],
 loc='\U0001f4cd Bij Gasselte / Drouwen, op de Hondsrug \u00b7 Ven met heide en bos \u00b7 Klein terrein',
 desc='Het <b>Sekmeer</b> is een klein ven op de Hondsrug bij Gasselte, en net als het Zwanemeer en talloze andere ronde laagten in dit landschap gaat het vrijwel zeker om een <b>pingoru\u00efne</b> uit de laatste ijstijd. Wat het Sekmeer interessant maakt is de <b>gradi\u00ebnt</b> die er in korte afstand te zien is: van open water via een drijvende veenmoszoom en natte dophei naar droge struikhei op de zandkoppen, en vandaar in het omringende grovedennenbos. Zulke complete overgangen zijn zeldzaam geworden \u2014 op de meeste plekken is er wel een schakel uit de reeks verdwenen door ontwatering of vermesting. Het ven is <b>voedselarm en zwak zuur</b>, met veenpluis, snavelzegge en op de oevers plaatselijk moerashertshooi. Voor amfibie\u00ebn en libellen is het een belangrijke voortplantingsplek: <b>heikikker, kleine watersalamander, zwarte heidelibel en venwitsnuitlibel</b>. Het beheer richt zich op het openhouden van de oeverzone en het tegengaan van verbossing.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013sep</b>; apr (heikikkers), jun\u2013aug (libellen), aug (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Warme middag voor libellen; vroege ochtend voor spiegelend water.',
 why=['Waarschijnlijk een <b>pingoru\u00efne</b> op de Hondsrug.',
      'Complete <b>gradi\u00ebnt</b> van open water tot droge heide en bos.',
      'Voedselarm ven met <b>veenpluis en moerashertshooi</b>.',
      'Belangrijke voortplantingsplek voor <b>heikikker en libellen</b>.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f438 <b>Heikikkers</b> roepen en kleuren blauw.',
       '<span class="months">Mei\u2013Jun</span> \U0001f33f <b>Veenpluis</b> op de natte oeverzone.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Heidelibellen</b> patrouilleren boven het ven.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Dop- en struikhei</b> bloeien rond het water.'],
 wild=['\U0001f438 Heikikker', '\U0001f98b Zwarte heidelibel', '\U0001f98b Venwitsnuitlibel', '\U0001f98e Levendbarende hagedis', '\U0001f33f Veenpluis \u00b7 Snavelzegge \u00b7 Moerashertshooi'],
 trail=['Parkeren bij <b>Gasselte</b> of Drouwen; bospaden leiden naar het ven.',
        'De <b>oeverzone niet betreden</b> \u2014 pionierflora is zeer gevoelig voor betreding.',
        'Beheer: <b>Staatsbosbeheer</b>.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Kwetsbare venoever \u2014 blijf op het pad'),
 dict(
 tags=['Drenthe \u00b7 Aa en Hunze', 'Pool &amp; wet heath \u00b7 pingo scar', 'list 33 \u00b7 no. 174'],
 loc='\U0001f4cd Near Gasselte / Drouwen, on the Hondsrug \u00b7 Pool with heath and woodland \u00b7 Small site',
 desc='The <b>Sekmeer</b> is a small pool on the Hondsrug near Gasselte and, like the Zwanemeer and countless other round hollows in this landscape, it is almost certainly a <b>pingo scar</b> from the last glaciation. What makes the Sekmeer interesting is the <b>gradient</b> visible over a short distance: from open water through a floating bog-moss fringe and wet cross-leaved heath to dry ling heath on the sand crests, and from there into the surrounding Scots pine wood. Such complete transitions have become rare \u2014 in most places one link in the sequence has been lost to drainage or nutrient enrichment. The pool is <b>nutrient-poor and weakly acid</b>, with cotton grass, beaked sedge and locally marsh St John\u2019s-wort on the shores. For amphibians and dragonflies it is an important breeding site: <b>moor frog, smooth newt, black darter and white-faced darter</b>. Management focuses on keeping the shore zone open and preventing encroachment by trees.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b>; Apr (moor frogs), Jun\u2013Aug (dragonflies), Aug (heather bloom)<br>\n    <b>Best time of day:</b> Warm midday for dragonflies; early morning for mirror-still water.',
 why=['Probably a <b>pingo scar</b> on the Hondsrug.',
      'A complete <b>gradient</b> from open water to dry heath and woodland.',
      'A nutrient-poor pool with <b>cotton grass and marsh St John\u2019s-wort</b>.',
      'An important breeding site for <b>moor frog and dragonflies</b>.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f438 <b>Moor frogs</b> call and turn blue.',
       '<span class="months">May\u2013Jun</span> \U0001f33f <b>Cotton grass</b> on the wet shore zone.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Darters</b> patrol above the pool.',
       '<span class="months">Aug</span> \U0001f7e3 <b>Cross-leaved and ling heath</b> flower around the water.'],
 wild=['\U0001f438 Moor frog', '\U0001f98b Black darter', '\U0001f98b White-faced darter', '\U0001f98e Viviparous lizard', '\U0001f33f Cotton grass \u00b7 Beaked sedge \u00b7 Marsh St John\u2019s-wort'],
 trail=['Park at <b>Gasselte</b> or Drouwen; woodland paths lead to the pool.',
        '<b>Do not enter the shore zone</b> \u2014 pioneer flora is highly sensitive to trampling.',
        'Managed by <b>Staatsbosbeheer</b>.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Fragile pool shore \u2014 keep to the path'),
 card_class='card water'))

insert(C, after_id=1195)
progress(1205)
check()
