# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mk import card, insert, check, progress

C = []

C.append(card(1226, 'Dal van de Ruiten Aa', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Beekdal \u00b7 esdorpen, bos en hooilanden', 'list 34 \u00b7 no. 3'],
 loc='\U0001f4cd Tussen Ter Apel, Sellingen en Wedde \u00b7 Beekdal met bossen en essen \u00b7 Zeer groot gebied',
 desc='Het <b>dal van de Ruiten Aa</b> is het mooiste beekdal van Groningen en misschien wel het best bewaarde geheim van Noord-Nederland. De <b>Ruiten Aa</b> ontspringt bij de Duitse grens en slingert noordwaarts door <b>Westerwolde</b>, een streek die eeuwenlang zo ingesloten lag tussen ondoordringbare hoogvenen dat hij bestuurlijk noch cultureel bij Groningen h\u00f3\u00f3rde \u2014 men sprak er een eigen dialect en keek naar Duitsland. Die isolatie bewaarde het landschap. Anders dan in het Oldambt bestaat Westerwolde uit <b>zandgrond</b>, en dus vind je hier wat je in de rest van Groningen niet vindt: <b>essen, houtwallen, eikenstrubben en beekdalhooilanden</b>. Sinds de jaren negentig is de beek over kilometers <b>hermeanderd</b> en zijn landbouwpercelen omgevormd tot natte natuur. Het resultaat is een <b>aaneengesloten natuurlint</b> van tientallen kilometers, met <b>otter, bever, ijsvogel</b> en in de hooilanden orchidee\u00ebn.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (voorjaarsflora, zang), mei\u2013jun (orchidee\u00ebn, beekjuffers), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 otter en bever bij de meanders, mist boven de hooilanden.',
 why=['Het <b>gaafste beekdal van Groningen</b>, over tientallen kilometers hersteld.',
      '<b>Zandlandschap in Groningen</b>: essen, houtwallen en strubben.',
      'Kilometers <b>hermeandering</b> met nieuwe natte natuur.',
      '<b>Otter, bever en ijsvogel</b> in een aaneengesloten natuurlint.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Dotterbloem en pinksterbloem</b> in de beekdalhooilanden.',
       '<span class="months">Mei\u2013Jul</span> \U0001f98b <b>Weidebeekjuffer</b> in metaalblauwe zwermen boven het water.',
       '<span class="months">Mei\u2013Jun</span> \U0001f33a <b>Orchidee\u00ebn</b> in de schrale hooilanden.',
       '<span class="months">Nov\u2013Feb</span> \U0001f30a <b>Winterhoogwater</b> zet delen van het dal blank.'],
 wild=['\U0001f9a6 Otter', '\U0001f9ab Bever', '\U0001f426 IJsvogel', '\U0001f98b Weidebeekjuffer', '\U0001f33a Dotterbloem \u00b7 Brede orchis \u00b7 Zomereik'],
 trail=['Parkeren bij <b>Sellingen</b>, Ter Apel of Wedde; het Ruiten Aa-pad volgt het dal.',
        'Zeer uitgestrekt \u2014 kies vooraf een <b>deeltraject</b> van enkele kilometers.',
        'Beheer: <b>Staatsbosbeheer</b> en Het Groninger Landschap.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f97e Natte paden bij hoogwater'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Brook valley \u00b7 esdorpen, woods and hay meadows', 'list 34 \u00b7 no. 3'],
 loc='\U0001f4cd Between Ter Apel, Sellingen and Wedde \u00b7 Brook valley with woods and fields \u00b7 Very large area',
 desc='The <b>valley of the Ruiten Aa</b> is the finest brook valley in Groningen and perhaps the best-kept secret in the northern Netherlands. The <b>Ruiten Aa</b> rises near the German border and winds north through <b>Westerwolde</b>, a district so hemmed in by impenetrable raised bogs for centuries that it belonged to Groningen neither administratively nor culturally \u2014 people spoke their own dialect and looked towards Germany. That isolation preserved the landscape. Unlike the Oldambt, Westerwolde consists of <b>sandy soil</b>, so here you find what the rest of Groningen lacks: <b>open arable fields, hedgebanks, oak strubben and brook-valley hay meadows</b>. Since the 1990s the brook has been <b>remeandered</b> over kilometres and farmland converted to wetland. The result is a <b>continuous ribbon of nature</b> tens of kilometres long, with <b>otter, beaver, kingfisher</b> and orchids in the hay meadows.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (spring flora, song), May\u2013Jun (orchids, demoiselles), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Early morning \u2014 otter and beaver at the meanders, mist over the meadows.',
 why=['The <b>most intact brook valley in Groningen</b>, restored over tens of kilometres.',
      'A <b>sandy landscape within Groningen</b>: open fields, hedgebanks and strubben.',
      'Kilometres of <b>remeandering</b> with new wetland.',
      '<b>Otter, beaver and kingfisher</b> in a continuous nature ribbon.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f338 <b>Marsh marigold and cuckooflower</b> in the valley meadows.',
       '<span class="months">May\u2013Jul</span> \U0001f98b <b>Banded demoiselle</b> in metallic-blue swarms above the water.',
       '<span class="months">May\u2013Jun</span> \U0001f33a <b>Orchids</b> in the poor hay meadows.',
       '<span class="months">Nov\u2013Feb</span> \U0001f30a <b>Winter high water</b> floods parts of the valley.'],
 wild=['\U0001f9a6 Otter', '\U0001f9ab Beaver', '\U0001f426 Kingfisher', '\U0001f98b Banded demoiselle', '\U0001f33a Marsh marigold \u00b7 Early marsh orchid \u00b7 Pedunculate oak'],
 trail=['Park at <b>Sellingen</b>, Ter Apel or Wedde; the Ruiten Aa path follows the valley.',
        'Very extensive \u2014 choose a <b>section</b> of a few kilometres in advance.',
        'Managed by <b>Staatsbosbeheer</b> and Het Groninger Landschap.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f97e Wet paths at high water'),
 card_class='card water'))

C.append(card(1227, 'De Schans Bourtange', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Vestingwerk &amp; veenmoeras \u00b7 historisch landschap', 'list 34 \u00b7 no. 4'],
 loc='\U0001f4cd Bourtange, aan de Duitse grens bij Vlagtwedde \u00b7 Vestingdorp met omringend landschap \u00b7 Middelgroot',
 desc='<b>Bourtange</b> is de best gereconstrueerde <b>vesting</b> van Nederland en tegelijk een les in militaire aardrijkskunde. De schans werd in <b>1593</b> op bevel van Willem van Oranje aangelegd op precies de enige plek waar dat mogelijk was: een smalle <b>zandrug</b> \u2014 een <i>tange</i> \u2014 door het onbegaanbare <b>Bourtanger Moor</b>, het reusachtige hoogveen dat zich van Groningen diep in Duitsland uitstrekte. Wie van Duitsland naar Groningen wilde, m\u00f3\u00e9st hier langs; alle andere routes verdronken in het veen. Door die ene doorgang af te sluiten controleerde men een hele grens. Het veen zelf is grotendeels verdwenen \u2014 afgegraven voor turf \u2014 maar rond de vesting is een deel van het <b>moerasmilieu gereconstrueerd</b>, met natte graslanden en rietkragen in de grachten en buitenwerken. Die vestinggrachten zijn ecologisch verrassend rijk: <b>waterral, blauwborst, kleine karekiet</b> in het riet, libellen boven het water en vleermuizen die \u2019s avonds langs de wallen jagen.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013jun (rietvogels), jun\u2013aug (libellen en vleermuizen), okt\u2013nov (mist over de grachten)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 vesting zonder bezoekers, mist boven de grachten.',
 why=['Best gereconstrueerde <b>vesting van Nederland</b>, aangelegd in 1593.',
      'Gebouwd op de enige <b>zandrug</b> door het onbegaanbare Bourtanger Moor.',
      'Deels <b>gereconstrueerd moerasmilieu</b> rond de buitenwerken.',
      'Rietrijke <b>vestinggrachten</b> met waterral en blauwborst.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f426 <b>Blauwborst</b> zingt vanaf de rietkragen in de grachten.',
       '<span class="months">Mei\u2013Jun</span> \U0001f426 <b>Waterral</b> gilt in het riet van de buitenwerken.',
       '<span class="months">Jun\u2013Aug</span> \U0001f987 <b>Vleermuizen</b> jagen \u2019s avonds langs de wallen.',
       '<span class="months">Okt\u2013Nov</span> \U0001f32b\ufe0f <b>Mist</b> over de grachten \u2014 de vesting op haar meest sfeervol.'],
 wild=['\U0001f426 Blauwborst', '\U0001f426 Waterral', '\U0001f987 Watervleermuis', '\U0001f98b Glazenmakers', '\U0001f33f Riet \u00b7 Gele lis \u00b7 Zwarte els'],
 trail=['Parkeren buiten de vesting bij <b>Bourtange</b>; het dorp is autovrij.',
        'De <b>wallen en grachten</b> zijn vrij toegankelijk; museum en gebouwen betaald.',
        'Combineer met het <b>dal van de Ruiten Aa</b> even westelijk.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Vestingterrein gratis, museum betaald \u00b7 \U0001f3f0 Rijksmonument'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Fortress &amp; bog marsh \u00b7 historic landscape', 'list 34 \u00b7 no. 4'],
 loc='\U0001f4cd Bourtange, on the German border near Vlagtwedde \u00b7 Fortress village with surroundings \u00b7 Medium-sized',
 desc='<b>Bourtange</b> is the best-reconstructed <b>fortress</b> in the Netherlands and at the same time a lesson in military geography. The redoubt was built in <b>1593</b> on the orders of William of Orange at precisely the only place where it was possible: a narrow <b>sand ridge</b> \u2014 a <i>tange</i> \u2014 through the impassable <b>Bourtanger Moor</b>, the enormous raised bog stretching from Groningen deep into Germany. Anyone travelling from Germany to Groningen <i>had</i> to pass here; every other route drowned in the bog. By closing that single gap you controlled an entire frontier. The bog itself has largely gone \u2014 dug away for peat \u2014 but around the fortress part of the <b>marsh environment has been reconstructed</b>, with wet grasslands and reed fringes in the moats and outworks. Those moats are ecologically surprisingly rich: <b>water rail, bluethroat, reed warbler</b> in the reed, dragonflies above the water and bats hunting along the ramparts at dusk.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013Jun (reed birds), Jun\u2013Aug (dragonflies and bats), Oct\u2013Nov (mist over the moats)<br>\n    <b>Best time of day:</b> Early morning \u2014 the fortress without visitors, mist above the moats.',
 why=['The best-reconstructed <b>fortress in the Netherlands</b>, built in 1593.',
      'Sited on the only <b>sand ridge</b> through the impassable Bourtanger Moor.',
      'Partly <b>reconstructed marsh environment</b> around the outworks.',
      'Reed-rich <b>fortress moats</b> with water rail and bluethroat.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f426 <b>Bluethroat</b> sings from the reed fringes in the moats.',
       '<span class="months">May\u2013Jun</span> \U0001f426 <b>Water rail</b> squeals in the reed of the outworks.',
       '<span class="months">Jun\u2013Aug</span> \U0001f987 <b>Bats</b> hunt along the ramparts at dusk.',
       '<span class="months">Oct\u2013Nov</span> \U0001f32b\ufe0f <b>Mist</b> over the moats \u2014 the fortress at its most atmospheric.'],
 wild=['\U0001f426 Bluethroat', '\U0001f426 Water rail', '\U0001f987 Daubenton\u2019s bat', '\U0001f98b Hawker dragonflies', '\U0001f33f Reed \u00b7 Yellow iris \u00b7 Black alder'],
 trail=['Park outside the fortress at <b>Bourtange</b>; the village is car-free.',
        'The <b>ramparts and moats</b> are freely accessible; museum and buildings charge.',
        'Combine with the <b>Ruiten Aa valley</b> just to the west.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Fortress grounds free, museum charges \u00b7 \U0001f3f0 National monument'),
 card_class='card estate'))

C.append(card(1228, 'Hoetmansmeer', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Natte natuurontwikkeling \u00b7 moeras en plassen', 'list 34 \u00b7 no. 5'],
 loc='\U0001f4cd Bij Vlagtwedde en Onstwedde \u00b7 Moerasgebied \u00b7 Middelgroot',
 desc='Het <b>Hoetmansmeer</b> bij Vlagtwedde is een van de nieuwe natuurgebieden die in Westerwolde zijn ontstaan uit het <b>waterbergingsprogramma</b> van de afgelopen decennia. Na de wateroverlast van 1998, toen grote delen van Groningen onderliepen, werd besloten dat het watersysteem meer ruimte nodig had: in plaats van alles zo snel mogelijk af te voeren, moest water bij piekbuien ergens <b>vastgehouden</b> kunnen worden. Het Hoetmansmeer is zo\u2019n bergingsgebied, en het is meteen als natuur ingericht \u2014 <b>ondiepe plassen, rietmoeras, natte graslanden en slikoevers</b>. Zulke jonge moerassen zijn ecologisch explosief: binnen enkele jaren vestigden zich <b>roerdomp, blauwborst, bruine kiekendief en baardman</b>, en tijdens de trek doen steltlopers de slikranden aan. In de winter functioneert het gebied als <b>rust- en foerageergebied voor ganzen en eenden</b>. Het toont hoe waterveiligheid en natuurherstel in Nederland steeds vaker dezelfde ingreep zijn geworden.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013jun (moerasvogels), aug\u2013okt (steltlopertrek), nov\u2013mrt (ganzen en eenden)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend en avond \u2014 roerdomp, kiekendief en ganzenvluchten.',
 why=['<b>Waterbergingsgebied</b> dat meteen als natuur is ingericht.',
      'Jong moeras met <b>explosieve kolonisatie</b> door rietvogels.',
      '<b>Roerdomp, bruine kiekendief en baardman</b> binnen enkele jaren gevestigd.',
      'Slikoevers als <b>steltloperstop</b> tijdens de najaarstrek.'],
 phen=['<span class="months">Mrt\u2013Mei</span> \U0001f426 <b>Roerdomp</b> hoempt; bruine kiekendief baltst boven het riet.',
       '<span class="months">Mei\u2013Jul</span> \U0001f426 <b>Baardmannetjes</b> in het jonge riet.',
       '<span class="months">Aug\u2013Okt</span> \U0001f426 <b>Steltlopers</b> op de slikranden tijdens de trek.',
       '<span class="months">Nov\u2013Mrt</span> \U0001f9a2 <b>Ganzen en eenden</b> gebruiken het gebied als rustplaats.'],
 wild=['\U0001f426 Roerdomp', '\U0001f985 Bruine kiekendief', '\U0001f426 Baardman', '\U0001f426 Blauwborst', '\U0001f33f Riet \u00b7 Lisdodde \u00b7 Zwanenbloem'],
 trail=['Parkeren bij <b>Vlagtwedde</b> of Onstwedde; kijkpunten langs de randen.',
        'Blijf op de paden en kijkpunten \u2014 <b>verstoring</b> raakt broedende moerasvogels hard.',
        'Beheer: <b>Staatsbosbeheer</b> en waterschap Hunze en Aa\u2019s.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f97e Natte paden \u00b7 \u26a0\ufe0f Waterbergingsgebied \u2014 kan onderlopen'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Wetland creation \u00b7 marsh and pools', 'list 34 \u00b7 no. 5'],
 loc='\U0001f4cd Near Vlagtwedde and Onstwedde \u00b7 Marshland \u00b7 Medium-sized',
 desc='The <b>Hoetmansmeer</b> near Vlagtwedde is one of the new nature areas that emerged in Westerwolde from the <b>water-storage programme</b> of recent decades. After the flooding of 1998, when large parts of Groningen went under, it was decided that the water system needed more room: instead of discharging everything as fast as possible, water had to be <b>held back</b> somewhere during peak rainfall. The Hoetmansmeer is such a storage area, and it was laid out as nature from the start \u2014 <b>shallow pools, reed marsh, wet grassland and muddy shores</b>. Young marshes like this are ecologically explosive: within a few years <b>bittern, bluethroat, marsh harrier and bearded reedling</b> settled, and on migration waders call at the muddy margins. In winter the area functions as a <b>roosting and feeding ground for geese and ducks</b>. It shows how water safety and nature restoration in the Netherlands have increasingly become the same intervention.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013Jun (marsh birds), Aug\u2013Oct (wader passage), Nov\u2013Mar (geese and ducks)<br>\n    <b>Best time of day:</b> Early morning and evening \u2014 bittern, harrier and goose flights.',
 why=['A <b>water-storage area</b> laid out as nature from the outset.',
      'Young marsh with <b>explosive colonisation</b> by reed birds.',
      '<b>Bittern, marsh harrier and bearded reedling</b> established within a few years.',
      'Muddy shores as a <b>wader stopover</b> during autumn passage.'],
 phen=['<span class="months">Mar\u2013May</span> \U0001f426 <b>Bittern</b> booms; marsh harrier displays above the reed.',
       '<span class="months">May\u2013Jul</span> \U0001f426 <b>Bearded reedlings</b> in the young reed.',
       '<span class="months">Aug\u2013Oct</span> \U0001f426 <b>Waders</b> on the muddy margins during passage.',
       '<span class="months">Nov\u2013Mar</span> \U0001f9a2 <b>Geese and ducks</b> use the area as a roost.'],
 wild=['\U0001f426 Eurasian bittern', '\U0001f985 Marsh harrier', '\U0001f426 Bearded reedling', '\U0001f426 Bluethroat', '\U0001f33f Reed \u00b7 Bulrush \u00b7 Flowering rush'],
 trail=['Park at <b>Vlagtwedde</b> or Onstwedde; viewpoints along the margins.',
        'Keep to paths and viewpoints \u2014 <b>disturbance</b> hits breeding marsh birds hard.',
        'Managed by <b>Staatsbosbeheer</b> and the Hunze en Aa\u2019s water board.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f97e Wet paths \u00b7 \u26a0\ufe0f Water-storage area \u2014 may flood'),
 card_class='card water'))

C.append(card(1229, 'Onstwedde', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Esdorp op zandrug \u00b7 essen en houtwallen', 'list 34 \u00b7 no. 6'],
 loc='\U0001f4cd Onstwedde, ten noorden van Stadskanaal \u00b7 Esdorp met omringend landschap \u00b7 Groot gebied',
 desc='<b>Onstwedde</b> is een van de oudste nederzettingen van Westerwolde en het duidelijkste bewijs dat deze streek landschappelijk bij Drenthe hoort en niet bij het Groninger kleigebied. Het dorp ligt op een <b>zandrug</b> boven het omringende veen- en beekdallandschap, en heeft de complete <b>esdorpstructuur</b> bewaard: een kerk op het hoogste punt \u2014 de romano-gotische <b>Sint-Nicolaaskerk</b> uit de dertiende eeuw \u2014 daaromheen de boerderijen, en aaneengesloten daarachter de <b>bolle essen</b>, opgehoogd door eeuwen plaggenbemesting. Tussen de essen en de lagere gronden ligt een dicht net van <b>houtwallen, singels en holle wegen</b>. Het bijzondere is de <b>schaal</b>: het essencomplex van Onstwedde behoort tot de grootste van Noord-Nederland, en omdat het nooit is geruilverkaveld op de manier die elders alles rechttrok, is de onregelmatige, historisch gegroeide perceelsvorm nog leesbaar. Ecologisch draagt het houtwallennetwerk <b>das, steenuil, geelgors</b> en een rijke insectenfauna.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (houtwalbloei), mei\u2013jun (zang), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Avondschemer \u2014 das en steenuil langs de wallen; ochtend voor zang.',
 why=['Een van de <b>oudste nederzettingen</b> van Westerwolde.',
      'Compleet <b>esdorp</b> met kerk uit de dertiende eeuw op het hoogste punt.',
      'Een van de <b>grootste essencomplexen</b> van Noord-Nederland.',
      'Dicht netwerk van <b>houtwallen en holle wegen</b>.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Meidoorn en sleedoorn</b> bloeien wit in de houtwallen.',
       '<span class="months">Mei\u2013Jun</span> \U0001f426 <b>Geelgors</b> zingt vanaf de wallen; steenuil roept in de schemer.',
       '<span class="months">Jul\u2013Aug</span> \U0001f33e <b>Graanoogst</b> op de bolle essen.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Houtwallen</b> in herfstkleur; paddenstoelen op de wallen.'],
 wild=['\U0001f9a1 Das', '\U0001f989 Steenuil', '\U0001f426 Geelgors', '\U0001f98c Ree', '\U0001f333 Zomereik \u00b7 Meidoorn \u00b7 Hulst'],
 trail=['Parkeren in <b>Onstwedde</b> bij de kerk; ommetjes leiden over de essen.',
        'De <b>Sint-Nicolaaskerk</b> is vaak overdag te bezichtigen.',
        'De essen zijn <b>particulier akkerland</b>: blijf op de paden en holle wegen.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Deels particulier akkerland'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Esdorp on a sand ridge \u00b7 open fields and hedgebanks', 'list 34 \u00b7 no. 6'],
 loc='\U0001f4cd Onstwedde, north of Stadskanaal \u00b7 Esdorp with surrounding landscape \u00b7 Large area',
 desc='<b>Onstwedde</b> is one of the oldest settlements in Westerwolde and the clearest proof that this district belongs, in landscape terms, with Drenthe rather than with the Groningen clay country. The village sits on a <b>sand ridge</b> above the surrounding peat and brook-valley land, and has kept the complete <b>esdorp structure</b>: a church on the highest point \u2014 the Romano-Gothic <b>St Nicholas church</b> of the thirteenth century \u2014 the farms around it, and directly beyond them the <b>domed arable fields</b>, raised by centuries of sod manuring. Between the fields and the lower ground lies a dense net of <b>hedgebanks, shelterbelts and sunken lanes</b>. What is remarkable is the <b>scale</b>: the field complex of Onstwedde is among the largest in the northern Netherlands, and because it was never subjected to the land consolidation that straightened everything elsewhere, the irregular, historically grown plot shapes are still legible. Ecologically the hedgebank network supports <b>badger, little owl, yellowhammer</b> and a rich insect fauna.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (hedgebank blossom), May\u2013Jun (song), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Dusk \u2014 badger and little owl along the banks; morning for song.',
 why=['One of the <b>oldest settlements</b> in Westerwolde.',
      'A complete <b>esdorp</b> with a thirteenth-century church on the highest point.',
      'One of the <b>largest field complexes</b> in the northern Netherlands.',
      'A dense network of <b>hedgebanks and sunken lanes</b>.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f338 <b>Hawthorn and blackthorn</b> flower white in the hedgebanks.',
       '<span class="months">May\u2013Jun</span> \U0001f426 <b>Yellowhammer</b> sings from the banks; little owl calls at dusk.',
       '<span class="months">Jul\u2013Aug</span> \U0001f33e <b>Grain harvest</b> on the domed fields.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Hedgebanks</b> in autumn colour; fungi on the banks.'],
 wild=['\U0001f9a1 Badger', '\U0001f989 Little owl', '\U0001f426 Yellowhammer', '\U0001f98c Roe deer', '\U0001f333 Pedunculate oak \u00b7 Hawthorn \u00b7 Holly'],
 trail=['Park in <b>Onstwedde</b> by the church; short loops lead across the fields.',
        'The <b>St Nicholas church</b> is often open to visitors during the day.',
        'The fields are <b>private farmland</b>: keep to the paths and sunken lanes.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Partly private farmland'),
 card_class='card estate'))

C.append(card(1230, 'Pagebos', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Bos &amp; landgoedelementen \u00b7 Ter Apel', 'list 34 \u00b7 no. 7'],
 loc='\U0001f4cd Bij Ter Apel \u00b7 Loof- en gemengd bos \u00b7 Middelgroot',
 desc='Het <b>Pagebos</b> bij Ter Apel behoort tot de bossen rond het beroemde <b>klooster van Ter Apel</b>, het enige goed bewaarde middeleeuwse plattelandsklooster van Nederland. De kruisheren die zich hier in <b>1465</b> vestigden kozen de plek bewust: op de zandrug aan de rand van het onbegaanbare Bourtanger Moor, ver van de wereld en toch aan de handelsroute. Rond het klooster ontwikkelde zich in de loop van eeuwen een <b>bos- en landgoedlandschap</b> met lanen, hakhoutpercelen en singels, en het Pagebos is daar een onderdeel van. Het bestaat uit <b>oud loofbos met zomereik en beuk</b>, delen naaldhout, en in de laagten elzenbroek. Wat het bijzonder maakt is de <b>continu\u00efteit</b>: op deze plek staat al eeuwen bos, en dat is te merken aan de bodemflora en de mossen \u2014 soorten die zich slecht verspreiden en alleen in oude bossen voorkomen. Er broeden <b>bosuil, glanskop, boomklever</b> en spechten in het dode hout.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013nov</b>; apr\u2013mei (voorjaarsflora en zang), sep\u2013nov (paddenstoelen), okt\u2013nov (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 bosuil roept nog, spechten worden actief.',
 why=['Bos bij het <b>klooster van Ter Apel</b>, het best bewaarde plattelandsklooster van Nederland.',
      '<b>Bosconinu\u00efteit</b> over eeuwen \u2014 zichtbaar in bodemflora en mossen.',
      'Oud <b>loofbos</b> met zomereik en beuk, elzenbroek in de laagten.',
      '<b>Bosuil, glanskop en spechten</b> in het dode hout.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f33c <b>Bosanemoon en speenkruid</b> op de bosbodem.',
       '<span class="months">Apr\u2013Mei</span> \U0001f426 <b>Glanskop en boomklever</b> zingen in het kronendak.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Paddenstoelen</b> \u2014 oude bossen leveren bijzondere soorten.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Herfstkleur</b> in eik en beuk.'],
 wild=['\U0001f989 Bosuil', '\U0001f426 Glanskop', '\U0001fab5 Grote bonte specht', '\U0001f43f\ufe0f Eekhoorn', '\U0001f333 Zomereik \u00b7 Beuk \u00b7 Zwarte els'],
 trail=['Parkeren bij het <b>klooster van Ter Apel</b>; paden leiden het bos in.',
        'Combineer met de <b>kloostertuinen</b> en het dal van de Ruiten Aa.',
        'Beheer: <b>Staatsbosbeheer</b> en de kloosterstichting.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis (klooster betaald) \u00b7 \u26e9\ufe0f Klooster Ter Apel nabij'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Woodland &amp; estate elements \u00b7 Ter Apel', 'list 34 \u00b7 no. 7'],
 loc='\U0001f4cd Near Ter Apel \u00b7 Broadleaf and mixed woodland \u00b7 Medium-sized',
 desc='The <b>Pagebos</b> near Ter Apel belongs to the woods around the famous <b>monastery of Ter Apel</b>, the only well-preserved medieval rural monastery in the Netherlands. The Crosier friars who settled here in <b>1465</b> chose the spot deliberately: on the sand ridge at the edge of the impassable Bourtanger Moor, far from the world yet on the trade route. Over the centuries a <b>woodland and estate landscape</b> of avenues, coppice parcels and shelterbelts developed around the monastery, and the Pagebos is part of it. It consists of <b>old broadleaf woodland with pedunculate oak and beech</b>, some conifer stands, and alder carr in the hollows. What makes it special is the <b>continuity</b>: woodland has stood on this spot for centuries, and it shows in the ground flora and the mosses \u2014 species that disperse poorly and occur only in ancient woods. <b>Tawny owl, marsh tit, nuthatch</b> and woodpeckers breed in the dead wood.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Nov</b>; Apr\u2013May (spring flora and song), Sep\u2013Nov (fungi), Oct\u2013Nov (autumn colour)<br>\n    <b>Best time of day:</b> Early morning \u2014 tawny owl still calling, woodpeckers becoming active.',
 why=['Woodland by the <b>monastery of Ter Apel</b>, the best-preserved rural monastery in the country.',
      '<b>Woodland continuity</b> over centuries \u2014 visible in ground flora and mosses.',
      'Old <b>broadleaf wood</b> with oak and beech, alder carr in the hollows.',
      '<b>Tawny owl, marsh tit and woodpeckers</b> in the dead wood.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f33c <b>Wood anemone and celandine</b> on the woodland floor.',
       '<span class="months">Apr\u2013May</span> \U0001f426 <b>Marsh tit and nuthatch</b> sing in the canopy.',
       '<span class="months">Sep\u2013Nov</span> \U0001f344 <b>Fungi</b> \u2014 ancient woods yield unusual species.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Autumn colour</b> in oak and beech.'],
 wild=['\U0001f989 Tawny owl', '\U0001f426 Marsh tit', '\U0001fab5 Great spotted woodpecker', '\U0001f43f\ufe0f Red squirrel', '\U0001f333 Pedunculate oak \u00b7 Beech \u00b7 Black alder'],
 trail=['Park at the <b>monastery of Ter Apel</b>; paths lead into the wood.',
        'Combine with the <b>monastery gardens</b> and the Ruiten Aa valley.',
        'Managed by <b>Staatsbosbeheer</b> and the monastery foundation.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free (monastery charges) \u00b7 \u26e9\ufe0f Ter Apel monastery nearby')))

C.append(card(1231, 'De Broeklanden', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Natte graslanden &amp; moeras \u00b7 beekdalherstel', 'list 34 \u00b7 no. 8'],
 loc='\U0001f4cd Bij Sellingen en Ter Apel, langs de Ruiten Aa \u00b7 Natte graslanden \u00b7 Middelgroot',
 desc='<b>De Broeklanden</b> zijn de natte laagten langs de Ruiten Aa, en het woord <i>broek</i> zegt precies wat ze zijn: moerassig laagland, te nat om te ploegen. In het oude landbouwsysteem waren dat geen waardeloze gronden maar juist onmisbare: hier werd het <b>hooi</b> gewonnen waarmee het vee de winter doorkwam, en de <b>elzenbroekbosjes</b> leverden geriefhout. Pas in de twintigste eeuw, toen bemaling en kunstmest alles mogelijk maakten, zijn de broeklanden ontwaterd en omgezet in productiegrasland \u2014 waarna ze hun natuurwaarde en hun karakter verloren. Het herstel van de laatste decennia draait die ingreep terug: <b>drainage is verwijderd, de waterstand verhoogd en de bemesting gestopt</b>. Het gevolg is dat het <b>kwelwater</b> vanuit de zandruggen weer aan de oppervlakte komt en de bijbehorende flora terugkeert: <b>dotterbloem, echte koekoeksbloem, waterdrieblad</b> en op de schraalste plekken orchidee\u00ebn. In de natte graslanden broeden <b>watersnip, kievit en grutto</b>.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>mrt\u2013okt</b>; mrt\u2013mei (weidevogels), apr\u2013jun (bloei), nov\u2013feb (watervogels en hoogwater)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 weidevogels roepen, mist boven de natte percelen.',
 why=['Herstelde <b>broeklanden</b>: natte hooilanden langs de Ruiten Aa.',
      'Teruggekeerde <b>kwelstroom</b> na vernatting en stoppen met bemesten.',
      '<b>Dotterbloem, koekoeksbloem en orchidee\u00ebn</b> op de schraalste delen.',
      'Broedgebied voor <b>watersnip, kievit en grutto</b>.'],
 phen=['<span class="months">Mrt\u2013Mei</span> \U0001f426 <b>Weidevogels</b> baltsen boven de natte percelen.',
       '<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Dotterbloem</b> kleurt de laagten goudgeel.',
       '<span class="months">Mei\u2013Jun</span> \U0001f33a <b>Koekoeksbloem en orchidee\u00ebn</b> in de schrale hooilanden.',
       '<span class="months">Nov\u2013Feb</span> \U0001f30a <b>Hoogwater</b> \u2014 de broeklanden lopen onder zoals vanouds.'],
 wild=['\U0001f426 Watersnip', '\U0001f426 Grutto', '\U0001f9a6 Otter', '\U0001f426 Blauwborst', '\U0001f33a Dotterbloem \u00b7 Echte koekoeksbloem \u00b7 Waterdrieblad'],
 trail=['Parkeren bij <b>Sellingen</b> of Ter Apel; paden volgen de Ruiten Aa.',
        'In het <b>broedseizoen (mrt\u2013jun)</b> extra rust houden voor de weidevogels.',
        'Beheer: <b>Staatsbosbeheer</b>. Laarzen aanbevolen.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f97e Natte paden \u00b7 \u26a0\ufe0f Broedseizoen: houd afstand'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Wet grassland &amp; marsh \u00b7 valley restoration', 'list 34 \u00b7 no. 8'],
 loc='\U0001f4cd Near Sellingen and Ter Apel, along the Ruiten Aa \u00b7 Wet grassland \u00b7 Medium-sized',
 desc='<b>De Broeklanden</b> are the wet hollows along the Ruiten Aa, and the word <i>broek</i> says exactly what they are: marshy lowland, too wet to plough. In the old farming system these were not worthless grounds but indispensable ones: here the <b>hay</b> was cut that carried the livestock through winter, and the <b>alder carr copses</b> supplied utility timber. Only in the twentieth century, when pumping and fertiliser made everything possible, were the broeklanden drained and turned into production grassland \u2014 after which they lost both their natural value and their character. The restoration of recent decades reverses that: <b>drainage removed, the water table raised and fertilising stopped</b>. As a result the <b>seepage water</b> from the sand ridges reaches the surface again and the associated flora returns: <b>marsh marigold, ragged robin, bogbean</b> and, on the poorest patches, orchids. In the wet grasslands <b>snipe, lapwing and black-tailed godwit</b> breed.',
 meta='<b>Best season &amp; peak months:</b> <b>Mar\u2013Oct</b>; Mar\u2013May (meadow birds), Apr\u2013Jun (flowering), Nov\u2013Feb (waterfowl and high water)<br>\n    <b>Best time of day:</b> Early morning \u2014 meadow birds calling, mist over the wet parcels.',
 why=['Restored <b>broeklanden</b>: wet hay meadows along the Ruiten Aa.',
      'Returned <b>seepage flow</b> after rewetting and ending fertilisation.',
      '<b>Marsh marigold, ragged robin and orchids</b> on the poorest parts.',
      'Breeding ground for <b>snipe, lapwing and godwit</b>.'],
 phen=['<span class="months">Mar\u2013May</span> \U0001f426 <b>Meadow birds</b> display above the wet parcels.',
       '<span class="months">Apr\u2013May</span> \U0001f338 <b>Marsh marigold</b> turns the hollows golden.',
       '<span class="months">May\u2013Jun</span> \U0001f33a <b>Ragged robin and orchids</b> in the poor hay meadows.',
       '<span class="months">Nov\u2013Feb</span> \U0001f30a <b>High water</b> \u2014 the broeklanden flood as they always did.'],
 wild=['\U0001f426 Common snipe', '\U0001f426 Black-tailed godwit', '\U0001f9a6 Otter', '\U0001f426 Bluethroat', '\U0001f33a Marsh marigold \u00b7 Ragged robin \u00b7 Bogbean'],
 trail=['Park at <b>Sellingen</b> or Ter Apel; paths follow the Ruiten Aa.',
        'In the <b>breeding season (Mar\u2013Jun)</b> keep extra quiet for the meadow birds.',
        'Managed by <b>Staatsbosbeheer</b>. Boots recommended.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f97e Wet paths \u00b7 \u26a0\ufe0f Breeding season: keep your distance'),
 card_class='card water'))

C.append(card(1232, 'Drouwenerzand', dict(
 tags=['Drenthe \u00b7 Borger-Odoorn', 'Stuifzand &amp; heide \u00b7 landduinen op de Hondsrug', 'list 34 \u00b7 no. 9'],
 loc='\U0001f4cd Bij Drouwen, tussen Borger en Gasselte \u00b7 Stuifzandgebied \u00b7 Ca. 100 ha',
 desc='Het <b>Drouwenerzand</b> is een van de weinige plekken op de Hondsrug waar het <b>stuifzand</b> nog echt stuift. Het complex ontstond zoals alle Nederlandse landduinen: middeleeuwse overbeweiding en plaggensteken sloopten het vegetatiedek van de heide, waarna de wind vrij spel kreeg in het dekzand. Op de Hondsrug, met zijn droge en schrale bodem, was dat proces bijzonder heftig. Anders dan elders is hier bewust gekozen om het zand <b>in beweging te houden</b>: door begroeiing te verwijderen en de wind ruimte te geven, blijft een habitat bestaan die in Europa vrijwel is verdwenen. Rond de open zandvlakten liggen <b>korstmosrijke duinen</b> met rendiermos, <b>struikheide</b> en verspreid jeneverbes en grove den. De fauna is die van warm, open zand: <b>zandhagedis, blauwvleugelsprinkhaan, zandloopkevers</b> en talrijke graafwespen en -bijen die hun nesten in het losse zand graven. In de schemer jaagt de <b>nachtzwaluw</b> over de open vlakte.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013sep</b>; apr\u2013mei (reptielen), jun\u2013jul (nachtzwaluw, graafbijen), jul\u2013aug (sprinkhanen en heide)<br>\n    <b>Beste tijd van de dag:</b> Warme middag voor insecten en reptielen; schemer in juni voor nachtzwaluw.',
 why=['<b>Actief stuifzand</b> \u2014 bewust in beweging gehouden.',
      'Korstmosrijke duinen met <b>rendiermos</b> rond de open vlakten.',
      '<b>Zandhagedis en blauwvleugelsprinkhaan</b> op het warme zand.',
      'Kolonies <b>graafbijen en -wespen</b> in het losse zand.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f98e <b>Zandhagedis</b> in groen bruidskleed op het open zand.',
       '<span class="months">Mei\u2013Jul</span> \U0001f41d <b>Graafbijen en -wespen</b> nestelen in de zandhellingen.',
       '<span class="months">Jun\u2013Jul</span> \U0001f989 <b>Nachtzwaluw</b> snort in de schemer boven de vlakte.',
       '<span class="months">Jul\u2013Aug</span> \U0001f997 <b>Blauwvleugelsprinkhaan</b> ratelt; heide begint te bloeien.'],
 wild=['\U0001f98e Zandhagedis', '\U0001f997 Blauwvleugelsprinkhaan', '\U0001f989 Nachtzwaluw', '\U0001f41d Graafbijen \u00b7 Graafwespen', '\U0001f33f Rendiermos \u00b7 Buntgras \u00b7 Struikhei'],
 trail=['Parkeren bij <b>Drouwen</b>; gemarkeerde routes over en langs het zand.',
        'Blijf op de paden: <b>korstmossen</b> herstellen zich na betreding pas na jaren.',
        'Beheer: <b>Het Drentse Landschap</b>.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Korstmossen zeer kwetsbaar \u00b7 \u2600\ufe0f Weinig schaduw'),
 dict(
 tags=['Drenthe \u00b7 Borger-Odoorn', 'Drift sand &amp; heath \u00b7 inland dunes on the Hondsrug', 'list 34 \u00b7 no. 9'],
 loc='\U0001f4cd Near Drouwen, between Borger and Gasselte \u00b7 Drift-sand area \u00b7 About 100 ha',
 desc='The <b>Drouwenerzand</b> is one of the few places on the Hondsrug where the <b>drift sand</b> still genuinely drifts. The complex arose as all Dutch inland dunes did: medieval overgrazing and sod cutting stripped the vegetation cover from the heath, after which the wind had free play in the cover sand. On the Hondsrug, with its dry and impoverished soil, that process was particularly fierce. Unlike elsewhere, the deliberate choice here has been to keep the sand <b>in motion</b>: by removing vegetation and giving the wind room, a habitat survives that has all but vanished from Europe. Around the open sand flats lie <b>lichen-rich dunes</b> with reindeer lichen, <b>ling heath</b> and scattered juniper and Scots pine. The fauna is that of warm, open sand: <b>sand lizard, blue-winged grasshopper, tiger beetles</b> and numerous digger wasps and mining bees that excavate their nests in the loose sand. At dusk the <b>nightjar</b> hunts across the open plain.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b>; Apr\u2013May (reptiles), Jun\u2013Jul (nightjar, mining bees), Jul\u2013Aug (grasshoppers and heather)<br>\n    <b>Best time of day:</b> Warm midday for insects and reptiles; dusk in June for nightjar.',
 why=['<b>Active drift sand</b> \u2014 deliberately kept in motion.',
      'Lichen-rich dunes with <b>reindeer lichen</b> around the open flats.',
      '<b>Sand lizard and blue-winged grasshopper</b> on the warm sand.',
      'Colonies of <b>mining bees and digger wasps</b> in the loose sand.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f98e <b>Sand lizard</b> in green breeding dress on the open sand.',
       '<span class="months">May\u2013Jul</span> \U0001f41d <b>Mining bees and digger wasps</b> nest in the sandy slopes.',
       '<span class="months">Jun\u2013Jul</span> \U0001f989 <b>Nightjar</b> churrs at dusk above the plain.',
       '<span class="months">Jul\u2013Aug</span> \U0001f997 <b>Blue-winged grasshopper</b> rattles; heather starts to flower.'],
 wild=['\U0001f98e Sand lizard', '\U0001f997 Blue-winged grasshopper', '\U0001f989 European nightjar', '\U0001f41d Mining bees \u00b7 Digger wasps', '\U0001f33f Reindeer lichen \u00b7 Grey hair-grass \u00b7 Ling'],
 trail=['Park at <b>Drouwen</b>; waymarked routes cross and skirt the sand.',
        'Keep to the paths: <b>lichens</b> take years to recover from trampling.',
        'Managed by <b>Het Drentse Landschap</b>.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Lichens very fragile \u00b7 \u2600\ufe0f Little shade'),
 card_class='card dune'))

C.append(card(1233, 'Vledderveen', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Veenontginningsdorp \u00b7 landschapselementen', 'list 34 \u00b7 no. 10'],
 loc='\U0001f4cd Vledderveen, tussen Onstwedde en Stadskanaal \u00b7 Ontginningsdorp met landschap \u00b7 Middelgroot',
 desc='<b>Vledderveen</b> is een <b>veenontginningsdorp</b> op de rand van Westerwolde, ontstaan in de negentiende eeuw toen de laatste venen tussen de zandruggen werden afgegraven. De naam is samengesteld uit <i>vledder</i> \u2014 een oud woord voor drassig, laaggelegen grasland \u2014 en <i>veen</i>, en beschrijft daarmee het landschap zoals het v\u00f3\u00f3r de ontginning was. Wat er nu ligt is het typische <b>rationele ontginningspatroon</b>: rechte wegen, rechte sloten, langgerekte percelen en een lintbebouwing van boerderijen. Toch is het niet kaal geworden, want bij de ontginning zijn stelselmatig <b>houtsingels en wegbeplantingen</b> aangelegd \u2014 nodig als windkering op de open vlakte en als leverancier van geriefhout. Juist die groenstructuren vormen nu de ecologische ruggengraat van het gebied: lange, doorlopende <b>corridors</b> waarlangs <b>das, steenuil, geelgors en vleermuizen</b> zich door het agrarische land bewegen. In de bermen en slootkanten overleven bovendien nog kruiden die van de percelen zijn verdwenen.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013okt</b>; apr\u2013mei (singelbloei), mei\u2013jun (zang), jun\u2013aug (bermflora en vleermuizen)<br>\n    <b>Beste tijd van de dag:</b> Avondschemer \u2014 vleermuizen volgen de singels, steenuil roept.',
 why=['Gaaf <b>veenontginningspatroon</b>: rechte wegen, sloten en lintbebouwing.',
      'Naam <i>vledder-veen</i> beschrijft het landschap v\u00f3\u00f3r de ontginning.',
      '<b>Houtsingels</b> als windkering \u00e9n ecologische corridor.',
      'Restanten <b>bermflora</b> in slootkanten en wegbermen.'],
 phen=['<span class="months">Apr\u2013Mei</span> \U0001f338 <b>Meidoorn en vlier</b> bloeien in de singels.',
       '<span class="months">Mei\u2013Jun</span> \U0001f426 <b>Geelgors</b> zingt vanaf de wegbeplanting.',
       '<span class="months">Jun\u2013Aug</span> \U0001f987 <b>Vleermuizen</b> volgen de singels als vliegroute.',
       '<span class="months">Okt\u2013Nov</span> \U0001f341 <b>Singels</b> in herfstkleur boven de kale akkers.'],
 wild=['\U0001f9a1 Das', '\U0001f989 Steenuil', '\U0001f426 Geelgors', '\U0001f987 Gewone dwergvleermuis', '\U0001f333 Meidoorn \u00b7 Vlier \u00b7 Zomereik'],
 trail=['Parkeren in <b>Vledderveen</b>; landwegen en fietspaden volgen de singels.',
        'Combineer met <b>Onstwedde</b> voor het contrast es\u2013ontginning.',
        'Grotendeels <b>particulier boerenland</b>: blijf op de openbare wegen.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Deels particulier agrarisch land'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Peat reclamation village \u00b7 landscape elements', 'list 34 \u00b7 no. 10'],
 loc='\U0001f4cd Vledderveen, between Onstwedde and Stadskanaal \u00b7 Reclamation village with landscape \u00b7 Medium-sized',
 desc='<b>Vledderveen</b> is a <b>peat reclamation village</b> on the edge of Westerwolde, created in the nineteenth century when the last bogs between the sand ridges were dug away. The name combines <i>vledder</i> \u2014 an old word for boggy, low-lying grassland \u2014 with <i>veen</i>, peat, and so describes the landscape as it was before reclamation. What lies there now is the typical <b>rational reclamation pattern</b>: straight roads, straight ditches, elongated plots and a ribbon of farmhouses. Yet it did not become bare, because the reclamation systematically included <b>shelterbelts and roadside planting</b> \u2014 needed as windbreaks on the open plain and as a source of utility timber. It is precisely those green structures that now form the ecological backbone of the area: long, continuous <b>corridors</b> along which <b>badger, little owl, yellowhammer and bats</b> move through the farmland. In the verges and ditch banks, moreover, herbs survive that have vanished from the fields.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Oct</b>; Apr\u2013May (shelterbelt blossom), May\u2013Jun (song), Jun\u2013Aug (verge flora and bats)<br>\n    <b>Best time of day:</b> Dusk \u2014 bats follow the belts, little owl calls.',
 why=['An intact <b>peat reclamation pattern</b>: straight roads, ditches and ribbon housing.',
      'The name <i>vledder-veen</i> describes the landscape before reclamation.',
      '<b>Shelterbelts</b> as windbreak and ecological corridor alike.',
      'Remnant <b>verge flora</b> in ditch banks and roadsides.'],
 phen=['<span class="months">Apr\u2013May</span> \U0001f338 <b>Hawthorn and elder</b> flower in the belts.',
       '<span class="months">May\u2013Jun</span> \U0001f426 <b>Yellowhammer</b> sings from the roadside planting.',
       '<span class="months">Jun\u2013Aug</span> \U0001f987 <b>Bats</b> follow the belts as flight routes.',
       '<span class="months">Oct\u2013Nov</span> \U0001f341 <b>Shelterbelts</b> in autumn colour above bare fields.'],
 wild=['\U0001f9a1 Badger', '\U0001f989 Little owl', '\U0001f426 Yellowhammer', '\U0001f987 Common pipistrelle', '\U0001f333 Hawthorn \u00b7 Elder \u00b7 Pedunculate oak'],
 trail=['Park in <b>Vledderveen</b>; country lanes and cycle paths follow the belts.',
        'Combine with <b>Onstwedde</b> for the contrast between field and reclamation.',
        'Largely <b>private farmland</b>: keep to the public roads.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Partly private farmland')))

C.append(card(1234, 'Boerendiep', dict(
 tags=['Groningen \u00b7 Westerwolde', 'Beek &amp; oeverlanden \u00b7 zijtak van de Ruiten Aa', 'list 34 \u00b7 no. 11'],
 loc='\U0001f4cd Bij Onstwedde en Wedde \u00b7 Beekloop met oeverlanden \u00b7 Middelgroot',
 desc='Het <b>Boerendiep</b> is een van de kleinere beken van Westerwolde, een zijtak in het systeem dat uiteindelijk in de Westerwoldsche Aa uitkomt. De naam is nuchter en typisch voor de streek: het <i>diep</i> van de boeren, de watergang die het land van de omliggende boerderijen ontwaterde. Net als de grotere beken is het Boerendiep in de twintigste eeuw <b>rechtgetrokken en verdiept</b> om het water sneller af te voeren, en net als daar wordt dat nu deels teruggedraaid. Langs delen van de loop zijn <b>natuurvriendelijke oevers</b> aangelegd \u2014 flauwe taluds waar riet, zeggen en oeverkruiden kunnen groeien in plaats van steile, kale wanden \u2014 en op sommige trajecten heeft de beek zijn <b>bochten terug</b>. Dat maakt een groot verschil: waar de oever gevarieerd is, verschijnen <b>libellen, kikkers en kleine vissen</b>, en met hen de <b>ijsvogel</b>. In de aangrenzende natte graslanden broeden watersnip en kievit.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>apr\u2013sep</b>; apr\u2013jun (weidevogels, oeverflora), jun\u2013aug (libellen), okt\u2013mrt (hoogwater)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend \u2014 ijsvogel jaagt vanaf overhangende takken.',
 why=['Kleine <b>Westerwoldse beek</b> met natuurvriendelijke oevers.',
      'Deels <b>hermeanderd</b> na twintigste-eeuwse normalisatie.',
      'Flauwe taluds met <b>riet, zeggen en oeverkruiden</b>.',
      '<b>IJsvogel, libellen en weidevogels</b> in de oeverlanden.'],
 phen=['<span class="months">Mrt\u2013Apr</span> \U0001f426 <b>IJsvogel</b> graaft nestgangen in steile oeverdelen.',
       '<span class="months">Apr\u2013Jun</span> \U0001f33f <b>Dotterbloem en gele lis</b> op de flauwe taluds.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Weidebeekjuffer en glazenmakers</b> boven het water.',
       '<span class="months">Nov\u2013Mrt</span> \U0001f30a <b>Hoogwater</b> in de oeverlanden.'],
 wild=['\U0001f426 IJsvogel', '\U0001f98b Weidebeekjuffer', '\U0001f426 Watersnip', '\U0001f438 Groene kikker', '\U0001f33f Riet \u00b7 Gele lis \u00b7 Dotterbloem'],
 trail=['Parkeren bij <b>Onstwedde</b> of Wedde; paden en fietsroutes volgen de beek.',
        'Combineer met het <b>dal van de Ruiten Aa</b> waarin het uitmondt.',
        'Beheer: <b>waterschap Hunze en Aa\u2019s</b> en Staatsbosbeheer.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \U0001f97e Natte oeverpaden'),
 dict(
 tags=['Groningen \u00b7 Westerwolde', 'Brook &amp; bankside land \u00b7 tributary of the Ruiten Aa', 'list 34 \u00b7 no. 11'],
 loc='\U0001f4cd Near Onstwedde and Wedde \u00b7 Brook with bankside land \u00b7 Medium-sized',
 desc='The <b>Boerendiep</b> is one of the smaller brooks of Westerwolde, a tributary in the system that eventually feeds the Westerwoldsche Aa. The name is matter-of-fact and typical of the district: the farmers\u2019 <i>diep</i>, the watercourse that drained the land of the surrounding farms. Like the larger brooks, the Boerendiep was <b>straightened and deepened</b> in the twentieth century to discharge water faster, and like them that is now partly being undone. Along stretches of its course <b>nature-friendly banks</b> have been created \u2014 gentle slopes where reed, sedges and bankside herbs can grow instead of steep bare walls \u2014 and on some reaches the brook has its <b>bends back</b>. That makes a great difference: where the bank is varied, <b>dragonflies, frogs and small fish</b> appear, and with them the <b>kingfisher</b>. In the adjoining wet grasslands snipe and lapwing breed.',
 meta='<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b>; Apr\u2013Jun (meadow birds, bankside flora), Jun\u2013Aug (dragonflies), Oct\u2013Mar (high water)<br>\n    <b>Best time of day:</b> Early morning \u2014 kingfisher hunting from overhanging branches.',
 why=['A small <b>Westerwolde brook</b> with nature-friendly banks.',
      'Partly <b>remeandered</b> after twentieth-century canalisation.',
      'Gentle slopes with <b>reed, sedges and bankside herbs</b>.',
      '<b>Kingfisher, dragonflies and meadow birds</b> in the bankside land.'],
 phen=['<span class="months">Mar\u2013Apr</span> \U0001f426 <b>Kingfisher</b> digs nest tunnels in the steeper bank sections.',
       '<span class="months">Apr\u2013Jun</span> \U0001f33f <b>Marsh marigold and yellow iris</b> on the gentle slopes.',
       '<span class="months">Jun\u2013Aug</span> \U0001f98b <b>Banded demoiselle and hawkers</b> above the water.',
       '<span class="months">Nov\u2013Mar</span> \U0001f30a <b>High water</b> in the bankside land.'],
 wild=['\U0001f426 Kingfisher', '\U0001f98b Banded demoiselle', '\U0001f426 Common snipe', '\U0001f438 Green frog', '\U0001f33f Reed \u00b7 Yellow iris \u00b7 Marsh marigold'],
 trail=['Park at <b>Onstwedde</b> or Wedde; paths and cycle routes follow the brook.',
        'Combine with the <b>Ruiten Aa valley</b> into which it flows.',
        'Managed by the <b>Hunze en Aa\u2019s water board</b> and Staatsbosbeheer.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \U0001f97e Wet bankside paths'),
 card_class='card water'))

C.append(card(1235, 'Polder Nieuwe Compagnie', dict(
 tags=['Groningen \u00b7 Veenkoloni\u00ebn', 'Veenkoloniale polder \u00b7 akkerland en wijken', 'list 34 \u00b7 no. 12'],
 loc='\U0001f4cd Bij Veendam en Wildervank \u00b7 Veenkoloniaal polderlandschap \u00b7 Groot gebied',
 desc='De <b>Polder Nieuwe Compagnie</b> bij Veendam is een leerboekvoorbeeld van het <b>veenkoloniale landschap</b>, en de naam vertelt hoe het ontstond. Een <i>compagnie</i> was een vennootschap van investeerders \u2014 vaak Groninger stadsbestuurders en kooplieden \u2014 die het recht kocht om een veengebied af te graven. Zij financierden de <b>hoofddiepen en wijken</b>, de kanalen waarover de turf naar de stad werd geschipt, en verkochten daarna de kale <b>dalgrond</b> aan boeren. Dat systeem heeft het landschap tot in het kleinste detail bepaald: alles ligt in <b>rechte, evenwijdige lijnen</b>, de percelen zijn langgerekt, en de bebouwing volgt de kanalen in linten. Ecologisch is dit geen rijk gebied \u2014 grootschalige akkerbouw op dalgrond \u2014 maar de <b>wijken, bermen en erfbeplantingen</b> vormen samen een fijnmazig netwerk dat er wel toe doet. Er broeden <b>gele kwikstaart, veldleeuwerik en patrijs</b>, en \u2019s winters foerageren grote groepen <b>ganzen, zwanen en akkervogels</b> op de open velden.',
 meta='<b>Beste seizoen &amp; piekmaanden:</b> <b>hele jaar</b>; apr\u2013jun (akkervogels), nov\u2013feb (ganzen, zwanen en akkervogelzwermen)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend voor akkervogels; winterse schemer voor ganzenvluchten.',
 why=['Leerboekvoorbeeld van het <b>veenkoloniale ontginningspatroon</b>.',
      'Naam <i>compagnie</i> verwijst naar de <b>investeerdersvennootschap</b> die het veen kocht.',
      '<b>Wijken, bermen en erven</b> als fijnmazig netwerk in grootschalig akkerland.',
      'Winterse concentraties <b>ganzen, zwanen en akkervogels</b>.'],
 phen=['<span class="months">Apr\u2013Jun</span> \U0001f426 <b>Veldleeuwerik en gele kwikstaart</b> boven de akkers.',
       '<span class="months">Mei\u2013Jul</span> \U0001f426 <b>Patrijs</b> in de ruige bermen en akkerranden.',
       '<span class="months">Aug\u2013Sep</span> \U0001f33e <b>Oogst</b> \u2014 aardappelen en granen van de dalgrond.',
       '<span class="months">Nov\u2013Feb</span> \U0001f9a2 <b>Ganzen en wilde zwanen</b> foerageren op de open velden.'],
 wild=['\U0001f426 Veldleeuwerik', '\U0001f426 Gele kwikstaart', '\U0001f426 Patrijs', '\U0001f9a2 Kolgans \u00b7 Wilde zwaan', '\U0001f33e Akkerranden \u00b7 Riet in de wijken'],
 trail=['Parkeren bij <b>Veendam</b> of Wildervank; fietsroutes volgen de kanalen.',
        'Vooral een <b>fiets- en autolandschap</b> \u2014 de schaal is groot en open.',
        'Grotendeels <b>particulier akkerland</b>: blijf op openbare wegen en paden.'],
 foot='\U0001f436 Honden aan de lijn \u00b7 \U0001f4b6 Gratis \u00b7 \u26a0\ufe0f Grootschalig particulier akkerland \u00b7 \U0001f6b4 Fietslandschap'),
 dict(
 tags=['Groningen \u00b7 Peat Colonies', 'Peat-colony polder \u00b7 arable land and canals', 'list 34 \u00b7 no. 12'],
 loc='\U0001f4cd Near Veendam and Wildervank \u00b7 Peat-colony polder landscape \u00b7 Large area',
 desc='The <b>Polder Nieuwe Compagnie</b> near Veendam is a textbook example of the <b>peat-colony landscape</b>, and the name tells how it came about. A <i>compagnie</i> was a partnership of investors \u2014 often Groningen city magistrates and merchants \u2014 that bought the right to dig out a peat area. They financed the <b>main canals and side canals</b> along which the peat was shipped to the city, and then sold the bare <b>dalgrond</b> (cut-over soil) to farmers. That system determined the landscape down to the smallest detail: everything lies in <b>straight, parallel lines</b>, the plots are elongated, and the buildings follow the canals in ribbons. Ecologically this is not a rich area \u2014 large-scale arable farming on cut-over soil \u2014 but the <b>side canals, verges and farmyard planting</b> together form a fine-meshed network that does matter. <b>Yellow wagtail, skylark and grey partridge</b> breed here, and in winter large flocks of <b>geese, swans and farmland birds</b> feed on the open fields.',
 meta='<b>Best season &amp; peak months:</b> <b>All year</b>; Apr\u2013Jun (farmland birds), Nov\u2013Feb (geese, swans and farmland bird flocks)<br>\n    <b>Best time of day:</b> Early morning for farmland birds; winter dusk for goose flights.',
 why=['A textbook example of the <b>peat-colony reclamation pattern</b>.',
      'The name <i>compagnie</i> refers to the <b>investors\u2019 partnership</b> that bought the bog.',
      '<b>Side canals, verges and yards</b> as a fine network in large-scale arable land.',
      'Winter concentrations of <b>geese, swans and farmland birds</b>.'],
 phen=['<span class="months">Apr\u2013Jun</span> \U0001f426 <b>Skylark and yellow wagtail</b> above the fields.',
       '<span class="months">May\u2013Jul</span> \U0001f426 <b>Grey partridge</b> in the rough verges and field margins.',
       '<span class="months">Aug\u2013Sep</span> \U0001f33e <b>Harvest</b> \u2014 potatoes and grain from the cut-over soil.',
       '<span class="months">Nov\u2013Feb</span> \U0001f9a2 <b>Geese and whooper swans</b> feed on the open fields.'],
 wild=['\U0001f426 Skylark', '\U0001f426 Yellow wagtail', '\U0001f426 Grey partridge', '\U0001f9a2 White-fronted goose \u00b7 Whooper swan', '\U0001f33e Field margins \u00b7 Reed in the canals'],
 trail=['Park at <b>Veendam</b> or Wildervank; cycle routes follow the canals.',
        'Chiefly a <b>cycling and driving landscape</b> \u2014 the scale is large and open.',
        'Largely <b>private arable land</b>: keep to public roads and paths.'],
 foot='\U0001f436 Dogs on leash \u00b7 \U0001f4b6 Free \u00b7 \u26a0\ufe0f Large-scale private farmland \u00b7 \U0001f6b4 Cycling landscape')))

insert(C, after_id=1225)
progress(1235)
check()
