# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1770, 'Kernhem', {
 'tags': ['Gelderland · Ede', 'Landgoed met huis, lanen en vleermuisreservaat · zes eeuwen geschiedenis aan de rand van Ede', 'list 36 · no. 489'],
 'loc': '📍 Aan de noordrand van Ede, ten noorden van de N224 · Landgoed · start bij Huis Kernhem, Kernhemseweg 7',
 'desc': '<b>Landgoed Kernhem</b> aan de noordrand van Ede behoort tot de oudste landgoederen van Nederland en gaat ruim zeshonderd jaar terug: het huis werd voor het eerst vermeld in 1421 en was eeuwenlang in handen van machtige Veluwse geslachten, tot de familie Bentinck het goed in de achttiende eeuw klassiek liet inrichten met kaarsrechte lanen, vijvers en een parkbos. In 1970 schonk Sophie gravin Bentinck huis Kernhem aan de gemeente Ede, die het omringende landgoed met het Edese Bos aankocht; sindsdien is het vrij toegankelijk. Rond het classicistische <b>Huis Kernhem</b> — nu trouwlocatie met kunstexposities — liggen de kruidentuin, de Vissekom, de Hanepol en het park met eeuwenoude bomen. De <b>Doolhoflaan</b> met beuken uit 1735 is ingericht als reservaat voor vleermuizen; aan het eind ligt een grafheuvel uit de bronstijd waar in de achttiende eeuw een doolhof omheen werd aangelegd. Bij de monumentale boerderijen op het landgoed ligt de oorsprong van de bekende Remeker kaas en staat de oudste boom van de regio; zorgboerderij Makandra kweekt er paddenstoelen. Het klompenpad <b>Doesburgermolenpad</b> en de Trage Tocht Ede Kernhem (15 km) starten er.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (park en lanen), apr–mei (voorjaarsflora)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — zangvogels in de lanen.',
 'why': ['De <b>zeshonderd jaar oude landgoedgeschiedenis</b> rond Huis Kernhem.', 'De <b>Doolhoflaan</b> met beuken uit 1735 en het vleermuisreservaat.', 'De <b>bronstijdgrafheuvel</b> en het achttiende-eeuwse doolhof.', 'De sfeer van <b>lanen, vijvers en monumentale bomen</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Sneeuwklokjes</b> en narcissen in het park.', '<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> onder de oude beuken.', '<span class="months">Jun–Aug</span> 🦇 <b>Vleermuizen</b> jagen boven de vijvers in de schemering.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van lanen en park.'], 'wild': ['🐦 Bosuil · Boomklever · Grote bonte specht', '🦇 Watervleermuis · Rosse vleermuis · Gewone dwergvleermuis', '🐿️ Eekhoorn · Haas · Ree', '🌼 Bosanemoon · Sneeuwklokje · Daslook', '🌳 Beuk (1735) · Zomereik · Linde'],
 'trail': ['Start bij <b>Huis Kernhem</b> (Kernhemseweg 7, gratis parkeren).', 'Loop de <b>Doolhoflaan</b> af naar de grafheuvel en het Edese Bos.', 'Volg het <b>Doesburgermolenpad</b> (8 km) of de Trage Tocht Ede Kernhem (15 km).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Vleermuisreservaat — blijf op de paden · 🚶 Park-, laan- en zandpaden'
}, {
 'tags': ['Gelderland · Ede', 'Estate with house, avenues and bat reserve · six centuries of history on the edge of Ede', 'list 36 · no. 489'],
 'loc': '📍 On the northern edge of Ede, north of the N224 · Estate · start at Huis Kernhem, Kernhemseweg 7',
 'desc': '<b>Kernhem estate</b> on the northern edge of Ede is one of the oldest estates of the Netherlands and goes back more than six hundred years: the house was first mentioned in 1421 and was in the hands of powerful Veluwe families for centuries, until the Bentinck family had the estate laid out in the eighteenth century in a classical style with straight avenues, ponds and a park wood. In 1970 Sophie Countess Bentinck donated Huis Kernhem to the municipality of Ede, which bought the surrounding estate together with the Edese Bos; since then it has been freely accessible. Around the classical <b>Huis Kernhem</b> — now a wedding venue with art exhibitions — lie the herb garden, the Vissekom, the Hanepol and the park with centuries-old trees. The <b>Doolhoflaan</b> with beeches from 1735 has been set aside as a reserve for bats; at its end lies a Bronze Age burial mound around which a maze was laid out in the eighteenth century. The origins of the well-known Remeker cheese lie on the estate farms, where the oldest tree of the region also stands; the Makandra care farm cultivates mushrooms there. The clompenpad <b>Doesburgermolenpad</b> and the Trage Tocht Ede Kernhem (15 km) start here.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (park and avenues), Apr–May (spring flora)<br>\n    <b>Best time of day:</b> Morning — songbirds in the avenues.',
 'why': ['The <b>six-hundred-year estate history</b> around Huis Kernhem.', 'The <b>Doolhoflaan</b> with beeches from 1735 and the bat reserve.', 'The <b>Bronze Age burial mound</b> and the eighteenth-century maze.', 'The atmosphere of <b>avenues, ponds and monumental trees</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Snowdrops</b> and daffodils in the park.', '<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> under the old beeches.', '<span class="months">Jun–Aug</span> 🦇 <b>Bats</b> hunt above the ponds at dusk.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of avenues and park.'], 'wild': ['🐦 Tawny owl · Nuthatch · Great spotted woodpecker', '🦇 Pond bat · Noctule · Common pipistrelle', '🐿️ Squirrel · Hare · Roe deer', '🌼 Wood anemone · Snowdrop · Wild garlic', '🌳 Beech (1735) · Pedunculate oak · Lime'],
 'trail': ['Start at <b>Huis Kernhem</b> (Kernhemseweg 7, free parking).', 'Walk the <b>Doolhoflaan</b> down to the burial mound and the Edese Bos.', 'Follow the <b>Doesburgermolenpad</b> (8 km) or the Trage Tocht Ede Kernhem (15 km).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Bat reserve — stay on the paths · 🚶 Park, avenue and sand paths'
}))

C.append(mk.card(1771, 'Edese Bos', {
 'tags': ['Gelderland · Ede', 'Gemeentebos al genoemd in de boswet van 1512 · oude lanen, grafheuvels en doolhof', 'list 36 · no. 490'],
 'loc': '📍 Ten noordoosten van het centrum van Ede · Oud gemeentebos · tussen landgoed Kernhem, de Hessenweg en de Eder Heide',
 'desc': 'Het <b>Edese Bos</b> ligt direct ten noordoosten van het centrum van Ede en is een van de oudste bossen van Nederland: al in 1512 werd het genoemd in een toen opgestelde <b>boswet</b> — een zeldzaam vroeg bewijs van bosbeheer. Eeuwenlang was het bos het gemeenschappelijke bezit van dertien hoeven onder leiding van een houtrichter; de huidige opstand dateert grotendeels van tussen 1885 en 1925. In 1888 kwam het bos aan de heren van Kernhem, en sinds 1970 is de gemeente Ede eigenaar. Het is een gevarieerd bos van beuken, eiken, naaldbomen en hier en daar een bijzonder bosvak, met licht glooiende paden, statige lanen en open plekken waar de natuur haar gang mocht gaan. De <b>Doolhoflaan</b> doorsnijdt het bos vanaf Huis Kernhem; langs de laan liggen een <b>grafheuvel uit de bronstijd</b> met de resten van een achttiende-eeuws doolhof en de geheimzinnige ‘bloedsteen’. De oude beuken van de laan zijn een reservaat voor vleermuizen. Gemarkeerde routes als de Edese Bosroute (4 km) en de Driesprongroute (5 km) maken rondjes door het bos; de Trage Tocht Ede Kernhem en de wandeling rond de Hunnenberg doen het eveneens aan.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (bos), apr–mei (voorjaarsflora)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — zang en licht in de oude lanen.',
 'why': ['Een <b>oud gemeentebos</b> met een boswet uit 1512 als geboorteakte.', 'De <b>Doolhoflaan</b> met beuken, grafheuvel en ‘bloedsteen’.', 'De <b>vleermuizen</b> in de oude lanen en holle bomen.', 'De <b>gemarkeerde routes</b> en de ligging naast landgoed Kernhem.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> en dalkruid in het loofbos.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> rond lanen en open plekken.', '<span class="months">Jun–Aug</span> 🦇 <b>Vleermuizen</b> boven de Doolhoflaan in de schemering.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van beuken en eiken.'], 'wild': ['🐦 Zwarte specht · Boomklever · Havik', '🦇 Rosse vleermuis · Watervleermuis · Gewone dwergvleermuis', '🐿️ Eekhoorn · Ree · Vos', '🌼 Bosanemoon · Dalkruid · Blauwe bosbes', '🌳 Beuk · Zomereik · Grove den'],
 'trail': ['Start bij <b>Huis Kernhem</b> of aan de Wekeromseweg en de Hessenweg.', 'Volg de <b>Edese Bosroute</b> (4 km) of de Driesprongroute (5 km).', 'Combineer met het <b>landgoed Kernhem</b>, Zonneoord of de Eder Heide.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Vleermuisreservaat — blijf op de paden · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Ede', 'Municipal forest already mentioned in the forest law of 1512 · old avenues, burial mounds and maze', 'list 36 · no. 490'],
 'loc': '📍 North-east of the centre of Ede · Ancient municipal forest · between Kernhem estate, the Hessenweg and the Eder Heide',
 'desc': 'The <b>Edese Bos</b> lies just north-east of the centre of Ede and is one of the oldest forests of the Netherlands: as early as 1512 it was mentioned in a <b>forest law</b> drawn up then — a remarkably early proof of forest management. For centuries the wood was the common property of thirteen farms under a wood-reeve (houtrichter); the present stand largely dates from between 1885 and 1925. In 1888 the forest came to the lords of Kernhem, and since 1970 the municipality of Ede has owned it. It is a varied forest of beeches, oaks, conifers and here and there a special stand, with gently rolling paths, stately avenues and clearings where nature was allowed its way. The <b>Doolhoflaan</b> crosses the wood from Huis Kernhem; along the avenue lie a <b>Bronze Age burial mound</b> with the remains of an eighteenth-century maze and the mysterious ‘blood stone’. The old beeches of the avenue are a reserve for bats. Marked routes such as the Edese Bosroute (4 km) and the Driesprongroute (5 km) make circuits through the wood; the Trage Tocht Ede Kernhem and the walk around the Hunnenberg also pass through it.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (forest), Apr–May (spring flora)<br>\n    <b>Best time of day:</b> Morning — song and light in the old avenues.',
 'why': ['An <b>ancient municipal forest</b> with a forest law of 1512 as its birth certificate.', 'The <b>Doolhoflaan</b> with beeches, burial mound and ‘blood stone’.', 'The <b>bats</b> in the old avenues and hollow trees.', 'The <b>marked routes</b> and the location next to the Kernhem estate.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> and may lily in the broadleaf wood.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> around avenues and clearings.', '<span class="months">Jun–Aug</span> 🦇 <b>Bats</b> above the Doolhoflaan at dusk.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of beeches and oaks.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Goshawk', '🦇 Noctule · Pond bat · Common pipistrelle', '🐿️ Squirrel · Roe deer · Fox', '🌼 Wood anemone · May lily · Bilberry', '🌳 Beech · Pedunculate oak · Scots pine'],
 'trail': ['Start at <b>Huis Kernhem</b> or on the Wekeromseweg and the Hessenweg.', 'Follow the <b>Edese Bosroute</b> (4 km) or the Driesprongroute (5 km).', 'Combine with the <b>Kernhem estate</b>, Zonneoord or the Eder Heide.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Bat reserve — stay on the paths · 🚶 Forest and sand paths'
}))

C.append(mk.card(1772, 'Edese Heide', {
 'tags': ['Gelderland · Ede', 'Heide met militair verleden · Airborne-herdenking, Belgenmonument en koepelgraven van de Drieberg', 'list 36 · no. 491'],
 'loc': '📍 Ten oosten van Ede, van de Ginkelse Heide gescheiden door de N224 · Heidegebied De Ginkel · start bij Natuurcentrum De Ginkel of parkeerplaats De Heidebloem',
 'desc': 'De <b>Edese Heide</b> (ook Eder Heide) is het grote heidegebied ten oosten van Ede, samen met de aangrenzende Ginkelse Heide het bekendste wandelgebied van de gemeente. De heide ligt in het natuurgebied <b>De Ginkel</b>, tussen de bossen van de Veluwe en de oude bouwlanden van Ede. Eeuwenlang was het woeste grond waar de boeren van Ede-Veldhuizen hun schapen lieten grazen; in de twintigste eeuw kwam het leger er oefenen en werd de heide doorsneden door schietbanen met kogelvangers, waarvan de wallen nog in het veld liggen. De oorlogsgeschiedenis is voelbaar: in september 1944 landden rond de schaapskooi parachutisten tijdens de Slag om Arnhem — jaarlijks herdacht met de Airborne-herdenking — en bij de Eerste Wereldoorlog lag hier een groot Belgisch vluchtelingenkamp, waaraan het <b>Belgenmonument</b> herinnert. Midden op de heide liggen bij de <b>Drieberg</b> prehistorische koepelgraven van het Klokbekervolk (± 2000 v.Chr.). Natuurcentrum De Ginkel aan de rand van de heide is het startpunt voor excursies; wandelingen als de Edese Heide en Bossen-route (7 km) en de Driebergroute (7,5 km) voeren over de paarse vlaktes, die in augustus volop bloeien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — laag licht over de heide.',
 'why': ['De <b>uitgestrekte heide</b> van De Ginkel met vrij uitzicht.', 'De <b>koepelgraven van de Drieberg</b> (± 2000 v.Chr.).', 'De <b>militaire en oorlogsgeschiedenis</b>: Airborne en het Belgenmonument.', 'De <b>gemarkeerde heidewandelingen</b> vanaf Natuurcentrum De Ginkel.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐦 <b>Boomleeuwerik</b> en veldleeuwerik boven de heide.', '<span class="months">Jun–Aug</span> 🦋 <b>Heideblauwtje</b> en hooibeestje tussen de struikhei.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de vlaktes paars.', '<span class="months">Sep</span> 🎖️ <b>Airborne-herdenking</b> bij de Ginkelse Heide.'], 'wild': ['🐦 Boomleeuwerik · Geelgors · Roodborsttapuit', '🦌 Edelhert · Ree · Wild zwijn', '🐑 Veluwse heideschapen · Drents heideschaap', '🦋 Heideblauwtje · Hooibeestje · Bruin blauwtje', '🌼 Struikhei · Dophei · Jeneverbes'],
 'trail': ['Start bij <b>Natuurcentrum De Ginkel</b> of parkeerplaats De Heidebloem.', 'Volg de <b>Driebergroute</b> (7,5 km) langs de koepelgraven.', 'Wandel de <b>Edese Heide en Bossen-route</b> (7 km) of combineer met de Ginkelse Heide.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Militaire oefeningen mogelijk — volg bebording · 🚶 Heide- en zandpaden'
}, {
 'tags': ['Gelderland · Ede', 'Heath with a military past · Airborne commemoration, Belgian Monument and the dome graves of the Drieberg', 'list 36 · no. 491'],
 'loc': '📍 East of Ede, separated from the Ginkelse Heide by the N224 · Heath area De Ginkel · start at Nature Centre De Ginkel or car park De Heidebloem',
 'desc': 'The <b>Edese Heide</b> (also Eder Heide) is the large heath area east of Ede and, together with the adjacent Ginkelse Heide, the best-known walking area of the municipality. The heath lies in the nature area <b>De Ginkel</b>, between the forests of the Veluwe and the old arable lands of Ede. For centuries it was common waste land where the farmers of Ede-Veldhuizen grazed their sheep; in the twentieth century the army came to exercise and firing ranges with bullet stops (kogelvangers) cut across the heath, their banks still visible in the field. The war history is tangible: in September 1944 paratroopers landed around the sheep fold during the Battle of Arnhem — commemorated annually at the Airborne memorial service — and in the First World War a large Belgian refugee camp lay here, recalled by the <b>Belgian Monument</b>. In the middle of the heath, near the <b>Drieberg</b>, lie prehistoric dome graves of the Bell Beaker people (± 2000 BC). Nature Centre De Ginkel on the edge of the heath is the starting point for excursions; walks such as the Edese Heide en Bossen route (7 km) and the Driebergroute (7.5 km) lead over the purple plains, which bloom abundantly in August.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Morning or late afternoon — low light over the heath.',
 'why': ['The <b>vast heath</b> of De Ginkel with open views.', 'The <b>dome graves of the Drieberg</b> (± 2000 BC).', 'The <b>military and war history</b>: Airborne and the Belgian Monument.', 'The <b>marked heath walks</b> from Nature Centre De Ginkel.'],
 'phen': ['<span class="months">Apr–May</span> 🐦 <b>Woodlark</b> and skylark above the heath.', '<span class="months">Jun–Aug</span> 🦋 <b>Silver-studded blue</b> and small heath among the heather.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the plains purple.', '<span class="months">Sep</span> 🎖️ <b>Airborne commemoration</b> at the Ginkelse Heide.'], 'wild': ['🐦 Woodlark · Yellowhammer · Stonechat', '🦌 Red deer · Roe deer · Wild boar', '🐑 Veluwe heath sheep · Drenthe heath sheep', '🦋 Silver-studded blue · Small heath · Brown argus', '🌼 Bell heather · Cross-leaved heath · Juniper'],
 'trail': ['Start at <b>Nature Centre De Ginkel</b> or car park De Heidebloem.', 'Follow the <b>Driebergroute</b> (7.5 km) past the dome graves.', 'Walk the <b>Edese Heide en Bossen route</b> (7 km) or combine with the Ginkelse Heide.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Military exercises possible — follow the signs · 🚶 Heath and sand paths'
}))

C.append(mk.card(1773, 'Roekel', {
 'tags': ['Gelderland · Otterlo/Ede', 'Landgoed van 518 ha tussen Ede en Otterlo · gemeentebos sinds 1960 met wild en hondenlosloopgebied', 'list 36 · no. 492'],
 'loc': '📍 Tussen Ede en Otterlo, gemeente Ede · Landgoed en bos · ingang met zwerfkeien aan de Apeldoornseweg',
 'desc': '<b>Roekel</b> — ook wel het Roekelse Bos — is een typisch Veluws bosgebied van 518 hectare tussen Ede en Otterlo. De landgoederen Westerrode en Peppelenburg vormen samen het landgoed Roekel, dat in 1960 in bezit kwam van de gemeente Ede en op 18 augustus van dat jaar officieel voor het publiek werd opengesteld; de twee grote zwerfkeien bij de ingang aan de Apeldoornseweg herinneren daaraan. Het is een rustig, glooiend bos met veel kleine paden, waar je zomaar een wild zwijn of edelhert tegenkomt. In het zuiden ligt het <b>losloopgebied De Roekel</b> (circa 48 hectare), waar honden het hele jaar los mogen tussen dennen, berken, eiken en beuken — met een verhard pad dat ook rolstoel- en kinderwagenproof is. Gemarkeerde wandelroutes zijn de Westerrode-route (4 km) en de Lettense Berg-route (4,1 of 6,1 km); richting de Valenberg en het Mosselse Veld liggen wildobservatiepunten en de routes gaan over in het open stuifzand van het Mosselse Zand.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of schemering — wild op de paden.',
 'why': ['Het <b>stille, wildrijke bos</b> met tientallen kleine paden.', 'Het <b>48 hectare grote hondenlosloopgebied</b> met verhard pad.', 'De kans op <b>edelhert en wild zwijn</b> op de bospaden.', 'De gemarkeerde routes naar de <b>Valenberg en het Mosselse Veld</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> en voorjaarsgroen in het loofbos.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het gemengde bos.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de open veldjes.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de omgeving.'], 'wild': ['🐦 Zwarte specht · Boomklever · Havik', '🦌 Edelhert · Wild zwijn · Ree', '🦋 Bont zandoogje · Citroenvlinder · Kleine vos', '🌼 Blauwe bosbes · Struikhei · Adelaarsvaren', '🌳 Grove den · Beuk · Ruwe berk'],
 'trail': ['Start bij de <b>ingang aan de Apeldoornseweg</b> (tussen Ede en Otterlo).', 'Volg de <b>Westerrode-route</b> (4 km) of de Lettense Berg-route (4,1 of 6,1 km).', 'Laat de hond los in <b>losloopgebied De Roekel</b> (Mosselsepad).'],
 'foot': '🐕 Honden los in het losloopgebied, aangelijnd daarbuiten · 💶 Gratis · ⚠️ Wildgebied — rustig en blijf op de paden · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Otterlo/Ede', 'Estate of 518 ha between Ede and Otterlo · municipal forest since 1960 with game and dog exercise area', 'list 36 · no. 492'],
 'loc': '📍 Between Ede and Otterlo, Ede municipality · Estate and forest · entrance with erratic boulders on the Apeldoornseweg',
 'desc': '<b>Roekel</b> — also called the Roekelse Bos — is a typical Veluwe forest area of 518 hectares between Ede and Otterlo. The estates of Westerrode and Peppelenburg together form the Roekel estate, which came into the possession of the municipality of Ede in 1960 and was officially opened to the public on 18 August of that year; the two large erratic boulders at the entrance on the Apeldoornseweg recall that event. It is a quiet, rolling forest with many small paths, where you may easily meet a wild boar or a red deer. In the south lies the <b>De Roekel dog exercise area</b> (about 48 hectares), where dogs may run free all year between pines, birches, oaks and beeches — with a paved path that is also wheelchair- and buggy-friendly. Marked walking routes are the Westerrode route (4 km) and the Lettense Berg route (4.1 or 6.1 km); towards the Valenberg and the Mosselse Veld lie game-viewing points and the routes merge into the open drift sand of the Mosselse Zand.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or dusk — game on the paths.',
 'why': ['The <b>quiet, game-rich forest</b> with dozens of small paths.', 'The <b>48-hectare dog exercise area</b> with a paved path.', 'The chance of <b>red deer and wild boar</b> on the forest paths.', 'The marked routes to the <b>Valenberg and the Mosselse Veld</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> and spring greenery in the broadleaf wood.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the mixed forest.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the open fields.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the surroundings.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Goshawk', '🦌 Red deer · Wild boar · Roe deer', '🦋 Speckled wood · Brimstone · Small tortoiseshell', '🌼 Bilberry · Bell heather · Bracken', '🌳 Scots pine · Beech · Silver birch'],
 'trail': ['Start at the <b>entrance on the Apeldoornseweg</b> (between Ede and Otterlo).', 'Follow the <b>Westerrode route</b> (4 km) or the Lettense Berg route (4.1 or 6.1 km).', 'Let the dog run free in the <b>De Roekel exercise area</b> (Mosselsepad).'],
 'foot': '🐕 Dogs free in the exercise area, on lead outside it · 💶 Free · ⚠️ Game area — be quiet and stay on the paths · 🚶 Forest and sand paths'
}))

C.append(mk.card(1774, 'De Zanding', {
 'tags': ['Gelderland · Otterlo/Ede', 'Heide- en stuifzandgebied aan de rand van Otterlo · het Otterloop-pad en houtsnijwerk van de Grote 5', 'list 36 · no. 493'],
 'loc': '📍 Aan de zuidwestrand van Otterlo, richting Nationaal Park De Hoge Veluwe · Heide en stuifzand · start bij Wever Lodge (Onderlangs)',
 'desc': 'De <b>Zanding</b> is een natuurgebied met heide, stuifzand en dennenbos net buiten Otterlo, tegen de rand van Nationaal Park De Hoge Veluwe aan. Terwijl de bekendere Veluwegebieden vol lopen, blijft het hier opvallend rustig: een kleinschalig landschap van open zandvlaktes, heide met solitaire dennen en glooiende stuifwallen die omstreeks 1900 werden beplant om het zand te bedwingen. Door het gebied loopt het <b>Otterloop-pad</b>, een rode rondwandeling van 4,9 kilometer die door vrijwilligers van de Natuurwerkgroep De Zanding is uitgezet: eerst over heide en zand, dan met een stevige klim de stuwwal op en door het dennenbos, met bankjes en doorkijkjes over de zandvlakte. Onderweg kom je de <b>houtsnijwerken</b> van De Grote 5 van Otterlo tegen — onder meer een valk die over het zand uitkijkt. Het losse zand en de hoogteverschillen maken het gebied minder geschikt voor rolstoelen en kinderwagens, maar een paradijs voor kinderen; honden zijn er welkom aan de lijn. Start- en eindpunt is Wever Lodge, het voormalige Carnegie Cottage aan de rand van het vakantiepark De Zanding.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — laag licht over het zand.',
 'why': ['Het <b>rustige heide- en stuifzandlandschap</b> aan de rand van Otterlo.', 'Het <b>Otterloop-pad</b> (4,9 km) met klimmetjes en doorkijkjes.', 'De <b>houtsnijwerken</b> van De Grote 5 van Otterlo.', 'De <b>speelduinen voor kinderen</b> en de rust vergeleken met de grote gebieden.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Zandblauwtje</b> en muizenoor bloeien op het zand.', '<span class="months">Mei–Aug</span> 🐦 <b>Boomleeuwerik</b> en nachtzwaluw boven de heide.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> tussen zand en dennen.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten aan de bosranden.'], 'wild': ['🐦 Nachtzwaluw · Boomleeuwerik · Roodborsttapuit', '🦌 Edelhert · Ree · Wild zwijn', '🦎 Zandhagedis · Levendbarende hagedis', '🦋 Heideblauwtje · Bont zandoogje · Citroenvlinder', '🌼 Struikhei · Zandzegge · Buntgras'],
 'trail': ['Start bij <b>Wever Lodge</b> (Onderlangs 35, Otterlo) en volg het Otterloop-pad.', 'Klim de <b>stuwwal</b> op voor de doorkijkjes over het zand.', 'Combineer met het <b>Mosselse Zand</b> en Planken Wambuis of de Trage Tocht Otterlo.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Stuifzand en stijlere paden — stevig schoeisel · 🚶 Zand-, heide- en bospaden'
}, {
 'tags': ['Gelderland · Otterlo/Ede', 'Heath and drift-sand area on the edge of Otterlo · the Otterloop path and wood carvings of the Big 5', 'list 36 · no. 493'],
 'loc': '📍 On the south-western edge of Otterlo, towards National Park De Hoge Veluwe · Heath and drift sand · start at Wever Lodge (Onderlangs)',
 'desc': 'The <b>Zanding</b> is a nature area with heath, drift sand and pine forest just outside Otterlo, against the edge of National Park De Hoge Veluwe. While the better-known Veluwe areas fill up, it stays remarkably quiet here: a small-scale landscape of open sand plains, heath with solitary pines and rolling drift banks that were planted around 1900 to tame the sand. The <b>Otterloop path</b> runs through the area, a red circular walk of 4.9 kilometres laid out by volunteers of the Natuurwerkgroep De Zanding: first over heath and sand, then a steady climb up the push moraine and through the pine forest, with benches and views over the sand plain. Along the way you meet the <b>wood carvings</b> of De Grote 5 van Otterlo (the Big 5 of Otterlo) — including a falcon looking out over the sand. The loose sand and differences in height make the area less suitable for wheelchairs and buggies, but a paradise for children; dogs are welcome on the lead. The start and finish is Wever Lodge, the former Carnegie Cottage on the edge of the De Zanding holiday park.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Morning or late afternoon — low light over the sand.',
 'why': ['The <b>quiet heath and drift-sand landscape</b> on the edge of Otterlo.', 'The <b>Otterloop path</b> (4.9 km) with climbs and views.', 'The <b>wood carvings</b> of De Grote 5 van Otterlo.', 'The <b>play dunes for children</b> and the peace compared with the large areas.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Sand sedge</b> and mouse-ear hawkweed bloom on the sand.', '<span class="months">May–Aug</span> 🐦 <b>Woodlark</b> and nightjar above the heath.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> between sand and pines.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer at the forest edges.'], 'wild': ['🐦 Nightjar · Woodlark · Stonechat', '🦌 Red deer · Roe deer · Wild boar', '🦎 Sand lizard · Viviparous lizard', '🦋 Silver-studded blue · Speckled wood · Brimstone', '🌼 Bell heather · Sand sedge · Grey hair-grass'],
 'trail': ['Start at <b>Wever Lodge</b> (Onderlangs 35, Otterlo) and follow the Otterloop path.', 'Climb the <b>push moraine</b> for the views over the sand.', 'Combine with the <b>Mosselse Zand</b> and Planken Wambuis or the Trage Tocht Otterlo.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Drift sand and steeper paths — sturdy footwear · 🚶 Sand, heath and forest paths'
}))

mk.insert(C, '1769')
mk.progress(1774)
mk.check()
