# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1795, 'Oostereng', {
 'tags': ['Gelderland · Wageningen/Bennekom/Renkum', 'Boswachterij van Staatsbosbeheer (685 ha) · ontginningslandgoed met arboretum en grafheuvels', 'list 36 · no. 514'],
 'loc': '📍 Op de grens van Wageningen, Bennekom en Renkum, tussen de Wageningse Berg en het Renkums beekdal · Bos en arboretum · start bij het Arboretum Oostereng (Keijenbergseweg 2, Bennekom)',
 'desc': '<b>Boswachterij Oostereng</b> ligt op de grens van Wageningen, Bennekom en Renkum, tussen de Wageningse Berg, de Keijenbergseweg en het Renkums beekdal. De naam verwijst naar de \u2019eng\u2019 — de omheinde gemeenschapsakker ten oosten van Bennekom — waarop dit landgoed in de negentiende eeuw werd ontgonnen: in 1847 kochten de Leidse zeepzieders Adriaen Tieleman en Cornelis Dros 280 hectare woeste domeingrond, beplantten die met dennen voor de productie van boswol en dennenolie en bouwden er in 1854 een boerderij. Via jonkheer Joan Quarles van Ufford kwam het landgoed in 1941 aan Staatsbosbeheer; het landhuis ging in de Tweede Wereldoorlog verloren. De 685 hectare grote boswachterij omvat nu oude ontginningsbossen, heiderestanten, sprengen en beekdalen met opvallende relicten: een bosreservaat uit 1840, een parkbos uit 1899 en het <b>Arboretum Oostereng</b> uit 1911 — een van Nederlands meest vergeten bomentuinen (circa 8 hectare), waaraan tuinarchitect Leonard Springer bijdroeg en die studenten van Wageningen University met vrijwilligers beheren. Verspreid door het bos liggen <b>grafheuvels</b> van de klokbekercultuur (3000–1500 v.Chr.), en langs de zuidrand loopt de oude wildwal tussen Bennekom en Meulunteren. Het bos is rijk aan dood hout: havik, zwarte specht, groene specht, draaihals, boommarter en ree leven er. Het Wageningse Engpad (klompenpad) en de dagwandeling \u2018Van beekdal tot stuwwal\u2019 doorkruisen het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, apr–mei (voorjaarsflora), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — vogelzang in de oude lanen.',
 'why': ['De <b>negentiende-eeuwse ontginningsgeschiedenis</b> van zeepzieders en boswol.', 'Het <b>Arboretum Oostereng</b>, een vergeten bomentuin uit 1911.', 'De <b>grafheuvels</b> van de klokbekercultuur in het bos.', 'De ligging op de <b>overgang van stuwwal naar beekdal</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Bosanemoon</b> in het oude loofbos.', '<span class="months">Apr–Mei</span> 🌸 <b>Arboretum</b> in bloei en jong blad.', '<span class="months">Mei–Jun</span> 🐦 <b>Havik en spechten</b> voeren jongen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van beuk en eik.'], 'wild': ['🐦 Havik · Zwarte specht · Draaihals', '🦌 Ree · Das · Boommarter', '🦋 Bont zandoogje · Citroenvlinder · Gehakkelde aurelia', '🌼 Bosanemoon · Dalkruid · Wilde kamperfoelie', '🌳 Beuk · Zomereik · Grove den'],
 'trail': ['Start bij het <b>Arboretum Oostereng</b> (Keijenbergseweg 2, Bennekom).', 'Volg het <b>Wageningse Engpad</b> of de routes richting het Renkums beekdal.', 'Combineer met de <b>Wageningse Berg</b> en de grafheuvels van de Ritzema Bosweg.'],
 'foot': '🐕 Honden aangelijnd (losloopgebied bij het Bennekomse Bos) · 💶 Gratis · ⚠️ Blijf op de paden · 🚶 Bos-, laan- en zandpaden'
}, {
 'tags': ['Gelderland · Wageningen/Bennekom/Renkum', 'Forest district of Staatsbosbeheer (685 ha) · reclaimed estate with arboretum and burial mounds', 'list 36 · no. 514'],
 'loc': '📍 On the border of Wageningen, Bennekom and Renkum, between the Wageningse Berg and the Renkums Beekdal · Forest and arboretum · start at Arboretum Oostereng (Keijenbergseweg 2, Bennekom)',
 'desc': '<b>Oostereng forest district</b> lies on the border of Wageningen, Bennekom and Renkum, between the Wageningse Berg, the Keijenbergseweg and the Renkums Beekdal. The name refers to the \u2018eng\u2019 — the enclosed communal field east of Bennekom — on which this estate was reclaimed in the nineteenth century: in 1847 the Leiden soap boilers Adriaen Tieleman and Cornelis Dros bought 280 hectares of barren crown land, planted it with pines for the production of forest wool and pine oil, and built a farm there in 1854. Via Jonkheer Joan Quarles van Ufford the estate passed to Staatsbosbeheer in 1941; the manor house was lost in the Second World War. The 685-hectare forest district now comprises old reclamation forests, heath remnants, spring streams and stream valleys with striking relics: a forest reserve from 1840, a park wood from 1899 and the <b>Arboretum Oostereng</b> from 1911 — one of the most forgotten tree gardens of the Netherlands (about 8 hectares), to which landscape architect Leonard Springer contributed and which students of Wageningen University manage with volunteers. Scattered through the forest lie <b>burial mounds</b> of the Bell Beaker culture (3000–1500 BC), and along the southern edge runs the old game wall between Bennekom and Meulunteren. The forest is rich in dead wood: goshawk, black woodpecker, green woodpecker, wryneck, pine marten and roe deer live here. The Wageningse Engpad (clompenpad) and the \u2018Van beekdal tot stuwwal\u2019 day walk cross the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Apr–May (spring flora), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — bird song in the old avenues.',
 'why': ['The <b>nineteenth-century reclamation history</b> of soap boilers and forest wool.', 'The <b>Arboretum Oostereng</b>, a forgotten tree garden from 1911.', 'The <b>burial mounds</b> of the Bell Beaker culture in the forest.', 'Its position on the <b>transition from ice-margin ridge to stream valley</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Wood anemone</b> in the old broadleaf forest.', '<span class="months">Apr–May</span> 🌸 <b>Arboretum</b> in bloom and young leaf.', '<span class="months">May–Jun</span> 🐦 <b>Goshawk and woodpeckers</b> rear young.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of beech and oak.'], 'wild': ['🐦 Goshawk · Black woodpecker · Wryneck', '🦌 Roe deer · Badger · Pine marten', '🦋 Speckled wood · Brimstone · Comma', '🌼 Wood anemone · May lily · Wild honeysuckle', '🌳 Beech · Pedunculate oak · Scots pine'],
 'trail': ['Start at <b>Arboretum Oostereng</b> (Keijenbergseweg 2, Bennekom).', 'Follow the <b>Wageningse Engpad</b> or the routes towards the Renkums Beekdal.', 'Combine with the <b>Wageningse Berg</b> and the burial mounds of the Ritzema Bosweg.'],
 'foot': '🐕 Dogs on lead (off-lead area at the Bennekomse Bos) · 💶 Free · ⚠️ Stay on the paths · 🚶 Forest, avenue and sand paths'
}))

C.append(mk.card(1796, 'Lange Hut en Grijsoord', {
 'tags': ['Gelderland · Wolfheze/Papendal', 'Landgoed en buurtschap aan de oude grens Ede–Arnhem · stille paadjes in de zone van het Bommenlijntje', 'list 36 · no. 515'],
 'loc': '📍 Tussen Wolfheze en Papendal, ten zuiden van de A12 · Bos en landgoed · te belopen via de historische Planken Wambuis-route van Natuurmonumenten',
 'desc': '<b>Lange Hut</b> en <b>Grijsoord</b> liggen in de stille boszone tussen Wolfheze en Papendal, net ten zuiden van de A12. Lange Hut is een klein landgoed waarvan de naam teruggaat op een langgerekt onderkomen uit de tijd van ontginning en herbergen; een bord met de naam markeert nog altijd de plek langs de oude wandelweg. Buurtschap Grijsoord vormt de nabijgelegen nederzetting, genoemd naar het groene oord dat dit dal tussen de Veluwezoom en de stuwwal ooit was. Door het gebied loopt de <b>grenswal tussen Ede en Arnhem</b> over de zuidelijke helling van het Papendal: bij het bord \u2019Lange Hut\u2019 voert de historische route van Natuurmonumenten het pad zo\u2019n vijftig meter omhoog langs die oude gemeentegrens. De streek ligt bovendien in de zone van het <b>Bommenlijntje</b>, het Duitse spoorlijntje uit 1941 dat Wolfheze met vliegveld Deelen verbond en waarvan het oude tracé nog goed te volgen is. De paden zijn er smal en soms modderig en er zijn geen voorzieningen — een gebied voor wie de stilte zoekt tussen de grote namen van de Veluwe. De route van Natuurmonumenten (vanaf parkeerplaats Planken Wambuis of via de onderdoorgang van de A12 bij Papendal) verbindt het geheel met de open heide en bossen van de Reijerscamp en Planken Wambuis.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt–mrt (open zicht op de grenswal)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilste uren op de smalle paden.',
 'why': ['De <b>stille, smalle paadjes</b> langs de oude grenswal tussen Ede en Arnhem.', 'De <b>historische wandelroute Planken Wambuis</b> van Natuurmonumenten.', 'De sporen van het <b>Bommenlijntje</b> uit de Tweede Wereldoorlog.', 'De rust <b>onder de A12</b>, ver van de grote wandelgebieden.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Voorjaarsbloeiers</b> langs de bosranden.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in de oude eiken.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> langs de modderpaadjes.', '<span class="months">Okt–Mrt</span> 🍂 <b>Open zicht</b> op grenswal en bommenlijntracé.'], 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Edelhert · Ree · Wild zwijn', '🦊 Vos · Das', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Beuk · Grove den'],
 'trail': ['Loop de <b>historische Planken Wambuis-route</b> van Natuurmonumenten langs het bord \u2019Lange Hut\u2019.', 'Combineer met de <b>Reijerscamp</b> en het ecoduct Jac. P. Thijsse.', 'Parkeren kan bij de <b>parkeerplaats aan de N224</b> of bij Papendal.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Smalle, modderige paden — stevig schoeisel · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Wolfheze/Papendal', 'Estate and hamlet at the old Ede–Arnhem boundary · quiet paths in the Bommenlijntje zone', 'list 36 · no. 515'],
 'loc': '📍 Between Wolfheze and Papendal, south of the A12 · Forest and estate · walkable via the historic Planken Wambuis route of Natuurmonumenten',
 'desc': '<b>Lange Hut</b> and <b>Grijsoord</b> lie in the quiet forest zone between Wolfheze and Papendal, just south of the A12. Lange Hut is a small estate whose name goes back to an elongated shelter from the age of reclamation and inns; a sign with the name still marks the spot along the old walking road. The hamlet of Grijsoord is the nearby settlement, named after the green place this valley between the Veluwezoom and the ice-margin ridge once was. Through the area runs the <b>boundary wall between Ede and Arnhem</b> over the southern slope of the Papendal: at the \u2018Lange Hut\u2019 sign the historic Natuurmonumenten route climbs some fifty metres along that old municipal boundary. The region also lies in the zone of the <b>Bommenlijntje</b>, the German railway line from 1941 that linked Wolfheze with Deelen airfield and whose old trackbed is still easy to follow. The paths are narrow and sometimes muddy and there are no facilities — an area for those seeking silence between the great names of the Veluwe. The Natuurmonumenten route (from the Planken Wambuis car park or through the underpass of the A12 at Papendal) links it all with the open heath and forests of the Reijerscamp and Planken Wambuis.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct–Mar (open views of the boundary wall)<br>\n    <b>Best time of day:</b> Morning — the quietest hours on the narrow paths.',
 'why': ['The <b>quiet, narrow paths</b> along the old boundary wall between Ede and Arnhem.', 'The <b>historic Planken Wambuis walking route</b> of Natuurmonumenten.', 'The traces of the <b>Bommenlijntje</b> from the Second World War.', 'The peace <b>under the A12</b>, far from the big walking areas.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Spring bloomers</b> along the forest edges.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old oaks.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> along the muddy paths.', '<span class="months">Oct–Mar</span> 🍂 <b>Open views</b> of wall and railway trace.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Red deer · Roe deer · Wild boar', '🦊 Fox · Badger', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Beech · Scots pine'],
 'trail': ['Walk the <b>historic Planken Wambuis route</b> of Natuurmonumenten past the \u2018Lange Hut\u2019 sign.', 'Combine with the <b>Reijerscamp</b> and the Jac. P. Thijsse wildlife crossing.', 'Park at the <b>car park on the N224</b> or near Papendal.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Narrow, muddy paths — sturdy footwear · 🚶 Forest and sand paths'
}))

C.append(mk.card(1797, 'Reierscamp', {
 'tags': ['Gelderland · Wolfheze', 'Jong natuurgebied van Natuurmonumenten (bijna 200 ha) · akkers omgevormd tot heide, met landingshistorie 1944', 'list 36 · no. 516'],
 'loc': '📍 Ten zuiden van Wolfheze, tussen de A12, de spoorlijn Arnhem–Utrecht en de Buunderkamp · Heide en grasland · beheer door Natuurmonumenten',
 'desc': 'De <b>Reierscamp</b> (ook wel Reijerscamp) is een jong natuurgebied van Natuurmonumenten ten zuiden van Wolfheze, tussen de A12, de spoorlijn en de bossen van de Buunderkamp. Het was eeuwenlang een golvend akkercomplex: in de negentiende eeuw deels bebost voor mijnhout, in de twintigste eeuw weer ontgonnen voor de landbouw. Natuurmonumenten kocht het gebied rond 2004 aan — mede om de aanleg van het <b>ecoduct Jac. P. Thijsse</b> over de A12 (geopend in 2012) mogelijk te maken — en heeft sindsdien bijna 200 hectare voormalig landbouwland in tien jaar omgevormd tot een open heide- en schraallandschap, een van de grootste natuurontwikkelingsprojecten van de zuidelijke Veluwe. Edelherten kunnen er via het ecoduct van de voedselarme Veluwe de rijke graasgebieden van het rivierenland bereiken; in het gebied grazen ook runderen om de graslanden kort te houden. De geschiedenis is bewogen: op 17 september 1944 landden op deze open velden honderden zweefvliegtuigen met materieel voor de Slag om Arnhem, en bij het uitkijkpunt aan de Duitsekampweg zijn in 2014 herdenkingsobjecten geplaatst. Wandelroutes doorkruisen het jonge heideland, dat al door zandhagedissen, boomleeuweriken en heideblauwtjes wordt gekoloniseerd.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — edelherten op de open vlakten.',
 'why': ['De <b>natuurontwikkeling</b>: landbouwgrond wordt weer heide en schraalland.', 'Het <b>ecoduct Jac. P. Thijsse</b> dat de Veluwe met het rivierenland verbindt.', 'De <b>zweefvlieglandingen van 1944</b> en de herdenkingsobjecten.', 'De weidse stilte <b>dicht bij Arnhem</b>.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🐦 <b>Boomleeuwerik en graspieper</b> boven het jonge land.', '<span class="months">Jun–Aug</span> 🐄 <b>Begrazing</b> houdt de graslanden open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de voormalige akkers.', '<span class="months">Sep–Okt</span> 🦌 <b>Edelherten</b> steken het ecoduct over.'], 'wild': ['🐦 Boomleeuwerik · Graspieper · Roodborsttapuit', '🦌 Edelhert · Ree · Wild zwijn', '🐄 Rund (begrazing)', '🦎 Zandhagedis · Levendbarende hagedis', '🦋 Heideblauwtje · Bruin zandoogje · Hooibeestje'],
 'trail': ['Loop vanaf <b>station Wolfheze</b> of het uitkijkpunt aan de Duitsekampweg het gebied in.', 'Bekijk vanaf het <b>ecoduct Jac. P. Thijsse</b> de wildwissel over de A12.', 'Combineer met de <b>Johannahoeve</b> en de heide van Wolfheze.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Begrazing — houd afstand van de runderen · 🚶 Zand-, heide- en graspaden'
}, {
 'tags': ['Gelderland · Wolfheze', 'Young nature area of Natuurmonumenten (almost 200 ha) · farmland turned into heath, with 1944 landing history', 'list 36 · no. 516'],
 'loc': '📍 South of Wolfheze, between the A12, the Arnhem–Utrecht railway and the Buunderkamp · Heath and grassland · managed by Natuurmonumenten',
 'desc': 'The <b>Reierscamp</b> (also spelled Reijerscamp) is a young nature area of Natuurmonumenten south of Wolfheze, between the A12, the railway and the woods of the Buunderkamp. For centuries it was a rolling field complex: partly forested for pitwood in the nineteenth century, reclaimed for agriculture again in the twentieth. Natuurmonumenten bought the area around 2004 — partly to make possible the construction of the <b>Jac. P. Thijsse wildlife crossing</b> over the A12 (opened in 2012) — and has since, over ten years, converted almost 200 hectares of former farmland into an open heath and species-poor grassland landscape, one of the largest nature-development projects of the southern Veluwe. Via the crossing, red deer can move from the nutrient-poor Veluwe to the rich grazing grounds of the river land; cattle also graze the area to keep the grasslands short. The history is eventful: on 17 September 1944 hundreds of gliders with equipment for the Battle of Arnhem landed on these open fields, and memorial objects were placed at the viewpoint on the Duitsekampweg in 2014. Walking routes cross the young heath land, which is already being colonised by sand lizards, woodlarks and silver-studded blues.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Morning — red deer on the open plains.',
 'why': ['The <b>nature development</b>: farmland turning back into heath and grassland.', 'The <b>Jac. P. Thijsse crossing</b> linking the Veluwe with the river land.', 'The <b>glider landings of 1944</b> and the memorial objects.', 'The wide silence <b>close to Arnhem</b>.'],
 'phen': ['<span class="months">Mar–May</span> 🐦 <b>Woodlark and meadow pipit</b> above the young land.', '<span class="months">Jun–Aug</span> 🐄 <b>Grazing</b> keeps the grasslands open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the former fields.', '<span class="months">Sep–Oct</span> 🦌 <b>Red deer</b> cross the wildlife bridge.'], 'wild': ['🐦 Woodlark · Meadow pipit · Stonechat', '🦌 Red deer · Roe deer · Wild boar', '🐄 Cattle (grazing)', '🦎 Sand lizard · Viviparous lizard', '🦋 Silver-studded blue · Meadow brown · Small heath'],
 'trail': ['Walk in from <b>Wolfheze station</b> or the viewpoint on the Duitsekampweg.', 'Watch the wildlife crossing over the A12 from the <b>Jac. P. Thijsse bridge</b>.', 'Combine with the <b>Johannahoeve</b> and the heath of Wolfheze.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Grazing — keep your distance from the cattle · 🚶 Sand, heath and grass paths'
}))

C.append(mk.card(1798, 'Westerheide', {
 'tags': ['Gelderland · Arnhem-Noord (Schaarsbergen)', 'Hersteld heideveld in de landgoederengordel · begraasd door Veluwse heideschapen', 'list 36 · no. 517'],
 'loc': '📍 Tussen landgoed Warnsborn, Vijverberg en Schaarsbergen, ten noorden van Arnhem · Heide en bos · start bij de parkeerplaats aan de Harderwijkerweg',
 'desc': 'De <b>Westerheide</b> is een vlak, open heideveld in de landgoederengordel ten noorden van Arnhem, tussen Warnsborn, Vijverberg en het dorp Schaarsbergen. De naam is een overblijfsel van de tijd dat de hele noordflank van Arnhem uit gemeenschappelijke heide bestond — de westerhei van de stad, tegenhanger van de Kemperheide en de Arnhemse Heide in het oosten. In de negentiende eeuw werd de heide als <b>ontginningslandgoed</b> met productiebos beplant; de gemeente Arnhem en Geldersch Landschap &amp; Kasteelen hebben het terrein inmiddels weer opengemaakt, zodat er opnieuw een glooiend heideveld ligt, omgeven door gemengd bos met een rijke ondergroei van heesters en kruiden. Een kudde <b>Veluwse heideschapen</b> houdt het veld open. Rond het heideveld loopt de <b>Cirkelweg</b>: binnen de cirkel lag ooit de kern van het landgoed. Langs de randen kruis je een oude <b>schaapsdrift</b> tussen twee wildwallen, en op een naburig heideveldje liggen vier grafheuvels. Over de heide lopen de Westerheide-route (4 km, vanaf de Harderwijkerweg), de landgoederenwandeling en de Trage Tocht Arnhem-Schaarsbergen (11 km); het Schaarsbergenpad (klompenpad) sluit aan.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — licht over het vlakke veld.',
 'why': ['Het <b>herstelde heideveld</b> met schaapskudde in de landgoederengordel.', 'De <b>Cirkelweg</b> rond de oude kern van het ontginningslandgoed.', 'De <b>schaapsdrift en wildwallen</b> uit de heidetijd.', 'De rust van een <b>onbekend pareltje</b> tussen de Arnhemse landgoederen.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🐑 <b>Lammetjes</b> bij de kudde.', '<span class="months">Mei–Jun</span> 🐦 <b>Heidevogels</b>: boomleeuwerik en roodborsttapuit.', '<span class="months">Aug</span> 🟣 <b>Heidebloei</b> kleurt het veld paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Reeën</b> tussen heide en bosrand.'], 'wild': ['🐑 Veluws heideschaap', '🐦 Boomleeuwerik · Roodborsttapuit · Geelgors', '🦌 Ree · Das', '🦎 Levendbarende hagedis', '🌼 Struikhei · Dophei · Brem'],
 'trail': ['Start bij de <b>parkeerplaats aan de Harderwijkerweg</b>.', 'Loop de <b>Westerheide-route</b> (4 km) of de Trage Tocht Arnhem-Schaarsbergen (11 km).', 'Verbind met de landgoederen <b>Vijverberg en Warnsborn</b> of pannenkoekenhuis Den Strooper.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Schaapskudde — houd afstand · 🚶 Heide-, zand- en bospaden'
}, {
 'tags': ['Gelderland · Arnhem-Noord (Schaarsbergen)', 'Restored heath field in the estate belt · grazed by Veluwe heath sheep', 'list 36 · no. 517'],
 'loc': '📍 Between Warnsborn estate, Vijverberg and Schaarsbergen, north of Arnhem · Heath and forest · start at the car park on the Harderwijkerweg',
 'desc': 'The <b>Westerheide</b> is a flat, open heath field in the estate belt north of Arnhem, between Warnsborn, Vijverberg and the village of Schaarsbergen. The name is a relic of the time when the whole northern flank of Arnhem consisted of common heath — the city\u2019s western heath, counterpart of the Kemperheide and the Arnhemse Heide in the east. In the nineteenth century the heath was planted as a <b>reclamation estate</b> with production forest; the municipality of Arnhem and Geldersch Landschap &amp; Kasteelen have since opened the terrain up again, so that a rolling heath field once more lies there, surrounded by mixed forest with a rich undergrowth of shrubs and herbs. A flock of <b>Veluwe heath sheep</b> keeps the field open. Around the heath runs the <b>Cirkelweg</b>: inside the circle once lay the core of the estate. Along the edges you cross an old <b>sheep drift</b> between two game walls, and on a neighbouring heath plot lie four burial mounds. Across the heath run the Westerheide route (4 km, from the Harderwijkerweg), the estate walk and the Trage Tocht Arnhem-Schaarsbergen (11 km); the Schaarsbergenpad (clompenpad) links up.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather bloom)<br>\n    <b>Best time of day:</b> Morning or late afternoon — light over the flat field.',
 'why': ['The <b>restored heath field</b> with sheep flock in the estate belt.', 'The <b>Cirkelweg</b> around the old core of the reclamation estate.', 'The <b>sheep drift and game walls</b> from the heath age.', 'The peace of an <b>unknown gem</b> between the Arnhem estates.'],
 'phen': ['<span class="months">Mar–May</span> 🐑 <b>Lambs</b> with the flock.', '<span class="months">May–Jun</span> 🐦 <b>Heath birds</b>: woodlark and stonechat.', '<span class="months">Aug</span> 🟣 <b>Heather bloom</b> colours the field purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Roe deer</b> between heath and forest edge.'], 'wild': ['🐑 Veluwe heath sheep', '🐦 Woodlark · Stonechat · Yellowhammer', '🦌 Roe deer · Badger', '🦎 Viviparous lizard', '🌼 Bell heather · Cross-leaved heath · Broom'],
 'trail': ['Start at the <b>car park on the Harderwijkerweg</b>.', 'Walk the <b>Westerheide route</b> (4 km) or the Trage Tocht Arnhem-Schaarsbergen (11 km).', 'Link with the estates of <b>Vijverberg and Warnsborn</b> or pancake house Den Strooper.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Sheep flock — keep your distance · 🚶 Heath, sand and forest paths'
}))

C.append(mk.card(1799, 'Maasbergse Bossen', {
 'tags': ['Gelderland · Arnhem-Noord', 'Gemeentelijk bosgebied tussen Schaarsbergen en Warnsborn · oude jachtpalen en de Groote Kweek', 'list 36 · no. 518'],
 'loc': '📍 Ten noorden van Arnhem, tussen de Koningsweg/Schaarsbergen en landgoed Warnsborn · Gemeentebos · start bij Pannenkoekenhuis Den Strooper of de Kemperbergerweg',
 'desc': 'De <b>Maasbergse bossen</b> vormen het heuvelachtige gemeentebos van Arnhem tussen de wijk Schaarsbergen, de Koningsweg en landgoed Warnsborn, in de noordelijke bosgordel die via de landgoederen overgaat in het terrein van Deelen en de Veluwezoom. Het bos is een afwisseling van oud loofbos, naaldpercelen, lanen en open plekken, doorsneden door rustige zandpaden — de route.nl-wandeling \u2018Wandelen door de bossen boven Arnhem\u2019 start er bij Pannenkoekenhuis Den Strooper en passeert halverwege de monumentale boerderij <b>De Groote Kweek</b> uit 1900. Wie goed kijkt vindt er een curieus erfgoed: een betonnen <b>grenspaal uit 1932</b> die de scheiding tussen het Maasbergse Bos en landgoed Warnsborn markeert, en verspreid door het terrein oude jacht- en bospalen uit de tijd dat deze bossen bij de jachtbezittingen van de Arnhemse elite hoorden. Het bos ligt midden in de vrije wildbaan van de zuidelijke Veluwe: edelherten, reeën en wilde zwijnen trekken hier tussen Warnsborn, de Koningsheide en Deelen. Vlakbij liggen het Arnhems Oorlogsmuseum 40-45 (in een voormalig schoolgebouw aan de Kemperbergerweg) en de landgoederen van de Bakenbergseweg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt (herfstkleuren en zwammen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — wild en stilte in het stadbos.',
 'why': ['Het <b>rustige gemeentebos</b> tussen stad en wildbaan.', 'De <b>grenspaal uit 1932</b> en de oude jacht- en bospalen.', 'De monumentale boerderij <b>De Groote Kweek</b> uit 1900.', 'De kans op <b>edelhert, ree en wild zwijn</b> vlak bij Arnhem.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Bosanemoon</b> onder het oude loofhout.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in lanen en percelen.', '<span class="months">Sep–Okt</span> 🦌 <b>Edelherten</b> in de bronst aan de bosranden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van beuk en eik.'], 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Edelhert · Ree · Wild zwijn', '🦊 Vos · Das', '🦋 Bont zandoogje · Citroenvlinder · Dagpauwoog', '🌳 Beuk · Zomereik · Grove den'],
 'trail': ['Start bij <b>Pannenkoekenhuis Den Strooper</b> (Koningsweg, Arnhem).', 'Loop de wandeling \u2018door de bossen boven Arnhem\u2019 (12,3 km) langs De Groote Kweek.', 'Combineer met het <b>Arnhems Oorlogsmuseum 40-45</b> of landgoed Warnsborn.'],
 'foot': '🐕 Honden aangelijnd (deels losloopgebied) · 💶 Gratis · ⚠️ Blijf op de paden · wildbaan · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Arnhem-Noord', 'Municipal forest area between Schaarsbergen and Warnsborn · old hunting posts and De Groote Kweek', 'list 36 · no. 518'],
 'loc': '📍 North of Arnhem, between the Koningsweg/Schaarsbergen and Warnsborn estate · Municipal forest · start at pancake house Den Strooper or the Kemperbergerweg',
 'desc': 'The <b>Maasbergse bossen</b> form the hilly municipal forest of Arnhem between the Schaarsbergen district, the Koningsweg and Warnsborn estate, in the northern forest belt that passes via the estates into the terrain of Deelen and the Veluwezoom. The forest alternates old broadleaf wood, conifer stands, avenues and open glades, crossed by quiet sand paths — the route.nl walk \u2018Through the woods above Arnhem\u2019 starts there at pancake house Den Strooper and passes halfway the monumental farmstead <b>De Groote Kweek</b> from 1900. If you look closely you find a curious heritage: a concrete <b>boundary post from 1932</b> marking the division between the Maasbergse Bos and Warnsborn estate, and scattered over the terrain old hunting and forest posts from the time these woods belonged to the hunting grounds of the Arnhem elite. The forest lies in the middle of the free game range of the southern Veluwe: red deer, roe deer and wild boar move here between Warnsborn, the Koningsheide and Deelen. Nearby lie the Arnhem War Museum 40-45 (in a former school building on the Kemperbergerweg) and the estates of the Bakenbergseweg.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct (autumn colours and fungi)<br>\n    <b>Best time of day:</b> Morning — game and silence in the city forest.',
 'why': ['The <b>quiet municipal forest</b> between city and game range.', 'The <b>boundary post from 1932</b> and the old hunting and forest posts.', 'The monumental farmstead <b>De Groote Kweek</b> from 1900.', 'The chance of <b>red deer, roe deer and wild boar</b> close to Arnhem.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Wood anemone</b> under the old broadleaf trees.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in avenues and stands.', '<span class="months">Sep–Oct</span> 🦌 <b>Red deer</b> rutting at the forest edges.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of beech and oak.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Red deer · Roe deer · Wild boar', '🦊 Fox · Badger', '🦋 Speckled wood · Brimstone · Peacock', '🌳 Beech · Pedunculate oak · Scots pine'],
 'trail': ['Start at <b>pancake house Den Strooper</b> (Koningsweg, Arnhem).', 'Walk the route \u2018through the woods above Arnhem\u2019 (12.3 km) past De Groote Kweek.', 'Combine with the <b>Arnhem War Museum 40-45</b> or Warnsborn estate.'],
 'foot': '🐕 Dogs on lead (partly off-lead area) · 💶 Free · ⚠️ Stay on the paths · game range · 🚶 Forest and sand paths'
}))

mk.insert(C, '1794')
mk.progress(1799)
mk.check()
