# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1720, 'Breeschoten', {
 'tags': ['Gelderland · Scherpenzeel', 'Ontginningslandgoed · heideontginning met Breeschoterplas', 'list 36 · no. 439'],
 'loc': '📍 Scherpenzeel, gemeente Scherpenzeel · Landgoed · Onderdeel van Landgoed Scherpenzeel',
 'desc': '<b>Breeschoten</b> hoort sinds het einde van de negentiende eeuw bij de voormalige Heerlijkheid Scherpenzeel. De naam verwijst naar \u2019schoten\u2019, afgeleid van het Germaanse \u2019skautum\u2019: een hoger gelegen, beboste hoek zandgrond die uitspringt in een moerassig terrein. Tot begin twintigste eeuw was het een <b>moerassig heideveld</b> met kwelplaatsen; pas rond 1930 werd het laatste deel ontgonnen, waarbij naaldhout werd geplant voor het stutwerk in de kolenmijnen. In het kleinschalige landschap ligt de <b>Breeschoterplas</b>, een kwelwaterven dat in 1915 verder is uitgegraven voor de eendenjacht. Rondom liggen boerderijen met namen als Ubbeschoten, Veenschoten en Kolfschoten. Het <b>Breeschoterpad</b>, een klompenpad, voert door dit coulisselandschap.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr\u2013sep</b> (klompenpad en plas), mei\u2013jun (vogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilte bij de Breeschoterplas.',
 'why': ['De <b>Breeschoterplas</b>, een kwelwaterven uit 1915.', 'Het <b>Breeschoterpad</b> door het coulisselandschap.', 'De <b>schoten-namen</b> van het oude landschap.', 'Van moerassig heideveld tot <b>bos- en landbouwontginning</b>.'],
 'phen': ['<span class="months">Mrt\u2013Mei</span> \U0001f426 <b>Weidevogels</b> op de natte percelen.', '<span class="months">Mei\u2013Jun</span> \U0001f98b <b>Vlinders</b> langs de houtwallen.', '<span class="months">Jun\u2013Aug</span> \U0001f33c <b>Bloeiende bermen</b> langs het pad.', '<span class="months">Okt</span> \U0001f342 <b>Herfstkleur</b> in de naaldbossen.'],
 'wild': ['\U0001f426 Kievit · Grutto · Torenvalk', '\U0001f98c Ree · Haas · Egel', '\U0001f98b Dagpauwoog · Atalanta · Citroenvlinder', '\U0001f33c Zonnedauw · Klokjesgentiaan · Struikhei', '\U0001f333 Grove den · Zomereik · Berk'],
 'trail': ['Wandel het <b>Breeschoterpad</b> (klompenpad) door het landschap.', 'Start bij <b>Scherpenzeel</b> of vanaf de plas.', 'Combineer met landgoed <b>Scherpenzeel</b> en Berkhorst.'],
 'foot': '\U0001f415 Honden aangelijnd · \U0001f4b6 Gratis · \u26a0\ufe0f Natte percelen — laarzen aan · \U0001f6b6 Klompenpaden en landwegen'
}, {
 'tags': ['Gelderland · Scherpenzeel', 'Reclaimed estate · heath reclamation with the Breeschoterplas', 'list 36 · no. 439'],
 'loc': '📍 Scherpenzeel, Scherpenzeel municipality · Estate · Part of the Scherpenzeel estate',
 'desc': '<b>Breeschoten</b> has belonged to the former Lordship of Scherpenzeel since the end of the nineteenth century. The name refers to \u2019schoten\u2019, derived from the Germanic \u2019skautum\u2019: a higher, wooded corner of sandy ground jutting into marshy terrain. Until the early twentieth century it was a <b>marshy heath field</b> with seepage sites; only around 1930 was the last part reclaimed, with conifers planted for pit props in the coal mines. In the small-scale landscape lies the <b>Breeschoterplas</b>, a seepage-water fen further excavated in 1915 for duck hunting. Around it lie farms with names such as Ubbeschoten, Veenschoten and Kolfschoten. The <b>Breeschoterpad</b>, a klompenpad, leads through this hedgerow landscape.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b> (klompenpad and fen), May\u2013Jun (birds)<br>\n    <b>Best time of day:</b> Morning — quiet at the Breeschoterplas.',
 'why': ['The <b>Breeschoterplas</b>, a seepage fen of 1915.', 'The <b>Breeschoterpad</b> through the hedgerow landscape.', 'The <b>schoten names</b> of the old landscape.', 'From marshy heath to <b>forest and farmland reclamation</b>.'],
 'phen': ['<span class="months">Mar\u2013May</span> \U0001f426 <b>Meadow birds</b> on the wet plots.', '<span class="months">May\u2013Jun</span> \U0001f98b <b>Butterflies</b> along the hedge banks.', '<span class="months">Jun\u2013Aug</span> \U0001f33c <b>Flowering verges</b> along the path.', '<span class="months">Oct</span> \U0001f342 <b>Autumn colour</b> in the conifer woods.'],
 'wild': ['\U0001f426 Lapwing · Black-tailed godwit · Kestrel', '\U0001f98c Roe deer · Hare · Hedgehog', '\U0001f98b Peacock · Red admiral · Brimstone', '\U0001f33c Sundew · Marsh gentian · Heather', '\U0001f333 Scots pine · Pedunculate oak · Birch'],
 'trail': ['Walk the <b>Breeschoterpad</b> (klompenpad) through the landscape.', 'Start at <b>Scherpenzeel</b> or from the fen.', 'Combine with the <b>Scherpenzeel</b> estate and Berkhorst.'],
 'foot': '\U0001f415 Dogs on lead · \U0001f4b6 Free · \u26a0\ufe0f Wet plots — wear boots · \U0001f6b6 Klompenpaden and country lanes'
}))

C.append(mk.card(1721, 'Kasteelbos Renswoude', {
 'tags': ['Utrecht · Renswoude', 'Kasteelbos · park met grand canal en 150-jarige loofbomen', 'list 36 · no. 440'],
 'loc': '📍 Renswoude, gemeente Renswoude · Kasteelbos · ca. 60 ha',
 'desc': 'Rond <b>Kasteel Renswoude</b> — dat uit 1654 dateert op de plek waar al sinds eind veertiende eeuw het versterkte huis Borchwal stond — ligt een 60 hectare groot kasteelbos met loofbomen van meer dan 150 jaar oud. V\u00f3\u00f3r het kasteel strekt zich het <b>Grand Canal</b> uit, een rond 1700 gegraven gracht van wel 700 meter. Het park kende van oorsprong de Hollandse classicistische stijl, kreeg in 1708 de geometrische Franse barokstijl met rechte lanen, en veranderde begin negentiende eeuw in de Engelse landschapsstijl met glooiende lijnen rond de slotvijver. Bij een driesprong in het kasteelbos staan drie monumentale <b>Italiaanse bankjes</b> uit 1900. Achter het kasteel ligt een park met beuken, eiken, een vijver en een <b>duiventoren</b>. Het bos sluit aan op de Grebbelinie.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr\u2013jun</b> (grand canal en lanen), okt (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegeling in het grand canal.',
 'why': ['Het <b>Grand Canal</b> van 700 meter uit 1700.', 'Loofbomen van <b>meer dan 150 jaar</b> oud.', 'De drie <b>Italiaanse bankjes</b> (1900).', 'Aansluiting op de <b>Grebbelinie</b> en Fort Daatselaar.'],
 'phen': ['<span class="months">Apr\u2013Mei</span> \U0001f33c <b>Stinzenplanten</b> langs het grand canal.', '<span class="months">Mei\u2013Jul</span> \U0001f426 <b>Spechten</b> in de oude bomen.', '<span class="months">Mei\u2013Aug</span> \U0001f98b <b>Vlinders</b> in het park.', '<span class="months">Okt</span> \U0001f342 <b>Herfstkleur</b> in de oude lanen.'],
 'wild': ['\U0001f426 Grote bonte specht · Boomklever · Bosuil', '\U0001f98c Ree · Eekhoorn · Egel', '\U0001f98b Dagpauwoog · Citroenvlinder · Atalanta', '\U0001f33c Bosanemoon · Daslook · Wilde hyacint', '\U0001f333 Beuk · Zomereik · Haagbeuk'],
 'trail': ['Start bij de <b>Dorpsstraat</b> of aan de Grebbelounge.', 'Wandel langs het <b>Grand Canal</b> naar het kasteel.', 'Combineer met de <b>Grebbeliniedijk</b> en Fort Daatselaar.'],
 'foot': '\U0001f415 Honden aangelijnd · \U0001f4b6 Gratis · \u26a0\ufe0f Kasteel particulier — op paden · \U0001f6b6 Park- en dijkpaden'
}, {
 'tags': ['Utrecht · Renswoude', 'Castle wood · park with a grand canal and 150-year-old broadleaf trees', 'list 36 · no. 440'],
 'loc': '📍 Renswoude, Renswoude municipality · Castle wood · c. 60 ha',
 'desc': 'Around <b>Kasteel Renswoude</b> — dating from 1654 on the spot where the fortified house Borchwal had stood since the late fourteenth century — lies a 60-hectare castle wood with broadleaf trees over 150 years old. In front of the castle stretches the <b>Grand Canal</b>, a moat of no less than 700 metres dug around 1700. The park originally had the Dutch classicist style, received the geometric French baroque style with straight avenues in 1708, and changed in the early nineteenth century to the English landscape style with flowing lines around the castle pond. At a fork in the castle wood stand three monumental <b>Italian benches</b> of 1900. Behind the castle lies a park with beeches, oaks, a pond and a <b>dovecote</b>. The wood links to the Grebbelinie.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr\u2013Jun</b> (grand canal and avenues), Oct (autumn colour)<br>\n    <b>Best time of day:</b> Morning — reflections in the grand canal.',
 'why': ['The <b>Grand Canal</b> of 700 metres from 1700.', 'Broadleaf trees <b>over 150 years</b> old.', 'The three <b>Italian benches</b> (1900).', 'A link to the <b>Grebbelinie</b> and Fort Daatselaar.'],
 'phen': ['<span class="months">Apr\u2013May</span> \U0001f33c <b>Spring flora</b> along the grand canal.', '<span class="months">May\u2013Jul</span> \U0001f426 <b>Woodpeckers</b> in the old trees.', '<span class="months">May\u2013Aug</span> \U0001f98b <b>Butterflies</b> in the park.', '<span class="months">Oct</span> \U0001f342 <b>Autumn colour</b> in the old avenues.'],
 'wild': ['\U0001f426 Great spotted woodpecker · Nuthatch · Tawny owl', '\U0001f98c Roe deer · Squirrel · Hedgehog', '\U0001f98b Peacock · Brimstone · Red admiral', '\U0001f33c Wood anemone · Ramsons · Bluebell', '\U0001f333 Beech · Pedunculate oak · Hornbeam'],
 'trail': ['Start on the <b>Dorpsstraat</b> or at the Grebbelounge.', 'Walk along the <b>Grand Canal</b> to the castle.', 'Combine with the <b>Grebbeliniedijk</b> and Fort Daatselaar.'],
 'foot': '\U0001f415 Dogs on lead · \U0001f4b6 Free · \u26a0\ufe0f Castle private — on paths · \U0001f6b6 Park and dike paths'
}))

C.append(mk.card(1722, 'Grebbelinie', {
 'tags': ['Utrecht/Gelderland · Renswoude/Veenendaal', 'Waterlinie · 18e-eeuwse linie met forten en groene dijken', 'list 36 · no. 441'],
 'loc': '📍 Renswoude\u2013Veenendaal\u2013Scherpenzeel, grens Utrecht/Gelderland · Waterlinie · ruim 40 km groen erfgoed',
 'desc': 'De <b>Grebbelinie</b> is een waterlinie op de grens van Gelderland en Utrecht, aangelegd in de achttiende eeuw en meer dan 40 kilometer lang: van de Grebbeberg tot de voormalige Zuiderzee, dwars door de Gelderse Vallei. Door het lage land onder water te zetten (inundatie) werd de vijand de doorgang belet. De linie werd in 1939\u201340 onder de naam <b>Valleistelling</b> opnieuw in stelling gebracht als hoofdverdediging, waarna er in mei 1940 hevig werd gevochten. In 1951 werd de linie definitief opgeheven; sinds 1976 is het een natuurreservaat dat grotendeels door <b>Staatsbosbeheer</b> wordt beheerd, en sinds 2011 een rijksmonument. Langs de groene dijk liggen onder meer Fort aan de Buursteeg (1786, met bezoekerscentrum), Fort Daatselaar (1799), de Asschatterkade en de Post van Lambalgen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr\u2013sep</b> (groene dijken), mei\u2013jun (bloeiende velden)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilte op de liniedijk.',
 'why': ['Een <b>waterlinie</b> van ruim 40 kilometer.', 'De <b>Valleistelling</b> uit de meidagen van 1940.', 'Het <b>bezoekerscentrum</b> op Fort aan de Buursteeg.', 'Groene dijken met kazematten, vogels en bloemen.'],
 'phen': ['<span class="months">Mei\u2013Jun</span> \U0001f33c <b>Bloemrijke dijken</b> in bloei.', '<span class="months">Apr\u2013Jun</span> \U0001f426 <b>Weidevogels</b> langs de linie.', '<span class="months">Mei\u2013Aug</span> \U0001f98b <b>Vlinders</b> op de kruiden.', '<span class="months">Okt</span> \U0001f342 <b>Herfstkleur</b> op de kaden.'],
 'wild': ['\U0001f426 Buizerd · Torenvalk · Geelgors', '\U0001f98c Ree · Haas · Wezel', '\U0001f98b Dagpauwoog · Atalanta · Icarusblauwtje', '\U0001f33c Margriet · Rode klaver · Wilde peen', '\U0001f333 Zomereik · Es · Meidoorn'],
 'trail': ['Start bij het <b>Grebbelinie Bezoekerscentrum</b> (Fort aan de Buursteeg).', 'Wandel de <b>liniedijk</b> langs de forten en kazematten.', 'Combineer met <b>Kasteel Renswoude</b> en Fort Daatselaar.'],
 'foot': '\U0001f415 Honden aangelijnd · \U0001f4b6 Gratis · \u26a0\ufe0f Kazematten niet betreden · \U0001f6b6 Dijk- en graspaden'
}, {
 'tags': ['Utrecht/Gelderland · Renswoude/Veenendaal', 'Water line · 18th-century line with forts and green dikes', 'list 36 · no. 441'],
 'loc': '📍 Renswoude\u2013Veenendaal\u2013Scherpenzeel, Utrecht/Gelderland border · Water line · over 40 km of green heritage',
 'desc': 'The <b>Grebbelinie</b> is a water line on the border of Gelderland and Utrecht, laid out in the eighteenth century and over 40 kilometres long: from the Grebbeberg to the former Zuiderzee, straight through the Gelderse Vallei. By flooding the low land (inundation) the enemy\u2019s passage was blocked. The line was brought into position again in 1939\u201340 under the name <b>Valleistelling</b> as the main defence, after which heavy fighting took place in May 1940. In 1951 the line was finally abolished; since 1976 it has been a nature reserve largely managed by <b>Staatsbosbeheer</b>, and since 2011 a national monument. Along the green dike lie, among others, Fort aan de Buursteeg (1786, with visitor centre), Fort Daatselaar (1799), the Asschatterkade and the Post van Lambalgen.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr\u2013Sep</b> (green dikes), May\u2013Jun (flowering fields)<br>\n    <b>Best time of day:</b> Morning — quiet on the line dike.',
 'why': ['A <b>water line</b> of over 40 kilometres.', 'The <b>Valleistelling</b> of the May days of 1940.', 'The <b>visitor centre</b> at Fort aan de Buursteeg.', 'Green dikes with casemates, birds and flowers.'],
 'phen': ['<span class="months">May\u2013Jun</span> \U0001f33c <b>Flowering dikes</b> in bloom.', '<span class="months">Apr\u2013Jun</span> \U0001f426 <b>Meadow birds</b> along the line.', '<span class="months">May\u2013Aug</span> \U0001f98b <b>Butterflies</b> on the herbs.', '<span class="months">Oct</span> \U0001f342 <b>Autumn colour</b> on the banks.'],
 'wild': ['\U0001f426 Buzzard · Kestrel · Yellowhammer', '\U0001f98c Roe deer · Hare · Weasel', '\U0001f98b Peacock · Red admiral · Common blue', '\U0001f33c Oxeye daisy · Red clover · Wild carrot', '\U0001f333 Pedunculate oak · Ash · Hawthorn'],
 'trail': ['Start at the <b>Grebbelinie visitor centre</b> (Fort aan de Buursteeg).', 'Walk the <b>line dike</b> past the forts and casemates.', 'Combine with <b>Kasteel Renswoude</b> and Fort Daatselaar.'],
 'foot': '\U0001f415 Dogs on lead · \U0001f4b6 Free · \u26a0\ufe0f Do not enter the casemates · \U0001f6b6 Dike and grass paths'
}))

C.append(mk.card(1723, 'Hardenbroek', {
 'tags': ['Utrecht · Cothen/Langbroek', 'Ridderhofstad · kasteel aan de Langbroekerwetering', 'list 36 · no. 442'],
 'loc': '📍 Cothen, gemeente Wijk bij Duurstede · Ridderhofstad · Langbroekerdijk',
 'desc': 'Kasteel <b>Hardenbroek</b> ligt langs de historische Langbroekerwetering, in het kastelenlint tussen Cothen en Werkhoven. De naam betekent harde kleigrond op een broek (moerasland). Het kasteel is rond 1280\u20131300 gesticht door de familie Van Wulven als vierkante woontoren en werd in 1392 voor het eerst vermeld; in 1536 werd het erkend als ridderhofstad. De familie Van Hardenbroek bleef tot 1684 eigenaar. In 1762 liet <b>Johan Adolph van Hardenbroek</b> de binnenplaats overbouwen met een prestigieus gebouw met torenvormige hoekpaviljoens; de achtergevel van 1793 wordt toegeschreven aan <b>Jacob Otten Husly</b>. Het landgoed van zo\u2019n 60 hectare omvat bos, landbouwgrond en een park in Engelse landschapsstijl. Het kasteel is particulier bewoond en goed te zien vanaf de openbare weg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr\u2013jun</b> (langs de wetering), okt (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht op het kasteel.',
 'why': ['Een <b>ridderhofstad</b> uit de 13e eeuw.', 'Het 18e-eeuwse gebouw met <b>hoekpaviljoens</b>.', 'De achtergevel van <b>Jacob Otten Husly</b> (1793).', 'Onderdeel van het <b>kastelenlint</b> langs de Langbroekerwetering.'],
 'phen': ['<span class="months">Apr\u2013Mei</span> \U0001f33c <b>Stinzenplanten</b> langs de wetering.', '<span class="months">Mei\u2013Jul</span> \U0001f426 <b>IJsvogels</b> bij de grachten.', '<span class="months">Mei\u2013Aug</span> \U0001f98b <b>Vlinders</b> langs de dijk.', '<span class="months">Okt</span> \U0001f342 <b>Herfstkleur</b> in het kasteelpark.'],
 'wild': ['\U0001f426 IJsvogel · Grote bonte specht · Bosuil', '\U0001f98c Ree · Eekhoorn · Egel', '\U0001f98b Dagpauwoog · Citroenvlinder · Atalanta', '\U0001f33c Bosanemoon · Daslook · Speenkruid', '\U0001f333 Beuk · Zomereik · Linde'],
 'trail': ['Bekijk het kasteel vanaf de <b>Langbroekerdijk</b>.', 'Wandel de <b>Langbroekerwetering</b> langs de kastelen.', 'Combineer met <b>Sterkenburg</b> en Leeuwenburgh.'],
 'foot': '\U0001f415 Honden aangelijnd · \U0001f4b6 Gratis · \u26a0\ufe0f Kasteel en tuinen priv\u00e9 — vanaf de weg · \U0001f6b6 Dijk- en weteringpaden'
}, {
 'tags': ['Utrecht · Cothen/Langbroek', 'Knightly manor · castle along the Langbroekerwetering', 'list 36 · no. 442'],
 'loc': '📍 Cothen, Wijk bij Duurstede municipality · Knightly manor · Langbroekerdijk',
 'desc': 'Castle <b>Hardenbroek</b> lies along the historic Langbroekerwetering, in the castle belt between Cothen and Werkhoven. The name means hard clay soil on a broek (marshland). The castle was founded around 1280\u20131300 by the Van Wulven family as a square keep and was first mentioned in 1392; in 1536 it was recognised as a knightly manor. The Van Hardenbroek family remained owner until 1684. In 1762 <b>Johan Adolph van Hardenbroek</b> had the courtyard built over with a prestigious building with tower-shaped corner pavilions; the rear facade of 1793 is attributed to <b>Jacob Otten Husly</b>. The estate of some 60 hectares comprises woodland, farmland and a park in English landscape style. The castle is privately occupied and clearly visible from the public road.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr\u2013Jun</b> (along the wetering), Oct (autumn colour)<br>\n    <b>Best time of day:</b> Morning — light on the castle.',
 'why': ['A <b>knightly manor</b> of the 13th century.', 'The 18th-century building with <b>corner pavilions</b>.', 'The rear facade by <b>Jacob Otten Husly</b> (1793).', 'Part of the <b>castle belt</b> along the Langbroekerwetering.'],
 'phen': ['<span class="months">Apr\u2013May</span> \U0001f33c <b>Spring flora</b> along the wetering.', '<span class="months">May\u2013Jul</span> \U0001f426 <b>Kingfishers</b> at the moats.', '<span class="months">May\u2013Aug</span> \U0001f98b <b>Butterflies</b> along the dike.', '<span class="months">Oct</span> \U0001f342 <b>Autumn colour</b> in the castle park.'],
 'wild': ['\U0001f426 Kingfisher · Great spotted woodpecker · Tawny owl', '\U0001f98c Roe deer · Squirrel · Hedgehog', '\U0001f98b Peacock · Brimstone · Red admiral', '\U0001f33c Wood anemone · Ramsons · Lesser celandine', '\U0001f333 Beech · Pedunculate oak · Lime'],
 'trail': ['View the castle from the <b>Langbroekerdijk</b>.', 'Walk the <b>Langbroekerwetering</b> past the castles.', 'Combine with <b>Sterkenburg</b> and Leeuwenburgh.'],
 'foot': '\U0001f415 Dogs on lead · \U0001f4b6 Free · \u26a0\ufe0f Castle and gardens private — from the road · \U0001f6b6 Dike and wetering paths'
}))

C.append(mk.card(1724, 'Leeuwenburgh', {
 'tags': ['Utrecht · Langbroek', 'Buitenplaats · classicistisch huis met formele zichtassen', 'list 36 · no. 443'],
 'loc': '📍 Langbroek, gemeente Utrechtse Heuvelrug · Buitenplaats · Langbroekerdijk 39',
 'desc': 'Buitenplaats <b>Leeuwenburgh</b> ligt aan de Langbroekerwetering, ten westen van het dorp Langbroek. Het omgrachte, blokvormige huis werd in 1657 gebouwd door Christiaan van Vianen in opdracht van de Utrechtse patrici\u00ebr <b>Gerard Zoudenbalch</b> — en heette aanvankelijk dan ook Zoudenbalch; in 1667 doopte de nieuwe eigenaar Melchior Toussain het Leeuwenburgh. Rond 1700 liet Gideon Boudaan een park in Frans-classicistische stijl aanleggen met ronde kom en zichtassen, waarvan de structuur nog resteert. In 1859 liet <b>Pieter de Beaufort</b> het huis grotendeels herbouwen, waarbij de gracht werd gedempt tot vijver met eilandje. De houten <b>duiventoren</b> (1880) en de zichtassen op toren en boerderij zijn kenmerkend. De familie De Beaufort is nog steeds eigenaar.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr\u2013jun</b> (zichtassen en vijver), okt (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht over de zichtassen.',
 'why': ['Het huis van <b>1657</b> voor Gerard Zoudenbalch.', 'De <b>zichtassen</b> op duiventoren en boerderij.', 'De <b>duiventoren</b> van 1880.', 'Een buitenplaats in het <b>kastelenlint</b> van Langbroek.'],
 'phen': ['<span class="months">Apr\u2013Mei</span> \U0001f33c <b>Stinzenplanten</b> langs de vijver.', '<span class="months">Mei\u2013Jul</span> \U0001f426 <b>Zangvogels</b> bij de boomgaard.', '<span class="months">Mei\u2013Aug</span> \U0001f98b <b>Vlinders</b> in de moestuin.', '<span class="months">Okt</span> \U0001f342 <b>Herfstkleur</b> in het park.'],
 'wild': ['\U0001f426 Grote bonte specht · Boomklever · IJsvogel', '\U0001f98c Ree · Eekhoorn · Egel', '\U0001f98b Dagpauwoog · Citroenvlinder · Atalanta', '\U0001f33c Bosanemoon · Daslook · Speenkruid', '\U0001f333 Beuk · Zomereik · Linde'],
 'trail': ['Wandel de <b>Langbroekerdijk</b> langs de buitenplaats.', 'Volg de <b>Leeuwenburgerlaan</b> richting de wetering.', 'Combineer met <b>Hardenbroek</b> en Sterkenburg.'],
 'foot': '\U0001f415 Honden aangelijnd · \U0001f4b6 Gratis · \u26a0\ufe0f Huis particulier — op paden · \U0001f6b6 Dijk- en laanpaden'
}, {
 'tags': ['Utrecht · Langbroek', 'Country seat · classical house with formal sightlines', 'list 36 · no. 443'],
 'loc': '📍 Langbroek, Utrechtse Heuvelrug municipality · Country seat · Langbroekerdijk 39',
 'desc': 'The <b>Leeuwenburgh</b> country seat lies on the Langbroekerwetering, west of the village of Langbroek. The moated, block-shaped house was built in 1657 by Christiaan van Vianen for the Utrecht patrician <b>Gerard Zoudenbalch</b> — and was accordingly first called Zoudenbalch; in 1667 the new owner Melchior Toussain renamed it Leeuwenburgh. Around 1700 Gideon Boudaan had a park laid out in French classical style with a round basin and sightlines, the structure of which remains. In 1859 <b>Pieter de Beaufort</b> had the house largely rebuilt, the moat being filled in to form a pond with a small island. The wooden <b>dovecote</b> (1880) and the sightlines to tower and farm are characteristic. The De Beaufort family is still the owner.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr\u2013Jun</b> (sightlines and pond), Oct (autumn colour)<br>\n    <b>Best time of day:</b> Morning — light over the sightlines.',
 'why': ['The house of <b>1657</b> for Gerard Zoudenbalch.', 'The <b>sightlines</b> to dovecote and farm.', 'The <b>dovecote</b> of 1880.', 'A country seat in the <b>castle belt</b> of Langbroek.'],
 'phen': ['<span class="months">Apr\u2013May</span> \U0001f33c <b>Spring flora</b> along the pond.', '<span class="months">May\u2013Jul</span> \U0001f426 <b>Songbirds</b> at the orchard.', '<span class="months">May\u2013Aug</span> \U0001f98b <b>Butterflies</b> in the kitchen garden.', '<span class="months">Oct</span> \U0001f342 <b>Autumn colour</b> in the park.'],
 'wild': ['\U0001f426 Great spotted woodpecker · Nuthatch · Kingfisher', '\U0001f98c Roe deer · Squirrel · Hedgehog', '\U0001f98b Peacock · Brimstone · Red admiral', '\U0001f33c Wood anemone · Ramsons · Lesser celandine', '\U0001f333 Beech · Pedunculate oak · Lime'],
 'trail': ['Walk the <b>Langbroekerdijk</b> along the country seat.', 'Follow the <b>Leeuwenburgerlaan</b> towards the wetering.', 'Combine with <b>Hardenbroek</b> and Sterkenburg.'],
 'foot': '\U0001f415 Dogs on lead · \U0001f4b6 Free · \u26a0\ufe0f House private — on paths · \U0001f6b6 Dike and avenue paths'
}))

mk.insert(C, '1719')
mk.progress(1724)
mk.check()
