# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1755, 'Van der Huchtbos', {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Bos van de Kwartguldenvereniging · werkverschaffingsbos uit 1898 met monumentale banken', 'list 36 · no. 474'],
 'loc': '📍 Ten zuiden van Ugchelen, gemeente Apeldoorn · Bos · tussen De Cantharel en de A1',
 'desc': 'Het <b>Van der Huchtbos</b> ligt ten zuiden van Ugchelen, op de oostelijke flank van de Veluwe, tussen het parkbos van De Cantharel en de snelweg A1. Het bos is genoemd naar <b>Bertha Louise Wilhelmina van der Hucht</b>, voorzitster van de <b>Kwartguldenvereniging</b>: dames uit de gegoede kringen van Apeldoorn zamelden vanaf 1894 kwartguldens in en kochten er woeste heidegrond mee aan, die onder aanvoering van de anti-socialistische <b>Oranjebond van Orde</b> door werklozen als pootarbeiders werd beplant. Zo ontstond vanaf 1898 een bos dat uiteindelijk meer dan 140 hectare besloeg — werkverschaffing en natuur kwamen er in één beweging samen. Nu is het een stil, glooiend bos met oude beuken- en eikenlanen, heiderestanten en enkele vennen. Monumentale banken in het bos herinneren aan de oprichtster en aan jhr. J. Hora Siccama van de Harkstede, die de ontginning leidde en wiens naam een laan draagt; ook verzorgingsplaats De Hucht aan de A1 is naar het bos genoemd. Wandelroutes vanuit Ugchelen en rond De Cantharel voeren door dit rustige bos, waar ree en wild zwijn leven.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (bos en lanen), aug (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht in de lanen en stilte.',
 'why': ['De geschiedenis van <b>werkverschaffing en natuur</b> in één bos.', 'De monumentale <b>gedenkbanken</b> en de Hora Siccama-laan.', 'De <b>rustige lanen</b> en heiderestanten op de Veluwerand.', 'De ligging naast <b>De Kooiberg</b> en het Ugchelse bos.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Voorjaarsgroen</b> onder eiken en beuken.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het oude bos.', '<span class="months">Aug</span> 🟣 <b>Struikhei</b> bloeit op de heiderestanten.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van de lanen.'], 'wild': ['🐦 Zwarte specht · Boomklever · Grote bonte specht', '🦌 Ree · Wild zwijn · Eekhoorn', '🦋 Bont zandoogje · Citroenvlinder · Atalanta', '🌼 Struikhei · Blauwe bosbes · Bosanemoon', '🌳 Beuk · Zomereik · Grove den'],
 'trail': ['Start in <b>Ugchelen</b> en wandel via de Hoog Buurloseweg het bos in.', 'Combineer met het <b>Rondje De Kooiberg</b> van IVN Apeldoorn.', 'Parkeren kan onder meer bij <b>De Cantharel</b> of aan de rand van Ugchelen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Rustig bos — blijf op de paden · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Forest of the Quarter-Guilder Society · 1898 relief-work wood with memorial benches', 'list 36 · no. 474'],
 'loc': '📍 South of Ugchelen, Apeldoorn municipality · Woodland · between De Cantharel and the A1 motorway',
 'desc': 'The <b>Van der Huchtbos</b> lies south of Ugchelen, on the eastern flank of the Veluwe, between the park wood of De Cantharel and the A1 motorway. The forest is named after <b>Bertha Louise Wilhelmina van der Hucht</b>, chairwoman of the <b>Kwartguldenvereniging</b> (Quarter-Guilder Society): ladies from the better circles of Apeldoorn collected quarter-guilder coins from 1894 onwards and bought barren heath land with them, which was then planted by unemployed men as tree planters under the leadership of the anti-socialist <b>Oranjebond van Orde</b>. From 1898 this grew into a forest of ultimately more than 140 hectares — relief work and nature came together in a single movement. Today it is a quiet, rolling wood with old beech and oak avenues, heath remnants and a few pools. Monumental benches in the forest commemorate the founder and Jonkheer J. Hora Siccama van de Harkstede, who led the reclamation and whose name an avenue bears; the motorway service area De Hucht on the A1 is also named after the forest. Walking routes from Ugchelen and around De Cantharel lead through this quiet wood, home to roe deer and wild boar.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (woodland and avenues), Aug (heather bloom)<br>\n    <b>Best time of day:</b> Morning — light in the avenues and silence.',
 'why': ['The story of <b>relief work and nature</b> in one forest.', 'The monumental <b>memorial benches</b> and the Hora Siccama avenue.', 'The <b>quiet avenues</b> and heath remnants on the Veluwe edge.', 'The location next to <b>De Kooiberg</b> and the Ugchelen woods.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Spring greenery</b> under oaks and beeches.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old forest.', '<span class="months">Aug</span> 🟣 <b>Bell heather</b> blooms on the heath remnants.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of the avenues.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Great spotted woodpecker', '🦌 Roe deer · Wild boar · Squirrel', '🦋 Speckled wood · Brimstone · Red admiral', '🌼 Bell heather · Bilberry · Wood anemone', '🌳 Beech · Pedunculate oak · Scots pine'],
 'trail': ['Start in <b>Ugchelen</b> and walk into the forest via the Hoog Buurloseweg.', 'Combine with the <b>Rondje De Kooiberg</b> walk of IVN Apeldoorn.', 'Park, among other places, at <b>De Cantharel</b> or on the edge of Ugchelen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Quiet forest — stay on the paths · 🚶 Forest and sand paths'
}))

C.append(mk.card(1756, 'De Kooiberg', {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Heuvel en landgoedbos in een smeltwaterdal · NTKC-terrein op de oostflank van de Veluwe', 'list 36 · no. 475'],
 'loc': '📍 Oostflank van de Veluwe bij Ugchelen, gemeente Apeldoorn · Bos en kampeerterrein · in een ijstijd-smeltwaterdal',
 'desc': '<b>De Kooiberg</b> is een heuvel en landgoedbos aan de oostflank van de Veluwe bij Ugchelen, verstopt in een <b>smeltwaterdal</b> uit de voorlaatste ijstijd: oprukkende ijstongen stuwden de bodem hier op tot een stuwwal en het smeltwater sneed er diepe dalen in. De sterk glooiende hellingen zijn begroeid met een afwisselend bos van grove den, zomereik en beuk, met blauwe bosbes en struikhei in de ondergroei; op de hogere delen heb je uitzicht over de Ugchelse Enk en Apeldoorn. Het bosgebied hoort bij de boswachterij Ugchelen van Staatsbosbeheer en wordt natuurvolgend beheerd, met ruimte voor dood hout en voor grofwild als edelhert, ree en wild zwijn. Midden op het terrein ligt het kampeerterrein van de <b>NTKC</b>, dat hier al sinds omstreeks 1945 huist en waarvan het veld van oudsher <b>Johnnies land</b> heet. IVN Apeldoorn heeft het gemarkeerde <b>Rondje De Kooiberg</b> uitgezet over dit natuurrijk beheerde bos; de paden sluiten aan op het wandelnetwerk rond Ugchelen, met informatiecentrum ’t Leesten en de Ugchelse bossen binnen handbereik.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (bos en dal), aug (heide)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht en vogelzang in het dal.',
 'why': ['Het <b>smeltwaterdal</b> uit de ijstijd in de stuwwal.', 'Het <b>glooiende, wildrijke bos</b> van de boswachterij Ugchelen.', 'De historische kampeerplek van de <b>NTKC</b> (“Johnnies land”).', 'Het <b>uitzicht</b> over de Ugchelse Enk en Apeldoorn.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> en voorjaarsgroen op de hellingen.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het gevarieerde bos.', '<span class="months">Aug</span> 🟣 <b>Struikhei</b> bloeit op de open plekken.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de omgeving.'], 'wild': ['🐦 Zwarte specht · Boomklever · Kuifmees', '🦌 Edelhert · Ree · Wild zwijn', '🦋 Bont zandoogje · Citroenvlinder · Kleine vos', '🌼 Blauwe bosbes · Struikhei · Lelietje-van-dalen', '🌳 Grove den · Zomereik · Beuk'],
 'trail': ['Volg het <b>Rondje De Kooiberg</b> (IVN Apeldoorn) door bos en dal.', 'Start in <b>Ugchelen</b> of bij informatiecentrum ’t Leesten.', 'Combineer met het <b>Van der Huchtbos</b> en de Ugchelse Enk.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Kampeerterrein is privéterrein · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Hill and estate wood in a meltwater valley · NTKC terrain on the eastern flank of the Veluwe', 'list 36 · no. 475'],
 'loc': '📍 Eastern flank of the Veluwe near Ugchelen, Apeldoorn municipality · Woodland and campsite · in an ice-age meltwater valley',
 'desc': '<b>De Kooiberg</b> is a hill and estate wood on the eastern flank of the Veluwe near Ugchelen, hidden in a <b>meltwater valley</b> from the penultimate ice age: advancing ice tongues pushed the ground up into a push moraine and the meltwater cut deep valleys into it. The strongly undulating slopes carry a mixed wood of Scots pine, pedunculate oak and beech, with bilberry and bell heather in the undergrowth; from the higher parts you look out over the Ugchelse Enk and Apeldoorn. The wooded area belongs to the Ugchelen forest district of Staatsbosbeheer and is managed nature-oriented, with room for dead wood and for large game such as red deer, roe deer and wild boar. In the middle of the terrain lies the campsite of the <b>NTKC</b>, which has been here since about 1945 and whose field is traditionally called <b>Johnnies land</b>. IVN Apeldoorn has marked the <b>Rondje De Kooiberg</b> walk across this nature-rich forest; the paths link up with the walking network around Ugchelen, with the ’t Leesten information centre and the Ugchelen woods within reach.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (woodland and valley), Aug (heather)<br>\n    <b>Best time of day:</b> Morning — light and birdsong in the valley.',
 'why': ['The <b>meltwater valley</b> from the ice age in the push moraine.', 'The <b>rolling, game-rich forest</b> of the Ugchelen forest district.', 'The historic campsite of the <b>NTKC</b> (“Johnnies land”).', 'The <b>view</b> over the Ugchelse Enk and Apeldoorn.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> and spring greenery on the slopes.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the varied forest.', '<span class="months">Aug</span> 🟣 <b>Bell heather</b> blooms in the glades.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the surroundings.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Crested tit', '🦌 Red deer · Roe deer · Wild boar', '🦋 Speckled wood · Brimstone · Small tortoiseshell', '🌼 Bilberry · Bell heather · Lily of the valley', '🌳 Scots pine · Pedunculate oak · Beech'],
 'trail': ['Follow the <b>Rondje De Kooiberg</b> (IVN Apeldoorn) through wood and valley.', 'Start in <b>Ugchelen</b> or at the ’t Leesten information centre.', 'Combine with the <b>Van der Huchtbos</b> and the Ugchelse Enk.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The campsite is private property · 🚶 Forest and sand paths'
}))

C.append(mk.card(1757, 'Bruggelen', {
 'tags': ['Gelderland · Beekbergen/Apeldoorn', 'Landgoedbos van GLK · Noorse huisjes en een park met exotische bomen', 'list 36 · no. 476'],
 'loc': '📍 Tussen Beekbergen en Engelanderholt, gemeente Apeldoorn · Landgoed en bos · aan de westrand van Beekbergen',
 'desc': '<b>Bruggelen</b> is een landgoed aan de westrand van Beekbergen, ingeklemd tussen het dorp, de Engelanderholt en de bossen van de Veluwe. Het glooiende bos- en parklandschap kwam in de late jaren veertig uit de familie van Dr. J. Ooster in handen van <b>Geldersch Landschap &amp; Kasteelen</b> en bestaat uit afwisselend naald- en loofbos, weilanden, een parkbos rond het huis en enkele heideveldjes. In het bos staan twee karakteristieke <b>Noorse huizen</b>, ooit als bouwpakket gekocht bij Strømmen Trævarefabrik bij Oslo; rond het huis ligt een park met vijftig tot zestig <b>exotische bomen</b>, waaronder monumentale mammoetbomen. Met de Noorse huizen kwamen ook bijzondere mossen mee — onder meer het zeldzame priembladmos en breed moerasvorkje — die in de graslanden rond de huisjes nog altijd groeien. Het bos wordt natuurvolgend beheerd en herbergt onder meer twee dassenburchten. Vanaf de parkeerplaats aan de Engelanderholt voert de oranje wandelroute van <b>Geldersch Landschap</b> (circa 7,5 km) door het landgoed; de Trage Tocht en het Veluws Zwerfpad lopen erlangs.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (bos en park), apr–mei (voorjaarsflora)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilte in het glooiende bos.',
 'why': ['De <b>Noorse bouwpakket-huizen</b> midden in het bos.', 'Het park met <b>exotische bomen</b> en mammoetbomen.', 'De zeldzame <b>Scandinavische mossen</b> rond de huisjes.', 'De <b>natuurvolgend beheerde bossen</b> met dassen en dood hout.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Stinzenflora</b> en voorjaarsgroen in het park.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het oude bos.', '<span class="months">Sep–Okt</span> 🦡 <b>Dassen</b> actief rond de burchten in de schemering.', '<span class="months">Okt–Nov</span> 🍄 <b>Paddenstoelen</b> in het doodhoutrijke bos.'], 'wild': ['🐦 Zwarte specht · Boomklever · Gekraagde roodstaart', '🦡 Das · Ree · Eekhoorn', '🦋 Bont zandoogje · Citroenvlinder · Dagpauwoog', '🌼 Bosanemoon · Dalkruid · Daslook', '🌳 Mammoetboom · Beuk · Zomereik'],
 'trail': ['Parkeer aan de <b>Engelanderholt</b> en volg de oranje route van GLK (7,5 km).', 'Verken het <b>parkbos</b> rond het huis over de korte veldpaden.', 'Combineer met het <b>Beekberger bos</b> of Kasteel Spelderholt.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Privéterrein rond het huis respecteren · 🚶 Bos- en graspaden'
}, {
 'tags': ['Gelderland · Beekbergen/Apeldoorn', 'Estate wood of Geldersch Landschap · Norwegian houses and a park with exotic trees', 'list 36 · no. 476'],
 'loc': '📍 Between Beekbergen and Engelanderholt, Apeldoorn municipality · Estate and woodland · on the western edge of Beekbergen',
 'desc': '<b>Bruggelen</b> is an estate on the western edge of Beekbergen, wedged between the village, the Engelanderholt and the forests of the Veluwe. The rolling wooded and park landscape came into the hands of <b>Geldersch Landschap &amp; Kasteelen</b> in the late 1940s from the family of Dr J. Ooster, and consists of alternating conifer and broadleaf woodland, meadows, a park wood around the house and a few heath fields. In the forest stand two characteristic <b>Norwegian houses</b>, once bought as build-it-yourself kits from Strømmen Trævarefabrik near Oslo; around the house lies a park with fifty to sixty <b>exotic trees</b>, including monumental giant sequoias. The Norwegian houses also brought special mosses with them — among them the rare pincushion moss (priembladmos) and broad-leaved hook-moss — which still grow in the grasslands around the houses. The forest is managed nature-oriented and shelters, among other things, two badger setts. From the car park on the Engelanderholt the orange walking route of <b>Geldersch Landschap</b> (about 7.5 km) leads through the estate; the Trage Tocht and the Veluwe Zwerfpad pass along it.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (woodland and park), Apr–May (spring flora)<br>\n    <b>Best time of day:</b> Morning — silence in the rolling forest.',
 'why': ['The <b>Norwegian kit houses</b> in the middle of the forest.', 'The park with <b>exotic trees</b> and giant sequoias.', 'The rare <b>Scandinavian mosses</b> around the houses.', 'The <b>nature-oriented forests</b> with badgers and dead wood.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Garden-escape flora</b> and spring greenery in the park.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old forest.', '<span class="months">Sep–Oct</span> 🦡 <b>Badgers</b> active around the setts at dusk.', '<span class="months">Oct–Nov</span> 🍄 <b>Fungi</b> in the dead-wood-rich forest.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Common redstart', '🦡 Badger · Roe deer · Squirrel', '🦋 Speckled wood · Brimstone · Peacock', '🌼 Wood anemone · May lily · Wild garlic', '🌳 Giant sequoia · Beech · Pedunculate oak'],
 'trail': ['Park on the <b>Engelanderholt</b> and follow the orange GLK route (7.5 km).', 'Explore the <b>park wood</b> around the house on the short field paths.', 'Combine with the <b>Beekberger bos</b> or Kasteel Spelderholt.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Respect the private grounds around the house · 🚶 Forest and grass paths'
}))

C.append(mk.card(1758, 'Oosterbos', {
 'tags': ['Gelderland · Barneveld', 'Klein wandelbos met eiken- en beukenlanen · poel waar honden mogen zwemmen', 'list 36 · no. 477'],
 'loc': '📍 Aan de oostrand van het centrum van Barneveld · Wandelbos · tussen de wijken en de Barneveldse Beek',
 'desc': 'Het <b>Oosterbos</b> is het kleine wandelbos van Barneveld, pal ten oosten van het centrum. Het parkbos ligt er rustig bij en is geliefd bij omwonenden die er hun rondje lopen of de hond uitlaten: kaarsrechte <b>lanen met eiken en beuken</b> aan weerszijden wisselen af met slingerende graspaden. In het midden van het bos ligt een <b>poel</b>, omzoomd door bomen, waar eenden dobberen en waar honden in de zomer een duik mogen nemen — een van de weinige plekken in de omgeving waar dat mag. Het bos is klein maar fijn: bankjes, vogelzang en in de herfst prachtige kleuren, zonder dat je de stad uit hoeft. Wandelroutes langs de Barneveldse beken, zoals de rondwandeling <b>Barneveldse Bossen &amp; Beken</b>, doen het park aan tussen kasteel De Schaffelaar en de Esvelderbeek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, okt (herfstkleuren)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — rustig en veel vogelzang.',
 'why': ['Een <b>dichtbijzijnd wandelbos</b> midden in Barneveld.', 'De <b>lanen met eiken en beuken</b> rond de centrale poel.', 'De <b>hondenpoel</b> waar viervoeters mogen zwemmen.', 'De combinatie met de <b>routes langs de Barneveldse beken</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Speenkruid</b> en bosanemoon onder de bomen.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> in de boomkronen.', '<span class="months">Jun–Aug</span> 🦟 <b>Libellen</b> en kikkers bij de poel.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van eiken en beuken.'], 'wild': ['🐦 Koolmees · Merel · Grote bonte specht', '🐿️ Eekhoorn · Egel · Huismus', '🦋 Dagpauwoog · Citroenvlinder · Atalanta', '🌼 Bosanemoon · Speenkruid · Fluitenkruid', '🌳 Zomereik · Beuk · Gewone esdoorn'],
 'trail': ['Start bij de <b>oostrand van het centrum</b> van Barneveld en loop het parkbos in.', 'Maak het <b>rondje om de poel</b> over de slingerpaden.', 'Combineer met <b>De Schaffelaar</b> en de Barneveldse Beek.'],
 'foot': '🐕 Honden aangelijnd, los zwemmen mag in de poel · 💶 Gratis · ⚠️ Stadspark — rust en netheid · 🚶 Verharde en graspaden'
}, {
 'tags': ['Gelderland · Barneveld', 'Small walking wood with oak and beech avenues · pond where dogs may swim', 'list 36 · no. 477'],
 'loc': '📍 On the eastern edge of the centre of Barneveld · Walking wood · between the districts and the Barneveldse Beek',
 'desc': 'The <b>Oosterbos</b> is the little walking wood of Barneveld, just east of the centre. The park wood lies quiet and is popular with local residents who do their rounds here or walk the dog: straight <b>avenues with oaks and beeches</b> on both sides alternate with winding grass paths. In the middle of the wood lies a <b>pond</b>, lined with trees, where ducks bob and where dogs may take a dip in summer — one of the few places in the area where that is allowed. The wood is small but fine: benches, birdsong and, in autumn, wonderful colours, without leaving the town. Walking routes along the Barneveld brooks, such as the <b>Barneveldse Bossen &amp; Beken</b> circuit, pass through the park between Kasteel De Schaffelaar and the Esvelderbeek.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Oct (autumn colours)<br>\n    <b>Best time of day:</b> Early morning — quiet and full of birdsong.',
 'why': ['A <b>walking wood nearby</b> in the middle of Barneveld.', 'The <b>avenues with oaks and beeches</b> around the central pond.', 'The <b>dog pond</b> where four-legged friends may swim.', 'The combination with the <b>routes along the Barneveld brooks</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Lesser celandine</b> and wood anemone under the trees.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> in the tree crowns.', '<span class="months">Jun–Aug</span> 🦟 <b>Dragonflies</b> and frogs at the pond.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of oaks and beeches.'], 'wild': ['🐦 Great tit · Blackbird · Great spotted woodpecker', '🐿️ Squirrel · Hedgehog · House sparrow', '🦋 Peacock · Brimstone · Red admiral', '🌼 Wood anemone · Lesser celandine · Cow parsley', '🌳 Pedunculate oak · Beech · Sycamore'],
 'trail': ['Start at the <b>eastern edge of the centre</b> of Barneveld and walk into the park wood.', 'Make the <b>round of the pond</b> on the winding paths.', 'Combine with <b>De Schaffelaar</b> and the Barneveldse Beek.'],
 'foot': '🐕 Dogs on lead; free swimming allowed in the pond · 💶 Free · ⚠️ Town park — quiet and clean · 🚶 Paved and grass paths'
}))

C.append(mk.card(1759, 'Schaffelaar', {
 'tags': ['Gelderland · Barneveld', 'Kasteel en landgoed met sterrenbos · WOII-verblijf voor de Barneveldgroep en Joods monument', 'list 36 · no. 478'],
 'loc': '📍 Aan de rand van het centrum van Barneveld · Kasteel en landgoed · op loopafstand van station Barneveld Centrum',
 'desc': 'Het <b>landgoed De Schaffelaar</b> ligt direct aan de rand van het centrum van Barneveld, op loopafstand van het station. Het is het mooiste wandelgebied van de pluimveestad: een aangelegd parkbos met vijvers, kronkelende waterlopen, oude lanen en een <b>sterrenbos</b> waarin veertien lanen in één punt samenkomen. Rond de met een gracht omgeven <b>Koewei</b>, een grote weide midden in het landgoed, en het in het midden van de negentiende eeuw in neotudorstijl opgetrokken <b>Kasteel De Schaffelaar</b> — al in de zestiende eeuw stond hier een adellijk huis — is het heerlijk wandelen. Het landgoed heeft een beladen geschiedenis: van 1942 tot 1943 diende het kasteel als verblijf voor de <b>Barneveldgroep</b>, zo’n zeshonderd Joden met een bijzondere status die via kamp Westerbork uiteindelijk naar Theresienstadt werden gedeporteerd; een monument van vormgever <b>Ralph Prins</b> herdenkt hen. Het sierlijke, deels vergulde <b>gietijzeren toegangshek</b> aan de Stationsweg geldt als een van de honderd mooiste hekken van Nederland. Vanaf station Barneveld Centrum loopt het gemarkeerde <b>Rondje De Schaffelaar</b> over het landgoed.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (park en vijvers), okt (herfstkleuren)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig en mooi licht over de vijvers.',
 'why': ['Het <b>parkbos met sterrenbos</b>, vijvers en de gracht rond de Koewei.', 'Het <b>neotudor-kasteel</b> en het sierlijke gietijzeren hek.', 'De indrukwekkende <b>WOII-geschiedenis</b> van de Barneveldgroep.', 'Het <b>Rondje De Schaffelaar</b> vanaf het station.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Sneeuwklokjes</b> en narcissen in het park.', '<span class="months">Mei–Jun</span> 🐦 <b>Parkvogels</b> rond vijvers en lanen.', '<span class="months">Jun–Aug</span> 🦆 <b>Waterhoen</b> en eenden met jongen.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van de veertien lanen.'], 'wild': ['🐦 Grote bonte specht · Boomklever · Halsbandparkiet', '🐿️ Eekhoorn · Egel · Vos (schemering)', '🦋 Dagpauwoog · Klein geaderd witje · Oranjetipje', '🌼 Sneeuwklokje · Bosanemoon · Holwortel', '🌳 Beuk · Zomereik · Linde'],
 'trail': ['Start bij <b>station Barneveld Centrum</b> en volg het Rondje De Schaffelaar.', 'Wandel om de <b>Koewei</b> en door het sterrenbos.', 'Combineer met het <b>Oosterbos</b> of het Pluimveemuseum.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Respecteer de rust rond het kasteel · 🚶 Park-, bos- en veldpaden'
}, {
 'tags': ['Gelderland · Barneveld', 'Castle and estate with star-shaped wood · WWII home of the Barneveld group and Jewish monument', 'list 36 · no. 478'],
 'loc': '📍 On the edge of the centre of Barneveld · Castle and estate · within walking distance of Barneveld Centrum station',
 'desc': 'The <b>De Schaffelaar estate</b> lies right on the edge of the centre of Barneveld, within walking distance of the station. It is the finest walking area of the poultry town: a landscaped park wood with ponds, winding watercourses, old avenues and a <b>star-shaped wood</b> in which fourteen avenues converge on a single point. Around the moat-ringed <b>Koewei</b>, a large meadow in the middle of the estate, and the <b>Kasteel De Schaffelaar</b>, built in the neo-Tudor style in the mid-nineteenth century — a noble house already stood here in the sixteenth century — it is wonderful to walk. The estate has a painful history: from 1942 to 1943 the castle served as the home of the <b>Barneveld group</b>, some six hundred Jews with a special status who were ultimately deported via Camp Westerbork to Theresienstadt; a monument by designer <b>Ralph Prins</b> commemorates them. The graceful, partly gilded <b>cast-iron entrance gate</b> on the Stationsweg counts as one of the hundred most beautiful gates of the Netherlands. From Barneveld Centrum station the marked <b>Rondje De Schaffelaar</b> runs over the estate.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (park and ponds), Oct (autumn colours)<br>\n    <b>Best time of day:</b> Morning — quiet, with lovely light over the ponds.',
 'why': ['The <b>park wood with star-shaped wood</b>, ponds and the moat around the Koewei.', 'The <b>neo-Tudor castle</b> and the graceful cast-iron gate.', 'The moving <b>Second World War history</b> of the Barneveld group.', 'The <b>Rondje De Schaffelaar</b> from the station.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Snowdrops</b> and daffodils in the park.', '<span class="months">May–Jun</span> 🐦 <b>Park birds</b> around ponds and avenues.', '<span class="months">Jun–Aug</span> 🦆 <b>Moorhen</b> and ducks with young.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of the fourteen avenues.'], 'wild': ['🐦 Great spotted woodpecker · Nuthatch · Ring-necked parakeet', '🐿️ Squirrel · Hedgehog · Fox (dusk)', '🦋 Peacock · Green-veined white · Orange tip', '🌼 Snowdrop · Wood anemone · Hollowroot', '🌳 Beech · Pedunculate oak · Lime'],
 'trail': ['Start at <b>Barneveld Centrum station</b> and follow the Rondje De Schaffelaar.', 'Walk round the <b>Koewei</b> and through the star-shaped wood.', 'Combine with the <b>Oosterbos</b> or the Poultry Museum.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Respect the quiet around the castle · 🚶 Park, wood and field paths'
}))

mk.insert(C, '1754')
mk.progress(1759)
mk.check()
