# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1780, 'Delerwoud', {
 'tags': ['Gelderland · Deelen/Kootwijk', 'Stiltegebied van Natuurmonumenten (2.380 ha) · tussen de grote heidevelden van de Veluwe', 'list 36 · no. 499'],
 'loc': '📍 Ten oosten van de A50, tussen Deelen en Kootwijk · Bos, heide en stuifzand · start bij P Deelen of het Deelerwoud (Delenseweg, Deelen)',
 'desc': 'Het <b>Deelerwoud</b> is met 2.380 hectare een van de grootste stiltegebieden van de Veluwe en ligt tussen de Ginkelse Heide en de Hoge Veluwe in, ten oosten van de A50. Natuurmonumenten verwierf het na de succesvolle actie \u2018Behoud het Deelerwoud\u2019 in 1967 en beheert het sindsdien als rustgebied voor groot wild. Het landschap is weids: de Grote Heide en Kleine Heide met daaromheen bossen, de Bruine Berg en het Aalderinksveld. De wandelroute met groene paaltjes (8–9 km) start bij de parkeerplaats van het Deelerwoud aan de Delenseweg en voert langs heide, vennen en coulissen; ook de Schotse hooglanders van de Ginkelse Heide grazen soms in het Deelerwoud. Het terrein is in de nazomer het domein van <b>edelherten in bronst</b>: het burlen klinkt er van half september tot half oktober, als delen van het gebied \u2019s nachts gesloten zijn. Ook reeën, wilde zwijnen en das zitten er, naast vogels als nachtzwaluw, raaf en wespendief. Omdat het een rustgebied is, geldt: blijven op wegen en paden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — wild in de rustzones.',
 'why': ['De <b>stilte en ruimte</b> van een van de grootste rustgebieden van de Veluwe.', 'De <b>grote heidevelden</b> met in de nazomer de bronst van edelherten.', 'De <b>vrij toegankelijke wandelroute</b> met groene paaltjes.', 'De bijzondere <b>heide- en bosvogels</b> in een stil bos.'],
 'phen': ['<span class="months">Jun–Aug</span> 🐦 <b>Nachtzwaluw</b> en raaf boven heide en bos.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op Grote en Kleine Heide.', '<span class="months">Sep 15–Okt 15</span> 🦌 <b>Bronst</b>: burlende edelherten, delen ’s nachts gesloten.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in de bossen.'], 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐄 Schotse hooglander (dwaalgast)', '🐦 Nachtzwaluw · Raaf · Wespendief', '🦎 Hazelworm · Levendbarende hagedis', '🌼 Struikhei · Dophei · Klokjesgentiaan'],
 'trail': ['Start bij de <b>parkeerplaats Deelerwoud</b> (Delenseweg, Deelen).', 'Volg de <b>groene paaltjes</b> (8–9 km) over heide en door bos.', 'Loop het <b>rode rondje</b> (7,2 km) vanaf de parkeerplaats bij Deelen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (parkeren o.b.v. parkeerrecht) · ⚠️ Rustgebied voor wild · tijdens bronst delen gesloten · 🚶 Zand-, heide- en bospaden'
}, {
 'tags': ['Gelderland · Deelen/Kootwijk', 'Silence area of Natuurmonumenten (2,380 ha) · between the great heath fields of the Veluwe', 'list 36 · no. 499'],
 'loc': '📍 East of the A50, between Deelen and Kootwijk · Forest, heath and drift sand · start at P Deelen or Deelerwoud (Delenseweg, Deelen)',
 'desc': 'The <b>Deelerwoud</b> is, at 2,380 hectares, one of the largest silence areas of the Veluwe and lies between the Ginkelse Heide and De Hoge Veluwe, east of the A50. Natuurmonumenten acquired it after the successful \u2018Behoud het Deelerwoud\u2019 campaign in 1967 and has since managed it as a rest area for large game. The landscape is sweeping: the Grote Heide and Kleine Heide surrounded by forest, the Bruine Berg and the Aalderinksveld. The walking route with green posts (8–9 km) starts at the Deelerwoud car park on the Delenseweg and leads along heath, pools and woodland edges; the Scottish Highland cattle of the Ginkelse Heide sometimes also graze in the Deelerwoud. In late summer the terrain belongs to <b>rutting red deer</b>: the belling sounds from mid-September to mid-October, when parts of the area are closed at night. Roe deer, wild boar and badger also occur, alongside birds such as nightjar, raven and honey buzzard. Because it is a rest area, the rule is: stay on roads and paths.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or late afternoon — game in the rest zones.',
 'why': ['The <b>silence and space</b> of one of the largest rest areas of the Veluwe.', 'The <b>great heath fields</b> with the red deer rut in late summer.', 'The <b>freely accessible walking route</b> with green posts.', 'The special <b>heath and forest birds</b> in a silent forest.'],
 'phen': ['<span class="months">Jun–Aug</span> 🐦 <b>Nightjar</b> and raven above heath and forest.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on Grote and Kleine Heide.', '<span class="months">Sep 15–Oct 15</span> 🦌 <b>Rutting</b>: belling red deer, parts closed at night.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the forests.'], 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐄 Scottish Highland cattle (stray visitor)', '🐦 Nightjar · Raven · Honey buzzard', '🦎 Slow worm · Viviparous lizard', '🌼 Bell heather · Cross-leaved heath · Gentianella'],
 'trail': ['Start at the <b>Deelerwoud car park</b> (Delenseweg, Deelen).', 'Follow the <b>green posts</b> (8–9 km) over heath and through forest.', 'Walk the <b>red circuit</b> (7.2 km) from the car park near Deelen.'],
 'foot': '🐕 Dogs on lead · 💶 Free (parking by parking permit) · ⚠️ Game rest area · parts closed during the rut · 🚶 Sand, heath and forest paths'
}))

C.append(mk.card(1781, 'Loenermark en Loenense Bos', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Grootste terrein van Geldersch Landschap &amp; Kasteelen · heide, stuifduinen en het oude Loenense Bos', 'list 36 · no. 500'],
 'loc': '📍 Ten noorden van Loenen op de Veluwe · Heide, oude stuifduinen en bos · start bij P Droefakkers of de schaapskooi van GLK',
 'desc': 'De <b>Loenermark</b> en het <b>Loenense Bos</b> vormen samen het grootste terrein van Geldersch Landschap &amp; Kasteelen, ingeklemd tussen de snelwegen A50 en A1. De Loenermark is een groot heide- en stuifzandterrein met jeneverbesstruwelen en oude stuifduinen, omringd door het oude <b>Loenense Bos</b> — een van de oudste bossen van Nederland, dat al in de vroege middeleeuwen werd genoemd. Vanaf de schaapskooi van GLK bij Droefakkers laat een herder van april tot december de kudde Veluwse heideschapen over de heide grazen, die zo open blijft. Bij de schaapskooi starten vier gemarkeerde wandelroutes van 2,5 tot 13,5 kilometer (groen, geel, oranje en paars) over heide, stuifduinen en door het bos, met hier en daar een zwerfkei als herkenningspunt. In de bronst — september en oktober — klinkt het burlen van edelherten over de open vlakten; reeën, wilde zwijnen, das en boommarter zitten er ook.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — heide in het laagste licht.',
 'why': ['Het <b>grootste terrein van GLK</b> met heide, jeneverbes en stuifduinen.', 'De <b>schaapskudde</b> die van april tot december met de herder op de hei graast.', 'Het <b>Loenense Bos</b>, een van de oudste bossen van Nederland.', 'De <b>gemarkeerde routes</b> van 2,5 tot 13,5 km vanaf de schaapskooi.'],
 'phen': ['<span class="months">Apr–Dec</span> 🐑 <b>Heideschapen</b> met herder op de Loenermark.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> en jeneverbessen.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten over de vlakten.', '<span class="months">Okt</span> 🍄 <b>Paddenstoelen</b> in het oude Loenense Bos.'], 'wild': ['🐑 Veluws heideschaap', '🦌 Edelhert · Ree · Wild zwijn', '🐦 Zwarte specht · Boomleeuwerik · Roodborsttapuit', '🦎 Zandhagedis · Levendbarende hagedis', '🌼 Struikhei · Jeneverbes · Kraaihei'],
 'trail': ['Parkeer bij <b>Droefakkers</b> aan de Zilvenseweg in Loenen.', 'Start aan de <b>schaapskooi</b> en kies een van de vier gemarkeerde routes.', 'Volg de paarse route (13,5 km) voor heide én oud bos.'],
 'foot': '🐕 Honden aangelijnd (losloopgebieden aangegeven) · 💶 Gratis · ⚠️ Rustgebied · blijf op de paden · 🚶 Heide-, duin- en bospaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Largest terrain of Geldersch Landschap &amp; Kasteelen · heath, drift dunes and the ancient Loenense Bos', 'list 36 · no. 500'],
 'loc': '📍 North of Loenen on the Veluwe · Heath, old drift dunes and forest · start at P Droefakkers or the GLK sheep fold',
 'desc': 'The <b>Loenermark</b> and the <b>Loenense Bos</b> together form the largest terrain of Geldersch Landschap &amp; Kasteelen, wedged between the A50 and A1 motorways. The Loenermark is a large heath and drift-sand terrain with juniper scrub and old drift dunes, surrounded by the ancient <b>Loenense Bos</b> — one of the oldest forests of the Netherlands, already mentioned in the early Middle Ages. From the GLK sheep fold near Droefakkers, a shepherd lets the flock of Veluwe heath sheep graze the heath from April to December, keeping it open. Four marked walking routes of 2.5 to 13.5 kilometres (green, yellow, orange and purple) start at the fold, over heath, drift dunes and through the forest, with the occasional erratic boulder as a landmark. During the rut — September and October — the belling of red deer sounds over the open plains; roe deer, wild boar, badger and pine marten also live here.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or late afternoon — heath in the lowest light.',
 'why': ['The <b>largest GLK terrain</b> with heath, juniper and drift dunes.', 'The <b>sheep flock</b> that grazes the heath with its shepherd from April to December.', 'The <b>Loenense Bos</b>, one of the oldest forests of the Netherlands.', 'The <b>marked routes</b> of 2.5 to 13.5 km from the sheep fold.'],
 'phen': ['<span class="months">Apr–Dec</span> 🐑 <b>Heath sheep</b> with shepherd on the Loenermark.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> and juniper berries.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer over the plains.', '<span class="months">Oct</span> 🍄 <b>Fungi</b> in the ancient Loenense Bos.'], 'wild': ['🐑 Veluwe heath sheep', '🦌 Red deer · Roe deer · Wild boar', '🐦 Black woodpecker · Woodlark · Stonechat', '🦎 Sand lizard · Viviparous lizard', '🌼 Bell heather · Juniper · Crowberry'],
 'trail': ['Park at <b>Droefakkers</b> on the Zilvenseweg in Loenen.', 'Start at the <b>sheep fold</b> and choose one of the four marked routes.', 'Follow the purple route (13.5 km) for heath and ancient forest alike.'],
 'foot': '🐕 Dogs on lead (off-lead areas indicated) · 💶 Free · ⚠️ Rest area · stay on the paths · 🚶 Heath, dune and forest paths'
}))

C.append(mk.card(1782, 'Veluwezoom, Nationaal Park', {
 'tags': ['Gelderland · Rheden/Rozendaal', 'Eerste nationale park van Nederland (1930) · de Posbank en de heide van de Veluwezoom', 'list 36 · no. 501'],
 'loc': '📍 Zuidoostrand van de Veluwe tussen Arnhem, Dieren en Rheden · Nationaal park van Natuurmonumenten · start bij de Posbank of het bezoekerscentrum',
 'desc': 'Nationaal Park <b>Veluwezoom</b> is het oudste nationale park van Nederland: in 1930 stelde Natuurmonumenten het eerste deel open en in 2013 kreeg het de status nationaal park. Het beslaat circa 5.000 hectare bos, heide en beekdalen op de stuwwal tussen Arnhem en Dieren. Het bekendste punt is de <b>Posbank</b> op het Herikhuizerveld, waar in 1918 een stenen bank werd onthuld ter ere van G.A. Pos, voorzitter van de ANWB, met uitzicht over de IJsselvallei; in de nazomer kleurt het omringende heideveld paars. Een kudde Veluwse heideschapen met herder houdt de heide open, Schotse hooglanders en IJslandse paarden grazen in de beekdalen, en edelherten, reeën en wilde zwijnen trekken door het park. Vanaf de parkeerplaatsen Posbank en Heuven, het Veluwetransferium en het bezoekerscentrum in Rheden lopen gemarkeerde routes; ook de oude beukenlanen en grafheuvels van de Imbossche Heide zijn wandelwaardig.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei op de Posbank), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Zonsopgang of late middag — licht over de IJsselvallei.',
 'why': ['Het <b>eerste nationale park</b> van Nederland met uitzicht over de IJsselvallei.', 'De <b>Posbank</b> met heidebloei en de steenbank uit 1918.', 'De <b>schaapskudde, hooglanders en IJslandse paarden</b> in het landschap.', 'De <b>gemarkeerde routes</b> over hei, bos en beekdalen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐑 <b>Lammetjes</b> bij de kudde op de hei.', '<span class="months">Jun–Aug</span> 🐦 <b>Heidevogels</b> en jagende boomvalken.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op het Herikhuizerveld.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de dalen.'], 'wild': ['🐑 Veluws heideschaap · Schotse hooglander', '🦌 Edelhert · Ree · Wild zwijn', '🐦 Zwarte specht · Boomvalk · Roodborsttapuit', '🐴 IJslands paard', '🌼 Struikhei · Dophei · Klokjesgentiaan'],
 'trail': ['Parkeer bij de <b>Posbank</b> (Rheden) en loop het Herikhuizerveld op.', 'Volg een van de <b>gemarkeerde routes</b> vanaf de Posbank of Heuven.', 'Bezoek het <b>bezoekerscentrum Veluwezoom</b> in Rheden.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (parkeren bij Posbank betaald) · ⚠️ Blijf op de paden · rustgebieden · 🚶 Heide-, bos- en dalpaden'
}, {
 'tags': ['Gelderland · Rheden/Rozendaal', 'First national park of the Netherlands (1930) · the Posbank and the heath of the Veluwezoom', 'list 36 · no. 501'],
 'loc': '📍 South-eastern edge of the Veluwe between Arnhem, Dieren and Rheden · National park of Natuurmonumenten · start at the Posbank or the visitor centre',
 'desc': 'National Park <b>Veluwezoom</b> is the oldest national park of the Netherlands: in 1930 Natuurmonumenten opened the first part and in 2013 it received national park status. It covers some 5,000 hectares of forest, heath and stream valleys on the ice-margin ridge between Arnhem and Dieren. The best-known spot is the <b>Posbank</b> on the Herikhuizerveld, where in 1918 a stone bench was unveiled in honour of G.A. Pos, chairman of the ANWB, with a view over the IJssel valley; in late summer the surrounding heath field turns purple. A flock of Veluwe heath sheep with a shepherd keeps the heath open, Scottish Highland cattle and Icelandic horses graze in the stream valleys, and red deer, roe deer and wild boar move through the park. Marked routes start from the Posbank and Heuven car parks, the Veluwetransferium and the visitor centre in Rheden; the old beech avenues and burial mounds of the Imbossche Heide are also worth walking.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom at the Posbank), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Sunrise or late afternoon — light over the IJssel valley.',
 'why': ['The <b>first national park</b> of the Netherlands with a view over the IJssel valley.', 'The <b>Posbank</b> with heather bloom and the 1918 stone bench.', 'The <b>sheep flock, Highland cattle and Icelandic horses</b> in the landscape.', 'The <b>marked routes</b> over heath, forest and stream valleys.'],
 'phen': ['<span class="months">Apr–May</span> 🐑 <b>Lambs</b> with the flock on the heath.', '<span class="months">Jun–Aug</span> 🐦 <b>Heath birds</b> and hunting hobbies.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the Herikhuizerveld.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the valleys.'], 'wild': ['🐑 Veluwe heath sheep · Scottish Highland cattle', '🦌 Red deer · Roe deer · Wild boar', '🐦 Black woodpecker · Hobby · Stonechat', '🐴 Icelandic horse', '🌼 Bell heather · Cross-leaved heath · Gentianella'],
 'trail': ['Park at the <b>Posbank</b> (Rheden) and walk onto the Herikhuizerveld.', 'Follow one of the <b>marked routes</b> from the Posbank or Heuven.', 'Visit the <b>Veluwezoom visitor centre</b> in Rheden.'],
 'foot': '🐕 Dogs on lead · 💶 Free (parking at Posbank paid) · ⚠️ Stay on the paths · rest areas · 🚶 Heath, forest and valley paths'
}))

C.append(mk.card(1783, 'Terletse Heide', {
 'tags': ['Gelderland · Terlet/Wolfheze', 'Heide bij zweefvliegveld Terlet · stiltegebied van de Veluwezoom met Schotse hooglanders', 'list 36 · no. 502'],
 'loc': '📍 Tussen Terlet en Wolfheze, oostelijk van de A50 · Heide en bos · start bij zweefvliegveld Terlet (parkeerplaats Terletseweg)',
 'desc': 'De <b>Terletse Heide</b> ligt in de uiterste noordoosthoek van de Veluwezoom, tussen de A50 en het zweefvliegveld Terlet — dat zijn naam aan dit heidegebied ontleent. Het terrein ligt op een oud smeltwaterdal met hard zand en grind, waardoor het hier ook in natte perioden goed wandelen is. Runderen en Schotse hooglanders houden de heide en het grasland open; in de nazomer kleurt de struikhei paars. Boven het veld zweven in het weekend de zweefvliegtuigen van Terlet, een bijzonder decor voor een wandeling over de hei. De wandelroutes starten bij de parkeerplaats aan de Terletseweg tegenover café De Thermiekbel: de rode route door de Terletse Heide en de gele route richting Kerk- en Westerheide. De Terletse Heide grenst aan de Vierheidenroute, die in één tocht de Terletse, Kerk- en Westerheide en de Zijpenberg verbindt. Het oostelijke deel is stiltegebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — rust op de heide.',
 'why': ['De <b>open heide</b> met Schotse hooglanders in een oud smeltwaterdal.', 'De bijzondere combinatie met het <b>zweefvliegveld Terlet</b>.', 'De <b>gemarkeerde routes</b> en de aansluiting op de Vierheidenroute.', 'De rust van het <b>stiltegebied</b> in de oostelijke hoek.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐦 <b>Zangvogels</b> en graspiepers boven de hei.', '<span class="months">Jun–Aug</span> 🐄 <b>Runderen</b> en hooglanders grazen de hei open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de vlakte paars.', '<span class="months">Heel jaar (weekend)</span> 🛩️ <b>Zweefvliegen</b> boven het veld.'], 'wild': ['🐄 Schotse hooglander · Galloway', '🦌 Ree · Edelhert · Wild zwijn', '🐦 Boomleeuwerik · Graspieper · Roodborsttapuit', '🦋 Heideblauwtje · Hooibeestje', '🌼 Struikhei · Dophei · Pilzegge'],
 'trail': ['Parkeer aan de <b>Terletseweg</b> tegenover café De Thermiekbel.', 'Volg de <b>rode route</b> over de Terletse Heide (vanaf het hek).', 'Loop de <b>Vierheidenroute</b> naar Kerk- en Westerheide en de Zijpenberg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Stiltegebied in het oosten · blijf op de paden · 🚶 Heide- en zandpaden'
}, {
 'tags': ['Gelderland · Terlet/Wolfheze', 'Heath near Terlet glider airfield · silence area of the Veluwezoom with Scottish Highland cattle', 'list 36 · no. 502'],
 'loc': '📍 Between Terlet and Wolfheze, east of the A50 · Heath and forest · start at Terlet glider airfield (Terletseweg car park)',
 'desc': 'The <b>Terletse Heide</b> lies in the far north-eastern corner of the Veluwezoom, between the A50 and the Terlet glider airfield — which owes its name to this heath area. The terrain lies on an old meltwater valley with hard sand and gravel, making it easy walking even in wet periods. Cattle and Scottish Highland cattle keep the heath and grassland open; in late summer the bell heather turns purple. At the weekend gliders of Terlet soar above the field — a special backdrop for a walk over the heath. The walking routes start at the car park on the Terletseweg opposite café De Thermiekbel: the red route through the Terletse Heide and the yellow route towards Kerk- and Westerheide. The Terletse Heide borders the Vierheidenroute, which links the Terletse, Kerk- and Westerheide and the Zijpenberg in one hike. The eastern part is a silence area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Morning or late afternoon — peace on the heath.',
 'why': ['The <b>open heath</b> with Scottish Highland cattle in an old meltwater valley.', 'The special combination with <b>Terlet glider airfield</b>.', 'The <b>marked routes</b> and the link to the Vierheidenroute.', 'The peace of the <b>silence area</b> in the eastern corner.'],
 'phen': ['<span class="months">Apr–May</span> 🐦 <b>Songbirds</b> and meadow pipits above the heath.', '<span class="months">Jun–Aug</span> 🐄 <b>Cattle and Highlanders</b> keep the heath open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the plain purple.', '<span class="months">All year (weekend)</span> 🛩️ <b>Gliding</b> above the field.'], 'wild': ['🐄 Scottish Highland cattle · Galloway', '🦌 Roe deer · Red deer · Wild boar', '🐦 Woodlark · Meadow pipit · Stonechat', '🦋 Silver-studded blue · Small heath', '🌼 Bell heather · Cross-leaved heath · Pill sedge'],
 'trail': ['Park on the <b>Terletseweg</b> opposite café De Thermiekbel.', 'Follow the <b>red route</b> over the Terletse Heide (from the gate).', 'Walk the <b>Vierheidenroute</b> to Kerk- and Westerheide and the Zijpenberg.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Silence area in the east · stay on the paths · 🚶 Heath and sand paths'
}))

C.append(mk.card(1784, 'Arnhemsche Heide', {
 'tags': ['Gelderland · Arnhem/Terlet', 'Gemeenschapsheide van Arnhem · oefenterrein van Defensie tussen Terlet en Deelen', 'list 36 · no. 503'],
 'loc': '📍 Tussen Terlet, Schaarsbergen en Deelen, ten noorden van Arnhem · Heide en bos · start langs de Rozendaalscheweg of bij Deelen',
 'desc': 'De <b>Arnhemsche Heide</b> is het uitgestrekte heide- en oefenterrein ten noorden van Arnhem, tussen de wijk Schaarsbergen, Terlet en Deelen. De heide was eeuwenlang gemeenschappelijk bezit van de Arnhemse burgerij, die er vee liet grazen, plaggen stak en zand oogstte. Tegenwoordig is het gebied grotendeels in gebruik bij Defensie als oefenterrein, met de Arnhemse Heide, de Kemperheide en de Mosselse Heide als grote open vlaktes. Het gebied is vrij toegankelijk zolang de militaire oefeningen het toelaten: langs de randen staan borden die aangeven wanneer het terrein gesloten is. In de nazomer bloeit de heide paars en laten edelherten, reeën en zwijnen zich zien, vooral in de vroege ochtend. De wandelroute over de Arnhemse Heide start bij de parkeerplaats aan de Rozendaalscheweg; fietspad 92 voert vanaf Museum Vliegbasis Deelen langs de heide. Combineer een bezoek met de Ginkelse Heide of het Natuurcentrum Veluwe.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — wild op de heide.',
 'why': ['De <b>uitgestrekte heide</b> met edelherten, reeën en zwijnen.', 'De bijzondere <b>militaire historie</b> van het oefenterrein bij Deelen.', 'De <b>heidebloei</b> in augustus en september.', 'Het <b>open karakter</b> van een van de grootste heidevelden rond Arnhem.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐦 <b>Boomleeuweriken</b> zingen boven de hei.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de vlakte paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b>: burlende edelherten in de schemering.', '<span class="months">Heel jaar</span> 🎖️ <b>Militaire oefeningen</b> — afsluitingen mogelijk.'], 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐦 Boomleeuwerik · Roodborsttapuit · Geelgors', '🐍 Adder · Levendbarende hagedis', '🦋 Heideblauwtje · Hooibeestje', '🌼 Struikhei · Dophei · Klokjesgentiaan'],
 'trail': ['Start bij de <b>parkeerplaats aan de Rozendaalscheweg</b> (alleen als het terrein open is).', 'Controleer de <b>afsluitingsborden</b> van Defensie langs de randen.', 'Fiets <b>route 92</b> vanaf Museum Vliegbasis Deelen langs de heide.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Militair oefenterrein — let op afsluitingen en munitie · 🚶 Heide- en zandpaden'
}, {
 'tags': ['Gelderland · Arnhem/Terlet', 'Common heath of Arnhem · defence exercise area between Terlet and Deelen', 'list 36 · no. 503'],
 'loc': '📍 Between Terlet, Schaarsbergen and Deelen, north of Arnhem · Heath and forest · start along the Rozendaalscheweg or near Deelen',
 'desc': 'The <b>Arnhemsche Heide</b> is the vast heath and exercise terrain north of Arnhem, between the Schaarsbergen district, Terlet and Deelen. For centuries the heath was the common property of the citizens of Arnhem, who grazed livestock, cut sods and harvested sand there. Today the area is largely used by the Ministry of Defence as an exercise terrain, with the Arnhemse Heide, the Kemperheide and the Mosselse Heide as large open plains. The area is freely accessible as long as military exercises allow: signs along the edges indicate when the terrain is closed. In late summer the heath blooms purple and red deer, roe deer and boar show themselves, especially in the early morning. The walking route over the Arnhemsche Heide starts at the car park on the Rozendaalscheweg; cycle path 92 runs from Museum Vliegbasis Deelen along the heath. Combine a visit with the Ginkelse Heide or the Veluwe Nature Centre.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Early morning — game on the heath.',
 'why': ['The <b>vast heath</b> with red deer, roe deer and boar.', 'The special <b>military history</b> of the exercise area near Deelen.', 'The <b>heather bloom</b> in August and September.', 'The <b>open character</b> of one of the largest heath fields around Arnhem.'],
 'phen': ['<span class="months">Apr–May</span> 🐦 <b>Woodlarks</b> sing above the heath.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the plain purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b>: belling red deer at dusk.', '<span class="months">All year</span> 🎖️ <b>Military exercises</b> — closures possible.'], 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐦 Woodlark · Stonechat · Yellowhammer', '🐍 Adder · Viviparous lizard', '🦋 Silver-studded blue · Small heath', '🌼 Bell heather · Cross-leaved heath · Gentianella'],
 'trail': ['Start at the <b>car park on the Rozendaalscheweg</b> (only when the terrain is open).', 'Check the <b>closure signs</b> of the Ministry of Defence along the edges.', 'Cycle <b>route 92</b> from Museum Vliegbasis Deelen along the heath.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Military exercise area — mind closures and ammunition · 🚶 Heath and sand paths'
}))

mk.insert(C, '1779')
mk.progress(1784)
mk.check()
