# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1775, 'Otterlose Bos', {
 'tags': ['Gelderland · Otterlo', 'Oude bosgroeiplaats van ±200 ha in De Hoge Veluwe · een van de laatste populaties wilde appels', 'list 36 · no. 494'],
 'loc': '📍 In het noordwesten van Nationaal Park De Hoge Veluwe, nabij de ingang Otterlo · Oud bos · parkticket vereist',
 'desc': 'Het <b>Otterlose Bos</b> ligt in het noordwesten van Nationaal Park De Hoge Veluwe, op korte afstand van de ingang bij Otterlo. Het is een <b>oude bosgroeiplaats</b> van ongeveer 200 hectare: hier groeit al eeuwen onafgebroken bos en het terrein staat al op topografische kaarten uit 1830. De kern bestaat uit zeer oud eikenbos, met op de bodem soorten van oude bossen als dalkruid, zevenster, wilde kamperfoelie, boshavikskruid en gladde witbol. Bijzonder is de populatie <b>inheemse wilde appels</b> — een van de laatste en grootste van de Veluwe. Omdat de oude appelbomen geen nakomelingen meer kregen, kweekt het park sinds 2020 jonge boompjes uit hun pitten en plant die met rasters tegen vraat terug in het bos. Sinds 2025 wordt het bos met herstelmaatregelen versterkt: uitheemse soorten maken plaats voor inheems bos en wildvraat wordt beperkt. Het bos is te zien via de wandel- en fietsroutes van het park vanaf ingang Otterlo; de entree van De Hoge Veluwe is verplicht.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (bos), mei (bloei wilde appel)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de bospaden.',
 'why': ['Een <b>oude bosgroeiplaats</b> met al eeuwen onafgebroken bos.', 'De <b>inheemse wilde appels</b>, een van de laatste populaties van Nederland.', 'Het <b>herstelproject</b> met gekweekte appelboompjes en rasters.', 'De rustige <b>bos- en heidepaden</b> vanuit Otterlo.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Wilde appel</b> bloeit in de oude boskern.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het oude eikenbos.', '<span class="months">Aug–Sep</span> 🟣 <b>Heide</b> bloeit aan de bosranden.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> en eikels onder de oude eiken.'], 'wild': ['🐦 Zwarte specht · Boomklever · Havik', '🦌 Edelhert · Wild zwijn · Ree', '🦋 Bont zandoogje · Citroenvlinder · Dagpauwoog', '🌼 Wilde kamperfoelie · Dalkruid · Zevenster', '🌳 Wilde appel · Zomereik · Grove den'],
 'trail': ['Ga het park binnen bij <b>ingang Otterlo</b> en volg de wandelroutes naar het noordwesten.', 'Verken het bos op de <b>gratis witte fiets</b> over de onverharde paden.', 'Combineer met het <b>Museonder</b> of het Deelense Veld.'],
 'foot': '🐕 Honden niet toegestaan · 💶 Parkticket (De Hoge Veluwe) · ⚠️ Herstelwerkzaamheden — volg bebording · 🚶 Bos-, heide- en fietspaden'
}, {
 'tags': ['Gelderland · Otterlo', 'Ancient woodland site of ±200 ha in De Hoge Veluwe · one of the last populations of wild apple', 'list 36 · no. 494'],
 'loc': '📍 In the north-west of National Park De Hoge Veluwe, near the Otterlo entrance · Ancient woodland · park ticket required',
 'desc': 'The <b>Otterlose Bos</b> lies in the north-west of National Park De Hoge Veluwe, a short distance from the entrance at Otterlo. It is an <b>ancient woodland site</b> of about 200 hectares: forest has grown here continuously for centuries and the terrain already appears on topographic maps from 1830. The core consists of very old oak woodland, with old-forest species on the forest floor such as may lily, chickweed wintergreen, wild honeysuckle, hawkweed and smooth meadow-grass. Remarkable is the population of <b>native wild apple</b> — one of the last and largest of the Veluwe. Because the old apple trees no longer produced offspring, the park has been raising young trees from their pips since 2020 and planting them back into the forest behind fences against browsing. Since 2025 the forest is being strengthened with restoration measures: exotic species make way for native woodland and pressure from game is reduced. The forest can be seen via the park’s walking and cycling routes from the Otterlo entrance; admission to De Hoge Veluwe is required.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (forest), May (wild apple blossom)<br>\n    <b>Best time of day:</b> Morning — quiet on the forest paths.',
 'why': ['An <b>ancient woodland site</b> with centuries of continuous forest.', 'The <b>native wild apples</b>, one of the last populations in the Netherlands.', 'The <b>restoration project</b> with raised apple saplings and fences.', 'The quiet <b>forest and heath paths</b> from Otterlo.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Wild apple</b> blossoms in the old forest core.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old oak wood.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather</b> blooms along the forest edges.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> and acorns under the old oaks.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Goshawk', '🦌 Red deer · Wild boar · Roe deer', '🦋 Speckled wood · Brimstone · Peacock', '🌼 Wild honeysuckle · May lily · Chickweed wintergreen', '🌳 Wild apple · Pedunculate oak · Scots pine'],
 'trail': ['Enter the park at the <b>Otterlo entrance</b> and follow the walking routes to the north-west.', 'Explore the forest on a <b>free white bicycle</b> over the unpaved paths.', 'Combine with the <b>Museonder</b> or the Deelense Veld.'],
 'foot': '🐕 Dogs not allowed · 💶 Park ticket (De Hoge Veluwe) · ⚠️ Restoration works — follow the signs · 🚶 Forest, heath and cycle paths'
}))

C.append(mk.card(1776, 'Planken Wambuis', {
 'tags': ['Gelderland · Ede/Otterlo', 'Gebied van Natuurmonumenten (1.965 ha) · heide, stuifzand en biologische akkers rond de oude herberg', 'list 36 · no. 495'],
 'loc': '📍 Ten zuidwesten van Ede, tussen de N224, Otterlo en Oud Reemst · Bos, heide en stuifzand · start bij restaurant Planken Wambuis of P Oud Reemst',
 'desc': '<b>Planken Wambuis</b> is een natuurgebied van <b>Natuurmonumenten</b> van 1.965 hectare, ten westen van De Hoge Veluwe. Het landschap is een lappendeken van ruim 1.100 hectare bos, 430 hectare heide, 180 hectare open stuifzand en 200 hectare gras- en bouwland — met hoge stuifheuvels, oude lanen en de landbouwenclave Oud Reemst. De naam komt van de herberg die hier in 1782 aan een hessenweg werd gebouwd, de route waarlangs Hessen met hun huifkarren naar Amsterdam trokken; het huidige restaurant draagt die naam nog. Op de akkers van Oud Reemst verbouwt Natuurmonumenten biologisch graan als haver en winterrogge, met randen vol bloemen voor vogels en insecten. Het gebied is wildrijk: edelherten, reeën en wilde zwijnen, met vogels als nachtzwaluw, houtsnip, kruisbek en wespendief. De gele wandelroute (8 km) start bij parkeerplaats Oud Reemst en voert langs heide, stuifzand, akkers en bos; vanaf het restaurant lopen de rode Buunderkamp-route (4,6 km) en vanaf camping De Wije Werelt de oranje Mosselse Zand-route (3,7 km).',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of schemering — wild en stilte.',
 'why': ['De <b>afwisseling van bos, heide en stuifzand</b> op 1.965 hectare.', 'De historie van de <b>herberg Planken Wambuis</b> uit 1782.', 'De <b>biologische akkers</b> van Oud Reemst met bloemrijke randen.', 'De kans op <b>edelhert, ree en wild zwijn</b> en bijzondere vogels.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Akkerbloemen</b> en zangvogels boven de graanakkers.', '<span class="months">Jun–Aug</span> 🐦 <b>Nachtzwaluw</b> en boomleeuwerik boven heide en zand.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de velden paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten rond Oud Reemst.'], 'wild': ['🐦 Nachtzwaluw · Houtsnip · Wespendief', '🦌 Edelhert · Ree · Wild zwijn', '🦎 Hazelworm · Zandhagedis', '🌼 Struikhei · Zandzegge · Wilde kamperfoelie', '🌳 Grove den · Zomereik · Ruwe berk'],
 'trail': ['Start bij <b>parkeerplaats Oud Reemst</b> en volg de gele route (8 km).', 'Wandel vanaf <b>restaurant Planken Wambuis</b> de rode Buunderkamp-route (4,6 km).', 'Combineer met het <b>Mosselse Zand</b> of De Hoge Veluwe.'],
 'foot': '🐕 Honden aangelijnd op de paden · 💶 Gratis · ⚠️ Rustgebied voor wild — blijf op wegen en paden · 🚶 Bos-, heide- en zandpaden'
}, {
 'tags': ['Gelderland · Ede/Otterlo', 'Area of Natuurmonumenten (1,965 ha) · heath, drift sand and organic fields around the old inn', 'list 36 · no. 495'],
 'loc': '📍 South-west of Ede, between the N224, Otterlo and Oud Reemst · Forest, heath and drift sand · start at restaurant Planken Wambuis or P Oud Reemst',
 'desc': '<b>Planken Wambuis</b> is a nature area of <b>Natuurmonumenten</b> covering 1,965 hectares, west of De Hoge Veluwe. The landscape is a patchwork of more than 1,100 hectares of forest, 430 hectares of heath, 180 hectares of open drift sand and 200 hectares of grassland and arable land — with high drift hills, old avenues and the Oud Reemst farmland enclave. The name comes from the inn built here in 1782 on a Hessenweg, the route along which Hessen merchants drove their covered wagons to Amsterdam; the present restaurant still bears that name. On the fields of Oud Reemst, Natuurmonumenten organically grows grain such as oats and winter rye, with margins full of flowers for birds and insects. The area is rich in game: red deer, roe deer and wild boar, with birds such as nightjar, woodcock, crossbill and honey buzzard. The yellow walking route (8 km) starts at the Oud Reemst car park and leads along heath, drift sand, fields and forest; from the restaurant run the red Buunderkamp route (4.6 km) and from Camping De Wije Werelt the orange Mosselse Zand route (3.7 km).',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or dusk — game and silence.',
 'why': ['The <b>variety of forest, heath and drift sand</b> on 1,965 hectares.', 'The history of the <b>Planken Wambuis inn</b> from 1782.', 'The <b>organic fields</b> of Oud Reemst with flowery margins.', 'The chance of <b>red deer, roe deer and wild boar</b> and special birds.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Field flowers</b> and songbirds above the grain fields.', '<span class="months">Jun–Aug</span> 🐦 <b>Nightjar</b> and woodlark above heath and sand.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the fields purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer around Oud Reemst.'], 'wild': ['🐦 Nightjar · Woodcock · Honey buzzard', '🦌 Red deer · Roe deer · Wild boar', '🦎 Slow worm · Sand lizard', '🌼 Bell heather · Sand sedge · Wild honeysuckle', '🌳 Scots pine · Pedunculate oak · Silver birch'],
 'trail': ['Start at the <b>Oud Reemst car park</b> and follow the yellow route (8 km).', 'Walk the red <b>Buunderkamp route</b> (4.6 km) from restaurant Planken Wambuis.', 'Combine with the <b>Mosselse Zand</b> or De Hoge Veluwe.'],
 'foot': '🐕 Dogs on lead on the paths · 💶 Free · ⚠️ Game rest area — stay on roads and paths · 🚶 Forest, heath and sand paths'
}))

C.append(mk.card(1777, 'Hindenkamp', {
 'tags': ['Gelderland · Ede', 'Wildweide met overdekte wildkansel · edelherten, reeën en zwijnen aan de rand van de Eder Heide', 'list 36 · no. 496'],
 'loc': '📍 Aan de rand van de Eder Heide bij Ede · Wildweide en wildkansel · alleen met gids bereikbaar vanaf Natuurcentrum De Ginkel',
 'desc': 'De <b>Hindenkamp</b> (ook wel Hindekamp) is de wildweide van het Ginkelgebied bij Ede: een open grasvlakte aan de rand van de Eder Heide waar edelherten, reeën, wilde zwijnen en vossen zich in de schemering uit het bos wagen. Het is een van de beste plekken van de Veluwe om groot wild te zien zonder het te verstoren. Centraal staat <b>wildkansel De Hindekamp</b>, op circa twee kilometer van Natuurcentrum De Ginkel: een grote overdekte kansel met ruimte voor 45 personen, ook toegankelijk voor rolstoelgebruikers. De kansel ligt in een afgesloten rustgebied en is uitsluitend te bezoeken onder leiding van een gids van het natuurcentrum — de tocht gaat per fiets naar de rand van het bos en dan te voet over een fluisterpad naar de kansel. In september en oktober staan de <b>bronsttochten</b> op het programma, wanneer het burlen van de edelherten door de schemering galmt. Buiten de bronst zijn er het hele jaar wildkanseltochten. Reserveren is verplicht; trek donkere kleding aan en neem een verrekijker mee.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–okt</b> (bronst), heel jaar (wildkanseltochten)<br>\n    <b>Beste tijd van de dag:</b> Late middag tot schemering — de dieren komen de weide op.',
 'why': ['De kans om <b>edelherten, reeën en zwijnen</b> van dichtbij te zien.', 'De <b>overdekte wildkansel</b> met plek voor 45 personen (rolstoeltoegankelijk).', 'De <b>bronsttochten</b> in september en oktober.', 'Het <b>fluisterpad</b> door het afgesloten rustgebied.'],
 'phen': ['<span class="months">Apr–Aug</span> 🦌 <b>Wildkanseltochten</b> het hele jaar door.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b>: burlende edelherten op de wildweide.', '<span class="months">Sep–Okt</span> 🦊 <b>Vos</b> jaagt in de schemering op de weide.', '<span class="months">Heel jaar</span> 🐗 <b>Wilde zwijnen</b> wroeten aan de bosrand.'], 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🦊 Vos · Das · Boommarter', '🐦 Zwarte specht · Boomleeuwerik · Roodborsttapuit', '🌼 Struikhei · Pijpenstrootje · Blauwe bosbes', '🌳 Grove den · Zomereik · Ruwe berk'],
 'trail': ['Meld je aan bij <b>Natuurcentrum De Ginkel</b> (Groot Ginkelseweg 2a, Ede) voor een wildkanseltocht.', 'Ga op de <b>leenfiets</b> naar de rand van het rustgebied en loop het fluisterpad.', 'Reserveer in september en oktober een <b>bronsttocht</b> — snel volgeboekt.'],
 'foot': '🐕 Niet toegestaan · 💶 Tochten ca. €5–7 p.p. · ⚠️ Rustgebied — alleen met gids · 🚶 Fluisterpad en kansel'
}, {
 'tags': ['Gelderland · Ede', 'Game meadow with covered game hide · red deer, roe deer and boar on the edge of the Eder Heide', 'list 36 · no. 496'],
 'loc': '📍 On the edge of the Eder Heide near Ede · Game meadow and hide · only reachable with a guide from Nature Centre De Ginkel',
 'desc': 'The <b>Hindenkamp</b> (also spelled Hindekamp) is the game meadow of the Ginkel area near Ede: an open grassland on the edge of the Eder Heide where red deer, roe deer, wild boar and foxes venture out of the forest at dusk. It is one of the best places on the Veluwe to watch large game without disturbing it. Central stands <b>De Hindekamp game hide</b>, about two kilometres from Nature Centre De Ginkel: a large covered hide with room for 45 people, also accessible to wheelchair users. The hide lies in a closed rest area and can only be visited under the guidance of a centre ranger — the trip goes by bicycle to the edge of the forest and then on foot over a whisper path to the hide. In September and October the <b>rutting excursions</b> are on the programme, when the belling of red deer echoes through the twilight. Outside the rutting season, game-hide trips run all year. Booking is required; wear dark clothing and bring binoculars.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (rutting), all year (game-hide trips)<br>\n    <b>Best time of day:</b> Late afternoon to dusk — the animals come onto the meadow.',
 'why': ['The chance to see <b>red deer, roe deer and boar</b> close by.', 'The <b>covered game hide</b> with room for 45 people (wheelchair accessible).', 'The <b>rutting excursions</b> in September and October.', 'The <b>whisper path</b> through the closed rest area.'],
 'phen': ['<span class="months">Apr–Aug</span> 🦌 <b>Game-hide trips</b> all year round.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b>: belling red deer on the meadow.', '<span class="months">Sep–Oct</span> 🦊 <b>Fox</b> hunts at dusk on the meadow.', '<span class="months">All year</span> 🐗 <b>Wild boar</b> root along the forest edge.'], 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🦊 Fox · Badger · Pine marten', '🐦 Black woodpecker · Woodlark · Stonechat', '🌼 Bell heather · Purple moor-grass · Bilberry', '🌳 Scots pine · Pedunculate oak · Silver birch'],
 'trail': ['Book a game-hide trip at <b>Nature Centre De Ginkel</b> (Groot Ginkelseweg 2a, Ede).', 'Ride a <b>loan bicycle</b> to the edge of the rest area and walk the whisper path.', 'Reserve a <b>rutting excursion</b> in September and October — they sell out fast.'],
 'foot': '🐕 Not allowed · 💶 Trips about €5–7 p.p. · ⚠️ Rest area — guide only · 🚶 Whisper path and hide'
}))

C.append(mk.card(1778, 'Noord- en Zuid-Ginkel', {
 'tags': ['Gelderland · Ede', 'Ginkelse Heide met schaapskooi · Airborne-landingen 1944 en de Mechelse Kuil', 'list 36 · no. 497'],
 'loc': '📍 Ten oosten van Ede, aan weerszijden van de N224 · Heide, bos en landbouwenclave · rond Natuurcentrum De Ginkel en de schaapskooi',
 'desc': 'De <b>Noord- en Zuid-Ginkel</b> vormen het heide- en bosgebied ten oosten van Ede, samen bekend als De Ginkel. De <b>Zuid-Ginkel</b> omvat de beroemde <b>Ginkelse Heide</b> met de monumentale schaapskooi, waar een kudde Veluwse heideschapen de heide openhoudt; de <b>Noord-Ginkel</b> is de landbouwenclave met weilanden, de Kreelse Plas en de Plas van Gent, omzoomd door bos en heide. De heidevelden waren eeuwenlang woeste grond van de geërfden van de buurt Ede-Veldhuizen. Wereldberoemd werd het gebied op 17 en 18 september 1944, toen tijdens Operatie Market Garden rond de schaapskooi zo’n 1.900 Britse parachutisten landden — jaarlijks herdacht bij het Airborne-monument, waarna parachutisten opnieuw boven de hei springen. Tussen de heide ligt de <b>Mechelse Kuil</b>, een vochtige laagte met een bijzondere flora. Natuurcentrum De Ginkel is de uitvalsbasis; wandelroutes als de Schaapskooiroute (6,5 km), het Rondje Noord-Ginkel (4,6 km) en de militaire Rondje Zuid-Ginkel-route (3,5 km) doorkruisen het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei), eerste zaterdag van september (Airborne-herdenking)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — licht over de heide.',
 'why': ['De <b>Ginkelse Heide</b> met schaapskudde en de heidebloei in augustus.', 'De <b>Airborne-herdenking</b> met parachutesprongen boven de hei.', 'De <b>Mechelse Kuil</b> en het afwisselende landschap van De Ginkel.', 'De <b>gemarkeerde wandelroutes</b> vanaf Natuurcentrum De Ginkel.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🐑 <b>Lammetjes</b> bij de schaapskooi.', '<span class="months">Mei–Aug</span> 🐦 <b>Heidevogels</b>: boomleeuwerik en roodborsttapuit.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de Ginkelse Heide paars.', '<span class="months">Sep</span> 🪂 <b>Airborne-herdenking</b> met parachutisten op de hei.'], 'wild': ['🐦 Boomleeuwerik · Roodborsttapuit · Geelgors', '🦌 Edelhert · Ree · Wild zwijn', '🐑 Veluws heideschaap', '🦋 Heideblauwtje · Hooibeestje · Bruin blauwtje', '🌼 Struikhei · Dophei · Klokjesgentiaan'],
 'trail': ['Start bij de <b>parkeerplaats De Ginkel</b> aan de N224 (tegenover Juffrouw Tok).', 'Volg de <b>Schaapskooiroute</b> (6,5 km) of het Rondje Noord-Ginkel (4,6 km).', 'Combineer met <b>Natuurcentrum De Ginkel</b> of de Eder Heide.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Rustgebieden voor wild — blijf op de paden · 🚶 Heide-, bos- en zandpaden'
}, {
 'tags': ['Gelderland · Ede', 'Ginkelse Heide with sheep fold · Airborne landings of 1944 and the Mechelse Kuil', 'list 36 · no. 497'],
 'loc': '📍 East of Ede, on both sides of the N224 · Heath, forest and farmland enclave · around Nature Centre De Ginkel and the sheep fold',
 'desc': 'The <b>Noord- and Zuid-Ginkel</b> form the heath and forest area east of Ede, together known as De Ginkel. The <b>Zuid-Ginkel</b> includes the famous <b>Ginkelse Heide</b> with its monumental sheep fold, where a flock of Veluwe heath sheep keeps the heath open; the <b>Noord-Ginkel</b> is the farmland enclave with meadows, the Kreelse Plas and the Plas van Gent, framed by forest and heath. For centuries the heath fields were the common waste land of the landowners of the Ede-Veldhuizen neighbourhood. The area became world-famous on 17 and 18 September 1944, when during Operation Market Garden some 1,900 British paratroopers landed around the sheep fold — commemorated annually at the Airborne monument, after which paratroopers jump above the heath again. In the middle of the heath lies the <b>Mechelse Kuil</b>, a damp hollow with a special flora. Nature Centre De Ginkel is the base; walking routes such as the Schaapskooiroute (6.5 km), the Rondje Noord-Ginkel (4.6 km) and the military Rondje Zuid-Ginkel route (3.5 km) cross the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom), first Saturday of September (Airborne commemoration)<br>\n    <b>Best time of day:</b> Morning or late afternoon — light over the heath.',
 'why': ['The <b>Ginkelse Heide</b> with sheep flock and the August heather bloom.', 'The <b>Airborne commemoration</b> with parachute jumps above the heath.', 'The <b>Mechelse Kuil</b> and the varied landscape of De Ginkel.', 'The <b>marked walking routes</b> from Nature Centre De Ginkel.'],
 'phen': ['<span class="months">Mar–May</span> 🐑 <b>Lambs</b> at the sheep fold.', '<span class="months">May–Aug</span> 🐦 <b>Heath birds</b>: woodlark and stonechat.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the Ginkelse Heide purple.', '<span class="months">Sep</span> 🪂 <b>Airborne commemoration</b> with paratroopers on the heath.'], 'wild': ['🐦 Woodlark · Stonechat · Yellowhammer', '🦌 Red deer · Roe deer · Wild boar', '🐑 Veluwe heath sheep', '🦋 Silver-studded blue · Small heath · Brown argus', '🌼 Bell heather · Cross-leaved heath · Gentianella'],
 'trail': ['Start at the <b>De Ginkel car park</b> on the N224 (opposite Juffrouw Tok).', 'Follow the <b>Schaapskooiroute</b> (6.5 km) or the Rondje Noord-Ginkel (4.6 km).', 'Combine with <b>Nature Centre De Ginkel</b> or the Eder Heide.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Game rest areas — stay on the paths · 🚶 Heath, forest and sand paths'
}))

C.append(mk.card(1779, 'De Hoge Veluwe, Het Nationale Park', {
 'tags': ['Gelderland · Otterlo/Hoenderloo/Schaarsbergen', 'Nationale Park van 5.400 ha · Kröller-Müller, Jachthuis Sint Hubertus en 1.800 witte fietsen', 'list 36 · no. 498'],
 'loc': '📍 Tussen Otterlo, Hoenderloo en Schaarsbergen · Nationaal park · drie ingangen: Otterlo, Hoenderloo en Schaarsbergen',
 'desc': '<b>Het Nationale Park De Hoge Veluwe</b> is met 5.400 hectare een van de grootste aaneengesloten natuurgebieden van Nederland en de nalatenschap van het echtpaar Anton Kröller en Helene Kröller-Müller: vanaf 1909 kocht Anton stukje bij beetje de Veluwse gronden op en in 1935 werd het geheel als nationaal park aan een stichting overgedragen. Bossen, heide, stuifzand (De Pollen), vennen en wildrijke velden als het Deelense Veld wisselen elkaar af. Door het park staan <b>1.800 gratis witte fietsen</b> klaar bij de drie ingangen, het bezoekerscentrum op het Marchantplein, het Kröller-Müller Museum en Jachthuis Sint Hubertus. Het <b>Kröller-Müller Museum</b> met de beroemde Van Gogh-collectie en het beeldenpark en het door Berlage ontworpen <b>Jachthuis Sint Hubertus</b> liggen in het park; het ondergrondse museum <b>Museonder</b> vertelt het verhaal van de bodem. Wildspotkansels bieden uitzicht op edelherten, wilde zwijnen, reeën en moeflons. Er is entree; honden zijn niet toegestaan.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend of zonsondergang — wild op de open velden.',
 'why': ['Het <b>grootste nationale park</b> van de Veluwe met bos, heide en stuifzand.', 'De <b>gratis witte fietsen</b> om het hele park te verkennen.', 'Het <b>Kröller-Müller Museum</b> en <b>Jachthuis Sint Hubertus</b>.', 'De <b>wildspotkansels</b> voor edelhert, zwijn en moeflon.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🌼 <b>Voorjaarsbloei</b> en jonge dieren.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de open velden.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten bij de wildkansels.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in de lanen en bossen.'], 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐑 Moeflon', '🐦 Zwarte specht · Nachtzwaluw · Boomleeuwerik', '🦋 Heideblauwtje · Bont zandoogje · Citroenvlinder', '🌳 Grove den · Beuk · Zomereik'],
 'trail': ['Kies een van de <b>drie ingangen</b> (Otterlo, Hoenderloo of Schaarsbergen) en pak een witte fiets.', 'Wandel de route <b>De Hoge Veluwe</b> (9 km) of een rondje over het Deelense Veld.', 'Bezoek het <b>Kröller-Müller Museum</b>, het Museonder of Jachthuis Sint Hubertus.'],
 'foot': '🐕 Honden niet toegestaan · 💶 Entree park (museum en jachthuis apart) · ⚠️ 40 km fietspad, blijf op wegen en paden · 🚶 Fietspaden en wandelroutes'
}, {
 'tags': ['Gelderland · Otterlo/Hoenderloo/Schaarsbergen', 'National park of 5,400 ha · Kröller-Müller, Jachthuis Sint Hubertus and 1,800 white bicycles', 'list 36 · no. 498'],
 'loc': '📍 Between Otterlo, Hoenderloo and Schaarsbergen · National park · three entrances: Otterlo, Hoenderloo and Schaarsbergen',
 'desc': '<b>The National Park De Hoge Veluwe</b> is, at 5,400 hectares, one of the largest contiguous nature areas of the Netherlands and the legacy of the couple Anton Kröller and Helene Kröller-Müller: from 1909 Anton bought up the Veluwe grounds piece by piece and in 1935 the whole was transferred to a foundation as a national park. Forests, heath, drifting sand (De Pollen), pools and game-rich fields such as the Deelense Veld alternate. Throughout the park <b>1,800 free white bicycles</b> stand ready at the three entrances, the visitor centre on Marchantplein, the Kröller-Müller Museum and Jachthuis Sint Hubertus. The <b>Kröller-Müller Museum</b> with its famous Van Gogh collection and sculpture garden and the <b>Jachthuis Sint Hubertus</b> designed by Berlage lie inside the park; the underground museum <b>Museonder</b> tells the story of the soil. Game-viewing hides offer views of red deer, wild boar, roe deer and mouflons. Admission is charged; dogs are not allowed.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Early morning or sunset — game on the open fields.',
 'why': ['The <b>largest national park</b> of the Veluwe with forest, heath and drift sand.', 'The <b>free white bicycles</b> to explore the whole park.', 'The <b>Kröller-Müller Museum</b> and <b>Jachthuis Sint Hubertus</b>.', 'The <b>game-viewing hides</b> for red deer, boar and mouflon.'],
 'phen': ['<span class="months">Mar–May</span> 🌼 <b>Spring bloom</b> and young animals.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the open fields.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer at the hides.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the avenues and forests.'], 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐑 Mouflon', '🐦 Black woodpecker · Nightjar · Woodlark', '🦋 Silver-studded blue · Speckled wood · Brimstone', '🌳 Scots pine · Beech · Pedunculate oak'],
 'trail': ['Choose one of the <b>three entrances</b> (Otterlo, Hoenderloo or Schaarsbergen) and take a white bicycle.', 'Walk the <b>De Hoge Veluwe</b> route (9 km) or a circuit over the Deelense Veld.', 'Visit the <b>Kröller-Müller Museum</b>, the Museonder or Jachthuis Sint Hubertus.'],
 'foot': '🐕 Dogs not allowed · 💶 Park admission (museum and hunting lodge extra) · ⚠️ 40 km of cycle paths; stay on roads and paths · 🚶 Cycle paths and walking routes'
}))

mk.insert(C, '1774')
mk.progress(1779)
mk.check()
