# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1765, 'De Groote Woeste Hoeve', {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Buurtschap en wildgebied bij de A50 · oudste ecoduct van Nederland (1988)', 'list 36 · no. 484'],
 'loc': '📍 Bij buurtschap Woeste Hoeve, tussen Apeldoorn en Arnhem · Bos- en heidegebied · rond de A50 en de Oude Arnhemseweg',
 'desc': 'De <b>Groote Woeste Hoeve</b> is de naam van een oude Veluwse pleisterplaats en het omringende bos- en heidegebied, waar de A50 tussen Apeldoorn en Arnhem de Oude Arnhemseweg kruist. Al in de late middeleeuwen stond hier een herberg te midden van woeste gronden en zandverstuivingen; na een brand omstreeks 1770 werd de uitspanning herbouwd en in 1811 overnachtte keizer Napoleon er met Marie Louise. Rond de buurtschap liggen de grote wildbossen van de zuidelijke Veluwe, en precies daarom kreeg de plek in 1988 wereldwijde bekendheid: bij de opening van de A50 werd de <b>Wildwissel Woeste Hoeve</b> geopend, samen met Wildwissel Terlet het <b>eerste ecoduct van Nederland</b>. De 50 meter brede, met een twee tot drie meter dikke grondlaag bedekte wildbrug overspant snelweg én Oude Arnhemseweg en verbindt de wildgebieden rond het voormalige Staatswildreservaat met de Loenermark; tellingen lieten zien dat grote grazers en herten de brug in de jaren na opening tot acht keer zo vaak gebruikten. Wie hier wandelt steekt grote kans edelherten, wilde zwijnen en reeën te zien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Zonsopgang of schemering — wild rond de wildwissel.',
 'why': ['De <b>Wildwissel Woeste Hoeve</b>, het oudste ecoduct van Nederland.', 'De rijke historie van de <b>pleisterplaats</b> sinds de middeleeuwen.', 'De kans op <b>edelhert, wild zwijn en ree</b> rond de ecoducten.', 'De wandel- en fietsroutes langs de <b>Oude Arnhemseweg</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Voorjaarsflora</b> langs bosranden en wallen.', '<span class="months">Jun–Aug</span> 🦋 <b>Vlinders</b> op heiderestanten en open zand.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten rond de wildwissels.', '<span class="months">Okt–Nov</span> 🍄 <b>Paddenstoelen</b> in het wildbos.'], 'wild': ['🐦 Zwarte specht · Boomleeuwerik · Nachtzwaluw', '🦌 Edelhert · Wild zwijn · Ree', '🦋 Bont zandoogje · Citroenvlinder · Atalanta', '🌼 Struikhei · Blauwe bosbes · Bochtige smele', '🌳 Grove den · Zomereik · Beuk'],
 'trail': ['Start bij de <b>parkeerplaats aan de Oude Arnhemseweg</b> ter hoogte van de buurtschap.', 'Bekijk de <b>wildwissel</b> vanaf de wildkijkpunten aan weerszijden.', 'Wandel de <b>gemarkeerde routes</b> richting Ugchelen, Beekbergen of Hoenderloo.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ A50 kruist het gebied — houd honden bij je · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Hamlet and game area at the A50 · oldest wildlife crossing of the Netherlands (1988)', 'list 36 · no. 484'],
 'loc': '📍 Near the hamlet of Woeste Hoeve, between Apeldoorn and Arnhem · Forest and heath area · around the A50 and the Oude Arnhemseweg',
 'desc': 'The <b>Groote Woeste Hoeve</b> is the name of an old Veluwe staging post and the surrounding forest and heath area, where the A50 between Apeldoorn and Arnhem crosses the Oude Arnhemseweg. As early as the late Middle Ages an inn stood here amid wild grounds and drifting sands; after a fire around 1770 the hostelry was rebuilt and in 1811 Emperor Napoleon spent the night there with Marie Louise. Around the hamlet lie the great game forests of the southern Veluwe — and precisely for that reason the place gained worldwide fame in 1988: at the opening of the A50 the <b>Wildwissel Woeste Hoeve</b> was inaugurated, together with Wildwissel Terlet the <b>first wildlife crossing of the Netherlands</b>. The 50-metre-wide wildlife bridge, covered with a two-to-three-metre-thick layer of soil, spans both motorway and old road and connects the game areas around the former State Wildlife Reserve with the Loenermark; counts showed that large herbivores and deer used the bridge up to eight times more often in the years after its opening. Walkers here stand a good chance of seeing red deer, wild boar and roe deer.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Sunrise or dusk — game around the wildlife crossing.',
 'why': ['The <b>Wildwissel Woeste Hoeve</b>, the oldest ecoduct of the Netherlands.', 'The rich history of the <b>staging post</b> since the Middle Ages.', 'The chance of <b>red deer, wild boar and roe deer</b> around the ecoducts.', 'The walking and cycling routes along the <b>Oude Arnhemseweg</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Spring flora</b> along forest edges and banks.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> on heath remnants and open sand.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer around the wildlife crossings.', '<span class="months">Oct–Nov</span> 🍄 <b>Fungi</b> in the game forest.'], 'wild': ['🐦 Black woodpecker · Woodlark · Nightjar', '🦌 Red deer · Wild boar · Roe deer', '🦋 Speckled wood · Brimstone · Red admiral', '🌼 Bell heather · Bilberry · Wavy hair-grass', '🌳 Scots pine · Pedunculate oak · Beech'],
 'trail': ['Start at the <b>car park on the Oude Arnhemseweg</b> at the hamlet.', 'View the <b>wildlife crossing</b> from the game-viewing points on both sides.', 'Walk the <b>marked routes</b> towards Ugchelen, Beekbergen or Hoenderloo.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The A50 crosses the area — keep dogs close · 🚶 Forest and sand paths'
}))

C.append(mk.card(1766, 'Wekeromse Zand', {
 'tags': ['Gelderland · Wekerom/Lunteren', 'Stuifzandgebied van Geldersch Landschap & Kasteelen · celtic fields, grafheuvels en moeflons', 'list 36 · no. 485'],
 'loc': '📍 Ten zuidwesten van Wekerom en ten oosten van Lunteren · Stuifzand en heide · rode route vanaf de Vijfsprongweg of de Hoeverweg',
 'desc': 'Het <b>Wekeromse Zand</b> bij Wekerom is een van de laatste grote stuifzandgebieden van Noordwest-Europa en het pronkstuk van Geldersch Landschap &amp; Kasteelen op de zuidelijke Veluwe. Actief stuivend zand is buiten Nederland vrijwel verdwenen — hier is het nog te vinden in een ruim 500 hectare groot geheel van bos, heide en bouwland, met in de kern open zandvlaktes, diep uitgestoven laagten en grillige ‘forten’ van begroeid zand. Het gebied is al duizenden jaren bewoond: akkers uit de ijzertijd (celtic fields), grafheuvels en de zogenoemde Germaanse put getuigen ervan. De <b>rode route</b> van circa 7,5 kilometer voert over de raatakkers, door heide en langs de zandranden; een korte blauwe kindvriendelijke route is er ook. Moeflons en heidekoeien houden het landschap open. Honden zijn er niet welkom en delen van het terrein zijn rustgebied voor edelhert en wild zwijn. Starten kan bij de parkeerplaats aan de Vijfsprongweg bij de IJzertijdboerderij (Lunteren) of aan de Hoeverweg in Wekerom; aan de rand ligt een wildobservatiepost.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — laag licht over het zand.',
 'why': ['Een van de <b>laatste grote stuifzandgebieden</b> van Noordwest-Europa.', 'De <b>celtic fields, grafheuvels en Germaanse put</b> uit de prehistorie.', 'De <b>rode route van 7,5 km</b> over raatakkers en heide.', 'De kans op <b>edelhert en moeflon</b> aan de gebiedsrand.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Zandblauwtje</b> en muizenoor bloeien op het zand.', '<span class="months">Mei–Aug</span> 🐦 <b>Boomleeuwerik</b> en nachtzwaluw boven de vlaktes.', '<span class="months">Aug</span> 🟣 <b>Heidebloei</b> tussen de zandvlaktes.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de omgeving.'], 'wild': ['🐦 Nachtzwaluw · Boomleeuwerik · Geelgors', '🦌 Edelhert · Ree · Wild zwijn', '🐑 Moeflon · Brandrode heidekoe', '🦎 Zandhagedis · Levendbarende hagedis', '🌼 Struikhei · Zandzegge · Buntgras'],
 'trail': ['Start bij de <b>parkeerplaats aan de Vijfsprongweg</b> (bij de IJzertijdboerderij, Lunteren).', 'Volg de <b>rode route (7,5 km)</b> of de korte blauwe kinderroute.', 'Parkeren kan ook aan de <b>Hoeverweg</b> in Wekerom; gebruik de wildobservatiepost.'],
 'foot': '🐕 Honden niet toegestaan · 💶 Gratis · ⚠️ Stuifzand en rustgebieden — blijf op de paden · 🚶 Zand- en heidepaden'
}, {
 'tags': ['Gelderland · Wekerom/Lunteren', 'Drift-sand area of Geldersch Landschap & Kasteelen · Celtic fields, burial mounds and mouflons', 'list 36 · no. 485'],
 'loc': '📍 South-west of Wekerom and east of Lunteren · Drift sand and heath · red route from the Vijfsprongweg or the Hoeverweg',
 'desc': 'The <b>Wekeromse Zand</b> near Wekerom is one of the last large drift-sand areas of north-west Europe and the showpiece of Geldersch Landschap &amp; Kasteelen on the southern Veluwe. Actively drifting sand has almost vanished outside the Netherlands — here it can still be found in a whole of more than 500 hectares of forest, heath and arable land, with open sand plains in the core, deeply blown-out hollows and gnarled ‘forts’ of vegetated sand. The area has been inhabited for thousands of years: Iron Age fields (Celtic fields), burial mounds and the so-called Germanic well bear witness to that. The <b>red route</b> of about 7.5 kilometres leads over the ridge-and-furrow fields (raatakkers), through heath and along the sand edges; a short blue child-friendly route also exists. Mouflons and heath cattle keep the landscape open. Dogs are not welcome here and parts of the terrain are a rest area for red deer and wild boar. You can start at the car park on the Vijfsprongweg by the Iron Age Farm (Lunteren) or on the Hoeverweg in Wekerom; a wildlife observation post lies on the edge.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or late afternoon — low light over the sand.',
 'why': ['One of the <b>last large drift-sand areas</b> of north-west Europe.', 'The <b>Celtic fields, burial mounds and Germanic well</b> from prehistory.', 'The <b>red route of 7.5 km</b> over ridge-and-furrow fields and heath.', 'The chance of <b>red deer and mouflon</b> on the edge of the area.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Sand sedge</b> and mouse-ear hawkweed bloom on the sand.', '<span class="months">May–Aug</span> 🐦 <b>Woodlark</b> and nightjar above the plains.', '<span class="months">Aug</span> 🟣 <b>Heather bloom</b> between the sand plains.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the surroundings.'], 'wild': ['🐦 Nightjar · Woodlark · Yellowhammer', '🦌 Red deer · Roe deer · Wild boar', '🐑 Mouflon · Red-and-white heath cattle', '🦎 Sand lizard · Viviparous lizard', '🌼 Bell heather · Sand sedge · Grey hair-grass'],
 'trail': ['Start at the <b>car park on the Vijfsprongweg</b> (by the Iron Age Farm, Lunteren).', 'Follow the <b>red route (7.5 km)</b> or the short blue children’s route.', 'Parking is also possible on the <b>Hoeverweg</b> in Wekerom; use the wildlife observation post.'],
 'foot': '🐕 Dogs not allowed · 💶 Free · ⚠️ Drift sand and rest areas — stay on the paths · 🚶 Sand and heath paths'
}))

C.append(mk.card(1767, 'Het Luntersche Buurtbos', {
 'tags': ['Gelderland · Lunteren/Ede', 'Dorpsbos van de Stichting Luntersche Buurtbosch · padenpatroon als blad · rijksmonument', 'list 36 · no. 486'],
 'loc': '📍 Aan de oostkant van Lunteren, ten zuiden van de Boslaan · Bos · onder de Goudsberg, tegen het Wekeromse Zand',
 'desc': 'Het <b>Luntersche Buurtbos</b> is het bos dat een heel dorp bezit — het enige bos in Nederland dat ooit aan een dorp werd geschonken. Na de verdeling van de gemeenschappelijke buurtgronden in 1890 kocht notaris J. H. Th. W. van den Ham de woeste heidepercelen van Lunteren op en liet er in de winters met werklozen een bos aanplanten. Het padenpatroon kreeg de vorm van een <b>tak met bladeren</b>; dat ontwerp is uniek en maakt het padenstelsel tot een <b>groen rijksmonument</b>. Bij zijn overlijden in 1912 schonk Van den Ham het bos aan de Stichting Het Luntersche Buurtbosch, die het tot op vandaag beheert ten bate van het dorp. Boven op de Galgenberg in het midden van het bos staat <b>De Koepel</b>, een uitkijktoren die in fasen met de bomen meegroeide en bij helder weer zicht biedt tot de Domtoren van Utrecht; naast de toren herdenkt een monument bestuurder Jacob Groeneveld. Ook liggen in het bos de Van-de-Ham-bank uit 1914 en een oude schaapskolk. Langs de Boslaan grenst het Pinetum met coniferen uit alle werelddelen. Routes van het wandelnetwerk Goudsberg en de wandeling Neerlands Midden doorkruisen het bos, dat overgaat in heide, vennetjes en het Wekeromse Zand.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt (herfstkleuren)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door de oude lanen.',
 'why': ['Het <b>unieke padenpatroon</b> van tak en bladeren als groen rijksmonument.', 'Het bijzondere verhaal van de <b>bosschenker aan het dorp</b> (1912).', 'De <b>uitkijktoren De Koepel</b> op de Galgenberg.', 'De overgang naar <b>heide, vennetjes en het Wekeromse Zand</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> en daslook in het loofbos.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het oude bos.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de aangrenzende veldjes.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van lanen en bladpaden.'], 'wild': ['🐦 Zwarte specht · Boomklever · Grote bonte specht', '🦌 Ree · Wild zwijn · Eekhoorn', '🦋 Bont zandoogje · Citroenvlinder · Dagpauwoog', '🌼 Bosanemoon · Dalkruid · Lelietje-van-dalen', '🌳 Beuk · Zomereik · Grove den'],
 'trail': ['Start bij <b>Het Bosbad</b> aan de Boslaan 89/91 in Lunteren.', 'Volg de <b>gemarkeerde routes</b> van de Stichting over de bladpaden.', 'Beklim <b>De Koepel</b> en wandel door naar het Pinetum of het Wekeromse Zand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Rijksmonument — blijf op de paden · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Lunteren/Ede', 'Village wood of the Luntersche Buurtbosch Foundation · path pattern shaped like a leaf · national monument', 'list 36 · no. 486'],
 'loc': '📍 On the eastern side of Lunteren, south of the Boslaan · Woodland · below the Goudsberg, against the Wekeromse Zand',
 'desc': 'The <b>Luntersche Buurtbos</b> is the wood that an entire village owns — the only forest in the Netherlands ever presented to a village. After the division of the common community lands in 1890, notary J. H. Th. W. van den Ham bought up the barren heath plots of Lunteren and had a forest planted on them in the winters with unemployed workers. The path pattern was given the shape of a <b>branch with leaves</b>; that design is unique and makes the path system a <b>green national monument</b>. At his death in 1912 Van den Ham donated the wood to the Het Luntersche Buurtbosch Foundation, which manages it to this day for the benefit of the village. On top of the Galgenberg in the middle of the wood stands <b>De Koepel</b>, a lookout tower that grew up in stages together with the trees and, in clear weather, offers a view as far as the Dom Tower of Utrecht; next to the tower a monument commemorates the administrator Jacob Groeneveld. The wood also contains the Van-de-Ham bench from 1914 and an old sheep-washing pool. Along the Boslaan lies the Pinetum with conifers from all over the world. Routes of the Goudsberg walking network and the Neerlands Midden walk cross the wood, which merges into heath, pools and the Wekeromse Zand.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct (autumn colours)<br>\n    <b>Best time of day:</b> Morning — light through the old avenues.',
 'why': ['The <b>unique path pattern</b> of branch and leaves as a green national monument.', 'The special story of the <b>wood donated to the village</b> (1912).', 'The <b>lookout tower De Koepel</b> on the Galgenberg.', 'The transition to <b>heath, pools and the Wekeromse Zand</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> and wild garlic in the broadleaf wood.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old forest.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the adjacent fields.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of avenues and leaf paths.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Great spotted woodpecker', '🦌 Roe deer · Wild boar · Squirrel', '🦋 Speckled wood · Brimstone · Peacock', '🌼 Wood anemone · May lily · Lily of the valley', '🌳 Beech · Pedunculate oak · Scots pine'],
 'trail': ['Start at <b>Het Bosbad</b> on the Boslaan 89/91 in Lunteren.', 'Follow the <b>marked routes</b> of the Foundation over the leaf paths.', 'Climb <b>De Koepel</b> and walk on to the Pinetum or the Wekeromse Zand.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ National monument — stay on the paths · 🚶 Forest and sand paths'
}))

C.append(mk.card(1768, 'Doesburgerheide', {
 'tags': ['Gelderland · Ede', 'Voormalige heide van de Doesburgerbuurt · Doesburgermolen, wildwal en de Doesburger Eng', 'list 36 · no. 487'],
 'loc': '📍 Tussen Ede en Lunteren, ten noorden van de Doesburger Eng · Heide, eng en bosranden · rond de Doesburgermolen',
 'desc': 'De <b>Doesburgerheide</b> is de voormalige gemeenschappelijke heide van de Doesburgerbuurt, het oude buurtschap ten noorden van Ede tussen landgoed Kernhem en Lunteren. De heide lag op het hogere, drogere deel van de buurt, ten oosten van de <b>Doesburger Eng</b> waarvan zij werd gescheiden door een oude <b>wildwal</b>; de beroemde Hessenweg doorsneed het gebied. Eeuwenlang graasden er schapen, werden plaggen gestoken voor de potstallen en werd er zand en grind gewonnen — de grondstoffen waarmee de engen eeuwenlang werden opgehoogd tot hun kenmerkende, golvende akkers. Na de markenverdeling in de negentiende eeuw werd de heide verdeeld onder particulieren en raakte het gebied geleidelijk bebost en ontgonnen; plannen om er het eerste vliegveld van Nederland aan te leggen deden de grondprijzen opspringen, maar het kwam er niet. Vandaag is het een kleinschalig coulissenlandschap van bosranden, heiderestanten, wildwallen, engen en weilanden, doorkruist door het <b>Doesburgermolenpad</b>, een klompenpad van 8 kilometer langs de <b>Doesburgermolen</b> — een van de oudste windmolens van Nederland — en langs akkerranden die in de zomer vol bloemen staan.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, mei–jun (oranjetipje), jul (bloeiende akkerranden)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig over de eng.',
 'why': ['Het <b>cultuurlandschap</b> van heide, wildwal en golvende engakkers.', 'De <b>Doesburgermolen</b>, een van de oudste windmolens van Nederland.', 'Het <b>Doesburgermolenpad</b> over boerenland en langs oude wallen.', 'De <b>bloeiende akkerranden</b> vol vlinders en bijen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🦋 <b>Oranjetipje</b> fladdert langs de bosranden.', '<span class="months">Jun–Jul</span> 🌼 <b>Bijen- en bloemenranden</b> bloeien langs de akkers.', '<span class="months">Jul–Aug</span> 🐦 <b>Weidevogels</b> en zwaluwen boven de eng.', '<span class="months">Sep</span> 🌾 <b>Oogsttijd</b> op de akkers van de eng.'], 'wild': ['🐦 Torenvalk · Boerenzwaluw · Geelgors', '🦌 Ree · Haas · Egel', '🦋 Oranjetipje · Klein koolwitje · Citroenvlinder', '🌼 Klaproos · Korenbloem · Wilde peen', '🌳 Zomereik · Haagbeuk · Sleedoorn'],
 'trail': ['Start bij <b>Landgoed Kernhem</b> (Kernhemseweg 3, Ede) en volg het Doesburgermolenpad.', 'Verkort de route onderweg tot 5 km bij de Doesburgermolen.', 'Combineer met het <b>Luntersche Buurtbos</b> of landgoed Kernhem.'],
 'foot': '🐕 Honden niet toegestaan op het klompenpad · 💶 Gratis · ⚠️ Boerenland — blijf op de paden · 🚶 Zand-, graspaden en landweggetjes'
}, {
 'tags': ['Gelderland · Ede', 'Former heath of the Doesburgerbuurt · Doesburgermolen, game bank and the Doesburger Eng', 'list 36 · no. 487'],
 'loc': '📍 Between Ede and Lunteren, north of the Doesburger Eng · Heath, open field and forest edges · around the Doesburgermolen',
 'desc': 'The <b>Doesburgerheide</b> is the former common heath of the Doesburgerbuurt, the old hamlet north of Ede between the Kernhem estate and Lunteren. The heath lay on the higher, drier part of the neighbourhood, east of the <b>Doesburger Eng</b>, from which it was separated by an old <b>game bank</b> (wildwal); the famous Hessenweg crossed the area. For centuries sheep grazed there, sods were cut for the pot-stables and sand and gravel were won — the raw materials with which the engen (communal open fields) were raised over the centuries into their characteristic, rolling arable fields. After the division of the commons in the nineteenth century the heath was parcelled out among private owners and the area gradually became forested and reclaimed; plans to build the first airport of the Netherlands there sent land prices leaping, but it never happened. Today it is a small-scale enclosure landscape of forest edges, heath remnants, game banks, open fields and meadows, crossed by the <b>Doesburgermolenpad</b>, a clompenpad (farmland walking route) of 8 kilometres past the <b>Doesburgermolen</b> — one of the oldest windmills of the Netherlands — and along field margins that stand full of flowers in summer.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, May–Jun (orange tip), Jul (blooming field margins)<br>\n    <b>Best time of day:</b> Morning — quiet over the open field.',
 'why': ['The <b>cultural landscape</b> of heath, game bank and rolling open-field acres.', 'The <b>Doesburgermolen</b>, one of the oldest windmills of the Netherlands.', 'The <b>Doesburgermolenpad</b> over farmland and along old banks.', 'The <b>blooming field margins</b> full of butterflies and bees.'],
 'phen': ['<span class="months">Apr–May</span> 🦋 <b>Orange tip</b> flutters along the forest edges.', '<span class="months">Jun–Jul</span> 🌼 <b>Bee and flower margins</b> bloom along the fields.', '<span class="months">Jul–Aug</span> 🐦 <b>Meadow birds</b> and swallows above the open field.', '<span class="months">Sep</span> 🌾 <b>Harvest time</b> on the fields of the Eng.'], 'wild': ['🐦 Kestrel · Barn swallow · Yellowhammer', '🦌 Roe deer · Hare · Hedgehog', '🦋 Orange tip · Small white · Brimstone', '🌼 Poppy · Cornflower · Wild carrot', '🌳 Pedunculate oak · Hornbeam · Blackthorn'],
 'trail': ['Start at <b>Kernhem estate</b> (Kernhemseweg 3, Ede) and follow the Doesburgermolenpad.', 'Shorten the route en route to 5 km at the Doesburgermolen.', 'Combine with the <b>Luntersche Buurtbos</b> or the Kernhem estate.'],
 'foot': '🐕 Dogs not allowed on the clompenpad · 💶 Free · ⚠️ Farmland — stay on the paths · 🚶 Sand and grass paths and farm lanes'
}))

C.append(mk.card(1769, 'Allemanskamp', {
 'tags': ['Gelderland · Ederveen', 'Blauwgrasland in een komvormige laagte · natte natuur van Staatsbosbeheer bij Ederveen', 'list 36 · no. 488'],
 'loc': '📍 Tussen Ederveen en de provinciale weg De Klomp–Renswoude · Natuurgebied in de Gelderse Vallei · niet toegankelijk',
 'desc': 'De <b>Allemanskamp</b> is een natuurgebied van Staatsbosbeheer in de Gelderse Vallei, tussen Ederveen en de provinciale weg De Klomp–Renswoude. Het terrein ligt in een komvormige laagte en is van oudsher nat: er kwamen <b>schrale hooilanden</b> voor, gevoed door kwelwater. Daar groeien de planten van nat, voedselarm grasland — blauwe zegge, blauwe knoop, kale jonker en orchideeën — het zeldzame <b>blauwgrasland</b> waar de Vallei beroemd om is. Maar door watergangen als de centraal gelegen Munnikebeek droogde het gebied steeds verder uit en verdwenen de kwelplanten. Daarom werd tussen oktober 2025 en maart 2026 een grootschalig herstel uitgevoerd: de fosfaatrijke bovengrond werd afgegraven, kavelsloten gedempt, de Munnikebeek kreeg een omleiding en er werd bosplantsoen ingeplant, zodat het grondwater de wortelzone weer kan bereiken en de hooilanden zich opnieuw tot blauwgrasland ontwikkelen. Het terrein is vanwege de kwetsbare vegetatie <b>niet toegankelijk</b>, maar vanaf de omringende wegen en fietspaden is het natte, bloemrijke schouwspel van juni prima te zien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jun</b> (bloei), jan–mrt (water en vogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht over het natte grasland.',
 'why': ['Het zeldzame <b>blauwgrasland</b> van de Gelderse Vallei.', 'De <b>natte, kwelrijke laagte</b> rond de Munnikebeek.', 'Het recente <b>grootschalige herstel</b> van de verdroging.', 'De bloei in juni met <b>orchideeën en blauwe knoop</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌊 <b>Kwel en hoog water</b> in de laagte.', '<span class="months">Mei–Jun</span> 🌼 <b>Blauwgrasland bloeit</b>: blauwe knoop en orchideeën.', '<span class="months">Jun–Jul</span> 🦋 <b>Vlinders</b> boven het bloemrijke gras.', '<span class="months">Okt–Nov</span> 🐦 <b>Trekvogels</b> rusten op de natte percelen.'], 'wild': ['🐦 Grutto · Tureluur · Watersnip', '🦋 Zilveren maan · Hooibeestje · Bruin blauwtje', '🌼 Blauwe knoop · Blauwe zegge · Kale jonker', '🌼 Orchideeën · Klokjesgentiaan · Spaanse ruiter', '🌳 Zomereik · Bosplantsoen · Riet'],
 'trail': ['Bekijk het gebied vanaf de <b>omringende wegen en fietspaden</b> rond Ederveen.', 'Wandel of fiets langs de <b>rand van de Gelderse Vallei</b>.', 'Combineer met de <b>Binnenveldse Hooilanden</b> en het Binnenveld.'],
 'foot': '🐕 Niet toegankelijk — honden aan de rand aanlijnen · 💶 Gratis · ⚠️ Kwetsbare vegetatie: terrein niet betreden · 🚶 Kijkend vanaf wegen en fietspaden'
}, {
 'tags': ['Gelderland · Ederveen', 'Blue-grassland in a bowl-shaped hollow · wet nature of Staatsbosbeheer near Ederveen', 'list 36 · no. 488'],
 'loc': '📍 Between Ederveen and the De Klomp–Renswoude provincial road · Nature area in the Gelderse Vallei · not accessible',
 'desc': 'The <b>Allemanskamp</b> is a nature area of Staatsbosbeheer in the Gelderse Vallei, between Ederveen and the De Klomp–Renswoude provincial road. The terrain lies in a bowl-shaped hollow and has traditionally been wet: <b>species-poor hay meadows</b> (schrale hooilanden) occurred there, fed by seepage water. In them grow the plants of wet, nutrient-poor grassland — blue sedge, devil’s-bit scabious, meadow thistle and orchids — the rare <b>blue grassland</b> for which the Vallei is famous. But watercourses such as the centrally located Munnikebeek drained the area ever further and the seepage plants disappeared. Therefore a large-scale restoration was carried out between October 2025 and March 2026: the phosphate-rich topsoil was stripped, field ditches were filled in, the Munnikebeek was diverted and scrub was planted, so that the groundwater can reach the root zone again and the hay meadows can develop into blue grassland once more. Because of the vulnerable vegetation the terrain is <b>not accessible</b>, but from the surrounding roads and cycle paths the wet, flower-rich spectacle of June is easy to see.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (flowering), Jan–Mar (water and birds)<br>\n    <b>Best time of day:</b> Morning — light over the wet grassland.',
 'why': ['The rare <b>blue grassland</b> of the Gelderse Vallei.', 'The <b>wet, seepage-rich hollow</b> around the Munnikebeek.', 'The recent <b>large-scale restoration</b> of the desiccation.', 'The June flowering with <b>orchids and devil’s-bit scabious</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌊 <b>Seepage and high water</b> in the hollow.', '<span class="months">May–Jun</span> 🌼 <b>Blue grassland blooms</b>: devil’s-bit scabious and orchids.', '<span class="months">Jun–Jul</span> 🦋 <b>Butterflies</b> above the flower-rich grass.', '<span class="months">Oct–Nov</span> 🐦 <b>Migrating birds</b> rest on the wet plots.'], 'wild': ['🐦 Black-tailed godwit · Redshank · Snipe', '🦋 Silver-studded blue · Small heath · Brown argus', '🌼 Devil’s-bit scabious · Blue sedge · Meadow thistle', '🌼 Orchids · Gentianella · Marsh helloborine', '🌳 Pedunculate oak · Planted scrub · Reed'],
 'trail': ['View the area from the <b>surrounding roads and cycle paths</b> around Ederveen.', 'Walk or cycle along the <b>edge of the Gelderse Vallei</b>.', 'Combine with the <b>Binnenveldse Hooilanden</b> and the Binnenveld.'],
 'foot': '🐕 Not accessible — keep dogs on lead on the edge · 💶 Free · ⚠️ Vulnerable vegetation: do not enter · 🚶 Viewing from roads and cycle paths'
}))

mk.insert(C, '1764')
mk.progress(1769)
mk.check()
