# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1760, 'Kootwijk', {
 'tags': ['Gelderland · Kootwijk/Apeldoorn', 'Boswachterij met het Kootwijkerzand · grootste actieve stuifzand van West-Europa', 'list 36 · no. 479'],
 'loc': '📍 Rond Kootwijk en Radio Kootwijk, gemeente Apeldoorn · Boswachterij en stuifzand · in het hart van de Veluwe',
 'desc': 'De <b>boswachterij Kootwijk</b> van Staatsbosbeheer ligt rond het dorp Kootwijk en het voormalige zenderpark Radio Kootwijk, in het hart van de Veluwe. Het middelpunt is het <b>Kootwijkerzand</b>: met circa 700 hectare het grootste actieve stuifzandgebied van West-Europa, de kern van een aaneengesloten stuifzand- en heidecomplex van zo’n 1.800 hectare. Hier waait het zand nog echt — tussen grillige vliegdennen, uitgestoven laagten en jeneverbesstruwelen, met vennen aan de randen. Het is het rijk van nachtzwaluw, boomleeuwerik en levendbarende hagedis, en van edelhert en wild zwijn dat bij zonsopgang de open vlaktes oversteekt. Aan de rand staat de 13,5 meter hoge uitkijktoren <b>De Zandloper</b>, vanwaar je de kale zandvlakte en de omringende bossen overziet. De korte oranje paaltjesroute van Staatsbosbeheer (3 km) start bij de parkeerplaats aan de Houtvester van ’t Hoffweg; wie verder wil loopt het <b>Boswachterspad Kootwijk</b> (18,6 km) of het Veluws Rondje Kootwijk (8 km). Parkeren is er gratis.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heide en zand), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Zonsopgang of schemering — wild en stilte op het zand.',
 'why': ['Het <b>grootste actieve stuifzand</b> van West-Europa.', 'De 13,5 meter hoge uitkijktoren <b>De Zandloper</b>.', 'De kans op <b>edelhert en wild zwijn</b> op de open vlaktes.', 'De <b>eeuwenoude cultuurhistorie</b> met grafheuvels en vliegdennen.'],
 'phen': ['<span class="months">Apr–Aug</span> 🐦 <b>Nachtzwaluw</b> en boomleeuwerik boven het zand.', '<span class="months">Aug</span> 🟣 <b>Struikhei</b> kleurt de heiderand paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de boswachterij.', '<span class="months">Okt–Nov</span> 🍄 <b>Paddenstoelen</b> in de bossen rond het zand.'], 'wild': ['🐦 Nachtzwaluw · Boomleeuwerik · Geelgors', '🦌 Edelhert · Wild zwijn · Ree', '🦎 Levendbarende hagedis · Zandhagedis', '🌼 Struikhei · Jeneverbes · Zandzegge', '🌳 Grove den · Ruwe berk · Jeneverbes'],
 'trail': ['Parkeer aan de <b>Houtvester van ’t Hoffweg</b> en loop de oranje route (3 km).', 'Beklim <b>De Zandloper</b> aan de rand van het stuifzand.', 'Wandel het <b>Boswachterspad Kootwijk</b> (18,6 km) of het Veluws Rondje (8 km).'],
 'foot': '🐕 Honden aangelijnd (niet op het stuifzand) · 💶 Gratis · ⚠️ Stuifzand kwetsbaar — blijf op de paden · 🚶 Zand-, bos- en heidepaden'
}, {
 'tags': ['Gelderland · Kootwijk/Apeldoorn', 'Forest district with the Kootwijkerzand · largest active drift-sand area of Western Europe', 'list 36 · no. 479'],
 'loc': '📍 Around Kootwijk and Radio Kootwijk, Apeldoorn municipality · Forest district and drift sand · in the heart of the Veluwe',
 'desc': 'The <b>Kootwijk forest district</b> of Staatsbosbeheer lies around the village of Kootwijk and the former radio park Radio Kootwijk, in the heart of the Veluwe. Its centrepiece is the <b>Kootwijkerzand</b>: at about 700 hectares the largest active drift-sand area of Western Europe, the core of a continuous drift-sand and heath complex of some 1,800 hectares. Here the sand still really blows — between gnarled pioneer pines, wind-scoured hollows and juniper scrub, with pools on the edges. It is the realm of the nightjar, woodlark and viviparous lizard, and of red deer and wild boar crossing the open plains at sunrise. On the edge stands the 13.5-metre-high lookout tower <b>De Zandloper</b>, from which you overlook the bare sand plain and the surrounding forests. The short orange marker-post route of Staatsbosbeheer (3 km) starts at the car park on the Houtvester van ’t Hoffweg; those who want to go further walk the <b>Boswachterspad Kootwijk</b> (18.6 km) or the Veluws Rondje Kootwijk (8 km). Parking is free.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather and sand), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Sunrise or dusk — game and silence on the sand.',
 'why': ['The <b>largest active drift sand</b> of Western Europe.', 'The 13.5-metre-high lookout tower <b>De Zandloper</b>.', 'The chance of <b>red deer and wild boar</b> on the open plains.', 'The <b>centuries-old cultural history</b> with burial mounds and pioneer pines.'],
 'phen': ['<span class="months">Apr–Aug</span> 🐦 <b>Nightjar</b> and woodlark above the sand.', '<span class="months">Aug</span> 🟣 <b>Bell heather</b> colours the heath edge purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the forest district.', '<span class="months">Oct–Nov</span> 🍄 <b>Fungi</b> in the forests around the sand.'], 'wild': ['🐦 Nightjar · Woodlark · Yellowhammer', '🦌 Red deer · Wild boar · Roe deer', '🦎 Viviparous lizard · Sand lizard', '🌼 Bell heather · Juniper · Sand sedge', '🌳 Scots pine · Silver birch · Juniper'],
 'trail': ['Park on the <b>Houtvester van ’t Hoffweg</b> and walk the orange route (3 km).', 'Climb <b>De Zandloper</b> on the edge of the drift sand.', 'Walk the <b>Boswachterspad Kootwijk</b> (18.6 km) or the Veluws Rondje (8 km).'],
 'foot': '🐕 Dogs on lead (not on the drift sand) · 💶 Free · ⚠️ Drift sand is vulnerable — stay on the paths · 🚶 Sand, forest and heath paths'
}))

C.append(mk.card(1761, 'Ugchelen-Hoenderloo', {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Boswachterij van Staatsbosbeheer · van de zuidrand van Apeldoorn tot Hoenderloo, met ’t Leesten en Hoog Buurlo', 'list 36 · no. 480'],
 'loc': '📍 Tussen de zuidrand van Apeldoorn en Hoenderloo, gemeente Apeldoorn · Boswachterij · start bij Informatiecentrum ’t Leesten',
 'desc': 'De <b>boswachterij Ugchelen-Hoenderloo</b> van Staatsbosbeheer strekt zich uit van de zuidrand van Apeldoorn tot aan Hoenderloo en is een van de wildrijkste gebieden van de Veluwe. De bossen zijn ontstaan uit de oude markenbossen van Ugchelen en Beekbergen en vormden lang het <b>Staatswildreservaat</b> — vanuit dit reservaat werd na de Tweede Wereldoorlog de edelhertenstand van de hele Veluwe weer opgebouwd. Het startpunt bij uitstek is <b>Informatiecentrum ’t Leesten</b> aan de Hoenderloseweg, in Bospaviljoen ’t Leesten, met een grote gratis parkeerplaats, speelbos, hondenlosloopgebied en een brasserie. Vanaf hier voeren routes de bossen en heidevelden in: over <b>Hoog Buurlo</b> met zijn twee schaapskooien, naar Radio Kootwijk of over de Hoog Buurlose Heide via de rode <b>Heidewandeling</b> (circa 12 km). Bij de Hoog Buurlose Heide ligt wildscherm <b>De Ringakker</b>, waar edelherten en wilde zwijnen van dichtbij te zien zijn; het gele rondje voert langs de schaapskooien en gezinnen lopen het korte Kabouterpad.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of schemering — wild bij De Ringakker.',
 'why': ['Het <b>voormalige Staatswildreservaat</b>, de wieg van de Veluwse edelherten.', 'De <b>heide van Hoog Buurlo</b> met twee schaapskooien.', 'Het <b>wildscherm De Ringakker</b> voor wildspotten.', 'Informatiecentrum <b>’t Leesten</b> als makkelijk startpunt.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Voorjaarsflora</b> langs bosranden en heide.', '<span class="months">Jun–Aug</span> 🐑 <b>Schaapskudden</b> op de heide van Hoog Buurlo.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de Hoog Buurlose Heide.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten rond De Ringakker.'], 'wild': ['🐦 Zwarte specht · Boomleeuwerik · Nachtzwaluw', '🦌 Edelhert · Wild zwijn · Ree', '🐑 Drents heideschaap · Schotse hooglander', '🌼 Struikhei · Dophei · Blauwe bosbes', '🌳 Grove den · Beuk · Zomereik'],
 'trail': ['Start bij <b>Informatiecentrum ’t Leesten</b> (Hoenderloseweg 191, gratis parkeren).', 'Volg de rode <b>Heidewandeling</b> (±12 km) of het gele Hoog Buurlo-rondje.', 'Ga wildspotten bij <b>wildscherm De Ringakker</b> aan de Hoog Buurlose Heide.'],
 'foot': '🐕 Honden aangelijnd (losloopgebied bij ’t Leesten) · 💶 Gratis · ⚠️ Rustgebieden voor wild — blijf op de paden · 🚶 Bos-, heide- en zandpaden'
}, {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Forest district of Staatsbosbeheer · from the southern edge of Apeldoorn to Hoenderloo, with ’t Leesten and Hoog Buurlo', 'list 36 · no. 480'],
 'loc': '📍 Between the southern edge of Apeldoorn and Hoenderloo, Apeldoorn municipality · Forest district · start at Information Centre ’t Leesten',
 'desc': 'The <b>Ugchelen-Hoenderloo forest district</b> of Staatsbosbeheer stretches from the southern edge of Apeldoorn to Hoenderloo and is one of the most game-rich areas of the Veluwe. The forests grew from the old common woods (markenbossen) of Ugchelen and Beekbergen and long formed the <b>State Wildlife Reserve</b> — after the Second World War the red deer population of the whole Veluwe was rebuilt from this reserve. The obvious starting point is <b>Information Centre ’t Leesten</b> on the Hoenderloseweg, in Bospaviljoen ’t Leesten, with a large free car park, play forest, dog exercise area and a brasserie. From here routes lead into the forests and heath fields: over <b>Hoog Buurlo</b> with its two sheep folds, towards Radio Kootwijk, or over the Hoog Buurlose Heide on the red <b>Heidewandeling</b> (about 12 km). At the Hoog Buurlose Heide lies the wildlife screen <b>De Ringakker</b>, where red deer and wild boar can be watched close up; the yellow circuit passes the sheep folds and families walk the short Kabouterpad.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Morning or dusk — game at De Ringakker.',
 'why': ['The <b>former State Wildlife Reserve</b>, cradle of the Veluwe red deer.', 'The <b>heath of Hoog Buurlo</b> with its two sheep folds.', 'The <b>wildlife screen De Ringakker</b> for game watching.', 'Information Centre <b>’t Leesten</b> as an easy start.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Spring flora</b> along forest edges and heath.', '<span class="months">Jun–Aug</span> 🐑 <b>Sheep flocks</b> on the heath of Hoog Buurlo.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the Hoog Buurlose Heide.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer around De Ringakker.'], 'wild': ['🐦 Black woodpecker · Woodlark · Nightjar', '🦌 Red deer · Wild boar · Roe deer', '🐑 Drenthe heath sheep · Highland cattle', '🌼 Bell heather · Cross-leaved heath · Bilberry', '🌳 Scots pine · Beech · Pedunculate oak'],
 'trail': ['Start at <b>Information Centre ’t Leesten</b> (Hoenderloseweg 191, free parking).', 'Follow the red <b>Heidewandeling</b> (±12 km) or the yellow Hoog Buurlo circuit.', 'Watch game at <b>wildlife screen De Ringakker</b> on the Hoog Buurlose Heide.'],
 'foot': '🐕 Dogs on lead (exercise area at ’t Leesten) · 💶 Free · ⚠️ Game rest areas — stay on the paths · 🚶 Forest, heath and sand paths'
}))

C.append(mk.card(1762, 'Bos te Hoenderloo', {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Klein bos van het SBNL Natuurfonds (5,5 ha) · omvorming van naald- naar loofbos', 'list 36 · no. 481'],
 'loc': '📍 Hoenderloo, gemeente Apeldoorn · Bos · aan de Otterloseweg (N304), bereikbaar via de Weikamperweg',
 'desc': 'Het <b>Bos te Hoenderloo</b> is een klein bos van het <b>SBNL Natuurfonds</b> van slechts 5,5 hectare, aan de rand van Hoenderloo en ingebed in een groot boscomplex waarvan Staatsbosbeheer de grootste eigenaar is. Het terrein werd in 1988 verkregen uit de nalatenschap van mevrouw Van de Kemp, weduwe van de heer Jacobus Hendrikus Mosterd. Het is van oudsher een naaldbos met een ondergroei van pijpenstrootje, blauwe bosbes en struikhei. De beheerder koos in 2000 voor een opmerkelijke ommezwaai: tachtig procent van de grove dennen en douglassparren werd gekapt om het bos naar <b>loofbos</b> om te vormen. Door de hoge wilddruk overleefden maar een beperkt aantal beuken — die door herten worden ‘gesnoeid’ — maar de natuurlijke verjonging van grove den en lariks won het uiteindelijk van de vraat. Sporen van wilde zwijnen laten zien dat de dichte dekking als schuilplaats wordt gewaardeerd. Het bos is vrij toegankelijk; de ingang ligt aan de Weikamperweg, een zandpad vanaf de parkeerplaats aan de Otterloseweg bij hectometerpaal 20,2.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, okt–nov (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — vogelzang en verse wildsporen.',
 'why': ['Een <b>klein natuurreservaat</b> van een particuliere fondsbeheerder.', 'De <b>omvorming van naald- naar loofbos</b> als levend experiment.', 'De <b>wroetsporen en wildwissels</b> van wilde zwijnen en herten.', 'De rust: een <b>stil bos</b> net buiten Hoenderloo.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Voorjaarsgroen</b> onder de opengekapte kronen.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in het jonge loofbos.', '<span class="months">Okt–Nov</span> 🍄 <b>Paddenstoelen</b> op dood hout en strooisel.', '<span class="months">Heel jaar</span> 🐗 <b>Wildsporen</b> van zwijnen en herten.'], 'wild': ['🐦 Grote bonte specht · Boomklever · Goudhaan', '🦌 Ree · Edelhert · Wild zwijn', '🦋 Bont zandoogje · Citroenvlinder · Atalanta', '🌼 Blauwe bosbes · Struikhei · Pijpenstrootje', '🌳 Grove den · Lariks · Beuk'],
 'trail': ['Parkeer aan de <b>Otterloseweg</b> (N304) en loop de Weikamperweg in.', 'Volg de <b>bosrand</b> rond het terrein en de doorgaande bospaden.', 'Combineer met de <b>bossen van Hoenderloo</b> en ’t Leesten.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Klein reservaat — blijf op de paden · 🚶 Zand- en bospaden'
}, {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Small forest of the SBNL Natuurfonds (5.5 ha) · conversion from conifer to broadleaf wood', 'list 36 · no. 481'],
 'loc': '📍 Hoenderloo, Apeldoorn municipality · Woodland · on the Otterloseweg (N304), reached via the Weikamperweg',
 'desc': 'The <b>Bos te Hoenderloo</b> is a small forest of the <b>SBNL Natuurfonds</b> of only 5.5 hectares, on the edge of Hoenderloo and embedded in a large forest complex of which Staatsbosbeheer is the largest owner. The terrain was acquired in 1988 from the estate of Mrs Van de Kemp, widow of Mr Jacobus Hendrikus Mosterd. Traditionally it is a conifer wood with an undergrowth of purple moor-grass, bilberry and bell heather. In 2000 the manager chose a remarkable turnabout: eighty per cent of the Scots pines and Douglas firs were felled to convert the forest into <b>broadleaf woodland</b>. Because of the high pressure from game only a limited number of beeches survived — pruned, as it were, by deer — but the natural regeneration of Scots pine and larch eventually overcame the browsing. Traces of wild boar show that the dense cover is valued as a hiding place. The forest is freely accessible; the entrance lies on the Weikamperweg, a sand track from the car park on the Otterloseweg at hectometre post 20.2.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Oct–Nov (fungi)<br>\n    <b>Best time of day:</b> Morning — birdsong and fresh game tracks.',
 'why': ['A <b>small nature reserve</b> of a private fund manager.', 'The <b>conversion from conifer to broadleaf wood</b> as a living experiment.', 'The <b>rooting traces and game trails</b> of wild boar and deer.', 'The peace: a <b>quiet wood</b> just outside Hoenderloo.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Spring greenery</b> under the opened-up crowns.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the young broadleaf wood.', '<span class="months">Oct–Nov</span> 🍄 <b>Fungi</b> on dead wood and litter.', '<span class="months">All year</span> 🐗 <b>Game tracks</b> of boar and deer.'], 'wild': ['🐦 Great spotted woodpecker · Nuthatch · Goldcrest', '🦌 Roe deer · Red deer · Wild boar', '🦋 Speckled wood · Brimstone · Red admiral', '🌼 Bilberry · Bell heather · Purple moor-grass', '🌳 Scots pine · Larch · Beech'],
 'trail': ['Park on the <b>Otterloseweg</b> (N304) and walk into the Weikamperweg.', 'Follow the <b>forest edge</b> around the terrain and the through forest paths.', 'Combine with the <b>forests of Hoenderloo</b> and ’t Leesten.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Small reserve — stay on the paths · 🚶 Sand and forest paths'
}))

C.append(mk.card(1763, 'Het Spoek', {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Bos- en recreatiegebied aan de westrand van Hoenderloo · naam betekent ‘spook’', 'list 36 · no. 482'],
 'loc': '📍 Westrand van Hoenderloo, gemeente Apeldoorn · Bos en kampeerterrein · tussen de N304 en de Hoog Buurlose Heide',
 'desc': 'Het <b>Spoek</b> is het bos- en recreatiegebied aan de westrand van Hoenderloo, op de grens van de bebouwde kom en de uitgestrekte bossen en heidevelden van de boswachterij Ugchelen-Hoenderloo. De naam is Veluws dialect voor <b>‘spook’</b> — en wie er in de schemering wandelt begrijpt waarom: onder het hoge kronendak van grove den en beuk is het stil en donker, en overal in de bosbodem wroeten wilde zwijnen. Midden in het bos ligt vakantiepark ’t Spoek, dat sinds 1933 wordt geëxploiteerd en ooit werd opgericht door de geheelonthoudersbeweging: arbeidersgezinnen konden er voor weinig geld een gezonde, alcoholvrije vakantie houden op de Veluwe. Het park ligt er nog steeds rustig bij, omringd door bos. Staatsbosbeheer heeft aan de rand van Hoenderloo parkeerplaats Waterberg ingericht, vanwaar wandelroutes de bossen en de heide richting Hoog Buurlo en Ugchelen ingaan; vanaf de paden zie je wroetsporen, wildwissels en in de schemering reeën en zwijnen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heide), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Schemering — wild wordt actief.',
 'why': ['Het <b>stille ‘spookbos’</b> aan de rand van Hoenderloo.', 'De kans op <b>wilde zwijnen en reeën</b> in de schemering.', 'De bijzondere <b>kampeergeschiedenis</b> sinds 1933.', 'De routes naar de <b>Hoog Buurlose Heide</b> en ’t Leesten.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemoon</b> en voorjaarsgroen in het bos.', '<span class="months">Jun–Aug</span> 🐦 <b>Bosvogels</b> rond het kampeerterrein.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de nabije heide.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de omgeving.'], 'wild': ['🐦 Zwarte specht · Kuifmees · Goudhaan', '🐗 Wild zwijn · Ree · Edelhert', '🦋 Bont zandoogje · Citroenvlinder · Kleine vos', '🌼 Blauwe bosbes · Struikhei · Lelietje-van-dalen', '🌳 Grove den · Beuk · Zomereik'],
 'trail': ['Parkeer bij <b>parkeerplaats Waterberg</b> aan de rand van Hoenderloo.', 'Wandel de <b>gemarkeerde routes</b> richting Hoog Buurlo en Ugchelen.', 'Combineer met de <b>Hoog Buurlose Heide</b> en Informatiecentrum ’t Leesten.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Wildgebied — rustig aan, zeker in de schemering · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Hoenderloo/Apeldoorn', 'Forest and recreation area on the western edge of Hoenderloo · the name means ‘ghost’', 'list 36 · no. 482'],
 'loc': '📍 Western edge of Hoenderloo, Apeldoorn municipality · Woodland and campsite · between the N304 and the Hoog Buurlose Heide',
 'desc': 'The <b>Spoek</b> is the forest and recreation area on the western edge of Hoenderloo, on the border of the built-up area and the vast forests and heath fields of the Ugchelen-Hoenderloo forest district. The name is Veluwe dialect for <b>‘ghost’</b> — and anyone walking there at dusk understands why: under the high canopy of Scots pine and beech it is quiet and dark, and wild boar root everywhere in the forest floor. In the middle of the wood lies holiday park ’t Spoek, operated since 1933 and originally founded by the teetotal movement: working-class families could enjoy a healthy, alcohol-free holiday on the Veluwe for little money. The park is still quietly set there, surrounded by forest. Staatsbosbeheer has laid out car park Waterberg on the edge of Hoenderloo, from which walking routes enter the forests and the heath towards Hoog Buurlo and Ugchelen; from the paths you see rooting traces, game trails and, at dusk, roe deer and boar.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather), Sep–Oct (rutting)<br>\n    <b>Best time of day:</b> Dusk — game becomes active.',
 'why': ['The <b>quiet ‘ghost wood’</b> on the edge of Hoenderloo.', 'The chance of <b>wild boar and roe deer</b> at dusk.', 'The special <b>camping history</b> since 1933.', 'The routes to the <b>Hoog Buurlose Heide</b> and ’t Leesten.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemone</b> and spring greenery in the wood.', '<span class="months">Jun–Aug</span> 🐦 <b>Woodland birds</b> around the campsite.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the nearby heath.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer in the surroundings.'], 'wild': ['🐦 Black woodpecker · Crested tit · Goldcrest', '🐗 Wild boar · Roe deer · Red deer', '🦋 Speckled wood · Brimstone · Small tortoiseshell', '🌼 Bilberry · Bell heather · Lily of the valley', '🌳 Scots pine · Beech · Pedunculate oak'],
 'trail': ['Park at <b>car park Waterberg</b> on the edge of Hoenderloo.', 'Walk the <b>marked routes</b> towards Hoog Buurlo and Ugchelen.', 'Combine with the <b>Hoog Buurlose Heide</b> and Information Centre ’t Leesten.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Game area — be quiet, especially at dusk · 🚶 Forest and sand paths'
}))

C.append(mk.card(1764, 'Kruisvoorde', {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Straat- en buurtnaam aan de bosrand · ‘voorde’-toponiem in het sprengenlandschap', 'list 36 · no. 483'],
 'loc': '📍 Aan de bosrand van Ugchelen, gemeente Apeldoorn · woonbuurt en bosrand · nabij De Kooiberg en het Van der Huchtbos',
 'desc': '<b>Kruisvoorde</b> is vandaag een straat- en buurtnaam aan de zuidelijke bosrand van Ugchelen, in de wijk De Bouwhof, waar de huizen direct tegen de bossen van de Veluwe aanliggen. De naam is veel ouder dan de straat: een <b>voorde</b> is de klassieke benaming voor een doorwaadbare plek in een beek of spreng — een ondiep punt waar mensen, vee en karren konden oversteken — en het voorvoegsel <b>kruis</b> wijst op een kruispunt van wegen bij zo’n overgang of op een veldkruis dat er stond. De naam past naadloos in het sprengenlandschap van de zuidelijke Veluwerand, waar tientallen voorden de oversteken over sprengen en beekjes markeerden. Als zelfstandig natuurgebied is Kruisvoorde niet gedocumenteerd — deze kaart beschrijft het naamgebied en zijn omgeving. Wie de straat uitloopt staat meteen in het bos: de bossen van de boswachterij Ugchelen-Hoenderloo met op loopafstand het wandelgebied rond De Kooiberg en het Van der Huchtbos, de Ugchelse Enk en twee hondenlosloopbossen van de gemeente Apeldoorn.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (omgeving), okt (herfstkleuren)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustige bosrand.',
 'why': ['Het <b>eeuwenoude ‘voorde’-toponiem</b> aan de sprengenrand.', 'De directe overgang van <b>woonwijk naar Veluwebos</b>.', 'De ligging tussen <b>De Kooiberg en het Van der Huchtbos</b>.', 'De nabije <b>hondenlosloopbossen</b> van Apeldoorn.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Voorjaarsflora</b> langs de bosrand.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in de aangrenzende bossen.', '<span class="months">Aug</span> 🟣 <b>Struikhei</b> bloeit in de heiderestanten.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van de bosrand.'], 'wild': ['🐦 Zwarte specht · Boomklever · Roodborst', '🦌 Ree · Wild zwijn · Eekhoorn', '🦋 Bont zandoogje · Citroenvlinder · Atalanta', '🌼 Blauwe bosbes · Struikhei · Bosanemoon', '🌳 Grove den · Beuk · Zomereik'],
 'trail': ['Loop vanaf de <b>Kruisvoorde</b> (wijk De Bouwhof) zo het bos in.', 'Volg de <b>rondwandelingen</b> richting De Kooiberg en ’t Leesten.', 'Combineer met de <b>Ugchelse Enk</b> en het Van der Huchtbos.'],
 'foot': '🐕 Honden aangelijnd (losloopbossen in de buurt) · 💶 Gratis · ⚠️ Woonbuurt — parkeer niet voor opritten · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Ugchelen/Apeldoorn', 'Street and neighbourhood name on the forest edge · ‘voorde’ place name in the spring-stream landscape', 'list 36 · no. 483'],
 'loc': '📍 On the forest edge of Ugchelen, Apeldoorn municipality · residential area and forest edge · near De Kooiberg and the Van der Huchtbos',
 'desc': '<b>Kruisvoorde</b> is today a street and neighbourhood name on the southern forest edge of Ugchelen, in the De Bouwhof district, where the houses lie directly against the forests of the Veluwe. The name is much older than the street: a <b>voorde</b> (ford) is the classic term for a place where a brook or spring stream could be crossed — a shallow point where people, cattle and carts could pass — and the prefix <b>kruis</b> (cross) points to a crossing of roads at such a ford or to a wayside cross that stood there. The name fits seamlessly into the spring-stream (sprengen) landscape of the southern Veluwe edge, where dozens of fords marked the crossings over spring streams and brooks. As an independent nature area Kruisvoorde is not documented — this card describes the name area and its surroundings. Those who walk to the end of the street are straight in the forest: the woods of the Ugchelen-Hoenderloo forest district with, within walking distance, the walking area around De Kooiberg and the Van der Huchtbos, the Ugchelse Enk and two dog exercise woods of the municipality of Apeldoorn.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (surroundings), Oct (autumn colours)<br>\n    <b>Best time of day:</b> Morning — quiet forest edge.',
 'why': ['The <b>centuries-old ford place name</b> on the spring-stream edge.', 'The direct transition from <b>residential area to Veluwe forest</b>.', 'The location between <b>De Kooiberg and the Van der Huchtbos</b>.', 'The nearby <b>dog exercise woods</b> of Apeldoorn.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Spring flora</b> along the forest edge.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the adjacent forests.', '<span class="months">Aug</span> 🟣 <b>Bell heather</b> blooms in the heath remnants.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of the forest edge.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Robin', '🦌 Roe deer · Wild boar · Squirrel', '🦋 Speckled wood · Brimstone · Red admiral', '🌼 Bilberry · Bell heather · Wood anemone', '🌳 Scots pine · Beech · Pedunculate oak'],
 'trail': ['Walk from <b>Kruisvoorde</b> (De Bouwhof district) straight into the forest.', 'Follow the <b>circular walks</b> towards De Kooiberg and ’t Leesten.', 'Combine with the <b>Ugchelse Enk</b> and the Van der Huchtbos.'],
 'foot': '🐕 Dogs on lead (exercise woods nearby) · 💶 Free · ⚠️ Residential area — do not block driveways · 🚶 Forest and sand paths'
}))

mk.insert(C, '1759')
mk.progress(1764)
mk.check()
