# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1840, 'De Vrijenberg', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Landgoed met de Vrijenbergerspreng en de hoogste waterval van Nederland · bos, spreng en watervallen', 'list 36 · no. 559'],
 'loc': '📍 Ten noorden van Loenen, rond de Beekbergerweg · Landgoed van 73 hectare met spreng en watervallen · start bij de parkeerplaats aan de Beekbergerweg',
 'desc': '<b>De Vrijenberg</b> is een particulier landgoed van circa <b>73 hectare</b> bij Loenen op de oostelijke Veluwe, met het huis Bronkhorst en zacht glooiende naald- en gemengde bossen. Het landgoed grenst aan de bekendste waterattractie van de Veluwe: de <b>Loenense waterval</b>, met circa 15 meter de hoogste van Nederland. Die waterval is niet natuurlijk, maar het resultaat van negentiende-eeuwse waterbouw. Tussen <b>1848 en 1865</b> werd het kanaal Apeldoorn–Dieren gegraven; om de diepgang in het kanaal op peil te houden, werden sprengen gegraven en beken omgeleid. Zo ontstond de <b>Vrijenbergerspreng</b>, die al in 1657 in de kronieken wordt genoemd en tussen 1874 en 1876 met schop en kruiwagen werd uitgraven in een bestaand erosiedal en verlengd tot de Veldhuizerspreng. Vanaf de oorsprong van de spreng in het Schalterbos tot onder de grote waterval is er een totaal verval van <b>15,5 meter</b>; vlak bij de Beekbergerweg valt het water in vier trappen 7,13 meter naar beneden. Over het landgoed loopt de <b>Vrijenbergwandelroute</b> (circa 6 kilometer), die ook langs zorgboerderij Open Erf De Groote Modderkolk en de oude sprengkoppen voert — een wandeling langs water, wal en bos in de sfeer van weleer.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, okt–apr (veel water in de spreng), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig bij de waterval.',
 'why': ['De <b>Loenense waterval</b>: de hoogste van Nederland (circa 15 m).', 'De <b>Vrijenbergerspreng</b> met een totaal verval van 15,5 meter.', 'Het <b>73 hectare grote landgoed</b> met huis Bronkhorst en glooiende bossen.', 'De <b>Vrijenbergwandelroute</b> langs spreng, wal en watervallen.'],
 'phen': ['<span class="months">Heel jaar</span> 💧 <b>Waterval en spreng</b> in bedrijf.', '<span class="months">Okt–Apr</span> 🌊 <b>Veel water</b> in de spreng na regen.', '<span class="months">Mrt–Jun</span> 🐦 <b>Spechten en zangvogels</b> in het bos.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> langs de beek.'],
 'wild': ['🐦 Zwarte specht · Grote gele kwikstaart (beek)', '🦌 Edelhert · Ree · Wild zwijn', '🦊 Vos · Boommarter', '🌳 Beuk · Zomereik · Grove den', '💧 Beekjuffer · Schaatsenrijder (spreng)'],
 'trail': ['Start bij de <b>parkeerplaats aan de Beekbergerweg</b> bij de waterval.', 'Volg de <b>Vrijenbergwandelroute</b> (circa 6 km) over het landgoed.', 'Bezoek onderweg <b>Open Erf De Groote Modderkolk</b> aan de Vrijenbergweg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Landgoed deels particulier — blijf op de paden; de waterval is glad bij nat weer · 🚶 Bos-, veld- en graspaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Estate with the Vrijenbergerspreng and the highest waterfall of the Netherlands · woodland, spring stream and waterfalls', 'list 36 · no. 559'],
 'loc': '📍 North of Loenen, around the Beekbergerweg · 73-hectare estate with spring stream and waterfalls · start at the car park on the Beekbergerweg',
 'desc': '<b>De Vrijenberg</b> is a private estate of about <b>73 hectares</b> near Loenen on the eastern Veluwe, with Bronkhorst house and gently rolling conifer and mixed woods. The estate borders the most famous water attraction of the Veluwe: the <b>Loenense waterval</b>, at about 15 metres the highest waterfall of the Netherlands. That waterfall is not natural, but the result of nineteenth-century water engineering. Between <b>1848 and 1865</b> the Apeldoorn–Dieren canal was dug; to keep the depth of the canal constant, spring streams were dug and brooks diverted. This is how the <b>Vrijenbergerspreng</b> came into being, already mentioned in chronicles in 1657, dug out between 1874 and 1876 with spade and wheelbarrow in an existing erosion valley and extended to the Veldhuizerspreng. From the source of the spring stream in the Schalterbos to below the great waterfall the total drop is <b>15.5 metres</b>; close to the Beekbergerweg the water falls 7.13 metres in four steps. Over the estate runs the <b>Vrijenberg walking route</b> (about 6 kilometres), which also passes the care farm Open Erf De Groote Modderkolk and the old spring heads — a walk along water, rampart and woodland in the atmosphere of days gone by.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Oct–Apr (much water in the spring stream), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet at the waterfall.',
 'why': ['The <b>Loenense waterval</b>: the highest of the Netherlands (about 15 m).', 'The <b>Vrijenbergerspreng</b> with a total drop of 15.5 metres.', 'The <b>73-hectare estate</b> with Bronkhorst house and rolling woods.', 'The <b>Vrijenberg walking route</b> along spring stream, rampart and waterfalls.'],
 'phen': ['<span class="months">All year</span> 💧 <b>Waterfall and spring stream</b> in operation.', '<span class="months">Oct–Apr</span> 🌊 <b>Much water</b> in the spring stream after rain.', '<span class="months">Mar–Jun</span> 🐦 <b>Woodpeckers and songbirds</b> in the wood.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> along the brook.'],
 'wild': ['🐦 Black woodpecker · Grey wagtail (brook)', '🦌 Red deer · Roe deer · Wild boar', '🦊 Fox · Pine marten', '🌳 Beech · Pedunculate oak · Scots pine', '💧 Demoiselle · Pond skater (spring stream)'],
 'trail': ['Start at the <b>car park on the Beekbergerweg</b> at the waterfall.', 'Follow the <b>Vrijenberg walking route</b> (about 6 km) over the estate.', 'Visit <b>Open Erf De Groote Modderkolk</b> on the Vrijenbergweg along the way.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Estate partly private — keep to the paths; the waterfall is slippery when wet · 🚶 Forest, field and grass paths'
}))

C.append(mk.card(1841, 'Hoeve Delle', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Bos- en stuifzandgebied van Natuurmonumenten ten westen van Loenen · oude schaapsheide met hoogteverschillen', 'list 36 · no. 560'],
 'loc': '📍 Ten westen van Loenen, ten noorden van de Groenendaalse weg en grenzend aan de Reeënberg · Bos, heide en stuifduinen van Natuurmonumenten · start bij P Ramenberg of P Waterval',
 'desc': '<b>Hoeve Delle</b> is een bos- en stuifzandgebied van <b>Natuurmonumenten</b> ten westen van het dorp Loenen, ten noorden van de Groenendaalse weg en grenzend aan de Reeënberg. De naam verwijst naar de <b>dellen</b>: de lage delen van het glooiende landschap waar de oude wegen liepen — vanaf Hoeve Delle voerden de meeste wegen naar herberg De Woeste Hoeve, en op enkele plekken zijn nog karresporen van de Hessen te zien, de Duitse kooplui die met hun wagens naar de grote steden trokken. Vroeger graasden op de heidevelden van het gebied vele schaapskuddes uit Loenen. Het karakter van het landschap is die van de oostelijke Veluwe: bossen met flinke hoogteverschillen, oude stuifduinen, jeneverbessen en open plekken waar dikke Amerikaanse eiken en blauwe bosbes groeien. In het gebied liggen de infiltratiebekkens van drinkwaterbedrijf Vitens. Natuurmonumenten stelt de jeneverbessen vrij, onderhoudt de bossen en vormt het productiebos om naar een natuurlijker bos met dood hout. Er leven wilde zwijnen, vossen en boommarters, en ook edelherten, reeën en de zwarte specht voelen zich hier thuis. Een <b>wandelroute van circa 12 kilometer</b> start bij de parkeerplaats bij de watervallen aan de Beekbergerweg en voert dwars door het glooiende land.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, sep–okt (bronst), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond — wild en stilte.',
 'why': ['Het <b>glooiende bos- en stuifzandlandschap</b> met hoogteverschillen.', 'De <b>cultuurhistorie</b>: dellen, Hessenwegen en oude schaapsheide.', 'De <b>rijke wildstand</b>: edelhert, wild zwijn, vos en boommarter.', 'De <b>lange wandelroute van circa 12 km</b> door het gebied.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de open veldjes.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst van edelherten</b> in de omgeving.', '<span class="months">Mrt–Mei</span> 🐦 <b>Spechten roffelen</b> in het bos.', '<span class="months">Okt–Mrt</span> 🐗 <b>Wildsporen</b> op de zandpaden.'],
 'wild': ['🐗 Wild zwijn · Edelhert · Ree', '🦊 Vos · Boommarter · Das', '🐦 Zwarte specht · Boomklever · Raaf', '🌲 Grove den · Amerikaanse eik · Jeneverbes', '🫐 Blauwe bosbes · Struikhei'],
 'trail': ['Start bij de <b>parkeerplaats bij de watervallen</b> aan de Beekbergerweg en loop de route van 12 km.', 'Of start bij <b>P Ramenberg</b> aan de Groenendaalse weg.', 'Combineer met de <b>Reeënberg</b> of de Loenense watervallen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Flinke hoogteverschillen — stevig schoeisel · 🚶 Bos-, zand- en heidepaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Forest and drifting-sand area of Natuurmonumenten west of Loenen · old sheep heath with elevation differences', 'list 36 · no. 560'],
 'loc': '📍 West of Loenen, north of the Groenendaalse weg and adjacent to the Reeënberg · Woodland, heath and drifting-sand dunes of Natuurmonumenten · start at P Ramenberg or P Waterval',
 'desc': '<b>Hoeve Delle</b> is a forest and drifting-sand area of <b>Natuurmonumenten</b> west of the village of Loenen, north of the Groenendaalse weg and adjacent to the Reeënberg. The name refers to the <b>dellen</b>: the low parts of the undulating landscape where the old roads ran — from Hoeve Delle most roads led to the Woeste Hoeve inn, and in a few places wheel ruts of the Hessen can still be seen, the German traders who carried their goods by wagon to the big cities. In the past, many sheep flocks from Loenen grazed on the heath fields of the area. The landscape has the character of the eastern Veluwe: woods with considerable elevation differences, old drifting-sand dunes, junipers and open spots where thick American oaks and bilberry grow. The infiltration basins of drinking-water company Vitens lie in the area. Natuurmonumenten frees the junipers, maintains the woods and is converting the production forest into a more natural forest with dead wood. Wild boar, foxes and pine martens live here, and red deer, roe deer and the black woodpecker also feel at home. A <b>walking route of about 12 kilometres</b> starts at the car park at the waterfalls on the Beekbergerweg and leads straight through the undulating country.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Sep–Oct (rut), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or evening — wildlife and silence.',
 'why': ['The <b>rolling forest and drifting-sand landscape</b> with elevation differences.', 'The <b>cultural history</b>: dellen, Hessen roads and old sheep heath.', 'The <b>rich wildlife</b>: red deer, wild boar, fox and pine marten.', 'The <b>long walking route of about 12 km</b> through the area.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the open patches.', '<span class="months">Sep–Oct</span> 🦌 <b>Red deer rut</b> in the surroundings.', '<span class="months">Mar–May</span> 🐦 <b>Woodpeckers drum</b> in the wood.', '<span class="months">Oct–Mar</span> 🐗 <b>Wildlife tracks</b> on the sand paths.'],
 'wild': ['🐗 Wild boar · Red deer · Roe deer', '🦊 Fox · Pine marten · Badger', '🐦 Black woodpecker · Nuthatch · Raven', '🌲 Scots pine · Red oak · Juniper', '🫐 Bilberry · Bell heather'],
 'trail': ['Start at the <b>car park at the waterfalls</b> on the Beekbergerweg and walk the 12-km route.', 'Or start at <b>P Ramenberg</b> on the Groenendaalse weg.', 'Combine with the <b>Reeënberg</b> or the Loenense waterfalls.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Considerable elevation differences — sturdy footwear · 🚶 Forest, sand and heath paths'
}))

C.append(mk.card(1842, 'Ramenberg', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Bos en heide van Natuurmonumenten ten zuiden van Loenen · stuifzandheuvels en de 69 meter hoge Ramenberg', 'list 36 · no. 561'],
 'loc': '📍 Ten zuiden van Loenen, langs de Groenendaalse weg richting De Woeste Hoeve · Bos en heide van Natuurmonumenten · parkeerplaats Ramenberg aan de Groenendaalse weg',
 'desc': 'De <b>Ramenberg</b> is een bos- en heidegebied van <b>Natuurmonumenten</b> ten zuiden van Loenen, tussen de oude weg over de Veluwe en de uitgestrekte Loenermark. Het natuurgebied is vernoemd naar de <b>Ramenberg</b>, met 69 meter het hoogste punt van het terrein — vanaf de top kijk je over de heide en de bossen van de oostelijke Veluwe. Het landschap is gevarieerd: heidevelden, bossen met naaldbomen en twee voormalige <b>stuifzandheuvels</b> die begroeid zijn geraakt met grove dennen. In een laagte in het westen ligt een oud naaldbos met een ondergroei van kraaiheide. Het gebied herinnert ook aan oude ambachten: in het oosten liggen enkele uitgesleten <b>zwerfkeien</b> waarop eekschillers vroeger de schors van eiken klopten — het looizuur uit die schors gebruikten leerlooiers voor het looien van leer. Over de Ramenberg lopen wandelroutes, een ruiterpad en het is een bekend wildgebied: edelhert, wild zwijn, vos en raaf komen er voor, en bij de rand van het gebied ligt een wildkijkscherm aan de Oude Arnhemse weg. Honden zijn welkom, mits aangelijnd. Het startpunt is de parkeerplaats Ramenberg aan de Groenendaalse weg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, aug–sep (heidebloei), sep–okt (bronst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond — wild en uitzicht.',
 'why': ['De <b>69 meter hoge Ramenberg</b> met uitzicht over heide en bos.', 'De <b>heidevelden en stuifzandheuvels</b> met grove dennen.', 'De <b>cultuurhistorie van de eekschillers</b> bij de oude zwerfkeien.', 'Het <b>wild</b>: edelhert, wild zwijn, vos en raaf.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> rond de heuvels.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronsttijd</b> in de omgeving.', '<span class="months">Mrt–Mei</span> 🐦 <b>Vogels</b> in bos en heide.', '<span class="months">Heel jaar</span> 🪨 <b>Zwerfkeien</b> van de eekschillers te zien.'],
 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🦊 Vos · Das', '🐦 Raaf · Boomleeuwerik · Zwarte specht', '🌲 Grove den · Struikhei · Kraaiheide', '🦋 Heideblauwtje · Bont zandoogje'],
 'trail': ['Start bij de <b>parkeerplaats Ramenberg</b> aan de Groenendaalse weg.', 'Beklim de <b>Ramenberg</b> voor het uitzicht over heide en bos.', 'Combineer met een bezoek aan het <b>wildkijkscherm</b> aan de Oude Arnhemse weg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Open heide en stuifzand — niet van de paden · 🚶 Bos-, heide- en zandpaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Forest and heath of Natuurmonumenten south of Loenen · drifting-sand hills and the 69-metre Ramenberg', 'list 36 · no. 561'],
 'loc': '📍 South of Loenen, along the Groenendaalse weg towards De Woeste Hoeve · Forest and heath of Natuurmonumenten · Ramenberg car park on the Groenendaalse weg',
 'desc': 'The <b>Ramenberg</b> is a forest and heath area of <b>Natuurmonumenten</b> south of Loenen, between the old road across the Veluwe and the extensive Loenermark. The nature area is named after the <b>Ramenberg</b>, at 69 metres the highest point of the terrain — from the top you look out over the heath and the woods of the eastern Veluwe. The landscape is varied: heath fields, coniferous woods and two former <b>drifting-sand hills</b> that have become overgrown with Scots pines. In a depression in the west lies an old conifer wood with an undergrowth of crowberry. The area also recalls old crafts: in the east lie some worn <b>erratic boulders</b> on which bark peelers once beat the bark from oaks — tanners used the tannic acid from that bark for tanning leather. Walking routes and a bridle path run over the Ramenberg, and it is a well-known wildlife area: red deer, wild boar, fox and raven occur here, and at the edge of the area lies a wildlife-viewing screen on the Oude Arnhemse weg. Dogs are welcome, on a lead. The start is the Ramenberg car park on the Groenendaalse weg.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Aug–Sep (heather bloom), Sep–Oct (rut)<br>\n    <b>Best time of day:</b> Morning or evening — wildlife and views.',
 'why': ['The <b>69-metre Ramenberg</b> with views over heath and forest.', 'The <b>heath fields and drifting-sand hills</b> with Scots pines.', 'The <b>cultural history of the bark peelers</b> at the old erratic boulders.', 'The <b>wildlife</b>: red deer, wild boar, fox and raven.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> around the hills.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting season</b> in the surroundings.', '<span class="months">Mar–May</span> 🐦 <b>Birds</b> in forest and heath.', '<span class="months">All year</span> 🪨 <b>Erratic boulders</b> of the bark peelers to be seen.'],
 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🦊 Fox · Badger', '🐦 Raven · Woodlark · Black woodpecker', '🌲 Scots pine · Bell heather · Crowberry', '🦋 Silver-studded blue · Speckled wood'],
 'trail': ['Start at the <b>Ramenberg car park</b> on the Groenendaalse weg.', 'Climb the <b>Ramenberg</b> for the view over heath and forest.', 'Combine with a visit to the <b>wildlife-viewing screen</b> on the Oude Arnhemse weg.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Open heath and drifting sand — keep to the paths · 🚶 Forest, heath and sand paths'
}))

C.append(mk.card(1843, 'Loenermark en Loenense Bos', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Uitgestrekt bos- en heidegebied ten zuiden en oosten van Loenen · voormalige markegronden, nu beheerd door Het Geldersch Landschap', 'list 36 · no. 562'],
 'loc': '📍 Ten zuiden en oosten van Loenen, tussen de Groenendaalse weg, Zilven en Eerbeek · Bos en heide in beheer bij Het Geldersch Landschap · start bij de schaapskooi (Droefakkers) of Landal Coldenhove',
 'desc': 'De <b>Loenermark</b> en het <b>Loenense Bos</b> vormen samen een van de grootste aaneengesloten bos- en heidegebieden van de oostelijke Veluwe, rond het dorp Loenen. De Loenermark bestond eeuwenlang grotendeels uit heidevelden met hier en daar vliegdennen en hakhout; het bos wordt al in de tiende eeuw genoemd. Het gebied behoorde tot de gemeenschappelijke gronden — de <b>Marke</b> — van de inwoners van Loenen, waar zij hun vee lieten grazen, plaggen staken en hout haalden. In 1932 kocht de gemeente Apeldoorn de grond van de markegenoten en liet er in werkverschaffingsprojecten zand en grind afgraven en op grote schaal bos aanplanten; grote delen werden diep omgespit. Het noordelijker gelegen <b>Loenense Bos</b> werd in 1938 aangekocht. Sinds 1993 zijn Loenermark en Loenense Bos in erfpacht bij <b>Het Geldersch Landschap</b>, dat de bossen omvormt naar natuurlijker bos en de heide — waaronder de uitgestrekte <b>Zilvense heide</b> — openhoudt met een kudde Veluwse heideschapen. De witte zwerfkeienroute (7 km) en gele zwerfkeienroute (13,5 km) voeren langs drinkpoelen, de Stenen Bank, de Trapjesberg en oude sprengenbeken. Edelhert, ree en wild zwijn voelen zich hier thuis.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, aug–sep (heidebloei Zilvense heide), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — rust en laag licht.',
 'why': ['Het <b>uitgestrekte bos- en heidegebied</b> van de oostelijke Veluwe.', 'De <b>Zilvense heide</b> met de kudde Veluwse heideschapen.', 'De <b>cultuurhistorie van de marke</b>: heide, hakhout en werkverschaffing.', 'De <b>zwerfkeienroutes</b> van 7 en 13,5 kilometer.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de Zilvense heide.', '<span class="months">Heel jaar</span> 🐑 <b>Veluwse heideschapen</b> bij de schaapskooi.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronsttijd</b> van edelherten.', '<span class="months">Jun–Aug</span> 🫐 <b>Bosbessen</b> langs de paden.'],
 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐑 Veluws heideschaap', '🐦 Zwarte specht · Boomleeuwerik · Raaf', '🦊 Vos · Boommarter', '🌲 Grove den · Zomereik · Struikhei'],
 'trail': ['Start bij de <b>schaapskooi aan de Droefakkers</b> en loop de witte of gele zwerfkeienroute.', 'Verken de <b>Zilvense heide</b> vanaf de uitgang bij Landal Coldenhove.', 'Combineer met de <b>Loenense waterval</b> of het dorp Loenen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Uitgestrekt gebied — neem water mee; heide gevoelig, blijf op de paden · 🚶 Bos-, heide- en zandpaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Extensive forest and heath area south and east of Loenen · former common grounds, now managed by Het Geldersch Landschap', 'list 36 · no. 562'],
 'loc': '📍 South and east of Loenen, between the Groenendaalse weg, Zilven and Eerbeek · Forest and heath managed by Het Geldersch Landschap · start at the sheep fold (Droefakkers) or Landal Coldenhove',
 'desc': 'The <b>Loenermark</b> and the <b>Loenense Bos</b> together form one of the largest continuous forest and heath areas of the eastern Veluwe, around the village of Loenen. For centuries the Loenermark consisted largely of heath fields with scattered self-sown pines and coppice; the wood is already mentioned in the tenth century. The area belonged to the common grounds — the <b>Marke</b> — of the inhabitants of Loenen, where they grazed their cattle, cut sods and gathered wood. In 1932 the municipality of Apeldoorn bought the land from the commoners and had sand and gravel dug and forest planted on a large scale in job-creation projects; large parts were dug over deeply. The more northerly <b>Loenense Bos</b> was purchased in 1938. Since 1993 the Loenermark and the Loenense Bos have been held in hereditary lease by <b>Het Geldersch Landschap</b>, which is converting the woods into more natural forest and keeps the heath — including the extensive <b>Zilvense heide</b> — open with a flock of Veluwe heath sheep. The white erratic-boulder route (7 km) and yellow erratic-boulder route (13.5 km) lead past drinking pools, the Stenen Bank, the Trapjesberg and old spring streams. Red deer, roe deer and wild boar feel at home here.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Aug–Sep (heather bloom on the Zilvense heide), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon — quiet and low light.',
 'why': ['The <b>extensive forest and heath area</b> of the eastern Veluwe.', 'The <b>Zilvense heide</b> with the flock of Veluwe heath sheep.', 'The <b>cultural history of the common grounds</b>: heath, coppice and job creation.', 'The <b>erratic-boulder routes</b> of 7 and 13.5 kilometres.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the Zilvense heide.', '<span class="months">All year</span> 🐑 <b>Veluwe heath sheep</b> at the sheep fold.', '<span class="months">Sep–Oct</span> 🦌 <b>Red deer rut</b>.', '<span class="months">Jun–Aug</span> 🫐 <b>Bilberries</b> along the paths.'],
 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐑 Veluwe heath sheep', '🐦 Black woodpecker · Woodlark · Raven', '🦊 Fox · Pine marten', '🌲 Scots pine · Pedunculate oak · Bell heather'],
 'trail': ['Start at the <b>sheep fold on the Droefakkers</b> and walk the white or yellow erratic-boulder route.', 'Explore the <b>Zilvense heide</b> from the exit at Landal Coldenhove.', 'Combine with the <b>Loenense waterval</b> or the village of Loenen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Extensive area — bring water; heath is sensitive, keep to the paths · 🚶 Forest, heath and sand paths'
}))

C.append(mk.card(1844, 'Steilhul', {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Oud markebos van circa 40 hectare, omringd door de Loenermark · beheer sinds 2020 bij Het Geldersch Landschap', 'list 36 · no. 563'],
 'loc': '📍 In de bossen ten oosten van Loenen, tussen de Dalenk en het landgoed Groenouwe · Oud markebos van circa 40 ha · bereikbaar vanaf het einde van de Dalenk',
 'desc': '<b>Steilhul</b> is een bosgebied van circa <b>40 hectare</b> in de bossen bij Loenen, vrijwel geheel omsloten door de uitgestrekte Loenermark. Het is een <b>oud markebos</b>: vroeger was het gemeenschappelijk bezit van het dorp Loenen en werd het beheerd als wild- en houtvoorraad, waar maar beperkt mocht worden gekapt. Jarenlang beheerde Natuurmonumenten het gebied; in <b>maart 2020</b> droeg de vereniging het beheer over aan <b>Het Geldersch Landschap</b> als onderdeel van een kavelruil tussen Staatsbosbeheer, Geldersch Landschap en Natuurmonumenten, zodat Steilhul en de omliggende Loenermark één aaneengesloten beheereenheid vormen. Het bos bestaat voornamelijk uit naaldbos en kent opvallende hoogteverschillen van 35 tot 60 meter boven NAP — het pad is er zo steil en ligt zo hol in het landschap dat het gebied er zijn naam aan zou danken: <b>steil</b> en <b>hul</b> (hol). Langs de oostgrens is de <b>enkwal</b> te zien, een in de zeventiende eeuw opgeworpen wal die de akkers en weilanden van Loenen tegen het wild beschermde. Het bos wordt doorsneden door een zandweg vanaf de Dalenk; de <b>zwerfkeienroute</b> loopt erdoorheen. Edelhert, wild zwijn, ree en vos komen voor, net als verschillende spechtensoorten; in de overgang van bos naar open land jagen buizerd, raaf, sperwer en bosuil.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–jun (zangvogels), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stil in het oude markebos.',
 'why': ['Het <b>oude markebos</b> van Loenen, nu beheerd door Het Geldersch Landschap.', 'De <b>opvallende hoogteverschillen</b> van 35 tot 60 meter.', 'De <b>zeventiende-eeuwse enkwal</b> langs de oostgrens.', 'De <b>rijkdom aan spechten en roofvogels</b>.'],
 'phen': ['<span class="months">Mrt–Jun</span> 🐦 <b>Spechten en zangvogels</b> in het bos.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronsttijd</b> van edelherten.', '<span class="months">Okt–Mrt</span> 🐗 <b>Wildsporen</b> op de zandweg.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in loof en naald.'],
 'wild': ['🦌 Edelhert · Wild zwijn · Ree · Vos', '🐦 Zwarte specht · Buizerd · Raaf · Sperwer · Bosuil', '🦡 Das (burchten in de omgeving)', '🌲 Grove den · Fijnspar · Zomereik', '🌿 Dood hout · Mossen en korstmossen'],
 'trail': ['Bereik Steilhul vanaf het <b>einde van de Dalenk</b> (doodlopende weg).', 'Loop de <b>korte rondwandeling van circa 4 km</b> door Steilhul en langs landgoed Groenouwe.', 'Combineer met de <b>Loenermark</b> of de zwerfkeienroutes.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Steile, holle paden — niet geschikt voor kinderwagens · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Loenen (Apeldoorn)', 'Old common woodland of about 40 hectares, enclosed by the Loenermark · managed by Het Geldersch Landschap since 2020', 'list 36 · no. 563'],
 'loc': '📍 In the woods east of Loenen, between the Dalenk and the Groenouwe estate · Old common woodland of about 40 ha · accessible from the end of the Dalenk',
 'desc': '<b>Steilhul</b> is a woodland of about <b>40 hectares</b> in the woods near Loenen, almost entirely enclosed by the extensive Loenermark. It is an <b>old common woodland</b>: in the past it was the communal property of the village of Loenen and was managed as a game and timber reserve, where only limited felling was allowed. For years Natuurmonumenten managed the area; in <b>March 2020</b> the society transferred management to <b>Het Geldersch Landschap</b> as part of a land-swap between Staatsbosbeheer, Geldersch Landschap and Natuurmonumenten, so that Steilhul and the surrounding Loenermark form one contiguous management unit. The wood consists mainly of conifers and shows striking elevation differences of 35 to 60 metres above sea level — the path is so steep and lies so hollow in the landscape that the area may owe its name to that: <b>steil</b> (steep) and <b>hul</b> (hollow). Along the eastern edge runs the <b>enkwal</b>, a rampart raised in the seventeenth century to protect the fields and meadows of Loenen from game. A sand road from the Dalenk cuts through the wood; the <b>erratic-boulder route</b> runs through it. Red deer, wild boar, roe deer and fox occur here, as do several woodpecker species; in the transition from forest to open land hunt buzzard, raven, sparrowhawk and tawny owl.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–Jun (songbirds), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the old common woodland.',
 'why': ['The <b>old common woodland</b> of Loenen, now managed by Het Geldersch Landschap.', 'The <b>striking elevation differences</b> of 35 to 60 metres.', 'The <b>seventeenth-century enkwal</b> along the eastern edge.', 'The <b>richness of woodpeckers and birds of prey</b>.'],
 'phen': ['<span class="months">Mar–Jun</span> 🐦 <b>Woodpeckers and songbirds</b> in the wood.', '<span class="months">Sep–Oct</span> 🦌 <b>Red deer rut</b>.', '<span class="months">Oct–Mar</span> 🐗 <b>Wildlife tracks</b> on the sand road.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in leaf and needle.'],
 'wild': ['🦌 Red deer · Wild boar · Roe deer · Fox', '🐦 Black woodpecker · Buzzard · Raven · Sparrowhawk · Tawny owl', '🦡 Badger (setts in the surroundings)', '🌲 Scots pine · Norway spruce · Pedunculate oak', '🌿 Dead wood · Mosses and lichens'],
 'trail': ['Reach Steilhul from the <b>end of the Dalenk</b> (dead-end road).', 'Walk the <b>short circuit of about 4 km</b> through Steilhul and past the Groenouwe estate.', 'Combine with the <b>Loenermark</b> or the erratic-boulder routes.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Steep, hollow paths — not suitable for prams · 🚶 Forest and sand paths'
}))

mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1844)
mk.check()
