# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1805, 'Warnsborn en Hoog Erf', {
 'tags': ['Gelderland · Arnhem (Bakenbergseweg)', 'Landgoederen van GLK rond hotel Groot Warnsborn · Klein Zwitserland en de lanenzesster van Hoog Erf', 'list 36 · no. 524'],
 'loc': '📍 Tussen Arnhem en Oosterbeek, aan de Bakenbergseweg/Amsterdamseweg · Landgoederen · start bij de parkeerplaats tegenover hotel Groot Warnsborn of het Roadhouse',
 'desc': '<b>Warnsborn</b> en <b>Hoog Erf</b> zijn twee herenigde landgoederen in de gordel tussen Arnhem en Oosterbeek. De naam Warnsborn betekent \u2019zuivere of heldere bron\u2019 en wordt al in 1428 genoemd; het grote landgoed ontstond in 1640 door samenvoeging van het Hoog Erf en Laag Erf door de Arnhemse burgemeester Everhard Everwijn. In 1894 werden de goederen weer gesplitst, tot Geldersch Landschap in 1932 Warnsborn en in 1944 Hoog Erf verwierf — Warnsborn was een van de eerste bezittingen van GLK. Het in de oorlog afgebrande landhuis werd in de jaren vijftig herbouwd als hotel Groot Warnsborn. Rond het huis ligt een negentiende-eeuws parkbos over een achttiende-eeuwse ontginningsstructuur, met de tuinaanleg van H. Copijn (1912–1915): rotstuin, rododendronvallei, terrassentuin en de beroemde \u2019Klein Zwitserland\u2019-zone, een sterk geaccidenteerd, deels kunstmatig aangelegd terrein met smalle beeklopen en houten bruggetjes. Verder zijn er een ijskelder, de Warnsbornerbeek met bronnetjes, vijvers, de Cirkelweg en weilanden met Lakenvelders. Het glooiende <b>Hoog Erf</b> (92 hectare) is het open voorterrein met weilanden, bloemrijke akkerranden en een stervormige structuur van zes beukenlanen — de \u2019lanenzesster\u2019. Op de heidevelden graast een kudde Veluwse heideschapen. Het Schaarsbergenpad (klompenpad) en de Rondwandeling Groot Warnsborn (7 km, vanaf het Roadhouse aan de Amsterdamseweg 467) doorkruisen de landgoederen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, apr–mei (rododendrons), aug (heide)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door de lanen.',
 'why': ['De <b>zeven eeuwen landgoedgeschiedenis</b> sinds de bron uit 1428.', 'De tuinaanleg van <b>H. Copijn</b> met rotstuin en rododendronvallei.', 'De romantische <b>Klein Zwitserland</b>-zone met beekjes en bruggetjes.', 'De <b>lanenzesster</b> en bloemrijke akkerranden van Hoog Erf.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Bosanemoon</b> in het parkbos.', '<span class="months">Apr–Mei</span> 🌸 <b>Rododendrons</b> in de vallei.', '<span class="months">Aug</span> 🟣 <b>Heidebloei</b> en schapen op de velden.', '<span class="months">Okt</span> 🍂 <b>Herfstlanen</b> van Hoog Erf.'], 'wild': ['🐑 Veluws heideschaap · Lakenvelder rund', '🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Das · Eekhoorn', '🌼 Bosanemoon · Daslook · Wilde hyacint', '🌳 Beuk (lanen) · Zomereik · Amerikaanse eik'],
 'trail': ['Parkeer bij het <b>Roadhouse</b> (Amsterdamseweg 467) of tegenover hotel Groot Warnsborn.', 'Loop de <b>Rondwandeling Groot Warnsborn</b> (7 km) over Warnsborn, Hoog Erf en Vijverberg.', 'Volg het <b>Schaarsbergenpad</b> (klompenpad) langs de schaapsdrift.'],
 'foot': '🐕 Honden aangelijnd (deels losloopgebied) · 💶 Gratis · ⚠️ Hotelpark en tuin — blijf op de paden · 🚶 Landgoed-, laan- en heidepaden'
}, {
 'tags': ['Gelderland · Arnhem (Bakenbergseweg)', 'Estates of GLK around hotel Groot Warnsborn · Klein Zwitserland and the six-pointed avenues of Hoog Erf', 'list 36 · no. 524'],
 'loc': '📍 Between Arnhem and Oosterbeek, on the Bakenbergseweg/Amsterdamseweg · Estates · start at the car park opposite hotel Groot Warnsborn or the Roadhouse',
 'desc': '<b>Warnsborn</b> and <b>Hoog Erf</b> are two reunited estates in the belt between Arnhem and Oosterbeek. The name Warnsborn means \u2018pure or clear spring\u2019 and is already mentioned in 1428; the great estate arose in 1640 through the merger of Hoog Erf and Laag Erf by the Arnhem mayor Everhard Everwijn. In 1894 the properties were split again, until Geldersch Landschap acquired Warnsborn in 1932 and Hoog Erf in 1944 — Warnsborn was one of GLK\u2019s first possessions. The manor house, burnt down in the war, was rebuilt in the 1950s as hotel Groot Warnsborn. Around the house lies a nineteenth-century park wood on an eighteenth-century reclamation structure, with the garden design of H. Copijn (1912–1915): rock garden, rhododendron valley, terraced garden and the famous \u2018Klein Zwitserland\u2019 zone, a strongly undulating, partly artificial terrain with narrow brook courses and wooden bridges. There are also an ice cellar, the Warnsbornerbeek with little springs, ponds, the Cirkelweg and meadows with Lakenvelder cattle. The rolling <b>Hoog Erf</b> (92 hectares) is the open foreland with meadows, flowery field margins and a star-shaped structure of six beech avenues — the \u2018six-pointed avenues\u2019. A flock of Veluwe heath sheep grazes the heath fields. The Schaarsbergenpad (clompenpad) and the Groot Warnsborn circuit walk (7 km, from the Roadhouse on the Amsterdamseweg 467) cross the estates.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Apr–May (rhododendrons), Aug (heather)<br>\n    <b>Best time of day:</b> Morning — light through the avenues.',
 'why': ['The <b>seven centuries of estate history</b> since the spring of 1428.', 'The garden design of <b>H. Copijn</b> with rock garden and rhododendron valley.', 'The romantic <b>Klein Zwitserland</b> zone with brooks and bridges.', 'The <b>six-pointed avenues</b> and flowery field margins of Hoog Erf.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Wood anemone</b> in the park wood.', '<span class="months">Apr–May</span> 🌸 <b>Rhododendrons</b> in the valley.', '<span class="months">Aug</span> 🟣 <b>Heather bloom</b> and sheep on the fields.', '<span class="months">Oct</span> 🍂 <b>Autumn avenues</b> of Hoog Erf.'], 'wild': ['🐑 Veluwe heath sheep · Lakenvelder cattle', '🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Badger · Red squirrel', '🌼 Wood anemone · Wild garlic · Bluebell', '🌳 Beech (avenues) · Pedunculate oak · Red oak'],
 'trail': ['Park at the <b>Roadhouse</b> (Amsterdamseweg 467) or opposite hotel Groot Warnsborn.', 'Walk the <b>Groot Warnsborn circuit</b> (7 km) over Warnsborn, Hoog Erf and Vijverberg.', 'Follow the <b>Schaarsbergenpad</b> (clompenpad) along the sheep drift.'],
 'foot': '🐕 Dogs on lead (partly off-lead area) · 💶 Free · ⚠️ Hotel park and garden — stay on the paths · 🚶 Estate, avenue and heath paths'
}))

C.append(mk.card(1806, 'Schaarsbergen', {
 'tags': ['Gelderland · Arnhem (Schaarsbergen)', 'Ontginningsdorp en landgoedbos van de gemeente Arnhem · demobos en toegang tot de Veluwezoom', 'list 36 · no. 525'],
 'loc': '📍 Ten noorden van Arnhem, tussen Kemperbergerweg, Koningsweg en Deelenseweg · Dorp en bos · start bij pannenkoekenhuis Den Strooper of de kerk van Schaarsbergen',
 'desc': '<b>Schaarsbergen</b> ligt als een groen dorp midden in de bossen ten noorden van Arnhem. Het begon in 1849 als ontginningsnederzetting op de kale Arnhemse heide: eerst kwamen er arbeidershuisjes voor de ontginners, later kerk en school. De gemeente Arnhem had tussen 1834 en 1854 circa 2.700 hectare heide verkocht ter ontginning; de familie Brantsen van kasteel Zijpendaal liet op het resterende landgoed arbeiders de heide en later het bos bewerken. In 1959 kocht de gemeente het landgoed Schaarsbergen van de erven Brantsen. In de tweede helft van de vorige eeuw legde de gemeente hier samen met een hogeschool een <b>demobos</b> aan: proefpercelen waarin verschillende beheermethoden naast elkaar werden toegepast en die nog altijd zichtbaar zijn. Rond het dorp liggen nu de landgoedbossen van de Koningsweg, de Maasbergse bossen, de Koningsheide en het open heideveld van de Westerheide; de militaire enclave van de Legerplaats Schaarsbergen herinnert aan het lange militaire gebruik van dit gebied. Het dorp is een geliefd startpunt: pannenkoekenhuis Den Strooper, wandelroutes naar de Posbank en Warnsborn en het Veluws Rondje Schaarsbergen beginnen er, en het Arnhems Oorlogsmuseum 40-45 ligt aan de Kemperbergerweg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug (heide), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in de landgoedbossen.',
 'why': ['Het <b>ontginningsdorp uit 1849</b> midden in het bos.', 'Het <b>demobos</b> met proefpercelen in verschillende beheerstijlen.', 'De ligging als <b>toegangspoort</b> tot Veluwezoom, Koningsheide en Warnsborn.', 'De sfeer van <b>bos, heide en militaire historie</b> rond het dorp.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Voorjaarsbloeiers</b> in de landgoedbossen.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> rond het dorp.', '<span class="months">Aug</span> 🟣 <b>Heidebloei</b> op Wester- en Koningsheide.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> in demobos en lanen.'], 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Edelhert · Ree · Wild zwijn', '🐿️ Eekhoorn · Das', '🦎 Zandhagedis · Levendbarende hagedis', '🌳 Grove den · Beuk · Zomereik'],
 'trail': ['Start bij <b>pannenkoekenhuis Den Strooper</b> of de parkeerplaats aan de Koningsweg.', 'Loop het <b>Veluws Rondje Schaarsbergen</b> (7 km) over heide en door bos.', 'Bezoek het <b>Arnhems Oorlogsmuseum 40-45</b> of wandel naar de Posbank.'],
 'foot': '🐕 Honden aangelijnd (losloopgebieden aangegeven) · 💶 Gratis · ⚠️ Militair terrein in de buurt — niet betreden · 🚶 Bos-, heide- en zandpaden'
}, {
 'tags': ['Gelderland · Arnhem (Schaarsbergen)', 'Reclamation village and estate forest of the municipality of Arnhem · demo forest and gateway to the Veluwezoom', 'list 36 · no. 525'],
 'loc': '📍 North of Arnhem, between Kemperbergerweg, Koningsweg and Deelenseweg · Village and forest · start at pancake house Den Strooper or the church of Schaarsbergen',
 'desc': '<b>Schaarsbergen</b> lies as a green village in the middle of the forests north of Arnhem. It began in 1849 as a reclamation settlement on the bare Arnhem heath: first came workers\u2019 cottages for the reclaimers, later a church and school. Between 1834 and 1854 the municipality of Arnhem had sold some 2,700 hectares of heath for reclamation; the Brantsen family of Zijpendaal Castle had workers cultivate the heath and later the forest on the remaining estate. In 1959 the municipality bought the Schaarsbergen estate from the Brantsen heirs. In the second half of the last century the municipality, together with a college, laid out a <b>demo forest</b> here: trial plots in which different management methods were applied side by side and which are still visible. Around the village now lie the estate woods of the Koningsweg, the Maasbergse bossen, the Koningsheide and the open heath field of the Westerheide; the military enclave of the Legerplaats Schaarsbergen recalls this area\u2019s long military use. The village is a popular starting point: pancake house Den Strooper, walking routes to the Posbank and Warnsborn and the Veluws Rondje Schaarsbergen begin there, and the Arnhem War Museum 40-45 lies on the Kemperbergerweg.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug (heather), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the estate woods.',
 'why': ['The <b>reclamation village from 1849</b> in the middle of the forest.', 'The <b>demo forest</b> with trial plots in different management styles.', 'Its position as a <b>gateway</b> to the Veluwezoom, Koningsheide and Warnsborn.', 'The atmosphere of <b>forest, heath and military history</b> around the village.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Spring bloomers</b> in the estate woods.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> around the village.', '<span class="months">Aug</span> 🟣 <b>Heather bloom</b> on Wester- and Koningsheide.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> in demo forest and avenues.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Red deer · Roe deer · Wild boar', '🐿️ Red squirrel · Badger', '🦎 Sand lizard · Viviparous lizard', '🌳 Scots pine · Beech · Pedunculate oak'],
 'trail': ['Start at <b>pancake house Den Strooper</b> or the car park on the Koningsweg.', 'Walk the <b>Veluws Rondje Schaarsbergen</b> (7 km) over heath and through forest.', 'Visit the <b>Arnhem War Museum 40-45</b> or walk to the Posbank.'],
 'foot': '🐕 Dogs on lead (off-lead areas indicated) · 💶 Free · ⚠️ Military terrain nearby — do not enter · 🚶 Forest, heath and sand paths'
}))

C.append(mk.card(1807, 'Koningsheide', {
 'tags': ['Gelderland · Arnhem-Noord', 'Heide en bos van de gemeente Arnhem (circa 200 ha) · hersteld na de brand van 1976 · bosreservaat sinds 2020', 'list 36 · no. 526'],
 'loc': '📍 Ten noorden van Arnhem bij Schaarsbergen, tussen de A50 en de bossen van Deelen · Heide en bos · start bij de parkeerplaats aan de Koningsweg 35',
 'desc': 'De <b>Koningsheide</b> is een verrassend rustig heide- en bosgebied van circa 200 hectare ten noorden van Arnhem, in de oksel van de A50 en de A12 en naast de bossen van de Koningsweg — de naam verwijst naar die eeuwenoude route waarlangs de Oranjes naar Paleis Het Loo reisden. Op 7 juli 1976 werd het gebied getroffen door een van de grootste bosbranden van Nederland: door extreme droogte en een harde oostenwind bereikten de vlammen dertig tot veertig meter hoogte en ging honderden hectares bos verloren — alleen twee monumentale beuken overleefden de vuurzee en staan er nog altijd. Daarna werd de heide opnieuw ingeplant: een deel van het bos stamt uit de periode 1922–1945, de rest groeide na de brand op. Nu is de Koningsheide een gevarieerd landschap van open heide, berken en dennen, waar Schotse hooglanders en IJslandse pony\u2019s de heide kort houden en edelherten, damherten, reeën en wilde zwijnen leven — bij het wildscherm aan de rand van een wildweide zijn ze vaak te zien. In 2020 wees de gemeente 70 hectare aan als <b>bosreservaat</b>, naast het oerbos op De Waterberg, zodat te vergelijken valt hoe nietsdoenbeheer zich ontwikkelt naast regulier beheer. Bijzonder is de <b>slenk</b>: een diep droogdal uit het einde van de voorlaatste ijstijd (Saalien), met reptielen, amfibieën en insecten. De Rap Rondje Koningsheide (7 km) en de Koningsheide-route (5,8 km) doorkruisen het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — wild bij het wildscherm.',
 'why': ['De <b>brandgeschiedenis van 1976</b> en de twee overlevende beuken.', 'Het <b>bosreservaat van 70 hectare</b> met nietsdoenbeheer.', 'De <b>slenk</b>, een droogdal uit de ijstijd.', 'Groot wild (edelhert, damhert, zwijn) <b>dicht bij Arnhem</b>.'],
 'phen': ['<span class="months">Jun–Aug</span> 🐄 <b>Hooglanders en pony\u2019s</b> grazen de heide open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> tussen berken en dennen.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten aan de randen.', '<span class="months">Heel jaar</span> 🦎 <b>Reptielen en amfibieën</b> in de slenk.'], 'wild': ['🦌 Edelhert · Damhert · Ree · Wild zwijn', '🐄 Schotse hooglander · IJslands paard', '🐦 Boompieper · Roodborsttapuit · Zwarte specht', '🦎 Zandhagedis · Levendbarende hagedis · Ringslang', '🌼 Struikhei · Dophei · Pijpenstrootje'],
 'trail': ['Parkeer aan de <b>Koningsweg 35</b> en loop de Koningsheide-route (5,8 km).', 'Zoek het <b>wildscherm</b> op voor uitzicht over de wildweide.', 'Verken de <b>slenk</b> en combineer met De Waterberg of Schaarsbergen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Wild rustgebied — blijf op de paden · 🚶 Heide-, bos- en zandpaden'
}, {
 'tags': ['Gelderland · Arnhem-Noord', 'Heath and forest of the municipality of Arnhem (about 200 ha) · recovered after the 1976 fire · forest reserve since 2020', 'list 36 · no. 526'],
 'loc': '📍 North of Arnhem near Schaarsbergen, between the A50 and the woods of Deelen · Heath and forest · start at the car park at Koningsweg 35',
 'desc': 'The <b>Koningsheide</b> is a surprisingly quiet heath and forest area of some 200 hectares north of Arnhem, in the fork of the A50 and A12 and beside the woods of the Koningsweg — the name refers to that age-old route along which the House of Orange travelled to Paleis Het Loo. On 7 July 1976 the area was hit by one of the largest forest fires of the Netherlands: through extreme drought and a hard easterly wind the flames reached thirty to forty metres high and hundreds of hectares of forest were lost — only two monumental beeches survived the inferno and still stand there. The heath was then replanted: part of the forest dates from 1922–1945, the rest grew up after the fire. Now the Koningsheide is a varied landscape of open heath, birches and pines, where Scottish Highland cattle and Icelandic horses keep the heath short and red deer, fallow deer, roe deer and wild boar live — often visible at the game screen on the edge of a game meadow. In 2020 the municipality designated 70 hectares as a <b>forest reserve</b>, alongside the primeval forest on De Waterberg, so that the development of non-intervention management can be compared with regular management. Special is the <b>slenk</b>: a deep dry valley from the end of the penultimate ice age (Saalian), with reptiles, amphibians and insects. The Rap Rondje Koningsheide (7 km) and the Koningsheide route (5.8 km) cross the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Early morning — game at the game screen.',
 'why': ['The <b>fire history of 1976</b> and the two surviving beeches.', 'The <b>70-hectare forest reserve</b> with non-intervention management.', 'The <b>slenk</b>, a dry valley from the ice age.', 'Large game (red deer, fallow deer, boar) <b>close to Arnhem</b>.'],
 'phen': ['<span class="months">Jun–Aug</span> 🐄 <b>Highland cattle and ponies</b> graze the heath open.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> between birches and pines.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer at the edges.', '<span class="months">All year</span> 🦎 <b>Reptiles and amphibians</b> in the slenk.'], 'wild': ['🦌 Red deer · Fallow deer · Roe deer · Wild boar', '🐄 Scottish Highland cattle · Icelandic horse', '🐦 Tree pipit · Stonechat · Black woodpecker', '🦎 Sand lizard · Viviparous lizard · Grass snake', '🌼 Bell heather · Cross-leaved heath · Purple moor-grass'],
 'trail': ['Park at <b>Koningsweg 35</b> and walk the Koningsheide route (5.8 km).', 'Find the <b>game screen</b> for views over the game meadow.', 'Explore the <b>slenk</b> and combine with De Waterberg or Schaarsbergen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Game rest area — stay on the paths · 🚶 Heath, forest and sand paths'
}))

C.append(mk.card(1808, 'De Waterberg', {
 'tags': ['Gelderland · Arnhem-Noord', 'Oerbos van de gemeente Arnhem (80 ha, sinds 2015) · nietsdoenbeheer naast het Openluchtmuseum', 'list 36 · no. 527'],
 'loc': '📍 In Arnhem-Noord, tussen Burgers\u2019 Zoo en de A50 · Oerbos · vrij toegankelijk via het bospadennetwerk ten noorden van Sonsbeek',
 'desc': 'In 2015 wees de gemeente Arnhem 80 hectare van bos <b>De Waterberg</b> aan als <b>oerbos</b> — het eerste bosreservaat van de gemeente op de Veluwe en een \u2019cadeau aan toekomstige generaties\u2019: de natuur mag er haar gang gaan en beheer vindt alleen plaats voor de veiligheid van de paden. Het bos maakte vroeger deel uit van landgoed Zypendaal: in 1726 werd burgemeester Adriaan Menthen eigenaar van het goed met herenhuis, koetshuis, de Witte Boerderij, circa 65 hectare bouw- en weiland en een reusachtig bos met meer dan 15.000 beuken en dennen. In 1899 kocht de gemeente het grootste deel van de parken Sonsbeek en Zypendaal, waaronder De Waterberg, en in 1914 gaf ze 28 hectare in erfpacht aan het Nederlands Openluchtmuseum, dat er in 1918 opende: het museum is letterlijk uit dit bos geboren. Het oerbosexperiment vraagt geduld — bomen moeten tijd krijgen om oud te worden, te sterven en om te vallen, en pas over een tot drie eeuwen oogt het echt wild — maar nu al groeien er mossen en paddenstoelen die in het omringende gewone bos ontbreken. Op De Waterberg leven alleen reeën; edelherten en zwijnen ontbreken er. Langs de rand loopt het drukke knooppunt Waterberg van de A50, met fietstunnels die het bos met de rest van de Veluwe verbinden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt–mrt (structuur van het oerbos)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilte en vogelzang.',
 'why': ['Het <b>eerste oerbos van Arnhem</b> (2015) met volledig nietsdoenbeheer.', 'De <b>geschiedenis van landgoed Zypendaal</b> en de 15.000 beuken en dennen.', 'De <b>geboorte van het Openluchtmuseum</b> uit dit bos.', 'De bijzondere <b>mossen en paddenstoelen</b> van onbeheerd bos.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Sneeuwklokjes</b> langs de paden.', '<span class="months">Mei–Jun</span> 🐦 <b>Bosvogels</b> in de oude kronen.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> op dood hout.', '<span class="months">Heel jaar</span> 🌲 <b>Omvallende bomen</b> laten het bos verwilderen.'], 'wild': ['🦌 Ree', '🐦 Zwarte specht · Boomklever · Goudhaan', '🦊 Vos · Das · Eekhoorn', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Beuk · Zomereik · Grove den (oud)'],
 'trail': ['Loop vanaf <b>Sonsbeek/Zijpendaal</b> het bospadennetwerk van De Waterberg in.', 'Steek via de <b>fietstunnels</b> onder knooppunt Waterberg door naar de Koningsheide.', 'Combineer met het <b>Openluchtmuseum</b> of Burgers\u2019 Zoo aan de rand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Nietsdoenbeheer — blijf op de paden · omvallende bomen · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Arnhem-Noord', 'Primeval forest of the municipality of Arnhem (80 ha, since 2015) · non-intervention management next to the Open Air Museum', 'list 36 · no. 527'],
 'loc': '📍 In Arnhem-Noord, between Burgers\u2019 Zoo and the A50 · Primeval forest · freely accessible via the forest path network north of Sonsbeek',
 'desc': 'In 2015 the municipality of Arnhem designated 80 hectares of the <b>De Waterberg</b> forest as a <b>primeval forest</b> — the municipality\u2019s first forest reserve on the Veluwe and a \u2018gift to future generations\u2019: nature may take its course and management takes place only for the safety of the paths. The forest once formed part of Zypendaal estate: in 1726 mayor Adriaan Menthen became owner of the property with manor house, coach house, the Witte Boerderij, some 65 hectares of arable and pasture land and a gigantic forest with more than 15,000 beeches and pines. In 1899 the municipality bought the largest part of the Sonsbeek and Zypendaal parks, including De Waterberg, and in 1914 it leased 28 hectares to the Netherlands Open Air Museum, which opened there in 1918: the museum was literally born from this forest. The primeval-forest experiment demands patience — trees need time to grow old, die and fall, and only after one to three centuries will it truly look wild — but already mosses and fungi grow here that are absent from the surrounding managed forest. Only roe deer live on De Waterberg; red deer and boar are absent. Along the edge runs the busy Waterberg junction of the A50, with cycle tunnels connecting the forest to the rest of the Veluwe.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct–Mar (structure of the primeval forest)<br>\n    <b>Best time of day:</b> Morning — silence and bird song.',
 'why': ['The <b>first primeval forest of Arnhem</b> (2015) with fully non-intervention management.', 'The <b>history of Zypendaal estate</b> and its 15,000 beeches and pines.', 'The <b>birth of the Open Air Museum</b> from this forest.', 'The special <b>mosses and fungi</b> of unmanaged forest.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Snowdrops</b> along the paths.', '<span class="months">May–Jun</span> 🐦 <b>Woodland birds</b> in the old crowns.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on dead wood.', '<span class="months">All year</span> 🌲 <b>Falling trees</b> let the forest go wild.'], 'wild': ['🦌 Roe deer', '🐦 Black woodpecker · Nuthatch · Goldcrest', '🦊 Fox · Badger · Red squirrel', '🦋 Speckled wood · Brimstone', '🌳 Beech · Pedunculate oak · Scots pine (old)'],
 'trail': ['Walk in from <b>Sonsbeek/Zijpendaal</b> via the forest path network of De Waterberg.', 'Cross under the Waterberg junction through the <b>cycle tunnels</b> to the Koningsheide.', 'Combine with the <b>Open Air Museum</b> or Burgers\u2019 Zoo on the edge.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Non-intervention management — stay on the paths · falling trees · 🚶 Forest and sand paths'
}))

C.append(mk.card(1809, 'Valkenhuizen', {
 'tags': ['Gelderland · Arnhem-Noord', 'Historisch landgoed in de Arnhemse schependom · stadsbos en sportterrein in de noordelijke stadsrand', 'list 36 · no. 528'],
 'loc': '📍 In Arnhem-Noord, in de omgeving van de Beukenlaan/Valkenhuizerweg · Stadsbos en sportpark · dicht bij park Sonsbeek en de Waterberg',
 'desc': '<b>Valkenhuizen</b> is een van de oude landgoed- en boerderijnamen van de Arnhemse schependom, het buitengebied van de middeleeuwse stad waar ook Mariëndaal, Warnsborn, Bakenberg, de Kluis, Zijpendaal, Klarenbeek en Angerenstein lagen. De naam verwijst naar een <b>valkenhuis</b>: een onderkomen waar valken voor de jacht werden gehouden — een statussymbool dat past bij de adellijke jachtcultuur rond Arnhem. Al in de achttiende eeuw liet baron Van Heeckeren van Enghuizen de zandverstuiving bij Valkenhuizen beplanten om het oprukkende zand te stoppen; het zo ontstane \u2019stadsbosch\u2019 werd later aan de eigenaar van landgoed Klarenbeek verkocht. Vandaag leeft de naam voort in het hooggelegen stadsdeel en sportpark Valkenhuizen in Arnhem-Noord, met daaromheen het <b>Stadsbos Valkenhuizen</b>, dat op de Natura 2000-kaarten van de Veluwe is ingetekend als bos in de noordelijke stadsrand: een groene long die aansluit op de bosgordel van Zijpendaal en De Waterberg. ⚠️ Als zelfstandig natuurgebied is Valkenhuizen dun gedocumenteerd — deze kaart registreert het historische landgoedtoponiem en het stadsbos van nu, op een steenworp van park Sonsbeek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig wandelen in het stadsbos.',
 'why': ['De <b>historische naam</b>: het valkenhuis van de Arnhemse jachtcultuur.', 'Het <b>Stadsbos Valkenhuizen</b> als groene long in de stadsrand.', 'De eeuwenoude strijd tegen <b>zandverstuiving</b> die hier werd gevoerd.', 'De ligging <b>tussen park Sonsbeek en de Waterberg</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Bosanemoon</b> in het stadsbos.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> rond de sportvelden.', '<span class="months">Sep–Okt</span> 🦌 <b>Reeën</b> uit de Waterberg in de schemering.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> in de lanen.'], 'wild': ['🐦 Zwarte specht · Boomklever · Groene specht', '🦌 Ree · Eekhoorn · Egel', '🦋 Bont zandoogje · Citroenvlinder', '🌼 Bosanemoon · Speenkruid', '🌳 Beuk · Zomereik · Esdoorn'],
 'trail': ['Wandel vanuit <b>park Sonsbeek</b> via Zijpendaal naar het stadsbos.', 'Verken de <b>Valkenhuizerweg en Beukenlaan</b> en de omringende bospaden.', 'Combineer met <b>De Waterberg</b> of het Openluchtmuseum.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Stadsbos tussen wijken — blijf op de paden · 🚶 Bos- en wijkpaden'
}, {
 'tags': ['Gelderland · Arnhem-Noord', 'Historic estate in the Arnhem schependom · town forest and sports grounds in the northern city fringe', 'list 36 · no. 528'],
 'loc': '📍 In Arnhem-Noord, around the Beukenlaan/Valkenhuizerweg · Town forest and sports park · close to Sonsbeek park and the Waterberg',
 'desc': '<b>Valkenhuizen</b> is one of the old estate and farm names of the Arnhem schependom, the rural district of the medieval city where Mariëndaal, Warnsborn, Bakenberg, de Kluis, Zijpendaal, Klarenbeek and Angerenstein also lay. The name refers to a <b>falcon house</b>: a shelter where falcons were kept for hunting — a status symbol fitting the aristocratic hunting culture around Arnhem. As early as the eighteenth century Baron Van Heeckeren van Enghuizen had the drifting sand at Valkenhuizen planted to stop the advancing sand; the resulting \u2018town forest\u2019 was later sold to the owner of Klarenbeek estate. Today the name lives on in the high-lying district and sports park Valkenhuizen in Arnhem-Noord, surrounded by the <b>Stadsbos Valkenhuizen</b>, which is marked on the Natura 2000 maps of the Veluwe as forest in the northern city fringe: a green lung connecting to the forest belt of Zijpendaal and De Waterberg. ⚠️ As an independent nature area Valkenhuizen is thinly documented — this card registers the historic estate toponym and the town forest of today, a stone\u2019s throw from Sonsbeek park.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet walking in the town forest.',
 'why': ['The <b>historic name</b>: the falcon house of the Arnhem hunting culture.', 'The <b>Stadsbos Valkenhuizen</b> as a green lung on the city fringe.', 'The centuries-old fight against <b>drifting sand</b> waged here.', 'Its position <b>between Sonsbeek park and the Waterberg</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Wood anemone</b> in the town forest.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> around the sports fields.', '<span class="months">Sep–Oct</span> 🦌 <b>Roe deer</b> from the Waterberg at dusk.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> in the avenues.'], 'wild': ['🐦 Black woodpecker · Nuthatch · Green woodpecker', '🦌 Roe deer · Red squirrel · Hedgehog', '🦋 Speckled wood · Brimstone', '🌼 Wood anemone · Lesser celandine', '🌳 Beech · Pedunculate oak · Maple'],
 'trail': ['Walk from <b>Sonsbeek park</b> via Zijpendaal into the town forest.', 'Explore the <b>Valkenhuizerweg and Beukenlaan</b> and the surrounding forest paths.', 'Combine with <b>De Waterberg</b> or the Open Air Museum.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Town forest between districts — stay on the paths · 🚶 Forest and district paths'
}))

mk.insert(C, '1804')
mk.progress(1809)
mk.check()
