# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1830, 'Het Joppe', {
 'tags': ['Gelderland · Joppe (Lochem)', 'Buurtschap met kasteel \u2019t Joppe · honderd hectare landschapspark tussen Gorssel en Harfsen', 'list 36 · no. 549'],
 'loc': '📍 Tussen Gorssel en Harfsen, aan de Dortherdijk · Kasteel en landgoed · start bij de kerk of restaurant De Zessprong (Dortherdijk 6)',
 'desc': '<b>Het Joppe</b> is het buurtschap én het landgoed rond <b>kasteel \u2019t Joppe</b> in de gemeente Lochem, tussen Gorssel, Harfsen en de Gorsselse Heide. Het landgoed dateert al uit de zestiende eeuw; het huidige kasteel werd rond <b>1740</b> gebouwd als buitenverblijf voor Deventer burgemeestersfamilies. Het circa <b>100 hectare</b> grote landgoed is aangelegd in Engelse landschapsstijl: een parkbos met vijvers en oude bomen, afgewisseld met kleine stukken naald- en loofbos, weilanden en akkers met fraaie alleenstaande bomen en zichtlijnen op het witte landhuis. De eigenaren speelden een belangrijke rol in de ontwikkeling van het buurtschap: het station van Gorssel — nu restaurant Het Bosrestaurant — kwam er alleen doordat de kasteelheer grond voor de spoorlijn afstond op voorwaarde dat er een station zou komen. Rond het kasteel liggen een gracht, hoge taxushagen, een berceau van haagbeuken en een ommuurde sier- en moestuin. Langs de landgoedlaan stonden in de Tweede Wereldoorlog V1\u2019s opgesteld. Een bewegwijzerde wandeling van circa 4,5 kilometer start bij de R.K. kerk in Joppe; restaurant De Zessprong is het vertrekpunt van de doorstapwandelingen rond landgoed en Gorsselse Heide.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–mei (park en rododendrons), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in het park.',
 'why': ['Het <b>kasteel \u2019t Joppe</b> uit circa 1740 met Engelse landschapstuin.', 'Het <b>100 hectare grote landgoed</b> met parkbos, weilanden en vijvers.', 'De <b>taxushagen, berceau en ommuurde tuin</b> rond het huis.', 'De <b>wandeling van 4,5 km</b> vanuit het buurtschap Joppe.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Park en rododendrons</b> in bloei.', '<span class="months">Mrt–Mei</span> 🐦 <b>Spechten roffelen</b> in de bossen.', '<span class="months">Jun–Aug</span> 🌿 <b>Zomerse lanen en weilanden</b>.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in het parkbos.'],
 'wild': ['🐦 Zwarte specht · Grote bonte specht · Boomklever', '🦌 Ree · Eekhoorn · Haas', '🦆 Wilde eend · Waterhoen', '🦋 Oranjetipje · Bont zandoogje', '🌳 Beuk · Zomereik · Haagbeuk (berceau)'],
 'trail': ['Start bij de <b>R.K. kerk in Joppe</b> en loop de wandeling van 4,5 km.', 'Parkeer bij <b>De Zessprong</b> (Dortherdijk 6) voor de doorstapwandelingen.', 'Combineer met de <b>Gorsselse Heide</b> of de Trage Tocht Joppe–Gorssel.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Park en tuin deels privé — volg de gemarkeerde route · 🚶 Park-, laan- en bospaden'
}, {
 'tags': ['Gelderland · Joppe (Lochem)', 'Hamlet with \u2019t Joppe castle · hundred-hectare landscape park between Gorssel and Harfsen', 'list 36 · no. 549'],
 'loc': '📍 Between Gorssel and Harfsen, on the Dortherdijk · Castle and estate · start at the church or restaurant De Zessprong (Dortherdijk 6)',
 'desc': '<b>Het Joppe</b> is both the hamlet and the estate around <b>\u2019t Joppe castle</b> in the municipality of Lochem, between Gorssel, Harfsen and the Gorsselse Heide. The estate dates back to the sixteenth century; the present castle was built around <b>1740</b> as a country retreat for Deventer mayoral families. The estate of about <b>100 hectares</b> was laid out in the English landscape style: a park wood with ponds and old trees, alternating with small parcels of conifer and broadleaved woodland, meadows and fields with fine solitary trees and sightlines to the white manor house. The owners played an important role in the development of the hamlet: the station of Gorssel — now restaurant Het Bosrestaurant — was only built because the castle lord ceded land for the railway on condition that a station would be provided. Around the castle lie a moat, tall yew hedges, a beech-hornbeam berceau and a walled ornamental and kitchen garden. V1 flying bombs were stationed along the estate avenue during the Second World War. A marked walk of about 4.5 kilometres starts at the Roman Catholic church in Joppe; restaurant De Zessprong is the starting point of the guided walks around estate and Gorsselse Heide.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–May (park and rhododendrons), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the park.',
 'why': ['<b>\u2019t Joppe castle</b> from around 1740 with English landscape garden.', 'The <b>100-hectare estate</b> with park wood, meadows and ponds.', 'The <b>yew hedges, berceau and walled garden</b> around the house.', 'The <b>4.5-km walk</b> from the hamlet of Joppe.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Park and rhododendrons</b> in bloom.', '<span class="months">Mar–May</span> 🐦 <b>Woodpeckers drum</b> in the woods.', '<span class="months">Jun–Aug</span> 🌿 <b>Summer avenues and meadows</b>.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the park wood.'],
 'wild': ['🐦 Black woodpecker · Great spotted woodpecker · Nuthatch', '🦌 Roe deer · Red squirrel · Hare', '🦆 Mallard · Moorhen', '🦋 Orange tip · Speckled wood', '🌳 Beech · Pedunculate oak · Hornbeam (berceau)'],
 'trail': ['Start at the <b>Roman Catholic church in Joppe</b> and walk the 4.5-km route.', 'Park at <b>De Zessprong</b> (Dortherdijk 6) for the guided walks.', 'Combine with the <b>Gorsselse Heide</b> or the Trage Tocht Joppe–Gorssel.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Park and garden partly private — follow the marked route · 🚶 Park, avenue and forest paths'
}))

C.append(mk.card(1831, 'De Lange Oorden', {
 'tags': ['Gelderland · ligging onbekend', 'Naam uit de bronnenlijst van de gids · niet betrouwbaar aan een openbaar natuurterrein te koppelen', 'list 36 · no. 550'],
 'loc': '📍 Genoteerd in de gids tussen de natuurgebieden van de IJsselvallei en de Achterhoek (p. 266) · exacte ligging onbekend · niet in openbare bronnen teruggevonden',
 'desc': '<b>De Lange Oorden</b> is een naam die in de bronnenlijst van de gids waarop deze site is gebouwd wordt genoemd tussen de natuur- en wandelgebieden van de IJsselvallei en de Achterhoek, maar die zich niet betrouwbaar laat lokaliseren. Uitvoerig zoeken in provinciale natuurdatabanken, wandelroute-databanken, topografische registers en kadasterkaarten levert geen terrein, pad of waterloop op die onder deze naam bekendstaat. Mogelijk gaat het om een oude veldnaam of een streeknaam die inmiddels niet meer gangbaar is, of om een naam die in de bron een ander gebied aanduidt dan tegenwoordig gebruikelijk. ⚠️ Deze kaart registreert de naam daarom eerlijk als wat hij is: een naam uit de bron die vooralsnog niet aan een concreet, toegankelijk terrein is te koppelen. Wie in de omgeving wil wandelen, kan het beste terecht bij de wél beschreven gebieden uit deze reeks — van het Beekbergerwoud en de Veluwse Bandijk tot de Gorsselse Heide en het Larense Broek — die gezamenlijk het landschap vormen waarin \u2018De Lange Oorden\u2019 in de gids is opgenomen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> Niet van toepassing — naam niet gelokaliseerd<br>\n    <b>Beste tijd van de dag:</b> Niet van toepassing.',
 'why': ['Een <b>naam uit de bronnenlijst</b> die nog niet is gelokaliseerd.', 'De <b>omliggende, wél beschreven gebieden</b> uit dezelfde gidsreeks.', 'Het <b>landschap van IJsselvallei en Achterhoek</b> als geheel.'],
 'phen': ['<span class="months">Heel jaar</span> 📚 <b>Brononderzoek</b> naar de naam gaat door.', '<span class="months">Apr–Okt</span> 🚶 Wandel in de <b>omliggende, bekende gebieden</b>.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op de nabije Gorsselse Heide.', '<span class="months">Okt–Mrt</span> 🌊 <b>Hoogwater</b> in de IJsseluiterwaarden.'],
 'wild': ['🦌 Ree · Haas (omgeving)', '🐦 Buizerd · Torenvalk (omgeving)', '🦆 Kolgans · Wilde eend (winter)', '🌳 Zomereik · Beuk · Es'],
 'trail': ['Raadpleeg bij een bezoek de <b>omliggende, wél beschreven gebieden</b> uit deze reeks.', 'Loop het <b>Beekbergerwoud</b>, de Veluwse Bandijk of de Gorsselse Heide.', 'Volg de actualiteit via de <b>bronnenlijst en kaarten</b> van de regio.'],
 'foot': '🐕 Honden aangelijnd in natuurgebieden · 💶 Gratis · ⚠️ Naam niet gelokaliseerd — geen eigen terrein of route · 🚶 Zie de omliggende gebieden'
}, {
 'tags': ['Gelderland · location unknown', 'Name from the guide\u2019s source list · cannot be reliably linked to a public nature site', 'list 36 · no. 550'],
 'loc': '📍 Listed in the guide among the nature areas of the IJssel valley and the Achterhoek (p. 266) · exact location unknown · not found in public sources',
 'desc': '<b>De Lange Oorden</b> is a name listed in the source list of the guide on which this site is built, among the nature and walking areas of the IJssel valley and the Achterhoek, but it cannot be reliably located. Extensive searching in provincial nature databases, walking-route databases, topographical registers and cadastral maps yields no terrain, path or watercourse known under this name. It may be an old field name or district name that is no longer current, or a name that in the source denotes a different area than is customary today. ⚠️ This card therefore honestly registers the name for what it is: a name from the source that cannot yet be linked to a concrete, accessible site. Those who wish to walk in the area are best served by the documented areas of this series — from the Beekbergerwoud and the Veluwse Bandijk to the Gorsselse Heide and the Larense Broek — which together form the landscape in which \u2018De Lange Oorden\u2019 appears in the guide.',
 'meta': '<b>Best season &amp; peak months:</b> Not applicable — name not located<br>\n    <b>Best time of day:</b> Not applicable.',
 'why': ['A <b>name from the source list</b> that has not yet been located.', 'The <b>surrounding, documented areas</b> from the same guide series.', 'The <b>landscape of the IJssel valley and Achterhoek</b> as a whole.'],
 'phen': ['<span class="months">All year</span> 📚 <b>Source research</b> into the name continues.', '<span class="months">Apr–Oct</span> 🚶 Walk in the <b>surrounding, known areas</b>.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the nearby Gorsselse Heide.', '<span class="months">Oct–Mar</span> 🌊 <b>High water</b> in the IJssel floodplains.'],
 'wild': ['🦌 Roe deer · Hare (surroundings)', '🐦 Buzzard · Kestrel (surroundings)', '🦆 White-fronted goose · Mallard (winter)', '🌳 Pedunculate oak · Beech · Ash'],
 'trail': ['For a visit, consult the <b>surrounding, documented areas</b> of this series.', 'Walk the <b>Beekbergerwoud</b>, the Veluwse Bandijk or the Gorsselse Heide.', 'Follow current information via the <b>source list and maps</b> of the region.'],
 'foot': '🐕 Dogs on lead in nature areas · 💶 Free · ⚠️ Name not located — no own site or route · 🚶 See the surrounding areas'
}))

C.append(mk.card(1832, 'Gorsselse Heide', {
 'tags': ['Gelderland · Gorssel–Harfsen (Lochem)', 'Heide en ven tussen Joppe en Harfsen · hersteld en beheerd door de stichting Marke Gorsselse Heide', 'list 36 · no. 551'],
 'loc': '📍 In de driehoek Reeverdijk–Elzerdijk–Deventerdijk, tussen Joppe en Harfsen · Heide en ven · toegang bij de hoek Elzerdijk–Gerritslagmanstraat of Reeverdijk–Elzerdijk',
 'desc': 'De <b>Gorsselse Heide</b> is een open heide- en venlandschap tussen Joppe, Eefde en Harfsen, in de gemeente Lochem. Tot 2009 was het terrein een <b>militair oefenterrein</b>; toen het openbaar werd verkocht, richtten inwoners de <b>Stichting Marke Gorsselse Heide</b> op om het heideherstel en het beheer zelf ter hand te nemen — een bijzonder voorbeeld van burgerbeheer. Het resultaat is een mooi, deels nat heidegebied met een ven — het Lutea-ven — waar dophei, struikhei, pijpenstrootje en bijzondere libellen het beeld bepalen, omzoomd door bosranden en het Quarlesbosje. De heide is vrij toegankelijk; een rondwandeling van circa 5 kilometer is beschreven in het gidsje \u2018Van Lutea-ven tot Quarlesbosje\u2019. Bij Joppe wordt bovendien gewerkt aan de <b>Kleine Gorsselse Heide</b>, waar de stichting het heidegebied herstelt en vergroot om de Gorsselse Heide met de omliggende natuur te verbinden. Militaire erfenissen, zoals oude oefensporen, herinneren aan het verleden van het terrein. Entrees: hoek Elzerdijk–Gerritslagmanstraat en hoek Reeverdijk–Elzerdijk (parkeergelegenheid).',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — laag licht over de heide.',
 'why': ['De <b>herstelde heide met het Lutea-ven</b> tussen bosranden.', 'Het unieke <b>burgerbeheer</b> door de Marke Gorsselse Heide.', 'De <b>stilte en ruimte</b> vlak bij Gorssel en Zutphen.', 'Het <b>heideherstel van de Kleine Gorsselse Heide</b> bij Joppe.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐦 <b>Boomleeuwerik en veldleeuwerik</b> boven de heide.', '<span class="months">Jun–Jul</span> 🦎 <b>Levendbarende hagedis</b> op de zonnige plekken.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt het veld paars.', '<span class="months">Sep</span> 💧 <b>Libellen</b> bij het Lutea-ven.'],
 'wild': ['🐦 Boomleeuwerik · Roodborsttapuit · Graspieper', '🦎 Levendbarende hagedis · Ringslang (ven)', '🦋 Heideblauwtje · Hooibeestje', '💧 Bruine glazenmaker · Venglazenmaker', '🌼 Struikhei · Dophei · Pijpenstrootje'],
 'trail': ['Toegang bij de hoek <b>Elzerdijk–Gerritslagmanstraat</b>.', 'Parkeer op de hoek <b>Reeverdijk–Elzerdijk</b> en loop de rondwandeling van 5 km.', 'Combineer met <b>kasteel \u2019t Joppe</b> of de omgeving van Eefde.'],
 'foot': '🐕 Honden aangelijnd (delen losloop) · 💶 Gratis · ⚠️ Open heide — geen beschutting bij slecht weer · 🚶 Heide-, zand- en graspaden'
}, {
 'tags': ['Gelderland · Gorssel–Harfsen (Lochem)', 'Heath and pool between Joppe and Harfsen · restored and managed by the Marke Gorsselse Heide foundation', 'list 36 · no. 551'],
 'loc': '📍 In the triangle Reeverdijk–Elzerdijk–Deventerdijk, between Joppe and Harfsen · Heath and pool · access at the corner of Elzerdijk–Gerritslagmanstraat or Reeverdijk–Elzerdijk',
 'desc': 'The <b>Gorsselse Heide</b> is an open heath and pool landscape between Joppe, Eefde and Harfsen, in the municipality of Lochem. Until 2009 the terrain was a <b>military training ground</b>; when it was sold publicly, local residents founded the <b>Marke Gorsselse Heide foundation</b> to take heath restoration and management into their own hands — a remarkable example of community stewardship. The result is a fine, partly wet heath area with a pool — the Lutea-ven — where cross-leaved heath, bell heather, purple moor-grass and special dragonflies set the scene, fringed by forest edges and the Quarlesbosje. The heath is freely accessible; a circular walk of about 5 kilometres is described in the booklet \u2018Van Lutea-ven tot Quarlesbosje\u2019. Near Joppe, work is also under way on the <b>Kleine Gorsselse Heide</b>, where the foundation is restoring and enlarging the heath to connect the Gorsselse Heide with the surrounding countryside. Military relics, such as old exercise tracks, recall the terrain\u2019s past. Entrances: corner of Elzerdijk–Gerritslagmanstraat and corner of Reeverdijk–Elzerdijk (parking).',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Morning or late afternoon — low light over the heath.',
 'why': ['The <b>restored heath with the Lutea-ven</b> between forest edges.', 'The unique <b>community stewardship</b> by the Marke Gorsselse Heide.', 'The <b>silence and space</b> close to Gorssel and Zutphen.', 'The <b>heath restoration of the Kleine Gorsselse Heide</b> near Joppe.'],
 'phen': ['<span class="months">Apr–May</span> 🐦 <b>Woodlark and skylark</b> above the heath.', '<span class="months">Jun–Jul</span> 🦎 <b>Viviparous lizard</b> on the sunny spots.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the field purple.', '<span class="months">Sep</span> 💧 <b>Dragonflies</b> at the Lutea-ven.'],
 'wild': ['🐦 Woodlark · Stonechat · Meadow pipit', '🦎 Viviparous lizard · Grass snake (pool)', '🦋 Silver-studded blue · Small heath', '💧 Brown hawker · Common hawker', '🌼 Bell heather · Cross-leaved heath · Purple moor-grass'],
 'trail': ['Access at the corner of <b>Elzerdijk–Gerritslagmanstraat</b>.', 'Park at the corner of <b>Reeverdijk–Elzerdijk</b> and walk the 5-km circuit.', 'Combine with <b>\u2019t Joppe castle</b> or the surroundings of Eefde.'],
 'foot': '🐕 Dogs on lead (parts off lead) · 💶 Free · ⚠️ Open heath — no shelter in bad weather · 🚶 Heath, sand and grass paths'
}))

C.append(mk.card(1833, 'Larense Broek', {
 'tags': ['Gelderland · Laren (Lochem)', 'Waterrijk natuurgebied ten noorden van Laren · vochtige graslanden, moerasbosjes en jonge loofbosjes', 'list 36 · no. 552'],
 'loc': '📍 Direct ten noorden van Laren, tussen de Holterweg, de Toldijk en de Stoevenbeltdijk · Broekland van Natuurmonumenten · uitkijkpunt aan de Stoevenbeltdijk',
 'desc': 'Het <b>Larense Broek</b> is een waterrijk natuurgebied van <b>Natuurmonumenten</b> even ten noorden van het Gelderse Laren, in de gemeente Lochem. Het bestaat uit een aantal <b>vochtige graslanden, moerasbosjes en jonge loofbosjes</b> op de overgang van de hogere enkgronden naar het beekdal van de Molenbeek — een nat land waar het grondwater hoog staat en het landschap wordt getekend door sloten, houtwallen en elzenbroek. In het broek broeden riet- en weidevogels en groeien planten van voedselrijke én schrale natte grond. Het terrein zelf is <b>niet toegankelijk</b>: Natuurmonumenten houdt het bewust rustig voor de natuur. Je beleeft het Larense Broek daarom vanaf de openbare weg: vanaf het <b>uitkijkpunt aan de Stoevenbeltdijk</b> en langs de Oude Deventerweg heb je een schitterend uitzicht over het beekdal en de moerasbosjes. De Trage Tocht Laren en het klompenpad Laorns Enkenpad voeren door de directe omgeving, langs landgoed Oolde en de Kapraolsvenne.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–jun (vogels), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond — vogels en laag licht.',
 'why': ['Het <b>waterrijke broekland</b> met graslanden, moerasbosjes en jonge bosjes.', 'Het <b>uitkijkpunt aan de Stoevenbeltdijk</b> over het beekdal.', 'De <b>rust voor de natuur</b>: bewust niet toegankelijk gemaakt.', 'De combinatie met de <b>Trage Tocht Laren</b> en het Laorns Enkenpad.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🐦 <b>Weide- en rietvogels</b> in het broek.', '<span class="months">Apr–Jun</span> 🌼 <b>Voorjaarsbloei</b> in grasland en bosrand.', '<span class="months">Jun–Aug</span> 🦋 <b>Vlinders en libellen</b> boven het water.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van elzen en wilgen.'],
 'wild': ['🐦 Rietzanger · Graspieper · Torenvalk', '🦌 Ree · Haas · Bunzing', '🦋 Oranjetipje · Zilveren maan', '🐸 Bruine kikker · Gewone pad', '🌳 Zwarte els · Wilg · Zachte berk'],
 'trail': ['Bekijk het Larense Broek vanaf het <b>uitkijkpunt aan de Stoevenbeltdijk</b>.', 'Loop de <b>Trage Tocht Laren</b> of het Laorns Enkenpad in de omgeving.', 'Combineer met <b>landgoed Oolde</b> en de Kapraolsvenne.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Niet toegankelijk — bekijk het gebied vanaf de openbare weg · 🚶 Openbare wegen en omliggende paden'
}, {
 'tags': ['Gelderland · Laren (Lochem)', 'Water-rich nature area north of Laren · moist grasslands, marsh woods and young broadleaf copses', 'list 36 · no. 552'],
 'loc': '📍 Directly north of Laren, between the Holterweg, the Toldijk and the Stoevenbeltdijk · Wetland of Natuurmonumenten · viewpoint on the Stoevenbeltdijk',
 'desc': 'The <b>Larense Broek</b> is a water-rich nature area of <b>Natuurmonumenten</b> just north of the Gelders village of Laren, in the municipality of Lochem. It consists of a number of <b>moist grasslands, marsh woods and young broadleaf copses</b> on the transition from the higher enk grounds to the valley of the Molenbeek — a wet land where the groundwater stands high and the landscape is marked by ditches, hedgerows and alder carr. Reed and meadow birds breed in the wetland, and plants of both rich and poor moist soils grow there. The terrain itself is <b>not accessible</b>: Natuurmonumenten deliberately keeps it quiet for nature. You therefore experience the Larense Broek from the public road: from the <b>viewpoint on the Stoevenbeltdijk</b> and along the Oude Deventerweg you have a splendid view over the valley and the marsh woods. The Trage Tocht Laren and the Laorns Enkenpad farm trail run through the immediate surroundings, past estate Oolde and the Kapraolsvenne.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–Jun (birds), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or evening — birds and low light.',
 'why': ['The <b>water-rich wetland</b> with grasslands, marsh woods and young copses.', 'The <b>viewpoint on the Stoevenbeltdijk</b> over the valley.', 'The <b>quiet for nature</b>: deliberately left inaccessible.', 'The combination with the <b>Trage Tocht Laren</b> and the Laorns Enkenpad.'],
 'phen': ['<span class="months">Mar–May</span> 🐦 <b>Meadow and reed birds</b> in the wetland.', '<span class="months">Apr–Jun</span> 🌼 <b>Spring bloom</b> in grassland and forest edge.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies and dragonflies</b> above the water.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of alders and willows.'],
 'wild': ['🐦 Reed warbler · Meadow pipit · Kestrel', '🦌 Roe deer · Hare · Polecat', '🦋 Orange tip · Silver-washed fritillary', '🐸 Common frog · Common toad', '🌳 Black alder · Willow · Downy birch'],
 'trail': ['View the Larense Broek from the <b>viewpoint on the Stoevenbeltdijk</b>.', 'Walk the <b>Trage Tocht Laren</b> or the Laorns Enkenpad in the surroundings.', 'Combine with <b>estate Oolde</b> and the Kapraolsvenne.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Not accessible — view the area from the public road · 🚶 Public roads and surrounding paths'
}))

C.append(mk.card(1834, 'Kasteel Oolde', {
 'tags': ['Gelderland · Laren/Oolde (Lochem)', 'Huis Oolde met landgoed bij Laren · Copijn-tuinen, zichtassen en het Laorns Enkenpad', 'list 36 · no. 553'],
 'loc': '📍 Aan de Ooldselaan in Oolde, even ten oosten van Laren bij Verwolde · Buitenplaats met landgoed · start bij het huis (Ooldselaan 17) of via het Laorns Enkenpad',
 'desc': '<b>Kasteel Oolde</b> — in de streek vooral bekend als <b>Huis Oolde</b> — is een historische buitenplaats (havezate) in het buurtschap Oolde, even ten oosten van Laren in de gemeente Lochem, vlak bij kasteel Verwolde. Het landgoed heeft een aantal kenmerkende elementen door het <b>tuin- en bosontwerp van de beroemde tuinarchitect H. Copijn</b>: statige zichtassen die het landschap doorknippen, waarbij Copijn ze opvallend genoeg allemaal door een boom liet snijden — midden in elke zichtas staat een boom. Een van die zichtassen is in 2022 met hulp van studenten gerestaureerd en is nu vanaf het openbare klompenpad en het koeienpad van de buurman te bewonderen. Het huis, de tuinmanswoning aan de Ooldselaan 13 en de overige landgoedgebouwen zijn rijksmonumenten; rond het huis liggen parkbos, vijvers en weilanden. Over het landgoed lopen wandelpaden: de routeverlenger van het klompenpad <b>Laorns Enkenpad</b> voert om Oolde en door het natuurgebied Kapraolsvenne, en ook de etappe Laren–Harfsen van de lijnwandeling Ontmoet de Achterhoek passeert het landgoed. Het huis zelf is particulier bewoond.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–mei (park en voorjaar), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig licht over de zichtassen.',
 'why': ['Het <b>Copijn-landschap</b> met zichtassen die door een boom worden doorsneden.', 'De <b>in 2022 gerestaureerde zichtas</b>, zichtbaar vanaf het klompenpad.', 'De <b>rijksmonumentale bebouwing</b> van de buitenplaats.', 'De <b>wandelroutes</b> over het landgoed en door de Kapraolsvenne.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Park en rododendrons</b> in bloei.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> in het parkbos.', '<span class="months">Jun–Jul</span> 🌼 <b>Gevlekte orchis</b> bij de Kapraolsvenne.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> langs de zichtassen.'],
 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Eekhoorn', '🦋 Oranjetipje · Bont zandoogje', '🌼 Gevlekte orchis · Moerashertshooi (Kapraolsvenne)', '🌳 Beuk · Zomereik · Linde'],
 'trail': ['Loop de <b>routeverlenger van het Laorns Enkenpad</b> om landgoed Oolde.', 'Start bij de <b>Ooldselaan 17</b> en volg de paden over het landgoed.', 'Combineer met <b>kasteel Verwolde</b> en het dorp Laren.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Huis is particulier bewoond — houd afstand · 🚶 Landgoed-, laan- en bospaden'
}, {
 'tags': ['Gelderland · Laren/Oolde (Lochem)', 'Oolde House with estate near Laren · Copijn gardens, sight axes and the Laorns Enkenpad', 'list 36 · no. 553'],
 'loc': '📍 On the Ooldselaan in Oolde, just east of Laren near Verwolde · Country estate · start at the house (Ooldselaan 17) or via the Laorns Enkenpad',
 'desc': '<b>Kasteel Oolde</b> — known locally above all as <b>Huis Oolde</b> — is a historic country estate in the hamlet of Oolde, just east of Laren in the municipality of Lochem, close to Verwolde castle. The estate has a number of characteristic elements thanks to the <b>garden and woodland design of the famous landscape architect H. Copijn</b>: stately sight axes that cut through the landscape, with Copijn strikingly letting every one of them be crossed by a tree — in the middle of each sight axis stands a tree. One of those sight axes was restored with the help of students in 2022 and can now be admired from the public farm trail and the neighbour\u2019s cow path. The house, the gardener\u2019s cottage at Ooldselaan 13 and the other estate buildings are listed monuments; around the house lie park wood, ponds and meadows. Walking paths run over the estate: the extension of the <b>Laorns Enkenpad</b> farm trail leads around Oolde and through the Kapraolsvenne nature area, and the Laren–Harfsen stage of the Ontmoet de Achterhoek line walk also passes the estate. The house itself is privately inhabited.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–May (park and spring), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet light over the sight axes.',
 'why': ['The <b>Copijn landscape</b> with sight axes crossed by a tree.', 'The <b>sight axis restored in 2022</b>, visible from the farm trail.', 'The <b>listed buildings</b> of the country estate.', 'The <b>walking routes</b> over the estate and through the Kapraolsvenne.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Park and rhododendrons</b> in bloom.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> in the park wood.', '<span class="months">Jun–Jul</span> 🌼 <b>Heath spotted orchid</b> near the Kapraolsvenne.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> along the sight axes.'],
 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Red squirrel', '🦋 Orange tip · Speckled wood', '🌼 Heath spotted orchid · Marsh St John\u2019s-wort (Kapraolsvenne)', '🌳 Beech · Pedunculate oak · Lime'],
 'trail': ['Walk the <b>extension of the Laorns Enkenpad</b> around estate Oolde.', 'Start at <b>Ooldselaan 17</b> and follow the paths over the estate.', 'Combine with <b>Verwolde castle</b> and the village of Laren.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The house is privately inhabited — keep your distance · 🚶 Estate, avenue and forest paths'
}))

mk.insert(C, '1829', chunk='reserves-1732-1834.json')
mk.progress(1834)
mk.check()
