# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1910, 'Lochemse Berg', {
 'tags': ['Gelderland · Lochem–Barchem', 'Stuwwal met de Belvédère-toren uit 1893 · bosrijk gebied van Geldersch Landschap &amp; Kasteelen met kwelplekken en bijzondere flora', 'list 36 · no. 629'],
 'loc': '📍 Tussen Lochem en Barchem, start aan de Barchemseweg 7241 JE Lochem · Vrij toegankelijk; op de paden blijven',
 'desc': 'De <b>Lochemse Berg</b> is het hoogste punt (circa 49 meter) van de stuwwal die in de voorlaatste ijstijd door landijs werd opgestuwd en zich tussen <b>Lochem en Barchem</b> uitstrekt. Geldersch Landschap &amp; Kasteelen beheert de twee beboste heuvels — de Lochemse Berg en de Kale Berg — met hun bossen, oude lanen en houtwallen. Op de zuidhelling van de Lochemse Berg ligt een <b>kwelplek</b> met helder kwelwater vanaf de hogere delen, waar bijzondere planten groeien als waterpostelein en moerasdroogbloem; lager op de hellingen, waar de bodem leem bevat, bloeien dalkruid en kamperfoelie, en op de hellingen groeien lijsterbes en rankende helmbloem. Op het hoogste punt staat de ronde <b>Belvédère-uitkijktoren uit 1893</b> — de toren is niet meer toegankelijk, maar de plek zelf geeft nog altijd uitzicht over de omgeving. In het gebied leven reeën, eekhoorns, vossen en bosvogels als de groene specht, en langs de bosranden fladdert de kleine ijsvogelvlinder. De gemarkeerde <b>Route Lochemse Berg</b> (circa 7 kilometer) loopt over de heuvels en door het glooiende landschap tussen Lochem en Barchem.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang, voorjaarsflora), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de heuvels.',
 'why': ['De <b>stuwwal van bijna 50 meter</b> te midden van het vlakke Achterhoekse land.', 'De <b>Belvédère-toren uit 1893</b> op de top.', 'De <b>kwelplek</b> met waterpostelein en moerasdroogbloem.', 'De gemarkeerde <b>Route Lochemse Berg</b> van circa 7 kilometer.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🌿 <b>Voorjaarsflora</b> op de hellingen.', '<span class="months">Apr–Jun</span> 🐦 <b>Bosvogels</b> en groene specht.', '<span class="months">Jun–Aug</span> 🦋 <b>Kleine ijsvogelvlinder</b> langs de bosranden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> over de heuvels.'],
 'wild': ['🐦 Groene specht · Zwarte specht · Buizerd', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Kleine ijsvogelvlinder · Bont zandoogje', '🌿 Dalkruid · Rankende helmbloem · Waterpostelein'],
 'trail': ['Start de <b>Route Lochemse Berg</b> aan de Barchemseweg.', 'Beklim de heuvel naar de <b>Belvédère-toren</b>.', 'Combineer met <b>Barchem of de Zwiepse Berg</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Toren niet toegankelijk; blijf op de paden · 🚶 Gemarkeerde bos- en heuvelpaden'
}, {
 'tags': ['Gelderland · Lochem–Barchem', 'Push moraine with the 1893 Belvédère tower · wooded area of Geldersch Landschap &amp; Kasteelen with seepage spots and special flora', 'list 36 · no. 629'],
 'loc': '📍 Between Lochem and Barchem, start on the Barchemseweg 7241 JE Lochem · Freely accessible; stay on the paths',
 'desc': 'The <b>Lochemse Berg</b> is the highest point (about 49 metres) of the push moraine pushed up by land ice in the penultimate ice age, stretching between <b>Lochem and Barchem</b>. Geldersch Landschap &amp; Kasteelen manages the two wooded hills — the Lochemse Berg and the Kale Berg — with their forests, old avenues and hedgerows. On the southern slope of the Lochemse Berg lies a <b>seepage spot</b> with clear groundwater rising from the higher parts, where special plants grow such as water blinks and a marsh cudweed; lower on the slopes, where the soil contains loam, may lily and honeysuckle bloom, and rowan and climbing corydalis grow on the slopes. On the highest point stands the round <b>Belvédère lookout tower from 1893</b> — the tower is no longer accessible, but the spot itself still offers views over the surroundings. The area harbours roe deer, red squirrels, foxes and forest birds such as the green woodpecker, and along the forest edges, where honeysuckle grows, the <b>white admiral</b> butterfly flies. The marked <b>Route Lochemse Berg</b> (about 7 kilometres) runs over the hills and through the rolling landscape between Lochem and Barchem.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong, spring flora), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet on the hills.',
 'why': ['The <b>push moraine of almost 50 metres</b> amid the flat Achterhoek country.', 'The <b>Belvédère tower from 1893</b> on the summit.', 'The <b>seepage spot</b> with water blinks and marsh cudweed.', 'The marked <b>Route Lochemse Berg</b> of about 7 kilometres.'],
 'phen': ['<span class="months">Mar–May</span> 🌿 <b>Spring flora</b> on the slopes.', '<span class="months">Apr–Jun</span> 🐦 <b>Forest birds</b> and green woodpecker.', '<span class="months">Jun–Aug</span> 🦋 <b>White admiral</b> along the forest edges.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> over the hills.'],
 'wild': ['🐦 Green woodpecker · Black woodpecker · Buzzard', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 White admiral · Speckled wood', '🌿 May lily · Climbing corydalis · Water blinks'],
 'trail': ['Start the <b>Route Lochemse Berg</b> on the Barchemseweg.', 'Climb the hill to the <b>Belvédère tower</b>.', 'Combine with <b>Barchem or the Zwiepse Berg</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Tower not accessible; stay on the paths · 🚶 Marked forest and hill paths'
}))

C.append(mk.card(1911, 'De Kale Berg', {
 'tags': ['Gelderland · Lochem–Barchem', 'Zusterheuvel van de Lochemse Berg (46 meter) met houten koepel en de Witte Wievenkoele · sagenlandschap en vergezichten tot in Duitsland', 'list 36 · no. 630'],
 'loc': '📍 Tussen Lochem en Barchem, bereikbaar vanuit Barchem en vanaf de Barchemseweg · Vrij toegankelijk; op de paden blijven',
 'desc': 'De <b>Kale Berg</b> is met circa <b>46 meter</b> de tweede heuvel van de Lochemse stuwwal, direct ten noorden van de Lochemse Berg en vlak bij het wandeldorp <b>Barchem</b>. Op de top staat een houten <b>koepel</b> van waaruit je over Twente en de zuidelijke Achterhoek kijkt — op heldere dagen tot in Duitsland. Op de noordflank ligt de <b>Witte Wievenkoele</b>, waarschijnlijk een oude leemgroeve. De plek werd gevreesd omdat er ‘witte wieven’ zouden huizen: witte nevels die ’s nachts over heide en moerasgronden zweefden en die je maar beter kon ontwijken. In de sage van Lochem zijn het juist ‘goede’ witte wieven: de rijke boerendochter Johanna wordt verliefd op de arme boerenzoon Herbert, en dankzij de witte wieven — die hem een gouden bord toewerpen als hij ’s nachts durft — wint Herbert de hand van zijn geliefde. De Kale Berg maakt deel uit van de wandelroutes over de ‘drie Lochemse Bergen’ die in Barchem starten.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), okt (herfst), jan–feb (bladerloos uitzicht)<br>\n    <b>Beste tijd van de dag:</b> Late middag — mooie lichtval over het land.',
 'why': ['Het <b>uitzicht vanaf de houten koepel</b> over Twente en de Achterhoek.', 'De <b>Witte Wievenkoele</b> en de sage van Johanna en Herbert.', 'De ligging in het wandellandschap van <b>Barchem</b>.', 'De ‘<b>drie Lochemse Bergen</b>’-route over de stuwwal.'],
 'phen': ['<span class="months">Heel jaar</span> 👀 <b>Vergezichten</b> vanaf de topkoepel.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in de bossen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> op de hellingen.', '<span class="months">Jan–Feb</span> ❄️ <b>Winterzicht</b> over het landschap.'],
 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Beuk · Zomereik · Hulst'],
 'trail': ['Start in <b>Barchem</b> en beklim de Kale Berg.', 'Loop de <b>‘drie Lochemse Bergen’</b>-route over de stuwwal.', 'Bezoek de <b>Witte Wievenkoele</b> op de noordflank.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ De kuil zelf is niet toegankelijk · 🚶 Bos- en heuvelpaden'
}, {
 'tags': ['Gelderland · Lochem–Barchem', 'Sister hill of the Lochemse Berg (46 metres) with a wooden dome and the Witte Wievenkoele · legendary landscape with views as far as Germany', 'list 36 · no. 630'],
 'loc': '📍 Between Lochem and Barchem, reachable from Barchem and from the Barchemseweg · Freely accessible; stay on the paths',
 'desc': 'The <b>Kale Berg</b>, at about <b>46 metres</b>, is the second hill of the Lochem push moraine, directly north of the Lochemse Berg and close to the walking village of <b>Barchem</b>. On the summit stands a wooden <b>dome</b> from which you look out over Twente and the southern Achterhoek — on clear days as far as Germany. On the northern flank lies the <b>Witte Wievenkoele</b>, probably an old clay pit. The spot was feared because ‘witte wieven’ (white women) were said to dwell there: white mists that floated over heath and marshland by night and were best avoided. In the Lochem legend they are, on the contrary, ‘good’ white women: the rich farmer’s daughter Johanna falls in love with the poor farmer’s son Herbert, and thanks to the white women — who throw him a golden plate when he dares to go out at night — Herbert wins the hand of his beloved. The Kale Berg is part of the ‘three Lochem hills’ walking routes that start in Barchem.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Oct (autumn), Jan–Feb (leafless views)<br>\n    <b>Best time of day:</b> Late afternoon — beautiful light over the land.',
 'why': ['The <b>view from the wooden dome</b> over Twente and the Achterhoek.', 'The <b>Witte Wievenkoele</b> and the legend of Johanna and Herbert.', 'Its place in the walking landscape of <b>Barchem</b>.', 'The ‘<b>three Lochem hills</b>’ route over the moraine.'],
 'phen': ['<span class="months">All year</span> 👀 <b>Panoramic views</b> from the summit dome.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in the woods.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> on the slopes.', '<span class="months">Jan–Feb</span> ❄️ <b>Winter views</b> over the landscape.'],
 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Beech · Pedunculate oak · Holly'],
 'trail': ['Start in <b>Barchem</b> and climb the Kale Berg.', 'Walk the ‘<b>three Lochem hills</b>’ route over the moraine.', 'Visit the <b>Witte Wievenkoele</b> on the northern flank.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The pit itself is not accessible · 🚶 Forest and hill paths'
}))

C.append(mk.card(1912, 'Wanninkhof', {
 'tags': ['Gelderland · De Horst–Geesteren (Berkelland)', 'Boerenlandgoed van 17 hectare met monumentale Saksische hoeve uit 1797 · poelen met boomkikkers, kamsalamander en poelkikker', 'list 36 · no. 631'],
 'loc': '📍 In de oude buurtschap De Horst, Geesterse Broekweg 7274 GC Geesteren · Het erf is privé; het landschap is via wegen en paden (o.a. het Boereneschpad) te verkennen',
 'desc': 'Landgoed <b>Wanninkhof</b> is een klein boerenlandgoed van <b>17 hectare</b> in de oude buurtschap De Horst in het buitengebied van Geesteren en Borculo, sinds <b>1964</b> eigendom van Geldersch Landschap &amp; Kasteelen. Het middelpunt is de monumentale Saksische <b>boerderij Wanninkhof uit 1797</b> (de oudste vermelding van het erf gaat terug tot <b>1188</b> als Werninchof); de hoeve ligt aan de rand van de grote <b>Boerenes</b>, een hoge es die vroeger gemeenschappelijk werd gebruikt. Rond het erf liggen natte gronden, houtwallen, een boerenbosje en <b>kikkerpoelen</b> waarin de zeldzame <b>boomkikker</b> leeft — in de jaren negentig werd het landschap hersteld: poelen werden gegraven, het moeras uitgebaggerd en houtwallen opnieuw aangeplant, waarna het aantal boomkikkers groeide tot vele tientallen. Ook de <b>kamsalamander</b> en de <b>poelkikker</b> profiteerden van de verbeteringen. Over het landgoed loopt het <b>Boereneschpad</b>, een klompenpad dat bij Geesteren en Gelselaar langs essen, poelen en houtwallen voert.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (roepende boomkikkers), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Avond — boomkikkers roepen in de schemering.',
 'why': ['De <b>monumentale Saksische hoeve uit 1797</b> aan de Boerenes.', 'De <b>boomkikkers</b>, kamsalamanders en poelkikkers in de poelen.', 'Het <b>geslaagde natuurherstel</b> uit de jaren negentig.', 'Het <b>Boereneschpad</b> over het landgoed en de omgeving.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐸 <b>Roepende boomkikkers</b> in de schemering.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in bos en houtwallen.', '<span class="months">Mei–Jun</span> 🌸 <b>Bloeiende poelen en bermen</b>.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> rond de Boerenes.'],
 'wild': ['🐸 Boomkikker · Kamsalamander · Poelkikker', '🐦 Steenuil · Buizerd · Boomklever', '🦌 Ree · Haas', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Zwarte els · Meidoorn'],
 'trail': ['Wandel het <b>Boereneschpad</b> over het landgoed (blauwe klompen).', 'Luister in de schemering bij de <b>poelen</b> naar de boomkikkers.', 'Combineer met <b>Gelselaar of Geesteren</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Bewoond erf privé · 🚶 Klompenpad en landbouwwegen'
}, {
 'tags': ['Gelderland · De Horst–Geesteren (Berkelland)', 'Farm estate of 17 hectares with a monumental Low Saxon farmhouse from 1797 · pools with tree frogs, great crested newts and pool frogs', 'list 36 · no. 631'],
 'loc': '📍 In the old hamlet of De Horst, Geesterse Broekweg 7274 GC Geesteren · The farmyard is private; the landscape can be explored via roads and paths (incl. the Boereneschpad)',
 'desc': 'The <b>Wanninkhof</b> estate is a small farm estate of <b>17 hectares</b> in the old hamlet of De Horst in the countryside of Geesteren and Borculo, property of Geldersch Landschap &amp; Kasteelen since <b>1964</b>. Its centrepiece is the monumental Low Saxon <b>Wanninkhof farmhouse from 1797</b> (the oldest mention of the farmstead goes back to <b>1188</b> as Werninchof); the farm lies on the edge of the large <b>Boerenes</b>, a high common arable field formerly used collectively. Around the farmyard lie wet grounds, hedgerows, a farm wood and <b>frog pools</b> inhabited by the rare <b>European tree frog</b> — in the 1990s the landscape was restored: pools were dug, the marsh dredged and hedgerows replanted, after which the number of tree frogs grew to many dozens. The <b>great crested newt</b> and the <b>pool frog</b> also profited from the improvements. Over the estate runs the <b>Boereneschpad</b>, a klompenpad (traditional clog-path) that leads past Geesteren and Gelselaar along essen, pools and hedgerows.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (calling tree frogs), Oct (autumn)<br>\n    <b>Best time of day:</b> Evening — tree frogs call at dusk.',
 'why': ['The <b>monumental Low Saxon farmhouse from 1797</b> on the Boerenes.', 'The <b>tree frogs</b>, great crested newts and pool frogs in the pools.', 'The <b>successful nature restoration</b> of the 1990s.', 'The <b>Boereneschpad</b> over the estate and its surroundings.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐸 <b>Calling tree frogs</b> at dusk.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in wood and hedgerows.', '<span class="months">May–Jun</span> 🌸 <b>Pools and verges in bloom</b>.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> around the Boerenes.'],
 'wild': ['🐸 European tree frog · Great crested newt · Pool frog', '🐦 Little owl · Buzzard · Nuthatch', '🦌 Roe deer · Hare', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Black alder · Hawthorn'],
 'trail': ['Walk the <b>Boereneschpad</b> over the estate (blue clogs).', 'Listen at dusk near the <b>pools</b> for calling tree frogs.', 'Combine with <b>Gelselaar or Geesteren</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Lived-in farmyard private · 🚶 Clog path and farm lanes'
}))

C.append(mk.card(1913, 'Needse Berg', {
 'tags': ['Gelderland · Neede (Berkelland)', 'Stuwwal van 35 meter ten noorden van Neede · kindvriendelijk met Woudy-routes, speelbos Ordelmanskoele en een 10 meter hoge observatietoren', 'list 36 · no. 632'],
 'loc': '📍 Ten noorden van Neede; start bij de parkeerplaats bij begraafplaats De Drostenkamp · Vrij toegankelijk; kinderrouteboekjes bij VVV Neede en Restaurant Olde Molle',
 'desc': 'De <b>Needse Berg</b> is een <b>stuwwal van 35 meter</b> direct ten noorden van <b>Neede</b>, gevormd in de voorlaatste ijstijd toen landijs de bodem opstuwde — dezelfde ijstijd waarin ook de Lochemse en Markelose Berg ontstonden. Het ijs bedekte de wal daarna opnieuw, waardoor bodemlagen scheef kwamen te staan; afgravingen zorgden voor grote verschillen in hoogte, vochtigheid en voedselrijkdom. Die variatie bracht een rijke flora voort, met onder meer <b>gevlekte orchis, salomonszegel en klein springzaad</b>; het beukenbos werd er voor zover bekend pas rond <b>1840</b> aangeplant. De berg is bijzonder kindvriendelijk: de routes <b>‘Op zoek naar Woudy’</b> (circa 3 kilometer, voor kinderen van 4–8 jaar) en <b>‘Terug naar ’t Stenen Tijdperk’</b> (circa 5 kilometer, 8–12 jaar) volgen paaltjes met Woudy de woudolifant en starten bij de parkeerplaats bij begraafplaats De Drostenkamp. Onderweg liggen de open speelplek <b>Ordelmanskoele</b> met survivaltraject en natuurlijke klim- en klauterbaan, en de <b>10 meter hoge Natuurobservatietoren</b>, die bij helder weer uitzicht biedt tot in Duitsland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (orchideeën, vogelzang), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of middag — ook leuk met kinderen.',
 'why': ['De <b>stuwwal van 35 meter</b> met scheefgestelde bodemlagen.', 'De <b>Woudy-kinderroutes</b> over de berg (3 en 5 kilometer).', 'De <b>gratis natuurspeeltuin Ordelmanskoele</b>.', 'Het <b>uitzicht vanaf de observatietoren</b> tot in Duitsland.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Gevlekte orchis</b> in bloei.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in het bos.', '<span class="months">Heel jaar</span> 🧒 <b>Woudy-routes</b> voor kinderen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> over de berg.'],
 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌿 Gevlekte orchis · Salomonszegel · Klein springzaad'],
 'trail': ['Start bij de <b>parkeerplaats bij De Drostenkamp</b>.', 'Loop een <b>Woudy-kinderroute</b> of een gewone boswandeling.', 'Beklim de <b>Natuurobservatietoren</b>.'],
 'foot': '🐕 Honden aangelijnd (niet bij de speelplek) · 💶 Gratis; routeboekjes tegen betaling bij VVV en Olde Molle · ⚠️ Speelbos en toren op eigen risico · 🚶 Gemarkeerde bosroutes'
}, {
 'tags': ['Gelderland · Neede (Berkelland)', 'Push moraine of 35 metres north of Neede · child-friendly with Woudy routes, the Ordelmanskoele play wood and a 10-metre observation tower', 'list 36 · no. 632'],
 'loc': '📍 North of Neede; start at the car park by De Drostenkamp cemetery · Freely accessible; children’s route booklets at VVV Neede and Restaurant Olde Molle',
 'desc': 'The <b>Needse Berg</b> is a <b>push moraine of 35 metres</b> directly north of <b>Neede</b>, formed in the penultimate ice age when land ice pushed up the soil — the same ice age in which the Lochemse and Markelose hills also arose. The ice then covered the ridge again, tilting the soil layers; excavations created great differences in height, moisture and nutrient richness. That variation produced a rich flora, including <b>spotted orchid, Solomon’s seal and small balsam</b>; the beech wood was planted there, as far as is known, only around <b>1840</b>. The hill is exceptionally child-friendly: the routes <b>‘Op zoek naar Woudy’</b> (about 3 kilometres, for children aged 4–8) and <b>‘Terug naar ’t Stenen Tijdperk’</b> (about 5 kilometres, ages 8–12) follow posts marked with Woudy the forest elephant and start at the car park by De Drostenkamp cemetery. Along the way lie the open play area <b>Ordelmanskoele</b> with a survival course and natural climbing frames, and the <b>10-metre-high nature observation tower</b>, which on clear days offers views as far as Germany.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (orchids, birdsong), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or afternoon — also fun with children.',
 'why': ['The <b>push moraine of 35 metres</b> with tilted soil layers.', 'The <b>Woudy children’s routes</b> over the hill (3 and 5 kilometres).', 'The <b>free Ordelmanskoele natural playground</b>.', 'The <b>view from the observation tower</b> as far as Germany.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Spotted orchid</b> in bloom.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in the wood.', '<span class="months">All year</span> 🧒 <b>Woudy routes</b> for children.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> over the hill.'],
 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌿 Spotted orchid · Solomon’s seal · Small balsam'],
 'trail': ['Start at the <b>car park by De Drostenkamp</b>.', 'Walk a <b>Woudy children’s route</b> or an ordinary forest walk.', 'Climb the <b>nature observation tower</b>.'],
 'foot': '🐕 Dogs on lead (not at the play area) · 💶 Free; route booklets for a fee at VVV and Olde Molle · ⚠️ Play wood and tower at your own risk · 🚶 Marked forest routes'
}))

C.append(mk.card(1914, 'Het Olthaar', {
 'tags': ['Gelderland · omgeving Neede (Berkelland)', 'Naam uit de gids in de reeks tussen de Needse Berg en het Needse Achterveld · vermoedelijk een oude veldnaam, in moderne registers niet terug te vinden', 'list 36 · no. 633'],
 'loc': '📍 In de omgeving van Neede (gemeente Berkelland), tussen de Needse Berg en het Needse Achterveld · Naam uit de gids zonder teruggevonden terrein — wandel door het omringende landschap',
 'desc': '<b>Het Olthaar</b> is een naam die de gids opneemt in de reeks terreinen tussen de <b>Needse Berg</b> en het <b>Needse Achterveld</b>, in de omgeving van <b>Neede</b> in de gemeente Berkelland. De naam heeft de klank van een oude veldnaam: ‘olthaar’ of ‘oud haar’ zou kunnen wijzen op een oude ‘haar’ — een hoge, zandige rug begroeid met heide, zoals er in dit deel van de Achterhoek meer liggen op de overgang van de stuwwal naar de jonge veldontginningen. In moderne topografische registers, kadasters en wandelgidsen komt de naam niet meer voor, en ook oude kaarten geven geen uitsluitsel over een precieze ligging. Net als bij enkele andere namen uit deze oude bron registreert deze kaart daarom eerlijk wat er wél bekend is: Het Olthaar hoort bij het kleinschalige overgangslandschap ten oosten van de Needse Berg, waar essen, houtwallen, broekjes en ontginningsbossen elkaar afwisselen en waar nog altijd vrij gewandeld kan worden over wegen en paden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond.',
 'why': ['De <b>naam uit de gids</b> in de reeks tussen Needse Berg en Needse Achterveld.', 'De mogelijke herkomst: <b>‘oud haar’</b>, een oude zandige heuvelrug.', 'Het <b>overgangslandschap</b> van stuwwal naar veldontginning.', 'De eerlijke registratie zonder teruggevonden terrein.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en bosjes.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs wegen en paden.', '<span class="months">Mei–Jul</span> 🐄 <b>Vee</b> op de weilanden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Gele kwikstaart · Veldleeuwerik · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Zwarte els · Meidoorn'],
 'trail': ['Verken het landschap ten oosten van de <b>Needse Berg</b>.', 'Wandel via wegen en paden tussen <b>essen, houtwallen en broekjes</b>.', 'Combineer met de <b>Needse Berg of het Needse Achterveld</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Naam uit de gids zonder teruggevonden terrein — geen eigen voorzieningen · 🚶 Wegen en landbouwwegen'
}, {
 'tags': ['Gelderland · Neede area (Berkelland)', 'Name from the guide in the series between the Needse Berg and the Needse Achterveld · probably an old field name, no longer traceable in modern registers', 'list 36 · no. 633'],
 'loc': '📍 In the surroundings of Neede (municipality of Berkelland), between the Needse Berg and the Needse Achterveld · Name from the guide without a recovered terrain — walk through the surrounding landscape',
 'desc': '<b>Het Olthaar</b> is a name the guide includes in its series of areas between the <b>Needse Berg</b> and the <b>Needse Achterveld</b>, in the surroundings of <b>Neede</b> in the municipality of Berkelland. The name sounds like an old field name: ‘olthaar’ or ‘oud haar’ could point to an old ‘haar’ — a high, sandy ridge grown with heath, such as more of them lie in this part of the Achterhoek on the transition from the push moraine to the young heath reclamations. The name no longer occurs in modern topographical registers, cadastres or walking guides, and old maps give no answer about a precise location either. As with several other names from this old source, this card therefore honestly registers what is known: Het Olthaar belongs to the small-scale transitional landscape east of the Needse Berg, where essen, hedgerows, fens and reclamation woods alternate and where one can still walk freely over roads and paths.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or evening.',
 'why': ['The <b>name from the guide</b> in the series between the Needse Berg and the Needse Achterveld.', 'The possible origin: <b>‘oud haar’</b>, an old sandy ridge.', 'The <b>transitional landscape</b> from moraine to heath reclamation.', 'The honest registration without a recovered terrain.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and copses.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along roads and paths.', '<span class="months">May–Jul</span> 🐄 <b>Cattle</b> on the meadows.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Yellow wagtail · Skylark · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Black alder · Hawthorn'],
 'trail': ['Explore the landscape east of the <b>Needse Berg</b>.', 'Walk roads and paths between <b>essen, hedgerows and fens</b>.', 'Combine with the <b>Needse Berg or the Needse Achterveld</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Name from the guide without a recovered terrain — no facilities of its own · 🚶 Roads and farm lanes'
}))

mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1914)
mk.check()
