# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1920, 'Overbiel', {
 'tags': ['Gelderland · Borculo–Neede (Berkelland)', 'Buurtschap even ten oosten van Borculo · naam uit de gids in de reeks tussen de landgoederen Beekvliet en Wolink', 'list 36 · no. 639'],
 'loc': '📍 Even ten oosten van Borculo, langs de weg naar Neede en Geesteren · Landschap vrij te verkennen via wegen en paden; geen eigen terrein of voorzieningen',
 'desc': '<b>Overbiel</b> is een buurtschap in de gemeente Berkelland, even ten oosten van <b>Borculo</b> langs de weg naar Neede; tot 2005 behoorde het tot de gemeente Borculo. De naam heeft de klank van een oude veldnaam — ‘over de biel’, vermoedelijk over een waterloop of landscheiding — maar als zelfstandig natuurterrein met eigen voorzieningen is Overbiel in moderne registers niet terug te vinden. De gids zet de naam in de reeks tussen de landgoederen <b>Beekvliet</b> en <b>Wolink</b>, en dat is ook landschappelijk de juiste plek: Overbiel ligt in het kleinschalige beekdallandschap van de Berkel en de Slinge, waar essen, houtwallen, natte graslanden, bosjes en oude boerenerven elkaar afwisselen. Ten zuiden van de buurtschap stroomt de Berkel met zijn kades en het schouwpad; daarover loopt onder meer etappe 4 van het <b>Berkelpad</b> (Borculo–Haarlo), dat wandelaars door dit ‘achterland’ voert. Zoals bij meer register- en gidsnamen zonder teruggevonden terrein, registreert deze kaart eerlijk wat wél bekend is: Overbiel is het coulisselandschap ten oosten van Borculo, prima te wandelen via het Berkelpad, klompenpaden en landbouwwegen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang, bloemrijke bermen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag.',
 'why': ['De <b>buurtschap ten oosten van Borculo</b> langs de weg naar Neede.', 'De ligging tussen de landgoederen <b>Beekvliet en Wolink</b>.', 'Het <b>Berkelpad</b> met de kades en het schouwpad langs de Berkel.', 'De eerlijke registratie zonder teruggevonden terrein.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en bosjes.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs wegen en paden.', '<span class="months">Mei–Jul</span> 🐄 <b>Vee</b> op de natte graslanden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Gele kwikstaart · Veldleeuwerik · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Zwarte els · Meidoorn'],
 'trail': ['Wandel etappe 4 van het <b>Berkelpad</b> tussen Borculo en Haarlo.', 'Verken het coulisselandschap rond <b>Overbiel</b> via wegen en paden.', 'Combineer met <b>Beekvliet of landgoed Wolink</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Naam uit de gids zonder teruggevonden terrein — geen eigen voorzieningen · 🚶 Wegen, schouwpad en landbouwwegen'
}, {
 'tags': ['Gelderland · Borculo–Neede (Berkelland)', 'Hamlet just east of Borculo · name from the guide in the series between the Beekvliet and Wolink estates', 'list 36 · no. 639'],
 'loc': '📍 Just east of Borculo, along the road to Neede and Geesteren · Landscape freely explorable via roads and paths; no terrain or facilities of its own',
 'desc': '<b>Overbiel</b> is a hamlet in the municipality of Berkelland, just east of <b>Borculo</b> along the road to Neede; until 2005 it belonged to the municipality of Borculo. The name sounds like an old field name — ‘over de biel’, presumably across a watercourse or land boundary — but as an independent nature terrain with its own facilities, Overbiel cannot be traced in modern registers. The guide places the name in the series between the <b>Beekvliet</b> and <b>Wolink</b> estates, and that is also the right place in landscape terms: Overbiel lies in the small-scale brook-valley landscape of the Berkel and the Slinge, where essen, hedgerows, wet grasslands, copses and old farmsteads alternate. South of the hamlet flows the Berkel with its dykes and the inspection path; over it runs, among others, stage 4 of the <b>Berkelpad</b> (Borculo–Haarlo), which leads walkers through this ‘hinterland’. As with more register and guide names without a recovered terrain, this card honestly registers what is known: Overbiel is the small-scale landscape east of Borculo, easy to walk via the Berkelpad, clog paths and farm lanes.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong, flower-rich verges), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon.',
 'why': ['The <b>hamlet east of Borculo</b> along the road to Neede.', 'Its position between the <b>Beekvliet and Wolink</b> estates.', 'The <b>Berkelpad</b> with the dykes and inspection path along the Berkel.', 'The honest registration without a recovered terrain.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and copses.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along roads and paths.', '<span class="months">May–Jul</span> 🐄 <b>Cattle</b> on the wet grasslands.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Yellow wagtail · Skylark · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Black alder · Hawthorn'],
 'trail': ['Walk stage 4 of the <b>Berkelpad</b> between Borculo and Haarlo.', 'Explore the small-scale landscape around <b>Overbiel</b> via roads and paths.', 'Combine with <b>Beekvliet or the Wolink estate</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Name from the guide without a recovered terrain — no facilities of its own · 🚶 Roads, inspection path and farm lanes'
}))

C.append(mk.card(1921, 'Wolink', {
 'tags': ['Gelderland · Haarlo–Borculo (Berkelland)', 'Landgoed met monumentale boerderij tussen Borculo en Haarlo · kampenlandschap langs de Berkel; ook gespeld als Wollink', 'list 36 · no. 640'],
 'loc': '📍 Tussen Borculo en Haarlo, ten noorden van de Berkel · Terrein deels vrij toegankelijk via wegen en paden; het Berkelpad loopt over het landgoed',
 'desc': 'Landgoed <b>Wolink</b> — in moderne routes meestal <b>Wollink</b> gespeld — ligt tussen <b>Borculo en Haarlo</b> in de gemeente Berkelland, op de noordelijke oever van de Berkel. Het is een typisch Achterhoeks boerenlandgoed dat is gegroeid rond een oude hoeve met een monumentale boerderij: kleinschalige, hooggelegen akkers wisselen er af met bossen, lanen, graslanden en <b>hoogstamboomgaarden</b>. Het geheel ligt ingebed in het coulisselandschap van de voormalige Heerlijkheid Borculo, waar houtwallen, essen en beekdalgronden elkaar afwisselen. Etappe 4 van het <b>Berkelpad</b> (Borculo–Haarlo) loopt over het landgoed ‘over gras- en zandpaden en een kerkpad naar het dorpje Haarlo’, zoals de routebeschrijving het noemt — een van de fraaiste stukken van die tocht. Ook het rondje ‘Landgoed Wollink en Berkel’ voert langs de Veldweg, het Haarlose kanaal en de Waterhoekdijk door dit landschap. De Berkel met zijn stuwen en kades vormt de zuidgrens van het terrein; daar is het wandelen langs het schouwpad.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), apr–mei (boomgaarden in bloei), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig langs de Berkel.',
 'why': ['De <b>monumentale boerderij en oude hoeve</b> in het kampenlandschap.', 'De ligging <b>langs de Berkel</b> tussen Borculo en Haarlo.', 'Het <b>Berkelpad</b> dat over het landgoed loopt.', 'De <b>hoogstamboomgaarden</b> en kleinschalige akkers.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Bloeiende hoogstamboomgaarden</b>.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in bos en houtwallen.', '<span class="months">Jun–Aug</span> 🦋 <b>Vlinders</b> langs bermen en bosranden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Steenuil · Buizerd · Boomklever', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Es · Hoogstamfruitboom'],
 'trail': ['Volg het <b>Berkelpad</b> over landgoed Wolink richting Haarlo.', 'Fiets of wandel het <b>rondje Wollink en Berkel</b>.', 'Combineer met <b>Haarlo, Borculo of Beekvliet</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Bewoonde boerderij en erf privé · 🚶 Gras- en zandpaden, kerkpad en schouwpad'
}, {
 'tags': ['Gelderland · Haarlo–Borculo (Berkelland)', 'Estate with a monumental farmhouse between Borculo and Haarlo · small-scale landscape along the Berkel; also spelled Wollink', 'list 36 · no. 640'],
 'loc': '📍 Between Borculo and Haarlo, north of the Berkel · Terrain partly freely accessible via roads and paths; the Berkelpad runs over the estate',
 'desc': 'The <b>Wolink</b> estate — in modern routes usually spelled <b>Wollink</b> — lies between <b>Borculo and Haarlo</b> in the municipality of Berkelland, on the northern bank of the Berkel. It is a typical Achterhoek farm estate that grew around an old farmstead with a monumental farmhouse: small-scale, elevated arable fields alternate with woods, avenues, grasslands and <b>standard orchards</b>. The whole is embedded in the small-scale landscape of the former lordship of Borculo, where hedgerows, essen and brook-valley grounds alternate. Stage 4 of the <b>Berkelpad</b> (Borculo–Haarlo) runs over the estate ‘over grass and sand paths and a church path to the village of Haarlo’, as the route description puts it — one of the finest stretches of that walk. The ‘Landgoed Wollink en Berkel’ circular route likewise leads along the Veldweg, the Haarlose canal and the Waterhoekdijk through this landscape. The Berkel with its weirs and dykes forms the southern boundary of the terrain; there one walks along the inspection path.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Apr–May (orchards in bloom), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet along the Berkel.',
 'why': ['The <b>monumental farmhouse and old farmstead</b> in the small-scale landscape.', 'Its position <b>along the Berkel</b> between Borculo and Haarlo.', 'The <b>Berkelpad</b> that runs over the estate.', 'The <b>standard orchards</b> and small arable fields.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Blooming standard orchards</b>.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in wood and hedgerows.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> along verges and forest edges.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Little owl · Buzzard · Nuthatch', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Ash · Standard fruit tree'],
 'trail': ['Follow the <b>Berkelpad</b> over the Wolink estate towards Haarlo.', 'Cycle or walk the <b>Wollink and Berkel circular route</b>.', 'Combine with <b>Haarlo, Borculo or Beekvliet</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Lived-in farmhouse and yard private · 🚶 Grass and sand paths, church path and inspection path'
}))

C.append(mk.card(1922, 'Het Vinkennest', {
 'tags': ['Gelderland · Eibergen (Berkelland)', 'Naam uit de gids · teruggevonden als ’t Vinkennest, het openluchtzwembad van Eibergen op een grote ligweide aan de bosrand', 'list 36 · no. 641'],
 'loc': '📍 Stokkersweg 4, 7151 NN Eibergen · Terrein seizoensgebonden toegankelijk (zwembad geopend circa mei–september); de omgeving is vrij wandelbaar',
 'desc': '<b>Het Vinkennest</b> is een naam die de gids opneemt in de reeks tussen de landgoederen Wolink en het Kerkloo, in de omgeving van <b>Eibergen</b>. In moderne bronnen duikt de naam alleen op als <b>’t Vinkennest</b>, het openluchtzwembad van Eibergen aan de Stokkersweg: een buitenbad met een verhit 30-meterbad, duikplanken, een recreatiebad en een peuterbad, gelegen op een <b>grote ligweide</b> aan de rand van het dorp, omzoomd door bos en weiland. Waarschijnlijk doelde de oude gids op dit recreatieterrein aan de stadsrand, waar de ligweide en de omringende bosrand ook zonder zwemkaartje een wandeldoel vormen. Net als bij andere namen uit het register die geen zelfstandig natuurterrein meer blijken te zijn, registreert deze kaart eerlijk wat er wél te vinden is: het terrein van ’t Vinkennest ligt vlak bij het wandelpark <b>De Maat</b> langs de Berkel, vanwaar de wandeling langs de Mallumse Molen en de Kruidenhof begint. Wie in de buurt is, kan het recreatielandschap aan de rand van Eibergen dus prima combineren met een Berkelwandeling.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (buitenbad en ligweide), apr–jun (vogelzang langs de Berkel)<br>\n    <b>Beste tijd van de dag:</b> Middag voor het zwembad; ochtend voor een rustige wandeling.',
 'why': ['De <b>grote ligweide</b> van ’t Vinkennest aan de rand van Eibergen.', 'De ligging vlak bij <b>wandelpark De Maat</b> langs de Berkel.', 'De <b>wandeling naar de Mallumse Molen</b> en de Kruidenhof.', 'De eerlijke registratie van een recreatienaam zonder natuurterrein.'],
 'phen': ['<span class="months">Mei–Sep</span> 🏊 <b>Openluchtzwembad</b> geopend.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> langs de Berkel.', '<span class="months">Jun–Aug</span> 🌸 <b>Zomerbloei</b> op de ligweide en bermen.', '<span class="months">Heel jaar</span> 🚶 <b>Wandelpark De Maat</b> vrij toegankelijk.'],
 'wild': ['🐦 Ijsvogel · Grote gele kwikstaart · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Oranjetipje', '🌳 Zomereik · Wilg · Zwarte els'],
 'trail': ['Wandel door <b>park De Maat</b> langs de Berkel.', 'Loop de route naar de <b>Mallumse Molen</b> en de Kruidenhof.', 'Combineer met <b>Eibergen en landgoed Het Kerkloo</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Zwembad tegen betaling; wandelpark gratis · ⚠️ Zwembad alleen in het seizoen geopend · 🚶 Wandelpark, wegen en paden'
}, {
 'tags': ['Gelderland · Eibergen (Berkelland)', 'Name from the guide · traced as ’t Vinkennest, Eibergen’s open-air swimming pool on a large lawn at the forest edge', 'list 36 · no. 641'],
 'loc': '📍 Stokkersweg 4, 7151 NN Eibergen · Terrain seasonally accessible (pool open roughly May–September); the surroundings are freely walkable',
 'desc': '<b>Het Vinkennest</b> is a name the guide includes in its series between the Wolink estate and the Kerkloo, in the surroundings of <b>Eibergen</b>. In modern sources the name only appears as <b>’t Vinkennest</b>, Eibergen’s open-air swimming pool on the Stokkersweg: an outdoor pool with a heated 30-metre pool, diving boards, a recreational pool and a toddler pool, set on a <b>large lawn</b> at the edge of the village, lined by wood and meadow. The old guide probably meant this recreation area at the edge of town, where the lawn and the surrounding forest edge are also a walking destination without a pool ticket. As with other names from the register that no longer turn out to be independent nature terrains, this card honestly records what can be found: the ’t Vinkennest terrain lies close to the <b>De Maat</b> walking park along the Berkel, from where the walk to the Mallumse Molen mill and the herb garden starts. Anyone in the area can therefore easily combine the recreational landscape at the edge of Eibergen with a Berkel walk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (outdoor pool and lawn), Apr–Jun (birdsong along the Berkel)<br>\n    <b>Best time of day:</b> Afternoon for the pool; morning for a quiet walk.',
 'why': ['The <b>large lawn</b> of ’t Vinkennest at the edge of Eibergen.', 'Its position close to <b>De Maat walking park</b> along the Berkel.', 'The <b>walk to the Mallumse Molen</b> and the herb garden.', 'The honest registration of a recreation name without a nature terrain.'],
 'phen': ['<span class="months">May–Sep</span> 🏊 <b>Open-air pool</b> open.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> along the Berkel.', '<span class="months">Jun–Aug</span> 🌸 <b>Summer bloom</b> on the lawn and verges.', '<span class="months">All year</span> 🚶 <b>De Maat walking park</b> freely accessible.'],
 'wild': ['🐦 Kingfisher · Grey wagtail · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Orange tip', '🌳 Pedunculate oak · Willow · Black alder'],
 'trail': ['Walk through <b>De Maat park</b> along the Berkel.', 'Walk the route to the <b>Mallumse Molen</b> and the herb garden.', 'Combine with <b>Eibergen and the Het Kerkloo estate</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Pool for a fee; walking park free · ⚠️ Pool only open in season · 🚶 Walking park, roads and paths'
}))

C.append(mk.card(1923, 'Het Kerkloo', {
 'tags': ['Gelderland · Eibergen (Berkelland)', 'Het Kerkloobos, circa 40 hectare bos tussen Eibergen en Rekken · legaat van burgemeester Smits met een theekoepel uit 1912', 'list 36 · no. 642'],
 'loc': '📍 Ten noordoosten van Eibergen, langs de weg naar Rekken · Vrij toegankelijk over wegen en paden; de theekoepel staat langs de openbare weg',
 'desc': '<b>Het Kerkloo</b>, tegenwoordig meestal <b>Kerkloobos</b> genoemd, is een bosgebied van circa <b>40 hectare</b> tussen <b>Eibergen</b> en het buurtschap Rekken, op de overgang van het open Eibergse Veld naar het dal van de Berkel. De naam ‘loo’ duidt op een open bos op zandgrond; ‘kerk’ verwijst naar de kerk van Eibergen, die het bos vroeger bezat of beheerde. Het huidige bos is een afwisselend gemengd bos van loof- en naaldhout, deels aangeplant op <b>rabatten</b> (opgehoogde bedden met greppels ertussen voor de ontwatering). Het kwam mede tot stand dankzij een <b>legaat van burgemeester Smits</b>, burgemeester van Eibergen van 1903 tot 1915; de oudste bomen dateren van omstreeks 1870, en volgens de overlevering werd het terrein al eerder, rond 1820, als wandelbos gebruikt. Na de Tweede Wereldoorlog werd circa 8 hectare opnieuw beplant. Aan de bosrand staat nog altijd het <b>stenen theekoepeltje uit 1912</b>. In de winter van 1990 richtte een zware storm veel schade aan in het bos. Het Kerkloobos is een geliefd wandelgebied met rustige paden; er broeden onder meer de zwarte specht, de groene specht en de wielewaal, en de Trage Tocht Eibergen voert door het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang, wielewaal), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — veel vogelzang in het broedseizoen.',
 'why': ['Het <b>afwisselende bos van circa 40 hectare</b> tussen Eibergen en Rekken.', 'De <b>geschiedenis als legaat van burgemeester Smits</b>.', 'Het <b>stenen theekoepeltje uit 1912</b>.', 'De <b>broedvogels</b>, waaronder zwarte specht en wielewaal.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Wielewaal en spechten</b> in het broedseizoen.', '<span class="months">Mei–Jun</span> 🌸 <b>Berm- en bosrandflora</b>.', '<span class="months">Aug–Okt</span> 🍄 <b>Paddenstoelen</b> in het oude bos.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van loof en naaldhout.'],
 'wild': ['🐦 Zwarte specht · Groene specht · Wielewaal', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Grove den · Beuk'],
 'trail': ['Wandel door het <b>Kerkloobos</b> vanaf de weg naar Rekken.', 'Zoek het <b>theekoepeltje uit 1912</b> aan de bosrand.', 'Volg de <b>Trage Tocht Eibergen</b> door het gebied.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; theekoepel niet toegankelijk · 🚶 Boswegen en wandelpaden'
}, {
 'tags': ['Gelderland · Eibergen (Berkelland)', 'Het Kerkloobos, about 40 hectares of wood between Eibergen and Rekken · bequest of mayor Smits with a stone tea pavilion from 1912', 'list 36 · no. 642'],
 'loc': '📍 North-east of Eibergen, along the road to Rekken · Freely accessible over roads and paths; the tea pavilion stands along the public road',
 'desc': '<b>Het Kerkloo</b>, nowadays usually called <b>Kerkloobos</b>, is a wooded area of about <b>40 hectares</b> between <b>Eibergen</b> and the hamlet of Rekken, on the transition from the open Eibergse Veld to the valley of the Berkel. The name element ‘loo’ denotes an open wood on sandy soil; ‘kerk’ (church) refers to the church of Eibergen, which once owned or managed the wood. The present wood is a varied mixed forest of broadleaf and conifer, partly planted on <b>rabatten</b> (raised beds with ditches between them for drainage). It came about partly thanks to a <b>bequest of mayor Smits</b>, mayor of Eibergen from 1903 to 1915; the oldest trees date from around 1870, and according to tradition the terrain was already used as a walking wood earlier, around 1820. After the Second World War about 8 hectares were replanted. At the forest edge still stands the <b>stone tea pavilion from 1912</b>. In the winter of 1990 a heavy storm caused much damage in the wood. The Kerkloobos is a popular walking area with quiet paths; among its breeding birds are the black woodpecker, the green woodpecker and the golden oriole, and the Trage Tocht (slow route) Eibergen leads through the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong, golden oriole), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — much birdsong in the breeding season.',
 'why': ['The <b>varied wood of about 40 hectares</b> between Eibergen and Rekken.', 'Its <b>history as a bequest of mayor Smits</b>.', 'The <b>stone tea pavilion from 1912</b>.', 'The <b>breeding birds</b>, including black woodpecker and golden oriole.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Golden oriole and woodpeckers</b> in the breeding season.', '<span class="months">May–Jun</span> 🌸 <b>Verge and forest-edge flora</b>.', '<span class="months">Aug–Oct</span> 🍄 <b>Fungi</b> in the old wood.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of broadleaf and conifer.'],
 'wild': ['🐦 Black woodpecker · Green woodpecker · Golden oriole', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Scots pine · Beech'],
 'trail': ['Walk through the <b>Kerkloobos</b> from the road to Rekken.', 'Look for the <b>tea pavilion from 1912</b> at the forest edge.', 'Follow the <b>Trage Tocht Eibergen</b> through the area.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; tea pavilion not accessible · 🚶 Forest roads and walking paths'
}))

C.append(mk.card(1924, 'Het Zwilbroek', {
 'tags': ['Duitsland · Zwillbrock bij Vreden (grens Rekken–Groenlo)', 'Grensoverschrijdend vennengebied · het Zwillbrocker Venn met de noordelijkste flamingobroedkolonie van Europa', 'list 36 · no. 643'],
 'loc': '📍 Zwillbrock 10, D-48691 Vreden (Noordrijn-Westfalen), vlak over de grens bij Rekken · Vrij toegankelijk; rondwandeling van circa 6 kilometer langs twee vogelkijkhutten',
 'desc': '<b>Het Zwilbroek</b> — in het Duits <b>Zwillbrocker Venn</b> — ligt pal over de Nederlandse grens bij <b>Rekken en Groenlo</b>, in de gemeente Vreden in Noordrijn-Westfalen. Het is een oud veen- en vennengebied dat vroeger door turfstekers werd gebruikt; sinds <b>1985</b> is het beschermd en maakt het deel uit van het Duitse Natura 2000-landschap ‘Moore und Heiden des westlichen Münsterlandes’. Het ven is wereldberoemd geworden door zijn bijzondere gasten: sinds de jaren tachtig broeden er <b>flamingo’s</b> — de noordelijkste broedkolonie van Europa — samen met een grote kolonie kokmeeuwen. Vanaf het voorjaar kleurt het ondiepe, visrijke water roze en wit, en het geluidskoor van duizenden meeuwen is van ver te horen. De beste periode is <b>maart tot juli</b>: dan baltsen en broeden de flamingo’s, die soms met enkele tientallen tegelijk in het ven staan. Een rondwandeling van circa <b>6 kilometer</b> voert om het ven langs twee <b>vogelkijkhutten</b>, waar je met een verrekijker dicht bij het broedgebeuren komt. Het bezoekerscentrum, de <b>Biologische Station Zwillbrock</b> (Zwillbrock 10), is tweetalig ingericht en vertelt het verhaal van het ven, de flamingo’s en de veenhistorie.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–Jul</b> (balts, broedende flamingo’s en meeuwen), okt–mrt (watervogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig bij de kijkhutten.',
 'why': ['De <b>noordelijkste flamingobroedkolonie van Europa</b>.', 'De <b>grote kokmeeuwenkolonie</b> in het voorjaar.', 'De <b>rondwandeling van circa 6 kilometer</b> met twee kijkhutten.', 'Het tweetalige <b>bezoekerscentrum Biologische Station Zwillbrock</b>.'],
 'phen': ['<span class="months">Mrt–Jun</span> 🦩 <b>Balts en broedende flamingo’s</b>.', '<span class="months">Apr–Jul</span> 🐦 <b>Kokmeeuwenkolonie</b> boven het ven.', '<span class="months">Okt–Mrt</span> 🦆 <b>Overwinterende watervogels</b>.', '<span class="months">Mrt–Jul</span> 🔭 <b>Vogelkijkhutten</b> op hun best.'],
 'wild': ['🦩 Flamingo (Chileense en Europese)', '🐦 Kokmeeuw · Zwartkopmeeuw · Slobeend', '🦆 Wintertaling · Tafeleend', '🦋 Zilveren maan · Hooibeestje', '🌿 Veenmos · Pijpenstrootje · Eenarig wollegras'],
 'trail': ['Parkeer bij de <b>Biologische Station Zwillbrock</b>.', 'Loop de <b>rondwandeling van circa 6 kilometer</b> langs de kijkhutten.', 'Neem een <b>verrekijker</b> mee voor de flamingo’s en meeuwen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis; bezoekerscentrum met vrijwillige bijdrage · ⚠️ Broedseizoen: blijf op de paden en in de hutten · 🚶 Gemarkeerde rondwandeling'
}, {
 'tags': ['Germany · Zwillbrock near Vreden (border of Rekken–Groenlo)', 'Cross-border pool area · the Zwillbrocker Venn with Europe’s northernmost flamingo breeding colony', 'list 36 · no. 643'],
 'loc': '📍 Zwillbrock 10, D-48691 Vreden (North Rhine-Westphalia), just across the border from Rekken · Freely accessible; circular walk of about 6 kilometres past two bird hides',
 'desc': '<b>Het Zwilbroek</b> — in German <b>Zwillbrocker Venn</b> — lies just across the Dutch border near <b>Rekken and Groenlo</b>, in the municipality of Vreden in North Rhine-Westphalia. It is an old peat and pool area once used by turf cutters; since <b>1985</b> it has been protected and forms part of the German Natura 2000 landscape ‘Moore und Heiden des westlichen Münsterlandes’. The pool became world-famous through its special guests: since the 1980s <b>flamingos</b> breed here — the northernmost breeding colony in Europe — together with a large colony of black-headed gulls. From spring onwards the shallow, fish-rich water turns pink and white, and the chorus of thousands of gulls can be heard from afar. The best period is <b>March to July</b>: then the flamingos display and breed, sometimes with several dozen standing in the pool at once. A circular walk of about <b>6 kilometres</b> leads around the pool past two <b>bird hides</b>, where with binoculars you come close to the breeding spectacle. The visitor centre, the <b>Biologische Station Zwillbrock</b> (Zwillbrock 10), is set up bilingually and tells the story of the pool, the flamingos and the peat history.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jul</b> (display, breeding flamingos and gulls), Oct–Mar (waterbirds)<br>\n    <b>Best time of day:</b> Morning — quiet at the hides.',
 'why': ['Europe’s <b>northernmost flamingo breeding colony</b>.', 'The <b>large black-headed gull colony</b> in spring.', 'The <b>circular walk of about 6 kilometres</b> with two hides.', 'The bilingual <b>visitor centre Biologische Station Zwillbrock</b>.'],
 'phen': ['<span class="months">Mar–Jun</span> 🦩 <b>Display and breeding flamingos</b>.', '<span class="months">Apr–Jul</span> 🐦 <b>Black-headed gull colony</b> over the pool.', '<span class="months">Oct–Mar</span> 🦆 <b>Wintering waterbirds</b>.', '<span class="months">Mar–Jul</span> 🔭 <b>Bird hides</b> at their best.'],
 'wild': ['🦩 Flamingo (Chilean and European)', '🐦 Black-headed gull · Mediterranean gull · Northern shoveler', '🦆 Teal · Pochard', '🦋 Silver-washed fritillary · Small heath', '🌿 Sphagnum moss · Purple moor-grass · Hare’s-tail cottongrass'],
 'trail': ['Park at the <b>Biologische Station Zwillbrock</b>.', 'Walk the <b>circular route of about 6 kilometres</b> along the hides.', 'Bring <b>binoculars</b> for the flamingos and gulls.'],
 'foot': '🐕 Dogs on lead · 💶 Free; visitor centre with voluntary contribution · ⚠️ Breeding season: stay on the paths and in the hides · 🚶 Marked circular walk'
}, n2k='Het ven ligt in Duitsland en maakt deel uit van het Natura 2000-landschap “Moore und Heiden des westlichen Münsterlandes”.', n2k_en='The pool lies in Germany and forms part of the Natura 2000 landscape “Moore und Heiden des westlichen Münsterlandes”.'))

mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1924)
mk.check()
