# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1880, 'Het Maalderink', {
 'tags': ['Gelderland · Vorden (Bronckhorst)', 'Oud landgoed in de wijk Linde ten oosten van Vorden · onderdeel van het GLK-complex rond de Lindese Laak', 'list 36 · no. 599'],
 'loc': '📍 In de landgoederenwijk Linde ten oosten van Vorden, rond de Maalderinkweg en de Lindese Laak · Landgoed en paden vrij toegankelijk voor wandelaars en fietsers',
 'desc': '<b>Het Maalderink</b> is een van de oude landgoederen in de wijk <b>Linde</b> ten oosten van Vorden, een naam die in het landschap teruggaat tot <b>1402</b>, toen het goed als Maelrink aan het Stift Elten toebehoorde; later was de Hof To Maelrinck een leen van Huis Keppel. Tegenwoordig is Het Maalderink onderdeel van het <b>278 hectare</b> grote landgoederencomplex Kieftskamp, Lindese Laak, Maalderink en Hissink van <b>Geldersch Landschap &amp; Kasteelen</b> (sinds 1975). Rond de oude hoeve liggen hooilanden, houtwallen, oude bomen en de natuurvriendelijk heringerichte oevers van de <b>Lindese Laak</b>, waar inmiddels zo’n 170 plantensoorten zijn geteld; langs het water leven de ijsvogel en veel insecten. De hallenhuisboerderijen in de omgeving dateren uit het midden van de negentiende eeuw en staan op plaatsen waar al eeuwen eerder werd gewoond en gewerkt. Het rustige landgoederenlandschap leent zich uitstekend voor wandel- en fietstochten vanuit Vorden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en weidebloei), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig langs de Laak.',
 'why': ['De <b>eeuwenoude geschiedenis</b> van de naam, van Stift Elten tot Huis Keppel.', 'De ligging in het <b>landgoederenlandschap van de wijk Linde</b>.', 'De <b>natuurvriendelijke oevers van de Lindese Laak</b> met 170 plantensoorten.', 'De <b>stille wandel- en fietspaden</b> vanuit Vorden.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🌷 <b>Stinzenplanten</b> bij de oude erven.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels en ijsvogel</b> langs de Laak.', '<span class="months">Mei–Jul</span> 🌼 <b>Hooilanden en bermen</b> in bloei.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> rond hoeve en houtwallen.'],
 'wild': ['🐦 IJsvogel · Wielewaal · Zwarte specht', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌼 Koekoeksbloem · Penningkruid · Echt duizendguldenkruid'],
 'trail': ['Wandel vanuit <b>Vorden</b> over de landgoedpaden naar Linde.', 'Volg de <b>Laak</b> stroomafwaarts door het landgoederenlandschap.', 'Fiets de <b>landgoederenroute</b> langs Maalderink, Kieftskamp en Hissink.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Klein landgoed zonder voorzieningen; hoeve en erven privé · 🚶 Landgoed- en bospaden'
}, {
 'tags': ['Gelderland · Vorden (Bronckhorst)', 'Old estate in the Linde area east of Vorden · part of the Geldersch Landschap complex around the Lindese Laak', 'list 36 · no. 599'],
 'loc': '📍 In the estate area of Linde east of Vorden, around the Maalderinkweg and the Lindese Laak · Estate and paths freely accessible to walkers and cyclists',
 'desc': '<b>Het Maalderink</b> is one of the old estates in the <b>Linde</b> area east of Vorden, a name that goes back in the landscape to <b>1402</b>, when the property belonged to the Elten monastery as Maelrink; later the Hof To Maelrinck was a fief of Keppel House. Today Het Maalderink is part of the <b>278-hectare</b> estate complex Kieftskamp, Lindese Laak, Maalderink and Hissink of <b>Geldersch Landschap &amp; Kasteelen</b> (since 1975). Around the old farmstead lie hay meadows, hedgerows, old trees and the nature-friendly re-profiled banks of the <b>Lindese Laak</b>, where some 170 plant species have been counted; along the water live the kingfisher and many insects. The hall-house farms in the surroundings date from the mid-nineteenth century and stand where people already lived and worked centuries earlier. The quiet estate landscape is ideal for walking and cycling tours from Vorden.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and meadow bloom), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet along the Laak.',
 'why': ['The <b>centuries-old history</b> of the name, from Elten monastery to Keppel House.', 'Its position in the <b>estate landscape of the Linde area</b>.', 'The <b>nature-friendly banks of the Lindese Laak</b> with 170 plant species.', 'The <b>quiet walking and cycling paths</b> from Vorden.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring flowers</b> at the old farmsteads.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds and kingfisher</b> along the Laak.', '<span class="months">May–Jul</span> 🌼 <b>Hay meadows and verges</b> in bloom.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> around farmstead and hedgerows.'],
 'wild': ['🐦 Kingfisher · Golden oriole · Black woodpecker', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌼 Ragged-robin · Creeping jenny · Centaury'],
 'trail': ['Walk from <b>Vorden</b> over the estate paths towards Linde.', 'Follow the <b>Laak</b> downstream through the estate landscape.', 'Cycle the <b>estate route</b> past Maalderink, Kieftskamp and Hissink.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Small estate without facilities; farmstead and yards private · 🚶 Estate and forest paths'
}))
C.append(mk.card(1881, '\'t Klooster', {
 'tags': ['Gelderland · Hengelo (Bronckhorst)', 'Waterwingebied ten westen van ’t Zand bij Hengelo · 62 hectare rustig bos met heideveldjes en dassen', 'list 36 · no. 600'],
 'loc': '📍 Ten westen van het dorp Hengelo (Gld), in de richting van ’t Zand · Toegankelijk tussen zonsopgang en zonsondergang — wandelen op de paden',
 'desc': 'Het waterwingebied <b>’t Klooster</b> ligt ten westen van het Gelderse dorp Hengelo, in de richting van het natuurgebied ’t Zand. Vitens wint hier sinds jaar en dag drinkwater voor Hengelo, Ruurlo en omgeving en beheert het terrein van <b>62 hectare</b> als natuurgebied: een oase van rust en ruisende bomen, met coulisselandschap, kleine heideterreintjes en een afwisseling van boomsoorten. Verscholen in de bossen ligt een heideveld met enkele jeneverbessen. Speciaal voor reeën, hazen en ander wild is er een <b>ecologische akker</b> die jaarlijks wordt ingezaaid met groenbemester, gerst of rogge; op die graanakker is de bijzondere kleine parelmoervlinder gezien. De waterwinputten liggen tussen margrieten, knoopkruid en pinksterbloemen, waar het oranjetipje op afkomt. In de bossen van ’t Klooster woont een <b>dassenfamilie</b> die in de graslanden en akkers naar insecten zoekt. Het terrein is toegankelijk tussen zonsopgang en zonsondergang en wandelen is toegestaan op de paden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (bloeiende kruiden en vlinders), sep–okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig, kans op wild.',
 'why': ['De <b>rustige bossen en heideveldjes</b> van het 62 hectare grote wingebied.', 'De <b>ecologische akker</b> voor reeën, hazen en ander wild.', 'De <b>dassenfamilie</b> die in het gebied woont.', 'De bloeiende kruiden rond de winputten met <b>oranjetipje en kleine parelmoervlinder</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🦋 <b>Oranjetipje</b> bij de pinksterbloemen.', '<span class="months">Mei–Jul</span> 🌾 <b>Ecologische akker</b> in bloei en vogelrijk.', '<span class="months">Jun–Aug</span> 🦋 <b>Kleine parelmoervlinder</b> op de graanakker.', '<span class="months">Apr–Sep</span> 🦡 <b>Dassen</b> actief in de schemering.'],
 'wild': ['🦡 Das', '🦌 Ree · Haas', '🐦 Zwarte specht · Boomklever · Buizerd', '🦋 Kleine parelmoervlinder · Oranjetipje', '🌼 Margriet · Knoopkruid · Pinksterbloem'],
 'trail': ['Wandel op de <b>paden over het wingebied</b> tussen de bossen.', 'Combineer met het <b>natuurgebied ’t Zand</b> ten oosten van Hengelo.', 'Maak een <b>ochtendwandeling</b> voor ree en das.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Waterwingebied: alleen overdag, alleen op de paden · 🚶 Zand- en boswachterspaden'
}, {
 'tags': ['Gelderland · Hengelo (Bronckhorst)', 'Water catchment area west of ’t Zand near Hengelo · 62 hectares of quiet forest with heath plots and badgers', 'list 36 · no. 599'],
 'loc': '📍 West of the village of Hengelo (Gld), towards ’t Zand · Open between sunrise and sunset — walk on the paths',
 'desc': 'The <b>’t Klooster</b> water catchment area lies west of the Gelderse village of Hengelo, towards the ’t Zand nature area. Vitens has extracted drinking water here for years for Hengelo, Ruurlo and surroundings and manages the <b>62-hectare</b> terrain as a nature area: an oasis of quiet and rustling trees, with small-scale landscape, little heath plots and a variety of tree species. Hidden in the woods lies a heath plot with a few junipers. Especially for roe deer, hares and other wildlife there is an <b>ecological field</b> sown annually with green manure, barley or rye; on that cornfield the special silver-washed fritillary has been seen. The water wells lie among oxeye daisies, greater knapweed and cuckooflower, which attract the orange tip butterfly. In the woods of ’t Klooster lives a <b>family of badgers</b> that searches for insects in the grasslands and fields. The terrain is open between sunrise and sunset and walking is allowed on the paths.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (flowering herbs and butterflies), Sep–Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet, chance of wildlife.',
 'why': ['The <b>quiet woods and heath plots</b> of the 62-hectare catchment area.', 'The <b>ecological field</b> for roe deer, hares and other wildlife.', 'The <b>family of badgers</b> living in the area.', 'The flowering herbs around the wells with <b>orange tip and silver-washed fritillary</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🦋 <b>Orange tip</b> at the cuckooflowers.', '<span class="months">May–Jul</span> 🌾 <b>Ecological field</b> in bloom and bird-rich.', '<span class="months">Jun–Aug</span> 🦋 <b>Silver-washed fritillary</b> on the cornfield.', '<span class="months">Apr–Sep</span> 🦡 <b>Badgers</b> active at dusk.'],
 'wild': ['🦡 Badger', '🦌 Roe deer · Hare', '🐦 Black woodpecker · Nuthatch · Buzzard', '🦋 Silver-washed fritillary · Orange tip', '🌼 Oxeye daisy · Greater knapweed · Cuckooflower'],
 'trail': ['Walk the <b>paths over the catchment area</b> between the woods.', 'Combine with the <b>’t Zand nature area</b> east of Hengelo.', 'Make a <b>morning walk</b> for roe deer and badger.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Water catchment: day only, paths only · 🚶 Sand and forestry paths'
}))

C.append(mk.card(1882, 'Veluwezoom, Nationaal Park', {
 'tags': ['Gelderland · Rheden–Rozendaal (Rheden/Rozendaal)', 'Oudste nationale park van Nederland · 5.000 hectare bos, hei en stuifzand met de Posbank en de landgoederen aan de zuidrand', 'list 36 · no. 601'],
 'loc': '📍 Tussen Arnhem, Dieren en Ede · Bezoekerscentrum Heuvenseweg 5a, Rheden · Start veel routes bij de Posbank of het bezoekerscentrum',
 'desc': 'De <b>Veluwezoom</b> is het oudste nationale park van Nederland — in <b>1911</b> kocht Natuurmonumenten er het eerste stukje grond en sindsdien groeide het uit tot een gebied van ruim <b>5.000 hectare</b> met bossen, heidevelden, zandverstuivingen en landgoederen. Kenmerkend is het <b>reliëf</b>: nergens op de Veluwe vind je zoveel heuvels en vergezichten, zoals vanaf de beroemde <b>Posbank</b>, waar je bij helder weer tot in Duitsland kunt kijken. Over 350 kilometer aan paden kun je wilde zwijnen, reeën en edelherten tegenkomen, en vrijwel zeker <b>Schotse hooglanders</b>; ook grazen er IJslandse paarden en een schaapskudde. De zuidrand van het park ziet er anders uit dan de rest: daar liggen de landgoederen <b>Beekhuizen, Heuven en Rhederoord</b>, waar je wandelt over statige lanen en door oude loofbossen en een klaterende beek oversteekt. Het park grenst via de Terletse heide en het ecoduct Terlet aan de rest van de Veluwe, zodat het wild tot in Deelerwoud kan trekken. Het bezoekerscentrum aan de Heuvenseweg vormt het startpunt van vele routes.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–Sep</b> (heidebloei), sep–okt (bronst), apr–jun (vogelzang)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — wild en rust op de heide.',
 'why': ['Het <b>oudste nationale park van Nederland</b> met 5.000 hectare natuur.', 'Het <b>reliëf en de vergezichten</b>, onder andere vanaf de Posbank.', 'De <b>grote grazers</b>: Schotse hooglanders, IJslandse paarden en schapen.', 'De <b>landgoederenzuidrand</b> met Beekhuizen, Heuven en Rhederoord.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de heuvels paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronsttijd</b> van de edelherten.', '<span class="months">Heel jaar</span> 🐂 <b>Schotse hooglanders</b> op de heide.', '<span class="months">Apr–Jun</span> 🐦 <b>Vogelzang</b> in bossen en landgoederen.'],
 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐂 Schotse hooglander', '🐑 Schaapskudde · IJslands paard', '🐦 Zwarte specht · Boomleeuwerik · Nachtzwaluw', '🦎 Levendbarende hagedis · Adder'],
 'trail': ['Wandel vanaf de <b>Posbank</b> over de heideheuvels.', 'Start bij het <b>bezoekerscentrum Veluwezoom</b> aan de Heuvenseweg.', 'Verken de <b>landgoederen Beekhuizen en Heuven</b> aan de zuidrand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Bronst- en broedtijd: houd afstand van wild; toegang na zonsondergang afgesloten op de heide · 🚶 350 km paden'
}, {
 'tags': ['Gelderland · Rheden–Rozendaal (Rheden/Rozendaal)', 'Oldest national park of the Netherlands · 5,000 hectares of forest, heath and drifting sand with the Posbank and the estates along the southern edge', 'list 36 · no. 600'],
 'loc': '📍 Between Arnhem, Dieren and Ede · Visitor centre Heuvenseweg 5a, Rheden · Many routes start at the Posbank or the visitor centre',
 'desc': 'The <b>Veluwezoom</b> is the oldest national park of the Netherlands — in <b>1911</b> Natuurmonumenten bought its first piece of land here, and since then it has grown into an area of over <b>5,000 hectares</b> with forests, heathland, drifting sand and country estates. Its hallmark is the <b>relief</b>: nowhere on the Veluwe will you find so many hills and views, such as from the famous <b>Posbank</b>, where on a clear day you can see all the way to Germany. Over 350 kilometres of paths you can encounter wild boar, roe deer and red deer, and almost certainly <b>Highland cattle</b>; Icelandic horses and a sheep flock also graze here. The southern edge of the park looks different from the rest: there lie the estates of <b>Beekhuizen, Heuven and Rhederoord</b>, where you walk over stately avenues and through old broadleaf woods and cross a babbling brook. Via the Terletse heide and the Terlet ecoduct the park connects with the rest of the Veluwe, so wildlife can roam as far as the Deelerwoud. The visitor centre on the Heuvenseweg is the starting point of many routes.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather bloom), Sep–Oct (rut), Apr–Jun (birdsong)<br>\n    <b>Best time of day:</b> Early morning — wildlife and quiet on the heath.',
 'why': ['The <b>oldest national park of the Netherlands</b> with 5,000 hectares of nature.', 'The <b>relief and views</b>, among others from the Posbank.', 'The <b>large grazers</b>: Highland cattle, Icelandic horses and sheep.', 'The <b>estate-lined southern edge</b> with Beekhuizen, Heuven and Rhederoord.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the hills purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Rut</b> of the red deer.', '<span class="months">All year</span> 🐂 <b>Highland cattle</b> on the heath.', '<span class="months">Apr–Jun</span> 🐦 <b>Birdsong</b> in woods and estates.'],
 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐂 Highland cattle', '🐑 Sheep flock · Icelandic horse', '🐦 Black woodpecker · Woodlark · Nightjar', '🦎 Viviparous lizard · Adder'],
 'trail': ['Walk from the <b>Posbank</b> over the heath hills.', 'Start at the <b>Veluwezoom visitor centre</b> on the Heuvenseweg.', 'Explore the <b>Beekhuizen and Heuven estates</b> along the southern edge.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Rut and breeding season: keep your distance from wildlife; heath closed after sunset · 🚶 350 km of paths'
}))

C.append(mk.card(1883, 'Hof te Dieren', {
 'tags': ['Gelderland · Dieren (Rheden)', 'Landgoed van Stichting Twickel ten zuiden van Dieren · oud Oranje-jachtslot, Sterrenbos en grootste ommuurde wijngaard van Nederland', 'list 36 · no. 602'],
 'loc': '📍 Ten zuiden van Dieren, tussen de Arnhemsestraatweg en de IJssel · Groot deel van het landgoed vrij toegankelijk; het kasteelterrein zelf niet',
 'desc': '<b>Hof te Dieren</b> is het historische landgoed ten zuiden van Dieren, op de overgang van de Veluwezoom naar de IJsselvallei. De plek wordt al in <b>838</b> genoemd als Theothorne; in de middeleeuwen vestigde de Duitse Orde er een commanderij. In <b>1647</b> kocht stadhouder Willem II het landgoed, en zijn zoon Willem III liet het middeleeuwse huis door architect Jacob Roman verbouwen tot een <b>jachtslot</b>, van waaruit hij joeg in de wildbaan van de Veluwezoom. Tijdens de Franse intocht van <b>1795</b> brandde het huis af; rond 1820 verrees een nieuw landhuis met een tuin in Engelse landschapsstijl van de hand van Jan David Zocher en Eduard Petzold. In de Tweede Wereldoorlog werd het huis opnieuw door brand verwoest en in <b>1965</b> gesloopt; vandaag herinneren fundamenten en een ijskelder aan het rijke verleden. Het landgoed behoort tot <b>Stichting Twickel</b>. Een groot deel — waaronder het Sterrenbos en de Carolinaberg — is vrij toegankelijk; binnen de oude moestuinmuren ligt <b>Domein Hof te Dieren</b>, de grootste ommuurde wijngaard van Nederland, die je met een rondleiding kunt bezoeken.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), sep–okt (wijnoogst), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in Sterrenbos en lanen.',
 'why': ['De <b>rijke Oranje- en landgoedgeschiedenis</b> van jachtslot tot ruïne.', 'Het vrij toegankelijke <b>Sterrenbos en de Carolinaberg</b>.', 'De <b>grootste ommuurde wijngaard van Nederland</b>.', 'De <b>tuinaanleg van Zocher en Petzold</b> in landschapsstijl.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels en spechten</b> in het Sterrenbos.', '<span class="months">Mei–Jun</span> 🌿 <b>Voorjaarsflora</b> op de oude landgoedgronden.', '<span class="months">Sep–Okt</span> 🍇 <b>Wijnoogst</b> in de ommuurde wijngaard.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het landschapspark.'],
 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Gehakkelde aurelia', '🌳 Beuk · Zomereik · Linde'],
 'trail': ['Wandel door het <b>Sterrenbos</b> en over de Carolinaberg.', 'Bezoek <b>Domein Hof te Dieren</b> met een rondleiding.', 'Maak een <b>landgoedwandeling</b> over de lanen richting de IJssel.'],
 'foot': '🐕 Honden aangelijnd · 💶 Landgoed gratis; wijngaard tegen betaling · ⚠️ Kasteelterrein niet toegankelijk · 🚶 Landgoed- en bospaden'
}, {
 'tags': ['Gelderland · Dieren (Rheden)', 'Estate of Stichting Twickel south of Dieren · old Orange hunting castle, Sterrenbos and the largest walled vineyard of the Netherlands', 'list 36 · no. 601'],
 'loc': '📍 South of Dieren, between the Arnhemsestraatweg and the IJssel · A large part of the estate is freely accessible; the castle grounds themselves are not',
 'desc': '<b>Hof te Dieren</b> is the historic estate south of Dieren, on the transition from the Veluwezoom to the IJssel valley. The site is already mentioned in <b>838</b> as Theothorne; in the Middle Ages the Teutonic Order founded a commandery there. In <b>1647</b> Stadtholder William II bought the estate, and his son William III had the medieval house converted by architect Jacob Roman into a <b>hunting castle</b>, from which he hunted in the game park of the Veluwezoom. During the French invasion of <b>1795</b> the house burned down; around 1820 a new country house arose with a garden in English landscape style by Jan David Zocher and Eduard Petzold. In the Second World War the house was again destroyed by fire and demolished in <b>1965</b>; today foundations and an ice cellar recall the rich past. The estate belongs to <b>Stichting Twickel</b>. A large part — including the Sterrenbos and the Carolinaberg — is freely accessible; within the old kitchen-garden walls lies <b>Domein Hof te Dieren</b>, the largest walled vineyard of the Netherlands, which you can visit on a guided tour.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Sep–Oct (grape harvest), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the Sterrenbos and avenues.',
 'why': ['The <b>rich Orange and estate history</b> from hunting castle to ruin.', 'The freely accessible <b>Sterrenbos and the Carolinaberg</b>.', 'The <b>largest walled vineyard of the Netherlands</b>.', 'The <b>landscape-style garden design of Zocher and Petzold</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds and woodpeckers</b> in the Sterrenbos.', '<span class="months">May–Jun</span> 🌿 <b>Spring flora</b> on the old estate grounds.', '<span class="months">Sep–Oct</span> 🍇 <b>Grape harvest</b> in the walled vineyard.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the landscape park.'],
 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Comma', '🌳 Beech · Pedunculate oak · Lime'],
 'trail': ['Walk through the <b>Sterrenbos</b> and over the Carolinaberg.', 'Visit <b>Domein Hof te Dieren</b> on a guided tour.', 'Take an <b>estate walk</b> along the avenues towards the IJssel.'],
 'foot': '🐕 Dogs on lead · 💶 Estate free; vineyard for a fee · ⚠️ Castle grounds not accessible · 🚶 Estate and forest paths'
}))

C.append(mk.card(1884, 'Rozendaalse Veld', {
 'tags': ['Gelderland · Rozendaal (Rozendaal)', 'Groot heide- en stuifzandgebied ten noorden van Velp · 542 hectare hooggelegen hei met brandtoren en glooiend reliëf', 'list 36 · no. 603'],
 'loc': '📍 Ten noorden van Velp en Rozendaal, aan de rand van Nationaal Park Veluwezoom · Parkeerplaats aan de Kluizenaarsweg · Toegang verboden tussen zonsondergang en zonsopgang',
 'desc': 'Het <b>Rozendaalse Veld</b> is een groot heidegebied van <b>542 hectare</b> in de gemeente Rozendaal, ten noorden van Velp en grenzend aan Nationaal Park Veluwezoom. Het is een vrij hooggelegen heideveld met opvallend veel <b>reliëf en hoogteverschillen</b>: glooiende paarse heide, zandverstuivingen, vliegdennen en jeneverbessen wisselen elkaar af, met weidse uitzichten over de Veluwezoom. Op het veld staat een <b>brandtoren van 33 meter</b> (op circa 110 meter hoogte) die tot 1978 door de brandweer werd gebruikt om bos- en heidebranden te ontdekken. Het gebied is rijk aan heide- en bosvogels — denk aan boomleeuwerik, nachtzwaluw en klapekster — en aan de randen leven edelherten, wilde zwijnen en reeën. Een rondwandeling van ongeveer zes kilometer voert over het veld; het terrein is ook een geliefd losloopgebied voor honden langs de Kluizenaarsweg. Toegang is verboden tussen zonsondergang en zonsopgang.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–Sep</b> (heidebloei), mei–jun (broedvogels), okt–mrt (klapekster)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — licht op de heide.',
 'why': ['Het <b>grote, hooggelegen heideveld</b> met veel reliëf.', 'De <b>33 meter hoge brandtoren</b> als blikvanger.', 'De <b>afwisseling van hei, stuifzand, vliegdennen en jeneverbes</b>.', 'De weidse uitzichten over de <b>Veluwezoom</b>.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt de glooiingen paars.', '<span class="months">Mrt–Jul</span> 🐦 <b>Boomleeuwerik</b> zingt boven de heide.', '<span class="months">Mei–Jul</span> 🐦 <b>Nachtzwaluw</b> in de schemering.', '<span class="months">Okt–Mrt</span> 🐦 <b>Klapekster</b> overwintert op het veld.'],
 'wild': ['🐦 Boomleeuwerik · Nachtzwaluw · Klapekster', '🦌 Edelhert · Ree · Wild zwijn', '🦎 Levendbarende hagedis · Adder', '🦋 Heivlinder · Bruin blauwtje', '🌼 Struikhei · Dophei · Jeneverbes'],
 'trail': ['Loop de <b>rondwandeling van circa 6 km</b> over het heideveld.', 'Start bij de <b>parkeerplaats aan de Kluizenaarsweg</b>.', 'Combineer met <b>kasteel Rosendael of de Beekhuizense bossen</b>.'],
 'foot': '🐕 Honden los toegestaan in het losloopgedeelte (Kluizenaarsweg) · 💶 Gratis · ⚠️ Toegang verboden tussen zonsondergang en zonsopgang · 🚶 Heide- en zandpaden'
}, {
 'tags': ['Gelderland · Rozendaal (Rozendaal)', 'Large heath and drifting-sand area north of Velp · 542 hectares of elevated heath with fire tower and rolling relief', 'list 36 · no. 602'],
 'loc': '📍 North of Velp and Rozendaal, at the edge of National Park Veluwezoom · Car park on the Kluizenaarsweg · Access forbidden between sunset and sunrise',
 'desc': 'The <b>Rozendaalse Veld</b> is a large heath area of <b>542 hectares</b> in the municipality of Rozendaal, north of Velp and bordering National Park Veluwezoom. It is a fairly elevated heath field with remarkably much <b>relief and difference in height</b>: rolling purple heath, drifting sand, self-sown Scots pines and junipers alternate, with wide views over the Veluwezoom. On the field stands a <b>fire tower of 33 metres</b> (at about 110 metres elevation) used until 1978 by the fire brigade to spot forest and heath fires. The area is rich in heath and forest birds — think woodlark, nightjar and great grey shrike — and at the edges live red deer, wild boar and roe deer. A circular walk of about six kilometres leads over the field; the terrain along the Kluizenaarsweg is also a popular dog off-leash area. Access is forbidden between sunset and sunrise.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather bloom), May–Jun (breeding birds), Oct–Mar (great grey shrike)<br>\n    <b>Best time of day:</b> Morning or late afternoon — light on the heath.',
 'why': ['The <b>large, elevated heath field</b> with much relief.', 'The <b>33-metre fire tower</b> as an eyecatcher.', 'The <b>alternation of heath, drifting sand, pines and juniper</b>.', 'The wide views over the <b>Veluwezoom</b>.'],
 'phen': ['<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the slopes purple.', '<span class="months">Mar–Jul</span> 🐦 <b>Woodlark</b> sings above the heath.', '<span class="months">May–Jul</span> 🐦 <b>Nightjar</b> at dusk.', '<span class="months">Oct–Mar</span> 🐦 <b>Great grey shrike</b> winters on the field.'],
 'wild': ['🐦 Woodlark · Nightjar · Great grey shrike', '🦌 Red deer · Roe deer · Wild boar', '🦎 Viviparous lizard · Adder', '🦋 Grayling · Silver-studded blue', '🌼 Bell heather · Cross-leaved heath · Juniper'],
 'trail': ['Walk the <b>circular route of about 6 km</b> over the heath field.', 'Start at the <b>car park on the Kluizenaarsweg</b>.', 'Combine with <b>Rosendael Castle or the Beekhuizense bossen</b>.'],
 'foot': '🐕 Dogs off-lead allowed in the off-leash section (Kluizenaarsweg) · 💶 Free · ⚠️ Access forbidden between sunset and sunrise · 🚶 Heath and sand paths'
}))


mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1884)
mk.check()
