# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1900, 'Groot-Boerman', {
 'tags': ['Overijssel · Hengevelde (Hof van Twente)', 'Naam uit de gids die teruggaat op de eeuwenoude hofstede Boerman bij Hengevelde · geen eigen terrein, wel het coulisselandschap tussen Schipbeek en Regge', 'list 36 · no. 619'],
 'loc': '📍 In het buitengebied van Hengevelde, tussen de Schipbeek en de Regge · Oude hofstede in particulier cultuurlandschap — geen eigen parkeerterrein of route',
 'desc': '<b>Groot-Boerman</b> is een naam die de gids vermeldt in de reeks landgoederen en terreinen tussen Diepenheim en Hengevelde, in het Twentse coulisselandschap ten zuidoosten van Goor. De naam gaat terug op de <b>erve Boerman</b> — ook wel ‘Grooten Boerman’ genoemd — een van de ‘eeuwenoude hofsteden’ die historische gidsen rond 1900 bij Hengevelde noemen: in de Gids voor Twente uit 1917 verschijnen Kagelink, Boerman en Damme als oude hoeven in deze buurtschap. Een zelfstandig natuurterrein met eigen parkeerplaats of gemarkeerde route draagt Groot-Boerman vandaag niet; de oude hofstede ligt verscholen in het kleinschalige landschap van essen, houtwallen en beekjes rond het dorp. Net als bij enkele andere namen uit deze oude bron registreert deze kaart daarom eerlijk wat er wél bekend is: Groot-Boerman hoort bij het agrarische cultuurlandschap tussen de Schipbeek en de Regge, dat via het Wandelnetwerk Twente vrij te belopen is.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang, bloeiende houtwallen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond.',
 'why': ['De <b>oude hofstede Boerman</b>, in 1917 al ‘eeuwenoude hofstede’ genoemd.', 'De verwijzing in de <b>Gids voor Twente</b> naar Kagelink, Boerman en Damme.', 'Het <b>coulisselandschap</b> van essen, houtwallen en beekjes.', 'De wandelmogelijkheden via het <b>Wandelnetwerk Twente</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en singels.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs wegen en paden.', '<span class="months">Mei–Jul</span> 🐄 <b>Vee</b> op de hooilanden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Gele kwikstaart · Veldleeuwerik · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Es · Meidoorn'],
 'trail': ['Wandel over wegen en paden rond <b>Hengevelde</b>.', 'Verken het coulisselandschap tussen <b>Schipbeek en Regge</b>.', 'Combineer met <b>Huis te Diepenheim of het landgoed Twickel</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Agrarisch particulier landschap zonder voorzieningen — wandel met respect voor bewoners · 🚶 Wegen en landbouwwegen'
}, {
 'tags': ['Overijssel · Hengevelde (Hof van Twente)', 'Name from the guide going back to the centuries-old Boerman farmstead near Hengevelde · no terrain of its own, but the small-scale landscape between the Schipbeek and the Regge', 'list 36 · no. 619'],
 'loc': '📍 In the countryside of Hengevelde, between the Schipbeek and the Regge · Old farmstead in a private agricultural landscape — no own car park or route',
 'desc': '<b>Groot-Boerman</b> is a name the guide lists among the estates and areas between Diepenheim and Hengevelde, in the Twente small-scale landscape southeast of Goor. The name goes back to the <b>Boerman farmstead</b> — also written ‘Grooten Boerman’ — one of the ‘centuries-old homesteads’ that guides from around 1900 mention near Hengevelde: in the 1917 Guide to Twente, Kagelink, Boerman and Damme appear as old farms in this hamlet. Today Groot-Boerman carries no separate nature area with its own car park or marked route; the old farmstead lies hidden in the small-scale landscape of essen, hedgerows and brooklets around the village. As with several other names from this old source, this card therefore honestly registers what is known: Groot-Boerman belongs to the agricultural cultural landscape between the Schipbeek and the Regge, freely walkable via the Twente walking network.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong, blooming hedgerows), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or evening.',
 'why': ['The <b>old Boerman farmstead</b>, already called a ‘centuries-old homestead’ in 1917.', 'The mention of <b>Kagelink, Boerman and Damme</b> in the Guide to Twente.', 'The <b>small-scale landscape</b> of essen, hedgerows and brooklets.', 'The walking options via the <b>Twente walking network</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and belts of trees.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along roads and paths.', '<span class="months">May–Jul</span> 🐄 <b>Cattle</b> on the hay meadows.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Yellow wagtail · Skylark · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Ash · Hawthorn'],
 'trail': ['Walk on roads and paths around <b>Hengevelde</b>.', 'Explore the small-scale landscape between the <b>Schipbeek and the Regge</b>.', 'Combine with <b>Huis te Diepenheim or Twickel estate</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Agricultural private landscape without facilities — walk with respect for residents · 🚶 Roads and farm lanes'
}))

C.append(mk.card(1901, 'Hengevelde', {
 'tags': ['Overijssel · Hengevelde (Hof van Twente)', 'Dorp tussen Markelo en Delden in het Twentse coulisselandschap · geen eigen natuurterrein — de omgeving is te wandelen via het Wandelnetwerk Twente', 'list 36 · no. 620'],
 'loc': '📍 Rond het dorp Hengevelde, tussen Markelo en Delden (Hof van Twente) · Dorp in het coulisselandschap zonder eigen natuurterrein — wandel via het Wandelnetwerk Twente',
 'desc': '<b>Hengevelde</b> is een dorp in de gemeente Hof van Twente, tussen Markelo en Delden, dat de gids in het register van wandelgebieden opneemt. Een afzonderlijk aangewezen natuurreservaat ‘Hengevelde’ bestaat niet; de naam verwijst naar het dorp en zijn oude buurtschap, die liggen in het <b>Twentse coulisselandschap</b>: het kleinschalige landschap van essen, akkers, weilanden, <b>houtwallen en beekjes</b>. Rond Hengevelde voeren wandel- en fietsroutes onder meer langs de <b>Bolscherbeek</b>, een schoon Twents beekje dat natuur- en vogelliefhebbers door het buitengebied begeleidt. Het dorp is aangesloten op het Wandelnetwerk Twente met drieduizend kilometer bewegwijzerde routes, zodat de omgeving zich uitstekend leent voor een rondwandeling langs monumentale boerderijen en oude hofsteden — waaronder de eeuwenoude erven Kagelink, Boerman en Damme die historische bronnen bij Hengevelde noemen. Deze kaart registreert de naam eerlijk als onderdeel van dat wandellandschap, zonder eigen terrein of voorzieningen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang, bloeiende houtwallen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in het buitengebied.',
 'why': ['Het <b>typische Twentse coulisselandschap</b> rond het dorp.', 'Wandelen langs de <b>Bolscherbeek</b> en oude hofsteden.', 'De monumentale <b>Saksische boerderijen</b> in de omgeving.', 'De <b>duizenden kilometers bewegwijzerde routes</b> van het wandelnetwerk.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en beekjes.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs de paden.', '<span class="months">Mei–Jul</span> 🐄 <b>Vee</b> op de weilanden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Gele kwikstaart · Veldleeuwerik · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Es · Meidoorn'],
 'trail': ['Start in het dorp en volg de <b>knooppunten van het wandelnetwerk</b>.', 'Wandel langs de <b>Bolscherbeek</b> en de oude hofsteden.', 'Combineer met <b>Markelo, Delden of het Twentekanaal</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen eigen natuurterrein of voorzieningen — wandel met respect voor bewoners · 🚶 Wegen en landbouwwegen'
}, {
 'tags': ['Overijssel · Hengevelde (Hof van Twente)', 'Village between Markelo and Delden in the Twente small-scale landscape · no nature area of its own — the surroundings can be walked via the Twente walking network', 'list 36 · no. 620'],
 'loc': '📍 Around the village of Hengevelde, between Markelo and Delden (Hof van Twente) · Village in the small-scale landscape without its own nature area — walk via the Twente walking network',
 'desc': '<b>Hengevelde</b> is a village in the municipality of Hof van Twente, between Markelo and Delden, which the guide includes in its register of walking areas. No separately designated nature reserve ‘Hengevelde’ exists; the name refers to the village and its old hamlet, which lie in the <b>Twente small-scale landscape</b>: the intimate landscape of essen, fields, meadows, <b>hedgerows and brooklets</b>. Around Hengevelde walking and cycling routes lead, among others, along the <b>Bolscherbeek</b>, a clean Twente brook that accompanies nature and bird lovers through the countryside. The village is connected to the Twente walking network with three thousand kilometres of signposted routes, so the surroundings are ideal for a circular walk past monumental farmsteads and old homesteads — including the centuries-old farms Kagelink, Boerman and Damme that historical sources mention near Hengevelde. This card honestly registers the name as part of that walking landscape, without terrain or facilities of its own.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong, blooming hedgerows), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the countryside.',
 'why': ['The <b>typical Twente small-scale landscape</b> around the village.', 'Walking along the <b>Bolscherbeek</b> and old homesteads.', 'The monumental <b>Low Saxon farmsteads</b> in the area.', 'The <b>thousands of kilometres of signposted routes</b> in the network.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and brook valleys.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along the paths.', '<span class="months">May–Jul</span> 🐄 <b>Cattle</b> on the meadows.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Yellow wagtail · Skylark · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Ash · Hawthorn'],
 'trail': ['Start in the village and follow the <b>junction signs of the walking network</b>.', 'Walk along the <b>Bolscherbeek</b> and the old homesteads.', 'Combine with <b>Markelo, Delden or the Twente Canal</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No nature area or facilities of its own — walk with respect for residents · 🚶 Roads and farm lanes'
}))

C.append(mk.card(1902, 'Twickel', {
 'tags': ['Overijssel · Ambt Delden (Hof van Twente)', 'Grootste particuliere landgoed van Nederland, al sinds 1347 · kasteel, parkbossen, beken, boerderijen en wandelroutes vanaf de Twickelerlaan', 'list 36 · no. 621'],
 'loc': '📍 Bij Delden (Hof van Twente), start Twickelerlaan 7 · Kasteel en tuinen op gezette tijden te bezoeken; het landgoed is grotendeels vrij toegankelijk voor wandelaars',
 'desc': '<b>Landgoed Twickel</b> bij Delden is met zijn ruim <b>4.000 hectare</b> het grootste particuliere landgoed van Nederland en wordt al sinds de veertiende eeuw bewoond — de oudste vermelding dateert uit <b>1347</b>. Kasteel Twickel ligt in een landschap van parkbossen, beken, weilanden, essen, heide en vele boerderijen die nog altijd bij het landgoed horen. Rondom het kasteel loopt de <b>kasteelwandeling</b> van circa 4,5 kilometer, die start aan de <b>Twickelerlaan 7</b> en door het parkbos met oude bomen, vijvers en de Oude Gracht voert. Verderop op het landgoed draait de <b>Noordmolen</b> uit 1347 nog als oliemolen, en het bekenstelsel van Twickel behoort tot de best bewaarde van Nederland. Van oudsher is een groot deel van het landgoed opengesteld voor wandelaars; de wandelroutes zijn gemarkeerd en lopen ook over de historische <b>Umfassungsweg</b> langs de grens van het landgoed. Wie wil, combineert een bezoek aan de kasteeltuin en het park met een wandeling door de omliggende landgoedbossen en langs de Twickelse boerderijen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (park en tuinen), okt (herfst), mei (kasteeltuin)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de paden.',
 'why': ['Het <b>grootste particuliere landgoed van Nederland</b> met 700 jaar historie.', 'De <b>kasteelwandeling</b> van 4,5 km door het parkbos.', 'De <b>Noordmolen</b> en het gave bekenstelsel.', 'De historische <b>Umfassungsweg</b> rond het landgoed.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🌿 <b>Stinsenplanten</b> en voorjaarsbloei in het park.', '<span class="months">Mei–Jun</span> 🏰 <b>Kasteel en tuinen</b> op gezette tijden open.', '<span class="months">Heel jaar</span> 💧 <b>Noordmolen</b> en watermolen in bedrijf.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in park en bos.'],
 'wild': ['🐦 Zwarte specht · Boomklever · Buizerd', '🦌 Ree · Damhert', '🦊 Vos · Das', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Beuk · Es'],
 'trail': ['Start de <b>kasteelwandeling</b> aan de Twickelerlaan 7.', 'Bezoek de <b>Noordmolen</b> en het bekenlandschap.', 'Wandel een stuk van de <b>Umfassungsweg</b> langs de landgoedgrens.'],
 'foot': '🐕 Honden aangelijnd · 💶 Kasteel en tuinen tegen betaling; landgoed gratis · ⚠️ Check openingstijden op twickel.nl · 🚶 Gemarkeerde landgoedpaden'
}, {
 'tags': ['Overijssel · Ambt Delden (Hof van Twente)', 'Largest privately owned estate of the Netherlands, inhabited since 1347 · castle, park woods, brooks, farms and walking routes from the Twickelerlaan', 'list 36 · no. 621'],
 'loc': '📍 Near Delden (Hof van Twente), start Twickelerlaan 7 · Castle and gardens open at set times; the estate is largely freely accessible to walkers',
 'desc': '<b>Twickel Estate</b> near Delden, with its more than <b>4,000 hectares</b>, is the largest privately owned estate of the Netherlands and has been inhabited since the fourteenth century — the oldest mention dates from <b>1347</b>. Twickel Castle lies in a landscape of park woods, brooks, meadows, essen, heath and many farms that still belong to the estate. Around the castle runs the <b>castle walk</b> of about 4.5 kilometres, starting at <b>Twickelerlaan 7</b> and leading through the park wood with ancient trees, ponds and the Oude Gracht. Further on the estate the <b>Noordmolen</b> from 1347 still works as an oil mill, and the brook system of Twickel is among the best preserved in the Netherlands. A large part of the estate has traditionally been open to walkers; the walking routes are marked and also run over the historic <b>Umfassungsweg</b> along the edge of the estate. Visitors can combine a visit to the castle garden and park with a walk through the surrounding estate woods and past the Twickel farms.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (park and gardens), Oct (autumn), May (castle garden)<br>\n    <b>Best time of day:</b> Morning — quiet on the paths.',
 'why': ['The <b>largest private estate of the Netherlands</b> with 700 years of history.', 'The <b>castle walk</b> of 4.5 km through the park wood.', 'The <b>Noordmolen</b> and the intact brook system.', 'The historic <b>Umfassungsweg</b> around the estate.'],
 'phen': ['<span class="months">Mar–May</span> 🌿 <b>Stinsen plants and spring bloom</b> in the park.', '<span class="months">May–Jun</span> 🏰 <b>Castle and gardens</b> open at set times.', '<span class="months">All year</span> 💧 <b>Noordmolen</b> and watermill working.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in park and woods.'],
 'wild': ['🐦 Black woodpecker · Nuthatch · Buzzard', '🦌 Roe deer · Fallow deer', '🦊 Fox · Badger', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Beech · Ash'],
 'trail': ['Start the <b>castle walk</b> at Twickelerlaan 7.', 'Visit the <b>Noordmolen</b> and the brook landscape.', 'Walk a stretch of the <b>Umfassungsweg</b> along the estate edge.'],
 'foot': '🐕 Dogs on lead · 💶 Castle and gardens for a fee; estate free · ⚠️ Check opening hours at twickel.nl · 🚶 Marked estate paths'
}))

C.append(mk.card(1903, 'Stepelerveld', {
 'tags': ['Overijssel · Beckum–Haaksbergen (Enschede/Haaksbergen)', 'Bos-, heide- en vennengebied tussen Beckum en Haaksbergen · in 1984 door Natuurmonumenten gekocht, sinds 1995 bij landgoed Twickel', 'list 36 · no. 622'],
 'loc': '📍 Tussen Beckum (Enschede) en Haaksbergen, startpunt aan de Wieskamp 7481 PB Haaksbergen · Vrij toegankelijk, 24 uur per dag',
 'desc': 'Het <b>Stepelerveld</b> is een natuurgebied op de grens van de gemeenten Enschede en Haaksbergen, tussen de buurtschap <b>Beckum</b> en Haaksbergen. Tot in de zeventiende eeuw was dit een onherbergzame, woeste streek: rond <b>1615</b> werd er een eerste ‘maat in het veld’ ontgonnen, waaraan de nabijgelegen Veldmaat haar naam dankt. Rond 1900 kwam het terrein in handen van de textielfamilie <b>Van Heek</b>; in <b>1984</b> kocht Natuurmonumenten het van de erven Van Heek, en in <b>1995</b> ging het via een ruil over naar <b>landgoed Twickel</b>, dat het sindsdien beheert. Het terrein is vrij toegankelijk. Een wandeling voert langs heideveldjes en vennen, over singels en door een bos dat langzaam verandert van eenvormig dennenbos in een gevarieerd bos met loofbomen; langs de bosrand laten reeën zich geregeld zien. Vanaf het startpunt aan de <b>Wieskamp</b> zijn ook de omliggende boerenerven, heideveldjes en vennen van het buitengebied van Beckum te verkennen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), aug–sep (heidebloei), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — reeën langs de bosrand.',
 'why': ['De <b>bos-heide-vennen-mozaïek</b> tussen Beckum en Haaksbergen.', 'De bewogen eigendomsgeschiedenis: Van Heek, Natuurmonumenten (1984), Twickel (1995).', 'Het <b>langzaam veranderende bos</b>: van dennenbos naar gevarieerd loofbos.', 'De <b>eeuwenoude ontginningsgeschiedenis</b> van de Veldmaat (1615).'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in het gevarieerde bos.', '<span class="months">Jun–Sep</span> 🦋 <b>Vlinders</b> op heide en in bermen.', '<span class="months">Aug–Sep</span> 🌸 <b>Heidebloei</b> op de veldjes.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in bos en singels.'],
 'wild': ['🐦 Boomklever · Grote bonte specht · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦎 Levendbarende hagedis', '🌲 Grove den · Ruwe berk · Zomereik'],
 'trail': ['Start bij het <b>informatiepunt aan de Wieskamp</b> in Haaksbergen.', 'Wandel over de paden langs <b>heideveldjes en vennen</b>.', 'Verken het <b>buitengebied van Beckum</b> met zijn boerenerven.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen gebouwde voorzieningen · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Overijssel · Beckum–Haaksbergen (Enschede/Haaksbergen)', 'Area of wood, heath and pools between Beckum and Haaksbergen · bought by Natuurmonumenten in 1984, part of Twickel estate since 1995', 'list 36 · no. 622'],
 'loc': '📍 Between Beckum (Enschede) and Haaksbergen, starting point on Wieskamp 7481 PB Haaksbergen · Freely accessible, 24 hours a day',
 'desc': 'The <b>Stepelerveld</b> is a nature area on the border of the municipalities of Enschede and Haaksbergen, between the hamlet of <b>Beckum</b> and Haaksbergen. Until the seventeenth century this was a wild, inhospitable region: around <b>1615</b> the first ‘maat in the veld’ (a meadow lot in the field) was reclaimed here, to which the nearby Veldmaat owes its name. Around 1900 the land came into the hands of the <b>Van Heek</b> textile family; in <b>1984</b> Natuurmonumenten bought it from the Van Heek heirs, and in <b>1995</b> it passed through a swap to <b>Twickel estate</b>, which has managed it since. The terrain is freely accessible. A walk leads past heath plots and pools, over belts of trees and through a forest slowly changing from monotonous pine wood into a varied wood with broadleaved trees; roe deer regularly show themselves along the forest edge. From the starting point on the <b>Wieskamp</b> the surrounding farmyards, heath plots and pools of the Beckum countryside can also be explored.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Aug–Sep (heather bloom), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — roe deer along the forest edge.',
 'why': ['The <b>mosaic of wood, heath and pools</b> between Beckum and Haaksbergen.', 'The eventful ownership history: Van Heek, Natuurmonumenten (1984), Twickel (1995).', 'The <b>slowly changing forest</b>: from pine wood to varied broadleaved wood.', 'The <b>centuries-old reclamation history</b> of the Veldmaat (1615).'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in the varied forest.', '<span class="months">Jun–Sep</span> 🦋 <b>Butterflies</b> on heath and verges.', '<span class="months">Aug–Sep</span> 🌸 <b>Heather bloom</b> on the plots.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in wood and belts of trees.'],
 'wild': ['🐦 Nuthatch · Great spotted woodpecker · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦎 Viviparous lizard', '🌲 Scots pine · Silver birch · Pedunculate oak'],
 'trail': ['Start at the <b>information point on the Wieskamp</b> in Haaksbergen.', 'Walk the paths past <b>heath plots and pools</b>.', 'Explore the <b>Beckum countryside</b> with its farmyards.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No built facilities · 🚶 Forest and sandy paths'
}))

C.append(mk.card(1904, 'De Huttensmit en Koksbos', {
 'tags': ['Overijssel · tussen Enschede en Haaksbergen', 'Naam uit de gids voor een vrij toegankelijk bos- en weilandengebied met beek tussen Enschede en Haaksbergen · niet meer in moderne registers terug te vinden', 'list 36 · no. 623'],
 'loc': '📍 In de corridor tussen Enschede en Haaksbergen (omgeving Boekelo–Usselo) · Klein vrij toegankelijk bos- en weilandengebied met beek, zonder eigen parkeerterrein of route',
 'desc': 'De naam <b>De Huttensmit en Koksbos</b> combineert twee oude terreinnamen — een hofstede of weide (‘Huttensmit’) en een bosperceel (‘Koksbos’) — die de gids als één wandelterrein opneemt in de strook tussen <b>Enschede en Haaksbergen</b>. Wie er wandelt vindt er een vrij toegankelijk geheel van bos, weilanden en houtwallen waar een beek doorheen stroomt. In moderne topografische registers en wandelgidsen komt de naam niet meer voor; waarschijnlijk gaat het om een verdwenen of samengevoegd terrein in het coulisselandschap tussen de stadsrand van Enschede en het beekdal van de Buurserbeek, waar kleine bossen en houtwallen nog altijd het beeld bepalen. Net als bij enkele andere namen uit deze oude bron registreert deze kaart daarom eerlijk wat de gids beschrijft — een vrij toegankelijk beek- en bosgebiedje tussen Enschede en Haaksbergen — zonder dat er vandaag een bord of bezoekersinformatie bij staat.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in het groen.',
 'why': ['De <b>twee oude terreinnamen</b> in één wandelgebiedje uit de gids.', 'Het <b>vrij toegankelijke bos en weiland</b> met een beek.', 'De ligging in de <b>groene corridor tussen Enschede en Haaksbergen</b>.', 'De eerlijke registratie van een naam die uit moderne registers is verdwenen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in bos en houtwallen.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs de paden.', '<span class="months">Mei–Jul</span> 🐄 <b>Vee</b> op de weilanden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het kleinschalige landschap.'],
 'wild': ['🐦 Zwartkop · Tuinfluiter · Buizerd', '🦌 Ree · Haas', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Es · Zwarte els'],
 'trail': ['Wandel in de <b>corridor tussen Enschede en Haaksbergen</b>.', 'Volg de paden langs <b>beek, weilanden en houtwallen</b>.', 'Combineer met <b>Het Lankheet of de Buurserbeek</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Naam uit de gids zonder moderne bewegwijzering — blijf op de paden · 🚶 Wegen en veldpaden'
}, {
 'tags': ['Overijssel · between Enschede and Haaksbergen', 'Name from the guide for a freely accessible area of wood and meadows with a brook between Enschede and Haaksbergen · no longer traceable in modern registers', 'list 36 · no. 623'],
 'loc': '📍 In the corridor between Enschede and Haaksbergen (Boekelo–Usselo area) · Small freely accessible area of wood and meadows with a brook, without its own car park or route',
 'desc': 'The name <b>De Huttensmit en Koksbos</b> combines two old terrain names — a farmstead or meadow (‘Huttensmit’) and a woodland plot (‘Koksbos’) — which the guide lists as one walking area in the strip between <b>Enschede and Haaksbergen</b>. Those who walk there find a freely accessible whole of wood, meadows and hedgerows through which a brook flows. The name no longer occurs in modern topographical registers and walking guides; it probably concerns a vanished or merged terrain in the small-scale landscape between the edge of Enschede and the Buurserbeek valley, where small woods and hedgerows still set the tone. As with several other names from this old source, this card therefore honestly registers what the guide describes — a freely accessible brook-and-woodland area between Enschede and Haaksbergen — even though no signboard or visitor information marks it today.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the green.',
 'why': ['The <b>two old terrain names</b> in one small walking area from the guide.', 'The <b>freely accessible wood and meadow</b> with a brook.', 'Its position in the <b>green corridor between Enschede and Haaksbergen</b>.', 'The honest registration of a name that has vanished from modern registers.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in wood and hedgerows.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along the paths.', '<span class="months">May–Jul</span> 🐄 <b>Cattle</b> on the meadows.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Blackcap · Garden warbler · Buzzard', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Ash · Black alder'],
 'trail': ['Walk in the <b>corridor between Enschede and Haaksbergen</b>.', 'Follow the paths along <b>brook, meadows and hedgerows</b>.', 'Combine with <b>Het Lankheet or the Buurserbeek</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Name from the guide without modern signposting — stay on the paths · 🚶 Roads and field paths'
}))

mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1904)
mk.check()
