# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1810, 'Rozendaalse Veld', {
 'tags': ['Gelderland · Rozendaal', 'Uitgestrekt heideveld in de noordelijke Veluwezoom · droge heide met vliegdennen en stuifzand', 'list 36 · no. 529'],
 'loc': '📍 Ten noorden en oosten van Rozendaal, binnen Nationaal Park Veluwezoom · Heide en stuifzand · start bij kasteel Rosendael of de parkeerplaats aan de Kluizenaarsweg',
 'desc': 'Het <b>Rozendaalse Veld</b> is het uitgestrekte heideveld van Nationaal Park Veluwezoom ten noorden van het dorp Rozendaal en een van de rustigste delen van het oudste nationale park van Nederland. Het is een droog, glooiend heidelandschap met struikhei en dophei — op de nattere plekken overgroeid door pijpenstrootje — met vliegdennen, jeneverbesstruwelen, opvallende hoogteverschillen en langs de randen open stuifzand, waar het veld overgaat in het Rozendaalse Zand. In de negentiende eeuw was dit de heide van het nabije kasteel Rosendael; oude zandwegen herinneren nog aan die tijd. Het veld is een belangrijke schakel in de wildtrekroute van de zuidelijke Veluwe: edelherten, wilde zwijnen en reeën steken het tussen Deelen en de stuwwal over. Een groot deel van het veld is hondenlosloopgebied, en de stilte en weidsheid staan in schril contrast met de drukte van de Posbank even verderop. De Trage Tocht Rozendaalse Veld (17 km, vanaf de Kluizenaarsweg) voert over het veld en langs de Rheder- en Worth-Rhederheide; ook etappes van het Maarten van Rossumpad en de route vanaf kasteel Rosendael (16,9 km) doorkruisen het. In 2025 voerden Natuurmonumenten en de gemeente actie om het veld vrij te houden van militaire oefeningen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heidebloei)<br>\n    <b>Beste tijd van de dag:</b> Zonsopgang of late middag — wild en laag licht.',
 'why': ['De <b>weidsheid en stilte</b> van een van de grootste heidevelden van de Veluwezoom.', 'De <b>glooiende droge heide</b> met vliegdennen, jeneverbes en stuifzand.', 'De kans op <b>edelhert, zwijn en ree</b> op de wildtrekroute.', 'De rust <b>zonder de drukte</b> van de Posbank.'],
 'phen': ['<span class="months">Apr–Mei</span> 🐦 <b>Boomleeuweriken</b> boven de heide.', '<span class="months">Jun–Jul</span> 🐍 <b>Adder en levendbarende hagedis</b> in het zand.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> kleurt het veld paars.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b> van edelherten in de schemering.'], 'wild': ['🦌 Edelhert · Wild zwijn · Ree', '🐦 Boomleeuwerik · Roodborsttapuit · Nachtzwaluw', '🐍 Adder · Levendbarende hagedis', '🦋 Heideblauwtje · Hooibeestje', '🌼 Struikhei · Dophei · Jeneverbes'],
 'trail': ['Start bij de <b>parkeerplaats aan de Kluizenaarsweg</b> in Rozendaal.', 'Loop de <b>Trage Tocht Rozendaalse Veld</b> (17 km) of een kort rondje over veld en zand.', 'Combineer met <b>kasteel Rosendael</b> of de Posbank.'],
 'foot': '🐕 Honden losloopgebied (grote delen) · 💶 Gratis · ⚠️ Wild rustgebied — blijf op de paden · 🚶 Heide- en zandpaden'
}, {
 'tags': ['Gelderland · Rozendaal', 'Vast heath field in the northern Veluwezoom · dry heath with self-sown pines and drift sand', 'list 36 · no. 529'],
 'loc': '📍 North and east of Rozendaal, within Veluwezoom National Park · Heath and drift sand · start at Rosendael Castle or the car park on the Kluizenaarsweg',
 'desc': 'The <b>Rozendaalse Veld</b> is the vast heath field of Veluwezoom National Park north of the village of Rozendaal and one of the quietest parts of the oldest national park of the Netherlands. It is a dry, rolling heath landscape with bell heather and cross-leaved heath — overgrown in the wetter spots by purple moor-grass — with self-sown pines, juniper scrub, striking differences in elevation and open drift sand along the edges, where the field merges into the Rozendaalse Zand. In the nineteenth century this was the heath of the nearby Rosendael Castle; old sand roads still recall that time. The field is an important link in the game migration route of the southern Veluwe: red deer, wild boar and roe deer cross it between Deelen and the ice-margin ridge. A large part of the field is a dog off-lead area, and its silence and wide-open character contrast sharply with the crowds at the Posbank just beyond. The Trage Tocht Rozendaalse Veld (17 km, from the Kluizenaarsweg) runs over the field and along the Rheder- and Worth-Rhederheide; stages of the Maarten van Rossumpad and the route from Rosendael Castle (16.9 km) also cross it. In 2025 Natuurmonumenten and the municipality campaigned to keep the field free of military exercises.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather bloom)<br>\n    <b>Best time of day:</b> Sunrise or late afternoon — game and low light.',
 'why': ['The <b>wide-open character and silence</b> of one of the largest heath fields of the Veluwezoom.', 'The <b>rolling dry heath</b> with self-sown pines, juniper and drift sand.', 'The chance of <b>red deer, boar and roe deer</b> on the game migration route.', 'The peace <b>without the crowds</b> of the Posbank.'],
 'phen': ['<span class="months">Apr–May</span> 🐦 <b>Woodlarks</b> above the heath.', '<span class="months">Jun–Jul</span> 🐍 <b>Adder and viviparous lizard</b> in the sand.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> colours the field purple.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b> of red deer at dusk.'], 'wild': ['🦌 Red deer · Wild boar · Roe deer', '🐦 Woodlark · Stonechat · Nightjar', '🐍 Adder · Viviparous lizard', '🦋 Silver-studded blue · Small heath', '🌼 Bell heather · Cross-leaved heath · Juniper'],
 'trail': ['Start at the <b>car park on the Kluizenaarsweg</b> in Rozendaal.', 'Walk the <b>Trage Tocht Rozendaalse Veld</b> (17 km) or a short circuit over field and sand.', 'Combine with <b>Rosendael Castle</b> or the Posbank.'],
 'foot': '🐕 Dog off-lead area (large parts) · 💶 Free · ⚠️ Game rest area — stay on the paths · 🚶 Heath and sand paths'
}))

C.append(mk.card(1811, 'Landgoed Rosendaal', {
 'tags': ['Gelderland · Rozendaal', 'Kasteel Rosendael met tuinsieraden · bedriegertjes, schelpengalerij en een van de oudste parken van Nederland', 'list 36 · no. 530'],
 'loc': '📍 Aan de noordrand van Rozendaal, boven Arnhem · Kasteel en landschapspark · parkeerplaats Beekhuizenseweg 3 (entree kasteel en park betaald)',
 'desc': '<b>Landgoed Rosendaal</b> is het kasteel- en parklandschap van <b>Kasteel Rosendael</b> (ook wel Rosendaal gespeld) aan de noordrand van Rozendaal, boven Arnhem. Het kasteel is een van de beroemdste van Gelderland: elke aanbouw stamt uit een andere eeuw, en de machtige middeleeuwse donjon is de grootste van Nederland. Het huis behoorde eeuwenlang toe aan het geslacht Van Heeckeren, dat er ook de omliggende landgoederen op de Veluwezoom opbouwde. Rond het kasteel ligt een <b>landschapspark in Engelse stijl</b> — een van de oudste parken van Nederland — met slingerende paden, vijvers, watervallen, een beekje met kettingbrug en eeuwenoude bomen. Beroemd zijn de <b>tuinsieraden</b>: de bedriegertjes, verborgen fonteinen die argeloze wandelaars nat spuiten, de achttiende-eeuwse <b>schelpengalerij</b> en de theekoepel. Vanaf de parkeerplaats aan de Beekhuizenseweg wandel je zo de Koningsberg op, een parkbos met een met rode paaltjes gemarkeerd rondje van ruim 3 kilometer. Het kasteel is te bezoeken met een rondleiding; het park en de oranjerie zijn in het seizoen geopend (entree). Het Rondje Rozendaal (17 km) en de routes naar de Posbank passeren het landgoed.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, apr–mei (park en rododendrons), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in park en parkbos.',
 'why': ['Het <b>kasteel met de grootste donjon van Nederland</b>.', 'De <b>bedriegertjes en de schelpengalerij</b>: beroemde tuinsieraden.', 'Het <b>landschapspark</b>, een van de oudste parken van Nederland.', 'Het <b>parkbos De Koningsberg</b> met rode-paaltjesroute.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Rododendrons en voorjaarsbloei</b> in het park.', '<span class="months">Mei–Aug</span> 💦 <b>Bedriegertjes</b> spuiten wandelaars nat.', '<span class="months">Jun–Aug</span> 🐦 <b>Parkvogels</b> bij vijvers en beek.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> van het oude park.'], 'wild': ['🐦 Bosuil · Boomklever · Grote bonte specht', '🦌 Ree · Eekhoorn · Das', '🦆 Wilde eend · Waterhoen', '🌼 Bosanemoon · Daslook', '🌳 Beuk · Zomereik · Kastanje (oud)'],
 'trail': ['Parkeer bij <b>Kasteel Rosendael</b> (Beekhuizenseweg 3, Rozendaal).', 'Loop het <b>parkbos De Koningsberg</b> via de rode paaltjes (ruim 3 km).', 'Bezoek het kasteel met <b>rondleiding</b> en het park met tuinsieraden.'],
 'foot': '🐕 Honden aangelijnd (park) · 💶 Entree kasteel en park · ⚠️ Park alleen geopend in het seizoen · 🚶 Park-, laan- en bospaden'
}, {
 'tags': ['Gelderland · Rozendaal', 'Rosendael Castle with garden ornaments · trick fountains, shell gallery and one of the oldest parks of the Netherlands', 'list 36 · no. 530'],
 'loc': '📍 On the northern edge of Rozendaal, above Arnhem · Castle and landscape park · car park Beekhuizenseweg 3 (admission to castle and park charged)',
 'desc': '<b>Landgoed Rosendaal</b> is the castle and park landscape of <b>Rosendael Castle</b> (also spelled Rosendaal) on the northern edge of Rozendaal, above Arnhem. The castle is one of the most famous in Gelderland: every extension dates from a different century, and its mighty medieval keep is the largest in the Netherlands. For centuries the house belonged to the Van Heeckeren family, who also built up the surrounding estates on the Veluwezoom. Around the castle lies a <b>landscape park in the English style</b> — one of the oldest parks of the Netherlands — with winding paths, ponds, waterfalls, a brook with a chain bridge and centuries-old trees. Famous are the <b>garden ornaments</b>: the trick fountains (bedriegertjes), hidden jets that spray unsuspecting walkers, the eighteenth-century <b>shell gallery</b> and the tea pavilion. From the car park on the Beekhuizenseweg you walk straight onto the Koningsberg, a park wood with a circuit of just over 3 kilometres marked with red posts. The castle can be visited with a guided tour; the park and the orangery are open in season (admission). The Rondje Rozendaal (17 km) and the routes to the Posbank pass the estate.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Apr–May (park and rhododendrons), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in park and park wood.',
 'why': ['The <b>castle with the largest keep of the Netherlands</b>.', 'The <b>trick fountains and the shell gallery</b>: famous garden ornaments.', 'The <b>landscape park</b>, one of the oldest parks of the Netherlands.', 'The <b>Koningsberg park wood</b> with red-posts route.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Rhododendrons and spring bloom</b> in the park.', '<span class="months">May–Aug</span> 💦 <b>Trick fountains</b> spray walkers.', '<span class="months">Jun–Aug</span> 🐦 <b>Park birds</b> at ponds and brook.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> of the old park.'], 'wild': ['🐦 Tawny owl · Nuthatch · Great spotted woodpecker', '🦌 Roe deer · Red squirrel · Badger', '🦆 Mallard · Moorhen', '🌼 Wood anemone · Wild garlic', '🌳 Beech · Pedunculate oak · Chestnut (old)'],
 'trail': ['Park at <b>Rosendael Castle</b> (Beekhuizenseweg 3, Rozendaal).', 'Walk the <b>Koningsberg park wood</b> via the red posts (over 3 km).', 'Visit the castle on a <b>guided tour</b> and the park with garden ornaments.'],
 'foot': '🐕 Dogs on lead (park) · 💶 Admission to castle and park · ⚠️ Park open only in season · 🚶 Park, avenue and forest paths'
}))

C.append(mk.card(1812, 'Rozendaal', {
 'tags': ['Gelderland · Rozendaal', 'Dorp en kleinste gemeente van Nederland · aan de rand van de Veluwezoom met kasteel Rosendael', 'list 36 · no. 531'],
 'loc': '📍 Ten noorden van Arnhem, tussen de A12 en de Veluwezoom · Dorp en gemeente · start bij de kerk of kasteel Rosendael',
 'desc': '<b>Rozendaal</b> is met rond de 1.600 inwoners de kleinste gemeente van Nederland en ligt als een landelijk dorp tussen Arnhem en de bossen van de Veluwezoom. Het dorp ontstond rond een middeleeuws kasteel — de voorloper van het huidige Kasteel Rosendael — dat eeuwenlang het centrum van het dorpsleven was; de dorpskerk en de oude boerderijen rond de brinkachtige kom getuigen van die geschiedenis. Rond het dorp liggen de landgoederen en bossen van de Veluwezoom: het Rozendaalse Veld en het Rozendaalse Zand in het noorden, de Beekhuizense bossen met de Beekhuizense Beek en haar watervalletjes in het westen en de heide van de Veluwezoom richting de Posbank en het Herikhuizerveld. Door de ligging aan de rand van het nationaal park is Rozendaal een geliefd startpunt voor wandelaars en fietsers: het Rondje Rozendaal (17 km) doet kasteel, Posbank en Herikhuizerveld aan, en de fietsroutes van de Veluwezoom (onder meer naar de Posbank) starten er. Het dorp zelf heeft horeca en is via de wegen vanaf Arnhem en Velp goed bereikbaar.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, aug–sep (heide)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht over dorp en heide.',
 'why': ['Het <b>kleinste dorp-gemeente van Nederland</b> aan de rand van de Veluwezoom.', 'De ligging tussen <b>kasteel, heide en nationaal park</b>.', 'Het <b>Rondje Rozendaal</b> (17 km) langs kasteel en Posbank.', 'De <b>Beekhuizense beek</b> met watervalletjes in de nabije bossen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsbloei</b> in tuinen en park.', '<span class="months">Jun–Aug</span> 🐦 <b>Vogels</b> rond de Beekhuizense beek.', '<span class="months">Aug–Sep</span> 🟣 <b>Heidebloei</b> op het Rozendaalse Veld.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> in de omringende bossen.'], 'wild': ['🦌 Edelhert · Ree · Wild zwijn', '🐦 Zwarte specht · Boomklever · Buizerd', '🐿️ Eekhoorn · Das', '🦎 Zandhagedis · Levendbarende hagedis', '🌼 Struikhei · Dophei · Blauwe bosbes'],
 'trail': ['Start in <b>Rozendaal</b> bij de kerk of kasteel Rosendael.', 'Loop het <b>Rondje Rozendaal</b> (17 km) via de Posbank en het Herikhuizerveld.', 'Volg de <b>Beekhuizense beek</b> de bossen in richting de Veluwezoom.'],
 'foot': '🐕 Honden aangelijnd (losloopgebieden aangegeven) · 💶 Gratis · ⚠️ Rustige dorpswegen — let op fietsers · 🚶 Dorps-, bos- en heidepaden'
}, {
 'tags': ['Gelderland · Rozendaal', 'Village and smallest municipality of the Netherlands · on the edge of the Veluwezoom with Rosendael Castle', 'list 36 · no. 531'],
 'loc': '📍 North of Arnhem, between the A12 and the Veluwezoom · Village and municipality · start at the church or Rosendael Castle',
 'desc': '<b>Rozendaal</b>, with around 1,600 inhabitants, is the smallest municipality of the Netherlands and lies as a rural village between Arnhem and the forests of the Veluwezoom. The village grew around a medieval castle — the predecessor of the present Rosendael Castle — which for centuries was the centre of village life; the village church and the old farmhouses around the green recall that history. Around the village lie the estates and forests of the Veluwezoom: the Rozendaalse Veld and the Rozendaalse Zand to the north, the Beekhuizense woods with the Beekhuizense Beek and its waterfalls to the west, and the heath of the Veluwezoom towards the Posbank and the Herikhuizerveld. Thanks to its position on the edge of the national park, Rozendaal is a popular starting point for walkers and cyclists: the Rondje Rozendaal (17 km) takes in castle, Posbank and Herikhuizerveld, and the cycle routes of the Veluwezoom (including to the Posbank) start here. The village itself has catering facilities and is easily reached by road from Arnhem and Velp.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Aug–Sep (heather)<br>\n    <b>Best time of day:</b> Morning — light over village and heath.',
 'why': ['The <b>smallest village-municipality of the Netherlands</b> on the edge of the Veluwezoom.', 'Its position between <b>castle, heath and national park</b>.', 'The <b>Rondje Rozendaal</b> (17 km) past castle and Posbank.', 'The <b>Beekhuizense Beek</b> with waterfalls in the nearby woods.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring bloom</b> in gardens and park.', '<span class="months">Jun–Aug</span> 🐦 <b>Birds</b> around the Beekhuizense Beek.', '<span class="months">Aug–Sep</span> 🟣 <b>Heather bloom</b> on the Rozendaalse Veld.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> in the surrounding woods.'], 'wild': ['🦌 Red deer · Roe deer · Wild boar', '🐦 Black woodpecker · Nuthatch · Buzzard', '🐿️ Red squirrel · Badger', '🦎 Sand lizard · Viviparous lizard', '🌼 Bell heather · Cross-leaved heath · Bilberry'],
 'trail': ['Start in <b>Rozendaal</b> at the church or Rosendael Castle.', 'Walk the <b>Rondje Rozendaal</b> (17 km) via the Posbank and the Herikhuizerveld.', 'Follow the <b>Beekhuizense Beek</b> into the woods towards the Veluwezoom.'],
 'foot': '🐕 Dogs on lead (off-lead areas indicated) · 💶 Free · ⚠️ Quiet village roads — mind cyclists · 🚶 Village, forest and heath paths'
}))

C.append(mk.card(1813, 'Rosendaal', {
 'tags': ['Gelderland · Rozendaal', 'Oud bos rond kasteel Rosendael · ook Rozendaalse Bos genoemd · wild en statige lanen', 'list 36 · no. 532'],
 'loc': '📍 Direct rond kasteel Rosendael in Rozendaal · Oud bos en landgoedbos · start bij de parkeerplaats het Wageningsehek of Beekhuizenseweg',
 'desc': '<b>Rosendaal</b> — een van de vele schrijfwijzen van het goed dat ook als Rosendael en Rozendaal op de kaart staat — is het oude bos rond kasteel Rosendael, tegenwoordig ook bekend als het <b>Rozendaalse Bos</b>. Het is een statig, oud parkbos op de rand van de stuwwal, waarin vooral eiken en beuken domineren, afgewisseld met naaldpercelen en oude lanen; de hoge bomen en de hoogteverschillen maken het een van de mooiste boswandelingen van de Veluwezoom. Vroeger maakte het bos deel uit van het landgoed van het kasteel, dat er zijn hout haalde en er jaagde; nog altijd trekken er edelherten, damherten, reeën en wilde zwijnen rond. Het bos is vrij toegankelijk en wordt doorkruist door een netwerk van paden: een kort rondje van circa 2,5 kilometer en een grotere lus van 4,3 kilometer starten bij de parkeerplaats het Wageningsehek, en vanaf de parkeerplaats van het kasteel (Beekhuizenseweg 3) wandel je via de Koningsberg het bos in. In het bos liggen enkele grafheuvels; de routes sluiten aan op het Rozendaalse Veld en de Beekhuizense beek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, okt (herfst), mrt–apr (voorjaar)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — wild en stilte in het oude bos.',
 'why': ['Het <b>oude parkbos</b> met hoge eiken en beuken rond het kasteel.', 'De kans op <b>edelhert, damhert en wild zwijn</b> vlak bij Rozendaal.', 'De <b>korte, goed beloopbare routes</b> vanaf het Wageningsehek.', 'De aansluiting op <b>Rozendaalse Veld en Beekhuizense beek</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Bosanemoon</b> onder de oude bomen.', '<span class="months">Apr–Mei</span> 🐦 <b>Zangvogels</b> in de kronen.', '<span class="months">Sep–Okt</span> 🦌 <b>Bronst</b>: burlen in de schemering.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van beuk en eik.'], 'wild': ['🦌 Edelhert · Damhert · Ree · Wild zwijn', '🐦 Zwarte specht · Boomklever · Buizerd', '🐿️ Eekhoorn · Das', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Beuk · Grove den'],
 'trail': ['Parkeer bij <b>het Wageningsehek</b> en loop het rondje door het Rozendaalse Bos.', 'Wandel vanaf <b>kasteel Rosendael</b> via de Koningsberg het bos in.', 'Verbind met het <b>Rozendaalse Veld</b> of de Beekhuizense beek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden · wild · 🚶 Bos- en zandpaden'
}, {
 'tags': ['Gelderland · Rozendaal', 'Ancient forest around Rosendael Castle · also called Rozendaalse Bos · game and stately avenues', 'list 36 · no. 532'],
 'loc': '📍 Directly around Rosendael Castle in Rozendaal · Ancient forest and estate wood · start at the Wageningsehek car park or Beekhuizenseweg',
 'desc': '<b>Rosendaal</b> — one of the many spellings of the estate also shown on maps as Rosendael and Rozendaal — is the old forest around Rosendael Castle, today also known as the <b>Rozendaalse Bos</b>. It is a stately, old park forest on the edge of the ice-margin ridge, dominated above all by oaks and beeches, alternating with conifer stands and old avenues; the tall trees and the differences in elevation make it one of the finest forest walks of the Veluwezoom. Formerly the forest formed part of the castle estate, which drew its timber and hunted there; red deer, fallow deer, roe deer and wild boar still roam here. The forest is freely accessible and crossed by a network of paths: a short circuit of about 2.5 kilometres and a larger loop of 4.3 kilometres start at the Wageningsehek car park, and from the castle car park (Beekhuizenseweg 3) you enter the forest via the Koningsberg. A few burial mounds lie in the forest; the routes link up with the Rozendaalse Veld and the Beekhuizense Beek.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, Oct (autumn), Mar–Apr (spring)<br>\n    <b>Best time of day:</b> Morning — game and silence in the old forest.',
 'why': ['The <b>old park forest</b> with tall oaks and beeches around the castle.', 'The chance of <b>red deer, fallow deer and wild boar</b> close to Rozendaal.', 'The <b>short, easy routes</b> from the Wageningsehek.', 'The link to the <b>Rozendaalse Veld and the Beekhuizense Beek</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Wood anemone</b> under the old trees.', '<span class="months">Apr–May</span> 🐦 <b>Songbirds</b> in the crowns.', '<span class="months">Sep–Oct</span> 🦌 <b>Rutting</b>: belling at dusk.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of beech and oak.'], 'wild': ['🦌 Red deer · Fallow deer · Roe deer · Wild boar', '🐦 Black woodpecker · Nuthatch · Buzzard', '🐿️ Red squirrel · Badger', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Beech · Scots pine'],
 'trail': ['Park at <b>het Wageningsehek</b> and walk the circuit through the Rozendaalse Bos.', 'Walk in from <b>Rosendael Castle</b> via the Koningsberg.', 'Link with the <b>Rozendaalse Veld</b> or the Beekhuizense Beek.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths · game · 🚶 Forest and sand paths'
}))

C.append(mk.card(1814, 'Sonsbeek, Zijpendaal en Gulden Bodem', {
 'tags': ['Gelderland · Arnhem (centrum-noord)', 'Drie aaneengesloten stadsparken · de Sint-Jansbeek, de Grote Waterval en de Belvédère', 'list 36 · no. 533'],
 'loc': '📍 Ten noorden van het Arnhemse centrum, tussen de Apeldoornseweg en de Schelmseweg · Stadsparken · start bij bezoekerscentrum Molenplaats Sonsbeek',
 'desc': '<b>Sonsbeek</b>, <b>Zijpendaal</b> en <b>Gulden Bodem</b> vormen samen de groene vinger die vanuit de Veluwe bijna het centrum van Arnhem raakt. Park Sonsbeek is het beroemdst: in 1821 kocht baron Van Heeckeren van Enghuizen het landgoed en liet het in Engelse landschapsstijl omvormen, met vijvers, slingerpaden, de <b>Grote Waterval</b> (1826, met zwerfkeien uit het Kootwijkerzand en een grot) en de stenen <b>Belvédère</b>-uitkijktoren. In 1899 kocht de gemeente het park en stelde het open; sindsdien is het het stadspark van Arnhem. Alles draait om de <b>Sint-Jansbeek</b>: 3,5 kilometer lang met 35 meter verval, waarlangs ooit tien watermolens stonden — de beek legde de zandbank neer waarop de stad ontstond. In het park staan nog de Witte Watermolen (sinds de vijftiende eeuw, maalt nog steeds) en het Nederlands Watermuseum in een vijftiende-eeuwse bagijnemolen; bezoekerscentrum Molenplaats Sonsbeek is gevestigd in een oude molenschuur. Noordelijker liggen Park Zijpendaal met het achttiende-eeuwse Huis Zypendaal en het bosrijke Gulden Bodem. IJstijdenwandelingen, waterwandelingen en de NS-wandeling Arnhem–Wolfheze voeren door de drie parken; grote delen zijn hondenlosloopgebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–mei (voorjaarsbloei), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig voor de drukte van de stad.',
 'why': ['De <b>Grote Waterval</b> uit 1826 en de Belvédère-uitkijktoren.', 'De <b>Sint-Jansbeek</b>: 35 meter verval, tien molens, bakermat van Arnhem.', 'De <b>Witte Watermolen</b> en het Nederlands Watermuseum.', 'De aaneenschakeling van <b>Sonsbeek, Zijpendaal en Gulden Bodem</b>.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌼 <b>Sneeuwklokjes en narcissen</b> langs de beek.', '<span class="months">Apr–Mei</span> 🌸 <b>Rododendrons en voorjaarsbloei</b>.', '<span class="months">Mei–Aug</span> 🦆 <b>Watervogels</b> bij vijvers en waterval.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> boven de stad.'], 'wild': ['🐦 IJsvogel · Grote gele kwikstaart · Bosuil', '🦆 Wilde eend · Meerkoet · Fuut', '🐿️ Eekhoorn · Egel', '🦇 Gewone dwergvleermuis · Watervleermuis', '🌳 Beuk · Zomereik · Plataan · Linde'],
 'trail': ['Start bij <b>bezoekerscentrum Molenplaats Sonsbeek</b> (Zijpendaalseweg 26A).', 'Volg de <b>Waterwandeling</b> (5 km) langs beek, molens en waterval.', 'Wandel door naar <b>Zijpendaal en Gulden Bodem</b> of de Waterberg.'],
 'foot': '🐕 Honden losloopgebied (grote delen) · 💶 Gratis (musea betaald) · ⚠️ Blijf op de paden · 🚶 Park-, laan- en bospaden'
}, {
 'tags': ['Gelderland · Arnhem (centre-north)', 'Three connected city parks · the Sint-Jansbeek, the Great Waterfall and the Belvédère', 'list 36 · no. 533'],
 'loc': '📍 North of the Arnhem city centre, between the Apeldoornseweg and the Schelmseweg · City parks · start at visitor centre Molenplaats Sonsbeek',
 'desc': '<b>Sonsbeek</b>, <b>Zijpendaal</b> and <b>Gulden Bodem</b> together form the green finger that reaches from the Veluwe almost into the centre of Arnhem. Sonsbeek park is the most famous: in 1821 Baron Van Heeckeren van Enghuizen bought the estate and had it reshaped in the English landscape style, with ponds, winding paths, the <b>Great Waterfall</b> (1826, with boulders from the Kootwijkerzand and a grotto) and the stone <b>Belvédère</b> lookout tower. In 1899 the municipality bought the park and opened it; since then it has been the city park of Arnhem. Everything revolves around the <b>Sint-Jansbeek</b>: 3.5 kilometres long with a fall of 35 metres, along which ten water mills once stood — the brook laid down the sandbank on which the city arose. In the park still stand the Witte Watermolen (since the fifteenth century, still grinding) and the Netherlands Water Museum in a fifteenth-century beguine mill; visitor centre Molenplaats Sonsbeek is housed in an old mill barn. Further north lie Zijpendaal park with the eighteenth-century Huis Zypendaal and the wooded Gulden Bodem. Ice-age walks, water walks and the NS walk Arnhem–Wolfheze lead through the three parks; large parts are dog off-lead areas.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–May (spring bloom), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet before the bustle of the city.',
 'why': ['The <b>Great Waterfall</b> from 1826 and the Belvédère lookout tower.', 'The <b>Sint-Jansbeek</b>: 35 metres of fall, ten mills, cradle of Arnhem.', 'The <b>Witte Watermolen</b> and the Netherlands Water Museum.', 'The chain of <b>Sonsbeek, Zijpendaal and Gulden Bodem</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌼 <b>Snowdrops and daffodils</b> along the brook.', '<span class="months">Apr–May</span> 🌸 <b>Rhododendrons and spring bloom</b>.', '<span class="months">May–Aug</span> 🦆 <b>Water birds</b> at ponds and waterfall.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> above the city.'], 'wild': ['🐦 Kingfisher · Grey wagtail · Tawny owl', '🦆 Mallard · Coot · Great crested grebe', '🐿️ Red squirrel · Hedgehog', '🦇 Common pipistrelle · Daubenton\u2019s bat', '🌳 Beech · Pedunculate oak · Plane · Lime'],
 'trail': ['Start at <b>visitor centre Molenplaats Sonsbeek</b> (Zijpendaalseweg 26A).', 'Follow the <b>Water Walk</b> (5 km) along brook, mills and waterfall.', 'Walk on to <b>Zijpendaal and Gulden Bodem</b> or the Waterberg.'],
 'foot': '🐕 Dog off-lead area (large parts) · 💶 Free (museums charged) · ⚠️ Stay on the paths · 🚶 Park, avenue and forest paths'
}))

mk.insert(C, '1809')
mk.progress(1814)
mk.check()
