# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1850, 'Empese en Tondense Heide', {
 'tags': ['Gelderland · Empe–Hall (Voorst en Brummen)', 'Bloemrijk grasland- en venlandschap tussen Empe, Tonden en Hall · deel van Natura 2000 Landgoederen Brummen', 'list 36 · no. 569'],
 'loc': '📍 Tussen Empe, Tonden en Hall, aan de Hallsedijk · Bloemrijk grasland- en venlandschap van Natuurmonumenten · parkeerplaats Hallsedijk bij de ingang',
 'desc': 'De <b>Empese en Tondense Heide</b> is een natuurreservaat van <b>Natuurmonumenten</b> van circa <b>260 hectare</b> in de gemeente Brummen, tussen de dorpen Empe, Tonden en Hall. In tegenstelling tot wat de naam doet vermoeden, is het geen heide maar een <b>weids, waterrijk land van bijzonder bloemrijke graslanden</b>, met vennen en open water. Op de overgang van de Veluwe naar het IJsseldal welt kalkrijk grondwater op — de <b>kwel</b> — en daardoor groeien hier zeldzame planten als <b>Spaanse ruiter, gevlekte orchis en blauwe knoop</b>, samen met restanten van droge en natte heide, blauwgrasland en nat schraalland. Ooit graasden de gezamenlijke schaapskuddes van Empe en Tonden er; midden door het gebied loopt de hoger gelegen <b>Mestweg</b>, waarlangs de boeren mest en heideplaggen vervoerden. Het reservaat is deel van het <b>Natura 2000-gebied Landgoederen Brummen</b>, mede aangewezen voor de kamsalamander. In het natte grasland broeden dodaars, sprinkhaanzanger, kievit, grutto en wulp; in de winter zit er geregeld een klapekster op de uitkijk. Over vlonders en paden lopen een <b>rode route van 5 kilometer</b> en een <b>gele route van 7,5 kilometer</b>; delen zijn van 2 maart tot 15 juli gesloten vanwege het broedseizoen. Trek laarzen aan — ook buiten het vlonderpad is het er nat.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b>, mei–jun (orchideeën en broedvogels), jul–okt (bloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — vogels en dauw over de graslanden.',
 'why': ['Het <b>bloemrijke grasland- en venlandschap</b> met Spaanse ruiter en gevlekte orchis.', 'De <b>vogels</b>: van dodaars en sprinkhaanzanger tot klapekster in de winter.', 'Het <b>Natura 2000-gebied Landgoederen Brummen</b> met kwel- en bronwater.', 'Het <b>vlonderpad en de routes</b> van 5 en 7,5 kilometer.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Gevlekte orchis en Spaanse ruiter</b> in bloei.', '<span class="months">Apr–Jun</span> 🐦 <b>Broedvogels</b>: grutto, kievit en sprinkhaanzanger.', '<span class="months">Jul–Okt</span> 🟣 <b>Blauwe knoop</b> kleurt de hooilanden.', '<span class="months">Okt–Mrt</span> 🦅 <b>Klapekster</b> en wintergasten in het gebied.'],
 'wild': ['🐦 Grutto · Kievit · Wulp · Sprinkhaanzanger · Dodaars', '🦅 Klapekster (winter) · Bruine kiekendief', '🦎 Kamsalamander · Ree · Haas · Das', '🌸 Spaanse ruiter · Gevlekte orchis · Blauwe knoop', '🦋 Zilveren maan · Hooibeestje'],
 'trail': ['Parkeer bij de <b>Hallsedijk</b> en start de rode route van 5 km of de gele van 7,5 km.', 'Check van <b>2 mrt tot 15 jul</b> welke delen gesloten zijn (broedseizoen).', 'Combineer met <b>Leusveld en Voorstonden</b> via de stationswandeling Empe–Brummen.'],
 'foot': '🐕 Honden aangelijnd, op de paden · 💶 Gratis · ⚠️ Nat terrein — laarzen aan; delen gesloten in het broedseizoen · 🚶 Graslanden, zandweg en vlonderpad'
}, {
 'tags': ['Gelderland · Empe–Hall (Voorst en Brummen)', 'Flower-rich grassland and pool landscape between Empe, Tonden and Hall · part of Natura 2000 Landgoederen Brummen', 'list 36 · no. 569'],
 'loc': '📍 Between Empe, Tonden and Hall, on the Hallsedijk · Flower-rich grassland and pool landscape of Natuurmonumenten · Hallsedijk car park at the entrance',
 'desc': 'The <b>Empese en Tondense Heide</b> is a nature reserve of <b>Natuurmonumenten</b> of about <b>260 hectares</b> in the municipality of Brummen, between the villages of Empe, Tonden and Hall. Contrary to what the name suggests, it is not heathland but a <b>wide, water-rich land of exceptionally flower-rich grasslands</b>, with pools and open water. On the transition from the Veluwe to the IJssel valley, calcareous groundwater wells up — the <b>seepage</b> — and thanks to that, rare plants such as <b>meadow thistle, spotted orchid and devil\u2019s-bit scabious</b> grow here, together with remnants of dry and wet heath, purple-moor-grass meadow and poor fen. Once the joint sheep flocks of Empe and Tonden grazed here; through the middle of the area runs the higher-lying <b>Mestweg</b>, along which farmers carried manure and heath sods. The reserve is part of the <b>Natura 2000 site Landgoederen Brummen</b>, designated partly for the great crested newt. Little grebe, grasshopper warbler, lapwing, black-tailed godwit and curlew breed in the wet grassland; in winter a great grey shrike regularly keeps watch. Over boardwalks and paths run a <b>red route of 5 kilometres</b> and a <b>yellow route of 7.5 kilometres</b>; parts are closed from 2 March to 15 July because of the breeding season. Wear boots — even outside the boardwalk it is wet.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, May–Jun (orchids and breeding birds), Jul–Oct (bloom)<br>\n    <b>Best time of day:</b> Morning — birds and dew over the grasslands.',
 'why': ['The <b>flower-rich grassland and pool landscape</b> with meadow thistle and spotted orchid.', 'The <b>birds</b>: from little grebe and grasshopper warbler to great grey shrike in winter.', 'The <b>Natura 2000 site Landgoederen Brummen</b> with seepage and spring water.', 'The <b>boardwalk and routes</b> of 5 and 7.5 kilometres.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Spotted orchid and meadow thistle</b> in bloom.', '<span class="months">Apr–Jun</span> 🐦 <b>Breeding birds</b>: godwit, lapwing and grasshopper warbler.', '<span class="months">Jul–Oct</span> 🟣 <b>Devil\u2019s-bit scabious</b> colours the hay meadows.', '<span class="months">Oct–Mar</span> 🦅 <b>Great grey shrike</b> and winter visitors in the area.'],
 'wild': ['🐦 Black-tailed godwit · Lapwing · Curlew · Grasshopper warbler · Little grebe', '🦅 Great grey shrike (winter) · Marsh harrier', '🦎 Great crested newt · Roe deer · Hare · Badger', '🌸 Meadow thistle · Spotted orchid · Devil\u2019s-bit scabious', '🦋 Silver-washed fritillary · Small heath'],
 'trail': ['Park at the <b>Hallsedijk</b> and start the red 5-km route or the yellow 7.5-km route.', 'Check from <b>2 Mar to 15 Jul</b> which parts are closed (breeding season).', 'Combine with <b>Leusveld and Voorstonden</b> via the Empe–Brummen station walk.'],
 'foot': '🐕 Dogs on lead, on the paths · 💶 Free · ⚠️ Wet terrain — wear boots; parts closed in the breeding season · 🚶 Grasslands, sand road and boardwalk'
}, n2k='Natura 2000-gebied Landgoederen Brummen (nr. 58) — deelgebied met kwel- en bronwater op de overgang van Veluwe naar IJsseldal, aangewezen voor blauwgraslanden, vochtige heiden, zwak gebufferde vennen en de kamsalamander', n2k_en='Natura 2000 site Landgoederen Brummen (no. 58) — sub-area with seepage and spring water on the transition from the Veluwe to the IJssel valley, designated for purple-moor-grass meadows, wet heaths, weakly buffered pools and the great crested newt'))

C.append(mk.card(1851, 'De Overmars', {
 'tags': ['Gelderland · Empe (Voorst)', 'Open weidegebied in de binnenbocht van de Oude IJssel bij Empe · oude cultuurgronden met vliedberg', 'list 36 · no. 570'],
 'loc': '📍 Ten westen van Empe, tussen de oude IJsselmeander en het dorp · Open grasland- en weidegebied · wandelen vanuit Empe of langs de oude meander',
 'desc': '<b>De Overmars</b> is het open grasland- en weidegebied in de <b>binnenbocht van de Oude IJssel</b>, even ten westen van het dorp Empe in de gemeente Voorst. Al op een kaartboek uit <b>1573</b> worden de landerijen hier aangeduid als de \u2018Overmarsch\u2019 — de mars of het weideveld aan de overkant, gelegen langs de oude rivierbocht die later werd afgesneden. Tegenwoordig is de Overmars een weids, open landschap op de rand van het IJsseldal: weilanden en hooilanden, doorsneden door sloten, met hier en daar een oude boom of houtwal en vrij zicht over de vlakke kom. Op de topografische kaart staat in dit gebied een <b>vliedberg</b> aangegeven — een kunstmatige vluchtheuvel uit de middeleeuwen waar mensen en vee bij hoogwater of onrust hun toevlucht zochten. De Overmars grenst aan de ondoordringbare, verlandende Oude IJssel en aan de graslanden rond Huize Empe en het Sterrebos. Wie hier wandelt — bijvoorbeeld vanuit de kern van Empe of over de oude wegen langs de meander — komt in een rustig weidegebied met weidevogels in het voorjaar en ganzen in de winter, met op de achtergrond de kerktorens van Voorst en de IJsselvallei.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–jun (weidevogels), okt–mrt (watervogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond — stil en weids.',
 'why': ['Het <b>open weidegebied in de binnenbocht</b> van de Oude IJssel.', 'De <b>cultuurhistorie</b>: de \u2018Overmarsch\u2019 op kaarten uit 1573 en de vliedberg.', 'De <b>rust en ruimte</b> vlak bij Empe en de IJssel.', 'De <b>weide- en watervogels</b> in het seizoen.'],
 'phen': ['<span class="months">Mrt–Jun</span> 🐦 <b>Weidevogels</b> boven de graslanden.', '<span class="months">Okt–Mrt</span> 🦆 <b>Ganzen en eenden</b> op de natte weilanden.', '<span class="months">Apr–Mei</span> 🌼 <b>Bloeirijke slootkanten</b>.', '<span class="months">Heel jaar</span> 🏰 <b>Vliedberg</b> in het landschap te zoeken.'],
 'wild': ['🐦 Kievit · Grutto · Tureluur (voorjaar)', '🦆 Kolgans · Wilde eend (winter)', '🦌 Ree · Haas', '🦊 Vos (oevers en bosjes)', '🌳 Zomereik · Wilg · Meidoorn'],
 'trail': ['Wandel vanuit <b>Empe</b> de Overmars in via de oude wegen langs de meander.', 'Combineer met de route langs de <b>Oude IJssel en Huize Empe</b>.', 'Zoek de <b>vliedberg</b> op de topografische kaart en in het veld.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Open weidegebied op boerenland — blijf op wegen en paden · 🚶 Wegen, zandpaden en kades'
}, {
 'tags': ['Gelderland · Empe (Voorst)', 'Open meadow area in the inner bend of the Oude IJssel near Empe · old cultivated lands with a refuge mound', 'list 36 · no. 570'],
 'loc': '📍 West of Empe, between the old IJssel meander and the village · Open grassland and meadow area · walk from Empe or along the old meander',
 'desc': '<b>De Overmars</b> is the open grassland and meadow area in the <b>inner bend of the Oude IJssel</b>, just west of the village of Empe in the municipality of Voorst. Already in a map book from <b>1573</b> the lands here are designated the \u2018Overmarsch\u2019 — the marsh or meadow field on the other side, lying along the old river bend that was later cut off. Today the Overmars is a wide, open landscape on the edge of the IJssel valley: meadows and hayfields, crossed by ditches, with an occasional old tree or hedgerow and open views over the flat basin. On the topographical map a <b>refuge mound (vliedberg)</b> is marked in this area — an artificial refuge hill from the Middle Ages where people and livestock sought shelter during high water or unrest. The Overmars borders the impenetrable, silting-up Oude IJssel and the grasslands around Huize Empe and the Sterrebos. Those who walk here — for example from the centre of Empe or over the old roads along the meander — come to a quiet meadow area with breeding meadow birds in spring and geese in winter, with the church towers of Voorst and the IJssel valley on the horizon.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–Jun (meadow birds), Oct–Mar (waterbirds)<br>\n    <b>Best time of day:</b> Morning or evening — quiet and wide.',
 'why': ['The <b>open meadow area in the inner bend</b> of the Oude IJssel.', 'The <b>cultural history</b>: the \u2018Overmarsch\u2019 on maps from 1573 and the refuge mound.', 'The <b>peace and space</b> close to Empe and the IJssel.', 'The <b>meadow and water birds</b> in season.'],
 'phen': ['<span class="months">Mar–Jun</span> 🐦 <b>Meadow birds</b> above the grasslands.', '<span class="months">Oct–Mar</span> 🦆 <b>Geese and ducks</b> on the wet meadows.', '<span class="months">Apr–May</span> 🌼 <b>Flower-rich ditch banks</b>.', '<span class="months">All year</span> 🏰 <b>Refuge mound</b> to look for in the landscape.'],
 'wild': ['🐦 Lapwing · Black-tailed godwit · Redshank (spring)', '🦆 White-fronted goose · Mallard (winter)', '🦌 Roe deer · Hare', '🦊 Fox (banks and copses)', '🌳 Pedunculate oak · Willow · Hawthorn'],
 'trail': ['Walk from <b>Empe</b> into the Overmars via the old roads along the meander.', 'Combine with the route along the <b>Oude IJssel and Huize Empe</b>.', 'Look for the <b>refuge mound</b> on the map and in the field.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Open meadow area on farmland — keep to roads and paths · 🚶 Roads, sand paths and banks'
}))

C.append(mk.card(1852, 'Oude IJssel te Empe', {
 'tags': ['Gelderland · Empe (Voorst)', 'Afgesneden rivierarm van de IJssel tussen Empe en Voorstonden · verland tot een bijna ondoordringbare natte natuurstrook', 'list 36 · no. 571'],
 'loc': '📍 Ten zuiden en westen van Empe, tussen het dorp en Voorstonden · Oude rivierarm met moerasbos en riet · wandelen langs de meander vanaf Empe of station Voorst-Empe',
 'desc': 'De <b>Oude IJssel te Empe</b> is de oude rivierarm die ontstond toen in <b>1356</b> de hertog van Gelre een wijde meander van de IJssel bij Zutphen liet afsnijden — de bocht bedreigde letterlijk de zuidrand van de stad. Sindsdien ligt de oude waterloop langzaam te verlanden, en wat overbleef is een van de mooiste natuurverschijnselen van de IJsselvallei: een <b>bijna ondoordringbare, natte strook</b> tussen Empe en Voorstonden, waar de oude bedding nog goed herkenbaar is in het landschap. In de ondiepe, stilstaande arm groeien riet, lisdodde, elzen en wilgen; op het water rusten eenden en ganzen, en langs de randen foerageren reigers en ijsvogels. De arm wordt omzoomd door graslanden en oude landgoedbossen: ten zuiden liggen de weilanden van de Overmars en het <b>Sterrebos</b> met een oude bunker die uilen herbergt, en ten noorden het park van <b>Huize Empe</b>, waar een pad door het park wandelaars toelaat. Vanaf het talud van de oude arm en bij de <b>Meeuwenberg in de Emperbocht</b> heb je mooie vergezichten over dit stille rivierenlandschap. De wandeling langs de Oude IJssel is vanaf station Voorst-Empe of vanuit het dorp Empe gemakkelijk te maken.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, okt–mrt (watervogels), apr–jun (zangvogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of avond — vogels en rust.',
 'why': ['De <b>afgesneden rivierarm</b> uit 1356, nu een verlande natuurstrook.', 'De <b>vogels</b>: eenden, ganzen, reigers en misschien de ijsvogel.', 'Het <b>cultuurlandschap</b> met Sterrebos, Huize Empe en de Meeuwenberg.', 'De <b>rustige wandelingen</b> vanuit Empe of station Voorst-Empe.'],
 'phen': ['<span class="months">Okt–Mrt</span> 🦆 <b>Eenden en ganzen</b> op het open water.', '<span class="months">Mrt–Jun</span> 🐦 <b>Zangvogels</b> in riet en moerasbos.', '<span class="months">Apr–Sep</span> 💧 <b>IJsvogel en reiger</b> langs de oever.', '<span class="months">Heel jaar</span> 🌿 <b>Verlanding</b>: de arm groeit langzaam dicht.'],
 'wild': ['🦆 Wilde eend · Kuifeend · Kolgans (winter)', '🐦 IJsvogel · Blauwe reiger · Rietzanger', '🦌 Ree · Haas', '🦉 Bosuil (Sterrebos)', '🌿 Riet · Lisdodde · Zwarte els · Wilg'],
 'trail': ['Start bij <b>station Voorst-Empe</b> of in het dorp Empe en volg de meander.', 'Loop via het <b>Sterrebos</b> of het parkpad van Huize Empe terug.', 'Zoek het uitzicht bij de <b>Meeuwenberg in de Emperbocht</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ De arm zelf is ondoordringbaar — wandel op de omliggende wegen en paden · 🚶 Wegen, zandpaden en kades'
}, {
 'tags': ['Gelderland · Empe (Voorst)', 'Cut-off branch of the IJssel between Empe and Voorstonden · silted up into an almost impenetrable wet nature strip', 'list 36 · no. 571'],
 'loc': '📍 South and west of Empe, between the village and Voorstonden · Old river branch with marsh wood and reed · walk along the meander from Empe or Voorst-Empe station',
 'desc': 'The <b>Oude IJssel te Empe</b> is the old river branch that arose when in <b>1356</b> the Duke of Guelders had a wide meander of the IJssel near Zutphen cut off — the bend literally threatened the southern edge of the city. Since then the old watercourse has been slowly silting up, and what remains is one of the finest natural phenomena of the IJssel valley: an <b>almost impenetrable, wet strip</b> between Empe and Voorstonden, where the old bed is still clearly recognisable in the landscape. In the shallow, still branch grow reed, bulrush, alders and willows; ducks and geese rest on the water, and herons and kingfishers forage along the edges. The branch is bordered by grasslands and old estate woods: to the south lie the meadows of the Overmars and the <b>Sterrebos</b> with an old bunker that houses owls, and to the north the park of <b>Huize Empe</b>, where a path through the park admits walkers. From the bank of the old branch and at the <b>Meeuwenberg in the Emperbocht</b> you have fine views over this quiet river landscape. The walk along the Oude IJssel is easy to make from Voorst-Empe station or from the village of Empe.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Oct–Mar (waterbirds), Apr–Jun (songbirds)<br>\n    <b>Best time of day:</b> Morning or evening — birds and quiet.',
 'why': ['The <b>cut-off river branch</b> from 1356, now a silted-up nature strip.', 'The <b>birds</b>: ducks, geese, herons and maybe the kingfisher.', 'The <b>cultural landscape</b> with Sterrebos, Huize Empe and the Meeuwenberg.', 'The <b>quiet walks</b> from Empe or Voorst-Empe station.'],
 'phen': ['<span class="months">Oct–Mar</span> 🦆 <b>Ducks and geese</b> on the open water.', '<span class="months">Mar–Jun</span> 🐦 <b>Songbirds</b> in reed and marsh wood.', '<span class="months">Apr–Sep</span> 💧 <b>Kingfisher and heron</b> along the bank.', '<span class="months">All year</span> 🌿 <b>Siltation</b>: the branch slowly grows shut.'],
 'wild': ['🦆 Mallard · Tufted duck · White-fronted goose (winter)', '🐦 Kingfisher · Grey heron · Reed warbler', '🦌 Roe deer · Hare', '🦉 Tawny owl (Sterrebos)', '🌿 Reed · Bulrush · Black alder · Willow'],
 'trail': ['Start at <b>Voorst-Empe station</b> or in the village of Empe and follow the meander.', 'Return via the <b>Sterrebos</b> or the park path of Huize Empe.', 'Look for the view at the <b>Meeuwenberg in the Emperbocht</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The branch itself is impenetrable — walk on the surrounding roads and paths · 🚶 Roads, sand paths and banks'
}))

C.append(mk.card(1853, 'Voorstonden', {
 'tags': ['Gelderland · Voorstonden (Brummen)', 'Parkbos van landgoed Voorstonden tussen Brummen en Voorst · Zocher-vijvers, statige lanen en oude bomen', 'list 36 · no. 572'],
 'loc': '📍 Tussen Brummen en Voorst, aan de Voorsterweg (Voorsterweg 139) · Parkbos van Natuurmonumenten rond het witgepleisterde Huis Voorstonden · parkeerplaats bij het huis',
 'desc': '<b>Voorstonden</b> is het parkbos van het gelijknamige landgoed, gelegen tussen Brummen en Voorst en beheerd door <b>Natuurmonumenten</b>. Al in de middeleeuwen lag hier een landgoed; het huidige, <b>witgepleisterde Huis Voorstonden</b> kreeg zijn aanzien bij ingrijpende verbouwingen in <b>1825</b>, nadat de grachten al in de zestiende eeuw waren aangelegd en het goed vanaf 1656 eeuwenlang in handen was van de familie Schimmelpenninck van der Oye. In de negentiende eeuw nodigde de eigenaar tuinarchitect <b>Jan David Zocher</b> uit, die in Engelse landschapsstijl grote vijvers liet aanleggen en een afwisselend park rond het huis ontwierp. Het parkbos raakte verwaarloosd, maar Natuurmonumenten knapte het grondig op en stelde het in <b>2012</b> weer open: de slingerende paden, vijvers met vloeiende vormen, boskamers en romantische bruggetjes zijn weer als vroeger. Tegenwoordig wandel je er langs <b>doorkijkjes, statige lanen en eeuwenoude loofbomen</b>; in het voorjaar kleuren sneeuwklokjes de bosbodem, en hazen en ijsvogels laten zich geregeld zien. Vanaf de parkeerplaats lopen routes van 2, 2,5 en 7 kilometer (deels rolstoelgeschikt); het huis zelf is privé bewoond en alleen van afstand te bewonderen. Het landgoed maakt deel uit van het Natura 2000-gebied Landgoederen Brummen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, feb–mrt (sneeuwklokjes), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig en laag licht over de vijvers.',
 'why': ['Het <b>eeuwenoude parkbos</b> in de sfeer van weleer.', 'De <b>Zocher-vijvers en romantische bruggetjes</b> in landschapsstijl.', 'Het <b>witgepleisterde Huis Voorstonden</b> (privé) vanaf de paden.', 'De <b>routes van 2 tot 7 kilometer</b>, deels rolstoelgeschikt.'],
 'phen': ['<span class="months">Feb–Mrt</span> 🌼 <b>Sneeuwklokjes</b> in het parkbos.', '<span class="months">Mrt–Jun</span> 🐦 <b>Zangvogels en spechten</b>.', '<span class="months">Apr–Sep</span> 💧 <b>IJsvogel</b> boven de vijvers.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> langs de lanen.'],
 'wild': ['🐦 IJsvogel · Grote bonte specht · Boomklever', '🦌 Ree · Haas · Eekhoorn', '🦆 Wilde eend · Waterhoen', '🌳 Beuk · Zomereik · Linde', '🌼 Sneeuwklokje · Daslook'],
 'trail': ['Parkeer bij <b>Huis Voorstonden</b> (Voorsterweg 139).', 'Loop de <b>Parkbosroute van 2 km</b> (rolstoelgeschikt) of de rode route van 7 km.', 'Combineer met de <b>Oekense beek</b> of een bezoek aan Brummen.'],
 'foot': '🐕 Honden aangelijnd, op de paden · 💶 Gratis · ⚠️ Huis en tuin zijn niet toegankelijk — privé bewoond · 🚶 Park-, laan- en bospaden (halfverhard en zand)'
}, {
 'tags': ['Gelderland · Voorstonden (Brummen)', 'Park wood of the Voorstonden estate between Brummen and Voorst · Zocher ponds, stately avenues and old trees', 'list 36 · no. 572'],
 'loc': '📍 Between Brummen and Voorst, on the Voorsterweg (Voorsterweg 139) · Park wood of Natuurmonumenten around the white-plastered Huis Voorstonden · car park at the house',
 'desc': '<b>Voorstonden</b> is the park wood of the estate of the same name, between Brummen and Voorst and managed by <b>Natuurmonumenten</b>. An estate already lay here in the Middle Ages; the present, <b>white-plastered Huis Voorstonden</b> gained its appearance in extensive alterations in <b>1825</b>, after the moats had already been dug in the sixteenth century and the property had been in the hands of the Schimmelpenninck van der Oye family for centuries from 1656. In the nineteenth century the owner invited landscape architect <b>Jan David Zocher</b>, who had large ponds dug in the English landscape style and designed a varied park around the house. The park wood fell into neglect, but Natuurmonumenten thoroughly restored it and reopened it in <b>2012</b>: the winding paths, ponds with flowing forms, woodland rooms and romantic bridges are as they once were. Today you walk past <b>vistas, stately avenues and centuries-old broadleaf trees</b>; in spring snowdrops colour the forest floor, and hares and kingfishers show themselves regularly. From the car park run routes of 2, 2.5 and 7 kilometres (partly wheelchair-accessible); the house itself is privately inhabited and can only be admired from a distance. The estate forms part of the Natura 2000 site Landgoederen Brummen.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Feb–Mar (snowdrops), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet with low light over the ponds.',
 'why': ['The <b>centuries-old park wood</b> in the atmosphere of days gone by.', 'The <b>Zocher ponds and romantic bridges</b> in landscape style.', 'The <b>white-plastered Huis Voorstonden</b> (private) seen from the paths.', 'The <b>routes of 2 to 7 kilometres</b>, partly wheelchair-accessible.'],
 'phen': ['<span class="months">Feb–Mar</span> 🌼 <b>Snowdrops</b> in the park wood.', '<span class="months">Mar–Jun</span> 🐦 <b>Songbirds and woodpeckers</b>.', '<span class="months">Apr–Sep</span> 💧 <b>Kingfisher</b> above the ponds.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> along the avenues.'],
 'wild': ['🐦 Kingfisher · Great spotted woodpecker · Nuthatch', '🦌 Roe deer · Hare · Red squirrel', '🦆 Mallard · Moorhen', '🌳 Beech · Pedunculate oak · Lime', '🌼 Snowdrop · Wild garlic'],
 'trail': ['Park at <b>Huis Voorstonden</b> (Voorsterweg 139).', 'Walk the <b>2-km Parkbos route</b> (wheelchair-accessible) or the 7-km red route.', 'Combine with the <b>Oekense beek</b> or a visit to Brummen.'],
 'foot': '🐕 Dogs on lead, on the paths · 💶 Free · ⚠️ House and garden are not accessible — privately inhabited · 🚶 Park, avenue and forest paths (semi-paved and sand)'
}, n2k='Natura 2000-gebied Landgoederen Brummen (nr. 58) — landgoed met kwel- en bronwater, aangewezen voor onder meer vochtige alluviale bossen, blauwgraslanden en de kamsalamander', n2k_en='Natura 2000 site Landgoederen Brummen (no. 58) — estate with seepage and spring water, designated for, among others, alluvial wet forests, purple-moor-grass meadows and the great crested newt'))

C.append(mk.card(1854, 'Leusveld', {
 'tags': ['Gelderland · Hall (Brummen)', 'Landgoed van Natuurmonumenten bij Hall · rabattenbossen, orchideeën en het jachthuis Leusveld', 'list 36 · no. 573'],
 'loc': '📍 Ten zuiden van Hall, tussen de Rhienderensestraat en de Oekense beek · Landgoed van Natuurmonumenten · wandelen via het Hallsepad en de paden rond het jachthuis',
 'desc': 'Het <b>Leusveld</b> is een landgoed van <b>Natuurmonumenten</b> bij het buurtschap Hall, op de overgang van de Veluwe naar de IJsselvallei. Het is vanouds een nat, deels venig gebied — goed te zien aan de vele <b>rabatten</b> in het bos: langwerpige ophogingen met greppels ernaast die werden gegraven om het terrein te ontwateren. Centraal ligt het <b>jachthuis Leusveld</b> aan de Rhienderensestraat, een sierlijk huis uit de tijd dat hier nog gejaagd werd; de gevel toont dierfiguren die aan die geschiedenis herinneren. Het landgoed is beroemd om zijn flora: in de vochtige graslanden en langs de bosranden bloeien in het voorjaar en de vroege zomer tal van <b>orchideeën</b>, en ook dotterbloemen en andere kwelminnende planten doen het hier goed — dankzij het kalkrijke grondwater dat vanuit de Veluwe hier opwelt. Het Leusveld maakt deel uit van het <b>Natura 2000-gebied Landgoederen Brummen</b>. Over het landgoed lopen wandelpaden, waaronder het <b>Hallsepad</b>, een oud kerkenpad van Hall richting de omliggende landgoederen; het klompenpad Hallsekerkepad verbindt het gebied met Hall. Vanaf het uitkijkpunt \u2018Kiekuut\u2019 en bij de plas in het Turfveen kijk je uit over het natte landgoed.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jul</b>, mei–jun (orchideeën), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — vogels en bloemen.',
 'why': ['De <b>natte rabattenbossen</b> en het oude cultuurlandschap.', 'De <b>orchideeën</b> in grasland en bosrand.', 'Het <b>jachthuis Leusveld</b> met zijn dierfiguren.', 'Het <b>Hallsepad en klompenpad Hallsekerkepad</b> door het landgoed.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> in bloei.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in bos en struweel.', '<span class="months">Jun–Aug</span> 🦋 <b>Vlinders en libellen</b> bij het water.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in de rabattenbossen.'],
 'wild': ['🌸 Orchideeën · Dotterbloem · Spaanse ruiter', '🐦 IJsvogel · Grote bonte specht · Tjiftjaf', '🦌 Ree · Haas · Das', '🦋 Zilveren maan · Bont zandoogje', '🌳 Zwarte els · Zomereik · Es'],
 'trail': ['Wandel vanaf <b>Hall</b> over het Hallsepad of het klompenpad Hallsekerkepad het Leusveld in.', 'Bekijk het <b>jachthuis Leusveld</b> aan de Rhienderensestraat.', 'Zoek het <b>uitkijkpunt \u2018Kiekuut\u2019</b> en de plas in het Turfveen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Nat terrein — stevig schoeisel; orchideeënweides niet betreden · 🚶 Bos-, rabatten- en graspaden'
}, {
 'tags': ['Gelderland · Hall (Brummen)', 'Estate of Natuurmonumenten near Hall · ridge-and-furrow woods, orchids and the Leusveld hunting lodge', 'list 36 · no. 573'],
 'loc': '📍 South of Hall, between the Rhienderensestraat and the Oekense beek · Estate of Natuurmonumenten · walk via the Hallsepad and the paths around the hunting lodge',
 'desc': 'The <b>Leusveld</b> is an estate of <b>Natuurmonumenten</b> near the hamlet of Hall, on the transition from the Veluwe to the IJssel valley. It has always been a wet, partly peaty area — clearly visible in the many <b>ridge-and-furrow beds (rabatten)</b> in the wood: elongated raised beds flanked by ditches, dug to drain the terrain. In the centre stands the <b>Leusveld hunting lodge</b> on the Rhienderensestraat, an elegant house from the time when hunting still took place here; its facade shows animal figures that recall that history. The estate is famous for its flora: in the moist grasslands and along the forest edges, numerous <b>orchids</b> bloom in spring and early summer, and marsh marigolds and other seepage-loving plants also thrive — thanks to the calcareous groundwater that wells up here from the Veluwe. The Leusveld forms part of the <b>Natura 2000 site Landgoederen Brummen</b>. Walking paths run over the estate, including the <b>Hallsepad</b>, an old church path from Hall towards the surrounding estates; the Hallsekerkepad farm trail connects the area with Hall. From the \u2018Kiekuut\u2019 viewpoint and at the pool in the Turfveen you look out over the wet estate.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jul</b>, May–Jun (orchids), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — birds and flowers.',
 'why': ['The <b>wet ridge-and-furrow woods</b> and the old cultural landscape.', 'The <b>orchids</b> in grassland and forest edge.', 'The <b>Leusveld hunting lodge</b> with its animal figures.', 'The <b>Hallsepad and Hallsekerkepad farm trail</b> through the estate.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Orchids</b> in bloom.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in wood and scrub.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies and dragonflies</b> near the water.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the ridge-and-furrow woods.'],
 'wild': ['🌸 Orchids · Marsh marigold · Meadow thistle', '🐦 Kingfisher · Great spotted woodpecker · Chiffchaff', '🦌 Roe deer · Hare · Badger', '🦋 Silver-washed fritillary · Speckled wood', '🌳 Black alder · Pedunculate oak · Ash'],
 'trail': ['Walk from <b>Hall</b> over the Hallsepad or the Hallsekerkepad farm trail into the Leusveld.', 'View the <b>Leusveld hunting lodge</b> on the Rhienderensestraat.', 'Look for the <b>\u2018Kiekuut\u2019 viewpoint</b> and the pool in the Turfveen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Wet terrain — sturdy footwear; do not enter the orchid meadows · 🚶 Forest, ridge-and-furrow and grass paths'
}, n2k='Natura 2000-gebied Landgoederen Brummen (nr. 58) — landgoed met kwel- en bronwater, aangewezen voor blauwgraslanden, vochtige alluviale bossen en de kamsalamander', n2k_en='Natura 2000 site Landgoederen Brummen (no. 58) — estate with seepage and spring water, designated for purple-moor-grass meadows, alluvial wet forests and the great crested newt'))

mk.insert(C, chunk='reserves-1835-1934.json')
mk.progress(1854)
mk.check()
