# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1955, 'Buurserzand', {
 'tags': ['Overijssel · Haaksbergen (tussen Enschede en Haaksbergen)', 'Heide- en stuifzandgebied van Natuurmonumenten · jeneverbesstruwelen van wel 150 jaar oud · infopunt De Wakel en de herstelde Buurserbeek', 'list 36 · no. 674'],
 'loc': '📍 Tussen Enschede en Haaksbergen, tegen het dorp Buurse aan · vrij toegankelijk; wandelroutes starten bij parkeerplaats Molenbelt naast infopunt De Wakel (Stendermolenweg 9, Haaksbergen)',
 'desc': 'Het <b>Buurserzand</b> is het uitgestrekte heide- en stuifzandlandschap van <b>Natuurmonumenten</b> tussen Enschede en Haaksbergen, tegen het dorp Buurse aan. Samen met het Haaksbergerveen vormt het het <b>Natura 2000-gebied “Buurserzand &amp; Haaksbergerveen”</b>. Op de hogere gronden liggen uitgestrekte velden struikheide en dopheide, afgewisseld met open stuifzand, vennen, jeneverbesstruwelen en oude eiken-berkenbossen. De jeneverbesstruiken zijn hier uitzonderlijk: sommige zijn naar schatting <b>150 jaar oud</b> en behoren tot de oudste en grootste struwelen van West-Europa. De gemarkeerde wandelroutes beginnen bij parkeerplaats <b>Molenbelt</b> naast het infopunt <b>De Wakel</b> — Twents voor jeneverbes — gevestigd in de voormalige werkschuur van Natuurmonumenten, met uitzicht over de heide en koffie van vrijwilligers. De langere routes voeren langs de rand van het gebied, over de <b>Harrevelderschans</b> uit de zestiende eeuw en langs de herstelde <b>Buurserbeek</b>, die vanuit Duitsland richting de IJssel stroomt en waar ooit een vistrap werd aangelegd.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–Sep</b> (heide in bloei), apr–jun (vogelzang), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — licht en rust boven de heide.',
 'why': ['De <b>eeuwenoude jeneverbesstruiken</b>, uniek voor West-Europa.', 'De <b>paarse heide</b> in augustus en september.', 'De wandelroutes van <b>3 tot 10 kilometer</b> vanaf parkeerplaats Molenbelt.', 'De combinatie van <b>Harrevelderschans en Buurserbeek</b> met de heide.'],
 'phen': ['<span class="months">Aug–Sep</span> 🌸 <b>Heide in bloei</b>: de velden kleuren paars.', '<span class="months">Apr–Jun</span> 🐦 <b>Vogelzang</b> op de heide: boompieper, graspieper en roodborsttapuit.', '<span class="months">Mei–Jul</span> 🪰 <b>Libellen en amfibieën</b> rond de vennen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b>: jeneverbessen en nevel boven de heide.'],
 'wild': ['🌿 Struikheide · Dopheide · Jeneverbes', '🐦 Boompieper · Graspieper · Roodborsttapuit', '🦋 Heideblauwtje · Hooibeestje · Bont zandoogje', '🐸 Heikikker · Levendbarende hagedis', '🦌 Ree · Haas'],
 'trail': ['Wandel vanaf parkeerplaats <b>Molenbelt</b> (naast De Wakel) over de gemarkeerde routes van 3 tot 10 kilometer.', 'Volg de lange route langs de <b>Buurserbeek, de vistrap en de Harrevelderschans</b>.', 'Pauzeer bij <b>De Wakel</b> (za–do 12:00–16:30) voor koffie en een streekproduct.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ☕ De Wakel open za–do 12:00–16:30 (vrijdag gesloten) · ⚠️ Blijf op de paden; de heide is kwetsbaar · 🚶 Gemarkeerde wandelroutes 3–10 km'
}, {
 'tags': ['Overijssel · Haaksbergen (between Enschede and Haaksbergen)', 'Heathland and drifting-sand area of Natuurmonumenten · juniper scrub up to an estimated 150 years old · De Wakel visitor point and the restored Buurserbeek', 'list 36 · no. 674'],
 'loc': '📍 Between Enschede and Haaksbergen, against the village of Buurse · freely accessible; walking routes start at the Molenbelt car park next to the De Wakel visitor point (Stendermolenweg 9, Haaksbergen)',
 'desc': 'The <b>Buurserzand</b> is the vast heathland and drifting-sand landscape of <b>Natuurmonumenten</b> between Enschede and Haaksbergen, against the village of Buurse. Together with the Haaksbergerveen it forms the <b>Natura 2000 site “Buurserzand &amp; Haaksbergerveen”</b>. On the higher grounds lie extensive fields of heather and cross-leaved heath, alternating with open drifting sand, fens, juniper scrub and old oak-birch woodland. The juniper shrubs here are exceptional: some are an estimated <b>150 years old</b> and belong to the oldest and largest stands of Western Europe. The marked walking routes start at the <b>Molenbelt</b> car park next to the <b>De Wakel</b> visitor point — Twente dialect for juniper — housed in the former work shed of Natuurmonumenten, with a view over the heath and coffee served by volunteers. The longer routes run along the edge of the area, over the <b>Harrevelderschans</b> from the sixteenth century and along the restored <b>Buurserbeek</b>, which flows from Germany towards the IJssel and where a fish ladder was once built.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather in bloom), Apr–Jun (birdsong), Oct (autumn)<br>\n    <b>Best time of day:</b> Early morning — light and silence above the heath.',
 'why': ['The <b>centuries-old juniper scrub</b>, unique in Western Europe.', 'The <b>purple heath</b> in August and September.', 'The walking routes of <b>3 to 10 kilometres</b> from the Molenbelt car park.', 'The combination of the <b>Harrevelderschans and Buurserbeek</b> with the heath.'],
 'phen': ['<span class="months">Aug–Sep</span> 🌸 <b>Heather in bloom</b>: the fields turn purple.', '<span class="months">Apr–Jun</span> 🐦 <b>Birdsong</b> on the heath: tree pipit, meadow pipit and stonechat.', '<span class="months">May–Jul</span> 🪰 <b>Dragonflies and amphibians</b> around the fens.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b>: juniper berries and mist above the heath.'],
 'wild': ['🌿 Heather · Cross-leaved heath · Juniper', '🐦 Tree pipit · Meadow pipit · Stonechat', '🦋 Small heath · Gatekeeper · Speckled wood', '🐸 Moor frog · Viviparous lizard', '🦌 Roe deer · Hare'],
 'trail': ['Walk from the <b>Molenbelt</b> car park (next to De Wakel) over the marked routes of 3 to 10 kilometres.', 'Follow the long route along the <b>Buurserbeek, the fish ladder and the Harrevelderschans</b>.', 'Take a break at <b>De Wakel</b> (Sat–Thu 12:00–16:30) for coffee and a regional product.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ☕ De Wakel open Sat–Thu 12:00–16:30 (closed Friday) · ⚠️ Stay on the paths; the heath is fragile · 🚶 Marked walking routes 3–10 km'
}, n2k='Natura 2000-gebied “Buurserzand &amp; Haaksbergerveen” (Habitatrichtlijn): droge en natte heide, vennen en jeneverbesstruwelen', n2k_en='Natura 2000 site “Buurserzand &amp; Haaksbergerveen” (Habitats Directive): dry and wet heathland, fens and juniper scrub'))

C.append(mk.card(1956, 'Witte Veen', {
 'tags': ['Overijssel · Haaksbergen (Buurse, tegen de Duitse grens)', 'Grensoverschrijdend heide-, veen- en bosgebied van Natuurmonumenten · Natura 2000-hoogveen in de grens-veenketen · Schotse hooglanders en de Duitse Haarmühle', 'list 36 · no. 675'],
 'loc': '📍 Tussen Buurse en de Duitse grens (gemeente Haaksbergen) · vrij toegankelijk; wandelroutes starten bij Landgasthof Haarmühle in Alstätte (D) of vanaf de wegen rond Buurse',
 'desc': 'Het <b>Witte Veen</b> ligt tussen <b>Buurse</b> en de Duitse grens en is een van de hoogvenen van de lange veenketen die zich langs de grens uitstrekt — samen met onder meer het Aamsveen, het Haaksbergerveen en het Wooldse Veen. Het Nederlandse deel is sinds 2013 een <b>Natura 2000-gebied</b> en wordt beheerd door <b>Natuurmonumenten</b>: ruim 100 hectare, waarvan circa 40 hectare veen, omgeven door heide, bossen, vennetjes en graslandjes. <b>Schotse hooglanders</b> grazen er sinds jaar en dag en houden de heide open — het Witte Veen was een van de eerste gebieden in Nederland waar grote grazers voor dat doel werden ingezet. De naam verwijst waarschijnlijk naar het witte wollegras dat in het voorjaar boven het veen uitsteekt. In de herfst doen trekkende <b>kraanvogels</b> het gebied aan; de natte delen herbergen zeldzame libellen zoals de noordse glazenmaker en de hoogveenglanslibel, en de <b>boomkikker</b> breidt zich weer uit. Het is ook een grensverhaal: het veen was eeuwenlang een ideaal smokkelgebied, en langs de oude wegen staan nog achttiende-eeuwse grenspalen. Startpunt is vaak de Duitse <b>Haarmühle</b> in Alstätte, vanwaar twee korte ommetjes door het gebied lopen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en wollegras), aug–sep (heide en libellen), okt (kraanvogeltrek)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — rust en nevel boven het veen.',
 'why': ['Grensoverschrijdend wandelen: het landschap loopt hier <b>Nederland en Duitsland</b> door elkaar.', 'De <b>Schotse hooglanders</b> die de heide open houden.', 'De stilte en ruimte van <b>veen, heide en bos</b> tussen Buurse en de grens.', 'De <b>Natura 2000-status</b> van dit herstellende hoogveen.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌿 <b>Wollegras en veenpluis</b> steken wit boven het veen uit.', '<span class="months">Jun–Sep</span> 🪰 <b>Libellen</b>: noordse glazenmaker en hoogveenglanslibel.', '<span class="months">Sep–Okt</span> 🦢 <b>Kraanvogels</b> op de najaarstrek.', '<span class="months">Okt–Mrt</span> 🌫️ <b>Winter</b>: open landschap met rijp en ochtendnevel.'],
 'wild': ['🐮 Schotse hooglander', '🌿 Veenmos · Eenarig wollegras · Veenpluis', '🐸 Boomkikker · Heikikker', '🪰 Noordse glazenmaker · Hoogveenglanslibel', '🐦 Blauwborst · Boompieper · Rietgors'],
 'trail': ['Wandel het <b>gele ommetje (1,7 km)</b> of <b>rode ommetje (2,8 km)</b> vanaf Landgasthof Haarmühle in Alstätte.', 'Verken de zandweggetjes en paden <b>tussen Buurse en de grens</b> over de oude wegen.', 'Combineer met de fietsroute <b>Twente natuurlijk</b> langs Witte Veen en Buurserzand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ☕ Horeca bij de Duitse Haarmühle · ⚠️ Blijf op de paden; het veen is kwetsbaar · 🚶 Korte ommetjes en zandwegen'
}, {
 'tags': ['Overijssel · Haaksbergen (Buurse, against the German border)', 'Cross-border heath, bog and woodland area of Natuurmonumenten · Natura 2000 raised bog in the border chain of bogs · Scottish Highlanders and the German Haarmühle', 'list 36 · no. 675'],
 'loc': '📍 Between Buurse and the German border (municipality of Haaksbergen) · freely accessible; walking routes start at Landgasthof Haarmühle in Alstätte (D) or from the roads around Buurse',
 'desc': 'The <b>Witte Veen</b> lies between <b>Buurse</b> and the German border and is one of the raised bogs of the long chain of bogs along the frontier — together with, among others, the Aamsveen, the Haaksbergerveen and the Wooldse Veen. The Dutch part has been a <b>Natura 2000 site</b> since 2013 and is managed by <b>Natuurmonumenten</b>: more than 100 hectares, of which about 40 hectares of bog, surrounded by heath, woodland, small fens and grasslands. <b>Scottish Highlanders</b> have grazed here for years and keep the heath open — the Witte Veen was one of the first areas in the Netherlands where large grazers were used for that purpose. The name probably refers to the white cotton grass that rises above the bog in spring. In autumn, migrating <b>cranes</b> visit the area; the wet parts harbour rare dragonflies such as the fen emerald and the bog hawker, and the <b>tree frog</b> is expanding again. It is also a border story: the bog was an ideal smuggling area for centuries, and eighteenth-century border posts still stand along the old roads. The usual starting point is the German <b>Haarmühle</b> in Alstätte, from where two short circular walks run through the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and cotton grass), Aug–Sep (heath and dragonflies), Oct (crane migration)<br>\n    <b>Best time of day:</b> Early morning — silence and mist above the bog.',
 'why': ['Cross-border walking: here the landscape mixes <b>the Netherlands and Germany</b>.', 'The <b>Scottish Highlanders</b> that keep the heath open.', 'The silence and space of <b>bog, heath and woodland</b> between Buurse and the border.', 'The <b>Natura 2000 status</b> of this restoring raised bog.'],
 'phen': ['<span class="months">May–Jun</span> 🌿 <b>Cotton grass and bog cotton</b> rise white above the bog.', '<span class="months">Jun–Sep</span> 🪰 <b>Dragonflies</b>: fen emerald and bog hawker.', '<span class="months">Sep–Oct</span> 🦢 <b>Cranes</b> on their autumn migration.', '<span class="months">Oct–Mar</span> 🌫️ <b>Winter</b>: open landscape with frost and morning mist.'],
 'wild': ['🐮 Scottish Highlander', '🌿 Sphagnum moss · Hare’s-tail cotton grass · Bog cotton', '🐸 Tree frog · Moor frog', '🪰 Fen emerald · Bog hawker', '🐦 Bluethroat · Tree pipit · Reed bunting'],
 'trail': ['Walk the <b>yellow circuit (1.7 km)</b> or <b>red circuit (2.8 km)</b> from Landgasthof Haarmühle in Alstätte.', 'Explore the sandy lanes and paths <b>between Buurse and the border</b> over the old roads.', 'Combine with the <b>Twente natuurlijk</b> cycle route along the Witte Veen and Buurserzand.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ☕ Food and drink at the German Haarmühle · ⚠️ Stay on the paths; the bog is fragile · 🚶 Short circuits and sandy lanes'
}, n2k='Natura 2000-gebied Witte Veen (Habitatrichtlijn): herstellend en levend hoogveen, in beheer bij Natuurmonumenten', n2k_en='Natura 2000 site Witte Veen (Habitats Directive): restoring and active raised bog, managed by Natuurmonumenten'))

C.append(mk.card(1957, 'Haaksbergerveen', {
 'tags': ['Overijssel · Haaksbergen (oostkant, tegen de Duitse grens)', 'Een van de best herstellende hoogveenrestanten van Nederland · Staatsbosbeheer in de grensoverschrijdende veenketen · wandelen tussen levend hoogveen, heide en oude grensstenen', 'list 36 · no. 676'],
 'loc': '📍 Ten oosten van Haaksbergen, tegen de Duitse grens · vrij toegankelijk op wegen en paden; zes wandelroutes starten bij de parkeerplaats aan de Niekerkerweg',
 'desc': 'Het <b>Haaksbergerveen</b> is een van de <b>best herstellende hoogveenrestanten</b> van Nederland, gelegen ten oosten van <b>Haaksbergen</b> tegen de Duitse grens. Het vormt de kern van het Natura 2000-gebied “Buurserzand &amp; Haaksbergerveen” en maakt deel uit van de lange keten van grensvenen die zich van het Bargerveen tot diep in Duitsland uitstrekt. Staatsbosbeheer beheert het gebied: waar in het verleden turf werd gestoken, werken kades, stuwen en dammen aan een langzaam herstel — de natte delen groeien weer dicht met veenmossen, wollegras en lavendelhei, en in de putten en sloten zwemt de zeldzame <b>grote modderkruiper</b>. Door die herstellende natuur is het veen een van de beste plekken van Nederland om een <b>levend hoogveen</b> aan het werk te zien: veenmos groeit aan de bovenkant, verteert traag onder water en zet zo jaar na jaar nieuw veen af. Zes gemarkeerde wandelroutes starten bij de parkeerplaats aan de Niekerkerweg, van de korte Armenveenroute tot de lange John Dearpad-ommetocht. Onderweg passeren wandelaars de randen van het veen, heideveldjes, berkenbossen en oude <b>grenspalen</b> die de grens met Duitsland markeren.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en wollegras), jun–sep (libellen), sep–okt (veenheide)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — vogelzang en nevel boven het veen.',
 'why': ['Een van de <b>best herstellende hoogveenrestanten</b> van Nederland.', 'De grensoverschrijdende <b>veenketen</b> langs de Duitse grens.', 'De <b>zes wandelroutes</b> vanaf de Niekerkerweg, van 2,3 tot ver in de tientallen kilometers.', 'De <b>grote modderkruiper</b> en andere bijzondere bewoners van het natte veen.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌿 <b>Wollegras</b> pluist wit boven het veen.', '<span class="months">Apr–Jun</span> 🐦 <b>Broedvogels</b> van veen en rand: rietgors, blauwborst en graspieper.', '<span class="months">Jun–Sep</span> 🪰 <b>Libellen</b> boven de veenputten en -sloten.', '<span class="months">Sep–Okt</span> 🌸 <b>Veenheide en herfstkleuren</b> over het landschap.'],
 'wild': ['🐟 Grote modderkruiper', '🌿 Veenmos · Eenarig wollegras · Lavendelhei', '🐦 Rietgors · Blauwborst · Graspieper', '🐸 Heikikker · Levendbarende hagedis', '🪰 Libellen · Dagvlinders van het veen'],
 'trail': ['Start bij de <b>parkeerplaats aan de Niekerkerweg</b> en kies een van de zes gemarkeerde routes.', 'Wandel de <b>Armenveenroute</b> (kort rondje) of de lange <b>John Dearpad-ommetocht</b>.', 'Zoek onderweg de oude <b>grenspalen</b> langs de Duitse grens.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; het levende veen is kwetsbaar en deels onbegaanbaar · 🚶 Zes gemarkeerde routes vanaf de Niekerkerweg'
}, {
 'tags': ['Overijssel · Haaksbergen (east side, against the German border)', 'One of the best-restoring raised-bog remnants of the Netherlands · Staatsbosbeheer in the cross-border chain of bogs · walking between living bog, heath and old border posts', 'list 36 · no. 676'],
 'loc': '📍 East of Haaksbergen, against the German border · freely accessible on roads and paths; six walking routes start at the car park on the Niekerkerweg',
 'desc': 'The <b>Haaksbergerveen</b> is one of the <b>best-restoring raised-bog remnants</b> of the Netherlands, situated east of <b>Haaksbergen</b> against the German border. It forms the core of the Natura 2000 site “Buurserzand &amp; Haaksbergerveen” and is part of the long chain of border bogs that stretches from the Bargerveen deep into Germany. Staatsbosbeheer manages the area: where peat was once cut, dams, weirs and embankments work towards a slow recovery — the wet parts are growing closed again with sphagnum moss, cotton grass and cross-leaved bog heather, and the rare <b>spined loach</b> swims in the pits and ditches. Thanks to that recovery the bog is one of the best places in the Netherlands to see a <b>living raised bog</b> at work: sphagnum moss grows on top, decays slowly under water and thus builds new peat year after year. Six marked walking routes start at the car park on the Niekerkerweg, from the short Armenveen route to the long John Dearpad circuit. Along the way walkers pass the fringes of the bog, heath patches, birch woods and old <b>border posts</b> marking the frontier with Germany.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and cotton grass), Jun–Sep (dragonflies), Sep–Oct (bog heather)<br>\n    <b>Best time of day:</b> Early morning — birdsong and mist above the bog.',
 'why': ['One of the <b>best-restoring raised-bog remnants</b> of the Netherlands.', 'The cross-border <b>chain of bogs</b> along the German border.', 'The <b>six walking routes</b> from the Niekerkerweg, from 2.3 to tens of kilometres.', 'The <b>spined loach</b> and other special inhabitants of the wet bog.'],
 'phen': ['<span class="months">May–Jun</span> 🌿 <b>Cotton grass</b> blooms white above the bog.', '<span class="months">Apr–Jun</span> 🐦 <b>Breeding birds</b> of bog and fringe: reed bunting, bluethroat and meadow pipit.', '<span class="months">Jun–Sep</span> 🪰 <b>Dragonflies</b> above the peat pits and ditches.', '<span class="months">Sep–Oct</span> 🌸 <b>Bog heather and autumn colours</b> over the landscape.'],
 'wild': ['🐟 Spined loach', '🌿 Sphagnum moss · Hare’s-tail cotton grass · Cross-leaved bog heather', '🐦 Reed bunting · Bluethroat · Meadow pipit', '🐸 Moor frog · Viviparous lizard', '🪰 Dragonflies · Heath butterflies'],
 'trail': ['Start at the <b>car park on the Niekerkerweg</b> and choose one of the six marked routes.', 'Walk the <b>Armenveen route</b> (short circuit) or the long <b>John Dearpad circuit</b>.', 'Look for the old <b>border posts</b> along the German frontier on the way.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; the living bog is fragile and partly impassable · 🚶 Six marked routes from the Niekerkerweg'
}, n2k='Natura 2000-gebied “Buurserzand &amp; Haaksbergerveen” (Habitatrichtlijn): actief en herstellend hoogveen, in beheer bij Staatsbosbeheer', n2k_en='Natura 2000 site “Buurserzand &amp; Haaksbergerveen” (Habitats Directive): active and restoring raised bog, managed by Staatsbosbeheer'))

C.append(mk.card(1958, 'Bos bij de Duitse grens', {
 'tags': ['Overijssel · Twentse grensstreek (Buurse–Haaksbergen)', '⚠️ Naam uit de oude gids zonder eigen terrein of bezoekerspagina · oude benaming voor de bosstrook langs de rijksgrens, nu deel van het grensoverschrijdende natuurlandschap', 'list 36 · no. 677'],
 'loc': '📍 Niet meer als zelfstandig terrein aanwijsbaar · de oude gids noteert de naam na het Haaksbergerveen, in de grensstreek tussen Buurse en Haaksbergen; het huidige bos- en veenlandschap daar is van Natuurmonumenten en Staatsbosbeheer',
 'desc': '⚠️ Een eerlijke kaart: “Bos bij de Duitse grens” is een naam die de oude gids vermeldt in de reeks Twentse natuurgebieden langs de grens, direct na het Haaksbergerveen — maar een eigen terrein met die naam bestaat vandaag niet meer, en ook in moderne kaarten en registers komt de naam niet voor. De benaming is wel goed te begrijpen: tussen Buurse, Haaksbergen en de rijksgrens liggen de bossen en natuurgebieden die nu deel uitmaken van het grensoverschrijdende landschap van Natuurmonumenten en Staatsbosbeheer — het Witte Veen, het Buurserzand, het Haaksbergerveen en de bosranden langs de grenswegen. Langs die oude wegen staan nog historische grenspalen die herinneren aan de tijd dat de grens hier fel bewaakt werd en het veen een smokkelgebied was. Deze kaart registreert de naam eerlijk, zoals de gids hem geeft. Wie het bos- en grenslandschap wil beleven, wandelt het best door de aangrenzende natuurgebieden of over de stille wegen tussen Buurse en de Duitse grens.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), sep–okt (herfstkleuren)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rust op de grenswegen.',
 'why': ['De <b>historische naam</b> uit de oude gids — een stuk verdwenen topografie.', 'De <b>grensoverschrijdende bossen</b> langs de rijksgrens bij Buurse.', 'De oude <b>grenspalen</b> en het smokkelverleden van de streek.', 'De wandelmogelijkheden in het aangrenzende grenslandschap.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsbloei</b> in de bosranden.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> in bos en struweel.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleuren</b> en paddenstoelen.', '<span class="months">Okt–Mrt</span> 🌫️ <b>Winter</b>: kale bossen en stilte op de grenswegen.'],
 'wild': ['🌳 Beuk · Eik · Grove den', '🐦 Zwarte specht · Boomklever · Goudvink', '🦌 Ree · Haas', '🌿 Bosanemoon · Dalkruid', '🦋 Citroenvlinder · Oranjetipje'],
 'trail': ['Wandel door het aangrenzende <b>Witte Veen</b> of over de paden van het <b>Buurserzand</b>.', 'Verken de stille wegen tussen <b>Buurse en de Duitse grens</b>, langs oude grenspalen.', 'Maak een grensoverschrijdende wandeling vanaf <b>Landgasthof Haarmühle</b> in Duitsland.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen eigen terrein of route — deze kaart registreert de naam uit de oude gids · 🚶 Openbare wegen en paden van de aangrenzende natuurgebieden'
}, {
 'tags': ['Overijssel · Twente border region (Buurse–Haaksbergen)', '⚠️ Name from the old guide without its own terrain or visitor page · old designation for the woodland strip along the national border, now part of the cross-border natural landscape', 'list 36 · no. 677'],
 'loc': '📍 No longer identifiable as a separate terrain · the old guide notes the name after the Haaksbergerveen, in the border region between Buurse and Haaksbergen; the present woodland and bog landscape there belongs to Natuurmonumenten and Staatsbosbeheer',
 'desc': '⚠️ An honest card: “Bos bij de Duitse grens” is a name that the old guide lists in the series of Twente nature areas along the border, directly after the Haaksbergerveen — but a separate terrain with that name no longer exists, and modern maps and registers do not show it either. The designation is easy to understand though: between Buurse, Haaksbergen and the national border lie the woods and nature areas that today form part of the cross-border landscape of Natuurmonumenten and Staatsbosbeheer — the Witte Veen, the Buurserzand, the Haaksbergerveen and the woodland fringes along the border roads. Old border posts still stand along those roads, recalling the time when the frontier was heavily guarded and the bog was a smuggling area. This card records the name honestly, as the guide gives it. Those who want to experience the woodland and border landscape best walk through the adjacent nature areas or over the quiet roads between Buurse and the German border.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Sep–Oct (autumn colours)<br>\n    <b>Best time of day:</b> Morning — quiet on the border roads.',
 'why': ['The <b>historical name</b> from the old guide — a piece of vanished topography.', 'The <b>cross-border woods</b> along the national border near Buurse.', 'The old <b>border posts</b> and the smuggling past of the region.', 'The walking opportunities in the adjacent border landscape.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring bloom</b> in the woodland fringes.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> in wood and scrub.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colours</b> and fungi.', '<span class="months">Oct–Mar</span> 🌫️ <b>Winter</b>: bare woods and silence on the border roads.'],
 'wild': ['🌳 Beech · Oak · Scots pine', '🐦 Black woodpecker · Nuthatch · Bullfinch', '🦌 Roe deer · Hare', '🌿 Wood anemone · Lily of the valley', '🦋 Brimstone · Orange tip'],
 'trail': ['Walk through the adjacent <b>Witte Veen</b> or over the paths of the <b>Buurserzand</b>.', 'Explore the quiet roads between <b>Buurse and the German border</b>, past old border posts.', 'Take a cross-border walk from <b>Landgasthof Haarmühle</b> in Germany.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No terrain or route of its own — this card records the name from the old guide · 🚶 Public roads and paths of the adjacent nature areas'
}))

C.append(mk.card(1959, 'De Smalbraak', {
 'tags': ['Overijssel · Twentse grensstreek (Usselo–Buurse)', '⚠️ Naam uit de oude gids zonder eigen terrein of bezoekerspagina · “braak” duidt op braakliggende, ontgonnen grond · vermeld tussen de bos- en landgoednamen rond Usselo en Boekelo', 'list 36 · no. 678'],
 'loc': '📍 Niet meer als zelfstandig terrein aanwijsbaar · de oude gids plaatst de naam in dezelfde reeks als het Smalenbroek en Groot Brunink bij Usselo–Boekelo; de omgeving is vrij toegankelijk over wegen en paden',
 'desc': '⚠️ Een eerlijke kaart: <b>De Smalbraak</b> is een naam die de oude gids vermeldt in de reeks Twentse terreinen rond de grensstreek, tussen het Bos bij de Duitse grens en Het Broeke — in hetzelfde overzicht waarin ook het Smalenbroek, Groot Brunink en het Rutbeek staan. Een zelfstandig natuurterrein met deze naam bestaat vandaag niet meer; moderne kaarten en registers kennen alleen nog de naam als straat of veldnaam. De naam zelf is doorzichtig: “braak” of “braakland” betekent braakliggende of ontgonnen grond, en “smal” slaat op de geringe omvang — een klein, openliggend perceel te midden van bos en beek. Deze kaart registreert de naam eerlijk, zoals de gids hem geeft. Wie de sfeer van dit oude cultuurlandschap wil proeven, wandelt door de omgeving van Usselo en Boekelo: over de landgoederenroutes van het Smalenbroek, langs de Bruninksbeek en de Usselerstroom en door het coulisselandschap met houtwallen, essen en oude erven.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en voorjaarsflora), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de landgoedpaden.',
 'why': ['De <b>oude veldnaam</b> “braak” en de betekenis van braakliggende grond.', 'De ligging in de <b>reeks van de oude gids</b> rond Smalenbroek en Groot Brunink.', 'Het <b>coulisselandschap</b> van Usselo en Boekelo met houtwallen en beken.', 'De wandelroutes van <b>Landschap Overijssel</b> in de omgeving.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsbloei</b> in bosrand en houtwallen.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> en spechten in de landgoedbossen.', '<span class="months">Jun–Jul</span> 🌿 <b>Bloemrijke bermen</b> langs de paden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> over het landgoed.'],
 'wild': ['🌳 Beuk · Eik · Houtwallen', '🐦 Boomklever · Zwarte specht · Buizerd', '🦌 Ree · Eekhoorn', '🌿 Daslook · Bosanemoon (bosranden)', '🦋 Bont zandoogje · Citroenvlinder'],
 'trail': ['Wandel de <b>routes van Landschap Overijssel</b> door landgoed Smalenbroek en Groot Brunink.', 'Volg de paden langs de <b>Bruninksbeek en de Usselerstroom</b>.', 'Verken het buitengebied van <b>Usselo en Boekelo</b> over wegen en zandpaden.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen eigen terrein of route — deze kaart registreert de naam uit de oude gids · 🚶 Wegen en paden van de aangrenzende landgoederen'
}, {
 'tags': ['Overijssel · Twente border region (Usselo–Buurse)', '⚠️ Name from the old guide without its own terrain or visitor page · “braak” means fallow or reclaimed land · listed among the woodland and estate names around Usselo and Boekelo', 'list 36 · no. 678'],
 'loc': '📍 No longer identifiable as a separate terrain · the old guide places the name in the same series as the Smalenbroek and Groot Brunink near Usselo–Boekelo; the surroundings are freely accessible over roads and paths',
 'desc': '⚠️ An honest card: <b>De Smalbraak</b> is a name that the old guide lists in the series of Twente terrains around the border region, between the Bos bij de Duitse grens and Het Broeke — in the same overview that also contains the Smalenbroek, Groot Brunink and the Rutbeek. A separate nature terrain with this name no longer exists; modern maps and registers only know the name as a street or field name. The name itself is transparent: “braak” or “braakland” means fallow or reclaimed land, and “smal” refers to the small size — a small, open parcel amid woodland and brook. This card records the name honestly, as the guide gives it. Those who want to taste the atmosphere of this old cultivated landscape walk through the surroundings of Usselo and Boekelo: over the estate routes of the Smalenbroek, along the Bruninksbeek and the Usselerstroom and through the small-scale landscape with hedgerows, essen fields and old farmsteads.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and spring flora), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet on the estate paths.',
 'why': ['The <b>old field name</b> “braak” and the meaning of fallow land.', 'Its position in the <b>series of the old guide</b> around the Smalenbroek and Groot Brunink.', 'The <b>small-scale landscape</b> of Usselo and Boekelo with hedgerows and brooks.', 'The walking routes of <b>Landschap Overijssel</b> in the surroundings.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring bloom</b> in woodland fringe and hedgerows.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> and woodpeckers in the estate woods.', '<span class="months">Jun–Jul</span> 🌿 <b>Flower-rich verges</b> along the paths.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> over the estate.'],
 'wild': ['🌳 Beech · Oak · Hedgerows', '🐦 Nuthatch · Black woodpecker · Buzzard', '🦌 Roe deer · Red squirrel', '🌿 Wild garlic · Wood anemone (woodland fringes)', '🦋 Speckled wood · Brimstone'],
 'trail': ['Walk the <b>Landschap Overijssel routes</b> through the Smalenbroek and Groot Brunink estates.', 'Follow the paths along the <b>Bruninksbeek and the Usselerstroom</b>.', 'Explore the countryside of <b>Usselo and Boekelo</b> over roads and sandy lanes.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No terrain or route of its own — this card records the name from the old guide · 🚶 Roads and paths of the adjacent estates'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1959)
mk.check()
