# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1950, 'Het Rutbeek', {
 'tags': ['Overijssel · Enschede (Usselo)', 'Recreatie- en natuurpark van circa 120 hectare rond een zandwinput uit de jaren zeventig · plassen, bos, riet en grasland met orchideeën · archeologische plek “Laag van Usselo”', 'list 36 · no. 669'],
 'loc': '📍 Aan de zuidkant van Enschede, tussen Usselo en Broekheurne · vrij toegankelijk; diverse parkeerplaatsen rond het park, wandelroutes langs de plassen',
 'desc': '<b>Het Rutbeek</b> is een recreatie- en natuurpark van circa <b>120 hectare</b> aan de zuidkant van <b>Enschede</b>, ontstaan door grootschalige <b>zandwinning</b>: in de jaren zeventig werd hier zand gewonnen voor de wegen en wijken van Enschede, waarna het gat volliep met water. In 1975 werd begonnen met de aanleg van het recreatiegebied; in 1978 ging het eerste deel open en in 1982 was het park voltooid. Rond de grote plas liggen stranden, rietkragen, bospercelen, moerasjes en graslanden, met hoogteverschillen die door de zandwinning zijn ontstaan; het water is afgeschermd zwemwater, en op en om de plas wordt gezwommen, gezeild, gesurft, gereden (waterski) en gevist. Het park heeft ook natuurwaarde: in de bossen groeien onder meer wilde gagel en diverse orchideeën, de schone vijvers herbergen kranswieren en kleine natuurgebiedjes dienen als thuisbasis voor de beschermde <b>zandhagedis</b>. Bijzonder is de archeologische belevingsplek <b>“Laag van Usselo”</b> aan de rand van de plas, waar rendierjagers uit de steentijd hun sporen achterlieten. Rond het water lopen gemarkeerde wandelroutes door een verrassend afwisselend landschap van bos, vennen en open grasland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Sep</b>, jun–aug (recreatie op en rond de plas), mei–jun (vogelzang en orchideeën)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de wandelpaden.',
 'why': ['De <b>grote recreatieplas</b> die ontstond uit zandwinning.', 'De <b>afwisselende natuur</b>: bos, vennen, riet en orchideeëngrasland.', 'De <b>zandhagedis</b> in de kleine natuurgebiedjes.', 'De archeologische plek <b>“Laag van Usselo”</b> uit de steentijd.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> in de graslanden.', '<span class="months">Jun–Aug</span> 🏊 <b>Recreatie</b>: zwemmen, varen, surfen.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in bos en riet.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> rond de plassen.'],
 'wild': ['🦎 Zandhagedis', '🐦 Rietzanger · Aalscholver · Boomklever', '🐸 Poelkikker · Bruine kikker', '🦋 Bont zandoogje · Klein geaderd witje', '🌿 Wilde gagel · Orchideeën · Kranswieren'],
 'trail': ['Wandel de <b>blauwe route</b> rond de plas door bos, vennen en grasland.', 'Loop het fietspad rond het water of de <b>wandelroutes</b> vanaf de parkeerplaatsen.', 'Bezoek de belevingsplek <b>“Laag van Usselo”</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Parkeren en toegang grotendeels gratis; betaald bij evenementen · ⚠️ Zwemmen alleen in het afgeschermde deel · 🚶 Wandel- en fietspaden rond de plas'
}, {
 'tags': ['Overijssel · Enschede (Usselo)', 'Recreation and nature park of about 120 hectares around a 1970s sand-extraction pit · lakes, woodland, reed and grassland with orchids · archaeological site “Laag van Usselo”', 'list 36 · no. 669'],
 'loc': '📍 On the south side of Enschede, between Usselo and Broekheurne · freely accessible; several car parks around the park, walking routes along the lakes',
 'desc': '<b>Het Rutbeek</b> is a recreation and nature park of about <b>120 hectares</b> on the south side of <b>Enschede</b>, created by large-scale <b>sand extraction</b>: in the 1970s sand was won here for the roads and neighbourhoods of Enschede, after which the pit filled with water. In 1975 the construction of the recreation area began; in 1978 the first part opened and in 1982 the park was completed. Around the large lake lie beaches, reed beds, woodland parcels, marshes and grasslands, with height differences created by the sand extraction; the water is screened swimming water, and people swim, sail, surf, waterski and fish in and on the lake. The park also has nature value: in the woods grow among others wild bog-myrtle and several orchids, the clean ponds harbour stoneworts and small nature pockets serve as a home base for the protected <b>sand lizard</b>. Special is the archaeological experience site <b>“Laag van Usselo”</b> on the edge of the lake, where Stone Age reindeer hunters left their traces. Marked walking routes run around the water through a surprisingly varied landscape of woodland, fens and open grassland.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Sep</b>, Jun–Aug (recreation in and around the lake), May–Jun (birdsong and orchids)<br>\n    <b>Best time of day:</b> Morning — quiet on the walking paths.',
 'why': ['The <b>large recreation lake</b> that arose from sand extraction.', 'The <b>varied nature</b>: woodland, fens, reed and orchid grassland.', 'The <b>sand lizard</b> in the small nature pockets.', 'The archaeological site <b>“Laag van Usselo”</b> from the Stone Age.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Orchids</b> in the grasslands.', '<span class="months">Jun–Aug</span> 🏊 <b>Recreation</b>: swimming, boating, surfing.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in wood and reed.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> around the lakes.'],
 'wild': ['🦎 Sand lizard', '🐦 Reed warbler · Cormorant · Nuthatch', '🐸 Pool frog · Common frog', '🦋 Speckled wood · Green-veined white', '🌿 Wild bog-myrtle · Orchids · Stoneworts'],
 'trail': ['Walk the <b>blue route</b> around the lake through wood, fens and grassland.', 'Take the cycle path around the water or the <b>walking routes</b> from the car parks.', 'Visit the experience site <b>“Laag van Usselo”</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Parking and entry largely free; paid at events · ⚠️ Swim only in the screened section · 🚶 Walking and cycling paths around the lake'
}))

C.append(mk.card(1951, 'Groot Brunink', {
 'tags': ['Overijssel · Enschede (zuidkant, Usselo)', 'Landgoed van circa 100 hectare aan de zuidrand van Enschede · sinds 2013 deels beheerd door Landschap Overijssel · Hof te Brunink uit 1341 en de Bruninksbeek', 'list 36 · no. 670'],
 'loc': '📍 Aan de zuidkant van Enschede, tussen Usselo en het buitengebied van Lonneker · vrij toegankelijk over wegen en paden; wandelroutes starten bij de toegangslaan aan de Bruninkslaan',
 'desc': 'Landgoed <b>Groot Brunink</b> ligt aan de <b>zuidkant van Enschede</b>, ingebed in het Twentse hoevelandschap tussen de stad en het buitengebied. De geschiedenis gaat terug tot <b>1341</b>, toen de Hof te Brunink een borgleen was van de Nijeborg en daarmee indirect onder de bisschop van Münster viel; restanten van gracht, hoesstee en de zogenaamde Heerenwal herinneren nog aan die tijd. Het landgoed is circa 100 hectare groot en bestaat uit loof- en naaldbossen, houtwallen, weilanden en akkers, doorsneden door de <b>Bruninksbeek</b>; sinds 2013 beheert <b>Landschap Overijssel</b> een deel van circa 27 hectare (erfpacht van de gemeente Enschede), terwijl de monumentale boerderij Hof Brunink — een rijksmonument met jaarankers uit 1849 — tegenwoordig een biologisch melkveebedrijf huisvest. Het landgoed is een paradijs voor vogels met zo’n <b>58 soorten</b>, waaronder bosuil, patrijs en diverse spechten, en ree en vos laten er regelmatig hun sporen achter. Over het landgoed lopen wandelroutes van Landschap Overijssel en het IVN, die ook de mysterieuze put op Erve Brunink aandoen waarover verschillende verhalen de ronde doen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), mei (bloeiende houtwallen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of vroege avond.',
 'why': ['Het <b>landgoed met 900 jaar geschiedenis</b>, van borgleen tot natuurterrein.', 'De <b>58 vogelsoorten</b> waaronder bosuil, patrijs en spechten.', 'De <b>Bruninksbeek</b> en de oude gracht- en walrestanten.', 'De <b>wandelingen van Landschap Overijssel en IVN</b> over het landgoed.'],
 'phen': ['<span class="months">Mrt–Jun</span> 🐦 <b>Vogelzang</b>: spechten, bosuil en patrijs.', '<span class="months">Apr–Mei</span> 🌸 <b>Bosanemonen</b> en bloeiende houtwallen.', '<span class="months">Mei–Jun</span> 🌿 <b>Kruidenrijke graslanden</b> en akkerranden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> over het landgoed.'],
 'wild': ['🐦 Bosuil · Patrijs · Groene specht · Zwarte specht', '🦌 Ree · Vos', '🦔 Egel · Eekhoorn', '🦋 Bont zandoogje · Oranjetipje', '🌳 Eik · Beuk · Houtwallen · Oude gracht'],
 'trail': ['Loop de <b>Landschap Overijssel-route “Smalenbroek en Groot Brunink”</b>.', 'Wandel vanaf de <b>toegangslaan aan de Bruninkslaan</b> over de paden.', 'Sluit aan bij de <b>historische excursies</b> van IVN en Landschap Overijssel.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Deels agrarisch en particulier: blijf op wegen en paden · 🚶 Wegen, bospaden en landbouwwegen'
}, {
 'tags': ['Overijssel · Enschede (south side, Usselo)', 'Estate of about 100 hectares on the southern edge of Enschede · partly managed by Landschap Overijssel since 2013 · Hof te Brunink from 1341 and the Bruninksbeek', 'list 36 · no. 670'],
 'loc': '📍 On the south side of Enschede, between Usselo and the Lonneker countryside · freely accessible over roads and paths; walking routes start at the entrance avenue on the Bruninkslaan',
 'desc': 'The <b>Groot Brunink</b> estate lies on the <b>south side of Enschede</b>, embedded in the Twente farm landscape between the city and the countryside. The history goes back to <b>1341</b>, when the Hof te Brunink was a fief of the Nijeborg and thus indirectly under the bishop of Münster; remnants of moat, farmstead and the so-called Heerenwal still recall that era. The estate covers about 100 hectares and consists of broadleaf and conifer woods, hedgerows, pastures and fields, intersected by the <b>Bruninksbeek</b>; since 2013 <b>Landschap Overijssel</b> manages a part of about 27 hectares (leasehold from the municipality of Enschede), while the monumental farmstead Hof Brunink — a national monument with anchor dates from 1849 — now houses an organic dairy farm. The estate is a paradise for birds with some <b>58 species</b>, including tawny owl, partridge and several woodpeckers, and roe deer and fox regularly leave their traces here. Walking routes of Landschap Overijssel and IVN run over the estate, also passing the mysterious well on Erve Brunink about which various stories circulate.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), May (blooming hedgerows), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or early evening.',
 'why': ['The <b>estate with 900 years of history</b>, from fief to nature terrain.', 'The <b>58 bird species</b>, including tawny owl, partridge and woodpeckers.', 'The <b>Bruninksbeek</b> and the old moat and rampart remnants.', 'The <b>walks of Landschap Overijssel and IVN</b> over the estate.'],
 'phen': ['<span class="months">Mar–Jun</span> 🐦 <b>Birdsong</b>: woodpeckers, tawny owl and partridge.', '<span class="months">Apr–May</span> 🌸 <b>Wood anemones</b> and blooming hedgerows.', '<span class="months">May–Jun</span> 🌿 <b>Flower-rich grasslands</b> and field margins.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> over the estate.'],
 'wild': ['🐦 Tawny owl · Partridge · Green woodpecker · Black woodpecker', '🦌 Roe deer · Fox', '🦔 Hedgehog · Red squirrel', '🦋 Speckled wood · Orange tip', '🌳 Oak · Beech · Hedgerows · Old moat'],
 'trail': ['Walk the <b>Landschap Overijssel route “Smalenbroek en Groot Brunink”</b>.', 'Walk from the <b>entrance avenue on the Bruninkslaan</b> over the paths.', 'Join the <b>historical excursions</b> of IVN and Landschap Overijssel.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Partly agricultural and private: stay on roads and paths · 🚶 Roads, forest paths and farm lanes'
}))

C.append(mk.card(1952, 'Smalenbroek', {
 'tags': ['Overijssel · Enschede (Usselo–Boekelo)', 'Landgoed van Landschap Overijssel sinds 1981 · voormalig buiten van de textielfamilie Ter Kuile · rijksmonumentaal Erve Smalenbroek (1762) en park met vijver', 'list 36 · no. 671'],
 'loc': '📍 Tussen Usselo en Boekelo (gemeente Enschede), aan de Smalenbroeksweg · vrij toegankelijk; vier wandelroutes starten bij de parkeerplaats van Landschap Overijssel',
 'desc': 'Landgoed <b>Het Smalenbroek</b> is een van de zogenaamde <b>landgoederen van textiel</b> in Twente: het erf wordt al in 1346 genoemd, maar zijn huidige aanzien kreeg het nadat de Enschedese fabrikantenfamilie <b>Ter Kuile</b> het van 1894 tot 1981 bezat. M.E. ter Kuile liet rond 1900 het landgoed bebossen door de Nederlandse Heidemij en het park met vijver in landschappelijke stijl aanleggen door tuinarchitect Pieter Wattez; het landhuis dateert van 1958. Sinds 1981 is het landgoed in handen van de <b>Stichting Het Overijsselsche Landschap</b>. Op het erf staat het rijksmonumentale <b>Erve Smalenbroek</b> (jaartalsteen 1762), een hallenhuisboerderij met bovenkamer op een plint van Bentheimer zandsteen. Het landgoed bestaat uit bos, houtwallen, grasland en akkers, doorsneden door de Bruninksbeek en de Usselerstroom; vanaf de parkeerplaats van Landschap Overijssel lopen vier gemarkeerde wandelroutes (4,6 tot 11,7 kilometer) door het bos en het omringende coulisselandschap, langs de beken en de historische grenspaal “Werthepaal” bij de Duitse grens.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), mei (voorjaarsflora), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in het bos.',
 'why': ['Het <b>landgoed van textiel</b> van de familie Ter Kuile met park van Wattez.', 'De <b>rijksmonumentale hallenhuisboerderij</b> uit 1762.', 'De <b>vier wandelroutes</b> (4,6 tot 11,7 km) vanaf de parkeerplaats.', 'De ligging aan <b>Bruninksbeek en Usselerstroom</b> met de Werthepaal.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsbloei</b> in bos en park.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> en spechten.', '<span class="months">Jun–Jul</span> 🌿 <b>Kruidenrijke bermen</b> langs de paden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> over het landgoed.'],
 'wild': ['🐦 Boomklever · Zwarte specht · Buizerd', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Beuk · Eik · Douglas · Houtwallen'],
 'trail': ['Loop de <b>rode route</b> (4,6 km) door landgoed Smalenbroek.', 'Wandel de <b>paarse route</b> (11,7 km) langs Bruninksbeek en Usselerstroom.', 'Zoek onderweg de <b>Werthepaal</b> bij de Duitse grens.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Landgoed deels agrarisch in gebruik · 🚶 Gemarkeerde routes en bospaden'
}, {
 'tags': ['Overijssel · Enschede (Usselo–Boekelo)', 'Estate of Landschap Overijssel since 1981 · former country estate of the Ter Kuile textile family · nationally listed Erve Smalenbroek (1762) and park with pond', 'list 36 · no. 671'],
 'loc': '📍 Between Usselo and Boekelo (municipality of Enschede), on the Smalenbroeksweg · freely accessible; four walking routes start at the Landschap Overijssel car park',
 'desc': 'The <b>Het Smalenbroek</b> estate is one of the so-called <b>textile estates</b> in Twente: the farmyard is already mentioned in 1346, but it gained its present appearance after the Enschede manufacturer family <b>Ter Kuile</b> owned it from 1894 to 1981. Around 1900 M.E. ter Kuile had the estate afforested by the Nederlandse Heidemij and the park with pond laid out in landscape style by garden architect Pieter Wattez; the country house dates from 1958. Since 1981 the estate has been owned by the <b>Stichting Het Overijsselsche Landschap</b>. On the yard stands the nationally listed <b>Erve Smalenbroek</b> (anchor date 1762), a hall-house farm with an upper room on a plinth of Bentheim sandstone. The estate consists of woodland, hedgerows, grassland and fields, intersected by the Bruninksbeek and the Usselerstroom; from the Landschap Overijssel car park four marked walking routes (4.6 to 11.7 kilometres) run through the wood and the surrounding small-scale landscape, along the brooks and past the historic border post “Werthepaal” at the German border.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), May (spring flora), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet in the wood.',
 'why': ['The <b>textile estate</b> of the Ter Kuile family with Wattez park.', 'The <b>nationally listed hall-house farm</b> from 1762.', 'The <b>four walking routes</b> (4.6 to 11.7 km) from the car park.', 'Its position on the <b>Bruninksbeek and Usselerstroom</b> with the Werthepaal.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring bloom</b> in wood and park.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> and woodpeckers.', '<span class="months">Jun–Jul</span> 🌿 <b>Flower-rich verges</b> along the paths.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> over the estate.'],
 'wild': ['🐦 Nuthatch · Black woodpecker · Buzzard', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Beech · Oak · Douglas fir · Hedgerows'],
 'trail': ['Walk the <b>red route</b> (4.6 km) through the Smalenbroek estate.', 'Walk the <b>purple route</b> (11.7 km) along Bruninksbeek and Usselerstroom.', 'Look for the <b>Werthepaal</b> at the German border along the way.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Estate partly in agricultural use · 🚶 Marked routes and forest paths'
}))

C.append(mk.card(1953, 'Aamsveen', {
 'tags': ['Overijssel · Enschede (grens met Duitsland)', 'Hoogveengebied van Landschap Overijssel op de Nederlands-Duitse grens · deel van het grensoverschrijdende Amtsvenn-Hündfelder Moor · afgegraven veen, broekbossen, heide en veenputten', 'list 36 · no. 672'],
 'loc': '📍 Ten zuidoosten van Enschede, tegen de Duitse grens aan · vrij toegankelijk op wegen en paden; parkeerplaats aan de Aamsveenweg/Sagenweg, excursies starten bij Huize Hölterhof',
 'desc': 'Het <b>Aamsveen</b> is een van de laatste <b>levende hoogveengebieden</b> van Nederland, gelegen ten zuidoosten van <b>Enschede</b> op de grens met Duitsland, waar het overgaat in het veel grotere <b>Amtsvenn-Hündfelder Moor</b>. Het Nederlandse deel wordt beheerd door <b>Landschap Overijssel</b> en is aangewezen als <b>Natura 2000-gebied</b>. Het veen ontstond na afgraving van grote stukken hoogveen: je treft er afgegraven hoogveen met veenputten, natte broekbossen, heidevelden en schraalgraslanden, doorsneden door de Glanerbeek. Van de circa honderd hectare levend hoogveen die Nederland nog rest, ligt ruim een tiende in het Aamsveen. Een brand in 2011 legde een groot deel van het gebied in de as; sindsdien werkt Landschap Overijssel samen met Duitse partners aan <b>grensoverschrijdend hoogveenherstel</b> — met dammen, stuwen en lekdichting wordt het waterpeil gestabiliseerd zodat nieuw veenmos kan groeien. Het binnenste van het veen is tijdens de herstelwerkzaamheden deels afgesloten; wandelaars volgen de paden aan de rand, en wie het veen in wil, kan deelnemen aan de excursies van Landschap Overijssel en het Biologisch Station Zwillbrock.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Okt</b>, mei–jun (vogelzang en libellen), sep (veenheide in bloei)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — rust en nevel boven het veen.',
 'why': ['Een van de <b>laatste levende hoogveengebieden</b> van Nederland.', 'Het <b>grensoverschrijdende hoogveenherstel</b> met Duitsland.', 'De afwisseling van <b>veenputten, broekbossen, heide en schraalgrasland</b>.', 'De <b>excursies</b> van Landschap Overijssel het veen in.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌿 <b>Veenpluis en zonnedauw</b> in bloei.', '<span class="months">Jun–Sep</span> 🪰 <b>Libellen</b> boven de veenputten.', '<span class="months">Sep</span> 🌸 <b>Veenheide</b> kleurt het landschap.', '<span class="months">Heel jaar</span> 💧 <b>Herstelwerk</b>: dammen, stuwen en lekdichting.'],
 'wild': ['🐦 Geoorde fuut · Blauwborst · Boompieper', '🦋 Veenbesblauwtje · Hoogveenglanslibel', '🐸 Heikikker · Levendbarende hagedis', '🌿 Veenpluis · Ronde zonnedauw · Veenmos', '🌳 Berk · Grove den · Broekbos'],
 'trail': ['Wandel de <b>paden aan de rand</b> van het Aamsveen.', 'Doe mee met een <b>hoogveenexcursie</b> van Landschap Overijssel.', 'Start bij de <b>parkeerplaats Aamsveenweg/Sagenweg</b> of Huize Hölterhof.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis; excursies soms tegen betaling · ⚠️ Nat terrein; delen tijdens veenherstel afgesloten · 🚶 Zand- en veenpaden, deels smal'
}, {
 'tags': ['Overijssel · Enschede (border with Germany)', 'Raised-bog area of Landschap Overijssel on the Dutch-German border · part of the cross-border Amtsvenn-Hündfelder Moor · cut-over peat, fen woods, heath and peat pits', 'list 36 · no. 672'],
 'loc': '📍 South-east of Enschede, against the German border · freely accessible on roads and paths; car park at the Aamsveenweg/Sagenweg, excursions start at Huize Hölterhof',
 'desc': 'The <b>Aamsveen</b> is one of the last <b>living raised-bog areas</b> of the Netherlands, situated south-east of <b>Enschede</b> on the border with Germany, where it continues into the much larger <b>Amtsvenn-Hündfelder Moor</b>. The Dutch part is managed by <b>Landschap Overijssel</b> and has been designated a <b>Natura 2000 area</b>. The bog arose after the cutting of large stretches of raised bog: you will find cut-over bog with peat pits, wet fen woods, heath fields and species-poor grasslands, intersected by the Glanerbeek. Of the roughly one hundred hectares of living raised bog that remain in the Netherlands, more than a tenth lies in the Aamsveen. A fire in 2011 burnt a large part of the area to ashes; since then Landschap Overijssel works with German partners on <b>cross-border raised-bog restoration</b> — with dams, weirs and sealing, the water level is stabilised so that new sphagnum moss can grow. The interior of the bog is partly closed during the restoration works; walkers follow the paths on the edge, and those who want to enter the bog can join the excursions of Landschap Overijssel and the Biologisches Station Zwillbrock.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, May–Jun (birdsong and dragonflies), Sep (heath in bloom)<br>\n    <b>Best time of day:</b> Early morning — peace and mist above the bog.',
 'why': ['One of the <b>last living raised-bog areas</b> of the Netherlands.', 'The <b>cross-border raised-bog restoration</b> with Germany.', 'The variety of <b>peat pits, fen woods, heath and grasslands</b>.', 'The <b>excursions</b> of Landschap Overijssel into the bog.'],
 'phen': ['<span class="months">May–Jun</span> 🌿 <b>Cotton grass and sundew</b> in bloom.', '<span class="months">Jun–Sep</span> 🪰 <b>Dragonflies</b> above the peat pits.', '<span class="months">Sep</span> 🌸 <b>Bog heather</b> colours the landscape.', '<span class="months">All year</span> 💧 <b>Restoration work</b>: dams, weirs and sealing.'],
 'wild': ['🐦 Black-necked grebe · Bluethroat · Tree pipit', '🦋 Cranberry blue · Bog hawker', '🐸 Moor frog · Viviparous lizard', '🌿 Cotton grass · Round-leaved sundew · Sphagnum moss', '🌳 Birch · Scots pine · Fen wood'],
 'trail': ['Walk the <b>paths on the edge</b> of the Aamsveen.', 'Join a <b>raised-bog excursion</b> of Landschap Overijssel.', 'Start at the <b>Aamsveenweg/Sagenweg car park</b> or Huize Hölterhof.'],
 'foot': '🐕 Dogs on lead · 💶 Free; excursions sometimes paid · ⚠️ Wet terrain; parts closed during bog restoration · 🚶 Sandy and peat paths, partly narrow'
}, n2k='Natura 2000-gebied (Habitatrichtlijn): levend en herstellend hoogveen, in beheer bij Landschap Overijssel', n2k_en='Natura 2000 site (Habitats Directive): active and restoring raised bog, managed by Landschap Overijssel'))

C.append(mk.card(1954, 'De Zieppe', {
 'tags': ['Overijssel · Haaksbergen', '⚠️ Rijksmonumentaal boerderijcomplex “De Ziepe” uit 1915 aan de Enschedesestraat · betonnen vakwerk met spreuken — geen natuurterrein maar cultuurhistorisch wandeldoel', 'list 36 · no. 673'],
 'loc': '📍 Enschedesestraat 188, net buiten de bebouwde kom van Haaksbergen · het complex is particulier bewoond en vanaf de openbare weg te bekijken; geen parkeerterrein of eigen paden',
 'desc': '<b>De Zieppe</b> — ook wel gespeld <b>De Ziepe</b> — is een bijzonder boerderijcomplex uit <b>1915</b> aan de Enschedesestraat, even buiten de bebouwde kom van <b>Haaksbergen</b>. Het is in opdracht van de textielfabrikant <b>H. van Heek</b> gebouwd als experimentele Twentse boerderij: uiterlijk een traditioneel hallenhuis met vakwerk, maar het vakwerk is niet van hout maar van <b>gewapend beton</b> — een unieke constructie die in de betonnen balken van voor- en achtergevel en op de gebintbalken is voorzien van spreuken over de bouwgeschiedenis en de landbouwmaatregelen tijdens de Eerste Wereldoorlog. De gevels tonen decoratief metselmozaïek van gekleurde baksteen, met de naam “De Ziepe” ingemetseld tussen de verdiepingsvensters. Het complex, bestaande uit de boerderij en een houten schuur, is een <b>rijksmonument</b>. Het is geen natuurterrein met paden, maar een opvallend cultuurhistorisch object langs de weg — een mooie stopplaats voor wandelaars en fietsers die het buitengebied van Haaksbergen verkennen, waaronder de omgeving van de Veldmaat en het Haaksbergerveen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Heel jaar</b>, apr–okt (daglicht op het metselwerk)<br>\n    <b>Beste tijd van de dag:</b> Middag — licht op de voorgevel.',
 'why': ['De <b>unieke betonnen vakwerkconstructie</b> uit 1915.', 'De <b>ingemetselde spreuken</b> over oorlog en landbouw.', 'Het <b>decoratieve metselmozaïek</b> met de ingemetselde naam.', 'De ligging langs de route door het <b>Haaksbergse buitengebied</b>.'],
 'phen': ['<span class="months">Heel jaar</span> 🏛️ <b>Rijksmonument</b> vanaf de openbare weg.', '<span class="months">Mrt–Apr</span> 🌸 <b>Voorjaarsbloei</b> rond het erf.', '<span class="months">Apr–Jun</span> 🐦 <b>Vogelzang</b> in de omgeving.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het buitengebied.'],
 'wild': ['🏛️ Boerderij “De Ziepe” (1915, rijksmonument)', '🧱 Betonnen vakwerk met spreuken', '🎨 Metselmozaïek in gekleurde baksteen', '🐦 Buizerd · Boomklever (omgeving)', '🌳 Erfbeplanting · Oude bomen'],
 'trail': ['Bekijk het <b>complex</b> vanaf de Enschedesestraat.', 'Wandel of fiets door het <b>buitengebied van Haaksbergen</b>.', 'Combineer met de <b>Veldmaat, het Haaksbergerveen</b> of het Buurserzand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Particulier bewoond — niet betreden; bezichtiging vanaf de weg · 🚶 Openbare weg en omliggende wegen'
}, {
 'tags': ['Overijssel · Haaksbergen', '⚠️ Nationally listed farm complex “De Ziepe” from 1915 on the Enschedesestraat · concrete timber-frame with inscriptions — not a nature terrain but a cultural-historical walking destination', 'list 36 · no. 673'],
 'loc': '📍 Enschedesestraat 188, just outside the built-up area of Haaksbergen · the complex is privately inhabited and can be viewed from the public road; no car park or paths of its own',
 'desc': '<b>De Zieppe</b> — also spelled <b>De Ziepe</b> — is a special farm complex from <b>1915</b> on the Enschedesestraat, just outside the built-up area of <b>Haaksbergen</b>. It was built on the orders of textile manufacturer <b>H. van Heek</b> as an experimental Twente farm: outwardly a traditional hall-house with timber framing, but the frame is not of wood but of <b>reinforced concrete</b> — a unique construction bearing inscriptions in the concrete beams of the front and rear facades and on the tie beams about the building history and the agricultural measures during the First World War. The facades show decorative brick mosaics of coloured brick, with the name “De Ziepe” set into the masonry between the upper-floor windows. The complex, consisting of the farmhouse and a wooden barn, is a <b>national monument</b>. It is not a nature terrain with paths, but a striking cultural-historical object along the road — a nice stop for walkers and cyclists exploring the Haaksbergen countryside, including the surroundings of the Veldmaat and the Haaksbergerveen.',
 'meta': '<b>Best season &amp; peak months:</b> <b>All year</b>, Apr–Oct (daylight on the masonry)<br>\n    <b>Best time of day:</b> Afternoon — light on the front facade.',
 'why': ['The <b>unique concrete timber-frame construction</b> from 1915.', 'The <b>inscribed mottoes</b> about war and agriculture.', 'The <b>decorative brick mosaic</b> with the set-in name.', 'Its position along the route through the <b>Haaksbergen countryside</b>.'],
 'phen': ['<span class="months">All year</span> 🏛️ <b>National monument</b> from the public road.', '<span class="months">Mar–Apr</span> 🌸 <b>Spring bloom</b> around the yard.', '<span class="months">Apr–Jun</span> 🐦 <b>Birdsong</b> in the surroundings.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the countryside.'],
 'wild': ['🏛️ Farm “De Ziepe” (1915, national monument)', '🧱 Concrete timber frame with inscriptions', '🎨 Brick mosaic in coloured brick', '🐦 Buzzard · Nuthatch (surroundings)', '🌳 Farm planting · Old trees'],
 'trail': ['View the <b>complex</b> from the Enschedesestraat.', 'Walk or cycle through the <b>Haaksbergen countryside</b>.', 'Combine with the <b>Veldmaat, the Haaksbergerveen</b> or the Buurserzand.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Privately inhabited — do not enter; viewing from the road · 🚶 Public road and surrounding roads'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1954)
mk.check()
