# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1940, 'Bos te Meddo', {
 'tags': ['Gelderland · Meddo–Groenlo (Winterswijk, Oost Gelre)', 'Dennen-, eiken- en beukenbos van SBNL Natuurfonds (4,9 ha, geschonken 1988) aan de Groenlose Slinge · oude eiken en laanstructuren', 'list 36 · no. 659'],
 'loc': '📍 Ingeklemd tussen de Oosterholtweg en de Groenlose Slinge, op de grens van Meddo en Groenlo · vrij toegankelijk; rondom het perceel voert een wandeling via het werkpad langs de beek',
 'desc': 'Het <b>Bos te Meddo</b> is een klein bosperceel van het <b>SBNL Natuurfonds</b> van circa 4,9 hectare, dat als een taartpunt ligt ingeklemd tussen de <b>Oosterholtweg</b> en agrarische grond en aan de westzijde geheel wordt begrensd door de <b>Groenlose Slinge</b>. Het is een <b>dennen-, eiken- en beukenbos</b> op de grens van de buurtschap Meddo (Winterswijk) en de gemeente Oost Gelre; in 1988 kwam het door schenking van dhr. Theodore Kraakman uit Meddo in handen van het natuurfonds. Het perceel bewaart oud reliëf en <b>laanstructuren uit de tijd van vóór de ruilverkaveling</b> van 1998, en er staan nog enkele prachtige oude eiken die op zichzelf al natuurwaarde vertegenwoordigen. Via het werkpad van de beek en de werkpaden van de noordelijke afwateringssloot kan men om het gehele bosperceel wandelen: een stille ommetje door een van de vele groene oases van het Achterhoekse coulisselandschap, waar ooit het uitgestrekte heideveld van Meddo lag.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), mei (bosanemonen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig langs de Slinge.',
 'why': ['Het <b>SBNL-bosperceel van 4,9 hectare</b> aan de Groenlose Slinge.', 'De <b>oude eiken en laanstructuren</b> van vóór de ruilverkaveling.', 'De <b>wandeling om het perceel</b> via de werkpaden langs de beek.', 'De ligging op de grens van de <b>Meddose veldgronden</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsbloeiers</b> onder het oude loof.', '<span class="months">Mei–Jun</span> 🐦 <b>Zangvogels</b> in het gemengde bos.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> van eik en beuk.', '<span class="months">Heel jaar</span> 🚶 <b>Ommetje</b> langs de Groenlose Slinge.'],
 'wild': ['🐦 Boomklever · Grote bonte specht · Buizerd', '🦌 Ree · Eekhoorn', '🦊 Vos', '🦋 Bont zandoogje · Citroenvlinder', '🌳 Zomereik · Beuk · Grove den'],
 'trail': ['Loop de <b>wandeling om het perceel</b> via het werkpad langs de Slinge.', 'Wandel vanaf de <b>Oosterholtweg</b> het bos in.', 'Combineer met de routes over het <b>Meddose Veld</b> en langs de beek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Klein particulier natuurterrein: blijf op de paden · 🚶 Werkpaden en ommetje langs de beek'
}, {
 'tags': ['Gelderland · Meddo–Groenlo (Winterswijk, Oost Gelre)', 'Conifer, oak and beech wood of the SBNL Natuurfonds (4.9 ha, donated 1988) on the Groenlose Slinge · old oaks and avenue structures', 'list 36 · no. 659'],
 'loc': '📍 Wedged between the Oosterholtweg and the Groenlose Slinge, on the border of Meddo and Groenlo · freely accessible; a walk around the parcel runs via the maintenance path along the brook',
 'desc': 'The <b>Bos te Meddo</b> is a small wood parcel of the <b>SBNL Natuurfonds</b> of about 4.9 hectares, lying like a wedge of pie between the <b>Oosterholtweg</b> and farmland, fully bounded on the west side by the <b>Groenlose Slinge</b>. It is a <b>conifer, oak and beech wood</b> on the border of the hamlet of Meddo (Winterswijk) and the municipality of Oost Gelre; in 1988 it came into the hands of the nature fund through a donation from Mr Theodore Kraakman of Meddo. The parcel preserves old relief and <b>avenue structures from before the land consolidation</b> of 1998, and still holds several beautiful old oaks that represent nature value in themselves. Via the maintenance path of the brook and the service paths of the northern drainage ditch one can walk around the entire wood parcel: a quiet circuit through one of the many green oases of the Achterhoek small-scale landscape, where once the vast heath field of Meddo lay.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), May (wood anemones), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — quiet along the Slinge.',
 'why': ['The <b>SBNL wood parcel of 4.9 hectares</b> on the Groenlose Slinge.', 'The <b>old oaks and avenue structures</b> from before the land consolidation.', 'The <b>walk around the parcel</b> via the service paths along the brook.', 'Its position on the edge of the <b>Meddo field commons</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring bloomers</b> under the old broadleaf.', '<span class="months">May–Jun</span> 🐦 <b>Songbirds</b> in the mixed wood.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> of oak and beech.', '<span class="months">All year</span> 🚶 <b>Circuit</b> along the Groenlose Slinge.'],
 'wild': ['🐦 Nuthatch · Great spotted woodpecker · Buzzard', '🦌 Roe deer · Red squirrel', '🦊 Fox', '🦋 Speckled wood · Brimstone', '🌳 Pedunculate oak · Beech · Scots pine'],
 'trail': ['Walk the <b>circuit around the parcel</b> via the service path along the Slinge.', 'Enter the wood from the <b>Oosterholtweg</b>.', 'Combine with the routes over the <b>Meddose Veld</b> and along the brook.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Small private nature terrain: stay on the paths · 🚶 Service paths and circuit along the brook'
}))

C.append(mk.card(1941, 'Gelderesch', {
 'tags': ['Gelderland · Meddo (Winterswijk)', 'Scholtegoed en NSW-landgoed in de buurtschap Gelder Esch · monumentale T-boerderij met spin- en weefhuis · startpunt van “Rondje Gelderesch” en “Het Meddose Veld”', 'list 36 · no. 660'],
 'loc': '📍 Buurtschap Gelder Esch bij Winterswijk-Meddo, langs de Geldereschweg · landgoed deels vrij toegankelijk rondom; startpunt SP05 De Eendracht (Geldereschweg 84)',
 'desc': '<b>Gelderesch</b> is de buurtschap en het oude <b>scholtegoed</b> Gelder Esch in het buitengebied van <b>Winterswijk-Meddo</b>, genoemd naar de es waarop het erf werd gesticht. Het hart is een monumentaal boerderijcomplex aan de Geldereschweg 96: een <b>T-boerderij van omstreeks 1860</b> met daarnaast een <b>spin- en weefhuis van omstreeks 1900</b>, beide rijksmonument en onderdeel van een landgoed dat sinds 1928 de status van <b>NSW-landgoed</b> (landgoed onder de Natuurschoonwet) heeft en waarvan de wortels tot in de zeventiende eeuw teruggaan. Het landgoed omvat naast de erven ook grasland met houtwallen, bospercelen en een oude boomgaard, ingebed in het coulisselandschap tussen Meddo en de Groenlose Slinge. De Geldereschweg is daarnaast een bekend wandeladres: bij SP05 <b>De Eendracht</b> (Geldereschweg 84) starten de gemarkeerde routes <b>Rondje Gelderesch</b> (circa 8 kilometer) en <b>Het Meddose Veld</b> (circa 10,4 kilometer) door het omringende marke- en ontginningslandschap. Bezoekers wandelen over de openbare wegen en paden; de erven zelf zijn particulier bewoond.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en jong groen), mei–jun (bloeiende boomgaard), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag.',
 'why': ['Het <b>monumentale scholtegoed</b> met T-boerderij en spin- en weefhuis.', 'De routes <b>Rondje Gelderesch en Het Meddose Veld</b> vanaf SP05 De Eendracht.', 'De <b>NSW-landgoedstatus</b> sinds 1928 en de zeventiende-eeuwse wortels.', 'Het coulisselandschap rond <b>Meddo</b> met houtwallen en oude essen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Bloeiende boomgaard</b> op het landgoed.', '<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en bos.', '<span class="months">Mei–Jun</span> 🌿 <b>Kruidenrijke bermen</b> langs de wegen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> over het landgoed.'],
 'wild': ['🐦 Steenuil · Geelgors · Buizerd', '🦌 Ree · Haas', '🦋 Bont zandoogje · Oranjetipje', '🌳 Oude eiken · Fruitbomen', '🏛️ T-boerderij (1860) · Spin- en weefhuis (1900)'],
 'trail': ['Wandel <b>Rondje Gelderesch</b> (circa 8 km) vanaf SP05 De Eendracht.', 'Loop <b>Het Meddose Veld</b> (circa 10,4 km) door het buitengebied.', 'Bekijk het monumentale <b>boerderijcomplex</b> vanaf de Geldereschweg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Erven zijn particulier bewoond: blijf op de openbare paden en wegen · 🚶 Openbare wegen, paden en routeknooppunten'
}, {
 'tags': ['Gelderland · Meddo (Winterswijk)', 'Scholte estate and NSW estate in the hamlet of Gelder Esch · monumental T-farm with spinning and weaving house · start of the “Rondje Gelderesch” and “Het Meddose Veld” routes', 'list 36 · no. 660'],
 'loc': '📍 Hamlet of Gelder Esch near Winterswijk-Meddo, along the Geldereschweg · estate partly freely accessible around it; start point SP05 De Eendracht (Geldereschweg 84)',
 'desc': '<b>Gelderesch</b> is the hamlet and the old <b>scholte estate</b> Gelder Esch in the countryside of <b>Winterswijk-Meddo</b>, named after the field es on which the farm was founded. The heart is a monumental farm complex at Geldereschweg 96: a <b>T-farmhouse of about 1860</b> with beside it a <b>spinning and weaving house of about 1900</b>, both national monuments and part of an estate that has held the status of <b>NSW estate</b> (under the Natuurschoonwet fiscal nature-heritage scheme) since 1928 and whose roots go back to the seventeenth century. Besides the farmyards the estate comprises grassland with hedgerows, wood parcels and an old orchard, embedded in the small-scale landscape between Meddo and the Groenlose Slinge. The Geldereschweg is also a well-known walking address: at junction SP05 <b>De Eendracht</b> (Geldereschweg 84) start the marked routes <b>Rondje Gelderesch</b> (about 8 kilometres) and <b>Het Meddose Veld</b> (about 10.4 kilometres) through the surrounding common and reclamation landscape. Visitors walk over the public roads and paths; the farmyards themselves are privately inhabited.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and fresh green), May–Jun (blooming orchard), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon.',
 'why': ['The <b>monumental scholte estate</b> with T-farmhouse and spinning and weaving house.', 'The routes <b>Rondje Gelderesch and Het Meddose Veld</b> from SP05 De Eendracht.', 'The <b>NSW estate status</b> since 1928 and its seventeenth-century roots.', 'The small-scale landscape around <b>Meddo</b> with hedgerows and old essen.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Blooming orchard</b> on the estate.', '<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and wood.', '<span class="months">May–Jun</span> 🌿 <b>Flower-rich verges</b> along the roads.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> over the estate.'],
 'wild': ['🐦 Little owl · Yellowhammer · Buzzard', '🦌 Roe deer · Hare', '🦋 Speckled wood · Orange tip', '🌳 Old oaks · Fruit trees', '🏛️ T-farmhouse (1860) · Spinning and weaving house (1900)'],
 'trail': ['Walk <b>Rondje Gelderesch</b> (about 8 km) from SP05 De Eendracht.', 'Walk <b>Het Meddose Veld</b> (about 10.4 km) through the countryside.', 'View the monumental <b>farm complex</b> from the Geldereschweg.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Farmyards are privately inhabited: stay on public paths and roads · 🚶 Public roads, paths and route junctions'
}))

C.append(mk.card(1942, 'Meddoscheveld', {
 'tags': ['Gelderland · Meddo (Winterswijk)', 'Het “Meddose Veld”: meer dan 1.500 hectare heide, in de twintigste eeuw ontgonnen tot open weide- en bouwland · wandelroute van 10,4 km vanaf TOP Sevink Mölle', 'list 36 · no. 661'],
 'loc': '📍 Rond de buurtschap Meddo, ten noorden van Winterswijk · vrij toegankelijk over wegen en paden; route Het Meddose Veld start bij TOP Sevink Mölle (Meddoseweg 40)',
 'desc': 'Het <b>Meddoscheveld</b> — ook wel <b>Meddose Veld</b> genoemd — is het open veld- en ontginningslandschap rond de buurtschap <b>Meddo</b>, ten noorden van Winterswijk. Tot in de negentiende eeuw lag hier een van de grootste heidevelden van de Achterhoek: meer dan <b>1.500 hectare woeste heide</b>, in gemeenschappelijk gebruik door de marke van Meddo en omringende buurtschappen. In het begin van de twintigste eeuw werd het veld grootschalig ontgonnen: de heide maakte plaats voor akkers, weilanden, ontginningsbossen en rechte wegen met sloten, terwijl oude veldnamen als Masterveld en Bonkeveen aan de heidetijd herinneren. Tegenwoordig is het Meddoscheveld een open, rustig coulisselandschap met verspreide bosjes (waaronder het Armenbos en het Bos te Meddo), houtwallen en beekdalgraslanden langs de Groenlose Slinge en de Beurzerbeek; het is vrij te verkennen via wegen en paden. De gemarkeerde wandelroute <b>Het Meddose Veld</b> van circa 10,4 kilometer start bij TOP Sevink Mölle aan de Meddoseweg en voert door het buitengebied, langs de buurtschap, de beken en de oude ontginningslinten; ook startpunt De Eendracht aan de Geldereschweg doet de omgeving aan.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels), mei–jun (bloeiende bermen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — vogelzang boven het open veld.',
 'why': ['Het verhaal van <b>1.500 hectare heide</b> die plaatsmaakte voor ontginning.', 'De wandelroute <b>Het Meddose Veld</b> (circa 10,4 kilometer).', 'Het <b>open, rustige coulisselandschap</b> met beken en bosjes.', 'De oude veldnamen als <b>Masterveld en Bonkeveen</b>.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🎵 <b>Baltsende weidevogels</b>: kievit, grutto en wulp.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs de ontginningswegen.', '<span class="months">Jun–Jul</span> 🌾 <b>Hooi- en graantijd</b> op het voormalige veld.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> over het open land.'],
 'wild': ['🐦 Kievit · Grutto · Wulp · Veldleeuwerik', '🦌 Ree · Haas', '🦊 Vos', '🦋 Hooibeestje · Bont zandoogje', '🌾 Ontginningsland · Houtwallen · Beekdalgrasland'],
 'trail': ['Wandel <b>Het Meddose Veld</b> (circa 10,4 km) vanaf TOP Sevink Mölle.', 'Start ook mogelijk bij <b>De Eendracht</b> aan de Geldereschweg.', 'Combineer met het <b>Armenbos, Bos te Meddo</b> of de Beurzerbeek.'],
 'foot': '🐕 Honden aangelijnd (weidevogels!) · 💶 Gratis · ⚠️ Open terrein: weinig beschutting · 🚶 Wegen, zandpaden en routeknooppunten'
}, {
 'tags': ['Gelderland · Meddo (Winterswijk)', 'The “Meddose Veld”: more than 1,500 hectares of heath, reclaimed in the twentieth century into open pasture and arable land · 10.4 km walking route from TOP Sevink Mölle', 'list 36 · no. 661'],
 'loc': '📍 Around the hamlet of Meddo, north of Winterswijk · freely accessible over roads and paths; the Het Meddose Veld route starts at TOP Sevink Mölle (Meddoseweg 40)',
 'desc': 'The <b>Meddoscheveld</b> — also called the <b>Meddose Veld</b> — is the open field and reclamation landscape around the hamlet of <b>Meddo</b>, north of Winterswijk. Until the nineteenth century one of the largest heath fields of the Achterhoek lay here: more than <b>1,500 hectares of rough heath</b>, used in common by the marke of Meddo and surrounding hamlets. In the early twentieth century the field was reclaimed on a large scale: the heath made way for arable fields, pastures, reclamation woods and straight roads with ditches, while old field names such as Masterveld and Bonkeveen recall the heath era. Today the Meddoscheveld is an open, quiet small-scale landscape with scattered copses (including the Armenbos and the Bos te Meddo), hedgerows and brook-valley grasslands along the Groenlose Slinge and the Beurzerbeek; it can be freely explored via roads and paths. The marked walking route <b>Het Meddose Veld</b> of about 10.4 kilometres starts at TOP Sevink Mölle on the Meddoseweg and leads through the countryside, past the hamlet, the brooks and the old reclamation ribbons; start point De Eendracht on the Geldereschweg also serves the surroundings.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds), May–Jun (blooming verges), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — birdsong above the open field.',
 'why': ['The story of <b>1,500 hectares of heath</b> that made way for reclamation.', 'The <b>Het Meddose Veld</b> walking route (about 10.4 kilometres).', 'The <b>open, quiet small-scale landscape</b> with brooks and copses.', 'The old field names such as <b>Masterveld and Bonkeveen</b>.'],
 'phen': ['<span class="months">Mar–May</span> 🎵 <b>Displaying meadow birds</b>: lapwing, black-tailed godwit and curlew.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along the reclamation roads.', '<span class="months">Jun–Jul</span> 🌾 <b>Hay and grain time</b> on the former field.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> over the open land.'],
 'wild': ['🐦 Lapwing · Black-tailed godwit · Curlew · Skylark', '🦌 Roe deer · Hare', '🦊 Fox', '🦋 Small heath · Speckled wood', '🌾 Reclaimed land · Hedgerows · Brook-valley grassland'],
 'trail': ['Walk <b>Het Meddose Veld</b> (about 10.4 km) from TOP Sevink Mölle.', 'Also possible to start at <b>De Eendracht</b> on the Geldereschweg.', 'Combine with the <b>Armenbos, Bos te Meddo</b> or the Beurzerbeek.'],
 'foot': '🐕 Dogs on lead (meadow birds!) · 💶 Free · ⚠️ Open terrain: little shelter · 🚶 Roads, sandy tracks and route junctions'
}))

C.append(mk.card(1943, 'Beurzerbeek', {
 'tags': ['Gelderland · Winterswijk-Meddo', 'Beekdal van circa 19 hectare rond de Beurzerbeek, bovenloop van de Groenlose Slinge · in 1998–1999 heringericht met bypass en oude beekarmen · deel van Nationaal Landschap Winterswijk', 'list 36 · no. 662'],
 'loc': '📍 Ten noordoosten van Winterswijk en ten zuiden van Meddo, langs de Goorweg · vrij toegankelijk langs de beek; wandelingen starten bij de schuilhut bij de brug over de Slinge',
 'desc': 'De <b>Beurzerbeek</b> is een beek die net over de Duitse grens ten noordoosten van <b>Winterswijk</b> ontspringt en ten zuiden van <b>Meddo</b> uitmondt in de Groenlose Slinge; rond de beek en de aangrenzende gras- en bouwlanden ligt het gelijknamige <b>natuurgebied van circa 19 hectare</b>, sinds 1992 beschermd en een van de deelgebieden van het <b>Nationaal Landschap Winterswijk</b>. Het beekdal werd in 1998–1999 in het kader van de ecologische verbindingszone heringericht: oude beekarmen werden aan elkaar gekoppeld via een bypass, waardoor er meer ruimte kwam voor natuurontwikkeling en schoner, rustiger stromend water. De boeren in het dal werken biologisch met graan, hakvruchten en groenbemesters, wat de diversiteit aan planten en dieren ten goede komt. In en rond de beek leven onder meer <b>ijsvogel, dodaars, aalscholver en geelgors</b>, en ook de <b>rosse vleermuis</b> is in het gebied waargenomen; de herstelde beek maakt deel uit van een corridor voor onder andere de kamsalamander. Wie het gebied wil zien, wandelt langs de beek vanaf de schuilhut bij de brug aan de Goorweg te Meddo of volgt de streekroutes over de omliggende wegen en paden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en beekdalflora), okt–mrt (wintergasten als aalscholver en dodaars)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de beekarmen.',
 'why': ['De <b>herboren bovenloop</b> van de Groenlose Slinge met oude beekarmen.', 'De <b>biologische landbouw</b> langs het beekdal.', 'Vogels als <b>ijsvogel, dodaars en geelgors</b> en de rosse vleermuis.', 'De ligging in het <b>Nationaal Landschap Winterswijk</b>.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌿 <b>Beekdalflora</b> langs de nieuwe beekarmen.', '<span class="months">Apr–Aug</span> 🐦 <b>IJsvogel</b> boven het heldere water.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b>: dodaars en aalscholver.', '<span class="months">Aug–Sep</span> 🦗 <b>Sprinkhanen</b> in de akkerranden.'],
 'wild': ['🐦 IJsvogel · Dodaars · Aalscholver · Geelgors', '🦇 Rosse vleermuis', '🐸 Kamsalamander (doelsoort verbindingszone)', '🌿 Beekdalflora · Moerasplanten', '🌊 Herstelde beekloop · Bypass (1998–1999)'],
 'trail': ['Wandel vanaf de <b>schuilhut bij de brug aan de Goorweg</b> langs de beek.', 'Volg de streekroutes over de wegen en paden van het beekdal.', 'Combineer met <b>Meddo, de Beurzerbeek-fietsroute</b> of het Meddose Veld.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; beekoevers deels drassig · 🚶 Paden langs de beek, wegen en landbouwwegen'
}, {
 'tags': ['Gelderland · Winterswijk-Meddo', 'Brook valley of about 19 hectares around the Beurzerbeek, upper course of the Groenlose Slinge · restored in 1998–1999 with a bypass and old brook arms · part of Nationaal Landschap Winterswijk', 'list 36 · no. 662'],
 'loc': '📍 North-east of Winterswijk and south of Meddo, along the Goorweg · freely accessible along the brook; walks start at the shelter hut by the bridge over the Slinge',
 'desc': 'The <b>Beurzerbeek</b> is a brook that rises just across the German border north-east of <b>Winterswijk</b> and flows south of <b>Meddo</b> into the Groenlose Slinge; around the brook and the adjacent grassland and arable land lies the <b>nature area of about 19 hectares</b> of the same name, protected since 1992 and one of the sub-areas of the <b>Nationaal Landschap Winterswijk</b>. The brook valley was redesigned in 1998–1999 within the framework of the ecological corridor: old brook arms were connected by a bypass, creating more room for nature development and cleaner, more gently flowing water. The farmers in the valley work organically with grain, root crops and green manures, which benefits the diversity of plants and animals. In and around the brook live among others the <b>kingfisher, little grebe, cormorant and yellowhammer</b>, and the <b>greater noctule bat</b> has also been recorded in the area; the restored brook forms part of a corridor for species including the great crested newt. To see the area, walk along the brook from the shelter hut by the bridge on the Goorweg in Meddo or follow the regional routes over the surrounding roads and paths.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and brook-valley flora), Oct–Mar (winter visitors such as cormorant and little grebe)<br>\n    <b>Best time of day:</b> Morning — mist above the brook arms.',
 'why': ['The <b>reborn upper course</b> of the Groenlose Slinge with old brook arms.', 'The <b>organic farming</b> along the brook valley.', 'Birds such as <b>kingfisher, little grebe and yellowhammer</b> and the greater noctule bat.', 'Its position in the <b>Nationaal Landschap Winterswijk</b>.'],
 'phen': ['<span class="months">May–Jun</span> 🌿 <b>Brook-valley flora</b> along the new brook arms.', '<span class="months">Apr–Aug</span> 🐦 <b>Kingfisher</b> above the clear water.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b>: little grebe and cormorant.', '<span class="months">Aug–Sep</span> 🦗 <b>Grasshoppers</b> in the field margins.'],
 'wild': ['🐦 Kingfisher · Little grebe · Cormorant · Yellowhammer', '🦇 Greater noctule bat', '🐸 Great crested newt (target species of the corridor)', '🌿 Brook-valley flora · Marsh plants', '🌊 Restored brook course · Bypass (1998–1999)'],
 'trail': ['Walk from the <b>shelter hut by the bridge on the Goorweg</b> along the brook.', 'Follow the regional routes over the roads and paths of the valley.', 'Combine with <b>Meddo, the Beurzerbeek cycle route</b> or the Meddose Veld.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; brook banks partly marshy · 🚶 Paths along the brook, roads and farm lanes'
}))

C.append(mk.card(1944, 'Vragenderveld', {
 'tags': ['Gelderland · Vragender (Oost Gelre)', 'Open heide-ontginningslandschap rond het kerkdorp Vragender · wandelroute van 9,4 km langs het Vragenderveen met 15 meter hoge uitkijktoren', 'list 36 · no. 663'],
 'loc': '📍 Rond het kerkdorp Vragender (gemeente Oost Gelre), ten zuidwesten van de Groenlose Slinge · vrij toegankelijk; route start bij TOP Beneman aan de rand van het Korenburgerveen/Vragenderveen',
 'desc': 'Het <b>Vragenderveld</b> is het open veld rond het kerkdorp <b>Vragender</b>, tussen de spoorlijn Winterswijk–Zutphen en het beekdal van de Visserijbeek: een van de grootschalige, vochtige heide-ontginningen die ten zuidwesten van de Groenlose Slinge liggen en in de twintigste eeuw uit heide en veen tot akker- en weidegrond werden gemaakt. De naam leeft ook voort in de <b>wandelroute De Vragenderveld Wandeling</b> van circa 9,4 kilometer, die bij TOP Beneman start op de rand van het <b>Korenburgerveen en het Vragenderveen</b>, langs de spoorlijn door het buitengebied loopt en terugkeert via de kleine wegen van Vragender. Hoogtepunt onderweg is de <b>natuurobservatiepost Vragender</b>: een 15 meter hoge stalen uitkijktoren aan de rand van het Vragenderveen, vanwaar je over het levende hoogveen uitkijkt — het veen zelf mag alleen onder begeleiding van een gids worden betreden. Wie het landschap van dichtbij wil zien, volgt ’t Huttenpad door het elzenbroekbos met oude leemputten bij de Lankveldweg of wandelt langs de Visserijbeek, waar de Stichting Marke Vragender Veen vochtige beekdalgraslanden verschraalt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Okt</b>, mei–jun (vogelzang), jun–jul (bloeiende graslanden)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — mist boven het veen.',
 'why': ['De <b>uitkijktoren van 15 meter</b> over het levende hoogveen.', 'De <b>wandelroute van 9,4 kilometer</b> door het Vragenderveld.', 'Het verhaal van de <b>grootschalige heide-ontginningen</b>.', 'Het <b>elzenbroekbos ’t Huttenpad</b> met oude leemputten.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌫️ <b>Veenmist</b> boven het Vragenderveen.', '<span class="months">Apr–Jun</span> 🎵 <b>Vogelzang</b> in veld en broekbos.', '<span class="months">Mrt–Apr</span> 🌸 <b>Dotterbloem en speenkruid</b> in het elzenbroek.', '<span class="months">Jul–Sep</span> 🪰 <b>Libellen</b> boven veen en vennen.'],
 'wild': ['🐦 Boomleeuwerik · Geelgors · Graspieper', '🦌 Ree · Haas', '🦋 Oranjetipje · Hooibeestje', '🌿 Veenpluis · Zonnedauw (Vragenderveen)', '🌳 Elzenbroekbos · Oude leemputten'],
 'trail': ['Wandel de <b>Vragenderveld Wandeling</b> (circa 9,4 km) vanaf TOP Beneman.', 'Beklim de <b>uitkijktoren</b> bij het Vragenderveen.', 'Loop ’t <b>Huttenpad</b> door het elzenbroekbos of langs de Visserijbeek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Hoogveen alleen met gids; toren bij slecht weer gesloten · 🚶 Wegen, zandpaden en knooppunten'
}, {
 'tags': ['Gelderland · Vragender (Oost Gelre)', 'Open heath-reclamation landscape around the village of Vragender · 9.4 km walking route along the Vragenderveen with a 15-metre observation tower', 'list 36 · no. 663'],
 'loc': '📍 Around the village of Vragender (municipality of Oost Gelre), south-west of the Groenlose Slinge · freely accessible; the route starts at TOP Beneman on the edge of the Korenburgerveen/Vragenderveen',
 'desc': 'The <b>Vragenderveld</b> is the open field around the village of <b>Vragender</b>, between the Winterswijk–Zutphen railway line and the valley of the Visserijbeek: one of the large-scale, wet heath reclamations that lie south-west of the Groenlose Slinge and were turned from heath and peat into arable and pasture land in the twentieth century. The name also lives on in the <b>Vragenderveld walking route</b> of about 9.4 kilometres, which starts at TOP Beneman on the edge of the <b>Korenburgerveen and the Vragenderveen</b>, runs along the railway through the countryside and returns via the small roads of Vragender. The highlight along the way is the <b>Vragender nature observation post</b>: a 15-metre-high steel tower at the edge of the Vragenderveen, from which you look out over the living raised bog — the bog itself may only be entered under the guidance of a guide. To see the landscape up close, follow ’t Huttenpad through the alder fen wood with old clay pits near the Lankveldweg or walk along the Visserijbeek, where the Stichting Marke Vragender Veen is restoring wet valley grasslands by impoverishing the soil.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b>, May–Jun (birdsong), Jun–Jul (blooming grasslands)<br>\n    <b>Best time of day:</b> Early morning — mist above the bog.',
 'why': ['The <b>15-metre observation tower</b> over the living raised bog.', 'The <b>9.4-kilometre walking route</b> through the Vragenderveld.', 'The story of the <b>large-scale heath reclamations</b>.', 'The <b>’t Huttenpad alder fen wood</b> with old clay pits.'],
 'phen': ['<span class="months">May–Jun</span> 🌫️ <b>Bog mist</b> above the Vragenderveen.', '<span class="months">Apr–Jun</span> 🎵 <b>Birdsong</b> in field and fen wood.', '<span class="months">Mar–Apr</span> 🌸 <b>Marsh marigold and lesser celandine</b> in the alder fen.', '<span class="months">Jul–Sep</span> 🪰 <b>Dragonflies</b> above bog and fens.'],
 'wild': ['🐦 Woodlark · Yellowhammer · Meadow pipit', '🦌 Roe deer · Hare', '🦋 Orange tip · Small heath', '🌿 Cotton grass · Sundew (Vragenderveen)', '🌳 Alder fen wood · Old clay pits'],
 'trail': ['Walk the <b>Vragenderveld route</b> (about 9.4 km) from TOP Beneman.', 'Climb the <b>observation tower</b> at the Vragenderveen.', 'Follow ’t <b>Huttenpad</b> through the fen wood or along the Visserijbeek.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Raised bog only with a guide; tower closed in bad weather · 🚶 Roads, sandy tracks and junctions'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1944)
mk.check()
