# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2055, 'Hondswaard', {
 'tags': ['Zuid-Holland · Vuren (Vijfheerenlanden)', 'Waal-uiterwaard van Staatsbosbeheer bij Fort Vuren · runderen en bevers als landschapsvormers · vrij struinen toegestaan', 'list 36 · no. 774'],
 'loc': '📍 Aan de Waal bij Vuren, ten westen van de Biesbosch — overzien vanaf de Loevesteindijk/Waaldijk; Fort Vuren (torenfort uit 1845) aan de rand van het gebied',
 'desc': 'De <b>Hondswaard</b> is de <b>Waal-uiterwaard bij Vuren</b> — het westelijkste stukje Vijfheerenlanden, waar de rivier al richting Biesbosch stroomt en het <b>torenfort Vuren</b> (1845, met zijn contrescarp van 1878) vanaf de hoge oever de wacht houdt. <b>Staatsbosbeheer</b> beheert de waard als <b>halfnatuurlijke riviernatuur</b>: <b>runderen</b> grazen de graslanden en houden de wilgenopslag kort, en uit de Biesbosch zijn de <b>bevers</b> komen opgetrokken — hun vellen en vratplaatsen liggen langs de watergangen. Naast het natuurgebied ligt het <b>terrein van de oude steenfabriek</b>, waar de klei van de waard ooit tot stenen werd gebakken. Bijzonder aan de Hondswaard is de vrijheid die de beheerder geeft: in de Hondswaard (en in Passewaaij en Koornwaard) mag je <b>buiten de gebaande paden struinen</b> — door de ruigten, langs de wielen en de rivieroever. Dat de honden dan niet los mogen, nemen baasjes de beheerder soms kwalijk; maar de weidevogels en de rustzoekende zoogdieren van de waard hebben die regel nodig. Wie hier in de vroege ochtend loopt, hoort de Waal, de koeien en verder niets.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels, bloeiende uiterwaard), sep–mrt (winterganzen, hoogwater op de Waal)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — nevel boven de graslanden.',
 'why': ['De <b>vrijheid om te struinen</b>: buiten de paden door de uiterwaard zwerven.', '<b>Runderen en bevers</b> als makers van het landschap.', '<b>Fort Vuren</b> (1845) als middeleeuws aandoende waakhelder aan de Waal.', 'Het <b>steenfabriekterrein</b> als industriële herinnering aan de waard-klei.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogels</b> in de graslanden van de waard.', '<span class="months">Okt–Mrt</span> 🪿 <b>Winterganzen</b> op de overslikken.', '<span class="months">Nov–Feb</span> 🦫 <b>Bever-sporen</b> langs de watergangen.', '<span class="months">Heel jaar</span> 🏰 <b>Fort Vuren</b> aan de dijk.'],
 'wild': ['🐂 Runderen als begrazers', '🦫 Bevers vanuit de Biesbosch', '🐦 Weidevogels van de Waal-oever', '🌊 Wielen, ruigten en rivierklei', '🏰 Torenfort Vuren (1845)'],
 'trail': ['Struin de <b>Hondswaard</b> vanaf de dijk bij Vuren — buiten de paden mag het hier.', 'Bezoek <b>Fort Vuren</b> aan de Merwede-kant van het dorp.', 'Combineer met de <b>Avelingen</b> (kaart 2050) richting Gorinchem.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Vrij struinen toegestaan buiten de paden · ⚠️ Hoogwater kan delen afsluiten'
}, {
 'tags': ['Zuid-Holland · Vuren (Vijfheerenlanden)', 'Waal floodplain of Staatsbosbeheer at Fort Vuren · cattle and beavers as landscape shapers · free roaming allowed', 'list 36 · no. 774'],
 'loc': '📍 On the Waal near Vuren, west of the Biesbosch — surveyed from the Loevesteindijk/Waaldijk; Fort Vuren (tower fort of 1845) at the edge of the area',
 'desc': 'The <b>Hondswaard</b> is the <b>Waal floodplain at Vuren</b> — the westernmost bit of the Vijfheerenlanden, where the river already flows towards the Biesbosch and the <b>tower fort Vuren</b> (1845, with its 1878 counterscarp) keeps watch from the high bank. <b>Staatsbosbeheer</b> manages the waard as <b>semi-natural river nature</b>: <b>cattle</b> graze the grasslands and keep the willow scrub down, and the <b>beavers</b> have moved up from the Biesbosch — their lodges and gnawing places lie along the watercourses. Beside the reserve lies the <b>terrain of the old brickworks</b>, where the waard’s clay was once fired into bricks. What makes the Hondswaard special is the freedom the manager grants: in the Hondswaard (and in Passewaaij and Koornwaard) you may <b>roam off the beaten paths</b> — through the rough growth, past the scour holes and the river bank. That dogs must stay on a lead is sometimes held against the manager; but the meadow birds and the mammals seeking rest need that rule. Walk here in the early morning and you hear the Waal, the cattle, and nothing else.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds, flowering floodplain), Sep–Mar (winter geese, high water on the Waal)<br>\\n    <b>Best time of day:</b> Early morning — mist above the grasslands.',
 'why': ['The <b>freedom to roam</b>: off the paths through the floodplain.', '<b>Cattle and beavers</b> as makers of the landscape.', '<b>Fort Vuren</b> (1845) as a medieval-seeming watchman on the Waal.', 'The <b>brickworks terrain</b> as an industrial memory of the waard clay.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow birds</b> in the waard grasslands.', '<span class="months">Oct–Mar</span> 🪿 <b>Winter geese</b> on the mudflats.', '<span class="months">Nov–Feb</span> 🦫 <b>Beaver tracks</b> along the watercourses.', '<span class="months">All year</span> 🏰 <b>Fort Vuren</b> on the dike.'],
 'wild': ['🐂 Cattle as grazers', '🦫 Beavers from the Biesbosch', '🐦 Meadow birds of the Waal bank', '🌊 Scour holes, rough growth and river clay', '🏰 Tower fort Vuren (1845)'],
 'trail': ['Roam the <b>Hondswaard</b> from the dike at Vuren — off-path is allowed here.', 'Visit <b>Fort Vuren</b> on the Merwede side of the village.', 'Combine with the <b>Avelingen</b> (card 2050) towards Gorinchem.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Free roaming allowed off the paths · ⚠️ High water can close parts'
}))

C.append(mk.card(2056, 'Brakel', {
 'tags': ['Gelderland · Brakel (gemeente Zaltbommel, Land van Maas en Waal)', 'Boezem van Brakel en Brakelse Benedenwaarden · binnendijks moeras na vergraving · glanshaverhooilanden in de Waal-uiterwaard · Natura 2000 Loevestein', 'list 36 · no. 775'],
 'loc': '📍 Bezoekersparkeren aan de Waaldijk bij Brakel; vanaf de dijk overzien — de Boezem van Brakel ligt binnendijks ten oosten van het dorp, de Benedenwaarden buitendijks aan de Waal',
 'desc': 'Bij <b>Brakel</b> hoort een dubbeltje natuur: de <b>Brakelse Benedenwaarden</b> buitendijks aan de Waal — met een <b>geulenstelsel</b> waarvan de oostelijke geul enkele weken per jaar met de rivier meestroomt — en de <b>Boezem van Brakel</b>, een binnendijks <b>moerasgebied</b> dat na eerdere vergraving aan de natuur werd gelaten. De boezem is al decennia een geliefd studieobject: in de oude literatuur prijst men de <b>rietvelden, de schrale percelen met orchideeën en de waterdrieblad-slootjes</b>, die elk jaar opnieuw worden gemaaid om dichtgroeien tegen te gaan. In het noorden van de boezem staat het oude <b>Fort Brakel</b>. Samen vormen boezem en benedenwaarden het oostelijke deel van het Natura 2000-gebied <b>Loevestein, Pompveld &amp; Kornsche Boezem</b>: in de uiterwaard ligt een van de grootste <b>bloemrijke glanshaverhooilanden</b> van het gebied (H6510), die hier in juni geel en paars uitslaan; in de moerasruigten aan de voet van de dijk leeft de <b>kamsalamander</b>, in de geulen de <b>rivierdonderpad</b>. <b>Vanaf Brakel kan er vrijelijk langs de rivier gezworven worden</b> — de beheerder nodigde uit tot een wandeling langs hooiland, geul en boezem.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Jul</b> (glanshaverhooiland in bloei), apr–jun (kamsalamander, zang)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — dauw op de hooilanden van de Waal.',
 'why': ['De <b>Boezem van Brakel</b>: riet, orchideeën en waterdrieblad op oud vergraven terrein.', 'De <b>meestromende geul</b> in de Brakelse Benedenwaarden.', 'Eén van de grootste <b>glanshaverhooilanden</b> (H6510) van het N2000-gebied.', '<b>Kamsalamander en rivierdonderpad</b> als diersoorten van de deelgebieden.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Glanshaverhooiland</b> in volle bloei.', '<span class="months">Apr–Jun</span> 🦎 <b>Kamsalamander</b> in de moerasruigten.', '<span class="months">Mrt–Mei</span> 🌸 <b>Orchideeën</b> in de schrale boezem-percelen.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> op de geulen van de Waal.'],
 'wild': ['🌾 Glanshaverhooiland (H6510)', '🌸 Orchideeën · Waterdrieblad', '🦎 Kamsalamander · Rivierdonderpad', '🐟 Bittervoorn · Kleine modderkruiper', '🏰 Fort Brakel aan de noordrand'],
 'trail': ['Parkeer aan de <b>Waaldijk bij Brakel</b> en zwerver langs rivier en boezem.', 'Combineer met <b>Slot Loevestein</b> (kaart 2054) tien minuten stroomafwaarts.', 'Volg de dijk verder naar de <b>Waaluiterwaarden</b> van Polder Munnikenland.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Hooilanden niet betreden — paden en dijk volgen · 🚶 Knooppuntennetwerk Rivierenland'
}, {
 'tags': ['Gelderland · Brakel (Zaltbommel municipality, Land van Maas en Waal)', 'Boezem van Brakel and Brakel Benedenwaarden · inland marsh after excavation · soft-grass hay meadows on the Waal floodplain · Natura 2000 Loevestein', 'list 36 · no. 775'],
 'loc': '📍 Visitor parking on the Waaldijk at Brakel; survey from the dike — the Boezem van Brakel lies inland east of the village, the Benedenwaarden outside the dike on the Waal',
 'desc': 'At <b>Brakel</b> belongs a twin piece of nature: the <b>Brakel Benedenwaarden</b> outside the dike on the Waal — with a <b>channel system</b> whose eastern channel flows with the river for some weeks a year — and the <b>Boezem van Brakel</b>, an inland <b>marsh</b> left to nature after earlier excavation. The boezem has been a favourite study object for decades: the old literature praises its <b>reed fields, the nutrient-poor parcels with orchids and the water-violet ditches</b>, mown anew each year to keep the scrubbing out. On the boezem’s north side stands the old <b>Fort Brakel</b>. Together, boezem and benedenwaarden form the eastern part of the Natura 2000 site <b>Loevestein, Pompveld &amp; Kornsche Boezem</b>: on the floodplain lies one of the site’s largest <b>flower-rich soft-grass hay meadows</b> (H6510), bursting yellow and purple in June; in the marsh tall-herb at the foot of the dike lives the <b>warty newt</b>, in the channels the <b>spined loach</b>. <b>From Brakel you may freely roam along the river</b> — the manager invites you to walk past hay meadow, channel and boezem.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Jul</b> (soft-grass hay meadow in flower), Apr–Jun (warty newt, song)<br>\\n    <b>Best time of day:</b> Morning — dew on the Waal hay meadows.',
 'why': ['The <b>Boezem van Brakel</b>: reed, orchids and water violet on old excavated ground.', 'The <b>co-flowing channel</b> in the Brakel Benedenwaarden.', 'One of the largest <b>soft-grass hay meadows</b> (H6510) of the N2000 site.', '<b>Warty newt and spined loach</b> as animal species of the sub-areas.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Soft-grass hay meadow</b> in full flower.', '<span class="months">Apr–Jun</span> 🦎 <b>Warty newt</b> in the marsh tall-herb.', '<span class="months">Mar–May</span> 🌸 <b>Orchids</b> in the poor boezem parcels.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> on the Waal channels.'],
 'wild': ['🌾 Soft-grass hay meadow (H6510)', '🌸 Orchids · Water violet', '🦎 Warty newt · Spined loach', '🐟 Bitterling · Small weather loach', '🏰 Fort Brakel on the north edge'],
 'trail': ['Park on the <b>Waaldijk at Brakel</b> and roam along river and boezem.', 'Combine with <b>Loevestein Castle</b> (card 2054) ten minutes downstream.', 'Follow the dike on to the <b>Waal floodplains</b> of Polder Munnikenland.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Hay meadows not to be entered — follow paths and dike · 🚶 Rivierenland node network'
}, n2k='Loevestein, Pompveld &amp; Kornsche Boezem — Habitatrichtlijngebied nr. 71 (NL3004001, 2013): de Brakelse Benedenwaarden dragen vlakdekkend bloemrijk glanshaverhooiland (H6510) en zachthoutooibos (H91E0); de Boezem van Brakel is binnendijks moeras met kamsalamander, bittervoorn en kleine modderkruiper.',
 n2k_en='Loevestein, Pompveld &amp; Kornsche Boezem — Habitats Directive site no. 71 (NL3004001, 2013): the Brakel Benedenwaarden carry continuous flower-rich soft-grass hay meadow (H6510) and alluvial willow forest (H91E0); the Boezem van Brakel is inland marsh with warty newt, bitterling and small weather loach.'))

C.append(mk.card(2057, 'Waarden bij Gameren', {
 'tags': ['Gelderland · Gameren (gemeente Zaltbommel)', 'Gamerense Waard aan de Waal · drie meestromende nevengeulen uit de jaren negentig · levende rivierdynamiek op de grens van boven- en benedenrivier', 'list 36 · no. 776'],
 'loc': '📍 In de Waal-uiterwaard bij Gameren, tussen Zaltbommel en Brakel · overzien vanaf de Gamerense Waaldijk; wandelen over de uiterwaardspaden (bij hoogwater deels onbegaanbaar)',
 'desc': 'De <b>Gamerense Waard</b> is een schoolvoorbeeld van <b>levende rivierdynamiek</b>. Hier, op het beginpunt van de overgang van de slingerende <b>bovenrivier</b> naar de brede, rechte <b>beneden-Waal</b>, werden in de jaren negentig <b>drie nevengeulen</b> gegraven — twee die alleen bij hoog water meedoen, en één die <b>permanent meestroomt</b> met de rivier. Alleen bij Beneden-Leeuwen, Opijnen en Gameren bestaat zo’n echt meestromend systeem langs de Waal. Onderzoek van Wageningen Universiteit wees uit dat zich in de geulen binnen enkele jaren een <b>macrofauna-gemeenschap</b> vestigde die in de gebande rivier zelf ontbreekt: <b>kriebelmuggen</b> op de stenen, <b>libellenlarven</b> tussen de waterplanten, schrapers en vergaarders in het zwakstromende water — een compleet nieuw voedselweb, gevoed door de stroom. Om de geulen heen liggen uiterwaardgraslanden, wilgenopslag en kleiputten; bij laag water vallen de zandplaten droog waarvoor het wijde vlak van de rivier beroemd is. Vanaf de <b>Gamerense Waaldijk</b> is het hele schouwspel te volgen: een rivier die hier weer een stukje van zijn oude vrijheid terugkreeg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (waterplanten in de geulen, libellen), nov–mrt (hoogwater-schouwspel)<br>\\n    <b>Beste tijd van de dag:</b> Middag — zon op de stromende geulen.',
 'why': ['De <b>drie nevengeulen</b>, waarvan één permanent meestromend.', 'Eén van de <b>drie echte nevengeul-systemen</b> langs de Waal.', 'De <b>nieuwe onderwaterwereld</b>: kriebelmuggen en libellenlarven op de stenen.', 'De ligging op de <b>grens van boven- en benedenrivier</b>.'],
 'phen': ['<span class="months">Mei–Sep</span> 🌿 <b>Waterplanten</b> in de zwakstromende geulen.', '<span class="months">Jun–Aug</span> 🪰 <b>Libellen</b> boven de nevengeulen.', '<span class="months">Nov–Mrt</span> 🌊 <b>Hoogwater</b> — de geulen stromen vol met de rivier.', '<span class="months">Jul–Sep</span> 🏖️ <b>Zandplaten</b> bij laag water.'],
 'wild': ['🌊 Drie nevengeulen (1 permanent meestromend)', '🪰 Kriebelmuggen · Libellenlarven · Macrofauna', '🌿 Uiterwaardgraslanden en wilgenopslag', '🦆 Watervogels op de kleiputten', '🐟 Jonge vis in de stromende geulen'],
 'trail': ['Wandel de <b>Gamerense Waaldijk</b> met uitzicht over de geulen.', 'Volg de <b>uiterwaardspaden</b> tussen dijk en rivier (bij hoogwater onbegaanbaar).', 'Combineer met <b>Brakel</b> (kaart 2056) en de Waalkaden richting Zaltbommel.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Padvoering wisselt met de waterstand — laarzen aanbevolen · 🚶 Knooppuntennetwerk Rivierenland'
}, {
 'tags': ['Gelderland · Gameren (Zaltbommel municipality)', 'Gamerense Waard on the Waal · three co-flowing side channels from the nineties · living river dynamics at the border of upper and lower river', 'list 36 · no. 776'],
 'loc': '📍 In the Waal floodplain at Gameren, between Zaltbommel and Brakel · surveyed from the Gamerense Waaldijk; walk on the floodplain paths (partly impassable at high water)',
 'desc': 'The <b>Gamerense Waard</b> is a textbook example of <b>living river dynamics</b>. Here, at the starting point of the transition from the meandering <b>upper river</b> to the broad, straight <b>lower Waal</b>, <b>three side channels</b> were dug in the nineties — two that only join at high water, and one that <b>flows with the river permanently</b>. Only at Beneden-Leeuwen, Opijnen and Gameren does such a truly co-flowing system exist along the Waal. Research by Wageningen University showed that within a few years a <b>macroinvertebrate community</b> settled in the channels that is missing from the trained river itself: <b>blackflies</b> on the stones, <b>dragonfly larvae</b> among the water plants, grazers and gatherers in the slow-flowing water — a complete new food web, fed by the current. Around the channels lie floodplain grasslands, willow scrub and clay pits; at low water the sand banks fall dry for which the river’s open expanse is famous. From the <b>Gamerense Waaldijk</b> the whole spectacle can be followed: a river that won back a piece of its old freedom here.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (water plants in the channels, dragonflies), Nov–Mar (high-water spectacle)<br>\\n    <b>Best time of day:</b> Midday — sun on the flowing channels.',
 'why': ['The <b>three side channels</b>, one of them permanently co-flowing.', 'One of the <b>three true side-channel systems</b> along the Waal.', 'The <b>new underwater world</b>: blackflies and dragonfly larvae on the stones.', 'The position on the <b>border of upper and lower river</b>.'],
 'phen': ['<span class="months">May–Sep</span> 🌿 <b>Water plants</b> in the slow-flowing channels.', '<span class="months">Jun–Aug</span> 🪰 <b>Dragonflies</b> above the side channels.', '<span class="months">Nov–Mar</span> 🌊 <b>High water</b> — the channels fill with the river.', '<span class="months">Jul–Sep</span> 🏖️ <b>Sand banks</b> at low water.'],
 'wild': ['🌊 Three side channels (1 permanently co-flowing)', '🪰 Blackflies · Dragonfly larvae · Macroinvertebrates', '🌿 Floodplain grasslands and willow scrub', '🦆 Waterfowl on the clay pits', '🐟 Young fish in the flowing channels'],
 'trail': ['Walk the <b>Gamerense Waaldijk</b> with views over the channels.', 'Follow the <b>floodplain paths</b> between dike and river (impassable at high water).', 'Combine with <b>Brakel</b> (card 2056) and the Waal banks towards Zaltbommel.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Path conditions vary with the water level — boots recommended · 🚶 Rivierenland node network'
}))

C.append(mk.card(2058, 'Waarden van Poederoijen', {
 'tags': ['Gelderland · Poederoijen (gemeente Zaltbommel)', 'Waal- en Afgedamde Maas-uiterwaarden rond Slot Loevestein · kleiwinningsplassen van de buitenpolder · wielen en uiterwaardhooilanden · Natura 2000 Loevestein', 'list 36 · no. 777'],
 'loc': '📍 Rond Slot Loevestein en het dorp Poederoijen · wandelen via de Schouwendijk en de uiterwaardspaden; parkeerplaats bij het slot (Loevestein 1)',
 'desc': 'De <b>Waarden van Poederoijen</b> zijn de uiterwaarden waarin <b>Slot Loevestein</b> zijn grachten trekt: het waterland van <b>Waal en Afgedamde Maas</b> rondom het slot en het dorp. Buitendijks liggen de <b>hooilanden en rietkragen</b> van de Waal-oever, gevoed door de natuurlijke overstromingen van de rivier; ten zuidoosten van het fort ligt de oude <b>buitenpolder ‘Waarden bij Loevenstein’</b>, waar door eeuwen van <b>kleiwinning</b> een groot aantal plassen is ontstaan — nu een paradijs voor watervogels. Ten noordwesten van het dorp liggen de <b>wielen</b> die dijkdoorbraken hier achterlieten. In het kader van <b>Ruimte voor de Rivier</b> (project Munnikenland) is de uiterwaard heringericht: oevers afgegraven, nevengeulen gegraven en de natuurlijke dynamiek versterkt — de Waal kreeg hier letterlijk meer ruimte terug. Samen met de Brakelse waarden vormt dit de westelijke helft van het Natura 2000-gebied rond Loevestein: <b>bloemrijk glanshaverhooiland</b> op de hogere gronden, zachthoutooibos in de laagtes, en in de plassen en kreken de <b>grote modderkruiper</b> als kernsoort. Wie over de <b>Schouwendijk</b> naar het slot loopt, ziet de wielen, de plassen en de rivier om beurten opdoemen — vier eeuwen vesting en één doorlopende rivertuin.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Jul</b> (hooilandbloei), nov–mrt (watervogels op de kleiplassen, hoogwater)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de plassen bij het slot.',
 'why': ['De <b>kleiwinningsplassen</b> van de buitenpolder ‘Waarden bij Loevenstein’.', 'De <b>wielen</b> bij Poederoijen als littekens van dijkdoorbraken.', 'De <b>Ruimte voor de Rivier-herinrichting</b> van Polder Munnikenland.', '<b>Slot Loevestein</b> als middelpunt van de uiterwaardentuin.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Glanshaverhooiland</b> in bloei.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> op de kleiplassen.', '<span class="months">Nov–Feb</span> 🌊 <b>Hoogwater</b> op de Waal-uiterwaarden.', '<span class="months">Heel jaar</span> 🏰 <b>Het slot</b> boven de rietkragen.'],
 'wild': ['🌊 Waal- en Afgedamde Maas-uiterwaarden', '💧 Kleiwinningsplassen en wielen', '🌾 Glanshaverhooiland · Zachthoutooibos', '🐟 Grote modderkruiper in plassen en kreken', '🏰 Slot Loevestein als baken'],
 'trail': ['Parkeer bij <b>Slot Loevestein</b> (Loevestein 1) en loop de <b>Schouwendijk</b> langs de wielen.', 'Volg de <b>uiterwaardspaden</b> van Polder Munnikenland langs Waal en Afgedamde Maas.', 'Combineer met <b>Brakel</b> (kaart 2056) over de Waaldijk.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (slot betaald) · ⚠️ Paden kunnen bij hoogwater onderlopen · 🚶 Knooppuntennetwerk Rivierenland'
}, {
 'tags': ['Gelderland · Poederoijen (Zaltbommel municipality)', 'Waal and Afgedamde Maas floodplains around Loevestein Castle · clay-pit lakes of the outer polder · scour holes and floodplain hay meadows · Natura 2000 Loevestein', 'list 36 · no. 777'],
 'loc': '📍 Around Loevestein Castle and the village of Poederoijen · walk via the Schouwendijk and the floodplain paths; car park at the castle (Loevestein 1)',
 'desc': 'The <b>Waarden van Poederoijen</b> are the floodplains in which <b>Loevestein Castle</b> draws its moats: the water land of <b>Waal and Afgedamde Maas</b> around castle and village. Outside the dike lie the <b>hay meadows and reed fringes</b> of the Waal bank, fed by the river’s natural floods; southeast of the fort lies the old <b>outer polder ‘Waarden bij Loevenstein’</b>, where centuries of <b>clay digging</b> created a great number of lakes — now a paradise for waterfowl. Northwest of the village lie the <b>scour holes</b> left by dike breaches. Under <b>Room for the River</b> (project Munnikenland) the floodplain was redesigned: banks excavated, side channels dug and the natural dynamics strengthened — the Waal literally won back room here. Together with the Brakel waarden this forms the western half of the Natura 2000 site around Loevestein: <b>flower-rich soft-grass hay meadow</b> on the higher grounds, alluvial willow forest in the lows, and in lakes and creeks the <b>large weather loach</b> as core species. Walk the <b>Schouwendijk</b> towards the castle and the scour holes, lakes and river surface in turn — four centuries of fortress and one continuous river garden.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Jul</b> (hay meadow in flower), Nov–Mar (waterfowl on the clay lakes, high water)<br>\\n    <b>Best time of day:</b> Morning — mist above the lakes by the castle.',
 'why': ['The <b>clay-pit lakes</b> of the ‘Waarden bij Loevenstein’ outer polder.', 'The <b>scour holes</b> at Poederoijen as scars of dike breaches.', 'The <b>Room for the River redesign</b> of Polder Munnikenland.', '<b>Loevestein Castle</b> as the heart of the floodplain garden.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Soft-grass hay meadow</b> in flower.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> on the clay lakes.', '<span class="months">Nov–Feb</span> 🌊 <b>High water</b> on the Waal floodplains.', '<span class="months">All year</span> 🏰 <b>The castle</b> above the reed fringes.'],
 'wild': ['🌊 Waal and Afgedamde Maas floodplains', '💧 Clay-pit lakes and scour holes', '🌾 Soft-grass hay meadow · Alluvial willow forest', '🐟 Large weather loach in lakes and creeks', '🏰 Loevestein Castle as beacon'],
 'trail': ['Park at <b>Loevestein Castle</b> (Loevestein 1) and walk the <b>Schouwendijk</b> past the scour holes.', 'Follow the <b>floodplain paths</b> of Polder Munnikenland along Waal and Afgedamde Maas.', 'Combine with <b>Brakel</b> (card 2056) along the Waaldijk.'],
 'foot': '🐕 Dogs on lead · 💶 Free (castle paid) · ⚠️ Paths can flood at high water · 🚶 Rivierenland node network'
}, n2k='Loevestein, Pompveld &amp; Kornsche Boezem — Habitatrichtlijngebied nr. 71 (NL3004001, 2013): de uiterwaarden rond het slot dragen glanshaverhooiland (H6510) en zachthoutooibos (H91E0); de plassen van de buitenpolder zijn leefgebied van grote en kleine modderkruiper, bittervoorn en kamsalamander.',
 n2k_en='Loevestein, Pompveld &amp; Kornsche Boezem — Habitats Directive site no. 71 (NL3004001, 2013): the floodplains around the castle carry soft-grass hay meadow (H6510) and alluvial willow forest (H91E0); the outer-polder lakes are habitat of large and small weather loach, bitterling and warty newt.'))

C.append(mk.card(2059, 'Fort Giessen', {
 'tags': ['Noord-Brabant · Giessen (gemeente Altena)', 'Vestingfort uit 1879 aan de Nieuwe Hollandse Waterlinie · vleermuisfort met vijf soorten · Eerste-Wereldoorlogspark met loopgraaf', 'list 36 · no. 778'],
 'loc': '📍 Giessensesteeg 2, Giessen (4283 HP) · wandeling rond het fort (buiten de gracht) altijd mogelijk; fort zelf mei–augustus op bepaalde dagen open (check kalender), sep–apr gesloten voor de vleermuizen',
 'desc': '<b>Fort Giessen</b> (1879) is het zuidelijke sluitstuk van de <b>Nieuwe Hollandse Waterlinie</b> aan de Altenase kant: een bomvrij vestingfort te midden van wilgen- en grasland, gebouwd om de vijand via het geïnundeerde land tegen te houden. Na de reorganisatie van 1922 lag het fort <b>geïsoleerd vóór de linie</b> — ongeschikt als verdedigingswerk, te duur om af te breken — en zo werd het eerst pakhuis voor politie, leger en douane en na 1951 <b>munitieopslag</b>. Precies die rust maakte het fort tot wat het nu is: een <b>vleermuisfort</b>. In de vorstvrije, vochtige gangen overwinteren <b>baardvleermuis, bruine grootoor, gewone dwergvleermuis, meervleermuis en watervleermuis</b> — de watervleermuis talrijkst, de vleermuiswerkgroep Noord-Brabant telt ze elk jaar. Bij de <b>renovatie van 2016</b> is speciaal op hun winterhuisvesting gelet: constante luchtvochtigheid, betere invliegopeningen. Rond het fort groeide een nieuw verhaal: een <b>educatiepark Eerste Wereldoorlog</b> met <b>loopgraaf</b> en expositieruimte — Giessen lag tijdens de Grote Oorlog immers pal aan de Hollandse verdedigingslinie. In de vogelbosjes op het terrein broeden <b>boomkruiper, fitis en zwartkop</b>, boven de gracht jaagt de <b>ijsvogel</b>. Wie het fort rondloopt — de wandeling buiten de fortgracht is altijd open — voelt de stilte van honderd jaar opslag.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Aug</b> (fort open, vleermuizenverblijf te zien), apr &amp; okt (najaars- en voorjaarstrek rondom)<br>\\n    <b>Beste tijd van de dag:</b> Schemering — vleermuizen boven de gracht.',
 'why': ['De <b>vijf vleermuissoorten</b> in de vorstvrije gangen van het fort.', 'De <b>renovatie van 2016</b> met vleermuisvriendelijke maatregelen.', 'Het <b>WWI-educatiepark</b> met loopgraaf en expositie.', 'De <b>geïsoleerde ligging voor de linie</b> — een fort dat overleefde omdat het te duur was om af te breken.'],
 'phen': ['<span class="months">Mei–Aug</span> 🦇 <b>Vleermuizen-verblijf</b> te bezichtigen op open dagen.', '<span class="months">Sep–Apr</span> 🔒 <b>Winterrust</b> — fort gesloten, rondwandeling blijft open.', '<span class="months">Apr–Jun</span> 🎵 <b>Boomkruiper en fitis</b> in de fortbosjes.', '<span class="months">Heel jaar</b> 🪶 <b>IJsvogel</b> boven de fortgracht.'],
 'wild': ['🦇 Watervleermuis · Baardvleermuis · Bruine grootoor · Gewone dwergvleermuis · Meervleermuis', '🐦 Boomkruiper · Fitis · Zwartkop', '🪶 IJsvogel boven de gracht', '🏰 Fort uit 1879 met bomvrije gangen', '🕊️ WWI-loopgraaf en expositie'],
 'trail': ['Wandel de <b>rondweg om het fort</b> (buiten de gracht, altijd open).', 'Bezoek het fort op een <b>opendag in de zomer</b> voor gangen en vleermuizenverblijf.', 'Combineer met de <b>Hollandsche Waterlinie-route</b> langs Fort Vuren en Slot Loevestein.'],
 'foot': '🐕 Honden aangelijnd · 💶 Buiten gratis, fort betaald op open dagen · 🔒 Sep–apr gesloten (vleermuizen) · 🚶 Rondwandeling ± 1 km'
}, {
 'tags': ['North Brabant · Giessen (Altena municipality)', 'Fortress of 1879 on the New Dutch Waterline · bat fort with five species · First World War park with trench', 'list 36 · no. 778'],
 'loc': '📍 Giessensesteeg 2, Giessen (4283 HP) · walk around the fort (outside the moat) always possible; the fort itself open on certain days May–August (check calendar), closed Sep–Apr for the bats',
 'desc': '<b>Fort Giessen</b> (1879) is the southern capstone of the <b>New Dutch Waterline</b> on the Altena side: a bomb-proof fortress amid willow and grassland, built to stop the enemy across the flooded land. After the 1922 reorganisation the fort lay <b>isolated in front of the line</b> — unsuited as a defence work, too expensive to demolish — and so it became first a warehouse for police, army and customs, and after 1951 a <b>munitions store</b>. Precisely that quiet made the fort what it is now: a <b>bat fort</b>. In the frost-free, humid galleries winter the <b>Whiskered bat, brown long-eared bat, common pipistrelle, Natterer’s bat and Daubenton’s bat</b> — Daubenton’s most numerous, counted yearly by the North Brabant bat working group. The <b>2016 renovation</b> paid special attention to their winter quarters: constant humidity, better flight openings. Around the fort a new story grew: a <b>First World War education park</b> with a <b>trench</b> and exhibition space — during the Great War Giessen lay right on the Dutch defence line. In the little woods on the terrain <b>treecreeper, willow warbler and blackcap</b> breed, above the moat the <b>kingfisher</b> hunts. Walk around the fort — the route outside the moat is always open — and feel the silence of a hundred years of storage.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Aug</b> (fort open, bat quarters visible), Apr &amp; Oct (migration around the fort)<br>\\n    <b>Best time of day:</b> Dusk — bats above the moat.',
 'why': ['The <b>five bat species</b> in the frost-free galleries.', 'The <b>2016 renovation</b> with bat-friendly measures.', 'The <b>WWI education park</b> with trench and exhibition.', 'The <b>isolated position before the line</b> — a fort that survived because demolishing it cost too much.'],
 'phen': ['<span class="months">May–Aug</span> 🦇 <b>Bat quarters</b> visible on open days.', '<span class="months">Sep–Apr</span> 🔒 <b>Winter rest</b> — fort closed, walk stays open.', '<span class="months">Apr–Jun</span> 🎵 <b>Treecreeper and willow warbler</b> in the fort woods.', '<span class="months">All year</span> 🪶 <b>Kingfisher</b> above the fort moat.'],
 'wild': ['🦇 Daubenton’s · Whiskered · Brown long-eared · Common pipistrelle · Natterer’s bat', '🐦 Treecreeper · Willow warbler · Blackcap', '🪶 Kingfisher above the moat', '🏰 Fort of 1879 with bomb-proof galleries', '🕊️ WWI trench and exhibition'],
 'trail': ['Walk the <b>route around the fort</b> (outside the moat, always open).', 'Visit the fort on a <b>summer open day</b> for galleries and bat quarters.', 'Combine with the <b>Dutch Waterline route</b> past Fort Vuren and Loevestein Castle.'],
 'foot': '🐕 Dogs on lead · 💶 Outside free, fort paid on open days · 🔒 Closed Sep–Apr (bats) · 🚶 Loop walk ± 1 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2059)
mk.check()
