# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2005, 'Kwade Hoek', {
 'tags': ['Zuid-Holland · Goedereede (tussen havenhoofd en Stellendam)', 'Dynamisch getijdengebied van Natuurmonumenten · duin, slik, schor en riet · vogelkijkhut en nieuwe duinvorming', 'list 36 · no. 724'],
 'loc': '📍 Tussen Goedereede en de haven van Stellendam (Oostdijkseweg 100) · vrij toegankelijk; vogelkijkhut (2014); stranddeel deels afgesloten 1 apr–15 jul',
 'desc': 'De <b>Kwade Hoek</b> is een van de mooiste deltagebieden van Nederland: een uitgestrekt, ongerept duingebied tussen <b>Goedereede en de haven van Stellendam</b>, waar duinen, duinvalleien, slikken, schorren en rietgebieden elkaar afwisselen. Vroeger heette dit dynamische getijdengebied de “kwaaien hoek” om de verraderlijke stroming. Aan de noordoostkant liggen slikken, schorren en kreken met zoutminners als <b>lamsoor en echt lepelblad</b>; hier broeden <b>grutto, kluut en tureluur</b>. In de rietvegetatie klinkt ’s voorjaars een spectaculair vogelkoor met rietgors en karekieten, de <b>kramsvogel</b> pleistert op de besdragende struiken en aan de strandzijde vindt <b>nieuwe duinvorming</b> plaats. Natuurmonumenten laat het gebied in de zomer begrazen door koeien; ’s winters zitten er duizenden ganzen. Voor de kust zwemmen <b>bruinvissen en zeehonden</b>, in de duinen lopen reeën. Start bij Oostdijkseweg of Stellendamse haven — en werp altijd een blik op de haven, met zijn zeevogels.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelkoor en broedvogels), aug–okt (trek en zeehonden)<br>\\n    <b>Beste tijd van de dag:</b> Zonsopgang — vogelkoor; laag water voor slikken en zandplaten.',
 'why': ['Het <b>dynamische deltagebied</b>: van kwaaien hoek tot vogelparadijs.', 'De <b>vogelkijkhut</b> met uitzicht over de uitgestrekte duinvallei.', 'De <b>broedvogels van slik en schor</b>: kluut, tureluur en grutto.', 'De <b>zeehonden en bruinvissen</b> voor de kust.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Spectaculair vogelkoor</b> bij zonsopgang in het riet.', '<span class="months">Mei–Aug</span> 🐄 <b>Begrazing door koeien</b> in het duingebied.', '<span class="months">Aug–Okt</span> 🦭 <b>Zeehonden</b> op de zandplaten bij laag water.', '<span class="months">Okt–Mrt</span> 🪿 <b>Duizenden ganzen</b> in het wintergebied.'],
 'wild': ['🐦 Kluut · Tureluur · Grutto · Kramsvogel', '🌸 Lamsoor · Echt lepelblad · Zeekraal', '🦭 Zeehond · Bruinvis voor de kust', '🦌 Reeën van de duinen', '🔭 Vogelkijkhut (2014) in het duin'],
 'trail': ['Start bij <b>Oostdijkseweg 100</b> of de <b>Buitenhaven van Stellendam</b> en wandel naar de hut.', 'Loop het tweede deel van de <b>Koploper</b> door de Kwade Hoek.', 'Combineer met de <b>haven van Stellendam</b> (zeevogels) en Goedereede.'],
 'foot': '🐕 Honden aangelijnd (niet overal welkom — let op borden) · 💶 Gratis · ⚠️ Stranddeel afgesloten 1 apr–15 jul; laarzen aan · 🚶 Beperkte parkeerplaats; ook starten vanaf Vrijheidsweg of haven'
}, {
 'tags': ['Zuid-Holland · Goedereede (between Havenhoofd and Stellendam)', 'Dynamic tidal area of Natuurmonumenten · dunes, mudflats, salt marsh and reeds · bird hide and new dune formation', 'list 36 · no. 724'],
 'loc': '📍 Between Goedereede and the harbour of Stellendam (Oostdijkseweg 100) · freely accessible; bird hide (2014); beach section partly closed 1 Apr–15 Jul',
 'desc': 'The <b>Kwade Hoek</b> is one of the most beautiful delta areas of the Netherlands: a vast, pristine dune area between <b>Goedereede and the harbour of Stellendam</b>, where dunes, dune valleys, mudflats, salt marshes and reed beds alternate. This dynamic tidal area used to be called the “kwaaien hoek” (nasty corner) for its treacherous current. On the northeastern side lie mudflats, salt marshes and creeks with salt-lovers such as <b>sea lavender and true scurvygrass</b>; <b>godwit, avocet and redshank</b> breed here. In spring a spectacular dawn chorus sounds in the reed vegetation with buntings and warblers, the <b>fieldfare</b> stops over on the berry-bearing shrubs, and <b>new dune formation</b> takes place on the beach side. Natuurmonumenten has the area grazed by cows in summer; in winter thousands of geese sit here. <b>Porpoises and seals</b> swim off the coast, roe deer walk in the dunes. Start at Oostdijkseweg or Stellendam harbour — and always glance at the harbour, with its seabirds.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (dawn chorus and breeding birds), Aug–Oct (migration and seals)<br>\\n    <b>Best time of day:</b> Sunrise — dawn chorus; low water for mudflats and sandbanks.',
 'why': ['The <b>dynamic delta area</b>: from nasty corner to bird paradise.', 'The <b>bird hide</b> overlooking the vast dune valley.', 'The <b>breeding birds of mudflat and marsh</b>: avocet, redshank and godwit.', 'The <b>seals and porpoises</b> off the coast.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Spectacular dawn chorus</b> at sunrise in the reeds.', '<span class="months">May–Aug</span> 🐄 <b>Grazing by cows</b> in the dune area.', '<span class="months">Aug–Oct</span> 🦭 <b>Seals</b> on the sandbanks at low water.', '<span class="months">Oct–Mar</span> 🪿 <b>Thousands of geese</b> in the wintering area.'],
 'wild': ['🐦 Avocet · Redshank · Godwit · Fieldfare', '🌸 Sea lavender · True scurvygrass · Glasswort', '🦭 Seal · Porpoise off the coast', '🦌 Roe deer of the dunes', '🔭 Bird hide (2014) in the dunes'],
 'trail': ['Start at <b>Oostdijkseweg 100</b> or the <b>outer harbour of Stellendam</b> and walk to the hide.', 'Walk the second part of the <b>Koploper</b> through the Kwade Hoek.', 'Combine with the <b>harbour of Stellendam</b> (seabirds) and Goedereede.'],
 'foot': '🐕 Dogs on lead (not welcome everywhere — watch the signs) · 💶 Free · ⚠️ Beach section closed 1 Apr–15 Jul; wear boots · 🚶 Limited car park; also start from Vrijheidsweg or harbour'
}))

C.append(mk.card(2006, 'Kop van Goeree', {
 'tags': ['Zuid-Holland · Stellendam/Ouddorp (Haringvlietdam)', 'Duinpunt van Natuurmonumenten met ’t Kiekgat · riet- en moerasvogels aan het Zuiderdiep · vuurtoren Westhoofd om de hoek', 'list 36 · no. 725'],
 'loc': '📍 Op de kop van Goeree, bij Stellendam en de Haringvlietdam · vogelkijkhut ’t Kiekgat aan het Zuiderdiep; Koploper en Volgerland passeren de punt',
 'desc': 'De <b>Kop van Goeree</b> is de duinpunt van het eiland, waar Natuurmonumenten de natuur bewaakt tussen Noordzee, <b>Zuiderdiep</b> en Haringvlietdam. In de vogelkijkhut <b>’t Kiekgat</b> — op de scheiding van de voormalige eilandjes Goeree en Overflakkee — kijk je uit over riet en moeras vol riet- en watervogels, met tegenover de haven het fraaie Zuiderdiep. Wie de punt rondt, komt langs het purperrode rijksmonument <b>vuurtoren Westhoofd</b> (1950) met zijn drie schitteringen per kwartier, het in het duin opgenomen asfalt van <b>’t Flaauwe Werk</b> en de vogelrijke <b>Westhoofdvallei</b>, waar orchideeën bloeien tussen grazende koeien. De <b>Koploper</b> (11 km, blauw) voert door de uitgestrekte Duinen van Goeree naar de uitkijktoren en het strand met drieteenstrandlopertjes; het 5 kilometer lange <b>Volgerland</b> start bij de vuurtoren. Strand zonder tenten, maar met rust, natuur en vergezichten naar Schouwen-Duiveland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (rietvogels, orchideeën en strandlopers), sep–okt (trek)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over duin, vallei en Zuiderdiep.',
 'why': ['Vogelkijkhut <b>’t Kiekgat</b> op de naad van twee voormalige eilanden.', 'De <b>Westhoofdvallei</b>: orchideeën tussen de koeien.', 'De <b>vuurtoren Westhoofd</b>: purperrood baken uit 1950.', 'De <b>Koploper</b>: 11 kilometer duin, toren en strand.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Riet- en moerasvogels</b> bij ’t Kiekgat en Zuiderdiep.', '<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> in de Westhoofdvallei.', '<span class="months">Jun–Aug</span> 🐦 <b>Drieteenstrandlopertjes</b> langs de waterrand.', '<span class="months">Sep–Okt</span> 🦆 <b>Trekvogels</b> over punt en dam.'],
 'wild': ['🔭 ’t Kiekgat: riet- en moerasvogels', '🌸 Orchideeën van de Westhoofdvallei', '🗼 Vuurtoren Westhoofd (1950)', '🐦 Drieteenstrandloper · Strandvogels', '🌊 ’t Flaauwe Werk en vergezichten'],
 'trail': ['Kijk bij <b>’t Kiekgat</b> aan het Zuiderdiep (scheiding Goeree–Overflakkee).', 'Loop de <b>Koploper</b> (11 km, blauw) of het <b>Volgerland</b> (5 km) vanaf de vuurtoren.', 'Combineer met <b>Kwade Hoek</b>, Scheelhoek of de Brouwersdam.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op paden en strand; duin is kwetsbaar · 🚶 Knooppunten 13–25; parkeren bij vuurtoren en haven'
}, {
 'tags': ['Zuid-Holland · Stellendam/Ouddorp (Haringvlietdam)', 'Dune tip of Natuurmonumenten with ’t Kiekgat · reed and marsh birds on the Zuiderdiep · Westhoofd lighthouse around the corner', 'list 36 · no. 725'],
 'loc': '📍 On the tip of Goeree, near Stellendam and the Haringvlietdam · ’t Kiekgat bird hide on the Zuiderdiep; Koploper and Volgerland cross the tip',
 'desc': 'The <b>Kop van Goeree</b> is the dune tip of the island, where Natuurmonumenten guards nature between North Sea, <b>Zuiderdiep</b> and Haringvlietdam. In the <b>’t Kiekgat</b> bird hide — on the divide of the former islets of Goeree and Overflakkee — you look out over reeds and marsh full of reed and water birds, with the lovely Zuiderdiep opposite the harbour. Rounding the tip you pass the purple-red listed monument <b>Westhoofd lighthouse</b> (1950) with its three flashes per quarter hour, the asphalt of <b>’t Flaauwe Werk</b> absorbed into the dunes, and the bird-rich <b>Westhoofdvallei</b>, where orchids bloom among grazing cows. The <b>Koploper</b> (11 km, blue) runs through the vast Goeree Dunes to the lookout tower and the beach with sanderlings; the 5-kilometre <b>Volgerland</b> starts at the lighthouse. Beach without pavilions, but with peace, nature and views to Schouwen-Duiveland.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (reed birds, orchids and sandpipers), Sep–Oct (migration)<br>\\n    <b>Best time of day:</b> Morning — light over dunes, valley and Zuiderdiep.',
 'why': ['The <b>’t Kiekgat</b> bird hide on the seam of two former islets.', 'The <b>Westhoofdvallei</b>: orchids among the cows.', 'The <b>Westhoofd lighthouse</b>: purple-red beacon from 1950.', 'The <b>Koploper</b>: 11 kilometres of dunes, tower and beach.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Reed and marsh birds</b> at ’t Kiekgat and Zuiderdiep.', '<span class="months">May–Jun</span> 🌸 <b>Orchids</b> in the Westhoofdvallei.', '<span class="months">Jun–Aug</span> 🐦 <b>Sanderlings</b> along the waterline.', '<span class="months">Sep–Oct</span> 🦆 <b>Migrants</b> over tip and dam.'],
 'wild': ['🔭 ’t Kiekgat: reed and marsh birds', '🌸 Orchids of the Westhoofdvallei', '🗼 Westhoofd lighthouse (1950)', '🐦 Sanderling · Beach birds', '🌊 ’t Flaauwe Werk and far views'],
 'trail': ['Watch at <b>’t Kiekgat</b> on the Zuiderdiep (Goeree–Overflakkee divide).', 'Walk the <b>Koploper</b> (11 km, blue) or the <b>Volgerland</b> (5 km) from the lighthouse.', 'Combine with <b>Kwade Hoek</b>, Scheelhoek or the Brouwersdam.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on paths and beach; dunes are vulnerable · 🚶 Junctions 13–25; parking at lighthouse and harbour'
}))

C.append(mk.card(2007, 'Scheelhoek', {
 'tags': ['Zuid-Holland · Stellendam (Zuiderdiep–Haringvliet)', 'Vogelreservaat van 343 hectare · plaat met kreken, rietmoeras en Scheelhoekeilanden · observatorium TIJ als ei van de grote stern', 'list 36 · no. 726'],
 'loc': '📍 Aan de rand van Stellendam, tussen Zuiderdiep en Haringvliet · parkeerplaats Scheelhoekbos; TIJ via Deltahaven 69 (geen honden, niet rolstoeltoegankelijk)',
 'desc': 'De <b>Scheelhoek</b> (343 hectare) is het vogelreservaat aan de rand van <b>Stellendam</b>, tussen Zuiderdiep en Haringvliet — in beheer bij Natuurmonumenten. Rond <b>1870</b> ontstond hier een dynamisch zandplaatje in het Haringvliet, dat toen nog open met de Noordzee verbonden was; door het inpoten van <b>riet en biezen</b> werd het zand vastgelegd. Zo groeide de <b>Plaat van Scheelhoek</b> met kreken, riet- en graslanden, later aangevuld met het <b>Scheelhoekbos</b> (1974) op een werkeiland van de Haringvlietdam. Tot 2018 oogstten rietsnijders het moeras — het laatste riet is verwerkt in het naastgelegen <b>vogelobservatorium TIJ</b>, een 8 meter hoog ei van de grote stern met 360 graden uitzicht over Scheelhoekeilanden, waar grote stern, visdief, kluut en bontbekplevier broeden. Sinds de sluizen begin 2019 <b>op een kier</b> staan, keren trekvissen en riviernatuur terug; de <b>zeearend</b> brengt regelmatig bezoek. Twee gemarkeerde bosroutes (5 km geel en kort), uitkijkheuvel en ’t Kiekgat als uitstapje.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jul</b> (sterns, kluten en rietvogels; TIJ het hele jaar open)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over plaat en eilanden; avond voor de zeearend.',
 'why': ['Observatorium <b>TIJ</b>: een metershoog sterns-ei met rondom uitzicht.', 'De <b>Scheelhoekeilanden</b> met sterns, kluten en plevieren.', 'Het <b>rietmoeras</b>: van zandplaat (1870) via rietoogst tot reservaat.', 'De <b>kier in de sluizen</b>: terugkerende dynamiek sinds 2019.'],
 'phen': ['<span class="months">Apr–Jul</span> 🐦 <b>Sterns, kluten en plevieren</b> op de broedvogeleilandjes.', '<span class="months">Apr–Jun</span> 🎵 <b>Nachtegaal, specht en karekiet</b> in het Scheelhoekbos.', '<span class="months">Heel jaar</span> 🦅 <b>Zeearend</b> (“vliegende deur”) boven het Haringvliet.', '<span class="months">Sep–Mrt</span> 🦆 <b>Eenden, zilverreigers en lepelaars</b> op slikken en water.'],
 'wild': ['🥚 TIJ: ei-observatorium over het Haringvliet', '🐦 Grote stern · Visdief · Kluut · Bontbekplevier', '🎵 Nachtegaal · Bonte specht · Kleine karekiet', '🦅 Zeearend boven plaat en sluizen', '🌾 337 ha rietmoeras en Scheelhoekbos'],
 'trail': ['Loop de <b>gele Scheelhoekbos-route</b> (5 km) met uitkijkpunt over de plaat.', 'Bezoek <b>TIJ</b> via het pad met vlonders vanaf Deltahaven 69.', 'Maak het uitstapje naar <b>’t Kiekgat</b> aan de Noordzeezijde van de dam.'],
 'foot': '🐕 Honden aangelijnd op de paden (niet mee naar TIJ) · 💶 Gratis · ⚠️ Onverhard; controleer op teken; TIJ met trap · 🚶 Parkeerplaats Scheelhoekbos; groene route 3,7 km'
}, {
 'tags': ['Zuid-Holland · Stellendam (Zuiderdiep–Haringvliet)', '343-hectare bird reserve · island with creeks, reed marsh and Scheelhoek islets · TIJ observatory as a Sandwich tern egg', 'list 36 · no. 726'],
 'loc': '📍 At the edge of Stellendam, between Zuiderdiep and Haringvliet · Scheelhoekbos car park; TIJ via Deltahaven 69 (no dogs, not wheelchair accessible)',
 'desc': 'The <b>Scheelhoek</b> (343 hectares) is the bird reserve at the edge of <b>Stellendam</b>, between Zuiderdiep and Haringvliet — managed by Natuurmonumenten. Around <b>1870</b> a dynamic sandbank arose here in the Haringvliet, then still openly connected to the North Sea; by planting <b>reeds and club-rush</b> the sand was fixed. Thus grew the <b>Plaat van Scheelhoek</b> with creeks, reed beds and grasslands, later complemented by the <b>Scheelhoekbos</b> (1974) on a work island of the Haringvlietdam. Until 2018 reed cutters harvested the marsh — the last reed was used in the adjacent <b>TIJ bird observatory</b>, an 8-metre-high Sandwich tern egg with 360-degree views over the Scheelhoek islets, where Sandwich terns, common terns, avocets and ringed plovers breed. Since the sluices were set <b>ajar</b> in early 2019, migratory fish and river nature are returning; the <b>white-tailed eagle</b> visits regularly. Two marked forest routes (5 km yellow and short), viewpoint hill and ’t Kiekgat as a detour.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jul</b> (terns, avocets and reed birds; TIJ open all year)<br>\\n    <b>Best time of day:</b> Morning — light over island and islets; evening for the eagle.',
 'why': ['The <b>TIJ</b> observatory: a metres-high tern egg with all-round views.', 'The <b>Scheelhoek islets</b> with terns, avocets and plovers.', 'The <b>reed marsh</b>: from sandbank (1870) via reed harvest to reserve.', 'The <b>ajar sluices</b>: returning dynamics since 2019.'],
 'phen': ['<span class="months">Apr–Jul</span> 🐦 <b>Terns, avocets and plovers</b> on the breeding islets.', '<span class="months">Apr–Jun</span> 🎵 <b>Nightingale, woodpecker and warbler</b> in the Scheelhoekbos.', '<span class="months">All year</span> 🦅 <b>White-tailed eagle</b> (“flying door”) above the Haringvliet.', '<span class="months">Sep–Mar</span> 🦆 <b>Ducks, egrets and spoonbills</b> on mudflats and water.'],
 'wild': ['🥚 TIJ: egg observatory over the Haringvliet', '🐦 Sandwich tern · Common tern · Avocet · Ringed plover', '🎵 Nightingale · Great spotted woodpecker · Reed warbler', '🦅 White-tailed eagle above island and sluices', '🌾 337 ha of reed marsh and Scheelhoekbos'],
 'trail': ['Walk the <b>yellow Scheelhoekbos route</b> (5 km) with viewpoint over the island.', 'Visit <b>TIJ</b> via the path with boardwalks from Deltahaven 69.', 'Make the detour to <b>’t Kiekgat</b> on the North Sea side of the dam.'],
 'foot': '🐕 Dogs on lead on the paths (not to TIJ) · 💶 Free · ⚠️ Unpaved; check for ticks; TIJ has stairs · 🚶 Scheelhoekbos car park; 3.7-km green route'
}))

C.append(mk.card(2008, 'Bosobjecten Stellendam', {
 'tags': ['Zuid-Holland · Stellendam (Goeree-Overflakkee)', 'Verspreide bospercelen van Staatsbosbeheer · geen zelfstandig terrein op moderne kaarten · wandelaar week uit naar Scheelhoek en Zuiderdiep', 'list 36 · no. 727'],
 'loc': '📍 Rond Stellendam, op Goeree-Overflakkee · geen gemarkeerd terrein; wandel Scheelhoekbos (parkeerplaats Scheelhoekbos) of Zuiderdiepgorzen',
 'desc': 'De <b>Bosobjecten Stellendam</b> zijn in moderne kaarten niet als zelfstandig terrein terug te vinden — deze kaart registreert de naam eerlijk als <b>naam uit de gids</b>. Staatsbosbeheer beheert verspreide bospercelen op het eiland, maar wie bij Stellendam het bos in wil, weekt het beste uit naar de buren. Naast de jachthaven ligt het <b>Scheelhoekbos</b> van Natuurmonumenten (1974), ontstaan op een werkeiland van de Haringvlietdam net als ’t Kiekgat, met twee korte gemarkeerde routes, een uitkijkheuvel over 337 hectare rietmoeras en uitstapjes naar <b>’t Kiekgat</b> en observatorium <b>TIJ</b>. Aan de oostkant liggen de <b>Zuiderdiepgorzen</b>, sinds 2019 in gebruik met fietspad en laarzenpad van de gemeente. Tussen haven, dam en gorzen vind je hier alsnog bos, riet en weidse uitzichten — alleen onder een andere naam dan de gids noteerde.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (nachtegaal en rietvogels in Scheelhoekbos)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang in het werkeilandbos.',
 'why': ['Een <b>eerlijke gidsnaam</b>: genoteerd, maar nergens als terrein te vinden.', 'Het <b>Scheelhoekbos</b> als alternatief: werkeilandbos uit 1974.', 'De <b>Zuiderdiepgorzen</b>: nieuwe natuur met laarzenpad (2019).', '<b>TIJ en ’t Kiekgat</b> als tochten om de hoek.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nachtegaal en spechten</b> in het Scheelhoekbos.', '<span class="months">Apr–Jul</span> 🐦 <b>Sterns en kluten</b> op de Scheelhoekeilanden.', '<span class="months">Heel jaar</span> 🦅 <b>Zeearend</b> boven Haringvliet en gorzen.', '<span class="months">Sep–Mrt</span> 🦆 <b>Wintergasten</b> op Zuiderdiep en slikken.'],
 'wild': ['📖 Naam uit de gids (geen zelfstandig terrein)', '🌳 Scheelhoekbos: werkeilandbos 1974', '🥾 Zuiderdiepgorzen: fietspad en laarzenpad', '🥚 TIJ en ’t Kiekgat dichtbij', '🦅 Zeearend boven het Haringvliet'],
 'trail': ['Wandel het <b>Scheelhoekbos</b> (kort of 5 km geel) vanaf de parkeerplaats.', 'Verken de <b>Zuiderdiepgorzen</b> over fietspad en laarzenpad.', 'Combineer met <b>Kwade Hoek</b>, Kop van Goeree of de haven.'],
 'foot': '🐕 Honden aangelijnd (niet mee naar TIJ) · 💶 Gratis · ⚠️ Geen eigen terrein — volg de borden van Scheelhoek en gorzen · 🚶 Parkeerplaats Scheelhoekbos; Deltahaven voor TIJ'
}, {
 'tags': ['Zuid-Holland · Stellendam (Goeree-Overflakkee)', 'Scattered forest parcels of Staatsbosbeheer · no separate terrain on modern maps · walkers divert to Scheelhoek and Zuiderdiep', 'list 36 · no. 727'],
 'loc': '📍 Around Stellendam, on Goeree-Overflakkee · no marked terrain; walk Scheelhoekbos (Scheelhoekbos car park) or Zuiderdiepgorzen',
 'desc': 'The <b>Stellendam Forest Objects</b> cannot be found as a separate terrain on modern maps — this card honestly records the name as a <b>name from the guide</b>. Staatsbosbeheer manages scattered forest parcels on the island, but anyone wanting to walk into the forest at Stellendam is best diverted to the neighbours. Beside the marina lies the <b>Scheelhoekbos</b> of Natuurmonumenten (1974), created on a work island of the Haringvlietdam just like ’t Kiekgat, with two short marked routes, a viewpoint hill over 337 hectares of reed marsh and detours to <b>’t Kiekgat</b> and the <b>TIJ</b> observatory. On the eastern side lie the <b>Zuiderdiepgorzen</b>, in use since 2019 with a cycle path and boots trail from the municipality. Between harbour, dam and gorzen you still find forest, reeds and wide views here — just under a different name than the guide noted.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (nightingale and reed birds in Scheelhoekbos)<br>\\n    <b>Best time of day:</b> Morning — song in the work-island forest.',
 'why': ['An <b>honest guide name</b>: noted, but nowhere to be found as terrain.', 'The <b>Scheelhoekbos</b> as alternative: work-island forest from 1974.', 'The <b>Zuiderdiepgorzen</b>: new nature with boots trail (2019).', '<b>TIJ and ’t Kiekgat</b> as trips around the corner.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nightingale and woodpeckers</b> in the Scheelhoekbos.', '<span class="months">Apr–Jul</span> 🐦 <b>Terns and avocets</b> on the Scheelhoek islets.', '<span class="months">All year</span> 🦅 <b>White-tailed eagle</b> above Haringvliet and gorzen.', '<span class="months">Sep–Mar</span> 🦆 <b>Winter visitors</b> on Zuiderdiep and mudflats.'],
 'wild': ['📖 Name from the guide (no separate terrain)', '🌳 Scheelhoekbos: work-island forest 1974', '🥾 Zuiderdiepgorzen: cycle path and boots trail', '🥚 TIJ and ’t Kiekgat nearby', '🦅 White-tailed eagle above the Haringvliet'],
 'trail': ['Walk the <b>Scheelhoekbos</b> (short or 5 km yellow) from the car park.', 'Explore the <b>Zuiderdiepgorzen</b> over cycle path and boots trail.', 'Combine with <b>Kwade Hoek</b>, Kop van Goeree or the harbour.'],
 'foot': '🐕 Dogs on lead (not to TIJ) · 💶 Free · ⚠️ No terrain of its own — follow the signs of Scheelhoek and gorzen · 🚶 Scheelhoekbos car park; Deltahaven for TIJ'
}))

C.append(mk.card(2009, 'Beningerslikken', {
 'tags': ['Zuid-Holland · Zuidland (Spuimonding, Haringvliet)', 'Ruig vogelgebied van bijna 300 hectare · kreken, slikplaten en rietvelden · wandeling van 5 km met trekpontje', 'list 36 · no. 728'],
 'loc': '📍 Ten zuiden van Zuidland, waar het Spui in het Haringvliet overgaat (Koekendorpseweg/Zeedijk) · rondwandeling 5 km met trekpontje, uitkijktoren en hut',
 'desc': 'De <b>Beningerslikken</b> liggen in een verborgen hoekje aan de rand van het <b>Haringvliet</b>: een ruig en open natuurgebied van bijna <b>300 hectare</b>, beheerd door Natuurmonumenten. Waar de Atlantische vogeltrekroute de Delta kruist en de rivieren bij het Haringvliet de Noordzee instromen, liggen kreken, slikplaten, ruigten, rietvelden, drassige graslanden en waterplassen — het hele jaar vol vogels. Een <b>wandelpad van vijf kilometer</b> loopt er omheen over een ringdijk: aan de ene hand de nieuwe slikken en gorzen met gigantisch veel watervogels, aan de andere kant de oorspronkelijke rietvelden tot aan de einder. Onderweg steek je met een <b>trekpontje</b> een kreek over, beklim je de <b>uitkijktoren</b> van Spuimonding West en speur je vanaf het vogeluitkijkpunt naar <b>lepelaars, grote zilverreigers, kolganzen, bergeenden en baardmannetjes</b> — met paniek als er een buizerd overvliegt. Hemelsbreed nog geen twintig kilometer van Rotterdam, maar een oase van rust.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (lepelaars en steltlopers), okt–mrt (duizenden trekvogels)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over slikken en rietvelden.',
 'why': ['De <b>hotspot op de trekroute</b>: waar Atlantische route en rivieren kruisen.', 'De <b>rondwandeling van 5 km</b> met trekpontje en uitkijktoren.', 'De <b>lepelaars en zilverreigers</b> vanaf het uitkijkpunt.', 'De <b>oase van rust</b> op een steenworp van Rotterdam.'],
 'phen': ['<span class="months">Apr–Jun</span> 🥄 <b>Lepelaars en steltlopertjes</b> op slikken en platen.', '<span class="months">Mei–Aug</span> 🎵 <b>Baardmannetjes</b> in het riet van Spuimonding West.', '<span class="months">Okt–Mrt</span> 🪿 <b>Duizenden trekvogels</b> bij kreken en spaarbekken.', '<span class="months">Heel jaar</span> 🦅 <b>Buizerds en kiekendieven</b> boven ruigte en riet.'],
 'wild': ['🥄 Lepelaar · Grote zilverreiger · Bergeend', '🪿 Kolgans · Kievit · Steltlopertjes', '🎵 Baardmannetje · Kwak · Kiekendief', '⛴️ Trekpontje over de kreek', '🗼 Uitkijktoren Spuimonding West'],
 'trail': ['Loop de <b>rondwandeling van 5 km</b> over de ringdijk met trekpontje en brug.', 'Beklim de <b>uitkijktoren</b> met uitzicht over Haringvliet en Hoeksche Waard.', 'Combineer met <b>Zuidland</b>, Korendijkse Slikken of Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Grootste deel niet toegankelijk — blijf op pad en dijk · 🚶 Goede paden; Koekendorpseweg/Zeedijk, Zuidland'
}, {
 'tags': ['Zuid-Holland · Zuidland (Spui mouth, Haringvliet)', 'Rugged bird area of almost 300 hectares · creeks, mudflats and reed beds · 5-km walk with pull ferry', 'list 36 · no. 728'],
 'loc': '📍 South of Zuidland, where the Spui flows into the Haringvliet (Koekendorpseweg/Zeedijk) · 5-km circuit with pull ferry, lookout tower and hide',
 'desc': 'The <b>Beningerslikken</b> lie in a hidden corner on the edge of the <b>Haringvliet</b>: a rugged and open nature area of almost <b>300 hectares</b>, managed by Natuurmonumenten. Where the Atlantic bird migration route crosses the Delta and the rivers flow into the North Sea at the Haringvliet, lie creeks, mudflats, rough growth, reed beds, marshy grasslands and pools — full of birds all year. A <b>five-kilometre walking path</b> circles it over a ring dike: on one hand the new mudflats and gorzen with gigantic numbers of waterfowl, on the other the original reed beds to the horizon. Along the way you cross a creek with a <b>pull ferry</b>, climb the <b>lookout tower</b> of Spuimonding West and scan from the bird viewpoint for <b>spoonbills, great egrets, white-fronted geese, shelducks and bearded reedlings</b> — with panic when a buzzard flies over. Barely twenty kilometres from Rotterdam as the crow flies, but an oasis of peace.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spoonbills and waders), Oct–Mar (thousands of migrants)<br>\\n    <b>Best time of day:</b> Morning — light over mudflats and reed beds.',
 'why': ['The <b>hotspot on the flyway</b>: where Atlantic route and rivers cross.', 'The <b>5-km circuit</b> with pull ferry and lookout tower.', 'The <b>spoonbills and egrets</b> from the viewpoint.', 'The <b>oasis of peace</b> a stone’s throw from Rotterdam.'],
 'phen': ['<span class="months">Apr–Jun</span> 🥄 <b>Spoonbills and little waders</b> on mudflats and plates.', '<span class="months">May–Aug</span> 🎵 <b>Bearded reedlings</b> in the reeds of Spuimonding West.', '<span class="months">Oct–Mar</span> 🪿 <b>Thousands of migrants</b> at creeks and reservoir.', '<span class="months">All year</span> 🦅 <b>Buzzards and harriers</b> above rough and reeds.'],
 'wild': ['🥄 Spoonbill · Great egret · Shelduck', '🪿 White-fronted goose · Lapwing · Little waders', '🎵 Bearded reedling · Night heron · Harrier', '⛴️ Pull ferry across the creek', '🗼 Spuimonding West lookout tower'],
 'trail': ['Walk the <b>5-km circuit</b> over the ring dike with pull ferry and bridge.', 'Climb the <b>lookout tower</b> overlooking Haringvliet and Hoeksche Waard.', 'Combine with <b>Zuidland</b>, Korendijkse Slikken or Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Largest part not accessible — stay on path and dike · 🚶 Good paths; Koekendorpseweg/Zeedijk, Zuidland'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(2009)
mk.check()
