# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2000, 'Graswegbos', {
 'tags': ['Zuid-Holland · Hellevoetsluis (Grasweg)', 'Buurtbos tussen Kooisteebos en Grasweggebied · burgerinitiatief met SOVON-tellingen · kiekendief, ijsvogel en reeën om de hoek', 'list 36 · no. 719'],
 'loc': '📍 Aan de Grasweg in Hellevoetsluis, tussen Kooisteebos en Grasweggebied · wandelpaden; verbonden via het Grasweggebied met rolstoeltoegankelijk pad',
 'desc': 'Het <b>Graswegbos</b> aan de Grasweg in <b>Hellevoetsluis</b> is zo’n groen eilandje dat de stad leefbaar houdt — en dat buurtbewoners met hand en tand verdedigden. Tussen dit bos en het <b>Kooisteebos</b> lag een akker; bewoners van de Grasweg kregen het voor elkaar om die 7 hectare met steun van partijen in te richten als <b>Grasweggebied</b>: waar in 2008 nog een aardappelakker lag, wandel je nu door water, knotwilgen, riet, moeras, grasland en bos. Het Zuid-Hollands Landschap beheert het met vrijwilligers van de <b>Stichting Natuurlijk Grasweggebied</b>, en de soortenlijst groeit: twee paartjes <b>bruine kiekendief</b>, ijsvogels, groene spechten, vleermuizen, het bruin blauwtje en <b>reeën</b>. In het Graswegbos zelf inventariseerden SOVON-vogelaars en nachtvlinderaars al verrassend veel. Natuur zonder huizen — het kan, aan de Grasweg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (kiekendieven en zangvogels), mei–aug (vlinders en ijsvogel)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — kiekendieven boven moeras en bos.',
 'why': ['Het <b>burgerinitiatief</b>: van aardappelakker naar groene oase.', 'De <b>groene verbinding</b>: Graswegbos, Grasweggebied en Kooisteebos aan elkaar.', 'De <b>bruine kiekendieven</b> boven het moeras.', 'De <b>soortenrijkdom</b> op zeven hectare: van blauwtje tot ree.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Kiekendieven en zangvogels</b> in bos en moeras.', '<span class="months">Mei–Aug</span> 🦋 <b>Vlinders</b> als het bruin blauwtje op de bloemenweide.', '<span class="months">Heel jaar</span> 🐦 <b>Ijsvogel en groene specht</b> in het gebied.', '<span class="months">Heel jaar</span> 🦌 <b>Reeën</b> tussen bos en moeras.'],
 'wild': ['🪶 Twee paartjes bruine kiekendief', '🐦 Ijsvogel · Groene specht', '🦋 Bruin blauwtje en vleermuizen', '🦌 Reeën van het Grasweggebied', '🌿 Knotwilgen, riet en moeras'],
 'trail': ['Wandel vanuit het <b>Graswegbos</b> het <b>Grasweggebied</b> in (rolstoeltoegankelijk pad bij de entree).', 'Loop door naar het <b>Kooisteebos</b> via de groene verbinding.', 'Combineer met <b>Quackgors</b> of de vesting Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Afgeschermd deel met schapen; blijf op de paden · 🚶 Entree met bloemenweide, borden en parkeerplaatsen'
}, {
 'tags': ['Zuid-Holland · Hellevoetsluis (Grasweg)', 'Neighbourhood forest between Kooisteebos and Grasweggebied · citizen initiative with SOVON counts · harrier, kingfisher and roe deer around the corner', 'list 36 · no. 719'],
 'loc': '📍 On the Grasweg in Hellevoetsluis, between Kooisteebos and Grasweggebied · walking paths; linked via the Grasweggebied with wheelchair-accessible path',
 'desc': 'The <b>Graswegbos</b> on the Grasweg in <b>Hellevoetsluis</b> is one of those green islets that keep the town liveable — and that local residents defended tooth and nail. Between this forest and the <b>Kooisteebos</b> lay a field; residents of the Grasweg managed to convert those 7 hectares with support into the <b>Grasweggebied</b>: where a potato field still lay in 2008, you now walk through water, pollard willows, reeds, marsh, grassland and forest. Het Zuid-Hollands Landschap manages it with volunteers of the <b>Stichting Natuurlijk Grasweggebied</b>, and the species list keeps growing: two pairs of <b>marsh harrier</b>, kingfishers, green woodpeckers, bats, the brown argus and <b>roe deer</b>. In the Graswegbos itself SOVON birders and moth recorders already inventoried surprisingly much. Nature without houses — it can be done, on the Grasweg.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (harriers and songbirds), May–Aug (butterflies and kingfisher)<br>\\n    <b>Best time of day:</b> Morning — harriers above marsh and forest.',
 'why': ['The <b>citizen initiative</b>: from potato field to green oasis.', 'The <b>green link</b>: Graswegbos, Grasweggebied and Kooisteebos joined.', 'The <b>marsh harriers</b> above the marsh.', 'The <b>species richness</b> on seven hectares: from argus to roe deer.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Harriers and songbirds</b> in forest and marsh.', '<span class="months">May–Aug</span> 🦋 <b>Butterflies</b> such as the brown argus on the flower meadow.', '<span class="months">All year</span> 🐦 <b>Kingfisher and green woodpecker</b> in the area.', '<span class="months">All year</span> 🦌 <b>Roe deer</b> between forest and marsh.'],
 'wild': ['🪶 Two pairs of marsh harrier', '🐦 Kingfisher · Green woodpecker', '🦋 Brown argus and bats', '🦌 Roe deer of the Grasweggebied', '🌿 Pollard willows, reeds and marsh'],
 'trail': ['Walk from the <b>Graswegbos</b> into the <b>Grasweggebied</b> (wheelchair-accessible path at the entrance).', 'Continue to the <b>Kooisteebos</b> via the green link.', 'Combine with <b>Quackgors</b> or the fortress of Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Fenced section with sheep; stay on the paths · 🚶 Entrance with flower meadow, signs and car parks'
}))

C.append(mk.card(2001, 'Waalhoek', {
 'tags': ['Zuid-Holland · Hellevoetsluis (Polder Abbenbroek)', 'Graslandreservaat van 11 hectare rond het Katerwaaltje · wiel uit circa 1350 · plasdras tot ver in het voorjaar', 'list 36 · no. 720'],
 'loc': '📍 In Polder Abbenbroek, ten oosten van Hellevoetsluis (Katerwaalsedijk) · ruig grasland bij het wiel; KNNV doet broedvogelinventarisaties',
 'desc': 'Graslandreservaat <b>Waalhoek</b> (11 hectare) ligt midden in het agrarische land van <b>Polder Abbenbroek</b>, ten oosten van Hellevoetsluis. Rond <b>1350</b> brak hier de Katerwaalsedijk en kolkte het water een diep gat aan de binnenzijde van de dijk — een <b>wiel</b> dat omwonenden het “Katerwaaltje” noemen. Het Zuid-Hollands Landschap beheert het ruige grasland bij dit kleine wiel: met een <b>windmolentje en stuwen</b> houden we het waterpeil hoger dan in het omringende gebied, zodat grote delen tot ver in het voorjaar <b>plasdras</b> staan. Daar houden weidevogels als <b>kievit, grutto en tureluur</b> van. Langs de Katerwaalsedijk staan populieren als uitvalsbasis voor buizerds, en het riet rond het wiel biedt jonge vogels beschutting. Klein, nat en vol leven — een plasdras hart in de akkerpolder.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–Mei</b> (plasdras en baltsende weidevogels)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — weidevogels boven het plasdras.',
 'why': ['Het <b>Katerwaaltje</b>: een wiel uit circa 1350.', 'Het <b>plasdras</b> tot ver in het voorjaar dankzij molentje en stuwen.', 'De <b>balts van kievit, grutto en tureluur</b>.', 'Het <b>riet rond het wiel</b> als kraamkamer.'],
 'phen': ['<span class="months">Mrt–Mei</span> 💧 <b>Plasdras</b> en baltsende weidevogels.', '<span class="months">Apr–Jun</span> 🐣 <b>Kuikens</b> in het ruige grasland.', '<span class="months">Heel jaar</span> 🦅 <b>Buizerds</b> vanaf de populieren.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b> op wiel en plasdras.'],
 'wild': ['🐦 Kievit · Grutto · Tureluur', '💧 Katerwaaltje (wiel, ca. 1350)', '🦅 Buizerd en kraaien van de populieren', '🌾 Ruig grasland en rietkraag', '📋 Broedvogelinventarisaties (KNNV)'],
 'trail': ['Bekijk het reservaat vanaf de <b>Katerwaalsedijk</b> ten oosten van Hellevoetsluis.', 'Fiets door <b>Polder Abbenbroek</b> richting Bernisse.', 'Combineer met <b>Bernisse</b> of Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Kwetsbaar plasdras — blijf op dijk en paden · 🚶 Katerwaalsedijk; geen paden door het reservaat'
}, {
 'tags': ['Zuid-Holland · Hellevoetsluis (Polder Abbenbroek)', '11-hectare grassland reserve around the Katerwaaltje · breach pool from around 1350 · waterlogged well into spring', 'list 36 · no. 720'],
 'loc': '📍 In Polder Abbenbroek, east of Hellevoetsluis (Katerwaalsedijk) · rough grassland by the pool; KNNV carries out breeding-bird surveys',
 'desc': 'The <b>Waalhoek</b> grassland reserve (11 hectares) lies in the middle of the farmland of <b>Polder Abbenbroek</b>, east of Hellevoetsluis. Around <b>1350</b> the Katerwaalsedijk burst here and the swirling water gouged a deep hole on the inner side of the dike — a <b>breach pool</b> locals call the “Katerwaaltje”. Het Zuid-Hollands Landschap manages the rough grassland by this little pool: with a <b>windmill pump and weirs</b> we keep the water level higher than in the surroundings, so that large parts stand <b>splashy wet</b> well into spring. Meadow birds such as <b>lapwing, godwit and redshank</b> love that. Poplars along the Katerwaalsedijk serve as a base for buzzards, and the reeds around the pool shelter young birds. Small, wet and full of life — a splashy heart in the arable polder.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (shallow water and displaying meadow birds)<br>\\n    <b>Best time of day:</b> Morning — meadow birds above the wetness.',
 'why': ['The <b>Katerwaaltje</b>: a breach pool from around 1350.', 'The <b>shallow water</b> into late spring thanks to mill and weirs.', 'The <b>display of lapwing, godwit and redshank</b>.', 'The <b>reeds around the pool</b> as a nursery.'],
 'phen': ['<span class="months">Mar–May</span> 💧 <b>Shallow water</b> and displaying meadow birds.', '<span class="months">Apr–Jun</span> 🐣 <b>Chicks</b> in the rough grassland.', '<span class="months">All year</span> 🦅 <b>Buzzards</b> from the poplars.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b> on pool and wet fields.'],
 'wild': ['🐦 Lapwing · Godwit · Redshank', '💧 Katerwaaltje (breach pool, c. 1350)', '🦅 Buzzard and crows of the poplars', '🌾 Rough grassland and reed fringe', '📋 Breeding-bird surveys (KNNV)'],
 'trail': ['View the reserve from the <b>Katerwaalsedijk</b> east of Hellevoetsluis.', 'Cycle through <b>Polder Abbenbroek</b> towards Bernisse.', 'Combine with <b>Bernisse</b> or Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Vulnerable wetness — stay on dike and paths · 🚶 Katerwaalsedijk; no paths through the reserve'
}))

C.append(mk.card(2002, 'Natuur- en recreatiegebied Bernisse', {
 'tags': ['Zuid-Holland · Voorne-Putten (Heenvliet–Simonshaven)', '300 hectare en 7 kilometer voormalige rivier · strandjes, surfmeer en bossen · groene buffer tussen vijf dorpen', 'list 36 · no. 721'],
 'loc': '📍 Tussen Heenvliet, Geervliet, Abbenbroek, Zuidland en Simonshaven (Stompaardsedijk 2) · vrij toegankelijk; strandjes, steigers en knooppunten',
 'desc': 'De <b>Bernisse</b> is zowel een oude rivierarm — ooit Widele geheten, de scheiding tussen de eilanden <b>Voorne en Putten</b> — als het natuur- en recreatiegebied eromheen: <b>300 hectare</b> en <b>7 kilometer</b> lang, van Heenvliet via Abbenbroek en Zuidland tot Simonshaven en het Spui. Meertjes, kommen en plassen wisselen af met bossen, drassige natuur en weilanden; het gebied vormt een groene buffer tussen vijf dorpen. Er zijn strandjes (Stompaardseplas met <b>surfmeer</b> en spartelvijver, strand Simonshaven, Hoenderhoek), trailerhellingen en aanlegsteigers — roeien, kanoën, surfen en zwemmen mag, <b>motorboten niet</b>. Futen, zwanen en reigers vissen in de plassen met karper en snoek. Recreatieschap Voorne-Putten en Staatsbosbeheer beheren het samen en planten tientallen hectares <b>nieuw bos</b> voor waterbuffering en biodiversiteit. Het Heen- en Geervlietpad (5,9 km) verbindt vestingstadjes met waternatuur.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (zwemmen, varen en broedvogels), apr–jun (vogelzang)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogels; middag voor strand en water.',
 'why': ['De <b>voormalige rivier</b>: zeven kilometer water tussen twee eilanden.', 'De <b>strandjes en het surfmeer</b> van de Stompaardseplas.', 'Varen <b>zonder motorboten</b>: roeien, kanoën en surfen.', 'Het <b>nieuwe bos</b>: tientallen hectares aanplant.'],
 'phen': ['<span class="months">Mei–Sep</span> 🏖️ <b>Strand- en watersportseizoen</b> op plassen en surfmeer.', '<span class="months">Apr–Jun</span> 🐣 <b>Broedvogels</b>: futen, zwanen en reigers.', '<span class="months">Mei–Aug</span> 🎣 <b>Vissen</b>: karper en snoek in de plassen.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b> op het open water.'],
 'wild': ['🦢 Fuut · Zwaan · Reiger', '🎣 Karper · Snoek', '🏖️ Strandjes en surfmeer Stompaardseplas', '🌳 Nieuw bos in aanplant', '🚣 Roeien, kanoën en surfen (geen motorboten)'],
 'trail': ['Loop het <b>Heen- en Geervlietpad</b> (5,9 km) door kernen en recreatiegebied.', 'Fiets de <b>knooppunten</b> tussen dorpskernen en Spijkenisse.', 'Combineer met <b>polder Biert</b>, Brielle of Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd (strandregels beachten) · 💶 Gratis; parkeren bij strandjes · ⚠️ Zwem alleen bij aangewezen strandjes · 🚶 Wandelpaden en fietsroutes overal; horeca bij de strandjes'
}, {
 'tags': ['Zuid-Holland · Voorne-Putten (Heenvliet–Simonshaven)', '300 hectares and 7 kilometres of former river · beaches, surf lake and forests · green buffer between five villages', 'list 36 · no. 721'],
 'loc': '📍 Between Heenvliet, Geervliet, Abbenbroek, Zuidland and Simonshaven (Stompaardsedijk 2) · freely accessible; beaches, jetties and junctions',
 'desc': 'The <b>Bernisse</b> is both an old river branch — once called Widele, the divide between the islands of <b>Voorne and Putten</b> — and the nature and recreation area around it: <b>300 hectares</b> and <b>7 kilometres</b> long, from Heenvliet via Abbenbroek and Zuidland to Simonshaven and the Spui. Little lakes, bowls and pools alternate with forests, marshy nature and meadows; the area forms a green buffer between five villages. There are beaches (Stompaardseplas with <b>surf lake</b> and paddling pool, Simonshaven beach, Hoenderhoek), slipways and mooring jetties — rowing, canoeing, surfing and swimming are allowed, <b>motorboats are not</b>. Grebes, swans and herons fish in the pools with carp and pike. Recreation Board Voorne-Putten and Staatsbosbeheer manage it together and plant tens of hectares of <b>new forest</b> for water buffering and biodiversity. The Heen- en Geervlietpad (5.9 km) links fortress towns with water nature.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (swimming, boating and breeding birds), Apr–Jun (birdsong)<br>\\n    <b>Best time of day:</b> Morning — birds; afternoon for beach and water.',
 'why': ['The <b>former river</b>: seven kilometres of water between two islands.', 'The <b>beaches and the surf lake</b> of the Stompaardseplas.', 'Boating <b>without motorboats</b>: rowing, canoeing and surfing.', 'The <b>new forest</b>: tens of hectares being planted.'],
 'phen': ['<span class="months">May–Sep</span> 🏖️ <b>Beach and watersports season</b> on pools and surf lake.', '<span class="months">Apr–Jun</span> 🐣 <b>Breeding birds</b>: grebes, swans and herons.', '<span class="months">May–Aug</span> 🎣 <b>Fishing</b>: carp and pike in the pools.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b> on the open water.'],
 'wild': ['🦢 Grebe · Swan · Heron', '🎣 Carp · Pike', '🏖️ Beaches and surf lake Stompaardseplas', '🌳 New forest being planted', '🚣 Rowing, canoeing and surfing (no motorboats)'],
 'trail': ['Walk the <b>Heen- en Geervlietpad</b> (5.9 km) through historic cores and recreation area.', 'Cycle the <b>junctions</b> between village cores and Spijkenisse.', 'Combine with <b>polder Biert</b>, Brielle or Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead (observe beach rules) · 💶 Free; parking at the beaches · ⚠️ Swim only at designated beaches · 🚶 Walking paths and cycle routes everywhere; cafés at the beaches'
}))

C.append(mk.card(2003, 'Biert', {
 'tags': ['Zuid-Holland · Simonshaven (polder Biert, Voorne)', 'Veertiende-eeuwse veenpolder van Staatsbosbeheer · zoutplanten, orchideeën en weidevogels · Biertpad vanaf het Witte Kerkje', 'list 36 · no. 722'],
 'loc': '📍 Polder Biert tussen Spijkenisse en Zuidland (start Biertpad: Schuddebeursedijk, Simonshaven) · vogelrustgebied: in broedseizoen niet toegankelijk',
 'desc': '<b>Biert</b> is bij Staatsbosbeheer de <b>polder Biert</b>: een in de veertiende eeuw ingepolderd veenland waarvan de bodem sterk inklonk. Deze van oudsher natte polder was alleen als weiland te gebruiken — en dat betaalt zich uit in natuur. Tussen de kleine percelen stromen brede sloten en omdijkte kreekrestanten (<b>Welvliet, Oostenrijk, Vierambachtenboezem</b>); er groeien zoutminners als schijnspurrie, aarbeiklaver en rode ogentroost, en rond de kreken op de hogere delen staan <b>orchideeën</b>. Grutto, graspieper, leeuwerik en slobeend bevolken de weilanden, met kievit, tureluur en scholekster erbij. Het <b>Biertpad</b> (12,4 km) voert vanaf het schilderachtige <b>Witte Kerkje van Simonshaven</b> langs knotwilgdijken en kreken; door de polder loopt een oude dreef die je buiten het broedseizoen mag bewandelen, met zicht op het Spuigors. Onderweg: wijndomein De Vier Ambachten — als de poort openstaat, proeven.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels en orchideeën), sep–okt (overwinterende trekkers)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — weidevogelkoor boven de percelen.',
 'why': ['De <b>veertiende-eeuwse veenpolder</b> met ingeklonken percelen.', 'De <b>zoutplanten en orchideeën</b> langs sloten en kreken.', 'Het <b>Biertpad</b> (12,4 km) vanaf het Witte Kerkje.', 'De <b>oude dreef</b> door de polder (buiten broedseizoen).'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogelkoor</b>: grutto, graspieper en leeuwerik.', '<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> op de hogere kreekruggen.', '<span class="months">Sep–Okt</span> 🦆 <b>Overwinterende trekkers</b> in de natte polder.', '<span class="months">Mrt–Jul</span> 🚫 <b>Vogelrust</b>: polder dan niet toegankelijk.'],
 'wild': ['🐦 Grutto · Graspieper · Leeuwerik · Slobeend', '🌸 Orchideeën · Schijnspurrie · Rode ogentroost', '⛪ Witte Kerkje van Simonshaven', '🍷 Wijndomein De Vier Ambachten', '💧 Welvliet · Oostenrijk · Spuigors'],
 'trail': ['Loop het <b>Biertpad</b> (12,4 km) vanaf Schuddebeursedijk, Simonshaven.', 'Wandel buiten het broedseizoen de <b>oude dreef</b> door de polder.', 'Combineer met <b>Bernisse</b>, Spijkenisse of Zuidland.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Vogelrustgebied — in broedseizoen niet toegankelijk · 🚶 Biertpad met inkortmogelijkheden via Biertsedijk en Slikweg'
}, {
 'tags': ['Zuid-Holland · Simonshaven (polder Biert, Voorne)', 'Fourteenth-century peat polder of Staatsbosbeheer · salt plants, orchids and meadow birds · Biertpad from the White Church', 'list 36 · no. 722'],
 'loc': '📍 Polder Biert between Spijkenisse and Zuidland (Biertpad start: Schuddebeursedijk, Simonshaven) · bird rest area: closed in breeding season',
 'desc': '<b>Biert</b> is at Staatsbosbeheer the <b>polder Biert</b>: peatland impoldered in the fourteenth century whose soil subsided strongly. This traditionally wet polder could only be used as pasture — and that pays off in nature. Broad ditches and embanked creek remnants (<b>Welvliet, Oostenrijk, Vierambachtenboezem</b>) flow between the small parcels; salt-lovers such as sea-spurrey, strawberry clover and red bartsia grow, and <b>orchids</b> stand around the creeks on the higher parts. Godwit, meadow pipit, skylark and shoveler populate the meadows, with lapwing, redshank and oystercatcher. The <b>Biertpad</b> (12.4 km) runs from the picturesque <b>White Church of Simonshaven</b> along pollard-willow dikes and creeks; an old drove road crosses the polder that you may walk outside the breeding season, with a view of the Spuigors. Along the way: the Vier Ambachten vineyard — if the gate is open, taste.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds and orchids), Sep–Oct (wintering migrants)<br>\\n    <b>Best time of day:</b> Morning — meadow-bird chorus above the parcels.',
 'why': ['The <b>fourteenth-century peat polder</b> with subsided parcels.', 'The <b>salt plants and orchids</b> along ditches and creeks.', 'The <b>Biertpad</b> (12.4 km) from the White Church.', 'The <b>old drove road</b> through the polder (outside breeding season).'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow-bird chorus</b>: godwit, pipit and lark.', '<span class="months">May–Jun</span> 🌸 <b>Orchids</b> on the higher creek ridges.', '<span class="months">Sep–Oct</span> 🦆 <b>Wintering migrants</b> in the wet polder.', '<span class="months">Mar–Jul</span> 🚫 <b>Bird rest</b>: polder closed then.'],
 'wild': ['🐦 Godwit · Meadow pipit · Skylark · Shoveler', '🌸 Orchids · Sea-spurrey · Red bartsia', '⛪ White Church of Simonshaven', '🍷 Vier Ambachten vineyard', '💧 Welvliet · Oostenrijk · Spuigors'],
 'trail': ['Walk the <b>Biertpad</b> (12.4 km) from Schuddebeursedijk, Simonshaven.', 'Walk the <b>old drove road</b> through the polder outside the breeding season.', 'Combine with <b>Bernisse</b>, Spijkenisse or Zuidland.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Bird rest area — closed in breeding season · 🚶 Biertpad with shortcuts via Biertsedijk and Slikweg'
}))

C.append(mk.card(2004, 'Spijkenisse Mallebos', {
 'tags': ['Zuid-Holland · Spijkenisse (Maliedijk)', 'Loofbos van 52 hectare op verdronken Schiekamp · bewoond vóór de tiende eeuw, vergaan in 1164 · ruiterpaden sinds 1997', 'list 36 · no. 723'],
 'loc': '📍 Aan de westzijde van Spijkenisse (Maliedijk 10; parkeren Curieweg) · vrij toegankelijk; IVN-wandelingen vanaf Malledijk',
 'desc': 'Het <b>Mallebos</b> is het natuur- en recreatiebos aan de westzijde van <b>Spijkenisse</b> (circa 52 hectare), genoemd naar de aangrenzende <b>Malledijk</b> — misschien een verbastering van Molendijk, want op oude kaarten staat er een molen voor de afwatering van de polder. Het bos ligt op het oude gebied <b>Schiekamp</b>, dat volgens archeologen al vóór de tiende eeuw bewoond was en ten onder ging in de grote <b>overstromingsramp van 1164</b>, toen het hele deltagebied veranderde: rivieren als Bernisse (Widele) en Beninghe verdwenen, Haringvliet en Spui ontstonden. Het eerste bosdeel werd in <b>1980</b> aangelegd als landschappelijk element, het tweede in <b>1990</b>; Staatsbosbeheer beheert het duurzaam. Het gevarieerde loofbos grenst aan Malledijk en <b>Vierambachtenboezem</b>, het zuidwestelijke deel is open en nat — met gele lis, kattenstaart en koekoeksbloem in aantocht. Sinds 1997 liggen er ruiterpaden; IVN’ers starten aan de Malledijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en bloeiende slootkanten), sep–okt (herfstkleuren)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang in het gevarieerde loofbos.',
 'why': ['Het <b>verdronken Schiekamp</b>: bewoond vóór de tiende eeuw.', 'De <b>ramp van 1164</b> die het deltagebied herschiep.', 'Het <b>natte zuidwesten</b> met lis, kattenstaart en koekoeksbloem.', 'Bos, boezem en dijk in <b>één ommetje</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Vogelzang</b> in het jonge loofbos.', '<span class="months">Mei–Jul</span> 🌸 <b>Bloeiende slootkanten</b>: lis en kattenstaart.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleuren</b> van eik, es en els.', '<span class="months">Heel jaar</span> 🐴 <b>Ruiters</b> op de paden van 1997.'],
 'wild': ['🌳 Loofbos: wilg, eik, es en els', '🌸 Gele lis · Kattenstaart · Koekoeksbloem', '🏛️ Schiekamp: verdronken land uit 1164', '🐴 Ruiterpaden door het bos', '💧 Vierambachtenboezem naast de deur'],
 'trail': ['Wandel een <b>rondje Mallebos</b> (ca. 3 km) vanaf Malledijk 10.', 'Ga mee met een <b>IVN-wandeling</b> door bos en boezem.', 'Combineer met <b>polder Biert</b>, Bernisse of Spijkenisse.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Niet alle paden geschikt voor rolstoel of wagen · 🚶 Parkeren Curieweg; ruiterpaden apart'
}, {
 'tags': ['Zuid-Holland · Spijkenisse (Maliedijk)', '52-hectare deciduous forest on drowned Schiekamp · inhabited before the tenth century, lost in 1164 · bridle paths since 1997', 'list 36 · no. 723'],
 'loc': '📍 On the west side of Spijkenisse (Maliedijk 10; parking Curieweg) · freely accessible; IVN walks from Malledijk',
 'desc': 'The <b>Mallebos</b> is the nature and recreation forest on the west side of <b>Spijkenisse</b> (some 52 hectares), named after the adjacent <b>Malledijk</b> — perhaps a corruption of Molendijk, for old maps show a mill draining the polder. The forest lies on the old territory of <b>Schiekamp</b>, inhabited before the tenth century according to archaeologists and lost in the great <b>flood disaster of 1164</b>, when the entire delta changed: rivers such as the Bernisse (Widele) and Beninghe vanished, Haringvliet and Spui came into being. The first forest section was planted in <b>1980</b> as a landscape element, the second in <b>1990</b>; Staatsbosbeheer manages it sustainably. The varied deciduous forest borders the Malledijk and the <b>Vierambachtenboezem</b>, the southwestern part is open and wet — with yellow flag, purple loosestrife and ragged-robin on the way. Bridle paths have existed since 1997; IVN walkers start at the Malledijk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and flowering ditch banks), Sep–Oct (autumn colours)<br>\\n    <b>Best time of day:</b> Morning — song in the varied deciduous forest.',
 'why': ['The <b>drowned Schiekamp</b>: inhabited before the tenth century.', 'The <b>disaster of 1164</b> that remade the delta.', 'The <b>wet southwest</b> with flag, loosestrife and ragged-robin.', 'Forest, storage basin and dike in <b>a single stroll</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Birdsong</b> in the young deciduous forest.', '<span class="months">May–Jul</span> 🌸 <b>Flowering ditch banks</b>: flag and loosestrife.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colours</b> of oak, ash and alder.', '<span class="months">All year</span> 🐴 <b>Horse riders</b> on the 1997 paths.'],
 'wild': ['🌳 Deciduous forest: willow, oak, ash and alder', '🌸 Yellow flag · Purple loosestrife · Ragged-robin', '🏛️ Schiekamp: drowned land of 1164', '🐴 Bridle paths through the forest', '💧 Vierambachtenboezem next door'],
 'trail': ['Walk a <b>Mallebos circuit</b> (c. 3 km) from Malledijk 10.', 'Join an <b>IVN walk</b> through forest and basin.', 'Combine with <b>polder Biert</b>, Bernisse or Spijkenisse.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Not all paths suitable for wheelchairs or prams · 🚶 Parking Curieweg; separate bridle paths'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(2004)
mk.check()
mk.check()
