# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2010, 'Korendijkse Slikken', {
 'tags': ['Zuid-Holland · Goudswaard (Hoeksche Waard)', 'Vogelreservaat van bijna 500 hectare · graslanden en zoetwatergetijdennatuur · alleen open 1 jul–1 nov', 'list 36 · no. 729'],
 'loc': '📍 Ten zuiden van Goudswaard, tussen Haringvliet en Spui · alleen toegankelijk 1 jul–1 nov; hutten aan Groeneweg en Oudendijk; Korendijkse Slikkenwandeling',
 'desc': 'De <b>Korendijkse Slikken</b> zijn een vogelreservaat van bijna <b>vijfhonderd hectare</b> ten zuiden van <b>Goudswaard</b>, in beheer bij Natuurmonumenten. Graslanden en <b>zoetwatergetijdennatuur</b> — grenzend aan Haringvliet en Spui — vormen het hele jaar een rust- en foerageerplek voor smient, wulp en goudplevier; in najaar en winter zitten er grote groepen ganzen en eenden, in het voorjaar broeden kieviten, grutto’s en tureluurs. In het getijden-deel gedijen moerasvogels: <b>rietzangers, blauwborsten en grote zilverreigers</b>, met broedende bruine kiekendieven en haviken — en regelmatig <b>zeearend, klapekster, roerdomp en roodhalsgans</b>. Koeien, schapen en paarden houden het open; een deel mag verbossen. Tussen het riet groeien moerasmelkdistel, heemst, zeekraal en lamsoor. Bekijk het vanaf Oudendijk en Westdijk, vanuit de <b>vogelkijkhut</b> aan het einde van de Groeneweg of het oude <b>dijkmagazijn</b> aan de Oudendijk — en wandel mee door het beboste deel naar de observatiehut.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–Okt</b> (openstelling; trekkers en nazomergasten), okt (ganzen en eenden)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogels actief; avond voor de kiekendieven.',
 'why': ['Het <b>zoetwatergetij</b>: een van de weinige plekken met zeekraal en lamsoor.', 'De <b>vogelkijkhutten</b>: Groeneweg, dijkmagazijn en boshut.', 'De <b>zeearend en roerdomp</b> als regelmatige gasten.', 'De <b>Korendijkse Slikkenwandeling</b> vanaf het dijkdorp.'],
 'phen': ['<span class="months">Jul–Okt</span> 🦆 <b>Openstelling</b>: trekkers op slikken en grasland.', '<span class="months">Okt–Mrt</span> 🪿 <b>Ganzen- en eendenmassa’s</b> als rust- en foerageerplek.', '<span class="months">Apr–Jun</span> 🐣 <b>Broedende steltlopers</b> (buiten openstelling, vanaf de dijk).', '<span class="months">Heel jaar</span> 🦅 <b>Kiekendief, havik en zeearend</b> boven het getijdenland.'],
 'wild': ['🦅 Zeearend · Bruine kiekendief · Havik · Roerdomp', '🐦 Smient · Wulp · Goudplevier · Blauwborst', '🌸 Moerasmelkdistel · Heemst · Zeekraal · Lamsoor', '🐴 Koeien · Schapen · Paarden als begrazers', '🔭 Hutten aan Groeneweg en Oudendijk'],
 'trail': ['Loop de <b>Korendijkse Slikkenwandeling</b> vanaf Goudswaard (molen Windlust).', 'Kijk vanaf <b>Oudendijk en Westdijk</b>; hut aan het einde van de Groeneweg.', 'Combineer met <b>Beningerslikken</b>, het Spui of Numansdorp.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Alleen open 1 jul–1 nov; broedseizoen en winter gesloten · 🚶 Wandelroute Natuurmonumenten door het beboste deel'
}, {
 'tags': ['Zuid-Holland · Goudswaard (Hoeksche Waard)', 'Bird reserve of almost 500 hectares · grasslands and freshwater tidal nature · only open 1 Jul–1 Nov', 'list 36 · no. 729'],
 'loc': '📍 South of Goudswaard, between Haringvliet and Spui · only accessible 1 Jul–1 Nov; hides on Groeneweg and Oudendijk; Korendijkse Slikken walk',
 'desc': 'The <b>Korendijkse Slikken</b> form a bird reserve of almost <b>five hundred hectares</b> south of <b>Goudswaard</b>, managed by Natuurmonumenten. Grasslands and <b>freshwater tidal nature</b> — bordering Haringvliet and Spui — form a resting and foraging place all year for wigeon, curlew and golden plover; in autumn and winter large groups of geese and ducks sit here, in spring lapwings, godwits and redshanks breed. In the tidal part marsh birds thrive: <b>Savi’s, bluethroats and great egrets</b>, with breeding marsh harriers and goshawks — and regular <b>white-tailed eagle, great grey shrike, bittern and red-breasted goose</b>. Cows, sheep and horses keep it open; one part is left to turn to forest. Marsh sow-thistle, marsh mallow, glasswort and sea lavender grow among the reeds. View it from Oudendijk and Westdijk, from the <b>bird hide</b> at the end of the Groeneweg or the old <b>dike warehouse</b> on the Oudendijk — and walk along through the wooded part to the observation hut.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Oct</b> (opening; migrants and late-summer guests), Oct (geese and ducks)<br>\\n    <b>Best time of day:</b> Morning — birds active; evening for the harriers.',
 'why': ['The <b>freshwater tide</b>: one of few places with glasswort and sea lavender.', 'The <b>bird hides</b>: Groeneweg, dike warehouse and forest hut.', 'The <b>white-tailed eagle and bittern</b> as regular guests.', 'The <b>Korendijkse Slikken walk</b> from the dike village.'],
 'phen': ['<span class="months">Jul–Oct</span> 🦆 <b>Opening</b>: migrants on mudflats and grassland.', '<span class="months">Oct–Mar</span> 🪿 <b>Masses of geese and ducks</b> as resting and foraging place.', '<span class="months">Apr–Jun</span> 🐣 <b>Breeding waders</b> (outside opening, from the dike).', '<span class="months">All year</span> 🦅 <b>Harrier, goshawk and eagle</b> above the tidal land.'],
 'wild': ['🦅 White-tailed eagle · Marsh harrier · Goshawk · Bittern', '🐦 Wigeon · Curlew · Golden plover · Bluethroat', '🌸 Marsh sow-thistle · Marsh mallow · Glasswort · Sea lavender', '🐴 Cows · Sheep · Horses as grazers', '🔭 Hides on Groeneweg and Oudendijk'],
 'trail': ['Walk the <b>Korendijkse Slikken walk</b> from Goudswaard (Windlust mill).', 'Watch from <b>Oudendijk and Westdijk</b>; hide at the end of the Groeneweg.', 'Combine with <b>Beningerslikken</b>, the Spui or Numansdorp.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Only open 1 Jul–1 Nov; closed in breeding season and winter · 🚶 Natuurmonumenten walking route through the wooded part'
}))

C.append(mk.card(2011, 'Kreken Hoekse Waard', {
 'tags': ['Zuid-Holland · Hoeksche Waard (Strijen–Numansdorp)', 'Kreekrestanten als aders van het eiland · Oudeland van Strijen, Bekade Gorzen en oeverlanden · kluut, bergeend en zwarte stern', 'list 36 · no. 730'],
 'loc': '📍 Verspreid over de Hoeksche Waard: Oudeland van Strijen, Strijensas, Numansdorp · 470 km wandelnetwerk; vogelkijkhut Oude Gemaal; TOP’s bij Strijensas en Numansdorp',
 'desc': 'De <b>Kreken Hoekse Waard</b> zijn de aders van het eiland: restanten van getijdengeulen die het weidse polderland met dijken, wilgenbossen en bloemrijke graslanden dooraderen. Het mooiste complex is het <b>Oudeland van Strijen</b> van Staatsbosbeheer — De Keen, Vogeloase, Oude Gemaal, Lage Vliet en Dwarsche Vaart — met een goed bereikbare <b>vogelkijkhut in het Oude Gemaal</b> en de IJsvogelroute door open land, rietkragen en bosjes. Buitendijks langs het Hollands Diep liggen de <b>Oosterse Bekade Gorzen</b> met Oeverlanden en Hoogezandsche Gorzen: verruigd rietland, open water, geulen en wilgenbossen tussen Strijensas en Numansdorp. Fiets de <b>Land-van-Strijenroute</b> of de Krekenroutes langs polders, dijken en kreken — met kluut, bergeend en zwarte stern onderweg, de baltsvlucht van de veldleeuwerik erboven en fort Buitensluis (1793) bij de haven van Numansdorp als geschiedenis toe.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (grutto’s, kieviten en veldleeuwerik), aug–sep (zwarte stern en trekkers)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — balts en zang boven de kreken.',
 'why': ['Het <b>Oudeland van Strijen</b>: krekencomplex met vogelkijkhut.', 'De <b>Bekade Gorzen</b>: ongerepte buitendijkse natuur aan het Hollands Diep.', 'Kluut, bergeend en <b>zwarte stern</b> langs de routes.', 'Het <b>knooppuntennetwerk</b> (470 km) dwars door krekenland.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Grutto’s, kieviten en tureluurs</b> met baltsvluchten.', '<span class="months">Mei–Aug</span> 🐦 <b>Zwarte stern</b> boven geulen en kreken.', '<span class="months">Aug–Sep</span> 🦆 <b>Trekkers</b> op oeverlanden en gorzen.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleuren</b> van wilgenbossen en rietkragen.'],
 'wild': ['🐦 Kluut · Bergeend · Zwarte stern', '🔭 Vogelkijkhut Oude Gemaal (Strijen)', '🌿 Wilgenbossen en bloemrijke graslanden', '🏰 Fort Buitensluis (1793) bij Numansdorp', '🚲 Krekenroutes en Land van Strijen'],
 'trail': ['Wandel de <b>IJsvogelroute</b> door het Oudeland van Strijen.', 'Fiets de <b>Krekenroute Oost</b> vanaf TOP Numansdorp via Strijensas.', 'Bezoek de <b>vogelkijkhut Oude Gemaal</b> (parkeren Hoekseweg, Strijen).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Kreken en wilgenbossen beperkt toegankelijk — overzie vanaf dijken · 🚶 470 km netwerk; kaart bij VVV Hoeksche Waard'
}, {
 'tags': ['Zuid-Holland · Hoeksche Waard (Strijen–Numansdorp)', 'Creek remnants as veins of the island · Oudeland van Strijen, Bekade Gorzen and shore lands · avocet, shelduck and black tern', 'list 36 · no. 730'],
 'loc': '📍 Scattered across the Hoeksche Waard: Oudeland van Strijen, Strijensas, Numansdorp · 470-km walking network; Oude Gemaal bird hide; TOPs at Strijensas and Numansdorp',
 'desc': 'The <b>Hoeksche Waard Creeks</b> are the veins of the island: remnants of tidal channels veining the vast polderland of dikes, willow forests and flower-rich grasslands. The finest complex is the <b>Oudeland van Strijen</b> of Staatsbosbeheer — De Keen, Vogeloase, Oude Gemaal, Lage Vliet and Dwarsche Vaart — with an easily reached <b>bird hide in the Oude Gemaal</b> and the Kingfisher route through open land, reed fringes and copses. Outside the dikes along the Hollands Diep lie the <b>Oosterse Bekade Gorzen</b> with Oeverlanden and Hoogezandsche Gorzen: rank reedland, open water, channels and willow forests between Strijensas and Numansdorp. Cycle the <b>Land-van-Strijen route</b> or the Creek routes past polders, dikes and creeks — with avocet, shelduck and black tern along the way, the display flight of the skylark above and Buitensluis fort (1793) at Numansdorp harbour as history bonus.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (godwits, lapwings and skylark), Aug–Sep (black tern and migrants)<br>\\n    <b>Best time of day:</b> Morning — display and song above the creeks.',
 'why': ['The <b>Oudeland van Strijen</b>: creek complex with bird hide.', 'The <b>Bekade Gorzen</b>: pristine outer-dike nature on the Hollands Diep.', 'Avocet, shelduck and <b>black tern</b> along the routes.', 'The <b>junction network</b> (470 km) straight through creek land.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Godwits, lapwings and redshanks</b> with display flights.', '<span class="months">May–Aug</span> 🐦 <b>Black tern</b> above channels and creeks.', '<span class="months">Aug–Sep</span> 🦆 <b>Migrants</b> on shore lands and gorzen.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colours</b> of willow forests and reed fringes.'],
 'wild': ['🐦 Avocet · Shelduck · Black tern', '🔭 Oude Gemaal bird hide (Strijen)', '🌿 Willow forests and flower-rich grasslands', '🏰 Buitensluis fort (1793) at Numansdorp', '🚲 Creek routes and Land van Strijen'],
 'trail': ['Walk the <b>Kingfisher route</b> through the Oudeland van Strijen.', 'Cycle the <b>Krekenroute Oost</b> from TOP Numansdorp via Strijensas.', 'Visit the <b>Oude Gemaal bird hide</b> (parking Hoekseweg, Strijen).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Creeks and willow forests of limited access — survey from dikes · 🚶 470-km network; map at VVV Hoeksche Waard'
}))

C.append(mk.card(2012, 'Bosobjecten Hoekse Waard', {
 'tags': ['Zuid-Holland · Hoeksche Waard (Strijen–Oud-Beijerland)', 'Bospercelen van Staatsbosbeheer in het krekenland · Zuid-Beijerlandse Bos en Zuiddiepbos · IJsvogelroute en knooppunten', 'list 36 · no. 731'],
 'loc': '📍 Verspreid over de Hoeksche Waard: Zuid-Beijerlandse Bos, Zuiddiepbos, Oudeland van Strijen · bereikbaar per fiets en auto; 470 km wandelnetwerk',
 'desc': 'De <b>Bosobjecten Hoekse Waard</b> zijn de bospercelen waarmee <b>Staatsbosbeheer</b> het weidse krekenland aankleedt: het <b>Zuid-Beijerlandse Bos</b> en het <b>Zuiddiepbos</b> als groene kamers tussen de polders, aangevuld met het krekencomplex <b>Oudeland van Strijen</b>. Verken de polders te voet of per fiets — vergeet vooral de verrekijker niet: in het voorjaar hoor je grutto’s, kieviten en tureluurs en zie je de baltsvlucht van de veldleeuwerik boven bloemrijke graslanden. De <b>IJsvogelroute</b> ontdekt de noordkant van het Oudeland door open landschap, rietkragen, bosjes en agrarisch gebied; de <b>vogelkijkhut in het Oude Gemaal</b> is goed bereikbaar met parkeerplaats aan de Hoekseweg. De toegang tot kreken, wilgenbossen en graslanden is beperkt, maar vanaf polderwegen en dijken — en via het 470 kilometer lange <b>knooppuntennetwerk</b> — zijn ze prachtig te overzien. Weids, waterrijk en vol vogels.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels en ijsvogel), sep–okt (herfstkleuren)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang boven bosjes en kreken.',
 'why': ['Het <b>Zuid-Beijerlandse Bos en Zuiddiepbos</b>: groene kamers in de polder.', 'De <b>IJsvogelroute</b> door het Oudeland van Strijen.', 'De <b>vogelkijkhut Oude Gemaal</b> met parkeerplaats ernaast.', 'Het <b>knooppuntennetwerk</b>: stel je eigen krekenroute samen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogelkoor</b> en baltsvluchten boven het land.', '<span class="months">Mei–Aug</span> 🐦 <b>Ijsvogel</b> langs vlieten en vaarten.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleuren</b> in bosjes en wilgenbossen.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b> op kreken en graslanden.'],
 'wild': ['🌳 Zuid-Beijerlandse Bos · Zuiddiepbos', '🐦 Ijsvogel van vliet en vaart', '🔭 Vogelkijkhut Oude Gemaal', '🐦 Grutto · Kievit · Tureluur · Veldleeuwerik', '🚶 470 km knooppuntennetwerk'],
 'trail': ['Wandel de <b>IJsvogelroute</b> aan de noordkant van het Oudeland.', 'Stel via de <b>routeplanner</b> een knooppuntenroute langs kreken samen.', 'Combineer met de <b>Korendijkse Slikken</b>, Strijensas of Numansdorp.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Verharde polderwegen wel, onverharde paden niet rolstoeltoegankelijk · 🚶 Kaart gratis bij VVV Hoeksche Waard'
}, {
 'tags': ['Zuid-Holland · Hoeksche Waard (Strijen–Oud-Beijerland)', 'Forest parcels of Staatsbosbeheer in creek land · Zuid-Beijerlandse Bos and Zuiddiepbos · Kingfisher route and junctions', 'list 36 · no. 731'],
 'loc': '📍 Scattered across the Hoeksche Waard: Zuid-Beijerlandse Bos, Zuiddiepbos, Oudeland van Strijen · reachable by bike and car; 470-km walking network',
 'desc': 'The <b>Hoeksche Waard Forest Objects</b> are the forest parcels with which <b>Staatsbosbeheer</b> dresses the vast creek land: the <b>Zuid-Beijerlandse Bos</b> and the <b>Zuiddiepbos</b> as green rooms among the polders, complemented by the <b>Oudeland van Strijen</b> creek complex. Explore the polders on foot or by bike — and do bring your binoculars: in spring you hear godwits, lapwings and redshanks and see the display flight of the skylark above flower-rich grasslands. The <b>Kingfisher route</b> discovers the northern side of the Oudeland through open landscape, reed fringes, copses and farmland; the <b>bird hide in the Oude Gemaal</b> is easily reached with a car park on the Hoekseweg. Access to creeks, willow forests and grasslands is limited, but from polder roads and dikes — and via the 470-kilometre <b>junction network</b> — they can be splendidly surveyed. Vast, watery and full of birds.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds and kingfisher), Sep–Oct (autumn colours)<br>\\n    <b>Best time of day:</b> Morning — song above copses and creeks.',
 'why': ['The <b>Zuid-Beijerlandse Bos and Zuiddiepbos</b>: green rooms in the polder.', 'The <b>Kingfisher route</b> through the Oudeland van Strijen.', 'The <b>Oude Gemaal bird hide</b> with car park beside it.', 'The <b>junction network</b>: compose your own creek route.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow-bird chorus</b> and display flights above the land.', '<span class="months">May–Aug</span> 🐦 <b>Kingfisher</b> along vliets and waterways.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colours</b> in copses and willow forests.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b> on creeks and grasslands.'],
 'wild': ['🌳 Zuid-Beijerlandse Bos · Zuiddiepbos', '🐦 Kingfisher of vliet and waterway', '🔭 Oude Gemaal bird hide', '🐦 Godwit · Lapwing · Redshank · Skylark', '🚶 470-km junction network'],
 'trail': ['Walk the <b>Kingfisher route</b> on the northern side of the Oudeland.', 'Compose a junction route along creeks via the <b>route planner</b>.', 'Combine with the <b>Korendijkse Slikken</b>, Strijensas or Numansdorp.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Paved polder roads yes, unpaved paths not wheelchair accessible · 🚶 Map free at VVV Hoeksche Waard'
}))

C.append(mk.card(2013, 'De Hennepakkers', {
 'tags': ['Zuid-Holland/Utrecht · de Waard (Krimpener- en Lopikerwaard)', 'Leestekens van het hennepverleden · kleine percelen met brede sloten en knotwilgen · touw en zeildoek voor de scheepvaart', 'list 36 · no. 732'],
 'loc': '📍 Verspreid in Krimpener- en Lopikerwaard, bij boerderijen (o.a. Lekkerkerk) · geen gemarkeerd terrein; herkenbaar in het landschap langs kaden en wandelroutes',
 'desc': '<b>De Hennepakkers</b> zijn geen terrein maar een <b>leesteken van het landschap</b> — en daarom registreert deze kaart de naam eerlijk als zodanig. Tussen de zeventiende en de negentiende eeuw teelden boeren op kleine, door sloten omgeven percelen naast de boerderij <b>hennep</b> voor touw en zeildoek van de scheepvaart; de omvangrijke scheepsbouw schreeuwde om touw. De teelt was intensief: de akkertjes slokten een groot deel van de mest op, voor de bewerking was veel water nodig — vandaar de <b>brede sloten</b> eromheen — en tegen de wind plantte men er <b>knotwilgen</b> omheen. In de waard, rond Lekkerkerk, beheerste de hennepteelt het boerenbeeld tot ver in de twintigste eeuw. De voormalige akkertjes zijn nog vaak goed te herkennen: zoek langs de kaden — bijvoorbeeld de <b>Bergvlietse Kade</b> — naar kleine, hooggelegen percelen met knotbomenrijen. Wie het ziet, leest het verleden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (groene knotwilgen en leesbaar landschap)<br>\\n    <b>Beste tijd van de dag:</b> Middag — licht op sloten en knotbomen.',
 'why': ['Een <b>leesteken</b>: het hennepverleden afleesbaar in het land.', 'De <b>brede sloten en knotwilgen</b> als handtekening van de teelt.', 'Touw en zeildoek voor de <b>Gouden-Eeuwse scheepvaart</b>.', 'Nog <b>herkenbaar</b>: kleine percelen bij oude boerderijen.'],
 'phen': ['<span class="months">Mei–Sep</span> 🌿 <b>Groene knotwilgen</b> rond de voormalige akkertjes.', '<span class="months">Heel jaar</span> 📖 <b>Leesbaar landschap</b> langs kaden en boerderijen.', '<span class="months">Okt–Mrt</span> 🌳 <b>Knotvormen</b> als silhouetten in de waard.', '<span class="months">Feb–Mrt</span> ✂️ <b>Knotseizoen</b>: vrijwilligers aan het werk.'],
 'wild': ['📖 Leesteken van het hennepverleden', '🌳 Knotwilgen als windvang en droogrek', '💧 Brede sloten voor de bewerking', '🏡 Kleine percelen bij de boerderij', '🧵 Touw en zeildoek voor de vloot'],
 'trail': ['Zoek hennepakkers langs de <b>Bergvlietse Kade</b> en het Kraamvrouwenpad.', 'Wandel de <b>Groene Wissel Vlist</b> door de Krimpenerwaard.', 'Combineer met <b>Haastrecht</b>, Vlist of de Zouweboezem.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen terrein — privégrond respecteren, vanaf paden kijken · 🚶 Kaden en Klompenpaden in de waard'
}, {
 'tags': ['Zuid-Holland/Utrecht · de Waard (Krimpener- en Lopikerwaard)', 'Legible traces of the hemp past · small parcels with broad ditches and pollard willows · rope and sailcloth for shipping', 'list 36 · no. 732'],
 'loc': '📍 Scattered in Krimpener- en Lopikerwaard, near farms (including Lekkerkerk) · no marked terrain; recognisable in the landscape along embankments and walking routes',
 'desc': 'The <b>Hennepakkers</b> are not a terrain but a <b>legible trace of the landscape</b> — and so this card honestly records the name as such. Between the seventeenth and nineteenth centuries farmers grew <b>hemp</b> on small, ditch-enclosed parcels beside the farm for rope and sailcloth of shipping; the vast shipbuilding industry screamed for rope. Cultivation was intensive: the little fields swallowed much of the manure, processing needed lots of water — hence the <b>broad ditches</b> around them — and <b>pollard willows</b> were planted against the wind. In the waard, around Lekkerkerk, hemp cultivation dominated the farming scene well into the twentieth century. The former little fields are often still recognisable: look along the embankments — the <b>Bergvlietse Kade</b>, for instance — for small, raised parcels with pollard rows. Whoever sees it, reads the past.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (green pollards and legible landscape)<br>\\n    <b>Best time of day:</b> Afternoon — light on ditches and pollards.',
 'why': ['A <b>legible trace</b>: the hemp past readable in the land.', 'The <b>broad ditches and pollard willows</b> as the signature of cultivation.', 'Rope and sailcloth for <b>Golden-Age shipping</b>.', 'Still <b>recognisable</b>: small parcels at old farms.'],
 'phen': ['<span class="months">May–Sep</span> 🌿 <b>Green pollard willows</b> around the former little fields.', '<span class="months">All year</span> 📖 <b>Legible landscape</b> along embankments and farms.', '<span class="months">Oct–Mar</span> 🌳 <b>Pollard shapes</b> as silhouettes in the waard.', '<span class="months">Feb–Mar</span> ✂️ <b>Pollarding season</b>: volunteers at work.'],
 'wild': ['📖 Legible trace of the hemp past', '🌳 Pollard willows as windbreak and drying rack', '💧 Broad ditches for processing', '🏡 Small parcels at the farm', '🧵 Rope and sailcloth for the fleet'],
 'trail': ['Look for hemp parcels along the <b>Bergvlietse Kade</b> and Kraamvrouwenpad.', 'Walk the <b>Groene Wissel Vlist</b> through the Krimpenerwaard.', 'Combine with <b>Haastrecht</b>, Vlist or the Zouweboezem.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No terrain — respect private land, view from paths · 🚶 Embankments and Klompenpaden in the waard'
}))

C.append(mk.card(2014, 'Bergvlietse Kade', {
 'tags': ['Zuid-Holland · Vlist (Krimpenerwaard)', 'Ruim 3 km oudste onverharde kade · grens van polder Vlist Westzijde · vlonderpad en Groene Wissel', 'list 36 · no. 733'],
 'loc': '📍 Tussen Bilwijk en Geerpad bij Vlist (Krimpenerwaard) · officieel open sinds feb 2014; Groene Wissel Vlist (10 km); Kraamvrouwenpad (1732) ernaast',
 'desc': 'De <b>Bergvlietse Kade</b> bij <b>Vlist</b> is ruim drie kilometer oer-Hollands polderlandschap — een van de <b>oudste onverharde kades</b> van de Krimpenerwaard, aangelegd als grens van de ontginning van <b>polder Vlist Westzijde</b>. Aan beide kanten staan elzen, essen en wilgen; je kijkt kilometers ver over water, weiland en watervogels, met de <b>boezemmolen van Haastrecht</b> als herkenningspunt in de verte. Sinds februari <b>2014</b> is de kade officieel open — met een ludieke oplossing waar geen overeenstemming met een eigenaar kwam: een slingerend <b>vlonderpad</b> over het water, wiebelig met een groep, onmerkbaar alleen. De kade is het mooiste pad van de <b>Groene Wissel Vlist</b> (10 km) door houtkades, boerderijen en weiland; ernaast begint het <b>Kraamvrouwenpad</b> uit 1732, waarover de vroedvrouw van Stolwijk snel in Vlist kon zijn. Herfst met paddenstoelen, lente met weidevogels — oktober is de maand van het onverharde pad.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Okt</b> (maand van het onverharde pad; herfstkleuren), apr–mei (weidevogels)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven water en weiland.',
 'why': ['Een van de <b>oudste onverharde kades</b> van de Krimpenerwaard.', 'Het <b>vlonderpad</b>: een wiebelige, ludieke oplossing.', 'Het <b>Kraamvrouwenpad uit 1732</b> ernaast.', 'Het <b>weidse uitzicht</b>: kilometers water, weiland en vogels.'],
 'phen': ['<span class="months">Okt</span> 🍂 <b>Herfst op de kade</b>: verkleuring en paddenstoelen.', '<span class="months">Apr–Mei</span> 🎵 <b>Weidevogels</b> langs water en weiland.', '<span class="months">Heel jaar</span> 🚶 <b>Struinen</b> over kade en vlonderpad.', '<span class="months">Mei–Sep</span> 🌿 <b>Groene tunnel</b> van els, es en wilg.'],
 'wild': ['🌿 Els · Es · Wilg langs de kade', '🐦 Weide- en watervogels van de polder', '🍄 Herfstpaddenstoelen', '🌬️ Boezemmolen van Haastrecht in de verte', '🥾 Vlonderpad over het water'],
 'trail': ['Wandel de <b>Groene Wissel Vlist</b> (10 km) met de kade als mooiste deel.', 'Loop van <b>Bilwijk naar Geerpad</b> over kade en vlonderpad.', 'Neem het <b>Kraamvrouwenpad</b> (1,4 km) naar de West-Vlisterdijk.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Vlonderpad wiebelig met groepen; soms modderig · 🚶 Onverhard; niet 100% toegankelijk'
}, {
 'tags': ['Zuid-Holland · Vlist (Krimpenerwaard)', 'Over 3 km of oldest unpaved embankment · boundary of polder Vlist Westzijde · boardwalk and Green Exchange walk', 'list 36 · no. 733'],
 'loc': '📍 Between Bilwijk and Geerpad near Vlist (Krimpenerwaard) · officially open since Feb 2014; Groene Wissel Vlist (10 km); 1732 Kraamvrouwenpad alongside',
 'desc': 'The <b>Bergvlietse Kade</b> near <b>Vlist</b> is over three kilometres of primal Dutch polder landscape — one of the <b>oldest unpaved embankments</b> of the Krimpenerwaard, laid out as the boundary of the reclamation of <b>polder Vlist Westzijde</b>. Alders, ashes and willows stand on both sides; you look for kilometres across water, meadow and waterfowl, with the <b>drainage mill of Haastrecht</b> as a landmark in the distance. Since February <b>2014</b> the embankment has been officially open — with a playful solution where no agreement with one owner was reached: a winding <b>boardwalk</b> over the water, wobbly with a group, unnoticeable alone. The embankment is the finest path of the <b>Groene Wissel Vlist</b> (10 km) through wooded embankments, farms and meadows; alongside starts the <b>Kraamvrouwenpad</b> of 1732, by which the midwife of Stolwijk could quickly reach Vlist. Autumn with fungi, spring with meadow birds — October is the month of the unpaved path.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Oct</b> (month of the unpaved path; autumn colours), Apr–May (meadow birds)<br>\\n    <b>Best time of day:</b> Morning — mist above water and meadow.',
 'why': ['One of the <b>oldest unpaved embankments</b> of the Krimpenerwaard.', 'The <b>boardwalk</b>: a wobbly, playful solution.', 'The <b>1732 Kraamvrouwenpad</b> alongside.', 'The <b>wide view</b>: kilometres of water, meadow and birds.'],
 'phen': ['<span class="months">Oct</span> 🍂 <b>Autumn on the embankment</b>: colouring and fungi.', '<span class="months">Apr–May</span> 🎵 <b>Meadow birds</b> along water and meadow.', '<span class="months">All year</span> 🚶 <b>Roaming</b> over embankment and boardwalk.', '<span class="months">May–Sep</span> 🌿 <b>Green tunnel</b> of alder, ash and willow.'],
 'wild': ['🌿 Alder · Ash · Willow along the embankment', '🐦 Meadow and water birds of the polder', '🍄 Autumn fungi', '🌬️ Haastrecht drainage mill in the distance', '🥾 Boardwalk over the water'],
 'trail': ['Walk the <b>Groene Wissel Vlist</b> (10 km) with the embankment as its finest part.', 'Walk from <b>Bilwijk to Geerpad</b> over embankment and boardwalk.', 'Take the <b>Kraamvrouwenpad</b> (1.4 km) to the West-Vlisterdijk.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Boardwalk wobbly with groups; sometimes muddy · 🚶 Unpaved; not 100% accessible'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(2014)
mk.check()
