# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2045, 'Schaayk', {
 'tags': ['Vijfheerenlanden · ten oosten van Leerdam aan de Diefdijk', '78 hectare oude boomgaarden, grienden, rietputten en schrale graslanden · kamsalamander en heikikker · Zuid-Hollands Landschap', 'list 36 · no. 764'],
 'loc': '📍 Diefdijk ten oosten van Leerdam — overzien vanaf de Diefdijk en de Donkere Kade · combi met Schoonrewoerdse Wiel (knooppunt 58) en De Waai; Kamsalamanderroute 6,5/11,5 km',
 'desc': '<b>Schaayk</b> is het grootste natuurgebied van het <b>Zuid-Hollands Landschap</b> langs de <b>Diefdijk</b>: 78 hectare oude landschapselementen in een kleinschalige mozaïek — <b>bosjes, grienden, sloten, rietputten, oude boomgaarden en schrale graslanden</b>, alles door elkaar geworpen als in een oud boerenlandschap dat de tijd vergat. In het voorjaar staat het geel van de <b>dotterbloemen</b>, bloeit <b>veenpluis</b> op de natste plekken, kleurt de <b>ratelaar</b> de hooilanden en groeit het <b>moeraskartelblad</b> — de voedselarme sloten zijn het leefgebied van de <b>kamsalamander</b>, in de zomer klinkt de <b>heikikker</b> (van die grijze kikker met de groene rug). Boswachter <b>René Garskamp</b> noemt als geliefde soorten de <b>blauwborst</b> en de <b>sprinkhaanrietzanger</b> — en vertelt over <b>baltsende watersnippen</b> die in het vroege voorjaar met wapperende vleugels boven de natte landen bolderen. Het gebied is het beste te overzien vanaf de <b>Diefdijk</b> zelf en vanaf de <b>Donkere Kade</b>, die er 2 kilometer onverhard langs voert; samen met het Schoonrewoerdse Wiel en De Waai vormt Schaayk de groene long aan de zijkant van de dijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (dotterbloemen, salamanders, rietzang), mrt–apr (baltsende watersnippen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — rietvogels en dauw langs de Donkere Kade.',
 'why': ['De <b>mozaïek-structuur</b>: bosjes, grienden, rietputten, boomgaarden en schrale landen door elkaar.', '<b>Dotterbloem, veenpluis, ratelaar en moeraskartelblad</b> in één voorjaar.', 'De <b>kamsalamander en heikikker</b> van de voedselarme sloten.', 'De <b>baltsende watersnippen</b> en de blauwborst als trots van de boswachter.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🎵 <b>Baltsende watersnippen</b> boven de natte landen.', '<span class="months">Apr–Mei</span> 🌼 <b>Dotterbloemen en veenpluis</b> in bloei.', '<span class="months">Mei–Jun</span> 🦎 <b>Kamsalamander</b> in de schrale sloten.', '<span class="months">Jun–Jul</span> 🐸 <b>Heikikker</b> in de zomernacht.'],
 'wild': ['🌸 Dotterbloem · Veenpluis · Ratelaar · Moeraskartelblad', '🦎 Kamsalamander · Heikikker', '🐦 Blauwborst · Sprinkhaanrietzanger · Watersnip', '🌳 Oude boomgaarden en grienden', '💧 Rietputten en voedselarme sloten'],
 'trail': ['Overzie Schaayk vanaf de <b>Diefdijk</b> en de <b>Donkere Kade</b> (2 km onverhard).', 'Loop de <b>Kamsalamanderroute</b> (6,5 of 11,5 km) langs de ZHL-gebieden.', 'Combineer met het <b>Schoonrewoerdse Wiel</b> (knooppunt 58) voor één grote dijktocht.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen ontsluitingspaden door het terrein — vanaf dijk en kade kijken · 🚶 Knooppuntennetwerk Vijfheerenlanden'
}, {
 'tags': ['Vijfheerenlanden · east of Leerdam on the Diefdijk', '78 hectares of old orchards, copses, reed pits and nutrient-poor grasslands · warty newt and moor frog · Zuid-Hollands Landschap', 'list 36 · no. 764'],
 'loc': '📍 Diefdijk east of Leerdam — surveyed from the Diefdijk and the Donkere Kade · combine with Schoonrewoerdse Wiel (node 58) and De Waai; Warty Newt route 6.5/11.5 km',
 'desc': '<b>Schaayk</b> is the largest reserve of the <b>Zuid-Hollands Landschap</b> along the <b>Diefdijk</b>: 78 hectares of old landscape elements in a small-scale mosaic — <b>little woods, copses, ditches, reed pits, old orchards and nutrient-poor grasslands</b>, all thrown together like an old farming landscape that time forgot. In spring the yellow of the <b>marsh marigolds</b> stands out, <b>cottongrass</b> flowers on the wettest spots, <b>yellow rattle</b> colours the hay meadows and <b>marsh lousewort</b> grows — the nutrient-poor ditches are the habitat of the <b>warty newt</b>, and in summer the <b>moor frog</b> calls (that grey frog with the green back). Ranger <b>René Garskamp</b> names the <b>bluethroat</b> and the <b>grasshopper warbler</b> as his favourites — and tells of <b>displaying common snipe</b> that in early spring drum with quivering wings above the wet lands. The area is best surveyed from the <b>Diefdijk</b> itself and from the <b>Donkere Kade</b>, which runs 2 kilometres unpaved along it; together with the Schoonrewoerdse Wiel and De Waai, Schaayk forms the green lung at the dike’s side.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (marsh marigolds, newts, reed song), Mar–Apr (displaying snipe)<br>\\n    <b>Best time of day:</b> Morning — reed birds and dew along the Donkere Kade.',
 'why': ['The <b>mosaic structure</b>: woods, copses, reed pits, orchards and poor grasslands side by side.', '<b>Marsh marigold, cottongrass, rattle and marsh lousewort</b> in one spring.', 'The <b>warty newt and moor frog</b> of the nutrient-poor ditches.', 'The <b>displaying snipe</b> and the bluethroat as the ranger’s pride.'],
 'phen': ['<span class="months">Mar–Apr</span> 🎵 <b>Displaying snipe</b> above the wet lands.', '<span class="months">Apr–May</span> 🌼 <b>Marsh marigolds and cottongrass</b> in flower.', '<span class="months">May–Jun</span> 🦎 <b>Warty newt</b> in the poor ditches.', '<span class="months">Jun–Jul</span> 🐸 <b>Moor frog</b> in the summer night.'],
 'wild': ['🌸 Marsh marigold · Cottongrass · Yellow rattle · Marsh lousewort', '🦎 Warty newt · Moor frog', '🐦 Bluethroat · Grasshopper warbler · Common snipe', '🌳 Old orchards and copses', '💧 Reed pits and nutrient-poor ditches'],
 'trail': ['Survey Schaayk from the <b>Diefdijk</b> and the <b>Donkere Kade</b> (2 km unpaved).', 'Walk the <b>Warty Newt route</b> (6.5 or 11.5 km) past the ZHL reserves.', 'Combine with the <b>Schoonrewoerdse Wiel</b> (node 58) for one grand dike tour.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No access paths through the terrain — view from dike and embankment · 🚶 Vijfheerenlanden node network'
}, n2k='Lingegebied &amp; Diefdijk-Zuid — Schaayk ligt in de drassige strook langs de Diefdijk van Habitatrichtlijngebied nr. 70: grienden, elzenbroek en voedselarme wateren met kamsalamander als doelsoort.',
 n2k_en='Lingegebied &amp; Diefdijk-Zuid — Schaayk lies in the wet strip along the Diefdijk of Habitats Directive site no. 70: copses, alder carr and nutrient-poor waters with warty newt as target species.'))

C.append(mk.card(2046, 'Kedichem', {
 'tags': ['Vijfheerenlanden · ten westen van Leerdam aan de Linge', '29 hectare kamgrasweiden en zeggeland in de Linge-binnenbocht · margrieten en drie zeggesoorten · fitis en tjiftjaf · Zuid-Hollands Landschap', 'list 36 · no. 765'],
 'loc': '📍 Ten westen van Leerdam, in de binnenbocht van de Linge bij Kedichem · te voet via de Lingedijk en het knooppuntennetwerk; combi met het Lingepad ( LAW 6.1) langs de rivier',
 'desc': 'Bij <b>Kedichem</b>, waar de <b>Linge</b> zich in een trage bocht om het dorp slingert, beheert het <b>Zuid-Hollands Landschap</b> 29 hectare oud rivierkleilandschap in twee helften. In het <b>noorden</b> liggen <b>kamgrasweiden</b> — bloemrijke, nooit herschapen graslanden die in juni wit kleuren van de <b>margrieten</b> en roze van de <b>knopkruiden</b>; in het <b>zuiden</b>, in de sterk aangeslibde binnenbocht van de rivier, ligt <b>zeggeland</b>: natte, onaandoenlijke percelen met <b>scherpe zegge, blonde zegge en tweerijige zegge</b> — drie soorten die elk hun eigen vochtigheidsgraad verkiezen en samen de overgang van rivier naar land markeren. Het beheer is eenvoudig en oud: <b>maaien en hooien</b>, en in augustus <b>nabeweiden met jongvee</b> dat de naweeing van het grasland verzorgt. Vogels als <b>fitis en tjiftjaf</b> profiteren van de insectenrijke randen; in de winter staat de binnenbocht vol watervogels. Bezoekers volgen de <b>Lingedijk</b>: aan de ene kant de rivier, aan de andere het reservaat — en wie doorloopt, komt vanzelf bij <b>Huis te Kedichem</b> en zijn eeuwenoude bomen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Jul</b> (margrietenweiden), apr–mei (zangvogels), nov–feb (watervogels in de bocht)<br>\\n    <b>Beste tijd van de dag:</b> Avond — de Linge in de undergang-kleuren.',
 'why': ['De <b>kamgrasweiden</b> met margrieten en knopkruid — nooit herschapen grasland.', 'Het <b>zeggeland</b> in de binnenbocht: scherpe, blonde en tweerijige zegge.', 'Het <b>oude beheer</b>: maaien, hooien en nabeweiden met jongvee.', 'De <b>Lingedijk</b> als wandelader langs rivier en reservaat.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Margrieten</b> wit in de kamgrasweiden.', '<span class="months">Apr–Mei</span> 🎵 <b>Fitis en tjiftjaf</b> in de hagen.', '<span class="months">Aug</span> 🐄 <b>Nabeweiding</b> met jongvee op de landen.', '<span class="months">Nov–Feb</span> 🪿 <b>Watervogels</b> in de binnenbocht.'],
 'wild': ['🌼 Margriet · Knopkruid · Kamgras', '🌿 Scherpe zegge · Blonde zegge · Tweerijige zegge', '🐦 Fitis · Tjiftjaf', '🐄 Jongvee als nabeweider in augustus', '🌊 Linge-binnenbocht sterk aangeslibd'],
 'trail': ['Wandel de <b>Lingedijk</b> tussen Leerdam en Kedichem langs het reservaat.', 'Volg het <b>Lingepad (LAW 6.1)</b> voor de lange tocht langs de rivier.', 'Combineer met <b>Huis te Kedichem</b> en de Betuwse dijkdorpen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Percelen niet vrij te betreden — dijk volgen · 🚶 Knooppuntennetwerk; Lingepad'
}, {
 'tags': ['Vijfheerenlanden · west of Leerdam on the Linge', '29 hectares of crested dog-tail meadows and sedge beds in the Linge bend · ox-eye daisies and three sedge species · willow warbler and chiffchaff · Zuid-Hollands Landschap', 'list 36 · no. 765'],
 'loc': '📍 West of Leerdam, in the inner bend of the Linge at Kedichem · on foot via the Lingedijk and the node network; combine with the Lingepad (LAW 6.1) along the river',
 'desc': 'At <b>Kedichem</b>, where the <b>Linge</b> meanders in a slow bend around the village, the <b>Zuid-Hollands Landschap</b> manages 29 hectares of old river-clay landscape in two halves. In the <b>north</b> lie <b>crested dog-tail meadows</b> — flower-rich grasslands never re-seeded, white in June with <b>ox-eye daisies</b> and pink with <b>knautia</b>; in the <b>south</b>, in the heavily silted inner bend of the river, lies <b>sedge land</b>: wet, impenetrable parcels with <b>sharp-headed sedge, remote sedge and glaucous sedge</b> — three species that each prefer their own moisture level and together mark the transition from river to land. The management is simple and old: <b>mowing and haymaking</b>, and in August <b>after-grazing with young stock</b> that tidies the aftermath. Birds like <b>willow warbler and chiffchaff</b> profit from the insect-rich edges; in winter the inner bend fills with waterfowl. Visitors follow the <b>Lingedijk</b>: the river on one side, the reserve on the other — and continuing on you reach <b>Huis te Kedichem</b> with its centuries-old trees.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Jul</b> (daisy meadows), Apr–May (songbirds), Nov–Feb (waterfowl in the bend)<br>\\n    <b>Best time of day:</b> Evening — the Linge in sunset colours.',
 'why': ['The <b>crested dog-tail meadows</b> with daisies and knautia — never re-seeded grassland.', 'The <b>sedge land</b> in the inner bend: sharp-headed, remote and glaucous sedge.', 'The <b>old management</b>: mowing, haymaking and after-grazing with young stock.', 'The <b>Lingedijk</b> as walking artery along river and reserve.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Ox-eye daisies</b> white in the dog-tail meadows.', '<span class="months">Apr–May</span> 🎵 <b>Willow warbler and chiffchaff</b> in the hedges.', '<span class="months">Aug</span> 🐄 <b>After-grazing</b> with young stock on the lands.', '<span class="months">Nov–Feb</span> 🪿 <b>Waterfowl</b> in the inner bend.'],
 'wild': ['🌼 Ox-eye daisy · Knautia · Crested dog-tail', '🌿 Sharp-headed sedge · Remote sedge · Glaucous sedge', '🐦 Willow warbler · Chiffchaff', '🐄 Young cattle as after-grazers in August', '🌊 Linge inner bend heavily silted'],
 'trail': ['Walk the <b>Lingedijk</b> between Leerdam and Kedichem past the reserve.', 'Follow the <b>Lingepad (LAW 6.1)</b> for the long haul along the river.', 'Combine with <b>Huis te Kedichem</b> and the Betuwe dike villages.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Parcels not free to enter — follow the dike · 🚶 Node network; Lingepad'
}))

C.append(mk.card(2047, 'Linge Oevers-West', {
 'tags': ['Zuid-Holland · Linge-oevers tussen Arkel en Gellicum (Westelijke Betuwe)', 'Westelijke helft van SBB-Lingeoevers (436 ha) · oeverlanden, tichelterreinen en bloemrijke hooilanden · 12 Rode-Lijst-broedvogels (2019) · Natura 2000 Lingegebied', 'list 36 · no. 766'],
 'loc': '📍 Tussen Arkel en Gellicum langs de Linge — SBB-deelgebied van de Lingeoevers · wandelen via de Lingedijk en het Lingepad (LAW 6.1); combi met Lingebos bij Vuren',
 'desc': 'De <b>Linge Oevers-West</b> vormen samen met hun oostelijke voortzetting het SBB-complex <b>‘Lingeoevers’</b>: 436 hectare oeverlanden tussen <b>Arkel en Gellicum</b>, waaronder ook het <b>Lingebos</b> en het Zoelense Bos vallen. Het westelijke deel omvat de <b>natuurlijke oevers</b> van de trage rivier: <b>tichelterreinen</b> — oude kleinschalige klei- en tickegroeves die nu moerasjes zijn —, <b>bloemrijke hooilanden</b>, rietkragen en knotwilgen-rijen, met daar de <b>bever</b> die zijn burchten graaft in de steile wallen en de <b>bittervoorn</b> die zijn eitjes deponeert in riviermosselen. In de broedvogelkartering van <b>2019</b> werden in het complex <b>12 soorten van de Rode Lijst</b> vastgesteld — van <b>blauwborst</b> in de rietkragen via <b>purperreiger</b> en <b>bruine kiekendief</b> tot <b>woudaapje</b> — een indice dat het beheer van Staatsbosbeheer (niet of laat maaien, plas-dras in de winter, extensieve begrazing) werkt. In de zomer bloeien <b>orchideeën</b> op de tichelmoerassen, in de herfst staan de hooilanden vol <b>herfstaster</b> en in het voorjaar kleuren de fruitboomgaarden van de Betuwe de dijk. De <b>Lingedijk</b> voert er als een lint doorheen: links de rivier, rechts de natuur — en overal de geur van vers gemaaid hooi.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jul</b> (hooilanden in bloei, orchideeën), okt (herfstaster), nov–feb (watervogels, beversporen)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend of schemering — bevers in de weer.',
 'why': ['De <b>tichelterreinen</b>: oude kleigroeves als nieuwe moerassen met orchideeën.', '<b>12 Rode-Lijst-broedvogels</b> in de kartering van 2019 — van blauwborst tot woudaapje.', 'De <b>bever en bittervoorn</b> van de Linge-oevers.', 'De <b>Lingedijk en het Lingepad</b> als doorlopende wandeladers.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> op de tichelmoerassen.', '<span class="months">Jun–Jul</span> 🌼 <b>Hooilanden</b> op hun kleurrijkst.', '<span class="months">Okt</span> 💜 <b>Herfstaster</b> langs de dijk.', '<span class="months">Nov–Feb</span> 🦫 <b>Bever-sporen</b> langs de oevers.'],
 'wild': ['🐦 Blauwborst · Purperreiger · Bruine kiekendief · Woudaapje', '🦫 Bever in de steile oevers', '🐟 Bittervoorn · Riviermossels', '🌸 Orchideeën op tichelmoerassen · Herfstaster', '🦆 Watervogels op de Linge in de winter'],
 'trail': ['Wandel de <b>Lingedijk</b> tussen Arkel en Gellicum door het oevers-landschap.', 'Volg het <b>Lingepad (LAW 6.1)</b> van Bronckhorst naar Gorinchem.', 'Combineer met het <b>Lingebos</b> (kaart 2048) voor een volle dag Linge-natuur.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Oeverlanden deels drassig — dijk en paden volgen · 🚶 Knooppuntennetwerk; Lingepad'
}, {
 'tags': ['Zuid-Holland · Linge banks between Arkel and Gellicum (western Betuwe)', 'Western half of the Dutch Forestry Lingeoevers (436 ha) · banklands, brick-clay pits and flower-rich hay meadows · 12 Red List breeding birds (2019) · Natura 2000 Lingegebied', 'list 36 · no. 766'],
 'loc': '📍 Between Arkel and Gellicum along the Linge — SBB sub-area of the Lingeoevers · walk via the Lingedijk and the Lingepad (LAW 6.1); combine with the Lingebos at Vuren',
 'desc': 'The <b>Linge Banks-West</b> form, with their eastern continuation, the Staatsbosbeheer complex <b>‘Lingeoevers’</b>: 436 hectares of banklands between <b>Arkel and Gellicum</b>, which also include the <b>Lingebos</b> and the Zoelense Bos. The western part takes in the <b>natural banks</b> of the slow river: <b>brick-clay pits</b> — old small-scale clay diggings now turned marsh —, <b>flower-rich hay meadows</b>, reed fringes and pollard rows, with the <b>beaver</b> digging its lodges in the steep banks and the <b>bitterling</b> depositing its eggs in river mussels. The <b>2019</b> breeding bird survey recorded <b>12 Red List species</b> in the complex — from <b>bluethroat</b> in the reed via <b>purple heron</b> and <b>marsh harrier</b> to <b>little bittern</b> — a sign that the forestry commission’s management (no or late mowing, winter flash-flooding, extensive grazing) works. In summer <b>orchids</b> flower on the clay-pit marshes, in autumn the hay meadows stand full of <b>Michaelmas daisies</b> and in spring the Betuwe orchards colour the dike. The <b>Lingedijk</b> runs through it like a ribbon: river on the left, nature on the right — and everywhere the scent of fresh-mown hay.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (hay meadows in flower, orchids), Oct (Michaelmas daisy), Nov–Feb (waterfowl, beaver tracks)<br>\\n    <b>Best time of day:</b> Early morning or dusk — beavers at work.',
 'why': ['The <b>brick-clay pits</b>: old clay diggings as new marshes with orchids.', '<b>12 Red List breeding birds</b> in the 2019 survey — from bluethroat to little bittern.', 'The <b>beaver and bitterling</b> of the Linge banks.', 'The <b>Lingedijk and Lingepad</b> as continuous walking arteries.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Orchids</b> on the clay-pit marshes.', '<span class="months">Jun–Jul</span> 🌼 <b>Hay meadows</b> at their most colourful.', '<span class="months">Oct</span> 💜 <b>Michaelmas daisies</b> along the dike.', '<span class="months">Nov–Feb</span> 🦫 <b>Beaver tracks</b> along the banks.'],
 'wild': ['🐦 Bluethroat · Purple heron · Marsh harrier · Little bittern', '🦫 Beaver in the steep banks', '🐟 Bitterling · River mussels', '🌸 Orchids on clay-pit marshes · Michaelmas daisies', '🦆 Waterfowl on the Linge in winter'],
 'trail': ['Walk the <b>Lingedijk</b> between Arkel and Gellicum through the bank landscape.', 'Follow the <b>Lingepad (LAW 6.1)</b> from Bronckhorst to Gorinchem.', 'Combine with the <b>Lingebos</b> (card 2048) for a full day of Linge nature.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Banklands partly soggy — follow dike and paths · 🚶 Node network; Lingepad'
}, n2k='Lingegebied &amp; Diefdijk-Zuid — de oeverlanden van de Linge tussen Arkel en Gellicum zijn de kern van Habitatrichtlijngebied nr. 70 (NL3004007): H6510 blauwe glanshaverhooilanden, grotezeggenmoeras en moerasvogels als blauwborst, purperreiger en woudaapje; bittervoorn en bever als soorten van de rivier.',
 n2k_en='Lingegebied &amp; Diefdijk-Zuid — the Linge banklands between Arkel and Gellicum are the core of Habitats Directive site no. 70 (NL3004007): H6510 soft-grass hay meadows, great-sedge beds and marsh birds like bluethroat, purple heron and little bittern; bitterling and beaver as river species.'))

C.append(mk.card(2048, 'Lingebos', {
 'tags': ['Gelderland · Vuren (West Betuwe)', 'Recreatiebos van ± 115 hectare — geopend in 1969 door prinses Beatrix · zwemplas, speelbos De Kleine Waterlinie en 100 jaar oude grienden', 'list 36 · no. 767'],
 'loc': '📍 Haarweg 6, Vuren — parkeerplaatsen aan de noord- en zuidzijde (parkeergeld ± € 2,50) · 8-km wandelroute door het bos; kiosk Het Kraaiennest bij de zwemplas',
 'desc': 'Het <b>Lingebos</b> bij <b>Vuren</b> is het groene bewijs dat de Lage Landen in de jaren zestig serieus werk maakten van recreatie: het bos werd aangeplant als <b>recreatiebos</b> voor de dichtbevolkte randstad en op <b>26 juni 1969</b> geopend door <b>prinses Beatrix</b> — meteen de grootste openbare attractie van de Betuwe sinds de fruitveiling. Vandaag beslaat het ± <b>115 hectare</b> op de oostoever van de <b>Linge</b>: een <b>Staatsbosbeheer-natuurdeel</b> met <b>honderd jaar oude grienden</b> en zachtwoud-opstanden, en een <b>recreatiedeel</b> van de gemeente <b>West Betuwe</b> met de <b>zwemplas</b> van tien hectare, het avontuurlijke <b>speelbos De Kleine Waterlinie</b> (een speeltuin in wording — met dijken, grienden en klimwilgen) en de <b>8-kilometer wandelroute</b> die het geheel omarmt. Bij de plas staat de <b>kiosk Het Kraaiennest</b> voor ijs en koffie; in de zomer wordt het bos druk bezocht door zwemmers, in de herfst door paddenstoelenzoekers in de oude grienden. Wie het bos verlaat, staat meteen in het Linge-landschap van de <b>Lingeoevers</b> (kaart 2047) — bos, rivier en hooilanden binnen één adem.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (zwemplas, speelbos), sep–okt (paddenstoelen in de grienden), apr (vroege voorjaarsbloei)<br>\\n    <b>Beste tijd van de dag:</b> Ochenden rustig — middagen levendig bij de plas.',
 'why': ['De <b>opening van 1969</b> door prinses Beatrix — recreatiegeschiedenis van de randstad.', 'De <b>100 jaar oude grienden</b> van het SBB-natuurdeel.', 'De <b>zwemplas van 10 ha</b> met kiosk Het Kraaiennest.', 'Het <b>speelbos De Kleine Waterlinie</b> — klimmen tussen dijken en grienden.'],
 'phen': ['<span class="months">Mei–Sep</span> 🏊 <b>Zwemplas</b> in vol bedrijf.', '<span class="months">Jun–Aug</span> 🌳 <b>Speelbos</b> op zijn avontuurlijkst.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in de oude grienden.', '<span class="months">Apr</span> 🌸 <b>Vroege voorjaarsbloeiers</b> onder de bomen.'],
 'wild': ['🌳 100-jaar-oude grienden en zachthout', '🏊 Zwemplas van ± 10 hectare', '🍄 Paddenstoelen in het najaar', '🐦 Zangvogels van bos en griend', '🛝 Speelbos De Kleine Waterlinie'],
 'trail': ['Loop de <b>8-km wandelroute</b> door natuur- en recreatiedeel.', 'Bezoek de <b>zwemplas</b> en kiosk <b>Het Kraaiennest</b> (Haarweg 6).', 'Combineer met de <b>Lingeoevers</b> en de Lingedijk naar Gorinchem.'],
 'foot': '🐕 Honden aangelijnd · 💶 Parkeergeld ± € 2,50 · 🏊 Zwemmen op eigen risico in de plas · 🚶 Knooppuntennetwerk; Lingepad'
}, {
 'tags': ['Gelderland · Vuren (West Betuwe)', 'Recreation wood of ± 115 hectares — opened in 1969 by Princess Beatrix · swimming lake, play forest De Kleine Waterlinie and 100-year-old copses', 'list 36 · no. 767'],
 'loc': '📍 Haarweg 6, Vuren — car parks on the north and south sides (parking ± € 2.50) · 8-km walking route through the wood; kiosk Het Kraaiennest by the swimming lake',
 'desc': 'The <b>Lingebos</b> at <b>Vuren</b> is living proof that the Low Countries got serious about outdoor recreation in the sixties: the wood was planted as a <b>recreation forest</b> for the crowded Randstad and opened on <b>26 June 1969</b> by <b>Princess Beatrix</b> — at once the Betuwe’s biggest public attraction since the fruit auction. Today it covers ± <b>115 hectares</b> on the east bank of the <b>Linge</b>: a <b>Staatsbosbeheer nature section</b> with <b>hundred-year-old willow copses</b> and soft-wood stands, and a <b>recreation section</b> of the municipality of <b>West Betuwe</b> with the ten-hectare <b>swimming lake</b>, the adventurous <b>play forest De Kleine Waterlinie</b> (a playground in the making — with dikes, copses and climbing willows) and the <b>8-kilometre walking route</b> embracing it all. By the lake stands the <b>kiosk Het Kraaiennest</b> for ice cream and coffee; in summer the wood fills with swimmers, in autumn with mushroom seekers in the old copses. Leave the wood and you step straight into the Linge landscape of the <b>Lingeoevers</b> (card 2047) — wood, river and hay meadows in one breath.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (swimming lake, play forest), Sep–Oct (fungi in the copses), Apr (early spring flowers)<br>\\n    <b>Best time of day:</b> Quiet mornings — lively afternoons by the lake.',
 'why': ['The <b>1969 opening</b> by Princess Beatrix — Randstad recreation history.', 'The <b>100-year-old willow copses</b> of the forestry nature section.', 'The <b>10-ha swimming lake</b> with kiosk Het Kraaiennest.', 'The <b>play forest De Kleine Waterlinie</b> — climbing among dikes and copses.'],
 'phen': ['<span class="months">May–Sep</span> 🏊 <b>Swimming lake</b> in full swing.', '<span class="months">Jun–Aug</span> 🌳 <b>Play forest</b> at its most adventurous.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old copses.', '<span class="months">Apr</span> 🌸 <b>Early spring flowers</b> under the trees.'],
 'wild': ['🌳 100-year-old copses and soft wood', '🏊 Swimming lake of ± 10 hectares', '🍄 Autumn fungi', '🐦 Songbirds of wood and copse', '🛝 Play forest De Kleine Waterlinie'],
 'trail': ['Walk the <b>8-km route</b> through nature and recreation sections.', 'Visit the <b>swimming lake</b> and kiosk <b>Het Kraaiennest</b> (Haarweg 6).', 'Combine with the <b>Lingeoevers</b> and the Lingedijk towards Gorinchem.'],
 'foot': '🐕 Dogs on lead · 💶 Parking ± € 2.50 · 🏊 Swimming in the lake at your own risk · 🚶 Node network; Lingepad'
}))

C.append(mk.card(2049, 'Niemandshoek', {
 'tags': ['Zuid-Holland · Alblasserwaard (Molenlanden)', 'Natuurlanden van Staatsbosbeheer in het veenweidegebied van de Alblasserwaard · deelgebied van Groene Hart–Alblasserwaard (± 500 ha totaal)', 'list 36 · no. 768'],
 'loc': '📍 In de Alblasserwaard, gemeente Molenlanden · geen centraal toegangspunt — volg de kades tussen de SBB-deelgebieden; combi met Zouweboezem, Noordelose Kade en polder Blommendaal',
 'desc': '<b>Niemandshoek</b> is een van de kleinere <b>deelgebieden</b> waarmee <b>Staatsbosbeheer</b> het Groene Hart–Alblasserwaard beheert — een verre voortzetting van de grote veenweide- en moerascomplexen van de Zouweboezem-regio, met natte graslanden, brede sloten en rietkragen in het lage land achter de Lekdijk en de Zouwendijk. Het beheer is erop gericht het <b>veenweideland</b> als geheel te versterken: hogere waterpeilen, natuurvriendelijke oevers, terugkeer van <b>rietvogels</b> en <b>weidevogels</b>, en verbinding met de omliggende polders — geen spectaculair terrein, maar een schakel in de groene keten van Noordeloos tot Ameide. Publieke documentatie over dit kleine deeltje is beperkt: er is geen bezoekersvoorziening, geen uitgepiilde route, geen parkeerplaats met bord — wie het gebied wil ervaren, volgt gewoon de <b>kades en dijken</b> van de Alblasserwaard en kijkt naar wat zich aandient: een blauwborst in het riet, een ijsvogel op de slootkade, een groep jongvee in de bloemrijke wei. Zo hoort het bij het stille netwerk van het Groene Hart — een hoekje waar niemand de dienst uitmaakt, en juist daarom van belang.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (rietzang, weidevogels), okt–mrt (winterstilte en ganzen)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — dauw en zang boven de sloten.',
 'why': ['Een <b>schakel in de keten</b> van SBB-deelgebieden van het Groene Hart–Alblasserwaard.', 'Het <b>veenweide-beheer</b>: hoge peilen, natuurvriendelijke oevers, rietvogels.', 'De <b>stilte</b> van een gebied zonder voorzieningen — kades als routes.', 'De <b>naam</b> zelf: een hoek waar niemand de dienst uitmaakt.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Rietvogels en weidevogels</b> in het lage land.', '<span class="months">Jun–Aug</span> 🌼 <b>Bloemrijke oevers</b> langs de sloten.', '<span class="months">Okt–Mrt</span> 🪿 <b>Ganzen</b> op de natte percelen.', '<span class="months">Heel jaar</span> 🚶 <b>Kades</b> als stil wandelnetwerk.'],
 'wild': ['🐦 Blauwborst · Rietzanger · Kleine karekiet', '🐦 Grutto · Kievit · Tureluur', '💧 Natte graslanden, brede sloten en rietkragen', '🐟 Slootflora en libellen in de vaarten', '🚶 Kades en dijken als toegang'],
 'trail': ['Volg de <b>kades tussen Noordeloos en Ameide</b> door het SBB-gebiedsnetwerk.', 'Combineer met de <b>Zouweboezem</b> en de <b>Noordelose Kade</b> (kaart 2034).', 'Gebruik de parkeerplaatsen bij de <b>Driemolenseweg of Boezemweg</b> als start.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen voorzieningen of routes — kades volgen · 🚶 Knooppuntennetwerk Molenlanden'
}, {
 'tags': ['Zuid-Holland · Alblasserwaard (Molenlanden)', 'Staatsbosbeheer nature lands in the peat meadows of the Alblasserwaard · sub-area of Groene Hart–Alblasserwaard (± 500 ha total)', 'list 36 · no. 768'],
 'loc': '📍 In the Alblasserwaard, municipality of Molenlanden · no central access point — follow the embankments between the SBB sub-areas; combine with Zouweboezem, Noordelose Kade and polder Blommendaal',
 'desc': '<b>Niemandshoek</b> (‘Nobody’s Corner’) is one of the smaller <b>sub-areas</b> with which <b>Staatsbosbeheer</b> manages the Groene Hart–Alblasserwaard — a far continuation of the great peat-meadow and marsh complexes of the Zouweboezem region, with wet grasslands, broad ditches and reed fringes in the low land behind the Lekdijk and the Zouwendijk. The management aims to strengthen the <b>peat meadow land</b> as a whole: higher water levels, nature-friendly banks, the return of <b>reed birds</b> and <b>meadow birds</b>, and connection with the surrounding polders — no spectacular terrain, but a link in the green chain from Noordeloos to Ameide. Public documentation about this little piece is limited: there is no visitor facility, no signed route, no car park with a board — whoever wants to experience the area simply follows the <b>embankments and dikes</b> of the Alblasserwaard and watches what shows itself: a bluethroat in the reed, a kingfisher on the ditch bank, a herd of young cattle in the flower-rich meadow. That is how it belongs to the quiet network of the Groene Hart — a corner where nobody is in charge, and precisely therefore of value.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (reed song, meadow birds), Oct–Mar (winter quiet and geese)<br>\\n    <b>Best time of day:</b> Early morning — dew and song above the ditches.',
 'why': ['A <b>link in the chain</b> of SBB sub-areas of the Groene Hart–Alblasserwaard.', 'The <b>peat-meadow management</b>: high levels, nature-friendly banks, reed birds.', 'The <b>quiet</b> of an area without facilities — embankments as routes.', 'The <b>name</b> itself: a corner where nobody is in charge.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Reed birds and meadow birds</b> in the low land.', '<span class="months">Jun–Aug</span> 🌼 <b>Flower-rich banks</b> along the ditches.', '<span class="months">Oct–Mar</span> 🪿 <b>Geese</b> on the wet parcels.', '<span class="months">All year</span> 🚶 <b>Embankments</b> as a quiet walking network.'],
 'wild': ['🐦 Bluethroat · Reed warbler · Sedge warbler', '🐦 Godwit · Lapwing · Redshank', '💧 Wet grasslands, broad ditches and reed fringes', '🐟 Ditch flora and dragonflies', '🚶 Embankments and dikes as access'],
 'trail': ['Follow the <b>embankments between Noordeloos and Ameide</b> through the SBB area network.', 'Combine with the <b>Zouweboezem</b> and the <b>Noordelose Kade</b> (card 2034).', 'Use the car parks at the <b>Driemolenseweg or Boezemweg</b> as start.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No facilities or routes — follow embankments · 🚶 Molenlanden node network'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2049)
mk.check()
