# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1965, 'Westduinen', {
 'tags': ['Zuid-Holland · Ouddorp (kop van Goeree)', 'De “hobbelwei”: 160 hectare open duingrasland · eeuwenlang begraasd weiland met kerkpaden en drinkpoelen · soortenrijk duingrasland met herfstschroeforchis', 'list 36 · no. 684'],
 'loc': '📍 Aan de westkant van Ouddorp, tussen dorp en duinen · vrij toegankelijk; het Duinlichtpad (10,1 km) en de Schurvelingenroute voeren langs en over het gebied, start onder meer aan de Westduinweg',
 'desc': 'De <b>Westduinen</b> bij Ouddorp zijn door de bewoners eeuwenlang de <b>hobbelwei</b> genoemd: 160 hectare golvend duingrasland zonder struiken of bomen, dat generaties lang als gemeenschappelijke weide voor het vee diende. Die voortdurende begrazing schiep een van de oudste cultuurlandschappen van het eiland — en een vegetatie die er nog uitziet als het oorspronkelijke Goeree: open, laag en bloemrijk. Over het gebied lopen de oude <b>kerkpaden</b> waarlangs de boeren vroeger naar de kerk van Ouddorp liepen. In de duinvalleitjes blijft water staan doordat er klei in de ondergrond zit; boeren groeven er drinkpoelen voor het vee, waar nu de <b>rugstreeppad</b> paart en bijzondere planten groeien, waaronder de <b>herfstschroeforchis</b>. Langs de paden bloeien knoopkruid en slanke gentiaan. Om de rust te bewaren staat er tegenwoordig een hek om de hobbelwei; het <b>Duinlichtpad</b> van 10,1 kilometer voert erlangs en deels overheen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (bloei in de valleien), sep–okt (herfstschroeforchis)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig op de kerkpaden.',
 'why': ['Het oorspronkelijke Goeree: <b>open, begraasd duingrasland</b> zonder bebossing.', 'De <b>kerkpaden en drinkpoelen</b> — eeuwen gebruiksgeschiedenis in het zand.', 'De <b>herfstschroeforchis</b> en andere bijzondere duinplanten.', 'De lange <b>Duinlichtpad-wandeling</b> van 10,1 kilometer.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Knoopkruid en slanke gentiaan</b> in de valleien.', '<span class="months">Jun–Aug</span> 🐸 <b>Rugstreeppad</b> in de drinkpoelen.', '<span class="months">Sep–Okt</span> 🌱 <b>Herfstschroeforchis</b> bloeit bij de poelen.', '<span class="months">Okt–Mrt</span> 🌬️ <b>Winter</b>: open duin onder laag licht.'],
 'wild': ['🐄 Begrazing met koeien', '🏜️ Duingrasland met valleitjes', '🐸 Rugstreeppad', '🌸 Herfstschroeforchis · Slanke gentiaan · Knoopkruid', '🐦 Graspieper · Veldleeuwerik'],
 'trail': ['Wandel het <b>Duinlichtpad (10,1 km)</b> langs en over de Westduinen.', 'Volg de <b>Schurvelingenroute</b> om het duingebied.', 'Start aan de <b>Westduinweg</b> bij Ouddorp en loop de kerkpaden het veld in.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Het gebied is deels afgesloten om de rust te bewaren; volg de paden · 🚶 Kerkpaden en gemarkeerde routes'
}, {
 'tags': ['Zuid-Holland · Ouddorp (head of Goeree)', 'The “hobbelwei”: 160 hectares of open dune grassland · centuries-old grazed pasture with church paths and drinking pools · species-rich dune grassland with autumn lady’s-tresses', 'list 36 · no. 684'],
 'loc': '📍 On the west side of Ouddorp, between village and dunes · freely accessible; the Duinlichtpad (10.1 km) and the Schurvelingen route run along and over the area, with a start at the Westduinweg among others',
 'desc': 'The <b>Westduinen</b> near Ouddorp have for centuries been called the <b>hobbelwei</b> by the inhabitants: 160 hectares of rolling dune grassland without scrub or trees, which for generations served as common pasture for the cattle. That continuous grazing created one of the oldest cultural landscapes of the island — and a vegetation that still looks like the original Goeree: open, low and flower-rich. Over the area run the old <b>church paths</b> along which the farmers used to walk to the church of Ouddorp. In the dune valleys water remains standing because of the clay in the subsoil; farmers dug drinking pools for the cattle, where now the <b>natterjack toad</b> breeds and special plants grow, including the <b>autumn lady’s-tresses</b>. Along the paths bloom greater knapweed and marsh gentian. To preserve the quiet, a fence now surrounds the hobbelwei; the <b>Duinlichtpad</b> of 10.1 kilometres runs along it and partly across it.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (bloom in the valleys), Sep–Oct (autumn lady’s-tresses)<br>\n    <b>Best time of day:</b> Morning — quiet on the church paths.',
 'why': ['The original Goeree: <b>open, grazed dune grassland</b> without afforestation.', 'The <b>church paths and drinking pools</b> — centuries of use history in the sand.', 'The <b>autumn lady’s-tresses</b> and other special dune plants.', 'The long <b>Duinlichtpad walk</b> of 10.1 kilometres.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Greater knapweed and marsh gentian</b> in the valleys.', '<span class="months">Jun–Aug</span> 🐸 <b>Natterjack toad</b> in the drinking pools.', '<span class="months">Sep–Oct</span> 🌱 <b>Autumn lady’s-tresses</b> bloom near the pools.', '<span class="months">Oct–Mar</span> 🌬️ <b>Winter</b>: open dune under low light.'],
 'wild': ['🐄 Grazing with cattle', '🏜️ Dune grassland with valleys', '🐸 Natterjack toad', '🌸 Autumn lady’s-tresses · Marsh gentian · Greater knapweed', '🐦 Meadow pipit · Skylark'],
 'trail': ['Walk the <b>Duinlichtpad (10.1 km)</b> along and over the Westduinen.', 'Follow the <b>Schurvelingen route</b> around the dune area.', 'Start at the <b>Westduinweg</b> near Ouddorp and walk the church paths into the field.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ The area is partly fenced to preserve the quiet; follow the paths · 🚶 Church paths and marked routes'
}))

C.append(mk.card(1966, 'Kleistee', {
 'tags': ['Zuid-Holland · Ouddorp (westrand)', 'Bewaard middeleeuws wallenlandschap van het Zuid-Hollands Landschap · schurvelingen en hoagten rond akkertjes · winterputten voor vleermuizen, akkers vol bloemen en een oude moerbeiboom', 'list 36 · no. 685'],
 'loc': '📍 Aan de westrand van Ouddorp · vrij toegankelijk via de paaltjesroute vanaf de Dirkdoensweg; de Schurvelingenroute (11 km) doorkruist het gebied',
 'desc': 'In de <b>Kleistee</b> wandel je een middeleeuws landschap binnen dat op heel Goeree verdwenen is — behalve hier. Al rond het jaar 1000 legden boeren rond hun akkers begroeide zandwallen aan, de zogenaamde <b>schurvelingen</b>, om hun gewassen tegen het stuivende zand te beschermen; later werden die wallen tot <b>hoagten</b> opgehoogd. Het Zuid-Hollands Landschap beheert dit laatste gave restant: een mozaïek van wallen, akkertjes en boomgaarden. Op de natte noordhellingen groeien eikvarens, op de droge zuidhellingen zandzegge, buntgras en schapenzuring. De grote akkers worden één keer per jaar gemaaid en wemelen dan van het <b>bruin blauwtje</b>; elders staat <b>rode emmertarwe</b>, een oud graan waar wilde bijen voedsel en nestgelegenheid vinden. Vijf oude waterwinputten zijn omgebouwd tot <b>winterverblijf voor vleermuizen</b>, en in de oude hoogstamboomgaard staat een monumentale <b>moerbeiboom</b>. Een paaltjesroute vanaf de Dirkdoensweg voert door het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (bloei en vlinders), jul–aug (emmertarwe), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag.',
 'why': ['De <b>best bewaarde schurvelingen</b> van Goeree — cultuurhistorie in het zand.', 'De <b>bloemrijke akkers</b> met bruin blauwtje en rode emmertarwe.', 'De <b>winterputten voor vleermuizen</b> en de oude moerbeiboom.', 'De wandeling over wallen en akkertjes <b>als door een openluchtmuseum</b>.'],
 'phen': ['<span class="months">Mei–Jun</span> 🦋 <b>Bruin blauwtje</b> boven de bloemrijke akkers.', '<span class="months">Jun–Jul</span> 🌾 <b>Rode emmertarwe</b> in de aar.', '<span class="months">Jun–Aug</span> 🐝 <b>Wilde bijen</b> op de akkers en wallen.', '<span class="months">Okt–Mrt</span> 🦇 <b>Vleermuizen</b> overwinteren in de putten.'],
 'wild': ['📜 Schurvelingen en hoagten', '🦋 Bruin blauwtje', '🌾 Rode emmertarwe', '🦇 Vleermuizen in de winterputten', '🌳 Oude moerbeiboom'],
 'trail': ['Volg de <b>paaltjesroute</b> vanaf de Dirkdoensweg door het wallenlandschap.', 'Wandel de <b>Schurvelingenroute (11 km)</b> die de Kleistee doorkruist.', 'Combineer met de <b>Westduinen</b> of de duinen van Goeree.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; de akkers en wallen zijn kwetsbaar · 🚶 Paaltjesroute en gemarkeerde routes'
}, {
 'tags': ['Zuid-Holland · Ouddorp (west edge)', 'Preserved medieval embanked-field landscape of Het Zuid-Hollands Landschap · schurvelingen and hoagten around small fields · winter pits for bats, flower-rich fields and an old mulberry tree', 'list 36 · no. 685'],
 'loc': '📍 On the west edge of Ouddorp · freely accessible via the post route from the Dirkdoensweg; the Schurvelingen route (11 km) crosses the area',
 'desc': 'In the <b>Kleistee</b> you walk into a medieval landscape that has disappeared from the whole of Goeree — except here. As early as around the year 1000 farmers built vegetated sand banks around their fields, the so-called <b>schurvelingen</b>, to protect their crops against the drifting sand; later those banks were raised into <b>hoagten</b>. Het Zuid-Hollands Landschap manages this last intact remnant: a mosaic of banks, small fields and orchards. On the moist north slopes grow common polypody, on the dry south slopes sand sedge, wavy hair-grass and sheep’s sorrel. The large fields are mown once a year and then teem with the <b>small heath</b>; elsewhere grows <b>red emmer wheat</b>, an old grain that gives wild bees food and nesting places. Five old water wells have been converted into a <b>winter roost for bats</b>, and in the old standard orchard stands a monumental <b>mulberry tree</b>. A post route from the Dirkdoensweg leads through the area.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (bloom and butterflies), Jul–Aug (emmer wheat), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon.',
 'why': ['The <b>best-preserved schurvelingen</b> of Goeree — cultural history in the sand.', 'The <b>flower-rich fields</b> with small heath and red emmer wheat.', 'The <b>winter pits for bats</b> and the old mulberry tree.', 'Walking over banks and fields <b>as through an open-air museum</b>.'],
 'phen': ['<span class="months">May–Jun</span> 🦋 <b>Small heath</b> above the flower-rich fields.', '<span class="months">Jun–Jul</span> 🌾 <b>Red emmer wheat</b> in the ear.', '<span class="months">Jun–Aug</span> 🐝 <b>Wild bees</b> on the fields and banks.', '<span class="months">Oct–Mar</span> 🦇 <b>Bats</b> hibernate in the pits.'],
 'wild': ['📜 Schurvelingen and hoagten', '🦋 Small heath', '🌾 Red emmer wheat', '🦇 Bats in the winter pits', '🌳 Old mulberry tree'],
 'trail': ['Follow the <b>post route</b> from the Dirkdoensweg through the banked landscape.', 'Walk the <b>Schurvelingen route (11 km)</b> that crosses the Kleistee.', 'Combine with the <b>Westduinen</b> or the dunes of Goeree.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; the fields and banks are fragile · 🚶 Post route and marked routes'
}))

C.append(mk.card(1967, 'Oude Stee', {
 'tags': ['Zuid-Holland · Achthuizen (Oostflakkee)', '⚠️ Museumboerderij van ruim driehonderd jaar — geen natuurgebied, maar een poort naar de Slikken van Flakkee en het Melissantsebos', 'list 36 · no. 686'],
 'loc': '📍 Schaapsweg in Achthuizen (Oostflakkee) · de boerderij is als museum te bezoeken; parkeren bij de boerderij of doorrijden naar de Slikken van Flakkee en het Melissantsebos',
 'desc': '⚠️ Een eerlijke kaart: de <b>Oude Stee</b> — in de streek ook wel <b>De Ouwe Stee</b> genoemd — is geen natuurgebied maar een <b>museumboerderij</b> in Achthuizen, die al ruim driehonderd jaar op dezelfde plek staat. Binnen wordt het verhaal verteld van twee zussen die er samen bijna een eeuw lang een zelfvoorzienend boerenleven leidden: het interieur lijkt in hun tijd te zijn stilgezet, met de spullen van het dagelijks eilandleven om je heen. Voor natuurliefhebbers is de Oude Stee vooral een <b>poort</b>: Achthuizen ligt aan de rand van Oostflakkee, op een steenworp van de <b>Slikken van Flakkee</b> — het uitgestrekte buitendijkse schorren- en slikkenlandschap waar heckrunderen en fjordenpaarden grazen, reeën staan en in de winter regelmatig een <b>zeearend</b> jaagt. Ook het Melissantsebos van Staatsbosbeheer ligt vlakbij. Een bezoek is een contrast dat blijft hangen: eerst het boerenleven van binnenuit, daarna de wilde buitenkant van het eiland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (openstelling museumboerderij), okt–mrt (zeearenden boven de slikken)<br>\n    <b>Beste tijd van de dag:</b> Middag — eerst het museum, daarna de slikken.',
 'why': ['De <b>stilgezette wereld</b> van de twee zussen — erfgoed van het eilandleven.', 'De ligging als <b>poort naar de Slikken van Flakkee</b>.', 'De kans op <b>zeearend en heckrunderen</b> in de directe omgeving.', 'De combinatie van <b>cultuurhistorie en wildernis</b> op één middag.'],
 'phen': ['<span class="months">Mei–Sep</span> 🏛️ <b>Openstelling</b> van de museumboerderij.', '<span class="months">Okt–Mrt</span> 🦅 <b>Zeearenden</b> boven de slikken van Flakkee.', '<span class="months">Apr–Jun</span> 🐦 <b>Broedvogels</b> in het buitendijkse gebied.', '<span class="months">Heel jaar</span> 🐮 <b>Heckrunderen en fjordenpaarden</b> in de uiterwaarden.'],
 'wild': ['🏛️ Museumboerderij “Oude Stee”', '🐮 Heckrunderen en fjordenpaarden', '🦅 Zeearend (winter)', '🦌 Ree', '🌿 Schorren en slikken van Flakkee'],
 'trail': ['Bezoek eerst de <b>museumboerderij</b> aan de Schaapsweg in Achthuizen.', 'Rijd of wandel daarna naar de <b>Slikken van Flakkee</b> voor de buitendijkse natuur.', 'Maak een omweg langs het <b>Melissantsebos</b> van Staatsbosbeheer.'],
 'foot': '🐕 Honden aangelijnd (buitendijks aanlijnplicht) · 💶 Museumbezoek tegen betaling · ⚠️ Geen natuurterrein — museumboerderij met natuurpoortfunctie · 🚶 Omgeving via wegen en dijken'
}, {
 'tags': ['Zuid-Holland · Achthuizen (Oostflakkee)', '⚠️ Museum farmstead of more than three hundred years old — not a nature area, but a gateway to the Slikken van Flakkee and the Melissantsebos', 'list 36 · no. 686'],
 'loc': '📍 Schaapsweg in Achthuizen (Oostflakkee) · the farmstead can be visited as a museum; park at the farmstead or continue to the Slikken van Flakkee and the Melissantsebos',
 'desc': '⚠️ An honest card: the <b>Oude Stee</b> — in the region also called <b>De Ouwe Stee</b> — is not a nature area but a <b>museum farmstead</b> in Achthuizen, standing on the same spot for over three hundred years. Inside, the story is told of two sisters who lived a self-sufficient farming life there for almost a century: the interior seems frozen in their time, with the everyday objects of island life around you. For nature lovers the Oude Stee is above all a <b>gateway</b>: Achthuizen lies on the edge of Oostflakkee, a stone’s throw from the <b>Slikken van Flakkee</b> — the vast seaward salt-marsh and mudflat landscape where Heck cattle and fjord horses graze, roe deer stand and in winter a <b>white-tailed eagle</b> regularly hunts. The Melissantsebos of Staatsbosbeheer is also nearby. A visit is a contrast that lingers: first the farming life from within, then the wild outer side of the island.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (museum farmstead open), Oct–Mar (white-tailed eagles above the mudflats)<br>\n    <b>Best time of day:</b> Afternoon — first the museum, then the mudflats.',
 'why': ['The <b>frozen world</b> of the two sisters — heritage of island life.', 'Its position as a <b>gateway to the Slikken van Flakkee</b>.', 'The chance of <b>white-tailed eagle and Heck cattle</b> in the immediate surroundings.', 'The combination of <b>cultural history and wilderness</b> in one afternoon.'],
 'phen': ['<span class="months">May–Sep</span> 🏛️ <b>Opening</b> of the museum farmstead.', '<span class="months">Oct–Mar</span> 🦅 <b>White-tailed eagles</b> above the mudflats of Flakkee.', '<span class="months">Apr–Jun</span> 🐦 <b>Breeding birds</b> in the seaward area.', '<span class="months">All year</span> 🐮 <b>Heck cattle and fjord horses</b> in the outer polders.'],
 'wild': ['🏛️ Museum farmstead “Oude Stee”', '🐮 Heck cattle and fjord horses', '🦅 White-tailed eagle (winter)', '🦌 Roe deer', '🌿 Salt marshes and mudflats of Flakkee'],
 'trail': ['First visit the <b>museum farmstead</b> on the Schaapsweg in Achthuizen.', 'Then drive or walk to the <b>Slikken van Flakkee</b> for the seaward nature.', 'Take a detour past the <b>Melissantsebos</b> of Staatsbosbeheer.'],
 'foot': '🐕 Dogs on lead (leash duty seaward) · 💶 Museum visit for a fee · ⚠️ Not a nature terrain — museum farmstead with nature-gateway function · 🚶 Surroundings via roads and dikes'
}))

C.append(mk.card(1968, 'Bosobjecten Goeree', {
 'tags': ['Zuid-Holland · Goeree-Overflakkee (Stellendam, Dirksland, Melissant)', 'Verzamelkaart van de zeldzame bossen van Staatsbosbeheer op het eiland · Stellebos, bos langs de Smalle Gooi, Melissantsebos en kleine bosjes · nestbomen blijven gespaard', 'list 36 · no. 687'],
 'loc': '📍 Verspreid over Goeree-Overflakkee · toegankelijk via de hoofdingangen van het Stellebos bij Stellendam, het bos langs de Smalle Gooi bij Dirksland en het Melissantsebos bij Melissant',
 'desc': 'Op een eiland van duin en kleipolder zijn bossen zeldzaam — en daarom zijn de <b>bosobjecten van Staatsbosbeheer</b> op Goeree-Overflakkee des te waardevoller. De beheerder vat er de verspreide bosjes onder één noemer samen: het <b>Stellebos</b> bij Stellendam met elzen-, wilgen- en populierenbossen op voormalige slikken, het <b>bos langs de Smalle Gooi</b> bij Dirksland, het <b>Melissantsebos</b> en de kleine bosjes van de Scharrezeepolder en het Halsgat. Samen vormen ze groene eilanden in het open polderland. Staatsbosbeheer verzorgt de opstanden om beurten: populieren worden gedund en zwakke bomen opgeruimd — maar pas nadat de bossen zijn nagezocht op spechtenholtes en roofvogelhorsten; bomen met nesten blijven altijd staan. Voor wandelaars zijn het de stilteplekken van het eiland: in het voorjaar zangvogels en roffelende spechten, in de herfst paddenstoelen onder populier en els, en overal het jonge, lichte bos op jonge grond.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rustig in de bosjes.',
 'why': ['<b>Jong bos op jong land</b>: bosgroei op voormalige slikken en langs oude kreken.', 'De <b>nestbomen van spechten en roofvogels</b> die bewust gespaard blijven.', 'De afwisseling van <b>elzen-, wilgen- en populierenbos</b>.', 'De <b>stilte</b> midden in het open polderland van het eiland.'],
 'phen': ['<span class="months">Apr–Mei</span> 🎵 <b>Zangvogels en spechten</b> in de elzenbossen.', '<span class="months">Mei–Jun</span> 🐦 <b>Broedseizoen</b>: roofvogels in de nestbomen.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> onder populier en els.', '<span class="months">Okt–Mrt</span> 🍂 <b>Winter</b>: lichtval door het jonge bos.'],
 'wild': ['🌳 Populier · Els · Wilg', '🐦 Zwarte specht · Grote bonte specht', '🦅 Buizerd · Torenvalk', '🍄 Paddenstoelen in de herfst', '🌸 Bosanemoon · Daslook (voorjaar)'],
 'trail': ['Bezoek het <b>Stellebos</b> bij Stellendam via de hoofdingang.', 'Wandel langs het <b>bos aan de Smalle Gooi</b> bij Dirksland.', 'Verken het <b>Melissantsebos</b> bij Melissant of de kleine bosjes in de polder.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Verspreide bosjes zonder doorgaande routes; volg de paden en wegen · 🚶 Bos- en veldpaden bij de ingangen'
}, {
 'tags': ['Zuid-Holland · Goeree-Overflakkee (Stellendam, Dirksland, Melissant)', 'Overview card of the rare Staatsbosbeheer woods on the island · Stellebos, wood along the Smalle Gooi, Melissantsebos and small copses · nest trees are spared', 'list 36 · no. 687'],
 'loc': '📍 Scattered over Goeree-Overflakkee · accessible via the main entrances of the Stellebos near Stellendam, the wood along the Smalle Gooi near Dirksland and the Melissantsebos near Melissant',
 'desc': 'On an island of dune and clay polder, woods are rare — and that makes the <b>Staatsbosbeheer woodland objects</b> on Goeree-Overflakkee all the more valuable. The manager groups the scattered copses under one heading: the <b>Stellebos</b> near Stellendam with alder, willow and poplar woods on former mudflats, the <b>wood along the Smalle Gooi</b> near Dirksland, the <b>Melissantsebos</b> and the small copses of the Scharrezeepolder and the Halsgat. Together they form green islands in the open polder land. Staatsbosbeheer tends the stands in turn: poplars are thinned and weak trees removed — but only after the woods have been searched for woodpecker holes and raptor nests; trees with nests always remain standing. For walkers they are the quiet places of the island: in spring songbirds and drumming woodpeckers, in autumn fungi under poplar and alder, and everywhere the young, light woodland on young land.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — quiet in the copses.',
 'why': ['<b>Young wood on young land</b>: woodland growth on former mudflats and along old creeks.', 'The <b>nest trees of woodpeckers and raptors</b> that are deliberately spared.', 'The variety of <b>alder, willow and poplar woodland</b>.', 'The <b>silence</b> in the middle of the island’s open polder land.'],
 'phen': ['<span class="months">Apr–May</span> 🎵 <b>Songbirds and woodpeckers</b> in the alder woods.', '<span class="months">May–Jun</span> 🐦 <b>Breeding season</b>: raptors in the nest trees.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> under poplar and alder.', '<span class="months">Oct–Mar</span> 🍂 <b>Winter</b>: light falling through the young wood.'],
 'wild': ['🌳 Poplar · Alder · Willow', '🐦 Black woodpecker · Great spotted woodpecker', '🦅 Buzzard · Kestrel', '🍄 Fungi in autumn', '🌸 Wood anemone · Wild garlic (spring)'],
 'trail': ['Visit the <b>Stellebos</b> near Stellendam via the main entrance.', 'Walk along the <b>wood at the Smalle Gooi</b> near Dirksland.', 'Explore the <b>Melissantsebos</b> near Melissant or the small copses in the polder.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Scattered copses without through routes; follow the paths and roads · 🚶 Forest and field paths at the entrances'
}))

C.append(mk.card(1969, 'Oost- en Middelduinen', {
 'tags': ['Zuid-Holland · tussen Ouddorp en Oostdijk (kop van Goeree)', 'Oud binnenduinlandschap uit de vroege middeleeuwen · ruim 200 hectare vrijwel onveranderd · Westhoofdvallei en waterwinning sinds 1934/1938', 'list 36 · no. 688'],
 'loc': '📍 Tussen Ouddorp en Oostdijk op de kop van Goeree · vrij toegankelijk; lange route van 20 kilometer overziet het hele complex, korte lus via de Middelduinweg en de kijktoren',
 'desc': 'De kop van Goeree telt drie binnenduingebieden — West-, Middel- en Oostduinen — die samen het oude duinlandschap van het eiland vormen. De <b>Oost- en Middelduinen</b> tussen Ouddorp en Oostdijk zijn het grootste en oudste deel: de Middelduinen ontstonden omstreeks <b>600 na Christus</b> en zijn daarna — op beweiding na — nooit door de mens in gebruik genomen. Pas rond 1100 vormde zich de jongere buitenduinboog ervoor, waardoor dit binnenlandse duinlandschap bewaard bleef zoals het in de vroege middeleeuwen lag. Een bijzonderheid is de <b>waterwinning</b>, die sinds 1934 in de Oostduinen en 1938 in de Middelduinen plaatsvindt: het pompstation bij Oostdijk levert drinkwater, al zorgde de winning decennialang voor verdroging. Tussen de oude duintoppen ligt de vochtige <b>Westhoofdvallei</b> met bloemrijke duinvalleien. Sinds 1972 is de beweiding gestopt; wandelaars volgen de paden en de kijktoren bij Ouddorp geeft uitzicht over duinen, slikken en de Grevelingen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (bloeiende duinvalleien), sep–okt (paddenstoelen en herfstlicht)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend of late middag — laag licht over de valleien.',
 'why': ['Duinen van <b>veertienhonderd jaar oud</b> die er nog bij liggen als in de middeleeuwen.', 'De <b>Westhoofdvallei</b>: vochtige bloemrijke vallei tussen de oude toppen.', 'De <b>kijktoren</b> bij Ouddorp voor het overzicht over duinen, slik en meer.', 'De <b>lange rondroute van 20 kilometer</b> over het hele duincomplex.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌸 <b>Bloemrijke duinvalleien</b> met orchideeën.', '<span class="months">Jun–Aug</span> 🦋 <b>Vlinders en sprinkhanen</b> in het open duin.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in het onveranderde duinrelict.', '<span class="months">Okt–Mrt</span> 🦆 <b>Winter</b>: vogels op de nabije slikken.'],
 'wild': ['🏜️ Binnenduinrelict uit de vroege middeleeuwen', '🌿 Westhoofdvallei met orchideeën', '🐦 Boomleeuwerik · Graspieper', '🦋 Bruin blauwtje · Hooibeestje', '💧 Pompstation en waterwinning'],
 'trail': ['Wandel de <b>lange route van 20 kilometer</b> over het hele duincomplex.', 'Maak de korte lus via de <b>Middelduinweg</b> en de kijktoren.', 'Start bij de <b>Duinen van Goeree</b> bij Ouddorp en loop de vallei in.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; het oude duin is kwetsbaar · 🚶 Zandpaden en gemarkeerde routes'
}, {
 'tags': ['Zuid-Holland · between Ouddorp and Oostdijk (head of Goeree)', 'Old inland dune landscape from the early Middle Ages · over 200 hectares virtually unchanged · Westhoofdvallei and water extraction since 1934/1938', 'list 36 · no. 688'],
 'loc': '📍 Between Ouddorp and Oostdijk on the head of Goeree · freely accessible; a 20-kilometre route surveys the whole complex, short loop via the Middelduinweg and the observation tower',
 'desc': 'The head of Goeree counts three inland dune areas — West, Middle and East dunes — which together form the old dune landscape of the island. The <b>Oost- and Middelduinen</b> between Ouddorp and Oostdijk are the largest and oldest part: the Middelduinen arose around <b>600 AD</b> and were never used by man afterwards — except for grazing. Only around 1100 did the younger seaward dune arc form in front of them, which preserved this inland dune landscape as it lay in the early Middle Ages. A special feature is the <b>water extraction</b>, which has taken place since 1934 in the Oostduinen and 1938 in the Middelduinen: the pumping station near Oostdijk supplies drinking water, although extraction caused desiccation for decades. Between the old dune tops lies the moist <b>Westhoofdvallei</b> with flower-rich dune valleys. Grazing stopped in 1972; walkers follow the paths and the observation tower near Ouddorp gives a view over dunes, mudflats and the Grevelingen.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (blooming dune valleys), Sep–Oct (fungi and autumn light)<br>\n    <b>Best time of day:</b> Early morning or late afternoon — low light over the valleys.',
 'why': ['Dunes of <b>fourteen hundred years old</b> that still lie there as in the Middle Ages.', 'The <b>Westhoofdvallei</b>: moist flower-rich valley between the old tops.', 'The <b>observation tower</b> near Ouddorp for a view over dunes, mud and lake.', 'The <b>long 20-kilometre circuit</b> over the whole dune complex.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Flower-rich dune valleys</b> with orchids.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies and grasshoppers</b> in the open dune.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the unchanged dune relic.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter</b>: birds on the nearby mudflats.'],
 'wild': ['🏜️ Inland dune relic from the early Middle Ages', '🌿 Westhoofdvallei with orchids', '🐦 Woodlark · Meadow pipit', '🦋 Small heath · Gatekeeper', '💧 Pumping station and water extraction'],
 'trail': ['Walk the <b>long 20-kilometre route</b> over the whole dune complex.', 'Take the short loop via the <b>Middelduinweg</b> and the observation tower.', 'Start at the <b>Duinen van Goeree</b> near Ouddorp and walk into the valley.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; the old dune is fragile · 🚶 Sandy paths and marked routes'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1969)
mk.check()
