# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1935, 'Lievelderbroek', {
 'tags': ['Gelderland · Lievelde–Zieuwent (Oost Gelre)', 'Broekland in het brongebied van de Lievelderbeek · nat hooiland en kwelzones tussen Lievelderveld en Koolmansdijk', 'list 36 · no. 654'],
 'loc': '📍 Laaggelegen broekland ten noorden van Lievelde, tegen het Lievelderveld en de Koolmansdijk aan · vrij te verkennen via wegen, paden en landbouwwegen; geen eigen parkeerterrein',
 'desc': 'Het <b>Lievelderbroek</b> is het natte broekland in het <b>brongebied van de Lievelderbeek</b>, tegen de natuurterreinen van het Lievelderveld en de Koolmansdijk aan: laaggelegen, waterrijk hooi- en weiland waar de beek en haar zijsloten tussen houtwallen en broekbosjes door lopen. De bodem blijft hier vrijwel het hele jaar vochtig door <b>kwelwater</b> dat uit de hogere zandgronden omhoog komt; juist die voortdurende aanvoer van vers, mineraalrijk grondwater maakt de sloten, poelen en ruige perceelranden botanisch en voor amfibieën waardevol. De Lievelderbeek is een van de eerste Nederlandse beken die na kanalisatie haar oude, kronkelende loop terugkreeg; samen met de herstelde <b>ecologische verbindingszone</b> tussen het Korenburgerveen, het Lievelderveld en de Koolmansdijk geeft dat de boomkikker en de kamsalamander weer een leefgebied in dit deel van de Achterhoek. Een zelfstandig bezoekers- of beheerterrein met eigen voorzieningen is het Lievelderbroek niet — het is vooral landschap om doorheen te wandelen, bijvoorbeeld via de wegen tussen Lievelde, Zieuwent en Vragender of als onderdeel van de langere ommetjes rond de SBB-terreinen van Lievelde.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (amfibieën en zangvogels), mei–jun (bloeiende beekdalbermen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Avond — boomkikkers in de schemer.',
 'why': ['Het <b>natte broekland in het brongebied</b> van de Lievelderbeek.', 'De <b>kwelzones</b> die de grond het hele jaar vochtig houden.', 'De ligging tussen <b>Lievelderveld en Koolmansdijk</b> in de ecologische verbindingszone.', 'De eerlijke registratie van een broeklandschap zonder eigen bezoekersvoorzieningen.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🦎 <b>Kamsalamanders</b> op weg naar de poelen.', '<span class="months">Mei–Jun</span> 🐸 <b>Boomkikkerkoor</b> in de avond.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs sloten en wegen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> over het broekland.'],
 'wild': ['🐸 Boomkikker · Kamsalamander', '🐦 Graspieper · Veldleeuwerik · Buizerd', '🦌 Ree · Haas', '🦋 Oranjetipje · Bont zandoogje', '🌿 Dotterbloem · Pinksterbloem · Zwarte els'],
 'trail': ['Wandel over de wegen en landbouwwegen tussen <b>Lievelde, Zieuwent en Vragender</b>.', 'Combineer met het <b>Lievelderveld en de Koolmansdijk</b> van Staatsbosbeheer.', 'Volg de <b>Lievelderbeek</b> over het schouwpad en de kleine paden.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Nat terrein: laarzen aanbevolen; geen eigen voorzieningen · 🚶 Wegen, paden en landbouwwegen'
}, {
 'tags': ['Gelderland · Lievelde–Zieuwent (Oost Gelre)', 'Fenland in the headwater area of the Lievelderbeek · wet hayland and seepage zones between the Lievelderveld and the Koolmansdijk', 'list 36 · no. 654'],
 'loc': '📍 Low-lying fenland north of Lievelde, against the Lievelderveld and the Koolmansdijk · freely explorable via roads, paths and farm lanes; no car park of its own',
 'desc': 'The <b>Lievelderbroek</b> is the wet fenland in the <b>headwater area of the Lievelderbeek</b>, against the nature terrains of the Lievelderveld and the Koolmansdijk: low-lying, water-rich hay and pasture land where the brook and its side ditches run between hedgerows and fen copses. The soil here stays moist almost the whole year through <b>seepage water</b> rising from the higher sandy grounds; precisely that constant supply of fresh, mineral-rich groundwater makes the ditches, pools and rough field margins valuable for flora and amphibians. The Lievelderbeek is one of the first Dutch brooks that regained its old meandering course after canalisation; together with the restored <b>ecological corridor</b> between the Korenburgerveen, the Lievelderveld and the Koolmansdijk, this gives the tree frog and the great crested newt a habitat again in this part of the Achterhoek. The Lievelderbroek is not an independent visitor or managed terrain with facilities of its own — it is above all a landscape to walk through, for example via the roads between Lievelde, Zieuwent and Vragender or as part of the longer circuits around the Staatsbosbeheer terrains of Lievelde.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (amphibians and songbirds), May–Jun (blooming brook-valley verges), Oct (autumn)<br>\n    <b>Best time of day:</b> Evening — tree frogs at dusk.',
 'why': ['The <b>wet fenland in the headwater area</b> of the Lievelderbeek.', 'The <b>seepage zones</b> that keep the ground moist all year.', 'Its position between <b>Lievelderveld and Koolmansdijk</b> in the ecological corridor.', 'The honest registration of a fenland without visitor facilities of its own.'],
 'phen': ['<span class="months">Mar–May</span> 🦎 <b>Great crested newts</b> on their way to the pools.', '<span class="months">May–Jun</span> 🐸 <b>Tree frog chorus</b> in the evening.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along ditches and roads.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> over the fenland.'],
 'wild': ['🐸 Tree frog · Great crested newt', '🐦 Meadow pipit · Skylark · Buzzard', '🦌 Roe deer · Hare', '🦋 Orange tip · Speckled wood', '🌿 Marsh marigold · Cuckooflower · Black alder'],
 'trail': ['Walk the roads and farm lanes between <b>Lievelde, Zieuwent and Vragender</b>.', 'Combine with the <b>Lievelderveld and the Koolmansdijk</b> of Staatsbosbeheer.', 'Follow the <b>Lievelderbeek</b> over the maintenance path and small tracks.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Wet terrain: boots recommended; no facilities of its own · 🚶 Roads, paths and farm lanes'
}))

C.append(mk.card(1936, 'Mellinkmaat landschapselementen', {
 'tags': ['Gelderland · Zieuwent–Harreveld (Oost Gelre)', '⚠️ Naam uit de gids voor de landschapselementen tussen Zieuwent en Harreveld · buurtschap “Verspreide huizen Mellinkmaat” in een kleinschalig kampenlandschap', 'list 36 · no. 655'],
 'loc': '📍 Verspreide huizen tussen Zieuwent en Harreveld (buurt Mellinkmaat, gemeente Oost Gelre) · landschap vrij te verkennen via wegen en paden',
 'desc': '<b>Mellinkmaat</b> is in de gids opgenomen als <b>landschapselementen</b> nabij <b>Zieuwent</b>: een van de kleine natuurgebiedjes die het oude bronnenmateriaal rond Zieuwent beschrijft, circa 16 hectare groot en gelegen in een zogenaamd <b>kampenlandschap</b> — kleinschalig boerenland dat omzoomd wordt door groengordels van heggen en houtwallen. Op de moderne kaart van het Centraal Bureau voor de Statistiek leeft de naam voort als de buurt “Verspreide huizen Mellinkmaat”, tussen <b>Zieuwent en Harreveld</b> in de gemeente Oost Gelre. De naam is een ‘maat’ — een oud Achterhoeks woord voor hooiland — verbonden aan de familie Mellink; het oudste bronmateriaal spreekt van het Mellinghveen, een ontgonnen veengebied dat op latere kaarten als Mellinkmaat (weide) tevoorschijn komt. Een beheerd natuurterrein met bord of eigen paden is er niet: Mellinkmaat is landbouwland waarin de oude landschapselementen — houtwallen, singels, hagen, poelen en een enkele es — het wandelbaar coulisselandschap vormen, precies zoals de gids ze bedoelt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang), mei–jun (bloeiende hagen en bermen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag.',
 'why': ['De <b>landschapselementen</b> van het kampenlandschap tussen Zieuwent en Harreveld.', 'De naam als venster op de oude <b>‘maat’-cultuur</b> van de Achterhoek.', 'De buurtschap <b>“Verspreide huizen Mellinkmaat”</b> op de moderne kaart.', 'De eerlijke registratie van een gidsnaam zonder beheerd terrein.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Zangvogels</b> in houtwallen en singels.', '<span class="months">Mei–Jun</span> 🌸 <b>Bloeiende hagen en bermen</b>.', '<span class="months">Jun–Jul</span> 🌾 <b>Hooitijd</b> op de oude maten.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> in het coulisselandschap.'],
 'wild': ['🐦 Geelgors · Grasmus · Buizerd', '🦌 Ree · Haas · Egel', '🦋 Bont zandoogje · Citroenvlinder', '🦎 Levendbarende hagedis (wallen)', '🌳 Zomereik · Meidoorn · Sleedoorn'],
 'trail': ['Wandel over de wegen tussen <b>Zieuwent en Harreveld</b>.', 'Verken de <b>houtwallen en singels</b> rond de verspreide huizen.', 'Combineer met de SBB-terreinen rond <b>Lievelde</b> of het Vragenderveen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Naam uit de gids zonder beheerd terrein — geen eigen voorzieningen · 🚶 Wegen en landbouwwegen'
}, {
 'tags': ['Gelderland · Zieuwent–Harreveld (Oost Gelre)', '⚠️ Name from the guide for the landscape elements between Zieuwent and Harreveld · hamlet of “Verspreide huizen Mellinkmaat” in a small-scale enclosed-field landscape', 'list 36 · no. 655'],
 'loc': '📍 Scattered houses between Zieuwent and Harreveld (Mellinkmaat neighbourhood, municipality of Oost Gelre) · landscape freely explorable via roads and paths',
 'desc': '<b>Mellinkmaat</b> is listed in the guide as <b>landscape elements</b> near <b>Zieuwent</b>: one of the small nature areas that the old source material describes around Zieuwent, about 16 hectares in size and lying in a so-called <b>kampen landscape</b> — small-scale farmland fringed by green belts of hedges and hedgerows. On the modern map of the Dutch statistical office the name lives on as the neighbourhood “Verspreide huizen Mellinkmaat” (scattered houses of Mellinkmaat), between <b>Zieuwent and Harreveld</b> in the municipality of Oost Gelre. The name is a ‘maat’ — an old Achterhoek word for hayland — linked to the Mellink family; the oldest sources speak of the Mellinghveen, a reclaimed peat area that appears on later maps as Mellinkmaat (meadow). There is no managed nature terrain with signs or paths of its own: Mellinkmaat is farmland in which the old landscape elements — hedgerows, shelterbelts, hedges, pools and the occasional field es — form the walkable small-scale landscape, exactly as the guide intends them.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong), May–Jun (blooming hedges and verges), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon.',
 'why': ['The <b>landscape elements</b> of the enclosed-field landscape between Zieuwent and Harreveld.', 'The name as a window on the old <b>‘maat’ culture</b> of the Achterhoek.', 'The hamlet of <b>“Verspreide huizen Mellinkmaat”</b> on the modern map.', 'The honest registration of a guide name without a managed terrain.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in hedgerows and shelterbelts.', '<span class="months">May–Jun</span> 🌸 <b>Blooming hedges and verges</b>.', '<span class="months">Jun–Jul</span> 🌾 <b>Haymaking time</b> on the old meadows.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the small-scale landscape.'],
 'wild': ['🐦 Yellowhammer · Whitethroat · Buzzard', '🦌 Roe deer · Hare · Hedgehog', '🦋 Speckled wood · Brimstone', '🦎 Viviparous lizard (banks)', '🌳 Pedunculate oak · Hawthorn · Blackthorn'],
 'trail': ['Walk the roads between <b>Zieuwent and Harreveld</b>.', 'Explore the <b>hedgerows and shelterbelts</b> around the scattered houses.', 'Combine with the Staatsbosbeheer terrains around <b>Lievelde</b> or the Vragenderveen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Name from the guide without a managed terrain — no facilities of its own · 🚶 Roads and farm lanes'
}))

C.append(mk.card(1937, 'Hallse Heide', {
 'tags': ['Gelderland · Halle–Mariënvelde (Oost Gelre)', 'Deelgebied van Staatsbosbeheer en historische heidegrond bij de buurtschap Halle-Heide · kerkpaden en de beek de Veengoot', 'list 36 · no. 656'],
 'loc': '📍 Buurtschap Halle-Heide bij Halle (gemeente Oost Gelre), richting Mariënvelde · vrij toegankelijk; rondwandeling van 13 km start aan de Halle-Heideweg',
 'desc': 'De <b>Hallse Heide</b> is opgenomen in de terreinlijst van <b>Staatsbosbeheer</b> als deelgebied van het natuurgebied Achterhoek en leeft daarnaast voort in de naam van de buurtschap <b>Halle-Heide</b> tussen <b>Halle en Mariënvelde</b>. De “heide” is hier vooral geschiedenis: het uitgestrekte heideland van de oude marke van Halle werd in de negentiende en twintigste eeuw ontgonnen tot open gras- en bouwland, afgewisseld met bossen, singels en houtwallen. Een eigen bezoekerspagina heeft het SBB-terrein niet; wie het gebied wil beleven, wandelt de robuuste <b>rondwandeling van 13 kilometer</b> die in de buurtschap start en via rustige wegen, zandpaden en goed onderhouden <b>kerkpaden</b> naar Mariënvelde voert. Onderweg loopt de route langs de beek de <b>Veengoot</b> en door het natuurgebied Veengoot-Mariënvelde, en keert via het Oude Schoolpad terug naar Halle-Heide; in drogere periodes zijn de paden goed begaanbaar. Het land ligt er wijd en stil bij — met horeca in Mariënvelde op ongeveer 8,5 kilometer.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (zangvogels), mei–jun (bloeiende bermen), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of late middag — rustig op de kerkpaden.',
 'why': ['De <b>rondwandeling van 13 kilometer</b> over kerkpaden en het Oude Schoolpad.', 'De <b>Veengoot</b> en het natuurgebied Veengoot-Mariënvelde.', 'De geschiedenis van de <b>heide-ontginningen</b> rond Halle.', 'De ligging als <b>deelgebied van Staatsbosbeheer</b> in de Achterhoek.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Weide- en zangvogels</b> in het open land.', '<span class="months">Mei–Jun</span> 🌸 <b>Bermbloei</b> langs wegen en paden.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> langs de kerkpaden.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfst</b> over de ontginningen.'],
 'wild': ['🐦 Veldleeuwerik · Graspieper · Buizerd', '🦌 Ree · Haas', '🦋 Bont zandoogje · Klein geaderd witje', '🌿 Pitrus · Pijpenstrootje (historische heidegrond)', '🌳 Zomereik · Grove den · Meidoorn'],
 'trail': ['Wandel de <b>rondwandeling van 13 km</b> vanaf de Halle-Heideweg.', 'Loop het stuk langs de <b>Veengoot</b> tussen Mariënvelde en Halle-Heide.', 'Start in <b>Mariënvelde</b> en wandel via de kerkpaden naar Halle.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Paden in drogere periodes goed begaanbaar · 🚶 Rustige wegen, zandpaden en kerkpaden'
}, {
 'tags': ['Gelderland · Halle–Mariënvelde (Oost Gelre)', 'Sub-area of Staatsbosbeheer and historic heathland at the hamlet of Halle-Heide · church paths and the Veengoot brook', 'list 36 · no. 656'],
 'loc': '📍 Hamlet of Halle-Heide near Halle (municipality of Oost Gelre), towards Mariënvelde · freely accessible; a 13 km circuit starts at the Halle-Heideweg',
 'desc': 'The <b>Hallse Heide</b> features on the terrain list of <b>Staatsbosbeheer</b> as a sub-area of its Achterhoek nature area and also lives on in the name of the hamlet <b>Halle-Heide</b> between <b>Halle and Mariënvelde</b>. The “heath” here is mostly history: the extensive heathland of the old common of Halle was reclaimed in the nineteenth and twentieth centuries into open pasture and arable land, interspersed with woods, shelterbelts and hedgerows. The Staatsbosbeheer terrain has no visitor page of its own; to experience the area, walk the robust <b>13-kilometre circuit</b> that starts in the hamlet and leads via quiet roads, sandy tracks and well-kept <b>church paths</b> to Mariënvelde. Along the way the route follows the <b>Veengoot</b> brook and passes through the Veengoot-Mariënvelde nature area, returning via the Oude Schoolpad to Halle-Heide; in drier periods the paths are easily passable. The land lies wide and quiet — with catering in Mariënvelde after about 8.5 kilometres.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds), May–Jun (blooming verges), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning or late afternoon — quiet on the church paths.',
 'why': ['The <b>13-kilometre circuit</b> over church paths and the Oude Schoolpad.', 'The <b>Veengoot</b> and the Veengoot-Mariënvelde nature area.', 'The history of the <b>heath reclamations</b> around Halle.', 'Its position as a <b>sub-area of Staatsbosbeheer</b> in the Achterhoek.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Meadow and song birds</b> in the open land.', '<span class="months">May–Jun</span> 🌸 <b>Verge bloom</b> along roads and paths.', '<span class="months">Sep–Oct</span> 🍄 <b>Mushrooms</b> along the church paths.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> over the reclamations.'],
 'wild': ['🐦 Skylark · Meadow pipit · Buzzard', '🦌 Roe deer · Hare', '🦋 Speckled wood · Green-veined white', '🌿 Soft rush · Purple moor-grass (historic heath soil)', '🌳 Pedunculate oak · Scots pine · Hawthorn'],
 'trail': ['Walk the <b>13 km circuit</b> from the Halle-Heideweg.', 'Follow the section along the <b>Veengoot</b> between Mariënvelde and Halle-Heide.', 'Start in <b>Mariënvelde</b> and walk via the church paths to Halle.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Paths easily passable in drier periods · 🚶 Quiet roads, sandy tracks and church paths'
}))

C.append(mk.card(1938, 'Lievelderveld', {
 'tags': ['Gelderland · Lievelde (Oost Gelre)', 'Natuurterrein van Staatsbosbeheer in het brongebied van de Lievelderbeek · ’t Grieze Veld en natte heide met kwel · 48 Rode-Lijstsoorten in twee jaar', 'list 36 · no. 657'],
 'loc': '📍 Ten noorden van Lievelde, tussen Zieuwent, Vragender en de Koolmansdijk · vrij toegankelijk op de paden; wandelroutes starten rond Lievelde',
 'desc': 'Het <b>Lievelderveld</b> is een natuurterrein van <b>Staatsbosbeheer</b> in het <b>brongebied van de Lievelderbeek</b>, onderdeel van een ecologische verbindingszone die via het Lievelderbroek en de Koolmansdijk aansluit op het Korenburgerveen. Het terrein ligt in een kwelgebied: mineraalrijk grondwater welt hier op, wat de basis vormt voor <b>natte heide, heischrale graslanden, blauwgrasland en vennen</b> — in het Gelders Natuurnetwerk geldt het Lievelderveld dan ook als parel van natte heide. De bekendste plek is <b>’t Grieze Veld</b>, een voormalig bouwland waarvan eind vorige eeuw de mineraalrijke bovenlaag is afgeschraapt; op de schrale ondergrond die achterbleef ontstond een bijzondere vegetatie. Samen met de Koolmansdijk en de Nijkampsheide leverde het terrein rond Zieuwent en Lievelde binnen twee jaar <b>48 Rode-Lijstsoorten</b> van vaatplanten op. Over het gebied lopen wandelroutes rond Lievelde, waaronder het <b>’t Griezeveldpad</b> van circa 12 kilometer dat door ’t Grieze Veld en het Lievelderveld voert en onderweg ook de Lievelder Schans uit 1627 aandoet, onderdeel van de circumvallatielinie van Groenlo.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Aug</b> (bloeiende heide en graslanden), jun–jul (orchideeën en gentianen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend of vroege avond.',
 'why': ['Het <b>kwelgebied met natte heide</b> als parel van het Gelders Natuurnetwerk.', 'De <b>48 Rode-Lijstsoorten</b> na natuurherstel in ’t Grieze Veld.', 'De wandelroute <b>’t Griezeveldpad</b> van circa 12 kilometer.', 'De ligging in de <b>ecologische verbindingszone</b> richting Korenburgerveen.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌸 <b>Heischrale graslanden</b> in bloei.', '<span class="months">Aug–Sep</span> 🪰 <b>Libellen</b> boven de vennen.', '<span class="months">Jul–Aug</span> 🌸 <b>Natte heide</b> bloeit paars.', '<span class="months">Apr–Jun</span> 🐸 <b>Boomkikkers</b> in poelen en randzones.'],
 'wild': ['🐸 Boomkikker · Kamsalamander', '🐦 Boomvalk · Geelgors · Graspieper', '🦋 Hooibeestje · Bont zandoogje', '🌿 Klokjesgentiaan · Zonnedauw · Wilde orchis', '🌳 Grove den · Zomereik · Zachte berk'],
 'trail': ['Wandel het <b>’t Griezeveldpad</b> (circa 12 km) door veld en broek.', 'Loop de kortere ommetjes rond <b>Lievelde</b>.', 'Combineer met de <b>Koolmansdijk</b> en de uitkijktoren bij het Vragenderveen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; honden niet in de vennen · 🚶 Zand- en graspaden, deels onverhard'
}, {
 'tags': ['Gelderland · Lievelde (Oost Gelre)', 'Nature terrain of Staatsbosbeheer in the headwater area of the Lievelderbeek · ’t Grieze Veld and wet heath with seepage · 48 Red List species in two years', 'list 36 · no. 657'],
 'loc': '📍 North of Lievelde, between Zieuwent, Vragender and the Koolmansdijk · freely accessible on the paths; walking routes start around Lievelde',
 'desc': 'The <b>Lievelderveld</b> is a nature terrain of <b>Staatsbosbeheer</b> in the <b>headwater area of the Lievelderbeek</b>, part of an ecological corridor that connects via the Lievelderbroek and the Koolmansdijk to the Korenburgerveen. The terrain lies in a seepage area: mineral-rich groundwater wells up here, forming the basis for <b>wet heath, heath-grassland, blue-grassland and fens</b> — in the Gelders Natuurnetwerk the Lievelderveld therefore counts as a pearl of wet heath. The best-known spot is <b>’t Grieze Veld</b>, a former arable field whose mineral-rich top layer was scraped off at the end of the last century; on the poor subsoil that remained a special vegetation developed. Together with the Koolmansdijk and the Nijkampsheide, the terrain around Zieuwent and Lievelde yielded <b>48 Red List species</b> of vascular plants within two years. Walking routes run through the area around Lievelde, including the <b>’t Griezeveldpad</b> of about 12 kilometres which leads through ’t Grieze Veld and the Lievelderveld and along the way also passes the Lievelder Schans from 1627, part of the circumvallation line of Groenlo.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Aug</b> (blooming heath and grasslands), Jun–Jul (orchids and gentians)<br>\n    <b>Best time of day:</b> Morning or early evening.',
 'why': ['The <b>seepage area with wet heath</b> as a pearl of the Gelders Natuurnetwerk.', 'The <b>48 Red List species</b> after nature restoration in ’t Grieze Veld.', 'The <b>’t Griezeveldpad</b> walking route of about 12 kilometres.', 'Its position in the <b>ecological corridor</b> towards the Korenburgerveen.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌸 <b>Heath-grasslands</b> in bloom.', '<span class="months">Aug–Sep</span> 🪰 <b>Dragonflies</b> above the fens.', '<span class="months">Jul–Aug</span> 🌸 <b>Wet heath</b> blooms purple.', '<span class="months">Apr–Jun</span> 🐸 <b>Tree frogs</b> in pools and edge zones.'],
 'wild': ['🐸 Tree frog · Great crested newt', '🐦 Hobby · Yellowhammer · Meadow pipit', '🦋 Small heath · Speckled wood', '🌿 Marsh gentian · Sundew · Wild orchid', '🌳 Scots pine · Pedunculate oak · Downy birch'],
 'trail': ['Walk the <b>’t Griezeveldpad</b> (about 12 km) through field and fen.', 'Do the shorter circuits around <b>Lievelde</b>.', 'Combine with the <b>Koolmansdijk</b> and the observation tower at the Vragenderveen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; keep dogs out of the fens · 🚶 Sandy and grassy paths, partly unpaved'
}))

C.append(mk.card(1939, 'Reirinkbos', {
 'tags': ['Gelderland · Groenlo (Oost Gelre)', 'Bos van Het Geldersch Landschap (10 ha, verworven 1973) · elzenhakhout, graslandjes en vennetje · circumvallatielinie van Groenlo (1627)', 'list 36 · no. 658'],
 'loc': '📍 Even buiten Groenlo (gemeente Oost Gelre), in het kleinschalige land tussen de stad en Lievelde · vrij toegankelijk op de paden',
 'desc': 'Het <b>Reirinkbos</b> is een bos van <b>Het Geldersch Landschap</b> van circa 10 hectare, in 1973 verworven en gelegen even buiten <b>Groenlo</b> in de gemeente Oost Gelre — het beboste deel van het voormalige landgoed Reirink, dat verder uit cultuurgronden en een oude boerderij bestaat. In het bos wisselen gemengd bos, <b>elzenhakhout, natuurgraslandjes, een vennetje en poelen</b> elkaar af: precies het kleinschalige Achterhoekse patroon dat in de omgeving grotendeels verdween toen de houtwallen rond boerderijen en percelen werden verwijderd. Botanisch opvallend zijn wilde gagel en dubbelloof, oud-bosindicatoren als bosanemoon, gewone salomonszegel en witte klaverzuring, en in de vochtige graslanden waterkruiskruid en echte koekoeksbloem. Er broeden veel vogels, waaronder de <b>grauwe vliegenvanger</b>, en in de bosranden vliegt de <b>kleine ijsvogelvlinder</b>. Onder de bosbodem ligt geschiedenis: een deel van het Reirinkbos is archeologisch monument — het bos ligt gedeeltelijk op de plek van het voormalige legerkamp van graaf Ernst Casimir in de <b>circumvallatielinie</b> van Groenlo, de 15 kilometer lange belegeringswal met gracht die in 1627 rond de stad werd aangelegd.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (oud-bosflora), mei–jun (vogelzang), okt (herfst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht in het elzenhakhout.',
 'why': ['De <b>kleinschalige afwisseling</b> van bos, hakhout, graslandjes en vennetje.', 'De <b>oud-bosindicatoren</b> en bloeiende graslanden.', 'Het bos op de <b>circumvallatielinie van Groenlo</b> uit 1627.', 'De broedvogels waaronder de <b>grauwe vliegenvanger</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Bosanemoon en salomonszegel</b> in bloei.', '<span class="months">Mrt–Mei</span> 🐸 <b>Amfibieën</b> in poel en vennetje.', '<span class="months">Mei–Jun</span> 🐦 <b>Grauwe vliegenvanger</b> op uitkijkpost.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in het loofbos.'],
 'wild': ['🐦 Grauwe vliegenvanger · Boomklever · Buizerd', '🦋 Kleine ijsvogelvlinder', '🐸 Bruine kikker · Kleine watersalamander', '🦌 Ree · Eekhoorn', '🌿 Bosanemoon · Salomonszegel · Dubbelloof · Wilde gagel'],
 'trail': ['Wandel over de paden van het <b>Reirinkbos</b> bij Groenlo.', 'Verken de omgeving via de wegen van het <b>landgoed Reirink</b>.', 'Combineer met de <b>circumvallatielinie</b> en de vestingstad Groenlo.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Archeologisch monument: niet graven · 🚶 Bospaden, deels onverhard'
}, {
 'tags': ['Gelderland · Groenlo (Oost Gelre)', 'Wood of Het Geldersch Landschap (10 ha, acquired 1973) · alder coppice, grassland patches and a small fen · circumvallation line of Groenlo (1627)', 'list 36 · no. 658'],
 'loc': '📍 Just outside Groenlo (municipality of Oost Gelre), in the small-scale land between the town and Lievelde · freely accessible on the paths',
 'desc': 'The <b>Reirinkbos</b> is a wood of <b>Het Geldersch Landschap</b> of about 10 hectares, acquired in 1973 and situated just outside <b>Groenlo</b> in the municipality of Oost Gelre — the wooded part of the former Reirink estate, which further consists of farmland and an old farmstead. In the wood, mixed forest, <b>alder coppice, nature grassland patches, a small fen and pools</b> alternate: precisely the small-scale Achterhoek pattern that largely disappeared in the surroundings when the hedgerows around farms and parcels were removed. Botanically striking are wild bog-myrtle and hard fern, old-wood indicators such as wood anemone, common Solomon’s seal and wood sorrel, and in the wet grasslands water ragwort and ragged-robin. Many birds breed here, including the <b>spotted flycatcher</b>, and the <b>white admiral</b> flies along the forest edges. History lies beneath the forest floor: part of the Reirinkbos is an archaeological monument — the wood lies partly on the site of the former army camp of Count Ernst Casimir in the <b>circumvallation line</b> of Groenlo, the 15-kilometre siege rampart with moat built around the town in 1627.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (old-wood flora), May–Jun (birdsong), Oct (autumn)<br>\n    <b>Best time of day:</b> Morning — light in the alder coppice.',
 'why': ['The <b>small-scale variety</b> of wood, coppice, grassland and fen.', 'The <b>old-wood indicators</b> and blooming grasslands.', 'The wood on the <b>circumvallation line of Groenlo</b> from 1627.', 'The breeding birds, including the <b>spotted flycatcher</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Wood anemone and Solomon’s seal</b> in bloom.', '<span class="months">Mar–May</span> 🐸 <b>Amphibians</b> in pool and fen.', '<span class="months">May–Jun</span> 🐦 <b>Spotted flycatcher</b> on its lookout.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the broadleaf wood.'],
 'wild': ['🐦 Spotted flycatcher · Nuthatch · Buzzard', '🦋 White admiral', '🐸 Common frog · Smooth newt', '🦌 Roe deer · Red squirrel', '🌿 Wood anemone · Solomon’s seal · Hard fern · Bog-myrtle'],
 'trail': ['Walk the paths of the <b>Reirinkbos</b> near Groenlo.', 'Explore the surroundings via the roads of the <b>Reirink estate</b>.', 'Combine with the <b>circumvallation line</b> and the fortified town of Groenlo.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Archaeological monument: no digging · 🚶 Forest paths, partly unpaved'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1939)
mk.check()
