# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2020, 'Achthoven en Lakerveld', {
 'tags': ['Vijfheerenlanden · polders tussen Lexmond, Ameide en Meerkerk', 'Polder Achthoven 118 ha met blauwgraslanden · Polder Lakerveld met griend-in-wording tot bos · Zuid-Hollands Landschap', 'list 36 · no. 739'],
 'loc': '📍 Polder Achthoven tussen Lekdijk en Molenkade (Lexmond–Ameide); Polder Lakerveld bij de Lakerveldse Molenkade in Lexmond · terreinen niet vrij toegankelijk — overzien vanaf de kades; Sprinkhaanzangroute 13,5–15 km',
 'desc': '<b>Polder Achthoven</b> en <b>polder Lakerveld</b> zijn de twee Zuid-Hollands Landschap-polders die samen met de Zouweboezem één moerascomplex vormen. Achthoven (± 118 hectare, tussen de Lekdijk en de Molenkade) is een openbaar vogelgebied van <b>vochtige, soortenrijke graslanden</b>: langgerekte percelen met natte schraallanden — mede daarom liggen hier enkele van de <b>blauwgraslanden</b> van de Vijfheerenlanden — afgewisseld met ruige landen, een waterplas, boomgaarden, elzensingels en knotboomrijen. De polder is foerageergebied van de moerasvogels van de naastgelegen boezem: wie in de vroege ochtend over de kade loopt ziet de <b>purperreigers</b> neerstrijken om in de wei naar de grote modderkruiper en kamsalamander van deze polders te vissen. <b>Polder Lakerveld</b>, ten zuiden van Lexmond, is smaller en beslotener: de oude <b>griend is buiten gebruik</b> en wordt omgevormd tot gevarieerder, vitaler bos; ’s winters grazen er ganzen, in het voorjaar scharrelen <b>scholeksters, kieviten en tureluurs</b> en in de schemering lopen er hazen. De polder wordt bemalen als vanouds: tot 1925 deden twee windmolens dat werk — de <b>Achthovense Baakmolen</b> van 1777 verdween pas in 1999. De terreinen zelf blijven rustgebied; de kades eromheen zijn het panoramaterras.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels; purperreigers foeragerend), mei (orchideeën in het blauwgrasland)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — reigers van de Zouweboezem komen foerageren.',
 'why': ['De <b>blauwgraslanden</b> van polder Achthoven — natte schraallanden met orchideeën.', 'De <b>purperreigers</b> van de Zouweboezem foerageren tussen de koeien.', 'De <b>griend van Lakerveld</b> die langzaam bos wordt.', 'De <b>kades als panoramaterras</b>: Molenkade en Lekdijk omsluiten de polders.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogelkoor</b> van kievit, tureluur en grutto.', '<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> in de natte schraallanden.', '<span class="months">Okt–Mrt</span> 🪿 <b>Ganzen</b> grazen de winterpolders leeg.', '<span class="months">Heel jaar</span> 🦦 <b>Modderkruiper en kamsalamander</b> in sloten en poelen.'],
 'wild': ['🦅 Purperreiger · Buizerd · Zilverreiger', '🐦 Kievit · Tureluur · Scholekster', '🐟 Grote modderkruiper · Kamsalamander', '🌸 Blauwgrasland met orchideeën', '🌬️ Achthovense Baakmolen (1777, verdwenen 1999)'],
 'trail': ['Overzie de polders vanaf de <b>Lakerveldse Molenkade</b> in Lexmond en de Lekdijk.', 'Wandel de <b>Sprinkhaanzangroute</b> (13,5–15 km) vanaf Meerkerk langs Lakerveld en Scharperswijk.', 'Combineer met de <b>vogelkijkhut van de Zouweboezem</b> aan de Boezemweg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Terreinen niet vrij toegankelijk — weidevogelrust, vanaf kades kijken · 🚶 Kades en knooppunten rond Lexmond'
}, {
 'tags': ['Vijfheerenlanden · polders between Lexmond, Ameide and Meerkerk', 'Polder Achthoven 118 ha with blue-grassland · Polder Lakerveld with disused copse turning to forest · Zuid-Hollands Landschap', 'list 36 · no. 739'],
 'loc': '📍 Polder Achthoven between Lekdijk and Molenkade (Lexmond–Ameide); Polder Lakerveld at the Lakerveldse Molenkade in Lexmond · grounds not freely accessible — survey from the embankments; Sprinkhaanzangroute 13.5–15 km',
 'desc': '<b>Polder Achthoven</b> and <b>polder Lakerveld</b> are the two Zuid-Hollands Landschap polders that form one marsh complex together with the Zouweboezem. Achthoven (± 118 hectares, between the Lekdijk and the Molenkade) is a bird polder of <b>humid, species-rich grasslands</b>: long parcels with wet meadows — hence some of the Vijfheerenlanden’s <b>blue-grasslands</b> lie here — alternating with rough fields, a pool, orchards, alder rows and lines of pollards. The polder is the foraging ground of the marsh birds of the neighbouring boezem: walk the embankment in the early morning and see the <b>purple herons</b> come down to fish in the meadow for this polder’s weather loach and warty newt. <b>Polder Lakerveld</b>, south of Lexmond, is narrower and more secluded: the old <b>willow copse is out of use</b> and is being transformed into more varied, livelier forest; in winter geese graze here, in spring <b>oystercatchers, lapwings and redshanks</b> scuttle about and at dusk hares run. The polder is drained as of old: until 1925 two windmills did that work — the <b>Achthovense Baakmolen</b> of 1777 disappeared only in 1999. The grounds themselves stay quiet reserves; the embankments around them are the panorama terrace.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds; purple herons feeding), May (orchids in the blue-grassland)<br>\\n    <b>Best time of day:</b> Early morning — herons from the Zouweboezem come to feed.',
 'why': ['The <b>blue-grasslands</b> of polder Achthoven — wet meadows with orchids.', 'The <b>purple herons</b> of the Zouweboezem feeding among the cows.', 'The <b>Lakerveld copse</b> slowly becoming forest.', 'The <b>embankments as panorama terrace</b>: Molenkade and Lekdijk enclose the polders.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow-bird chorus</b> of lapwing, redshank and godwit.', '<span class="months">May–Jun</span> 🌸 <b>Orchids</b> in the wet meadows.', '<span class="months">Oct–Mar</span> 🪿 <b>Geese</b> graze the winter polders bare.', '<span class="months">All year</span> 🦦 <b>Weather loach and warty newt</b> in ditches and pools.'],
 'wild': ['🦅 Purple heron · Common buzzard · Great egret', '🐦 Lapwing · Redshank · Oystercatcher', '🐟 Weather loach · Warty newt', '🌸 Blue-grassland with orchids', '🌬️ Achthovense Baakmolen windmill (1777, gone 1999)'],
 'trail': ['Survey the polders from the <b>Lakerveldse Molenkade</b> in Lexmond and the Lekdijk.', 'Walk the <b>Sprinkhaanzangroute</b> (13.5–15 km) from Meerkerk past Lakerveld and Scharperswijk.', 'Combine with the <b>Zouweboezem bird hide</b> on the Boezemweg.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Grounds not freely accessible — meadow-bird peace, view from embankments · 🚶 Embankments and nodes around Lexmond'
}))

C.append(mk.card(2021, 'Eendenkooi Achthoven', {
 'tags': ['Vijfheerenlanden · polder Achthoven (Lexmond)', 'De “Kleine kooi” — gegraven plas met vier vangpijpen · nog volledig in gebruik bij een vrijwillige kooiker · rijksmonumentaal kooikershuisje', 'list 36 · no. 740'],
 'loc': '📍 In polder Achthoven tussen Lexmond en Ameide · niet te bezichtigen, behalve bij de ongeveer jaarlijkse open dag; te bekijken vanaf de kades rond de polder',
 'desc': 'De <b>eendenkooi Achthoven</b> — in de streek de <b>‘Kleine kooi’</b>, naast de ‘Groote kooi’ De Kuilen aan de Lekdijk — is een middelgrote kooi met een <b>gegraven, rechthoekige plas</b> waar vier lange <b>vangpijpen</b> het kooibos in lopen. In tegenstelling tot de kolkkooien van de Zouwe is deze plas met de hand gegraven, en dat is aan de regelmaat van het geheel te zien. De kooi is <b>nog volledig intact en in gebruik</b>: een vrijwillige kooiker onderhoudt het riet, de pijpen en de <b>lokvogels</b>, en in het seizoen wordt er gevangen volgens de eeuwenoude methode — voer, kooikershond en de bocht van de pijp doen de rest. Het <b>stenen kooikershuisje onder het rieten dak</b> (eind achttiende, begin negentiende eeuw) staat als <b>rijksmonument</b> in de polder. Voor de vogels is de kooi het rustigste plek van het hele Zouweboezemcomplex: water- en moerasvogels van de boezem profiteren van de stilte, en binnen de <b>kooicirkel</b> geldt het afpalingsrecht van de kooiker. Bezoek is er daarom niet bij — behalve tijdens de <b>ongeveer jaarlijkse open dag</b>, wanneer de kooi haar geheimen laat zien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–Mrt</b> (kooiseizoen), apr–jun (zang in het kooibos)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — het uur van de kooiker.',
 'why': ['Een <b>gegraven kooiplas</b> met vier vangpijpen, nog volledig intact.', 'Het <b>rijksmonumentale, stenen kooikershuisje</b> met rieten dak.', 'Een <b>actieve vrijwillige kooiker</b> — levende kooicultuur in de Vijfheerenlanden.', 'De <b>jaarlijkse open dag</b>: de enige kans om de kooi vanbinnen te zien.'],
 'phen': ['<span class="months">Sep–Mrt</span> 🦆 <b>Kooiseizoen</b>: vangst met lokvogels en hond.', '<span class="months">Apr–Jun</span> 🎵 <b>Zangvogels</b> in het kooibos van wilg en elzen.', '<span class="months">Nov–Mrt</span> 🌳 <b>Griendhakhout</b> in winterse vormen.', '<span class="months">Heel jaar</span> 🤫 <b>Kooicirkel-stilte</b> midden in het moerascomplex.'],
 'wild': ['🦆 Vangst: smient · krakeend · wintertaling', '🐦 Watervogels en moeraszangers van de boezem', '🏡 Stenen kooikershuisje (rijksmonument)', '🌳 Kooibos met vier vangpijpen', '🔓 Jaarlijkse open dag'],
 'trail': ['Wandel de kades rond <b>polder Achthoven</b> (Lekdijk–Molenkade) langs de kooi.', 'Combineer met de <b>vogelkijkhut van de Zouweboezem</b> aan de Boezemweg.', 'Houd de <b>open dag</b> in de gaten via regionale agenda’s en eendenkooi-verenigingen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (vanaf de kade) · ⚠️ Kooi niet openbaar — stiltegebied met afpalingsrecht · 🚶 Kade-rondjes rond Lexmond en Ameide'
}, {
 'tags': ['Vijfheerenlanden · polder Achthoven (Lexmond)', 'The “small decoy” — dug pond with four catch pipes · still fully worked by a volunteer keeper · nationally listed cottage', 'list 36 · no. 740'],
 'loc': '📍 In polder Achthoven between Lexmond and Ameide · not open to visitors except at the roughly annual open day; viewed from the embankments around the polder',
 'desc': 'The <b>Achthoven duck decoy</b> — locally the <b>‘small decoy’</b>, beside the ‘great decoy’ De Kuilen on the Lekdijk — is a medium-sized decoy with a <b>dug, rectangular pond</b> from which four long <b>catch pipes</b> run into the decoy wood. Unlike the scour-hole decoys of the Zouwe, this pond was dug by hand, and the regularity of it all shows. The decoy is <b>still fully intact and in use</b>: a volunteer keeper maintains the reed, the pipes and the <b>call birds</b>, and in the season catching follows the centuries-old method — feed, decoy dog and the bend of the pipe do the rest. The <b>stone keeper’s cottage under its thatched roof</b> (late eighteenth, early nineteenth century) stands in the polder as a <b>listed monument</b>. For the birds the decoy is the quietest spot of the whole Zouweboezem complex: water and marsh birds of the boezem profit from the silence, and within the <b>decoy circle</b> the keeper’s posting right applies. Visiting is therefore not on — except during the <b>roughly annual open day</b>, when the decoy shows her secrets.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Mar</b> (decoy season), Apr–Jun (song in the decoy wood)<br>\\n    <b>Best time of day:</b> Early morning — the keeper’s hour.',
 'why': ['A <b>dug decoy pond</b> with four catch pipes, still fully intact.', 'The <b>listed stone keeper’s cottage</b> with thatched roof.', 'An <b>active volunteer keeper</b> — living decoy culture in the Vijfheerenlanden.', 'The <b>annual open day</b>: the only chance to see the decoy inside.'],
 'phen': ['<span class="months">Sep–Mar</span> 🦆 <b>Decoy season</b>: catching with call birds and dog.', '<span class="months">Apr–Jun</span> 🎵 <b>Songbirds</b> in the decoy wood of willow and alder.', '<span class="months">Nov–Mar</span> 🌳 <b>Coppice wood</b> in winter shapes.', '<span class="months">All year</span> 🤫 <b>Decoy-circle silence</b> amid the marsh complex.'],
 'wild': ['🦆 Catch: wigeon · gadwall · teal', '🐦 Water birds and marsh warblers of the boezem', '🏡 Stone keeper’s cottage (listed monument)', '🌳 Decoy wood with four catch pipes', '🔓 Annual open day'],
 'trail': ['Walk the embankments around <b>polder Achthoven</b> (Lekdijk–Molenkade) past the decoy.', 'Combine with the <b>Zouweboezem bird hide</b> on the Boezemweg.', 'Watch for the <b>open day</b> in regional agendas and decoy associations.'],
 'foot': '🐕 Dogs on lead · 💶 Free (from the embankment) · ⚠️ Decoy not public — quiet zone with posting right · 🚶 Embankment loops around Lexmond and Ameide'
}))

C.append(mk.card(2022, 'De Kuilen', {
 'tags': ['Vijfheerenlanden · Lexmond (aan de Lekdijk)', 'De “Groote kooi” — kooi in een doorbraakkolk uit 1740/1744 · als schietkooi gebruikt eind jaren dertig, één vangpijp behouden', 'list 36 · no. 741'],
 'loc': '📍 Aan de Lekdijk ten noorden van Lexmond · niet openbaar — te overzien vanaf de Lekdijk; combi met de uiterwaarden en de Zouweboezem-vogelkijkhut',
 'desc': '<b>De Kuilen</b> bij Lexmond is de <b>‘Groote kooi’</b> van het Zouweboezemgebied: een eendenkooi die ontstond in een <b>doorbraakkolk uit 1740 en 1744</b> — een wiel dat de Lek tweemaal sloeg en dat, zo leerde de kadasterkaart, in de eerste helft van de negentiende eeuw tot kooi werd omgebouwd; de perceelsomschrijving luidde tot dan toe simpel <b>‘Onland’</b>. De kooi kende zijn kooiers: <b>Henk Stravers</b> kooide er jarenlang, en eind jaren dertig huurde het jachtgezelschap <b>‘Nimrod’</b> van de familie Van der Heiden de kooi — de vangkooi werd <b>schietkooi</b>, al bleef één van de vier vangpijpen intact, zodat het <b>paalrecht van 150 meter</b> behouden bleef. Vandaag is De Kuilen niet langer een van de geregistreerde, werkende kooien (dat zijn De Zouwe en Achthoven), maar het kooibos van wilgengriend en loofhout ligt er nog, als groene vinger aan de Lekdijk tussen de uiterwaarden en de boezem. Voor wie de kades loopt is het een leesbaar stukje <b>verdwenen kooicultuur</b>: de plas en de pijpcontouren zijn in het landschap terug te vinden, en de naam De Kuilen herinnert aan de kolken waar het mee begon.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Okt–Mrt</b> (winterstilte in het kooibos), apr–jun (zangvogels)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over de kolk en het kooibos.',
 'why': ['De <b>doorbraakkolk van 1740/1744</b>: het wiel waarmee de kooi begon.', 'Het <b>‘Onland’</b> van het kadaster dat kooi werd — leesbare geschiedenis.', 'Het verhaal van <b>schietkooi ‘Nimrod’</b> en het behoud van één vangpijp.', 'Het <b>kooibos als groene vinger</b> aan de Lekdijk bij Lexmond.'],
 'phen': ['<span class="months">Okt–Mrt</span> 🌳 <b>Winterse stilte</b> in het voormalige kooibos.', '<span class="months">Apr–Jun</span> 🎵 <b>Zangvogels</b> in wilgengriend en loofhout.', '<span class="months">Heel jaar</span> 📖 <b>Kolk en pijpen</b> in het veld afleesbaar.', '<span class="months">Nov–Mrt</span> 🪿 <b>Ganzen</b> uit de uiterwaarden overtrekkend.'],
 'wild': ['🌳 Wilgengriend en gemengd loofhout', '🐦 Zangvogels van kooibos en rietkraag', '🌊 Doorbraakkolk (wiel) uit 1740/1744', '📖 Kooigeschiedenis: Stravers en ‘Nimrod’', '🤫 Paalrecht-zone van 150 meter'],
 'trail': ['Wandel de <b>Lekdijk bij Lexmond</b> langs De Kuilen richting Ameide.', 'Combineer met de <b>uiterwaarden</b> en de <b>Zederikkade</b>.', 'Sluit af bij de <b>vogelkijkhut van de Zouweboezem</b> (Boezemweg, ± 1,5 km lopen).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Kooi niet openbaar — vanaf de Lekdijk bekijken · 🚶 Lekdijk-rondjes Lexmond–Ameide'
}, {
 'tags': ['Vijfheerenlanden · Lexmond (on the Lekdijk)', 'The “great decoy” — decoy in a breach pool of 1740/1744 · used as a shooting decoy in the late 1930s, one catch pipe kept', 'list 36 · no. 741'],
 'loc': '📍 On the Lekdijk north of Lexmond · not open to the public — surveyed from the Lekdijk; combine with the floodplains and the Zouweboezem bird hide',
 'desc': '<b>De Kuilen</b> (‘The Pools’) at Lexmond is the <b>‘great decoy’</b> of the Zouweboezem area: a duck decoy that arose in a <b>breach pool of 1740 and 1744</b> — a scour hole the Lek struck twice, which, as the cadastral map shows, was converted into a decoy in the first half of the nineteenth century; until then the parcel description read simply <b>‘waste land’</b>. The decoy knew its keepers: <b>Henk Stravers</b> worked it for years, and in the late 1930s the hunting party <b>‘Nimrod’</b> of the Van der Heiden family hired the decoy — the catch decoy became a <b>shooting decoy</b>, though one of the four catch pipes stayed intact so that the <b>posting right of 150 metres</b> was preserved. Today De Kuilen is no longer one of the registered working decoys (those are De Zouwe and Achthoven), but its decoy wood of willow copse and broadleaf still lies there, a green finger on the Lekdijk between the floodplains and the boezem. For those walking the embankments it is a readable piece of <b>vanished decoy culture</b>: the pond and the pipe contours can be found back in the land, and the name De Kuilen recalls the pools where it all began.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Oct–Mar</b> (winter silence in the decoy wood), Apr–Jun (songbirds)<br>\\n    <b>Best time of day:</b> Morning — light over the scour hole and the decoy wood.',
 'why': ['The <b>breach pool of 1740/1744</b>: the scour hole where the decoy began.', 'The cadastral <b>‘waste land’</b> that became a decoy — readable history.', 'The story of the <b>‘Nimrod’ shooting decoy</b> and the preserved catch pipe.', 'The <b>decoy wood as a green finger</b> on the Lekdijk at Lexmond.'],
 'phen': ['<span class="months">Oct–Mar</span> 🌳 <b>Winter silence</b> in the former decoy wood.', '<span class="months">Apr–Jun</span> 🎵 <b>Songbirds</b> in willow copse and broadleaf.', '<span class="months">All year</span> 📖 <b>Pool and pipes</b> readable in the field.', '<span class="months">Nov–Mar</span> 🪿 <b>Geese</b> passing over from the floodplains.'],
 'wild': ['🌳 Willow copse and mixed broadleaf', '🐦 Songbirds of decoy wood and reed fringe', '🌊 Breach pool (scour hole) of 1740/1744', '📖 Decoy history: Stravers and ‘Nimrod’', '🤫 Posting-right zone of 150 metres'],
 'trail': ['Walk the <b>Lekdijk at Lexmond</b> past De Kuilen towards Ameide.', 'Combine with the <b>floodplains</b> and the <b>Zederikkade</b>.', 'Finish at the <b>Zouweboezem bird hide</b> (Boezemweg, ± 1.5 km walk).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Decoy not open to the public — view from the Lekdijk · 🚶 Lekdijk loops Lexmond–Ameide'
}))

C.append(mk.card(2023, 'Zouweboezem', {
 'tags': ['Vijfheerenlanden · langgerekt tussen Ameide, Lexmond en Meerkerk', 'Natura 2000-moeras van rietvelden en moerasbos · grootste purperreigerkolonie van Nederland (218 nesten in 2023) · Zuid-Hollands Landschap', 'list 36 · no. 742'],
 'loc': '📍 Tussen Ameide (noord) en Meerkerk (zuid) · parkeerplaats Boezemweg: vlonderpad + kijkscherm, vogelkijkhut op ± 1,5 km; gele route vanaf de Grote Kanaaldijk bij Meerkerk (13,5–15 km); bus 153 halte Sluis',
 'desc': 'De <b>Zouweboezem</b> is het kloppende hart van de Vijfheerenlanden: een langgerekt <b>Natura 2000-moeras</b> tussen <b>Ameide, Lexmond en Meerkerk</b>, ontstaan als <b>boezem</b> waar de molens op de Zederikkade eeuwenlang het polderwater heen maalden — en beroemd als <b>productieperceel voor rietdekkers</b>, wiens riet de boerendaken van de streek dekte. Vandaag is het gebied van het <b>Zuid-Hollands Landschap</b> het domein van de <b>grootste broedkolonie purperreigers van Nederland</b>: in 2023 werden <b>218 nesten</b> geteld, gedeeld met <b>lepelaars en blauwe reigers</b> — de kolonie verhuisde van het rietland naar het <b>moerasbos</b>, veilig voor de vos, en wordt tegenwoordig zelfs met een drone geteld. In de rietvelden broeden <b>zwarte stern, porseleinhoen, snor en Cetti’s zanger</b>; over de boezem jagen <b>bruine kiekendieven</b>, en in de schorren leven <b>roerdomp, waterral en baardman</b>. <b>Schotse hooglanders</b> houden de oevers open. Het <b>vlonderpad</b> (geopend 1 april 2000) en de <b>vogelkijkhut</b> aan de Boezemweg dragen je het moeras in; wie de volle rondgang wil loopt de gele route vanaf <b>Meerkerk</b> langs de Vlietmolen naar huis. Het kleinste Belangrijke Vogelgebied van Nederland — en misschien wel het mooiste.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Sep</b> (purperreigers, rietvogels; tops in mei–jun), aug–okt (trek)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — reigers op de vleugel, riet in zang.',
 'why': ['De <b>grootste purperreigerkolonie van Nederland</b> — met lepelaar en blauwe reiger (218 nesten in 2023).', 'Het <b>vlonderpad en de vogelkijkhut</b>: het moeras op zonder het te storen.', 'De <b>rietgeschiedenis</b>: productievelden voor de rietdekkers van de streek.', '<b>Zwarte stern, porseleinhoen, snor en Cetti’s zanger</b> in één lang rietland.'],
 'phen': ['<span class="months">Apr–Jul</span> 🦅 <b>Purperreigers</b> vliegen af en aan naar polder Achthoven.', '<span class="months">Mei–Jun</span> 🎵 <b>Snor, Cetti’s zanger en porseleinhoen</b> hoorbaar in de nacht.', '<span class="months">Jun–Aug</span> 🐦 <b>Zwarte stern</b> boven de boezem.', '<span class="months">Aug–Okt</span> 🧭 <b>Trekvogels</b> gebruiken de boezem als tussenstop.'],
 'wild': ['🦅 Purperreiger · Lepelaar · Blauwe reiger', '🐦 Zwarte stern · Porseleinhoen · Snor · Cetti’s zanger', '🐦 Roerdomp · Waterral · Baardman · Bruine kiekendief', '🐴 Schotse hooglanders als begrazers', '🐟 Grote modderkruiper in De Boezem'],
 'trail': ['Parkeer aan de <b>Boezemweg</b>: vlonderpad, kijkscherm en vogelkijkhut (± 1,5 km).', 'Loop de <b>gele route</b> vanaf de Grote Kanaaldijk bij Meerkerk (13,5–15 km) met de Vlietmolen.', 'Combineer met <b>polder Achthoven</b> en de Lekdijk tot een grote rondwandeling (± 9,5 km).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op paden en vlonderpad — broedseizoenrust in het riet · 🚶 Knooppuntennetwerk; rondloop vanaf Ameide of Meerkerk'
}, {
 'tags': ['Vijfheerenlanden · stretched out between Ameide, Lexmond and Meerkerk', 'Natura 2000 marsh of reed beds and swamp forest · the Netherlands’ largest purple heron colony (218 nests in 2023) · Zuid-Hollands Landschap', 'list 36 · no. 742'],
 'loc': '📍 Between Ameide (north) and Meerkerk (south) · Boezemweg car park: boardwalk + viewing screen, bird hide at ± 1.5 km; yellow route from the Grote Kanaaldijk at Meerkerk (13.5–15 km); bus 153 stop Sluis',
 'desc': 'The <b>Zouweboezem</b> is the beating heart of the Vijfheerenlanden: a long <b>Natura 2000 marsh</b> between <b>Ameide, Lexmond and Meerkerk</b>, born as a <b>reservoir</b> to which the windmills on the Zederikkade pumped the polder water for centuries — and famous as a <b>production field for thatchers</b>, whose reed covered the region’s farm roofs. Today the <b>Zuid-Hollands Landschap</b> reserve is the domain of the <b>largest purple heron colony in the Netherlands</b>: in 2023 <b>218 nests</b> were counted, shared with <b>spoonbills and grey herons</b> — the colony moved from the reed beds to the <b>swamp forest</b>, safe from the fox, and is nowadays even counted by drone. In the reed fields breed <b>black tern, spotted crake, Savi’s warbler and Cetti’s warbler</b>; <b>marsh harriers</b> hunt over the boezem, and in the sedge beds live <b>bittern, water rail and bearded tit</b>. <b>Scottish highlanders</b> keep the banks open. The <b>boardwalk</b> (opened 1 April 2000) and the <b>bird hide</b> on the Boezemweg carry you into the marsh; for the full circuit walk the yellow route from <b>Meerkerk</b> past the Vlietmolen home. The smallest Important Bird Area of the Netherlands — and quite possibly its finest.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Sep</b> (purple herons, reed birds; peak May–Jun), Aug–Oct (passage)<br>\\n    <b>Best time of day:</b> Early morning — herons on the wing, reed in song.',
 'why': ['The <b>largest purple heron colony in the Netherlands</b> — with spoonbill and grey heron (218 nests in 2023).', 'The <b>boardwalk and bird hide</b>: into the marsh without disturbing it.', 'The <b>reed history</b>: production fields for the region’s thatchers.', '<b>Black tern, spotted crake, Savi’s warbler and Cetti’s warbler</b> in one long reed bed.'],
 'phen': ['<span class="months">Apr–Jul</span> 🦅 <b>Purple herons</b> fly to and from polder Achthoven.', '<span class="months">May–Jun</span> 🎵 <b>Savi’s, Cetti’s and spotted crake</b> audible at night.', '<span class="months">Jun–Aug</span> 🐦 <b>Black tern</b> above the boezem.', '<span class="months">Aug–Oct</span> 🧭 <b>Migrating birds</b> use the boezem as a stopover.'],
 'wild': ['🦅 Purple heron · Spoonbill · Grey heron', '🐦 Black tern · Spotted crake · Savi’s warbler · Cetti’s warbler', '🐦 Bittern · Water rail · Bearded tit · Marsh harrier', '🐴 Scottish highlanders as grazers', '🐟 Weather loach in De Boezem'],
 'trail': ['Park at the <b>Boezemweg</b>: boardwalk, viewing screen and bird hide (± 1.5 km).', 'Walk the <b>yellow route</b> from the Grote Kanaaldijk at Meerkerk (13.5–15 km) with the Vlietmolen.', 'Combine with <b>polder Achthoven</b> and the Lekdijk into one big loop (± 9.5 km).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on paths and boardwalk — breeding-season peace in the reed · 🚶 Node network; loop from Ameide or Meerkerk'
}, n2k='Zouweboezem — Vogelrichtlijngebied en een van de kleinste Important Bird Areas van Nederland: de grootste purperreigerkolonie van Nederland (record 218 nesten in 2023, samen met lepelaar en blauwe reiger), voorts zwarte stern, porseleinhoen, roerdomp, snor, Cetti’s zanger en bruine kiekendief; in De Boezem één van Nederland’s grootste populaties grote modderkruiper.',
 n2k_en='Zouweboezem — Bird Directive site and one of the smallest Important Bird Areas of the Netherlands: the country’s largest purple heron colony (record 218 nests in 2023, alongside spoonbill and grey heron), further black tern, spotted crake, bittern, Savi’s warbler, Cetti’s warbler and marsh harrier; in De Boezem one of the Netherlands’ largest populations of weather loach.'))

C.append(mk.card(2024, 'Scharperswijk', {
 'tags': ['Vijfheerenlanden · ten zuiden van Lexmond', '52 hectare authentiek kavelpatroon met grienden en hooilanden · wilgentenenoogst, kranswiersloten en sprinkhaanzangers · Zuid-Hollands Landschap', 'list 36 · no. 743'],
 'loc': '📍 Heicopperweg bij Lexmond · overzien vanaf de Bastaardkade en langs het Merwedekanaal (Hoekmolen); geen paden door het terrein — kades en kanaaldijk volgen',
 'desc': '<b>Scharperswijk</b> ten zuiden van Lexmond is het reservaat waar de tijd stil lijkt te hebben gestaan: 52 hectare met het <b>authentieke kavelpatroon van de Vijfheerenlanden</b> — langgerekte percelen grasland afgewisseld met <b>grienden</b>, waarin het <b>Zuid-Hollands Landschap</b> nog precies als vroeger <b>wilgentenenoogst</b>: het hakhout dat manden en schuttingen leverde en de winter het werk van de griendwerkers was. De sloten van Scharperswijk zijn <b>kraakhelder</b>: er groeien <b>kranswieren</b>, onderwaterwouden van algen die alleen in zuiver water gedijen. De vochtige graslanden worden gemaaid en het hooi afgevoerd, zodat de bodem <b>voedselarm</b> blijft — en juist daarom bloeien hier <b>vleeskleurige orchideeën</b> en groeien <b>blauwe en blonde zegge</b>. Vanaf half april klinkt de zang van de <b>sprinkhaanzanger</b>, het onopvallende bruine vogeltje met het hoge geratel waaraan het zijn naam dankt — in Scharperswijk meteen een van de grotere populaties van de streek. Het geheel is omringd door kades; wie de <b>Bastaardkade</b> volgt en terugloopt langs het <b>Merwedekanaal</b>, ziet het reservaat van alle kanten — met de <b>Hoekmolen</b>, die ooit Neder- en Over-Heicop bemaalde, als kapstop aan het water.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (sprinkhaanzanger vanaf half apr; orchideeën in mei), jun (hooitijd)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — sprinkhaanzangers zingen het eerst.',
 'why': ['De <b>wilgentenenoogst</b>: griendcultuur die hier nog echt wordt uitgeoefend.', 'De <b>kranswiersloten</b>: kraakhelder water met onderwaterwouden.', '<b>Vleeskleurige orchideeën</b> en blauwe en blonde zegge op het voedselarme hooiland.', 'De <b>sprinkhaanzanger</b> vanaf half april — het geluid van Scharperswijk.'],
 'phen': ['<span class="months">Apr–Jul</span> 🎵 <b>Sprinkhaanzanger</b>: hoog en snel geratel in de percelen.', '<span class="months">Mei–Jun</span> 🌸 <b>Vleeskleurige orchis</b> bloeit in de hooilanden.', '<span class="months">Nov–Mrt</span> ✂️ <b>Wilgentenenoogst</b> in de grienden.', '<span class="months">Heel jaar</span> 💧 <b>Kranswieren</b> in de heldere sloten.'],
 'wild': ['🐦 Sprinkhaanzanger · Rietgors · Kwikstaart', '🌸 Vleeskleurige orchis · Blauwe en blonde zegge', '💧 Kranswieren in kraakheldere sloten', '🌳 Wilgengrienden met hakhoutbeheer', '🌬️ Hoekmolen aan het Merwedekanaal'],
 'trail': ['Volg de <b>Bastaardkade</b> en keer terug langs het <b>Merwedekanaal</b> (met de Hoekmolen).', 'Wandel of fiets de routetip <b>Ontdek de Vijfheerenlanden</b> (start Nieuwland) langs het reservaat.', 'Combineer met de <b>Sprinkhaanzangroute</b> naar de Zouweboezem en polder Achthoven.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen paden door het terrein — vanaf kades en kanaaldijk overzien · 🚶 Kades rond Lexmond; knooppuntennetwerk'
}, {
 'tags': ['Vijfheerenlanden · south of Lexmond', '52 hectares of authentic parcel pattern with copses and hay meadows · willow-withy harvest, stonewort ditches and grasshopper warblers · Zuid-Hollands Landschap', 'list 36 · no. 743'],
 'loc': '📍 Heicopperweg near Lexmond · surveyed from the Bastaardkade and along the Merwedekanaal (Hoekmolen); no paths through the reserve — follow embankments and canal dike',
 'desc': '<b>Scharperswijk</b> south of Lexmond is the reserve where time seems to have stood still: 52 hectares holding the <b>authentic parcel pattern of the Vijfheerenlanden</b> — long strips of grassland alternating with <b>willow copses</b>, in which the <b>Zuid-Hollands Landschap</b> still harvests <b>willow withies</b> exactly as of old: the coppice that supplied baskets and hurdles and gave the copse workers their winter trade. The ditches of Scharperswijk are <b>crystal clear</b>: <b>stoneworts</b> grow there, underwater forests of algae that thrive only in pure water. The humid grasslands are mown and the hay carried off, keeping the soil <b>nutrient-poor</b> — and precisely therefore <b>marsh orchids</b> flower here and <b>blue and blonde sedges</b> grow. From mid-April the song of the <b>grasshopper warbler</b> sounds, the unremarkable brown bird with the high rattle it is named for — in Scharperswijk straightaway one of the larger populations of the region. The whole is framed by embankments; follow the <b>Bastaardkade</b> and walk back along the <b>Merwedekanaal</b> to see the reserve from every side — with the <b>Hoekmolen</b>, which once drained Neder- and Over-Heicop, as the capstone at the water.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (grasshopper warbler from mid-Apr; orchids in May), Jun (hay time)<br>\\n    <b>Best time of day:</b> Morning — grasshopper warblers sing first.',
 'why': ['The <b>willow-withy harvest</b>: copse culture still truly practised here.', 'The <b>stonewort ditches</b>: crystal-clear water with underwater forests.', '<b>Marsh orchids</b> and blue and blonde sedges on the nutrient-poor hay meadows.', 'The <b>grasshopper warbler</b> from mid-April — the sound of Scharperswijk.'],
 'phen': ['<span class="months">Apr–Jul</span> 🎵 <b>Grasshopper warbler</b>: high, fast rattle in the parcels.', '<span class="months">May–Jun</span> 🌸 <b>Marsh orchid</b> flowering in the hay meadows.', '<span class="months">Nov–Mar</span> ✂️ <b>Willow-withy harvest</b> in the copses.', '<span class="months">All year</span> 💧 <b>Stoneworts</b> in the clear ditches.'],
 'wild': ['🐦 Grasshopper warbler · Reed bunting · Wagtail', '🌸 Marsh orchid · Blue and blonde sedge', '💧 Stoneworts in crystal-clear ditches', '🌳 Willow copses under coppice management', '🌬️ Hoekmolen windmill on the Merwedekanaal'],
 'trail': ['Follow the <b>Bastaardkade</b> and return along the <b>Merwedekanaal</b> (with the Hoekmolen).', 'Walk or cycle the route tip <b>Ontdek de Vijfheerenlanden</b> (start Nieuwland) past the reserve.', 'Combine with the <b>Sprinkhaanzangroute</b> to the Zouweboezem and polder Achthoven.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No paths through the reserve — survey from embankments and canal dike · 🚶 Embankments around Lexmond; node network'
}))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(2024)
mk.check()
