# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2050, 'De Avelingen', {
 'tags': ['Zuid-Holland · tussen Gorinchem en Boven Hardinxveld', '± 100 hectare grienden en hakhout tussen Boven Merwede en Kanaal van Steenenhoek · eeuwenoude griendcultuur · schapenkudde en bevers · Staatsbosbeheer', 'list 36 · no. 769'],
 'loc': '📍 Tussen Gorinchem en Boven Hardinxveld, tussen de Boven Merwede en het Kanaal van Steenenhoek · toegang via de Avelingensekade; Pelgrimspad (LAW 7) doorkruist het gebied; paalkampeerterrein bij (51.832, 4.921)',
 'desc': 'De <b>Avelingen</b> — in oude akten de <b>‘Dortsche Avelingen’</b> — vormen een strook van ± 100 hectare <b>natte grienden en hakhout</b> tussen de <b>Boven Merwede</b> en het <b>Kanaal van Steenenhoek</b>, beheerd door <b>Staatsbosbeheer</b>. Eeuwenlang werden hier wilgen gekweekt voor de <b>mandenmakerij en het vlechtwerk van de streek</b>; de <b>griendcultuur</b> is hier nooit verdwenen, en nog altijd worden de percelen op de oude cyclus gehakt — met als onbedoelde gasten de <b>bevers</b>, die zich vanuit de Merwede in de zachte wilgenbossen hebben genesteld. Op de hogere delen liggen <b>graslanden</b> die na half juni worden gemaaid voor de <b>weidevogels</b> en ’s zomers worden begraasd door een <b>schapenkudde</b>; in de laagtes groeien <b>moerasvarens en moerasplanten</b> van de zoete rivierklei. De <b>Zwetplaat</b>, een oude kleigat-plas in het westen, trekt in de winter watervogels. Het <b>Pelgrimspad</b> (LAW 7-2) voert door het gebied; wie de <b>Avelingensekade</b> volgt, kijkt uit over een landschap dat er in de Gouden Eeuw al zo bijlag — en bij het <b>paalkampeerterrein</b> kan de wandelaar de nacht tussen de grienden doorbrengen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (zangvogels, moerasbloei), nov–mrt (winterse grienden, watervogels op de Zwetplaat)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — pak één moment van stilte bij de grienden.',
 'why': ['De <b>eeuwenoude griendcultuur</b> — wilgen voor manden en vlechtwerk sinds de Middeleeuwen.', 'De <b>bevers</b> in de zachte wilgenbossen aan de Merwede.', 'De <b>schapenkudde</b> op de zomerse graslanden.', 'Het <b>paalkampeerterrein</b> — overnachten tussen de grienden.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nachtegalen en rietzangers</b> in de grienden.', '<span class="months">Jun–Aug</span> 🐑 <b>Schapenkudde</b> op de graslanden.', '<span class="months">Nov–Mrt</span> ✂️ <b>Griendhak</b> op de oude cyclus.', '<span class="months">Nov–Feb</span> 🦫 <b>Bever-sporen</b> langs de Merwede-oever.'],
 'wild': ['🌳 Eeuwenoude grienden en hakhout', '🐑 Schapenkudde op het westdeel', '🦫 Bevers in de wilgenbossen', '🐦 Weidevogels — maaien na half juni', '🌊 Zwetplaat als wintervijver'],
 'trail': ['Volg het <b>Pelgrimspad (LAW 7-2)</b> door de Avelingen.', 'Wandel de <b>Avelingensekade</b> tussen Merwede en kanaal.', 'Overnacht op het <b>paalkampeerterrein</b> (alleen te voet/per kano).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Grienden deels onbegaanbaar — paden en kades volgen · ⛺ Paalkamperen alleen met vergunning'
}, {
 'tags': ['Zuid-Holland · between Gorinchem and Boven Hardinxveld', '± 100 hectares of copses and coppice between the Boven Merwede and the Steenenhoek Canal · centuries-old copse culture · sheep flock and beavers · Staatsbosbeheer', 'list 36 · no. 769'],
 'loc': '📍 Between Gorinchem and Boven Hardinxveld, between the Boven Merwede and the Steenenhoek Canal · access via the Avelingensekade; Pilgrim’s Path (LAW 7) crosses the area; pole camping site at (51.832, 4.921)',
 'desc': 'The <b>Avelingen</b> — in old deeds the <b>‘Dortsche Avelingen’</b> — form a strip of ± 100 hectares of <b>wet copses and coppice</b> between the <b>Boven Merwede</b> and the <b>Steenenhoek Canal</b>, managed by <b>Staatsbosbeheer</b>. For centuries willows were grown here for <b>basketry and the region’s wickerwork</b>; the <b>copse culture</b> never disappeared, and the parcels are still cut on the old cycle — with the <b>beavers</b> as unintended guests, settling from the Merwede into the soft willow woods. On the higher parts lie <b>grasslands</b> mown after mid-June for the <b>meadow birds</b> and grazed in summer by a <b>sheep flock</b>; in the lows grow <b>marsh ferns and marsh plants</b> of the sweet river clay. The <b>Zwetplaat</b>, an old clay-pit lake in the west, draws waterfowl in winter. The <b>Pilgrim’s Path</b> (LAW 7-2) leads through the area; follow the <b>Avelingensekade</b> and you look out over a landscape that already lay like this in the Golden Age — and at the <b>pole camping site</b> the walker can spend the night between the copses.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds, marsh flowers), Nov–Mar (winter copses, waterfowl on the Zwetplaat)<br>\\n    <b>Best time of day:</b> Morning — catch one silent moment in the copses.',
 'why': ['The <b>centuries-old copse culture</b> — willows for baskets and wickerwork since the Middle Ages.', 'The <b>beavers</b> in the soft willow woods on the Merwede.', 'The <b>sheep flock</b> on the summer grasslands.', 'The <b>pole camping site</b> — a night between the copses.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nightingales and warblers</b> in the copses.', '<span class="months">Jun–Aug</span> 🐑 <b>Sheep flock</b> on the grasslands.', '<span class="months">Nov–Mar</span> ✂️ <b>Copse cutting</b> on the old cycle.', '<span class="months">Nov–Feb</span> 🦫 <b>Beaver tracks</b> along the Merwede bank.'],
 'wild': ['🌳 Centuries-old copses and coppice', '🐑 Sheep flock on the western part', '🦫 Beavers in the willow woods', '🐦 Meadow birds — mowing after mid-June', '🌊 Zwetplaat as winter lake'],
 'trail': ['Follow the <b>Pilgrim’s Path (LAW 7-2)</b> through the Avelingen.', 'Walk the <b>Avelingensekade</b> between river and canal.', 'Stay overnight at the <b>pole camping site</b> (on foot/by canoe only).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Copses partly impassable — follow paths and embankments · ⛺ Pole camping with permit only'
}))

C.append(mk.card(2051, 'Oost- en Noordwaard', {
 'tags': ['Noord-Brabant · Biesbosch bij Werkendam en Nieuwendijk (Land van Altena)', 'Ontpolderde Biesbosch-natuur van de Noordwaard — grote plassen, wilgenbossen en doorkijkjes over de Petrusplaat · de Oostwaard met zijn oude kreken · Staatsbosbeheer', 'list 36 · no. 770'],
 'loc': '📍 Noordwaard: parkeerplaats met <b>vogelkijkhut</b> ± 100 m verder (Vossensteeg/Werkendam-Nieuwendijk); westelijke parkeerplaats met uitkijkpunt over het spaarbekken <b>Petrusplaat</b> · rondje Noordwaard ± 5 km',
 'desc': 'De <b>Noordwaard</b> en de <b>Oostwaard</b> zijn de twee grote polders in het oosten van de <b>Biesbosch</b>, en samen vertellen ze het verhaal van de mens en het getij in het Land van Altena. De <b>Noordwaard</b> werd na 2015 <b>ontpolderd</b> in het kader van Ruimte voor de Rivier: de kaden werden verlaagd, de sloten uitgediept tot <b>geulen</b>, en langzaam veroverden <b>grote plassen, rietvelden en wilgenbossen</b> het voormalige boerenland. Nu grazen er <b>kuddes grote grazers</b> die het jonge wilgenbos kort houden, groeien er <b>natte pijpenstrootje-velden</b> en broeden er <b>blauwborsten, sprinkhaanrietzangers en purperreigers</b>. Wie vanaf de parkeerplaats de <b>vogelkijkhut</b> inloopt (100 m), kijkt uit over een nieuwe wildernis vol <b>krakeenden, wintertalingen en pijlstaarten</b>; op de trekdagen vliegen er <b>lepelaars en visarenden</b> over. De <b>Oostwaard</b>, ten zuidoosten ervan, was tot <b>1969</b> nog een <b>getijdengebied</b> — tot de <b>Bakkerskil</b> en de <b>Oostkil</b> met hun kreken werden afgedamd; het gebied is nog agrarisch, maar de oude <b>kreken en poelen</b> herbergen <b>matkoppen, gekraagde roodstaarten, kleine bonte spechten en wielewaals</b>. In de winter van 2025/2026 werd er bovendien <b>8,5 hectare nieuw bos</b> aangeplant — eik, haagbeuk, lijsterbes en es. Samen vormen Oost- en Noordwaard de meest dynamische nieuwe natuur van de oostelijke Biesbosch.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (blauwborst, rietzang), aug–okt (trek), nov–mrt (wintergasten, kramsvogels in de Oostwaard)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de nieuwe geulen.',
 'why': ['De <b>ontpoldering van de Noordwaard</b>: boerenland wordt getijdenwildernis.', 'De <b>vogelkijkhut</b> op 100 m van de parkeerplaats — gratis wildernis kijken.', 'De <b>oude kreken van de Oostwaard</b>: getijdenhistorie van vóór 1969.', 'De <b>kuddes</b> van fjordenpaarden en Galloways als landschapsmakers.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Blauwborst en sprinkhaanrietzanger</b> in het nieuwe riet.', '<span class="months">Aug–Okt</span> 🦅 <b>Lepelaars en visarenden</b> op de trek.', '<span class="months">Nov–Mrt</span> 🪿 <b>Kramsvogels en koperwieken</b> in de Oostwaard.', '<span class="months">Heel jaar</span> 🐎 <b>Grote grazers</b> in de Noordwaard.'],
 'wild': ['🐦 Blauwborst · Sprinkhaanrietzanger · Purperreiger', '🦆 Krakeend · Wintertaling · Pijlstaart', '🦅 Lepelaar · Visarend · Grote zilverreiger', '🐦 Matkop · Gekraagde roodstaart · Kleine bonte specht · wielewaal (Oostwaard)', '🐂 Grote grazers houden de wilgen kort'],
 'trail': ['Parkeer bij de <b>Vossensteeg</b> en loop in 100 m naar de <b>vogelkijkhut</b>.', 'Wandel het <b>rondje Noordwaard</b> (± 5 km) langs geulen en plassen.', 'Bezoek het <b>uitkijkpunt Petrusplaat</b> bij de westelijke parkeerplaats.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🔭 Vogelkijkhut open · ⚠️ Paden kunnen drassig zijn — laarzen in de winter'
}, {
 'tags': ['North Brabant · Biesbosch near Werkendam and Nieuwendijk (Land van Altena)', 'Depoldered Biesbosch nature of the Noordwaard — great lakes, willow woods and views over the Petrusplaat · the Oostwaard with its old creeks · Staatsbosbeheer', 'list 36 · no. 770'],
 'loc': '📍 Noordwaard: car park with <b>bird hide</b> ± 100 m on (Vossensteeg/Werkendam–Nieuwendijk); western car park with lookout over the retention basin <b>Petrusplaat</b> · Noordwaard loop ± 5 km',
 'desc': 'The <b>Noordwaard</b> and the <b>Oostwaard</b> are the two great polders in the east of the <b>Biesbosch</b>, and together they tell the story of people and tide in the Land van Altena. The <b>Noordwaard</b> was <b>depoldered</b> after 2015 under Room for the River: the embankments were lowered, the ditches deepened into <b>channels</b>, and slowly <b>great lakes, reed fields and willow woods</b> took over the former farmland. Now <b>grazing herds</b> keep the young willow wood in check, <b>wet purple-moor-grass fields</b> grow and <b>bluethroats, grasshopper warblers and purple herons</b> breed. Walk from the car park into the <b>bird hide</b> (100 m) and you look out over a new wilderness full of <b>gadwall, teal and pintail</b>; on migration days <b>spoonbills and ospreys</b> pass over. The <b>Oostwaard</b>, to its southeast, was still a <b>tidal area</b> until <b>1969</b> — when the <b>Bakkerskil</b> and the <b>Oostkil</b> with their creeks were dammed; the area is still agricultural, but the old <b>creeks and pools</b> harbour <b>willow tits, redstarts, lesser spotted woodpeckers and golden orioles</b>. In the winter of 2025/2026 another <b>8.5 hectares of new forest</b> was planted — oak, hornbeam, rowan and ash. Together, Oost- and Noordwaard form the most dynamic new nature of the eastern Biesbosch.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (bluethroat, reed song), Aug–Oct (migration), Nov–Mar (winter guests, fieldfares in the Oostwaard)<br>\\n    <b>Best time of day:</b> Morning — mist above the new channels.',
 'why': ['The <b>depoldering of the Noordwaard</b>: farmland becoming tidal wilderness.', 'The <b>bird hide</b> 100 m from the car park — free wilderness watching.', 'The <b>old creeks of the Oostwaard</b>: tidal history from before 1969.', 'The <b>herds</b> of fjord horses and Galloways as landscape makers.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Bluethroat and grasshopper warbler</b> in the new reed.', '<span class="months">Aug–Oct</span> 🦅 <b>Spoonbills and ospreys</b> on migration.', '<span class="months">Nov–Mar</span> 🪿 <b>Fieldfares and redwings</b> in the Oostwaard.', '<span class="months">All year</span> 🐎 <b>Big grazers</b> in the Noordwaard.'],
 'wild': ['🐦 Bluethroat · Grasshopper warbler · Purple heron', '🦆 Gadwall · Teal · Pintail', '🦅 Spoonbill · Osprey · Great white egret', '🐦 Willow tit · Redstart · Lesser spotted woodpecker · Golden oriole (Oostwaard)', '🐂 Big grazers keep the willows short'],
 'trail': ['Park at the <b>Vossensteeg</b> and walk 100 m to the <b>bird hide</b>.', 'Walk the <b>Noordwaard loop</b> (± 5 km) past channels and lakes.', 'Visit the <b>Petrusplaat lookout</b> at the western car park.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🔭 Bird hide open · ⚠️ Paths can be soggy — boots in winter'
}, n2k='De Biesbosch — Habitatrichtlijngebied nr. 79 (NL9903064): wilgenvloedbossen (H91E0), moerassen en grote plassen; rivier- en moerassoorten als bittervoorn, bever en roerdomp; de ontpolderde Noordwaard als nieuwste natte hart van het gebied.',
 n2k_en='De Biesbosch — Habitats Directive site no. 79 (NL9903064): alluvial willow forests (H91E0), marshes and great lakes; river and marsh species like bitterling, beaver and bittern; the depoldered Noordwaard as the area’s newest wet heart.'))

C.append(mk.card(2052, 'Witdammen', {
 'tags': ['Noord-Brabant · Nieuwendijk (Land van Altena)', 'Dijken- en polderlandschap bij de Witdammen — Brabants Landschap zaait hier bloemrijke akkers voor insecten · graslanden en poelen langs de Altenase diken', 'list 36 · no. 771'],
 'loc': '📍 Buurt Buitengebied Nieuwendijk (noordoost), naast de Wilhelminapolder en de Noordwaard · te voet via de dijken; combi met de Biesbosch-polders Oost- en Noordwaard (kaart 2051)',
 'desc': '<b>Witdammen</b> is een kleine kern in het noordoosten van <b>Nieuwendijk</b>, in het <b>Land van Altena</b> — een streek van dijken, polders en kreken waar het <b>Brabants Landschap</b> hier en daar percelen beheert voor <b>bloemrijke akkers en graslanden</b>: zonnige stroken <b>phacelia, boekweit en zonnebloemen</b> die in de zomer gonzen van de <b>bijen, hommels en vlinders</b>, en die ’s winters voedsel bieden aan <b>rietzangers en gorzen</b>. In 2015 werden de Witdammen en het naburige <b>Pompveld</b> in de belangstelling gezet door een grootscheepse <b>zonnebloemenactie</b> van het Brabants Landschap — sindsdien is het gebiedje een vaste waarde in de lijst van Altenase bloemgebieden. Het landschap eromheen is typisch <b>Biesbosch-randland</b>: <b>kleiputten, ruigten en poelen</b> langs de oude dijken, met <b>grasmus, gele kwikstaart en Fazant</b> in de hagen en <b>kamsalamanders en groene kikkers</b> in de poelen. Wie de <b>dijk bij Nieuwendijk</b> volgt, ziet in het westen de nieuwe wildernis van de Noordwaard opdoemen en in het oosten de oude dijkhuizen van het Land van Altena — Witdammen ligt er precies tussenin, als een klein hoofdstuk bloemen tussen twee grote verhalen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–Sep</b> (bloemrijke akkers op hun hoogtepunt), apr–mei (graslandbloei), okt–mrt (wintergasten)<br>\\n    <b>Beste tijd van de dag:</b> Middag — bijen en vlinders in de zon.',
 'why': ['De <b>bloemrijke akkers</b> van het Brabants Landschap — phacelia, boekweit, zonnebloemen.', 'De <b>zonnebloemenactie van 2015</b> als geboortemoment van het gebiedje.', 'De <b>ligging</b> tussen de oude Altenase dijken en de nieuwe Noordwaard.', 'De <b>poelen en kleiputten</b> met amfibieën langs de dijken.'],
 'phen': ['<span class="months">Jul–Sep</span> 🌻 <b>Bloemakkers</b> op hun kleurrijkst.', '<span class="months">Apr–Jun</span> 🐝 <b>Bijen en hommels</b> in de velden.', '<span class="months">Mei–Jun</span> 🦋 <b>Vlinders</b> langs de ruigten.', '<span class="months">Okt–Mrt</span> 🐦 <b>Rietzangers en gorzen</b> in de winterakkers.'],
 'wild': ['🌻 Phacelia · Boekweit · Zonnebloemen', '🐝 Bijen · Hommels · Vlinders', '🐦 Grasmus · Gele kwikstaart · Fazant', '🐸 Kamsalamander · Groene kikker in de poelen', '🌾 Kleiputten en ruigten langs de dijken'],
 'trail': ['Wandel de <b>dijken rond Nieuwendijk</b> langs Witdammen en de Wilhelminapolder.', 'Combineer met het <b>rondje Noordwaard</b> (± 5 km) en de vogelkijkhut.', 'Volg de <b>binnendijkse paden</b> richting Pompveld en Werkendam.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Akkers niet betreden — vanaf de dijken kijken · 🚶 Knooppuntennetwerk Land van Heusden en Altena'
}, {
 'tags': ['North Brabant · Nieuwendijk (Land van Altena)', 'Dike and polder landscape at the Witdammen — Brabants Landschap sows flower-rich fields here for insects · grasslands and pools along the Altena dikes', 'list 36 · no. 771'],
 'loc': '📍 Hamlet Buitengebied Nieuwendijk (northeast), beside the Wilhelminapolder and the Noordwaard · on foot via the dikes; combine with the Biesbosch polders Oost- and Noordwaard (card 2051)',
 'desc': '<b>Witdammen</b> is a small hamlet in the northeast of <b>Nieuwendijk</b>, in the <b>Land van Altena</b> — a region of dikes, polders and creeks where the <b>Brabants Landschap</b> manages scattered parcels as <b>flower-rich fields and grasslands</b>: sunny strips of <b>phacelia, buckwheat and sunflowers</b> that buzz with <b>bees, bumblebees and butterflies</b> in summer, and offer food to <b>reed buntings and finches</b> in winter. In 2015 the Witdammen and the neighbouring <b>Pompveld</b> were put on the map by a large <b>sunflower campaign</b> of the Brabants Landschap — since then the little area has been a fixture on the list of Altena flower lands. The landscape around it is typical <b>Biesbosch edge land</b>: <b>clay pits, rough growth and pools</b> along the old dikes, with <b>whitethroat, grey wagtail and pheasant</b> in the hedges and <b>warty newts and green frogs</b> in the pools. Follow the <b>dike at Nieuwendijk</b> and you see the new wilderness of the Noordwaard rise in the west and the old dike houses of the Land van Altena in the east — Witdammen lies exactly in between, as a small chapter of flowers between two great stories.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Sep</b> (flower fields at their peak), Apr–May (grassland flowers), Oct–Mar (winter guests)<br>\\n    <b>Best time of day:</b> Midday — bees and butterflies in the sun.',
 'why': ['The <b>flower-rich fields</b> of the Brabants Landschap — phacelia, buckwheat, sunflowers.', 'The <b>2015 sunflower campaign</b> as the area’s birth moment.', 'The <b>position</b> between the old Altena dikes and the new Noordwaard.', 'The <b>pools and clay pits</b> with amphibians along the dikes.'],
 'phen': ['<span class="months">Jul–Sep</span> 🌻 <b>Flower fields</b> at their most colourful.', '<span class="months">Apr–Jun</span> 🐝 <b>Bees and bumblebees</b> in the fields.', '<span class="months">May–Jun</span> 🦋 <b>Butterflies</b> along the rough growth.', '<span class="months">Oct–Mar</span> 🐦 <b>Reed buntings and finches</b> in the winter fields.'],
 'wild': ['🌻 Phacelia · Buckwheat · Sunflowers', '🐝 Bees · Bumblebees · Butterflies', '🐦 Whitethroat · Grey wagtail · Pheasant', '🐸 Warty newt · Green frog in the pools', '🌾 Clay pits and rough growth along the dikes'],
 'trail': ['Walk the <b>dikes around Nieuwendijk</b> past Witdammen and the Wilhelminapolder.', 'Combine with the <b>Noordwaard loop</b> (± 5 km) and the bird hide.', 'Follow the <b>inner-dike paths</b> towards Pompveld and Werkendam.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Fields not to be entered — view from the dikes · 🚶 Land van Heusden en Altena node network'
}))

C.append(mk.card(2053, 'Griendcomplex Werkendam', {
 'tags': ['Noord-Brabant · Brabantse Biesbosch bij Werkendam', 'Aaneengesloten reeks SBB-grienden met historieke griendwerkersketen · wilgentuin, museumgriend en Sterlinggriend · Natura 2000 De Biesbosch', 'list 36 · no. 772'],
 'loc': '📍 Griendwerkerskeet Deeneplaatweg 6, Werkendam · Griendmuseumpad vanaf het Biesbosch MuseumEiland (Hank) of de grienden bij Werkendam-Drimmelen; combi met Nationaal Park De Biesbosch',
 'desc': 'Het <b>griendcomplex van Werkendam</b> omvat de aaneengesloten <b>grienden van Staatsbosbeheer</b> in de <b>Brabantse Biesbosch</b> — honderden hectares <b>gecultiveerd wilgenbos</b> die eeuwenlang het kapitaal van de streek vormden. In het hart ervan, aan de <b>Deeneplaatweg</b>, staat de <b>griendwerkerskeet van Werkendam</b>: een houten keet uit ± 1900 met de originele <b>bedsteekisten, fornuis en gereedschap</b> van de griendwerkersgezinnen die hier van maart tot november in woonden — origineel hout, nooit afgebroken. Elders in het complex liggen de <b>‘keet van de snor’</b> in de Houtganzewei bij Drimmelen, de <b>stenen keet en de schrankkeet</b> langs het <b>Griendmuseumpad</b>, en de <b>Sterlinggriend</b> — een historisch <b>cultuurlandschap</b> dat met zijn <b>wilgentuin</b> en oude perceelsindeling de griendbouwkunde van weleer toont. Bij het <b>Biesbosch MuseumEiland</b> wordt bovendien een <b>museumgriend</b> jaarlijks nog op de oude manier gehakt, zodat bezoekers het ambacht kunnen zien. Ecologisch zijn de grienden van Werkendam de zachtste hoek van de Biesbosch: <b>nachtegalen, blauwborsten en kleine karekieten</b> in de jonge aanwas, <b>waterspreeuwen en ijsvogels</b> langs de sloten, en in de winter <b>smienten en krakeenden</b> op de plas-dras-percelen. Het ambacht, de geschiedenis en de natuur vallen hier samen in één wilgenbos.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (nachtgalenzang), nov–mrt (griendhak, winterse stilte)<br>\\n    <b>Beste tijd van de dag:</b> Avond — nachtegalen in de grienden.',
 'why': ['De <b>griendwerkerskeet van Werkendam</b> (± 1900) met origineel hout en bedstee-kisten.', 'De <b>‘keet van de snor’</b> en de stenen keet langs het <b>Griendmuseumpad</b>.', 'De <b>Sterlinggriend</b> met wilgentuin als stukje griendbouwkunde.', 'De <b>nachtegalen en ijsvogels</b> van de zachtste hoek van de Biesbosch.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nachtegalen</b> zingen in de jonge aanwas.', '<span class="months">Nov–Mrt</span> ✂️ <b>Griendhak</b> — de winterse oogst.', '<span class="months">Nov–Feb</span> 🪿 <b>Smienten</b> op de plas-dras-percelen.', '<span class="months">Heel jaar</span> 🏚️ <b>Keten en paden</b> van het griendmuseumlandschap.'],
 'wild': ['🌳 Grienden (gecultiveerd wilgenbos)', '🐦 Nachtegaal · Blauwborst · Kleine karekiet', '🐦 Waterspreeuw · IJsvogel langs de sloten', '🪿 Smient · Krakeend in de winter', '🏚️ Griendwerkersketen en wilgentuin'],
 'trail': ['Bezoek de <b>griendwerkerskeet</b> aan de Deeneplaatweg 6 bij Werkendam.', 'Loop het <b>Griendmuseumpad</b> langs stenen keet en schrankkeet.', 'Zie het ambacht in de <b>museumgriend</b> bij het Biesbosch MuseumEiland (Hank).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (museum betaald) · ⚠️ Grienden deels gesloten i.v.m. hakwerkzaamheden · 🚶 Biesbosch-knooppunten; wandelnetwerk Brabantse Biesbosch'
}, {
 'tags': ['North Brabant · Brabantse Biesbosch near Werkendam', 'Contiguous chain of Forestry Commission copses with historic copse-workers’ sheds · willow garden, museum copse and Sterlinggriend · Natura 2000 De Biesbosch', 'list 36 · no. 772'],
 'loc': '📍 Copse-workers’ shed Deeneplaatweg 6, Werkendam · Griend Museum Path from Biesbosch MuseumEiland (Hank) or the copses near Werkendam–Drimmelen; combine with De Biesbosch National Park',
 'desc': 'The <b>copse complex of Werkendam</b> takes in the contiguous <b>willow copses of Staatsbosbeheer</b> in the <b>Brabantse Biesbosch</b> — hundreds of hectares of <b>cultivated willow wood</b> that for centuries formed the region’s capital. At its heart, on the <b>Deeneplaatweg</b>, stands the <b>copse-workers’ shed of Werkendam</b>: a wooden shed from ± 1900 with the original <b>bed-cupboards, stove and tools</b> of the copse-worker families who lived here from March to November — original timber, never demolished. Elsewhere in the complex lie the <b>‘shed of the moustache’</b> in the Houtganzewei near Drimmelen, the <b>stone shed and the rack shed</b> along the <b>Griend Museum Path</b>, and the <b>Sterlinggriend</b> — a historic <b>cultural landscape</b> whose <b>willow garden</b> and old parcel layout show the copse engineering of old. At <b>Biesbosch MuseumEiland</b> a <b>museum copse</b> is moreover still cut the old way each year, so visitors can see the craft. Ecologically the Werkendam copses are the softest corner of the Biesbosch: <b>nightingales, bluethroats and sedge warblers</b> in the young growth, <b>dippers and kingfishers</b> along the ditches, and in winter <b>wigeon and gadwall</b> on the flash-flooded parcels. Craft, history and nature come together here in one willow wood.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (nightingale song), Nov–Mar (copse cutting, winter quiet)<br>\\n    <b>Best time of day:</b> Evening — nightingales in the copses.',
 'why': ['The <b>copse-workers’ shed of Werkendam</b> (± 1900) with original timber and bed-cupboards.', 'The <b>‘shed of the moustache’</b> and the stone shed on the <b>Griend Museum Path</b>.', 'The <b>Sterlinggriend</b> with willow garden as a piece of copse engineering.', 'The <b>nightingales and kingfishers</b> of the Biesbosch’s softest corner.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nightingales</b> singing in the young growth.', '<span class="months">Nov–Mar</span> ✂️ <b>Copse cutting</b> — the winter harvest.', '<span class="months">Nov–Feb</span> 🪿 <b>Wigeon</b> on the flash-flooded parcels.', '<span class="months">All year</span> 🏚️ <b>Sheds and paths</b> of the copse museum landscape.'],
 'wild': ['🌳 Willow copses (cultivated willow wood)', '🐦 Nightingale · Bluethroat · Sedge warbler', '🐦 Dipper · Kingfisher along the ditches', '🪿 Wigeon in winter', '🏚️ Copse-workers’ sheds and willow garden'],
 'trail': ['Visit the <b>copse-workers’ shed</b> on Deeneplaatweg 6 at Werkendam.', 'Walk the <b>Griend Museum Path</b> past stone shed and rack shed.', 'See the craft in the <b>museum copse</b> at Biesbosch MuseumEiland (Hank).'],
 'foot': '🐕 Dogs on lead · 💶 Free (museum paid) · ⚠️ Copses partly closed during cutting works · 🚶 Biesbosch nodes; Brabantse Biesbosch walking network'
}, n2k='De Biesbosch — Habitatrichtlijngebied nr. 79 (NL9903064): de grienden zijn de meest omvangrijke restant van het oorspronkelijke zoetgetijdenbos (H91E0 wilgenvloedbos) in Noordwest-Europa; bever, roerdomp en purperreiger als doelsoorten.',
 n2k_en='De Biesbosch — Habitats Directive site no. 79 (NL9903064): the copses are the most extensive remnant of the original freshwater tidal forest (H91E0 alluvial willow forest) in Northwest Europe; beaver, bittern and purple heron as target species.'))

C.append(mk.card(2054, 'Loevesteyn', {
 'tags': ['Gelderland · westpunt van de provincie bij Poederoijen (aan de Afgedamde Maas)', 'Natuur rond Slot Loevestein — Natura 2000-gebied Loevestein, Pompveld &amp; Kornsche Boezem · bloemrijk glanshaverhooiland en grote modderkruiper · vesting, uiterwaarden en rivierbos', 'list 36 · no. 773'],
 'loc': '📍 Slot Loevestein, Loevestein 1, Poederoijen (parkeren bij het slot) · Poederoijense Uiterwaarden en Pompveld direct oostelijk; combi met de Waaluiterwaarden bij Brakel en de Merwede-oever bij Giessen',
 'desc': 'Rond <b>Slot Loevestein</b> — de middeleeuwse burcht aan de samenloop van <b>Waal en Afgedamde Maas</b>, beroemd door Hugo de Groot en zijn boekenkast — ligt een van de jongste Natura 2000-gebieden van Nederland: <b>Loevestein, Pompveld &amp; Kornsche Boezem</b>. Het gebied omvat de <b>Boezem van Brakel</b>, het <b>Pompveld</b> met zijn historische <b>eendenkooi</b>, de <b>Kornsche Boezem</b>, de <b>Polder Munnikenland</b> met de Waaluiterwaarden bij Brakel — en natuurlijk het <b>vestinglandschap</b> zelf: wallen, natte grachten en uiterwaarden waar de rivier nog altijd vat op heeft. Ecologisch gezien is het gebied een rivierenkamer vol verrassingen: het bevat het grootste, vlakdekkende <b>bloemrijke glanshaverhooiland</b> van Nederland (habitattype <b>H6510</b>), dat in juni geel ziet van de <b>schermbloemen</b> en roze van de <b>beemdooievaarsbek</b> die rond het slot groeit; in de poelen en kreken leeft de <b>grote modderkruiper</b> — een kwetsbare vis die elders zeldzaam is geworden — samen met <b>bittervoorn, rivierdonderpad en kamsalamander</b>. De <b>kwartelkoning</b> roept in het hooiland, de <b>grutto en wulp</b> trekken er over, en de <b>veldleeuwerik</b> zingt boven de uiterwaarden, waar ook de <b>bever</b> zijn sporen achterlaat. Wie over de <b>vestingwallen</b> loopt, kijkt uit op de plek waar <b>Waal en Merwede</b> elkaar ontmoeten — vier eeuwen vesting, één rivierlandschap.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Jul</b> (glanshaverhooiland in volle bloei), apr–jun (kwartelkoning, weidevogels), sep–okt (herfstkleur uiterwaarden)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — dauw boven het Pompveld en de koele wallen.',
 'why': ['De <b>samenloop van Waal en Merwede</b> bij een middeleeuws slot — vesting én rivier in één blik.', 'Het <b>grootste vlakdekkende glanshaverhooiland</b> van Nederland (H6510).', 'De <b>grote modderkruiper</b> als kernsoort van de poelen en kreken.', 'De <b>eendenkooi van het Pompveld</b> en de Kornsche Boezem als historische moerasdelen.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Glanshaverhooiland</b> in volle bloei.', '<span class="months">Mei–Jun</span> 🎵 <b>Kwartelkoning</b> roept in de avond.', '<span class="months">Apr–Jun</span> 🎵 <b>Grutto, wulp en veldleeuwerik</b> boven de uiterwaarden.', '<span class="months">Heel jaar</span> 🏰 <b>Slot Loevestein</b> en zijn wallen.'],
 'wild': ['🐟 Grote modderkruiper · Bittervoorn · Rivierdonderpad', '🦎 Kamsalamander · Bever', '🌾 Glanshaverhooiland (H6510) · Beemdooievaarsbek', '🐦 Kwartelkoning · Grutto · Wulp · Veldleeuwerik', '🏰 Slot Loevestein en vestingwallen'],
 'trail': ['Bezoek <b>Slot Loevestein</b> (LAW 6 Grote Rivierenpad passeert) en loop de vestingwallen.', 'Wandel de <b>Poederoijense Uiterwaarden</b> en het <b>Pompveld</b> oostelijk van het slot.', 'Combineer met de <b>Waaluiterwaarden bij Brakel</b> — één van de weinige onvergraven uiterwaarden van Nederland — en de Kornsche Boezem.'],
 'foot': '🐕 Honden aangelijnd · 💶 Buiten gratis, slot betaald · 🏰 Slot Loevestein open di–zo (check site) · 🚶 Grote Rivierenpad (LAW 6); knooppuntennetwerk'
}, {
 'tags': ['Gelderland · western tip of the province near Poederoijen (on the Afgedamde Maas)', 'Nature around Loevestein Castle — Natura 2000 site Loevestein, Pompveld &amp; Kornsche Boezem · flower-rich soft-grass hay meadow and large weather loach · fortress, river banks and riverine wood', 'list 36 · no. 773'],
 'loc': '📍 Loevestein Castle, Loevestein 1, Poederoijen (park at the castle) · Poederoijen flood plains and Pompveld directly east; combine with the Waal flood plains at Brakel and the Merwede bank near Giessen',
 'desc': 'Around <b>Loevestein Castle</b> — the medieval stronghold at the confluence of the <b>Waal and the Afgedamde Maas</b>, famous for Hugo de Groot and his book chest — lies one of the Netherlands’ youngest Natura 2000 sites: <b>Loevestein, Pompveld &amp; Kornsche Boezem</b>. The area takes in the <b>Brakel boezem</b>, the <b>Pompveld</b> with its historic <b>duck decoy</b>, the <b>Kornsche Boezem</b>, <b>Munnikenland polder</b> with the Waal flood plains at Brakel — and of course the <b>fortress landscape</b> itself: ramparts, wet moats and flood plains where the river still has a hand. Ecologically the area is a river chamber full of surprises: it holds the largest, continuous <b>flower-rich soft-grass hay meadow</b> of the Netherlands (habitat type <b>H6510</b>), yellow in June with <b>umbellifers</b> and pink with the <b>meadow cranesbill</b> that grows around the castle; in the pools and creeks lives the <b>large weather loach</b> — a vulnerable fish grown rare elsewhere — together with <b>bitterling, spined loach and warty newt</b>. The <b>corncrake</b> calls in the hay meadow, <b>godwit and whimbrel</b> pass over, and the <b>wood lark</b> sings above the flood plains, where the <b>beaver</b> leaves its tracks. Walk the <b>ramparts</b> and you look out over the spot where <b>Waal and Merwede</b> meet — four centuries of fortress, one river landscape.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Jul</b> (soft-grass hay meadow in full flower), Apr–Jun (corncrake, meadow birds), Sep–Oct (autumn colour on the flood plains)<br>\\n    <b>Best time of day:</b> Morning — dew above the Pompveld and the cool ramparts.',
 'why': ['The <b>confluence of Waal and Merwede</b> at a medieval castle — fortress and river in one glance.', 'The <b>largest continuous soft-grass hay meadow</b> of the Netherlands (H6510).', 'The <b>large weather loach</b> as core species of pools and creeks.', 'The <b>Pompveld duck decoy</b> and the Kornsche Boezem as historic marsh parts.'],
 'phen': ['<span class="months">Jun–Jul</span> 🌼 <b>Soft-grass hay meadow</b> in full flower.', '<span class="months">May–Jun</span> 🎵 <b>Corncrake</b> calling in the evening.', '<span class="months">Apr–Jun</span> 🎵 <b>Godwit, whimbrel and skylark</b> above the flood plains.', '<span class="months">All year</span> 🏰 <b>Loevestein Castle</b> and its ramparts.'],
 'wild': ['🐟 Large weather loach · Bitterling · Spined loach', '🦎 Warty newt · Beaver', '🌾 Soft-grass hay meadow (H6510) · Meadow cranesbill', '🐦 Corncrake · Godwit · Whimbrel · Skylark', '🏰 Loevestein Castle and ramparts'],
 'trail': ['Visit <b>Loevestein Castle</b> (LAW 6 Grote Rivierenpad passes) and walk the ramparts.', 'Walk the <b>Poederoijen flood plains</b> and the <b>Pompveld</b> east of the castle.', 'Combine with the <b>Waal flood plains at Brakel</b> — one of the few unexcavated flood plains of the Netherlands — and the Kornsche Boezem.'],
 'foot': '🐕 Dogs on lead · 💶 Outside free, castle paid · 🏰 Loevestein Castle open Tue–Sun (check site) · 🚶 Grote Rivierenpad (LAW 6); node network'
}, n2k='Loevestein, Pompveld &amp; Kornsche Boezem — Habitatrichtlijngebied nr. 71 (NL3004001, aangewezen 2013, Gelderland + Noord-Brabant): kerngebied grote modderkruiper; vlakdekkend bloemrijk glanshaverhooiland (H6510) in de uiterwaarden; kwartelkoning, grutto en wulp; bever, kamsalamander, bittervoorn en rivierdonderpad in poelen en kreken.',
 n2k_en='Loevestein, Pompveld &amp; Kornsche Boezem — Habitats Directive site no. 71 (NL3004001, designated 2013, Gelderland + North Brabant): core area for large weather loach; continuous flower-rich soft-grass hay meadow (H6510) on the flood plains; corncrake, godwit and whimbrel; beaver, warty newt, bitterling and spined loach in pools and creeks.'
))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2054)
mk.check()
