# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1995, 'Blanke Waal', {
 'tags': ['Zuid-Holland · Zwartewaal (Voorne)', 'Wiel van 6 hectare na een dijkdoorbraak · water, riet en natte graslanden tussen de akkers · Cetti’s zanger en overwinterende smienten', 'list 36 · no. 714'],
 'loc': '📍 Bij Zwartewaal (Kraakweg, Ooievaarsdijk) · te zien vanaf Kraakweg en Ooievaarsdijk; Boerenzwaluwroute passeert het gebied',
 'desc': 'Natuurgebied <b>Blanke Waal</b> (6 hectare) dankt zijn naam aan de grootste waterplas van het terrein: een <b>wiel</b> dat achterbleef na een <b>dijkdoorbraak</b>. Op Voorne is veel akkerbouw — Blanke Waal is anders. Hier vind je water, riet en natte graslanden, waar weidevogels een plek vinden om te rusten, te foerageren én te broeden, en waar ganzen en eenden als de <b>smient</b> overwinteren. Het Zuid-Hollands Landschap houdt de graslanden <b>bloemrijk</b>: dat trekt insecten aan, die op hun beurt weer voedsel vormen voor vogels. Hij laat zich zelden zien, maar zijn naam hoor je roepen: <i>CET-ti, CET-ti, CET-ti</i> — de <b>Cetti’s zanger</b> zit in het riet, samen met koekoeken. Een waterrijke onderbreking van de akkers, op een steenworp van Holle Mare en Derryvliet.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (Cetti’s zanger, koekoek en weidevogels), nov–feb (smienten en ganzen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang uit het riet.',
 'why': ['Het <b>wiel</b>: een ronde dijkdoorbraakplas tussen de akkers.', 'De <b>Cetti’s zanger</b> die zijn eigen naam roept uit het riet.', 'De <b>bloemrijke graslanden</b> vol insecten en vogels.', 'De <b>overwinterende smienten</b> op het open water.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Cetti’s zanger en koekoek</b> in het riet.', '<span class="months">Apr–Jun</span> 🐣 <b>Weidevogels</b>: rusten, foerageren en broeden.', '<span class="months">Mei–Jul</span> 🌸 <b>Bloemrijke graslanden</b> vol insecten.', '<span class="months">Nov–Feb</span> 🦆 <b>Smienten en ganzen</b> overwinteren op de plas.'],
 'wild': ['🎵 Cetti’s zanger · Koekoek', '🦆 Smient · Ganzen (winter)', '🌸 Bloemrijke natte graslanden', '💧 Wiel na dijkdoorbraak', '🐦 Weidevogels van Voorne'],
 'trail': ['Bekijk het gebied vanaf de <b>Kraakweg en Ooievaarsdijk</b> bij Zwartewaal.', 'Wandel de <b>Boerenzwaluwroute</b> langs Blanke Waal, Holle Mare en Derryvliet.', 'Combineer met <b>Zwartewaal</b> of Brielle.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Alleen te overzien vanaf de weg; betreed het terrein niet · 🚶 Kraakweg en Ooievaarsdijk; gemarkeerde route erlangs'
}, {
 'tags': ['Zuid-Holland · Zwartewaal (Voorne)', '6-hectare breach pool left by a dike burst · water, reeds and wet grasslands among the fields · Cetti’s warbler and wintering wigeons', 'list 36 · no. 714'],
 'loc': '📍 Near Zwartewaal (Kraakweg, Ooievaarsdijk) · visible from the Kraakweg and Ooievaarsdijk; the Barn Swallow route passes through',
 'desc': 'The <b>Blanke Waal</b> nature area (6 hectares) owes its name to the largest pool on the site: a <b>wiel</b> left behind after a <b>dike breach</b>. Voorne is mostly arable — Blanke Waal is different. Here you find water, reeds and wet grasslands, where meadow birds find a place to rest, forage and breed, and where geese and ducks such as the <b>wigeon</b> winter. Het Zuid-Hollands Landschap keeps the grasslands <b>rich in flowers</b>: that attracts insects, which in turn form food for birds. He rarely shows himself, but you can hear him calling his name: <i>CET-ti, CET-ti, CET-ti</i> — the <b>Cetti’s warbler</b> sits in the reeds, together with cuckoos. A watery interruption of the fields, a stone’s throw from the Holle Mare and the Derryvliet.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (Cetti’s warbler, cuckoo and meadow birds), Nov–Feb (wigeons and geese)<br>\\n    <b>Best time of day:</b> Morning — song from the reeds.',
 'why': ['The <b>wiel</b>: a round dike-breach pool among the fields.', 'The <b>Cetti’s warbler</b> calling its own name from the reeds.', 'The <b>flower-rich grasslands</b> full of insects and birds.', 'The <b>wintering wigeons</b> on the open water.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Cetti’s warbler and cuckoo</b> in the reeds.', '<span class="months">Apr–Jun</span> 🐣 <b>Meadow birds</b>: resting, foraging and breeding.', '<span class="months">May–Jul</span> 🌸 <b>Flower-rich grasslands</b> full of insects.', '<span class="months">Nov–Feb</span> 🦆 <b>Wigeons and geese</b> wintering on the pool.'],
 'wild': ['🎵 Cetti’s warbler · Cuckoo', '🦆 Wigeon · Geese (winter)', '🌸 Flower-rich wet grasslands', '💧 Pool left by a dike breach', '🐦 Meadow birds of Voorne'],
 'trail': ['View the area from the <b>Kraakweg and Ooievaarsdijk</b> near Zwartewaal.', 'Walk the <b>Barn Swallow route</b> past Blanke Waal, Holle Mare and Derryvliet.', 'Combine with <b>Zwartewaal</b> or Brielle.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Only viewable from the road; do not enter the terrain · 🚶 Kraakweg and Ooievaarsdijk; marked route alongside'
}))

C.append(mk.card(1996, 'Hillenhoek', {
 'tags': ['Zuid-Holland · tussen Zwartewaal en Hellevoetsluis', 'Echt weidevogelgebied van 10 hectare · kruidenrijk grasland tussen de maisakkers · grutto, tureluur en hermelijn', 'list 36 · no. 715'],
 'loc': '📍 Tussen Zwartewaal en Hellevoetsluis, langs de Kanaaldijk · niet toegankelijk; te overzien vanaf het fietspad langs Kanaaldijk-West en Abbewerveweg',
 'desc': 'Natuurgebied <b>Hillenhoek</b> (10 hectare) is een echt <b>weidevogelgebied</b> — en dat is belangrijk, zo midden in de polder. Weidevogels als <b>grutto, tureluur, scholekster en kievit</b> horen bij Zuid-Holland, maar hun aantal daalde in dertig jaar met de helft door gebrek aan geschikt leefgebied. Het Zuid-Hollands Landschap vormde Hillenhoek daarom om tot <b>kruidenrijk grasland</b>: vaker maaien na het broedseizoen, maaisel afvoeren en begrazen geeft een open grasmat vol kruiden en bloemen, met insecten als voedsel en beschutting voor kuikens. In deze natuurlijke oase tussen de <b>maisakkers</b> voelen ook hermelijn en woelmuizen zich thuis. Vanwege de rust is het terrein niet toegankelijk, maar vanaf het fietspad langs de <b>Kanaaldijk-West</b> en de Abbewerveweg is het goed te overzien — de KNNV telt er jaarlijks de broedvogels.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (baltsende grutto’s en tureluurs)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — weidevogelkoor boven het grasland.',
 'why': ['Een <b>oase voor weidevogels</b> tussen de maisakkers.', 'De <b>balts van grutto en tureluur</b> boven kruidenrijk gras.', 'Het <b>beheerrecept</b>: laat maaien, afvoeren en begrazen.', 'De <b>hermelijn</b> die tussen de kuikenweiden jaagt.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Baltsende grutto’s, tureluurs en kieviten</b>.', '<span class="months">Mei–Jul</span> 🌸 <b>Kruidenrijk grasland</b> vol bloemen en insecten.', '<span class="months">Jul–Aug</span> 🐄 <b>Begrazing</b> na het late maaien.', '<span class="months">Heel jaar</span> 🐾 <b>Hermelijn en woelmuizen</b> in de oase.'],
 'wild': ['🐦 Grutto · Tureluur · Scholekster · Kievit', '🐾 Hermelijn · Woelmuizen', '🌸 Kruidenrijk weidevogelgrasland', '🚲 Uitzicht vanaf Kanaaldijk-West', '📋 Jaarlijkse broedvogeltellingen (KNNV)'],
 'trail': ['Fiets over het <b>fietspad langs Kanaaldijk-West</b> met uitzicht op het gebied.', 'Rijd door over de <b>Abbewerveweg</b> voor een tweede blik.', 'Combineer met <b>Blanke Waal</b>, Derryvliet of Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd (fietspad) · 💶 Gratis · ⚠️ Niet toegankelijk — alleen te overzien vanaf fietspad en weg · 🚶 Fietspad Kanaaldijk-West; rust voor weidevogels'
}, {
 'tags': ['Zuid-Holland · between Zwartewaal and Hellevoetsluis', 'True meadow-bird area of 10 hectares · herb-rich grassland among the maize fields · godwit, redshank and stoat', 'list 36 · no. 715'],
 'loc': '📍 Between Zwartewaal and Hellevoetsluis, along the Kanaaldijk · not accessible; surveyed from the cycle path along Kanaaldijk-West and Abbewerveweg',
 'desc': 'The <b>Hillenhoek</b> nature area (10 hectares) is a true <b>meadow-bird area</b> — and that matters, in the middle of the polder. Meadow birds such as <b>godwit, redshank, oystercatcher and lapwing</b> belong to Zuid-Holland, but their numbers halved in thirty years for lack of suitable habitat. Het Zuid-Hollands Landschap therefore converted Hillenhoek into <b>herb-rich grassland</b>: mowing more often after the breeding season, removing the cuttings and grazing produces an open sward full of herbs and flowers, with insects as food and shelter for chicks. In this natural oasis among the <b>maize fields</b>, stoats and voles also feel at home. For tranquillity the terrain is not accessible, but from the cycle path along the <b>Kanaaldijk-West</b> and the Abbewerveweg it can be well surveyed — the KNNV counts its breeding birds each year.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (displaying godwits and redshanks)<br>\\n    <b>Best time of day:</b> Morning — meadow-bird chorus above the grassland.',
 'why': ['An <b>oasis for meadow birds</b> among the maize fields.', 'The <b>display of godwit and redshank</b> above herb-rich grass.', 'The <b>management recipe</b>: late mowing, removal and grazing.', 'The <b>stoat</b> hunting among the chick meadows.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Displaying godwits, redshanks and lapwings</b>.', '<span class="months">May–Jul</span> 🌸 <b>Herb-rich grassland</b> full of flowers and insects.', '<span class="months">Jul–Aug</span> 🐄 <b>Grazing</b> after the late mowing.', '<span class="months">All year</span> 🐾 <b>Stoat and voles</b> in the oasis.'],
 'wild': ['🐦 Godwit · Redshank · Oystercatcher · Lapwing', '🐾 Stoat · Voles', '🌸 Herb-rich meadow-bird grassland', '🚲 View from Kanaaldijk-West', '📋 Annual breeding-bird counts (KNNV)'],
 'trail': ['Cycle the <b>cycle path along Kanaaldijk-West</b> overlooking the area.', 'Ride on over the <b>Abbewerveweg</b> for a second look.', 'Combine with <b>Blanke Waal</b>, Derryvliet or Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead (cycle path) · 💶 Free · ⚠️ Not accessible — only viewable from cycle path and road · 🚶 Kanaaldijk-West cycle path; peace for meadow birds'
}))

C.append(mk.card(1997, 'Bosobjecten Voorne', {
 'tags': ['Zuid-Holland · Voorne-Putten (verspreid)', 'Verspreide bospercelen van Staatsbosbeheer · van Beerenplaat tot Wolvenpolder · ook beheer voor het recreatieschap', 'list 36 · no. 716'],
 'loc': '📍 Verspreid over Voorne-Putten: o.a. Mallebos (Spijkenisse), Kooisteebos en Ravensehout (Hellevoetsluis), Polder Biert · wandelnetwerk via Opvoorneputten.nl',
 'desc': 'De <b>Bosobjecten Voorne</b> zijn de verspreide groene percelen waarmee <b>Staatsbosbeheer</b> het eiland Voorne-Putten dooradert: <b>Beerenplaat, Kooisteebos, Mallebos, Polder Biert, Ravensehout, Spuigors, Vierambachtenboezem, Wellevliet en Wolvenpolder</b>. Het zijn jonge bossen en boezems in een verder open polderland — Ravensehout en Kooisteebos bij Hellevoetsluis werden zo’n 25 jaar geleden aangelegd, het Mallebos bij Spijkenisse is iets ouder — en juist die afwisseling van bos, kreek en weide maakt het eiland aantrekkelijk. In opdracht van <b>Recreatieschap Voorne-Putten</b> beheert Staatsbosbeheer bovendien Bernisse, Brielse Meer, De Uitwaayer, Oostvoornse Meer en de Slikken van Voorne. Wie de bosobjecten wil beleven, wandelt het Mallebos in, struint buiten het broedseizoen de oude dreef van polder Biert of fietst de beboomde dijken tussen de percelen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang en weidevogels), sep–okt (herfstkleuren)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang in de jonge bossen.',
 'why': ['De <b>groene dooradering</b>: negen percelen van bos tot boezem.', 'Het <b>Mallebos</b>: gevarieerd loofbos aan de Malledijk.', 'De <b>polder Biert</b>: oude dreef en weidevogels buiten het broedseizoen.', 'Het <b>beheer voor het recreatieschap</b>: van Bernisse tot Slikken van Voorne.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Vogelzang</b> in Kooisteebos en Ravensehout.', '<span class="months">Apr–Jun</span> 🐣 <b>Weidevogels</b> in polder Biert en Spuigors.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleuren</b> in de jonge bossen.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b> op boezems en kreken.'],
 'wild': ['🌳 Mallebos · Kooisteebos · Ravensehout', '🐦 Weidevogels van Biert en Spuigors', '💧 Vierambachtenboezem · Wellevliet · Wolvenpolder', '🌿 Beerenplaat en jonge aanplant', '🚶 Wandelnetwerk over het eiland'],
 'trail': ['Wandel het <b>Mallebos</b> bij Spijkenisse of de <b>oude dreef van Biert</b> (buiten broedseizoen).', 'Fiets de <b>beboomde dijken</b> tussen de percelen.', 'Combineer met <b>Bernisse</b>, Brielse Meer of de Slikken van Voorne.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Polder Biert in broedseizoen niet toegankelijk · 🚶 Uitgebreid wandelnetwerk; routes via Opvoorneputten.nl'
}, {
 'tags': ['Zuid-Holland · Voorne-Putten (scattered)', 'Scattered forest parcels of Staatsbosbeheer · from Beerenplaat to Wolvenpolder · also managing for the recreation board', 'list 36 · no. 716'],
 'loc': '📍 Scattered across Voorne-Putten: including Mallebos (Spijkenisse), Kooisteebos and Ravensehout (Hellevoetsluis), Polder Biert · walking network via Opvoorneputten.nl',
 'desc': 'The <b>Voorne Forest Objects</b> are the scattered green parcels with which <b>Staatsbosbeheer</b> veins the island of Voorne-Putten: <b>Beerenplaat, Kooisteebos, Mallebos, Polder Biert, Ravensehout, Spuigors, Vierambachtenboezem, Wellevliet and Wolvenpolder</b>. They are young forests and storage basins in an otherwise open polderland — Ravensehout and Kooisteebos near Hellevoetsluis were planted some 25 years ago, the Mallebos near Spijkenisse is a little older — and exactly that alternation of forest, creek and meadow makes the island attractive. Commissioned by the <b>Voorne-Putten Recreation Board</b>, Staatsbosbeheer additionally manages Bernisse, Brielse Meer, De Uitwaayer, Oostvoornse Meer and the Slikken van Voorne. To experience the forest objects, walk the Mallebos, roam the old drove road of polder Biert outside the breeding season, or cycle the tree-lined dikes between the parcels.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birdsong and meadow birds), Sep–Oct (autumn colours)<br>\\n    <b>Best time of day:</b> Morning — song in the young forests.',
 'why': ['The <b>green veining</b>: nine parcels from forest to storage basin.', 'The <b>Mallebos</b>: varied deciduous forest on the Malledijk.', 'The <b>polder Biert</b>: old drove road and meadow birds outside the breeding season.', 'The <b>management for the recreation board</b>: from Bernisse to Slikken van Voorne.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Birdsong</b> in Kooisteebos and Ravensehout.', '<span class="months">Apr–Jun</span> 🐣 <b>Meadow birds</b> in polder Biert and Spuigors.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colours</b> in the young forests.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b> on basins and creeks.'],
 'wild': ['🌳 Mallebos · Kooisteebos · Ravensehout', '🐦 Meadow birds of Biert and Spuigors', '💧 Vierambachtenboezem · Wellevliet · Wolvenpolder', '🌿 Beerenplaat and young plantings', '🚶 Walking network across the island'],
 'trail': ['Walk the <b>Mallebos</b> near Spijkenisse or the <b>old drove road of Biert</b> (outside breeding season).', 'Cycle the <b>tree-lined dikes</b> between the parcels.', 'Combine with <b>Bernisse</b>, Brielse Meer or the Slikken van Voorne.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Polder Biert closed in breeding season · 🚶 Extensive walking network; routes via Opvoorneputten.nl'
}))

C.append(mk.card(1998, 'Fort Noorddijk', {
 'tags': ['Zuid-Holland · Hellevoetsluis (Noorddijk, bij Nieuwenhoorn)', 'Vestingwerk uit 1884 van 5 hectare · Stelling van de Monden der Maas en het Haringvliet · gerestaureerd groen fort', 'list 36 · no. 717'],
 'loc': '📍 Aan de Noorddijk bij Hellevoetsluis, tussen Brielle en Hellevoetsluis · beheer Zuid-Hollands Landschap; van buitenaf te bezichtigen',
 'desc': '<b>Fort Noorddijk</b> (5 hectare) ligt aan de Noorddijk bij <b>Hellevoetsluis</b> en was van <b>1884 tot 1945</b> een militair verdedigingswerk. Samen met Fort Penserdijk bij Tinte en de vestingsteden Brielle en Hellevoetsluis vormde het de <b>Stelling van de Monden der Maas en het Haringvliet</b>: tegen de uit Engeland verwachte vijand, met polders die bij een aanval vanaf zee onder water konden worden gezet. Het Zuid-Hollands Landschap beheert het fort nu, zodat het behouden blijft voor toekomstige generaties — enkele jaren geleden is het <b>gerestaureerd</b>. Het fort en de begroeiing eromheen trekken veel dieren aan: wallen, gracht en groen vormen een toevlucht in het open polderland. Tweelingbroer van Fort Penserdijk, maar met een eigen gezicht aan de Noorddijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (groen fort en dierenleven), sep (Open Monumentendag in de regio)<br>\\n    <b>Beste tijd van de dag:</b> Middag — licht op wallen en gracht.',
 'why': ['Het <b>vestingwerk uit 1884</b> tussen twee vestingsteden.', 'De <b>Stelling van de Monden der Maas</b> met inundatievelden.', 'Het <b>gerestaureerde groen</b>: wallen en gracht vol dieren.', 'De <b>tweeling met Penserdijk</b>: vergelijk beide forten.'],
 'phen': ['<span class="months">Mei–Sep</span> 🦇 <b>Dierenleven</b> op wallen en in begroeiing.', '<span class="months">Mei</span> 🌸 <b>Bloeiende wallen</b> rond het fort.', '<span class="months">Sep</span> 🏛️ <b>Monumentensfeer</b> in vestingsteden eromheen.', '<span class="months">Nov–Mrt</span> 🦆 <b>Winterrust</b> op de fortgracht.'],
 'wild': ['⚔️ Vestingwerk 1884–1945', '🦇 Vleermuizen en klein wild van wallen en groen', '💧 Fortgracht met waterwild', '🌿 Begroeiing als toevlucht in de polder', '🏛️ Stelling van de Monden der Maas'],
 'trail': ['Bekijk het fort vanaf de <b>Noorddijk</b> bij Hellevoetsluis.', 'Fiets de <b>Atlantikwall- en stellingroute</b> langs Noorddijk en Penserdijk.', 'Combineer met <b>Brielle</b>, Hellevoetsluis of het Quackgors.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (van buitenaf) · ⚠️ Fortterrein beperkt toegankelijk; respecteer borden · 🚶 Noorddijk; fietsknooppunten erlangs'
}, {
 'tags': ['Zuid-Holland · Hellevoetsluis (Noorddijk, near Nieuwenhoorn)', 'Fortress from 1884 of 5 hectares · Position of the Meuse and Haringvliet Mouths · restored green fort', 'list 36 · no. 717'],
 'loc': '📍 On the Noorddijk near Hellevoetsluis, between Brielle and Hellevoetsluis · managed by Het Zuid-Hollands Landschap; viewable from outside',
 'desc': '<b>Fort Noorddijk</b> (5 hectares) lies on the Noorddijk near <b>Hellevoetsluis</b> and was a military defence work from <b>1884 to 1945</b>. Together with Fort Penserdijk near Tinte and the fortress towns of Brielle and Hellevoetsluis it formed the <b>Position of the Meuse and Haringvliet Mouths</b>: against the enemy expected from England, with polders that could be flooded in case of an attack from the sea. Het Zuid-Hollands Landschap now manages the fort so it is preserved for future generations — it was <b>restored</b> a few years ago. The fort and the surrounding vegetation attract many animals: ramparts, moat and green form a refuge in the open polderland. Twin brother of Fort Penserdijk, but with its own face on the Noorddijk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (green fort and animal life), Sep (Heritage Day in the region)<br>\\n    <b>Best time of day:</b> Afternoon — light on ramparts and moat.',
 'why': ['The <b>1884 fortress</b> between two fortress towns.', 'The <b>Position of the Meuse Mouths</b> with inundation fields.', 'The <b>restored green</b>: ramparts and moat full of animals.', 'The <b>twinning with Penserdijk</b>: compare both forts.'],
 'phen': ['<span class="months">May–Sep</span> 🦇 <b>Animal life</b> on ramparts and in vegetation.', '<span class="months">May</span> 🌸 <b>Flowering ramparts</b> around the fort.', '<span class="months">Sep</span> 🏛️ <b>Heritage atmosphere</b> in the surrounding fortress towns.', '<span class="months">Nov–Mar</span> 🦆 <b>Winter rest</b> on the fort moat.'],
 'wild': ['⚔️ Fortress 1884–1945', '🦇 Bats and small game of ramparts and green', '💧 Fort moat with waterfowl', '🌿 Vegetation as refuge in the polder', '🏛️ Position of the Meuse Mouths'],
 'trail': ['View the fort from the <b>Noorddijk</b> near Hellevoetsluis.', 'Cycle the <b>Atlantic Wall and fortress route</b> along Noorddijk and Penserdijk.', 'Combine with <b>Brielle</b>, Hellevoetsluis or the Quackgors.'],
 'foot': '🐕 Dogs on lead · 💶 Free (from outside) · ⚠️ Fort terrain of limited access; respect signs · 🚶 Noorddijk; cycle junctions alongside'
}))

C.append(mk.card(1999, 'Quackgors', {
 'tags': ['Zuid-Holland · Hellevoetsluis (Haringvlietoever)', 'Voormalig getijdengebied achter de sluizen · broedeenden, rietvogels en reeën · uitkijkpunt aan het Gorzenpad', 'list 36 · no. 718'],
 'loc': '📍 Bij Hellevoetsluis, aan de oevers van het Haringvliet (Gorzenpad) · uitkijkpunt; Gorzen & Bastions-route en fietsroute naar Quackjeswater passeren het gors',
 'desc': 'Het <b>Quackgors</b> bij <b>Hellevoetsluis</b> is een voormalig <b>getijdengebied</b> aan het Haringvliet — vlak achter de Haringvlietsluizen liggen zoet binnenwater en zoute zee hier vlak bij elkaar. Het gors staat nu alleen nog onder water als bij storm de sluizen dicht blijven; tegen afbrokkeling liggen er eilandjes en een stenen oeververdediging. Vanaf het <b>uitkijkpunt</b> is het vogelleven goed te volgen: er broeden eenden als <b>krakeend, bergeend en kuifeend</b>, scholekster, kievit en tureluur vinden er een plekje, in de rietkragen broeden <b>rietzanger, rietgors en bruine kiekendief</b>, en op de eilandjes — in 1996 opgespoten — broeden brandganzen en soms <b>kluut en kleine plevier</b>. Na het broedseizoen zoeken vogels voedsel op slik en gors; overdag laten zich soms <b>reeën</b> zien, terwijl paarden en runderen het gebied begrazen. Beschermd als Natura 2000-gebied Haringvliet.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (broedende eenden en rietvogels), aug–okt (foeragerende trekkers)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogelsymfonie vanaf het uitkijkpunt.',
 'why': ['Het <b>uitkijkpunt</b> over het voormalige getijdengebied.', 'De <b>broedeenden</b>: krakeend, bergeend en kuifeend.', 'De <b>rietvogels</b>: rietzanger, rietgors en bruine kiekendief.', 'De <b>reeën</b> die zich overdag soms laten zien.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐣 <b>Broedende eenden en rietvogels</b> op gors en eilandjes.', '<span class="months">Mei–Jul</span> 🪿 <b>Brandganzen</b> met jongen op de eilandjes.', '<span class="months">Aug–Okt</span> 🦆 <b>Foeragerende trekvogels</b> op slik en gors.', '<span class="months">Heel jaar</span> 🦌 <b>Reeën</b> en grazers in het gebied.'],
 'wild': ['🦆 Krakeend · Bergeend · Kuifeend', '🎵 Rietzanger · Rietgors · Bruine kiekendief', '🪿 Brandgans · Kluut · Kleine plevier', '🦌 Reeën · Paarden en runderen', '🌊 Haringvlietsluizen om de hoek'],
 'trail': ['Stop bij het <b>uitkijkpunt aan het Gorzenpad</b> (3221 LJ Hellevoetsluis).', 'Volg de <b>Gorzen & Bastions-route</b> of fiets naar het Quackjeswater.', 'Combineer met <b>Fort Noorddijk</b> of de vesting Hellevoetsluis.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Beschermd natuurmonument — blijf op paden en bij het uitkijkpunt · 🚶 Gorzenpad; bankje bij het uitkijkpunt'
}, {
 'tags': ['Zuid-Holland · Hellevoetsluis (Haringvliet shore)', 'Former tidal area behind the sluices · breeding ducks, reed birds and roe deer · viewpoint on the Gorzenpad', 'list 36 · no. 718'],
 'loc': '📍 Near Hellevoetsluis, on the shores of the Haringvliet (Gorzenpad) · viewpoint; Gorzen & Bastions route and cycle route to Quackjeswater pass the gors',
 'desc': 'The <b>Quackgors</b> near <b>Hellevoetsluis</b> is a former <b>tidal area</b> on the Haringvliet — just behind the Haringvliet sluices, fresh inland water and salty sea lie close together here. The gors now only floods when the sluices stay closed in storms; against erosion islets and stone bank protection have been laid. From the <b>viewpoint</b> the birdlife is easy to follow: ducks such as <b>gadwall, shelduck and tufted duck</b> breed, oystercatcher, lapwing and redshank find a spot, <b>Savi’s, reed bunting and marsh harrier</b> breed in the reed fringes, and on the islets — raised in 1996 — barnacle geese and sometimes <b>avocet and little ringed plover</b> breed. After the breeding season birds forage on mudflat and gors; by day <b>roe deer</b> sometimes show, while horses and cattle graze the area. Protected as Natura 2000 site Haringvliet.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (breeding ducks and reed birds), Aug–Oct (foraging migrants)<br>\\n    <b>Best time of day:</b> Morning — bird symphony from the viewpoint.',
 'why': ['The <b>viewpoint</b> over the former tidal area.', 'The <b>breeding ducks</b>: gadwall, shelduck and tufted duck.', 'The <b>reed birds</b>: Savi’s warbler, reed bunting and marsh harrier.', 'The <b>roe deer</b> sometimes showing by day.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐣 <b>Breeding ducks and reed birds</b> on gors and islets.', '<span class="months">May–Jul</span> 🪿 <b>Barnacle geese</b> with young on the islets.', '<span class="months">Aug–Oct</span> 🦆 <b>Foraging migrants</b> on mudflat and gors.', '<span class="months">All year</span> 🦌 <b>Roe deer</b> and grazers in the area.'],
 'wild': ['🦆 Gadwall · Shelduck · Tufted duck', '🎵 Savi’s warbler · Reed bunting · Marsh harrier', '🪿 Barnacle goose · Avocet · Little ringed plover', '🦌 Roe deer · Horses and cattle', '🌊 Haringvliet sluices around the corner'],
 'trail': ['Stop at the <b>viewpoint on the Gorzenpad</b> (3221 LJ Hellevoetsluis).', 'Follow the <b>Gorzen & Bastions route</b> or cycle to the Quackjeswater.', 'Combine with <b>Fort Noorddijk</b> or the fortress of Hellevoetsluis.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Protected nature monument — stay on paths and at the viewpoint · 🚶 Gorzenpad; bench at the viewpoint'
}, n2k='Natura 2000-gebied Haringvliet (Vogel- en Habitatrichtlijn): voormalig getijdengebied met broedeilanden, in beheer bij Natuurmonumenten', n2k_en='Natura 2000 site Haringvliet (Birds and Habitats Directives): former tidal area with breeding islets, managed by Natuurmonumenten'))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1999)
mk.check()
