# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(1985, 'Duinen van Oostvoorne', {
 'tags': ['Zuid-Holland · Oostvoorne', 'Parel van 264 hectare · bos, vochtige valleien, stuifduinen en bunkers · Meidoornroute met vogelhutten en strand van het Oostvoornse Meer', 'list 36 · no. 704'],
 'loc': '📍 Bij Oostvoorne, tussen dorp en Oostvoornse Meer · vrij toegankelijk; vernieuwd bezoekerscentrum; Meidoornroute van 12,5 km',
 'desc': 'De <b>Duinen van Oostvoorne</b> (264 hectare) zijn een van de parels van het <b>Zuid-Hollands Landschap</b>: in de verte zie je de kranen van de Maasvlakte, maar in het gebied zelf heerst rust. Bos, vochtige duinvalleien, stuifduinen en zelfs een landgoed wisselen elkaar af; de <b>Meidoornroute</b> (12,5 kilometer) neemt je mee langs duinmieren, de <b>Biberbunker</b>, de Kaapduin, vogelhutten en het zandstrand van het Oostvoornse Meer. Onderweg stap je even binnen bij het pas vernieuwde <b>bezoekerscentrum</b>. De bunkers herinneren aan de oorlog, de valleien en het groene duin aan eeuwen duinvorming — en overal is de ontmoeting tussen natuur en mens voelbaar: industrie aan de horizon, nachtegaal in het struweel. Wandel over gras, zand en grind, van donker bos naar open duin.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (nachtegaal, meidoornbloei en valleien), sep–okt (trek en herfstkleuren)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogels en licht; avond voor de bunkersfeer.',
 'why': ['De <b>Meidoornroute</b>: 12,5 kilometer duin in al zijn gedaanten.', 'De <b>bunkers</b>, met de Biberbunker als stille getuige.', 'De <b>vogelhutten</b> en het zandstrand van het Oostvoornse Meer.', 'Het <b>contrast</b>: Maasvlakte aan de horizon, rust in het duin.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nachtegaal en meidoornbloei</b> in valleien en struweel.', '<span class="months">Mei–Aug</span> 🐝 <b>Duinmieren en insectenleven</b> op het warme zand.', '<span class="months">Sep–Okt</span> 🍂 <b>Trekvogels en herfstkleuren</b> in het duinbos.', '<span class="months">Heel jaar</span> 🏚️ <b>Bunkers en oorlogsgeschiedenis</b> langs de route.'],
 'wild': ['🎵 Nachtegaal van het struweel', '🏚️ Biberbunker en duinbunkers', '🐝 Duinmieren op het zand', '🔭 Vogelhutten aan het Oostvoornse Meer', '🦌 Reeën van het duinbos'],
 'trail': ['Loop de <b>Meidoornroute</b> (12,5 km) vanaf het bezoekerscentrum.', 'Beklim de <b>Kaapduin</b> en daal af naar het strand van het Oostvoornse Meer.', 'Combineer met het <b>Groene Strand</b>, Mildenburg of Brielle.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; stuifduin en bunkers zijn kwetsbaar · 🚶 Gras, zand en grind; bezoekerscentrum met horeca'
}, {
 'tags': ['Zuid-Holland · Oostvoorne', '264-hectare gem · forest, moist valleys, drifting dunes and bunkers · Hawthorn route with bird hides and beach of the Oostvoornse Meer', 'list 36 · no. 704'],
 'loc': '📍 Near Oostvoorne, between village and Oostvoornse Meer · freely accessible; renewed visitor centre; 12.5-km Hawthorn route',
 'desc': 'The <b>Dunes of Oostvoorne</b> (264 hectares) are one of the gems of <b>Het Zuid-Hollands Landschap</b>: in the distance you see the cranes of the Maasvlakte, but within the area itself peace reigns. Forest, moist dune valleys, drifting dunes and even an estate alternate; the <b>Hawthorn route</b> (12.5 kilometres) takes you past dune ants, the <b>Beaver bunker</b>, the Kaapduin, bird hides and the sandy beach of the Oostvoornse Meer. Along the way step inside the newly renewed <b>visitor centre</b>. The bunkers recall the war, the valleys and the green dunes recall centuries of dune formation — and everywhere the encounter between nature and people is tangible: industry on the horizon, nightingale in the scrub. Walk over grass, sand and gravel, from dark forest to open dune.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (nightingale, hawthorn blossom and valleys), Sep–Oct (migration and autumn colours)<br>\\n    <b>Best time of day:</b> Morning — birds and light; evening for the bunker atmosphere.',
 'why': ['The <b>Hawthorn route</b>: 12.5 kilometres of dunes in all their forms.', 'The <b>bunkers</b>, with the Beaver bunker as a silent witness.', 'The <b>bird hides</b> and the sandy beach of the Oostvoornse Meer.', 'The <b>contrast</b>: Maasvlakte on the horizon, peace in the dunes.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Nightingale and hawthorn blossom</b> in valleys and scrub.', '<span class="months">May–Aug</span> 🐝 <b>Dune ants and insect life</b> on the warm sand.', '<span class="months">Sep–Oct</span> 🍂 <b>Migrants and autumn colours</b> in the dune forest.', '<span class="months">All year</span> 🏚️ <b>Bunkers and wartime history</b> along the route.'],
 'wild': ['🎵 Nightingale of the scrub', '🏚️ Beaver bunker and dune bunkers', '🐝 Dune ants on the sand', '🔭 Bird hides at the Oostvoornse Meer', '🦌 Roe deer of the dune forest'],
 'trail': ['Walk the <b>Hawthorn route</b> (12.5 km) from the visitor centre.', 'Climb the <b>Kaapduin</b> and descend to the beach of the Oostvoornse Meer.', 'Combine with the <b>Groene Strand</b>, Mildenburg or Brielle.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; drifting dunes and bunkers are vulnerable · 🚶 Grass, sand and gravel; visitor centre with café'
}))

C.append(mk.card(1986, 'Slikken van Voorne', {
 'tags': ['Zuid-Holland · Oostvoorne (monding Haringvliet)', 'Wadachtige slikken met zeeaster en schorrekruid · steltlopers, lepelaars en zeehonden · vogelkijkhutten aan de Noordzeeboulevard', 'list 36 · no. 705'],
 'loc': '📍 Bij Oostvoorne, aan de monding van het Haringvliet · te overzien vanaf vogelkijkhut Slikken van Voorne (Noordzeeboulevard) en Lyondellhut Westplaat',
 'desc': 'Waar het <b>Haringvliet</b> de Noordzee ontmoet, liggen de <b>Slikken van Voorne</b>: wadachtige slikken waar het getij nog vrij spel heeft. Door de natuurlijke ontwikkeling vestigden zich plantensoorten als <b>zeeaster</b>, melkkruid, kweldergras, schorrekruid en zilte schijnspurrie; in de wadachtige bodem wemelt het van de kleine diertjes — voedsel voor <b>scholekster</b>, bonte strandloper, wulp en tureluur. Rustende aalscholvers en <b>lepelaars</b> staan er schouder aan schouder, jagende slechtvalken, buizerds en haviken scheren over, en in de verte zijn regelmatig <b>zeehonden</b> te zien. Vanuit de <b>vogelkijkhut</b> aan de Noordzeeboulevard en de Lyondellhut op de Westplaat beleef je het schouwspel met verrekijker en camera. Een ideaal stukje getijdennatuur voor vogelaars — op een steenworp van het strand van Oostvoorne.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–Okt</b> (trekkende steltlopers), apr–jun (lepelaars en broedvogels)<br>\\n    <b>Beste tijd van de dag:</b> Laag water — slikken vallen droog en vogels foerageren.',
 'why': ['De <b>steltlopers van het slik</b>: wulp, tureluur en bonte strandloper dichtbij.', 'De <b>lepelaars</b> en rustende aalscholvers in de geulen.', 'De <b>zeehonden</b> in de verte bij de Westplaat.', 'De <b>vogelkijkhutten</b> met uitzicht over het getijdenlandschap.'],
 'phen': ['<span class="months">Aug–Okt</span> 🐦 <b>Trekkende steltlopers</b> op het droogvallende slik.', '<span class="months">Apr–Jun</span> 🥄 <b>Lepelaars</b> en broedvogels in de geulen.', '<span class="months">Heel jaar</span> 🦭 <b>Zeehonden</b> voor de kust bij de Westplaat.', '<span class="months">Aug–Sep</span> 🌸 <b>Bloeiende zeeaster</b> op de kwelder.'],
 'wild': ['🐦 Wulp · Tureluur · Scholekster · Bonte strandloper', '🥄 Lepelaar · Aalscholver', '🦭 Zeehonden in de verte', '🦅 Slechtvalk · Buizerd · Havik', '🌸 Zeeaster · Schorrekruid · Zilte schijnspurrie'],
 'trail': ['Kijk vanaf de <b>vogelkijkhut Slikken van Voorne</b> aan de Noordzeeboulevard.', 'Loop door naar de <b>Lyondellhut op de Westplaat</b> voor zeehonden en roofvogels.', 'Combineer met het <b>strand van Oostvoorne</b> of de Kwade Hoek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Verstoor de vogels niet; blijf bij de hutten en op de paden · 🚶 Neem verrekijker of camera mee'
}, {
 'tags': ['Zuid-Holland · Oostvoorne (Haringvliet mouth)', 'Mudflat-like sands with sea aster and glasswort · waders, spoonbills and seals · bird hides on the Noordzeeboulevard', 'list 36 · no. 705'],
 'loc': '📍 Near Oostvoorne, at the mouth of the Haringvliet · surveyed from the Slikken van Voorne bird hide (Noordzeeboulevard) and the Lyondell hut on the Westplaat',
 'desc': 'Where the <b>Haringvliet</b> meets the North Sea lie the <b>Slikken van Voorne</b>: mudflat-like sands where the tide still has free play. Through natural development plant species such as <b>sea aster</b>, sea milkwort, saltmarsh grass, glasswort and lesser sea-spurrey established themselves; the mudflat-like soil teems with tiny creatures — food for <b>oystercatcher</b>, dunlin, curlew and redshank. Resting cormorants and <b>spoonbills</b> stand shoulder to shoulder, hunting peregrines, buzzards and goshawks sweep across, and <b>seals</b> are regularly seen in the distance. From the <b>bird hide</b> on the Noordzeeboulevard and the Lyondell hut on the Westplaat you experience the spectacle with binoculars and camera. An ideal piece of tidal nature for birders — a stone’s throw from the beach of Oostvoorne.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Oct</b> (migrating waders), Apr–Jun (spoonbills and breeding birds)<br>\\n    <b>Best time of day:</b> Low water — mudflats fall dry and birds forage.',
 'why': ['The <b>waders of the mudflats</b>: curlew, redshank and dunlin up close.', 'The <b>spoonbills</b> and resting cormorants in the creeks.', 'The <b>seals</b> in the distance near the Westplaat.', 'The <b>bird hides</b> overlooking the tidal landscape.'],
 'phen': ['<span class="months">Aug–Oct</span> 🐦 <b>Migrating waders</b> on the drying mudflats.', '<span class="months">Apr–Jun</span> 🥄 <b>Spoonbills</b> and breeding birds in the creeks.', '<span class="months">All year</span> 🦭 <b>Seals</b> off the coast near the Westplaat.', '<span class="months">Aug–Sep</span> 🌸 <b>Flowering sea aster</b> on the salt marsh.'],
 'wild': ['🐦 Curlew · Redshank · Oystercatcher · Dunlin', '🥄 Spoonbill · Cormorant', '🦭 Seals in the distance', '🦅 Peregrine · Buzzard · Goshawk', '🌸 Sea aster · Glasswort · Lesser sea-spurrey'],
 'trail': ['Watch from the <b>Slikken van Voorne bird hide</b> on the Noordzeeboulevard.', 'Continue to the <b>Lyondell hut on the Westplaat</b> for seals and raptors.', 'Combine with the <b>beach of Oostvoorne</b> or the Kwade Hoek.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Do not disturb the birds; stay near the hides and on the paths · 🚶 Bring binoculars or a camera'
}))

C.append(mk.card(1987, 'Overbosch', {
 'tags': ['Zuid-Holland · ten zuiden van Oostvoorne', 'Knus bosje met eikenlanen · bosuilen en stinsenplanten · landgoedverleden aan de Overboslaan', 'list 36 · no. 706'],
 'loc': '📍 Aan de zuidkant van Oostvoorne, aan de Overboslaan · vrij toegankelijk voor publiek; paden worden vrijgehouden',
 'desc': 'Het <b>Overbosch</b> is een knus bos aan de zuidkant van <b>Oostvoorne</b>, waar je wandelt door mooie <b>eikenlanen</b> uit het landgoedverleden. In de oude bomen vinden <b>bosuilen</b> een plek om te rusten; in het voorjaar herinneren stinsenplanten als <b>bosanemoon</b> en look-zonder-look stil aan de buitenplaats die hier ooit lag — zulke voorjaarsbloeiers werden vroeger op buitenplaatsen aangeplant en verwilderden daarna. Het Zuid-Hollands Landschap houdt de paden vrij van takken en begroeiing, maar verder mag de natuur in Overbosch haar gang gaan. Klein van stuk, groot in sfeer: een bosje voor een ommetje, op een steenworp van Mildenburg, de Jacobaburcht en de duinen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–Apr</b> (bosanemoon en voorjaarsbloei), okt–nov (herfstkleuren)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogelzang; schemer voor de bosuil.',
 'why': ['De <b>eikenlanen</b> uit het landgoedverleden.', 'De <b>bosanemoon</b> en andere stinsenplanten in het voorjaar.', 'De <b>bosuil</b> die in de oude bomen rust.', 'Een <b>knus ommetjesbos</b> bij het dorp.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌸 <b>Bosanemoon en look-zonder-look</b> in bloei.', '<span class="months">Apr–Jun</span> 🎵 <b>Zangvogels</b> in de eikenlanen.', '<span class="months">Okt–Nov</span> 🍂 <b>Herfstkleuren</b> in het knusse bos.', '<span class="months">Heel jaar</span> 🦉 <b>Bosuil</b> rustend in de oude bomen.'],
 'wild': ['🦉 Bosuil', '🌸 Bosanemoon · Look-zonder-look', '🌳 Eikenlanen van het landgoed', '🐦 Bosvogels van het ommetje', '🍄 Herfstpaddenstoelen'],
 'trail': ['Maak een <b>ommetje door het Overbosch</b> vanaf de Overboslaan.', 'Wandel door naar <b>Mildenburg</b> en de Jacobaburcht.', 'Combineer met de <b>Duinen van Oostvoorne</b> of het Groene Strand.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Blijf op de paden; laat de natuur verder haar gang gaan · 🚶 Korte paden; goed te combineren met Mildenburg'
}, {
 'tags': ['Zuid-Holland · south of Oostvoorne', 'Cosy little forest with oak avenues · tawny owls and stinsen plants · estate past on the Overboslaan', 'list 36 · no. 706'],
 'loc': '📍 On the south side of Oostvoorne, on the Overboslaan · freely accessible to the public; paths are kept clear',
 'desc': 'The <b>Overbosch</b> is a cosy little forest on the south side of <b>Oostvoorne</b>, where you walk through lovely <b>oak avenues</b> from the estate past. <b>Tawny owls</b> find a place to rest in the old trees; in spring stinsen plants such as <b>wood anemone</b> and garlic mustard quietly recall the country seat that once lay here — such spring bloomers were planted on country seats in the past and then went wild. Het Zuid-Hollands Landschap keeps the paths free of branches and growth, but otherwise nature is left to its own devices in the Overbosch. Small in size, great in atmosphere: a little forest for a stroll, a stone’s throw from Mildenburg, the Jacoba castle ruins and the dunes.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Apr</b> (wood anemone and spring bloom), Oct–Nov (autumn colours)<br>\\n    <b>Best time of day:</b> Morning — birdsong; dusk for the tawny owl.',
 'why': ['The <b>oak avenues</b> from the estate past.', 'The <b>wood anemone</b> and other stinsen plants in spring.', 'The <b>tawny owl</b> resting in the old trees.', 'A <b>cosy strolling forest</b> near the village.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌸 <b>Wood anemone and garlic mustard</b> in bloom.', '<span class="months">Apr–Jun</span> 🎵 <b>Songbirds</b> in the oak avenues.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colours</b> in the cosy forest.', '<span class="months">All year</span> 🦉 <b>Tawny owl</b> resting in the old trees.'],
 'wild': ['🦉 Tawny owl', '🌸 Wood anemone · Garlic mustard', '🌳 Oak avenues of the estate', '🐦 Woodland birds of the stroll', '🍄 Autumn fungi'],
 'trail': ['Take a <b>stroll through the Overbosch</b> from the Overboslaan.', 'Walk on to <b>Mildenburg</b> and the Jacoba castle ruins.', 'Combine with the <b>Dunes of Oostvoorne</b> or the Groene Strand.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Stay on the paths; otherwise let nature take its course · 🚶 Short paths; easy to combine with Mildenburg'
}))

C.append(mk.card(1988, 'Strypemonde', {
 'tags': ['Zuid-Holland · Rockanje (Voornes Duin)', 'Betoverend voormalig landgoedbos aan de duinrand · metasequoia’s, wijngaardslakken en orchideeën · rode route van 5 km vanaf de Tenellaplas', 'list 36 · no. 707'],
 'loc': '📍 In Voornes Duin bij Rockanje · start bij bezoekerscentrum Tenellaplas (Duinstraat 12A); rode paaltjesroute van 5 km; honden aangelijnd op de paden',
 'desc': '<b>Strypemonde</b> is een betoverend bos vol verrassingen aan de duinrand van <b>Voornes Duin</b>. Rond 1900 werd hier aan de duinrand landgoed Strypemonde aangelegd; een deel is nu eigendom van <b>Natuurmonumenten</b> en kent een enorme variatie aan boomsoorten uit alle delen van de wereld — wandelend tussen <b>metasequoia’s</b>, steeneiken en osagedoorns kruist zomaar een enorme <b>wijngaardslak</b> je pad. Die slakken werden eind jaren tachtig naar verluidt door een liefhebber van escargots met een doos vol uit de Pyreneeën meegenomen en hier uitgezet — sindsdien vermeerderden ze zich flink. De route start bij de <b>Tenellaplas</b> van het Zuid-Hollands Landschap, volgt het A.J. Bootpad op de grens van de twee beheerders en voert langs de <b>Vogelwei</b>, een bloemrijke bosweide met orchideeën, en Italiaanse populieren met <b>maretak</b>. Spechten, mezen en roodborst zingen overal.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (orchideeën op de Vogelwei en vogelzang), na regen (wijngaardslakken)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht door het gevarieerde bos.',
 'why': ['Het <b>wereldbos</b>: metasequoia’s, steeneiken en osagedoorns bij elkaar.', 'De <b>wijngaardslakken</b> uit de Pyreneeën — zeker na een regenbui.', 'De <b>Vogelwei</b>: orchideeën in een bloemrijke bosweide.', 'De <b>maretak</b> hoog in de Italiaanse populieren.'],
 'phen': ['<span class="months">Apr–Jun</span> 🌸 <b>Orchideeën</b> op de bloemrijke Vogelwei.', '<span class="months">Na regen</span> 🐌 <b>Wijngaardslakken</b> massaal op het pad.', '<span class="months">Apr–Jun</span> 🎵 <b>Spechten, mezen en roodborst</b> in het landgoedbos.', '<span class="months">Heel jaar</span> 🌿 <b>Maretak</b> in de hoge populieren.'],
 'wild': ['🐌 Wijngaardslak (uitgezette exoot)', '🌳 Metasequoia · Steeneik · Osagedoorn', '🌸 Orchideeën van de Vogelwei', '🐦 Spechten · Mezen · Roodborst', '🌿 Maretak in de populieren'],
 'trail': ['Loop de <b>rode Strypemonderoute</b> (5 km) vanaf bezoekerscentrum Tenellaplas.', 'Volg het <b>A.J. Bootpad</b> op de grens van Natuurmonumenten en het Zuid-Hollands Landschap.', 'Combineer met het <b>Breede Water</b> of het Quackjeswater.'],
 'foot': '🐕 Honden aangelijnd op de paden · 💶 Gratis · ⚠️ Onverhard pad; controleer op teken · 🚶 Rode paaltjes; start Duinstraat 12A, Rockanje'
}, {
 'tags': ['Zuid-Holland · Rockanje (Voornes Duin)', 'Enchanting former estate forest at the dune edge · dawn redwoods, edible snails and orchids · red 5-km route from the Tenellaplas', 'list 36 · no. 707'],
 'loc': '📍 In Voornes Duin near Rockanje · start at the Tenellaplas visitor centre (Duinstraat 12A); red waymarked 5-km route; dogs on lead on the paths',
 'desc': '<b>Strypemonde</b> is an enchanting forest full of surprises at the dune edge of <b>Voornes Duin</b>. Around 1900 the Strypemonde estate was laid out here at the dune fringe; part is now owned by <b>Natuurmonumenten</b> and holds an enormous variety of tree species from all parts of the world — walking among <b>dawn redwoods</b>, holm oaks and osage oranges, a giant <b>edible snail</b> may well cross your path. Those snails were reportedly brought from the Pyrenees in a box by a lover of escargots in butter in the late eighties and released here — since then they have multiplied considerably. The route starts at the <b>Tenellaplas</b> of Het Zuid-Hollands Landschap, follows the A.J. Bootpad on the boundary of the two managers and passes the <b>Vogelwei</b>, a flowery forest glade with orchids, and Italian poplars with <b>mistletoe</b>. Woodpeckers, tits and robins sing everywhere.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (orchids on the Vogelwei and birdsong), after rain (edible snails)<br>\\n    <b>Best time of day:</b> Morning — light through the varied forest.',
 'why': ['The <b>world forest</b>: dawn redwoods, holm oaks and osage oranges together.', 'The <b>edible snails</b> from the Pyrenees — especially after rain.', 'The <b>Vogelwei</b>: orchids in a flowery forest glade.', 'The <b>mistletoe</b> high in the Italian poplars.'],
 'phen': ['<span class="months">Apr–Jun</span> 🌸 <b>Orchids</b> on the flowery Vogelwei.', '<span class="months">After rain</span> 🐌 <b>Edible snails</b> out in force on the path.', '<span class="months">Apr–Jun</span> 🎵 <b>Woodpeckers, tits and robin</b> in the estate forest.', '<span class="months">All year</span> 🌿 <b>Mistletoe</b> in the tall poplars.'],
 'wild': ['🐌 Edible snail (introduced exotic)', '🌳 Dawn redwood · Holm oak · Osage orange', '🌸 Orchids of the Vogelwei', '🐦 Woodpeckers · Tits · Robin', '🌿 Mistletoe in the poplars'],
 'trail': ['Walk the <b>red Strypemonde route</b> (5 km) from the Tenellaplas visitor centre.', 'Follow the <b>A.J. Bootpad</b> on the boundary of Natuurmonumenten and Het Zuid-Hollands Landschap.', 'Combine with the <b>Breede Water</b> or the Quackjeswater.'],
 'foot': '🐕 Dogs on lead on the paths · 💶 Free · ⚠️ Unpaved path; check for ticks · 🚶 Red waymarks; start Duinstraat 12A, Rockanje'
}))

C.append(mk.card(1989, 'Voornes Duin', {
 'tags': ['Zuid-Holland · Rockanje en Oostvoorne (Voorne)', 'Vochtig duingebied van 1400 hectare · lepelaars van Quackjeswater, Breede Water en Tenellaplas · Natura 2000 sinds 2008', 'list 36 · no. 708'],
 'loc': '📍 Op de punt van Voorne, bij Rockanje · vrij toegankelijk voor leden; bezoekerscentrum Tenellaplas (Duinstraat 12A); gemarkeerde routes, vogelkijkschermen en ruiterpaden',
 'desc': 'Het <b>Voornes Duin</b> (circa 1400 hectare) is het vochtige duingebied op de punt van <b>Voorne</b>, in beheer bij <b>Natuurmonumenten</b> (delen al sinds 1927) en het Zuid-Hollands Landschap — en sinds 2008 beschermd als <b>Natura 2000-gebied</b>. Bijna tweederde van de Nederlandse broedvogels nestelt hier. Het paradepaardje is de kolonie <b>lepelaars</b> van het oude duinmeer <b>Quackjeswater</b>, te zien vanaf het uitkijkpunt; het <b>Breede Water</b> ligt als duinmeer tussen twee duinenrijen in. Bij bezoekerscentrum <b>Tenellaplas</b> ligt het heempark dat Cees Sipkes in 1950 aanlegde, en in de vochtige valleien bloeit de <b>parnassia</b> welig. Dat dit unieke duinstruweel zo soortenrijk is, komt door het jonge kalkhoudende zand én doordat er geen drinkwater wordt gewonnen. Struin over onverharde paden door uitgestrekte duinen, sta stil bij het Breede Water en sluit af bij de Tenellaplas.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (lepelaars, parnassia en vogelkoor), okt–nov (trek en wintergasten)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over Breede Water en Quackjeswater.',
 'why': ['De <b>lepelaars van Quackjeswater</b> vanaf het uitkijkpunt.', 'Het <b>Breede Water</b>: duinmeer tussen twee duinenrijen.', 'Bezoekerscentrum <b>Tenellaplas</b> met heempark uit 1950.', 'De <b>parnassia</b> in de vochtige duinvalleien.'],
 'phen': ['<span class="months">Apr–Aug</span> 🥄 <b>Lepelaarkolonie</b> op het eilandje van Quackjeswater.', '<span class="months">Aug–Sep</span> 🌸 <b>Bloeiende parnassia</b> in de duinvalleien.', '<span class="months">Okt–Mrt</span> 🦆 <b>Wintergasten</b>: futen, eenden en ganzen op de plassen.', '<span class="months">Sep–Okt</span> 🫐 <b>Bessenrijkdom</b> voor trekvogels als lijsters.'],
 'wild': ['🥄 Lepelaar · Kleine zilverreiger · Aalscholver', '🌸 Parnassia van de duinvalleien', '💧 Quackjeswater · Breede Water · Tenellaplas', '🐦 Tweederde van de Nederlandse broedvogels', '🦌 Reeën en duinstruweel'],
 'trail': ['Loop de <b>Quackroute</b> (2,9 km) rond het Quackjeswater naar het uitkijkpunt.', 'Wandel de <b>Strypemonderoute</b> (5 km) of de <b>Breede-Waterroute</b> (3 km).', 'Start bij <b>bezoekerscentrum Tenellaplas</b>; excursies via Natuurmonumenten.'],
 'foot': '🐕 Honden aangelijnd op de paden · 💶 Gratis voor leden (excursies met korting) · ⚠️ Stevige waterdichte schoenen; verrekijker mee · 🚶 Gemarkeerde routes; fietspaden langs het gebied, ruiterpaden erdoor'
}, {
 'tags': ['Zuid-Holland · Rockanje and Oostvoorne (Voorne)', 'Humid dune area of 1,400 hectares · spoonbills of Quackjeswater, Breede Water and Tenellaplas · Natura 2000 since 2008', 'list 36 · no. 708'],
 'loc': '📍 On the tip of Voorne, near Rockanje · freely accessible to members; Tenellaplas visitor centre (Duinstraat 12A); marked routes, bird hides and bridle paths',
 'desc': 'The <b>Voornes Duin</b> (some 1,400 hectares) is the humid dune area on the tip of <b>Voorne</b>, managed by <b>Natuurmonumenten</b> (parts since 1927) and Het Zuid-Hollands Landschap — and protected as a <b>Natura 2000 site</b> since 2008. Nearly two-thirds of Dutch breeding birds nest here. The showpiece is the <b>spoonbill</b> colony of the old dune lake <b>Quackjeswater</b>, visible from the viewpoint; the <b>Breede Water</b> lies as a dune lake between two dune ridges. At the <b>Tenellaplas</b> visitor centre lies the native-plant garden laid out by Cees Sipkes in 1950, and <b>grass-of-Parnassus</b> blooms abundantly in the moist valleys. That this unique dune scrub is so rich in species is due to the young calcareous sand and to the fact that no drinking water is extracted. Roam over unpaved paths through vast dunes, pause at the Breede Water and finish at the Tenellaplas.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spoonbills, grass-of-Parnassus and dawn chorus), Oct–Nov (migration and winter visitors)<br>\\n    <b>Best time of day:</b> Morning — light over Breede Water and Quackjeswater.',
 'why': ['The <b>spoonbills of Quackjeswater</b> from the viewpoint.', 'The <b>Breede Water</b>: dune lake between two dune ridges.', 'The <b>Tenellaplas</b> visitor centre with its 1950 native-plant garden.', 'The <b>grass-of-Parnassus</b> in the moist dune valleys.'],
 'phen': ['<span class="months">Apr–Aug</span> 🥄 <b>Spoonbill colony</b> on the islet of Quackjeswater.', '<span class="months">Aug–Sep</span> 🌸 <b>Flowering grass-of-Parnassus</b> in the dune valleys.', '<span class="months">Oct–Mar</span> 🦆 <b>Winter visitors</b>: grebes, ducks and geese on the pools.', '<span class="months">Sep–Oct</span> 🫐 <b>Berry abundance</b> for migrant birds such as thrushes.'],
 'wild': ['🥄 Spoonbill · Little egret · Cormorant', '🌸 Grass-of-Parnassus of the dune valleys', '💧 Quackjeswater · Breede Water · Tenellaplas', '🐦 Two-thirds of Dutch breeding birds', '🦌 Roe deer and dune scrub'],
 'trail': ['Walk the <b>Quack route</b> (2.9 km) around Quackjeswater to the viewpoint.', 'Walk the <b>Strypemonde route</b> (5 km) or the <b>Breede Water route</b> (3 km).', 'Start at the <b>Tenellaplas visitor centre</b>; excursions via Natuurmonumenten.'],
 'foot': '🐕 Dogs on lead on the paths · 💶 Free for members (discount on excursions) · ⚠️ Sturdy waterproof shoes; bring binoculars · 🚶 Marked routes; cycle paths alongside, bridle paths through'
}, n2k='Natura 2000-gebied Voornes Duin (Habitat- en Vogelrichtlijn): vochtige duinvalleien, duinmeren en duinstruweel, in beheer bij Natuurmonumenten en het Zuid-Hollands Landschap', n2k_en='Natura 2000 site Voornes Duin (Habitats and Birds Directives): moist dune slacks, dune lakes and dune scrub, managed by Natuurmonumenten and Het Zuid-Hollands Landschap'))

mk.insert(C, chunk='reserves-1935-2034.json')
mk.progress(1989)
mk.check()
