# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2085, 'Personnenbos', {
 'tags': ['Gelderland · Beuningen (tussen Beuningen en Wijchen)', 'Zeldzaam middeleeuws rivierkleibos van 15 ha · percelen elk met eigen boomsoort · aronskelk en bosanemoon in het Broek', 'list 36 · no. 804'],
 'loc': '📍 Langgerekte bosstrook ten zuiden van Beuningen in het komgebied Het Broek · toegang via de Bijsterhuizenstraat / Wilhelminalaan; smalle paden door het bos',
 'desc': 'Het <b>Personnenbos</b> is een <b>15 hectare</b> grote, langgerekte bosstrook in het komgebied <b>Het Broek</b> tussen Beuningen en Wijchen — een van de laatste restanten van het <b>middeleeuwse rivierkleibos</b> dat hier ooit stond. Het gebied was in de middeleeuwen moeras, dat rond <b>1320</b> werd ontgonnen; op de topografische kaart van <b>1843/1844</b> heeft het bos al vrijwel zijn huidige begrenzing. De naam verwijst naar een Middelnederlands woord voor een <b>persoon</b> — een geestelijke die zijn kerk door een plaatsvervanger liet bedienen. Het bos werd ooit als productiebos aangelegd, en dat is nog af te lezen aan de <b>vierkante percelen</b> waarin telkens één boomsoort domineert: <b>eiken, populieren, wilgen, essen en esdoorns</b> door elkaar. Staatsbosbeheer beheert het sinds <b>1949</b>, toen het via het Besluit Vijandelijk Vermogen van de familie Von Nagel-Domick overging. Botanisch is het bos een A-locatie: het is het enige goed ontwikkelde voorbeeld van een <b>eiken-haagbeukenbos</b> binnen het rivierengebied, en in het vroege voorjaar bloeien <b>aronskelk en bosanemoon</b> op de kleigrond, terwijl de <b>groene specht</b> in de oude bomen hamert.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–Apr</b> (aronskelk, bosanemoon), mei–jun (broedvogels)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — lentelicht tussen de kale stammen.',
 'why': ['Een van de laatste <b>middeleeuwse rivierkleibossen</b> van Nederland (15 ha).', 'De <b>vierkante percelen</b> met elk een eigen boomsoort.', '<b>Aronskelk en bosanemoon</b> in het vroege voorjaar.', 'Het <b>eiken-haagbeukenbos</b> — enige voorbeeld in het rivierengebied.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌱 <b>Aronskelk en bosanemoon</b> bloeien.', '<span class="months">Apr–Jun</span> 🎵 <b>Broedvogels</b> in de oude bomen.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> van es en esdoorn.', '<span class="months">Heel jaar</span> 🌳 <b>Oude boslocatie</b> met gekartelde perceelsgrenzen.'],
 'wild': ['🌱 Aronskelk · bosanemoon', '🪶 Groene specht', '🌳 Eiken-haagbeukenbos (uniek in rivierengebied)', '🗺️ Boschrook al op kaart van 1843/1844', '💧 Komklei van Het Broek'],
 'trail': ['Wandel de <b>smalle paden</b> door de bosstrook vanaf de Bijsterhuizenstraat.', 'Combineer met een rondje over de <b>wegen van Het Broek</b> richting de Waaldijk.', 'Bezoek in het <b>vroege voorjaar</b> voor de bloeiende vloer.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Smalle paden — fietsen niet toegestaan · 🚶 Bosstrook ± 2 km'
}, {
 'tags': ['Gelderland · Beuningen (between Beuningen and Wijchen)', 'Rare 15-ha medieval river-clay woodland · square compartments each with its own tree species · lords-and-ladies and wood anemone in the Broek', 'list 36 · no. 804'],
 'loc': '📍 Long narrow strip of woodland south of Beuningen in the Broek basin · access via the Bijsterhuizenstraat / Wilhelminalaan; narrow paths through the wood',
 'desc': 'The <b>Personnenbos</b> is a <b>15-hectare</b> long strip of woodland in the basin of <b>Het Broek</b> between Beuningen and Wijchen — one of the last remnants of the <b>medieval river-clay forest</b> that once stood here. In the Middle Ages the area was marsh, reclaimed around <b>1320</b>; on the topographic map of <b>1843/1844</b> the wood already has almost its present boundaries. The name refers to a Middle Dutch word for a <b>parson</b> — a cleric who had his church served by a substitute. The wood was once laid out as production forest, still readable in the <b>square compartments</b> in which a single tree species dominates each time: <b>oaks, poplars, willows, ashes and maples</b> side by side. Staatsbosbeheer has managed it since <b>1949</b>, when it passed from the Von Nagel-Domick family under the Enemy Property Decree. Botanically the wood is an A-location: it is the only well-developed example of an <b>oak-hornbeam forest</b> within the river region, and in early spring <b>lords-and-ladies and wood anemone</b> flower on the clay, while the <b>green woodpecker</b> hammers in the old trees.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Apr</b> (lords-and-ladies, wood anemone), May–Jun (breeding birds)<br>\\n    <b>Best time of day:</b> Early morning — spring light between bare trunks.',
 'why': ['One of the last <b>medieval river-clay woodlands</b> of the Netherlands (15 ha).', 'The <b>square compartments</b>, each with its own tree species.', '<b>Lords-and-ladies and wood anemone</b> in early spring.', 'The <b>oak-hornbeam forest</b> — the only example in the river region.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌱 <b>Lords-and-ladies and wood anemone</b> in flower.', '<span class="months">Apr–Jun</span> 🎵 <b>Breeding birds</b> in the old trees.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> of ash and maple.', '<span class="months">All year</span> 🌳 <b>Ancient woodland site</b> with notched boundaries.'],
 'wild': ['🌱 Lords-and-ladies · wood anemone', '🪶 Green woodpecker', '🌳 Oak-hornbeam forest (unique in the river region)', '🗺️ Wood already on the 1843/1844 map', '💧 Basin clay of Het Broek'],
 'trail': ['Walk the <b>narrow paths</b> through the strip from the Bijsterhuizenstraat.', 'Combine with a loop over the <b>lanes of Het Broek</b> towards the Waal dike.', 'Visit in <b>early spring</b> for the flowering floor.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Narrow paths — no cycling allowed · 🚶 Strip ± 2 km'
}))

C.append(mk.card(2086, 'Den Tuut', {
 'tags': ['Gelderland · Appeltern (Maasoever, Land van Maas en Waal)', 'Tuitvormige plas met Stoomgemaal De Tuut (1917) — enige overgebleven van 34 Gelderse stoomgemalen · Heerlijkheid Appeltern en ooievaarsnest', 'list 36 · no. 805'],
 'loc': '📍 De Tuut 2, Appeltern (aan de Nieuwe Wetering) · parkeerplaats Prinsenwaard; wandeling 5 km langs gemaal, Heerlijkheid, Spijkswiel en de Maas',
 'desc': 'Aan de rand van Appeltern ligt <b>De Tuut</b>: een <b>tuitvormige plas</b> in het oude rivierenlandschap bij de Maas, waaraan één van de meest geliefde machines van Gelderland staat — het <b>Stoomgemaal De Tuut</b> uit <b>1917</b>. Het is het <b>enige nog bestaande van de 34 stoomgemalen</b> die het Gelderse rivierengebied ooit telde: een volledig gerestaureerd, werkend monument uit de strijd tegen het water, waarin de ketels tijdens de stoomweekends worden opgestookt en het Stoomcafé uitziet over de Nieuwe Wetering. Om het gemaal ligt een compact landschap vol geschiedenis: de <b>Heerlijkheid Appeltern</b>, een buitenplaats waarvan de wortels tot de middeleeuwen reiken, met parkbos, monumentale <b>Gelderse boerderijen</b> (de huidige gebouwen na de brand van 1927 heropgebouwd) en de beroemde Tuinen van Appeltern naast de deur; verderop het <b>Spijkswiel</b> en de <b>Maasbandijk</b> met weidse uitzichten over de rivier. Bij het gemaal broedt een <b>ooievaarsnest</b>-paar op het terrein. De korte wandeling (± 5 km) combineert waterstaatshistorie, landgoedcultuur en rivier natuur in één dorps rondje — rivierenland zoals het bedoeld is.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Sep</b> (stoomseizoen, ooievaars), mei–jun (weidevogels in de polder)<br>\\n    <b>Beste tijd van de dag:</b> Middag — stoom uit de schoorsteen bij een stoomweekend.',
 'why': ['Het <b>werkende Stoomgemaal De Tuut</b> (1917) — uniek in Gelderland.', 'De <b>tuitvormige plas</b> die het gebied zijn naam gaf.', 'De <b>Heerlijkheid Appeltern</b> met Gelderse boerderijen en parkbos.', 'Het <b>ooievaarsnest</b> bij het gemaal.'],
 'phen': ['<span class="months">Apr–Sep</span> ⚙️ <b>Stoomseizoen</b> — het gemaal onder stoom.', '<span class="months">Apr–Jul</span> 🪶 <b>Ooievaars</b> op het nest bij het gemaal.', '<span class="months">Mei–Jun</span> 🎵 <b>Weidevogels</b> in de Appelternse polder.', '<span class="months">Heel jaar</span> 🚶 <b>Dorpsrivierenland</b> langs Wetering, wiel en Maas.'],
 'wild': ['⚙️ Stoomgemaal De Tuut (rijksmonument)', '🪶 Ooievaars op het nest', '🏡 Heerlijkheid Appeltern', '💧 Tuitvormige plas en Nieuwe Wetering', '🌊 Maasbandijk en Spijkswiel'],
 'trail': ['Loop de <b>5 km-wandeling</b> vanaf de Prinsenwaard langs gemaal, Heerlijkheid, Spijkswiel en Maasdijk.', 'Bezoek het <b>stoomgemaal</b> tijdens de stoomweekends (Stoomcafé).', 'Combineer met de <b>Tuinen van Appeltern</b> voor de tuinliefhebber.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (gemaal met entreeprijs bij stoomdagen) · 🚶 Rondje ± 5 km'
}, {
 'tags': ['Gelderland · Appeltern (Maas bank, Land van Maas en Waal)', 'Funnel-shaped lake with the De Tuut steam pumping station (1917) — sole survivor of 34 Gelderland steam stations · Heerlijkheid Appeltern and a stork nest', 'list 36 · no. 805'],
 'loc': '📍 De Tuut 2, Appeltern (on the Nieuwe Wetering) · Prinsenwaard car park; 5-km walk past station, estate, Spijkswiel and the Maas',
 'desc': 'At the edge of Appeltern lies <b>De Tuut</b>: a <b>funnel-shaped lake</b> in the old river landscape by the Maas, beside one of Gelderland’s best-loved machines — the <b>De Tuut steam pumping station</b> of <b>1917</b>. It is the <b>sole survivor of the 34 steam stations</b> the Gelderland river region once counted: a fully restored, working monument of the struggle against the water, its boilers fired up during steam weekends and its Steam Café overlooking the Nieuwe Wetering. Around the station lies a compact landscape full of history: the <b>Heerlijkheid Appeltern</b>, a country seat whose roots reach the Middle Ages, with park woodland, monumental <b>Gelderse farmhouses</b> (rebuilt after the 1927 fire) and the famous Gardens of Appeltern next door; further on the <b>Spijkswiel</b> pool and the <b>Maas dike</b> with wide views over the river. On the terrain a pair of <b>storks</b> breeds on its nest by the station. The short walk (± 5 km) combines hydraulic engineering history, estate culture and river nature in one village loop — river country as it was meant to be.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Sep</b> (steam season, storks), May–Jun (meadow birds in the polder)<br>\\n    <b>Best time of day:</b> Midday — steam from the chimney during a steam weekend.',
 'why': ['The <b>working De Tuut steam pumping station</b> (1917) — unique in Gelderland.', 'The <b>funnel-shaped lake</b> that gave the area its name.', 'The <b>Heerlijkheid Appeltern</b> with Gelderse farmhouses and park woodland.', 'The <b>stork nest</b> by the station.'],
 'phen': ['<span class="months">Apr–Sep</span> ⚙️ <b>Steam season</b> — the station under steam.', '<span class="months">Apr–Jul</span> 🪶 <b>Storks</b> on the nest by the station.', '<span class="months">May–Jun</span> 🎵 <b>Meadow birds</b> in the Appeltern polder.', '<span class="months">All year</span> 🚶 <b>Village river land</b> along waterway, pool and Maas.'],
 'wild': ['⚙️ De Tuut steam station (national monument)', '🪶 Storks on the nest', '🏡 Heerlijkheid Appeltern', '💧 Funnel-shaped lake and Nieuwe Wetering', '🌊 Maas dike and Spijkswiel'],
 'trail': ['Walk the <b>5-km loop</b> from the Prinsenwaard past station, estate, Spijkswiel and Maas dike.', 'Visit the <b>steam station</b> during steam weekends (Steam Café).', 'Combine with the <b>Gardens of Appeltern</b> for garden lovers.'],
 'foot': '🐕 Dogs on lead · 💶 Free (station with entry fee on steam days) · 🚶 Loop ± 5 km'
}))

C.append(mk.card(2087, 'Laakse Bos', {
 'tags': ['Gelderland · Appeltern/Batenburg (gemeente Wijchen)', 'GLK-bos met oude bosgroeiplaats (al bos in 1820) · populieren omgevormd tot eiken-essenbos · Moringerwaarden met bevers', 'list 36 · no. 806'],
 'loc': '📍 Noord-Zuid bij Appeltern, tussen Appeltern en Batenburg · toegang via de landweggetjes; wandelroutes vanuit Batenburg (kasteelruïne) of Appeltern',
 'desc': 'Het <b>Laakse Bos</b> bij Appeltern en Batenburg is een <b>oude bosgroeiplaats</b>: op de oudste gevonden kaart, uit <b>1820</b>, is het gebied al bos. Tot <b>1948</b> bestond het vooral uit dicht eikenbos; daarna volgde de tijd van de populierenteelt, en nu zet Geldersch Landschap &amp; Kasteelen het terug naar een <b>eiken-essenbos</b> — de oorspronkelijke riviernatuur van deze gronden. Daartussen liggen <b>elzenhakhout</b>, <b>meidoornhagen</b>, graslanden en moeraspercelen, waardoor het bos het karakter van een kleinschalig landgoedbos houdt. Omdat het een van de <b>weinige bossen in de omgeving</b> is, is het van groot belang voor flora en fauna van heel dit deel van Maas en Waal. Aan de rivierzijde sluit het bos aan op de <b>Moringerwaarden</b>, een natuurontwikkelingsgebied met plassen, <b>wilgenmoeras</b> en graslanden — en met <b>bevers</b>, die er hun sporen achterlaten in de wilgen. Samen vormen bos en waarden een stil geheel van oude houtwallen en jonge rivierdynamiek, op loopafstand van de kasteelruïne van Batenburg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (voorjaarsflora), sep–okt (paddenstoelen in eiken-essenbos)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang van bosvogels onder oude eiken.',
 'why': ['De <b>oude bosgroeiplaats</b>: al bos op de kaart van 1820.', 'De <b>omvorming</b> van populieren naar eiken-essenbos door GLK.', 'De <b>Moringerwaarden</b> met wilgenmoeras en <b>bevers</b>.', 'Een van de <b>weinige bossen</b> van Maas en Waal — leefgebied voor de hele regio.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> onder eik en es.', '<span class="months">Mei–Jun</span> 🎵 <b>Bosvogels</b> in hakhout en hagen.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in het oude bos.', '<span class="months">Heel jaar</span> 🦫 <b>Bever-sporen</b> in de Moringerwaarden.'],
 'wild': ['🌳 Eiken-essenbos in ontwikkeling', '🌿 Elzenhakhout en meidoornhagen', '🦫 Bevers in de Moringerwaarden', '🗺️ Oude bosgroeiplaats (1820)', '🍄 Paddenstoelenrijk kleibos'],
 'trail': ['Wandel vanuit <b>Batenburg</b> (kasteelruïne) het Laakse Bos in richting Appeltern.', 'Volg de <b>landweggetjes</b> langs hagen en hooilandjes.', 'Steek over naar de <b>Moringerwaarden</b> voor moeras en beversporen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Bos-en-waardwandeling ± 6 km'
}, {
 'tags': ['Gelderland · Appeltern/Batenburg (municipality of Wijchen)', 'GLK woodland on an ancient woodland site (already forest on the 1820 map) · poplars converted back to oak-ash forest · Moringerwaarden with beavers', 'list 36 · no. 806'],
 'loc': '📍 Noord-Zuid by Appeltern, between Appeltern and Batenburg · access via the small country lanes; walking routes from Batenburg (castle ruin) or Appeltern',
 'desc': 'The <b>Laakse Bos</b> at Appeltern and Batenburg is an <b>ancient woodland site</b>: on the oldest surviving map, from <b>1820</b>, the area is already forest. Until <b>1948</b> it consisted mainly of dense oak forest; the era of poplar growing followed, and now Geldersch Landschap &amp; Kasteelen is converting it back to <b>oak-ash forest</b> — the original river nature of these soils. In between lie <b>coppiced alder</b>, <b>hawthorn hedges</b>, grasslands and marshy fields, keeping the wood the character of a small-scale estate forest. As one of the <b>few woods in the surroundings</b>, it matters greatly for the flora and fauna of this whole part of Maas en Waal. On the river side the wood connects to the <b>Moringerwaarden</b>, a nature development area of lakes, <b>willow marsh</b> and grasslands — and of <b>beavers</b>, who leave their tracks in the willows. Together, wood and waarden form a quiet whole of old hedgerows and young river dynamics, within walking distance of the Batenburg castle ruin.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring flora), Sep–Oct (fungi in the oak-ash forest)<br>\\n    <b>Best time of day:</b> Morning — woodland birdsong under old oaks.',
 'why': ['The <b>ancient woodland site</b>: already forest on the 1820 map.', 'The GLK <b>conversion</b> of poplars back to oak-ash forest.', 'The <b>Moringerwaarden</b> with willow marsh and <b>beavers</b>.', 'One of the <b>few woods</b> of Maas en Waal — habitat for the whole region.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> under oak and ash.', '<span class="months">May–Jun</span> 🎵 <b>Woodland birds</b> in coppice and hedges.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old wood.', '<span class="months">All year</span> 🦫 <b>Beaver tracks</b> in the Moringerwaarden.'],
 'wild': ['🌳 Oak-ash forest in the making', '🌿 Coppiced alder and hawthorn hedges', '🦫 Beavers in the Moringerwaarden', '🗺️ Ancient woodland site (1820)', '🍄 Fungus-rich clay woodland'],
 'trail': ['Walk from <b>Batenburg</b> (castle ruin) into the Laakse Bos towards Appeltern.', 'Follow the <b>country lanes</b> past hedges and hay fields.', 'Cross to the <b>Moringerwaarden</b> for marsh and beaver tracks.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Wood-and-waard walk ± 6 km'
}))

C.append(mk.card(2088, 'Eendenkooi Batenburg', {
 'tags': ['Gelderland · Batenburg (Bergharensestraat)', 'Volledig bedrijfsklare eendenkooi van GLK in originele staat · kooiplas met vangpijpen, lokeenden en kooikerhondje · alleen te bezoeken op excursie', 'list 36 · no. 807'],
 'loc': '📍 Bergharensestraat, Batenburg — begin toegangsweg naar de eendenkooi; parkeren langs de Bergharensestraat · uitsluitend toegankelijk via GLK-rondleidingen (apr–jun, vooraf reserveren)',
 'desc': 'Aan de Bergharensestraat bij Batenburg ligt een van de best bewaarde <b>eendenkooien</b> van Nederland. Van de ruim honderd geregistreerde kooien die Nederland nog telt, heeft menigmaal slechts één vangpijp gebruiksklare standing — maar de <b>eendenkooi Batenburg</b> is <b>volledig bedrijfsklaar en in originele staat</b>, met een flinke <b>kooiplas</b> waarop meerdere smalle sloten uitkomen: de <b>vangpijpen</b>, overdekt met netten die worden gedragen door gespannen wilgentakken. Hier werkte eeuwenlang de <b>kooiker</b> met zijn <b>tamme lokeenden</b> — de kwakers — en zijn <b>kooikerhondje</b>, dat de wilde eenden met speels gedrag de pij in lokte voor de vangst. Geldersch Landschap &amp; Kasteelen beheert de kooi en houdt haar <b>gesloten voor publiek</b>: rust is in een kooi alles. Wie haar wil zien, boekt in het voorjaar een <b>excursie met de boswachter</b> (± 2 uur, reserveren noodzakelijk), waarin de historie, de begroeiing en het beheer van de kooi worden uitgelegd — en de beroemde sfeer van rust en geheimzinnigheid zelf te ervaren is.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (excursieseizoen GLK), sep–mrt (rust- en trektijd rond de kooiplas)<br>\\n    <b>Beste tijd van de dag:</b> Volgens de kooiker: de vroege ochtend.',
 'why': ['De <b>volledig bedrijfsklare kooi</b> — uniek onder de ± 119 Nederlandse eendenkooien.', 'De <b>vangpijpen met netten op wilgentakken</b> en de kooiplas.', 'Het verhaal van <b>lokeenden en kooikerhondje</b>.', 'De <b>boswachtersexcursies</b> (apr–jun) — de enige manier om binnen te komen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🧭 <b>Excursieseizoen</b> met de GLK-boswachter.', '<span class="months">Sep–Nov</span> 🪿 <b>Trekeenden</b> boven het kooibos.', '<span class="months">Apr–Jul</span> 🦆 <b>Lokeenden</b> op de kooiplas.', '<span class="months">Heel jaar</span> 🌳 <b>Kooibos</b> in alle stilte gesloten.'],
 'wild': ['🦆 Wilde en tamme eenden', '🐕 Kooikerhondje (op de excursie)', '🌳 Kooibos met wilgen en riet', '💧 Kooiplas met vangpijpen', '🕰️ Eendenkooi in originele staat'],
 'trail': ['Boek een <b>rondleiding</b> via glk.nl/excursies (apr–jun, ± 2 uur).', 'Startpunt: <b>begin toegangsweg</b> Bergharensestraat, Batenburg.', 'Combineer met <b>kasteel Batenburg</b> en het Laakse Bos (kaart 2087).'],
 'foot': '🚫 Alleen op excursie toegankelijk — rust is het beheer · 💶 Excursie ± € 10 (kinderen korting) · 🐕 Honden niet toegestaan · 📅 Reserveren noodzakelijk'
}, {
 'tags': ['Gelderland · Batenburg (Bergharensestraat)', 'Fully operational GLK duck decoy in original state · decoy pond with pipes, tame decoy ducks and a kooikerhondje · accessible only on guided excursions', 'list 36 · no. 807'],
 'loc': '📍 Bergharensestraat, Batenburg — start of the access lane to the decoy; parking along the Bergharensestraat · accessible only via GLK guided tours (Apr–Jun, booking required)',
 'desc': 'On the Bergharensestraat at Batenburg lies one of the best-preserved <b>duck decoys</b> of the Netherlands. Of the roughly hundred registered decoys the country still counts, many have just one pipe in working order — but the <b>Batenburg decoy</b> is <b>fully operational and in original state</b>, with a sizeable <b>decoy pond</b> into which several narrow ditches open: the <b>pipes</b>, covered with nets carried by bent willow rods. Here the <b>kooiker</b> worked for centuries with his <b>tame decoy ducks</b> — the callers — and his <b>kooikerhondje</b>, whose playful antics lured wild ducks up the pipe for the catch. Geldersch Landschap &amp; Kasteelen manages the decoy and keeps it <b>closed to the public</b>: in a decoy, quiet is everything. To see it, book a <b>guided walk with the forester</b> in spring (± 2 hours, booking required), in which the history, the planting and the management are explained — and the famous atmosphere of peace and mystery can be experienced first-hand.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (GLK excursion season), Sep–Mar (quiet and migration time around the pond)<br>\\n    <b>Best time of day:</b> As any kooiker knows: the early morning.',
 'why': ['The <b>fully operational decoy</b> — unique among the ± 119 Dutch decoys.', 'The <b>pipes with nets on willow rods</b> and the pond.', 'The story of <b>decoy ducks and the kooikerhondje</b>.', 'The <b>forester-led excursions</b> (Apr–Jun) — the only way in.'],
 'phen': ['<span class="months">Apr–Jun</span> 🧭 <b>Excursion season</b> with the GLK forester.', '<span class="months">Sep–Nov</span> 🪿 <b>Migrating ducks</b> over the decoy wood.', '<span class="months">Apr–Jul</span> 🦆 <b>Decoy ducks</b> on the pond.', '<span class="months">All year</span> 🌳 <b>Decoy wood</b> closed in all its quiet.'],
 'wild': ['🦆 Wild and tame ducks', '🐕 Kooikerhondje (on the excursion)', '🌳 Decoy wood with willows and reed', '💧 Decoy pond with pipes', '🕰️ Decoy in original state'],
 'trail': ['Book a <b>guided tour</b> via glk.nl/excursies (Apr–Jun, ± 2 hours).', 'Starting point: <b>start of the access lane</b>, Bergharensestraat, Batenburg.', 'Combine with <b>Batenburg castle</b> and the Laakse Bos (card 2087).'],
 'foot': '🚫 Accessible only on an excursion — quiet is the management · 💶 Excursion ± € 10 (child discount) · 🐕 Dogs not allowed · 📅 Booking required'
}))

C.append(mk.card(2089, 'Hernense Bos en omgeving kasteel Hernen', {
 'tags': ['Gelderland · Hernen (Land van Maas en Waal)', 'Middeleeuws kasteel met overdekte weergangen op een rug van rivierzand · eikenhakhout en grove dennen · Hernense Ven en vijf spechtsoorten', 'list 36 · no. 808'],
 'loc': '📍 Dorp Hernen, toegang vanaf de Van Balverenlaan (bezoekerscentrum Land van de Heerlijkheden) · gemarkeerde rondwandeling 2 km (rood/geel) door bos, ven en langs kasteel en molen',
 'desc': 'In het dorpje <b>Hernen</b> komt de tijd tot stilstand: daar staat, omgracht en half verstoken van de wereld, <b>Kasteel Hernen</b> — een middeleeuwse burcht met <b>unieke overdekte weergangen</b>, die in <b>1940</b> het allereerste bezit werd van de Stichting Vrienden der Geldersche Kasteelen. Kasteel en <b>Hernense Bos</b> vormden vroeger de heerlijkheid Hernen, een gebied van ruim <b>109 hectare</b> op een rug van <b>opgestoven rivierzand</b> die zo’n tienduizend jaar geleden ontstond. Het bos bestaat vooral uit <b>eikenhakhout en grove dennen</b> — de dennen werden vroeger aangeplant voor stuthout voor de mijnbouw — afgewisseld met graslanden, lanen en <b>oude rivierlopen</b>. Bij de aanleg van de A50 werden bos en kasteelterrein van elkaar gescheiden. In het bos ligt het <b>Hernense Ven</b>: een laagte die ontstond doordat de wind het stuifzand wegblies en die zich vult met regenwater — rijk aan libellen, waterplanten en amfibieën. De <b>spechten</b> zijn de trots van het gebied: de <b>grote, middelste en kleine bonte specht</b> en de <b>groene en zwarte specht</b> werden hier alle vijf vastgesteld. Aan de rand staat de <b>Hernense molen</b> uit 1745, en de gemarkeerde wandeling van ± 2 km voert langs bos, ven, molen en kasteel.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (spechten, venlibellen), mei–sep (kasteel open op zon- en feestdagen)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — spechtengeluid in het hakhout.',
 'why': ['<b>Kasteel Hernen</b> met zijn overdekte weergangen — eerste bezit van de Vrienden der Geldersche Kasteelen (1940).', 'De <b>rug van opgestoven rivierzand</b> met eikenhakhout en dennen.', 'Het <b>Hernense Ven</b> met libellen en amfibieën.', '<b>Vijf spechtsoorten</b> in één bos — van klein bont tot zwart.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Spechten</b> hameren in hakhout en lanen.', '<span class="months">Mei–Sep</span> 🏰 <b>Kasteel</b> opent op zon- en feestdagen.', '<span class="months">Jun–Aug</span> 🦟 <b>Libellen</b> boven het Hernense Ven.', '<span class="months">Heel jaar</span> 🌾 <b>Oude rivierlopen</b> en lanen in het landschap.'],
 'wild': ['🪶 5 spechtsoorten', '🏰 Kasteel Hernen met weergangen', '💧 Hernense Ven (regenwater-ven)', '🌬️ Eikenhakhout op rivierzand', '⚙️ Hernense molen (1745)'],
 'trail': ['Loop de <b>gemarkeerde rondwandeling</b> (± 2 km, rood/geel) langs bos, ven, molen en kasteel.', 'Bezoek het <b>bezoekerscentrum Land van de Heerlijkheden</b> in Leur als start.', 'Combineer met de <b>wandelroute Heerlijkheid Leur</b> (kaart 2090, 8 km).'],
 'foot': '🐕 Honden aangelijnd (in delen van het gebied los) · 💶 Gratis (kasteel met entreeprijs) · 🚶 Rondje ± 2 km'
}, {
 'tags': ['Gelderland · Hernen (Land van Maas en Waal)', 'Medieval castle with covered wall-walks on a ridge of blown river sand · oak coppice and Scots pines · Hernense Ven pool and five woodpecker species', 'list 36 · no. 808'],
 'loc': '📍 Village of Hernen, access from the Van Balverenlaan (Land van de Heerlijkheden visitor centre) · marked 2-km circular walk (red/yellow) through wood, pool, past castle and mill',
 'desc': 'In the little village of <b>Hernen</b> time comes to a standstill: there stands, moated and half hidden from the world, <b>Hernen Castle</b> — a medieval keep with <b>unique covered wall-walks</b>, which in <b>1940</b> became the very first possession of the Friends of the Gelderse Castles Foundation. Castle and <b>Hernense Bos</b> once formed the lordship of Hernen, an area of over <b>109 hectares</b> on a ridge of <b>blown river sand</b> that arose some ten thousand years ago. The wood consists mainly of <b>oak coppice and Scots pines</b> — the pines were once planted for mine props — alternating with grasslands, lanes and <b>old river courses</b>. With the building of the A50, wood and castle grounds were separated. In the wood lies the <b>Hernense Ven</b>: a hollow created by wind blowing out the drift sand, now filled with rain water — rich in dragonflies, water plants and amphibians. The <b>woodpeckers</b> are the pride of the area: <b>great, middle and lesser spotted</b> and <b>green and black woodpecker</b> have all five been recorded here. At the edge stands the <b>Hernense mill</b> of 1745, and the marked walk of ± 2 km leads past wood, pool, mill and castle.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (woodpeckers, pool dragonflies), May–Sep (castle open on Sundays and holidays)<br>\\n    <b>Best time of day:</b> Early morning — woodpecker sound in the coppice.',
 'why': ['<b>Hernen Castle</b> with its covered wall-walks — first possession of the Friends of the Gelderse Castles (1940).', 'The <b>ridge of blown river sand</b> with oak coppice and pines.', 'The <b>Hernense Ven</b> with dragonflies and amphibians.', '<b>Five woodpecker species</b> in one wood — from lesser spotted to black.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Woodpeckers</b> drumming in coppice and lanes.', '<span class="months">May–Sep</span> 🏰 <b>Castle</b> opens on Sundays and holidays.', '<span class="months">Jun–Aug</span> 🦟 <b>Dragonflies</b> over the Hernense Ven.', '<span class="months">All year</span> 🌾 <b>Old river courses</b> and lanes in the landscape.'],
 'wild': ['🪶 5 woodpecker species', '🏰 Hernen Castle with wall-walks', '💧 Hernense Ven (rain-water pool)', '🌬️ Oak coppice on river sand', '⚙️ Hernense mill (1745)'],
 'trail': ['Walk the <b>marked circular walk</b> (± 2 km, red/yellow) past wood, pool, mill and castle.', 'Start at the <b>Land van de Heerlijkheden visitor centre</b> in Leur.', 'Combine with the <b>Heerlijkheid Leur walk</b> (card 2090, 8 km).'],
 'foot': '🐕 Dogs on lead (off-lead in parts) · 💶 Free (castle with entry fee) · 🚶 Loop ± 2 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2089)
mk.check()
