# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2075, 'Ochtense Buitenpolder', {
 'tags': ['Gelderland · Ochten/Dodewaard (zuidoever van de Waal)', 'Agrarische uiterwaard met oude strangen, tichelgaten en zachthoutooibos · weidevogelgraslanden en begrazing · kleiwinninggebied in ontwikkeling', 'list 36 · no. 794'],
 'loc': '📍 Tussen Dodewaard en Ochten aan de zuidkant van de Waal, via de Waalbandijk bij Ochten · graspaden en landwegen door de polder; runderen grazen in het gebied',
 'desc': 'De <b>Ochtense Buitenpolder</b> — op oude kaarten de <b>Gouverneurspolder</b> — is de brede uiterwaard tussen Dodewaard en Ochten aan de zuidoever van de Waal: een nog overwegend agrarisch rivierenlandschap, maar één met een rijke ondergroei van natuur. Tussen de dijk en de rivier liggen <b>oude strangen met beplanting</b>, <b>tichelgaten</b> — kleiputten van de voormalige steenfabricage — <b>plassen met elzenbossen en bosschages</b>, en graslanden die als <b>weidevogelgebied</b> in stand worden gehouden. In de polder grazen <b>runderen</b>: rustig blijven en afstand houden. Bij de voormalige <b>veerhaven van Ochten</b> werkt de rivierpartnerschap aan herinrichting met struinpaden, zodat de uiterwaard steeds beter te beleven is; de kleiwinning in de Gouverneurspolder maakt het gebied voortdurend in beweging. Vanaf de hoge <b>Waalbandijk</b> — waaraan Ochten staat, een dorp dat in de Tweede Wereldoorlog grotendeels werd verwoest — overzie je het hele systeem: akkers, weiden, geulen, strangen en plassen, met de Waal op enkele afstand.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels), nov–mrt (watervogels op plassen en strangen)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — weidevogelgeluid boven de polder.',
 'why': ['De <b>oude strangen en tichelgaten</b> van de steentijd van de Waaloever.', '<b>Weidevogelgraslanden</b> tussen akkers en weilanden.', 'De <b>begrazing met runderen</b> die de polder open houdt.', 'Het uitzicht vanaf de <b>Waalbandijk</b> over het hele rivierenlandschap.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogels</b> in de graslanden.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> op plassen en strangen.', '<span class="months">Heel jaar</span> 🐄 <b>Runderen</b> in de uiterwaard — afstand houden.', '<span class="months">Nov–Feb</span> 🌊 <b>Hoogwater</b> op de Waal vanuit de dijk aanschouwen.'],
 'wild': ['🎵 Kievit · Grutto · Tureluur', '🌾 Zachthoutooibos langs de strangen', '🏡 Elzenbossen en bosschages bij de plassen', '🧱 Tichelgaten uit de steenfabricagetijd', '🐄 Runderen in de polder'],
 'trail': ['Wandel de <b>Waalbandijk</b> tussen Dodewaard en Ochten met afdalingen in de polder.', 'Volg de <b>graspaden en landwegen</b> langs geulen, strangen en plassen.', 'Combineer met het <b>veerhooft van Ochten</b> aan de rivier.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Runderen in het gebied — rustig blijven, afstand houden · 🚶 Ommetje ± 6 km'
}, {
 'tags': ['Gelderland · Ochten/Dodewaard (south bank of the Waal)', 'Agrarian floodplain with old river arms, clay pits and softwood forest · meadow-bird grasslands and grazing · clay-extraction area in development', 'list 36 · no. 794'],
 'loc': '📍 Between Dodewaard and Ochten on the south side of the Waal, via the Waalbandijk at Ochten · grass paths and farm lanes through the polder; cattle graze in the area',
 'desc': 'The <b>Ochtense Buitenpolder</b> — the <b>Gouverneurspolder</b> on old maps — is the broad floodplain between Dodewaard and Ochten on the Waal’s south bank: a still predominantly agrarian river landscape, but one with a rich undergrowth of nature. Between the dike and the river lie <b>old river arms with planting</b>, <b>clay pits</b> from the former brick industry, <b>lakes with alder woods and hedgerows</b>, and grasslands maintained as <b>meadow-bird habitat</b>. <b>Cattle</b> graze the polder: stay calm and keep your distance. By the former <b>ferry harbour of Ochten</b> the river partnership is redeveloping the area with wandering paths, making the floodplain ever more accessible; clay extraction in the Gouverneurspolder keeps the area in constant motion. From the high <b>Waalbandijk</b> — where Ochten stands, a village largely destroyed in the Second World War — you survey the whole system: fields, meadows, channels, old arms and lakes, with the Waal at some distance.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds), Nov–Mar (waterfowl on lakes and old arms)<br>\\n    <b>Best time of day:</b> Early morning — meadow-bird sound above the polder.',
 'why': ['The <b>old river arms and clay pits</b> of the brick era on the Waal bank.', '<b>Meadow-bird grasslands</b> between fields and pastures.', 'The <b>cattle grazing</b> that keeps the polder open.', 'The view from the <b>Waalbandijk</b> over the whole river landscape.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow birds</b> in the grasslands.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> on lakes and old arms.', '<span class="months">All year</span> 🐄 <b>Cattle</b> in the floodplain — keep your distance.', '<span class="months">Nov–Feb</span> 🌊 <b>High water</b> on the Waal, watched from the dike.'],
 'wild': ['🎵 Lapwing · Godwit · Redshank', '🌾 Softwood forest along the old arms', '🏡 Alder woods and hedgerows by the lakes', '🧱 Clay pits from the brick-making era', '🐄 Cattle in the polder'],
 'trail': ['Walk the <b>Waalbandijk</b> between Dodewaard and Ochten with descents into the polder.', 'Follow the <b>grass paths and farm lanes</b> past channels, old arms and lakes.', 'Combine with the <b>ferry head of Ochten</b> at the river.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Cattle in the area — stay calm, keep your distance · 🚶 Loop ± 6 km'
}))

C.append(mk.card(2076, 'Drutense- en Deestsewaard', {
 'tags': ['Gelderland · Druten en Deest (zuidoever van de Waal)', 'Afferdense en Deestse Waarden van Staatsbosbeheer · meestromende nevengeul van 4,5 km · struingebied met steenfabrieksverleden', 'list 36 · no. 795'],
 'loc': '📍 Parkeren bij het havenhoofd (veerdam) van Druten; toegang via wandelpaden of eigen route — struinen mag hier · rondwandeling ± 9,3 km',
 'desc': 'Tussen Druten en Deest ligt aan de zuidkant van de Waal een van de jongste natuurgebieden van de rivier: de <b>Afferdense en Deestse Waarden</b>, zoals Staatsbosbeheer ze noemt — in het boek als Drutense- en Deestsewaard. Bij de herinrichting werd een <b>meestromende nevengeul van 4,5 kilometer</b> gegraven en werden delen van de uiterwaard verlaagd: de rivier mag hier zelf haar loop weer bepalen, en bij hoogwater dient de geul als waterberging. Het resultaat is een <b>struingebied</b> — je mag de paden verlaten en je eigen route kieien — van ooibos, poelen, grasland en ruigten, met een lange <b>voetgangersbrug</b> over de geul en hoge wilgen langs de oever. In de uiterwaard grazen <b>koeien en paarden</b>. De <b>steenindustrie</b> liet haar sporen: de schoorsteen van steenfabriek Turkswaard (vroegste vestiging 1862) werd bij de herinrichting gerestaureerd, en oude fabriekspijpen en vlamoven-restanten herinneren aan de bloeitijd. Op de achtergrond denderen de schepen: de Waal is met <b>120.000 schepen per jaar</b> de drukst bevaren rivier van Nederland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (broedvogels in ooibos en ruigte), nov–mrt (watervogels, hoogwater)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de nevengeul.',
 'why': ['De <b>meestromende nevengeul van 4,5 km</b> — de rivier mag er zelf haar gang gaan.', 'Het <b>struingebied</b>: wandelen buiten de paden is hier toegestaan.', 'De <b>gerestaureerde schoorsteen van steenfabriek Turkswaard</b> (1862).', '<b>Koeien en paarden</b> in de uiterwaard, schepen op de achtergrond.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Broedvogels</b> in ooibos, poelen en ruigten.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> in de geul en op de poelen.', '<span class="months">Nov–Feb</span> 🌊 <b>Hoogwater</b> — de geul als waterberging aan het werk.', '<span class="months">Heel jaar</span> 🚢 <b>120.000 schepen per jaar</b> passerend op de Waal.'],
 'wild': ['🌊 Meestromende nevengeul', '🐎 Koeien en paarden in de uiterwaard', '🧱 Steenfabrieksverleden (Turkswaard, 1862)', '🐦 Ooibos- en riviertoezichtvogels', '🌿 Pioniersvegetatie op verlaagde delen'],
 'trail': ['Struin vanaf het <b>havenhoofd van Druten</b> je eigen route door de waarden (± 9,3 km rondje).', 'Steek de <b>voetgangersbrug</b> over de nevengeul.', 'Bekijk de <b>vlamoven-restanten</b> en de schoorsteen van Turkswaard.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Struingebied — paden kunnen wijzigen; hoogwater sluit delen af · 🚶 Rondje ± 9,3 km'
}, {
 'tags': ['Gelderland · Druten and Deest (south bank of the Waal)', 'Staatsbosbeheer Afferdense and Deestse Waarden · 4.5-km co-flowing side channel · striding area with a brickworks past', 'list 36 · no. 795'],
 'loc': '📍 Parking at the harbour head (veerdam) of Druten; access via footpaths or your own route — striding is allowed here · circular walk ± 9.3 km',
 'desc': 'Between Druten and Deest, on the Waal’s south bank, lies one of the river’s youngest nature reserves: the <b>Afferdense and Deestse Waarden</b> as Staatsbosbeheer calls them — the Drutense and Deestse waarden of the book. The redesign dug a <b>co-flowing side channel of 4.5 kilometres</b> and lowered parts of the floodplain: the river may shape its own course here again, and at high water the channel serves as water storage. The result is a <b>striding area</b> — you may leave the paths and choose your own route — of softwood forest, pools, grassland and roughs, with a long <b>footbridge</b> over the channel and tall willows along the bank. <b>Cattle and horses</b> graze the floodplain. The <b>brick industry</b> left its marks: the chimney of the Turkswaard brickworks (earliest works 1862) was restored during the redesign, and old factory pipes and flame-oven remains recall the heyday. In the background the ships thunder past: with <b>120,000 ships a year</b> the Waal is the busiest river of the Netherlands.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (breeding birds in forest and roughs), Nov–Mar (waterfowl, high water)<br>\\n    <b>Best time of day:</b> Morning — mist above the side channel.',
 'why': ['The <b>4.5-km co-flowing side channel</b> — the river runs free again.', 'The <b>striding area</b>: walking off the paths is allowed here.', 'The <b>restored chimney of the Turkswaard brickworks</b> (1862).', '<b>Cattle and horses</b> in the floodplain, ships in the background.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Breeding birds</b> in forest, pools and roughs.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> in the channel and on the pools.', '<span class="months">Nov–Feb</span> 🌊 <b>High water</b> — the channel at work as water storage.', '<span class="months">All year</span> 🚢 <b>120,000 ships a year</b> passing on the Waal.'],
 'wild': ['🌊 Co-flowing side channel', '🐎 Cattle and horses in the floodplain', '🧱 Brickworks past (Turkswaard, 1862)', '🐦 Softwood-forest and river birds', '🌿 Pioneer vegetation on lowered ground'],
 'trail': ['Stride your own route from the <b>harbour head of Druten</b> through the waarden (± 9.3 km loop).', 'Cross the <b>footbridge</b> over the side channel.', 'View the <b>flame-oven remains</b> and the Turkswaard chimney.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Striding area — paths may shift; high water closes parts · 🚶 Loop ± 9.3 km'
}, n2k='Rijntakken — Vogelrichtlijngebied nr. 38 (VR-sitecode NL2014038): de Afferdense en Deestse Waarden aan de zuid-Waaloever vallen binnen de begrenzing; de meestromende nevengeul is ingericht als voorbeeldgebied van de Rijntakken.',
 n2k_en='Rijntakken — Birds Directive site no. 38 (VR site code NL2014038): the Afferdense and Deestse Waarden on the southern Waal bank fall within the designation; the co-flowing side channel was laid out as a showcase of the Rijntakken.'))

C.append(mk.card(2077, 'Heerlijkheid Loenen', {
 'tags': ['Gelderland · Loenen bij Slijk-Ewijk (Overbetuwe, Waaloever)', 'Historisch landgoed met huis uit 1572 · monumentale Grote Allee van 1,5 km · boomgaarden, koetshuis en orangerie', 'list 36 · no. 796'],
 'loc': '📍 Grote Allee 4, Loenen (tussen Arnhem en Nijmegen aan de Waal) · landgoed vrij toegankelijk voor wandelaars; parkeergelegenheid aan de Waaldijk',
 'desc': 'Aan de noordoever van de Waal, tussen Arnhem en Nijmegen, ligt het dorpje <b>Loenen</b> — en daarachter een landgoed dat teruggaat tot <b>1572</b>: de <b>Heerlijkheid Loenen</b>. De ruggengraat van het goed is de <b>Grote Allee</b>, een monumentale laan van <b>anderhalve kilometer</b> waarop tal van kortere lanen haaks uitkomen; aan de laan staat het <b>Huis te Loenen</b>, een betrekkelijk eenvoudig rechthoekig gebouw met een torentje aan de entreezijde, met koetshuis en orangerie. Om het huis liggen het parkbos met oude eiken, de <b>boomgaarden</b> die zo typisch zijn voor de Betuwe, en graslanden die afwisselen met houtwallen en singels; in de buurt ligt het meertje de <b>Duivelswaai</b>, dat de ligging van een oude Waaloog illustreert. Buitendijks hoort de <b>Loenense Buitenpolder</b> bij het goed (kaart 2082). Het landgoed is particulier bezit, maar de lanen en paden — het meest bescheiden eerbetoon aan de Gelderse buitenplaatsencultuur — mogen vrij worden bewandeld — met de kerk van Loenen en de windmolens van de omgeving als secundaire coulissen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (boomgaardbloesem), sep–okt (herfstkleur op de Grote Allee)<br>\\n    <b>Beste tijd van de dag:</b> Vroege avond — lang licht over de lanen.',
 'why': ['De <b>Grote Allee</b>: 1,5 km monumentale laan als ruggengraat van het goed.', 'Het <b>Huis te Loenen</b> (1572) met koetshuis en orangerie.', 'De <b>Betuwe-boomgaarden</b> rondom het parkbos.', 'Het meertje <b>Duivelswaai</b> en de vrij toegankelijke lanen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Boomgaardbloesem</b> in de Betuwe-percelen.', '<span class="months">Jun–Jul</span> 🌾 <b>Hooiland en graslanden</b> om het goed.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> over de Grote Allee.', '<span class="months">Nov–Feb</span> 🪿 <b>Watervogels</b> op de Duivelswaai en de Waal.'],
 'wild': ['🌸 Boomgaarden en oude eiken', '🏰 Huis te Loenen met torentje', '🏡 Koetshuis en orangerie', '💧 Duivelswaai-meertje', '🦉 Bosvogels in parkbos en singels'],
 'trail': ['Wandel de <b>Grote Allee</b> van begin tot eind en de haakse lanen eromheen.', 'Bezoek de <b>kerk van Loenen</b> en het oude dorp.', 'Combineer met de <b>Loenense Buitenpolder</b> buitendijks (kaart 2082).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis toegankelijk · 🚫 Respecteer privé-gebieden rond huis en hoeves · 🚶 Lanenwandeling ± 5 km'
}, {
 'tags': ['Gelderland · Loenen near Slijk-Ewijk (Overbetuwe, Waal bank)', 'Historic estate with a house from 1572 · monumental 1.5-km Grote Allee · orchards, coach house and orangery', 'list 36 · no. 796'],
 'loc': '📍 Grote Allee 4, Loenen (between Arnhem and Nijmegen on the Waal) · estate freely accessible to walkers; parking on the Waal dike',
 'desc': 'On the north-east bank of the Waal, between Arnhem and Nijmegen, lies the hamlet of <b>Loenen</b> — and behind it an estate reaching back to <b>1572</b>: the <b>Heerlijkheid Loenen</b>. The backbone of the estate is the <b>Grote Allee</b>, a monumental avenue of <b>one and a half kilometres</b> onto which many shorter lanes open at right angles; on the avenue stands <b>Huis te Loenen</b>, a fairly simple rectangular building with a tower on the entrance side, with coach house and orangery. Around the house lie the park woodland with old oaks, the <b>orchards</b> so typical of the Betuwe, and grasslands alternating with hedgerows; nearby lies the little lake <b>Duivelswaai</b>, illustrating the position of an old Waal eye. Outside the dike the <b>Loenense Buitenpolder</b> belongs to the estate (card 2082). The estate is privately owned but its lanes and paths are the land’s most modest tribute to the Gelderland country-house culture, and may be walked freely — with the church of Loenen and the windmills of the surroundings as secondary coulisses.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (orchard blossom), Sep–Oct (autumn colour on the Grote Allee)<br>\\n    <b>Best time of day:</b> Early evening — long light over the avenues.',
 'why': ['The <b>Grote Allee</b>: a 1.5-km monumental avenue as the estate’s backbone.', '<b>Huis te Loenen</b> (1572) with coach house and orangery.', 'The <b>Betuwe orchards</b> around the park woodland.', 'The <b>Duivelswaai</b> lake and the freely walkable lanes.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Orchard blossom</b> in the Betuwe fields.', '<span class="months">Jun–Jul</span> 🌾 <b>Hay meadows and grasslands</b> around the estate.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> over the Grote Allee.', '<span class="months">Nov–Feb</span> 🪿 <b>Waterfowl</b> on the Duivelswaai and the Waal.'],
 'wild': ['🌸 Orchards and old oaks', '🏰 Huis te Loenen with its tower', '🏡 Coach house and orangery', '💧 Duivelswaai lake', '🦉 Woodland birds in park and hedgerows'],
 'trail': ['Walk the <b>Grote Allee</b> from end to end and the perpendicular lanes around it.', 'Visit the <b>church of Loenen</b> and the old hamlet.', 'Combine with the <b>Loenense Buitenpolder</b> outside the dike (card 2082).'],
 'foot': '🐕 Dogs on lead · 💶 Free access · 🚫 Respect private grounds around house and farms · 🚶 Avenue walk ± 5 km'
}))

C.append(mk.card(2078, 'Ewijkse Plaat', {
 'tags': ['Gelderland · Ewijk (zuidoever van de Waal, bij de Ewijkse brug)', 'Voormalig zandeiland als laboratorium van nieuwe natuur · vrij rondlopende paarden en runderen · cyclische verjonging sinds 2011', 'list 36 · no. 797'],
 'loc': '📍 Parkeren nabij Ingenieur van Stuivenbergweg 2, Ewijk; toegang via de zuidelijke Waaldijk · IVN-route 6 km; let op: bij waterstand &gt; 7,50 m +NAP bij haven Nijmegen lopen delen onder',
 'desc': 'De <b>Ewijkse Plaat</b> is een langwerpig schiereiland aan de zuidoever van de Waal bij de <b>Ewijkse brug</b> — en tegelijk een van de beroemdste proeftuins van het Nederlandse rivierennatuur. Als voormalig <b>zandeiland</b> werd de plaat in <b>1989</b> door Rijkswaterstaat voor het laatst afgegraven, en wat overbleef was een kale zandvlakte: de ideale <b>nulsituatie</b> om natuurontwikkeling te volgen. Sindsdien lopen er <b>paarden en runderen vrij rond</b>, die aan gras én bomen knabbelen en zo een afwisselend mozaïek van dichte bosjes, ruigten en graslandjes hebben gecreëerd. De Waal gebruikt de plaat als <b>zandbak</b>: bij ieder hoogwater wordt zand en slib afgezet, waardoor de geomorfologie voortdurend verandert en er steeds nieuwe groeiplaatsen voor <b>pionierplanten</b> ontstaan. Sinds 2011 passen ARK en Rijkswaterstaat hier <b>cyclische verjonging</b> toe — hoge begroeiing wordt om de zoveel tijd teruggedrongen zodat hoogwater beter doorstroomt en de biodiversiteit wordt gestimuleerd. Een deel van het gebied mag met hond (aangelijnd), een ander deel is voor honden verboden; neem de borden van Staatsbosbeheer goed door.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Sep</b> (pioniers, rivierflora, grazers), nov–mrt (watervogels, hoogwater)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — leeg strand, schepen in de mist.',
 'why': ['Het <b>laboratorium van nieuwe natuur</b>: nulsituatie sinds de zandwinning van 1989.', '<b>Paarden en runderen</b> die vrij rondlopen tussen bosjes en ruigten.', 'De <b>Waal als zandbak</b>: jaarlijks nieuw zand, nieuwe pioniers.', '<b>Cyclische verjonging</b> sinds 2011 — de rivier blijft de baas.'],
 'phen': ['<span class="months">Mei–Sep</span> 🌿 <b>Pionierplanten</b> op vers rivierzand.', '<span class="months">Apr–Jun</span> 🎵 <b>Broedvogels</b> in bosjes en ruigten.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> op de ondieptes.', '<span class="months">Nov–Feb</span> 🌊 <b>Hoogwater</b> dat zand en slib afzet.'],
 'wild': ['🐎 Vrij rondlopende paarden en runderen', '🌿 Pioniers van het rivierstrand', '🐦 Ooibos- en ruigtevogels', '🏖️ Rivierstrand en kribben', '🌊 Dynamiek van zand en slib'],
 'trail': ['Loop de <b>IVN-route Ewijkse Plaat</b> (6 km) vanaf de Van Stuivenbergweg.', 'Struin over het <b>Waalstrand</b> en de verjongde oevers.', 'Combineer met de <b>Beuningse uiterwaarden</b> (Staartjeswaard, kaart 2080).'],
 'foot': '🐕 Honden aangelijnd; deel van het gebied verboden voor honden · ⚠️ Bij waterstand &gt; 7,50 m +NAP (haven Nijmegen) overstroomd; grote grazers — afstand houden · 🚶 Route 6 km'
}, {
 'tags': ['Gelderland · Ewijk (south bank of the Waal, by the Ewijk bridge)', 'Former sand island as a laboratory of new nature · freely roaming horses and cattle · cyclical rejuvenation since 2011', 'list 36 · no. 797'],
 'loc': '📍 Parking near Ingenieur van Stuivenbergweg 2, Ewijk; access via the southern Waal dike · IVN route 6 km; note: at water levels &gt; 7.50 m +NAP at Nijmegen harbour parts flood',
 'desc': 'The <b>Ewijkse Plaat</b> is a long peninsula on the south bank of the Waal by the <b>Ewijk bridge</b> — and at the same time one of the most famous testing grounds of Dutch river nature. A former <b>sand island</b>, the plate was last dredged by Rijkswaterstaat in <b>1989</b>, leaving a bare expanse of sand: the ideal <b>zero situation</b> for following nature development. Since then <b>horses and cattle have roamed freely</b>, nibbling at grass and trees alike and creating a varied mosaic of dense thickets, roughs and grassy patches. The Waal uses the plate as a <b>sand box</b>: every high water deposits sand and silt, so the landforms change constantly and new growing places for <b>pioneer plants</b> keep appearing. Since 2011 ARK and Rijkswaterstaat have applied <b>cyclical rejuvenation</b> here — tall vegetation is cut back every few years so that high water flows through better and biodiversity is stimulated. Part of the area admits dogs (on lead), another part forbids them; read the Staatsbosbeheer signs carefully.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (pioneers, river flora, grazers), Nov–Mar (waterfowl, high water)<br>\\n    <b>Best time of day:</b> Morning — empty beach, ships in the mist.',
 'why': ['The <b>laboratory of new nature</b>: a zero situation since the 1989 sand extraction.', '<b>Horses and cattle</b> roaming freely among thickets and roughs.', 'The <b>Waal as a sand box</b>: fresh sand and fresh pioneers every year.', '<b>Cyclical rejuvenation</b> since 2011 — the river stays in charge.'],
 'phen': ['<span class="months">May–Sep</span> 🌿 <b>Pioneer plants</b> on fresh river sand.', '<span class="months">Apr–Jun</span> 🎵 <b>Breeding birds</b> in thickets and roughs.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> on the shallows.', '<span class="months">Nov–Feb</span> 🌊 <b>High water</b> depositing sand and silt.'],
 'wild': ['🐎 Freely roaming horses and cattle', '🌿 Pioneers of the river beach', '🐦 Softwood-forest and rough birds', '🏖️ River beach and groynes', '🌊 Dynamics of sand and silt'],
 'trail': ['Walk the <b>IVN route Ewijkse Plaat</b> (6 km) from the Van Stuivenbergweg.', 'Stride over the <b>Waal beach</b> and the rejuvenated banks.', 'Combine with the <b>Beuningen floodplains</b> (Staartjeswaard, card 2080).'],
 'foot': '🐕 Dogs on lead; part of the area forbidden for dogs · ⚠️ Floods at water levels &gt; 7.50 m +NAP (Nijmegen harbour); large grazers — keep your distance · 🚶 Route 6 km'
}, n2k='Rijntakken — Vogelrichtlijngebied nr. 38 (VR-sitecode NL2014038): de Ewijkse Plaat is onderdeel van de Beuningse uiterwaarden binnen de Rijntakken-begrenzing; de cyclische verjonging is afgestemd op doorstroming en riviernatuur.',
 n2k_en='Rijntakken — Birds Directive site no. 38 (VR site code NL2014038): the Ewijkse Plaat is part of the Beuningen floodplains within the Rijntakken designation; the cyclical rejuvenation is tuned to flow-through and river nature.'))

C.append(mk.card(2079, 'Doddendaal', {
 'tags': ['Gelderland · Ewijk (binnendijks, achter de Waaldijk)', 'Slot Doddendael met witgepleisterd hoofdgebouw in de bossen · landgoedbos met het Roodslag · contrast tussen binnendijks bos en uiterwaardooibos', 'list 36 · no. 798'],
 'loc': '📍 P-terrein bij Slot Doddendael, Binnenweg 2, Ewijk · wandelroute 5,9 km (rood-geel gemarkeerd) door bos, over de dijk en 2 km struinen langs de Waal',
 'desc': 'Half verscholen in de bossen achter de Waaldijk van Ewijk staat <b>Slot Doddendael</b>: een kasteel waarvan het <b>witgepleisterde hoofdgebouw</b> het silhouet bepaalt, omringd door een landgoedbos dat sinds de naoorlogse jaren grotendeels door <b>Staatsbosbeheer</b> wordt beheerd. De naam gaat vrijwel zeker terug op de <b>lisdodden</b> die in de drassige omgeving ruim groeiden. De geschiedenis van het goed is bewogen: na de Tweede Wereldoorlog werd het als Duits bezit <b>verbeurd verklaard</b> en kwam het tijdelijk aan de rentmeester; pas in <b>1956</b> kreeg de familie Von Nagel-Doornick het slot terug — maar het grootste deel van het terrein ging naar Staatsbosbeheer. Dat maakt Doddendaal tot een mooi dualisme: het particuliere kasteel met zijn laantjes, en daaromheen het openbare landgoedbos, waarin het bos <b>’t Roodslag</b> en de uiterwaarden van de Ewijkse Plaat (kaart 2078) vlak tegen elkaar aan liggen. Excursiegidsen gebruiken het goed precies daarom: hier zie je in één middag het verschil tussen een <b>bos achter de dijk</b> en een <b>ooibos in de uiterwaard</b>.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (vloer van anemonen), sep–okt (paddenstoelen, herfstlicht in ’t Roodslag)<br>\\n    <b>Beste tijd van de dag:</b> Middag — zon tussen de stammen van de lanen.',
 'why': ['<b>Slot Doddendael</b> — wit, half verscholen, met de lisdodden in de naam.', 'De <b>naoorlogse restitutiegeschiedenis</b> (verbeurd verklaard, 1956 teruggegeven).', 'Het landgoedbos <b>’t Roodslag</b> tegen de uiterwaard aan.', 'Het <b>contrast</b> tussen binnendijks bos en ooibos in één wandeling.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌼 <b>Bosanemonen</b> in de ondergroei.', '<span class="months">Jun–Jul</span> 🦉 <b>Bosvogels</b> in de lanen van het goed.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in ’t Roodslag.', '<span class="months">Nov–Feb</span> ❄️ <b>Kale lanen</b> en zicht op het slot.'],
 'wild': ['🏰 Slot Doddendael', '🌳 Landgoedbos ’t Roodslag', '🐦 Holenbroeders in oude lanen', '🌊 Blik op de Waal-uiterwaarden', '🦌 Reeën tussen bos en wei'],
 'trail': ['Loop de <b>wandelroute Doddendaal</b> (5,9 km, rood-geel) vanaf het P-terrein van het slot.', 'Struin de <b>2 km langs de Waal</b> aan het eind van de route.', 'Combineer met de <b>Ewijkse Plaat</b> (kaart 2078) voor het ooibos-contrast.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ 2 km rul zand — stevig schoeisel; privéterrein rond het slot respecteren · 🚶 Route 5,9 km'
}, {
 'tags': ['Gelderland · Ewijk (inland, behind the Waal dike)', 'Doddendael Castle with white-plastered main house in the woods · estate woodland with ’t Roodslag · contrast between inland forest and floodplain softwood forest', 'list 36 · no. 798'],
 'loc': '📍 Car park at Doddendael Castle, Binnenweg 2, Ewijk · walking route 5.9 km (marked red-yellow) through woodland, over the dike and 2 km striding along the Waal',
 'desc': 'Half hidden in the woods behind the Waal dike of Ewijk stands <b>Doddendael Castle</b>: a country house whose <b>white-plastered main building</b> sets the silhouette, surrounded by estate woodland managed largely by <b>Staatsbosbeheer</b> since the post-war years. The name almost certainly goes back to the <b>reed mace</b> that grew abundantly in the marshy surroundings. The estate’s history was turbulent: after the Second World War it was <b>confiscated</b> as German property and temporarily given to the steward; only in <b>1956</b> did the Von Nagel-Doornick family get the castle back — but most of the terrain went to Staatsbosbeheer. That makes Doddendaal a fine duality: the private castle with its lanes, and around it the public estate woodland, in which the wood <b>’t Roodslag</b> and the floodplains of the Ewijkse Plaat (card 2078) lie right against each other. Field guides use the estate precisely for that: here you see in one afternoon the difference between a <b>forest behind the dike</b> and a <b>softwood forest in the floodplain</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (carpet of anemones), Sep–Oct (fungi, autumn light in ’t Roodslag)<br>\\n    <b>Best time of day:</b> Midday — sun between the trunks of the avenues.',
 'why': ['<b>Doddendael Castle</b> — white, half hidden, with reed mace in its name.', 'The <b>post-war restitution history</b> (confiscated, returned in 1956).', 'The estate wood <b>’t Roodslag</b> against the floodplain.', 'The <b>contrast</b> between inland forest and softwood forest in one walk.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Wood anemones</b> in the undergrowth.', '<span class="months">Jun–Jul</span> 🦉 <b>Woodland birds</b> in the estate lanes.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in ’t Roodslag.', '<span class="months">Nov–Feb</span> ❄️ <b>Bare avenues</b> and views of the castle.'],
 'wild': ['🏰 Doddendael Castle', '🌳 ’t Roodslag estate wood', '🐦 Hole-nesters in old avenues', '🌊 Views over the Waal floodplains', '🦌 Roe deer between wood and meadow'],
 'trail': ['Walk the <b>Doddendaal route</b> (5.9 km, red-yellow) from the castle car park.', 'Stride the <b>2 km along the Waal</b> at the end of the route.', 'Combine with the <b>Ewijkse Plaat</b> (card 2078) for the softwood contrast.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ 2 km of soft sand — sturdy footwear; respect private ground around the castle · 🚶 Route 5.9 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2079)
mk.check()
