# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2110, 'Vennebulten', {
 'tags': ['Gelderland · Heelweg (gemeente Oude IJsselstreek)', '± 40 ha vennen en jeneverbesheuvels op de Halserug · uitkijktoren over heide · stichting De Vennemarke herstelt de heide', 'list 36 · no. 829'],
 'loc': '📍 Heelweg, 3 km ten noordoosten van Varsseveld — parkeren langs de weg bij de ingang · wandelrondes over bulten en vennen; uitkijktoren in het gebied',
 'desc': 'De <b>Vennebulten</b> bij Heelweg zijn het ongerepte hart van de <b>Halserug</b>: een ± <b>40 hectare</b> groot gebied van <b>vennen met heuvels</b>, begroeid met <b>jeneverbes, heide, grove den, inlandse eik en berk</b>. De structuur ontstond in de <b>laatste ijstijd</b>, toen dekzanden tot een langgerekte rug tussen Aalten en Zelhem werden opgestoven; na de markeverdelingen van de 19e eeuw werden grote stukken ontgonnen tot bouwland, en tot 1945 hield schaapherder Hendrik Wisselink met zijn kudde de heide nog in stand; daarna groeide het gebied snel dicht met bos. Eerder eigendom van de gemeente Wisch, die er bomen plantte; tegenwoordig zet <b>stichting De Vennemarke</b> zich in om juist de <b>heide in stand te houden en uit te breiden</b>. Door het gebied loopt een oude <b>Hessenweg</b>, hier <b>Romienendiek</b> geheten. Vroeger was dit het domein van <b>struikrovers</b>; nu van de <b>nachtegaal en de wielewaal</b>, de grauwe klauwier en de geelgors — te overzien vanaf de moderne <b>uitkijktoren</b> die boven de heide staat. Wie de ongerepte tegenhanger van de productiebossen rond Varsseveld zoekt, is hier op de juiste plek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jul</b> (nachtegaal, wielewaal, heidebloei begin), aug–sep (heide paars)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — nachtegaalzang vanaf de toren.',
 'why': ['De <b>jeneverbesheuvels en vennen</b> op de Halserug.', 'De <b>uitkijktoren</b> boven heide en ven.', '<b>Nachtegaal, wielewaal en grauwe klauwier</b> als broedvogels.', 'De <b>Romienendiek</b> — een oude Hessenweg door het gebied.'],
 'phen': ['<span class="months">Mei–Jul</span> 🎵 <b>Nachtegaal en wielewaal</b> in zang.', '<span class="months">Aug–Sep</span> 🌸 <b>Paarse heide</b> om de vennen.', '<span class="months">Apr–Okt</span> 🥾 <b>Wandelen</b> over bulten en vennen.', '<span class="months">Heel jaar</span> 🌲 <b>Jeneverbesstruiken</b> op de bulten.'],
 'wild': ['🎵 Nachtegaal · wielewaal · grauwe klauwier', '🌲 Jeneverbes op de bulten', '💧 Vennen van de Halserug', '🗼 Uitkijktoren over de heide', '🗺️ Hessenweg Romienendiek'],
 'trail': ['Beklim de <b>uitkijktoren</b> bij de ingang voor het overzicht.', 'Wandel de <b>vennen-rondes</b> vanaf Heelweg (± 4–6 km).', 'Combineer met het <b>Aaltense Goor</b> (kaart 2111) voor vogels en coulissen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes 4–6 km'
}, {
 'tags': ['Gelderland · Heelweg (Oude IJsselstreek municipality)', '± 40 ha of pools and juniper hills on the Halserug · watchtower over the heath · De Vennemarke foundation restoring the heath', 'list 36 · no. 829'],
 'loc': '📍 Heelweg, 3 km north-east of Varsseveld — parking along the road at the entrance · walking loops over hills and pools; watchtower in the area',
 'desc': 'The <b>Vennebulten</b> at Heelweg are the pristine heart of the <b>Halserug</b>: a ± <b>40-hectare</b> area of <b>pools with hills</b> covered in <b>juniper, heather, Scots pine, native oak and birch</b>. The structure arose in the <b>last ice age</b>, when cover sands blew up into a long ridge running from Aalten towards Zelhem. Large parts were reclaimed after the 19th-century mark divisions, and until 1945 shepherd Hendrik Wisselink kept the heath alive with his flock; after that the area quickly grew shut with wood. Once owned by the municipality of Wisch, which planted trees; today the <b>De Vennemarke foundation</b> works to keep and extend precisely the <b>heath</b>. Through the area runs an old <b>Hessian road</b>, here called the <b>Romienendiek</b>. Formerly the domain of <b>footpads</b>; now of the <b>nightingale and golden oriole</b>, the red-backed shrike and the yellowhammer — all surveyed from the modern <b>watchtower</b> standing above the heath. For the untouched counterpart of the production woods around Varsseveld, this is the place.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (nightingale, oriole, heath flowering), Aug–Sep (purple heath)<br>\\n    <b>Best time of day:</b> Early morning — nightingale song from the tower.',
 'why': ['The <b>juniper hills and pools</b> of the Halserug.', 'The <b>watchtower</b> above heath and pool.', '<b>Nightingale, golden oriole and red-backed shrike</b> as breeders.', 'The <b>Romienendiek</b> — an old Hessian road through the area.'],
 'phen': ['<span class="months">May–Jul</span> 🎵 <b>Nightingale and golden oriole</b> in song.', '<span class="months">Aug–Sep</span> 🌸 <b>Purple heath</b> around the pools.', '<span class="months">Apr–Oct</span> 🥾 <b>Walking</b> over hills and pools.', '<span class="months">All year</span> 🌲 <b>Juniper bushes</b> on the hills.'],
 'wild': ['🎵 Nightingale · golden oriole · red-backed shrike', '🌲 Juniper on the hills', '💧 Pools of the Halserug', '🗼 Watchtower over the heath', '🗺️ Romienendiek Hessian road'],
 'trail': ['Climb the <b>watchtower</b> at the entrance for the overview.', 'Walk the <b>pool loops</b> from Heelweg (± 4–6 km).', 'Combine with the <b>Aaltense Goor</b> (card 2111) for birds and hedgerows.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops 4–6 km'
}))

C.append(mk.card(2111, 'Aaltense Goor', {
 'tags': ['Gelderland · Aalten (ten noordwesten van het dorp)', '± 200 ha coulissenlandschap: vanaf de 18e eeuw ontgonnen goor-gronden · elzen langs sloten, rechte paden · in 2021 zelfs een flamingo', 'list 36 · no. 830'],
 'loc': '📍 3 km ten noordwesten van Aalten, grenzend aan de Vennebulten (kaart 2110) · TOP Het Noorden nabij; rechte lanen en voetpaden, fiets- en wandelnetwerk',
 'desc': 'Het <b>Aaltense Goor</b> is het grote, stille zusje van de Vennebulten: ± <b>200 hectare</b> coulissenlandschap ten noordwesten van Aalten, ontstaan doordat de <b>moerassige goor-gronden</b> — goor betekent zompig — <b>vanaf de 18e eeuw</b> werden ontgonnen tot grasland. Het resultaat is een karakteristiek <b>coulissenlandschap</b>: lange rechte paden, percelen grasland omzoomd door <b>singels en elzen langs de slootkanten</b>, met daartussen houtwallen en poelen. Juist die afwisseling maakt het gebied rijk aan <b>broedvogels</b> — zangers van singel, sloot en hooiland — en in 2021 werd zelfs een <b>flamingo</b> gespot — als gast uit het zuiden, maar toch. Samen met de Vennebulten vormt het Goor het groene dak boven Aalten: heide en jeneverbes hier, hooiland en elzensingels daar, en overal de lange lijnen van een oud ontginningslandschap dat zijn rust heeft bewaard.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (zang van broedvogels), apr–mei (vol voorjaar), sep–okt (morgennevel over de singels)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — zang uit elke singel.',
 'why': ['Het <b>coulissenlandschap</b> van de 18e-eeuwse goor-ontginning.', '<b>Elzensingels langs de sloten</b> en rechte lanen.', 'De <b>vogelrijkdom</b> van zangvogels in singel en sloot.', 'De <b>flamingo van 2021</b> als beroemdste gast.'],
 'phen': ['<span class="months">Mei–Jun</span> 🎵 <b>Volle zang</b> van broedvogels.', '<span class="months">Apr–Mei</span> 🐦 <b>Voorjaar in de singels</b> — alles zingt.', '<span class="months">Jun–Jul</span> 🌾 <b>Hooilandbeheer</b> — bloemrijke percelen.', '<span class="months">Sep–Okt</span> 🌫️ <b>Morgennevel</b> over het ontginningsland.'],
 'wild': ['🎵 Broedvogels van singel en sloot', '🌳 Elzensingels langs sloten', '🌾 Coulissen van grasland en houtwal', '🦩 Flamingo-gast in 2021', '🥾 TOP Het Noorden nabij'],
 'trail': ['Wandel de <b>rechte lanen</b> van het Goor vanaf Aalten of de Vennebulten.', 'Volg het <b>wandelnetwerk</b> door het coulissenlandschap.', 'Combineer met de <b>Vennebulten</b> (kaart 2110) voor heide en toren.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Agrarisch gebied — paden volgen · 🚶 Rondes 5–8 km'
}, {
 'tags': ['Gelderland · Aalten (north-west of the village)', '± 200-ha hedgerow landscape: goor marshlands reclaimed from the 18th century · alders along ditches, straight lanes · even a flamingo in 2021', 'list 36 · no. 830'],
 'loc': '📍 3 km north-west of Aalten, bordering the Vennebulten (card 2110) · TOP Het Noorden nearby; straight lanes and footpaths, cycle and walking network',
 'desc': 'The <b>Aaltense Goor</b> is the great, quiet sister of the Vennebulten: ± <b>200 hectares</b> of hedgerow landscape north-west of Aalten, arising from the reclamation of the <b>marshy goor soils</b> — goor means spongy — <b>from the 18th century</b> onwards, turned into grassland. The result is a characteristic <b>bocage landscape</b>: long straight lanes, parcels of grassland fringed by <b>singels and alders along the ditches</b>, with hedgerows and ponds in between. Precisely that variety makes the area rich in <b>breeding birds</b> — songsters of hedge, ditch and hay meadow — and in 2021 even a <b>flamingo</b> was spotted — a guest from the south, but still. Together with the Vennebulten the Goor forms the green roof over Aalten: heath and juniper here, hay meadow and alder hedge there, and everywhere the long lines of an old reclamation landscape that kept its peace.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (breeding-bird song), Apr–May (full spring), Sep–Oct (morning mist over the hedges)<br>\\n    <b>Best time of day:</b> Early morning — song from every hedge.',
 'why': ['The <b>hedgerow landscape</b> of the 18th-century goor reclamation.', '<b>Alder hedges along the ditches</b> and straight lanes.', 'The <b>bird richness</b> of songsters in hedge and ditch.', 'The <b>2021 flamingo</b> as most famous guest.'],
 'phen': ['<span class="months">May–Jun</span> 🎵 <b>Full song</b> of breeding birds.', '<span class="months">Apr–May</span> 🐦 <b>Spring in the hedges</b> — everything sings.', '<span class="months">Jun–Jul</span> 🌾 <b>Hay management</b> — flowery fields.', '<span class="months">Sep–Oct</span> 🌫️ <b>Morning mist</b> over the reclaimed land.'],
 'wild': ['🎵 Breeding birds of hedge and ditch', '🌳 Alder hedges along ditches', '🌾 Hedgerows of grassland and timber belt', '🦩 Flamingo guest in 2021', '🥾 TOP Het Noorden nearby'],
 'trail': ['Walk the <b>straight lanes</b> of the Goor from Aalten or the Vennebulten.', 'Follow the <b>walking network</b> through the hedgerow landscape.', 'Combine with the <b>Vennebulten</b> (card 2110) for heath and tower.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Agricultural land — follow the paths · 🚶 Loops 5–8 km'
}))

C.append(mk.card(2112, 'Eppink', {
 'tags': ['Gelderland · Aalten (aan de Romienendiek)', 'Klein NSW-landgoed van 8 ha: bos, weiland en hoogstamboomgaard · eeuwenoude eiken en beuken · kruidentuin, knechtenhuusken en pauwen', 'list 36 · no. 831'],
 'loc': '📍 Romienendiek, Aalten — landgoed vrij toegankelijk (NSW-openstelling); parkeren langs de dijk · scholieren van Staring Educatie op het erf in oktober',
 'desc': 'Aan de <b>Romienendiek</b> — dezelfde oude Hessenweg die ook door de Vennebulten loopt — ligt <b>landgoed Eppink</b>: klein maar o zo fraai, <b>8 hectare</b> bos, weiland en hooggelegen bouwland, met in het aangrenzende bos <b>eeuwenoude eiken en beuken</b>. Als <b>Natuurschoonwet-landgoed</b> staat Eppink opengesteld voor wandelaars, en het leven er is nog echt levend: op het erf staan de <b>hoogstamboomgaard</b>, de <b>moestuin en kruidentuin</b>, het <b>knechtenhuusken</b> waar de knechten van weleer woonden, het <b>vogelbosje</b>, de <b>Belgische trekpaarden</b> en de <b>pauwen</b> die hun veren aan de bezoekers nalaten. Elk najaar ontvangt de familie Mateman met Staring Educatie de <b>schoolklassen</b> voor lessen in boomgaard, kruiden en boerenerf. Voor de wandelaar is Eppink een ommetje van het mooiste soort: lanen, oude bomen, en de Romienendiek die je mee terug neemt naar de tijd van de Hessen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (boomgaardbloesem), mei–jun (kruidentuin), okt (appelpluktijd, oogst op het erf)<br>\\n    <b>Beste tijd van de dag:</b> Middag — het erf en de boomgaard in de zon.',
 'why': ['De <b>hoogstamboomgaard</b> met appelpluktijd in oktober.', '<b>Eeuwenoude eiken en beuken</b> in het aangrenzende bos.', 'Het <b>knechtenhuusken</b> en de kruidentuin van het erf.', 'De <b>Romienendiek</b> als oude Hessenweg waarop het goed ligt.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Boomgaardbloesem</b> op het erf.', '<span class="months">Mei–Jun</span> 🌿 <b>Kruidentuin</b> op haar top.', '<span class="months">Okt</span> 🍎 <b>Appelpluktijd</b> en schoolklassen op het erf.', '<span class="months">Heel jaar</span> 🦚 <b>Pauwen</b> tussen de oude bomen.'],
 'wild': ['🍎 Hoogstamboomgaard', '🌳 Eeuwenoude eiken en beuken', '🌿 Kruidentuin en moestuin', '🏡 Knechtenhuusken', '🦚 Pauwen en Belgische trekpaarden'],
 'trail': ['Wandel het <b>ommetje over het goed</b> langs lanen, boomgaard en bos.', 'Volg daarna de <b>Romienendiek</b> naar de Vennebulten (kaart 2110).', 'Kom in oktober voor de <b>oogst op het erf</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (NSW-openstelling) · ⚠️ Erf en tuinen privé — paden volgen · 🚶 Ommetje ± 2–3 km'
}, {
 'tags': ['Gelderland · Aalten (on the Romienendiek)', 'Small 8-ha Nature Beauty Act estate: wood, meadow and standard orchard · centuries-old oaks and beeches · herb garden, servants’ cottage and peacocks', 'list 36 · no. 831'],
 'loc': '📍 Romienendiek, Aalten — estate open to walkers (Nature Beauty Act); parking along the dike · schoolchildren of Staring Educatie on the yard in October',
 'desc': 'On the <b>Romienendiek</b> — the same old Hessian road that also runs through the Vennebulten — lies <b>Eppink estate</b>: small but oh so fine, <b>8 hectares</b> of wood, meadow and high arable land, with <b>centuries-old oaks and beeches</b> in the adjoining wood. As a <b>Nature Beauty Act estate</b> Eppink is open to walkers, and life here is still genuinely alive: on the yard stand the <b>standard orchard</b>, the <b>vegetable and herb gardens</b>, the <b>servants’ cottage</b> where the farmhands of old lived, the <b>little bird wood</b>, the <b>Belgian draft horses</b> and the <b>peacocks</b> that leave their feathers to visitors. Every autumn the Mateman family welcomes, with Staring Educatie, <b>school classes</b> for lessons in orchard, herbs and farmyard. For the walker Eppink is a walk of the finest kind: avenues, old trees, and the Romienendiek carrying you back to the age of the Hessians.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (orchard blossom), May–Jun (herb garden), Oct (apple picking, harvest on the yard)<br>\\n    <b>Best time of day:</b> Midday — the yard and orchard in the sun.',
 'why': ['The <b>standard orchard</b> with apple-picking time in October.', '<b>Centuries-old oaks and beeches</b> in the adjoining wood.', 'The <b>servants’ cottage</b> and the herb garden of the yard.', 'The <b>Romienendiek</b> as the old Hessian road the estate lies on.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Orchard blossom</b> on the yard.', '<span class="months">May–Jun</span> 🌿 <b>Herb garden</b> at its peak.', '<span class="months">Oct</span> 🍎 <b>Apple picking</b> and school classes on the yard.', '<span class="months">All year</span> 🦚 <b>Peacocks</b> among the old trees.'],
 'wild': ['🍎 Standard orchard', '🌳 Centuries-old oaks and beeches', '🌿 Herb and vegetable garden', '🏡 Servants’ cottage', '🦚 Peacocks and Belgian draft horses'],
 'trail': ['Walk the <b>little loop over the estate</b> past avenues, orchard and wood.', 'Then follow the <b>Romienendiek</b> to the Vennebulten (card 2110).', 'Come in October for the <b>harvest on the yard</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free (Nature Beauty Act opening) · ⚠️ Yard and gardens private — follow the paths · 🚶 Loop ± 2–3 km'
}))

C.append(mk.card(2113, 'Loohuis', {
 'tags': ['Gelderland · Aalten (ten oosten van het dorp)', 'Natuurmonumenten-bos van 21 ha uit 1927 · twee bosplassen, rosse vleermuis · Ringkampsbulten (41 m) als hoogste punt van Aalten', 'list 36 · no. 832'],
 'loc': '📍 Haartseweg, Aalten — parkeerplaats Haartseweg; ± 15 minuten fietsen vanaf station Aalten · paden door bos, ven en grasland met houtwallen (hoofdpad kan tijdelijk afgesloten zijn i.v.m. Vitens-werk)',
 'desc': 'Ten oosten van Aalten ligt <b>Loohuis</b> van Natuurmonumenten: een aantrekkelijk bos van <b>21 hectare</b>, aangelegd in <b>1927</b> en ingeklemd tussen de Loohuisweg en de Haartseweg. Het is een bos van het bescheiden soort: <b>laag hout</b> in een enigszins heuvelachtig terrein, met meer dan honderd jaar oude <b>grove dennen</b>, grote <b>mierenhopen</b>, en <b>twee bosplassen</b> — waarvan de ene door verdroging is dichtgegroeid met berk en eenjarig wollegras, maar de andere nog water houdt en de <b>groene kikker</b> herbergt. In het bos zoeken <b>vogels en zoogdieren</b> voedsel en dekking in het verder open agrarische landschap — een groene oase tussen de akkers; de <b>rosse vleermuis</b> foerageert boven de paden, en <b>boomklever, grote bonte en groene specht</b> zijn de vaste vogels. Verderop, in de buurtschap De Haart, liggen de <b>Ringkampsbulten</b>, met <b>41 meter</b> boven NAP het hoogste punt van Aalten — een bos van laag hout met opvallende hoogteverschillen. Wie het grote rondje loopt, combineert Loohuis met De Haart en de Ringkampsbulten.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (spechten, voorjaarsbos), jul–aug (vijver als picknickplek), sep–okt (paddenstoelen)<br>\\n    <b>Beste tijd van de dag:</b> Schemering — rosse vleermuizen jagen.',
 'why': ['Het <b>Natuurmonumenten-bos uit 1927</b> met 100 jaar oude dennen.', 'De <b>twee bosplassen</b> — één verdroogd, één vol kikkerleven.', 'De <b>rosse vleermuis</b> en de mierenhopen van de rode bosmier.', 'De <b>Ringkampsbulten</b> (41 m) als hoogste punt van Aalten.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Drie spechtsoorten</b> in bos en houtwal.', '<span class="months">Jun–Aug</span> 🧺 <b>Picknickplek</b> bij de vijver.', '<span class="months">Jul–Sep</span> 🦇 <b>Vleermuizen</b> na schemering.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> tussen laag hout.'],
 'wild': ['🦇 Rosse vleermuis', '🐸 Groene kikker in de plas', '🐜 Rode bosmier-bergen', '🦌 Ree en kleine zoogdieren', '⛰️ Ringkampsbulten (41 m)'],
 'trail': ['Start bij de <b>parkeerplaats Haartseweg</b> voor het bosrondje.', 'Picknick aan de <b>vijver</b> (banken geplaatst).', 'Combineer met <b>De Haart en de Ringkampsbulten</b> voor een grotere ronde.'],
 'foot': '🐕 Honden aangelijnd, op de paden · 💶 Gratis · ⚠️ Hoofdpad soms afgesloten (Vitens-werkzaamheden) · 🚶 Rondje ± 4 km'
}, {
 'tags': ['Gelderland · Aalten (east of the village)', '21-ha Natuurmonumenten wood from 1927 · two forest pools, brown long-eared bat · Ringkampsbulten (41 m) as the highest point of Aalten', 'list 36 · no. 832'],
 'loc': '📍 Haartseweg, Aalten — Haartseweg car park; ± 15 minutes by bike from Aalten station · paths through wood, pool and grassland with hedgerows (main path temporarily closed at times due to Vitens works)',
 'desc': 'East of Aalten lies <b>Loohuis</b>, a Natuurmonumenten reserve: an attractive wood of <b>21 hectares</b>, planted in <b>1927</b> and enclosed between the Loohuisweg and the Haartseweg. It is a wood of the modest kind: <b>low woodland</b> in slightly hilly terrain, with <b>Scots pines</b> over a hundred years old, great <b>anthills</b>, and <b>two forest pools</b> — one grown shut with birch and cotton-grass through desiccation, but the other still holding water and harbouring the <b>common frog</b>. In the wood <b>birds and mammals</b> find food and shelter in an otherwise open farmland — a green oasis between the fields; the <b>brown long-eared bat</b> hunts above the paths, and <b>nuthatch, great spotted and green woodpecker</b> are the resident birds. Further on, in the hamlet of De Haart, lie the <b>Ringkampsbulten</b>, at <b>41 metres</b> above NAP the highest point of Aalten — a wood of low woodland with striking height differences. Walk the grand loop and you combine Loohuis with De Haart and the Ringkampsbulten.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (woodpeckers, spring wood), Jul–Aug (pond as picnic spot), Sep–Oct (fungi)<br>\\n    <b>Best time of day:</b> Dusk — brown long-eared bats hunting.',
 'why': ['The <b>1927 Natuurmonumenten wood</b> with 100-year-old pines.', 'The <b>two forest pools</b> — one desiccated, one full of frog life.', 'The <b>brown long-eared bat</b> and the red wood ant hills.', 'The <b>Ringkampsbulten</b> (41 m) as the highest point of Aalten.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Three woodpecker species</b> in wood and hedgerow.', '<span class="months">Jun–Aug</span> 🧺 <b>Picnic spot</b> by the pond.', '<span class="months">Jul–Sep</span> 🦇 <b>Bats</b> after dusk.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> among the low woodland.'],
 'wild': ['🦇 Brown long-eared bat', '🐸 Common frog in the pool', '🐜 Red wood ant hills', '🦌 Roe deer and small mammals', '⛰️ Ringkampsbulten (41 m)'],
 'trail': ['Start at the <b>Haartseweg car park</b> for the wood loop.', 'Picnic at the <b>pond</b> (benches in place).', 'Combine with <b>De Haart and the Ringkampsbulten</b> for a grander loop.'],
 'foot': '🐕 Dogs on lead, on the paths · 💶 Free · ⚠️ Main path sometimes closed (Vitens works) · 🚶 Loop ± 4 km'
}))

C.append(mk.card(2114, 'Aalten landschapselementen', {
 'tags': ['Gelderland · rond Aalten (Achterhoek)', 'netwerk van kleine landschapselementen — houtwallen, singels, poelen en bosjes, samengehouden door opengestelde NSW-landgoederen · geen omrasterd reservaat', 'list 36 · no. 833'],
 'loc': '📍 Verspreid rond Aalten en Heelweg, tussen Vennebulten, Aaltense Goor en Bredevoort · Opengestelde NSW-landgoederen — borden bij de toegangen',
 'desc': 'Geen omrasterd reservaat maar een collectie kleine landschapselementen rond Aalten: houtwallen, singels, poelen, oude erfbeplantingen en kleine bosjes — onder meer de opengestelde NSW-landgoederen, van Eppink (kaart 2112) en Beestmans tot Geessink, Groot Heinen, Klein Zwitserland, Leemkamp en Het Winkel — die het coulissenlandschap tussen Vennebulten, Goor en Bredevoort aaneenrijgen. Dit zijn de groene aders van het Achterhoekse cultuurlandschap: klein, particulier en kwetsbaar, in stand gehouden door boeren en eigenaren die hun wallen en singels beheren. Wie de rechte lanen van het Aaltense Goor of de Romienendiek loopt, ziet ze overal: de houtwal als erfgoed van de veeteelt, de poel als historische drinkplaats, het bosje als houtvoorraad van weleer.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (bloeiende singels), sep–okt (paddenstoelen op oude stobben)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogels langs de houtwallen.',
 'why': ['De <b>houtwallen en elzensingels</b> als erfgoed van de oude veeteelt.', 'De <b>NSW-landgoederen</b> rond Aalten die openstellen.', 'De <b>poelen en erfbeplantingen</b> als kleine oases.', 'Het <b>aaneengeregen landschap</b> tussen de grotere gebieden door.'],
 'phen': ['<span class="months">Apr–Jun</span> 🌸 <b>Bloeiende singels</b> en houtwallen.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> op oude stobben.', '<span class="months">Heel jaar</span> 🐦 <b>Vogels</b> langs de groene aders.', '<span class="months">Winter</span> ❄️ <b>Koude schemering</b> — de wallen als silhouet.'],
 'wild': ['🌳 Houtwallen en singels', '💧 Poelen en erfbeplantingen', '🏡 NSW-landgoederen rond Aalten', '🐦 Vogels van het coulissenlandschap', '🗺️ Netwerk tussen Vennebulten en Bredevoort'],
 'trail': ['Combineer de elementen via de <b>landwegen rond Heelweg</b> en de Romienendiek.', 'Bezoek de <b>opengestelde NSW-goederen</b> (borden bij de toegangen).', 'Sluit aan op de rondes van <b>Vennebulten en Aaltense Goor</b> (kaarten 2110–2111).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Particuliere gronden — paden en openstellingen respecteren · 🚶 Netwerkrondes naar keuze'
}, {
 'tags': ['Gelderland · around Aalten (Achterhoek)', 'network of small landscape elements — hedgerows, belts, ponds and little woods, held together by open Nature Beauty Act estates · no fenced reserve', 'list 36 · no. 833'],
 'loc': '📍 Scattered around Aalten and Heelweg, between the Vennebulten, Aaltense Goor and Bredevoort · Open Nature Beauty Act estates — signs at the entrances',
 'desc': 'No fenced reserve but a collection of small landscape elements around Aalten: hedgerows, belts, ponds, old farmyard planting and small woods — among them the open Nature Beauty Act estates, from Eppink (card 2112) and Beestmans to Geessink, Groot Heinen, Klein Zwitserland, Leemkamp and Het Winkel — stringing together the hedgerow landscape between the Vennebulten, the Goor and Bredevoort. These are the green veins of the Achterhoek cultural landscape: small, private and vulnerable, kept alive by the farmers and owners who tend their belts and hedges. Walk the straight lanes of the Aaltense Goor or the Romienendiek and you see them everywhere: the timber belt as heritage of old stock-keeping, the pond as the historic drinking place, the little wood as the firewood store of old.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (flowering hedges), Sep–Oct (fungi on old stumps)<br>\\n    <b>Best time of day:</b> Morning — birds along the timber belts.',
 'why': ['The <b>hedgerows and alder belts</b> as heritage of old stock-keeping.', 'The <b>Nature Beauty Act estates</b> around Aalten that open their gates.', 'The <b>ponds and farmyard planting</b> as small oases.', 'The <b>strung-together landscape</b> between the larger reserves.'],
 'phen': ['<span class="months">Apr–Jun</span> 🌸 <b>Flowering hedges</b> and belts.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on old stumps.', '<span class="months">All year</span> 🐦 <b>Birds</b> along the green veins.', '<span class="months">Winter</span> ❄️ <b>Cold dusk</b> — the belts as silhouettes.'],
 'wild': ['🌳 Hedgerows and singels', '💧 Ponds and farmyard planting', '🏡 Nature Beauty Act estates around Aalten', '🐦 Birds of the hedgerow landscape', '🗺️ Network between Vennebulten and Bredevoort'],
 'trail': ['Combine the elements via the <b>country lanes around Heelweg</b> and the Romienendiek.', 'Visit the <b>open Nature Beauty Act estates</b> (signs at the entrances).', 'Link up with the loops of the <b>Vennebulten and Aaltense Goor</b> (cards 2110–2111).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Private grounds — respect paths and openings · 🚶 Network loops of your choice'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2114)
mk.check()
