# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2100, 'Heerlijkheid Beek', {
 'tags': ['Gelderland · Beek en Berg en Dal (stuwwal ten oosten van Nijmegen)', 'GLK-landgoed van 49 ha: bos hoog, Elyzeese velden laag · Kabouterboom van 850 cm (begin 16e eeuw) · Van Randwijck 1660–1941', 'list 36 · no. 819'],
 'loc': '📍 Rijksstraatweg, Beek — ingangen vanaf Beek en Berg en Dal (Ommetje Heerlijkheid Beek 3,5 km; N70-route 16 km) · hondenlosloopgebied 1,7 ha bovenop de berg',
 'desc': 'Op de <b>steile heuvelrand tussen Beek en Berg en Dal</b> ligt de <b>Heerlijkheid Beek</b>: een 49 hectare groot GLK-gebied op de stuwwal, waar de hoogteverschillen bijna <b>on-Nederlands</b> aandoen. Het is een oud leen van de graven van Kleef: rond <b>1350</b> kwam het aan de heren van Groesbeek, en van <b>1660 tot 1941</b> was het in handen van de familie <b>Van Randwijck</b>, die in 1941 de gronden langs de heuvelrand aan Het Geldersch Landschap verkocht. Het landschap is een klassieker: <b>bos op de hoogten</b>, de <b>Elyzeese velden</b> — weilanden — in de laagte, met daartussen een <b>bron, een beek en vijvers</b>. Uit de stuwwal sijpelen meerdere beken; de <b>tamme kastanjes</b> herinneren aan de Romeinen, die de boom 2.000 jaar geleden als proviand introduceerden. Op het hoogste deel staat sinds 1880 het <b>Huys te Schengen</b>. De beroemdste bewoner staat buiten: de <b>Kabouterboom</b>, een tamme kastanje met een <b>omtrek van 850 centimeter</b> die er sinds het <b>begin van de 16e eeuw</b> staat — mogelijk de oudste boom van Nederland (brand in 2005, het litteken is nog zichtbaar). In 2022 herstelde GLK drie historische <b>zichtlijnen</b>, onder andere naar het kerkje van Persingen en de Hoge 80.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (bronbeekjes, zangvogels), mei (kastanjebloei), sep–okt (herfst in de Elyzeese velden)<br>\\n    <b>Beste tijd van de dag:</b> Late middag — licht over de Elyzeese velden.',
 'why': ['De <b>Kabouterboom</b>: 850 cm omtrek, begin 16e eeuw, misschien de oudste boom van Nederland.', '<b>Bos hoog, weiland laag</b> — de Elyzeese velden van de Van Randwijcks.', 'De <b>Romeinse kastanjes</b> en de bronnetjes van de stuwwal.', 'De herstelde <b>zichtlijnen</b> naar Persingen en de Hoge 80.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Zangvogels</b> in bos en singels.', '<span class="months">Mei–Jun</span> 🌸 <b>Kastanjebloesem</b> rond de Kabouterboom.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> in de Elyzeese velden.', '<span class="months">Heel jaar</span> 💧 <b>Brongebeek</b> uit de stuwwal.'],
 'wild': ['🌳 Kabouterboom (850 cm, 16e eeuw)', '💧 Bronnen en beken van de stuwwal', '🌰 Romeinse tamme kastanjes', '🏡 Huys te Schengen (1880)', '🪶 Spechten en bosvogels'],
 'trail': ['Loop het <b>Ommetje Heerlijkheid Beek</b> (3,5 km) vanaf Berg en Dal.', 'Volg de <b>N70</b> voor het grote rondje over acht bergen en acht dalen.', 'Zoek de <b>zichtlijnen</b> en de Kabouterboom in het bos.'],
 'foot': '🐕 Honden aangelijnd (losloopgebied 1,7 ha boven) · 💶 Gratis · ⚠️ Steile paden — goed schoeisel · 🚶 Ommetje 3,5 km'
}, {
 'tags': ['Gelderland · Beek and Berg en Dal (moraine east of Nijmegen)', '49-ha GLK estate: woodland high, Elysian fields low · 850-cm Kabouterboom from the early 16th century · Van Randwijck 1660–1941', 'list 36 · no. 819'],
 'loc': '📍 Rijksstraatweg, Beek — entrances from Beek and Berg en Dal (Heerlijkheid Beek loop 3.5 km; N70 route 16 km) · 1.7-ha off-lead dog area on top of the hill',
 'desc': 'On the <b>steep hill edge between Beek and Berg en Dal</b> lies the <b>Heerlijkheid Beek</b>: a 49-hectare GLK reserve on the push moraine, where the height differences feel almost <b>un-Dutch</b>. It is an ancient fief of the counts of Cleves: around <b>1350</b> it passed to the lords of Groesbeek, and from <b>1660 to 1941</b> it belonged to the <b>Van Randwijck</b> family, who in 1941 sold the grounds along the hill edge to Het Geldersch Landschap. The landscape is a classic: <b>woodland on the heights</b>, the <b>Elysian fields</b> — meadows — below, with a <b>spring, a stream and ponds</b> in between. Several streams seep from the moraine; the <b>sweet chestnuts</b> recall the Romans, who introduced the tree 2,000 years ago as provisions. On the highest part stands the <b>Huys te Schengen</b>, built 1880. The most famous resident stands outside: the <b>Kabouterboom</b>, a sweet chestnut with a <b>girth of 850 centimetres</b> standing there since the <b>early 16th century</b> — possibly the oldest tree of the Netherlands (fire in 2005, the scar still visible). In 2022 GLK restored three historic <b>sight lines</b>, among others towards the little church of Persingen and the Hoge 80.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring streams, songbirds), May (chestnut blossom), Sep–Oct (autumn in the Elysian fields)<br>\\n    <b>Best time of day:</b> Late afternoon — light over the Elysian fields.',
 'why': ['The <b>Kabouterboom</b>: 850 cm girth, early 16th century, perhaps the oldest tree of the Netherlands.', '<b>Woodland high, meadow low</b> — the Elysian fields of the Van Randwijcks.', 'The <b>Roman chestnuts</b> and the springs of the moraine.', 'The restored <b>sight lines</b> to Persingen and the Hoge 80.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Songbirds</b> in wood and hedgerow.', '<span class="months">May–Jun</span> 🌸 <b>Chestnut blossom</b> around the Kabouterboom.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> in the Elysian fields.', '<span class="months">All year</span> 💧 <b>Spring-fed stream</b> from the moraine.'],
 'wild': ['🌳 Kabouterboom (850 cm, 16th century)', '💧 Springs and streams of the moraine', '🌰 Roman sweet chestnuts', '🏡 Huys te Schengen (1880)', '🪶 Woodpeckers and woodland birds'],
 'trail': ['Walk the <b>Heerlijkheid Beek loop</b> (3.5 km) from Berg en Dal.', 'Follow the <b>N70</b> for the grand tour over eight hills and eight valleys.', 'Seek out the <b>sight lines</b> and the Kabouterboom in the wood.'],
 'foot': '🐕 Dogs on lead (1.7-ha off-lead area on top) · 💶 Free · ⚠️ Steep paths — sturdy footwear · 🚶 Loop 3.5 km'
}))

C.append(mk.card(2101, 'Duivelsberg', {
 'tags': ['Gelderland · Berg en Dal (aan de Duitse grens)', '75,9 meter hoge heuvel: Duits tot 1949, geannexeerd als oorlogscompensatie en in 1963 definitief Nederlands · middeleeuwse motte Mergelp en Wylermeer', 'list 36 · no. 820'],
 'loc': '📍 Te voet vanaf Berg en Dal of via het Airbornepad; grensovergang Wylerbaan · Duivelsberg- en Duffeltroute (struinroutes) door het reservaat; uitzicht over de Duffelt',
 'desc': 'De <b>Duivelsberg</b> — in het Duits <b>Wylerberg</b> of <b>Teufelsberg</b> — is met <b>75,9 meter</b> een van de hoogste heuvels van de Nijmeegse stuwwal en tegelijk het raarste stukje Nederland: een heuvel die tot <b>1949 Duits</b> was, als <b>oorlogscompensatie</b> werd geannexeerd en — anders dan de andere geannexeerde gebieden — op <b>1 augustus 1963 niet werd teruggegeven</b>. Staatsbosbeheer beheert het reservaat sinds 1966; dat het Nederlands bleef, was mede te danken aan de Nijmeegse politicus <b>Van der Goes van Naters</b>, die tijdens de onderhandelingen op het natuurschoon wees. De geschiedenis is nog veel ouder: in de middeleeuwen stond op de heuvel de <b>burcht Mergelp</b> met houten toren en palissades, later een vluchtburcht voor de lokale bevolking; in de Tweede Wereldoorlog vochten Amerikaanse luchtlandingstroepen om <b>heuvel 75.9</b> tijdens Market Garden. Het bos is loofrijk, met <b>tamme kastanjes</b> die volgens de overlevering door de Romeinen zijn aangeplant; onderaan ligt het <b>Wylermeer</b>, dat deels eveneens Nederlands werd. Vanaf de top kijk je uit over <b>de Duffelt</b>, het Duitse land tussen Nijmegen en Kleef — de naam Duivelsberg zou dan ook van <b>Duffelsberg</b> komen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Okt</b> (struinseizoen), mei (kastanjebloei), nov (mist over de Duffelt)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — uitzicht over de Duffelt in tegenlicht.',
 'why': ['De <b>annexatiegeschiedenis</b>: Duits tot 1949, Nederlands voor altijd sinds 1963.', 'De <b>75,9 meter</b> met uitzicht over de Duffelt en het Wylermeer.', 'De middeleeuwse <b>motte Mergelp</b> en de strijd om heuvel 75.9.', 'De <b>Romeinse kastanjes</b> en het loofrijke struinbos.'],
 'phen': ['<span class="months">Mei</span> 🌸 <b>Kastanjebloesem</b> op de hellingen.', '<span class="months">Apr–Okt</span> 🥾 <b>Struinroutes</b> over heuvel en Duffeltroute.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstbos</b> op de stuwwal.', '<span class="months">Nov–Feb</span> 🌫️ <b>Mist over de Duffelt</b> vanaf de top.'],
 'wild': ['⛰️ Heuvel van 75,9 m', '🏰 Motte Mergelp (middeleeuwen)', '🌰 Romeinse kastanjebossen', '🌊 Wylermeer onderaan', '🚩 Grensgeschiedenis 1949/1963'],
 'trail': ['Loop de <b>Duivelsberg- en Duffeltroute</b> (struingids) over en om de heuvel.', 'Volg het <b>Airbornepad</b> vanaf de Canadese erebegraafplaats bij Groesbeek.', 'Daal af naar het <b>Wylermeer</b> en steek bij Wyler de grens over.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Steile klimmetjes; grenspaden — pas op waar Duitsland begint · 🚶 Struinrondes 5–10 km'
}, {
 'tags': ['Gelderland · Berg en Dal (at the German border)', '75.9-metre hill: German until 1949, annexed as war compensation and definitively Dutch since 1963 · medieval Mergelp mote and Wyler lake', 'list 36 · no. 820'],
 'loc': '📍 On foot from Berg en Dal or via the Airborne path; Wylerbaan border crossing · Duivelsberg and Duffelt striding routes through the reserve; views over the Duffelt',
 'desc': 'The <b>Duivelsberg</b> — in German <b>Wylerberg</b> or <b>Teufelsberg</b> — is, at <b>75.9 metres</b>, one of the highest hills of the Nijmegen moraine and at once the strangest corner of the Netherlands: a hill that was <b>German until 1949</b>, annexed as <b>war compensation</b> and — unlike the other annexed areas — <b>not returned on 1 August 1963</b>. Staatsbosbeheer has managed the reserve since 1966; that it stayed Dutch was partly thanks to the Nijmegen politician <b>Van der Goes van Naters</b>, who pointed to its natural beauty during the negotiations. The history is far older: in the Middle Ages the castle <b>Mergelp</b> stood on the hill with wooden tower and palisades, later a refuge for the local population; in the Second World War American airborne troops fought for <b>hill 75.9</b> during Market Garden. The wood is rich in broadleaves, with <b>sweet chestnuts</b> planted, so legend says, by the Romans; at its foot lies the <b>Wylermeer</b>, itself partly Dutch. From the top you look out over <b>the Duffelt</b>, the German land between Nijmegen and Kleve — the name Duivelsberg, they say, simply comes from <b>Duffelsberg</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (striding season), May (chestnut blossom), Nov (mist over the Duffelt)<br>\\n    <b>Best time of day:</b> Morning — views over the Duffelt in backlight.',
 'why': ['The <b>annexation history</b>: German until 1949, Dutch for good since 1963.', 'The <b>75.9 metres</b> with views over the Duffelt and the Wylermeer.', 'The medieval <b>Mergelp mote</b> and the battle for hill 75.9.', 'The <b>Roman chestnuts</b> and the broadleaved striding wood.'],
 'phen': ['<span class="months">May</span> 🌸 <b>Chestnut blossom</b> on the slopes.', '<span class="months">Apr–Oct</span> 🥾 <b>Striding routes</b> over hill and Duffelt route.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn wood</b> on the moraine.', '<span class="months">Nov–Feb</span> 🌫️ <b>Mist over the Duffelt</b> from the top.'],
 'wild': ['⛰️ Hill of 75.9 m', '🏰 Mergelp mote (Middle Ages)', '🌰 Roman chestnut woods', '🌊 Wylermeer at its foot', '🚩 Border history 1949/1963'],
 'trail': ['Walk the <b>Duivelsberg and Duffelt route</b> (striding guide) over and around the hill.', 'Follow the <b>Airborne path</b> from the Canadian war cemetery at Groesbeek.', 'Descend to the <b>Wylermeer</b> and cross the border at Wyler.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Steep climbs; border paths — mind where Germany begins · 🚶 Striding loops 5–10 km'
}))

C.append(mk.card(2102, 'Nederrijk', {
 'tags': ['Gelderland · tussen Berg en Dal en Groesbeek (stuwwalzuid)', 'Oerbos-restant dat tot de 15e eeuw met de Reichswald één geheel vormde · in 1916 gekocht door margarinefabrikant Jurgens: Landgoed van Jurgens', 'list 36 · no. 821'],
 'loc': '📍 Bosgebied ten zuiden van Berg en Dal, toegankelijk via het Airbornepad en de paden vanaf de Zevenheuvelenweg · combineren met Duivelsberg (kaart 2101) en Groesbeek (kaart 2103)',
 'desc': 'Het <b>Nederrijk</b> is het oude naamloze bos tussen <b>Berg en Dal en Groesbeek</b> — een restant van het <b>oerbos</b> dat tot in de <b>15e eeuw</b> één geheel vormde met de Duitse <b>Reichswald</b> en dat de Romeinen naar men zegt het <b>Heilige Woud</b> noemden. In <b>1916</b> kocht de margarinefabrikant <b>Jurgens</b> het goed, sindsdien <b>Landgoed van Jurgens</b> geheten; de villa staat er nog. Het is het Nederlandse deel van wat plaatselijk de <b>Nederrijkswald</b> wordt genoemd: hoge stuwwalbossen met diepe beekdalen, oude eiken en beuken, en hier en daar een zichtlijn die tot over de Duffelt reikt. Het <b>Airbornepad</b> voert er dwars doorheen, van de Canadese erebegraafplaats naar de Duivelsberg — in 1944-1945 werd juist hier zwaar gevochten tijdens <b>Operatie Veritable</b>. Wie de Zevenheuvelenweg oversteekt, wandelt van het Nederrijk zo het Groesbeekse bos in: voor de wandelaar is het één adembenemend geheel van heuvel en dal.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (voorjaarsbos, anemonen), sep–nov (herfstkleur op de stuwwal)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel in de beekdalen.',
 'why': ['Restant van het <b>oerbos</b> dat één was met de Reichswald.', 'De <b>Jurgens-geschiedenis</b>: margarinegeld uit 1916.', 'De <b>beekdalen en oude eiken</b> van de hoge stuwwal.', 'Het <b>Airbornepad</b> door het oorlogslandschap van Veritable.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🌱 <b>Anemonen</b> in de beekdalen.', '<span class="months">Apr–Jun</span> 🎵 <b>Bosvogels</b> op de zuidhellingen.', '<span class="months">Sep–Nov</span> 🍂 <b>Herfstkleur</b> over het gehele goed.', '<span class="months">Heel jaar</span> 🥾 <b>Airbornepad</b> als rode draad.'],
 'wild': ['🌲 Oerbos-restant (Nederrijkswald)', '🏡 Landgoed van Jurgens (1916)', '💧 Beekdalen van de stuwwal', '🍂 Oude eiken en beuken', '🪖 Veritable-1945 landschap'],
 'trail': ['Volg het <b>Airbornepad</b> door het Nederrijk richting Duivelsberg.', 'Wandel de <b>stuwwalpaden</b> tussen Zevenheuvelenweg en Duitse grens.', 'Combineer met <b>Groesbeek</b> (kaart 2103) voor de grote bosroute.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Bosrondes 5–12 km'
}, {
 'tags': ['Gelderland · between Berg en Dal and Groesbeek (southern moraine)', 'Primeval-forest remnant that formed one whole with the Reichswald until the 15th century · bought in 1916 by margarine maker Jurgens: Landgoed van Jurgens', 'list 36 · no. 821'],
 'loc': '📍 Woodland south of Berg en Dal, accessible via the Airborne path and the paths from the Zevenheuvelenweg · combine with Duivelsberg (card 2101) and Groesbeek (card 2103)',
 'desc': 'The <b>Nederrijk</b> is the old nameless wood between <b>Berg en Dal and Groesbeek</b> — a remnant of the <b>primeval forest</b> that until the <b>15th century</b> formed one whole with the German <b>Reichswald</b>, and which the Romans, so it is said, called the <b>Holy Wood</b>. In <b>1916</b> the margarine manufacturer <b>Jurgens</b> bought the estate, since then called <b>Landgoed van Jurgens</b>; the villa still stands. It is the Dutch part of what is locally called the <b>Nederrijkswald</b>: high moraine woods with deep stream valleys, old oaks and beeches, and here and there a sight line reaching across the Duffelt. The <b>Airborne path</b> leads straight through it, from the Canadian war cemetery to the Duivelsberg — in 1944–1945 heavy fighting took place precisely here during <b>Operation Veritable</b>. Cross the Zevenheuvelenweg and you walk from the Nederrijk straight into the Groesbeek wood: for the walker it is one breathtaking whole of hill and valley.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring wood, anemones), Sep–Nov (autumn colour on the moraine)<br>\\n    <b>Best time of day:</b> Morning — mist in the stream valleys.',
 'why': ['Remnant of the <b>primeval forest</b> that was one with the Reichswald.', 'The <b>Jurgens history</b>: margarine money from 1916.', 'The <b>stream valleys and old oaks</b> of the high moraine.', 'The <b>Airborne path</b> through the Veritable war landscape.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌱 <b>Anemones</b> in the stream valleys.', '<span class="months">Apr–Jun</span> 🎵 <b>Woodland birds</b> on the south slopes.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn colour</b> over the whole estate.', '<span class="months">All year</span> 🥾 <b>Airborne path</b> as the common thread.'],
 'wild': ['🌲 Primeval-forest remnant (Nederrijkswald)', '🏡 Landgoed van Jurgens (1916)', '💧 Stream valleys of the moraine', '🍂 Old oaks and beeches', '🪖 Veritable-1945 landscape'],
 'trail': ['Follow the <b>Airborne path</b> through the Nederrijk towards the Duivelsberg.', 'Walk the <b>moraine paths</b> between Zevenheuvelenweg and the German border.', 'Combine with <b>Groesbeek</b> (card 2103) for the grand woodland route.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Wood loops 5–12 km'
}))

C.append(mk.card(2103, 'Groesbeek', {
 'tags': ['Gelderland · Groesbeek (stuwwal Nijmegen–Kleef)', 'Groesbeekse bossen met Canadese erebegraafplaats (2.617 graven) · Zevenheuvelenweg van de Vierdaagse · heuvelachtig bos- en heuvelland tot aan de grens', 'list 36 · no. 822'],
 'loc': '📍 Start bij de Canadese Oorlogsbegraafplaats (groot parkeerterrein) of het Vrijheidsmuseum · Trage Tocht Groesbeek 13 km; Zevenheuvelenwandeling 10–11 km; Pieterpad kruist het gebied',
 'desc': 'De bossen van <b>Groesbeek</b> vormen het middendeel van de stuwwal tussen Nijmegen en Kleef: heuvelachtig bos- en heuvelland dat zich over kilometers uitstrekt tot aan de Duitse grens, doorkruist door de beroemde <b>Zevenheuvelenweg</b> — de derde dag van de <b>Nijmeegse Vierdaagse</b>, waar duizenden wandelaars jaarlijks de heuvels op en af gaan. Midden in het bos ligt de <b>Canadese Oorlogsgraafplaats</b> met <b>2.617 graven</b> van gesneuvelde militairen van het Britse Gemenebest en de namen van <b>1.047 vermisten</b> aan de muur — een van de indrukwekkendste plekken van Gelderland. In de buurt vertelt het <b>Vrijheidsmuseum</b> het verhaal van Market Garden en Veritable; het <b>Airbornepad</b> en het <b>Pieterpad</b> kruisen elkaar in deze bossen. Het landschap wisselt hoge dennenbossen af met oude landgoedpercelen, heiderestanten (de <b>Mulderskop</b>), beekdalen en glooiende akkers waarvan de boeren in oorlogstijd deel uitmaakten van het front. Wie hier wandelt, loopt door drie tijdslagen tegelijk: het ijs van de stuwwal, de ontginningen van de landgoederen en de bevrijding van 1944–1945.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Okt</b> (wandelseizoen), jul (Vierdaagse over de Zevenheuvelen), nov (stille herdenking)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — lege heuvels, mist tussen de dennen.',
 'why': ['De <b>Canadese Oorlogsgraafplaats</b>: 2.617 graven en 1.047 vermisten.', 'De <b>Zevenheuvelenweg</b> als ruggengraat van de Vierdaagse.', 'Het <b>heuvelandschap</b> van de stuwwal: bos, heide en glooiende akkers.', '<b>Airbornepad en Pieterpad</b> kruisen elkaar in deze bossen.'],
 'phen': ['<span class="months">Jul</span> 🚶 <b>Vierdaagse</b> over de Zevenheuvelenweg.', '<span class="months">Apr–Mei</span> 🎵 <b>Voorjaarsbos</b> in de beekdalen.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> op de stuwwalhellingen.', '<span class="months">Heel jaar</span> ⚰️ <b>Ereveld</b> als plek van stilte.'],
 'wild': ['⚰️ Canadese Oorlogsgraafplaats (2.617 graven)', '⛰️ Zevenheuvelen en stuwwalhellingen', '🌿 Heiderestant Mulderskop', '🥾 Pieterpad + Airbornepad', '🏛️ Vrijheidsmuseum Groesbeek'],
 'trail': ['Loop de <b>Trage Tocht Groesbeek</b> (13 km) vanaf de erebegraafplaats.', 'Wandel de <b>Zevenheuvelenwandeling</b> (10–11 km) rondom het dorp.', 'Combineer met <b>Duivelsberg</b> (kaart 2101) en <b>Nederrijk</b> (kaart 2102).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (museum met entreeprijs) · ⚠️ Heuvelachtig — 200+ hoogtemeters mogelijk · 🚶 Routes 6–16 km'
}, {
 'tags': ['Gelderland · Groesbeek (Nijmegen–Kleve moraine)', 'Groesbeek woods with the Canadian war cemetery (2,617 graves) · Seven Hills road of the Four Days Marches · hilly woodland and fields up to the border', 'list 36 · no. 822'],
 'loc': '📍 Start at the Canadian War Cemetery (large car park) or the Freedom Museum · Groesbeek Slow Walk 13 km; Seven Hills walk 10–11 km; the Pieterpad crosses the area',
 'desc': 'The woods of <b>Groesbeek</b> form the middle section of the moraine between Nijmegen and Kleve: hilly woodland and fields stretching for kilometres to the German border, crossed by the famous <b>Zevenheuvelenweg</b> — day three of the <b>Nijmegen Four Days Marches</b>, on which thousands of walkers yearly climb and descend the hills. In the middle of the wood lies the <b>Canadian War Cemetery</b> with <b>2,617 graves</b> of fallen servicemen of the British Commonwealth and the names of <b>1,047 missing</b> on the wall — one of the most impressive places of Gelderland. Nearby the <b>Freedom Museum</b> tells the story of Market Garden and Veritable; the <b>Airborne path</b> and the <b>Pieterpad</b> cross each other in these woods. The landscape alternates high pine woods with old estate parcels, heath remnants (the <b>Mulderskop</b>), stream valleys and rolling fields whose farms formed part of the front in wartime. Walk here and you move through three layers of time at once: the ice of the moraine, the estates’ plantings, and the liberation of 1944–1945.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (walking season), Jul (Four Days Marches over the Seven Hills), Nov (quiet remembrance)<br>\\n    <b>Best time of day:</b> Early morning — empty hills, mist among the pines.',
 'why': ['The <b>Canadian War Cemetery</b>: 2,617 graves and 1,047 missing.', 'The <b>Seven Hills road</b> as the backbone of the Marches.', 'The <b>hill landscape</b> of the moraine: wood, heath and rolling fields.', '<b>Airborne path and Pieterpad</b> cross in these woods.'],
 'phen': ['<span class="months">Jul</span> 🚶 <b>Four Days Marches</b> over the Seven Hills road.', '<span class="months">Apr–May</span> 🎵 <b>Spring woodland</b> in the stream valleys.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> on the moraine slopes.', '<span class="months">All year</span> ⚰️ <b>War cemetery</b> as a place of silence.'],
 'wild': ['⚰️ Canadian War Cemetery (2,617 graves)', '⛰️ Seven Hills and moraine slopes', '🌿 Mulderskop heath remnant', '🥾 Pieterpad + Airborne path', '🏛️ Freedom Museum Groesbeek'],
 'trail': ['Walk the <b>Groesbeek Slow Walk</b> (13 km) from the war cemetery.', 'Take the <b>Seven Hills walk</b> (10–11 km) around the village.', 'Combine with the <b>Duivelsberg</b> (card 2101) and <b>Nederrijk</b> (card 2102).'],
 'foot': '🐕 Dogs on lead · 💶 Free (museum with entry fee) · ⚠️ Hilly — 200+ metres of climb possible · 🚶 Routes 6–16 km'
}))

C.append(mk.card(2104, 'Maldens Vlak', {
 'tags': ['Gelderland · Malden/Heumen (ten zuiden van Nijmegen)', '± 77 ha gemeentebos op voormalig heidevlakte · zweefvliegveld Malden (1958) midden in het bos · das, ree en wilde zwijn als stille bewoners', 'list 36 · no. 823'],
 'loc': '📍 Tussen Nijmegen, Malden en Groesbeek — toegangen vanaf de Bisseltsebaan en de zweefvliegveldweg · bospaden en -lanen; nachtelijke toegang verboden (wildrust)',
 'desc': 'Het <b>Maldens Vlak</b> is een ± <b>77 hectare</b> groot bosgebied van de gemeente Heumen, dat naadloos aansluit op <b>Heumensoord</b> en de Groesbeekse bossen — samen het grote bosplateau ten zuiden van Nijmegen. Vroeger was het een <b>geaccidenteerd heidegebied</b> op de stuwwal; in <b>1958</b> werd midden op het Vlak het <b>zweefvliegveld van Malden</b> aangelegd, waarvan de kruisende banen het terrein in vier vlakken delen en waar de <b>Nijmeegse Aeroclub</b> (opgericht 1954) nog altijd de thermiek boven de stuwwal benut. Rondom het veld is het een productiebos in ontwikkeling, doorkruist door lanen en drukbezocht door ruiters, mountainbikers en wandelaars — en veel stiller dan het stadsnabije Heumensoord. Het wild weet dat: in het bos leven <b>konijnen, hazen, vossen, dassen, reeën</b> en incidenteel <b>wilde zwijnen</b>. Om de wildrust te beschermen is het gebied <b>tussen zonsondergang en zonsopgang verboden</b> te betreden, en vragen de borden op de paden om niet van de wegen af te wijken. Wie wil uitrusten kan dat in het <b>Boscafé De Zweef</b> aan het vliegveld.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Sep</b> (zweefvliegseizoen), mei–jun (bloeiende bosranden), sep–okt (herfstkleur)<br>\\n    <b>Beste tijd van de dag:</b> Middag — zweefvliegers klimmen boven het Vlak.',
 'why': ['Het <b>zweefvliegveld midden in het bos</b> — uniek in Nederland.', 'De <b>wildrust</b>: das, ree en soms wilde zwijn zo dicht bij de stad.', 'De verbinding met <b>Heumensoord en Groesbeek</b> tot één bosplateau.', 'Het <b>Boscafé De Zweef</b> als wandelbasis.'],
 'phen': ['<span class="months">Apr–Sep</span> 🛩️ <b>Zweefvliegers</b> in de thermiek boven de stuwwal.', '<span class="months">Apr–Jun</span> 🎵 <b>Bosvogels</b> in lanen en randen.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> over het Vlak.', '<span class="months">Schemering</span> 🦡 <b>Wild op drift</b> — het bos sluit bij zonsondergang.'],
 'wild': ['🛩️ Zweefvliegveld Malden (1958)', '🦡 Das · ree · vos', '🐗 Wilde zwijnen incidenteel', '🌲 Productiebos op oude heide', '☕ Boscafé De Zweef'],
 'trail': ['Wandel de <b>bospaden rond het zweefvliegveld</b> vanaf de Bisseltsebaan.', 'Combineer met <b>Heumensoord</b> (kaart 2097) voor de grote route.', 'Houd de <b>zonsondergangsdrempel</b> in de gaten — het bos sluit.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Nachtelijke toegang verboden; blijf op de paden (wildrust) · 🚶 Bosrondes 4–8 km'
}, {
 'tags': ['Gelderland · Malden/Heumen (south of Nijmegen)', '± 77-ha municipal wood on a former heath plain · Malden glider field (1958) in the middle of the wood · badger, roe and boar as quiet residents', 'list 36 · no. 823'],
 'loc': '📍 Between Nijmegen, Malden and Groesbeek — accesses from the Bisseltsebaan and the glider-field road · woodland paths and avenues; night access forbidden (game quiet)',
 'desc': 'The <b>Maldens Vlak</b> is a ± <b>77-hectare</b> municipal wood of the municipality of Heumen, joining seamlessly onto <b>Heumensoord</b> and the Groesbeek woods — together the great woodland plateau south of Nijmegen. It was once an <b>uneven heath plain</b> on the moraine; in <b>1958</b> the <b>Malden glider field</b> was laid out in the middle of the Vlak, its crossing runways dividing the terrain into four quarters, where the <b>Nijmegen Aeroclub</b> (founded 1954) still rides the thermals above the moraine. Around the field lies production woodland in transition, crossed by avenues and busy with riders, mountain bikers and walkers — and much quieter than city-side Heumensoord. The game knows it: in the wood live <b>rabbit, hare, fox, badger and roe deer</b>, and incidentally <b>wild boar</b>. To protect the game the area is <b>closed between sunset and sunrise</b>, and the signs ask you not to leave the paths. For a rest, the <b>Boscafé De Zweef</b> at the airfield is the walking base.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Sep</b> (gliding season), May–Jun (flowering wood edges), Sep–Oct (autumn colour)<br>\\n    <b>Best time of day:</b> Midday — gliders climbing above the Vlak.',
 'why': ['The <b>glider field in the middle of the wood</b> — unique in the Netherlands.', 'The <b>game quiet</b>: badger, roe and sometimes boar this close to the city.', 'The connection with <b>Heumensoord and Groesbeek</b> into one woodland plateau.', 'The <b>Boscafé De Zweef</b> as walking base.'],
 'phen': ['<span class="months">Apr–Sep</span> 🛩️ <b>Gliders</b> in the thermals above the moraine.', '<span class="months">Apr–Jun</span> 🎵 <b>Woodland birds</b> in avenues and edges.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> over the Vlak.', '<span class="months">Dusk</span> 🦡 <b>Game on the move</b> — the wood closes at sunset.'],
 'wild': ['🛩️ Malden glider field (1958)', '🦡 Badger · roe · fox', '🐗 Wild boar occasionally', '🌲 Production wood on old heath', '☕ Boscafé De Zweef'],
 'trail': ['Walk the <b>woodland paths around the glider field</b> from the Bisseltsebaan.', 'Combine with <b>Heumensoord</b> (card 2097) for the long route.', 'Mind the <b>sunset threshold</b> — the wood closes.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Night access forbidden; stay on the paths (game quiet) · 🚶 Wood loops 4–8 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2104)
mk.check()
