# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2120, 'Mentink', {
 'tags': ['Gelderland · ten westen van Winterswijk', 'Natuurmonumenten-landgoed van 136 ha, gesticht ± 1930 door een textielbaron — zonder landhuis · vijf boerderijen, biologische akkers, lanen en zandpaden', 'list 36 · no. 839'],
 'loc': '📍 Parkeerplaats Arrasveldweg, Winterswijk — gele route 5 km, rode Korenburgerveen-route 4,4 km, groene Schaddenpad-route 12 km; Gasterij Ankomm’n op de Mentinkweg',
 'desc': 'Landgoed <b>Mentink</b> is een landgoed dat er geen is: rond <b>1930</b> stichtte een <b>Winterswijkse textielbaron</b> het goed, maar het landhuis dat een landgoed hoort te dragen werd nooit gebouwd. Wel kocht hij <b>vijf boerderijen</b> met hun landen bijeen — met de bedoeling dat altijd <b>één pachtfamilie</b> het geheel zou pachten, zodat het niet versnipperde. Sinds <b>1975</b> is <b>Natuurmonumenten</b> die ene familie, en het plan is geslaagd: de vijf hoeven staan er nog, een derde van de 136 hectare is boerenland waar <b>biologische rogge</b> verbouwd wordt en de pachters moeten <b>stroken langs de bosranden verwilderen</b>. De rest is een afwisselend geheel van <b>oude bomenlanen, zandpaden, productiebos dat steeds gevarieerder wordt, houtwallen, akkers en een snufje heide</b> — met wat geluk de kleine, bonte of groene specht. Het Mentinkveld, vroeger drassig heideland, is nu grasland; veldnamen als Mentink-es en Mentinkhof verraden de boerengeschiedenis, en in de 19e eeuw emigreerde vrijwel het hele Mentinkvolk naar Amerika. Vanaf de Arrasveldweg lopen de routes het landgoed op en door naar het <b>Korenburgerveen</b> (kaart 2118).',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (spechten, lanen in blad), jul (rogge goudgeel), sep–okt (paddenstoelen in het variatiebos)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zang onder de oude lanen.',
 'why': ['Het <b>landgoed zonder landhuis</b> van de textielbaron uit 1930.', 'De <b>vijf boerderijen</b> onder één pachtfamilie — en sinds 1975 Natuurmonumenten.', '<b>Biologische rogge</b> en verwilderde bosranden.', 'De <b>oude lanen en zandpaden</b> richting Korenburgerveen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Drie spechtsoorten</b> in het bos.', '<span class="months">Jul</span> 🌾 <b>Biologische rogge</b> goudgeel op de akkers.', '<span class="months">Aug–Sep</span> 🌸 <b>Verwilderde bosranden</b> in bloei.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in het jonge variatiebos.'],
 'wild': ['🚜 Biologische rogge-akkers', '🌳 Oude bomenlanen', '🪶 Kleine · bonte · groene specht', '🏡 Vijf landgoedboerderijen', '🥾 Schaddenpad 12 km'],
 'trail': ['Start bij de <b>parkeerplaats Arrasveldweg</b> en volg de <b>gele route</b> (5 km).', 'Loop het <b>Schaddenpad</b> (groen, 12 km) naar Korenburgerveen en Mentinkveld.', 'Koffie op <b>Gasterij Ankomm’n</b> in boerderij Mentink.'],
 'foot': '🐕 Honden aangelijnd, op de paden · 💶 Gratis · 🥾 Wandelroutes geel/rood/groen · 🚶 4,4–12 km'
}, {
 'tags': ['Gelderland · west of Winterswijk', '136-ha Natuurmonumenten estate founded ± 1930 by a textile baron — without a mansion · five farms, organic fields, avenues and sand paths', 'list 36 · no. 839'],
 'loc': '📍 Arrasveldweg car park, Winterswijk — yellow route 5 km, red Korenburgerveen route 4.4 km, green Schaddenpad route 12 km; Ankomm’n café on the Mentinkweg',
 'desc': 'Mentink <b>estate</b> is an estate that never was one: around <b>1930</b> a <b>Winterswijk textile baron</b> assembled the property, but the mansion an estate is supposed to carry was never built. He did buy <b>five farms</b> with their lands — intending that always <b>one tenant family</b> rent the whole, so it would not fragment. Since <b>1975</b> <b>Natuurmonumenten</b> has been that one family, and the plan worked: the five farms still stand, a third of the 136 hectares is farmland growing <b>organic rye</b>, and the tenants must let <b>strips along the wood edges grow wild</b>. The rest is a varied whole of <b>old tree avenues, sand paths, production woodland growing ever more varied, hedgerows, fields and a pinch of heath</b> — with luck the lesser, great spotted or green woodpecker. The Mentinkveld, once marshy heath, is grassland now; field names like Mentink-es and Mentinkhof betray the farming history, and in the 19th century nearly the whole Mentink community emigrated to America. From the Arrasveldweg the routes enter the estate and run on to the <b>Korenburgerveen</b> (card 2118).',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (woodpeckers, avenues in leaf), Jul (rye golden), Sep–Oct (fungi in the varied wood)<br>\\n    <b>Best time of day:</b> Morning — song under the old avenues.',
 'why': ['The <b>estate without a mansion</b> of the 1930 textile baron.', 'The <b>five farms</b> under one tenant family — and Natuurmonumenten since 1975.', '<b>Organic rye</b> and wilded wood edges.', 'The <b>old avenues and sand paths</b> towards the Korenburgerveen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🪶 <b>Three woodpecker species</b> in the wood.', '<span class="months">Jul</span> 🌾 <b>Organic rye</b> golden on the fields.', '<span class="months">Aug–Sep</span> 🌸 <b>Wilded wood edges</b> in flower.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the young varied wood.'],
 'wild': ['🚜 Organic rye fields', '🌳 Old tree avenues', '🪶 Lesser · great spotted · green woodpecker', '🏡 Five estate farms', '🥾 Schaddenpad 12 km'],
 'trail': ['Start at the <b>Arrasveldweg car park</b> and follow the <b>yellow route</b> (5 km).', 'Walk the <b>Schaddenpad</b> (green, 12 km) to the Korenburgerveen and Mentinkveld.', 'Coffee at <b>Ankomm’n café</b> in the Mentink farm.'],
 'foot': '🐕 Dogs on lead, on the paths · 💶 Free · 🥾 Walking routes yellow/red/green · 🚶 4.4–12 km'
}))

C.append(mk.card(2121, 'Groters', {
 'tags': ['Gelderland · ten zuidwesten van Winterswijk (Arresveld)', 'omgrachte scholtenboerderij aan de rand van de bolle es van het Arresveld · beekdal van de Muldersbeek met schapen en hooiland', 'list 36 · no. 840'],
 'loc': '📍 Grotersweg, ten zuiden van het Arresveld, Winterswijk — landwegen rond es en beekdal; wandelnetwerk en Mentink-routes (parkeerplaats Arrasveldweg op loopafstand)',
 'desc': 'Aan de zuidkant van de <b>bolle es van het Arresveld</b> — een akkercomplex dat waarschijnlijk al in de vroege middeleeuwen in gebruik was en door eeuwen plaggenbemesting tot anderhalve meter is opgehoogd — ligt de <b>omgrachte scholtenboerderij Groters</b>, een van de statige hoeven van het Winterswijkse scholtenlandschap. Om de akkers tegen wild en vee te beschermen werden vanouds <b>wallen met greppels</b> aangelegd, beplant met dicht eikenhakhout; aan de binnenzijde groeide de es steeds hoger, aan de buitenzijde bleef de <b>steilrand</b> bestaan. Ongeveer een meter lager dan de es ligt het <b>beekdal van de Muldersbeek</b>, de bovenloop die vanaf de Grotersweg door het landgoedgebied slingert: graslanden waar <b>schapen</b> grazen, beekeerdgronden die representatief zijn voor de beekdalen van het Oost-Nederlandse plateau, en percelen van landgoed De Batenborgh die als botanisch hooiland worden beheerd. Samen met het aangrenzende <b>Mentink</b> (kaart 2120) en het Korenburgerveen een kilometer westelijker vormt Groters een schakel in de groene gordel rond Winterswijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (hooiland in bloei), jul–aug (schapen op de percelen), sep–okt (paddenstoelen langs esrand en houtwal)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht over de bolle es.',
 'why': ['De <b>omgrachte scholtenboerderij Groters</b> aan de esrand.', 'De <b>bolle es van het Arresveld</b> met zijn steilranden en houtwallen.', 'Het <b>beekdal van de Muldersbeek</b> met schapen en hooiland.', 'De ligging tussen <b>Mentink en Korenburgerveen</b>.'],
 'phen': ['<span class="months">Mei–Jun</span> 🌾 <b>Botanisch hooiland</b> in bloei.', '<span class="months">Jun–Aug</span> 🐑 <b>Schapen</b> in het beekdal.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> langs de esrand.', '<span class="months">Nov–Feb</span> 🌫️ <b>Winterlicht</b> over de bolle es.'],
 'wild': ['🏡 Omgrachte scholtenhoeve', '⛰️ Bolle es met steilranden', '💧 Muldersbeek-bovenloop', '🐑 Schapen in het beekdal', '🌳 Eikenhakhout op de wallen'],
 'trail': ['Wandel vanaf de <b>Arrasveldweg</b> rond es, erf en beekdal.', 'Volg de <b>landwegen Grotersweg–Mentinkweg</b> door het scholtenlandschap.', 'Combineer met <b>Mentink</b> (kaart 2120) en het <b>Rommelgebergte</b> (kaart 2119).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Erf en landerijen privé — paden volgen · 🚶 Rondje ± 5 km'
}, {
 'tags': ['Gelderland · south-west of Winterswijk (Arresveld)', 'moated scholten farm on the edge of the Arresveld crown es · Muldersbeek valley with sheep and hay meadow', 'list 36 · no. 840'],
 'loc': '📍 Grotersweg, south of the Arresveld, Winterswijk — country lanes around es and valley; walking network and Mentink routes (Arrasveldweg car park within walking distance)',
 'desc': 'On the south side of the <b>crown es of the Arresveld</b> — an arable complex probably already in use in the early Middle Ages and raised by centuries of plaggen manuring to as much as a metre and a half — lies the <b>moated scholten farm Groters</b>, one of the stately farmhouses of the Winterswijk scholten landscape. To keep wild game and cattle off the fields, <b>banks with ditches</b> were traditionally laid out, planted with dense oak coppice; on the inside the es kept rising, on the outside the <b>steep edge</b> remained. About a metre below the es lies the <b>valley of the Muldersbeek</b>, the upper course winding through the estate land from the Grotersweg: grasslands where <b>sheep</b> graze, brook-earth soils representative of the stream valleys of the East-Netherlands plateau, and parcels of the De Batenborgh estate managed as botanical hay meadow. Together with neighbouring <b>Mentink</b> (card 2120) and the Korenburgerveen a kilometre west, Groters forms a link in the green belt around Winterswijk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (hay meadow in flower), Jul–Aug (sheep on the parcels), Sep–Oct (fungi along es edge and hedgerow)<br>\\n    <b>Best time of day:</b> Morning — light over the crown es.',
 'why': ['The <b>moated scholten farm Groters</b> at the es edge.', 'The <b>crown es of the Arresveld</b> with its steep edges and hedgerows.', 'The <b>Muldersbeek valley</b> with sheep and hay meadow.', 'The position between <b>Mentink and the Korenburgerveen</b>.'],
 'phen': ['<span class="months">May–Jun</span> 🌾 <b>Botanical hay meadow</b> in flower.', '<span class="months">Jun–Aug</span> 🐑 <b>Sheep</b> in the valley.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> along the es edge.', '<span class="months">Nov–Feb</span> 🌫️ <b>Winter light</b> over the crown es.'],
 'wild': ['🏡 Moated scholten farm', '⛰️ Crown es with steep edges', '💧 Muldersbeek upper course', '🐑 Sheep in the valley', '🌳 Oak coppice on the banks'],
 'trail': ['Walk from the <b>Arrasveldweg</b> around es, farmyard and valley.', 'Follow the <b>Grotersweg–Mentinkweg lanes</b> through the scholten landscape.', 'Combine with <b>Mentink</b> (card 2120) and the <b>Rommelgebergte</b> (card 2119).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Farmyard and lands private — follow the paths · 🚶 Loop ± 5 km'
}))

C.append(mk.card(2122, 'Gossink', {
 'tags': ['Gelderland · Henxel, ten zuidoosten van Winterswijk', '18e-eeuws Scholtengoed met lanen en vijvers · helft bos: oude eiken en grove den · beroemd paddenstoelenparadijs van KNNV en IVN', 'list 36 · no. 841'],
 'loc': '📍 Kruising Ratumseweg (N820)/Gossinkweg of Vredenseweg/Gossinkweg, Winterswijk-Henxel — wandelpaden over het goed; Döttinkraederoute en Scholtenpad Ratum voeren erlangs',
 'desc': 'Landgoed <b>Gossink</b> in Henxel ligt op een steenworp van het centrum van Winterswijk en is toch een wereld apart: een <b>18e-eeuws Scholtengoed</b> met de fraaie boerderijen <b>Gossink en Nieuw Gossink</b>, omringd door een afwisselend geheel van <b>boslanen, vijvers, bouwland en weiland</b>. De helft van het goed is bos — <b>hoog opgaande eiken</b> afgewisseld met <b>oud grove-dennenbos</b> — en tussen de percelen lopen beekjes en houtwallen. Die variatie maakt Gossink bij natuurliefhebbers vooral geliefd als <b>paddenstoelenparadijs</b>: de werkgroepen van KNNV en IVN Oost-Achterhoek komen er elke najaar op excursie, op zoek naar zeldzame soorten die elk hun eigen plekje kiezen — licht of donker, vochtig of droog, bos of wei. Over het goed lopen wandelpaden die aansluiten op de <b>Döttinkraederoute</b> en het <b>Scholtenpad Ratum</b>; de Ratumse beek voert het water van het goed naar de stad. Wie de wandeling Steengroeve loopt, passeert het landgoed vlak voordat het landschap naar de groeve en de Willinksbeek daalt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–Nov</b> (paddenstoelenexcursies), apr–mei (voorjaarsflora onder de eiken), jun (vijvers vol leven)<br>\\n    <b>Beste tijd van de dag:</b> Na regen — paddenstoelen op hun best.',
 'why': ['Het <b>18e-eeuwse Scholtengoed</b> met zijn twee boerderijen.', '<b>Boslanen en vijvers</b> in een parkachtig geheel.', 'De <b>oude eiken- en grovedennenbossen</b> als paddenstoelenparadijs.', 'De ligging aan <b>Döttinkraederoute en Scholtenpad</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> onder de oude eiken.', '<span class="months">Jun–Jul</span> 💧 <b>Vijvers en beekjes</b> vol leven.', '<span class="months">Sep–Nov</span> 🍄 <b>Paddenstoelen</b> — excursies van KNNV/IVN.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> in het lanenstelsel.'],
 'wild': ['🍄 Paddenstoelenparadijs', '🌳 Oude eiken en grove den', '💧 Vijvers en Ratumse beek', '🏡 Gossink en Nieuw Gossink', '🥾 Döttinkraederoute'],
 'trail': ['Start bij de <b>kruising Ratumseweg/Gossinkweg</b> voor de paden over het goed.', 'Volg de <b>Döttinkraederoute</b> of het <b>Scholtenpad Ratum</b> (19 km).', 'Combineer met de <b>wandeling Steengroeve</b> (± 15 km) richting Willinksbeek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Landerijen deels agrarisch — paden volgen · 🚶 Rondje ± 4–6 km'
}, {
 'tags': ['Gelderland · Henxel, south-east of Winterswijk', '18th-century scholten estate with avenues and ponds · half woodland: old oaks and Scots pine · celebrated fungi paradise of KNNV and IVN', 'list 36 · no. 841'],
 'loc': '📍 Junction Ratumseweg (N820)/Gossinkweg or Vredenseweg/Gossinkweg, Winterswijk-Henxel — footpaths across the estate; Döttinkrade route and Scholtenpad Ratum pass by',
 'desc': 'Gossink <b>estate</b> at Henxel lies a stone’s throw from the centre of Winterswijk and is still a world apart: an <b>18th-century scholten estate</b> with the fine farms <b>Gossink and Nieuw Gossink</b>, surrounded by a varied whole of <b>wood avenues, ponds, arable and meadow</b>. Half the estate is woodland — <b>tall oaks</b> alternating with <b>old Scots-pine wood</b> — and between the parcels run streams and hedgerows. That variety makes Gossink beloved above all as a <b>fungi paradise</b>: the KNNV and IVN East-Achterhoek working groups come here every autumn on excursion, seeking rare species that each choose their own spot — light or dark, moist or dry, wood or meadow. Footpaths across the estate link into the <b>Döttinkrade route</b> and the <b>Scholtenpad Ratum</b>; the Ratumse beek carries the estate’s water towards town. Walk the Steengroeve route and you pass the estate just before the land drops to the quarry and the Willinksbeek.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Nov</b> (fungi excursions), Apr–May (spring flora under the oaks), Jun (ponds full of life)<br>\\n    <b>Best time of day:</b> After rain — fungi at their best.',
 'why': ['The <b>18th-century scholten estate</b> with its two farms.', '<b>Wood avenues and ponds</b> in a park-like whole.', 'The <b>old oak and Scots-pine woods</b> as a fungi paradise.', 'The position on the <b>Döttinkrade route and Scholtenpad</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> under the old oaks.', '<span class="months">Jun–Jul</span> 💧 <b>Ponds and streams</b> full of life.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> — KNNV/IVN excursions.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> in the avenue system.'],
 'wild': ['🍄 Fungi paradise', '🌳 Old oaks and Scots pine', '💧 Ponds and Ratumse beek', '🏡 Gossink and Nieuw Gossink', '🥾 Döttinkrade route'],
 'trail': ['Start at the <b>Ratumseweg/Gossinkweg junction</b> for the paths across the estate.', 'Follow the <b>Döttinkrade route</b> or the <b>Scholtenpad Ratum</b> (19 km).', 'Combine with the <b>Steengroeve walk</b> (± 15 km) towards the Willinksbeek.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Partly agricultural — follow the paths · 🚶 Loop ± 4–6 km'
}))

C.append(mk.card(2123, 'De Horst', {
 'tags': ['Gelderland · Horstweg bij Brinkheurne/Ratum, Winterswijk', 'coulissenlandschap rond de Horstweg: kruidenrijk grasland van de Horstermaat met oude houtwallen, bosjes en poelen', 'list 36 · no. 842'],
 'loc': '📍 Horstweg (onverhard), Brinkheurne — rand van Winterswijk bij de Pelkwijk; landwegen en wandelnetwerk door houtwallen en weilanden',
 'desc': 'Aan de onverharde <b>Horstweg</b>, waar Winterswijk overgaat in de buurtschap Brinkheurne, ligt het gebied <b>De Horst</b>: een stil coulissenlandschap van houtwallen, weilanden, akkers en bosjes rond de oude boerderijen van de Horst en het naburige Hilbelink (kaart 2124). Het openbare hart is de <b>Horstermaat</b>, een terrein van de Van der Lugt Stichting: <b>kruidenrijk grasland</b> dat in <b>2016</b> bewust werd verschraald en omgevormd tot soortenrijk kruiden- en faunagrastand, omringd door <b>oudere houtwallen</b> en afgewisseld met <b>bosjes en poelen</b>. In de loop van de twintigste eeuw werd aan de rand van dit gebied de wijk <b>Pelkwijk</b> gebouwd — maar de landschappelijke verscheidenheid achter de dijk bleef. Wie hier loopt ziet het Achterhoekse kleinschalige landschap op zijn zuiverst: elzen in de natte hoeken, eiken op de wallen, en overal de wisselwerking van gras, hout en water die dit deel van het Nationaal Landschap Winterswijk draagt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (kruidenrijk grasland in bloei), mrt–apr (amfibieën in de poelen), sep–okt (herfstlicht op de houtwallen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en vogelzang.',
 'why': ['De <b>Horstermaat</b> met zijn verschraalde kruidenrijke graslanden.', '<b>Oude houtwallen, bosjes en poelen</b> aan de Horstweg.', 'De overgang van <b>stad naar buurtschap</b> bij de Pelkwijk.', 'Het <b>zuivere kleinschalige coulissenlandschap</b> van Brinkheurne.'],
 'phen': ['<span class="months">Mrt–Apr</span> 🐸 <b>Amfibieëntrek</b> naar de poelen.', '<span class="months">Mei–Jun</span> 🌸 <b>Kruidenrijk grasland</b> in volle bloei.', '<span class="months">Nov–Feb</span> 🌫️ <b>Morgennevel</b> tussen de wallen.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstlicht</b> over wallen en weilanden.'],
 'wild': ['🌾 Kruidenrijk grasland (Horstermaat)', '🌳 Oude houtwallen', '💧 Poelen voor amfibieën', '🏡 Scholtenhoeves aan de Horstweg', '🌃 Stadrand-natuur bij de Pelkwijk'],
 'trail': ['Wandel de <b>Horstweg</b> en de landwegen eromheen (± 4 km).', 'Zoek de <b>poelen en houtwallen</b> van de Horstermaat.', 'Combineer met <b>Hilbelink</b> (kaart 2124) en het Brinkheurne-landschap.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Terreinen deels privé — paden volgen · 🚶 Rondje ± 4–5 km'
}, {
 'tags': ['Gelderland · Horstweg at Brinkheurne/Ratum, Winterswijk', 'bocage along the Horstweg: herb-rich grassland of the Horstermaat with old hedgerows, copses and ponds', 'list 36 · no. 842'],
 'loc': '📍 Horstweg (unmetalled), Brinkheurne — edge of Winterswijk by the Pelkwijk quarter; country lanes and walking network through hedgerows and meadows',
 'desc': 'On the unmetalled <b>Horstweg</b>, where Winterswijk gives way to the Brinkheurne hamlet, lies the <b>De Horst</b> area: a quiet bocage of hedgerows, meadows, fields and copses around the old farms of the Horst and neighbouring Hilbelink (card 2124). Its public heart is the <b>Horstermaat</b>, a Van der Lugt Stichting reserve: <b>herb-rich grassland</b> deliberately impoverished in <b>2016</b> and turned into species-rich herb and fauna turf, ringed by <b>older hedgerows</b> and alternating with <b>copses and ponds</b>. In the wider sweep of the twentieth century the <b>Pelkwijk</b> estate was built at the edge of this area — but the landscape variety behind it survived. Walk here and you see the small-scale Achterhoek landscape at its purest: alders in the wet corners, oaks on the banks, and everywhere the interplay of grass, timber and water that carries this part of the National Landscape Winterswijk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (herb-rich grassland in flower), Mar–Apr (amphibians in the ponds), Sep–Oct (autumn light on the hedgerows)<br>\\n    <b>Best time of day:</b> Morning — dew and birdsong.',
 'why': ['The <b>Horstermaat</b> with its impoverished herb-rich grasslands.', '<b>Old hedgerows, copses and ponds</b> along the Horstweg.', 'The transition from <b>town to hamlet</b> at the Pelkwijk.', 'The <b>pure small-scale bocage</b> of Brinkheurne.'],
 'phen': ['<span class="months">Mar–Apr</span> 🐸 <b>Amphibian migration</b> to the ponds.', '<span class="months">May–Jun</span> 🌸 <b>Herb-rich grassland</b> in full flower.', '<span class="months">Nov–Feb</span> 🌫️ <b>Morning mist</b> between the banks.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn light</b> over banks and meadows.'],
 'wild': ['🌾 Herb-rich grassland (Horstermaat)', '🌳 Old hedgerows', '💧 Ponds for amphibians', '🏡 Scholten farms on the Horstweg', '🌃 Town-edge nature at the Pelkwijk'],
 'trail': ['Walk the <b>Horstweg</b> and the lanes around it (± 4 km).', 'Seek the <b>ponds and hedgerows</b> of the Horstermaat.', 'Combine with <b>Hilbelink</b> (card 2124) and the Brinkheurne landscape.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Grounds partly private — follow the paths · 🚶 Loop ± 4–5 km'
}))

C.append(mk.card(2124, 'Hilbelink', {
 'tags': ['Gelderland · Horstweg 10, Brinkheurne (Winterswijk)', 'rijksmonumentale scholtenboerderij uit de 19e eeuw met passantenhuisje · klein landgoedbos, leverancier van een record-eik op de veiling van Schaarsbergen', 'list 36 · no. 843'],
 'loc': '📍 Horstweg 10, Brinkheurne — passantenhuisje bij de boerderij; landwegen richting De Horst (kaart 2123) en het Brinkheurne-coulissenlandschap',
 'desc': 'De <b>scholtenboerderij Hilbelink</b> aan de Horstweg is een statige hallenhuisboerderij uit de tweede helft van de <b>19e eeuw</b>, gebouwd als boerderij van het langsdeeltype waarbij het voorste deel als woonhuis diende en de oogst door de grote schuurdeuren naar binnen reed — vandaag een <b>rijksmonument</b> met een <b>passantenhuisje</b> waar wandelaars en fietsers terecht kunnen. Rond de hoeve ligt het kleine <b>landgoed Hilbelink</b>: bescheiden bospercelen die bij het jachtgebied van ± 250 bunder hoorden dat de familie Van Eerden hier beheerde, met ruimte voor bosbouw en wild. De bomen van Brinkheurne waren van nationale klasse: de <b>duurste eik</b> die de boswachter zich van de houtveiling van Schaarsbergen herinnerde — een superboom van <b>5,6 kubieke meter</b> die <b>560 euro per kuub</b> opbracht — kwam van het landgoed Hilbelink. Het <b>Scholtenpad Ratum</b> voert langs het erf; samen met de Horstermaat (kaart 2123), het Buskersbos en de Borkense Baan vormt dit de wandelstreek Brinkheurne, het groene zuidelijke portaal van Winterswijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (vogelzang rond het erf), sep–okt (paddenstoelen in de bospercelen), dec–feb (winterstilte op de landwegen)<br>\\n    <b>Beste tijd van de dag:</b> Middag — koffie in het passantenhuisje.',
 'why': ['De <b>rijksmonumentale scholtenboerderij</b> met passantenhuisje.', 'Het verhaal van de <b>duurste eik van de veiling</b> (5,6 m³, 560 euro per kuub).', 'Het <b>bescheiden landgoedbos</b> van het oude jachtgebied.', 'De ligging aan het <b>Scholtenpad Ratum</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Zangvogels</b> rond erf en bosrand.', '<span class="months">Jun–Jul</span> 🌾 <b>Hooilandgeur</b> op de landwegen.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in de oude bospercelen.', '<span class="months">Dec–Feb</span> ❄️ <b>Winterwandeling</b> naar het Buskersbos.'],
 'wild': ['🏡 Rijksmonument-scholtenhoeve', '🌳 Landgoedbos van Brinkheurne', '🪓 Duurste eik van Schaarsbergen', '☕ Passantenhuisje', '🦌 Jachtgebied van ± 250 bunder'],
 'trail': ['Bezoek het <b>passantenhuisje</b> aan de Horstweg 10.', 'Wandel het <b>Scholtenpad Ratum</b> (19 km) langs erf en coulissen.', 'Combineer met <b>De Horst</b> (kaart 2123) en het <b>Buskersbos</b> (kaart 2128).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Erf en bos deels privé — paden volgen · 🚶 Rondje ± 4–6 km'
}, {
 'tags': ['Gelderland · Horstweg 10, Brinkheurne (Winterswijk)', '19th-century scholten farm, a listed monument, with a wayfarers’ cottage · small estate wood, supplier of a record oak at the Schaarsbergen auction', 'list 36 · no. 843'],
 'loc': '📍 Horstweg 10, Brinkheurne — wayfarers’ cottage at the farm; country lanes towards De Horst (card 2123) and the Brinkheurne bocage',
 'desc': 'The <b>scholten farm Hilbelink</b> on the Horstweg is a stately hall-house farm from the second half of the <b>19th century</b>, built as a longitudinal-type farmhouse whose front part served as dwelling while the harvest rolled in through the great barn doors — today a <b>listed monument</b> with a <b>wayfarers’ cottage</b> where walkers and cyclists are welcome. Around it lies the small <b>Hilbelink estate</b>: modest woodland parcels belonging to the ± 250-bunder hunting ground the Van Eerden family managed here, with room for forestry and game. The trees of Brinkheurne were of national class: the <b>most expensive oak</b> the forester remembered from the Schaarsbergen timber auction — a champion of <b>5.6 cubic metres</b> fetching <b>560 euros per cubic metre</b> — came from the Hilbelink estate. The <b>Scholtenpad Ratum</b> passes the farmyard; together with the Horstermaat (card 2123), the Buskersbos and the Borkense Baan this forms the Brinkheurne walking country, the green southern gateway of Winterswijk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birds around the farmyard), Sep–Oct (fungi in the woodland parcels), Dec–Feb (winter silence on the lanes)<br>\\n    <b>Best time of day:</b> Midday — coffee at the wayfarers’ cottage.',
 'why': ['The <b>listed scholten farm</b> with its wayfarers’ cottage.', 'The story of the <b>auction’s most expensive oak</b> (5.6 m³, 560 euros per cubic metre).', 'The <b>modest estate wood</b> of the old hunting ground.', 'The position on the <b>Scholtenpad Ratum</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Songbirds</b> around farmyard and wood edge.', '<span class="months">Jun–Jul</span> 🌾 <b>Hay scent</b> on the lanes.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old woodland parcels.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter walk</b> to the Buskersbos.'],
 'wild': ['🏡 Listed scholten farm', '🌳 Brinkheurne estate wood', '🪓 Dearest oak of Schaarsbergen', '☕ Wayfarers’ cottage', '🦌 ± 250-bunder hunting ground'],
 'trail': ['Visit the <b>wayfarers’ cottage</b> at Horstweg 10.', 'Walk the <b>Scholtenpad Ratum</b> (19 km) past farmyard and bocage.', 'Combine with <b>De Horst</b> (card 2123) and the <b>Buskersbos</b> (card 2128).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Farmyard and wood partly private — follow the paths · 🚶 Loop ± 4–6 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2124)
mk.check()
