# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2090, 'Heerlijkheid Leur', {
 'tags': ['Gelderland · Leur (Land van Maas en Waal)', 'Particulier landgoed sinds 1748 (ruim 250 ha) met landhuis uit 1778 · statige lanen, motte en middeleeuwse kerk · Leurse Bos in Engelse landschapsstijl', 'list 36 · no. 809'],
 'loc': '📍 Puitsestraat 3, Leur — startpunt bezoekerscentrum Land van de Heerlijkheden, Van Balverenlaan 1b · wandelroute Heerlijkheid Leur en Hernense Bos 8 km (niet gemarkeerd, folder beschikbaar)',
 'desc': 'In het hart van het Land van Maas en Waal ligt de <b>Heerlijkheid Leur</b>: een landgoed van ruim <b>250 hectare</b> dat al sinds <b>1748</b> in particulier bezit is — nog altijd bij dezelfde familie. Midden in het parkbos staat geen kasteel maar een sober, statig <b>landhuis</b> met classicistische motieven, gebouwd in <b>1778</b> in opdracht van Christaan W.H.E. van Verschuer. Het goed wordt gedragen door <b>statige lanen</b> met oude eiken en beuken: het <b>Leurse Bos</b> werd eind 18e eeuw aangelegd in strakke, formele stijl en in de 19e eeuw uitgebreid in de <b>Engelse landschapsstijl</b>, met slingerende lanen, boomgroepen en open weidegronden. Langs de zwierige landwegen staan <b>oude lindebomen</b>; in de weilanden groeien kruiden en klaver, en in de bossen klinken specht en koekoek. In het gehucht Leur zelf staan de <b>middeleeuwse kerk</b> uit de 13e/14e eeuw en ernaast de <b>motte</b> — een kunstmatige heuvel waar in de 11e eeuw vermoedelijk een houten burcht stond, later dienend als vliedberg bij overstromingen. De Elst, het riviertje van het goed, voedde ooit de kasteelgracht. Met de Maalderij, de boswinkel en de leerbedrijven is Leur een levend landgoed — en een van de weinige heerlijkheden die haar karakter mocht behouden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (lindes in blad, spechten), sep–okt (herfstkleur in het Leurse Bos)<br>\\n    <b>Beste tijd van de dag:</b> Late middag — licht door de linde-lanen.',
 'why': ['Particulier landgoed <b>sinds 1748</b> — ruim 250 ha, nog altijd dezelfde familie.', 'Het <b>landhuis uit 1778</b> midden in het parkbos.', 'De <b>motte</b> bij de middeleeuwse kerk — heuvel met houten burcht en vliedberg-verleden.', 'Het <b>Leurse Bos</b>: formeel 18e-eeuws, Engels 19e-eeuws.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌳 <b>Lindes en eiken</b> in jong blad.', '<span class="months">Apr–Jun</span> 🎵 <b>Specht en koekoek</b> in de bossen.', '<span class="months">Jun–Jul</span> 🌾 <b>Kruidenrijke weilanden</b> met klaver in bloei.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> langs de slingerlanen.'],
 'wild': ['🏡 Landhuis uit 1778', '🌳 Statige eiken- en beuken-lanen', '⛪ Middeleeuwse kerk van Leur', '⛰️ Motte met vliedberg-geschiedenis', '💧 De Elst — beekje van het goed'],
 'trail': ['Loop de <b>8 km-route Heerlijkheid Leur en Hernense Bos</b> (folder bij bezoekerscentrum).', 'Bezoek de <b>motte en de kerk</b> in het gehucht Leur.', 'Start of slot bij de <b>Maalderij</b> op het goed.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Levend landgoed — landbouw en doorgaand verkeer respecteren · 🚶 Route 8 km'
}, {
 'tags': ['Gelderland · Leur (Land van Maas en Waal)', 'Private estate since 1748 (over 250 ha) with an 1778 country house · stately avenues, motte and medieval church · Leurse Bos in English landscape style', 'list 36 · no. 809'],
 'loc': '📍 Puitsestraat 3, Leur — starting point Land van de Heerlijkheden visitor centre, Van Balverenlaan 1b · Heerlijkheid Leur and Hernense Bos walking route 8 km (unmarked, folder available)',
 'desc': 'In the heart of the Land van Maas en Waal lies the <b>Heerlijkheid Leur</b>: an estate of over <b>250 hectares</b> in private hands since <b>1748</b> — still with the same family. In the middle of the park woodland stands no castle but a sober, stately <b>country house</b> with classical motifs, built in <b>1778</b> for Christaan W.H.E. van Verschuer. The estate is carried by <b>stately avenues</b> of old oak and beech: the <b>Leurse Bos</b> was laid out at the end of the 18th century in strict formal style and extended in the 19th century in the <b>English landscape style</b>, with winding lanes, tree groups and open meadows. Along the sweeping country roads stand <b>old lime trees</b>; in the pastures grow herbs and clover, and in the woods sound woodpecker and cuckoo. In the hamlet of Leur itself stand the <b>medieval church</b> of the 13th/14th century and beside it the <b>motte</b> — an artificial mound where a wooden keep probably stood in the 11th century, later serving as a refuge mound in floods. The Elst, the estate’s little river, once fed the castle moat. With its mill-house, wood shop and training farms, Leur is a living estate — and one of the few lordships that kept its character.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (limes in leaf, woodpeckers), Sep–Oct (autumn colour in the Leurse Bos)<br>\\n    <b>Best time of day:</b> Late afternoon — light through the lime avenues.',
 'why': ['Private estate <b>since 1748</b> — over 250 ha, still the same family.', 'The <b>1778 country house</b> in the park woodland.', 'The <b>motte</b> by the medieval church — mound with a wooden-keep and refuge past.', 'The <b>Leurse Bos</b>: formal 18th-century, English 19th-century.'],
 'phen': ['<span class="months">Apr–May</span> 🌳 <b>Limes and oaks</b> in young leaf.', '<span class="months">Apr–Jun</span> 🎵 <b>Woodpecker and cuckoo</b> in the woods.', '<span class="months">Jun–Jul</span> 🌾 <b>Herb-rich pastures</b> with clover in flower.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> along the winding lanes.'],
 'wild': ['🏡 Country house of 1778', '🌳 Stately oak and beech avenues', '⛪ Medieval church of Leur', '⛰️ Motte with refuge-mound history', '💧 De Elst — the estate’s stream'],
 'trail': ['Walk the <b>8-km Heerlijkheid Leur and Hernense Bos route</b> (folder at the visitor centre).', 'Visit the <b>motte and the church</b> in the hamlet of Leur.', 'Start or finish at the <b>Maalderij</b> on the estate.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Living estate — respect farming and through traffic · 🚶 Route 8 km'
}))

C.append(mk.card(2091, 'Balgoyse Meer', {
 'tags': ['Gelderland · Balgoy en Keent (oude Maasbedding)', 'Meer in de afgesneden Maasmeander bij Keent · kuddes runderen en paarden als grote grazers · geschiedenis van Balgoy en Keent, tot 1923 één gemeente', 'list 36 · no. 810'],
 'loc': '📍 Ten zuiden van Balgoy in de oude Maasbedding bij het buurtschap Keent · te bereiken via de Hoeveweg (Balgoy) en de Oude Maasweg (Keent); oversteek naar Keent via de John F. Thompsonbrug',
 'desc': 'Het <b>Balgoyse Meer</b> ligt in de <b>oude bedding van de Maas</b> ten zuiden van Balgoy — een landschap waarin de eeuwenoude twist tussen mens en rivier nog af te lezen is. De meanderende Maas sneed hier eeuwenlang Balgoy en het buurtschap <b>Keent</b> van de wereld; de twee vormden sinds de middeleeuwen één <b>heerlijkheid</b> en tot <b>1923</b> zelfs één gemeente. Eind jaren dertig werd de Maas <b>gekanaliseerd</b>: de nieuwe rivierarm kwam precies tussen beide dorpen te liggen, de standerdmolen van Keent (al in 1550 vermeld) verloor zijn functie en werd in 1938 afgebroken, en de veerpont van 1938 tot 1952 was de laatste directe verbinding. De oude bedding bleef als slaper achter — om in recente jaren <b>deels weer te worden uitgegraven en op de rivier aangesloten</b>, wat de waterstand op de Maas verlaagt en een mooi natuurgebied schiep. Op de <b>Keentse oever</b> lopen <b>kuddes runderen en paarden</b> die het gebied open houden voor waterberging; over het water is de <b>kerktoren van Balgoy</b> goed zichtbaar, en de <b>Maasheggen</b> van de streek prijken op de dijk. Wie hier loopt, wandelt door een dorp dat van Brabant naar Gelderland verhuisde: tot de elfde eeuw lag Balgoy zuidelijk van de rivier.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (weidevogels, bloeiende heggen), nov–mrt (watervogels op het meer)<br>\\n    <b>Beste tijd van de dag:</b> Avond — kuddes aan het water, de toren van Balgoy in tegenlicht.',
 'why': ['De <b>oude Maasbedding</b> als meer — de kanalisatie van ± 1938 afleesbaar in het landschap.', '<b>Kuddes runderen en paarden</b> op de Keentse oevers.', 'De dubbelgeschiedenis van <b>Balgoy en Keent</b>: één heerlijkheid, één gemeente tot 1923.', 'De <b>Maasheggen</b> en de kerktoren van Balgoy over het water.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Weidevogels</b> in de uiterwaardjes.', '<span class="months">Apr–Mei</span> 🌳 <b>Maasheggen</b> in blad en bloei.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> op het meer.', '<span class="months">Heel jaar</span> 🐎 <b>Grote grazers</b> langs de oevers.'],
 'wild': ['🐎 Runderen en paarden op Keent', '🌊 Oude Maasmeander als meer', '🌳 Maasheggen op de dijk', '⛪ Kerktoren van Balgoy als landmark', '🕳️ Wielen en uiterwaardjes'],
 'trail': ['Wandel de <b>Balgoyse ommetjes</b> (4,7 en 6,4 km) vanaf de Oude Toren over dijk en Herreweg.', 'Steek bij gelegenheid de <b>Thompsonbrug</b> over naar Keent voor de grazers.', 'Combineer met de <b>Maasbandijk</b> richting Grave.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Grote grazers — afstand houden; agrarisch gebied · 🚶 Ommetjes 4,7–6,4 km'
}, {
 'tags': ['Gelderland · Balgoy and Keent (old Maas bed)', 'Lake in the cut-off Maas meander at Keent · herds of cattle and horses as large grazers · history of Balgoy and Keent, one municipality until 1923', 'list 36 · no. 810'],
 'loc': '📍 South of Balgoy in the old Maas bed by the hamlet of Keent · reach via the Hoeveweg (Balgoy) and Oude Maasweg (Keent); crossing to Keent via the John F. Thompson bridge',
 'desc': 'The <b>Balgoyse Meer</b> lies in the <b>old bed of the Maas</b> south of Balgoy — a landscape in which the centuries-old contest between people and river can still be read. The meandering Maas cut Balgoy and the hamlet of <b>Keent</b> off from the world for centuries; the two formed one <b>lordship</b> since the Middle Ages and even one <b>municipality until 1923</b>. At the end of the 1930s the Maas was <b>canalised</b>: the new river arm came to lie exactly between the two villages, the Keent post mill (recorded as early as 1550) lost its function and was demolished in 1938, and the ferry of 1938 to 1952 was the last direct link. The old bed remained as a sleeper — until in recent years it was <b>partly excavated again and reconnected to the river</b>, lowering Maas water levels and creating fine nature. On the <b>Keent bank</b> <b>herds of cattle and horses</b> keep the ground open for water storage; across the water the <b>church tower of Balgoy</b> stands clear, and the <b>Maas hedges</b> of the region deck the dike. Walk here and you stroll through a village that moved from Brabant to Gelderland: until the eleventh century Balgoy lay south of the river.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds, flowering hedges), Nov–Mar (waterfowl on the lake)<br>\\n    <b>Best time of day:</b> Evening — herds at the water, Balgoy tower in backlight.',
 'why': ['The <b>old Maas bed</b> as a lake — the ± 1938 canalisation readable in the landscape.', '<b>Herds of cattle and horses</b> on the Keent banks.', 'The double history of <b>Balgoy and Keent</b>: one lordship, one municipality until 1923.', 'The <b>Maas hedges</b> and Balgoy church tower across the water.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Meadow birds</b> in the small floodplains.', '<span class="months">Apr–May</span> 🌳 <b>Maas hedges</b> in leaf and flower.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> on the lake.', '<span class="months">All year</span> 🐎 <b>Large grazers</b> along the banks.'],
 'wild': ['🐎 Cattle and horses on Keent', '🌊 Old Maas meander as lake', '🌳 Maas hedges on the dike', '⛪ Balgoy church tower as landmark', '🕳️ Breach pools and small floodplains'],
 'trail': ['Walk the <b>Balgoy loops</b> (4.7 and 6.4 km) from the Old Tower over dike and Herreweg.', 'Cross the <b>Thompson bridge</b> to Keent for the grazers when you can.', 'Combine with the <b>Maas dike</b> towards Grave.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Large grazers — keep your distance; agricultural land · 🚶 Loops 4.7–6.4 km'
}))

C.append(mk.card(2092, 'Molenwiel', {
 'tags': ['Gelderland · Nederasselt (Maasoever)', 'Wiel met de Maasmolen uit 1741 (voorganger al in 1301 vermeld) · struinpad langs de Maas met Maasheggen en dassenburcht', 'list 36 · no. 811'],
 'loc': '📍 Molenwiel bij Nederasselt, net buiten de Maasdijk — te voet via de Trage Tocht Nederasselt (13 km) of kort vanaf het dorp · parkeeren bij de kerken van Nederasselt',
 'desc': 'Vlak voor het dorpje <b>Nederasselt</b> ligt het <b>Molenwiel</b> rustig en vredig aan de dijkvoet: een <b>wiel</b> — een kolk die door een oude <b>dijkdoorbraak</b> werd uitgeschuurd — waarop de <b>Maasmolen</b> staat, een gesloten standerdmolen uit <b>1741</b>. De borden op de dijk vertellen het verhaal: een eerdere molen, al vermeld in <b>1301</b>, werd bij een dijkdoorbraak weggespoeld; de huidige molen bouwde men meer landinwaarts, en de letters <b>HH</b> in de windvaan verwijzen naar de molenaarsfamilie Heijnen van de 19e eeuw. Rondom ligt een van de lieflijkste stukjes van het Rijk van Nijmegen: kilometers <b>struinpad langs de Maas</b> — geen pad maar een brede strook weiland waar schapen grazen — met de <b>Maasheggen</b> als levend erfgoed, uitzicht op de <b>sluis en de John S. Thompsonbrug</b> bij Grave, en in het boerenland een oude <b>dassenburcht</b>. Nabij liggen natuurgebied <b>De Kadans</b> (hooiland met stinzenbosje), de standerdmolen <b>Zeldenrust</b> van Overasselt (na storm 1972 in 1981 herbouwd) en het <b>Kroonwerk De Coehoorn</b>, restant van de Zuiderwaterlinie waarmee Menno van Coehoorn Grave verdedigde. Het Molenwiel zelf is een geliefd viswater — het hele gebied ademt de rust van het rivierenlandschap tussen Nederasselt en Overasselt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (schapen op de uiterwaard, heggen in blad), sep–okt (mist boven het wiel)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — de molen in de nevel.',
 'why': ['De <b>Maasmolen uit 1741</b> op zijn wiel — met een voorganger uit 1301.', 'Het <b>struinpad langs de Maas</b>: vrij slenteren over de uiterwaard.', 'De <b>Maasheggen</b> en de dassenburcht in het boerenland.', 'De <b>dijkdoorbraak-geschiedenis</b> die het wiel schiep.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐑 <b>Schapen</b> grazen de struinstrook af.', '<span class="months">Apr–Mei</span> 🌳 <b>Maasheggen</b> in blad en bloei.', '<span class="months">Sep–Okt</span> 🌫️ <b>Ochtendnevel</b> boven wiel en molen.', '<span class="months">Heel jaar</span> 🦡 <b>Dassenburcht</b> langs de Trage Tocht.'],
 'wild': ['⚙️ Maasmolen (1741, windvaan HH)', '🌊 Wiel door dijkdoorbraak', '🌳 Maasheggen als levend erfgoed', '🦡 Dassenburcht in het boerenland', '🐟 Visrijk wiel'],
 'trail': ['Loop de <b>Trage Tocht Nederasselt</b> (13 km) langs wiel, Maas, De Kadans en Zeldenrust.', 'Struin de <b>Maasoever</b> richting de sluis en Thompsonbrug.', 'Bezoek het <b>Kroonwerk De Coehoorn</b> aan de overzijde bij Grave.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Struinpad kan hoog staan; geen duidelijk pad — goed schoeisel · 🚶 Trage Tocht 13 km'
}, {
 'tags': ['Gelderland · Nederasselt (Maas bank)', 'Breach pool with the 1741 Maasmolen (predecessor recorded in 1301) · striding path along the Maas with hedges and a badger sett', 'list 36 · no. 811'],
 'loc': '📍 Molenwiel at Nederasselt, just outside the Maas dike — on foot via the Trage Tocht Nederasselt (13 km) or short from the village · parking by the churches of Nederasselt',
 'desc': 'Just before the little village of <b>Nederasselt</b> lies the <b>Molenwiel</b>, quiet and peaceful at the foot of the dike: a <b>breach pool</b> scoured out by an old <b>dike burst</b>, on which stands the <b>Maasmolen</b>, a closed post mill of <b>1741</b>. The signs on the dike tell the story: an earlier mill, recorded as early as <b>1301</b>, was washed away in a dike burst; the present mill was built further inland, and the letters <b>HH</b> on the wind vane recall the 19th-century miller family Heijnen. Around it lies one of the loveliest corners of the Rijk van Nijmegen: kilometres of <b>striding path along the Maas</b> — not a path but a broad strip of meadow where sheep graze — with the <b>Maas hedges</b> as living heritage, views of the <b>lock and the John S. Thompson bridge</b> at Grave, and in the farmland an old <b>badger sett</b>. Nearby lie the <b>De Kadans</b> nature reserve (hay meadow with a stinzen wood), the Overasselt post mill <b>Zeldenrust</b> (rebuilt in 1981 after the 1972 storm) and <b>Kroonwerk De Coehoorn</b>, remnant of the Zuider Waterline with which Menno van Coehoorn defended Grave. The Molenwiel itself is a favourite fishing water — the whole breathes the calm of the river landscape between Nederasselt and Overasselt.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (sheep on the floodplain, hedges in leaf), Sep–Oct (mist over the pool)<br>\\n    <b>Best time of day:</b> Early morning — the mill in the mist.',
 'why': ['The <b>Maasmolen of 1741</b> on its pool — with a predecessor of 1301.', 'The <b>striding path along the Maas</b>: free wandering over the floodplain.', 'The <b>Maas hedges</b> and the badger sett in the farmland.', 'The <b>dike-burst history</b> that created the pool.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐑 <b>Sheep</b> grazing the striding strip.', '<span class="months">Apr–May</span> 🌳 <b>Maas hedges</b> in leaf and flower.', '<span class="months">Sep–Oct</span> 🌫️ <b>Morning mist</b> over pool and mill.', '<span class="months">All year</span> 🦡 <b>Badger sett</b> along the Trage Tocht.'],
 'wild': ['⚙️ Maasmolen (1741, vane HH)', '🌊 Breach pool from a dike burst', '🌳 Maas hedges as living heritage', '🦡 Badger sett in the farmland', '🐟 Fish-rich pool'],
 'trail': ['Walk the <b>Trage Tocht Nederasselt</b> (13 km) past pool, Maas, De Kadans and Zeldenrust.', 'Stride the <b>Maas bank</b> towards the lock and Thompson bridge.', 'Visit <b>Kroonwerk De Coehoorn</b> across the water at Grave.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Striding path can be high-grown; no clear path — good footwear · 🚶 Trage Tocht 13 km'
}))

C.append(mk.card(2093, 'Vennengebied', {
 'tags': ['Gelderland · Hatert en Overasselt (ten zuidwesten van Nijmegen)', 'Hatertse en Overasseltse Vennen: ± 520 ha met ± 20 vennen op rivierduin · zonnedauw en veenmos · Sint-Walrickkapel en Koortsboom', 'list 36 · no. 812'],
 'loc': '📍 Tussen Nijmegen, Wijchen en Overasselt — toegangen vanaf de Sint-Walrickweg en de wegen rond Blankenberg/De Schatkuil · wandel- en fietsroutes door vennen, heide en bos',
 'desc': 'Het <b>Vennengebied</b> — de <b>Hatertse en Overasseltse Vennen</b> — is een ± <b>520 hectare</b> groot landschap van zo’n <b>twintig benoemde vennen</b>, rivierduinen, heidevelden en bossen ten zuidwesten van Nijmegen. De vennen zijn jonger dan ze lijken: ze ontstonden in de <b>19e eeuw</b> door zandafgravingen voor de spoorweg en de aanloopdijk van de <b>spoorbrug van Nijmegen</b>. Het zijn <b>echte vennen</b>: waterpartijen die niet door grondwater maar door <b>mineraalarm regenwater</b> worden gevoed, met een flora van <b>kleine en ronde zonnedauw</b>, <b>veenmos</b> en vegetaties uit het dophei-verbond. Sommige vennen — het <b>Meeuwenven</b> voorop — zijn geliefde broedplaatsen voor watervogels. Staatsbosbeheer zet <b>schapen en Schotse hooglanders</b> in om de vegetatie open te houden; in 2013 werden 36 hectare bosgekapt en omgezet in heide en vier dichtgegroeide vennen uitgebaggerd. In het gebied leven <b>das, ree, vos en konijn</b>. Aan de rand staat de <b>15e-eeuwse ruïne van de Sint-Walrickkapel</b>, gewijd aan de beschermheilige van koortslijders, met ernaast de <b>Koortsboom</b>: een oude zomereik waarvan de schors eeuwenlang werd afgesneden tegen koorts. Scoutinggroepen, wandelaars en fietsers delen het gebied — en de provincie wil het via de "Groen Kluis" weer aan Heumensoord koppelen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Aug</b> (vennen op hun kleurrijkst, zonnedauw), apr–mei (broedvogels op het Meeuwenven)<br>\\n    <b>Beste tijd van de dag:</b> Late middag — zon laag over de vennen.',
 'why': ['± <b>20 vennen op rivierduin</b> — regenwatervennen met zonnedauw en veenmos.', 'De <b>ontstaansgeschiedenis</b>: zand voor de spoorbrug van Nijmegen (19e eeuw).', 'De <b>Sint-Walrickkapel</b> en de <b>Koortsboom</b> van Overasselt.', '<b>Schapen en Schotse hooglanders</b> als beheerders van heide en venoevers.'],
 'phen': ['<span class="months">Jun–Aug</span> 🌺 <b>Zonnedauw en veenmos</b> aan de venoevers.', '<span class="months">Apr–Jun</span> 🪿 <b>Broedvogels</b> op het Meeuwenven.', '<span class="months">Jul–Sep</span> 🦗 <b>Heide en dophei</b> in bloei (na 2013 verdubbeld).', '<span class="months">Heel jaar</span> 🐑 <b>Schapen en hooglanders</b> op de heide.'],
 'wild': ['🌺 Kleine en ronde zonnedauw', '🐑 Schapen en Schotse hooglanders', '🦡 Das · ree · vos', '⛪ Sint-Walrickkapel-ruïne (15e eeuw)', '🌳 Koortsboom van Overasselt'],
 'trail': ['Wandel de <b>vennen-rondes</b> vanaf de Sint-Walrickweg door heide en bos.', 'Bezoek de <b>kapelruïne en de Koortsboom</b> aan de rand van het gebied.', 'Combineer met het <b>Meeuwenven</b> (kijktje in het voorjaar) en Heumensoord.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Venoever gevoelig — niet betreden; scoutingterreinen respecteren · 🚶 Rondes 4–10 km'
}, {
 'tags': ['Gelderland · Hatert and Overasselt (south-west of Nijmegen)', 'Hatertse and Overasseltse Vennen: ± 520 ha with ± 20 pools on river dunes · sundew and sphagnum · St Walrick chapel ruin and Fever Tree', 'list 36 · no. 812'],
 'loc': '📍 Between Nijmegen, Wijchen and Overasselt — accesses from the Sint-Walrickweg and the roads around Blankenberg/De Schatkuil · walking and cycling routes through pools, heath and woodland',
 'desc': 'The <b>Vennengebied</b> — the <b>Hatertse and Overasseltse Vennen</b> — is a ± <b>520-hectare</b> landscape of some <b>twenty named pools</b>, river dunes, heaths and woods south-west of Nijmegen. The pools are younger than they look: they arose in the <b>19th century</b> from sand digging for the railway and the approach bank of the <b>Nijmegen railway bridge</b>. They are <b>true vennen</b>: bodies of water fed not by groundwater but by <b>mineral-poor rain water</b>, with a flora of <b>round-leaved and great sundew</b>, <b>sphagnum</b> and vegetation of the crowberry heath alliance. Some pools — the <b>Meeuwenven</b> foremost — are beloved breeding places for water birds. Staatsbosbeheer deploys <b>sheep and Scottish highlanders</b> to keep the vegetation open; in 2013, 36 hectares of woodland were felled and turned to heath, and four overgrown pools were dredged. In the area live <b>badger, roe deer, fox and rabbit</b>. At the edge stands the <b>15th-century ruin of the St Walrick chapel</b>, dedicated to the patron saint of fever sufferers, with beside it the <b>Fever Tree</b>: an old summer oak whose bark was cut for centuries against fever. Scouts, walkers and cyclists share the area — and the province wants to link it back to Heumensoord through the "Groen Kluis" plan.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Aug</b> (pools at their most colourful, sundew), Apr–May (breeding birds on the Meeuwenven)<br>\\n    <b>Best time of day:</b> Late afternoon — sun low over the pools.',
 'why': ['± <b>20 pools on river dunes</b> — rain-water vennen with sundew and sphagnum.', 'The <b>origin story</b>: sand for the Nijmegen railway bridge (19th century).', 'The <b>St Walrick chapel</b> and the <b>Fever Tree</b> of Overasselt.', '<b>Sheep and Scottish highlanders</b> as keepers of heath and pool edges.'],
 'phen': ['<span class="months">Jun–Aug</span> 🌺 <b>Sundew and sphagnum</b> at the pool edges.', '<span class="months">Apr–Jun</span> 🪿 <b>Breeding birds</b> on the Meeuwenven.', '<span class="months">Jul–Sep</span> 🦗 <b>Heath and crowberry</b> in flower (doubled since 2013).', '<span class="months">All year</span> 🐑 <b>Sheep and highlanders</b> on the heath.'],
 'wild': ['🌺 Round-leaved and great sundew', '🐑 Sheep and Scottish highlanders', '🦡 Badger · roe deer · fox', '⛪ St Walrick chapel ruin (15th century)', '🌳 Fever Tree of Overasselt'],
 'trail': ['Walk the <b>pool loops</b> from the Sint-Walrickweg through heath and woodland.', 'Visit the <b>chapel ruin and the Fever Tree</b> at the edge of the area.', 'Combine with the <b>Meeuwenven</b> (a spring look) and Heumensoord.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Pool edges sensitive — do not enter; respect scout terrains · 🚶 Loops 4–10 km'
}))

C.append(mk.card(2094, 'Heumens Bos', {
 'tags': ['Gelderland · Heumen (Rijk van Nijmegen)', 'Bosgebied tussen dorp en Maas-Waalkanaal · Ommetje Heumen door bossen, vennen, uiterwaarden en Maas · aansluitend aan heide van Heumensoord', 'list 36 · no. 813'],
 'loc': '📍 Ten zuiden van Heumen, tussen het dorp en het Maas-Waalkanaal · toegang via de Vosseneindseweg en de recreatiezone bij het Heumens Bos; knooppunten 32–49 van het wandelnetwerk',
 'desc': 'Het <b>Heumens Bos</b> is het groene keurslijf van het dorpje <b>Heumen</b>: een bosrijk gebied tussen het dorp, de uiterwaarden van de Maas en het drukbevaren <b>Maas-Waalkanaal</b>. Wie het <b>Ommetje Heumen</b> loopt — kort 7 km, lang 12 km — passeert alles wat deze hoek van het Rijk van Nijmegen rijk is: <b>bossen en vennen</b> (de vingerwijzing naar het grote Vennengebied van kaart 2093), <b>uiterwaarden</b> langs de Maas, oude dijken en de <b>kogelvangers</b> van het aangrenzende <b>Heumensoord</b>, de zandheuvels die herinneren aan de schietbaan van weleer op wat na de Romeinse ontginning eeuwen heide bleef en in de 19e eeuw werd beplant. In het bos zelf ligt een kindvriendelijk <b>recreatiecentrum</b> met camping dat het gebied sinds jaar en dag als uitvalsbasis dient; rondom staan het <b>kasteel van Heumen</b> aan het water en de <b>Joannusmolen</b>. Het is geen wildernis maar een beschaafd, veelzijdig bos — precies waar Heumen om bekend staat: rust, schaduw en rivier nabij.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (voorjaarsbos), jun–aug (schaduw, kanaal-recreatie), sep–okt (herfstkleur)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — vogels in het bos, mist op de uiterwaard.',
 'why': ['Het <b>Ommetje Heumen</b>: bossen, vennen, uiterwaarden en Maas in één route.', 'De <b>kogelvangers van Heumensoord</b> — zandheuvels met schietbaan-verleden.', 'Het <b>Maas-Waalkanaal</b> en de uiterwaarden als rivierschouw.', '<b>Kasteel en Joannusmolen</b> als culturele bouwstenen.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> in het bos.', '<span class="months">Jun–Aug</span> 🏕️ <b>Zomer in het bos</b> — camping en kanorrecreatie.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> langs de kanalen en paden.', '<span class="months">Nov–Feb</span> 🪿 <b>Watervogels</b> in uiterwaarden en vennen.'],
 'wild': ['🌳 Bos tussen dorp en kanaal', '🏰 Kasteel van Heumen', '⚙️ Joannusmolen', '🦆 Uiterwaarden van de Maas', '🎯 Kogelvangers van Heumensoord'],
 'trail': ['Loop het <b>Ommetje Heumen kort</b> (7 km) of <b>lang</b> (12 km) met knooppunten.', 'Volg de <b>Maasoever en de uiterwaarden</b> zuidwaarts.', 'Combineer met <b>Heumensoord</b> en het Vennengebied (kaart 2093).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Ommetjes 7–12 km'
}, {
 'tags': ['Gelderland · Heumen (Rijk van Nijmegen)', 'Woodland between village and Maas-Waal canal · Ommetje Heumen through woods, pools, floodplains and the Maas · adjoining the Heumensoord heath', 'list 36 · no. 813'],
 'loc': '📍 South of Heumen, between the village and the Maas-Waal canal · access via the Vosseneindseweg and the recreation zone at the Heumens Bos; nodes 32–49 of the walking network',
 'desc': 'The <b>Heumens Bos</b> is the green corset of the little village of <b>Heumen</b>: a wooded area between the village, the Maas floodplains and the busy <b>Maas-Waal canal</b>. Walk the <b>Ommetje Heumen</b> — short 7 km, long 12 km — and you pass all that this corner of the Rijk van Nijmegen holds: <b>woods and pools</b> (a pointer to the great Vennengebied of card 2093), <b>floodplains</b> along the Maas, old dikes and the <b>bullet catchers</b> of adjoining <b>Heumensoord</b>, the sand hills recalling the old shooting range on what remained heath for centuries after Roman times and was planted in the 19th century. In the wood itself lies a family-friendly <b>recreation centre</b> with campsite that has served as the area’s base camp for decades; around it stand <b>Heumen castle</b> by the water and the <b>Joannusmolen</b> mill. It is no wilderness but a civilised, varied wood — just what Heumen is known for: quiet, shade and the river nearby.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring woodland), Jun–Aug (shade, canal recreation), Sep–Oct (autumn colour)<br>\\n    <b>Best time of day:</b> Morning — birds in the wood, mist on the floodplain.',
 'why': ['The <b>Ommetje Heumen</b>: woods, pools, floodplains and the Maas in one route.', 'The <b>bullet catchers of Heumensoord</b> — sand hills with a shooting-range past.', 'The <b>Maas-Waal canal</b> and the floodplains as river scenery.', '<b>Castle and Joannusmolen</b> as cultural building blocks.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> in the wood.', '<span class="months">Jun–Aug</span> 🏕️ <b>Summer in the wood</b> — campsite and canoe recreation.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> along canals and paths.', '<span class="months">Nov–Feb</span> 🪿 <b>Waterfowl</b> in floodplains and pools.'],
 'wild': ['🌳 Wood between village and canal', '🏰 Heumen castle', '⚙️ Joannusmolen', '🦆 Maas floodplains', '🎯 Bullet catchers of Heumensoord'],
 'trail': ['Walk the <b>Ommetje Heumen short</b> (7 km) or <b>long</b> (12 km) with nodes.', 'Follow the <b>Maas bank and floodplains</b> southwards.', 'Combine with <b>Heumensoord</b> and the Vennengebied (card 2093).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops 7–12 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2094)
mk.check()
