# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2140, 'De Haar', {
 'tags': ['Gelderland · Woold, Winterswijk', 'scholtengoed met infopunt en picknickplaats aan de Haarweg · bloemrijk hooiland met orchideeën, vennetjes in het zuiden · deel van het GLK-complex met Hijink en Aarnink', 'list 36 · no. 859'],
 'loc': '📍 Boerderij De Haar, Haarweg/Woold — bushalte, informatiepunt en picknicktafels; startpunt voor wandel- en fietstochten door de scholtengoederen',
 'desc': 'Van de drie scholtengoederen van het Woold is <b>De Haar</b> de natuurlijke voordeur: bij de boerderij aan de Haarweg stopt de bus, staat een <b>informatiepunt met picknicktafels</b> en beginnen de wandel- en fietstochten door het complex van <b>132 hectare</b> dat Geldersch Landschap &amp; Kasteelen sinds <b>1971</b> beheert samen met <b>Hijink</b> en <b>Aarnink</b> (kaart 2137). Rondom ligt het klassieke scholtenlandschap: kleine akkers en velden, gescheiden door <b>hagen, houtwallen en muurtjes</b>, en daaromheen de <b>fraaie oude eikenbossen met rijke ondergroei</b> — in het voorjaar dalkruid tussen de eiken. In het <b>zuiden van het goed</b> ligt een natter deel met <b>vennetjes</b>, en op de bloemrijke hooilanden bloeien <b>orchideeën</b>. Voor wie de Haart van Aalten al kent (kaarten 2114 en 2135): dit is de Winterswijkse variant — zelfde systeem, eigen accenten, en een picknicktafel op de goede plek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–Jun</b> (orchideeën op het hooiland), apr–mei (dalkruid in het eikenbos), jul–aug (evens en libellen bij de vennetjes)<br>\\n    <b>Beste tijd van de dag:</b> Middag — picknicken bij het infopunt, dan het bos in.',
 'why': ['Het <b>infopunt met picknicktafels</b> bij boerderij De Haar — de voordeur van het complex.', '<b>Orchideeën</b> op de bloemrijke hooilanden.', 'De <b>vennetjes</b> in het natte zuidelijke deel.', 'De <b>oude eikenbossen</b> met dalkruid in de ondergroei.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌿 <b>Dalkruid</b> in het oude eikenbos.', '<span class="months">Mei–Jun</span> 🌸 <b>Orchideeën</b> op het hooiland.', '<span class="months">Jun–Aug</span> 🐉 <b>Libellen</b> bij de vennetjes.', '<span class="months">Okt</span> 🍂 <b>Herfstkleuren</b> in eik en beuk.'],
 'wild': ['🌸 Orchideeën op hooiland', '🌿 Dalkruid onder oude eiken', '💧 Vennetjes in het zuiden', '🧺 Infopunt en picknicktafels', '🌳 GLK-complex sinds 1971'],
 'trail': ['Start bij het <b>informatiepunt De Haar</b> (bushalte).', 'Wandel de <b>landwegen rond de drie scholtengoederen</b>.', 'Combineer met <b>Rondje Rot</b> (kaart 2138) in het najaar.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🧺 Picknick mogelijk bij het infopunt · 🚶 Rondes 5–8 km'
}, {
 'tags': ['Gelderland · Woold, Winterswijk', 'scholten estate with information point and picnic spot on the Haarweg · flower-rich hay meadow with orchids, pools in the south · part of the GLK complex with Hijink and Aarnink', 'list 36 · no. 859'],
 'loc': '📍 De Haar farm, Haarweg/Woold — bus stop, information point and picnic tables; trailhead for walks and rides through the scholten estates',
 'desc': 'Of the three scholten estates of the Woold, <b>De Haar</b> is the natural front door: at the farm on the Haarweg the bus stops, an <b>information point with picnic tables</b> stands ready, and the walks and rides through the <b>132-hectare</b> complex that Geldersch Landschap &amp; Kasteelen has managed since <b>1971</b> together with <b>Hijink</b> and <b>Aarnink</b> (card 2137) begin here. Around it lies the classic scholten landscape: small fields and paddocks, separated by <b>hedges, hedgerows and banks</b>, and beyond them the <b>fine old oak woods with rich ground flora</b> — in spring may lily among the oaks. In the <b>south of the estate</b> lies a wetter part with <b>small pools</b>, and on the flower-rich hay meadows bloom <b>orchids</b>. For those who know the Haart of Aalten (cards 2114 and 2135): this is the Winterswijk variant — same system, own accents, and a picnic table in the right place.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (orchids on the hay meadow), Apr–May (may lily in the oak wood), Jul–Aug (damselflies and dragonflies at the pools)<br>\\n    <b>Best time of day:</b> Midday — picnic at the information point, then into the wood.',
 'why': ['The <b>information point with picnic tables</b> at De Haar farm — the complex’s front door.', '<b>Orchids</b> on the flower-rich hay meadows.', 'The <b>pools</b> in the wet southern part.', 'The <b>old oak woods</b> with may lily in the ground flora.'],
 'phen': ['<span class="months">Apr–May</span> 🌿 <b>May lily</b> in the old oak wood.', '<span class="months">May–Jun</span> 🌸 <b>Orchids</b> on the hay meadow.', '<span class="months">Jun–Aug</span> 🐉 <b>Dragonflies</b> at the pools.', '<span class="months">Oct</span> 🍂 <b>Autumn colours</b> in oak and beech.'],
 'wild': ['🌸 Orchids on hay meadow', '🌿 May lily under old oaks', '💧 Pools in the south', '🧺 Information point and picnic tables', '🌳 GLK complex since 1971'],
 'trail': ['Start at the <b>De Haar information point</b> (bus stop).', 'Walk the <b>lanes around the three scholten estates</b>.', 'Combine with <b>Rondje Rot</b> (card 2138) in autumn.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🧺 Picnic possible at the information point · 🚶 Loops 5–8 km'
}))

C.append(mk.card(2141, 'Veenhuis', {
 'tags': ['Gelderland · Kienveenweg/Woold, Winterswijk', 'GLK-bos van 21,5 ha op een voormalige heideontginning, genoemd naar het oude erf Veenhuis (1647) · beuk en den tussen Kienveen en de oude spoorbaan · B&amp;B in de schoppe', 'list 36 · no. 860'],
 'loc': '📍 Kienveenweg/Veenweg, Woold — de onverharde Haarweg voert erlangs; oude Veenhuiswaterleiding stroomt noordwaarts door het Kienveen; B&amp;B ‘de Schoppe’ op het erf',
 'desc': 'Boerderij <b>Veenhuis</b> in het Woold is een van oudsher bekend erf: al in het <b>verpondingskohier van 1647</b> staat het opgetekend als ‘Ter Veen, kaete’ — een goed gekozen plek, met het bouwland op een hoger deel te midden van keileem en arme podzolgronden. In de 19e eeuw was de boerderij zover gegroeid dat er zelfs een <b>korenmolen</b> stond, en de <b>Veenhuiswaterleiding</b> — de waterloop die bij het erf begint — ontwatert sinds mensenheugenis de gronden noordwaarts door het <b>Kienveen</b> naar de Oosink-Beemersbeek. Het GLK-bos van <b>21,5 hectare</b> dat er vandaag ligt is een <b>(voormalige) heideontginning</b>: rond 1900 werd de heide hier ontgonnen tot landbouwgrond of ingeplant met bos — beuk en den, met de oude spoorbaan naar Bocholt als stille buur. Op het erf van de ontginningsboerderij uit de <b>jaren dertig</b> huisvest de schoppe vandaag een <b>bed &amp; breakfast</b>, waar de rand van het Wooldse Veen (kaart 2142) om de hoek ligt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (voorjaarsbos), mei (beukenblad), sep–nov (paddenstoelen in de oude bospercelen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — de Veenhuiswaterleiding in zacht licht.',
 'why': ['Het <b>oude erf Veenhuis</b>, al in 1647 opgetekend als ‘Ter Veen’.', 'De <b>Veenhuiswaterleiding</b> door het Kienveen.', 'Het <b>GLK-bos van 21,5 ha</b> uit de heideontginning rond 1900.', 'De <b>B&amp;B in de schoppe</b> van de ontginningsboerderij.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> tussen beuk en den.', '<span class="months">Mei</span> 🌳 <b>Beukenblad</b> licht door het bos.', '<span class="months">Sep–Nov</span> 🍄 <b>Paddenstoelen</b> in de oude percelen.', '<span class="months">Heel jaar</span> 💧 <b>Waterleiding</b> als stille beek.'],
 'wild': ['🏡 Erf Veenhuis sinds 1647', '💧 Veenhuiswaterleiding', '🌳 Beuk en den op voormalige heide', '🛏️ B&amp;B in de schoppe', '🛤️ Oude spoorbaan naar Bocholt'],
 'trail': ['Volg de <b>onverharde Haarweg</b> langs natuurgebied en erf.', 'Zoek de loop van de <b>Veenhuiswaterleiding</b> richting Kienveen.', 'Combineer met het <b>Wooldse Veen</b> (kaart 2142) en <b>Kulverheide</b> (kaart 2143).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Erf privé — paden volgen · 🚶 Rondje ± 4–5 km'
}, {
 'tags': ['Gelderland · Kienveenweg/Woold, Winterswijk', '21.5-ha GLK wood on a former heath reclamation, named for the old Veenhuis farm (1647) · beech and pine between the Kienveen and the old railway · B&amp;B in the barn', 'list 36 · no. 860'],
 'loc': '📍 Kienveenweg/Veenweg, Woold — the unmetalled Haarweg passes along; the old Veenhuis watercourse runs north through the Kienveen; ‘de Schoppe’ B&amp;B on the farmyard',
 'desc': 'The <b>Veenhuis</b> farm in the Woold is a farmyard of old renown: the <b>1647 land-tax register</b> already records it as ‘Ter Veen, kaete’ — a well-chosen spot, its arable land on a higher part amid boulder clay and poor podzols. By the 19th century the farm had grown so far that even a <b>corn mill</b> stood here, and the <b>Veenhuis watercourse</b> — the stream that begins at the farm — has drained the lands northwards through the <b>Kienveen</b> towards the Oosink-Beemersbeek since time immemorial. The GLK wood of <b>21.5 hectares</b> lying here today is a <b>(former) heath reclamation</b>: around 1900 the heath was reclaimed for farming or planted with wood — beech and pine, with the old railway bank to Bocholt as silent neighbour. On the yard of the reclamation farm of the <b>1930s</b> the barn today houses a <b>bed &amp; breakfast</b>, with the edge of the Wooldse Veen (card 2142) around the corner.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring wood), May (beech leaves), Sep–Nov (fungi in the old parcels)<br>\\n    <b>Best time of day:</b> Morning — the Veenhuis watercourse in soft light.',
 'why': ['The <b>old Veenhuis farm</b>, recorded as early as 1647 as ‘Ter Veen’.', 'The <b>Veenhuis watercourse</b> through the Kienveen.', 'The <b>21.5-ha GLK wood</b> of the ± 1900 heath reclamation.', 'The <b>B&amp;B in the barn</b> of the reclamation farm.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> between beech and pine.', '<span class="months">May</span> 🌳 <b>Beech leaves</b> lighting the wood.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> in the old parcels.', '<span class="months">All year</span> 💧 <b>Watercourse</b> as a silent stream.'],
 'wild': ['🏡 Veenhuis farm since 1647', '💧 Veenhuis watercourse', '🌳 Beech and pine on former heath', '🛏️ B&amp;B in the barn', '🛤️ Old railway bank to Bocholt'],
 'trail': ['Follow the <b>unmetalled Haarweg</b> past wood and farmyard.', 'Trace the <b>Veenhuis watercourse</b> towards the Kienveen.', 'Combine with the <b>Wooldse Veen</b> (card 2142) and <b>Kulverheide</b> (card 2143).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Farmyard private — follow the paths · 🚶 Loop ± 4–5 km'
}))

C.append(mk.card(2142, 'Wooldse Veen', {
 'tags': ['Gelderland · Woold, tegen de Duitse grens (Winterswijk)', 'Natura 2000-hoogveen van ± 63 ha, één geheel met het Duitse Burlo-Vardingholter Venn · veenputten en veendijken met zonnedauw en lavendelheide · regeneratie van actief hoogveen in de veenputten', 'list 36 · no. 861'],
 'loc': '📍 Wooldse Veen, rand van het plateau bij Woold — ± 2 km wandelpad door het veen; grenspalen markeren de Duitse grens; natuurhuisje ‘Grenslicht’ aan de Grensweg',
 'desc': 'Het <b>Wooldse Veen</b> — in oude bronnen ook Burloërveen of Vardingholterveen — vormt samen met het Duitse <b>Burlo-Vardingholter Venn und Entenschlatt</b> één grensoverschrijdend hoogveen op het Oost-Nederlandse Keileemplateau. Het Nederlandse deel, sinds <b>1949</b> reservaat en nu ± <b>63 hectare</b> Natura 2000, is een <b>grondig vergraven en verdroogd</b> veen: de oude <b>veenputten en veendijken</b> getuigen van de turfafgraving van weleer. Maar in de putten gebeurt bijzonders: door het regeneratieplan herstelt zich <b>actief hoogveen</b>, met <b>zonnedauw, lavendelheide, kleine veenbes en veenmossen</b>; op de berkenrijke veendijken leven <b>gladde slangen</b>, en in de bosachtige veenputjes huist de <b>zeer zeldzame dansmug</b> <i>Lasiodiamesa gracilis</i>. De natte heiden eromheen dragen <b>gouden en zompsprinkhaan</b>; tot de vogels behoren <b>geelgors, roodborsttapuit, middelste bonte specht</b> en soms een <b>klapekster</b> of <b>blauwe kiekendief</b>, terwijl in de nabije steengroeve de <b>oehoe</b> broedt die ’s nachts tot hier klinkt. Wie de oude <b>grenspalen</b> zoekt, combineert veen en grens in één wandeling.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–Aug</b> (sprinkhanen, lavendelheide), apr–jun (tapuit en specht), sep–okt (herfstlicht op de veenputten)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — nevel boven de veenputten.',
 'why': ['Het <b>grensoverschrijdende hoogveen</b> met het Duitse Burlo-Vardingholter Venn.', 'De <b>regenererende veenputten</b> met zonnedauw en lavendelheide.', 'De <b>zeer zeldzame dansmug</b> in de beboste putjes.', '<b>Gladde slang</b> op de veendijken, <b>gouden sprinkhaan</b> op de heide.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Roodborsttapuit en geelgors</b> in de struikjes.', '<span class="months">Jun–Aug</span> 🦗 <b>Gouden en zompsprinkhaan</b> in de heide.', '<span class="months">Jul–Sep</span> 🌸 <b>Lavendelheide</b> paars tussen de berken.', '<span class="months">Sep–Okt</span> 🌫️ <b>Herfstnevel</b> over de veenputten.'],
 'wild': ['🌿 Actief hoogveen in de putten', '🐍 Gladde slang op veendijken', '🦟 Zeer zeldzame dansmug', '🐦 Geelgors · tapuit · klapekster', '🪦 Oude grenspalen in het veen'],
 'trail': ['Loop het <b>± 2 km lange wandelpad</b> door het veen.', 'Zoek de <b>oude grenspalen</b> van de Rijksgrens.', 'Combineer met <b>Kulverheide</b> (kaart 2143) en de <b>steengroeve</b>.'],
 'foot': '🐕 Honden aangelijnd, op de paden · 💶 Gratis · ⚠️ Broedveen — paden niet verlaten · 🚶 Pad ± 2 km, rondes 4–6 km'
}, {
 'tags': ['Gelderland · Woold, against the German border (Winterswijk)', '± 63-ha Natura 2000 raised bog, one whole with the German Burlo-Vardingholter Venn · peat pits and bog dikes with sundew and marsh heather · active raised bog regenerating in the pits', 'list 36 · no. 861'],
 'loc': '📍 Wooldse Veen, edge of the plateau at Woold — ± 2 km of footpath through the bog; boundary stones mark the German border; ‘Grenslicht’ nature house on the Grensweg',
 'desc': 'The <b>Wooldse Veen</b> — in old sources also the Burloër or Vardingholter Veen — forms with the German <b>Burlo-Vardingholter Venn und Entenschlatt</b> one cross-border raised bog on the East-Netherlands boulder-clay plateau. The Dutch part, a reserve since <b>1949</b> and now ± <b>63 hectares</b> of Natura 2000, is a <b>thoroughly cut and desiccated</b> bog: the old <b>peat pits and bog dikes</b> tell of the turf cutting of old. But in the pits something remarkable happens: under the regeneration plan <b>active raised bog</b> recovers, with <b>sundew, marsh heather, small cranberry and sphagnum mosses</b>; on the birch-rich dikes live <b>smooth snakes</b>, and in the wooded pits dwells the <b>very rare non-biting midge</b> <i>Lasiodiamesa gracilis</i>. The wet heaths around them carry <b>large gold and marsh grasshoppers</b>; among the birds are <b>yellowhammer, stonechat and middle spotted woodpecker</b>, now and then a <b>great grey shrike</b> or <b>hen harrier</b>, while in the nearby quarry the <b>eagle owl</b> breeds, heard here at night. Seek the old <b>boundary stones</b> and bog and border become one walk.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Aug</b> (grasshoppers, marsh heather), Apr–Jun (stonechat and woodpecker), Sep–Oct (autumn light on the pits)<br>\\n    <b>Best time of day:</b> Early morning — mist over the peat pits.',
 'why': ['The <b>cross-border raised bog</b> with the German Burlo-Vardingholter Venn.', 'The <b>regenerating peat pits</b> with sundew and marsh heather.', 'The <b>very rare non-biting midge</b> in the wooded pits.', '<b>Smooth snake</b> on the dikes, <b>large gold grasshopper</b> on the heath.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Stonechat and yellowhammer</b> in the scrub.', '<span class="months">Jun–Aug</span> 🦗 <b>Gold and marsh grasshoppers</b> in the heath.', '<span class="months">Jul–Sep</span> 🌸 <b>Marsh heather</b> purple among the birches.', '<span class="months">Sep–Oct</span> 🌫️ <b>Autumn mist</b> over the peat pits.'],
 'wild': ['🌿 Active raised bog in the pits', '🐍 Smooth snake on the dikes', '🦟 Very rare non-biting midge', '🐦 Yellowhammer · stonechat · shrike', '🪦 Old boundary stones in the bog'],
 'trail': ['Walk the <b>± 2-km footpath</b> through the bog.', 'Seek the <b>old boundary stones</b> of the border.', 'Combine with <b>Kulverheide</b> (card 2143) and the <b>quarry</b>.'],
 'foot': '🐕 Dogs on lead, on the paths · 💶 Free · ⚠️ Breeding bog — keep to the path · 🚶 Path ± 2 km, loops 4–6 km'
}, n2k='Wooldse Veen — Habitatrichtlijngebied nr. 64 (NL2003053, ± 63 ha, samen met het Duitse Burlo-Vardingholter Venn één grensoverschrijdend hoogveen op het keileemplateau): veenputten met herstel van actief hoogveen (veenmossen, zonnedauw, lavendelheide, kleine veenbes), natte heiden en berkenveendijken; de zeer zeldzame dansmug Lasiodiamesa gracilis, gladde slang en kamsalamander, gouden sprinkhaan en zompsprinkhaan als bijzondere bewoners.',
 n2k_en='Wooldse Veen — Habitats Directive site no. 64 (NL2003053, ± 63 ha, one cross-border raised bog with the German Burlo-Vardingholter Venn on the boulder-clay plateau): peat pits with recovery of active raised bog (sphagnum, sundew, marsh heather, small cranberry), wet heaths and birch bog dikes; the very rare non-biting midge Lasiodiamesa gracilis, smooth snake and great crested newt, large gold grasshopper and marsh grasshopper as notable inhabitants.'))

C.append(mk.card(2143, 'Kulverheide', {
 'tags': ['Gelderland · ten noorden van Woold (Winterswijk)', 'hoogste plateau van Winterswijk met tertiaire kleien aan de oppervlakte · middeleeuwse nederzetting van Roerdink, na 1866 ontgonnen · dennenbossen met rabatten waar heide terugkeert', 'list 36 · no. 862'],
 'loc': '📍 Kulverweg en Grote Veldweg, ten noorden van Woold — kaarsrechte wegen door het ontginningslandschap; bankje aan de rand van de Kulverheide; fietsroutes richting Kotten',
 'desc': 'De <b>Kulverheide</b> is het <b>hoogste deel van Winterswijk</b> — een plateau waar de erosiebestendige <b>tertiaire zeekleien</b> dicht aan de oppervlakte liggen en het maaiveld tot ruim <b>50 meter</b> boven NAP reikt. Hier lag eeuwenlang een uitgestrekt heideveld, en hier vestigden zich in de <b>middeleeuwen</b> de eerste boeren: <b>Roerdink</b>, nog altijd een scholtengoed van formaat, groeide op de Kulverheide uit tot een volwaardige nederzetting. Na de <b>markenverdeling van het Woold in 1866</b> werd de grote heide opgedeeld en in de <b>jaren twintig en dertig</b> ontgonnen: <b>grove dennen</b> voor de mijnbouw, hier en daar loofbos, en overal <b>rabatten</b> — diepgegraven greppels met opgeworpen plantruggen die ’s winters vol water staan. Maar de heide gaf niet op: <b>na elke kap keert ze spontaan terug</b> in de kale percelen. Zo is de Kulverheide vandaag een schoolvoorbeeld van een <b>heide-ontginningslandschap</b> — kaarsrechte wegen (de Kulverweg), dennenbossen met cultuurhistorische relicten, en in de bermen en velden de oude bewoners: <b>geelgors en roodborsttapuit</b> van de arme gronden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (tapuit en veldvogels), aug (heide in de kappen en bermen), okt–nov (paddenstoelen op de rabatten)<br>\\n    <b>Beste tijd van de dag:</b> Avond — het open plateau in laag licht.',
 'why': ['Het <b>hoogste plateau van Winterswijk</b> met tertiaire kleien aan de oppervlakte.', 'De <b>middeleeuwse nederzetting Roerdink</b> op de heide.', 'Het <b>ontginningslandschap na 1866</b>: dennen, rabatten, kaarsrechte wegen.', 'De <b>spontaan terugkerende heide</b> na elke kap.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Roodborsttapuit en geelgors</b> van de arme gronden.', '<span class="months">Aug</span> 🌸 <b>Heideresten</b> paars in kappen en bermen.', '<span class="months">Okt–Nov</span> 🍄 <b>Paddenstoelen</b> op de oude rabatten.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter over het plateau</b> — wijde stilte.'],
 'wild': ['⛰️ Hoogste plateau van Winterswijk', '🌲 Dennenbossen met rabatten', '🌸 Heide die terugkeert', '🐦 Geelgors en roodborsttapuit', '🏡 Scholtengoed Roerdink'],
 'trail': ['Wandel of fiets de <b>Kulverweg</b> door het ontginningslandschap.', 'Zoek het <b>bankje aan de rand van de oude heide</b>.', 'Combineer met <b>Wooldse Veen</b> (kaart 2142) en <b>Veenhuis</b> (kaart 2141).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Deels productiebos — let op kapwerk · 🚶 Rondes 5–8 km'
}, {
 'tags': ['Gelderland · north of Woold (Winterswijk)', 'highest plateau of Winterswijk with Tertiary clays at the surface · medieval Roerdink settlement, reclaimed after 1866 · pine woods with ridges where heather returns', 'list 36 · no. 862'],
 'loc': '📍 Kulverweg and Grote Veldweg, north of Woold — dead-straight roads through the reclamation landscape; a bench at the edge of the Kulverheide; cycle routes towards Kotten',
 'desc': 'The <b>Kulverheide</b> is the <b>highest part of Winterswijk</b> — a plateau where erosion-resistant <b>Tertiary marine clays</b> lie close to the surface and the ground rises to over <b>50 metres</b> above sea level. For centuries an immense heath lay here, and in the <b>Middle Ages</b> the first farmers settled it: <b>Roerdink</b>, still a scholten estate of standing, grew on the Kulverheide into a full settlement. After the <b>division of the Woold mark in 1866</b> the great heath was parcelled out and in the <b>1920s and ’30s</b> reclaimed: <b>Scots pines</b> for the mines, here and there broadleaves, and everywhere <b>ridges</b> — deeply dug ditches with thrown-up planting banks that stand full of water in winter. But the heath never gave up: <b>after every felling it springs back</b> in the cleared parcels. So the Kulverheide today is a textbook <b>heath-reclamation landscape</b> — dead-straight roads (the Kulverweg), pine woods with cultural-historical relics, and in verges and fields the old inhabitants: <b>yellowhammer and stonechat</b> of the poor grounds.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (stonechat and field birds), Aug (heather in the fellings and verges), Oct–Nov (fungi on the ridges)<br>\\n    <b>Best time of day:</b> Evening — the open plateau in low light.',
 'why': ['The <b>highest plateau of Winterswijk</b> with Tertiary clays at the surface.', 'The <b>medieval Roerdink settlement</b> on the heath.', 'The <b>reclamation landscape after 1866</b>: pines, ridges, straight roads.', 'The <b>heather springing back</b> after every felling.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Stonechat and yellowhammer</b> of the poor grounds.', '<span class="months">Aug</span> 🌸 <b>Heather remains</b> purple in fellings and verges.', '<span class="months">Oct–Nov</span> 🍄 <b>Fungi</b> on the old ridges.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter over the plateau</b> — wide silence.'],
 'wild': ['⛰️ Highest plateau of Winterswijk', '🌲 Pine woods with ridges', '🌸 Heather that returns', '🐦 Yellowhammer and stonechat', '🏡 Roerdink scholten estate'],
 'trail': ['Walk or cycle the <b>Kulverweg</b> through the reclamation landscape.', 'Find the <b>bench at the edge of the old heath</b>.', 'Combine with <b>Wooldse Veen</b> (card 2142) and <b>Veenhuis</b> (card 2141).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Partly production forest — mind felling work · 🚶 Loops 5–8 km'
}))

C.append(mk.card(2144, 'Wisch', {
 'tags': ['Gelderland · Terborg/Silvolde (Oude IJsselstreek)', 'landgoed rond kasteel Wisch aan de Oude IJssel: bosbouw-landgoed met lanen en houtwallen · eeuwenoude kern van de heerlijkheid Wisch', 'list 36 · no. 863'],
 'loc': '📍 Laan van Wisch, Terborg — landgoedpaden en lanen rond het kasteel; uitzicht op de landerijen vanaf de Paasberg bij Etten; kasteel niet openbaar',
 'desc': 'Aan de oever van de <b>Oude IJssel</b>, tussen Terborg en Silvolde, liggen de <b>landerijen van kasteel Wisch</b> — het hart van de oude <b>heerlijkheid Wisch</b>, die eeuwenlang deze streek regeerde vanuit haar slot aan de <b>Laan van Wisch</b>. Het landgoed van vandaag is bovenal een <b>bosbouwbedrijf</b>: lanen, productiepercelen en houtwallen die de vallei van de Oude IJssel en de hogere gronden richting Silvolde groen houden. Vanaf de <b>Paasberg</b> bij Etten — een oud rivierduinencomplex — kijk je uit over deze landerijen, en wie de routes van de Oude IJsselstreek loopt, kruist het ene perceel na het andere: eiken en beuken op de betere gronden, naaldhout op de arme, en overal de structuur van lanen en wallen van een goed dat zijn hout al generaties lang beheert. Het kasteel zelf is particulier en niet te bezoeken; het landgoed eromheen is van de wandelaar. Zo sluit deze kaart de kring van de Achterhoekse havezaten: Walfort, Plekenpol, Landfort (kaart 2152) — en Wisch als de statigste van allemaal.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (lanen in jong groen), sep–nov (paddenstoelen in de bosbouwpercelen), dec–feb (winterstilte in de lanen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de Oude IJssel-vallei.',
 'why': ['De <b>landerijen van kasteel Wisch</b>, hart van de oude heerlijkheid.', 'Het <b>bosbouwlandgoed</b> met lanen en houtwallen.', 'Het <b>uitzicht vanaf de Paasberg</b> bij Etten.', 'De statigste van de <b>Achterhoekse havezaten</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌳 <b>Lanen in jong groen</b>.', '<span class="months">Jun–Aug</span> 🌾 <b>Hooitijd</b> in de riviervallei.', '<span class="months">Sep–Nov</span> 🍄 <b>Paddenstoelen</b> tussen eik en beuk.', '<span class="months">Dec–Feb</span> ❄️ <b>Winterstilte</b> rond het slot.'],
 'wild': ['🏰 Kasteel Wisch en de heerlijkheid', '🌳 Bosbouwlanen en -percelen', '💧 Oude IJssel-vallei', '⛰️ Uitzicht vanaf de Paasberg', '🍃 Houtwallen van generaties'],
 'trail': ['Wandel de <b>landerijen rond de Laan van Wisch</b>.', 'Bekijk het landgoed vanaf de <b>Paasberg</b> bij Etten.', 'Combineer met de <b>Oude IJssel-routes</b> richting Ulft.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (landgoed); kasteel gesloten · ⚠️ Percelen productiebos · 🚶 Rondes 4–8 km'
}, {
 'tags': ['Gelderland · Terborg/Silvolde (Oude IJsselstreek)', 'estate around Wisch Castle on the Oude IJssel: a forestry estate with avenues and hedgerows · centuries-old heart of the heerlijkheid Wisch', 'list 36 · no. 863'],
 'loc': '📍 Laan van Wisch, Terborg — estate paths and avenues around the castle; views over the lands from the Paasberg at Etten; castle not open to the public',
 'desc': 'On the banks of the <b>Oude IJssel</b>, between Terborg and Silvolde, lie the <b>lands of Wisch Castle</b> — the heart of the old <b>heerlijkheid Wisch</b>, which ruled this region for centuries from its seat on the <b>Laan van Wisch</b>. The estate of today is above all a <b>forestry property</b>: avenues, production parcels and hedgerows keeping the valley of the Oude IJssel and the higher grounds towards Silvolde green. From the <b>Paasberg</b> at Etten — an old river-dune complex — you look out over these lands, and walking the routes of the Oude IJsselstreek you cross parcel after parcel: oak and beech on the better soils, conifer on the poor, and everywhere the avenue-and-bank structure of an estate that has managed its timber for generations. The castle itself is private and not open; the estate around it belongs to the walker. This card closes the circle of Achterhoek havezates: Walfort, Plekenpol, Landfort (card 2152) — and Wisch, stateliest of them all.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (avenues in young green), Sep–Nov (fungi in the forestry parcels), Dec–Feb (winter silence in the avenues)<br>\\n    <b>Best time of day:</b> Morning — mist over the Oude IJssel valley.',
 'why': ['The <b>lands of Wisch Castle</b>, heart of the old heerlijkheid.', 'The <b>forestry estate</b> with avenues and hedgerows.', 'The <b>view from the Paasberg</b> at Etten.', 'Stateliest of the <b>Achterhoek havezates</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌳 <b>Avenues in young green</b>.', '<span class="months">Jun–Aug</span> 🌾 <b>Hay time</b> in the river valley.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> between oak and beech.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter silence</b> around the castle.'],
 'wild': ['🏰 Wisch Castle and heerlijkheid', '🌳 Forestry avenues and parcels', '💧 Oude IJssel valley', '⛰️ Views from the Paasberg', '🍃 Hedgerows of generations'],
 'trail': ['Walk the <b>lands around the Laan van Wisch</b>.', 'View the estate from the <b>Paasberg</b> at Etten.', 'Combine with the <b>Oude IJssel routes</b> towards Ulft.'],
 'foot': '🐕 Dogs on lead · 💶 Free (estate); castle closed · ⚠️ Parcels are production forest · 🚶 Loops 4–8 km'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2144)
mk.check()
