# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2105, 'Dennenoord', {
 'tags': ['Gelderland · Aalten (richting Bredevoort)', 'Gemeentelijk bos- en zwemterrein op oude heide · paviljoen voor tbc-lijders dat leeg bleef · natuurzwembad \'t Walfort (1934) als werkverschaffingsproject', 'list 36 · no. 824'],
 'loc': '📍 Dennenoord 2, Aalten — halverwege Aalten en Bredevoort langs de Hessenweg · bospaden rond het terrein; natuurzwembad \'t Walfort met ligweide',
 'desc': 'Halverwege <b>Aalten en Bredevoort</b> ligt het terrein <b>Dennenoord</b>: een gordel van bos en groen op wat in <b>1852</b> nog kale <b>heide</b> was (36.380 vierkante meter, eigendom van baron van Pallandt). De gemeente Aalten kocht het terrein in de jaren twintig en beplantte het met <b>dennen</b> — in 1923 staat het in de boeken als "heide &amp; dennen". De merkwaardigste geschiedenis is die van het <b>paviljoen Dennenoord</b>: begin twintigste eeuw gebouwd voor <b>tuberculosepatiënten</b> als kuuroord-herberg, maar <b>nooit in gebruik genomen</b> — de patiënten wilden er eenvoudig niet naartoe. Op 10 juni 1933 besloot de gemeenteraad er een <b>groot modern zwem- en zonnebad met breed strand</b> aan te leggen, als <b>werkverschaffingsproject</b> in de crisisjaren: in <b>1934</b> opende <b>natuurzwembad \'t Walfort</b> zijn deuren, met een zandbodem en zwaar geboomte eromheen. Zo groeide Dennenoord uit tot het groene hart van de Aaltense vrijheid: bos voor het wandelen, water voor de zomer, en de oudheid van de Hessenweg erdoorheen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–Aug</b> (natuurbad seizoen), apr–mei (voorjaarsbos), sep–okt (herfstkleur)<br>\\n    <b>Beste tijd van de dag:</b> Middag — het bad en het bos in de zon.',
 'why': ['Het <b>paviljoen dat nooit gebruikt werd</b> — de tbc-patiënten wilden niet.', '<b>Natuurzwembad \'t Walfort</b> (1934) als werkverschaffingsproject.', 'De transformatie van <b>kale heide (1852) naar dennenbos (1923)</b>.', 'De ligging aan de oude <b>Hessenweg</b> tussen Aalten en Bredevoort.'],
 'phen': ['<span class="months">Jul–Aug</span> 🏊 <b>Natuurbad</b> met zandbodem in seizoen.', '<span class="months">Apr–Mei</span> 🎵 <b>Voorjaarsvogels</b> in het dennenbos.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> rond het bad.', '<span class="months">Heel jaar</span> 🚶 <b>Bospaden</b> als uitloop van twee dorpen.'],
 'wild': ['🏊 Natuurbad \'t Walfort (1934)', '🌲 Dennaanplant op oude heide', '🏥 Paviljoen-geschiedenis (tbc, ongebruikt)', '🐎 Hessenweg als oude route', '🌳 Zwaar geboomte rond het bad'],
 'trail': ['Wandel de <b>bospaden rond Dennenoord</b> tussen Aalten en Bredevoort.', 'Combineer met een bezoek aan <b>Bredevoort</b> (boekdorp).', 'Duik in de zomer in het <b>natuurbad</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Bos gratis (bad met entreeprijs) · 🚶 Rondje ± 3 km'
}, {
 'tags': ['Gelderland · Aalten (towards Bredevoort)', 'Municipal woodland and bathing ground on old heath · pavilion for TB patients that stayed empty · \'t Walfort natural pool (1934) as a job-creation project', 'list 36 · no. 824'],
 'loc': '📍 Dennenoord 2, Aalten — halfway between Aalten and Bredevoort along the Hessenweg · woodland paths around the terrain; \'t Walfort natural pool with sun meadow',
 'desc': 'Halfway between <b>Aalten and Bredevoort</b> lies the terrain of <b>Dennenoord</b>: a belt of woodland and green on what was still bare <b>heath</b> in <b>1852</b> (36,380 square metres, owned by Baron van Pallandt). The municipality of Aalten bought the ground in the 1920s and planted it with <b>pines</b> — by 1923 the books record "heath &amp; pines". The strangest history is that of the <b>Dennenoord pavilion</b>: built in the early twentieth century for <b>tuberculosis patients</b> as a convalescent inn, but <b>never taken into use</b> — the patients simply refused to come. On 10 June 1933 the council decided to lay out a <b>large modern swimming and sunbathing bath with a broad beach</b> there, as a <b>job-creation project</b> in the crisis years: in <b>1934</b> the <b>\'t Walfort natural pool</b> opened its doors, with a sandy bottom and heavy trees around it. Thus Dennenoord grew into the green heart of Aalten’s outdoors: wood for walking, water for summer, and the antiquity of the Hessenweg running through.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Aug</b> (natural pool season), Apr–May (spring wood), Sep–Oct (autumn colour)<br>\\n    <b>Best time of day:</b> Midday — the pool and the wood in the sun.',
 'why': ['The <b>pavilion that was never used</b> — the TB patients would not come.', 'The <b>\'t Walfort natural pool</b> (1934) as a job-creation project.', 'The transformation from <b>bare heath (1852) to pine wood (1923)</b>.', 'The position on the old <b>Hessenweg</b> between Aalten and Bredevoort.'],
 'phen': ['<span class="months">Jul–Aug</span> 🏊 <b>Natural pool</b> with sandy bottom in season.', '<span class="months">Apr–May</span> 🎵 <b>Spring birds</b> in the pine wood.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> around the pool.', '<span class="months">All year</span> 🚶 <b>Woodland paths</b> as the outlet of two villages.'],
 'wild': ['🏊 \'t Walfort natural pool (1934)', '🌲 Pine planting on old heath', '🏥 Pavilion history (TB, unused)', '🐎 Hessenweg as an old route', '🌳 Heavy trees around the pool'],
 'trail': ['Walk the <b>woodland paths around Dennenoord</b> between Aalten and Bredevoort.', 'Combine with a visit to <b>Bredevoort</b> (book village).', 'Swim in the <b>natural pool</b> in summer.'],
 'foot': '🐕 Dogs on lead · 💶 Wood free (pool with entry fee) · 🚶 Loop ± 3 km'
}))

C.append(mk.card(2106, 'Noorderbroek', {
 'tags': ['Gelderland · Westendorp/Varsseveld (gemeente Oude IJsselstreek)', 'Bos op oud broekland waar de Boven Slinge doorheen stroomt · geliefd Varssevelds wandelbos · productiebos met mooie beekoevers', 'list 36 · no. 825'],
 'loc': '📍 Ten noorden van Westendorp, te voet vanaf restaurant De Vos (Halseweg 2) · smalle bospaadjes en beekpad langs de Boven Slinge; hardlooproute 10,5 km met Tandem en Slinge',
 'desc': 'Het <b>Noorderbroek</b> ligt ten noorden van <b>Westendorp</b>, tegen Varsseveld aan: een bosgebied waarvan de naam de geschiedenis draagt — <b>broek</b> is drassig land, en voordat de <b>Boven Slinge</b> in cultuur werd gebracht was dit een <b>moerassig veengebied</b>. Tegenwoordig is het vooral bos: een productiebos dat de Varssevelders en Westendorpers al generaties lang als hun wandelbos gebruiken, met <b>smalle paadjes</b> die tussen de opstanden door naar de beek voeren. Juist langs de <b>Slingebeek</b> is het Noorderbroek op zijn mooist: de meanderende oevers, de elzen en de wilgen geven het produktiebos een strook wildernis mee. In de herfst organiseren de IVN-afdelingen hier hun <b>paddenstoelenwandelingen</b>. Wie het grotere rondje loopt, combineert het Noorderbroek met <b>landgoed Tandem</b> (kaart 2107) en de Boven Slinge tot een typisch Achterhoekse tocht van bos, beek en boerenland — het gebied mist dan wel het ongerepte van de Vennebulten en het parkachtige van de Slangenburg, maar als dagelijks wandelbos is het geliefd genoeg.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–Okt</b> (paddenstoelen, herfstbeek), apr–mei (voorjaarsvogels)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de Slinge.',
 'why': ['De <b>Boven Slinge</b> die dwars door het bos meandert.', 'De <b>broek-geschiedenis</b>: van moerassig veen naar productiebos.', 'De <b>smalle paadjes</b> van het geliefde Varsseveldse wandelbos.', 'De combinatie met <b>Tandem</b> tot een klassiek rondje.'],
 'phen': ['<span class="months">Sep–Nov</span> 🍄 <b>Paddenstoelen</b> — IVN-wandelingen in de herfst.', '<span class="months">Apr–Jun</span> 🎵 <b>Bosvogels</b> in de naaldbanden.', '<span class="months">Heel jaar</span> 💧 <b>De Slingebeek</b> langs de oevers.', '<span class="months">Dec–Feb</span> ❄️ <b>Kale beekbossen</b> in winterlicht.'],
 'wild': ['💧 Boven Slinge door het bos', '🍄 Paddenstoelen in de herfst', '🌳 Productiebos met wilde beekstrook', '🐦 Bosvogels van het dagelijkse rondje', '🗺️ Oud broekland (veen)'],
 'trail': ['Start bij <b>restaurant De Vos</b> in Westendorp voor de 10,5 km door Tandem en Noorderbroek.', 'Volg het <b>beekpad langs de Boven Slinge</b>.', 'Loop in de herfst mee met de <b>IVN-paddenstoelenwandeling</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes 5–10,5 km'
}, {
 'tags': ['Gelderland · Westendorp/Varsseveld (Oude IJsselstreek municipality)', 'Woodland on old marsh land with the Boven Slinge flowing through · beloved walking wood of Varsseveld · production forest with fine stream banks', 'list 36 · no. 825'],
 'loc': '📍 North of Westendorp, on foot from restaurant De Vos (Halseweg 2) · narrow woodland paths and a stream path along the Boven Slinge; running route 10.5 km with Tandem and the Slinge',
 'desc': 'The <b>Noorderbroek</b> lies north of <b>Westendorp</b>, against Varsseveld: a woodland whose name carries its history — <b>broek</b> means marshy land, and before the <b>Boven Slinge</b> was brought under cultivation this was a <b>swampy peat area</b>. Today it is mostly wood: a production forest that the people of Varsseveld and Westendorp have used as their walking wood for generations, with <b>narrow paths</b> leading between the stands down to the stream. Precisely along the <b>Slinge stream</b> the Noorderbroek is at its best: the meandering banks, the alders and willows lend the production forest a strip of wilderness. In autumn the IVN branches hold their <b>fungus walks</b> here. Walk the bigger loop and you combine the Noorderbroek with <b>Tandem estate</b> (card 2107) and the Boven Slinge into a typical Achterhoek tour of wood, stream and farmland — the area may lack the pristine air of the Vennebulten and the parkland of the Slangenburg, but as an everyday walking wood it is well loved.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (fungi, autumn stream), Apr–May (spring birds)<br>\\n    <b>Best time of day:</b> Morning — mist above the Slinge.',
 'why': ['The <b>Boven Slinge</b> meandering straight through the wood.', 'The <b>broek history</b>: from swampy peat to production forest.', 'The <b>narrow paths</b> of the beloved Varsseveld walking wood.', 'The combination with <b>Tandem</b> into a classic loop.'],
 'phen': ['<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> — IVN walks in autumn.', '<span class="months">Apr–Jun</span> 🎵 <b>Woodland birds</b> in the conifer stands.', '<span class="months">All year</span> 💧 <b>The Slinge stream</b> along its banks.', '<span class="months">Dec–Feb</span> ❄️ <b>Bare stream woods</b> in winter light.'],
 'wild': ['💧 Boven Slinge through the wood', '🍄 Fungi in autumn', '🌳 Production forest with a wild stream strip', '🐦 Woodland birds of the daily round', '🗺️ Old marsh land (peat)'],
 'trail': ['Start at <b>restaurant De Vos</b> in Westendorp for the 10.5 km through Tandem and the Noorderbroek.', 'Follow the <b>stream path along the Boven Slinge</b>.', 'Join the <b>IVN fungus walk</b> in autumn.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops 5–10.5 km'
}))

C.append(mk.card(2107, 'Tandem-Vlaswinkel', {
 'tags': ['Gelderland · tussen Varsseveld en Westendorp', 'GLK-landgoedbos met huis, beukenlaan en Canadese inscripties uit 1945 · lelietje-van-dalen en dalkruid in de ondergroei · sinds 2016 van GLK', 'list 36 · no. 826'],
 'loc': '📍 Landgoed Tandem tussen Varsseveld en Westendorp — bospad en beukenlaan vrij toegankelijk · combineer met het Noorderbroek (kaart 2106) voor het grote rondje',
 'desc': 'Tussen <b>Varsseveld en Westendorp</b> ligt <b>landgoed Tandem</b>, met de boerderij <b>Vlaswinkel</b> als beroemdste buur: het boek noemt ze samen, en samen vormen ze het GLK-bos dat sinds <b>2016</b> van Geldersch Landschap &amp; Kasteelen is — gekocht van de gemeente Oude IJsselstreek, die het bos in <b>1954</b> van de erven van de laatste bewoonster had gekregen. Het terrein heeft echt <b>landgoedkarakter</b>: een huis, statige lanen en een bosgebied met veel soorten bomen, verdeeld in <b>kleine opstanden van telkens één soort</b> — geen monocultuur, geen volkomen gemengd bos, maar een mozaïek. In de <b>beukenlaan</b> naar het huis staan bomen met <b>ingesneden inscripties</b>, gemaakt door <b>Canadese militairen</b> die in 1945 hielpen de Achterhoek te bevrijden. In de ondergroei groeien soorten van oude, matig voedselrijke bossen: <b>blauwe bosbes, dalkruid, bosanemoon</b> en het <b>lelietje-van-dalen</b>. Waargenomen zijn onder meer <b>bunzing, laatvlieger en rosse vleermuis</b>, en als broedvogels de <b>wespendief</b> en de <b>zwarte specht</b>; in het poeltje in het noordoosten leven amfibieën.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (bosanemoon, lelietje-van-dalen), sep–okt (paddenstoelen in het mozaïekbos)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht in de beukenlaan.',
 'why': ['De <b>beukenlaan met Canadese inscripties</b> uit 1945.', 'Het <b>mozaïek van kleine mono-soortige opstanden</b> — zeldzaam bosstructuur.', '<b>Lelietje-van-dalen en dalkruid</b> in de oude ondergroei.', 'De <b>landgoedgeschiedenis</b>: 1954 van de erven, 2016 naar GLK.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Bosanemoon en lelietje-van-dalen</b> in bloei.', '<span class="months">Mei–Jun</span> 🪶 <b>Zwarte specht en wespendief</b> aanwezig.', '<span class="months">Jul–Aug</span> 🦇 <b>Vleermuizen</b> (laatvlieger, rosse) na schemering.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in het mozaïekbos.'],
 'wild': ['🌸 Lelietje-van-dalen · dalkruid · blauwe bosbes', '🪶 Zwarte specht · wespendief', '🦇 Rosse vleermuis · laatvlieger', '🦡 Bunzing', '✍️ Beukenlaan met 1945-inscripties'],
 'trail': ['Wandel de <b>beukenlaan</b> naar het huis en lees de <b>Canadese inscripties</b>.', 'Volg het <b>bospad</b> door de kleine opstanden.', 'Combineer met <b>Noorderbroek</b> (kaart 2106) voor het grote rondje.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Huis en erf privé · 🚶 Bos-rondje ± 4 km'
}, {
 'tags': ['Gelderland · between Varsseveld and Westendorp', 'GLK estate wood with house, beech avenue and Canadian inscriptions from 1945 · lily-of-the-valley and Solomon’s-seal in the undergrowth · GLK since 2016', 'list 36 · no. 826'],
 'loc': '📍 Tandem estate between Varsseveld and Westendorp — woodland path and beech avenue freely accessible · combine with the Noorderbroek (card 2106) for the grand loop',
 'desc': 'Between <b>Varsseveld and Westendorp</b> lies <b>Tandem estate</b>, with the farm of <b>Vlaswinkel</b> as its famous neighbour: the book names them together, and together they form the GLK wood that has belonged to Geldersch Landschap &amp; Kasteelen since <b>2016</b> — bought from the municipality of Oude IJsselstreek, which had received the wood in <b>1954</b> from the heirs of the last resident. The terrain has genuine <b>estate character</b>: a house, stately avenues and a woodland of many tree species, divided into <b>small stands of a single species each</b> — no monoculture, no fully mixed wood, but a mosaic. In the <b>beech avenue</b> towards the house stand trees with <b>carved inscriptions</b>, made by <b>Canadian soldiers</b> who helped liberate the Achterhoek in 1945. In the undergrowth grow species of old, moderately rich woodland: <b>bilberry, Solomon’s-seal, wood anemone</b> and <b>lily-of-the-valley</b>. Recorded here are among others <b>polecat, common pipistrelle and brown long-eared bat</b>, and as breeding birds <b>honey buzzard</b> and <b>black woodpecker</b>; in the pond in the north-east live amphibians.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (wood anemone, lily-of-the-valley), Sep–Oct (fungi in the mosaic wood)<br>\\n    <b>Best time of day:</b> Morning — light in the beech avenue.',
 'why': ['The <b>beech avenue with Canadian inscriptions</b> from 1945.', 'The <b>mosaic of small single-species stands</b> — a rare forest structure.', '<b>Lily-of-the-valley and Solomon’s-seal</b> in the old undergrowth.', 'The <b>estate history</b>: 1954 from the heirs, 2016 to GLK.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Wood anemone and lily-of-the-valley</b> in flower.', '<span class="months">May–Jun</span> 🪶 <b>Black woodpecker and honey buzzard</b> present.', '<span class="months">Jul–Aug</span> 🦇 <b>Bats</b> (pipistrelle, long-eared) after dusk.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the mosaic wood.'],
 'wild': ['🌸 Lily-of-the-valley · Solomon’s-seal · bilberry', '🪶 Black woodpecker · honey buzzard', '🦇 Brown long-eared bat · pipistrelle', '🦡 Polecat', '✍️ Beech avenue with 1945 inscriptions'],
 'trail': ['Walk the <b>beech avenue</b> to the house and read the <b>Canadian inscriptions</b>.', 'Follow the <b>woodland path</b> through the small stands.', 'Combine with the <b>Noorderbroek</b> (card 2106) for the grand loop.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ House and yard private · 🚶 Wood loop ± 4 km'
}))

C.append(mk.card(2108, 'Hiddink', {
 'tags': ['Gelderland · Varsseveld (ten noorden van het dorp)', 'Particulier bosgebied aan weerszijden van de Hiddinkdijk · aangelegd op drassige gronden met greppels · de Boven Slinge stroomt erdoorheen', 'list 36 · no. 827'],
 'loc': '📍 Hiddinkdijk, ten noorden van Varsseveld — landwegen en bospaden langs de Boven Slinge · op te nemen in rondes met Tandem (kaart 2107) en Noorderbroek (kaart 2106)',
 'desc': 'Aan weerszijden van de <b>Hiddinkdijk</b>, ten noorden van <b>Varsseveld</b>, ligt het bosgebied <b>Hiddink</b>: particulier bezit, gedragen door een geslacht waarvan de naam in deze streek telkens terugkeert — van boerderijen tot de beroemdste voetbaltrainer die Nederlands ooit had. Het bos is aangelegd op de <b>lagere, drassige delen</b> van het Slingedal, waarbij <b>greppels</b> werden gegraven om het water af te voeren; door het terrein loopt nog altijd de <b>Boven Slinge</b>, die er net als in het Noorderbroek zijn meanders mag houden. Het is het kleinste type natuurgebied dat deze gids kent: geen bord, geen poort, maar een bos dat het Achterhoekse coulissenlandschap z’n diepte geeft — hout op de natte plekken, weiden op de hogere gronden, en hier en daar een zitbank langs de paden waar de dorpers hun rondje lopen. Samen met Tandem, het Noorderbroek en de Vennebulten vormt het het groene raamwerk rond Varsseveld.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (voorjaarsbos), sep–okt (herfst in het Slingedal)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — de Slinge in de nevel.',
 'why': ['De <b>Hiddinkdijk</b> als naamgevende as van het gebied.', 'De <b>greppels en drassige gronden</b> van de bosaanleg.', 'De <b>Boven Slinge</b> die door het terrein loopt.', 'Het kleinschalige groene raamwerk rond <b>Varsseveld</b>.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> in de nattebossen.', '<span class="months">Jun–Aug</span> 🌿 <b>Dichte zomerbossen</b> bij de beek.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> in het Slingedal.', '<span class="months">Heel jaar</span> 💧 <b>De Slinge</b> als levende ader.'],
 'wild': ['💧 Boven Slinge door het bos', '🌳 Bos op drassige gronden met greppels', '🌾 Wissel van hout en weide', '🪶 Bosvogels van het dagelijkse rondje', '🗺️ Particulier gebied, vrij padennetwerk'],
 'trail': ['Wandel de <b>Hiddinkdijk</b> en de bospaden langs de Slinge.', 'Neem Hiddink op in het <b>grote rondje</b> met Tandem en Noorderbroek.', 'Volg de beek stroomafwaarts richting Westendorp.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Particulier gebied — paden volgen · 🚶 Rondje ± 5 km'
}, {
 'tags': ['Gelderland · Varsseveld (north of the village)', 'Private woodland on both sides of the Hiddinkdijk · laid out on wet grounds with ditches · the Boven Slinge flows through it', 'list 36 · no. 827'],
 'loc': '📍 Hiddinkdijk, north of Varsseveld — country lanes and woodland paths along the Boven Slinge · include in loops with Tandem (card 2107) and the Noorderbroek (card 2106)',
 'desc': 'On both sides of the <b>Hiddinkdijk</b>, north of <b>Varsseveld</b>, lies the woodland of <b>Hiddink</b>: private property, carried by a family whose name returns again and again in this region — from farms to the most famous football trainer the Netherlands ever had. The wood was laid out on the <b>lower, marshy parts</b> of the Slinge valley, with <b>ditches</b> dug to carry off the water; through the terrain still runs the <b>Boven Slinge</b>, which here, as in the Noorderbroek, may keep its meanders. It is the smallest kind of nature area this guide knows: no sign, no gate, but a wood that gives the Achterhoek hedgerow landscape its depth — timber on the wet spots, meadows on the higher ground, and here and there a bench along the paths where villagers walk their daily round. Together with Tandem, the Noorderbroek and the Vennebulten it forms the green framework around Varsseveld.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring wood), Sep–Oct (autumn in the Slinge valley)<br>\\n    <b>Best time of day:</b> Morning — the Slinge in the mist.',
 'why': ['The <b>Hiddinkdijk</b> as the naming axis of the area.', 'The <b>ditches and wet grounds</b> of the original planting.', 'The <b>Boven Slinge</b> running through the terrain.', 'The small-scale green framework around <b>Varsseveld</b>.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> in the wet woods.', '<span class="months">Jun–Aug</span> 🌿 <b>Dense summer woods</b> by the stream.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> in the Slinge valley.', '<span class="months">All year</span> 💧 <b>The Slinge</b> as a living artery.'],
 'wild': ['💧 Boven Slinge through the wood', '🌳 Wood on wet ground with ditches', '🌾 Alternation of timber and meadow', '🪶 Woodland birds of the daily round', '🗺️ Private area, open path network'],
 'trail': ['Walk the <b>Hiddinkdijk</b> and the woodland paths along the Slinge.', 'Include Hiddink in the <b>grand loop</b> with Tandem and the Noorderbroek.', 'Follow the stream downstream towards Westendorp.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Private area — follow the paths · 🚶 Loop ± 5 km'
}))

C.append(mk.card(2109, 'Het Leemscherbos', {
 'tags': ['Gelderland · Varsseveld (Achterhoek, SBB-deelgebied)', 'Klein eikenbos van meer dan 100 jaar oud met blauwe reigerkolonie · leem in de naam en in de bodem · vrij toegankelijk voor wandelaars, fietsers en ruiters', 'list 36 · no. 828'],
 'loc': '📍 Bij Varsseveld — bospaden vrij toegankelijk (wandelaars, fietsers, ruiters) · op te nemen in de Varsseveldse rondes met Tandem, Hiddink en Noorderbroek',
 'desc': 'Het <b>Leemscherbos</b> bij Varsseveld is een klein maar fier natuurbos: een <b>eikenbos van meer dan honderd jaar oud</b>, dat zijn naam dankt aan de <b>lemige bodem</b> van de Achterhoekse dekzandgronden — leem die hier van oudsher ook werd gewonnen. Als deelgebied van het Staatsbosbeheer-complex in de Achterhoek wordt het kleinschalig beheerd, en precies die kleinschaligheid draagt zijn beroemdste bewoner: in het bos zit een <b>kolonie blauwe reigers</b>, die elk voorjaar de oude eiken tot een lawaaiige kraamkamer maakt. Het bos is vrij toegankelijk voor <b>wandelaars, fietsers en ruiters</b> — in deze streek geen vanzelfsprekendheid — en de paden sluiten aan op de landwegen richting Varsseveld en de Slinge-vallei. Wie de stille kant van de Achterhoek zoekt, vindt hier honderd jaar eiken, reigers in de kruin en de geleende stilte van een klein bos.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–Mei</b> (reigerkolonie op het nest), apr–mei (voorjaarsflora), sep–okt (paddenstoelen)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — de reigers vliegen uit.',
 'why': ['De <b>blauwe reigerkolonie</b> in honderd jaar oude eiken.', 'De <b>lemige bodem</b> die het bos zijn naam gaf.', '<b>Vrij toegankelijk</b> voor wandelaars, fietsers én ruiters.', 'De <b>kleinschaligheid</b> van een SBB-deelgebied dat stil blijft.'],
 'phen': ['<span class="months">Mrt–Mei</span> 🪶 <b>Reigerkolonie</b> — lawaai van jongen in de kruinen.', '<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> op lemige bodem.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> onder oude eiken.', '<span class="months">Nov–Feb</span> ❄️ <b>Kale eiken</b> met oude nesten.'],
 'wild': ['🪶 Blauwe reigerkolonie', '🌳 Eikenbos van 100+ jaar', '🧱 Lemige bodem (naamgever)', '🍄 Paddenstoelen onder eik', '🐎 Vrij toegankelijk voor ruiters'],
 'trail': ['Wandel de <b>bospaden</b> door het eikenbos bij Varsseveld.', 'Zoek in het voorjaar de <b>reigerkolonie</b> (vanaf de rand).', 'Combineer met <b>Tandem, Hiddink en Noorderbroek</b> (kaarten 2106–2108).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Bos-rondje ± 3 km'
}, {
 'tags': ['Gelderland · Varsseveld (Achterhoek, SBB sub-area)', 'Small oak wood over a hundred years old with a grey heron colony · loam in the name and in the soil · open to walkers, cyclists and riders', 'list 36 · no. 828'],
 'loc': '📍 By Varsseveld — woodland paths freely accessible (walkers, cyclists, riders) · include in the Varsseveld loops with Tandem, Hiddink and the Noorderbroek',
 'desc': 'The <b>Leemscherbos</b> by Varsseveld is a small but proud wood: an <b>oak wood more than a hundred years old</b>, owing its name to the <b>loamy soil</b> of the Achterhoek cover sands — loam that was also dug here from of old. As a sub-area of the Staatsbosbeheer complex in the Achterhoek it is managed on a small scale, and precisely that small scale carries its most famous resident: in the wood sits a <b>colony of grey herons</b> that turns the old oaks into a noisy nursery every spring. The wood is freely accessible to <b>walkers, cyclists and riders</b> — no matter of course in this region — and the paths connect to the country lanes towards Varsseveld and the Slinge valley. For the quiet side of the Achterhoek, look no further: a hundred years of oak, herons in the crown and the borrowed silence of a small wood.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (heron colony on the nest), Apr–May (spring flora), Sep–Oct (fungi)<br>\\n    <b>Best time of day:</b> Early morning — the herons fly out.',
 'why': ['The <b>grey heron colony</b> in hundred-year-old oaks.', 'The <b>loamy soil</b> that gave the wood its name.', '<b>Freely accessible</b> to walkers, cyclists and riders alike.', 'The <b>small scale</b> of an SBB sub-area that stays quiet.'],
 'phen': ['<span class="months">Mar–May</span> 🪶 <b>Heron colony</b> — the noise of young in the crowns.', '<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> on loamy soil.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> under old oaks.', '<span class="months">Nov–Feb</span> ❄️ <b>Bare oaks</b> with old nests.'],
 'wild': ['🪶 Grey heron colony', '🌳 Oak wood of 100+ years', '🧱 Loamy soil (name-giver)', '🍄 Fungi under oak', '🐎 Open to riders'],
 'trail': ['Walk the <b>woodland paths</b> through the oak wood by Varsseveld.', 'Seek out the <b>heron colony</b> in spring (from the edge).', 'Combine with <b>Tandem, Hiddink and the Noorderbroek</b> (cards 2106–2108).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Wood loop ± 3 km'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2109)
mk.check()
