# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2060, 'Stadsbossen, Lijstereng en Kerkebos', {
 'tags': ['Utrecht · Rhenen (Utrechtse Heuvelrug)', 'Stadsbossen van Rhenen met eng-akkers, heidevelden en bronstijd-grafheuvels · Koerheuvel met watertoren · Nationaal Park Utrechtse Heuvelrug', 'list 36 · no. 779'],
 'loc': '📍 Startpunt De Leemkuil (Autoweg, Rhenen) — Lijsterengroute 3 km blauw gemarkeerd · mountainbikeroute doorkruist het bos; ook onderdeel van de Traagste Tocht etappe Rhenen–Elst',
 'desc': 'De <b>Stadsbossen van Rhenen</b> zijn het bosfront van de stad tegen de zijkant van de Heuvelrug: een afwisselend geheel van <b>naaldbossen, heidevelden, loofbos en de Leemkuil</b> als natuurlijk startpunt. Boven het bos torent de <b>Koerheuvel</b> uit — de stuwwaltop waarop ooit restaurant en watertoren in één gebouw stonden en nu een woontoren staat. Het bijzonderste onderdeel is de <b>Lijstereng</b>: een eeuwenoude <b>eng</b>, het Zuid-Nederlandse woord voor de arme zandgrond-akkers, waar <b>rogge en aardappelen</b> (tegenwoordig veelal maïs) in kleine percelen tussen de bosjes liggen — door bosjes omgeven akkers en weilanden die al eeuwenlang agrarisch in gebruik zijn. In en om deze eng liggen <b>grafheuvels en een urnenveld uit de bronstijd</b> — drieduizend jaar oude graven die de oudste bewoners van de Rijnbocht hier achterlieten. De productiebossen van dennen, lariks en sparren worden stukje bij beetje omgevormd naar <b>structuurrijk bos met rijke ondergroei</b>; de gemeente legde een <b>eco-akker</b> aan waar niet de opbrengst maar de ecologische kwaliteit telt. En langs de routes staan de <b>‘Waterbomen’</b>: zes reusachtige beuken die de eeuwen trotseren. In 2011 verenigden bewoners zich in een stichting die een sportcomplex op de Lijstereng wist te weren — het bos is er nog steeds beter af om.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (zangvogels, bosondergroei), aug–sep (heidebloei op de velmpjes)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — zon tussen de bomen van de Koerheuvel-helling.',
 'why': ['De <b>Lijstereng</b>: eeuwenoude eng-akkers tussen de bosjes van de Heuvelrug.', 'De <b>grafheuvels en urnenveld</b> uit de bronstijd.', 'De <b>Waterbomen</b>: zes reusachtige oude beuken.', 'De <b>Leemkuil</b> als natuurlijke poort van de stad.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Broedvogels</b> van bos, struweel en eng.', '<span class="months">Aug–Sep</span> 🌸 <b>Heiderestanten</b> in bloei.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in de omgevormde bossen.', '<span class="months">Heel jaar</span> 🗼 <b>De Koerheuvel</b> als herkenningspunt.'],
 'wild': ['🌳 Naaldbos, loofbos en heidevelden', '🌾 Eng-akkers (rogge, aardappel, maïs)', '⚱️ Bronstijd-grafheuvels en urnenveld', '🌳 De zes Waterbomen (reusachtige beuken)', '🌾 Eco-akker van de gemeente'],
 'trail': ['Loop de <b>Lijsterengroute</b> (3 km, blauw gemarkeerd) vanaf de <b>Leemkuil</b>.', 'Volg de <b>Traagste Tocht etappe 6</b> (Rhenen–Elst, 16 km) over de eng.', 'Combineer met de <b>Heuvelrughike etappe 5</b> richting Amerongen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚵 Mountainbikeroute kruist de wandelpaden · 🚶 Routes gemarkeerd — volg de paaltjes'
}, {
 'tags': ['Utrecht · Rhenen (Utrechtse Heuvelrug)', 'Town woods of Rhenen with eng fields, heath patches and Bronze Age barrows · Koerheuvel with water tower · Utrechtse Heuvelrug National Park', 'list 36 · no. 779'],
 'loc': '📍 Start De Leemkuil (Autoweg, Rhenen) — Lijstereng route 3 km marked blue · mountain bike route crosses the wood; also part of the Slowest Walk stage Rhenen–Elst',
 'desc': 'The <b>town woods of Rhenen</b> are the city’s forest front on the flank of the Heuvelrug: a varied whole of <b>conifer woods, heath patches, broadleaved wood and the Leemkuil</b> as natural starting point. Above the wood rises the <b>Koerheuvel</b> — the ice-pushed hill top on which a restaurant and water tower once shared one building and a residential tower stands now. The most special part is the <b>Lijstereng</b>: a centuries-old <b>eng</b>, the southern Dutch word for the poor sandy fields, where <b>rye and potatoes</b> (nowadays mostly maize) lie in small parcels between the woods — fields and meadows surrounded by copses that have been farmed for centuries. In and around this eng lie <b>burial mounds and an urnfield from the Bronze Age</b> — three-thousand-year-old graves left by the oldest inhabitants of the Rhine bend. The production woods of pine, larch and spruce are gradually converted into <b>structurally rich forest with a lush understorey</b>; the municipality laid out an <b>eco-field</b> where not the yield but the ecological quality counts. And along the routes stand the <b>‘Water Trees’</b>: six giant beeches defying the centuries. In 2011 residents united in a foundation that kept a sports complex off the Lijstereng — the wood is still the better for it.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds, forest understorey), Aug–Sep (heath in flower)<br>\\n    <b>Best time of day:</b> Morning — sun between the trees on the Koerheuvel slope.',
 'why': ['The <b>Lijstereng</b>: centuries-old eng fields between the Heuvelrug copses.', 'The <b>Bronze Age barrows and urnfield</b>.', 'The <b>Water Trees</b>: six giant old beeches.', 'The <b>Leemkuil</b> as the town’s natural gateway.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Breeding birds</b> of wood, scrub and eng.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath remnants</b> in flower.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the converted woods.', '<span class="months">All year</span> 🗼 <b>The Koerheuvel</b> as landmark.'],
 'wild': ['🌳 Conifer wood, broadleaved wood and heath', '🌾 Eng fields (rye, potato, maize)', '⚱️ Bronze Age barrows and urnfield', '🌳 The six Water Trees (giant beeches)', '🌾 Municipal eco-field'],
 'trail': ['Walk the <b>Lijstereng route</b> (3 km, marked blue) from the <b>Leemkuil</b>.', 'Follow the <b>Slowest Walk stage 6</b> (Rhenen–Elst, 16 km) over the eng.', 'Combine with the <b>Heuvelrughike stage 5</b> towards Amerongen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚵 Mountain bike route crosses the walking paths · 🚶 Routes marked'
}))

C.append(mk.card(2061, 'Wageningse Uiterwaarden', {
 'tags': ['Gelderland · Wageningen (Bovenpolder)', 'Uiterwaarden van de Nederrijn onder de Wageningse Berg · bevers, paarden en runderen · herstel van overstromingsmoeras (2021) · Natura 2000 Rijntakken', 'list 36 · no. 780'],
 'loc': '📍 Tussen Grebbedijk en Nederrijn, beneden Wageningen — toegang vanaf de Grebbedijk / Pabstendam; veerpontje Lexkesveer over de Rijn; bij hoogwater deels afgesloten',
 'desc': 'De <b>Wageningse uiterwaarden</b> — officieel de <b>Bovenpolder</b> — zijn het groene voorland van Wageningen tussen de <b>Grebbedijk</b> en de <b>Nederrijn</b>, met boven zich het <b>Arboretum Belmonte</b> op de Wageningse Berg. <b>Staatsbosbeheer</b> beheert het gebied als levende uiterwaard: <b>paarden en runderen</b> grazen de zuidkant van de nevengeul, terwijl de noordkant sinds 2021 wordt gemaaid — waardoor <b>bloeiende kruiden</b> de grassen verdringen en insecten en rupsen profiteren. De <b>bever</b> is hier vaste gast: wie over de nevengeul tuurt, ziet soms een kopje door het water ploegen (of juist een grauwe gans, die het ook kan zijn — het gebied houdt je aan het verwonderen). In 2021 is het gebied <b>natter gemaakt</b>: de inlaat bij hoogwater gaat eerder open en de stuw bij de <b>Pabstendam</b> houdt een eenhalve voet hoger peil vast, zodat de <b>rietmoerassen met hun bijzondere vogels en amfibieën</b> zich kunnen herstellen — een klein stukje <b>overstromingsmoeras</b> zoals het hier eeuwenlang lag. Bij het <b>Lexkesveer</b vaart een pontje over de Rijn; het oude veerhuis van 1891 staat er nog. Wie de dijk en de polder combineert met de berg erboven, heeft in één middag rivier, moeras en arboretum.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (rietvogels, kruidenbloei), nov–mrt (watervogels, hoogwater-schouwspel)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel over de nevengeul.',
 'why': ['De <b>Bovenpolder</b> als levende uiterwaard onder de Wageningse Berg.', '<b>Paarden, runderen en bevers</b> als mede-vormgevers.', 'Het <b>herstel van het overstromingsmoeras</b> (Pabstendam, 50 cm hoger peil).', 'Het <b>Lexkesveer</b> met zijn veerhuis uit 1891.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Rietvogels</b> in de herstelde moerassen.', '<span class="months">Jun–Aug</span> 🌼 <b>Bloeiende kruiden</b> op de gemaaide noordkant.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> en hoogwater op de uiterwaard.', '<span class="months">Heel jaar</span> 🦫 <b>Bever-sporen</b> langs de wateren.'],
 'wild': ['🐴 Paarden en runderen als begrazers', '🦫 Bever in nevengeul en sloten', '🐦 Riet- en watervogels van de Bovenpolder', '🌿 Rietmoeras met amfibieën', '⛴️ Lexkesveer-pont over de Nederrijn'],
 'trail': ['Wandel de <b>Grebbedijk</b> en de uiterwaardspaden van de Bovenpolder (± 8 km rondje).', 'Steek met het <b>Lexkesveer</b> over naar de overkant van de Rijn.', 'Combineer met <b>Arboretum Belmonte</b> op de Wageningse Berg.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (veerpont betaald) · ⚠️ Bij hoogwater delen afgesloten; zwemmen verboden · 🚶 Knooppuntennetwerk Rivierenland'
}, {
 'tags': ['Gelderland · Wageningen (Bovenpolder)', 'Nederrijn floodplains below the Wageningse Berg · beavers, horses and cattle · flood-marsh restoration (2021) · Natura 2000 Rijntakken', 'list 36 · no. 780'],
 'loc': '📍 Between Grebbedijk and Nederrijn, below Wageningen — access from the Grebbedijk / Pabstendam; Lexkesveer foot ferry across the Rhine; partly closed at high water',
 'desc': 'The <b>Wageningen floodplains</b> — officially the <b>Bovenpolder</b> — are Wageningen’s green foreland between the <b>Grebbedijk</b> and the <b>Nederrijn</b>, with the <b>Belmonte Arboretum</b> on the Wageningse Berg above. <b>Staatsbosbeheer</b> manages the area as a living floodplain: <b>horses and cattle</b> graze the south side of the side channel, while the north side has been mown since 2021 — allowing <b>flowering herbs</b> to push back the grasses, to the benefit of insects and caterpillars. The <b>beaver</b> is a regular here: peer across the side channel and you may see a head ploughing through the water (or precisely a greylag goose — the area keeps you wondering). In 2021 the area was made <b>wetter</b>: the inlet at high water opens earlier and the weir at the <b>Pabstendam</b> holds a level half a foot higher, so the <b>reed marshes with their special birds and amphibians</b> can recover — a small piece of <b>flood marsh</b> as it lay here for centuries. At the <b>Lexkesveer</b> a little ferry crosses the Rhine; the old ferry house of 1891 still stands. Combine dike and polder with the mountain above and you have river, marsh and arboretum in a single afternoon.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (reed birds, herb flowering), Nov–Mar (waterfowl, high-water spectacle)<br>\\n    <b>Best time of day:</b> Morning — mist over the side channel.',
 'why': ['The <b>Bovenpolder</b> as a living floodplain below the Wageningse Berg.', '<b>Horses, cattle and beavers</b> as co-shapers.', 'The <b>flood-marsh restoration</b> (Pabstendam, 50 cm higher level).', 'The <b>Lexkesveer</b> with its 1891 ferry house.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎵 <b>Reed birds</b> in the recovering marshes.', '<span class="months">Jun–Aug</span> 🌼 <b>Flowering herbs</b> on the mown north side.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> and high water on the floodplain.', '<span class="months">All year</span> 🦫 <b>Beaver tracks</b> along the waters.'],
 'wild': ['🐴 Horses and cattle as grazers', '🦫 Beaver in side channel and ditches', '🐦 Reed and water birds of the Bovenpolder', '🌿 Reed marsh with amphibians', '⛴️ Lexkesveer ferry over the Nederrijn'],
 'trail': ['Walk the <b>Grebbedijk</b> and the Bovenpolder floodplain paths (± 8 km loop).', 'Cross the Rhine with the <b>Lexkesveer</b> ferry.', 'Combine with the <b>Belmonte Arboretum</b> on the Wageningse Berg.'],
 'foot': '🐕 Dogs on lead · 💶 Free (ferry paid) · ⚠️ Parts closed at high water; swimming forbidden · 🚶 Rivierenland node network'
}, n2k='Rijntakken — Vogelrichtlijngebied nr. 38 (VR-sitecode NL2014038) over de uiterwaarden van IJssel, Nederrijn en Waal: de Wageningse Bovenpolder valt binnen de Nederrijn-zone; bever, blauwborst en rivier-gebonden vogelsoorten als instandhoudingsdoelen; een derde van het gebied is ook Habitatrichtlijngebied.',
 n2k_en='Rijntakken — Birds Directive site no. 38 (VR site code NL2014038) over the floodplains of IJssel, Nederrijn and Waal: the Wageningen Bovenpolder lies within the Nederrijn zone; beaver, bluethroat and river-bound bird species as conservation targets; a third of the site is also a Habitats Directive area.'))

C.append(mk.card(2062, "Oranje Nassau's Oord", {
 'tags': ['Gelderland · Renkum / Wageningen', 'Landgoed met koninklijk verleden — paleis van Willem III (1883), later tuberculose-sanatorium · Renkums Beekdal en bos op de Wageningse Berg · Ommuurde Tuin', 'list 36 · no. 781'],
 'loc': '📍 Boslaan, Wageningen (landgoed achter het voormalige sanatorium) · Knopenrondje Oranje Nassau\'s Oord 7 km; vorstelijke rondwandeling 14 km over Bergpad en beekdal',
 'desc': 'Op <b>Landgoed Oranje Nassau’s Oord</b> — lokaal kortweg <b>ONO</b> — stond ooit een <b>koninklijk paleis</b>: koning <b>Willem III</b> kocht en verbouwde het huis (1883 gereed, naar ontwerp van tuinarchitect <b>Louis Paul Zocher</b>, die het eikenhakhout door grove den verving) en <b>koningin Emma</b> bracht er enkele zomers door. Het paleis werd later een <b>sanatorium voor longlijders</b> — het licht gebogen gebouw van architect Roelof Kuipers staat er nog, nu als verpleeghuis — en het landgoed werd wat het nog steeds is: <b>weiland in het Renkums Beekdal</b> en <b>bos op de oostflank van de Wageningse Berg</b>, met oude beuken, een hertenkampje en de sporen van de paleistuin. Op de terreinen zijn zelfs <b>broedende raven</b> gesignaleerd. Aan de noordkant sluit het landgoed via Domeinweg en Grenspad aan op de SBB-bossen van de <b>Dorschkamp</b>: een aaneengesloten wandelgebied van Wageningse Berg tot Renkums Beekdal. Bezoekers vinden er de <b>Ommuurde Tuin</b> — de historische moestuin van koning Willem III, nu met theeterras — en verderop de <b>Hartense Oliemolen</b>, ooit één van de negen watermolens van het beekdal. Wie het beekdal oversteekt, doet dat over <b>vlonderpaden</b>: het kan hier zo nat zijn dat wandelen anders niet lukt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (beekdal in lentegroen), sep–okt (herfstkleur in beukenbos)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — nevel in het beekdal onder de berg.',
 'why': ['Het <b>koninklijk paleis</b> van Willem III en Emma (1883, tuin door Zocher).', 'Het <b>sanatorium-verleden</b> — het gebogen gebouw van Kuipers staat er nog.', 'De <b>Ommuurde Tuin</b>: moestuin van koning Willem III met theeterras.', 'De verbinding <b>Dorschkamp–ONO</b>: één wandelgebied van berg tot beekdal.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Lentebloei</b> in beekdal en parkbossen.', '<span class="months">Apr–Jun</span> 🐦 <b>Raven</b> boven de bossen van het landgoed.', '<span class="months">Sep–Okt</span> 🍂 <b>Herfstkleur</b> in de oude beuken.', '<span class="months">Heel jaar</span> 🦌 <b>Hertenkampje</b> aan de rand van het bos.'],
 'wild': ['🦌 Hertenkamp op het landgoed', '🐦 Raven · Staartmezen · Sijzen', '🌳 Oud beukenbos op de bergflank', '💧 Renkums Beekdal met Oliemolenbeek', '🏰 Paleis- en sanatoriumgeschiedenis'],
 'trail': ['Loop het <b>Knopenrondje Oranje Nassau’s Oord</b> (7 km) langs Benedenwaard en beekdal.', 'Neem de <b>vorstelijke rondwandeling</b> (14 km) over Bergpad, Belmonte en Quadenoord.', 'Bezoek de <b>Ommuurde Tuin</b> en de <b>Hartense Oliemolen</b> in het beekdal.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (theeterras betaald) · ⚠️ Vlonderpaden kunnen glad zijn · 🚶 Wandelnetwerk Zuidwest-Veluwe'
}, {
 'tags': ['Gelderland · Renkum / Wageningen', 'Estate with a royal past — palace of Willem III (1883), later tuberculosis sanatorium · Renkums Beekdal and wood on the Wageningse Berg · Walled Garden', 'list 36 · no. 781'],
 'loc': '📍 Boslaan, Wageningen (estate behind the former sanatorium) · Oranje Nassau’s Oord node loop 7 km; royal circular walk 14 km over Bergpad and beek valley',
 'desc': 'On <b>Oranje Nassau’s Oord estate</b> — locally simply <b>ONO</b> — once stood a <b>royal palace</b>: King <b>Willem III</b> bought and rebuilt the house (completed 1883, with grounds by garden architect <b>Louis Paul Zocher</b>, who replaced the oak coppice with Scots pine) and <b>Queen Emma</b> spent several summers here. The palace later became a <b>sanatorium for lung patients</b> — the gently curved building by architect Roelof Kuipers still stands, now a nursing home — and the estate became what it still is: <b>meadows in the Renkums Beekdal</b> and <b>wood on the eastern flank of the Wageningse Berg</b>, with old beeches, a deer enclosure and the traces of the palace garden. Breeding <b>ravens</b> have even been recorded on the grounds. On the north side the estate connects, via Domeinweg and Grenspad, to the Staatsbosbeheer woods of the <b>Dorschkamp</b>: one continuous walking area from Wageningse Berg to the Renkum beek valley. Visitors find the <b>Walled Garden</b> — King Willem III’s historic kitchen garden, now with a tea terrace — and further on the <b>Harten oil mill</b>, once one of the nine water mills of the valley. Crossing the valley means crossing <b>boardwalks</b>: it can be so wet here that walking otherwise fails.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (beek valley in spring green), Sep–Oct (autumn colour in the beech wood)<br>\\n    <b>Best time of day:</b> Morning — mist in the valley below the hill.',
 'why': ['The <b>royal palace</b> of Willem III and Emma (1883, grounds by Zocher).', 'The <b>sanatorium past</b> — Kuipers’ curved building still stands.', 'The <b>Walled Garden</b>: King Willem III’s kitchen garden with tea terrace.', 'The <b>Dorschkamp–ONO connection</b>: one walking area from hill to valley.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flowers</b> in valley and park woods.', '<span class="months">Apr–Jun</span> 🐦 <b>Ravens</b> above the estate woods.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> in the old beeches.', '<span class="months">All year</span> 🦌 <b>Deer enclosure</b> at the wood’s edge.'],
 'wild': ['🦌 Deer enclosure on the estate', '🐦 Ravens · Long-tailed tits · Siskins', '🌳 Old beech wood on the hill flank', '💧 Renkums Beekdal with Oliemolenbeek', '🏰 Palace and sanatorium history'],
 'trail': ['Walk the <b>Oranje Nassau’s Oord node loop</b> (7 km) past Benedenwaard and beek valley.', 'Take the <b>royal circular walk</b> (14 km) over Bergpad, Belmonte and Quadenoord.', 'Visit the <b>Walled Garden</b> and the <b>Harten oil mill</b> in the valley.'],
 'foot': '🐕 Dogs on lead · 💶 Free (tea terrace paid) · ⚠️ Boardwalks can be slippery · 🚶 Zuidwest-Veluwe walking network'
}))

C.append(mk.card(2063, 'Jufferswaard', {
 'tags': ['Gelderland · Renkum', 'Uiterwaard van 31 hectare aan de Nederrijn · Pilo-schoorsteen van de steenfabriek (1875) · beverburchten en paardenkudde · Natura 2000 Rijntakken', 'list 36 · no. 782'],
 'loc': '📍 Tussen papierfabriek Parenco en de Rijnbrug bij Heteren · toegang vanaf de Fonteinallee / Veerweg bij Renkum; Pilo Podwalk (GPS-rondleiding) beschikbaar',
 'desc': 'De <b>Jufferswaard</b> is een klein (31 hectare) maar geliefd natuurgebied in de uiterwaard van de <b>Nederrijn</b>, tussen het fabrieksterrein van papierfabriek <b>Parenco</b> en de Rijnbrug bij Heteren — jaarlijks goede voor ± 55.000 bezoekers. De naam gaat terug tot <b>1372</b>, wanneer hertogin <b>Mechteld van Gelre</b> de ‘<b>Jonckfrouwenweert</b>’ in leen uitgeeft — vermoedelijk vernoemd naar de jonkvrouw van het kasteel, voor wie de opbrengsten bestemd waren. Vanaf <b>1875</b> stond hier een <b>steenfabriek</b>; haar <b>45 meter hoge Pilo-schoorsteen</b> torent nog altijd boven de overwoekerde ruïnes, spoorbaantjes en kleibulten — een industrieel erfgoed dat steeds zeldzamer wordt. De kleigaten van toen zijn nu <b>plassen vol watervogels</b>: <b>zomertaling, bergeend, kleine plevier, porseleinhoen, lepelaar en knobbelzwaan</b> broedden hier in recente jaren — en de beroemde zwarte zwaan <b>Zorro</b> leefde er tot zijn dood. Door de waard loopt de <b>Heelsumse beek</b>, in 2015 verlegd en van een vistrap voorzien; langs beek en plas zijn overal <b>beversporen</b> te zien. Een <b>kudde paarden</b> houdt de vegetatie open, en soms staat het gebied wekenlang onder water — rivier zoals de rivier bedoeld was. De oude <b>Fonteinallee</b> (± 1680) liep als laan van Renkum naar kasteel Doorwerth; op de Noordberg stond ooit de gerechtsplaats. Vrijwilligersgroepen houden de waard schoon, geven excursies en consolideren de schoorsteen — komende generaties waardig.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Jun</b> (broedvogels op de plassen), nov–mrt (watervogels, hoogwater)<br>\\n    <b>Beste tijd van de dag:</b> Vroege ochtend — bevers actief, vogels wakker.',
 'why': ['De <b>Pilo-schoorsteen</b> (45 m) als industriële markant van de waard.', 'De <b>kleiput-plassen</b> met porseleinhoen, lepelaar en kleine plevier.', 'De <b>beverburchten</b> langs Heelsumse beek en plas.', 'Het <b>leen van 1372</b> — de ‘Jonckfrouwenweert’ van Mechteld van Gelre.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Broedvogels</b> op plassen en rivierstrandjes.', '<span class="months">Nov–Mrt</span> 🪿 <b>Watervogels</b> en hoogwater in de waard.', '<span class="months">Heel jaar</span> 🦫 <b>Bever-sporen</b> overal langs het water.', '<span class="months">Heel jaar</span> 🧱 <b>Pilo Podwalk</b> langs ruïnes en schoorsteen.'],
 'wild': ['🐦 Zomertaling · Bergeend · Kleine plevier · Porseleinhoen', '🦆 Lepelaar · Knobbelzwaan', '🦫 Bevers met burchten', '🐴 Paardenkudde als begrazer', '🧱 Pilo-schoorsteen en steenfabriek-ruïnes'],
 'trail': ['Wandel de <b>Jufferswaard</b> vanaf de Fonteinallee / Veerweg bij Renkum.', 'Download de <b>Pilo Podwalk</b> voor het verhaal van steenfabriek en schoorsteen.', 'Combineer met de <b>Noordberg</b> en het <b>Renkums Beekdal</b> (kaart 2062).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Soms wekenlang onder water — laarzen; paden kunnen dichtgroeven · 🚶 Rondje ± 3 km'
}, {
 'tags': ['Gelderland · Renkum', 'Floodplain of 31 hectares on the Nederrijn · Pilo chimney of the brickworks (1875) · beaver lodges and a horse herd · Natura 2000 Rijntakken', 'list 36 · no. 782'],
 'loc': '📍 Between the Parenco paper mill and the Rhine bridge at Heteren · access from the Fonteinallee / Veerweg at Renkum; Pilo Podwalk (GPS-guided tour) available',
 'desc': 'The <b>Jufferswaard</b> is a small (31 hectares) but beloved nature reserve in the floodplain of the <b>Nederrijn</b>, between the Parenco <b>paper mill</b> site and the Rhine bridge at Heteren — good for some <b>55,000 visits a year</b>. The name goes back to <b>1372</b>, when Duchess <b>Mechteld of Guelders</b> granted the ‘<b>Jonckfrouwenweert</b>’ as a fief — presumably named after the lord’s maiden daughter, for whom the proceeds were destined. From <b>1875</b> a <b>brickworks</b> stood here; its <b>45-metre Pilo chimney</b> still towers above the overgrown ruins, rail tracks and clay mounds — industrial heritage grown ever rarer. The clay pits of old are now <b>lakes full of waterfowl</b>: <b>garganey, shelduck, little ringed plover, baillon’s crake, spoonbill and mute swan</b> bred here in recent years — and the famous black swan <b>Zorro</b> lived here until his death. Through the waard runs the <b>Heelsumse beek</b>, relocated in 2015 and given a fish pass; along brook and lake <b>beaver tracks</b> are everywhere. A <b>herd of horses</b> keeps the vegetation open, and at times the area stands under water for weeks — river as the river was meant. The old <b>Fonteinallee</b> (± 1680) ran as a tree-lined lane from Renkum to Doorwerth Castle; on the Noordberg once stood the gallows. Volunteer groups keep the waard clean, guide excursions and consolidate the chimney — worthy of generations to come.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (breeding birds on the lakes), Nov–Mar (waterfowl, high water)<br>\\n    <b>Best time of day:</b> Early morning — beavers active, birds awake.',
 'why': ['The <b>Pilo chimney</b> (45 m) as the waard’s industrial landmark.', 'The <b>clay-pit lakes</b> with baillon’s crake, spoonbill and little ringed plover.', 'The <b>beaver lodges</b> along Heelsumse beek and lake.', 'The <b>fief of 1372</b> — Mechteld of Guelders’ ‘Jonckfrouwenweert’.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Breeding birds</b> on lakes and river beaches.', '<span class="months">Nov–Mar</span> 🪿 <b>Waterfowl</b> and high water in the waard.', '<span class="months">All year</span> 🦫 <b>Beaver tracks</b> everywhere along the water.', '<span class="months">All year</span> 🧱 <b>Pilo Podwalk</b> past ruins and chimney.'],
 'wild': ['🐦 Garganey · Shelduck · Little ringed plover · Baillon’s crake', '🦆 Spoonbill · Mute swan', '🦫 Beavers with lodges', '🐴 Horse herd as grazer', '🧱 Pilo chimney and brickworks ruins'],
 'trail': ['Walk the <b>Jufferswaard</b> from the Fonteinallee / Veerweg at Renkum.', 'Download the <b>Pilo Podwalk</b> for the story of brickworks and chimney.', 'Combine with the <b>Noordberg</b> and the <b>Renkums Beekdal</b> (card 2062).'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ Sometimes under water for weeks — boots; paths can overgrow · 🚶 Loop ± 3 km'
}, n2k='Rijntakken — Vogelrichtlijngebied nr. 38 (VR-sitecode NL2014038): de Jufferswaard ligt als Nederrijn-uiterwaard binnen de begrenzing; de plassen en oevers zijn foerageer- en rustgebied voor rivier- en moerasvogels; de bever als vaste bewoner van de Habitatrichtlijn-zone.',
 n2k_en='Rijntakken — Birds Directive site no. 38 (VR site code NL2014038): the Jufferswaard lies within the boundary as a Nederrijn floodplain; its lakes and banks are feeding and resting ground for river and marsh birds; the beaver as permanent inhabitant of the Habitats Directive zone.'))

C.append(mk.card(2064, 'Wilhelminapark', {
 'tags': ['Gelderland · Heelsum (gemeente Renkum)', 'Parkbos uit 1887 rond het voormalige hotel Klein Zwitserland · lanen en open plekken tussen Ginkelseweg en Doorwerthse Heide · stoomtram-geschiedenis', 'list 36 · no. 783'],
 'loc': '📍 Wilhelminapark/Wilhelminabos bij Heelsum, tussen Ginkelseweg en de Doorwerthse Heide · te voet vanuit Heelsum (stoomtram-tracé Arnhem–Wageningen als historische ruggengraat)',
 'desc': 'Het <b>Wilhelminapark</b> bij <b>Heelsum</b> is een van de stilste hoofdstukken uit de bloeitijd van de Gelderse buitenplaatsen: in <b>1887</b> werd hier — op wat vroeger een hoekje van de <b>Keijenberg</b> was, omringd door heide en eikenhakhout — een <b>park met lanen</b> aangelegd, bedoeld als deftige nieuwe woonwijk bij de <b>stoomtram Arnhem–Wageningen</b>. De bouwmaatschappij ‘Heelsum’ trok er villakopers en dagjesmensen naartoe; vanaf <b>1905/1906</b> verrees het hotel <b>‘Klein Zwitserland’</b> met zijn lanen, heidegronden en de belofte van ‘bosrijke, gezonde en hooggelegen’ lucht. Van het hotel is niets meer over, maar het <b>Wilhelminabos</b> tussen de <b>Ginkelseweg</b> en de <b>Doorwerthse Heide</b> is er nog altijd: een aangelegd bosterrein met <b>rechte lanen, open gedeelten en oude bosranden</b>, waar wandelaars van het Wandelnet-broodje eten op een bank en de streekgeschiedenis uit de krantenknipsels van Heelsum terug te voelen is. Bouwplannen hebben sinds de jaren tachtig herhaaldelijk gesproken over villabouw — de Raad van State hield het merendeel tegen, en zo bleef het bos. Wie de lanen volgt, wandelt in één adem door naar de <b>Renkumse Heide</b> en de <b>Doorwerthse Heide</b> aan de ene kant, en het beekdal en de Rijn aan de andere.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–Mei</b> (voorjaarsflora in de lanen), sep–okt (paddenstoelen)<br>\\n    <b>Beste tijd van de dag:</b> Ochtend — licht tussen de oude lanen.',
 'why': ['Het <b>park van 1887</b> met zijn lanenpatroon uit de tram-periode.', 'Het verhaal van hotel <b>‘Klein Zwitserland’</b> (1905) en de bouwmaatschappij.', 'De ligging tussen <b>Ginkelseweg en Doorwerthse Heide</b> als wandelketen.', 'De <b>behouden strijd</b> tegen villabouw sinds de jaren tachtig.'],
 'phen': ['<span class="months">Apr–Mei</span> 🌸 <b>Voorjaarsflora</b> onder de lanenbomen.', '<span class="months">Jun–Aug</span> 🌳 <b>Zomers loof</b> op de open plekken.', '<span class="months">Sep–Okt</span> 🍄 <b>Paddenstoelen</b> in het oude bos.', '<span class="months">Heel jaar</span> 🚶 <b>Stille lanen</b> voor wandelaars.'],
 'wild': ['🌳 Aangelegd parkbos met lanen (1887)', '🌸 Bosrandflora van de Veluwezoom-rand', '🍄 Paddenstoelen in het najaar', '🐦 Zangvogels van laan en bosrand', '🚋 Stoomtram-geschiedenis Arnhem–Wageningen'],
 'trail': ['Wandel de <b>lanen van het Wilhelminapark</b> vanuit Heelsum.', 'Volg de route naar de <b>Doorwerthse Heide</b> en het <b>Renkums Beekdal</b>.', 'Combineer met de <b>stuwwalwandeling</b> Wageningen–Rhenen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · ⚠️ Geen voorzieningen — rustig boswandgebied · 🚶 Wandelnetwerk Zuidwest-Veluwe'
}, {
 'tags': ['Gelderland · Heelsum (Renkum municipality)', 'Park wood of 1887 around the former hotel Klein Zwitserland · avenues and glades between Ginkelseweg and Doorwerthse Heide · steam tram history', 'list 36 · no. 783'],
 'loc': '📍 Wilhelminapark/Wilhelminabos at Heelsum, between the Ginkelseweg and the Doorwerthse Heide · on foot from Heelsum (the Arnhem–Wageningen steam tram line as historic backbone)',
 'desc': 'The <b>Wilhelminapark</b> at <b>Heelsum</b> is one of the quietest chapters of the Gelderland estate heyday: in <b>1887</b> a <b>park with avenues</b> was laid out here — on what used to be a corner of the <b>Keijenberg</b>, surrounded by heath and oak coppice — meant as a genteel new residential quarter by the <b>Arnhem–Wageningen steam tram</b>. The ‘Heelsum’ building company drew villa buyers and day trippers; from <b>1905/1906</b> the hotel <b>‘Klein Zwitserland’</b> rose with its avenues, heath grounds and the promise of ‘wooded, healthy and elevated’ air. Nothing remains of the hotel, but the <b>Wilhelminabos</b> between the <b>Ginkelseweg</b> and the <b>Doorwerthse Heide</b> is still there: a laid-out woodland with <b>straight avenues, open glades and old wood edges</b>, where Wandelen-walkers eat their sandwich on a bench and the local history of Heelsum’s newspaper clippings can be felt. Building plans have spoken of villa construction since the eighties — the Council of State stopped most of it, and so the wood remained. Follow the avenues and you walk in one breath towards the <b>Renkum heath</b> and the <b>Doorwerthse Heide</b> on one side, and the beek valley and the Rhine on the other.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring flora in the avenues), Sep–Oct (fungi)<br>\\n    <b>Best time of day:</b> Morning — light between the old avenues.',
 'why': ['The <b>park of 1887</b> with its avenue pattern from the tram era.', 'The story of hotel <b>‘Klein Zwitserland’</b> (1905) and the building company.', 'The position between <b>Ginkelseweg and Doorwerthse Heide</b> as a walking chain.', 'The <b>successful defence</b> against villa building since the eighties.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Spring flora</b> under the avenue trees.', '<span class="months">Jun–Aug</span> 🌳 <b>Summer leaf</b> on the glades.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old wood.', '<span class="months">All year</span> 🚶 <b>Quiet avenues</b> for walkers.'],
 'wild': ['🌳 Laid-out park wood with avenues (1887)', '🌸 Wood-edge flora of the Veluwezoom rim', '🍄 Autumn fungi', '🐦 Songbirds of avenue and wood edge', '🚋 Steam tram history Arnhem–Wageningen'],
 'trail': ['Walk the <b>avenues of the Wilhelminapark</b> from Heelsum.', 'Follow the route to the <b>Doorwerthse Heide</b> and the <b>Renkums Beekdal</b>.', 'Combine with the <b>ice-pushed ridge walk</b> Wageningen–Rhenen.'],
 'foot': '🐕 Dogs on lead · 💶 Free · ⚠️ No facilities — quiet woodland walking · 🚶 Zuidwest-Veluwe walking network'
}))

mk.insert(C, chunk='reserves-2035-2134.json')
mk.progress(2064)
mk.check()
