# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2183, 'Tongelaar', {
 'tags': ['Noord-Brabant · bij Grave/Escharen (Maasvallei-zuidrand)', 'klein natuurgebied in de Grave-vlakte · de naam van een oude hoeveplaats tussen Raamdal en Kraaijenbergse Plassen — graslanden, poelen en hagen in het stramien van de oude Maasland', 'list 81 · no. 12'],
 'loc': '📍 Tongelaar, ten zuiden van Grave bij Escharen — landwegen rond de percelen; combineer met het Raamdal (kaart 2180) en de Kraaijenbergse Plassen',
 'desc': 'In de vlakte ten zuiden van <b>Grave</b>, waar de oude hoevenamen de kaart nog tekenen, ligt <b>Tongelaar</b>: een klein natuurgebied dat zijn naam draagt van een hoeveplaats uit de middeleeuwse ontginning van de Maasrand. Het is gebied van het bescheiden soort — graslanden, poelen, hagen en slootkanten, ingepast in het stramien van de Grave-vlakte — maar zijn ligging maakt het tot schakel tussen de grote buren: het <b>Raamdal</b> (kaart 2180) in het oosten, de <b>Kraaijenbergse Plassen</b> in het noorden, en de Gasselse Heide (kaart 2181) in het zuiden. Wie hier in het vroege voorjaar loopt, hoort de weidevogels van de vlakte; in de zomer jagen libellen boven de poelen; en in de winter grazen de ganzen op de natte percelen. De gids noteert Tongelaar om dezelfde reden als het boek: omdat de kleine namen de grote verbindingen dragen — en omdat wie de vlakte wil begrijpen, ook de hoevenamen moet leren lezen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (weidevogels), jun–aug (libellen), okt–mrt (ganzen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — de vlakte ontwaakt.',
 'why': ['De <b>oude hoevenaam</b> uit de middeleeuwse Maasontginning.', 'De <b>schakelligging</b> tussen Raamdal en de plassen.', 'De <b>weidevogels</b> van de Grave-vlakte.', 'De <b>poelen en hagen</b> als klein-grondelementen.', 'Het <b>lezen van de vlakte</b> via haar namen.'],
 'phen': ['<span class="months">Apr–jun</span> 🐦 <b>Weidevogels</b> boven de percelen.', '<span class="months">Jun–aug</span> 🪰 <b>Libellen</b> bij poel en sloot.', '<span class="months">Sep–nov</span> 🍂 <b>Herfstlicht</b> over de vlakte.', '<span class="months">Nov–feb</span> 🪿 <b>Ganzen</b> op het natte gras.'],
 'wild': ['🌾 Graslanden en poelen', '🌳 Hagen en houtsingels', '🐦 Weidevogels', '🦆 Watervogels', '📜 Oude hoevenaam'],
 'trail': ['Wandel de <b>landwegen rond Tongelaar</b>.', 'Leg de verbinding met het <b>Raamdal</b> (kaart 2180).', 'Bekijk de <b>Kraaijenbergse Plassen</b> bij hoogwater.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Korte rondes ± 2–5 km · ⚠️ Agrarisch verkeer op de wegen'
}, {
 'tags': ['North Brabant · near Grave/Escharen (Meuse-valley south edge)', 'small nature area in the Grave plain · the name of an old farmstead between Raamdal and the Kraaijenbergse Plassen — grasslands, pools and hedges in the old Maasland grain', 'list 81 · no. 12'],
 'loc': '📍 Tongelaar, south of Grave near Escharen — lanes around the parcels; combine with the Raamdal (card 2180) and the Kraaijenbergse Plassen',
 'desc': 'In the plain south of <b>Grave</b>, where old farmstead names still draw the map, lies <b>Tongelaar</b>: a small nature area named for a homestead of the medieval reclamation of the Meuse edge. It is country of the modest kind — grasslands, pools, hedges and ditch sides, fitted into the grain of the Grave plain — but its position makes it a link between the great neighbours: the <b>Raamdal</b> (card 2180) to the east, the <b>Kraaijenbergse Plassen</b> to the north, and the Gasselse Heide (card 2181) to the south. Walk here in early spring and you hear the plain’s meadow birds; in summer dragonflies hunt above the pools; and in winter geese graze the wet parcels. The guide notes Tongelaar for the same reason the book did: because the small names carry the great connections — and because whoever wishes to understand the plain must also learn to read its farmstead names.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow birds), Jun–Aug (dragonflies), Oct–Mar (geese)<br>\n    <b>Best time of day:</b> Morning — the plain wakes.',
 'why': ['The <b>old farmstead name</b> of the medieval Meuse reclamation.', 'The <b>link position</b> between Raamdal and the lakes.', 'The <b>meadow birds</b> of the Grave plain.', 'The <b>pools and hedges</b> as small-scale elements.', '<b>Reading the plain</b> through its names.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Meadow birds</b> above the parcels.', '<span class="months">Jun–Aug</span> 🪰 <b>Dragonflies</b> at pool and ditch.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn light</b> over the plain.', '<span class="months">Nov–Feb</span> 🪿 <b>Geese</b> on the wet grass.'],
 'wild': ['🌾 Grasslands and pools', '🌳 Hedges and belts', '🐦 Meadow birds', '🦆 Water birds', '📜 Old farmstead name'],
 'trail': ['Walk the <b>lanes around Tongelaar</b>.', 'Make the link with the <b>Raamdal</b> (card 2180).', 'View the <b>Kraaijenbergse Plassen</b> at high water.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Short loops ± 2–5 km · ⚠️ Agricultural traffic on the roads'
}))

C.append(mk.card(2184, 'Langenboom', {
 'tags': ['Noord-Brabant · Langenboom (gemeente Mill en Sint Hubert)', 'de Langenboomse Bossen van Natuurmonumenten · dennen op oude heide en stuifzand, dassenburchten, de levendbarende hagedis en het Duits Lijntje — spoorweg en militair oefenterrein in één bos', 'list 81 · no. 13'],
 'loc': '📍 Langenboomse Bossen, ten noordwesten van Mill rond Langenboom — parkeerplaats De Kuilen (Fazantenweg 16); wandelroutes door bos en heiderestanten; beheer Natuurmonumenten (sinds 2000)',
 'desc': 'Rond het kerkdorp <b>Langenboom</b> liggen de <b>Langenboomse Bossen</b>: sinds <b>2000</b> in beheer van <b>Natuurmonumenten</b>, gegroeid uit de heide en het stuifzand dat hier in de 19e eeuw nog het beeld bepaalde. Alleen geschikt om <b>schapen te hoeden</b>, zei men toen — tot begin 20e eeuw de <b>dennen</b> kwamen, aangeplant voor de houtproductie: de grove stammen die vandaag het dak van het gebied vormen. In de ondergroei leeft een verborgen gezelschap: de <b>das</b> heeft er verschillende <b>burchten</b>, de beschermde <b>levendbarende hagedis</b> heeft via het beheer van Natuurmonumenten de weg terug gevonden naar de heideveldjes, en in de herfst staan <b>vliegenzwam en ridderzwam</b> tussen de naalden. Door het bos loopt het <b>Duits Lijntje</b>, de oude spoorweg Boxtel–Wesel, als kaarsrecht lint door het groen; <b>Defensie</b> oefent er nog met verbindingseenheden — geknal en militaire voertuigen horen bij het gebied. In de boomkronen broeden <b>boomklever</b> en drie soorten <b>spechten</b>; boven het geheel cirkelen <b>wespendief en havik</b>. Wie de rondes van De Kuilen (kaart 2179) loopt, wandelt dwars door dit bos — en door honderd jaar bosgeschiedenis.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jun</b> (vogels), jul–aug (hagedissen in de zon), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — vogelkoor vóór de oefeningen.',
 'why': ['De <b>dennen op oude heide</b> — honderd jaar bosgeschiedenis.', 'De <b>dassenburchten</b> in het stille bos.', 'De <b>levendbarende hagedis</b> terug op de heideveldjes.', 'Het <b>Duits Lijntje</b> als spoorlint door het bos.', '<b>Wespendief en havik</b> boven de kronen.'],
 'phen': ['<span class="months">Apr–jun</span> 🐦 <b>Boomklever en spechten</b> in de kronen.', '<span class="months">Jul–aug</span> 🦎 <b>Levendbarende hagedis</b> op de heideranden.', '<span class="months">Sep–okt</span> 🍄 <b>Vliegenzwam en ridderzwam</b>.', '<span class="months">Nov–feb</span> ❄️ <b>Sneeuwstilte</b> langs het Duits Lijntje.'],
 'wild': ['🌲 Dennenbos op oude heide', '🦡 Dassenburchten', '🦎 Levendbarende hagedis', '🚂 Duits Lijntje', '🦅 Wespendief en havik'],
 'trail': ['Wandel de <b>routes vanuit De Kuilen</b> door de bossen.', 'Zoek de <b>heideveldjes</b> voor hagedis en vlinders.', 'Let op <b>militaire oefeningen</b> en het spoorlint.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes ± 3–8 km · ⚠️ Defensie-oefeningen mogelijk — aanwijzingen volgen'
}, {
 'tags': ['North Brabant · Langenboom (municipality of Mill en Sint Hubert)', 'the Langenboomse Bossen of the Netherlands Nature Trust · pines on old heath and drift sand, badger setts, the viviparous lizard and the Duits Lijntje — railway and military training ground in one wood', 'list 81 · no. 13'],
 'loc': '📍 Langenboomse Bossen, northwest of Mill around Langenboom — car park De Kuilen (Fazantenweg 16); walking routes through wood and heath remnants; managed by Natuurmonumenten (since 2000)',
 'desc': 'Around the church village of <b>Langenboom</b> lie the <b>Langenboomse Bossen</b>: managed by the <b>Netherlands Nature Trust (Natuurmonumenten)</b> since <b>2000</b>, grown from the heath and drift sand that ruled the image here in the 19th century. Fit only <b>for shepherds</b>, they said then — until the <b>pines</b> arrived in the early 20th century, planted for timber: the towering trunks that today roof the area. In the undergrowth lives a hidden company: the <b>badger</b> keeps several <b>setts</b> here, the protected <b>viviparous lizard</b> has found its way back to the little heaths through the Trust’s management, and in autumn <b>fly agaric and knight fungus</b> stand among the needles. Through the wood runs the <b>Duits Lijntje</b>, the old Boxtel–Wesel railway, a dead-straight ribbon through the green; the <b>military</b> still trains here with signals units — gunfire and army vehicles belong to the area. In the canopy breed <b>nuthatch</b> and three species of <b>woodpecker</b>; above it all circle <b>honey buzzard and goshawk</b>. Walk the loops from De Kuilen (card 2179) and you cross this wood — and a century of forest history.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (birds), Jul–Aug (lizards in the sun), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Early morning — birdsong before the exercises.',
 'why': ['The <b>pines on old heath</b> — a century of forest history.', 'The <b>badger setts</b> in the quiet wood.', 'The <b>viviparous lizard</b> back on the heaths.', 'The <b>Duits Lijntje</b> as a rail ribbon through the wood.', '<b>Honey buzzard and goshawk</b> above the canopy.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Nuthatch and woodpeckers</b> in the canopy.', '<span class="months">Jul–Aug</span> 🦎 <b>Viviparous lizard</b> on the heath edges.', '<span class="months">Sep–Oct</span> 🍄 <b>Fly agaric and knight fungus</b>.', '<span class="months">Nov–Feb</span> ❄️ <b>Snow silence</b> along the Duits Lijntje.'],
 'wild': ['🌲 Pine wood on old heath', '🦡 Badger setts', '🦎 Viviparous lizard', '🚂 Duits Lijntje', '🦅 Honey buzzard and goshawk'],
 'trail': ['Walk the <b>routes from De Kuilen</b> through the woods.', 'Seek the <b>little heaths</b> for lizard and butterflies.', 'Mind <b>military exercises</b> and the rail ribbon.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes ± 3–8 km · ⚠️ Defence exercises possible — follow instructions'
}))

C.append(mk.card(2185, 'Ossenbroek, Nieuwenhof en De Dennen', {
 'tags': ['Noord-Brabant · Land van Cuijk (streek tussen Mill en Oploo)', 'drie bosnamen uit de Cuijkse ontginningsgeschiedenis · os-broek, nieuwe hof en dennen-aanplant — kleine percelen die de verscheidenheid van het Land van Cuijk op straatniveau laten zien', 'list 81 · no. 14'],
 'loc': '📍 Bospercelen Ossenbroek, Nieuwenhof en De Dennen in het Land van Cuijk tussen Mill, Sint Anthonis en Oploo — landelijke rondes; combineer met de staatsbossen en natuurpoorten',
 'desc': 'Drie namen, drie hoofdstukken ontginning: <b>Ossenbroek</b> — het natte broek waar de ossen weidden; <b>Nieuwenhof</b> — de “nieuwe hof”, akkerlijk goed van een late ontginning; en <b>De Dennen</b> — de aanplant die de naam van zijn bomen draagt. Samen zijn ze de kleine lettertypes van het <b>Land van Cuijk</b> (kaart 2182): percelen bos die op de grote kaart bijna verdwijnen tussen de staatsbossen van Sint Anthonis en de bossen van Mill, maar die in het veld de verscheidenheid maken waar de streek trots op is. Hier wisselen dennenrand en eikenbos, sandpad en poel, open ruit en dicht struweel elkaar af op enkele honderden meters — precies de mozaïekstructuur waarin specht, das en nachtzwaluw zich thuis voelen. De gids noteert ze zoals het boek ze noteerde: als bewijs dat het meest gevarieerde landschap van Nederland niet alleen in de grote gebieden woont, maar vooral in de naamloze percelen ertussen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (vogels), jun–jul (nachtzwaluw-kans), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Schemering — het uur van de nachtzwaluw.',
 'why': ['De <b>drie namen</b> als drie hoofdstukken ontginning.', 'De <b>mozaïekstructuur</b> van kleine bospercelen.', 'De <b>ligging tussen</b> de grote staatsbossen.', 'De <b>nachtzwaluw-kans</b> op de open plekken.', 'De <b>verscheidenheid</b> van het Land van Cuijk in het klein.'],
 'phen': ['<span class="months">Apr–jun</span> 🐦 <b>Zangvogels</b> in de percelen.', '<span class="months">Jun–jul</span> 🌙 <b>Nachtzwaluw</b> bij schemer (kans).', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> op zand en stobben.', '<span class="months">Dec–feb</span> ❄️ <b>Winterrondes</b> tussen de dennen.'],
 'wild': ['🌲 Dennenrand en eikenbos', '💧 Poelen en sandpaden', '🐦 Spechten en zangvogels', '🌙 Nachtzwaluw (kans)', '🧩 Mozaïek van percelen'],
 'trail': ['Wandel de <b>landelijke rondes</b> tussen Mill, Oploo en Sint Anthonis.', 'Verbind de percelen met de <b>staatsbossen</b> (kaart 2182).', 'Kies de <b>schemering</b> voor de nachtzwaluw-kans.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes naar keuze · ⚠️ Kleine percelen — privaat randbeleid respecteren'
}, {
 'tags': ['North Brabant · Land van Cuijk (country between Mill and Oploo)', 'three wood names from the Cuijk reclamation history · ox-carr, new farmstead and pine plantation — small parcels showing the Land van Cuijk’s variety at street level', 'list 81 · no. 14'],
 'loc': '📍 Wood parcels Ossenbroek, Nieuwenhof and De Dennen in the Land van Cuijk between Mill, Sint Anthonis and Oploo — rural loops; combine with the state forests and nature gates',
 'desc': 'Three names, three chapters of reclamation: <b>Ossenbroek</b> — the wet carr where oxen grazed; <b>Nieuwenhof</b> — the “new farmstead”, arable land of a late reclamation; and <b>De Dennen</b> — the plantation named for its pines. Together they are the small print of the <b>Land van Cuijk</b> (card 2182): parcels of woodland that nearly vanish on the big map between the state forests of Sint Anthonis and the woods of Mill, but that in the field create the variety the region prides itself on. Here pine edge and oak wood, sand path and pool, open ride and dense scrub alternate within a few hundred metres — precisely the mosaic structure in which woodpecker, badger and nightjar feel at home. The guide notes them as the book did: as proof that the most varied landscape of the Netherlands lives not only in its great reserves, but above all in the nameless parcels between them.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birds), Jun–Jul (nightjar chance), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Dusk — the nightjar’s hour.',
 'why': ['The <b>three names</b> as three chapters of reclamation.', 'The <b>mosaic structure</b> of small woodland parcels.', 'The <b>position between</b> the great state forests.', 'The <b>nightjar chance</b> in the open parts.', 'The <b>variety</b> of the Land van Cuijk in miniature.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Songbirds</b> in the parcels.', '<span class="months">Jun–Jul</span> 🌙 <b>Nightjar</b> at dusk (chance).', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on sand and stumps.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter loops</b> among the pines.'],
 'wild': ['🌲 Pine edge and oak wood', '💧 Pools and sand paths', '🐦 Woodpeckers and songbirds', '🌙 Nightjar (chance)', '🧩 Mosaic of parcels'],
 'trail': ['Walk the <b>rural loops</b> between Mill, Oploo and Sint Anthonis.', 'Link the parcels with the <b>state forests</b> (card 2182).', 'Choose <b>dusk</b> for the nightjar chance.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops of your choice · ⚠️ Small parcels — respect private edges'
}))

C.append(mk.card(2186, 'Zevenhutten', {
 'tags': ['Noord-Brabant · Land van Cuijk (streek rond Sint Anthonis/Westerbeek)', 'klein bos- en heidegebied bij de Zevenhutten · naam van een huttencomplex uit de ontginningstijd — de bescheiden nawerking van de grote staatsbossen om de hoek', 'list 81 · no. 15'],
 'loc': '📍 Zevenhutten, in het Land van Cuijk tussen Sint Anthonis en Westerbeek — landwegen rond bos en heiderestanten; combineer met de Ullingse Bergen en het Sint Anthonisbos',
 'desc': 'De naam <b>Zevenhutten</b> bewaart de herinnering aan wat hier vóór het bos stond: een handvol hutten van de ontginners, arbeiders en schaapherders die op de heide van het Land van Cuijk hun onderkomen vonden. Toen de grote ontginningen van de twintigste eeuw de heide in dennen en akkers verdeelden, bleven rond zulke plaatsnamen kleine bos- en heidecomplexen achter — de rafelrand van de staatsbossen die Sint Anthonis, Westerbeek en Wanroij tot één gordel smeedden (kaart 2182). Zevenhutten is zo’n rafelrand: deels dennen op oud zand, deels heiderestant waar de jeneverbes kans ziet, doorkruist met sandpaden die de streek haar karakter geven. In de vroege ochtend zingt hier de veldleeuwerik; in de schemer bonkt de nachtzwaluw — dichterbij dan in de grote bossen, want dit kleintje heeft alles dicht bij elkaar. Wie de Natuurpoort Sint Anthonis als basis neemt, wandelt hier de stille tegenhanger van de drukke Ullingse Bergen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (vogels), jun–jul (nachtzwaluw), aug–sep (heide en jeneverbes)<br>\n    <b>Beste tijd van de dag:</b> Schemering — nachtzwaluw en stilte.',
 'why': ['De <b>naam uit de huttentijd</b> van de heide-ontginning.', 'De <b>rafelrand van de staatsbossen</b> als habitat.', 'De <b>jeneverbes</b> op de heiderestanten.', 'De <b>nachtzwaluw</b> dicht bij de wandelaar.', 'De <b>stille tegenhanger</b> van de Ullingse Bergen.'],
 'phen': ['<span class="months">Apr–jun</span> 🐦 <b>Veldleeuwerik</b> boven het heiderestant.', '<span class="months">Jun–jul</span> 🌙 <b>Nachtzwaluw</b> in de schemering.', '<span class="months">Aug–sep</span> 🌸 <b>Heide en jeneverbes</b> in herfsttooi.', '<span class="months">Okt–nov</span> 🍂 <b>Paddenstoelen</b> in de dennenranden.'],
 'wild': ['🌲 Dennen op oud zand', '🌸 Heiderestanten', '🌲 Jeneverbes', '🌙 Nachtzwaluw', '🛖 Hutten-naam uit de ontginning'],
 'trail': ['Wandel de <b>sandpaden rond Zevenhutten</b>.', 'Combineer met de <b>Ullingse Bergen</b> en het <b>Sint Anthonisbos</b>.', 'Start bij de <b>Natuurpoort Sint Anthonis</b> (Bosweg 40).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Korte rondes ± 3–5 km · ⚠️ Open terrein — zon en wind'
}, {
 'tags': ['North Brabant · Land van Cuijk (country around Sint Anthonis/Westerbeek)', 'small wood and heath area at the Zevenhutten · name of a hut complex from the reclamation era — the modest afterglow of the great state forests around the corner', 'list 81 · no. 15'],
 'loc': '📍 Zevenhutten, in the Land van Cuijk between Sint Anthonis and Westerbeek — lanes around wood and heath remnants; combine with the Ullingse Bergen and the Sint Anthonisbos',
 'desc': 'The name <b>Zevenhutten</b> (“seven huts”) preserves the memory of what stood here before the wood: a handful of huts of the reclaimers, labourers and shepherds who found shelter on the heath of the Land van Cuijk. When the great reclamations of the twentieth century divided the heath into pines and fields, small wood and heath complexes survived around such place names — the frayed edge of the state forests that forged Sint Anthonis, Westerbeek and Wanroij into one belt (card 2182). Zevenhutten is such a frayed edge: partly pines on old sand, partly heath remnant where the juniper stands a chance, crossed by the sand paths that give the region its character. In the early morning the sky lark sings here; at dusk the nightjar churs — closer than in the great forests, for this little one has everything within reach. Take the Sint Anthonis nature gate as your base and you walk here the quiet counterpart of the busy Ullingse Bergen.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birds), Jun–Jul (nightjar), Aug–Sep (heath and juniper)<br>\n    <b>Best time of day:</b> Dusk — nightjar and silence.',
 'why': ['The <b>name from the hut era</b> of the heath reclamation.', 'The <b>frayed edge of the state forests</b> as habitat.', 'The <b>juniper</b> on the heath remnants.', 'The <b>nightjar</b> close to the walker.', 'The <b>quiet counterpart</b> of the Ullingse Bergen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Sky lark</b> above the heath remnant.', '<span class="months">Jun–Jul</span> 🌙 <b>Nightjar</b> at dusk.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath and juniper</b> in autumn dress.', '<span class="months">Oct–Nov</span> 🍂 <b>Fungi</b> in the pine edges.'],
 'wild': ['🌲 Pines on old sand', '🌸 Heath remnants', '🌲 Juniper', '🌙 Nightjar', '🛖 Hut name from the reclamation'],
 'trail': ['Walk the <b>sand paths around Zevenhutten</b>.', 'Combine with the <b>Ullingse Bergen</b> and the <b>Sint Anthonisbos</b>.', 'Start at the <b>Sint Anthonis nature gate</b> (Bosweg 40).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Short loops ± 3–5 km · ⚠️ Open ground — sun and wind'
}))

C.append(mk.card(2187, 'Mookerschans', {
 'tags': ['Limburg/Noord-Brabant · Mook (Zandsteeg), stuwwal van het Rijk van Nijmegen', 'zeventiende-eeuws verdedigingswerk met uitkijktoren · vierkante schans met hele en halve bastions uit de tijd van Willem III — Schotse Hooglanders, zandhagedis en overzicht over de Mookerheide', 'list 81 · no. 17'],
 'loc': '📍 Mookerschans bij de Zandsteeg, Mook — uitkijktoren op de schans met overzicht over de heide; onderdeel van de gordel Mookerheide–Herrendal–Sint Jansberg; geen honden toegestaan',
 'desc': 'Bij de <b>Zandsteeg</b> in Mook ligt de <b>Mookerschans</b>: een zeventiende-eeuws <b>verdedigingswerk</b>, uitgevoerd als een <b>vierkant met aan de noordzijde hele bastions en aan de zuidzijde halve</b> — vermoedelijk opgeworpen ten tijde van stadhouder <b>Willem III</b>, in de eeuw waarin de Rijk-van-Nijmegense heuvels steeds opnieuw krijgstoneel waren. Uit die tijd stamt ook de Slag op de Mookerheide van 1574, twee kilometer verderop (kaart 2189). Op de <b>uitkijktoren</b> van de schans is vandaag een deel van de heide te overzien — de functie is dus eigenlijk onveranderd: eerst de vijand, nu de natuur zien aankomen. Om de schans grazen <b>Schotse Hooglanders</b>, die de begroeiing kort houden en de diversiteit van de plantengroei ten goede komen; in de zandige randen leeft de <b>zandhagedis</b>. Een <b>gedenksteen</b> herinnert aan de naamgever van de stichting die dit natuurgebied aan <b>Vereniging Natuurmonumenten</b> schonk. De Mookerschans vormt met de Mookerheide, het Herrendal (kaart 2188) en de Sint Jansberg één reeks heuvels uit de ijstijden — de ademruimte van de regio, met de oorlog als oude huisgenoot.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heidebloei), apr–jun (vogels), mei–sep (hagedissen in de zon)<br>\n    <b>Beste tijd van de dag:</b> Middag — hagedissen; avond — heide in het licht.',
 'why': ['De <b>schans van Willem III</b> met hele en halve bastions.', 'De <b>uitkijktoren</b> over de Mookerheide.', 'De <b>Schotse Hooglanders</b> rond de wallen.', 'De <b>zandhagedis</b> in de zandige randen.', 'De <b>gedenksteen</b> van de schenker aan Natuurmonumenten.'],
 'phen': ['<span class="months">Apr–jun</span> 🐦 <b>Tapuiten en zangvogels</b> op de heide.', '<span class="months">Mei–sep</span> 🦎 <b>Zandhagedis</b> in de zon.', '<span class="months">Aug–sep</span> 🌸 <b>Heidebloei</b> vanaf de toren.', '<span class="months">Okt–nov</span> 🍂 <b>Herfstlicht</b> over wallen en bastions.'],
 'wild': ['🏰 17e-eeuwse schans', '🗼 Uitkijktoren', '🌽 Schotse Hooglanders', '🦎 Zandhagedis', '🌸 Mookerheide-uitzicht'],
 'trail': ['Beklim de <b>uitkijktoren</b> op de Mookerschans.', 'Wandel door naar de <b>Mookerheide</b> (kaart 2189) en het <b>Herrendal</b> (kaart 2188).', 'Lees de <b>gedenksteen</b> en de schansvorm in het veld.'],
 'foot': '🚫 Honden niet toegestaan · 💶 Gratis · 🚶 Rondes ± 3–6 km over de heuvelgordel'
}, {
 'tags': ['Limburg/North Brabant · Mook (Zandsteeg), push moraine of the Rijk van Nijmegen', 'seventeenth-century defensive work with watchtower · a square sconce with full and half bastions from the era of William III — Highland cattle, sand lizard and a view over the Mookerheide', 'list 81 · no. 17'],
 'loc': '📍 Mookerschans at the Zandsteeg, Mook — watchtower on the sconce overlooking the heath; part of the belt Mookerheide–Herrendal–Sint Jansberg; no dogs allowed',
 'desc': 'At the <b>Zandsteeg</b> in Mook lies the <b>Mookerschans</b>: a seventeenth-century <b>defensive work</b>, laid out as <b>a square with full bastions on the north side and half bastions on the south</b> — probably raised in the days of stadtholder <b>William III</b>, in the century when the hills of the Rijk van Nijmegen were theatre of war again and again. From that age too dates the Battle of the Mookerheide of 1574, two kilometres away (card 2189). From the <b>watchtower</b> on the sconce part of the heath can be surveyed today — the function, in truth, unchanged: first the enemy, now nature to be seen coming. Around the sconce <b>Highland cattle</b> graze, keeping the growth short and benefiting the diversity of the flora; in the sandy edges lives the <b>sand lizard</b>. A <b>memorial stone</b> recalls the namesake of the foundation that gave this nature reserve to the <b>Netherlands Nature Trust (Natuurmonumenten)</b>. With the Mookerheide, the Herrendal (card 2188) and the Sint Jansberg the Mookerschans forms one chain of ice-age hills — the region’s breathing space, with war as its old housemate.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heath bloom), Apr–Jun (birds), May–Sep (lizards in the sun)<br>\n    <b>Best time of day:</b> Midday — lizards; evening — heath in the light.',
 'why': ['The <b>sconce of William III</b> with full and half bastions.', 'The <b>watchtower</b> over the Mookerheide.', 'The <b>Highland cattle</b> around the ramparts.', 'The <b>sand lizard</b> in the sandy edges.', 'The <b>memorial stone</b> of the donor to Natuurmonumenten.'],
 'phen': ['<span class="months">Apr–Jun</span> 🐦 <b>Stonechats and songbirds</b> on the heath.', '<span class="months">May–Sep</span> 🦎 <b>Sand lizard</b> in the sun.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath bloom</b> from the tower.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn light</b> over ramparts and bastions.'],
 'wild': ['🏰 17th-century sconce', '🗼 Watchtower', '🌽 Highland cattle', '🦎 Sand lizard', '🌸 Mookerheide view'],
 'trail': ['Climb the <b>watchtower</b> on the Mookerschans.', 'Walk on to the <b>Mookerheide</b> (card 2189) and the <b>Herrendal</b> (card 2188).', 'Read the <b>memorial stone</b> and the sconce shape in the field.'],
 'foot': '🚫 Dogs not allowed · 💶 Free · 🚶 Loops ± 3–6 km across the hill belt'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2187)
mk.check()
