# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2193, 'Goorbos', {
 'tags': ['Noord-Brabant · Schaijk-streek (noordwestelijke Maashorst-rand)', 'bos op “goor” — nat, schraal land · het goorbos van Schaijk als vochtige tegenhanger van de droge Maashorstbossen: kwel, elzen en zachte paden in de gordel van de gemeentebossen', 'list 81 · no. 26'],
 'loc': '📍 Goorbos in de bosgordel van Schaijk (noordrand van De Maashorst) — zandpaden en landwegen; combineer met de Maashorst-routes en Herperduin (kaart 2174)',
 'desc': 'In de bosgordel van <b>Schaijk</b>, waar de gemeentebossen al eeuwen de noordrand van De Maashorst bezetten, ligt het <b>Goorbos</b>: het bos dat zijn naam draagt van het <b>goor</b> — in Brabant het woord voor nat, schraal land waar kwel en opslag het voor het zeggen hebben. Waar de hogere Maashorstgronden (kaart 2174) droog en stuivend zijn, is de goor het omgekeerde: zacht, vochtig, met elzen en berken die natte voeten verdragen, en met paden die in de winter modderig blijven — precies waarom de boswandelaar hier liever komt dan de fietser. Het Goorbos is een bescheiden parel binnen de grotere gordel: geen poorten of torens, maar de stille overgang van eiken- naar elzenbos, van droog naar nat, die de Maashorst zijn volledige karakter geeft. In het voorjaar bloeien hier de eerste bosanemonen op de overgangszones; in de herfst is het de paddenstoelen van het natte bos die de show stelen. Wie de hele gordel loopt, voelt het goor als het hart van de streek: het water dat van de hoogte komt, blijft hier hangen — en maakt het groen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (voorjaarsflora), sep–nov (paddenstoelen in het natte bos), winter (kwel zichtbaar in sloten en plassen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en licht in het elzenbos.',
 'why': ['Het <b>goor</b> — nat schraalland als naamgever.', 'De <b>vochtige tegenhanger</b> van de droge Maashorstbossen.', 'Het <b>elzen- en berkenbos</b> van de kwelzone.', 'De <b>gordel van Schaijk</b> als groene noordrand.', 'De <b>paddenstoelen</b> van het natte bos.'],
 'phen': ['<span class="months">Mrt–apr</span> 🌷 <b>Bosanemoon</b> op de overgangszones.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het zachte groen.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelengolf</b> van het natte bos.', '<span class="months">Dec–feb</span> 💧 <b>Kwel en sloten</b> op hun volst.'],
 'wild': ['💧 Nat schraalland (goor)', '🌳 Elzen- en berkenbos', '🍄 Paddenstoelen', '🐦 Zangvogels', '🥾 Zachte paden'],
 'trail': ['Wandel de <b>zandpaden van het Goorbos</b> bij Schaijk.', 'Combineer met de <b>Maashorst-gordel</b> en Herperduin (kaart 2174).', 'Voel de <b>overgang droog-nat</b> onder je voeten.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–6 km · 👢 In de winter laarzen raad'
}, {
 'tags': ['North Brabant · Schaijk country (northwestern Maashorst edge)', 'wood on “goor” — wet, poor land · the Schaijk goor wood as the damp counterpart of the dry Maashorst forests: seepage, alders and soft paths in the belt of the municipal woods', 'list 81 · no. 26'],
 'loc': '📍 Goorbos in the woodland belt of Schaijk (north edge of De Maashorst) — sand paths and lanes; combine with the Maashorst routes and Herperduin (card 2174)',
 'desc': 'In the woodland belt of <b>Schaijk</b>, where the municipal woods have held the northern edge of De Maashorst for centuries, lies the <b>Goorbos</b>: the wood named for the <b>goor</b> — in Brabant the word for wet, nutrient-poor land ruled by seepage and soft ground. Where the higher Maashorst soils (card 2174) are dry and drifting, the goor is the opposite: soft, damp, with alders and birches that tolerate wet feet, and paths that stay muddy in winter — precisely why the woodland walker prefers it here. The Goorbos is a modest pearl within the greater belt: no gates or towers, but the quiet transition from oak to alder wood, from dry to wet, that gives the Maashorst its full character. In spring the first wood anemones bloom on the transition zones; in autumn the fungi of the damp wood steal the show. Walk the whole belt and you feel the goor as the region’s heart: the water coming down from the heights stays here — and makes the green.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring flora), Sep–Nov (fungi of the damp wood), winter (seepage visible in ditches and pools)<br>\n    <b>Best time of day:</b> Morning — dew and light in the alder wood.',
 'why': ['The <b>goor</b> — wet poor land as name-giver.', 'The <b>damp counterpart</b> of the dry Maashorst forests.', 'The <b>alder and birch wood</b> of the seepage zone.', 'The <b>belt of Schaijk</b> as green north edge.', 'The <b>fungi</b> of the damp wood.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌷 <b>Wood anemone</b> on the transition zones.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the soft green.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi wave</b> of the damp wood.', '<span class="months">Dec–Feb</span> 💧 <b>Seepage and ditches</b> at their fullest.'],
 'wild': ['💧 Wet poor land (goor)', '🌳 Alder and birch wood', '🍄 Fungi', '🐦 Songbirds', '🥾 Soft paths'],
 'trail': ['Walk the <b>sand paths of the Goorbos</b> at Schaijk.', 'Combine with the <b>Maashorst belt</b> and Herperduin (card 2174).', 'Feel the <b>dry-wet transition</b> underfoot.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–6 km · 👢 Boots advised in winter'
}))

C.append(mk.card(2194, 'Boscomplex Odiliapeel', {
 'tags': ['Noord-Brabant · Odiliapeel (ten zuiden van het dorp, gemeente Maashorst)', 'gemengd ontginningsbos van 130 ha · bos van het turfstadje Terraveen (1922) met bunker en loopgraaf uit de Tweede Wereldoorlog en de vliegbasis Volkel als noorderbuur — met rolstoelvriendelijk Jeanny van Kuppeveltpad', 'list 81 · no. 27'],
 'loc': '📍 Boscomplex Odiliapeel, ten zuiden van het dorp Odiliapeel — parkeerplaatsen aan de randwegen; diverse wandelpaden, ruiter- en trimbaanroute; Jeanny van Kuppeveltpad (rolstoeltoegankelijk)',
 'desc': 'Ten zuiden van het dorp <b>Odiliapeel</b> — in de Brabantse volksmond <i>De Piejel</i>, gesticht in <b>1922</b> als ontginningsdorp <b>Terraveen</b> voor de turfstekers van de Peel — ligt het <b>Boscomplex Odiliapeel</b>: <b>130 hectare</b> gemengd ontginningsbos, eigendom van de gemeente. Wie door het bos loopt, wandelt door de geschiedenis van de Peelontginning: hier werd beuk en eik aangeplant tussen de den, hier liggen de oude rabatten van de eerste bosbouw, en hier staan nog de <b>overblijfselen van de Duitsers uit de Tweede Wereldoorlog</b> — een <b>bunker</b> en een <b>loopgraaf</b>, achtergelaten rond het vliegveld dat zij aanlegden en dat nu, direct ten noorden van het dorp, de <b>vliegbasis Volkel</b> is. Het bos is klein maar verrassend afwisselend door de krachtige natuurontwikkeling; beeldhouwer <b>André van Boxtel</b> maakte er kunstwerken van bomen, met de kettingzaag. Bijzonder is het <b>Jeanny van Kuppeveltpad</b>: een rolstoelwandelpad dat op burgerinitiatief werd aangelegd en dat iedereen — rolstoel, rollator, wandelwagen of kinderwagen — door het bos voert. Odiliapeel ligt te midden van Peelontginningen met intensieve veehouderij; dit bos is het groene hart van de Piejel.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels en ondergroei), sep–okt (paddenstoelen), winter (open bos met oorlogssporen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — het bos net wakker.',
 'why': ['Het <b>ontginningsbos van 130 ha</b> bij turfstadje Terraveen (1922).', 'De <b>bunker en loopgraaf</b> uit de Tweede Wereldoorlog.', 'De <b>vliegbasis Volkel</b> als historische noorderbuur.', 'Het <b>rolstoelvriendelijke Jeanny van Kuppeveltpad</b>.', 'De <b>kettingzaag-kunst</b> van André van Boxtel.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Ondergroei</b> in het gemengde bos.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogelkoor</b> in de Peelrand.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> op rabat en stobbe.', '<span class="months">Nov–feb</span> ❄️ <b>Oorlogssporen</b> zichtbaar in het kale bos.'],
 'wild': ['🌲 Gemengd ontginningsbos', '🧱 Bunker en loopgraaf', '✈️ Volkel-geschiedenis', '♿ Rolstoelpad', '🎨 Kettingzaag-kunst'],
 'trail': ['Wandel de <b>paden van het Boscomplex</b>, ook het <b>Jeanny van Kuppeveltpad</b>.', 'Zoek de <b>bunker en de loopgraaf</b> uit de oorlog.', 'Combineer met de <b>Peel-ontginningen</b> rondom het dorp.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 2–5 km · ♿ Rolstoeltoegankelijk pad aanwezig'
}, {
 'tags': ['North Brabant · Odiliapeel (south of the village, municipality of Maashorst)', '130-ha mixed reclamation wood · forest of the peat village Terraveen (1922) with a Second World War bunker and trench and Volkel air base as northern neighbour — with the wheelchair-friendly Jeanny van Kuppevelt path', 'list 81 · no. 27'],
 'loc': '📍 Boscomplex Odiliapeel, south of the village of Odiliapeel — car parks on the edge roads; various footpaths, a riding and trim course; Jeanny van Kuppevelt path (wheelchair accessible)',
 'desc': 'South of the village of <b>Odiliapeel</b> — <i>De Piejel</i> in Brabant dialect, founded in <b>1922</b> as the reclamation village of <b>Terraveen</b> for the Peel peat cutters — lies the <b>Odiliapeel Forest Complex</b>: <b>130 hectares</b> of mixed reclamation wood owned by the municipality. Walk through it and you walk through the history of the Peel reclamation: beech and oak were planted among the pines, the old rabatten of the first forestry lie here, and so do the <b>remains of the German presence of the Second World War</b> — a <b>bunker</b> and a <b>trench</b>, left behind around the airfield they built and which, immediately north of the village, is now <b>Volkel air base</b>. The wood is small but surprisingly varied thanks to vigorous nature development; sculptor <b>André van Boxtel</b> made artworks of trees here, with a chainsaw. Remarkable is the <b>Jeanny van Kuppevelt path</b>: a wheelchair walking path laid out on a citizens’ initiative that leads everyone — wheelchair, walker, pram or pushchair — through the wood. Odiliapeel sits amid Peel reclamations with intensive livestock farming; this wood is the green heart of the Piejel.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds and ground flora), Sep–Oct (fungi), winter (open wood with war traces)<br>\n    <b>Best time of day:</b> Morning — the wood just awake.',
 'why': ['The <b>130-ha reclamation wood</b> of peat village Terraveen (1922).', 'The <b>Second World War bunker and trench</b>.', '<b>Volkel air base</b> as historic northern neighbour.', 'The <b>wheelchair-friendly Jeanny van Kuppevelt path</b>.', 'The <b>chainsaw art</b> of André van Boxtel.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Ground flora</b> in the mixed wood.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbird chorus</b> at the Peel edge.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on rabat and stump.', '<span class="months">Nov–Feb</span> ❄️ <b>War traces</b> visible in the bare wood.'],
 'wild': ['🌲 Mixed reclamation wood', '🧱 Bunker and trench', '✈️ Volkel history', '♿ Wheelchair path', '🎨 Chainsaw art'],
 'trail': ['Walk the <b>paths of the Forest Complex</b>, including the <b>Jeanny van Kuppevelt path</b>.', 'Seek the <b>bunker and the trench</b> from the war.', 'Combine with the <b>Peel reclamations</b> around the village.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 2–5 km · ♿ Wheelchair-accessible path available'
}))

C.append(mk.card(2195, 'Voskuilenheuvel', {
 'tags': ['Noord-Brabant · 1 km ten noordwesten van Venhorst (Horst aan de Maas)', 'natuurgebied van 18 ha met schaapskooi · in 2012 met 6 ha uitgebreid en verlicht — minder bomen, meer heide: de kudde van Venhorst als het vaste punt van het gebied', 'list 81 · no. 28'],
 'loc': '📍 Voskuilenheuvel, ± 1 km ten noordwesten van Venhorst — wandelingen vanuit de Voskuilen-ingang; de schaapskooi is het herkenningspunt; combineer met de Peelbreuk- en Venhorster routes',
 'desc': 'Een kilometer ten noordwesten van <b>Venhorst</b> ligt de <b>Voskuilenheuvel</b>: een natuurgebied van <b>18 hectare</b> dat rond zijn <b>schaapskooi</b> is gebouwd — het vaste punt waar de kudde van Venhorst thuiskomt en van waaruit de schaapherder het gebied begraast. In <b>2012</b> werd het gebied met <b>6 hectare</b> uitgebreid, en de kern van het beheer was toen precies wat de naam al deed vermoeden: <b>er kwamen fors minder bomen</b>. Waar het productiebos de boventoon voerde, werd geopend naar heide en schraal grasland — het oude Peel- en Maashorstlandschap dat hier eeuwenlang lag voordat de dennen kwamen. Vandaag wisselen denneranden, heideveldjes en poelen elkaar af; de schapen houden de heide jong, en in de zomer zoemen de sprinkhanen en vlinders van de open plekken. Het is een klein gebied, maar juist daardoor overzichtelijk: wie bij de kooi parkeert, wandelt in een uur om het geheel — en ziet in het klein hetzelfde verhaal als in de grote Maashorstgebieden (kaart 2174): de heide keert terug waar het bos wijkt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide en sprinkhanen), apr–jun (vogels), okt (herfstlicht rond de kooi)<br>\n    <b>Beste tijd van de dag:</b> Middag — warmte op de heide; schemering — de kudde komt thuis.',
 'why': ['De <b>schaapskooi</b> als kloppend hart van het gebied.', 'De <b>uitbreiding van 2012</b> met 6 ha en minder bomen.', 'De <b>terugkeer van heide</b> waar productiebos stond.', 'De <b>overzichtelijke schaal</b> van 18 ha natuur.', 'De <b>verbinding</b> met de Peel- en Maashorst-dynamiek.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Veldleeuwerik en tapuit</b> op de open delen.', '<span class="months">Jun–aug</span> 🦗 <b>Sprinkhanen</b> in de warme heide.', '<span class="months">Aug–sep</span> 🌸 <b>Heidebloei</b> rond de kooi.', '<span class="months">Okt–nov</span> 🍂 <b>Herfstlicht</b> over heide en dennerand.'],
 'wild': ['🐑 Schaapskooi en kudde', '🌸 Heide en schraal gras', '🦗 Sprinkhanen', '🐦 Veldleeuwerik', '🌳 Denneranden'],
 'trail': ['Start bij de <b>Voskuilen-ingang</b> en de schaapskooi.', 'Wandel de <b>rondes over heuvel en heide</b> (± 1–2 uur).', 'Combineer met de <b>Venhorster Peelroutes</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–5 km · ⚠️ Kudde en schapen op afstand'
}, {
 'tags': ['North Brabant · 1 km northwest of Venhorst (Horst aan de Maas)', '18-ha nature reserve with sheepfold · expanded by 6 ha in 2012 and thinned — fewer trees, more heath: the Venhorst flock as the area’s fixed point', 'list 81 · no. 28'],
 'loc': '📍 Voskuilenheuvel, ± 1 km northwest of Venhorst — walks from the Voskuilen entrance; the sheepfold is the landmark; combine with the Peel-edge and Venhorst routes',
 'desc': 'A kilometre northwest of <b>Venhorst</b> lies the <b>Voskuilenheuvel</b>: an 18-hectare nature reserve built around its <b>sheepfold</b> — the fixed point where the Venhorst flock comes home and from which the shepherd grazes the area. In <b>2012</b> the reserve was expanded by <b>6 hectares</b>, and the heart of the management was exactly what the name already suggested: <b>far fewer trees</b>. Where production forest dominated, the area was opened towards heath and poor grassland — the old Peel and Maashorst landscape that lay here for centuries before the pines arrived. Today pine edges, heath fields and pools alternate; the sheep keep the heath young, and in summer the grasshoppers and butterflies of the open parts hum and flutter. It is a small area, but precisely therefore manageable: park at the fold and you walk around the whole in an hour — seeing in miniature the same story as in the great Maashorst reserves (card 2174): the heath returns where the wood gives way.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heath and grasshoppers), Apr–Jun (birds), Oct (autumn light at the fold)<br>\n    <b>Best time of day:</b> Midday — warmth on the heath; dusk — the flock comes home.',
 'why': ['The <b>sheepfold</b> as the beating heart of the area.', 'The <b>2012 expansion</b> by 6 ha with fewer trees.', 'The <b>return of heath</b> where production forest stood.', 'The <b>manageable scale</b> of 18 ha of nature.', 'The <b>connection</b> with the Peel and Maashorst dynamic.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Sky lark and stonechat</b> on the open parts.', '<span class="months">Jun–Aug</span> 🦗 <b>Grasshoppers</b> in the warm heath.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath bloom</b> around the fold.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn light</b> over heath and pine edge.'],
 'wild': ['🐑 Sheepfold and flock', '🌸 Heath and poor grass', '🦗 Grasshoppers', '🐦 Sky lark', '🌳 Pine edges'],
 'trail': ['Start at the <b>Voskuilen entrance</b> and the sheepfold.', 'Walk the <b>loops over hill and heath</b> (± 1–2 hours).', 'Combine with the <b>Venhorst Peel routes</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–5 km · ⚠️ Keep distance from flock and sheep'
}))

C.append(mk.card(2196, 'Sint Anthonisbos', {
 'tags': ['Noord-Brabant · Sint Anthonis/Wanroij/Westerbeek (staatsbossen)', '± 830 ha staatsbos met de Ullingse Bergen · eerste natuurreservaat van de Peel (1930: het Peelven), jeneverbessen op de heide, Peel-Raamstelling-kazematten en het Boswachterspad van 14,5 km', 'list 81 · no. 30'],
 'loc': '📍 Staatsbossen van Sint Anthonis ("Sint Tunnis") — natuurpoort De Heksenboom; vier SBB-wandelroutes (2–26 km, onderling verbonden) en het Boswachterspad (14,5 km); schaapskooi bij de Ullingse Bergen',
 'desc': 'De <b>staatsbossen van Sint Anthonis</b> — in de streek liefkozend <b>"Sint Tunnis"</b> — omvatten ± <b>830 hectare</b> bos, heide en zandverstuiving, samen met Vierlingsbeek, Oploo, Wanroij en Mill onderdeel van de <b>bosgordel van 3.000 hectare</b> (kaart 2182). Centraal liggen de <b>Ullingse Bergen</b>: een groot, open heideterrein waar de natuur voorop staat en waar de <b>jeneverbes</b> staat — de karakteristieke naaldboom van de woeste gronden die in Nederland zeldzaam is geworden. Hier lag in <b>1930</b> het <b>eerste natuurreservaat van de Peel</b>: het <b>Peelven</b> met heide, aangelegd in de jaren twintig nadat Natuurmonumenten in 1919 was gevraagd een stuk Peel te redden voor de <b>goudplevier</b>. In het bos liggen de <b>veenplassen</b> en de natte graslanden van de <b>Visdel en het Berkenbos</b> (± 30 ha, in 1983 aangekocht); door het gebied lopen resten van de <b>Peel-Raamstelling</b> — het <b>Defensiekanaal</b> met oude <b>kazematten</b> uit de meidagen van 1940. Staatsbosbeheer heeft vier wandelroutes uitgezet die alle onderling verbonden zijn — van 2 tot 26 km — plus het <b>Boswachterspad</b> van 14,5 km dat alles bijeenbrengt; de <b>schaapskooi</b> houdt de heide kort. Startpunt bij uitstek: natuurpoort <b>De Heksenboom</b>.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide en jeneverbes-bessen), apr–jun (vogels), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — mist over de Ullingse Bergen.',
 'why': ['De <b>Ullingse Bergen</b> als open heidehart met jeneverbessen.', 'Het <b>eerste natuurreservaat van de Peel (1930)</b>: het Peelven.', 'De <b>Peel-Raamstelling</b>: Defensiekanaal en kazematten.', 'De <b>vier verbonden SBB-routes</b> en het Boswachterspad.', 'Natuurpoort <b>De Heksenboom</b> als startpunt.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Heidevogels</b> boven de Bergen.', '<span class="months">Aug–sep</span> 🌸 <b>Paarse heide</b> en jeneverbes-bessen.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in de bosgordel.', '<span class="months">Nov–feb</span> ❄️ <b>Kazematten en kanaal</b> in winterlicht.'],
 'wild': ['🌸 Ullingse Bergen', '🌲 Jeneverbes', '💧 Peelven en veenplassen', '🧱 Peel-Raamstelling-kazematten', '🐑 Schaapskooi'],
 'trail': ['Loop het <b>Boswachterspad (14,5 km)</b> of een kortere variant.', 'Start bij natuurpoort <b>De Heksenboom</b>.', 'Zoek de <b>kazematten langs het Defensiekanaal</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes 2–26 km · 🅿️ Natuurpoort De Heksenboom (horeca)'
}, {
 'tags': ['North Brabant · Sint Anthonis/Wanroij/Westerbeek (state forests)', '± 830 ha of state forest with the Ullingse Bergen · the Peel’s first nature reserve (1930: the Peelven), junipers on the heath, Peel-Raamstelling pillboxes and the 14.5-km Boswachterspad', 'list 81 · no. 30'],
 'loc': '📍 State forests of Sint Anthonis ("Sint Tunnis") — nature gate De Heksenboom; four SBB walking routes (2–26 km, interconnected) and the Boswachterspad (14.5 km); sheepfold at the Ullingse Bergen',
 'desc': 'The <b>state forests of Sint Anthonis</b> — affectionately <b>"Sint Tunnis"</b> in the region — cover ± <b>830 hectares</b> of forest, heath and drifting sand, part with Vierlingsbeek, Oploo, Wanroij and Mill of the <b>3,000-hectare woodland belt</b> (card 2182). At their centre lie the <b>Ullingse Bergen</b>: a great open heath where nature comes first and where the <b>juniper</b> stands — the characteristic conifer of the wastelands that has become rare in the Netherlands. Here, in <b>1930</b>, lay the <b>first nature reserve of the Peel</b>: the <b>Peelven</b> with its heath, laid out in the 1920s after Natuurmonumenten was asked in 1919 to save a piece of Peel for the <b>golden plover</b>. In the forest lie the <b>peat lakes</b> and the wet grasslands of the <b>Visdel and the Berkenbos</b> (± 30 ha, bought in 1983); through the area run remains of the <b>Peel-Raamstelling</b> — the <b>Defence Canal</b> with old <b>pillboxes</b> from the May days of 1940. Staatsbosbeheer has set out four walking routes, all interconnected — from 2 to 26 km — plus the <b>Boswachterspad</b> of 14.5 km that ties it all together; the <b>sheepfold</b> keeps the heath short. Best starting point: nature gate <b>De Heksenboom</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heath and juniper berries), Apr–Jun (birds), Sep–Oct (fungi and migration)<br>\n    <b>Best time of day:</b> Morning — mist over the Ullingse Bergen.',
 'why': ['The <b>Ullingse Bergen</b> as open heath heart with junipers.', 'The <b>Peel’s first nature reserve (1930)</b>: the Peelven.', 'The <b>Peel-Raamstelling</b>: Defence Canal and pillboxes.', 'The <b>four linked SBB routes</b> and the Boswachterspad.', 'Nature gate <b>De Heksenboom</b> as starting point.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Heath birds</b> above the Bergen.', '<span class="months">Aug–Sep</span> 🌸 <b>Purple heath</b> and juniper berries.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the woodland belt.', '<span class="months">Nov–Feb</span> ❄️ <b>Pillboxes and canal</b> in winter light.'],
 'wild': ['🌸 Ullingse Bergen', '🌲 Juniper', '💧 Peelven and peat lakes', '🧱 Peel-Raamstelling pillboxes', '🐑 Sheepfold'],
 'trail': ['Walk the <b>Boswachterspad (14.5 km)</b> or a shorter variant.', 'Start at nature gate <b>De Heksenboom</b>.', 'Seek the <b>pillboxes along the Defence Canal</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 2–26 km · 🅿️ Nature gate De Heksenboom (catering)'
}))

C.append(mk.card(2197, 'Brestbosch en Sassekamp', {
 'tags': ['Noord-Brabant · Rijkevoort/De Rips (Land van Cuijk, Peel en Maas)', 'hakhout, rabatten en het parkachtige Brestbosch van Brabants Landschap · genoemd naar jonkheer Sasse van Ysselt — bosgordelrestant tussen Vortum-Mullem en Ossenbroek, verbonden door de Lage Raam', 'list 81 · no. 31'],
 'loc': '📍 Brestbosch (ten zuiden van De Rips) en het Sassekamp (ten zuiden van Rijkevoort) — Kikkerpad-routes bij Rijkevoort; de Oeffeltse Raam verbindt met De Vilt en de Oeffelter Meent (kaart 2191)',
 'desc': 'Twee namen uit de oude bosgordel van het Land van Cuijk. Het <b>Sassekamp</b> ten zuiden van <b>Rijkevoort</b> dankt zijn naam aan <b>jonkheer Sasse van Ysselt</b>, wonende te Boxmeer, in wiens bezit dit stukje overgebleven bos ooit was: eeuwenoude <b>hakhoutbossen</b> op <b>rabatten</b> — hier het plaatselijke woord voor een houtwal, begrensd door een of twee sloten — beplant met gemengd loofhout waarvan het grootste deel <b>zomereik</b> was. Het bos bestaat uit droog berken-eikenbos, elzenbroek en eiken-haagbeukenbos; in de kruidlaag groeit de <b>grote keverorchis</b>. Het <b>Brestbosch</b> bij De Rips is het grotere, <b>parkachtige</b> broertje van Brabants Landschap — bos afgewisseld met landbouwgronden en <b>hooilanden begrensd door houtwallen</b>, samen met Schraalzand en het Luneven een restant van de eertijdse gordel tussen <b>Vortum-Mullem en landgoed Ossenbroek</b>, gedraineerd door Snelle Loop en Esperloop. De provincie wees de <b>Lage Raam</b> aan als <b>ecologische verbindingszone</b>: houtwallen en poelen die Sassekamp, Brestbosch, Ullingse Bergen, Molenheide en landgoed Tongelaar (kaart 2183) tot één dal verbinden — de <b>Kikkerpad</b>-wandeling bij Rijkevoort volgt die as. Wie hier loopt, ziet het Peelrand-Brabant van vóór de ontginningen: klein, houtig en vol namen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jun</b> (keverorchis en hooilanden), sep–okt (paddenstoelen op rabat en eik), winter (hakhoutsilhouetten)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door het loofhout.',
 'why': ['Het <b>Sassekamp van jonkheer Sasse van Ysselt</b> op zijn rabatten.', 'De <b>grote keverorchis</b> in de kruidlaag.', 'Het <b>parkachtige Brestbosch</b> met hooilanden en houtwallen.', 'De <b>Lage Raam</b> als ecologische verbindingszone.', 'De <b>Kikkerpad-wandeling</b> als gastheer van het geheel.'],
 'phen': ['<span class="months">Mei–jun</span> 🌸 <b>Keverorchis</b> in bos en zoom.', '<span class="months">Jun–jul</span> 🌾 <b>Hooilanden</b> in volle groei.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> op rabat en eik.', '<span class="months">Dec–feb</span> ❄️ <b>Hakhoutsilhouet</b> van eik en haagbeuk.'],
 'wild': ['🌳 Hakhout en rabatten', '🌸 Grote keverorchis', '🌾 Hooilanden en houtwallen', '💧 Lage Raam-verbinding', '🦡 Das-migratie-as'],
 'trail': ['Loop het <b>Kikkerpad</b> bij Rijkevoort door het Sassekamp.', 'Wandel de <b>percelen van het Brestbosch</b> bij De Rips.', 'Volg de <b>Oeffeltse Raam</b> naar De Vilt en de Meent (kaart 2191).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 4–8 km · ⚠️ Rabatbossen plaatselijk nat'
}, {
 'tags': ['North Brabant · Rijkevoort/De Rips (Land van Cuijk, Peel and Meuse)', 'coppice wood, rabatten and the park-like Brestbosch of the Brabant Landscape Trust · named for jonkheer Sasse van Ysselt — remnant of the forest belt between Vortum-Mullem and Ossenbroek, joined by the Lage Raam', 'list 81 · no. 31'],
 'loc': '📍 Brestbosch (south of De Rips) and the Sassekamp (south of Rijkevoort) — Kikkerpad routes at Rijkevoort; the Oeffeltse Raam connects to De Vilt and the Oeffelter Meent (card 2191)',
 'desc': 'Two names from the old forest belt of the Land van Cuijk. The <b>Sassekamp</b> south of <b>Rijkevoort</b> owes its name to <b>jonkheer Sasse van Ysselt</b>, resident of Boxmeer, in whose possession this surviving patch of woodland once lay: centuries-old <b>coppice woods</b> on <b>rabatten</b> — here the local word for a wood bank bounded by one or two ditches — planted with mixed hardwoods, the greater part <b>pedunculate oak</b>. The wood holds dry birch-oak forest, alder carr and oak-hornbeam forest; in the herb layer grows the <b>large helleborine</b>. The <b>Brestbosch</b> near De Rips is its larger, <b>park-like</b> sibling of the Brabant Landscape Trust — woodland alternating with farmland and <b>hay meadows bounded by wood banks</b>, with Schraalzand and the Luneven a remnant of the former belt between <b>Vortum-Mullem and the Ossenbroek estate</b>, drained by Snelle Loop and Esperloop. The province designated the <b>Lage Raam</b> an <b>ecological corridor</b>: wood banks and pools joining Sassekamp, Brestbosch, the Ullingse Bergen, Molenheide and Tongelaar estate (card 2183) into one valley — the <b>Kikkerpad</b> walk at Rijkevoort follows that axis. Walk here and you see the Peel-edge Brabant of before the reclamations: small, woody and full of names.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (helleborine and hay meadows), Sep–Oct (fungi on rabat and oak), winter (coppice silhouettes)<br>\n    <b>Best time of day:</b> Morning — light through the hardwoods.',
 'why': ['The <b>Sassekamp of jonkheer Sasse van Ysselt</b> on its rabatten.', 'The <b>large helleborine</b> in the herb layer.', 'The <b>park-like Brestbosch</b> with hay meadows and wood banks.', 'The <b>Lage Raam</b> as ecological corridor.', 'The <b>Kikkerpad walk</b> as host of the whole.'],
 'phen': ['<span class="months">May–Jun</span> 🌸 <b>Helleborine</b> in wood and fringe.', '<span class="months">Jun–Jul</span> 🌾 <b>Hay meadows</b> in full growth.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on rabat and oak.', '<span class="months">Dec–Feb</span> ❄️ <b>Coppice silhouette</b> of oak and hornbeam.'],
 'wild': ['🌳 Coppice and rabatten', '🌸 Large helleborine', '🌾 Hay meadows and wood banks', '💧 Lage Raam corridor', '🦡 Badger migration axis'],
 'trail': ['Walk the <b>Kikkerpad</b> at Rijkevoort through the Sassekamp.', 'Walk the <b>Brestbosch parcels</b> near De Rips.', 'Follow the <b>Oeffeltse Raam</b> to De Vilt and the Meent (card 2191).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 4–8 km · ⚠️ Rabat woods locally wet'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2197)
mk.check()
