# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2198, 'Veghel en Erp', {
 'tags': ['Noord-Brabant · Veghel en Erp (Meierijstad, dal van de Aa)', 'natuur rond Veghel en Erp: “plukken groen” en de Aa · coulissen van bomenrijen, houtsingels en erfbeplantingen, met het beekdal van de Aa als groene verbindingsader tussen de dorpen', 'list 81 · no. 32'],
 'loc': '📍 Groen rond Veghel en Erp (Meierijstad) — de Aa doorkruist beide dorpen met natuurvriendelijke oevers; fietsknooppuntennetwerk en kleine wandelrondes; combineer met De Coevering/Logtenburg (kaart 2173)',
 'desc': 'De natuur van <b>Veghel en Erp</b> is niet één gebied maar een weefsel: “plukken groen” die overal aanwezig zijn en het landschap in kleine stukjes verdelen — <b>bomenrijen, houtsingels, bosjes en erfbeplantingen</b> die samen de coulissen van de Meierij vormen. De belangrijke groene ader is de <b>Aa</b>: het riviertje dat Veghel en Erp doorkruist en langs zijn natuurvriendelijke oevers de verbinding legt. Via het beekdal kunnen <b>dieren en planten migreren tussen de versnipperde groenstroken</b> — de Aa is de ruggengraat waaraan de plukken groen hangen. Voor de wandelaar betekent dat een landschap van korte wisselingen: vanaf de beek door een houtsingel, over een es, langs een erf met oude eiken — en altijd het gevoel van het kleinschalige dat de Meierij haar naam gaf. Deze kaart is de kapstok voor wie de losse stukjes wil snappen: de Coevering en Logtenburg (kaart 2173) aan de ene kant, het Leijnt bij Zijtaart (kaart 2199) aan de andere, en de Aa als draad door het geheel.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels in de singels), jul–aug (de Aa op zijn zachtst), okt (herfstlicht over es en erf)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — mist boven het beekdal.',
 'why': ['De <b>“plukken groen”</b> als karakter van de Meierij.', 'De <b>Aa</b> als groene verbindingsader tussen de dorpen.', 'De <b>natuurvriendelijke oevers</b> van het riviertje.', 'De <b>migratie-as</b> voor dieren en planten.', 'De <b>kapstok-functie</b> voor de losse gebiedjes.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌸 <b>Stinzen- en erfplanten</b> bij boerderijen.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in singels en hagen.', '<span class="months">Jun–aug</span> 🦋 <b>Vlinders</b> langs de beekoevers.', '<span class="months">Sep–okt</span> 🍂 <b>Oogstlicht</b> over es en coulissen.'],
 'wild': ['💧 Dal van de Aa', '🌳 Houtsingels en bomenrijen', '🏡 Erfbeplantingen', '🐦 Zangvogels', '🧵 Weefsel van plukken groen'],
 'trail': ['Volg de <b>Aa</b> door Veghel en Erp langs de oevers.', 'Fiets het <b>knooppuntennetwerk</b> van groen naar groen.', 'Combineer met kaart <b>2173</b> (Coevering/Logtenburg) en <b>2199</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Korte rondes en netwerkroutes · ⚠️ Agrarisch verkeer'
}, {
 'tags': ['North Brabant · Veghel and Erp (Meierijstad, valley of the Aa)', 'nature around Veghel and Erp: “patches of green” and the Aa · coulisses of tree rows, belts and farm planting, with the Aa stream valley as green connecting artery between the villages', 'list 81 · no. 32'],
 'loc': '📍 Green around Veghel and Erp (Meierijstad) — the Aa crosses both villages with nature-friendly banks; cycle junction network and short walking loops; combine with De Coevering/Logtenburg (card 2173)',
 'desc': 'The nature of <b>Veghel and Erp</b> is not one area but a weave: “patches of green” present everywhere, dividing the landscape into small pieces — <b>tree rows, belts, copses and farmyard planting</b> that together form the coulisses of the Meierij. The great green artery is the <b>Aa</b>: the stream that crosses Veghel and Erp and lays the connection along its nature-friendly banks. Via the stream valley <b>animals and plants can migrate between the fragmented green strips</b> — the Aa is the backbone from which the patches hang. For the walker that means a landscape of short changes: from the stream through a belt, across an old field, past a farm with ancient oaks — and always the small-scale feeling that gave the Meierij its name. This card is the peg for understanding the loose pieces: De Coevering and Logtenburg (card 2173) on one side, Het Leijnt at Zijtaart (card 2199) on the other, and the Aa as thread through the whole.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds in the belts), Jul–Aug (the Aa at its gentlest), Oct (autumn light over field and farm)<br>\n    <b>Best time of day:</b> Morning — mist over the stream valley.',
 'why': ['The <b>“patches of green”</b> as the Meierij’s character.', 'The <b>Aa</b> as green artery between the villages.', 'The <b>nature-friendly banks</b> of the stream.', 'The <b>migration axis</b> for animals and plants.', 'The <b>peg function</b> for the separate little areas.'],
 'phen': ['<span class="months">Mar–May</span> 🌸 <b>Yard and garden plants</b> at the farms.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in belts and hedges.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> along the banks.', '<span class="months">Sep–Oct</span> 🍂 <b>Harvest light</b> over fields and coulisses.'],
 'wild': ['💧 Valley of the Aa', '🌳 Belts and tree rows', '🏡 Farmyard planting', '🐦 Songbirds', '🧵 Weave of green patches'],
 'trail': ['Follow the <b>Aa</b> through Veghel and Erp along the banks.', 'Cycle the <b>junction network</b> from green to green.', 'Combine with card <b>2173</b> (Coevering/Logtenburg) and <b>2199</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Short loops and network routes · ⚠️ Agricultural traffic'
}))

C.append(mk.card(2199, 'Het Leijnt', {
 'tags': ['Noord-Brabant · ten zuidoosten van Zijtaart (Meierijstad)', 'voormalig heidegebied, deels bos en deels landbouw · de ± 4 ha grote natuurlijke bosrand van 20–25 meter breed als schoolvoorbeeld van zachte overgang tussen bos en akker', 'list 81 · no. 33'],
 'loc': '📍 Het Leijnt (ook: Het Lijnt), ten zuidoosten van Zijtaart — landwegen rond het gebied; combineer met de Aa-rondes van Veghel en Erp (kaart 2198)',
 'desc': 'Ten zuidoosten van <b>Zijtaart</b> ligt <b>Het Leijnt</b>: een voormalig <b>heidegebied</b> dat vandaag deels uit bos en deels uit landbouwgrond bestaat — en juist daardoor iets te vertellen heeft wat grotere gebieden vergeten zijn. De scherpe, natuurarme bosrand die hier decennialang het bos van de akker scheidde, is in de laatste jaren door de gemeente omgevormd tot een <b>natuurlijke bosrandzone</b>: over een breedte van <b>20 tot 25 meter</b> gaat het bos geleidelijk over in het naastgelegen agrarische gebied, met struweel, ruigte en houtige randen. Die nu ± <b>4 hectare</b> grote zachte overgang moet <b>nest- en voedselgelegenheid</b> bieden aan vogels, vlinders en kleine zoogdieren — de strook waar het leven zich verzamelt dat in het productiebos en op de akker allebei geen plek vond. Het Leijnt is daarmee een schoolvoorbeeld van moderne natuurinrichting: niet meer bos, maar beter bos — en een rand die de moeite van het omweggetje waard is. Wie hier in het vroege voorjaar langs de rand loopt, hoort het verschil: waar de bosrand hard was, zingt hij nu.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (randvol zangvogels), jun–aug (vlinders in de ruigte), winter (struweel als winterverblijf)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — de rand zingt het hardst.',
 'why': ['De <b>natuurlijke bosrandzone</b> van 20–25 meter breed.', 'De zachte overgang <b>bos–akker</b> als modern idee.', 'De <b>nest- en voedselstrook</b> voor vogels en vlinders.', 'Het <b>voormalig heidegebied</b> als historische laag.', 'Het <b>schoolvoorbeeld</b> voor kleine natuurgebieden.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in de zachte rand.', '<span class="months">Jun–aug</span> 🦋 <b>Vlinders</b> in struweel en ruigte.', '<span class="months">Sep–okt</span> 🍂 <b>Bessen en trek</b> langs de overgang.', '<span class="months">Dec–feb</span> ❄️ <b>Winterverblijf</b> in het houtige randje.'],
 'wild': ['🌳 Zachte bosrand', '🌸 Ruigte en struweel', '🐦 Randvogels', '🦋 Vlinders', '📖 Schoolvoorbeeld-inrichting'],
 'trail': ['Wandel de <b>landwegen rond Het Leijnt</b> bij Zijtaart.', 'Bekijk de <b>bosrandzone</b> en zijn bewoners.', 'Combineer met de <b>Aa-rondes</b> (kaart 2198).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Korte rondes ± 2–4 km · ⚠️ Randzones niet betreden'
}, {
 'tags': ['North Brabant · southeast of Zijtaart (Meierijstad)', 'former heathland, partly wood and partly farmland · the ± 4 ha natural wood edge of 20–25 metres wide as a textbook example of a soft transition between forest and field', 'list 81 · no. 33'],
 'loc': '📍 Het Leijnt (also: Het Lijnt), southeast of Zijtaart — lanes around the area; combine with the Aa loops of Veghel and Erp (card 2198)',
 'desc': 'Southeast of <b>Zijtaart</b> lies <b>Het Leijnt</b>: a former <b>heathland</b> that today consists partly of wood and partly of farmland — and precisely therefore has something to say that larger areas have forgotten. The sharp, nature-poor wood edge that separated wood from field here for decades has in recent years been transformed by the municipality into a <b>natural wood-edge zone</b>: over a width of <b>20 to 25 metres</b> the wood gradually passes into the adjoining agricultural land, with scrub, rough growth and woody fringes. That now ± <b>4-hectare</b> soft transition is meant to offer <b>nesting and feeding opportunities</b> to birds, butterflies and small mammals — the strip where life gathers that found no place either in the production forest or on the field. Het Leijnt is thus a textbook example of modern nature design: not more wood, but better wood — and an edge worth the small detour. Walk along it in early spring and you hear the difference: where the edge was hard, it now sings.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (edge full of songbirds), Jun–Aug (butterflies in the rough), winter (scrub as winter shelter)<br>\n    <b>Best time of day:</b> Early morning — the edge sings loudest.',
 'why': ['The <b>natural wood-edge zone</b> of 20–25 metres wide.', 'The soft transition <b>wood–field</b> as a modern idea.', 'The <b>nesting and feeding strip</b> for birds and butterflies.', 'The <b>former heathland</b> as historical layer.', 'The <b>textbook example</b> for small nature areas.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the soft edge.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> in scrub and rough.', '<span class="months">Sep–Oct</span> 🍂 <b>Berries and migration</b> along the transition.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter shelter</b> in the woody fringe.'],
 'wild': ['🌳 Soft wood edge', '🌸 Rough and scrub', '🐦 Edge birds', '🦋 Butterflies', '📖 Textbook design example'],
 'trail': ['Walk the <b>lanes around Het Leijnt</b> at Zijtaart.', 'Study the <b>wood-edge zone</b> and its inhabitants.', 'Combine with the <b>Aa loops</b> (card 2198).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Short loops ± 2–4 km · ⚠️ Do not enter the edge zones'
}))

C.append(mk.card(2200, 'Gemeentebossen Lieshout', {
 'tags': ['Noord-Brabant · ten noorden van Mariahout (gemeente Laarbeek)', 'de Mariahoutse/Lieshoutse Bossen: 158 ha jong heideontginningsbos · grove den en beuk op de 10.000 jaar oude Midden-Brabantse dekzandrug, met het Torreven en het in 2019 herstelde Vossenbergven', 'list 81 · no. 34'],
 'loc': '📍 Mariahoutse Bossen (ook Lieshoutse Bossen of -heide), direct ten noorden van Mariahout — wandelroutes (o.a. Lieshoutse Bossen-tocht 12 km); buur: Ruweeuwsels en waterwingebied Lieshout; beheer gemeente Laarbeek',
 'desc': 'Direct ten noorden van <b>Mariahout</b> ligt een langgerekt bosgebied van <b>158 hectare</b> dat drie namen draagt: <b>Mariahoutse Bossen</b>, <b>Lieshoutse Bossen</b> of <b>Lieshoutse Heide</b> — de laatste naam verraadt de oorsprong. Het is een <b>jong heideontginningsbos</b>, vooral aangeplant met <b>grove den</b> met hier en daar beuk, eigendom van de <b>gemeente Laarbeek</b>, gelegen op de <b>Midden-Brabantse dekzandrug</b> die 10.000 jaar geleden na de ijstijd door opwaaiend zand ontstond — een droog ruggetje in wat toen een moerassige, vennenrijke omgeving was. Van de veel grotere Lieshoutse Heide is de rest tot landbouwgebied ontgonnen; wat bleef is dit smalle bos met zijn vennen: het <b>Torreven</b> (ook Torren- of Torenven) en sinds <b>2019</b> het <b>herstelde Vossenbergven</b> — twee ogen van oud Peelrand-water in de dennerij. In het zuidwesten grenst het <b>waterwingebied Lieshout</b>; verderop liggen de <b>Ruweeuwsels</b>, het in 1760 ingerichte “eeuwsel”-hout (laag, moerassig struweelland) op de zuidwestgrens van het goed van Lieshout. De <b>Lieshoutse Bossen-tocht</b> van 12 km haalt alles aan; voor de stad Mariahout is dit de eigenlijke achtertuin.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (vennen en zangvogels), jul–aug (libellen op Torreveen), sep–okt (paddenstoelen onder de den)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegelend Torreven.',
 'why': ['Het <b>jonge heideontginningsbos</b> van 158 ha op de dekzandrug.', 'De <b>dekzandrug van 10.000 jaar</b> oud als ondergrond.', 'Het <b>Torreven</b> en het <b>herstelde Vossenbergven (2019)</b>.', 'De <b>Lieshoutse Heide</b> als verdwenen moedergebied.', 'De <b>Ruweeuwsels</b> van 1760 als bijzondere buur.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Voorjaar</b> in den en beuk.', '<span class="months">Jun–aug</span> 🪰 <b>Libellen</b> op Torre- en Vossenbergven.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> onder de grove den.', '<span class="months">Nov–feb</span> ❄️ <b>Winterrust</b> op de smalle rug.'],
 'wild': ['🌲 Grove den en beuk', '💧 Torreven en Vossenbergven', '🏔️ Dekzandrug', '💧 Waterwingebied', '🌳 Ruweeuwsels-buur'],
 'trail': ['Loop de <b>Lieshoutse Bossen-tocht (12 km)</b>.', 'Zoek het <b>Torreven</b> en het herstelde <b>Vossenbergven</b>.', 'Combineer met de <b>Ruweeuwsels</b> en Molenheide.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Tocht 12 km (inkortbaar) · 🅿️ Parkeren aan de bosrand Mariahout'
}, {
 'tags': ['North Brabant · north of Mariahout (municipality of Laarbeek)', 'the Mariahoutse/Lieshoutse Bossen: 158 ha of young heath-reclamation wood · Scots pine and beech on the 10,000-year-old Mid-Brabant cover-sand ridge, with the Torreven and the Vossenbergven restored in 2019', 'list 81 · no. 34'],
 'loc': '📍 Mariahoutse Bossen (also Lieshoutse Bossen or -heide), immediately north of Mariahout — walking routes (a.o. Lieshoutse Bossen-tocht 12 km); neighbours: Ruweeuwsels and the Lieshout water catchment; managed by the municipality of Laarbeek',
 'desc': 'Immediately north of <b>Mariahout</b> lies an elongated woodland of <b>158 hectares</b> carrying three names: <b>Mariahoutse Bossen</b>, <b>Lieshoutse Bossen</b> or <b>Lieshoutse Heide</b> — the last betraying the origin. It is a <b>young heath-reclamation wood</b>, planted mostly with <b>Scots pine</b> and some beech, owned by the <b>municipality of Laarbeek</b>, lying on the <b>Mid-Brabant cover-sand ridge</b> that arose 10,000 years ago after the ice age from blowing sand — a dry little ridge in what was then a marshy, fen-rich surroundings. Of the much larger Lieshoutse Heide the rest was reclaimed as farmland; what remained is this narrow wood with its fens: the <b>Torreven</b> (also Torren- or Torenven) and since <b>2019</b> the <b>restored Vossenbergven</b> — two eyes of old Peel-edge water in the pinery. To the southwest borders the <b>Lieshout water catchment</b>; further on lie the <b>Ruweeuwsels</b>, the “eeuwsel” wood (low, marshy scrubland) laid out in 1760 on the southwest border of the Lieshout estate. The 12-km <b>Lieshoutse Bossen-tocht</b> takes in everything; for Mariahout this is the real back garden.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (fens and songbirds), Jul–Aug (dragonflies on the Torreven), Sep–Oct (fungi under the pine)<br>\n    <b>Best time of day:</b> Morning — the Torreven mirroring.',
 'why': ['The <b>young heath-reclamation wood</b> of 158 ha on the cover-sand ridge.', 'The <b>10,000-year-old cover-sand ridge</b> as subsoil.', 'The <b>Torreven</b> and the <b>restored Vossenbergven (2019)</b>.', 'The <b>Lieshoutse Heide</b> as vanished mother area.', 'The <b>Ruweeuwsels</b> of 1760 as special neighbour.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring</b> in pine and beech.', '<span class="months">Jun–Aug</span> 🪰 <b>Dragonflies</b> on Torre- and Vossenbergven.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> under the Scots pine.', '<span class="months">Nov–Feb</span> ❄️ <b>Winter rest</b> on the narrow ridge.'],
 'wild': ['🌲 Scots pine and beech', '💧 Torreven and Vossenbergven', '🏔️ Cover-sand ridge', '💧 Water catchment', '🌳 Ruweeuwsels neighbour'],
 'trail': ['Walk the <b>Lieshoutse Bossen-tocht (12 km)</b>.', 'Seek the <b>Torreven</b> and the restored <b>Vossenbergven</b>.', 'Combine with the <b>Ruweeuwsels</b> and Molenheide.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Route 12 km (shortenable) · 🅿️ Parking at the Mariahout wood edge'
}))

C.append(mk.card(2201, 'Het Hurkske', {
 'tags': ['Noord-Brabant · tussen Erp en Gemert (Meierijstad/gem. Gemert-Bakel)', 'bosgebied van ± 170 ha op oude heide · naald- en gemengd bos met het Rauwven — een ven met enigszins kalkrijk water en een palet van amfibieën en planten', 'list 81 · no. 35'],
 'loc': '📍 Het Hurkske, tussen Erp en Gemert, omringd door agrarisch gebied — zandpaden door het bos; het Rauwven ligt in het gebied; combineer met het Hurkske-bos en de Gemertse routes (kaart 2202)',
 'desc': 'Tussen <b>Erp</b> en <b>Gemert</b>, midden in agrarisch Brabant, ligt <b>Het Hurkske</b>: een bosgebied van ± <b>170 hectare</b> dat van oorsprong vooral <b>heide</b> was en vandaag uit <b>naaldbos en gemengd bos</b> bestaat — een eiland van groen dat de wandelaar in een paar uur rondom loopt. De naam (“hurk” = hoek/hoekje grond) bewaart de herinnering aan het bescheiden begin: een hoekje van de grote Gemertse heidevelden dat bebost raakte toen de ontginningen van de negentiende en twintigste eeuw het open land verdeelden. De parel van het gebied is het <b>Rauwven</b>: een prachtig ven met <b>enigszins kalkrijk water</b> — zeldzaam in het zure Brabant — waar rondom een mooi palet aan <b>amfibieën- en plantensoorten</b> voorkomt: kamsalamander en kleine watersalamander in het voorjaar in het water, geelgroene muur- en veenmossen op de randen. In het bos zelf wonen spechten, bosuil en de das; de randen zijn rijk aan zangvogels die van de overgang bos-akker profiteren. Het Hurkske is de stille tegenhanger van de grote Peelbossen: geen poorten, geen drukte — alleen bos, ven en de stilte tussen twee dorpen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (amfibieën in het Rauwven), apr–jun (zangvogels), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Avond — amfibieën en schemering.',
 'why': ['Het <b>Rauwven</b> met zijn enigszins kalkrijke water.', 'Het <b>palet van amfibieën</b> rond het ven.', 'De <b>170 ha</b> naald- en gemengd bos op oude heide.', 'De <b>eilandsligging</b> midden in agrarisch gebied.', 'De <b>stilte</b> tussen Erp en Gemert.'],
 'phen': ['<span class="months">Mrt–mei</span> 🐸 <b>Salamanders</b> in het Rauwven.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogelkoor</b> in de randen.', '<span class="months">Jun–aug</span> 🪰 <b>Libellen</b> boven het ven.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in naald en loof.'],
 'wild': ['💧 Rauwven (kalkrijk)', '🐸 Amfibieën-palet', '🌲 Naald- en gemengd bos', '🐦 Spechten en bosuil', '🤫 Stille eilandbossen'],
 'trail': ['Wandel de <b>zandpaden rond Het Hurkske</b>.', 'Zoek het <b>Rauwven</b> en zijn bewoners.', 'Combineer met de <b>bosroutes van Gemert</b> (kaart 2202).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 4–7 km · ⚠️ Venranden niet betreden'
}, {
 'tags': ['North Brabant · between Erp and Gemert (Meierijstad/gem. Gemert-Bakel)', '± 170-ha woodland on old heath · coniferous and mixed wood with the Rauwven — a fen of slightly calcareous water with a palette of amphibians and plants', 'list 81 · no. 35'],
 'loc': '📍 Het Hurkske, between Erp and Gemert, surrounded by farmland — sand paths through the wood; the Rauwven lies within; combine with the Hurkske wood and the Gemert routes (card 2202)',
 'desc': 'Between <b>Erp</b> and <b>Gemert</b>, in the middle of agricultural Brabant, lies <b>Het Hurkske</b>: a woodland of ± <b>170 hectares</b> that was originally mostly <b>heath</b> and today consists of <b>coniferous and mixed woodland</b> — an island of green that the walker rounds in a few hours. The name (“hurk” = nook of ground) keeps the memory of the modest beginning: a corner of the great Gemert heath fields that became wooded as the reclamations of the nineteenth and twentieth centuries divided the open land. The pearl of the area is the <b>Rauwven</b>: a beautiful fen of <b>slightly calcareous water</b> — rare in acid Brabant — around which occurs a fine palette of <b>amphibian and plant species</b>: great crested and smooth newts in the spring water, yellow-green wall and peat mosses on the edges. In the wood itself live woodpeckers, tawny owl and the badger; the edges are rich in songbirds profiting from the wood-field transition. Het Hurkske is the quiet counterpart of the great Peel forests: no gates, no bustle — only wood, fen and the silence between two villages.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (amphibians in the Rauwven), Apr–Jun (songbirds), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Evening — amphibians and dusk.',
 'why': ['The <b>Rauwven</b> with its slightly calcareous water.', 'The <b>palette of amphibians</b> around the fen.', 'The <b>170 ha</b> of coniferous and mixed wood on old heath.', 'The <b>island position</b> amid farmland.', 'The <b>silence</b> between Erp and Gemert.'],
 'phen': ['<span class="months">Mar–May</span> 🐸 <b>Newts</b> in the Rauwven.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbird chorus</b> in the edges.', '<span class="months">Jun–Aug</span> 🪰 <b>Dragonflies</b> over the fen.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in conifer and broadleaf.'],
 'wild': ['💧 Rauwven (calcareous)', '🐸 Amphibian palette', '🌲 Coniferous and mixed wood', '🐦 Woodpeckers and tawny owl', '🤫 Quiet island woodland'],
 'trail': ['Walk the <b>sand paths around Het Hurkske</b>.', 'Seek the <b>Rauwven</b> and its inhabitants.', 'Combine with the <b>woodland routes of Gemert</b> (card 2202).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 4–7 km · ⚠️ Do not enter the fen edges'
}))

C.append(mk.card(2202, 'Gemertse Bos', {
 'tags': ['Noord-Brabant · Gemert-Bakel (rand van de Brabantse Peel)', 'de bosgordel van Gemert-Bakel · ± 420 ha gemeentenatuur in de Peelrandbreuk-zone — rijk aan beekjes (Esperloop, Randleloop) en geflankeerd door Grotelse Heide, Nederheide, Stippelberg, De Krim en Cleefswit', 'list 81 · no. 37'],
 'loc': '📍 Bosgebieden van Gemert-Bakel aan de rand van de Brabantse Peel — routes vanaf de dorpen Gemert, Handel en Milheeze; de Esperloop is hersteld; combineer De Sijp (2203) en Beestenveld (2204)',
 'desc': 'De gemeente <b>Gemert-Bakel</b> bezit ± <b>420 hectare natuur</b> aan de rand van de Brabantse Peel en behoort daarmee tot de groenste gemeenten van Nederland — het <b>Gemertse Bos</b> is de kapstoknaam voor die gordel. Het geheim van het gebied ligt onder de grond: hier loopt een <b>zone van breuken</b> met de <b>Peelrandbreuk</b> als belangrijkste, waardoor het landschap gevarieerd is en <b>rijk aan beekjes</b> — de <b>Esperloop</b> (waarvan de loop in 2015 werd hersteld), de Randleloop en de Overschotseloop doorsnijden de bossen en voeren kwelwater af naar de Aa en de Peel. Boven de grond vormt de gordel één geheel met de grote buurgebieden: de <b>Grotelse Heide</b>, de <b>Nederheide</b>, de <b>Stippelberg</b>, <b>De Krim</b>, <b>Cleefswit</b> en het Beestenveld (kaart 2204) — samen het Peelrand-mozaïek van den, eik, heide en beekdal. Voor de wandelaar is het Gemertse Bos de poort naar dat geheel: wie bij Gemert of Handel start, kan van bos naar heide naar ven lopen zonder de groene gordel te verlaten. Het oude gehucht <b>Esp</b>, waaraan de Esperloop haar naam ontleent, vormt de stilte-kern van het gebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (beekdalen en zangvogels), aug–sep (heideranden), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — kwellicht in de beekdalen.',
 'why': ['De <b>± 420 ha gemeentenatuur</b> van Gemert-Bakel.', 'De <b>Peelrandbreuk-zone</b> als ondergrondse motor.', 'De <b>beekjes</b>: Esperloop (2015 hersteld), Randleloop.', 'De <b>gordel</b> met Stippelberg, De Krim en Cleefswit.', 'Het <b>oude gehucht Esp</b> als stilte-kern.'],
 'phen': ['<span class="months">Mrt–mei</span> 💧 <b>Beekdalen</b> op volledige kracht.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> door de hele gordel.', '<span class="months">Aug–sep</span> 🌸 <b>Heideranden</b> in bloei.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in den en eik.'],
 'wild': ['🌲 Bosgordel van de Peelrand', '💧 Esperloop en Randleloop', '⛰️ Peelrandbreuk', '🌸 Heide- en venmozaïek', '🏡 Gehucht Esp'],
 'trail': ['Start in <b>Gemert of Handel</b> en loop de gordel in.', 'Volg de <b>herstelde Esperloop</b> door het dal.', 'Combineer met <b>De Sijp</b> (2203) en <b>Beestenveld</b> (2204).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 5–12 km · 🅿️ Dorpsranden Gemert/Handel/Milheeze'
}, {
 'tags': ['North Brabant · Gemert-Bakel (edge of the Brabant Peel)', 'the woodland belt of Gemert-Bakel · ± 420 ha of municipal nature in the Peel-edge fault zone — rich in streams (Esperloop, Randleloop) and flanked by Grotelse Heide, Nederheide, Stippelberg, De Krim and Cleefswit', 'list 81 · no. 37'],
 'loc': '📍 Woodlands of Gemert-Bakel at the edge of the Brabant Peel — routes from the villages of Gemert, Handel and Milheeze; the Esperloop has been restored; combine De Sijp (2203) and Beestenveld (2204)',
 'desc': 'The municipality of <b>Gemert-Bakel</b> owns ± <b>420 hectares of nature</b> at the edge of the Brabant Peel, ranking among the greenest municipalities of the Netherlands — the <b>Gemertse Bos</b> is the peg name for that belt. The secret of the area lies underground: here runs a <b>zone of faults</b> with the <b>Peel-edge fault</b> as the most important, making the landscape varied and <b>rich in streams</b> — the <b>Esperloop</b> (whose course was restored in 2015), the Randleloop and the Overschotseloop cut through the woods and carry seepage water to the Aa and the Peel. Above ground the belt forms one whole with the great neighbours: the <b>Grotelse Heide</b>, the <b>Nederheide</b>, the <b>Stippelberg</b>, <b>De Krim</b>, <b>Cleefswit</b> and the Beestenveld (card 2204) — together the Peel-edge mosaic of pine, oak, heath and stream valley. For the walker the Gemertse Bos is the gateway to that whole: start at Gemert or Handel and you can walk from wood to heath to fen without leaving the green belt. The old hamlet of <b>Esp</b>, which gave the Esperloop its name, forms the area’s silent core.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (stream valleys and songbirds), Aug–Sep (heath edges), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — seepage light in the valleys.',
 'why': ['The <b>± 420 ha of municipal nature</b> of Gemert-Bakel.', 'The <b>Peel-edge fault zone</b> as underground engine.', 'The <b>streams</b>: Esperloop (restored 2015), Randleloop.', 'The <b>belt</b> with Stippelberg, De Krim and Cleefswit.', 'The <b>old hamlet of Esp</b> as silent core.'],
 'phen': ['<span class="months">Mar–May</span> 💧 <b>Stream valleys</b> at full force.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> through the belt.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath edges</b> in bloom.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in pine and oak.'],
 'wild': ['🌲 Peel-edge woodland belt', '💧 Esperloop and Randleloop', '⛰️ Peel-edge fault', '🌸 Heath and fen mosaic', '🏡 Esp hamlet'],
 'trail': ['Start at <b>Gemert or Handel</b> and walk into the belt.', 'Follow the <b>restored Esperloop</b> through the valley.', 'Combine with <b>De Sijp</b> (2203) and <b>Beestenveld</b> (2204).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 5–12 km · 🅿️ Village edges Gemert/Handel/Milheeze'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2202)
mk.check()
