# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2203, 'De Sijp', {
 'tags': ['Noord-Brabant · Elsendorp (gem. Gemert-Bakel, hart van de Peel)', 'landgoed van 132 ha van Brabants Landschap · in 1895 gekocht door bankier Ledeboer, aangelegd met beuken- en Amerikaanse-eikenlanen op een sikkelduin uit het Weichselien — met voorwerkerswoning (1906) en Augustehoeve (1927)', 'list 81 · no. 38'],
 'loc': '📍 Landgoed De Sijp, Sijpseweg, Elsendorp — lanen en paden door bos, heide en landbouwgrond; combineer met Cleefswit (noord) en De Krim/Vossenberg (oost); beheer Brabants Landschap',
 'desc': 'In het hart van de Peel bij <b>Elsendorp</b> ligt <b>landgoed De Sijp</b>: <b>132 hectare</b> van <b>Brabants Landschap</b>, in <b>1895</b> gekocht door de Twentse bankier <b>Abraham Hendrik Ledeboer</b> — dezelfde ondernemer die ook de Stippelberg bezat. Het landgoed ligt op de zuidelijke helft van een <b>sikkelduin</b> uit de laatste fase van het <b>Weichselien</b>: een door de wind gevormde zandrug, duizenden jaren lang een verre uithoek in de Peelmoerassen. Ledeboer liet de Heidemaatschappij het gebied ontginnen; in de <b>crisisjaren dertig</b> werd de heide als <b>werkverschaffingsproject</b> ontgonnen. Nog altijd lopen er <b>lanen met beuk en Amerikaanse eik</b> door het afwisselende gebied van bos, heide en landbouwgrond, met naaldhout en droog loofhout. De oudste gebouwen vertellen het verhaal van de ontginning: de <b>voorwerkerswoning van 1906</b> met stallen voor de paarden en ossenploeg, en de hoge, onderkelderde <b>Augustehoeve van 1927</b> — gebouwd voor de kaasmakerij. Vandaag is De Sijp <b>rijk aan roofvogels</b>: havik, sperwer en buizerd jagen boven de lanen; in het noorden sluit het landgoed aan bij <b>Cleefswit</b> en in het oosten bij <b>De Krim</b> en het gehucht Vossenberg — de Peel-gordel van kaart 2202.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (vogels en lanen in jong groen), aug–sep (heideresten), sep–okt (paddenstoelen en herfstlicht)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht over de sikkelduin-lanen.',
 'why': ['Het <b>landgoed van Ledeboer (1895)</b> in het hart van de Peel.', 'De <b>sikkelduin-vorm</b> uit het Weichselien.', 'De <b>lanen van beuk en Amerikaanse eik</b>.', 'De <b>voorwerkerswoning (1906)</b> en <b>Augustehoeve (1927)</b>.', 'De <b>werkverschaffings-ontginning</b> van de jaren dertig.'],
 'phen': ['<span class="months">Apr–mei</span> 🌷 <b>Jong groen</b> over beuk en eikenlaan.', '<span class="months">Apr–jun</span> 🦅 <b>Roofvogels</b> boven bos en heide.', '<span class="months">Aug–sep</span> 🌸 <b>Heideresten</b> in late zomerbloei.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in het gemengde bos.'],
 'wild': ['🏡 Landgoed met lanen', '🌾 Bos, heide en landbouw', '🦅 Roofvogels', '🏔️ Sikkelduin uit het Weichselien', '🏚️ Augustehoeve 1927'],
 'trail': ['Wandel de <b>lanen van De Sijp</b> vanaf de Sijpseweg.', 'Bekijk de <b>voorwerkerswoning en Augustehoeve</b>.', 'Combineer met <b>Cleefswit</b> en <b>De Krim</b> (kaart 2202).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 4–8 km · ⚠️ Landbouwpercelen actief — paden volgen'
}, {
 'tags': ['North Brabant · Elsendorp (gem. Gemert-Bakel, heart of the Peel)', '132-ha estate of the Brabant Landscape Trust · bought in 1895 by banker Ledeboer, laid out with beech and American-oak avenues on a crescent dune from the Weichselian — with a foreman’s house (1906) and Augustehoeve (1927)', 'list 81 · no. 38'],
 'loc': '📍 De Sijp estate, Sijpseweg, Elsendorp — avenues and paths through wood, heath and farmland; combine with Cleefswit (north) and De Krim/Vossenberg (east); managed by the Brabant Landscape Trust',
 'desc': 'In the heart of the Peel near <b>Elsendorp</b> lies <b>De Sijp estate</b>: <b>132 hectares</b> of the <b>Brabant Landscape Trust</b>, bought in <b>1895</b> by the Twente banker <b>Abraham Hendrik Ledeboer</b> — the same entrepreneur who also owned the Stippelberg. The estate lies on the southern half of a <b>crescent dune</b> from the last phase of the <b>Weichselian</b>: a wind-built sand ridge, for thousands of years a remote corner in the Peel marshes. Ledeboer had the Heidemaatschappij reclaim the land; in the <b>crisis years of the 1930s</b> the heath was reclaimed as a <b>relief-works project</b>. Still, <b>avenues of beech and American oak</b> run through the varied area of wood, heath and farmland, with conifers and dry broadleaf. The oldest buildings tell the story of the reclamation: the <b>foreman’s house of 1906</b> with stables for the horses and ox team, and the tall, cellared <b>Augustehoeve of 1927</b> — built for the cheese dairy. Today De Sijp is <b>rich in birds of prey</b>: goshawk, sparrowhawk and buzzard hunt above the avenues; to the north the estate joins <b>Cleefswit</b>, to the east <b>De Krim</b> and the hamlet of Vossenberg — the Peel belt of card 2202.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birds and avenues in young green), Aug–Sep (heath remnants), Sep–Oct (fungi and autumn light)<br>\n    <b>Best time of day:</b> Morning — light over the crescent-dune avenues.',
 'why': ['The <b>estate of Ledeboer (1895)</b> in the Peel’s heart.', 'The <b>crescent-dune shape</b> from the Weichselian.', 'The <b>avenues of beech and American oak</b>.', 'The <b>foreman’s house (1906)</b> and <b>Augustehoeve (1927)</b>.', 'The <b>relief-works reclamation</b> of the 1930s.'],
 'phen': ['<span class="months">Apr–May</span> 🌷 <b>Young green</b> over beech and oak avenue.', '<span class="months">Apr–Jun</span> 🦅 <b>Birds of prey</b> over wood and heath.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath remnants</b> in late-summer bloom.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the mixed wood.'],
 'wild': ['🏡 Estate with avenues', '🌾 Wood, heath and farmland', '🦅 Birds of prey', '🏔️ Weichselian crescent dune', '🏚️ Augustehoeve 1927'],
 'trail': ['Walk the <b>avenues of De Sijp</b> from the Sijpseweg.', 'View the <b>foreman’s house and Augustehoeve</b>.', 'Combine with <b>Cleefswit</b> and <b>De Krim</b> (card 2202).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 4–8 km · ⚠️ Active farmland — follow paths'
}))

C.append(mk.card(2204, 'Beestenveld', {
 'tags': ['Noord-Brabant · bij De Rips (gem. Gemert-Bakel, Peel)', 'bosgebied van ± 362–398 ha van Staatsbosbeheer · restant van de Bakelse Peel (verdeeld in 1864) — mossen, dubbelloof en paddenstoelen, samen met Stippelberg en Nederheide ± 1.925 ha aaneengesloten bos', 'list 81 · no. 40'],
 'loc': '📍 Beestenveld bij De Rips — rondwandelingen vanaf de Deurneseweg en de Hazenhutsedijk; vormt een wandelgeheel met de Stippelberg; buur: Klotterpeel; beheer Staatsbosbeheer',
 'desc': 'Bij <b>De Rips</b> ligt het <b>Beestenveld</b>: een bosgebied van ± <b>362 tot 398 hectare</b> in eigendom van <b>Staatsbosbeheer</b> — en een naam die herinnert aan wat hier vóór het bos was. Tot <b>1864</b> besloeg het Beestenveld een veel groter gebied van <b>droge en (zeer) natte heide</b>, reikend vanaf Bakel langs de hele grens met Gemert tot aan Oploo; bij de <b>verdeling van de Bakelse Peel in 1864</b> kromp het tot het huidige kerngebied, dat de voormalige gemeente Bakel in eigendom kreeg. Vandaag is het een bos van grote stilte: een <b>grootschalig netwerk van zandpaden</b> dat zich ver uitstrekt en het gebied geliefd maakt voor <b>lange wandelingen</b>. Op de bosbodem <b>schitteren mossen en varens</b> — waaronder het zeldzame <b>dubbelloof</b> aan de randen van beekjes en greppels — en in het najaar <b>wemelt het van de paddenstoelen</b>: echte en roodgerande houtzwam het hele jaar, waaierkorstzwam in het seizoen. In het zuiden sluit het Beestenveld nauw aan bij landgoed <b>Stippelberg</b>; samen met de <b>Nederheide</b> vormt het ± <b>1.925 hectare aaneengesloten bos</b> — het grootste Peelcomplex van de regio (kaart 2202). In het oosten ligt de <b>Jodenpeel</b>, een landbouwontginning die de oude naam bewaart.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–okt</b> (paddenstoelen op top), apr–jun (vogels), winter (diepe rust en zicht)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — stilte op de zandpaden.',
 'why': ['Het <b>restant van de Bakelse Peel</b> (verdeeld 1864).', 'De <b>± 1.925 ha aaneengesloten bos</b> met Stippelberg en Nederheide.', 'De <b>mossen en het dubbelloof</b> langs beekjes en greppels.', 'De <b>paddenstoelen</b>: tonderzwam tot waaierkorstzwam.', 'De <b>diepe rust</b> van het zandpadennetwerk.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het grote bos.', '<span class="months">Jun–aug</span> 🌿 <b>Varens en mossen</b> op hun mooist.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelengolf</b> over bosbodem.', '<span class="months">Nov–feb</span> ❄️ <b>Diepe rust</b> en ver zicht.'],
 'wild': ['🌲 Groot Peelbos', '🌿 Dubbelloof en mossen', '🍄 Tonderzwammen', '🦅 Bosvogels', '🤫 Zandpaden-stilte'],
 'trail': ['Start bij de <b>Deurneseweg</b> of <b>Hazenhutsedijk</b> voor rondwandelingen.', 'Combineer met de <b>Stippelberg</b> tot één grote tocht.', 'Bezoek de <b>Klotterpeel</b> als natte buur.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 5–15 km · 🅿️ Parkeerplaatsen aan de randwegen'
}, {
 'tags': ['North Brabant · near De Rips (gem. Gemert-Bakel, Peel)', '± 362–398-ha woodland of Staatsbosbeheer · remnant of the Bakelse Peel (divided in 1864) — mosses, moonwort and fungi, with Stippelberg and Nederheide ± 1,925 ha of contiguous forest', 'list 81 · no. 40'],
 'loc': '📍 Beestenveld near De Rips — circular walks from the Deurneseweg and the Hazenhutsedijk; forms one walking whole with the Stippelberg; neighbour: Klotterpeel; managed by Staatsbosbeheer',
 'desc': 'Near <b>De Rips</b> lies the <b>Beestenveld</b>: a woodland of ± <b>362 to 398 hectares</b> owned by <b>Staatsbosbeheer</b> — and a name remembering what stood here before the wood. Until <b>1864</b> the Beestenveld covered a far greater area of <b>dry and (very) wet heath</b>, reaching from Bakel along the whole border with Gemert to Oploo; with the <b>division of the Bakelse Peel in 1864</b> it shrank to the present core, which the former municipality of Bakel received in ownership. Today it is a wood of great silence: a <b>large-scale network of sand paths</b> stretching far and wide, loved for <b>long walks</b>. On the forest floor <b>mosses and ferns glitter</b> — among them the rare <b>moonwort</b> at the edges of streams and ditches — and in autumn it <b>teems with fungi</b>: tinder and red-rimmed polypore all year, fan-shaped crust fungus in season. To the south the Beestenveld joins the <b>Stippelberg</b> estate closely; together with the <b>Nederheide</b> it forms ± <b>1,925 hectares of contiguous forest</b> — the region’s greatest Peel complex (card 2202). To the east lies the <b>Jodenpeel</b>, an agricultural reclamation that keeps the old name.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (fungi at their peak), Apr–Jun (birds), winter (deep silence and views)<br>\n    <b>Best time of day:</b> Early morning — silence on the sand paths.',
 'why': ['The <b>remnant of the Bakelse Peel</b> (divided 1864).', 'The <b>± 1,925 ha of contiguous forest</b> with Stippelberg and Nederheide.', 'The <b>mosses and moonwort</b> along streams and ditches.', 'The <b>fungi</b>: from polypore to crust fungus.', 'The <b>deep silence</b> of the sand-path network.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the great wood.', '<span class="months">Jun–Aug</span> 🌿 <b>Ferns and mosses</b> at their best.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi wave</b> over the forest floor.', '<span class="months">Nov–Feb</span> ❄️ <b>Deep silence</b> and long views.'],
 'wild': ['🌲 Great Peel wood', '🌿 Moonwort and mosses', '🍄 Polypores', '🦅 Forest birds', '🤫 Sand-path silence'],
 'trail': ['Start at the <b>Deurneseweg</b> or <b>Hazenhutsedijk</b> for circular walks.', 'Combine with the <b>Stippelberg</b> into one great walk.', 'Visit the <b>Klotterpeel</b> as wet neighbour.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 5–15 km · 🅿️ Car parks on the edge roads'
}))

C.append(mk.card(2205, 'Radiobossen', {
 'tags': ['Noord-Brabant · ten noorden van Stevensbeek (gem. Land van Cuijk)', '50 ha bos met het verhaal van Radio Sambeek (1919) · ontvangststation voor de langegolfzenders van Bandoeng — zeven masten van 61,5 m; de zender zelf moest 60 km verderop komen: Radio Kootwijk', 'list 81 · no. 43'],
 'loc': '📍 Radiobossen, ten noorden van Stevensbeek — gelegen ten noorden van de Radioplassen, de Radioweg loopt er doorheen; wandelroutes vanaf Stevensbeek (3–19 km); zwemmen in de plassen',
 'desc': 'Ten noorden van <b>Stevensbeek</b> ligt een bos dat naar een verdwenen wonder van de twintigste eeuw is genoemd: de <b>Radiobossen</b>, <b>50 hectare</b> groot, met de <b>Radioplassen</b> en de <b>Radioweg</b> als getuigen. Hier vestigde zich in <b>1919</b> een radiotelegrafie-<b>ontvangststation</b> onder de naam <b>Radio Sambeek</b> — bestemd voor de <b>langegolfzenders in Bandoeng</b>, waarmee het contact met het toenmalige Nederlandsch-Indië mogelijk werd gemaakt. Op de heide verrees een woud van <b>zeven masten van elk 61,5 meter</b>, waaraan antennekabels hingen. Maar de gevoelige ontvanger mocht niet gestoord worden door de sterke zender, en dus kwam het zendstation <b>ruim 60 kilometer verderop</b> te staan: <b>Radio Kootwijk</b> op de Veluwe. De zender is allang verdwenen, de naam bleef — en het bos groeide eromheen: de oudste delen stammen uit <b>1925</b>, de jongste uit de <b>jaren tachtig</b>, voornamelijk <b>grove en Corsicaanse den</b>. Vandaag is het een geliefd recreatiegebied met <b>zwemplassen</b>; uit <b>12 putten</b> wordt water tot 46 meter diep opgepompt. Wie hier wandelt, loopt tussen masten die er niet meer staan — en hoort alleen de wind.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–aug</b> (zwemseizoen op de plassen), apr–jun (zangvogels), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Middag — zon op de plassen; ochtend voor rust.',
 'why': ['Het verhaal van <b>Radio Sambeek (1919)</b> en Bandoeng.', 'De <b>zeven masten van 61,5 meter</b> met antennekabels.', 'De <b>afstand tot Radio Kootwijk</b> als technisch noodzakelijke.', 'Het <b>bos van 1925 tot de jaren tachtig</b> (grove en Corsicaanse den).', 'De <b>Radioplassen</b> als zwem-en rustwater.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in den en rond plas.', '<span class="months">Jun–aug</span> 🏊 <b>Zwemseizoen</b> op de Radioplassen.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> onder de dennen.', '<span class="months">Nov–feb</span> ❄️ <b>Winterstilte</b> rond het voormalig mastenveld.'],
 'wild': ['📻 Radio Sambeek 1919', '🌲 Grove en Corsicaanse den', '🏊 Radioplassen', '🦅 Bosvogels', '💧 Waterwinning (12 putten)'],
 'trail': ['Wandel de <b>routes vanaf Stevensbeek</b> (3–19 km).', 'Rondje <b>Radioplassen</b> combineren met bos en heiderand.', 'Lees het <b>informatiebord</b> over Radio Sambeek.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes 3–19 km · 🏊 Zwemen op eigen risico in plassen'
}, {
 'tags': ['North Brabant · north of Stevensbeek (gem. Land van Cuijk)', '50 ha of wood with the story of Radio Sambeek (1919) · receiving station for the long-wave transmitters of Bandoeng — seven 61.5-m masts; the transmitter itself had to stand 60 km away: Radio Kootwijk', 'list 81 · no. 43'],
 'loc': '📍 Radiobossen, north of Stevensbeek — lying north of the Radioplassen, the Radioweg runs through it; walking routes from Stevensbeek (3–19 km); swimming in the lakes',
 'desc': 'North of <b>Stevensbeek</b> lies a wood named after a vanished wonder of the twentieth century: the <b>Radiobossen</b>, <b>50 hectares</b> in size, with the <b>Radioplassen</b> lakes and the <b>Radioweg</b> as witnesses. Here, in <b>1919</b>, a radio-telegraphy <b>receiving station</b> was established under the name <b>Radio Sambeek</b> — intended for the <b>long-wave transmitters of Bandoeng</b>, with which contact with the then Dutch East Indies was made possible. On the heath rose a forest of <b>seven masts each 61.5 metres tall</b>, hung with antenna cables. But the sensitive receiver had to remain undisturbed by the powerful transmitter, and so the transmitting station came <b>more than 60 kilometres away</b>: <b>Radio Kootwijk</b> on the Veluwe. The station is long gone, the name remained — and the wood grew around it: the oldest parts date from <b>1925</b>, the youngest from the <b>1980s</b>, chiefly <b>Scots and Corsican pine</b>. Today it is a popular recreation area with <b>swimming lakes</b>; from <b>12 wells</b> water is pumped up from 46 metres deep. Walk here and you move among masts that no longer stand — and hear only the wind.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Aug</b> (swimming season on the lakes), Apr–Jun (songbirds), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Midday — sun on the lakes; morning for quiet.',
 'why': ['The story of <b>Radio Sambeek (1919)</b> and Bandoeng.', 'The <b>seven 61.5-metre masts</b> with antenna cables.', 'The <b>distance to Radio Kootwijk</b> as a technical necessity.', 'The <b>wood of 1925 to the 1980s</b> (Scots and Corsican pine).', 'The <b>Radioplassen</b> as swimming and resting water.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in pine and around lake.', '<span class="months">Jun–Aug</span> 🏊 <b>Swimming season</b> on the Radioplassen.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> under the pines.', '<span class="months">Nov–Feb</span> ❄️ <b>Winter silence</b> around the former mast field.'],
 'wild': ['📻 Radio Sambeek 1919', '🌲 Scots and Corsican pine', '🏊 Radioplassen', '🦅 Forest birds', '💧 Water winning (12 wells)'],
 'trail': ['Walk the <b>routes from Stevensbeek</b> (3–19 km).', 'Combine a <b>Radioplassen loop</b> with wood and heath edge.', 'Read the <b>information board</b> about Radio Sambeek.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–19 km · 🏊 Swimming in the lakes at own risk'
}))

C.append(mk.card(2206, 'Lactaria', {
 'tags': ['Noord-Brabant · Sambeek/Vredepeel (Peel, gem. Land van Cuijk)', 'natuurgebied op de gronden van de beroemde proefboerderij Lactaria · de modelontginning van 1909 (725 ha) die uitgroeide tot Vredepeel — met bos uit de werkverschaffingsjaren dertig', 'list 81 · no. 44'],
 'loc': '📍 Lactaria, bij Sambeek/Vredepeel in de Peel — zandpaden door bos en ontginingsland; combineer met Zwartwater (kaart 2207) en de Vredepeel-gebieden',
 'desc': 'De naam <b>Lactaria</b> klinkt als een paddenstoel — en inderdaad is het de wetenschappelijke naam van de <b>melkzwam</b> — maar in de Peel verwijst ze naar iets anders: de beroemde <b>proefboerderij Lactaria</b> die in <b>1909</b> in <b>Sambeek</b> startte met de ontginning van <b>725 hectare</b> Peelwoeste grond. Het was de tijd van de grote ontginningen, waarin de Peel van hoogveen en heide werd omgezet in grasland en bouwland; de proefboerderij moest aantonen hoe. Uiteindelijk groeide het gebied uit tot <b>Vredepeel</b> — de jongste grote Peelontginning van ± 800 hectare uit <b>1950–1955</b>, genoemd naar de vrede die de Eerste Wereldoorlog net had gebracht. Het natuurgebied <b>Lactaria</b> op die oude gronden is het bos dat de geschiedenis bewaart: naaldbos uit de <b>werkverschaffingsjaren dertig</b>, aangeplant toen de crisis de ontginningen stillegde en de werklozen met de schop naar de heide werden gestuurd. Wie hier loopt, wandelt door twee verhalen tegelijk: de droom van de moderne landbouw (Lactaria, de modelboerderij) en de noodzaak van de crisis (de dennen die vandaag het dak vormen). De melkzwammen waar de naam toevallig naar verwijst, groeien er in het najaar gewoon tussen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–okt</b> (paddenstoelen, ironisch genoeg), apr–jun (zangvogels), winter (open bos)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door de dennen.',
 'why': ['De <b>proefboerderij Lactaria (1909)</b> en haar 725 ha.', 'De <b>uitgroei naar Vredepeel</b> (1950–55, ± 800 ha).', 'Het <b>naaldbos van de werkverschaffing</b> uit de jaren dertig.', 'De <b>melkzwam</b> als toevallige naamgenoot.', 'Twee verhalen: <b>landbouwdroom en crisisnoodzaak</b>.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het ontginningsbos.', '<span class="months">Jun–aug</span> 🌿 <b>Zomergroen</b> op zand en rand.', '<span class="months">Sep–okt</span> 🍄 <b>Melkzwammen en meer</b> op de bodem.', '<span class="months">Nov–feb</span> ❄️ <b>Open winterbos</b> op de Peelgronden.'],
 'wild': ['🌲 Werkverschaffingsbos', '🍄 Melkzwammen (Lactaria)', '🚜 Ontginingsgeschiedenis', '🐦 Bosvogels', '🌾 Peelrand-gronden'],
 'trail': ['Wandel de <b>zandpaden van Lactaria</b> bij Sambeek/Vredepeel.', 'Combineer met <b>Zwartwater</b> (kaart 2207).', 'Lees het landschap van <b>ontginning en bos</b> als één verhaal.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–6 km · ⚠️ Ontginningsland actief — paden volgen'
}, {
 'tags': ['North Brabant · Sambeek/Vredepeel (Peel, gem. Land van Cuijk)', 'nature area on the grounds of the famous Lactaria model farm · the 1909 reclamation (725 ha) that grew into Vredepeel — with woodland from the relief-works years of the 1930s', 'list 81 · no. 44'],
 'loc': '📍 Lactaria, near Sambeek/Vredepeel in the Peel — sand paths through wood and reclamation land; combine with Zwartwater (card 2207) and the Vredepeel areas',
 'desc': 'The name <b>Lactaria</b> sounds like a fungus — and indeed it is the scientific name of the <b>milk cap</b> — but in the Peel it points to something else: the famous <b>Lactaria model farm</b> that started the reclamation of <b>725 hectares</b> of Peel wasteland at <b>Sambeek</b> in <b>1909</b>. It was the age of the great reclamations, when the Peel of raised bog and heath was turned into grassland and arable; the model farm was to show how. Eventually the area grew into <b>Vredepeel</b> — the youngest great Peel reclamation of ± 800 hectares from <b>1950–1955</b>, named after the peace the First World War had just brought. The nature area <b>Lactaria</b> on those old grounds is the wood that keeps the history: coniferous forest from the <b>relief-works years of the 1930s</b>, planted when the crisis halted the reclamations and the unemployed were sent to the heath with spades. Walk here and you walk through two stories at once: the dream of modern farming (Lactaria, the model farm) and the necessity of the crisis (the pines that roof it today). The milk caps the name coincidentally refers to simply grow there in autumn.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (fungi, ironically enough), Apr–Jun (songbirds), winter (open wood)<br>\n    <b>Best time of day:</b> Morning — light through the pines.',
 'why': ['The <b>Lactaria model farm (1909)</b> and its 725 ha.', 'The <b>growth into Vredepeel</b> (1950–55, ± 800 ha).', 'The <b>relief-works coniferous wood</b> of the 1930s.', 'The <b>milk cap</b> as coincidental namesake.', 'Two stories: <b>farming dream and crisis necessity</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the reclamation wood.', '<span class="months">Jun–Aug</span> 🌿 <b>Summer green</b> on sand and edge.', '<span class="months">Sep–Oct</span> 🍄 <b>Milk caps and more</b> on the floor.', '<span class="months">Nov–Feb</span> ❄️ <b>Open winter wood</b> on the Peel grounds.'],
 'wild': ['🌲 Relief-works wood', '🍄 Milk caps (Lactaria)', '🚜 Reclamation history', '🐦 Forest birds', '🌾 Peel-edge grounds'],
 'trail': ['Walk the <b>sand paths of Lactaria</b> near Sambeek/Vredepeel.', 'Combine with <b>Zwartwater</b> (card 2207).', 'Read the landscape of <b>reclamation and wood</b> as one story.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–6 km · ⚠️ Active reclamation land — follow paths'
}))

C.append(mk.card(2207, 'Zwartwater', {
 'tags': ['Noord-Brabant · nabij Vredepeel (gem. Land van Cuijk)', '165 ha bos en heide met zwarte venen · schrale heidevelden en poelen, plagbeheer tegen vergrassing, een gehoede kudde en oude grove, Corsicaanse en Oostenrijkse dennen na noodvellingen', 'list 81 · no. 46'],
 'loc': '📍 Zwartwater (ook: Zwart Water), nabij Vredepeel — wandelingen door bos en heidevelden; combineer met Lactaria (kaart 2206) en de Ballonzuilbossen (kaart 2208)',
 'desc': 'Nabij <b>Vredepeel</b> ligt <b>Zwartwater</b> (ook geschreven als Zwart Water): een gebied van <b>165 hectare</b> waarin de zwarte venen van de Peel de kleur van het water en de naam van het gebied bepaalden. De bossen liggen op overwegend <b>droge grond</b>; in het <b>oosten</b> sluit een <b>groot natuurterrein</b> aan — het open hart van het gebied, met <b>schrale heidevelden</b>, hier en daar een <b>poel</b> en <b>mooie vergezichten</b> over het vlakke Peelrandland. Het beheer is een oefening in volhouden: al jarenlang worden <b>diverse stukken geplagd</b> om de <b>vergrassing</b> tegen te gaan, en een <b>gehoede kudde</b> graast jaarlijks de grassen kort — de schaapherder als opvolger van de ontginner. De bossen zelf dragen de sporen van de twintigste eeuw: voornamelijk <b>oudere grove, Corsicaanse en Oostenrijkse dennen</b>, waarbij eind <b>jaren tachtig grootschalige noodvellingen</b> plaatsvonden — waarna vooral <b>eiken, grove dennen en berken</b> werden aangeplant. Zo is Zwartwater een generatiebos: oud naaldhout aan de ene kant, jong gemengd aan de andere, en daartussen de heide die het allemaal ooit was. Wie de Vredepeel-gordel loopt — Lactaria (2206), Zwartwater, Ballonzuilbossen (2208) — proeft de hele Peelgeschiedenis in één middag.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide in bloei), apr–jun (vogels en poelen), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Middag — warmte op de heide; avondlucht boven de velden.',
 'why': ['De <b>schrale heidevelden met poelen</b> als open hart.', 'Het <b>plagbeheer tegen vergrassing</b> als volhouderij.', 'De <b>gehoede kudde</b> als grazende beheerder.', 'De <b>oude dennen</b> (grove, Corsicaanse, Oostenrijkse).', 'De <b>noodvellingen en herplant</b> als generatiebos-verhaal.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Heidevogels</b> boven de velden.', '<span class="months">Jun–aug</span> 🦗 <b>Sprinkhanen</b> op de schrale delen.', '<span class="months">Aug–sep</span> 🌸 <b>Heidebloei</b> over het oostterrein.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in oud en jong bos.'],
 'wild': ['🌸 Schrale heidevelden', '💧 Poelen en zwarte venen', '🐑 Gehoede kudde', '🌲 Oude dennensoorten', '🧹 Plagbeheer'],
 'trail': ['Wandel de <b>heidevelden en bossen</b> van Zwartwater.', 'Combineer met <b>Lactaria</b> (2206) en <b>Ballonzuilbossen</b> (2208).', 'Zoek de <b>poelen</b> en de vergezichten van het oostterrein.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 4–8 km · ⚠️ Kudde op afstand — aanwijzingen volgen'
}, {
 'tags': ['North Brabant · near Vredepeel (gem. Land van Cuijk)', '165 ha of wood and heath with black fens · poor heath fields and pools, sod-cutting against grass encroachment, a shepherded flock and old Scots, Corsican and Austrian pines after salvage fellings', 'list 81 · no. 46'],
 'loc': '📍 Zwartwater (also: Zwart Water), near Vredepeel — walks through wood and heath fields; combine with Lactaria (card 2206) and the Ballonzuilbossen (card 2208)',
 'desc': 'Near <b>Vredepeel</b> lies <b>Zwartwater</b> (also written Zwart Water): an area of <b>165 hectares</b> in which the black fens of the Peel determined the colour of the water and the area’s name. The woods stand on predominantly <b>dry ground</b>; to the <b>east</b> a <b>large nature terrain</b> joins — the open heart of the area, with <b>poor heath fields</b>, here and there a <b>pool</b> and <b>fine views</b> across the flat Peel-edge land. The management is an exercise in persistence: for years <b>various patches have been sod-cut</b> to fight <b>grass encroachment</b>, and a <b>shepherded flock</b> grazes the grasses short each year — the shepherd as successor of the reclaimers. The woods themselves bear the traces of the twentieth century: mainly <b>older Scots, Corsican and Austrian pines</b>, among which <b>large-scale salvage fellings</b> took place at the end of the <b>1980s</b> — after which chiefly <b>oaks, Scots pines and birches</b> were planted. Thus Zwartwater is a two-generation wood: old conifer on one side, young mixed on the other, and between them the heath it all once was. Walk the Vredepeel belt — Lactaria (2206), Zwartwater, Ballonzuilbossen (2208) — and taste the whole Peel history in one afternoon.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heath in bloom), Apr–Jun (birds and pools), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Midday — warmth on the heath; evening sky over the fields.',
 'why': ['The <b>poor heath fields with pools</b> as open heart.', 'The <b>sod-cutting against grass encroachment</b> as persistence.', 'The <b>shepherded flock</b> as grazing manager.', 'The <b>old pines</b> (Scots, Corsican, Austrian).', 'The <b>salvage fellings and replanting</b> as a two-generation story.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Heath birds</b> above the fields.', '<span class="months">Jun–Aug</span> 🦗 <b>Grasshoppers</b> on the poor parts.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath bloom</b> over the east terrain.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in old and young wood.'],
 'wild': ['🌸 Poor heath fields', '💧 Pools and black fens', '🐑 Shepherded flock', '🌲 Old pine species', '🧹 Sod-cutting management'],
 'trail': ['Walk the <b>heath fields and woods</b> of Zwartwater.', 'Combine with <b>Lactaria</b> (2206) and the <b>Ballonzuilbossen</b> (2208).', 'Seek the <b>pools</b> and views of the east terrain.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 4–8 km · ⚠️ Keep distance from flock — follow signs'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2207)
mk.check()
