# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2208, 'Ballonzuilbossen', {
 'tags': ['Noord-Brabant · tussen Venray, Overloon, Vierlingsbeek en Boxmeer', 'bosgebied met het ballonvaart-monument van 18 januari 1896 · de luchtballon “La poste de Paris” landde hier ruim 130 jaar geleden in het natte heidegebied — paaltjesroutes van 8, 13 en 14 km', 'list 81 · no. 47'],
 'loc': '📍 Ballonzuilbossen tussen Venray, Overloon, Vierlingsbeek en Boxmeer — start bij de Ballonzuil aan de weg “Roosendael” (roos = riet); visvijvers bij de start; paaltjesroutes 8/13/14 km',
 'desc': 'Tussen <b>Venray</b>, <b>Overloon</b>, <b>Vierlingsbeek</b> en <b>Boxmeer</b> liggen de <b>Ballonzuilbossen</b> — genoemd naar een van de curiositeiten van de Brabantse Peel: de <b>Ballonzuil</b>, opgericht op <b>18 januari 1896</b> ter plekke waar een luchtballon met de naam <b>“La poste de Paris”</b> ruim 130 jaar geleden neerkwam in wat toen een <b>nat heidegebied</b> was. De ballonvaart was een sensatie in haar tijd — en de zuil hield de herinnering vast toen de heide allang door bos was vervangen. De weg erheen heet <b>“Roosendael”</b>, naar de roos (riet) die hier ooit groeide. De bossen zelf zijn typisch Peelrand-naaldbos afgewisseld met open stukken en vennen; bij de start liggen <b>visvijvers</b>, en het gebied wordt ontsloten door <b>paaltjesroutes van 8, 13 en 14 kilometer</b> die bos, heiderest en monument aan elkaar rijgen. Wie hier wandelt, loopt van de negentiende-eeuwse luchtvaart naar de twintigste-eeuwse bebossing — en terug: de zuil staat er nog, midden in het groen dat de heide verdrong.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (vogels), aug–sep (heideresten), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — rust bij de zuil en de vijvers.',
 'why': ['De <b>Ballonzuil van 18 januari 1896</b> als merkwaardig monument.', 'De ballon <b>“La poste de Paris”</b> en haar noodlanding in de heide.', 'De <b>visvijvers</b> en de rustige startplaats.', 'De <b>paaltjesroutes van 8, 13 en 14 km</b>.', 'De <b>naam “Roosendael”</b> (roos = riet) als taalschat.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in bos en venrand.', '<span class="months">Jun–aug</span> 🎣 <b>Vijverleven</b> bij de start.', '<span class="months">Aug–sep</span> 🌸 <b>Heideresten</b> in late bloei.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in het Peelrandbos.'],
 'wild': ['🎈 Ballonzuil 1896', '🌲 Peelrand-naaldbos', '🎣 Visvijvers', '🌸 Heideresten', '🥾 Paaltjesroutes'],
 'trail': ['Start bij de <b>Ballonzuil</b> en de visvijvers.', 'Volg de <b>paaltjesroutes</b> van 8, 13 of 14 km.', 'Combineer met <b>Zwartwater</b> (2207) en <b>Lactaria</b> (2206).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes 8/13/14 km · 🅿️ Parkeerplek bij de zuil'
}, {
 'tags': ['North Brabant · between Venray, Overloon, Vierlingsbeek and Boxmeer', 'woodland with the balloon monument of 18 January 1896 · the air balloon “La poste de Paris” landed here over 130 years ago in the wet heathland — waymarked routes of 8, 13 and 14 km', 'list 81 · no. 47'],
 'loc': '📍 Ballonzuilbossen between Venray, Overloon, Vierlingsbeek and Boxmeer — start at the Ballonzuil on the road “Roosendael” (roos = reed); fishing ponds at the start; waymarked routes 8/13/14 km',
 'desc': 'Between <b>Venray</b>, <b>Overloon</b>, <b>Vierlingsbeek</b> and <b>Boxmeer</b> lie the <b>Ballonzuilbossen</b> — named after one of the curiosities of the Brabant Peel: the <b>Ballonzuil</b>, erected on <b>18 January 1896</b> at the spot where an air balloon named <b>“La poste de Paris”</b> came down over 130 years ago in what was then a <b>wet heathland</b>. The balloon flight was a sensation in its day — and the pillar held the memory when the heath had long since been replaced by wood. The road to it is called <b>“Roosendael”</b>, after the roos (reed) that once grew here. The woods themselves are typical Peel-edge conifer forest alternating with open parts and fens; at the start lie <b>fishing ponds</b>, and the area is opened up by <b>waymarked routes of 8, 13 and 14 kilometres</b> stringing wood, heath remnant and monument together. Walk here and you move from nineteenth-century ballooning to twentieth-century planting — and back: the pillar still stands, in the middle of the green that displaced the heath.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (birds), Aug–Sep (heath remnants), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — quiet at the pillar and the ponds.',
 'why': ['The <b>Ballonzuil of 18 January 1896</b> as a remarkable monument.', 'The balloon <b>“La poste de Paris”</b> and its forced landing in the heath.', 'The <b>fishing ponds</b> and quiet starting point.', 'The <b>waymarked routes of 8, 13 and 14 km</b>.', 'The <b>name “Roosendael”</b> (roos = reed) as language treasure.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in wood and fen edge.', '<span class="months">Jun–Aug</span> 🎣 <b>Pond life</b> at the start.', '<span class="months">Aug–Sep</span> 🌸 <b>Heath remnants</b> in late bloom.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the Peel-edge wood.'],
 'wild': ['🎈 Ballonzuil 1896', '🌲 Peel-edge conifer wood', '🎣 Fishing ponds', '🌸 Heath remnants', '🥾 Waymarked routes'],
 'trail': ['Start at the <b>Ballonzuil</b> and the fishing ponds.', 'Follow the <b>waymarked routes</b> of 8, 13 or 14 km.', 'Combine with <b>Zwartwater</b> (2207) and <b>Lactaria</b> (2206).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 8/13/14 km · 🅿️ Parking at the pillar'
}))

C.append(mk.card(2209, 'Kuststrook Walcheren', {
 'tags': ['Zeeland · Walcheren (duinen en strand tussen Westkapelle en Domburg/Vlissingen)', 'strand, duinen en de “Zeeuwse Rivièra” van Zoutelande · met het oudste bosgebied van Walcheren en een gordel van ± tien middeleeuwse landgoederen — meidoorn als kenmerkendste struik en tienduizenden trekvogels', 'list 83 · no. 1'],
 'loc': '📍 Kuststrook van Walcheren — duinen en strand van Westkapelle via Zoutelande naar Domburg; SBB-deelgebied Walcheren; hondenloslooproutes; combineer met de landgoederen Berkenbosch, Duinbeek en Westhove',
 'desc': 'De <b>kuststrook van Walcheren</b> is meer dan strand: het is een aaneengesloten lint van <b>duinen, stranden en bos</b> dat van <b>Westkapelle</b> via <b>Zoutelande</b> naar <b>Domburg</b> loopt — met dank aan het milde <b>microklimaat</b> aan de zuidkant van het eiland. Dat microklimaat maakte de badplaatsen groot: <b>Zoutelande</b> heet niet voor niets de <b>“Zeeuwse Rivièra”</b>, met zijn breedde strand en zongerichte hellingen. Direct achter de duinen ligt een verrassing: het <b>oudste bosgebied van Walcheren</b>, deel van een strook van ± <b>tien middeleeuwse landgoederen</b> — met namen als <b>Berkenbosch, Duinbeek en Westhove</b> — met oude lanen, vijvers en rododendrons die de landgoederentijd verraden. De kenmerkendste struik van de kuststrook is de <b>meidoorn</b>: dichte, doornige struweelvormers die in mei wit bloeien en in de herfst vol bessen zitten. En dan de vogels: Walcheren ligt op een van de grote vliegroutes van Europa — de <b>voor- en najaarstrek</b> brengt <b>tienduizenden vogels</b> over de kust, van klein tot zeldzaam. Staatsbosbeheer ontsluit het gebied met wandelroutes en <b>hondenloslooproutes</b>; wie rust wil, zoekt de stilte bij de bunkers; wie leven wil, loopt in mei langs de meidoorns.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei</b> (meidoornbloei), aug–okt (najaarstrek), mrt–apr (voorstrek)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — trek en rust op het strand.',
 'why': ['De <b>“Zeeuwse Rivièra”</b> van Zoutelande en het microklimaat.', 'Het <b>oudste bos van Walcheren</b> achter de duinen.', 'De <b>± tien middeleeuwse landgoederen</b> (Berkenbosch, Duinbeek, Westhove).', 'De <b>meidoorn</b> als kenmerkendste struik.', 'De <b>tienduizenden trekvogels</b> in voor- en najaar.'],
 'phen': ['<span class="months">Mrt–mei</span> 🕊️ <b>Voorjaarstrek</b> over de kust.', '<span class="months">Mei</span> 🌸 <b>Meidoornbloei</b> wit langs de paden.', '<span class="months">Jul–aug</span> 🌊 <b>Zomerstrand</b> en duingroen.', '<span class="months">Sep–okt</span> 🕊️ <b>Najaarstrek</b> op zijn hoogtepunt.'],
 'wild': ['🌊 Duinen en strand', '🌳 Oudste bos van Walcheren', '🏡 Middeleeuwse landgoederen', '🌸 Meidoorn', '🕊️ Vogeltrek'],
 'trail': ['Wandel de <b>duinovergang Westkapelle–Domburg</b>.', 'Bezoek de <b>landgoederen</b> Berkenbosch, Duinbeek en Westhove.', 'Gebruik de <b>hondenloslooproutes</b> van SBB.'],
 'foot': '🐕 Loslooproutes aanwezig · 💶 Gratis · 🚶 Duinstranden ± 8–17 km · ⚠️ Duinpaadjes kwetsbaar — pad volgen'
}, {
 'tags': ['Zeeland · Walcheren (dunes and beach between Westkapelle and Domburg/Vlissingen)', 'beach, dunes and the “Zeeland Riviera” of Zoutelande · with Walcheren’s oldest woodland and a belt of ± ten medieval estates — hawthorn as most characteristic shrub and tens of thousands of migratory birds', 'list 83 · no. 1'],
 'loc': '📍 Coastal strip of Walcheren — dunes and beach from Westkapelle via Zoutelande to Domburg; SBB sub-area Walcheren; dog-exercise routes; combine with the estates Berkenbosch, Duinbeek and Westhove',
 'desc': 'The <b>coastal strip of Walcheren</b> is more than beach: it is a continuous ribbon of <b>dunes, beaches and wood</b> running from <b>Westkapelle</b> via <b>Zoutelande</b> to <b>Domburg</b> — thanks to the mild <b>microclimate</b> on the island’s south side. That microclimate made the resorts grow: <b>Zoutelande</b> is rightly called the <b>“Zeeland Riviera”</b>, with its broad beach and sun-facing slopes. Just behind the dunes lies a surprise: <b>Walcheren’s oldest woodland</b>, part of a strip of ± <b>ten medieval estates</b> — with names like <b>Berkenbosch, Duinbeek and Westhove</b> — with old avenues, ponds and rhododendrons betraying the estate era. The coast’s most characteristic shrub is the <b>hawthorn</b>: dense, thorny masses that bloom white in May and hang full of berries in autumn. And then the birds: Walcheren lies on one of Europe’s great flyways — the <b>spring and autumn migration</b> brings <b>tens of thousands of birds</b> over the coast, from common to rare. Staatsbosbeheer opens the area with walking routes and <b>dog-exercise routes</b>; those seeking quiet find it by the bunkers; those seeking life walk the hawthorns in May.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May</b> (hawthorn bloom), Aug–Oct (autumn migration), Mar–Apr (spring migration)<br>\n    <b>Best time of day:</b> Early morning — migration and calm on the beach.',
 'why': ['The <b>“Zeeland Riviera”</b> of Zoutelande and the microclimate.', '<b>Walcheren’s oldest wood</b> behind the dunes.', 'The <b>± ten medieval estates</b> (Berkenbosch, Duinbeek, Westhove).', 'The <b>hawthorn</b> as most characteristic shrub.', 'The <b>tens of thousands of migrants</b> in spring and autumn.'],
 'phen': ['<span class="months">Mar–May</span> 🕊️ <b>Spring migration</b> over the coast.', '<span class="months">May</span> 🌸 <b>Hawthorn bloom</b> white along the paths.', '<span class="months">Jul–Aug</span> 🌊 <b>Summer beach</b> and dune green.', '<span class="months">Sep–Oct</span> 🕊️ <b>Autumn migration</b> at its peak.'],
 'wild': ['🌊 Dunes and beach', '🌳 Oldest Walcheren wood', '🏡 Medieval estates', '🌸 Hawthorn', '🕊️ Bird migration'],
 'trail': ['Walk the <b>dune crossing Westkapelle–Domburg</b>.', 'Visit the <b>estates</b> Berkenbosch, Duinbeek and Westhove.', 'Use the SBB <b>dog-exercise routes</b>.'],
 'foot': '🐕 Dog-exercise routes available · 💶 Free · 🚶 Dune stretches ± 8–17 km · ⚠️ Fragile dune paths — stay on path'
}))

C.append(mk.card(2210, 'Het Zwin en Kievittepolder', {
 'tags': ['Zeeland · bij Cadzand-Bad en Retranchement (gem. Sluis)', 'zeearm-slufter van schorren, slikken en zandplaten · oude vaarroute naar Brugge, ± 200 ha schor in de monding (80% in België) — het Zeeuwse deel is de Kievittepolder van Stichting Het Zwin, met lepelaars', 'list 83 · no. 3'],
 'loc': '📍 Het Zwin bij Cadzand-Bad en Retranchement — bezoekerscentrum ’t Zwin in Retranchement; wandelen langs de zeedijk met zicht op schorren en slufter; radartoren Walradarketen; grensoverschrijdend naar Knokke (BE)',
 'desc': 'Het <b>Zwin</b> is de versteende herinnering aan een glorietijd: de <b>zeearm die Brugge tot de rijkste handelsstad van Noord-Europa maakte</b> — via deze vaarroute voeren de schepen van de zee naar de stad, tot verzanding de monding in de vijftiende eeuw sloot. Wat bleef is een <b>slufter</b>: een getijdengebied van <b>schorren, slikken en zandvlaktes</b> dat bij elke vloed opnieuw volloopt en bij eb leegloopt — ± <b>200 hectare schor</b> in de monding, waarvan ± <b>80% in België</b> ligt. Het Nederlandse deel draagt de naam <b>Kievittepolder</b> (de inlaag die na de stormvloed van 1530 ten noorden van de Noorddijk ontstond) en is in beheer bij <b>Stichting Het Zwin</b>; in de polder broeden o.a. <b>lepelaars</b>. Het gebied is <b>Natura 2000</b>-gebied — en juist die status staat onder druk: de <b>nieuwbouw van Cadzand-Bad</b> (hotel Noordzee, residentie De Nieuwe Wielingen) nadert de grens van het beschermd gebied. Wie hier wandelt, loopt over de <b>Zeedijk</b> met uitzicht over de slufter, naar de <b>radartoren Walradarketen</b>, of steekt de grens over naar het Belgische Zwin-park. Het contrast is het mooist bij <b>hoogwater</b>: de schorren worden eilanden, de vogels worden dicht, en voor even is de middeleeuwse zee terug.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–okt</b> (najaarstrek), mrt–mei (broedtijd lepelaars), jul–aug (hoogwater-schouw)<br>\n    <b>Beste tijd van de dag:</b> Rond hoogwater — vogels dicht op de schorren.',
 'why': ['De <b>oude zeearm naar Brugge</b> als handelsroute.', 'De <b>slufter van schorren, slikken en zandplaten</b>.', 'De <b>Kievittepolder</b> als Nederlandse helft.', 'De <b>lepelaars</b> en de broedvogels van het schor.', 'De spanning tussen <b>Cadzand-Bad-nieuwbouw</b> en Natura 2000.'],
 'phen': ['<span class="months">Mrt–mei</span> 🥄 <b>Lepelaars</b> broeden in de polder.', '<span class="months">Jun–aug</span> 🌊 <b>Hoogwater</b> over schor en slik.', '<span class="months">Sep–okt</span> 🕊️ <b>Najaarstrek</b> langs de kust.', '<span class="months">Nov–feb</span> ❄️ <b>Winterstiltewanden</b> over de slufter.'],
 'wild': ['🌊 Slufter en getij', '🌱 Schorren en slikken', '🥄 Lepelaars', '🏛️ Zeearm naar Brugge', '🇧🇪 Grensgebied'],
 'trail': ['Wandel over de <b>Zeedijk</b> met uitzicht op de slufter.', 'Bezoek het <b>bezoekerscentrum ’t Zwin</b> in Retranchement.', 'Zoek de <b>radartoren Walradarketen</b> op de dijk.'],
 'foot': '🐕 Honden aangelijnd (vogelgebied) · 💶 Dijk gratis, centrum tegen betaling · 🚶 Dijkwandelingen ± 3–10 km · 🇧🇪 Grens naar Knokke vrij'
}, {
 'tags': ['Zeeland · near Cadzand-Bad and Retranchement (gem. Sluis)', 'sea-arm slufter of salt marshes, mudflats and sand plates · old shipping route to Bruges, ± 200 ha of marsh at the mouth (80% in Belgium) — the Zeeland part is the Kievittepolder of the Zwin Foundation, with spoonbills', 'list 83 · no. 3'],
 'loc': '📍 Het Zwin near Cadzand-Bad and Retranchement — visitor centre ’t Zwin in Retranchement; walk the sea dike with views of marshes and slufter; Walradarketen radar tower; cross-border to Knokke (BE)',
 'desc': 'The <b>Zwin</b> is the petrified memory of a golden age: the <b>sea arm that made Bruges the richest trading city of Northern Europe</b> — through this route the ships sailed from sea to city, until silting closed the mouth in the fifteenth century. What remains is a <b>slufter</b>: a tidal area of <b>salt marshes, mudflats and sand flats</b> that refills with every flood and empties with every ebb — ± <b>200 hectares of marsh</b> at the mouth, of which ± <b>80% lies in Belgium</b>. The Dutch part carries the name <b>Kievittepolder</b> (the inlet that arose north of the Noorddijk after the storm flood of 1530) and is managed by the <b>Zwin Foundation</b>; among others, <b>spoonbills</b> breed in the polder. The area is a <b>Natura 2000</b> site — and precisely that status is under pressure: the <b>new building of Cadzand-Bad</b> (hotel Noordzee, residence De Nieuwe Wielingen) approaches the protected border. Walk here along the <b>sea dike</b> overlooking the slufter, to the <b>Walradarketen radar tower</b>, or cross the border into the Belgian Zwin park. The contrast is finest at <b>high water</b>: the marshes become islands, the birds crowd together, and for a moment the medieval sea is back.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (autumn migration), Mar–May (spoonbill breeding), Jul–Aug (high-tide spectacle)<br>\n    <b>Best time of day:</b> Around high water — birds tight on the marshes.',
 'why': ['The <b>old sea arm to Bruges</b> as trade route.', 'The <b>slufter of marshes, mudflats and sand flats</b>.', 'The <b>Kievittepolder</b> as the Dutch half.', 'The <b>spoonbills</b> and breeding birds of the marsh.', 'The tension between <b>Cadzand-Bad building</b> and Natura 2000.'],
 'phen': ['<span class="months">Mar–May</span> 🥄 <b>Spoonbills</b> breeding in the polder.', '<span class="months">Jun–Aug</span> 🌊 <b>High water</b> over marsh and mudflat.', '<span class="months">Sep–Oct</span> 🕊️ <b>Autumn migration</b> along the coast.', '<span class="months">Nov–Feb</span> ❄️ <b>Winter-silence walks</b> over the slufter.'],
 'wild': ['🌊 Slufter and tide', '🌱 Marshes and mudflats', '🥄 Spoonbills', '🏛️ Sea arm to Bruges', '🇧🇪 Border area'],
 'trail': ['Walk the <b>sea dike</b> with views of the slufter.', 'Visit the <b>’t Zwin visitor centre</b> in Retranchement.', 'Seek the <b>Walradarketen radar tower</b> on the dike.'],
 'foot': '🐕 Dogs on lead (bird area) · 💶 Dike free, centre for a fee · 🚶 Dike walks ± 3–10 km · 🇧🇪 Border to Knokke open'
}, n2k='Het Zwin en Kievittepolder is onderdeel van het Natura 2000-gebied “Het Zwin” — internationaal beschermd getijdengebied waar de grens dwars door de schorren loopt.', n2k_en='Het Zwin en Kievittepolder is part of the Natura 2000 site “Het Zwin” — an internationally protected tidal area whose border runs straight through the marshes.'))

C.append(mk.card(2211, 'Oudelandse Polder', {
 'tags': ['Zeeland · Cadzand, Retranchement en Terhofstede (gem. Sluis)', '± 906 ha polderlandschap van −0,1 tot +1,4 m NAP · een conglomeraat van kleine middeleeuwse poldertjes — de oudste inpolderingen van West-Europa, in 1530 vrijwel geheel weggespoeld', 'list 83 · no. 4'],
 'loc': '📍 Oudelandse Polder rond Cadzand, delen van Retranchement en Terhofstede (NW grenzend aan Het Zwin) — dijkpaden en polderweggetjes; uitwateringskanaal naar de Wielingen; combineer met Het Zwin (kaart 2210)',
 'desc': 'De <b>Oudelandse Polder</b> (± <b>906 hectare</b>, gelegen tussen <b>−0,1 en +1,4 meter NAP</b>) bij <b>Cadzand</b> is een oeroud landschap: een <b>conglomeraat van kleine middeleeuwse poldertjes</b> die samen de <b>oudste inpolderingen van West-Europa</b> vormen. De namen op de kaart verraden de leeftijd: na de oudste inpoldering (Sudhpolra) zijn <b>Kerckpolre en Sudpolre</b> de oudste namen die bewaard bleven — middeleeuwse dijkjes en slootpatroon die vandaag nog steeds de verkaveling bepalen. In de <b>13e eeuw</b> was <b>Cadzand</b> een eiland van ruwweg de huidige polderomvang; de <b>stormvloed van 1530</b> liep het gebied vrijwel geheel onder, waarna de <b>Noorddijk</b> (≈ de inlaagdijk van 1531) het herstel markeert — ten noorden daarvan ontstond later de <b>Kievittepolder</b>. Het water gaat nog steeds de oude weg: via het <b>uitwateringskanaal</b> stroomt de polder af op de <b>Wielingen</b>. Wie hier fietst, ziet het verleden in het kleine: kreekresten, oude dijkhuizen, wilgen en weilanden vol grazende ganzen in de winter — de stilte achter de Zeedijk, waar het Zwin (kaart 2210) de revolutie van getij en schor levert en de Oudelandse Polder de eeuwen van droogmakerij.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Okt–mrt</b> (overwinterende ganzen en zwanen), apr–mei (weilandvogels), jun–aug (werkend polderlandschap)<br>\n    <b>Beste tijd van de dag:</b> Avond — licht over de oude dijkjes.',
 'why': ['De <b>oudste inpolderingen van West-Europa</b>.', 'De middeleeuwse namen <b>Kerckpolre en Sudpolre</b>.', 'De <b>stormvloed van 1530</b> en de Noorddijk als inlaagdijk.', 'Het <b>uitwateringskanaal naar de Wielingen</b>.', 'Het <b>eiland Cadzand van de 13e eeuw</b> als oervorm.'],
 'phen': ['<span class="months">Okt–mrt</span> 🪿 <b>ganzen en zwanen</b> op de weilanden.', '<span class="months">Apr–mei</span> 🎶 <b>Weilandvogels</b> boven de polder.', '<span class="months">Jun–aug</span> 🌾 <b>Zomerweiden</b> en koeien.', '<span class="months">Sep–okt</span> 🍂 <b>Oogstlicht</b> over oude verkaveling.'],
 'wild': ['🦆 Poldervogels', '🌾 Oude verkaveling', '🏛️ Middeleeuwse dijkjes', '💧 Uitwateringskanaal', '🤫 Stilte achter de zeedijk'],
 'trail': ['Fiets of wandel de <b>dijkpaden rond Cadzand</b>.', 'Zoek de <b>oude poldernamen</b> op de kaart en in het veld.', 'Combineer met <b>Het Zwin</b> (kaart 2210) als contrast.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Rondes ± 5–15 km · ⚠️ Polderweggetjes smal — verkeer'
}, {
 'tags': ['Zeeland · Cadzand, Retranchement and Terhofstede (gem. Sluis)', '± 906-ha polder landscape from −0.1 to +1.4 m NAP · a conglomerate of small medieval polders — the oldest reclamations of Western Europe, almost entirely washed away in 1530', 'list 83 · no. 4'],
 'loc': '📍 Oudelandse Polder around Cadzand, parts of Retranchement and Terhofstede (NW bordering Het Zwin) — dike paths and polder lanes; drainage canal to the Wielingen; combine with Het Zwin (card 2210)',
 'desc': 'The <b>Oudelandse Polder</b> (± <b>906 hectares</b>, lying between <b>−0.1 and +1.4 metres NAP</b>) near <b>Cadzand</b> is an ancient landscape: a <b>conglomerate of small medieval polders</b> that together form the <b>oldest reclamations of Western Europe</b>. The names on the map betray the age: after the oldest reclamation (Sudhpolra), <b>Kerckpolre and Sudpolre</b> are the oldest preserved names — medieval dikes and ditch patterns that still determine the parcel layout today. In the <b>13th century</b> <b>Cadzand</b> was an island of roughly the present polder’s size; the <b>storm flood of 1530</b> submerged almost the whole area, after which the <b>Noorddijk</b> (≈ the inlay dike of 1531) marked the recovery — north of it the <b>Kievittepolder</b> later arose. The water still takes the old way: via the <b>drainage canal</b> the polder discharges into the <b>Wielingen</b>. Cycle here and you see the past in the small: creek remnants, old dike houses, willows and meadows full of geese in winter — the silence behind the sea dike, where the Zwin (card 2210) provides the revolution of tide and marsh and the Oudelandse Polder the centuries of reclamation.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Oct–Mar</b> (overwintering geese and swans), Apr–May (meadow birds), Jun–Aug (working polder landscape)<br>\n    <b>Best time of day:</b> Evening — light over the old dikes.',
 'why': ['The <b>oldest reclamations of Western Europe</b>.', 'The medieval names <b>Kerckpolre and Sudpolre</b>.', 'The <b>storm flood of 1530</b> and the Noorddijk as inlay dike.', 'The <b>drainage canal to the Wielingen</b>.', 'The <b>13th-century island of Cadzand</b> as primal shape.'],
 'phen': ['<span class="months">Oct–Mar</span> 🪿 <b>Geese and swans</b> on the meadows.', '<span class="months">Apr–May</span> 🎶 <b>Meadow birds</b> over the polder.', '<span class="months">Jun–Aug</span> 🌾 <b>Summer meadows</b> and cows.', '<span class="months">Sep–Oct</span> 🍂 <b>Harvest light</b> over old parcels.'],
 'wild': ['🦆 Polder birds', '🌾 Old parcel layout', '🏛️ Medieval dikes', '💧 Drainage canal', '🤫 Silence behind the sea dike'],
 'trail': ['Cycle or walk the <b>dike paths around Cadzand</b>.', 'Seek the <b>old polder names</b> on map and in the field.', 'Combine with <b>Het Zwin</b> (card 2210) as contrast.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Loops ± 5–15 km · ⚠️ Narrow polder lanes — traffic'
}))

C.append(mk.card(2212, 'Verdronken Zwarte Polder', {
 'tags': ['Zeeland · bij Nieuwvliet-Bad (gem. Sluis)', 'slufter ontstaan door dijkdoorbraak van 1802 · de in 1603 aangelegde Zwarte Polder verdronk en werd natuurgebied — rondwandeling over de Zeedijk, door kreken op plankenpaden en naar het strand', 'list 83 · no. 5'],
 'loc': '📍 Verdronken Zwarte Polder tussen Nieuwvliet-Bad en de zeedijk — rondwandeling Zeedijk → kreken (plankenpaden) → strand; parkeerplaats aan de Zwarte Poldersedijk; buurgebied: Waterdunen (derde slufter, in ontwikkeling)',
 'desc': 'Bij <b>Nieuwvliet-Bad</b> ligt een gebied wiens naam het hele verhaal vertelt: de <b>Verdronken Zwarte Polder</b>. Hier legde men in <b>1603</b> een polder aan — de <b>Zwarte Polder</b>, genoemd naar het zwarte zoute land — maar de zee gaf hem niet permanent terug: bij een <b>dijkdoorbraak in 1802</b> verdron de polder definitief en werd nooit meer ingedijkt. Wat overbleef is een <b>slufter</b>: een brak getijdengebied van <b>kreken, slikken en schorren</b> achter de Zeedijk, dat bij elke vloed zout water binnenlaat — een klein Zwin zonder poorten. De rondwandeling is een klassieker geworden: vanaf de <b>Zeedijk</b> daalt het pad af naar <b>plankenpaden die door en over de kreken</b> voeren, langs zilte vegetatie en zwart hout, om uit te komen op het <b>strand</b> — en vandaar terug over de dijk. In de kreken fourageren steltlopers en eenden; op de schorren groeit zeealsem, lamsoor en zeeweegbree. Wie wil begrijpen hoe Zeeland zijn natuurlandschap te danken heeft aan verlies en herstel, loopt hier in ± 1,5 uur het hele principe: de polder die verdronk werd natuurgebied — en naast de deur groeit de toekomst: <b>Waterdunen</b>, de “derde slufter” die als nieuw natuurgebied (± 250 ha) wordt aangelegd.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–okt</b> (trek en zilte bloei), mrt–mei (steltlopers), jun–aug (warm en licht)<br>\n    <b>Beste tijd van de dag:</b> Rond de hoogwater-wissel — kreken vol, vogels actief.',
 'why': ['De <b>dijkdoorbraak van 1802</b> als geboorte van het gebied.', 'De <b>Zwarte Polder van 1603</b> die verdronk.', 'De <b>plankenpaden door de kreken</b> als unieke wandeling.', 'De <b>zilte vegetatie</b>: lamsoor, zeealsem, zeeweegbree.', 'De <b>aanstaande derde slufter Waterdunen</b> als toekomst.'],
 'phen': ['<span class="months">Mrt–mei</span> 🦆 <b>Steltlopers</b> in de kreken.', '<span class="months">Jun–aug</span> 🌸 <b>Lamsoor en zeealsem</b> in zilte bloei.', '<span class="months">Sep–okt</span> 🕊️ <b>Najaarstrek</b> langs de kust.', '<span class="months">Nov–feb</span> ❄️ <b>Winterse slufterstilte</b> en leeg strand.'],
 'wild': ['🌊 Slufter-kreken', '🌱 Zilte schorvegetatie', '🦆 Steltlopers', '🪵 Plankenpaden', '🏖️ Stranduitgang'],
 'trail': ['Loop de klassieke <b>rondwandeling Zeedijk–kreken–strand</b>.', 'Volg de <b>plankenpaden</b> door het getijdengebied.', 'Kijk over de dijk naar <b>Waterdunen</b>, de nieuwe slufter.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondwandeling ± 5 km · ⚠️ Plankenpaden glad bij nat weer'
}, {
 'tags': ['Zeeland · near Nieuwvliet-Bad (gem. Sluis)', 'slufter born of the 1802 dike breach · the Zwarte Polder laid out in 1603 drowned and became nature — circular walk over the sea dike, through creeks on boardwalks and onto the beach', 'list 83 · no. 5'],
 'loc': '📍 Verdronken Zwarte Polder between Nieuwvliet-Bad and the sea dike — circular walk sea dike → creeks (boardwalks) → beach; car park at the Zwarte Poldersedijk; neighbour: Waterdunen (third slufter, in development)',
 'desc': 'Near <b>Nieuwvliet-Bad</b> lies an area whose name tells the whole story: the <b>Verdronken Zwarte Polder</b> — the Drowned Black Polder. Here a polder was laid out in <b>1603</b> — the <b>Zwarte Polder</b>, named after the black salt land — but the sea did not give it back for good: in a <b>dike breach of 1802</b> the polder drowned for good and was never reclaimed again. What remained is a <b>slufter</b>: a brackish tidal area of <b>creeks, mudflats and marshes</b> behind the sea dike, letting in salt water with every flood — a small Zwin without gates. The circular walk has become a classic: from the <b>sea dike</b> the path descends to <b>boardwalks leading through and across the creeks</b>, past salty vegetation and black wood, to open onto the <b>beach</b> — and back over the dike. In the creeks waders and ducks forage; on the marshes grow sea wormwood, sea lavender and sea plantain. To understand how Zeeland owes its natural landscape to loss and recovery, walk the whole principle here in ± 1.5 hours: the polder that drowned became nature — and next door the future grows: <b>Waterdunen</b>, the “third slufter” being laid out as new nature (± 250 ha).',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Oct</b> (migration and salt bloom), Mar–May (waders), Jun–Aug (warm and light)<br>\n    <b>Best time of day:</b> Around the high-water turn — creeks full, birds active.',
 'why': ['The <b>1802 dike breach</b> as the area’s birth.', 'The <b>Zwarte Polder of 1603</b> that drowned.', 'The <b>boardwalks through the creeks</b> as unique walk.', 'The <b>salty vegetation</b>: sea lavender, wormwood, plantain.', 'The <b>coming third slufter Waterdunen</b> as future.'],
 'phen': ['<span class="months">Mar–May</span> 🦆 <b>Waders</b> in the creeks.', '<span class="months">Jun–Aug</span> 🌸 <b>Sea lavender and wormwood</b> in salt bloom.', '<span class="months">Sep–Oct</span> 🕊️ <b>Autumn migration</b> along the coast.', '<span class="months">Nov–Feb</span> ❄️ <b>Winter slufter silence</b> and empty beach.'],
 'wild': ['🌊 Slufter creeks', '🌱 Salt marsh vegetation', '🦆 Waders', '🪵 Boardwalks', '🏖️ Beach exit'],
 'trail': ['Walk the classic <b>circular route sea dike–creeks–beach</b>.', 'Follow the <b>boardwalks</b> through the tidal area.', 'Look over the dike at <b>Waterdunen</b>, the new slufter.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Circular walk ± 5 km · ⚠️ Boardwalks slippery when wet'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2212)
mk.check()
