# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2228, 'Weel in de Heerenpolder', {
 'tags': ['Zeeland · Heerenpolder bij Wolphaartsdijk (Zuid-Beveland)', 'voormalige getijdengeul, bij de bedijking van 1649 binnendijks geraakt · alleen het westelijke deel is nog open water met rietkragen — zilte invloed in de plantengroei, bruine kiekendief boven de kreekloop', 'list 84 · no. 9'],
 'loc': '📍 Weel in de Heerenpolder, bij Wolphaartsdijk — gebied niet toegankelijk; uitzicht over het weel vanaf de Weeldijk; combineer met Schenge (kaart 2225) en Sabbingedijk (2226); beheer Het Zeeuwse Landschap',
 'desc': 'In de <b>Heerenpolder</b> bij <b>Wolphaartsdijk</b> ligt een stuk water dat zijn vorm aan een verdwenen ritme dankt: het <b>Weel</b> — een <b>voormalige getijdengeul</b> die bij de <b>bedijking van 1649</b> binnen de dijken kwam te liggen en zo van zee-arm tot binnenveld veranderde. De oude <b>kreekloop</b> is in het landschap nog altijd te herkennen aan de <b>laaggelegen graslanden</b> die als een donkere slang door de polder kronkelen; alleen het <b>westelijke deel</b> van de geul is nog <b>open water</b>, omzoomd door <b>rietkragen</b> die hun eigen wereld vormen. De eeuwen na 1649 hebben het zout niet helemaal kunnen wegspoelen: nog steeds is de <b>zilte invloed terug te zien in de plantengroei</b> van de oevers — een erfenis van de tijd dat hier tweemaal per dag de vloed binnenliep. In de rietkragen huizen de moerasvogels: kleine karekiet en rietgors in de zomer, en boven het geheel cirkelt de <b>bruine kiekendief</b>, die deze stille hoek van Zuid-Beveland als jachtgebied gebruikt. Het gebied is niet toegankelijk — maar precies daardoor is het wat het is: een raam van water in een polder, <b>cultuurhistorie van Zuid-Beveland</b> in zijn zuiverste vorm, te overzien vanaf de <b>Weeldijk</b>.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (rietzangers en kiekendief), mrt–mei (weidevogels op de kreekloop-graslanden), okt–mrt (winterse rust)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — kiekendief over het riet.',
 'why': ['De <b>getijdengeul die in 1649 binnendijks raakte</b>.', 'De <b>open water-lichting</b> met rietkragen in het westen.', 'De <b>zilte plantengroei</b> als erfenis van de vloed.', 'De <b>bruine kiekendief</b> als jager boven de kreek.', 'De <b>laaggelegen graslanden</b> als zichtbare kreekloop.'],
 'phen': ['<span class="months">Apr–jun</span> 🎤 <b>Kleine karekiet</b> in de rietkragen.', '<span class="months">Mrt–mei</span> 🎶 <b>Weidevogels</b> op de oude kreekloop.', '<span class="months">Mei–aug</span> 🦅 <b>Bruine kiekendief</b> boven het weel.', '<span class="months">Nov–feb</span> ❄️ <b>Winterstilte</b> over water en riet.'],
 'wild': ['💧 Weel (binnengedijkt water)', '🌿 Zilte oevers', '🎤 Rietvogels', '🦅 Bruine kiekendief', '🏔️ Kreekloop in reliëf'],
 'trail': ['Overzicht vanaf de <b>Weeldijk</b> bij Wolphaartsdijk.', 'Fiets door de <b>Heerenpolder</b> langs de oude kreekloop.', 'Combineer met <b>Schenge</b> (2225) en <b>Sabbingedijk</b> (2226).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Uitzicht vanaf de dijk · ⚠️ Gebied zelf niet toegankelijk'
}, {
 'tags': ['Zeeland · Heerenpolder near Wolphaartsdijk (Zuid-Beveland)', 'former tidal channel, embanked with the 1649 diking · only the western part remains open water with reed collars — saline influence in the vegetation, marsh harrier over the creek course', 'list 84 · no. 9'],
 'loc': '📍 Weel in the Heerenpolder, near Wolphaartsdijk — area not accessible; view over the wheel from the Weeldijk; combine with Schenge (card 2225) and Sabbingedijk (2226); managed by the Zeeland Landscape Trust',
 'desc': 'In the <b>Heerenpolder</b> near <b>Wolphaartsdijk</b> lies a stretch of water that owes its shape to a vanished rhythm: the <b>Weel</b> — a <b>former tidal channel</b> that came inside the dikes with the <b>embankment of 1649</b>, changing from sea arm to inland field. The old <b>creek course</b> can still be read in the landscape in the <b>low-lying grasslands</b> winding through the polder like a dark snake; only the <b>western part</b> of the channel is still <b>open water</b>, fringed by <b>reed collars</b> forming a world of their own. The centuries after 1649 never fully washed out the salt: the <b>saline influence is still visible in the bank vegetation</b> — a legacy of the days when the flood ran in here twice a day. In the reed collars live the marsh birds: sedge warbler and reed bunting in summer, and over it all circles the <b>marsh harrier</b>, using this quiet corner of Zuid-Beveland as hunting ground. The area is not accessible — precisely therefore it is what it is: a window of water in a polder, <b>cultural history of Zuid-Beveland</b> in its purest form, to be surveyed from the <b>Weeldijk</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (reed warblers and harrier), Mar–May (meadow birds on the creek-course grasslands), Oct–Mar (winter calm)<br>\n    <b>Best time of day:</b> Morning — harrier over the reed.',
 'why': ['The <b>tidal channel embanked in 1649</b>.', 'The <b>open-water pane</b> with reed collars in the west.', 'The <b>saline vegetation</b> as legacy of the tide.', 'The <b>marsh harrier</b> hunting over the creek.', 'The <b>low grasslands</b> as visible creek course.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎤 <b>Sedge warbler</b> in the reed collars.', '<span class="months">Mar–May</span> 🎶 <b>Meadow birds</b> on the old creek course.', '<span class="months">May–Aug</span> 🦅 <b>Marsh harrier</b> over the wheel.', '<span class="months">Nov–Feb</span> ❄️ <b>Winter silence</b> over water and reed.'],
 'wild': ['💧 Wheel (embanked water)', '🌿 Saline banks', '🎤 Reed birds', '🦅 Marsh harrier', '🏔️ Creek course in relief'],
 'trail': ['Overview from the <b>Weeldijk</b> near Wolphaartsdijk.', 'Cycle through the <b>Heerenpolder</b> along the old creek course.', 'Combine with <b>Schenge</b> (2225) and <b>Sabbingedijk</b> (2226).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 View from the dike · ⚠️ Area itself not accessible'
}))

C.append(mk.card(2229, 'Deesche Watergang', {
 'tags': ['Zeeland · tussen Goes en Kattendijke (Zuid-Beveland)', 'plas-drasgebied in een verlande kreek · de Wijtvliet of Ee uit de middeleeuwen, omstreeks 1190 bedijkt met de Monnikendijk — kluten, visdieven en de zeldzame graslatyrus in de zilte graslanden', 'list 84 · no. 10'],
 'loc': '📍 Deesche Watergang tussen Goes en Kattendijke — te overzien vanaf de Kattendijksedijk; onderdeel van het oude waterstaatslandschap met de Groote Waterleiding; beheer Staatsbosbeheer',
 'desc': 'Tussen <b>Goes</b> en <b>Kattendijke</b> ligt een water dat ouder is dan de dijken eromheen: de <b>Deesche Watergang</b>, een <b>brakke, verlande kreekrest</b> die teruggaat op de <b>Wijtvliet of Ee</b> — de getijdengeul die hier eeuwenlang het land deelde en waarvan het diepste deel <b>nooit volledig verlandde</b>. Na een middeleeuwse overstroming vatte men de bedijking aan: omstreeks <b>1190</b> werden Kattendijke en omgeving beveiligd met de <b>Monnikendijk</b>, en de kreek werd binnendijks water — een <b>watergang</b> in het afwateringsstelsel dat de polder nog steeds beheerst. De <b>abdij ter Doest</b> had hier al in <b>1214</b> de uithof <b>Monsterhoek</b> (monnikenhoek); de boerderij <b>Monnikenhof</b> herinnert eraan. Vandaag is de Watergang een <b>plas-drasgebied</b>: een schor, een kreekrest met rietranden en natte weiden, waarin ook bij droogte nog water staat — en dat bij <b>hoogwater op zee</b> dient als rustplaats voor vogels die van de schorren verdreven worden. Er broeden <b>kluten, kleine plevieren, tureluurs, visdieven en kokmeeuwen</b>; in de graslanden zingen graspiepers, gele kwikstaarten en veldleeuweriken, en in de rietkragen rietgors en kleine karekiet. Bijzonder is de flora: de <b>zeldzame graslatyrus</b>, massaal rolklaver en op de dijk stinkende ballast — terwijl het schor zich met <b>zeekraal en zilte rus</b> tooit.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–jun</b> (broedvogels), jul–sep (steltlopers en hoogwater-rust), okt–mrt (wintergasten)<br>\n    <b>Beste tijd van de dag:</b> Rond hoogwater — de rustplaats vult zich.',
 'why': ['De <b>Wijtvliet of Ee</b> als middeleeuwse moederkreek.', 'De <b>Monnikendijk van ± 1190</b> als eerste omarming.', 'De <b>uithof Monsterhoek (1214)</b> van de abdij ter Doest.', 'De <b>hoogwater-rustfunctie</b> voor schorvogels.', 'De <b>graslatyrus</b> als zeldzame plant.'],
 'phen': ['<span class="months">Mrt–jun</span> 🥚 <b>Kluten en visdieven</b> op de eilandjes.', '<span class="months">Apr–jun</span> 🎶 <b>Gele kwikstaarten</b> in de weiden.', '<span class="months">Jul–sep</span> 🦆 <b>Steltlopers</b> bij hoogwater-rust.', '<span class="months">Okt–mrt</span> 🪿 <b>Wintergasten</b> op plas en dras.'],
 'wild': ['💧 Verlande kreek', '🐦 Kluten en visdieven', '🌸 Graslatyrus', '🌿 Zeekraal en zilte rus', '⛪ Monnikengeschiedenis'],
 'trail': ['Overzicht vanaf de <b>Kattendijksedijk</b>.', 'Fiets de dijk tussen <b>Goes en Kattendijke</b> langs water en schor.', 'Combineer met het <b>Schelde-landschap</b> van Zuid-Beveland.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Vooral vanaf de dijk · 🔭 Verrekijker nuttig'
}, {
 'tags': ['Zeeland · between Goes and Kattendijke (Zuid-Beveland)', 'splashy-splashy area in a silted creek · the medieval Wijtvliet or Ee, embanked around 1190 with the Monnikendijk — avocets, terns and the rare grass vetchling in the saline grasslands', 'list 84 · no. 10'],
 'loc': '📍 Deesche Watergang between Goes and Kattendijke — to be surveyed from the Kattendijksedijk; part of the old water-management landscape with the Groote Waterleiding; managed by Staatsbosbeheer',
 'desc': 'Between <b>Goes</b> and <b>Kattendijke</b> lies a water older than the dikes around it: the <b>Deesche Watergang</b>, a <b>brackish, silted creek remnant</b> going back to the <b>Wijtvliet or Ee</b> — the tidal channel that divided the land here for centuries and whose deepest part <b>never fully silted up</b>. After a medieval flood the embankment began: around <b>1190</b> Kattendijke and surroundings were protected with the <b>Monnikendijk</b>, and the creek became inland water — a “watergang” in the drainage system that still governs the polder. The <b>Ter Doest abbey</b> already held the grange <b>Monsterhoek</b> (monks’ corner) here in <b>1214</b>; the farm <b>Monnikenhof</b> recalls it. Today the Watergang is a <b>wet splashy area</b>: a marsh, a creek remnant with reed edges and wet meadows holding water even in drought — and serving at <b>high tide at sea</b> as a resting place for birds driven from the outer-dike marshes. <b>Avocets, little ringed plovers, redshanks, common terns and black-headed gulls</b> breed; in the grasslands sing meadow pipits, yellow wagtails and skylarks, and in the reed collars reed bunting and sedge warbler. The flora is special: the <b>rare grass vetchling</b>, masses of bird’s-foot trefoil and, on the dike, black horehound — while the marsh dresses itself in <b>glasswort and salt rush</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jun</b> (breeding birds), Jul–Sep (waders and high-water roost), Oct–Mar (winter guests)<br>\n    <b>Best time of day:</b> Around high water — the roost fills up.',
 'why': ['The <b>Wijtvliet or Ee</b> as medieval mother creek.', 'The <b>Monnikendijk of ± 1190</b> as first embrace.', 'The <b>Monsterhoek grange (1214)</b> of Ter Doest abbey.', 'The <b>high-water roost function</b> for marsh birds.', 'The <b>grass vetchling</b> as rare plant.'],
 'phen': ['<span class="months">Mar–Jun</span> 🥚 <b>Avocets and terns</b> on the islands.', '<span class="months">Apr–Jun</span> 🎶 <b>Yellow wagtails</b> in the meadows.', '<span class="months">Jul–Sep</span> 🦆 <b>Waders</b> at the high-water roost.', '<span class="months">Oct–Mar</span> 🪿 <b>Winter guests</b> on pool and splash.'],
 'wild': ['💧 Silted creek', '🐦 Avocets and terns', '🌸 Grass vetchling', '🌿 Glasswort and salt rush', '⛪ Monk history'],
 'trail': ['Overview from the <b>Kattendijksedijk</b>.', 'Cycle the dike between <b>Goes and Kattendijke</b> past water and marsh.', 'Combine with the <b>Scheldt landscape</b> of Zuid-Beveland.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 Mainly from the dike · 🔭 Binoculars useful'
}))

C.append(mk.card(2230, 'Ter Hooge', {
 'tags': ['Zeeland · direct ten westen van Middelburg (Walcheren)', 'de laatste buitenplaats van Walcheren · ± 25 ha park- en boscomplex rond een kasteel — Engelse landschapsstijl uit de 18e eeuw, na de oorlogsinundatie opnieuw beplant in 1947; meer dan 200 paddenstoelensoorten', 'list 84 · no. 11'],
 'loc': '📍 Landgoed Ter Hooge, Koudekerkseweg, direct ten westen van Middelburg — vrij wandelbaar over onverharde paden; twee routes (parkbos en weidegebied; laarzen aanbevolen voor het laatste); beheer Het Zeeuwse Landschap / Stichting Lynden Ter Hooge',
 'desc': 'Direct ten westen van <b>Middelburg</b> ligt <b>landgoed Ter Hooge</b> — de <b>laatste buitenplaats van Walcheren</b> met alle kenmerken van dien, en bovendien het <b>enige boscomplex in het centrale deel van het eiland</b>. Het hart is het <b>kasteel</b>, in eerste aanleg middeleeuws, met zijn twee ranke achtkantige traptorens; het landgoed bestaat uit ± <b>25 hectare</b> park- en bosgebied, waarvan de <b>parkachtige aanleg in Engelse landschapsstijl</b> uit de tweede helft van de <b>18e eeuw</b> stamt. Tijdens de <b>inundatie van Walcheren in de Tweede Wereldoorlog</b> ging alle beplanting verloren — het huidige bos is in <b>1947</b> ingeplant en bestaat uit <b>eik, es en esdoorn</b>, aangevuld met beuken, tamme kastanjes en lindes, terwijl langs de gazons sierstruiken en exoten staan. Het bos is <b>rijk aan stinzenplanten</b> — gulden boterbloem, voorjaarshelmbloem, aronskelk en stengelloze sleutelbloem, die al in oude documenten over Ter Hooge voorkomen — en opvallend is het grote aantal <b>paddenstoelen: meer dan 200 soorten</b>, waarvan enkele op de Rode Lijst, vooral dankbaar aan het <b>dode hout</b> in het bos. Er broeden ± <b>40 soorten vogels</b>, van staartmees en tuinfluiter tot grote bonte specht — en er is een <b>blauwe reiger-kolonie</b>. Twee routes doorkruisen het gebied: één door het parkbos, één door het omringende weidegebied.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (stinzenplanten), sep–nov (paddenstoelen), apr–jun (zangvogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door eik en es.',
 'why': ['De <b>laatste buitenplaats van Walcheren</b> met kasteel.', 'Het <b>enige boscomplex van centraal Walcheren</b>.', 'De <b>Engelse landschapsstijl</b> van de 18e eeuw.', 'De <b>stinzenplanten</b> uit oude documenten.', 'De <b>200+ paddenstoelensoorten</b> op dood hout.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Stinzenplanten</b> in het parkbos.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> rond kasteel en gazons.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelentijd</b> op dood hout.', '<span class="months">Dec–feb</span> ❄️ <b>Winterbos</b> en blauwe reigers op het nest.'],
 'wild': ['🏡 Buitenplaats met kasteel', '🌳 Parkbos', '🌷 Stinzenplanten', '🍄 200+ paddenstoelen', '🐦 Blauwe reiger-kolonie'],
 'trail': ['Wandel de <b>parkbos-route</b> over de onverharde paden.', 'Neem de <b>weidegebied-route</b> (laarzen aanbevolen).', 'Combineer met <b>Middelburg</b> en de Graslanden Oude Veerseweg (2221).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes ± 2–5 km · 🅿️ Parkeren aan de Koudekerkseweg'
}, {
 'tags': ['Zeeland · directly west of Middelburg (Walcheren)', 'the last country seat of Walcheren · ± 25-ha park and wood complex around a castle — English landscape style from the 18th century, replanted in 1947 after the wartime inundation; more than 200 fungus species', 'list 84 · no. 11'],
 'loc': '📍 Ter Hooge estate, Koudekerkseweg, directly west of Middelburg — free walking on unpaved paths; two routes (park wood and meadow area; boots recommended for the latter); managed by the Zeeland Landscape Trust / Lynden Ter Hooge Foundation',
 'desc': 'Directly west of <b>Middelburg</b> lies <b>Ter Hooge estate</b> — the <b>last country seat of Walcheren</b> with all its classic features, and moreover the <b>only woodland complex in the island’s central part</b>. The heart is the <b>castle</b>, medieval in its first outline, with its two slender octagonal corner turrets; the estate comprises ± <b>25 hectares</b> of park and woodland, whose <b>park-like layout in English landscape style</b> dates from the second half of the <b>18th century</b>. During the <b>wartime inundation of Walcheren</b> all planting was lost — the present wood was planted in <b>1947</b> and consists of <b>oak, ash and maple</b>, supplemented with beeches, sweet chestnuts and limes, while ornamental shrubs and exotics line the lawns. The wood is <b>rich in stinsen plants</b> — lesser celandine, hollowroot, lords-and-ladies and primrose, already appearing in old documents about Ter Hooge — and remarkable is the great number of <b>fungi: more than 200 species</b>, several on the Red List, especially grateful for the <b>dead wood</b> in the forest. Around <b>40 bird species</b> breed, from long-tailed tit and garden warbler to great spotted woodpecker — and there is a <b>grey heron colony</b>. Two routes cross the area: one through the park wood, one through the surrounding meadows.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (stinsen plants), Sep–Nov (fungi), Apr–Jun (songbirds)<br>\n    <b>Best time of day:</b> Morning — light through oak and ash.',
 'why': ['The <b>last country seat of Walcheren</b> with its castle.', 'The <b>only woodland complex of central Walcheren</b>.', 'The <b>18th-century English landscape style</b>.', 'The <b>stinsen plants</b> from old documents.', 'The <b>200+ fungus species</b> on dead wood.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Stinsen plants</b> in the park wood.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> around castle and lawns.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungus season</b> on dead wood.', '<span class="months">Dec–Feb</span> ❄️ <b>Winter wood</b> and grey herons on the nest.'],
 'wild': ['🏡 Country seat with castle', '🌳 Park wood', '🌷 Stinsen plants', '🍄 200+ fungi', '🐦 Grey heron colony'],
 'trail': ['Walk the <b>park-wood route</b> on the unpaved paths.', 'Take the <b>meadow route</b> (boots recommended).', 'Combine with <b>Middelburg</b> and the Oude Veerseweg grasslands (2221).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes ± 2–5 km · 🅿️ Parking at the Koudekerkseweg'
}))

C.append(mk.card(2231, 'Dijkbeemden Walcheren', {
 'tags': ['Zeeland · verspreid langs de oude binnendijken van Walcheren', 'natte hooilanden (beemden) achter de Walcherse dijken · bloemrijk beemdland op moernerings- en kwelgrond — weidevogels, zilte randjes en de kleinschaligheid van het oude Walcheren', 'list 84 · no. 12'],
 'loc': '📍 Dijkbeemden langs de oude binnendijken van Walcheren (rond Arnemuiden, de Oranjepolder en de polders bij Sint-Laurens) — te verkennen per fiets langs de dijkweggetjes; combineer met het Heggengebied Arnemuiden (kaart 2223)',
 'desc': 'Achter de oude <b>binnendijken van Walcheren</b> ligt een landschapstype dat je op de kaart niet vindt, maar in het veld meteen herkent: de <b>beemden</b> — natte, bloemrijke <b>hooilanden</b> die eeuwenlang het ideale midden hielden tussen te nat en te waardevol. Walcheren was er ooit vol van: een mozaïek van kleine percelen, gescheiden door <b>dijkjes, hagen en sloten</b>, waarin het water — gevoed door <b>kwel</b> en de sporen van eeuwen <b>moernering</b> — het hele jaar dicht onder de oppervlakte bleef. De ruilverkaveling maakte daar korte metten mee; wat bleef zijn de randjes, en juist die randjes vormen vandaag de <b>dijkbeemden van Walcheren</b>: percelen die te nat bleven voor intensief gebruik en daardoor hun <b>hooilandkarakter</b> behielden — en met het karakter de bewoners: <b>kievit en tureluur</b> in het vroege voorjaar, <b>graspieper en gele kwikstaart</b> langs de randen, en in de natste veentjes de planten van zure en zilte plekjes. In mei kleuren de beemden <b>paars en geel</b> — echte hooilandbloei, die nergens anders op het eiland nog zo samenkomt. Wie ze zoekt, volgt de oude dijkweggetjes: achter elke bocht een perceel, achter elk perceel een andere dijk — kleinschaligheid als landschapswet.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (weidevogels), mei–jun (hooilandbloei), sep (natte herfst van de beemden)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en zang.',
 'why': ['De <b>beemd</b> als historisch landschapstype van Walcheren.', 'De <b>kwel en moernering</b> als bodem-oorzaak.', 'De <b>hooilandbloei</b> in paars en geel.', 'De <b>weidevogels</b> van de natte percelen.', 'De <b>randjes</b> die de ruilverkaveling overleefden.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Kievit en tureluur</b> op de natte percelen.', '<span class="months">Mei–jun</span> 🌸 <b>Hooilandbloei</b> in volle glorie.', '<span class="months">Jun–aug</span> 🦋 <b>Vlinders</b> langs bloemrijke randen.', '<span class="months">Sep–okt</span> 💧 <b>Herfstnat</b> en zwartgeblakerde slootkanten.'],
 'wild': ['🌾 Natte hooilanden', '💧 Kwel en moernering', '🐦 Weidevogels', '🌸 Hooilandflora', '🌳 Dijkjes en hagen'],
 'trail': ['Fiets de <b>oude dijkweggetjes</b> van Walcheren langs de beemden.', 'Zoek de <b>natste percelen</b> achter de dijken.', 'Combineer met het <b>Heggengebied Arnemuiden</b> (2223).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Dijkroutes ± 4–10 km · ⚠️ Nat — laarzen aanbevolen'
}, {
 'tags': ['Zeeland · scattered along the old inner dikes of Walcheren', 'wet hay meadows (“beemden”) behind the Walcheren dikes · flower-rich meadow land on peat-digging and seepage ground — meadow birds, salty edges and the small scale of old Walcheren', 'list 84 · no. 12'],
 'loc': '📍 Dike meadows along the old inner dikes of Walcheren (around Arnemuiden, the Oranjepolder and the polders near Sint-Laurens) — to explore by bike along the little dike roads; combine with the Arnemuiden hedge area (card 2223)',
 'desc': 'Behind the <b>old inner dikes of Walcheren</b> lies a landscape type you will not find on the map but recognise instantly in the field: the <b>beemden</b> — wet, flower-rich <b>hay meadows</b> that for centuries held the perfect middle between too wet and too valuable. Walcheren was once full of them: a mosaic of small parcels, separated by <b>little dikes, hedges and ditches</b>, where the water — fed by <b>seepage</b> and the traces of centuries of <b>peat digging</b> — stayed close beneath the surface all year. Land consolidation dealt with them summarily; what remained are the edges, and precisely those edges form today’s <b>dike meadows of Walcheren</b>: parcels that stayed too wet for intensive use and therefore kept their <b>hay-meadow character</b> — and with the character the inhabitants: <b>lapwing and redshank</b> in early spring, <b>meadow pipit and yellow wagtail</b> along the edges, and in the wettest hollows the plants of acid and salty spots. In May the meadows colour <b>purple and yellow</b> — true hay-meadow bloom, found nowhere else on the island so concentrated. To find them, follow the old dike roads: behind every bend a parcel, behind every parcel another dike — small scale as landscape law.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (meadow birds), May–Jun (hay-meadow bloom), Sep (the wet autumn of the meadows)<br>\n    <b>Best time of day:</b> Morning — dew and song.',
 'why': ['The <b>beemd</b> as historic landscape type of Walcheren.', 'The <b>seepage and peat digging</b> as soil cause.', 'The <b>hay-meadow bloom</b> in purple and yellow.', 'The <b>meadow birds</b> of the wet parcels.', 'The <b>edges</b> that survived land consolidation.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Lapwing and redshank</b> on the wet parcels.', '<span class="months">May–Jun</span> 🌸 <b>Hay-meadow bloom</b> in full glory.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> along flowery edges.', '<span class="months">Sep–Oct</span> 💧 <b>Autumn wet</b> and blackened ditch sides.'],
 'wild': ['🌾 Wet hay meadows', '💧 Seepage and peat digging', '🐦 Meadow birds', '🌸 Hay-meadow flora', '🌳 Dikes and hedges'],
 'trail': ['Cycle the <b>old dike roads</b> of Walcheren past the meadows.', 'Seek the <b>wettest parcels</b> behind the dikes.', 'Combine with the <b>Arnemuiden hedge area</b> (2223).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Dike routes ± 4–10 km · ⚠️ Wet — boots recommended'
}))

C.append(mk.card(2232, 'Rammekens', {
 'tags': ['Zeeland · bij Ritthem, aan de Westerschelde (zuidkust van Walcheren)', 'fort Rammekens (1547) — het oudste zeefort van Noordwest-Europa — met het Rammekenshoek-landschap · kreken uit 1944, het enige schor van Walcheren, zilte slufterplanten en muurplanten op de vesting', 'list 84 · no. 13'],
 'loc': '📍 Fort Rammekens en Rammekenshoek, Rammekensweg bij Ritthem — parkeerplaats bij het fort; wandelen over de wallen en langs de kreken richting Westerschelde; combineer met Vlissingen (15 min)',
 'desc': 'Op de zuidpunt van <b>Walcheren</b>, waar de Westerschelde het eiland raakt, staat een fort dat de geschiedenis van Europa in zijn muren draagt: <b>Fort Rammekens</b>, gebouwd <b>tussen 1547 en 1557</b> door <b>Italiaanse bouwmeesters</b> in opdracht van keizer Karel V — en sindsdien het <b>oudste zeefort van Noordwest-Europa</b>. Het moest de havens van <b>Middelburg en Antwerpen</b> beschermen en diende later als ankerplaats voor <b>VOC-schepen</b>; binnen de metersdikke muren lieten Spaanse musketiers, watergeuzen, VOC-kooplieden, Franse fusiliers en Duitse soldaten hun sporen na. Napoleon voorzag het fort in 1810 van kazematten; vandaag is het een rijksmonument, gedeeltelijk vervallen en juist daardoor imposant. Rond het fort ligt <b>Rammekenshoek</b>: de <b>kreken</b> in het gebied zijn ontstaan door de <b>oorlogshandelingen van eind 1944</b> — bommen en inundatie die het land openscheurden en aan de natuur teruggaben. Buitendijks ligt het <b>(nog) enige schor van Walcheren</b>; in het duin met de slufter groeien <b>zeekraal, schorrenkruid en Engels slijkgras</b>, in het duindoornstruweel broeden grasmus en braamsluiper en is het <b>kneutje</b> talrijk. Op de oude muren groeien <b>gevarieerde muurplanten</b>, en het gebied is bovendien rijk aan <b>paddenstoelen</b> — rode kelkzwam, voorjaarspronkridder en vingerhoedje. Een plek van stilte aan een dynamische, industriële riviermonding.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (muurplanten en broedvogels), jul–sep (zilte bloei op het schor), sep–nov (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Avond — licht op fort en schor, schepen op de Schelde.',
 'why': ['Het <b>oudste zeefort van Noordwest-Europa (1547–1557)</b>.', 'De <b>VOC-ankerplaats</b> en de sporen van vier eeuwen soldaten.', 'De <b>kreken van 1944</b> als oorlogs-erfgoed.', 'Het <b>enige schor van Walcheren</b>.', 'De <b>zilte slufter en de muurplanten</b> op de vesting.'],
 'phen': ['<span class="months">Apr–jun</span> 🌸 <b>Muurplanten</b> op fort en wallen.', '<span class="months">Apr–jul</span> 🎶 <b>Braamsluiper en kneu</b> in het struweel.', '<span class="months">Jul–sep</span> 🌿 <b>Zeekraal en slijkgras</b> op schor en slufter.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> rond muren en bomen.'],
 'wild': ['🏰 Zeefort 1547', '🌊 Schor van Walcheren', '💧 Kreken van 1944', '🌿 Zilte slufterplanten', '🍄 Rode kelkzwam'],
 'trail': ['Bezoek <b>Fort Rammekens</b> en loop over de wallen.', 'Wandel langs de <b>kreken van Rammekenshoek</b> naar de Schelde.', 'Combineer met <b>Vlissingen</b> en de Westerschelde-dijk.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis (fort tegen betaling bij evenementen) · 🚶 Rondes ± 2–5 km · 🅿️ Parkeerplaats bij het fort'
}, {
 'tags': ['Zeeland · near Ritthem, on the Westerschelde (south coast of Walcheren)', 'Fort Rammekens (1547) — the oldest sea fort of Northwest Europe — with the Rammekenshoek landscape · creeks from 1944, Walcheren’s only salt marsh, saline slufter plants and wall plants on the fortress', 'list 84 · no. 13'],
 'loc': '📍 Fort Rammekens and Rammekenshoek, Rammekensweg near Ritthem — car park at the fort; walking over the ramparts and along the creeks towards the Westerschelde; combine with Vlissingen (15 min)',
 'desc': 'On the southern tip of <b>Walcheren</b>, where the Westerschelde touches the island, stands a fort carrying Europe’s history in its walls: <b>Fort Rammekens</b>, built <b>between 1547 and 1557</b> by <b>Italian master builders</b> on orders of Emperor Charles V — and ever since the <b>oldest sea fort of Northwest Europe</b>. It was to protect the harbours of <b>Middelburg and Antwerp</b> and later served as anchorage for <b>VOC ships</b>; within the metres-thick walls Spanish musketeers, Sea Beggars, VOC merchants, French fusiliers and German soldiers left their traces. Napoleon gave the fort casemates in 1810; today it is a national monument, partly decayed and precisely therefore imposing. Around the fort lies <b>Rammekenshoek</b>: the <b>creeks</b> in the area arose from the <b>warfare of late 1944</b> — bombs and inundation that tore the land open and gave it back to nature. Outside the dike lies <b>Walcheren’s (still) only salt marsh</b>; in the dune with the slufter grow <b>glasswort, saltmarsh grass and English scurvygrass</b>, in the sea-buckthorn scrub whitethroat and lesser whitethroat breed and the <b>linnet</b> is numerous. On the old walls grow <b>varied wall plants</b>, and the area is also rich in <b>fungi</b> — scarlet cup, spring trumpet and (finger-shaped) clitocybe. A place of silence on a dynamic, industrial river mouth.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (wall plants and breeding birds), Jul–Sep (saline bloom on the marsh), Sep–Nov (fungi)<br>\n    <b>Best time of day:</b> Evening — light on fort and marsh, ships on the Scheldt.',
 'why': ['The <b>oldest sea fort of Northwest Europe (1547–1557)</b>.', 'The <b>VOC anchorage</b> and traces of four centuries of soldiers.', 'The <b>creeks of 1944</b> as war heritage.', '<b>Walcheren’s only salt marsh</b>.', 'The <b>saline slufter and wall plants</b> on the fortress.'],
 'phen': ['<span class="months">Apr–Jun</span> 🌸 <b>Wall plants</b> on fort and ramparts.', '<span class="months">Apr–Jul</span> 🎶 <b>Lesser whitethroat and linnet</b> in the scrub.', '<span class="months">Jul–Sep</span> 🌿 <b>Glasswort and scurvygrass</b> on marsh and slufter.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> around walls and trees.'],
 'wild': ['🏰 Sea fort 1547', '🌊 Walcheren’s marsh', '💧 Creeks of 1944', '🌿 Saline slufter plants', '🍄 Scarlet cup fungus'],
 'trail': ['Visit <b>Fort Rammekens</b> and walk the ramparts.', 'Walk along the <b>creeks of Rammekenshoek</b> to the Scheldt.', 'Combine with <b>Vlissingen</b> and the Westerschelde dike.'],
 'foot': '🐕 Dogs on lead · 💶 Free (fort for a fee at events) · 🚶 Loops ± 2–5 km · 🅿️ Car park at the fort'
}))

mk.insert(C, chunk='reserves-2135-2234.json')
mk.progress(2232)
mk.check()
