# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2238, 'Akerwegje, Grenslinde en Meidoornhaag', {
 'tags': ['Zeeland · de Zak van Zuid-Beveland (bloemdijkjes-landschap rond Heinkenszand en Nisse)', 'de kleine elementen van het oude Zuid-Beveland · smalle akkerwegjes, eeuwenoude grenslinden (± 100 in de Zak) en meidoornhagen — linden die eigendomsgrenzen markeerden en als beschermers van geluk golden', 'list 84 · no. 19'],
 'loc': '📍 Akerwegjes, grenslinden en meidoornhagen in de Zak van Zuid-Beveland — te zien langs de bloemdijken en de Grote Dijk bij Heinkenszand (grenslinde op de kruising met de Westhofsezandweg) en de Sint-Pieterdijk; wandelroute “over de bloemdijken” van Natuurmonumenten voert erlangs',
 'desc': 'Wie door de <b>Zak van Zuid-Beveland</b> fietst, ziet ze overal: de kleine elementen die het oude Zuid-Beveland samenstellen — smalle <b>akerwegjes</b> (akkerweggetjes tussen de percelen), oude <b>meidoornhagen</b> en, op de meest markante plekken, de <b>grenslinden</b>. Zeeland staat niet bekend om oude of hoge bomen — zeewind, inundaties en de stookbehoefte van de oorlogsjaren zorgden daarvoor — en juist daarom zijn de ± <b>100 oude linden van de Zak</b> zo opmerkelijk. De oorspronkelijke <b>“Vier Linden”</b>, die de grens tussen Kloetinge en ’s-Gravenpolder markeerden, lijken naamgever van het fenomeen; waarschijnlijk wezen de bomen lang niet altijd grenzen aan, maar werden ze vooral op <b>markante locaties</b> aangeplant — als eigendomsgrens van een ambachtsheerlijkheid, als herinnering aan een <b>dijkdoorbraak</b>, of vanwege de bescherming die ze zouden bieden. De linde stond voor <b>geluk en huiselijke vrede</b>: er werden vroeger <b>huwelijken onder gesloten</b>. Dat de linde beter dan de meeste bomen tegen wind kan, heeft zeker meegespeeld. Samen met de <b>meidoornhagen</b> — in mei wit, in de herfst vol bessen — vormen de grenslinden de verticale tekens in het Zuid-Bevelandse kleinschalige landschap: klein natuur, maar met een geschiedenis die tot in de middeleeuwen reikt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei</b> (meidoornbloei), jun–jul (lindebloei en bijen), sep–okt (bessen en zacht licht)<br>\n    <b>Beste tijd van de dag:</b> Middag — zon op de dijkjes en hagen.',
 'why': ['De <b>± 100 oude grenslinden</b> van de Zak.', 'De <b>“Vier Linden”</b> als oorsprong van het fenomeen.', 'De <b>huwelijkstraditie</b> onder de linde.', 'De <b>meidoornhagen</b> als seizoenskleur.', 'De <b>akerwegjes</b> als aders van het oude landschap.'],
 'phen': ['<span class="months">Mei</span> 🌸 <b>Meidoornhagen</b> wit in bloei.', '<span class="months">Jun–jul</span> 🐝 <b>Lindebloei</b> vol bijen en hommels.', '<span class="months">Sep–okt</span> 🍒 <b>Bessen</b> in de hagen voor trekvogels.', '<span class="months">Nov–feb</span> 🌳 <b>Kale linden</b> als silhouet op de dijk.'],
 'wild': ['🌳 Grenslinden', '🌸 Meidoornhagen', '🛤️ Akerwegjes', '🐝 Lindebloei-bijen', '💍 Huwelijkslinde-traditie'],
 'trail': ['Zoek de <b>grenslinden</b> op de Grote Dijk en Sint-Pieterdijk.', 'Loop de <b>wandelroute over de bloemdijken</b> van Natuurmonumenten.', 'Fiets de <b>akerwegjes</b> tussen Heinkenszand en Nisse.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Dijkjes ± 3–8 km · ⚠️ Smalle wegjes — uitkijken naar verkeer'
}, {
 'tags': ['Zeeland · the Zak van Zuid-Beveland (flower-dike landscape around Heinkenszand and Nisse)', 'the small elements of old Zuid-Beveland · narrow field lanes, centuries-old boundary limes (± 100 in the Zak) and hawthorn hedges — limes marking property borders and held as protectors of happiness', 'list 84 · no. 19'],
 'loc': '📍 Field lanes, boundary limes and hawthorn hedges in the Zak van Zuid-Beveland — to be seen along the flower dikes and the Grote Dijk at Heinkenszand (boundary lime at the crossing with the Westhofsezandweg) and the Sint-Pieterdijk; the Nature Trust walk “over the bloemdijken” passes them',
 'desc': 'Cycle through the <b>Zak van Zuid-Beveland</b> and you see them everywhere: the small elements composing old Zuid-Beveland — narrow <b>field lanes</b> between the parcels, old <b>hawthorn hedges</b> and, at the most striking spots, the <b>boundary limes</b>. Zeeland is not known for old or tall trees — sea wind, inundations and the fuel needs of the war years saw to that — which makes the ± <b>100 old limes of the Zak</b> all the more remarkable. The original <b>“Vier Linden”</b> (Four Limes), marking the border between Kloetinge and ’s-Gravenpolder, seem to have named the phenomenon; likely the trees did not always mark borders, but were planted chiefly at <b>striking locations</b> — as property line of a lordship, as memory of a <b>dike breach</b>, or for the protection they were believed to give. The lime stood for <b>luck and domestic peace</b>: <b>weddings</b> were once held beneath it. That the lime withstands wind better than most trees surely played a part too. Together with the <b>hawthorn hedges</b> — white in May, full of berries in autumn — the boundary limes form the vertical signs in Zuid-Beveland’s small-scale landscape: small nature, but with a history reaching into the Middle Ages.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May</b> (hawthorn bloom), Jun–Jul (lime bloom and bees), Sep–Oct (berries and soft light)<br>\n    <b>Best time of day:</b> Midday — sun on the dikes and hedges.',
 'why': ['The <b>± 100 old boundary limes</b> of the Zak.', 'The <b>“Vier Linden”</b> as origin of the phenomenon.', 'The <b>wedding tradition</b> under the lime.', 'The <b>hawthorn hedges</b> as seasonal colour.', 'The <b>field lanes</b> as arteries of the old landscape.'],
 'phen': ['<span class="months">May</span> 🌸 <b>Hawthorn hedges</b> white in bloom.', '<span class="months">Jun–Jul</span> 🐝 <b>Lime bloom</b> full of bees.', '<span class="months">Sep–Oct</span> 🍒 <b>Berries</b> in the hedges for migrants.', '<span class="months">Nov–Feb</span> 🌳 <b>Bare limes</b> as silhouettes on the dike.'],
 'wild': ['🌳 Boundary limes', '🌸 Hawthorn hedges', '🛤️ Field lanes', '🐝 Lime-bloom bees', '💍 Wedding-lime tradition'],
 'trail': ['Seek the <b>boundary limes</b> on the Grote Dijk and Sint-Pieterdijk.', 'Walk the Nature Trust route <b>over the flower dikes</b>.', 'Cycle the <b>field lanes</b> between Heinkenszand and Nisse.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Dikes ± 3–8 km · ⚠️ Narrow lanes — mind traffic'
}))

C.append(mk.card(2239, 'Jachtse Bos', {
 'tags': ['Zeeland · bij Kapelle/Kloetinge (Zuid-Beveland)', 'bospartij van ± 10 ha, mogelijk restant van een buitenplaats-bos · hoge populieren met beuk, iep, es en esdoorn — bekend om zijn vele paddenstoelen; groene en grote bonte specht, boomvalk en ree', 'list 84 · no. 20'],
 'loc': '📍 Jachtse Bos (Jagtsebos) tussen Kloetinge en Kapelle — paadjes door het bos, midden tussen akkers en fruitboomgaarden; combineer met de bloemdijken (2233) en Zwaakse Weel (2241); beheer Staatsbosbeheer',
 'desc': 'Tussen <b>Kloetinge</b> en <b>Kapelle</b>, midden tussen de akkers en fruitboomgaarden van het Zuid-Bevelandse platteland, ligt een bos dat er altijd al had kunnen staan: het <b>Jachtse Bos</b>, mogelijk het <b>overblijfsel van een bospartij bij een buitenplaats</b> — het jachtbos van een voormalig landgoed. Het is een aantrekkelijk wandelgebied dat bestaat uit <b>hoge populieren</b>, afgewisseld met <b>beuk, iep, es en esdoorn</b>, met flink uit de kluiten gewassen <b>meidoorns</b> en vlier als ondergroei. Langs de paden groeien <b>fluitekruid, speenkruid, nagelkruid en penningkruid</b> — het voorjaarskleed van een oud bos op rijke grond. Het bos staat bovendien <b>bekend om zijn vele soorten paddenstoelen</b>, die in het najaar op dood hout en oude boomvoeten verschijnen. In de toppen broeden <b>groene en grote bonte specht</b>; de <b>boomvalk</b> jaagt boven de kruinen, en zwartkop, tuinfluiter, roodborst en lijsters vullen het koor. Zo nu en dan steekt een <b>ree</b> het bos over, en de <b>haas</b> komt vanaf de omringende polders regelmatig langs de bosrand grazen. Klein bos, grote stilte — en in april, wanneer de fruitbomen rondom bloeien, het mooiste decor van Zuid-Beveland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (voorjaarsflora en -vogels), apr (fruitboomgaarden rondom), sep–nov (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door de populieren.',
 'why': ['Het <b>mogelijke buitenplaats-bos</b> als oorsprong.', 'De <b>hoge populieren</b> met beuk, iep, es en esdoorn.', 'De <b>vele paddenstoelensoorten</b> in het najaar.', 'De <b>groene specht en boomvalk</b> als broedvogels.', 'De <b>ligging tussen fruitboomgaarden</b>.'],
 'phen': ['<span class="months">Mrt–apr</span> 🌷 <b>Speenkruid en fluitekruid</b> langs de paden.', '<span class="months">Apr–mei</span> 🎶 <b>Spechten en zangvogels</b> in broedtijd.', '<span class="months">Apr</span> 🌸 <b>Fruitboomgaarden</b> in bloei rondom.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> op hout en boomvoeten.'],
 'wild': ['🌲 Oud bosrestant', '🍄 Paddenstoelenrijk', '🦅 Boomvalk', '🐦 Groene specht', '🦌 Ree en haas'],
 'trail': ['Wandel de <b>paadjes door het Jachtse Bos</b>.', 'Combineer met de <b>fruitboomgaard-routes</b> van Kapelle.', 'Sluit aan op de <b>bloemdijken</b> (2233) en <b>Zwaakse Weel</b> (2241).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 2–4 km · 🅿️ Parkeren aan de bosrand bij Kloetinge/Kapelle'
}, {
 'tags': ['Zeeland · near Kapelle/Kloetinge (Zuid-Beveland)', '± 10-ha wood, possibly remnant of a country-seat wood · tall poplars with beech, elm, ash and maple — known for its many fungi; green and great spotted woodpecker, hobby and roe deer', 'list 84 · no. 20'],
 'loc': '📍 Jachtse Bos (Jagtsebos) between Kloetinge and Kapelle — paths through the wood, amid fields and orchards; combine with the flower dikes (2233) and Zwaakse Weel (2241); managed by Staatsbosbeheer',
 'desc': 'Between <b>Kloetinge</b> and <b>Kapelle</b>, amid the fields and orchards of the Zuid-Beveland countryside, lies a wood that looks as if it has always been there: the <b>Jachtse Bos</b>, possibly the <b>remnant of the wood of a country seat</b> — the chase wood of a former estate. It is an attractive walking area consisting of <b>tall poplars</b>, alternating with <b>beech, elm, ash and maple</b>, with stoutly grown <b>hawthorns</b> and elder as undergrowth. Along the paths grow <b>cow parsley, lesser celandine, herb bennet and pennywort</b> — the spring dress of an old wood on rich soil. The wood is moreover <b>known for its many fungus species</b>, appearing in autumn on dead wood and old tree feet. In the crowns breed <b>green and great spotted woodpecker</b>; the <b>hobby</b> hunts above the tops, and blackcap, garden warbler, robin and thrushes fill the chorus. Now and then a <b>roe deer</b> crosses the wood, and the <b>brown hare</b> regularly grazes the wood edge from the surrounding polders. Small wood, great silence — and in April, when the orchards around bloom, Zuid-Beveland’s finest decor.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (spring flora and birds), Apr (orchards around in bloom), Sep–Nov (fungi)<br>\n    <b>Best time of day:</b> Morning — light through the poplars.',
 'why': ['The <b>possible country-seat wood</b> as origin.', 'The <b>tall poplars</b> with beech, elm, ash and maple.', 'The <b>many fungus species</b> in autumn.', 'The <b>green woodpecker and hobby</b> as breeders.', 'The <b>position among orchards</b>.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌷 <b>Lesser celandine and cow parsley</b> along the paths.', '<span class="months">Apr–May</span> 🎶 <b>Woodpeckers and songbirds</b> in breeding time.', '<span class="months">Apr</span> 🌸 <b>Orchards</b> in bloom around.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> on wood and tree feet.'],
 'wild': ['🌲 Old wood remnant', '🍄 Fungus-rich', '🦅 Hobby', '🐦 Green woodpecker', '🦌 Roe deer and hare'],
 'trail': ['Walk the <b>paths through the Jachtse Bos</b>.', 'Combine with the <b>orchard routes</b> of Kapelle.', 'Link up with the <b>flower dikes</b> (2233) and <b>Zwaakse Weel</b> (2241).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 2–4 km · 🅿️ Parking at the wood edge near Kloetinge/Kapelle'
}))

C.append(mk.card(2240, 'Landlust', {
 'tags': ['Zeeland · midden in Heinkenszand (Zuid-Beveland)', 'historische buitenplaats van ± 3 ha (gebouwen ± 1800) · parkbos met monumentale bomen, ronde waterpartij en stinzenplanten — lenteklokje, daslook en voorjaarszonnebloem; boomkruiper en ransuil', 'list 84 · no. 21'],
 'loc': '📍 Landgoed Landlust, ingang Eendvogelstraat, midden in Heinkenszand — vrij toegankelijk via onverharde paden (geen gemarkeerde route); parkeren in de Eendvogelstraat; beheer Het Zeeuwse Landschap',
 'desc': 'Midden in de dorpskern van <b>Heinkenszand</b> ligt een groen geheim: <b>landgoed Landlust</b>, een <b>historische buitenplaats</b> van ± <b>3 hectare</b> waarvan de gebouwen rond <b>1800</b> werden opgetrokken — de nabije ligweide en het buitenhuis zijn <b>rijksmonument</b>. Het landgoed ligt op een deel van de <b>zandrug</b> waarop ook het dorp zelf is gebouwd; de natuur heeft een uitgesproken <b>parkachtig karakter</b> met gazons, een <b>ronde waterpartij</b>, struiken en loofbos. Het westelijke deel bestaat uit een natuurlijk bostype met veel <b>eik, beuk, esdoorn en iep</b>; in het oostelijke deel staan veel <b>niet-inheemse boom- en struiksoorten</b> — de collectie van een buitenplaats. Op Landlust staan <b>oude monumentale bomen die uniek zijn voor Zuid-Beveland</b>, en op de bosbodem gedijen <b>stinzenplanten</b>: <b>lenteklokje, daslook, gevlekte aronskelk en voorjaarszonnebloem</b> — het voorjaar begint hier eerder dan waar ook in de streek. Het bos is rijk aan vogels: <b>grote bonte specht, ransuil, boomkruiper</b> en zwartkop broeden er, en in de schemering zijn de oude bomen een veilige slaapplaats. Vrij toegankelijk, onverharde paden, geen bordjes: een landgoed dat zich laat vinden door wie de Eendvogelstraat inslaat.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (stinzenplanten), apr–jun (bosvogels), sep–nov (paddenstoelen en oud blad)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — daslookgeur en zang.',
 'why': ['De <b>buitenplaats van ± 1800</b> midden in het dorp.', 'De <b>monumentale bomen</b>, uniek voor Zuid-Beveland.', 'De <b>stinzenplanten</b>: lenteklokje, daslook, aronskelk.', 'De <b>ronde waterpartij</b> in het park.', 'De <b>boomkruiper en ransuil</b> als bewoners.'],
 'phen': ['<span class="months">Mrt–apr</span> 🌷 <b>Lenteklokje en daslook</b> in bloei.', '<span class="months">Apr–mei</span> 🎶 <b>Boomkruiper en specht</b> in broedtijd.', '<span class="months">Mei–jun</span> 🌻 <b>Voorjaarszonnebloem</b> op de bosbodem.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> bij oude bomen.'],
 'wild': ['🏡 Buitenplaats ± 1800', '🌳 Monumentale bomen', '🌷 Stinzenplanten', '💧 Ronde waterpartij', '🐦 Boomkruiper'],
 'trail': ['Ga de <b>Eendvogelstraat</b> in naar de ingang van Landlust.', 'Wandel de <b>onverharde paden</b> door park en bos.', 'Combineer met de <b>bloemdijken</b> (2233) en <b>Zwaakse Weel</b> (2241).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Padennetwerk ± 1–2 km · 🅿️ Parkeren in de Eendvogelstraat'
}, {
 'tags': ['Zeeland · in the middle of Heinkenszand (Zuid-Beveland)', 'historic country seat of ± 3 ha (buildings ± 1800) · park wood with monumental trees, round pond and stinsen plants — spring snowflake, wild garlic and leopard’s bane; treecreeper and long-eared owl', 'list 84 · no. 21'],
 'loc': '📍 Landlust estate, entrance Eendvogelstraat, in the middle of Heinkenszand — freely accessible via unpaved paths (no marked route); parking in the Eendvogelstraat; managed by the Zeeland Landscape Trust',
 'desc': 'In the middle of the village core of <b>Heinkenszand</b> lies a green secret: <b>Landlust estate</b>, a <b>historic country seat</b> of ± <b>3 hectares</b> whose buildings were erected around <b>1800</b> — the nearby lying meadow and the country house are <b>national monuments</b>. The estate lies on part of the <b>sand ridge</b> on which the village itself was built; the nature has a pronounced <b>park-like character</b> with lawns, a <b>round pond</b>, shrubs and broadleaf wood. The western part consists of a natural forest type with much <b>oak, beech, maple and elm</b>; in the eastern part stand many <b>non-native tree and shrub species</b> — the collection of a country seat. On Landlust stand <b>old monumental trees unique in Zuid-Beveland</b>, and on the forest floor thrive <b>stinsen plants</b>: <b>spring snowflake, wild garlic, spotted lords-and-ladies and leopard’s bane</b> — spring begins here earlier than anywhere in the region. The wood is rich in birds: <b>great spotted woodpecker, long-eared owl, treecreeper</b> and blackcap breed, and at dusk the old trees are a safe roost. Freely accessible, unpaved paths, no signs: an estate that lets itself be found by whoever turns into the Eendvogelstraat.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (stinsen plants), Apr–Jun (woodland birds), Sep–Nov (fungi and old leaves)<br>\n    <b>Best time of day:</b> Early morning — garlic scent and song.',
 'why': ['The <b>country seat of ± 1800</b> in the middle of the village.', 'The <b>monumental trees</b>, unique in Zuid-Beveland.', 'The <b>stinsen plants</b>: spring snowflake, wild garlic, arum.', 'The <b>round pond</b> in the park.', 'The <b>treecreeper and long-eared owl</b> as inhabitants.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌷 <b>Spring snowflake and wild garlic</b> in bloom.', '<span class="months">Apr–May</span> 🎶 <b>Treecreeper and woodpecker</b> in breeding time.', '<span class="months">May–Jun</span> 🌻 <b>Leopard’s bane</b> on the forest floor.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> by old trees.'],
 'wild': ['🏡 Country seat ± 1800', '🌳 Monumental trees', '🌷 Stinsen plants', '💧 Round pond', '🐦 Treecreeper'],
 'trail': ['Enter the <b>Eendvogelstraat</b> to the Landlust entrance.', 'Walk the <b>unpaved paths</b> through park and wood.', 'Combine with the <b>flower dikes</b> (2233) and <b>Zwaakse Weel</b> (2241).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Path network ± 1–2 km · 🅿️ Parking in the Eendvogelstraat'
}))

C.append(mk.card(2241, 'Zwaakse Weel', {
 'tags': ['Zeeland · tussen Kwadendamme en \'s-Gravenpolder (Zak van Zuid-Beveland)', 'het enige overblijfsel van de zeearm de Zwake · langgerekte kreek in de Middelzwakepolder (afgedamd 1445/1474) — een van de grootste natuurgebieden van de Zak, met trekpaarden-akkers, hoogstamboomgaard en Vlinderbelevingspad', 'list 84 · no. 23'],
 'loc': '📍 Zwaakse Weel, startpunt/informatiepunt Zwaaksedijk 5, Kwadendamme — wandelroute ± 4,2 km (1 u 23) rond kreek en graslanden; OERRR-Beleefpad, Vlinderbelevingspad, picknickplek en kruidentuin; beheer Natuurmonumenten',
 'desc': 'Tussen <b>Kwadendamme</b> en <b>’s-Gravenpolder</b> ligt het <b>enige overblijfsel van de Zwake</b> — de zeearm die in de late middeleeuwen diep in Zuid-Beveland sneed en waarover tot in de veertiende eeuw <b>kleine vrachtschepen tussen Middelburg en Antwerpen</b> voeren. Toen de polders groeiden, werd de geul in fases afgedamd: rond <b>1316</b> de ’s Gravenpolder, ± <b>1320</b> de Slabbekoornpolder, vóór <b>1445</b> de Rondepolder (de huidige <b>Zwaaksedijk</b>), ± <b>1460</b> de Vlieguitpolder en in <b>1474</b> de laatste dam — waarna de restgeul binnendijks kwam te liggen als <b>kreek</b>. Wat overbleef is de <b>Zwaakse Weel</b>: een langgerekte, brede kreek in de <b>Middelzwakepolder</b>, vandaag een van de <b>grootste natuurgebieden van de Zak van Zuid-Beveland</b> en grotendeels in bezit van Natuurmonumenten. De wandelroute van ± <b>4,2 km</b> voert rond de oude kreek en de omliggende <b>gras- en rietlanden</b>, waar <b>schapen, koeien en paarden</b> grazen in een kleinschalig landschap vol bloemen en insecten. Bijzonder zijn de <b>akkertjes die op ouderwetse manier worden bewerkt met Zeeuwse trekpaarden</b>, en de <b>hoogstamboomgaard</b> waar je in het najaar fruit kunt plukken; voor kinderen zijn er het <b>Vlinderbelevingspad</b> en het <b>OERRR-Beleefpad</b>, met een picknickplek en <b>kruidentuin</b> naast het informatiepunt. Middeleeuwse scheepvaart, Zeeuwse landbouw en moderne natuurbeleving — in één kreek.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–sep</b> (vlinders en kruidentuin), apr–jun (weidevogels), sep–okt (fruit plukken in de boomgaard)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — nevel op de kreek.',
 'why': ['Het <b>laatste restant van de zeearm de Zwake</b>.', 'De <b>afdammingen van 1316 tot 1474</b> als ontstaansgeschiedenis.', 'De <b>middeleeuwse scheepvaart</b> Middelburg–Antwerpen.', 'De <b>trekpaarden-akkers en hoogstamboomgaard</b>.', 'Het <b>Vlinderbelevingspad en OERRR-Beleefpad</b>.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Weidevogels</b> in de graslanden.', '<span class="months">Mei–sep</span> 🦋 <b>Vlinders</b> langs kreek en bloemen.', '<span class="months">Sep–okt</span> 🍎 <b>Fruit plukken</b> in de hoogstamboomgaard.', '<span class="months">Nov–feb</span> 🪿 <b>Wintergasten</b> op de oude geul.'],
 'wild': ['💧 Kreek de Zwake', '🐎 Zeeuwse trekpaarden', '🍎 Hoogstamboomgaard', '🦋 Vlinderbelevingspad', '🐑 Grazende kuddes'],
 'trail': ['Start bij het <b>informatiepunt Zwaaksedijk 5</b> in Kwadendamme.', 'Loop de <b>wandelroute van ± 4,2 km</b> rond de kreek.', 'Bezoek <b>Vlinder- en OERRR-Beleefpad</b> met de kinderen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Route ± 4,2 km · 🅿️ Parkeren bij het informatiepunt'
}, {
 'tags': ['Zeeland · between Kwadendamme and \'s-Gravenpolder (Zak van Zuid-Beveland)', 'the only remnant of the Zwake sea arm · elongated creek in the Middelzwakepolder (dammed 1445/1474) — one of the largest nature areas of the Zak, with draft-horse fields, standard orchard and butterfly experience path', 'list 84 · no. 23'],
 'loc': '📍 Zwaakse Weel, starting point/information point Zwaaksedijk 5, Kwadendamme — walking route ± 4.2 km (1 h 23) around creek and grasslands; OERRR experience path, butterfly path, picnic spot and herb garden; managed by the Netherlands Nature Trust',
 'desc': 'Between <b>Kwadendamme</b> and <b>’s-Gravenpolder</b> lies the <b>only remnant of the Zwake</b> — the sea arm that cut deep into Zuid-Beveland in the late Middle Ages and over which until the fourteenth century <b>small freight ships sailed between Middelburg and Antwerp</b>. As the polders grew, the channel was dammed in phases: around <b>1316</b> the ’s Gravenpolder, ± <b>1320</b> the Slabbekoornpolder, before <b>1445</b> the Rondepolder (the present <b>Zwaaksedijk</b>), ± <b>1460</b> the Vlieguitpolder and in <b>1474</b> the last dam — after which the residual channel lay embanked as a <b>creek</b>. What remained is the <b>Zwaakse Weel</b>: an elongated, broad creek in the <b>Middelzwakepolder</b>, today one of the <b>largest nature areas of the Zak van Zuid-Beveland</b> and mostly owned by the Nature Trust. The ± <b>4.2-km</b> walking route leads around the old creek and the surrounding <b>grass and reed lands</b>, where <b>sheep, cows and horses</b> graze in a small-scale landscape full of flowers and insects. Special are the <b>fields worked the old way with Zeeland draft horses</b>, and the <b>standard orchard</b> where fruit can be picked in autumn; for children there are the <b>butterfly experience path</b> and the <b>OERRR path</b>, with a picnic spot and <b>herb garden</b> beside the information point. Medieval shipping, Zeeland farming and modern nature experience — in one creek.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (butterflies and herb garden), Apr–Jun (meadow birds), Sep–Oct (fruit picking in the orchard)<br>\n    <b>Best time of day:</b> Morning — mist on the creek.',
 'why': ['The <b>last remnant of the Zwake sea arm</b>.', 'The <b>damming phases from 1316 to 1474</b> as origin story.', 'The <b>medieval shipping</b> Middelburg–Antwerp.', 'The <b>draft-horse fields and standard orchard</b>.', 'The <b>butterfly and OERRR experience paths</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Meadow birds</b> in the grasslands.', '<span class="months">May–Sep</span> 🦋 <b>Butterflies</b> along creek and flowers.', '<span class="months">Sep–Oct</span> 🍎 <b>Fruit picking</b> in the standard orchard.', '<span class="months">Nov–Feb</span> 🪿 <b>Winter guests</b> on the old channel.'],
 'wild': ['💧 Zwake creek', '🐎 Zeeland draft horses', '🍎 Standard orchard', '🦋 Butterfly path', '🐑 Grazing herds'],
 'trail': ['Start at the <b>information point Zwaaksedijk 5</b> in Kwadendamme.', 'Walk the <b>± 4.2-km route</b> around the creek.', 'Visit the <b>butterfly and OERRR paths</b> with children.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Route ± 4.2 km · 🅿️ Parking at the information point'
}))

C.append(mk.card(2242, 'Kapelle Bank', {
 'tags': ['Zeeland · Westerschelde-oever tussen Eversdijk en Schore (Zuid-Beveland)', 'buitendijks slikken- en schorsterras aan de Westerschelde · genoemd naar de gemeente Kapelle — op de bank borrelt grondwater op; het dijkvak Hansweert–Kapellebank (5,2 km) wordt versterkt', 'list 84 · no. 24'],
 'loc': '📍 Kapelle Bank, buitendijks langs de Westerschelde tussen Eversdijk en Schore — te overzien vanaf de Westerscheldedijk; onderdeel van het dijkversterkingstraject Hansweert–Kapellebank; combineer met de Zwaakse Weel (2241) en de Schenge (2225)',
 'desc': 'Aan de noordoever van de <b>Westerschelde</b>, ter hoogte van <b>Eversdijk</b> en <b>Schore</b>, ligt een buitendijks gebied dat op de kaart als <b>Kapelle Bank</b> staat — een <b>slikken- en schorsterras</b> dat bij eb droogvalt en bij vloed onderloopt, genoemd naar de gemeente Kapelle aan wie het kustvak toebehoort. Bijzonder is de <b>kwel</b>: op de bank <b>borrelt water op</b> uit de ondergrond — zoet grondwater dat door de kleilagen heen drukt en het schor zijn eigen, brakke plekken geeft. Voor de vogels van de Westerschelde is de bank onderdeel van de grote <b>slikken- en schorrenketting</b>: bij eb fourageren steltlopers op de platen, bij vloed schuilen ze hoog op het schor; in de winter grazen eenden en ganzen op het buitendijkse gras. De naam duikt ook op in de waterstaatsgeschiedenis van nu: het <b>dijkvak van het sluizencomplex Hansweert tot en met de Kapellebank (5,2 km)</b> wordt in het kader van de dijkversterking aangepakt — de zeezijde van Zuid-Beveland wordt toekomstvast gemaakt, met de bank als oriëntatiepunt. Wie over de <b>Westerscheldedijk</b> fietst, ziet de bank wisselen met het getij: moddervlakte, spiegel, en weer moddervlakte — het oudste ritme van Zeeland.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Sep–mrt</b> (steltlopers en wintergasten), mrt–mei (trek en broedtijd schor), jun–aug (hoogwater-schouw)<br>\n    <b>Beste tijd van de dag:</b> Rond de eb-vloed-wissel — vogels op de beweging.',
 'why': ['Het <b>buitendijkse slikken- en schorsterras</b> aan de Westerschelde.', 'De <b>kwel</b> waar water opborrelt uit de ondergrond.', 'De <b>getijden-dynamiek</b> als oudste ritme.', 'Het <b>dijkvak Hansweert–Kapellebank (5,2 km)</b> als hedendaagse waterstaat.', 'De <b>slikken- en schorrenketting</b> van de Westerschelde.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Schorvogels</b> in broedtijd.', '<span class="months">Jun–aug</span> 🌊 <b>Hoogwater-schouw</b> over de bank.', '<span class="months">Sep–mrt</span> 🦆 <b>Steltlopers en wintergasten</b> bij eb.', '<span class="months">Jaarrond</span> 🌊 <b>Getijdenwissel</b> tweemaal daags.'],
 'wild': ['🌊 Slikken en schorren', '💧 Grondwater-kwel', '🦆 Steltlopers', '🏔️ Getijdenritme', '🏗️ Dijkversterking-gebied'],
 'trail': ['Fiets of wandel over de <b>Westerscheldedijk</b> bij Schore.', 'Kijk bij <b>eb</b> naar de fouragerende steltlopers.', 'Combineer met <b>Zwaakse Weel</b> (2241) en <b>Schenge</b> (2225).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Overzicht vanaf de dijk · ⚠️ Buitendijks gebied niet betreden'
}, {
 'tags': ['Zeeland · Westerschelde shore between Eversdijk and Schore (Zuid-Beveland)', 'outer-dike mudflat and salt-marsh terrace on the Westerschelde · named after the municipality of Kapelle — on the bank groundwater bubbles up; the dike section Hansweert–Kapellebank (5.2 km) is being reinforced', 'list 84 · no. 24'],
 'loc': '📍 Kapelle Bank, outer-dike along the Westerschelde between Eversdijk and Schore — to be surveyed from the Westerschelde dike; part of the Hansweert–Kapellebank dike reinforcement stretch; combine with Zwaakse Weel (2241) and Schenge (2225)',
 'desc': 'On the north-east shore of the <b>Westerschelde</b>, near <b>Eversdijk</b> and <b>Schore</b>, lies an outer-dike area shown on the map as the <b>Kapelle Bank</b> — a <b>mudflat and salt-marsh terrace</b> that falls dry at low water and floods at high tide, named after the municipality of Kapelle to which the coastal section belongs. Special is the <b>seepage</b>: on the bank <b>water bubbles up</b> from the subsoil — fresh groundwater pushing through the clay layers and giving the marsh its own brackish spots. For the birds of the Westerschelde the bank is part of the great <b>chain of mudflats and marshes</b>: at low water waders forage on the plates, at high water they shelter high on the marsh; in winter ducks and geese graze the outer-dike grass. The name also appears in present-day water management: the <b>dike section from the Hansweert lock complex to the Kapellebank (5.2 km)</b> is being reinforced — the seaward side of Zuid-Beveland made future-proof, with the bank as landmark. Cycle the <b>Westerschelde dike</b> and you see the bank change with the tide: mud flat, mirror, and mud flat again — Zeeland’s oldest rhythm.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Sep–Mar</b> (waders and winter guests), Mar–May (migration and marsh breeding), Jun–Aug (high-water spectacle)<br>\n    <b>Best time of day:</b> Around the ebb-flood turn — birds on the move.',
 'why': ['The <b>outer-dike mudflat and marsh terrace</b> on the Westerschelde.', 'The <b>seepage</b> where water bubbles up.', 'The <b>tidal dynamics</b> as oldest rhythm.', 'The <b>Hansweert–Kapellebank dike section (5.2 km)</b> as modern water management.', 'The <b>Westerschelde mudflat-marsh chain</b>.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Marsh birds</b> in breeding time.', '<span class="months">Jun–Aug</span> 🌊 <b>High-water spectacle</b> over the bank.', '<span class="months">Sep–Mar</span> 🦆 <b>Waders and winter guests</b> at low tide.', '<span class="months">Year-round</span> 🌊 <b>Tidal change</b> twice a day.'],
 'wild': ['🌊 Mudflats and marshes', '💧 Groundwater seepage', '🦆 Waders', '🏔️ Tidal rhythm', '🏗️ Dike reinforcement area'],
 'trail': ['Cycle or walk the <b>Westerschelde dike</b> at Schore.', 'Look at <b>low tide</b> for foraging waders.', 'Combine with <b>Zwaakse Weel</b> (2241) and <b>Schenge</b> (2225).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 Overview from the dike · ⚠️ Outer-dike area — do not enter'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2242)
mk.check()
