# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2248, 'Zuidgors', {
 'tags': ['Zeeland · buitendijks voor de Zeedijk bij Ellewoutsdijk (Westerschelde)', 'buitendijs schorren- en slikkengebied · hoe Zeeland eruitzag vóór de inpoldering — kokmeeuw- en zwartkopmeeuwkolonies, zoutmelde en lamsoor; het schor krimpt jaarlijks door de uitdieping van de Westerschelde', 'list 84 · no. 30'],
 'loc': '📍 Zuidgors, buitendijks voor de Zeedijk bij Ellewoutsdijk — niet toegankelijk; prima te overzien vanaf de Zeedijk (strandbrasserie De Landing richting Baarland als uitvalsbasis); combineer met Fort Ellewoutsdijk (2247) en Inlaag 1887 (2246)',
 'desc': 'Voor de dijk bij <b>Ellewoutsdijk</b> ligt een stuk Zeeland zoals het er eeuwenlang uitzag: de <b>Zuidgors</b>, een <b>buitendijks schorren- en slikkengebied</b> aan de Westerschelde, met zijn <b>kreken, kommen en oeverwallen</b> — het getijdenlandschap van vóór de inpoldering, nog steeds twee keer per dag onderlopend. Het is een van de <b>weinige buitendijkse schorren van de Westerschelde</b> en daarmee van nationale betekenis. In het voorjaar is het een <b>drukte van jewelste</b>: grote <b>broedkolonies van kokmeeuw en zwartkopmeeuw</b> bezetten het schor, en de lucht erboven is vol. Op de hogere delen groeien <b>gewone zoutmelde, zulte, lamsoor en strandkweek</b> — planten uit het zoute verleden; de <b>kale slikken</b> eromheen vormen bij eb een rust- en voedselgebied voor steltlopers en watervogels. ’s Winters bezoeken <b>duizenden bonte strandlopers, rosse grutto’s en zilverplevieren</b> het gebied. Maar het schor staat onder druk: voor de grote schepen naar Antwerpen is de Westerschelde <b>uitgediept</b>, de stroming langs de slikken is sneller geworden — en de <b>Zuidgors krimpt jaarlijks met enkele meters</b>. Wie vanaf de Zeedijk kijkt, ziet dus een verdwijnend landschap — des te meer reden om het nu te zien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (meeuwkolonies), sep–mrt (wintergasten: strandlopers, grutto’s), jul–sep (zilte bloei)<br>\n    <b>Beste tijd van de dag:</b> Bij eb — de slikken vol vogels.',
 'why': ['Het <b>schor vóór de inpoldering</b> als levend museum.', 'De <b>kokmeeuw- en zwartkopmeeuwkolonies</b>.', 'De <b>zoutmelde, zulte en lamsoor</b> op het schor.', 'De <b>duizenden winterse strandlopers en grutto’s</b>.', 'De <b>jaarlijkse krimp</b> door de uitdieping van de Schelde.'],
 'phen': ['<span class="months">Apr–jun</span> 🥚 <b>Meeuwkolonies</b> in vol bedrijf.', '<span class="months">Jul–sep</span> 🌿 <b>Lamsoor en zulte</b> in zilte bloei.', '<span class="months">Sep–mrt</span> 🦆 <b>Bonte strandlopers en rosse grutto’s</b>.', '<span class="months">Jaarrond</span> 🌊 <b>Getijdenwissel</b> over kreken en platen.'],
 'wild': ['🌊 Schor en slik', '🥚 Kokmeeuwkolonie', '🌿 Zoutmelde en lamsoor', '🦆 Winterse steltlopers', '⚠️ Krimpend schor'],
 'trail': ['Overzicht vanaf de <b>Zeedijk</b> bij Ellewoutsdijk.', 'Combineer met <b>Fort Ellewoutsdijk</b> (2247) en <b>Inlaag 1887</b> (2246).', 'Kies <b>eb</b> voor de vogels op de slikken.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Uitzicht vanaf de dijk · ⚠️ Buitendijks — niet betreden'
}, {
 'tags': ['Zeeland · outer-dike before the sea dike at Ellewoutsdijk (Westerschelde)', 'outer-dike marsh and mudflat area · Zeeland as it looked before the reclamation — Mediterranean and black-headed gull colonies, saltbush and sea lavender; the marsh shrinks yearly through the deepening of the Westerschelde', 'list 84 · no. 30'],
 'loc': '📍 Zuidgors, outer-dike before the Zeedijk at Ellewoutsdijk — not accessible; well visible from the sea dike (beach brasserie De Landing towards Baarland as base); combine with Fort Ellewoutsdijk (2247) and Inlaag 1887 (2246)',
 'desc': 'Before the dike at <b>Ellewoutsdijk</b> lies a piece of Zeeland as it looked for centuries: the <b>Zuidgors</b>, an <b>outer-dike marsh and mudflat area</b> on the Westerschelde, with its <b>creeks, pans and levees</b> — the tidal landscape of before the reclamation, still flooding twice a day. It is one of the <b>few outer-dike marshes of the Westerschelde</b> and therefore of national significance. In spring it is <b>bustling</b>: large <b>breeding colonies of Mediterranean and black-headed gulls</b> occupy the marsh, and the air above is full. On the higher parts grow <b>annual saltbush, samphire, sea lavender and sea couch</b> — plants from the salty past; the <b>bare mudflats</b> around them form a resting and feeding ground for waders and waterfowl at low tide. In winter <b>thousands of dunlins, bar-tailed godwits and grey plovers</b> visit the area. But the marsh is under pressure: for the great ships to Antwerp the Westerschelde has been <b>deepened</b>, the current along the mudflats faster — and the <b>Zuidgors shrinks by several metres a year</b>. Look from the sea dike and you see a vanishing landscape — all the more reason to see it now.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (gull colonies), Sep–Mar (winter guests: dunlins, godwits), Jul–Sep (saline bloom)<br>\n    <b>Best time of day:</b> At low tide — the mudflats full of birds.',
 'why': ['The <b>marsh of before the reclamation</b> as living museum.', 'The <b>Mediterranean and black-headed gull colonies</b>.', 'The <b>saltbush, samphire and sea lavender</b> on the marsh.', 'The <b>thousands of wintering dunlins and godwits</b>.', 'The <b>yearly shrinkage</b> through the Scheldt deepening.'],
 'phen': ['<span class="months">Apr–Jun</span> 🥚 <b>Gull colonies</b> in full swing.', '<span class="months">Jul–Sep</span> 🌿 <b>Sea lavender and samphire</b> in saline bloom.', '<span class="months">Sep–Mar</span> 🦆 <b>Dunlins and bar-tailed godwits</b>.', '<span class="months">Year-round</span> 🌊 <b>Tidal change</b> over creeks and plates.'],
 'wild': ['🌊 Marsh and mudflat', '🥚 Mediterranean gull colony', '🌿 Saltbush and lavender', '🦆 Wintering waders', '⚠️ Shrinking marsh'],
 'trail': ['Overview from the <b>sea dike</b> at Ellewoutsdijk.', 'Combine with <b>Fort Ellewoutsdijk</b> (2247) and <b>Inlaag 1887</b> (2246).', 'Choose <b>low tide</b> for the birds on the flats.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 View from the dike · ⚠️ Outer-dike — do not enter'
}, n2k='De Zuidgors valt onder het Natura 2000-gebied Westerschelde & Saeftinghe — het buitendijkse schor is een beschermd onderdeel van het estuarium van de Westerschelde.', n2k_en='The Zuidgors falls under the Natura 2000 site Westerschelde & Saeftinghe — the outer-dike marsh is a protected part of the Westerschelde estuary.'))

C.append(mk.card(2249, 'Hooge Platencomplex', {
 'tags': ['Zeeland · midden in de Westerschelde (tussen Vlissingen/Borssele en Breskens/Hoofdplaat)', '1.800 ha zandplaten, slikken en schorren in het getij · bij eb droogvallende platen vol voedsel — “De Bol” blijft altijd droog met broedkolonies van sterns, kokmeeuwen en sinds kort lepelaars; zeehonden rusten er bij laagwater', 'list 84 · no. 31'],
 'loc': '📍 Hooge Platen, midden in de Westerschelde — de platen zelf zijn niet toegankelijk; te zien vanaf het fietspad buitenlangs de Westerscheldedijk, vanaf de vogelhut bij Nummer Eén (kaart 2250) en tijdens vaartochten vanuit Breskens; beheer Het Zeeuwse Landschap',
 'desc': 'Midden in de <b>Westerschelde</b>, tussen de noordoever van Walcheren/Borssele en de Zeeuws-Vlaamse zuidkant, ligt een natuurgebied dat met het getij verandert van vorm: de <b>Hooge Platen</b>, ± <b>1.800 hectare</b> <b>zandplaten, slikken en schorren</b> die bij eb droogvallen en bij vloed onder de golven verdwijnen. Bij eb is het één groot <b>restaurant</b>: grote aantallen vogels zoeken er voedsel — wormen, schelpdieren en kreeftachtigen uit de slikbodem; bij vloed, als de platen weer onder water staan, komen <b>scholen jonge vis</b> er foerageren. Midden in het gebied ligt <b>De Bol</b>, het deel dat <b>altijd droog blijft</b> — en dat maakt het tot een van de belangrijkste <b>broedeilanden</b> van Zuidwest-Nederland: <b>dwergsterns, visdieven en grote sterns</b> broeden er, naast kokmeeuwen, strandplevieren en zilvermeeuwen, en de laatste jaren is ook een <b>kolonie lepelaars</b> neergestreken. Op de platen rusten bovendien <b>zeehonden</b> — rond de dertig gewone en grijze zeehonden leven in de monding. De Hooge Platen zijn rustplaats, kraamkamer en restaurant in één; wie ze wil zien, fietst het <b>pad buitenlangs de dijk</b>, zit in de <b>vogelhut bij Nummer Eén</b> — of vaart er vanuit Breskens langs.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jul</b> (broedkolonies op De Bol), jul–sep (jonge zeehonden), sep–mrt (wintergasten op de platen)<br>\n    <b>Beste tijd van de dag:</b> Bij eb — platen en zeehonden zichtbaar.',
 'why': ['De <b>1.800 ha getijdenplaten</b> midden in de Westerschelde.', '<b>De Bol</b> als altijd-droog broedeiland.', 'De <b>sternkolonies</b>: dwergstern, visdief, grote stern.', 'De <b>nieuwkomers: lepelaars</b>.', 'De <b>zeehonden</b> op de platen bij laagwater.'],
 'phen': ['<span class="months">Mei–jul</span> 🥚 <b>Sternkolonies</b> op De Bol.', '<span class="months">Jul–sep</span> 🦭 <b>Zeehonden</b> zonnend op de platen.', '<span class="months">Sep–mrt</span> 🦆 <b>Wintergasten</b> over slik en zand.', '<span class="months">Jaarrond</span> 🌊 <b>Eb en vloed</b> als landschapsvormer.'],
 'wild': ['🌊 Getijdenplaten', '🐦 Sternkolonies', '🥄 Lepelaarkolonie', '🦭 Zeehonden', '🏝️ De Bol'],
 'trail': ['Fiets het <b>pad buitenlangs de Westerscheldedijk</b>.', 'Zit in de <b>vogelhut bij Nummer Eén</b> (kaart 2250).', 'Vaar mee op een <b>vaartocht vanuit Breskens</b>.'],
 'foot': '🐕 n.v.t. (water) · 💶 Vaartocht tegen betaling · 🔭 Verrekijker of telescoop nodig · ⚠️ Platen niet betreden'
}, {
 'tags': ['Zeeland · in the middle of the Westerschelde (between Vlissingen/Borssele and Breskens/Hoofdplaat)', '1,800 ha of sand plates, mudflats and marshes in the tide · plates falling dry at low tide, full of food — “De Bol” stays dry always, with breeding colonies of terns, gulls and recently spoonbills; seals rest there at low water', 'list 84 · no. 31'],
 'loc': '📍 Hooge Platen, in the middle of the Westerschelde — the plates themselves are not accessible; visible from the cycle path outside the Westerschelde dike, from the bird hut at Nummer Eén (card 2250) and on boat trips from Breskens; managed by the Zeeland Landscape Trust',
 'desc': 'In the middle of the <b>Westerschelde</b>, between the Walcheren/Borssele north shore and the Zeeuws-Vlaanderen side, lies a nature area that changes shape with the tide: the <b>Hooge Platen</b>, ± <b>1,800 hectares</b> of <b>sand plates, mudflats and marshes</b> falling dry at low tide and disappearing under the waves at high. At low tide it is one great <b>restaurant</b>: large numbers of birds forage — worms, shellfish and crustaceans from the mud; at high tide, when the plates sink away, <b>schools of young fish</b> come to feed. In the middle lies <b>De Bol</b>, the part that <b>always stays dry</b> — making it one of the most important <b>breeding islands</b> of the southwest: <b>little terns, common terns and sandwich terns</b> breed, beside Mediterranean gulls, Kentish plovers and herring gulls, and in recent years a <b>colony of spoonbills</b> has settled too. On the plates <b>seals</b> also rest — around thirty common and grey seals live in the mouth. The Hooge Platen are resting place, nursery and restaurant in one; to see them, cycle the <b>path outside the dike</b>, sit in the <b>bird hut at Nummer Eén</b> — or sail past from Breskens.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (breeding colonies on De Bol), Jul–Sep (young seals), Sep–Mar (winter guests on the plates)<br>\n    <b>Best time of day:</b> At low tide — plates and seals visible.',
 'why': ['The <b>1,800 ha of tidal plates</b> in the middle of the Westerschelde.', '<b>De Bol</b> as always-dry breeding island.', 'The <b>tern colonies</b>: little, common and sandwich tern.', 'The <b>newcomers: spoonbills</b>.', 'The <b>seals</b> on the plates at low water.'],
 'phen': ['<span class="months">May–Jul</span> 🥚 <b>Tern colonies</b> on De Bol.', '<span class="months">Jul–Sep</span> 🦭 <b>Seals</b> basking on the plates.', '<span class="months">Sep–Mar</span> 🦆 <b>Winter guests</b> over mud and sand.', '<span class="months">Year-round</span> 🌊 <b>Ebb and flood</b> as landscape maker.'],
 'wild': ['🌊 Tidal plates', '🐦 Tern colonies', '🥄 Spoonbill colony', '🦭 Seals', '🏝️ De Bol'],
 'trail': ['Cycle the <b>path outside the Westerschelde dike</b>.', 'Sit in the <b>bird hut at Nummer Eén</b> (card 2250).', 'Join a <b>boat trip from Breskens</b>.'],
 'foot': '🐕 n/a (water) · 💶 Boat trip for a fee · 🔭 Binoculars or telescope needed · ⚠️ Do not enter the plates'
}, n2k='De Hooge Platen vormen de dynamische kern van het Natura 2000-gebied Westerschelde & Saeftinghe — zandplaten, slikken en schorren die met eb en vloed blijven verschuiven.', n2k_en='The Hooge Platen form the dynamic heart of the Natura 2000 site Westerschelde & Saeftinghe — sand plates, mudflats and marshes that keep shifting with the tides.'))

C.append(mk.card(2250, 'Nummer Eén', {
 'tags': ['Zeeland · buurtschap aan de Westerscheldedijk bij Hoofdplaat (Zeeuws-Vlaanderen)', 'dijkplaatsje met de vogelhut bovenop de zeedijk · het klassieke kijkpunt over de Hooge Platen — sterns, zeehonden en schorren op één horizon; poort naar het Westerschelde-getijdenlandschap', 'list 84 · no. 32'],
 'loc': '📍 Nummer Eén aan de Westerscheldedijk ten westen van Hoofdplaat — vogelhut bovenop de dijk (vrij toegankelijk); fietspad buitenlangs de dijk; combineer met Inlaag Hoofdplaat (kaart 2251) en de Hooge Platen (2249)',
 'desc': 'Aan de <b>Westerscheldedijk</b> ten westen van <b>Hoofdplaat</b> ligt een buurtschap die op de kaart weinig meer is dan een naam: <b>Nummer Eén</b> — maar voor vogelaars is het een adres op zich. Bovenop de dijk staat hier de <b>vogelhut Nummer Eén</b>, het klassieke kijkpunt over de <b>Hooge Platen</b> (kaart 2249): wie door de kijkgaten tuurt, ziet bij eb de <b>zandplaten vol steltlopers</b>, bij vloed de rustende <b>zeehonden</b>, en in de zomer de <b>sternkolonies</b> die van De Bol op en neer vliegen. De hut is het sein van een landschap dat hier buiten de dijk nog volledig leeft: schorren, slikken en platen, met op de achtergrond de scheepvaart naar Antwerpen — de rivier en het getij in één beeld. De naam herinnert aan de tijd dat de polders van Hoofdplaat genummerd werden: het eerste stukje inpoldering droogde hier als “nummer één” op. Wie de <b>fietsroute buitenlangs de dijk</b> rijdt van Breskens naar Hoofdplaat, doet Nummer Eén vanzelf aan — en blijft, telescoop in de hut, meestal langer dan gepland. Combineer het met de <b>Inlaag Hoofdplaat</b> (kaart 2251) binnendijks voor een complete Westerschelde-dag.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–sep</b> (sterns, zeehonden), sep–mrt (winterse platen), apr–mei (trek)<br>\n    <b>Beste tijd van de dag:</b> Rond eb — platen droog, zeehonden zichtbaar.',
 'why': ['De <b>vogelhut bovenop de zeedijk</b>.', 'Het <b>klassieke kijkpunt op de Hooge Platen</b>.', 'De <b>naam uit de genummerde polders</b> van Hoofdplaat.', 'Het <b>fietspad buitenlangs de dijk</b>.', 'De <b>combinatie rivier-getij-vogels</b> in één beeld.'],
 'phen': ['<span class="months">Mei–jul</span> 🥚 <b>Sterntrek</b> van en naar De Bol.', '<span class="months">Jul–sep</span> 🦭 <b>Zeehonden</b> op de droge platen.', '<span class="months">Sep–mrt</span> 🦆 <b>Winterse steltlopers</b> bij eb.', '<span class="months">Jaarrond</span> 🚢 <b>Scheepvaart</b> op de achtergrond.'],
 'wild': ['👀 Vogelhut', '🌊 Hooge Platen-uitzicht', '🦭 Zeehonden', '🐦 Sternkolonies', '🚴 Dijkfietsroute'],
 'trail': ['Zit in de <b>vogelhut</b> bovenop de dijk.', 'Fiets het <b>pad buitenlangs de Westerscheldedijk</b>.', 'Combineer met <b>Inlaag Hoofdplaat</b> (2251) en <b>Hooge Platen</b> (2249).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🔭 Telescoop aan te raden · 🅿️ Parkeren bij de dijk bij Nummer Eén'
}, {
 'tags': ['Zeeland · hamlet on the Westerschelde dike near Hoofdplaat (Zeeuws-Vlaanderen)', 'dike hamlet with the bird hut on top of the sea dike · the classic viewpoint over the Hooge Platen — terns, seals and marshes on one horizon; gateway to the Westerschelde tidal landscape', 'list 84 · no. 32'],
 'loc': '📍 Nummer Eén on the Westerschelde dike west of Hoofdplaat — bird hut on top of the dike (free access); cycle path outside the dike; combine with Inlaag Hoofdplaat (card 2251) and the Hooge Platen (2249)',
 'desc': 'On the <b>Westerschelde dike</b> west of <b>Hoofdplaat</b> lies a hamlet that on the map is little more than a name: <b>Nummer Eén</b> (Number One) — but for birders it is an address in itself. On top of the dike stands the <b>Nummer Eén bird hut</b>, the classic viewpoint over the <b>Hooge Platen</b> (card 2249): look through the flaps and at low tide you see the <b>sand plates full of waders</b>, at high tide the resting <b>seals</b>, and in summer the <b>tern colonies</b> flying to and from De Bol. The hut marks a landscape that outside the dike still lives fully here: marshes, mudflats and plates, with the shipping to Antwerp behind — river and tide in one image. The name recalls the days when the Hoofdplaat polders were numbered: the first reclamation dried as “number one” here. Ride the <b>cycle route outside the dike</b> from Breskens to Hoofdplaat and you pass Nummer Eén automatically — and with a telescope in the hut, most stay longer than planned. Combine with the <b>Inlaag Hoofdplaat</b> (card 2251) inland for a complete Westerschelde day.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Sep</b> (terns, seals), Sep–Mar (wintry plates), Apr–May (migration)<br>\n    <b>Best time of day:</b> Around low tide — plates dry, seals visible.',
 'why': ['The <b>bird hut on top of the sea dike</b>.', 'The <b>classic viewpoint on the Hooge Platen</b>.', 'The <b>name from the numbered polders</b> of Hoofdplaat.', 'The <b>cycle path outside the dike</b>.', 'The <b>river-tide-birds combination</b> in one image.'],
 'phen': ['<span class="months">May–Jul</span> 🥚 <b>Tern traffic</b> to and from De Bol.', '<span class="months">Jul–Sep</span> 🦭 <b>Seals</b> on the dry plates.', '<span class="months">Sep–Mar</span> 🦆 <b>Wintry waders</b> at low tide.', '<span class="months">Year-round</span> 🚢 <b>Shipping</b> in the background.'],
 'wild': ['👀 Bird hut', '🌊 Hooge Platen views', '🦭 Seals', '🐦 Tern colonies', '🚴 Dike cycle route'],
 'trail': ['Sit in the <b>bird hut</b> on top of the dike.', 'Cycle the <b>path outside the Westerschelde dike</b>.', 'Combine with <b>Inlaag Hoofdplaat</b> (2251) and <b>Hooge Platen</b> (2249).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🔭 Telescope recommended · 🅿️ Parking at the dike at Nummer Eén'
}))

C.append(mk.card(2251, 'Inlaag Hoofdplaat', {
 'tags': ['Zeeland · ten westen van Hoofdplaat (Zeeuws-Vlaanderen)', 'inlaag van ± 1800, in 1921 afgegraven voor dijkversterking · de zandige, kalkrijke ondergrond kreeg een soortenrijke, duinvallei-achtige begroeiing — een klein zilt juweel achter de Westerscheldedijk', 'list 84 · no. 33'],
 'loc': '📍 Inlaag Hoofdplaat, ten westen van Hoofdplaat achter de Westerscheldedijk — te bekijken vanaf de dijk; combineer met de vogelhut Nummer Eén (kaart 2250) en de Hooge Platen (2249); beheer Het Zeeuwse Landschap',
 'desc': 'Ten westen van <b>Hoofdplaat</b> ligt een klein natuurgebied met een dubbel verleden: de <b>Inlaag Hoofdplaat</b>. Omstreeks <b>1800</b> werd hier een inlaag aangelegd — een reservestrip achter de dijk, ontstaan na <b>dijkval</b> in die jaren: op 22 januari <b>1802</b> overstroomde de hele inlaag nog eens. Maar het bijzondere gebeurde veel later: in <b>1921</b> werd het gebied <b>grotendeels afgegraven voor dijkversterkingen</b>, en door die afgraving kwam een <b>zandige, kalkrijke ondergrond</b> vrij — grond die in Zeeuws-Vlaanderen zeldzaam is. Daarop ontwikkelde zich een <b>soortenrijke, duinvallei-achtige begroeiing</b>: een stukje duinnatuur achter de zeedijk, met de bijbehorende orchideeën, nachtsilene en andere kalkminnaars. Samen met de inlaagstructuur — laag, nat, beschut tussen de dijken — is zo een klein <b>zilt-droog mozaïek</b> ontstaan dat nergens anders in de Westerschelde-regio zo voorkomt. Voor vogels is de inlaag een rust- en broedplek binnendijks, een stukje compensation voor de drukte op de platen. De inlaag is een van de kleine reservaten van Het Zeeuwse Landschap (± 2 ha) — maar wie de dijk fietst van Nummer Eén naar Hoofdplaat begint er onbedoeld mee: de geschiedenis van dijkval, afgraving en terugkeer van de natuur in één oogopslag.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jun</b> (duinvallei-bloei), apr–jun (broedvogels), sep–mrt (winterse rust)<br>\n    <b>Beste tijd van de dag:</b> Middag — zon op de kalkrijde plekken.',
 'why': ['De <b>inlaag van ± 1800</b> met de overstroming van 1802.', 'De <b>afgraving van 1921</b> voor dijkversterking.', 'De <b>zandige, kalkrijke ondergrond</b> die vrijkwam.', 'De <b>duinvallei-achtige begroeiing</b> als verrassing.', 'Het <b>zilt-droog mozaïek</b> achter de zeedijk.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Broedvogels</b> in de beschutte inlaag.', '<span class="months">Mei–jun</span> 🌸 <b>Orchideeën en nachtsilene</b> in bloei.', '<span class="months">Jul–sep</span> 🦋 <b>Vlinders</b> op de droge delen.', '<span class="months">Okt–mrt</span> 🦆 <b>Winterse rust</b> in de laagte.'],
 'wild': ['🌸 Duinvallei-vegetatie', '🧂 Kalkrijke grond', '💧 Inlaag-structuur', '🐦 Broedvogels', '📜 Dijkval-geschiedenis'],
 'trail': ['Bekijk de inlaag vanaf de <b>Westerscheldedijk</b>.', 'Combineer met de <b>vogelhut Nummer Eén</b> (2250).', 'Lees de lagen: <b>1800 inlaag, 1921 afgraving</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Zicht vanaf de dijk · 🔭 Verrekijker nuttig'
}, {
 'tags': ['Zeeland · west of Hoofdplaat (Zeeuws-Vlaanderen)', 'inlay of ± 1800, dug off in 1921 for dike reinforcement · the sandy, calcareous subsoil developed a species-rich, dune-valley-like vegetation — a small saline jewel behind the Westerschelde dike', 'list 84 · no. 33'],
 'loc': '📍 Inlaag Hoofdplaat, west of Hoofdplaat behind the Westerschelde dike — to be viewed from the dike; combine with the Nummer Eén bird hut (card 2250) and the Hooge Platen (2249); managed by the Zeeland Landscape Trust',
 'desc': 'West of <b>Hoofdplaat</b> lies a small nature area with a double past: the <b>Inlaag Hoofdplaat</b>. Around <b>1800</b> an inlay was laid here — a reserve strip behind the dike, arising after <b>dike failure</b> in those years: on 22 January <b>1802</b> the whole inlay flooded once more. But the special came much later: in <b>1921</b> the area was <b>largely dug off for dike reinforcements</b>, and that excavation freed a <b>sandy, calcareous subsoil</b> — rare in Zeeuws-Vlaanderen. On it developed a <b>species-rich, dune-valley-like vegetation</b>: a piece of dune nature behind the sea dike, with its orchids, night silene and other lime lovers. Together with the inlay structure — low, wet, sheltered between the dikes — a small <b>saline-dry mosaic</b> arose that occurs nowhere else in the Westerschelde region. For birds the inlay is an inland resting and breeding spot, a compensation for the bustle on the plates. It is one of the small reserves of the Zeeland Landscape Trust (± 2 ha) — but cycle the dike from Nummer Eén to Hoofdplaat and you begin with it unintentionally: the history of dike failure, excavation and nature’s return in one glance.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (dune-valley bloom), Apr–Jun (breeding birds), Sep–Mar (wintry rest)<br>\n    <b>Best time of day:</b> Midday — sun on the calcareous spots.',
 'why': ['The <b>inlay of ± 1800</b> with the 1802 flood.', 'The <b>1921 excavation</b> for dike reinforcement.', 'The <b>sandy, calcareous subsoil</b> that came free.', 'The <b>dune-valley-like vegetation</b> as surprise.', 'The <b>saline-dry mosaic</b> behind the sea dike.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Breeding birds</b> in the sheltered inlay.', '<span class="months">May–Jun</span> 🌸 <b>Orchids and night silene</b> in bloom.', '<span class="months">Jul–Sep</span> 🦋 <b>Butterflies</b> on the dry parts.', '<span class="months">Oct–Mar</span> 🦆 <b>Wintry rest</b> in the low ground.'],
 'wild': ['🌸 Dune-valley vegetation', '🧂 Calcareous soil', '💧 Inlay structure', '🐦 Breeding birds', '📜 Dike-failure history'],
 'trail': ['View the inlay from the <b>Westerschelde dike</b>.', 'Combine with the <b>Nummer Eén bird hut</b> (2250).', 'Read the layers: <b>1800 inlay, 1921 excavation</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 View from the dike · 🔭 Binoculars useful'
}, n2k='Inlaag Hoofdplaat is een binnendijks onderdeel van het Natura 2000-gebied Westerschelde & Saeftinghe — een van de gebieden waarmee het estuarium ook achter de dijk beschermd is.', n2k_en='Inlaag Hoofdplaat is an inner-dike part of the Natura 2000 site Westerschelde & Saeftinghe — one of the areas by which the estuary is protected behind the dikes too.'))

C.append(mk.card(2252, 'Inlaag Kruispolderkaai', {
 'tags': ['Zeeland · in de Kruispolder bij Retranchement/Breskens (Zeeuws-Vlaanderen)', 'kleine inlaag van ± 3 ha aan de kruispolder-kade · zilte graslanden en poelen in de luwte van de oude Westerscheldedijk — broed- en rustgebied voor scholeksters, tureluurs en eenden', 'list 84 · no. 34'],
 'loc': '📍 Inlaag Kruispolderkaai, in de Kruispolder ten oosten van Retranchement — te bekijken vanaf de dijken rond de Kruispolder; combineer met Het Zwin (kaart 2210) en de Wallen van Retranchement (2213); beheer Het Zeeuwse Landschap',
 'desc': 'In de <b>Kruispolder</b>, het oude inpolderingsgebied ten oosten van <b>Retranchement</b>, ligt een van de kleinste reservaten van Het Zeeuwse Landschap: de <b>Inlaag Kruispolderkaai</b>, ± <b>3 hectare</b> aan de kade van de Kruispolder — de oude aanlegplaats waaraan de “kaai” herinnert. Een inlaag is hier wat het woord zegt: laaggelegen land <b>tussen of achter de dijken</b>, ooit uitgeschuurd bij dijkwerken en daarna aan de natuur gelaten — nat, brak en beschut. In deze kleinschalige setting gedijt een typisch Zeeuws-Vlaams gezelschap: <b>zilte graslanden</b> die bij hoge waterstand onderlopen, <b>poelen en slootjes</b> voor eenden en steltlopers, en een dijkvegetatie van zoutminnaars op de randen. In het voorjaar broeden <b>scholeksters, tureluurs en kneuen</b> in de ruigte; in de najaars- en wintermaanden is de inlaag een rustplek voor <b>watervogels</b> die van de Westerschelde-platen komen. De Kruispolder zelf — stil, oud en met de Wallen van Retranchement (kaart 2213) om de hoek — maakt het gebiedje tot meer dan de som van zijn hectaren: een stopplaats op de fietstocht tussen Zwin en Westerschelde, waar de zee nog steeds een vinger in de klei heeft.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–jun</b> (broedvogels), jul–sep (trek), okt–mrt (winterse rustvogels)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — zang en spiegelende poelen.',
 'why': ['De <b>± 3 ha inlaag</b> aan de Kruispolder-kade.', 'De <b>kaai</b> als oude aanlegplaats in de naam.', 'De <b>zilte graslanden en poelen</b>.', 'De <b>broedvogels</b>: scholekster, tureluur, kneu.', 'De <b>ligging in de stille Kruispolder</b>.'],
 'phen': ['<span class="months">Mrt–jun</span> 🎶 <b>Scholekster en tureluur</b> in broedstemming.', '<span class="months">Jul–sep</span> 🕊️ <b>Trekvogels</b> in de poelen.', '<span class="months">Okt–mrt</span> 🦆 <b>Watervogel-rust</b> uit de Schelde.', '<span class="months">Jaarrond</span> 💧 <b>Brakke wisseling</b> van nat en zout.'],
 'wild': ['💧 Kleine inlaag', '🌾 Zilte graslanden', '🐦 Scholekster-broeders', '⚓ Kruispolder-kaai', '🤫 Stille polder'],
 'trail': ['Bekijk de inlaag vanaf de <b>dijken van de Kruispolder</b>.', 'Fiets door naar de <b>Wallen van Retranchement</b> (2213) en het <b>Zwin</b> (2210).', 'Combineer met <b>Hoofdplaat</b> en <b>Nummer Eén</b> (2250).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Zicht vanaf de dijk · ⚠️ Kleine kern — niet betreden'
}, {
 'tags': ['Zeeland · in the Kruispolder near Retranchement/Breskens (Zeeuws-Vlaanderen)', 'small inlay of ± 3 ha at the Kruispolder quay · saline grasslands and pools in the lee of the old Westerschelde dike — breeding and resting ground for oystercatchers, redshanks and ducks', 'list 84 · no. 34'],
 'loc': '📍 Inlaag Kruispolderkaai, in the Kruispolder east of Retranchement — to be viewed from the dikes around the Kruispolder; combine with Het Zwin (card 2210) and the Wallen van Retranchement (2213); managed by the Zeeland Landscape Trust',
 'desc': 'In the <b>Kruispolder</b>, the old reclamation area east of <b>Retranchement</b>, lies one of the smallest reserves of the Zeeland Landscape Trust: the <b>Inlaag Kruispolderkaai</b>, ± <b>3 hectares</b> at the Kruispolder quay — the old landing place the “kaai” (quay) recalls. An inlay here is what the word says: low land <b>between or behind the dikes</b>, scoured out during dike works and left to nature — wet, brackish and sheltered. In this small-scale setting thrives a typical Zeeuws-Vlaanderen company: <b>saline grasslands</b> flooding at high water, <b>pools and ditches</b> for ducks and waders, and dike vegetation of salt lovers on the edges. In spring <b>oystercatchers, redshanks and linnets</b> breed in the rough; in autumn and winter the inlay is a resting place for <b>waterfowl</b> from the Westerschelde plates. The Kruispolder itself — quiet, old, with the Wallen van Retranchement (card 2213) around the corner — makes the little area more than the sum of its hectares: a stop on the cycle ride between Zwin and Westerschelde, where the sea still keeps a finger in the clay.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jun</b> (breeding birds), Jul–Sep (migration), Oct–Mar (wintry resting birds)<br>\n    <b>Best time of day:</b> Morning — song and mirroring pools.',
 'why': ['The <b>± 3-ha inlay</b> at the Kruispolder quay.', 'The <b>quay</b> as old landing place in the name.', 'The <b>saline grasslands and pools</b>.', 'The <b>breeding birds</b>: oystercatcher, redshank, linnet.', 'The <b>position in the quiet Kruispolder</b>.'],
 'phen': ['<span class="months">Mar–Jun</span> 🎶 <b>Oystercatcher and redshank</b> in breeding mood.', '<span class="months">Jul–Sep</span> 🕊️ <b>Migrating birds</b> in the pools.', '<span class="months">Oct–Mar</span> 🦆 <b>Waterfowl rest</b> from the Scheldt.', '<span class="months">Year-round</span> 💧 <b>Brackish change</b> of wet and salt.'],
 'wild': ['💧 Small inlay', '🌾 Saline grasslands', '🐦 Oystercatcher breeders', '⚓ Kruispolder quay', '🤫 Quiet polder'],
 'trail': ['View the inlay from the <b>dikes of the Kruispolder</b>.', 'Cycle on to the <b>Wallen van Retranchement</b> (2213) and the <b>Zwin</b> (2210).', 'Combine with <b>Hoofdplaat</b> and <b>Nummer Eén</b> (2250).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 View from the dike · ⚠️ Small core — do not enter'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2252)
mk.check()
