# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2253, 'Westzeeuwsvlaamse Dijken', {
 'tags': ['Zeeland · West-Zeeuws-Vlaanderen (rond Sluis, Zuidzande en Cadzand)', 'tientallen kilometers dijk met ± 2.000 knotbomen · het “land van de eeuwige knotbomen” — knotpopulieren en -wilgen met steenuil en holenduif; plantrechten op Sluisse Dijk, Schenkeldijk en het Noordmanswegje', 'list 84 · no. 35'],
 'loc': '📍 Bloemdijken in West-Zeeuws-Vlaanderen — dijken als de Sluisse Dijk, Schenkeldijk, de Oude Zeedijk bij Zuidzande en de Polderdijk en het Noordmanswegje bij Cadzand; per fiets te volgen; beheer Het Zeeuwse Landschap',
 'desc': 'West-Zeeuws-Vlaanderen is het <b>land van de eeuwige knotbomen</b>: bijna elke dijk draagt zijn rij geknotte koppen, die decennia en soms eeuwen lang zijn gehakt voor <b>geriefhout en brandhout</b>. Verschil met de rest van Zeeland: hier zijn veel van de knoesten <b>populieren</b> naast de algemene knotwilg — enorm brede, hoog opgaande bomen waarvan het onderhoud een werk van lange adem is. Veel knotbomen zijn beschermd omdat ze op bodem met bestemming “Natuur” of “Agrarisch met waarden” staan; Het Zeeuwse Landschap beheert in West-Zeeuws-Vlaanderen <b>tientallen kilometers dijk, samen ± 20 hectare</b>, met bij elkaar zo’n <b>2.000 knotbomen</b>, en heeft op een aantal dijken zelfs <b>plantrechten</b> verworven om ze te blijven verjongen: de <b>Sluisse Dijk, de Schenkeldijk, de Oude Zeedijk bij Zuidzande</b> en de <b>Polderdijk en het Noordmanswegje</b> bij Cadzand. Op de dijken waar knotbomen staan broeden <b>vogels die in holen nestelen</b>: de <b>steenuil</b> en de <b>holenduif</b> zijn de vaste bewoners van de oude koppen. Wie er in de winter fietst, ziet de kale knotten als silhouet tegen de lucht — en in het voorjaar het jonge hakhouw dat het eeuwenoude ritme voortzet.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jun</b> (bloemdijk-vegetatie), winter (kale knotboom-silhouetten), apr–mei (holbroeders actief)<br>\n    <b>Beste tijd van de dag:</b> Schemering — steenuilen op de dijk.',
 'why': ['De <b>± 2.000 knotbomen</b> op tientallen km dijk.', 'De <b>knotpopulieren</b> als westelijke specialiteit.', 'De <b>plantrechten</b> op vijf historische dijken.', 'De <b>steenuil en holenduif</b> in de oude koppen.', 'De <b>eeuwenlange knip-cyclus</b> als levende traditie.'],
 'phen': ['<span class="months">Mrt–mei</span> 🦉 <b>Steenuilen</b> rond de knotbomen.', '<span class="months">Mei–jun</span> 🌸 <b>Bloemdijk-vegetatie</b> in kleur.', '<span class="months">Nov–mrt</span> 🌳 <b>Kale knotten</b> als winter-silhouet.', '<span class="months">Winter</span> ✂️ <b>Knotten en hakken</b> in het winterseizoen.'],
 'wild': ['🌳 2.000 knotbomen', '🦉 Steenuil', '🐦 Holenduif', '🌾 Bloemdijken', '✂️ Knip-traditie'],
 'trail': ['Fiets de <b>dijkroutes rond Sluis en Cadzand</b>.', 'Zoek het <b>Noordmanswegje</b> en de <b>Sluisse Dijk</b>.', 'Combineer met <b>Zwin</b> (2210) en de <b>Wallen van Retranchement</b> (2213).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Dijkjes ± 4–12 km · ⚠️ Smalle dijkwegen — verkeer'
}, {
 'tags': ['Zeeland · West-Zeeuws-Vlaanderen (around Sluis, Zuidzande and Cadzand)', 'tens of kilometres of dike with ± 2,000 pollard trees · the “land of the eternal pollards” — pollard poplars and willows with little owl and stock dove; planting rights on the Sluisse Dijk, Schenkeldijk and Noordmanswegje', 'list 84 · no. 35'],
 'loc': '📍 Flower dikes in West-Zeeuws-Vlaanderen — dikes such as the Sluisse Dijk, Schenkeldijk, the Oude Zeedijk at Zuidzande and the Polderdijk and Noordmanswegje at Cadzand; to follow by bike; managed by the Zeeland Landscape Trust',
 'desc': 'West-Zeeuws-Vlaanderen is the <b>land of the eternal pollards</b>: nearly every dike carries its row of cut heads, hacked for <b>small wood and firewood</b> for decades and sometimes centuries. A difference with the rest of Zeeland: many of the gnarled trees here are <b>poplars</b> beside the common pollard willow — enormously broad, towering specimens whose maintenance is work of long breath. Many pollards are protected because they stand on soil designated “Nature” or “Agricultural with values”; the Zeeland Landscape Trust manages <b>tens of kilometres of dike in West-Zeeuws-Vlaanderen, together ± 20 hectares</b>, with some <b>2,000 pollard trees</b> in all, and has even acquired <b>planting rights</b> on a number of dikes to keep rejuvenating them: the <b>Sluisse Dijk, the Schenkeldijk, the Oude Zeedijk at Zuidzande</b> and the <b>Polderdijk and Noordmanswegje</b> at Cadzand. On dikes with pollards breed <b>birds that nest in holes</b>: the <b>little owl</b> and the <b>stock dove</b> are the permanent residents of the old heads. Cycle here in winter and you see the bare pollards as silhouettes against the sky — and in spring the young shoots continuing the centuries-old rhythm.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jun</b> (flower-dike vegetation), winter (bare pollard silhouettes), Apr–May (hole breeders active)<br>\n    <b>Best time of day:</b> Dusk — little owls on the dike.',
 'why': ['The <b>± 2,000 pollard trees</b> on tens of km of dike.', 'The <b>pollard poplars</b> as western specialty.', 'The <b>planting rights</b> on five historic dikes.', 'The <b>little owl and stock dove</b> in the old heads.', 'The <b>centuries-old cutting cycle</b> as living tradition.'],
 'phen': ['<span class="months">Mar–May</span> 🦉 <b>Little owls</b> around the pollards.', '<span class="months">May–Jun</span> 🌸 <b>Flower-dike vegetation</b> in colour.', '<span class="months">Nov–Mar</span> 🌳 <b>Bare pollards</b> as winter silhouettes.', '<span class="months">Winter</span> ✂️ <b>Cutting and hacking</b> in the winter season.'],
 'wild': ['🌳 2,000 pollards', '🦉 Little owl', '🐦 Stock dove', '🌾 Flower dikes', '✂️ Cutting tradition'],
 'trail': ['Cycle the <b>dike routes around Sluis and Cadzand</b>.', 'Seek the <b>Noordmanswegje</b> and the <b>Sluisse Dijk</b>.', 'Combine with the <b>Zwin</b> (2210) and the <b>Wallen van Retranchement</b> (2213).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Dikes ± 4–12 km · ⚠️ Narrow dike roads — traffic'
}))

C.append(mk.card(2254, 'Paulinaschor', {
 'tags': ['Zeeland · in de Westerschelde, 3 km ten noordoosten van Biervliet', 'schorrenrestant van de Braakman-monding · overgebleven na de inpoldering van de Paulinapolder (1845) — schapenweide tot de Tweede Wereldoorlog, met dammetjes tussen de geulen; zeealsem en schorrenkruid op de oeverwallen', 'list 84 · no. 36'],
 'loc': '📍 Paulinaschor, in de Westerschelde 3 km ten noordoosten van Biervliet — niet toegankelijk; goed te overzien vanaf de Scheldedijk; combineer met de Braakman (kaart 2255) en Hooge Platen (2249); beheer Het Zeeuwse Landschap',
 'desc': 'Drie kilometer ten noordoosten van <b>Biervliet</b> ligt een schor dat de geschiedenis van de hele Westerschelde-monding in zich draagt: het <b>Paulinaschor</b>, overgebleven na de <b>inpoldering van de Paulinapolder in 1845</b>. Op de plek van die polder bevond zich vroeger de <b>Hooge Plaat van Biervliet</b> — onderdeel van de uitgestrekte <b>schorren en slikken van de Braakman</b>, de zeearm die Zeeuws-Vlaanderen eeuwenlang in tweeën deelde. Wat na 1845 bleef, was een levend schor: tot na de <b>Tweede Wereldoorlog</b> diende het als <b>schapenweide</b>, en de <b>dammetjes</b> die de door getijdegeulen gescheiden schordelen verbonden, liggen er nog altijd — de voetstappen van de schaapherders in het getij. De zee blijft vormen: van het schor worden <b>stukken afgeslagen</b> met een steile overgang naar het slik, terwijl de slikken juist <b>aanwassen</b> — met velden <b>Engels slijkgras</b> die nieuwe groei beloven. Op de oeverwallen langs de geulen groeien <b>strandkweek, zeealsem en schorrenkruid</b>; in de kommen domineren <b>lamsoor, zeeaster en zeeweegbree</b>. Vogels vinden in de slikken voedsel bij eb. Het geheel is fraai te overzien vanaf de <b>Scheldedijk</b> — een schor dat verdwijnt en groeit tegelijk.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–sep</b> (zeeaster en lamsoor in bloei), sep–mrt (winterse platen en steltlopers), apr–jun (broedtijd schor)<br>\n    <b>Beste tijd van de dag:</b> Bij eb — slikken vol voedselzoekers.',
 'why': ['Het <b>restant van de Braakman-schorren</b> na 1845.', 'De <b>dammetjes</b> van de oude schapenweide.', 'De <b>afslag en aanwas</b> van schor en slik.', 'De <b>zeealsem en schorrenkruid</b> op de oeverwallen.', 'De <b>lamsoor- en zeeasterkommen</b> in late zomer.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Schorvogels</b> in broedtijd.', '<span class="months">Jul–sep</span> 🌸 <b>Zeeaster en lamsoor</b> in paarse bloei.', '<span class="months">Sep–mrt</span> 🦆 <b>Steltlopers</b> op de winterse slikken.', '<span class="months">Jaarrond</span> 🌊 <b>Getij</b> als vormgever van schor en slik.'],
 'wild': ['🌊 Schor en slik', '🐑 Schapenweide-dammetjes', '🌿 Zeealsem', '🌸 Zeeasterkomen', '🦆 Slikvogels'],
 'trail': ['Overzicht vanaf de <b>Scheldedijk</b> bij Biervliet.', 'Combineer met de <b>Braakman</b> (2255) en <b>Hooge Platen</b> (2249).', 'Kies <b>eb</b> voor de fouragerende vogels.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Uitzicht vanaf de dijk · ⚠️ Buitendijks — niet betreden'
}, {
 'tags': ['Zeeland · in the Westerschelde, 3 km northeast of Biervliet', 'marsh remnant of the Braakman mouth · left over after the embankment of the Paulinapolder (1845) — sheep grazing until the Second World War, with little dams between the channels; sea wormwood and saltmarsh plants on the levees', 'list 84 · no. 36'],
 'loc': '📍 Paulinaschor, in the Westerschelde 3 km northeast of Biervliet — not accessible; well visible from the Scheldedijk; combine with the Braakman (card 2255) and Hooge Platen (2249); managed by the Zeeland Landscape Trust',
 'desc': 'Three kilometres northeast of <b>Biervliet</b> lies a marsh carrying the history of the whole Westerschelde mouth: the <b>Paulinaschor</b>, left over after the <b>embankment of the Paulinapolder in 1845</b>. On the spot of that polder formerly lay the <b>Hooge Plaat van Biervliet</b> — part of the vast <b>marshes and mudflats of the Braakman</b>, the sea arm that divided Zeeuws-Vlaanderen for centuries. What remained after 1845 was a living marsh: until after the <b>Second World War</b> it served as <b>sheep grazing</b>, and the <b>little dams</b> connecting the marsh parts separated by tidal channels still lie there — the shepherds’ footsteps in the tide. The sea keeps shaping: pieces of the marsh are <b>washed away</b> with a steep transition to the mudflat, while the flats <b>accrete</b> — with fields of <b>English scurvygrass</b> promising new growth. On the levees along the channels grow <b>sea couch, sea wormwood and seablite</b>; in the pans <b>sea lavender, sea aster and sea plantain</b> dominate. Birds find food in the flats at low tide. The whole is finely visible from the <b>Scheldedijk</b> — a marsh disappearing and growing at once.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Sep</b> (sea aster and lavender in bloom), Sep–Mar (wintry flats and waders), Apr–Jun (marsh breeding season)<br>\n    <b>Best time of day:</b> At low tide — flats full of feeders.',
 'why': ['The <b>remnant of the Braakman marshes</b> after 1845.', 'The <b>little dams</b> of the old sheep grazing.', 'The <b>erosion and accretion</b> of marsh and flat.', 'The <b>sea wormwood and seablite</b> on the levees.', 'The <b>sea lavender and aster pans</b> in late summer.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Marsh birds</b> in breeding time.', '<span class="months">Jul–Sep</span> 🌸 <b>Sea aster and lavender</b> in purple bloom.', '<span class="months">Sep–Mar</span> 🦆 <b>Waders</b> on the wintry flats.', '<span class="months">Year-round</span> 🌊 <b>Tide</b> as shaper of marsh and flat.'],
 'wild': ['🌊 Marsh and mudflat', '🐑 Sheep-grazing dams', '🌿 Sea wormwood', '🌸 Sea aster pans', '🦆 Flat birds'],
 'trail': ['Overview from the <b>Scheldedijk</b> at Biervliet.', 'Combine with the <b>Braakman</b> (2255) and <b>Hooge Platen</b> (2249).', 'Choose <b>low tide</b> for the foraging birds.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 View from the dike · ⚠️ Outer-dike — do not enter'
}, n2k='Het Paulinaschor ligt in het Natura 2000-gebied Westerschelde & Saeftinghe — samen met de Hooge Platen en de Zuidgors vormt het de beschermde getijdenmonding van de Westerschelde.', n2k_en='The Paulinaschor lies in the Natura 2000 site Westerschelde & Saeftinghe — with the Hooge Platen and the Zuidgors it forms the protected tidal mouth of the Westerschelde.'))

C.append(mk.card(2255, 'Braakman', {
 'tags': ['Zeeland · ten noorden van de weg Hoek–Biervliet (Zeeuws-Vlaanderen)', 'natuurgebied in de inpolderde Braakman (1952) · Braakman-Noord met Westgeul-bos, spaarbekkens en struinrecreatie; Braakman-Zuid: ± 50 jaar oud bos langs het Isabellakanaal — het restant van de oude zeearm', 'list 84 · no. 37'],
 'loc': '📍 De Braakman, ten noorden van de weg Hoek–Biervliet — wandel-, fiets- en ruiterpaden, rolstoelpad, uitkijkpunten en picknicktafels; hondenloslooppercelen; parkeerterrein met wandelroute bij Braakman-Zuid; beheer Staatsbosbeheer',
 'desc': 'De <b>Braakman</b> was eeuwenlang de grote <b>zeearm</b> die Zeeuws-Vlaanderen in tweeën deelde — de oude zeeverbinding van IJzendijke en Biervliet. Met de <b>inpoldering van de grote Braakmanpolder in 1952</b> verdween de open monding; wat bleef was een nieuw land dat langzaam zijn natuur vond. <b>Braakman-Noord</b> is vandaag de trots van Staatsbosbeheer Zeeuws-Vlaanderen: op de nieuwe grond werden <b>landbouwgronden, spaarbekkens voor de drinkwatervoorziening en een recreatieterrein</b> aangelegd, langs de <b>Westgeul</b> — een restant van de oude geul — werd <b>bos ingeplant</b> en gronden werden als natuurgebied aangewezen. Je kunt er naar hartenlust <b>wandelen en struinen</b>, over wandel- en fietspaden, een <b>rolstoelpad</b>, langs <b>uitkijkpunten</b> en informatiezuilen; kinderen ravotten in de <b>natuurlijke speelzone</b> en op het Kabouterpad. <b>Braakman-Zuid</b> is een <b>bosgebied van ± 50 jaar oud</b>, aangeplant met eik, beuk, haagbeuk, populier, spar en den (in 2011 uitgebreid), aan beide zijden van het <b>Isabellakanaal</b> dat water uit België afvoert naar de <b>Braakmankreek</b> — twee bruggetjes overspannen het. Voor liefhebbers van planten, paddenstoelen en insecten is er altijd wat te beleven: het jonge bos op zeeklei ontwikkelt zich ieder jaar verder van polder naar bos.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (voorjaarsbos en broedvogels), jul–aug (speel- en struinseizoen), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door het jonge bos.',
 'why': ['De <b>inpoldering van 1952</b> als geboorte van het gebied.', 'De <b>Westgeul</b> als levend restant van de zeearm.', 'De <b>spaarbekkens voor drinkwater</b> in het noorden.', 'Het <b>± 50-jarige bos</b> van Braakman-Zuid.', 'Het <b>Isabellakanaal</b> met zijn twee bruggetjes.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Voorjaarsontwikkeling</b> in het jonge bos.', '<span class="months">Apr–jun</span> 🎶 <b>Broedvogels</b> van bos en riet.', '<span class="months">Jun–aug</span> 🧚 <b>Struin- en speelseizoen</b> op zijn top.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> op zeeklei.'],
 'wild': ['🌊 Oude zeearm', '🌲 Jong bos op klei', '💧 Spaarbekkens', '🧚 Speel- en struingebied', '🌉 Isabellakanaal'],
 'trail': ['Struin <b>vrij rond</b> in Braakman-Noord langs de Westgeul.', 'Loop de <b>wandelroute vanaf het parkeerterrein</b> in Braakman-Zuid.', 'Gebruik het <b>rolstoelpad</b> en de uitkijkpunten.'],
 'foot': '🐕 Loslooppercelen aanwezig · 💶 Gratis · 🚶 Rondes ± 3–10 km · 🅿️ Parkeerterreinen Noord en Zuid'
}, {
 'tags': ['Zeeland · north of the Hoek–Biervliet road (Zeeuws-Vlaanderen)', 'nature area in the embanked Braakman (1952) · Braakman-Noord with Westgeul wood, storage basins and roaming recreation; Braakman-Zuid: ± 50-year-old wood along the Isabellakanaal — the remnant of the old sea arm', 'list 84 · no. 37'],
 'loc': '📍 De Braakman, north of the Hoek–Biervliet road — walking, cycling and bridle paths, wheelchair path, viewpoints and picnic tables; dog-exercise parcels; car park with walking route at Braakman-Zuid; managed by Staatsbosbeheer',
 'desc': 'The <b>Braakman</b> was for centuries the great <b>sea arm</b> dividing Zeeuws-Vlaanderen in two — the old sea link of IJzendijke and Biervliet. With the <b>embankment of the great Braakmanpolder in 1952</b> the open mouth vanished; what remained was new land slowly finding its nature. <b>Braakman-Noord</b> is today the pride of Staatsbosbeheer Zeeuws-Vlaanderen: on the new ground <b>farmland, storage basins for the drinking-water supply and a recreation area</b> were laid out, wood was planted along the <b>Westgeul</b> — a remnant of the old channel — and grounds were designated as nature. You can <b>walk and roam</b> to your heart’s content, on foot and cycle paths, a <b>wheelchair path</b>, past <b>viewpoints</b> and information pillars; children romp in the <b>natural play zone</b> and on the gnome path. <b>Braakman-Zuid</b> is a <b>woodland ± 50 years old</b>, planted with oak, beech, hornbeam, poplar, spruce and pine (extended in 2011), on both sides of the <b>Isabellakanaal</b> carrying water from Belgium to the <b>Braakmankreek</b> — two little bridges span it. For lovers of plants, fungi and insects there is always something: the young wood on sea clay develops from polder to forest a little more each year.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring wood and breeding birds), Jul–Aug (play and roaming season), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — light through the young wood.',
 'why': ['The <b>embankment of 1952</b> as the area’s birth.', 'The <b>Westgeul</b> as living remnant of the sea arm.', 'The <b>drinking-water storage basins</b> in the north.', 'The <b>± 50-year-old wood</b> of Braakman-Zuid.', 'The <b>Isabellakanaal</b> with its two little bridges.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring development</b> in the young wood.', '<span class="months">Apr–Jun</span> 🎶 <b>Breeding birds</b> of wood and reed.', '<span class="months">Jun–Aug</span> 🧚 <b>Roaming and play season</b> at its peak.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on sea clay.'],
 'wild': ['🌊 Old sea arm', '🌲 Young wood on clay', '💧 Storage basins', '🧚 Play and roaming area', '🌉 Isabellakanaal'],
 'trail': ['Roam <b>freely</b> in Braakman-Noord along the Westgeul.', 'Walk the <b>route from the car park</b> in Braakman-Zuid.', 'Use the <b>wheelchair path</b> and the viewpoints.'],
 'foot': '🐕 Dog-exercise parcels available · 💶 Free · 🚶 Loops ± 3–10 km · 🅿️ Car parks North and South'
}))

C.append(mk.card(2256, 'Toorenbos', {
 'tags': ['Zeeland · ten noorden van Hoek (Zeeuws-Vlaanderen)', 'jong bos tussen Voorste en Achterste Kreek · in ± 30 jaar uitgegroeid tot gevarieerd, dichtbegroeid bos met verharde paden, open plekken en picknickbanken — het groene hart van het Hoekse kreeklandschap', 'list 84 · no. 38'],
 'loc': '📍 Toorenbos, ten noorden van de kom van Hoek — ommetje Hoek van ± 5 km combineert Voorste Kreek en Toorenbos; verharde paden en picknickbanken; combineer met de Braakman (kaart 2255)',
 'desc': 'Ten noorden van het dorp <b>Hoek</b>, in het kreeklandschap van oostelijk Zeeuws-Vlaanderen, ligt een bos dat er had kunnen staan sinds mensenheugenis — maar jonger is dan het lijkt: het <b>Toorenbos</b>, in ± <b>30 jaar</b> uitgegroeid tot een <b>gevarieerd, dichtbegroeid bos</b>. De omgeving bepaalt het decor: ten westen ligt de <b>Voorste Kreek</b>, ten oosten de <b>Achterste Kreek</b> — twee watergangen die herinneren aan de oude Braakman-monding — en het bos ertussen vormt het groene hart van het gebied. Voor wandelaars is het aangenaam geregeld: <b>verharde paden</b>, <b>open plekken</b> en <b>picknickbanken</b> maken het geschikt voor een ommetje met de kinderwagen zo goed als voor een stille wandeling tussen de dichte stammen. In het voorjaar zingen de eerste zangvogels hier eerder dan op de open polders; in de herfst is het jonge bos al rijk aan paddenstoelen op het gevallen blad. Het klassieke <b>ommetje Hoek</b> (± 5 km) combineert de Voorste Kreek met een ronde door het Toorenbos — de ideale manier om het kreek- en boslandschap van Hoek in één wals te zien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels), mei (jong groen), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht en zang in het jonge bos.',
 'why': ['Het <b>jonge bos van ± 30 jaar</b> tussen de kreken.', 'De <b>Voorste en Achterste Kreek</b> als buren.', 'De <b>verharde paden en picknickbanken</b>.', 'Het <b>ommetje Hoek</b> als klassieke ronde.', 'De <b>ligging bij de Braakman</b> (kaart 2255).'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Jong groen</b> tussen kreek en bos.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogelkoor</b> in de vroege ochtend.', '<span class="months">Jun–aug</span> 🌳 <b>Koelte</b> op de warme dagen.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> op blad en stam.'],
 'wild': ['🌲 Jong bos', '💧 Voorste en Achterste Kreek', '🧺 Picknickplekken', '🐦 Zangvogels', '🚶 Ommetje Hoek'],
 'trail': ['Loop het <b>ommetje Hoek</b> (± 5 km) langs Voorste Kreek en Toorenbos.', 'Gebruik de <b>picknickbanken</b> op de open plekken.', 'Combineer met de <b>Braakman</b> (2255).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Ommetje ± 5 km · 🧺 Picknickbanken aanwezig'
}, {
 'tags': ['Zeeland · north of Hoek (Zeeuws-Vlaanderen)', 'young wood between Voorste and Achterste Kreek · grown in ± 30 years into a varied, dense wood with paved paths, clearings and picnic benches — the green heart of the Hoek creek landscape', 'list 84 · no. 38'],
 'loc': '📍 Toorenbos, north of the village of Hoek — the ± 5-km “ommetje Hoek” combines the Voorste Kreek and the Toorenbos; paved paths and picnic benches; combine with the Braakman (card 2255)',
 'desc': 'North of the village of <b>Hoek</b>, in the creek landscape of eastern Zeeuws-Vlaanderen, lies a wood that might have stood there time out of mind — but is younger than it looks: the <b>Toorenbos</b>, grown in ± <b>30 years</b> into a <b>varied, dense wood</b>. The surroundings set the scene: to the west lies the <b>Voorste Kreek</b>, to the east the <b>Achterste Kreek</b> — two waterways recalling the old Braakman mouth — and the wood between them forms the area’s green heart. Walkers are well served: <b>paved paths</b>, <b>clearings</b> and <b>picnic benches</b> make it fit for a stroll with the pram as much as for a silent walk between the dense trunks. In spring the first songbirds sing here earlier than on the open polders; in autumn the young wood is already rich in fungi on the fallen leaves. The classic <b>ommetje Hoek</b> (± 5 km) combines the Voorste Kreek with a round through the Toorenbos — the ideal way to see Hoek’s creek and wood landscape in one sweep.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds), May (young green), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — light and song in the young wood.',
 'why': ['The <b>young wood of ± 30 years</b> between the creeks.', 'The <b>Voorste and Achterste Kreek</b> as neighbours.', 'The <b>paved paths and picnic benches</b>.', 'The <b>ommetje Hoek</b> as classic round.', 'The <b>position by the Braakman</b> (card 2255).'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Young green</b> between creek and wood.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbird chorus</b> in the early morning.', '<span class="months">Jun–Aug</span> 🌳 <b>Cool shade</b> on warm days.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> on leaf and trunk.'],
 'wild': ['🌲 Young wood', '💧 Voorste and Achterste Kreek', '🧺 Picnic spots', '🐦 Songbirds', '🚶 Ommetje Hoek'],
 'trail': ['Walk the <b>ommetje Hoek</b> (± 5 km) along Voorste Kreek and Toorenbos.', 'Use the <b>picnic benches</b> in the clearings.', 'Combine with the <b>Braakman</b> (2255).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loop ± 5 km · 🧺 Picnic benches available'
}))

C.append(mk.card(2257, 'Wemeldingse Bos', {
 'tags': ['Zeeland · bij Wemeldinge (Zuid-Beveland, aan de Oosterschelde)', 'bos van Staatsbosbeheer achter de zeedijk · populieren die worden uitgedund voor variatie — hondenloslooproute; de overzijde van de dijk is Nationaal Park Oosterschelde', 'list 85 · no. 1'],
 'loc': '📍 Wemeldingse Bos, ten zuiden van Wemeldinge achter de zeedijk (Hogeweg als oriëntatiepunt) — wandelpaden en hondenloslooproute; over de dijk: Oosterschelde-schorren; beheer Staatsbosbeheer',
 'desc': 'Achter de zeedijk van <b>Wemeldinge</b>, waar de Oosterschelde het land raakt, ligt het <b>Wemeldingse Bos</b> — het bos van het dorp, beheerd door <b>Staatsbosbeheer</b> en in de loop van de jaren gegroeid tot een volwaardig wandelbos. Het gezicht wordt bepaald door <b>populieren</b>, die in opdracht van de beheerder <b>worden uitgedund</b>: bomen verdwijnen om ruimte te maken voor de groei van hun buren, en in de ontstane gaten schieten nieuwe bomen op — waardoor <b>meer variatie in leeftijd</b> ontstaat en andere planten zich door licht en ruimte beter ontwikkelen. Zo wordt het bos ook aantrekkelijker voor dieren; voorafgaand aan elke dunning wordt getoetst waar bijzondere soorten voorkomen, en die plekken worden ontzien. Wat het bos extra aangenaam maakt: er loopt een <b>hondenloslooproute</b> — een van de weinige in Zuid-Beveland waar de hond het hele jaar onder appèl mag loslopen. En wie de zeedijk oversteekt, wisselt het bos in één stap voor de <b>schorren en platen van de Oosterschelde</b> (Nationaal Park): bos achter, getij voor — de volledige Zeeuwse ervaring binnen één dijklengte.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels en jong groen), jul–aug (koel bos aan de Schelde), sep–okt (herfstkleur)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — zang in het bos, eb buiten.',
 'why': ['Het <b>dorpsbos van Wemeldinge</b> achter de zeedijk.', 'De <b>uitdunning</b> als beleid van variatie.', 'De <b>hondenloslooproute</b> als zeldzaamheid.', 'De <b>ligging aan de Oosterschelde</b> (Nationaal Park).', 'De <b>populieren</b> als snelle bosbouwers.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Voorjaarsflora</b> op de bosbodem.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> tussen populieren.', '<span class="months">Jun–aug</span> 🌳 <b>Schaduw</b> achter de dijk.', '<span class="months">Sep–okt</span> 🍂 <b>Herfstkleur</b> van de populieren.'],
 'wild': ['🌲 Populierenbos', '🐕 Hondenloslooproute', '🌊 Oosterschelde-dijk', '🐦 Bosvogels', '🚶 Wandelnetwerk'],
 'trail': ['Wandel de <b>paden van het Wemeldingse Bos</b>.', 'Laat de hond in de <b>loslooproute</b> (onder appèl).', 'Steek de <b>zeedijk</b> over naar de Oosterschelde-schorren.'],
 'foot': '🐕 Loslooproute in delen van het bos · 💶 Gratis · 🚶 Rondes ± 2–5 km · 🅿️ Parkeren bij Wemeldinge/Hogeweg'
}, {
 'tags': ['Zeeland · near Wemeldinge (Zuid-Beveland, on the Oosterschelde)', 'Staatsbosbeheer wood behind the sea dike · poplars being thinned for variation — dog-exercise route; across the dike lies the Oosterschelde National Park', 'list 85 · no. 1'],
 'loc': '📍 Wemeldingse Bos, south of Wemeldinge behind the sea dike (Hogeweg as landmark) — footpaths and dog-exercise route; across the dike: Oosterschelde marshes; managed by Staatsbosbeheer',
 'desc': 'Behind the sea dike of <b>Wemeldinge</b>, where the Oosterschelde touches the land, lies the <b>Wemeldingse Bos</b> — the village wood, managed by <b>Staatsbosbeheer</b> and grown over the years into a full walking wood. Its face is set by <b>poplars</b>, which are being <b>thinned</b> on the manager’s orders: trees are removed to give their neighbours room to grow, and in the gaps new trees shoot up — creating <b>more variation in age</b> and allowing other plants to develop better through light and space. Thus the wood becomes more attractive to animals too; before every thinning a survey is made of where special species occur, and those spots are spared. What makes the wood extra pleasant: a <b>dog-exercise route</b> runs through it — one of the few in Zuid-Beveland where dogs may run free year-round under control. And cross the sea dike and you swap the wood in one step for the <b>marshes and plates of the Oosterschelde</b> (National Park): wood behind, tide in front — the complete Zeeland experience within one dike’s length.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds and young green), Jul–Aug (cool wood by the Scheldt), Sep–Oct (autumn colour)<br>\n    <b>Best time of day:</b> Morning — song in the wood, low tide outside.',
 'why': ['The <b>village wood of Wemeldinge</b> behind the sea dike.', 'The <b>thinning</b> as policy of variation.', 'The <b>dog-exercise route</b> as rarity.', 'The <b>position on the Oosterschelde</b> (National Park).', 'The <b>poplars</b> as fast forest builders.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring flora</b> on the forest floor.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> among the poplars.', '<span class="months">Jun–Aug</span> 🌳 <b>Shade</b> behind the dike.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn colour</b> of the poplars.'],
 'wild': ['🌲 Poplar wood', '🐕 Dog-exercise route', '🌊 Oosterschelde dike', '🐦 Woodland birds', '🚶 Walking network'],
 'trail': ['Walk the <b>paths of the Wemeldingse Bos</b>.', 'Let the dog into the <b>exercise route</b> (under control).', 'Cross the <b>sea dike</b> to the Oosterschelde marshes.'],
 'foot': '🐕 Exercise route in parts of the wood · 💶 Free · 🚶 Loops ± 2–5 km · 🅿️ Parking at Wemeldinge/Hogeweg'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2257)
mk.check()
