# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2273, 'Zoomland', {
 'tags': ['Noord-Brabant · ten oosten van Bergen op Zoom (Brabantse Wal)', 'landgoed van ± 308 ha Brabants Landschap · gegroeid uit vier landgoederen van ± 1700 — met de Zeezuiper, een middeleeuwse turfplas die sinds de watermaatregelen weer vol staat; visarend op de trek', 'list 85 · no. 17'],
 'loc': '📍 Zoomland, ten oosten van Bergen op Zoom (toegang via de Mastendreef) — oude lanen en wandelpaden; combineer met Lievensberg (kaart 2274) en de Bergse Heide (2272); beheer Brabants Landschap',
 'desc': 'Ten oosten van <b>Bergen op Zoom</b> ligt een landgoed dat uit vier delen is samengegroeid: <b>Zoomland</b>, ± <b>308 hectare</b> van het <b>Brabants Landschap</b>, ontstaan uit de zeventiende- en achttiende-eeuwse landgoederen <b>Weltevreden (Klein Gemini), Groot Gemini, Goeree (Hengstmere) en ’s-Heeren Plantage</b> — gesticht rond <b>1700</b> door Bergse notabelen die boven op de Wal een buitenplaats wilden. Van al die goederen zijn de sporen nog leesbaar: <b>lanen, eikenhakhout, houtwallen en grachten</b> bepalen het patroon van wat nu één aaneengesloten wandellandgoed is. Middenin ligt de verrassing van het gebied: de <b>Zeezuiper</b>, de rest van een middeleeuws moeras waar vanaf de <b>13e eeuw turf</b> werd gewonnen — na het weggraven van het veen bleef een plas achter “die kon zuipen als de zee”. Door ontginning en ontwatering was daar eind vorige eeuw weinig van over, maar Brabants Landschap <b>leidde sloten om en hield water vast</b>: de Zeezuiper liep weer vol, en nu staan de bomen er tot in de stam in het water — <b>luguber en tegelijk majestueus</b>. Sindsdien komt de <b>visarend</b> op bezoek, in <b>april en september</b> op de trek. Daarbuiten dwalen bezoekers over kilometers <b>oude lanen</b> — het klassieke Bergse ommetje, vlak achter de stad.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (voorjaarsbos en zang), apr + sep (visarend op trek), okt–nov (herfstlicht op de Zeezuiper)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegeling in de Zeezuiper.',
 'why': ['De <b>vier oude landgoederen</b> uit ± 1700.', 'De <b>Zeezuiper</b> als middeleeuwse turfplas.', 'De <b>doodhout-scenografie</b> van staande verdrinkende bomen.', 'De <b>visarend</b> in april en september.', 'De <b>oude lanen</b> over kilometers.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in de lanen.', '<span class="months">Apr/sep</span> 🦅 <b>Visarend</b> boven de Zeezuiper.', '<span class="months">Jun–aug</span> 🦗 <b>Zomer</b> in de houtwallen.', '<span class="months">Okt–nov</span> 🍂 <b>Herfsttooi</b> over landgoed en plas.'],
 'wild': ['🌳 Landgoedbossen', '💧 Zeezuiper', '🦅 Visarend-trek', '🛤️ Oude lanen', '🍂 Eikenhakhout'],
 'trail': ['Wandel de <b>lanen van Zoomland</b> vanaf de Mastendreef.', 'Zoek de <b>Zeezuiper</b> met de verdrinkende bomen.', 'Combineer met <b>Lievensberg</b> (2274) en de <b>Bergse Heide</b> (2272).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–8 km · 🅿️ Parkeren aan de Mastendreef'
}, {
 'tags': ['North Brabant · east of Bergen op Zoom (Brabantse Wal)', '± 308-ha Brabants Landschap estate · grown from four estates of ± 1700 — with the Zeezuiper, a medieval peat lake refilled since the water measures; osprey on migration', 'list 85 · no. 17'],
 'loc': '📍 Zoomland, east of Bergen op Zoom (access via the Mastendreef) — old lanes and footpaths; combine with Lievensberg (card 2274) and the Bergse Heide (2272); managed by Brabants Landschap',
 'desc': 'East of <b>Bergen op Zoom</b> lies an estate grown together from four parts: <b>Zoomland</b>, ± <b>308 hectares</b> of <b>Brabants Landschap</b>, arising from the seventeenth- and eighteenth-century estates <b>Weltevreden (Klein Gemini), Groot Gemini, Goeree (Hengstmere) and ’s-Heeren Plantage</b> — founded around <b>1700</b> by Bergen notables wanting a country seat on top of the Wal. Of all those estates the traces remain legible: <b>lanes, oak coppice, hedges and moats</b> set the pattern of what is now one continuous walking estate. At its centre lies the area’s surprise: the <b>Zeezuiper</b>, remnant of a medieval marsh where <b>peat was cut from the 13th century</b> — once the peat was dug off, a lake remained “that could drink like the sea”. By the end of the last century little of it was left, but Brabants Landschap <b>redirected ditches and held the water</b>: the Zeezuiper filled again, and trees now stand to their trunks in the water — <b>eerie and majestic at once</b>. Since then the <b>osprey</b> visits, in <b>April and September</b> on migration. Beyond that, visitors wander kilometres of <b>old lanes</b> — the classic Bergen walk, just behind town.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring wood and song), Apr + Sep (osprey on migration), Oct–Nov (autumn light on the Zeezuiper)<br>\n    <b>Best time of day:</b> Morning — mirror in the Zeezuiper.',
 'why': ['The <b>four old estates</b> from ± 1700.', 'The <b>Zeezuiper</b> as medieval peat lake.', 'The <b>dead-wood scenery</b> of drowning trees.', 'The <b>osprey</b> in April and September.', 'The <b>old lanes</b> over kilometres.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the lanes.', '<span class="months">Apr/Sep</span> 🦅 <b>Osprey</b> over the Zeezuiper.', '<span class="months">Jun–Aug</span> 🦗 <b>Summer</b> in the hedges.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn colour</b> over estate and lake.'],
 'wild': ['🌳 Estate woods', '💧 Zeezuiper', '🦅 Osprey migration', '🛤️ Old lanes', '🍂 Oak coppice'],
 'trail': ['Walk the <b>lanes of Zoomland</b> from the Mastendreef.', 'Seek the <b>Zeezuiper</b> with its drowning trees.', 'Combine with <b>Lievensberg</b> (2274) and the <b>Bergse Heide</b> (2272).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–8 km · 🅿️ Parking at the Mastendreef'
}, n2k='Zoomland ligt binnen het Natura 2000-gebied Brabantse Wal — het uitgestrekte natuurgebied op de steilrand tussen de Brabantse zandgronden en de Zeeuwse zeeklei.', n2k_en='Zoomland lies within the Natura 2000 site Brabantse Wal — the extensive nature area on the steep edge between the Brabant sands and the Zeeland sea clay.'))

C.append(mk.card(2274, 'Lievensberg', {
 'tags': ['Noord-Brabant · ten oosten van de A58 bij Bergen op Zoom (Brabantse Wal)', '127 ha bosrijk landgoed met heidetuin · loof- en naaldbos, vaste stuifduintjes en ± 25 ha heide — met 30 soorten heide in de tuin, blotevoetenpad en Natuurpoort', 'list 85 · no. 18'],
 'loc': '📍 Lievensberg, ten oosten van de A58 bij Bergen op Zoom (Balsedreef / Natuurpoort Boslustweg) — parkachtige beukenlanen, heidetuin en vijver; combineer met Zoomland (kaart 2273) noordwaarts en Groot Molenbeek (2277) zuidwaarts',
 'desc': 'Achter de <b>A58</b>, een steenworp van Bergen op Zoom, ligt de <b>Lievensberg</b>: <b>127 hectare</b> bosrijk landgoed van <b>loof- en naaldbos</b>, vastgelegde <b>stuifduintjes</b> en een ± <b>25 hectare</b> groot <b>heideveld</b> — het stadswandelpark van Bergen bij uitstek. De entree via de <b>Balsedreef</b> is parkachtig aangelegd met <b>zware beukenlanen</b>, picknickplaatsen, een <b>vijver</b> en de beroemde <b>heidetuin</b>, waar maar liefst <b>30 soorten heide</b> bij elkaar staan — van struikhei tot zeldzame cultivars, een levende collectie op een klein oppervlak. Wie de lanen volgt, klimt ongemerkt de <b>Wal</b> op: de stuifduintjes in het bos zijn vastgelegde resten van het zand dat eeuwenlang over de heide joeg. Het gebied is slim ingericht voor bezoekers: er is een <b>blotevoetenpad</b>, er staat kunst langs de routes, en aan de Boslustweg wacht <b>Natuurpoort Lievensberg</b> als startpunt met het Natuurpodium. Een deel van het gebied is <b>waterwingebied</b> en ligt binnen het <b>Natura 2000-gebied Brabantse Wal</b>; de levendbarende hagedis zont er op de zandpaden. De Lievensberg is het stadsgroen dat geen stadspark is — natuur met geschiedenis, op loopafstand van de Brabantse Wal-rand.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide paars, heidetuin op top), apr–jun (zangvogels), mrt–okt (blotevoetenpad-seizoen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — zon op de beukenlanen.',
 'why': ['De <b>heidetuin met 30 soorten heide</b>.', 'De <b>parkachtige Balsedreef</b> met beukenlanen.', 'De <b>stuifduintjes</b> als Wal-relicten.', 'Het <b>blotevoetenpad</b> en de Natuurpoort.', 'De <b>25 ha heide</b> naast stad en bos.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Zangvogels</b> in de lanen.', '<span class="months">Apr–sep</span> 🦎 <b>Levendarende hagedis</b> op de zandpaden.', '<span class="months">Aug–sep</span> 💜 <b>Heide paars</b> — veld en tuin.', '<span class="months">Okt–nov</span> 🍂 <b>Beukenherfst</b> in het park.'],
 'wild': ['💜 Heidetuin', '🌳 Beukenlanen', '🏔️ Stuifduintjes', '🦎 Levendarende hagedis', '🦶 Blotevoetenpad'],
 'trail': ['Start bij <b>Natuurpoort Lievensberg</b> (Boslustweg).', 'Bezoek de <b>heidetuin en vijver</b> aan de Balsedreef.', 'Combineer met <b>Zoomland</b> (2273) en <b>Groot Molenbeek</b> (2277).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 2–6 km · 🅿️ Parkeren bij de Natuurpoort'
}, {
 'tags': ['North Brabant · east of the A58 near Bergen op Zoom (Brabantse Wal)', '127-ha wooded estate with heather garden · broadleaf and conifer wood, fixed dunelets and ± 25 ha of heath — with 30 heather species in the garden, barefoot path and Nature Gate', 'list 85 · no. 18'],
 'loc': '📍 Lievensberg, east of the A58 near Bergen op Zoom (Balsedreef / Nature Gate Boslustweg) — park-like beech lanes, heather garden and pond; combine with Zoomland (card 2273) to the north and Groot Molenbeek (2277) to the south',
 'desc': 'Behind the <b>A58</b>, a stone’s throw from Bergen op Zoom, lies the <b>Lievensberg</b>: <b>127 hectares</b> of wooded estate with <b>broadleaf and conifer wood</b>, fixed <b>dunelets</b> and a ± <b>25-hectare</b> <b>heath field</b> — the town’s walking park par excellence. The entrance by the <b>Balsedreef</b> is laid out park-like with <b>heavy beech lanes</b>, picnic spots, a <b>pond</b> and the famous <b>heather garden</b>, where no fewer than <b>30 heather species</b> stand together — from ling to rare cultivars, a living collection on a small surface. Follow the lanes and you climb the <b>Wal</b> unnoticed: the dunelets in the wood are fixed remains of the sand that raced over the heath for centuries. The area is smartly arranged for visitors: there is a <b>barefoot path</b>, art stands along the routes, and at the Boslustweg <b>Nature Gate Lievensberg</b> awaits as starting point with its Nature Podium. Part of the area is a <b>water extraction site</b> within the <b>Natura 2000 site Brabantse Wal</b>; the viviparous lizard basks on the sandy paths. The Lievensberg is town green that is no town park — nature with history, within walking distance of the Wal’s edge.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather purple, garden at its peak), Apr–Jun (songbirds), Mar–Oct (barefoot-path season)<br>\n    <b>Best time of day:</b> Morning — sun on the beech lanes.',
 'why': ['The <b>heather garden with 30 species</b>.', 'The <b>park-like Balsedreef</b> with beech lanes.', 'The <b>dunelets</b> as Wal relics.', 'The <b>barefoot path</b> and Nature Gate.', 'The <b>25 ha of heath</b> beside town and wood.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Songbirds</b> in the lanes.', '<span class="months">Apr–Sep</span> 🦎 <b>Viviparous lizard</b> on the sandy paths.', '<span class="months">Aug–Sep</span> 💜 <b>Heather purple</b> — field and garden.', '<span class="months">Oct–Nov</span> 🍂 <b>Beech autumn</b> in the park.'],
 'wild': ['💜 Heather garden', '🌳 Beech lanes', '🏔️ Dunelets', '🦎 Viviparous lizard', '🦶 Barefoot path'],
 'trail': ['Start at <b>Nature Gate Lievensberg</b> (Boslustweg).', 'Visit the <b>heather garden and pond</b> at the Balsedreef.', 'Combine with <b>Zoomland</b> (2273) and <b>Groot Molenbeek</b> (2277).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 2–6 km · 🅿️ Parking at the Nature Gate'
}))

C.append(mk.card(2275, 'Molenzicht', {
 'tags': ['Noord-Brabant · bossen ten westen van Bergen op Zoom (richting Wouwse Plantage)', 'bosgebied met molens-uitzicht op de Wal · wandel- en ruiterland tussen Bergen op Zoom en de Wouwse Plantage — de naam verwijst naar het zicht op de standerdmolen en poldermolens aan de voet van de Wal', 'list 85 · no. 19'],
 'loc': '📍 Molenzicht, bosrijk gebied ten westen van Bergen op Zoom richting de Wouwse Plantage — ruiterpaden en wandelroutes; combineer met de Wouwse Plantage (kaart 2276) en Zoomland (2273)',
 'desc': 'Wie van Bergen op Zoom westwaarts de <b>bossen van de Wal</b> in loopt, komt door gebied dat zijn naam aan het uitzicht dankt: <b>Molenzicht</b> — het land waar je, kijkend over de rand van de hoge zandgronden, de <b>molens</b> van de lage polders ziet draaien. Aan de voet van de Brabantse Wal staan er nog steeds: de <b>standerdmolen van de Wouwse Plantage</b> en de poldermolens van de Zeeuwse kleilanden erachter — eeuwenlang de machines die dit druipnatte land leefbaar hielden, nu monumenten in het landschap. Het gebied zelf is <b>wandel- en rijland</b>: paden door productiebos en lanen, met de ruiterpaden waarvoor de Bergse bossen bekend staan (de manege aan de Boslustweg zit om de hoek). In het voorjaar zingen tuinfluiter en tjiftjaf in de opgaande randen; in de herfst liggen de paden vol beukenblad; en altijd is er, ergens tussen de stammen, een <b>kijkje op de polders</b> — het vlakke land achter de Wal, waar de molens de horizon markeren. Molenzicht is de kaart voor wie de overgang van bos naar polder wil voelen: eerst hoogte, dan zicht, dan vlakte.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zang in de bosranden), sep–okt (herfstpaden), jaarrond (molens in het zicht)<br>\n    <b>Beste tijd van de dag:</b> Middag — molens in het zonlicht over de polders.',
 'why': ['De <b>molens aan de voet van de Wal</b> als naamgever.', 'De <b>overgang bos → polder</b> in één wandeling.', 'De <b>ruiterpaden</b> door de Bergse bossen.', 'De <b>standerdmolen van Wouwse Plantage</b> in de buurt.', 'De <b>rust</b> vlak achter de stad.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Bosrand-zangers</b> volop.', '<span class="months">Mei–aug</span> 🦋 <b>Vlinders</b> op de open plekken.', '<span class="months">Sep–okt</span> 🍂 <b>Beukenblad</b> op de paden.', '<span class="months">Jaarrond</span> 🌬️ <b>Molens</b> aan de polderhorizon.'],
 'wild': ['🌬️ Molens-uitzicht', '🌳 Wal-bossen', '🐎 Ruiterpaden', '🌾 Polderovergang', '🚶 Wandelroutes'],
 'trail': ['Loop of rijd de <b>paden richting Wouwse Plantage</b>.', 'Zoek het <b>uitzicht over de poldermolens</b> vanaf de Wal-rand.', 'Combineer met de <b>Wouwse Plantage</b> (2276).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🐎 Rondes ± 3–8 km · ⚠️ Ruiterpaden — paarden voorrang'
}, {
 'tags': ['North Brabant · woods west of Bergen op Zoom (towards Wouwse Plantage)', 'woodland with mill views on the Wal · walking and riding land between Bergen op Zoom and the Wouwse Plantage — the name refers to the view of the post mill and polder mills at the foot of the Wal', 'list 85 · no. 19'],
 'loc': '📍 Molenzicht, wooded area west of Bergen op Zoom towards the Wouwse Plantage — riding trails and walking routes; combine with the Wouwse Plantage (card 2276) and Zoomland (2273)',
 'desc': 'Walking west from Bergen op Zoom into the <b>woods of the Wal</b>, you pass through land owing its name to the view: <b>Molenzicht</b> — the country where, looking over the edge of the high sands, you see the <b>mills</b> of the low polders turning. At the foot of the Brabantse Wal they still stand: the <b>post mill of the Wouwse Plantage</b> and the polder mills of the Zeeland clays behind it — for centuries the machines that kept this wet land liveable, now monuments in the landscape. The area itself is <b>walking and riding land</b>: paths through production woodland and lanes, with the horse trails for which the Bergen woods are known (the riding stable by the Boslustweg is around the corner). In spring garden warbler and chiffchaff sing in the rising edges; in autumn the paths lie full of beech leaves; and always there is, somewhere between the trunks, a <b>glimpse of the polders</b> — the flat land behind the Wal, where the mills mark the horizon. Molenzicht is the card for those who want to feel the transition from wood to polder: first height, then view, then flatness.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (song in the wood edges), Sep–Oct (autumn paths), year-round (mills in view)<br>\n    <b>Best time of day:</b> Midday — mills in sunlight over the polders.',
 'why': ['The <b>mills at the foot of the Wal</b> as name givers.', 'The <b>wood-to-polder transition</b> in one walk.', 'The <b>horse trails</b> through the Bergen woods.', 'The <b>Wouwse Plantage post mill</b> nearby.', 'The <b>quiet</b> just behind town.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Wood-edge singers</b> in full voice.', '<span class="months">May–Aug</span> 🦋 <b>Butterflies</b> in the clearings.', '<span class="months">Sep–Oct</span> 🍂 <b>Beech leaves</b> on the paths.', '<span class="months">Year-round</span> 🌬️ <b>Mills</b> on the polder horizon.'],
 'wild': ['🌬️ Mill views', '🌳 Wal woods', '🐎 Horse trails', '🌾 Polder transition', '🚶 Walking routes'],
 'trail': ['Walk or ride the <b>paths towards the Wouwse Plantage</b>.', 'Seek the <b>view over the polder mills</b> from the Wal’s edge.', 'Combine with the <b>Wouwse Plantage</b> (2276).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🐎 Loops ± 3–8 km · ⚠️ Horse trails — give way to horses'
}))

C.append(mk.card(2276, 'Wouwse Plantage', {
 'tags': ['Noord-Brabant · bij het dorp Wouwse Plantage (gem. Roosendaal, Brabantse Wal)', 'het eerste productiebos van Nederland · in 1504 door Jan III van Glymes aangeplant — 74 ha SBB-bos binnen een landgoed van ± 900 ha met Sterrenbos-lanen, Sleutelgathuis en standerdmolen', 'list 85 · no. 20'],
 'loc': '📍 Wouwse Plantage, ten zuiden van het gelijknamige dorp (bereikbaar via de A58 / Plantagebaan) — drie wandelroutes, informatiecentrum en rijksmonumentaal Plantage Centrum; combineer met Molenzicht (kaart 2275) en het Grenspark Kalmthoutse Heide',
 'desc': 'Bij het dorp <b>Wouwse Plantage</b> staat het bos waar de Nederlandse bosbouw begon: in <b>1504</b> gaf <b>Jan III van Glymes, heer van Bergen op Zoom</b>, opdracht om hier bos aan te planten voor de houtproductie — <b>het eerste expliciete productiebos op Nederlandse bodem</b>, nog vóór het Mastbos (1516) bij Breda. Op de uitgestrekte zandgronden van de Wal, waar eeuwen tevoren <b>veenmoeras</b> lag (vervening vanaf <b>1477</b>) en daarna heide, verrees een plantage die ook de <b>zandverstuiving</b> moest vastleggen en diende voor de <b>jacht</b>. Wat ervan over is, is een gebied in lagen: het <b>± 74 ha meten Staatsbosbeheer-bos</b> (sinds 1996) ten zuiden van het dorp, en daaromheen het <b>± 900 ha grote landgoed Wouwse Plantage</b> van de Stichting Behoud Natuur en Leefmilieu — met het 19e-eeuwse <b>Plantage Centrum</b> (rijksmonument), het <b>Sleutelgathuis</b> met zijn sleutelgatvormige venster, een jachthuis, houtzagerij en boswachtershuis uit 1871. In het bos lopen de lanen <b>in ster- en raster-vorm</b>, met eiken en beuken op de hoogten en elzen in de laagtes; de vennetjes <b>Mosven en Bergsven</b> werden bosvijvers, en op het voormalige <b>Woeste Gedeelte</b> is het reliëf tot <b>20 meter</b>. Sinds <b>1987</b> is het landgoed voor het publiek open, met drie wandelroutes — blijf op de paden, dan werkt de geschiedenis mee.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (voorjaarsbos), mrt–mei (stinsen-achtige lanen), sep–nov (paddenstoelen en herfstlicht)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht in de sterlanen.',
 'why': ['Het <b>eerste productiebos van Nederland (1504)</b>.', 'De <b>lanen in ster- en rastervorm</b>.', 'Het <b>rijksmonumentale Plantage Centrum</b>.', 'Het <b>Sleutelgathuis</b> en de standerdmolen.', 'Het <b>reliëf tot 20 m</b> op het Woeste Gedeelte.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Voorjaarsbundel</b> in de lanen.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in eik en beuk.', '<span class="months">Jul–aug</span> 🦗 <b>Zomer</b> bij de bosvijvers.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> in het oude bos.'],
 'wild': ['📜 1504-productiebos', '⭐ Sterrenlanen', '🏘️ Plantage Centrum', '💧 Mosven/Bergsven', '🏔️ 20 m reliëf'],
 'trail': ['Loop een van de <b>drie wandelroutes</b> vanaf Plantage Centrum.', 'Zoek het <b>Sleutelgathuis</b> en de bosvijvers.', 'Combineer met <b>Molenzicht</b> (2275) en het <b>Grenspark</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes ± 3–8 km · 🅿️ Parkeren Plantagebaan / dorp'
}, {
 'tags': ['North Brabant · near the village of Wouwse Plantage (gem. Roosendaal, Brabantse Wal)', 'the first production forest of the Netherlands · planted in 1504 by Jan III van Glymes — 74 ha of Staatsbosbeheer wood within a ± 900-ha estate with star-pattern lanes, Keyhole House and post mill', 'list 85 · no. 20'],
 'loc': '📍 Wouwse Plantage, south of the village of the same name (reachable via the A58 / Plantagebaan) — three walking routes, information centre and nationally listed Plantage Centrum; combine with Molenzicht (card 2275) and the Grenspark Kalmthoutse Heide',
 'desc': 'Near the village of <b>Wouwse Plantage</b> stands the wood where Dutch forestry began: in <b>1504</b> <b>Jan III van Glymes, lord of Bergen op Zoom</b>, ordered wood to be planted here for timber production — <b>the first explicit production forest on Dutch soil</b>, even before the Mastbos (1516) near Breda. On the wide sands of the Wal, where centuries earlier <b>peat marsh</b> lay (peat digging from <b>1477</b>) and heath followed, a plantation arose that also had to fix the <b>drifting sand</b> and serve the <b>hunt</b>. What remains is an area in layers: the <b>± 74-hectare Staatsbosbeheer wood</b> (since 1996) south of the village, and around it the <b>± 900-hectare Wouwse Plantage estate</b> of the Behoud Natuur en Leefmilieu foundation — with the 19th-century <b>Plantage Centrum</b> (nationally listed), the <b>Keyhole House</b> with its keyhole-shaped window, a hunting lodge, sawmill and forester’s house of 1871. In the wood the lanes run <b>in star and grid patterns</b>, with oak and beech on the heights and alder in the low parts; the small pools <b>Mosven and Bergsven</b> became woodland ponds, and on the former <b>Woeste Gedeelte</b> the relief reaches <b>20 metres</b>. Since <b>1987</b> the estate has been open to the public, with three walking routes — stay on the paths and history walks along.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring wood), Mar–May (stinsen-like lanes), Sep–Nov (fungi and autumn light)<br>\n    <b>Best time of day:</b> Morning — light in the star lanes.',
 'why': ['The <b>first production forest of the Netherlands (1504)</b>.', 'The <b>star- and grid-pattern lanes</b>.', 'The <b>listed Plantage Centrum</b>.', 'The <b>Keyhole House</b> and the post mill.', 'The <b>20 m of relief</b> on the Woeste Gedeelte.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring bundle</b> in the lanes.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in oak and beech.', '<span class="months">Jul–Aug</span> 🦗 <b>Summer</b> at the woodland ponds.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> in the old wood.'],
 'wild': ['📜 1504 production forest', '⭐ Star lanes', '🏘️ Plantage Centrum', '💧 Mosven/Bergsven', '🏔️ 20 m relief'],
 'trail': ['Walk one of the <b>three routes</b> from Plantage Centrum.', 'Seek the <b>Keyhole House</b> and the woodland ponds.', 'Combine with <b>Molenzicht</b> (2275) and the <b>Grenspark</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes ± 3–8 km · 🅿️ Parking Plantagebaan / village'
}, n2k='De Wouwse Plantage ligt binnen het Natura 2000-gebied Brabantse Wal — met oude gemengde bossen, landbouwgronden, een restant van zandverstuiving en de lange beukenlanen in stervorm.', n2k_en='The Wouwse Plantage lies within the Natura 2000 site Brabantse Wal — with old mixed woods, farmland, a relic of drifting sand and the long star-pattern beech lanes.'))

C.append(mk.card(2277, 'Groot Molenbeek', {
 'tags': ['Noord-Brabant · ten zuidoosten van Bergen op Zoom (Brabantse Wal)', '39 ha landgoed van Brabants Landschap · al in 1291 vermeld — stervormige lanen, een 300 jaar oude zilverlinde en de vallei van de Molenbeek tussen Lievensberg en Mattemburgh', 'list 85 · no. 21'],
 'loc': '📍 Groot Molenbeek, ten zuidoosten van Bergen op Zoom (gelijknamige weg) — vrij toegankelijk op wegen en paden; combineer met Lievensberg (kaart 2274) en Mattemburgh (kaart 2280); beheer Brabants Landschap',
 'desc': 'Ten zuidoosten van <b>Bergen op Zoom</b>, in de vallei van de <b>Molenbeek</b>, ligt een van de oudst gedocumenteerde plekken van de streek: <b>Groot Molenbeek</b>, een <b>39 hectare</b> groot landgoed van het <b>Brabants Landschap</b> dat al in een akte uit <b>1291</b> wordt genoemd — als enclave van Noordgeest, later leengoed van de heren van Bergen op Zoom. De geschiedenis ligt er duimendik bovenop: over het landgoed liep de <b>oude verbindingsweg tussen Antwerpen en Bergen op Zoom</b>, en om de strategische overgang over het toen nog volwaardige riviertje te bewaken, stond hier een <b>versterkt huis</b>. De families Von Frijtag, Drabbe en Van Dam van Isselt erfden het goed eeuwenlang door vererving en huwelijk; nu vormen <b>landhuis, boerderijtje en schuur</b> een als gemeentelijk monument aangewezen ensemble, midden in een klein park met een <b>meer dan 300 jaar oude zilverlinde</b>. Vanuit het landhuis lopen de lanen <b>in stervorm</b> de dalflanken op — monumentale bomen langs productiebos (vooral naaldhout), akkers en grasland. De beekvallei zelf vormt de groene ader tussen de bossen van de <b>Lievensberg</b> (kaart 2274) in het noorden en <b>Mattemburgh</b> (kaart 2280) in het zuiden. Klein, oud, en vrij toegankelijk — het compactste stukje Middeleeuwen van de Wal.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zang in de lanen), mrt–mei (voorjaarsbloei in de vallei), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw in de beekvallei.',
 'why': ['De <b>akte van 1291</b> als oudste vermelding.', 'Het <b>versterkte huis</b> aan de oude Antwerpse weg.', 'De <b>300 jaar oude zilverlinde</b>.', 'De <b>stervormige lanen</b> vanuit het landhuis.', 'De <b>beekvallei</b> tussen Lievensberg en Mattemburgh.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌷 <b>Voorjaarsbloei</b> in de vallei.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> langs de lanen.', '<span class="months">Jun–aug</span> 🦋 <b>Vlinders</b> op de akkerranden.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in het naaldbos.'],
 'wild': ['📜 Akte van 1291', '🌳 Zilverlinde 300 jr', '⭐ Stervormige lanen', '💧 Molenbeek-vallei', '🏰 Versterkt huis'],
 'trail': ['Wandel de <b>stervormige lanen</b> rond het landhuis.', 'Zoek de <b>oude zilverlinde</b> in het park.', 'Combineer met <b>Lievensberg</b> (2274) en <b>Mattemburgh</b> (2280).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 2–4 km · 🅿️ Parkeren aan de weg Groot Molenbeek'
}, {
 'tags': ['North Brabant · south-east of Bergen op Zoom (Brabantse Wal)', '39-ha Brabants Landschap estate · recorded as early as 1291 — star-pattern lanes, a 300-year-old silver linden and the Molenbeek valley between Lievensberg and Mattemburgh', 'list 85 · no. 21'],
 'loc': '📍 Groot Molenbeek, south-east of Bergen op Zoom (road of the same name) — freely accessible on roads and paths; combine with Lievensberg (card 2274) and Mattemburgh (card 2280); managed by Brabants Landschap',
 'desc': 'South-east of <b>Bergen op Zoom</b>, in the valley of the <b>Molenbeek</b>, lies one of the oldest documented places of the region: <b>Groot Molenbeek</b>, a <b>39-hectare</b> estate of the <b>Brabants Landschap</b> trust already named in a charter of <b>1291</b> — an enclave of Noordgeest, later a feudal holding of the lords of Bergen op Zoom. History lies thick upon it: the <b>old road between Antwerp and Bergen op Zoom</b> crossed the estate, and to guard the strategic passage over what was then a full little river, a <b>fortified house</b> stood here. The families Von Frijtag, Drabbe and Van Dam van Isselt inherited the estate for centuries by marriage and descent; today <b>country house, small farm and barn</b> form an ensemble listed as a municipal monument, at the heart of a small park with a <b>silver linden over 300 years old</b>. From the country house the lanes run <b>in star shape</b> up the valley slopes — monumental trees along production woodland (chiefly conifer), fields and grassland. The valley itself is the green artery between the woods of the <b>Lievensberg</b> (card 2274) to the north and <b>Mattemburgh</b> (card 2280) to the south. Small, old, and freely accessible — the most compact piece of Middle Ages on the Wal.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (song in the lanes), Mar–May (spring bloom in the valley), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — dew in the stream valley.',
 'why': ['The <b>charter of 1291</b> as oldest record.', 'The <b>fortified house</b> on the old Antwerp road.', 'The <b>300-year-old silver linden</b>.', 'The <b>star-pattern lanes</b> from the country house.', 'The <b>stream valley</b> between Lievensberg and Mattemburgh.'],
 'phen': ['<span class="months">Mar–May</span> 🌷 <b>Spring bloom</b> in the valley.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> along the lanes.', '<span class="months">Jun–Aug</span> 🦋 <b>Butterflies</b> on the field edges.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the conifer wood.'],
 'wild': ['📜 Charter of 1291', '🌳 300-yr silver linden', '⭐ Star-pattern lanes', '💧 Molenbeek valley', '🏰 Fortified house'],
 'trail': ['Walk the <b>star-pattern lanes</b> around the country house.', 'Seek the <b>old silver linden</b> in the park.', 'Combine with <b>Lievensberg</b> (2274) and <b>Mattemburgh</b> (2280).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 2–4 km · 🅿️ Parking at the Groot Molenbeek road'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2277)
mk.check()
