# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2283, 'Kooiheide', {
 'tags': ['Noord-Brabant · noordrand van Huijbergen (waterwingebied, Grenspark Kalmthoutse Heide)', 'heide in het stilste hoekje van het Grenspark · Evides-waterwingebied waar in 2018 het bos open ging en de heide terugkeert — nachtzwaluwen boven de vlakte, salamanders in de vennen', 'list 85 · no. 27'],
 'loc': '📍 Kooiheide, ten noorden van Huijbergen in het waterwingebied van Evides (toegang vanaf de Abdijlaan) — wandelroutes (o.a. onderdeel van het Boswachterspad); combineer met de Staartse Heide (kaart 2285) en de Woensdrechtse Heide (2281)',
 'desc': 'Aan de noordrand van <b>Huijbergen</b>, op het <b>noordelijkste puntje van het Grenspark Kalmthoutse Heide</b>, ligt een gebied dat twee karrières combineert: de <b>Kooiheide</b> is tegelijk <b>natuurgebied</b> en <b>waterwingebied</b> van Evides — het bedrijf dat hier op grote diepte grondwater wint en de stilte daarboven aan de natuur laat. Het gebied is een mozaïek van <b>gemengde bossen, houtwallen, heide, bloemrijke graslanden en vennen</b>: in de plassen leven <b>kleine, alpen- en vinpootsalamanders</b>, kikkers en libellen — een oude bezinkvijver van de waterwinning is omgetoverd tot een <b>libellenparadijs</b>. In <b>2018</b> gebeurde wat puristen pijn doet en natuurliefhebbers juichen: Evides <b>kapte het bos rond de Kooiheide open en verwijderde de humuslaag</b> — en langzaam komen <b>struikheide en bosbessen</b> terug. Boven de nieuwe vlakte jagen ’s avonds <b>nachtzwaluwen</b> op insecten, en vanaf de randen van de heide is <b>reewild</b> ongezien te bekijken. Koeien en schapen begrazen weilanden en heide, en in de voormalige productiebossen groeit een soortenrijker gemengd bos. Wie het <b>Boswachterspad</b> loopt (7,7 km vanaf de Abdijlaan) komt er vanzelf doorheen — het stilste stukje van het Grenspark.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jul</b> (nachtzwaluw in de schemering), mrt–mei (salamanders in de vennen), jul–sep (libellen bij de oude vijver)<br>\n    <b>Beste tijd van de dag:</b> Avondschemering — nachtzwaluwen jagen.',
 'why': ['De <b>nachtzwaluwen</b> boven de opengekapte vlakte.', 'Het <b>heideherstel van 2018</b> met humusverwijdering.', 'De <b>drie salamandersoorten</b> in de vennen.', 'De <b>libellenvijver</b> uit een oude bezinkvijver.', 'De <b>waterwingebied-stilte</b> van Evides.'],
 'phen': ['<span class="months">Mrt–mei</span> 🐸 <b>Salamanders</b> in de vennen.', '<span class="months">Mei–jul</span> 🌙 <b>Nachtzwaluwen</b> in de schemering.', '<span class="months">Jun–sep</span> 🌿 <b>Struikheide en bosbessen</b> terug op de vlakte.', '<span class="months">Jul–sep</span> 🐉 <b>Libellen</b> bij de voormalige vijver.'],
 'wild': ['🌙 Nachtzwaluw', '🐸 Salamanders', '💜 Heideherstel', '🐉 Libellenvijver', '💧 Waterwingebied'],
 'trail': ['Loop (een deel van) het <b>Boswachterspad</b> vanaf de Abdijlaan.', 'Bezoek de <b>open heidevlakte</b> van 2018.', 'Combineer met de <b>Staartse Heide</b> (2285) en <b>Woensdrechtse Heide</b> (2281).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Boswachterspad 7,7 km (of korter) · 🅿️ Parkeerplaats Abdijlaan (beperkt)'
}, {
 'tags': ['North Brabant · northern edge of Huijbergen (water catchment, Grenspark Kalmthoutse Heide)', 'heath in the quietest corner of the Grenspark · Evides water catchment where the wood was opened in 2018 and heath returns — nightjars over the plain, newts in the pools', 'list 85 · no. 27'],
 'loc': '📍 Kooiheide, north of Huijbergen in the Evides water catchment (access from the Abdijlaan) — walking routes (part of the Forester’s Path); combine with the Staartse Heide (card 2285) and the Woensdrechtse Heide (2281)',
 'desc': 'On the northern edge of <b>Huijbergen</b>, at the <b>northernmost point of the Grenspark Kalmthoutse Heide</b>, lies an area combining two careers: the <b>Kooiheide</b> is at once <b>nature area</b> and <b>water catchment</b> of Evides — the company drawing groundwater from great depth and leaving the silence above to nature. The area is a mosaic of <b>mixed woods, hedges, heath, flower-rich grasslands and pools</b>: in the waters live <b>smooth, alpine and palmate newts</b>, frogs and dragonflies — an old settling basin of the water works was transformed into a <b>dragonfly paradise</b>. In <b>2018</b> came what pains purists and delights nature lovers: Evides <b>opened the wood around the Kooiheide and removed the humus layer</b> — and slowly <b>ling heather and bilberries</b> return. Above the new plain <b>nightjars</b> hunt insects in the evening, and from the heath’s edges <b>roe deer</b> can be watched unseen. Cattle and sheep graze meadows and heath, and in the former production woods a richer mixed forest grows. Walk (part of) the <b>Forester’s Path</b> (7.7 km from the Abdijlaan) and you pass through automatically — the quietest bit of the Grenspark.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (nightjar at dusk), Mar–May (newts in the pools), Jul–Sep (dragonflies at the old basin)<br>\n    <b>Best time of day:</b> Evening dusk — nightjars hunting.',
 'why': ['The <b>nightjars</b> over the opened plain.', 'The <b>2018 heath restoration</b> with humus removal.', 'The <b>three newt species</b> in the pools.', 'The <b>dragonfly basin</b> from an old settling pond.', 'The <b>water-catchment quiet</b> of Evides.'],
 'phen': ['<span class="months">Mar–May</span> 🐸 <b>Newts</b> in the pools.', '<span class="months">May–Jul</span> 🌙 <b>Nightjars</b> at dusk.', '<span class="months">Jun–Sep</span> 🌿 <b>Ling heather and bilberries</b> back on the plain.', '<span class="months">Jul–Sep</span> 🐉 <b>Dragonflies</b> at the former basin.'],
 'wild': ['🌙 Nightjar', '🐸 Newts', '💜 Heath restoration', '🐉 Dragonfly basin', '💧 Water catchment'],
 'trail': ['Walk (part of) the <b>Forester’s Path</b> from the Abdijlaan.', 'Visit the <b>open heath plain</b> of 2018.', 'Combine with the <b>Staartse Heide</b> (2285) and <b>Woensdrechtse Heide</b> (2281).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Forester’s Path 7.7 km (or shorter) · 🅿️ Parking Abdijlaan (limited)'
}))

C.append(mk.card(2284, 'Kortenhoef', {
 'tags': ['Noord-Brabant · grensgebied bij Hoogerheide en Ossendrecht (Grenspark Kalmthoutse Heide)', 'vennengebiedje achter de Wal-rand · Kortenhoeff, met de Kleine Meer als buur — schapenbegrazing, PAS-herstel en een grensoverschrijdende wandeling door velden en plassen', 'list 85 · no. 28'],
 'loc': '📍 Kortenhoef (Kortenhoeff), grensgebied Hoogerheide–Ossendrecht — onverharde paden tussen vennen en bos (lus ± 9,5 km met de Kleine Meer mogelijk); combineer met de Staartse Heide (kaart 2285); beheer Staatsbosbeheer',
 'desc': 'Achter de rand van de Wal, tegen de <b>Belgische grens</b> aan, ligt een van de stille ven-gebiedjes van West-Brabant: <b>Kortenhoeff</b> — in het boek als “Kortenhoef” genoteerd, op de kaart en bij wandelaars als Kortenhoeff bekend. Samen met de <b>Kleine Meer</b> net over de grens vormt het een grensoverschrijdende gordel van <b>vennen, heideresten en bossen</b>, die Staatsbosbeheer en zijn Belgische collega’s van het <b>Grenspark Kalmthoutse Heide</b> als één geheel beheren. De vennen hier zijn de kroonjuwelen van het Grenspark: kale zandbodems waar <b>waterlobelia, oeverkruid en drijvende waterweegbree</b> hun laatste bolwerken hebben — planten van voedselarm water, dat hier door de kwel van de Wal nog steeds voorhanden is. Om die kwaliteit te behouden wordt er hard gewerkt: in <b>2019</b> startte SBB het <b>PAS-herstel</b> waarbij stukken verruigd grasland werden <b>gechopt</b> — de toplaag weg tot op de schone bodem) en <b>Belgisch heimaaisel</b> over het kale zand werd uitgestrooid — heidezaad uit Kalmthout, terug naar Brabant. <b>Schapen</b> houden de heide daarna kort. Wie de lus van ± <b>9,5 km</b> loopt, kruist bos, velden en venoevers — en begrijpt waarom de Grenspark-kaart hier geen grens meer tekent.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jul</b> (venbloei met waterlobelia), jun–sep (libellen), aug–sep (heide paars)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegeling op de vennen.',
 'why': ['De <b>vennen met waterlobelia en oeverkruid</b>.', 'Het <b>PAS-herstel met Belgisch heimaaisel</b>.', 'De <b>schapenbegrazing</b> op de heide.', 'De <b>grensoverschrijdende lus</b> met de Kleine Meer.', 'De <b>kwelwater-kwaliteit</b> van de Wal.'],
 'phen': ['<span class="months">Mei–jul</span> 🌸 <b>Waterlobelia</b> in bloei.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> over de vennen.', '<span class="months">Aug–sep</span> 💜 <b>Heide paars</b> na het herstel.', '<span class="months">Okt–mrt</span> 🌫️ <b>Winterse venstilte</b>.'],
 'wild': ['💧 Vennen', '🌸 Waterlobelia', '🐑 Schapen', '🇧🇪 Grens-lus', '🍃 Heimaaisel-herstel'],
 'trail': ['Loop de <b>lus Kortenhoeff–Kleine Meer</b> (± 9,5 km, deels België).', 'Zoek de <b>kale zandbodems</b> van de vennen.', 'Combineer met de <b>Staartse Heide</b> (2285).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Lus ± 9,5 km · ⚠️ Onverhard — laarzen in natte perioden'
}, {
 'tags': ['North Brabant · border area near Hoogerheide and Ossendrecht (Grenspark Kalmthoutse Heide)', 'small pool area behind the Wal edge · Kortenhoeff, with the Kleine Meer as neighbour — sheep grazing, PAS restoration and a cross-border walk through fields and waters', 'list 85 · no. 28'],
 'loc': '📍 Kortenhoef (Kortenhoeff), border area Hoogerheide–Ossendrecht — unpaved paths between pools and wood (± 9.5-km loop with the Kleine Meer possible); combine with the Staartse Heide (card 2285); managed by Staatsbosbeheer',
 'desc': 'Behind the edge of the Wal, hard against the <b>Belgian border</b>, lies one of West Brabant’s quiet pool areas: <b>Kortenhoeff</b> — recorded in the book as “Kortenhoef”, known on the map and among walkers as Kortenhoeff. Together with the <b>Kleine Meer</b> just across the border it forms a cross-border belt of <b>pools, heath remnants and woods</b>, managed as one whole by Staatsbosbeheer and its Belgian colleagues of the <b>Grenspark Kalmthoutse Heide</b>. The pools here are the Grenspark’s crown jewels: bare sand beds where <b>water lobelia, shoreweed and floating plantain</b> hold their last strongholds — plants of nutrient-poor water, still available here through the Wal’s seepage. To keep that quality, hard work is done: in <b>2019</b> Staatsbosbeheer started <b>PAS restoration</b>, with overgrown grassland <b>chopped</b> (stripped to the clean soil) and <b>Belgian heath mowings</b> spread over the bare sand — heath seed from Kalmthout, back to Brabant. <b>Sheep</b> keep the heath short afterwards. Walk the ± <b>9.5-km loop</b> through wood, fields and pool shores — and understand why the Grenspark map no longer draws a border here.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (pool bloom with water lobelia), Jun–Sep (dragonflies), Aug–Sep (heather purple)<br>\n    <b>Best time of day:</b> Morning — mirror on the pools.',
 'why': ['The <b>pools with water lobelia and shoreweed</b>.', 'The <b>PAS restoration with Belgian heath mowings</b>.', 'The <b>sheep grazing</b> on the heath.', 'The <b>cross-border loop</b> with the Kleine Meer.', 'The <b>seepage-water quality</b> of the Wal.'],
 'phen': ['<span class="months">May–Jul</span> 🌸 <b>Water lobelia</b> in bloom.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> over the pools.', '<span class="months">Aug–Sep</span> 💜 <b>Heather purple</b> after restoration.', '<span class="months">Oct–Mar</span> 🌫️ <b>Wintry pool silence</b>.'],
 'wild': ['💧 Pools', '🌸 Water lobelia', '🐑 Sheep', '🇧🇪 Border loop', '🍃 Mowing restoration'],
 'trail': ['Walk the <b>Kortenhoeff–Kleine Meer loop</b> (± 9.5 km, partly Belgium).', 'Seek the <b>bare sand beds</b> of the pools.', 'Combine with the <b>Staartse Heide</b> (2285).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loop ± 9.5 km · ⚠️ Unpaved — boots in wet periods'
}))

C.append(mk.card(2285, 'Staartse Heide en Duinen', {
 'tags': ['Noord-Brabant · bij Huijbergen (Grenspark Kalmthoutse Heide)', 'heide, bos en binnenlandse duinen op de Wal · met de “grote verbindingszone” tussen Groote/Kleine Meer en Kortenhoeff — nachtzwaluw-gebied met hoop op de gladde slang', 'list 85 · no. 29'],
 'loc': '📍 Staartse Heide en Duinen, ten noordoosten van Huijbergen (Staartsestraat) — routes Vos 3,3 km en grensoverschrijdende Ree 24 km; combineer met Kortenhoeff (kaart 2284) en de Kooiheide (2283); beheer Staatsbosbeheer',
 'desc': 'Ten noordoosten van <b>Huijbergen</b> ligt het heidegebied tussen de bossen dat de <b>Staartse Heide</b> heet — met de <b>Staartse Duinen</b> als ruggengraat: een gebied van <b>gemengd bos, heide en binnenlandse duinen</b> doortrokken van de hoogteverschillen die de Brabantse Wal typeren. De laatste jaren is het gebied het laboratorium van het Grenspark geworden: een groot stuk bos werd <b>gekapt</b> tot de <b>“grote verbindingszone”</b> — een open corridor die de vennen van de <b>Groote en Kleine Meer</b> (Natuurmonumenten, net over de grens) verbindt met <b>Kortenhoeff</b> (kaart 2284), zodat reptielen, insecten en heidesoorten hun leefgebieden weer kunnen uitwisselen. De eerste successen zijn er: de <b>nachtzwaluw</b>, hier al zeldzaam, profiteert van de nieuwe open vlakten — en men verwacht dat de <b>gladde slang</b> via de zone zal terugkeren. In hetzelfde PAS-programma werd het vergraste deel <b>gechopt en met Belgisch heidezaad overzaaid</b>; <b>schaapskuddes</b> houden de nieuwe heide kort. Voor wandelaars is het een gebied van alle landen: de <b>route Vos</b> (3,3 km) voor de korte rondgang, de <b>route Ree</b> (24 km) voor de grensoverschrijdende grote ronde — en daartussen duinen, hei en bosranden op een steenworp van België.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mei–jul</b> (nachtzwaluw), aug–sep (heide paars), apr–jun (zang in de bosranden)<br>\n    <b>Beste tijd van de dag:</b> Avondschemering — nachtzwaluwen over de verbindingszone.',
 'why': ['De <b>“grote verbindingszone”</b> als kap-project met doel.', 'De <b>nachtzwaluw</b> als eerste profiteur.', 'De <b>verwachte gladde slang</b>.', 'De <b>Staartse Duinen</b> als binnenlands duingebied.', 'De <b>grensoverschrijdende route Ree</b> van 24 km.'],
 'phen': ['<span class="months">Mei–jul</span> 🌙 <b>Nachtzwaluwen</b> boven de zone.', '<span class="months">Jun–aug</span> 🦎 <b>Reptielen-zoeken</b> op de duinranden.', '<span class="months">Aug–sep</span> 💜 <b>Heide paars</b> over de vlakte.', '<span class="months">Sep–okt</span> 🍂 <b>Bosrand-herfst</b> rond de route Vos.'],
 'wild': ['🌙 Nachtzwaluw', '🦎 Gladde slang (verwacht)', '🏔️ Binnenlandse duinen', '🔗 Verbindingszone', '🐑 Schapen'],
 'trail': ['Loop de <b>route Vos</b> (3,3 km) of verbind met de <b>Ree</b> (24 km).', 'Zie de <b>open verbindingszone</b> tussen de vennen.', 'Combineer met <b>Kortenhoeff</b> (2284) en de <b>Kooiheide</b> (2283).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes 3,3 / 24 km · 🅿️ Parkeergelegenheid Staartsestraat'
}, {
 'tags': ['North Brabant · near Huijbergen (Grenspark Kalmthoutse Heide)', 'heath, wood and inland dunes on the Wal · with the “great connecting zone” between Groote/Kleine Meer and Kortenhoeff — nightjar territory and hoped-for return of the smooth snake', 'list 85 · no. 29'],
 'loc': '📍 Staartse Heide en Duinen, north-east of Huijbergen (Staartsestraat) — Vos route 3.3 km and cross-border Ree route 24 km; combine with Kortenhoeff (card 2284) and the Kooiheide (2283); managed by Staatsbosbeheer',
 'desc': 'North-east of <b>Huijbergen</b> lies the heath between woods that bears the name <b>Staartse Heide</b> — with the <b>Staartse Duinen</b> as backbone: an area of <b>mixed wood, heath and inland dunes</b> threaded by the height differences typical of the Brabantse Wal. In recent years the area has become the Grenspark’s laboratory: a large stretch of wood was <b>cleared</b> into the <b>“great connecting zone”</b> — an open corridor linking the pools of the <b>Groote and Kleine Meer</b> (Nature Trust, just across the border) with <b>Kortenhoeff</b> (card 2284), so reptiles, insects and heath species can exchange their habitats again. The first successes are in: the <b>nightjar</b>, rare here, profits from the new open plains — and the <b>smooth snake</b> is expected to return via the zone. In the same PAS programme the roughened part was <b>chopped and over-seeded with Belgian heath seed</b>; <b>sheep flocks</b> keep the new heath short. For walkers it is a country of all lands: the <b>Vos route</b> (3.3 km) for a short stretch, the <b>Ree route</b> (24 km) for the great cross-border round — and between them dunes, heath and wood edges within a stone’s throw of Belgium.',
 'meta': '<b>Best season &amp; peak months:</b> <b>May–Jul</b> (nightjar), Aug–Sep (heather purple), Apr–Jun (song in the wood edges)<br>\n    <b>Best time of day:</b> Evening dusk — nightjars over the connecting zone.',
 'why': ['The <b>“great connecting zone”</b> as felling with purpose.', 'The <b>nightjar</b> as first beneficiary.', 'The <b>expected smooth snake</b>.', 'The <b>Staartse Duinen</b> as inland dune area.', 'The <b>cross-border 24-km Ree route</b>.'],
 'phen': ['<span class="months">May–Jul</span> 🌙 <b>Nightjars</b> above the zone.', '<span class="months">Jun–Aug</span> 🦎 <b>Reptile searching</b> on the dune edges.', '<span class="months">Aug–Sep</span> 💜 <b>Heather purple</b> over the plain.', '<span class="months">Sep–Oct</span> 🍂 <b>Wood-edge autumn</b> around the Vos route.'],
 'wild': ['🌙 Nightjar', '🦎 Smooth snake (expected)', '🏔️ Inland dunes', '🔗 Connecting zone', '🐑 Sheep'],
 'trail': ['Walk the <b>Vos route</b> (3.3 km) or connect with the <b>Ree</b> (24 km).', 'See the <b>open connecting zone</b> between the pools.', 'Combine with <b>Kortenhoeff</b> (2284) and the <b>Kooiheide</b> (2283).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3.3 / 24 km · 🅿️ Parking Staartsestraat'
}))

C.append(mk.card(2286, 'Noordpolder van Ossendrecht', {
 'tags': ['Noord-Brabant · ten noorden van Ossendrecht (voet van de Brabantse Wal)', 'polder in de schaduw van de steilrand · ± 30 meter lager dan de Vluchtheuvel erboven — zoet verlaten polderland met sloten, weilanden en de Wal als muur', 'list 85 · no. 30'],
 'loc': '📍 Noordpolder van Ossendrecht, ten noorden van Ossendrecht aan de voet van de Wal — polderweggetjes en kerkenpaden (verbindt met de Stoppelbergen, kaart 2290); combineer met de Vluchtheuvel (kaart 2287) voor het hoogtecontrast',
 'desc': 'Aan de voet van de <b>Brabantse Wal</b>, ten noorden van <b>Ossendrecht</b>, ligt land dat zich het best laat lezen als het negatief van de bossen erboven: de <b>Noordpolder van Ossendrecht</b>, waarin het polderland <b>± 30 meter lager</b> ligt dan de <b>Vluchtheuvel</b> op de rand — één van de scherpste hoogtesprongen van de hele Wal. Hier staat de <b>steilrand</b> als een muur in het landschap: boven bos en heide, beneden sloten en weilanden, en daartussen een helling van klei en zand waar de eeuwen de overgang hebben genivelleerd maar nooit gewist. De polder is waterland: <b>zoete kwel</b> uit de Wal houdt de percelen vochtig, en in de slootkanten groeit een vegetatie die van die kwel profiteert. In de lenteweiden pronken <b>koekoeksbloem en dotterbloem</b>; in het vroege voorjaar treden hier <b>weidevogels</b> op — kievit, grutto, tureluur — die de rust van de kleine polder weten te vinden; in de winter zoeken <b>ganzen en smienten</b> de natte graslanden op. Wie hier wandelt, voelt de geologie onder de voeten: het is de kaart van de overgang zand–klei, het verhaal van de Wal in het klein — en de kerkenpaden die de polder met het dorp verbinden, lopen er al eeuwen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (weidevogels en lentebloei), okt–mrt (wintergasten), mei–jun (slootranden in bloei)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en weidevogelzang onder de Wal-rand.',
 'why': ['Het <b>30-meter contrast</b> met de Vluchtheuvel.', 'De <b>steilrand als muur</b> boven de polder.', 'De <b>zoete kwel</b> uit de Wal.', 'De <b>weidevogels</b> in de rustige polder.', 'De <b>kerkenpaden</b> naar Ossendrecht.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Weidevogels</b> in de weiden.', '<span class="months">Apr–jun</span> 🌸 <b>Koekoeks- en dotterbloem</b> aan de sloten.', '<span class="months">Okt–mrt</span> 🪿 <b>Ganzen en smienten</b> op nat grasland.', '<span class="months">Jaarrond</span> 🏔️ <b>De Wal als muur</b> in het zicht.'],
 'wild': ['🏔️ Steilrand-voet', '💧 Zoete kwel', '🐦 Weidevogels', '🌾 Polderstilte', '🚶 Kerkenpaden'],
 'trail': ['Wandel de <b>polderweggetjes</b> beneden de steilrand.', 'Klim daarna de <b>Vluchtheuvel</b> (2287) in voor het contrast.', 'Volg een <b>kerkenpad</b> richting Ossendrecht.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–7 km · ⚠️ Natte paden — laarzen'
}, {
 'tags': ['North Brabant · north of Ossendrecht (foot of the Brabantse Wal)', 'polder in the shadow of the escarpment · ± 30 metres lower than the Vluchtheuvel above it — quiet polder land of fresh seepage with ditches, meadows and the Wal as wall', 'list 85 · no. 30'],
 'loc': '📍 Noordpolder van Ossendrecht, north of Ossendrecht at the foot of the Wal — polder lanes and church paths (connecting with the Stoppelbergen, card 2290); combine with the Vluchtheuvel (card 2287) for the height contrast',
 'desc': 'At the foot of the <b>Brabantse Wal</b>, north of <b>Ossendrecht</b>, lies land best read as the negative of the woods above: the <b>Noordpolder van Ossendrecht</b>, where the polder lies <b>± 30 metres lower</b> than the <b>Vluchtheuvel</b> on the edge — one of the sharpest height jumps of the whole Wal. Here the <b>escarpment</b> stands as a wall in the landscape: wood and heath above, ditches and meadows below, and between them a slope of clay and sand where the centuries levelled the transition but never erased it. The polder is water land: <b>fresh seepage</b> from the Wal keeps the parcels moist, and the ditch banks carry vegetation profiting from that seepage. In the spring meadows <b>cuckoo flower and marsh marigold</b> shine; in early spring <b>meadow birds</b> appear — lapwing, black-tailed godwit, redshank — finding the quiet of the small polder; in winter <b>geese and wigeon</b> seek the wet grasslands. Walk here and you feel the geology underfoot: it is the card of the sand-to-clay transition, the Wal’s story in miniature — and the church paths linking polder and village have run here for centuries.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (meadow birds and spring bloom), Oct–Mar (winter guests), May–Jun (ditch banks in bloom)<br>\n    <b>Best time of day:</b> Morning — dew and meadow-bird song beneath the Wal edge.',
 'why': ['The <b>30-metre contrast</b> with the Vluchtheuvel.', 'The <b>escarpment as wall</b> above the polder.', 'The <b>fresh seepage</b> from the Wal.', 'The <b>meadow birds</b> in the quiet polder.', 'The <b>church paths</b> to Ossendrecht.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Meadow birds</b> in the meadows.', '<span class="months">Apr–Jun</span> 🌸 <b>Cuckoo flower and marsh marigold</b> by the ditches.', '<span class="months">Oct–Mar</span> 🪿 <b>Geese and wigeon</b> on wet grassland.', '<span class="months">Year-round</span> 🏔️ <b>The Wal as wall</b> in view.'],
 'wild': ['🏔️ Escarpment foot', '💧 Fresh seepage', '🐦 Meadow birds', '🌾 Polder quiet', '🚶 Church paths'],
 'trail': ['Walk the <b>polder lanes</b> below the escarpment.', 'Then climb the <b>Vluchtheuvel</b> (2287) for the contrast.', 'Follow a <b>church path</b> towards Ossendrecht.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–7 km · ⚠️ Wet paths — boots'
}))

C.append(mk.card(2287, 'Vluchtheuvel', {
 'tags': ['Noord-Brabant · op de Wal-rand bij Ossendrecht (Abdijbossen, Grenspark Kalmthoutse Heide)', 'bos op de hoge zandgronden van de Abdijbossen · ± 30 m boven de Noordpolder — tot voor kort bekend als “Vluchtheuvel”, het publieksbos bovenop de steilrand', 'list 85 · no. 31'],
 'loc': '📍 Vluchtheuvel, op de Wal-rand bij Ossendrecht (Schapendreef) — paden door de Abdijbossen met uitzicht over de Noordpolder; combineer met Pottenbergen (kaart 2288) en de Noordpolder van Ossendrecht (2286)',
 'desc': 'Bovenop de rand van de Wal bij <b>Ossendrecht</b> ligt het bos dat op de kaarten tegenwoordig onder de <b>Abdijbossen</b> valt — maar dat wandelaars van vroeger nog steeds bij de oude naam kennen: de <b>Vluchtheuvel</b>. Het is het <b>publieksbos op de hoge zandgronden</b>, ± <b>30 meter boven</b> de <b>Noordpolder</b> (kaart 2286) aan de noordkant — het hoogteverschil dat hier de Brabantse Wal het scherpst maakt. Wie vanaf de <b>Schapendreef</b> de paden in loopt, wandelt door stil naald- en loofbos waar de <b>zwarte specht</b> zijn territorium roffelt en ’s avonds de <b>nachtzwaluw</b> kan jagen — de Abdijbossen behoren tot de kerngebieden van de Grenspark-soorten. Aan de noordrand opent het bos zich boven de polder: het <b>uitzicht over het lage land</b> is het klassieke Wal-gevoel, met de kerktoren van Ossendrecht als oriëntatiepunt en bij helder weer de Zeeuwse polders tot ver in het westen. De bossen danken hun naam aan de <b>abdij van Huijbergen</b>, wier gronden hier eeuwen lang bos en heide droegen; nu beheren Staatsbosbeheer en het Grenspark ze samen met de Belgische buren. Vluchtheuvel is de kaart voor wie de Wal wil <b>voelen</b>: eerst klimmen door stil bos, dan het plateau, dan het uitzicht — de heuvel als vlucht, zoals de naam belooft.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (spechten en zang), mei–jul (nachtzwaluw in de schemering), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Avond — nachtzwaluw vanaf de open plekken.',
 'why': ['De <b>oude naam</b> in de nieuwe Abdijbossen.', 'Het <b>30 m hoogteverschil</b> met de polder.', 'De <b>nachtzwaluw en zwarte specht</b> als bossoorten.', 'Het <b>uitzicht over de Noordpolder</b>.', 'De <b>abdij-geschiedenis</b> van Huijbergen.'],
 'phen': ['<span class="months">Apr–jun</span> 🥁 <b>Zwarte specht</b> roffelt.', '<span class="months">Mei–jul</span> 🌙 <b>Nachtzwaluw</b> boven de open plekken.', '<span class="months">Jun–aug</span> 🦗 <b>Zomeravonden</b> op de rand.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in de Abdijbossen.'],
 'wild': ['🏔️ Wal-rand-bos', '🥁 Zwarte specht', '🌙 Nachtzwaluw', '👀 Polder-uitzicht', '📜 Abdij-verleden'],
 'trail': ['Loop de <b>paden vanaf de Schapendreef</b> het bos in.', 'Zoek de <b>rand met polder-uitzicht</b> aan de noordkant.', 'Combineer met <b>Pottenbergen</b> (2288) en de <b>Noordpolder</b> (2286).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–6 km · 🅿️ Parkeren Schapendreef'
}, {
 'tags': ['North Brabant · on the Wal edge near Ossendrecht (Abdijbossen, Grenspark Kalmthoutse Heide)', 'wood on the high sands of the Abdijbossen · ± 30 m above the Noordpolder — until recently known as “Vluchtheuvel”, the public wood atop the escarpment', 'list 85 · no. 31'],
 'loc': '📍 Vluchtheuvel, on the Wal edge near Ossendrecht (Schapendreef) — paths through the Abdijbossen with views over the Noordpolder; combine with Pottenbergen (card 2288) and the Noordpolder van Ossendrecht (2286)',
 'desc': 'Atop the edge of the Wal near <b>Ossendrecht</b> lies the wood now mapped under the <b>Abdijbossen</b> — but known to old walkers by its former name: the <b>Vluchtheuvel</b>. It is the <b>public wood on the high sands</b>, ± <b>30 metres above</b> the <b>Noordpolder</b> (card 2286) to the north — the height difference that makes the Brabantse Wal sharpest here. From the <b>Schapendreef</b> the paths lead through quiet conifer and broadleaf wood where the <b>black woodpecker</b> drums its territory and at dusk the <b>nightjar</b> may hunt — the Abdijbossen belong to the core areas of the Grenspark species. At the northern edge the wood opens above the polder: the <b>view over the low land</b> is the classic Wal feeling, with Ossendrecht’s church tower as landmark and, in clear weather, the Zeeland polders far to the west. The woods owe their name to the <b>abbey of Huijbergen</b>, whose lands carried wood and heath here for centuries; Staatsbosbeheer and the Grenspark now manage them together with the Belgian neighbours. Vluchtheuvel is the card for those who want to <b>feel</b> the Wal: first climbing through quiet wood, then the plateau, then the view — the hill as escape, as the name promises.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (woodpeckers and song), May–Jul (nightjar at dusk), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Evening — nightjar from the clearings.',
 'why': ['The <b>old name</b> within the new Abdijbossen.', 'The <b>30-m height difference</b> with the polder.', 'The <b>nightjar and black woodpecker</b> as wood species.', 'The <b>view over the Noordpolder</b>.', 'The <b>abbey history</b> of Huijbergen.'],
 'phen': ['<span class="months">Apr–Jun</span> 🥁 <b>Black woodpecker</b> drums.', '<span class="months">May–Jul</span> 🌙 <b>Nightjar</b> above the clearings.', '<span class="months">Jun–Aug</span> 🦗 <b>Summer evenings</b> on the edge.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the Abdijbossen.'],
 'wild': ['🏔️ Wal-edge wood', '🥁 Black woodpecker', '🌙 Nightjar', '👀 Polder view', '📜 Abbey past'],
 'trail': ['Walk the <b>paths from the Schapendreef</b> into the wood.', 'Seek the <b>edge with polder view</b> to the north.', 'Combine with <b>Pottenbergen</b> (2288) and the <b>Noordpolder</b> (2286).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–6 km · 🅿️ Parking Schapendreef'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2287)
mk.check()
