# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2288, 'Pottenbergen', {
 'tags': ['Noord-Brabant · bij Ossendrecht (Abdijbossen, Grenspark Kalmthoutse Heide)', 'waterwingebied van 153 ha in de Abdijbossen · het publiek toegankelijke deel van Evides’ wingebied — stil bos met kwel, vennen en een oude bezinkvijver', 'list 85 · no. 32'],
 'loc': '📍 Pottenbergen, ten zuidwesten van Ossendrecht in de Abdijbossen — paden door het voor publiek openstaande deel van het waterwingebied; combineer met de Vluchtheuvel (kaart 2287) en de Woensdrechtse Heide (2281)',
 'desc': 'In de <b>Abdijbossen</b> bij <b>Ossendrecht</b> ligt het gebied dat de drinkwaterkraan van de streek in de hand houdt: <b>Pottenbergen</b>, een <b>waterwingebied van 153 hectare</b> waar <b>Evides</b> al decennia grondwater wint — en waarvan het <b>voor publiek toegankelijke deel</b> optreedt als de rustigste boskamer van de hele streek. De naam Pottenbergen herinnert aan de <b>pottenbakkersklei</b> die hier in heuvels lag voordat het bos kwam; nu bepalen <b>stil naaldbos, oude beuken en vochtige laagten</b> het beeld. Het waterwingebied werkt onbedoeld als natuurreservaat: waar geen bemesting en verstorende recreatie komt, gedijen de <b>kwel-vegetaties</b> van de Wal — en in de oudere delen van het gebied liggen vennen en vochtige plassen waar <b>salamanders en libellen</b> hun rondes draaien. De naam “Abdijbossen” verwijst naar de <b>abdij van Huijbergen</b>, die hier eeuwen geleden de eerste bossen liet groeien; tot voor kort stond het gebied op de kaarten als <b>Vluchtheuvel</b> (kaart 2287) — de oude naam leeft onder waarnemers voort. Wie de paden volgt, merkt vooral de rust: een bos dat water moet leveren, mag geen lawaai verdragen — en dat proef je.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels), mrt–mei (salamanders in de vennen), sep–okt (paddenstoelen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — stilte is de hoofdattractie.',
 'why': ['De <b>153 ha waterwingebied</b> als onbedoeld reservaat.', 'De <b>kwel-vegetaties</b> van de Wal.', 'De <b>pottenbakkersklei</b> achter de naam.', 'De <b>salamanders en libellen</b> in de laagten.', 'De <b>rust</b> van een gebied zonder massarecreatie.'],
 'phen': ['<span class="months">Mrt–mei</span> 🐸 <b>Salamanders</b> in de vochtige plassen.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het stilste bos.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven de vennen.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in het oude bos.'],
 'wild': ['💧 Waterwingebied', '🤫 Bosstilte', '🐸 Salamanders', '🧱 Klei-heuvels', '📜 Abdij-bossen'],
 'trail': ['Wandel het <b>toegankelijke deel</b> van het waterwingebied.', 'Combineer met de <b>Vluchtheuvel</b> (2287) en de <b>Woensdrechtse Heide</b> (2281).', 'Respecteer de <b>gesloten zones</b> — paden volgen.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–6 km · ⚠️ Delen gesloten — verbodborden volgen'
}, {
 'tags': ['North Brabant · near Ossendrecht (Abdijbossen, Grenspark Kalmthoutse Heide)', '153-ha water catchment in the Abdijbossen · the publicly accessible part of Evides’ extraction area — quiet wood with seepage, pools and an old settling basin', 'list 85 · no. 32'],
 'loc': '📍 Pottenbergen, south-west of Ossendrecht in the Abdijbossen — paths through the publicly open part of the water catchment; combine with the Vluchtheuvel (card 2287) and the Woensdrechtse Heide (2281)',
 'desc': 'In the <b>Abdijbossen</b> near <b>Ossendrecht</b> lies the area holding the region’s drinking-water tap: <b>Pottenbergen</b>, a <b>water catchment of 153 hectares</b> where <b>Evides</b> has drawn groundwater for decades — and whose <b>publicly accessible part</b> acts as the quietest wood-chamber of the whole region. The name Pottenbergen recalls the <b>potter’s clay</b> that lay heaped here before the wood came; now <b>quiet conifer stands, old beeches and moist hollows</b> set the scene. The catchment works unintentionally as a nature reserve: where no fertiliser and no mass recreation come, the Wal’s <b>seepage vegetations</b> thrive — and in the older parts lie pools and wet hollows where <b>newts and dragonflies</b> make their rounds. The name “Abdijbossen” refers to the <b>abbey of Huijbergen</b>, which grew the first woods here centuries ago; until recently the area appeared on maps as <b>Vluchtheuvel</b> (card 2287) — the old name lives on among observers. Follow the paths and you notice above all the quiet: a wood that must yield water cannot bear noise — and you taste it.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds), Mar–May (newts in the pools), Sep–Oct (fungi)<br>\n    <b>Best time of day:</b> Morning — silence is the main attraction.',
 'why': ['The <b>153-ha catchment</b> as unintended reserve.', 'The Wal’s <b>seepage vegetations</b>.', 'The <b>potter’s clay</b> recalled in the name.', 'The <b>newts and dragonflies</b> in the hollows.', 'The <b>quiet</b> of an area without mass recreation.'],
 'phen': ['<span class="months">Mar–May</span> 🐸 <b>Newts</b> in the wet hollows.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the quietest wood.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> over the pools.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old wood.'],
 'wild': ['💧 Water catchment', '🤫 Wood silence', '🐸 Newts', '🧱 Clay hills', '📜 Abbey woods'],
 'trail': ['Walk the <b>accessible part</b> of the catchment.', 'Combine with the <b>Vluchtheuvel</b> (2287) and the <b>Woensdrechtse Heide</b> (2281).', 'Respect the <b>exclusion zones</b> — follow paths.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–6 km · ⚠️ Parts closed — follow signs'
}))

C.append(mk.card(2289, 'Ossendrecht', {
 'tags': ['Noord-Brabant · dorpsnatuur rond Ossendrecht (Brabantse Wal, Grenspark)', 'natuur-hoofdstad aan de steilrand · het dorp tussen Abdijbossen, Stoppelbergen en de polders — waar Wal, kwel en kerkenpaden samenkomen', 'list 85 · no. 33'],
 'loc': '📍 Ossendrecht, dorp op de Brabantse Wal — kerkenpaden en polderrondes rond het dorp; combineer met de Vluchtheuvel/Pottenbergen (kaarten 2287/2288), de Stoppelbergen (2290) en de Noordpolder (2286)',
 'desc': 'Wie de natuur van de Brabantse Wal wil begrijpen, kan het beste in <b>Ossendrecht</b> beginnen: het dorp ligt precies op de <b>rand</b> — de hoge zandgronden met de <b>Abdijbossen</b> (kaarten 2287 en 2288) in het zuiden, de <b>Stoppelbergen</b> (kaart 2290) in het oosten, en in het noorden de <b>val van de steilrand</b> naar de Noordpolder, waar het zand overgaat in Zeeuwse klei. Die positie maakt Ossendrecht tot een natuur-knooppunt: <b>kerkenpaden</b> verbinden al eeuwen het dorp met de polders en de buurtschappen, en wie ze loopt, daalt in één kilometer van bos naar weide — het gehele verhaal van de Wal in een namiddag. De omgeving is rijk aan geschiedenis: de <b>abdij van Huijbergen</b> gaf de streek zijn bossen, de <b>markiezen van Bergen op Zoom</b> hun landgoederen, en de <b>twee wereldoorlogen</b> lieten bunkers en loopgraven die nu vleermuis- en salamanderhabitat zijn. In het voorjaar zingt de boomklever in de dorpslinde; in de herfst ruiken de Abdijbossen naar paddenstoelen; in de winter staan de polders vol ganzen. Deze kaart is de <b>kapstok</b> voor de Ossendrechtse natuur: hang hier de wandelingen aan en vertrek — naar het bos, de heide of de polder, alle drie op loopafstand.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (wandelseizoen rond het dorp), mrt–mei (voorjaar in bos en polder), okt–mrt (winterganzen beneden de Wal)<br>\n    <b>Beste tijd van de dag:</b> Middag — kerkenpad-rondes vanaf het dorp.',
 'why': ['De <b>positie op de rand</b>: bos, heide én polder.', 'De <b>kerkenpaden</b> als eeuwenoude verbindingen.', 'De <b>abdij van Huijbergen</b> als bos-stichter.', 'De <b>oorlogsresten</b> als nieuw habitat.', 'De <b>drie landschappen</b> op loopafstand.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Voorjaarszang</b> in bos en dorp.', '<span class="months">Mei–aug</span> 🦇 <b>Vleermuizen</b> rond oude bunkers.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in de Abdijbossen.', '<span class="months">Okt–mrt</span> 🪿 <b>Winterganzen</b> in de Noordpolder.'],
 'wild': ['📍 Rand-dorp', '🚶 Kerkenpaden', '⚔️ Oorlogsresten', '🌲 Abdijbossen', '🌾 Polder-uitzicht'],
 'trail': ['Loop een <b>kerkenpad</b> het dorp uit richting de polder.', 'Kies daarna: <b>Abdijbossen</b> (2287/2288) of <b>Stoppelbergen</b> (2290).', 'Daal af naar de <b>Noordpolder</b> (2286) voor het contrast.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 4–10 km · 🅿️ Parkeren in het dorp'
}, {
 'tags': ['North Brabant · village nature around Ossendrecht (Brabantse Wal, Grenspark)', 'nature capital on the escarpment · the village between Abdijbossen, Stoppelbergen and the polders — where Wal, seepage and church paths meet', 'list 85 · no. 33'],
 'loc': '📍 Ossendrecht, village on the Brabantse Wal — church paths and polder rounds around the village; combine with the Vluchtheuvel/Pottenbergen (cards 2287/2288), the Stoppelbergen (2290) and the Noordpolder (2286)',
 'desc': 'To understand the nature of the Brabantse Wal, start in <b>Ossendrecht</b>: the village lies exactly on the <b>edge</b> — the high sands with the <b>Abdijbossen</b> (cards 2287 and 2288) to the south, the <b>Stoppelbergen</b> (card 2290) to the east, and to the north the <b>drop of the escarpment</b> towards the Noordpolder, where sand gives way to Zeeland clay. That position makes Ossendrecht a nature junction: <b>church paths</b> have linked the village to the polders and hamlets for centuries, and walking them you descend from wood to meadow in a single kilometre — the whole story of the Wal in one afternoon. The surroundings are rich in history: the <b>abbey of Huijbergen</b> gave the region its woods, the <b>marquises of Bergen op Zoom</b> their estates, and the <b>two world wars</b> left bunkers and trenches that are now bat and salamander habitat. In spring the nuthatch sings in the village lime; in autumn the Abdijbossen smell of fungi; in winter the polders stand full of geese. This card is the <b>starting point</b> for Ossendrecht’s nature: hang your walks on it and set out — to the wood, the heath or the polder, all three within walking distance.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (walking season around the village), Mar–May (spring in wood and polder), Oct–Mar (winter geese below the Wal)<br>\n    <b>Best time of day:</b> Midday — church-path rounds from the village.',
 'why': ['The <b>position on the edge</b>: wood, heath and polder.', 'The <b>church paths</b> as age-old connections.', 'The <b>abbey of Huijbergen</b> as founder of woods.', 'The <b>war remains</b> as new habitat.', 'The <b>three landscapes</b> within walking distance.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Spring song</b> in wood and village.', '<span class="months">May–Aug</span> 🦇 <b>Bats</b> around old bunkers.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the Abdijbossen.', '<span class="months">Oct–Mar</span> 🪿 <b>Winter geese</b> in the Noordpolder.'],
 'wild': ['📍 Edge village', '🚶 Church paths', '⚔️ War remains', '🌲 Abdijbossen', '🌾 Polder view'],
 'trail': ['Walk a <b>church path</b> out of the village towards the polder.', 'Then choose: <b>Abdijbossen</b> (2287/2288) or <b>Stoppelbergen</b> (2290).', 'Descend to the <b>Noordpolder</b> (2286) for the contrast.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Rounds ± 4–10 km · 🅿️ Parking in the village'
}))

C.append(mk.card(2290, 'Stoppelbergen', {
 'tags': ['Noord-Brabant · ten zuiden van Ossendrecht, tegen de Belgische grens (gem. Woensdrecht)', '190 ha zeeden-bos van Staatsbosbeheer · het grootste zeedenareaal van de Brabantse bossen — ± 50 broedvogelsoorten, kuifmezen onder de naalden, en de steilrand naar de Zuidpolder', 'list 85 · no. 34'],
 'loc': '📍 Stoppelbergen, ten zuiden van Ossendrecht (Zandvlietseweg) — wandelroutes door het dennenbos en naar de polders; combineer met Ossendrecht-dorp (kaart 2289) en de Abdijbossen (2287); beheer Staatsbosbeheer',
 'desc': 'Ten zuiden van <b>Ossendrecht</b>, tegen de <b>Belgische grens</b> aan, ligt het bos dat van één boomsoort zijn karakter draagt: de <b>Stoppelbergen</b>, <b>190 hectare</b> boswachterij van Staatsbosbeheer waar de <b>zeeden</b> — de kustden van de duinstreken — zo’n groot areaal beslaat als nergens anders in de Brabantse bossen. De zeeden bepaalt de sfeer: hoge, open kronen, veel licht op de bosbodem, en overal de lange naalden die het tapijt vormen waar <b>kuifmezen en andere insecteneters</b> doorheen ploegen — het gebied telt rond de <b>50 soorten broedvogels</b> en is juist om dat insektenetende gezelschap beroemd. De naam Stoppelbergen herinnert aan de akkers die er lagen voordat het bos kwam: stoppelland op de zandgronden van de Wal. Aan de randen valt het gebied de <b>steilrand</b> af naar de <b>Zuidpolder</b>: het hoogteverschil van ± 12 meter waarin het hele Wal-verhaal zit — boven zand en den, beneden klei en weide. De wandelroute <b>Stoppelbergen–Zuidpolder</b> combineert beide: eerst het stilste dennenbos van Brabant, dan de val, dan de polder — en via een <b>kerkenpad</b> terug naar Ossendrecht.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (broedvogels, kuifmezen), sep–okt (paddenstoelen onder de dennen), okt–mrt (winterganzen in de Zuidpolder)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — mezen-koor in de dennen.',
 'why': ['Het <b>grootste zeedenareaal</b> van de Brabantse bossen.', 'De <b>± 50 broedvogelsoorten</b>.', 'De <b>kuifmezen</b> als specialiteit.', 'De <b>steilrand van ± 12 m</b> naar de Zuidpolder.', 'De <b>naam uit het stoppelland</b>.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Kuifmezen-koor</b> onder de naalden.', '<span class="months">Mei–aug</span> 🐿️ <b>Insecteneters</b> op volle sterkte.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in het dennentapijt.', '<span class="months">Okt–mrt</span> 🪿 <b>Ganzen</b> in de Zuidpolder beneden.'],
 'wild': ['🌲 Zeeden-bos', '🐦 50 broedvogels', '🎩 Kuifmees', '🏔️ Steilrand 12 m', '🌾 Zuidpolder'],
 'trail': ['Loop de <b>wandelroute Stoppelbergen–Zuidpolder</b>.', 'Zoek de <b>kuifmezen</b> in de zeeden-kronen.', 'Combineer met <b>Ossendrecht</b> (2289) en de <b>Abdijbossen</b> (2287).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondes ± 3–8 km · 🅿️ Parkeren Zandvlietseweg'
}, {
 'tags': ['North Brabant · south of Ossendrecht, against the Belgian border (gem. Woensdrecht)', '190 ha of maritime-pine wood of Staatsbosbeheer · the largest area of maritime pine among the Brabant woods — ± 50 breeding bird species, crested tits under the needles, and the escarpment to the Zuidpolder', 'list 85 · no. 34'],
 'loc': '📍 Stoppelbergen, south of Ossendrecht (Zandvlietseweg) — walking routes through the pine wood and to the polders; combine with Ossendrecht village (card 2289) and the Abdijbossen (2287); managed by Staatsbosbeheer',
 'desc': 'South of <b>Ossendrecht</b>, hard against the <b>Belgian border</b>, lies the wood owing its character to a single tree species: the <b>Stoppelbergen</b>, <b>190 hectares</b> of Staatsbosbeheer forestry where <b>maritime pine</b> — the coast pine of the dune regions — covers as large an area as anywhere in the Brabant woods. The pine sets the mood: high open crowns, much light on the forest floor, and everywhere the long needles forming the carpet through which <b>crested tits and other insect-eaters</b> work — the area counts some <b>50 breeding bird species</b> and is famous precisely for that insectivorous company. The name Stoppelbergen recalls the fields that lay here before the wood: stubble land on the Wal’s sands. At the edges the area drops along the <b>escarpment</b> to the <b>Zuidpolder</b>: a height difference of ± 12 metres holding the whole Wal story — sand and pine above, clay and meadow below. The <b>Stoppelbergen–Zuidpolder walking route</b> combines both: first Brabant’s quietest pine wood, then the drop, then the polder — and back to Ossendrecht along a <b>church path</b>.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (breeding birds, crested tits), Sep–Oct (fungi under the pines), Oct–Mar (winter geese in the Zuidpolder)<br>\n    <b>Best time of day:</b> Morning — tit chorus in the pines.',
 'why': ['The <b>largest maritime-pine area</b> among the Brabant woods.', 'The <b>± 50 breeding bird species</b>.', 'The <b>crested tits</b> as speciality.', 'The <b>± 12-m escarpment</b> to the Zuidpolder.', 'The <b>name from the stubble fields</b>.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Crested-tit chorus</b> under the needles.', '<span class="months">May–Aug</span> 🐿️ <b>Insect-eaters</b> at full strength.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the pine carpet.', '<span class="months">Oct–Mar</span> 🪿 <b>Geese</b> in the Zuidpolder below.'],
 'wild': ['🌲 Maritime-pine wood', '🐦 50 breeding birds', '🎩 Crested tit', '🏔️ 12-m escarpment', '🌾 Zuidpolder'],
 'trail': ['Walk the <b>Stoppelbergen–Zuidpolder route</b>.', 'Seek the <b>crested tits</b> in the pine crowns.', 'Combine with <b>Ossendrecht</b> (2289) and the <b>Abdijbossen</b> (2287).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Loops ± 3–8 km · 🅿️ Parking Zandvlietseweg'
}))

C.append(mk.card(2291, 'Verdronken Land van Saeftinghe', {
 'tags': ['Zeeland · Westerschelde-monding bij Emmadorp/Nieuw-Namen (Zeeuws-Vlaanderen)', 'grootste brakwaterschor van Europa · 3.580 ha slikken, schorren en geulen waar tot in de 16e eeuw dorpen lagen — dagelijks getij, waterbuffels op het Schor van Baalhoek, vrij toegankelijk deel rond Emmadorp en Paal', 'list 85 · no. 36'],
 'loc': '📍 Verdronken Land van Saeftinghe, tussen Emmadorp en de Belgische grens (bezoekerscentrum bij Emmadorp) — ± 400 ha vrij toegankelijk rond Emmadorp en Paal, rest alleen met excursie; open zonsopgang–zonsondergang, gesloten bij springtij; beheer Het Zeeuwse Landschap',
 'desc': 'Aan de monding van de Westerschelde, waar Nederland en België elkaar over het water raken, ligt het wildste stukje getijdenland van het land: het <b>Verdronken Land van Saeftinghe</b>, <b>3.580 hectare</b> slikken, schorren en geulen — het <b>grootste brakwaterschor van Europa</b>. De naam is geen beeldspraak: hier lagen in de late middeleeuwen de <b>dorpen Saeftinghe, Casuwele, Namen en Sint-Laureins</b>, en zelfs een <b>kasteel</b> — tot overstromingen in de <b>14e en 16e eeuw</b> het land heroverden en het getij er sindsdien dagelijks in- en uitstroomt. Wat overbleef is een <b>delta van geulen</b> — de grootste het <b>Speelmansgat</b>, de IJskelder en het Hondegat — met voor <b>70%</b> begroeid schor: <b>zeeaster, echt lepelblad, heen, schorrenzoutgras en zilte rus</b> op het zoute westen, uitgestrekte <b>rietvelden</b> op het verzoetende oosten, en hier en daar <b>eeuwenoud veen</b> aan de oppervlakte. De runderen begrazen het schor zoals eeuwenlang de <b>schaapskuddes</b> deden — en op het <b>Schor van Baalhoek</b> doen sinds recent <b>waterbuffels</b> dat werk, om het dichtgegroeide schor weer jong te maken voor <b>tureluurs</b>. Tot in de jaren vijftig wilde men het gebied <b>inpolderen</b> — de Rijksdam en de Dam naar de Noord getuigen daar nog van — maar het werd natuurgebied, en nu trekt het jaarlijks tienduizenden bezoekers. Wie over de <b>dijk bij Emmadorp</b> kijkt, ziet het oerlandschap van de Schelde: modder die dampt, vogels die trekken, en een horizon die twee keer per dag verandert.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (broedtijd op het schor), jul–sep (oeverloper en steltlopers-trek), sep–mrt (winterse schorren-rust)<br>\n    <b>Beste tijd van de dag:</b> Rond de wissel van eb en vloed — de geulen lopen vol en leeg.',
 'why': ['Het <b>grootste brakwaterschor van Europa</b> (3.580 ha).', 'De <b>verdronken dorpen</b> in de naam.', 'De <b>geulen-delta</b> met Speelmansgat en Hondegat.', 'De <b>waterbuffels op Baalhoek</b>.', 'Het <b>eeuwenoud veen</b> aan de oppervlakte.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Schorrenzangers</b> in het riet.', '<span class="months">Jul–sep</span> 🦅 <b>Trek van steltlopers</b> langs de geulen.', '<span class="months">Okt–mrt</span> 🪿 <b>Winterse schorren</b> met ganzen en smienten.', '<span class="months">Jaarrond</span> 🌊 <b>Getij</b> dat de horizon tweemaal daags herschrijft.'],
 'wild': ['🌊 Getijdenschor', '🏰 Verdronken dorp', '🐃 Waterbuffels', '🌿 Zilte flora', '🧭 Geulen-delta'],
 'trail': ['Start bij het <b>bezoekerscentrum bij Emmadorp</b>.', 'Wandel het <b>vrije gebied rond Emmadorp en Paal</b> (± 400 ha).', 'Boek een <b>excursie</b> voor het grote schor — nooit bij springtij alleen op pad.'],
 'foot': '🐕 Honden verboden/gesloten gebied · 💶 Gratis · ⚠️ Alleen met gids buiten vrije zone · 🌊 Check getij en springtij vooraf'
}, {
 'tags': ['Zeeland · Westerschelde mouth near Emmadorp/Nieuw-Namen (Zeeuws-Vlaanderen)', 'largest brackish marsh of Europe · 3,580 ha of mudflats, salt marshes and channels where villages lay until the 16th century — daily tide, water buffalo on the Schor van Baalhoek, freely accessible part around Emmadorp and Paal', 'list 85 · no. 36'],
 'loc': '📍 Verdronken Land van Saeftinghe, between Emmadorp and the Belgian border (visitor centre near Emmadorp) — ± 400 ha freely accessible around Emmadorp and Paal, the rest only by excursion; open sunrise–sunset, closed at spring tide; managed by the Zeeland Landscape Trust',
 'desc': 'At the mouth of the Westerschelde, where the Netherlands and Belgium touch across the water, lies the wildest tidal land of the country: the <b>Verdronken Land van Saeftinghe</b>, <b>3,580 hectares</b> of mudflats, salt marshes and channels — the <b>largest brackish marsh of Europe</b>. The name is no metaphor: in the late Middle Ages the <b>villages of Saeftinghe, Casuwele, Namen and Sint-Laureins</b> lay here, and even a <b>castle</b> — until floods in the <b>14th and 16th centuries</b> reclaimed the land and the tide has flowed in and out daily ever since. What remained is a <b>delta of channels</b> — the largest the <b>Speelmansgat</b>, the IJskelder and the Hondegat — with <b>70%</b> grown-over marsh: <b>sea aster, sea plantain, sea club-rush, saltmarsh grass and salt rush</b> on the salty west, vast <b>reed fields</b> on the freshening east, and here and there <b>centuries-old peat</b> at the surface. Cattle graze the marsh as the <b>sheep flocks</b> did for centuries — and on the <b>Schor van Baalhoek</b> <b>water buffalo</b> recently do that work, rejuvenating the overgrown marsh for <b>avocets</b>. Into the 1950s the plan was to <b>embank</b> the area — the Rijksdam and the Dam naar de Noord still witness it — but it became a nature area, now drawing tens of thousands of visitors yearly. Look over the <b>dike at Emmadorp</b> and you see the Scheldt’s primal landscape: steaming mud, travelling birds, and a horizon that changes twice a day.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (breeding season on the marsh), Jul–Sep (wader migration), Sep–Mar (wintry marsh rest)<br>\n    <b>Best time of day:</b> Around the turn of the tide — the channels fill and empty.',
 'why': ['The <b>largest brackish marsh of Europe</b> (3,580 ha).', 'The <b>drowned villages</b> in the name.', 'The <b>channel delta</b> with Speelmansgat and Hondegat.', 'The <b>water buffalo on Baalhoek</b>.', 'The <b>centuries-old peat</b> at the surface.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Marsh warblers</b> in the reed.', '<span class="months">Jul–Sep</span> 🦅 <b>Wader migration</b> along the channels.', '<span class="months">Oct–Mar</span> 🪿 <b>Wintry marsh</b> with geese and wigeon.', '<span class="months">Year-round</span> 🌊 <b>Tide</b> rewriting the horizon twice daily.'],
 'wild': ['🌊 Tidal marsh', '🏰 Drowned village', '🐃 Water buffalo', '🌿 Saline flora', '🧭 Channel delta'],
 'trail': ['Start at the <b>visitor centre near Emmadorp</b>.', 'Walk the <b>free area around Emmadorp and Paal</b> (± 400 ha).', 'Book an <b>excursion</b> for the great marsh — never go out alone at spring tide.'],
 'foot': '🐕 Dogs prohibited/closed area · 💶 Free · ⚠️ Guide only outside free zone · 🌊 Check tide and spring tide beforehand'
}, n2k='Het Verdronken Land van Saeftinghe vormt samen met de Westerschelde het Natura 2000-gebied Westerschelde & Saeftinghe — het brakke getijdenestuarium waar schorren, slikken en geulen de habitat bepalen.', n2k_en='The Verdronken Land van Saeftinghe forms, together with the Westerschelde, the Natura 2000 site Westerschelde & Saeftinghe — the brackish tidal estuary where marshes, mudflats and channels define the habitat.'))

C.append(mk.card(2292, 'De Grote Putting', {
 'tags': ['Zeeland · tussen Hengstdijk, Kloosterzande en Lamswaarde (gem. Hulst, Zeeuws-Vlaanderen)', 'oudland-weidegebied tot 1,6 m beneden NAP · in 2016 uitgebreid van 50 naar 176 ha — perceeltjes, slootjes en kijkheuvel; zomers weidevogels, winters ganzen', 'list 85 · no. 37'],
 'loc': '📍 De Grote Putting, ten zuidoosten van Hengstdijk in de Groote Hengstdijkpolder (kijkheuvel aan de Karnemelkstraat) — paden deels om het gebied; combineer met het Verdronken Land van Saeftinghe (kaart 2291) en De Vogel bij Kuitaart; beheer Staatsbosbeheer',
 'desc': 'In de <b>Groote Hengstdijkpolder</b> van Zeeuws-Vlaanderen, al vóór <b>1161</b> bedijkt door de <b>monniken van de Abdij Onze-Lieve-Vrouw Ten Duinen</b>, ligt een van de weinige echte <b>oudlandgebieden</b> die Zeeland nog telt: <b>De Grote Putting</b> — een laaggelegen weidegebied van <b>kleine perceeltjes, begrensd door kronkelende slootjes en greppels</b>, tot <b>1,6 meter beneden NAP</b>. Terwijl de ruilverkaveling van <b>1969</b> elders in de polder de historische indeling uitwiste, bleef de oude perceelsstructuur hier intact — het hollebollige grasland herinnert bovendien aan de <b>veenstekerij</b> die hier eeuwen geleden de ondergrond uitholde. In <b>2016</b> kreeg het gebied een nieuwe toekomst: de provincie en Staatsbosbeheer breidden het van <b>50 naar 176 hectare</b> uit — gras ingezaaid, laagtes gegraven, een <b>uitkijkpunt en infopunt</b> toegevoegd, en het wandelpad met 800 meter verlengd. Het resultaat is een open, vochtrijk grasland dat ’s zomers als <b>weidevogelgebied</b> functioneert — <b>grutto, tureluur, kievit, slobeend en kluut</b> — en ’s winters <b>kolganzen, grauwe ganzen en canadese ganzen</b> herbergt; broedvogels als <b>graspieper, veldleeuwerik, blauwborst, rietzanger en rietgors</b> vullen het koor, en <b>lepelaars en kleine zilverreigers</b> fourageren in de natte delen. Het gebied zelf is grotendeels gesloten — maar vanaf de <b>kijkheuvel aan de Karnemelkstraat</b>, en op het pad eromheen, is het hele oudland te overzien.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–jun</b> (weidevogels op het veld), okt–mrt (ganzen in grote aantallen), apr–mei (slobeend en kluut)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — weidevogels actief, licht over de slootjes.',
 'why': ['Het <b>oudland</b> met perceeltjes en slootjes.', 'De <b>ligging tot −1,6 m NAP</b>.', 'De <b>uitbreiding van 2016</b> (50 → 176 ha).', 'De <b>weidevogels</b> van grutto tot kluut.', 'De <b>winterse ganzen</b> in drie soorten.'],
 'phen': ['<span class="months">Mrt–jun</span> 🎶 <b>Weidevogels</b> op het oude land.', '<span class="months">Apr–sep</span> 🥄 <b>Lepelaars en zilverreigers</b> in de laagtes.', '<span class="months">Okt–mrt</span> 🪿 <b>Kol- en grauwe ganzen</b> op het gras.', '<span class="months">Jaarrond</span> 💧 <b>Slootjes-patronen</b> als oudland-erkenning.'],
 'wild': ['🌾 Oudland', '📉 −1,6 m NAP', '🐦 Weidevogels', '🪿 Winterganzen', '👁️ Kijkheuvel'],
 'trail': ['Bekijk het gebied vanaf de <b>kijkheuvel Karnemelkstraat</b>.', 'Loop het <b>pad rond het gebied</b> (deels langs slootjes).', 'Combineer met <b>Saeftinghe</b> (2291) voor het grote getijdencontrast.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 👀 Overzicht vanaf kijkheuvel · ⚠️ Gebied zelf grotendeels gesloten'
}, {
 'tags': ['Zeeland · between Hengstdijk, Kloosterzande and Lamswaarde (gem. Hulst, Zeeuws-Vlaanderen)', 'old-land meadow area up to 1.6 m below sea level · expanded in 2016 from 50 to 176 ha — small parcels, ditches and a viewing mound; summer meadow birds, winter geese', 'list 85 · no. 37'],
 'loc': '📍 De Grote Putting, south-east of Hengstdijk in the Groote Hengstdijkpolder (viewing mound at the Karnemelkstraat) — paths partly around the area; combine with the Verdronken Land van Saeftinghe (card 2291) and De Vogel near Kuitaart; managed by Staatsbosbeheer',
 'desc': 'In the <b>Groote Hengstdijkpolder</b> of Zeeuws-Vlaanderen, embanked before <b>1161</b> by the <b>monks of Ter Duinen Abbey</b>, lies one of the few true <b>old-land areas</b> left in Zeeland: <b>De Grote Putting</b> — a low-lying meadow area of <b>small parcels bounded by winding ditches and trenches</b>, up to <b>1.6 metres below sea level</b>. While the <b>1969</b> land consolidation wiped out the historic pattern elsewhere in the polder, the old parcel structure survived here — the bumpy grassland also recalls the <b>peat cutting</b> that hollowed out the subsoil centuries ago. In <b>2016</b> the area gained a new future: the province and Staatsbosbeheer expanded it from <b>50 to 176 hectares</b> — grass sown, hollows dug, a <b>viewpoint and info point</b> added, and the footpath extended by 800 metres. The result is an open, moisture-rich grassland serving in summer as a <b>meadow-bird area</b> — <b>black-tailed godwit, redshank, lapwing, shoveler and avocet</b> — and hosting <b>white-fronted, grey-lag and Canada geese</b> in winter; breeding birds such as <b>meadow pipit, skylark, bluethroat, reed warbler and reed bunting</b> fill the chorus, and <b>spoonbills and little egrets</b> feed in the wet parts. The area itself is mostly closed — but from the <b>viewing mound at the Karnemelkstraat</b>, and on the path around it, the whole old land can be surveyed.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jun</b> (meadow birds on the field), Oct–Mar (geese in large numbers), Apr–May (shoveler and avocet)<br>\n    <b>Best time of day:</b> Morning — meadow birds active, light over the ditches.',
 'why': ['The <b>old land</b> with parcels and ditches.', 'The <b>position up to −1.6 m NAP</b>.', 'The <b>2016 expansion</b> (50 → 176 ha).', 'The <b>meadow birds</b> from godwit to avocet.', 'The <b>winter geese</b> in three species.'],
 'phen': ['<span class="months">Mar–Jun</span> 🎶 <b>Meadow birds</b> on the old land.', '<span class="months">Apr–Sep</span> 🥄 <b>Spoonbills and egrets</b> in the hollows.', '<span class="months">Oct–Mar</span> 🪿 <b>White-fronted and grey-lag geese</b> on the grass.', '<span class="months">Year-round</span> 💧 <b>Ditch patterns</b> as old-land signature.'],
 'wild': ['🌾 Old land', '📉 −1.6 m NAP', '🐦 Meadow birds', '🪿 Winter geese', '👁️ Viewing mound'],
 'trail': ['View the area from the <b>Karnemelkstraat viewing mound</b>.', 'Walk the <b>path around the area</b> (partly along ditches).', 'Combine with <b>Saeftinghe</b> (2291) for the great tidal contrast.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 👀 Overview from the mound · ⚠️ Area itself mostly closed'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2292)
mk.check()
