# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2293, 'Het Koegat', {
 'tags': ['Zeeland · Stoppeldijkpolder, ten zuidoosten van Vogelwaarde (gem. Hulst)', '22 ha kreekrestant van Staatsbosbeheer · brak, ondiep water met rietzoom in de in 1707 bedijkte polder — watersnippen in de graspollen, rietgors in de riettop, kolganzen in de winter', 'list 85 · no. 38'],
 'loc': '📍 Het Koegat, ten zuidoosten van Vogelwaarde in de Stoppeldijkpolder — niet toegankelijk, maar prima te overzien vanaf de openbare weg bij Rapenburg; combineer met De Grote Putting (kaart 2292) en het Verdronken Land van Saeftinghe (2291); beheer Staatsbosbeheer',
 'desc': 'In de <b>Stoppeldijkpolder</b> van Zeeuws-Vlaanderen, die in <b>1707</b> werd ingedijkt nadat het land bij de <b>inundaties van 1584–1585</b> onder was gelopen, ligt een van de stille kreekrestanten van het oosten: <b>Het Koegat</b>, <b>22 hectare</b> natuurgebied van <b>Staatsbosbeheer</b> — een ondiepe, <b>brakke</b> kreek met een brede <b>rietzoom</b>, omringd door lage, door <b>koeien</b> beweide oevers. De naam zegt wat het is: het gat waar het vee bij de kreek dronk, of de kijk die de boer er op zijn beesten had — in elk geval is de landbouw nooit ver weg geweest. De natuur heeft het water overgenomen: in de winter herbergt het gebied <b>kolganzen</b> en andere watervogels; in de vorstvrije maanden verbergen <b>watersnippen</b> zich tussen de graspollen van de oevers en zingt de <b>rietgors</b> vanuit de top van een riethalm. In en om het water groeien enkele <b>zoutminnende plantensoorten</b> — het brakke karakter van het oude kreekwater is na drie eeuwen nog altijd voelbaar. Het gebied zelf is <b>niet toegankelijk</b>, maar dat is geen gemis: vanaf de <b>openbare weg van Rapenburg</b> is de hele kreek te overzien — een rustig pareltje in de polder, ver van alle drukte.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Okt–mrt</b> (kolganzen en winterse rust), mrt–mei (rietzangers in de zang), nov–feb (watersnippen bij vorst)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegeling op het brakke water.',
 'why': ['Het <b>kreekrestant</b> in de polder van 1707.', 'Het <b>brakke water</b> met zoutminnende planten.', 'De <b>watersnippen</b> tussen de graspollen.', 'De <b>rietgors</b> op de riethalm.', 'De <b>rust</b> van een niet-toegankelijk gebied.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎤 <b>Rietzangers</b> in de rietzoom.', '<span class="months">Apr–jun</span> 🦆 <b>Eenden en steltlopers</b> op de kreek.', '<span class="months">Okt–mrt</span> 🪿 <b>Kolganzen</b> op de poldervelden.', '<span class="months">Nov–feb</span> 🐦 <b>Watersnippen</b> in de winterse oevers.'],
 'wild': ['💧 Kreekrestant', '🧂 Brak water', '🌾 Rietzoom', '🐦 Watersnip', '🪿 Kolgans-winter'],
 'trail': ['Overzicht het gebied <b>vanaf de weg bij Rapenburg</b>.', 'Combineer met <b>De Grote Putting</b> (2292) en <b>Saeftinghe</b> (2291).', 'Neem de <b>verrekijker</b> mee — afstand kijken is hier de vorm.'],
 'foot': '🐕 Honden in de auto laten · 💶 Gratis · 👀 Alleen op afstand te zien · ⚠️ Gebied zelf niet toegankelijk'
}, {
 'tags': ['Zeeland · Stoppeldijkpolder, south-east of Vogelwaarde (gem. Hulst)', '22-ha creek remnant of Staatsbosbeheer · shallow brackish water with reed fringe in the polder embanked in 1707 — snipe in the tussocks, reed bunting on the reed top, white-fronted geese in winter', 'list 85 · no. 38'],
 'loc': '📍 Het Koegat, south-east of Vogelwaarde in the Stoppeldijkpolder — not accessible, but well surveyed from the public road at Rapenburg; combine with De Grote Putting (card 2292) and the Verdronken Land van Saeftinghe (2291); managed by Staatsbosbeheer',
 'desc': 'In the <b>Stoppeldijkpolder</b> of Zeeuws-Vlaanderen, embanked in <b>1707</b> after the land had flooded in the <b>inundations of 1584–1585</b>, lies one of the east’s quiet creek remnants: <b>Het Koegat</b>, <b>22 hectares</b> of nature of <b>Staatsbosbeheer</b> — a shallow, <b>brackish</b> creek with a broad <b>reed fringe</b>, surrounded by low banks grazed by <b>cattle</b>. The name says what it is: the gap where the livestock drank at the creek — in any case farming was never far away. Nature has taken over the water: in winter the area holds <b>white-fronted geese</b> and other water birds; in the snow-free months <b>snipe</b> hide between the tussocks of the banks and the <b>reed bunting</b> sings from the top of a reed stem. In and around the water grow several <b>salt-loving plant species</b> — the brackish character of the old creek water still tangible after three centuries. The area itself is <b>not accessible</b>, but that is no loss: from the <b>public road at Rapenburg</b> the whole creek can be surveyed — a quiet pearl in the polder, far from all bustle.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Oct–Mar</b> (white-fronted geese and wintry rest), Mar–May (reed warblers in song), Nov–Feb (snipe in frost)<br>\n    <b>Best time of day:</b> Morning — mirror on the brackish water.',
 'why': ['The <b>creek remnant</b> in the 1707 polder.', 'The <b>brackish water</b> with salt-loving plants.', 'The <b>snipe</b> between the tussocks.', 'The <b>reed bunting</b> on the reed stem.', 'The <b>quiet</b> of an inaccessible area.'],
 'phen': ['<span class="months">Mar–May</span> 🎤 <b>Reed warblers</b> in the reed fringe.', '<span class="months">Apr–Jun</span> 🦆 <b>Ducks and waders</b> on the creek.', '<span class="months">Oct–Mar</span> 🪿 <b>White-fronted geese</b> on the polder fields.', '<span class="months">Nov–Feb</span> 🐦 <b>Snipe</b> on the wintry banks.'],
 'wild': ['💧 Creek remnant', '🧂 Brackish water', '🌾 Reed fringe', '🐦 Snipe', '🪿 Goose winter'],
 'trail': ['Survey the area <b>from the road at Rapenburg</b>.', 'Combine with <b>De Grote Putting</b> (2292) and <b>Saeftinghe</b> (2291).', 'Bring <b>binoculars</b> — distance watching is the form here.'],
 'foot': '🐕 Leave dogs in the car · 💶 Free · 👀 Visible from a distance only · ⚠️ Area itself not accessible'
}))

C.append(mk.card(2294, 'De Molenbeek', {
 'tags': ['Noord-Brabant · beekdal in het grensland van Zundert, Rucphen en Etten-Leur', 'kleine molenbeek met haar dal · waterlopen als de Aa of Weerijs, de Bijloop en de Turfvaart doorsnijden dit land — de Molenbeek dankt haar naam aan de watermolen die er eeuwen geleden op stond', 'list 86 · no. 2'],
 'loc': '📍 De Molenbeek, beekdal in het West-Brabantse grensland van Zundert, Rucphen en Etten-Leur — weggetjes en paden langs beek en houtwallen; combineer met de Pannenhoef (kaart 2303) en het Schuitvaartjaagpad (2304)',
 'desc': 'Het West-Brabantse grensland is een land van <b>water</b>: van de hogere zandgronden bij de Belgische grens loopt een fijn web van beken naar het noorden — de <b>Aa of Weerijs</b>, de <b>Bijloop</b>, de <b>Turfvaart</b> — en tussen die grotere namen stroomden eeuwenlang ook de kleine <b>molenbeekjes</b>, genoemd naar de <b>watermolens</b> die er op stonden en het land zijn meel en zijn papier leverden. <b>De Molenbeek</b> uit het boek is zo’n klein dal: een beekje met <b>houtwallen en singels</b>, natte <b>hooilanden</b> op de komgronden, en hier en daar een <b>beekbegeleidend bosje</b> van els en es — het klassieke beekdallandschap van dit deel van Brabant, dat eeuwenlang te nat was voor de ploeg en daardoor zijn structuur mocht houden. Wie de weggetjes langs zo’n beek volgt, ziet de ecologie van het kleine water: <b>dotterbloem en pinksterbloem</b> in de natte randen van het voorjaar, <b>libellen</b> boven de stroom in de zomer, en in de winter de <b>ijsvogel</b> die de kleine beken als jachtterrein gebruikt. De beekdalen van Zundert en Rucphen zijn bovendien de <b>verbindende aders</b> tussen de natuurgebieden — van de Pannenhoef (kaart 2303) tot de Gooren en Krochten (2307) loopt het leven langs het water. De Molenbeek is de kaart van dat kleine water: geen park, geen poort, maar een beek die het land bij elkaar houdt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (dotterbloemen-tapijt, libellen beginnen), mei–sep (ijsvogel-season), sep–okt (hooiland-nazomer)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en stromend water.',
 'why': ['De <b>watermolen</b> als naamgever van de beek.', 'Het <b>web van beken</b> in het grensland.', 'De <b>hooilanden en houtwallen</b> van het dal.', 'De <b>ijsvogel</b> als kleine-beek-soort.', 'De <b>verbindende functie</b> tussen de natuurgebieden.'],
 'phen': ['<span class="months">Apr–mei</span> 🌸 <b>Dotter- en pinksterbloem</b> in de natte randen.', '<span class="months">Mei–sep</span> 🐦 <b>IJsvogel</b> boven het stromende water.', '<span class="months">Jun–aug</span> 🐉 <b>Libellen</b> op de beek.', '<span class="months">Sep–okt</span> 🍂 <b>Hooiland-nazomer</b> in het dal.'],
 'wild': ['💧 Beekdal', '⚙️ Watermolen-verleden', '🌸 Dotterbloemen', '🐦 IJsvogel', '🧵 Verbindende ader'],
 'trail': ['Volg de <b>weggetjes langs beek en houtwallen</b>.', 'Combineer met de <b>Pannenhoef</b> (2303) — het water komt er samen.', 'Zoek in de zomer de <b>ijsvogel</b> op de kleine beken.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Routetjes ± 3–8 km · ⚠️ Natte stukken — laarzen'
}, {
 'tags': ['North Brabant · stream valley in the border land of Zundert, Rucphen and Etten-Leur', 'small mill stream with its valley · waterways such as the Aa of Weerijs, the Bijloop and the Turfvaart cross this land — the Molenbeek owes its name to the watermill that once stood on it', 'list 86 · no. 2'],
 'loc': '📍 De Molenbeek, stream valley in the West-Brabant border land of Zundert, Rucphen and Etten-Leur — lanes and paths along stream and hedges; combine with the Pannenhoef (card 2303) and the Schuitvaart towpath (2304)',
 'desc': 'The West-Brabant border land is a country of <b>water</b>: from the higher sands at the Belgian border a fine web of streams runs north — the <b>Aa of Weerijs</b>, the <b>Bijloop</b>, the <b>Turfvaart</b> — and among those greater names small <b>mill streams</b> have flowed for centuries, named after the <b>watermills</b> that stood on them, providing the land with its flour and its paper. The book’s <b>Molenbeek</b> is such a small valley: a stream with <b>hedges and tree rows</b>, wet <b>hay meadows</b> on the basin clays, and here and there a <b>streamside wood</b> of alder and ash — the classic stream-valley landscape of this part of Brabant, for centuries too wet for the plough and therefore allowed to keep its structure. Follow the lanes along such a stream and you see the ecology of small water: <b>marsh marigold and cuckoo flower</b> in the wet edges of spring, <b>dragonflies</b> over the current in summer, and in winter the <b>kingfisher</b> using the small streams as hunting ground. The valleys of Zundert and Rucphen are moreover the <b>connecting arteries</b> between the nature areas — from the Pannenhoef (card 2303) to the Gooren and Krochten (2307) life runs along the water. The Molenbeek is the card of that small water: no park, no gate, but a stream holding the land together.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (marsh-marigold carpet, dragonflies starting), May–Sep (kingfisher season), Sep–Oct (hay-meadow late summer)<br>\n    <b>Best time of day:</b> Morning — dew and running water.',
 'why': ['The <b>watermill</b> as the stream’s name giver.', 'The <b>web of streams</b> in the border land.', 'The <b>hay meadows and hedges</b> of the valley.', 'The <b>kingfisher</b> as small-stream species.', 'The <b>connecting function</b> between nature areas.'],
 'phen': ['<span class="months">Apr–May</span> 🌸 <b>Marsh marigold and cuckoo flower</b> in the wet edges.', '<span class="months">May–Sep</span> 🐦 <b>Kingfisher</b> over the running water.', '<span class="months">Jun–Aug</span> 🐉 <b>Dragonflies</b> on the stream.', '<span class="months">Sep–Oct</span> 🍂 <b>Hay-meadow late summer</b> in the valley.'],
 'wild': ['💧 Stream valley', '⚙️ Watermill past', '🌸 Marsh marigolds', '🐦 Kingfisher', '🧵 Connecting artery'],
 'trail': ['Follow the <b>lanes along stream and hedges</b>.', 'Combine with the <b>Pannenhoef</b> (2303) — the water gathers there.', 'Seek the <b>kingfisher</b> on the small streams in summer.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Routes ± 3–8 km · ⚠️ Wet stretches — boots'
}))

C.append(mk.card(2295, 'Visdonk en Rozeven', {
 'tags': ['Noord-Brabant · ten zuiden van Roosendaal, ten oosten van Nispen', 'landgoed Visdonk met het Rozenven · 110 ha Natuurmonumenten (sinds 2010) in een landgoed van ± 300 ha — beenbreek, klokjesgentiaan en zonnedauw rond het ven; Kalmthoutse schapen en een hertenkamp', 'list 86 · no. 3'],
 'loc': '📍 Landgoed Visdonk, ten zuiden van Roosendaal (parkeerplaats aan de Zundertseweg) — rode route 11 km, gele route 2,4 km en natuurpad voor kinderen; combineer met de Rucphense Bossen (kaart 2296); beheer Natuurmonumenten',
 'desc': 'Als Roosendalers zeggen dat ze “naar het bos gaan”, bedoelen ze <b>Visdonk</b>: het landgoed ten zuiden van de stad, ± <b>300 hectare</b> groot in zijn geheel, waarvan sinds <b>2010</b> <b>110 hectare natuurgebied van Natuurmonumenten</b> is — overgenomen van de gemeente en sindsdien beheerd als een parel van de “<b>groene kamertjes</b>”: kleine percelen bos, heide, weide en lanen die elkaar afwisselen als kamers in een oud huis. Middenin ligt de beroemdste kamer: het <b>Rozenven</b>, één van de <b>laatste overgebleven vennen van de regio Roosendaal</b>, waar rond het water <b>beenbreek, klokjesgentiaan, kleine en ronde zonnedauw, witte snavelbies en moerashertshooi</b> groeien — een venflora die in West-Brabant zeldzamer is geworden dan elders in het land. De heidevelden worden begraasd door <b>Kalmthoutse schapen</b>, en in het gebied ligt een <b>herten- en moeflonkamp</b> — de grote grazers die kinderen van het pad af kunnen spotten. Natuurmonumenten herstelde de laatste jaren <b>heide en vennen</b>: sloten gedicht, heideplaggen uitgereden, en over het nieuwe heideveld ligt nu een <b>vlonderpad</b> (tussen knooppunt 72 en 73) dat het natte terrein voor wandelaars opent. De <b>rode route van 11 km</b> voert langs ven en heide; de <b>gele van 2,4 km</b> en het <b>natuurpad</b> aan de Zundertseweg houden het kort. Visdonk is bovendien de <b>groene schakel</b> tussen de Rucphense Bossen, de landgoederen van Zundert en het Grenspark De Zoom-Kalmthoutse Heide — het bos van Roosendaal, in het grootste verband dat West-Brabant kent.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide paars rond het ven), apr–jun (zangvogels), jun–sep (libellen op het Rozenven)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — nevel over het ven, reeën op de kamertjes.',
 'why': ['De <b>groene kamertjes</b> van bos, hei en weide.', 'Het <b>Rozenven</b> met zijn zeldzame venflora.', 'De <b>beenbreek en klokjesgentiaan</b>.', 'De <b>Kalmthoutse schapen en het hertenkamp</b>.', 'De <b>schakelfunctie</b> tussen drie natuurgebieden.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Zangvogels</b> in de kamertjes.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven het Rozenven.', '<span class="months">Aug–sep</span> 💜 <b>Paarse heide</b> tot aan het water.', '<span class="months">Okt–nov</span> 🦌 <b>Herten in het kamp</b> tijdens de bronst.'],
 'wild': ['💧 Rozenven', '💜 Heide', '🌸 Klokjesgentiaan', '🐑 Kalmthoutse schapen', '🦌 Hertenkamp'],
 'trail': ['Loop de <b>rode route</b> (11 km) langs ven en heide.', 'Neem de kids mee op het <b>natuurpad</b> aan de Zundertseweg.', 'Ga het <b>vlonderpad</b> op tussen knooppunt 72–73.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routes 2,4 / 11 km · 🅿️ Parkeerplaats Zundertseweg'
}, {
 'tags': ['North Brabant · south of Roosendaal, east of Nispen', 'Visdonk estate with the Rozenven · 110 ha of the Nature Trust (since 2010) within a ± 300-ha estate — bog asphodel, gentian and sundew around the pool; Kalmthout sheep and a deer enclosure', 'list 86 · no. 3'],
 'loc': '📍 Landgoed Visdonk, south of Roosendaal (parking at the Zundertseweg) — red route 11 km, yellow route 2.4 km and a nature trail for children; combine with the Rucphense Bossen (card 2296); managed by Natuurmonumenten',
 'desc': 'When Roosendaal locals say they are “going to the woods”, they mean <b>Visdonk</b>: the estate south of the city, ± <b>300 hectares</b> as a whole, of which <b>110 hectares</b> have been <b>Nature Trust land since 2010</b> — taken over from the municipality and managed as a pearl of the “<b>green rooms</b>”: small parcels of wood, heath, meadow and lanes alternating like rooms in an old house. At the centre lies the most famous room: the <b>Rozenven</b>, one of the <b>last surviving pools of the Roosendaal region</b>, where around the water grow <b>bog asphodel, gentian, round-leaved and great sundew, white beak-sedge and marsh St John’s wort</b> — a pool flora become rarer in West Brabant than anywhere else in the country. The heath fields are grazed by <b>Kalmthout sheep</b>, and the area holds a <b>deer and mouflon enclosure</b> — the big grazers children can spot from the path. In recent years the Trust restored <b>heath and pools</b>: ditches sealed, heath turfs spread, and across the new heath field runs a <b>boardwalk</b> (between nodes 72 and 73) opening the wet terrain to walkers. The <b>red route of 11 km</b> leads past pool and heath; the <b>yellow of 2.4 km</b> and the <b>nature trail</b> at the Zundertseweg keep it short. Visdonk is moreover the <b>green link</b> between the Rucphense Bossen, the Zundert estates and the Grenspark De Zoom-Kalmthoutse Heide — Roosendaal’s wood, in the widest frame West Brabant knows.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather purple around the pool), Apr–Jun (songbirds), Jun–Sep (dragonflies on the Rozenven)<br>\n    <b>Best time of day:</b> Morning — mist over the pool, deer in the rooms.',
 'why': ['The <b>green rooms</b> of wood, heath and meadow.', 'The <b>Rozenven</b> with its rare pool flora.', 'The <b>bog asphodel and gentian</b>.', 'The <b>Kalmthout sheep and the deer enclosure</b>.', 'The <b>link function</b> between three nature areas.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Songbirds</b> in the rooms.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> over the Rozenven.', '<span class="months">Aug–Sep</span> 💜 <b>Purple heath</b> down to the water.', '<span class="months">Oct–Nov</span> 🦌 <b>Deer in the enclosure</b> during the rut.'],
 'wild': ['💧 Rozenven', '💜 Heath', '🌸 Gentian', '🐑 Kalmthout sheep', '🦌 Deer enclosure'],
 'trail': ['Walk the <b>red route</b> (11 km) past pool and heath.', 'Take the children on the <b>nature trail</b> at the Zundertseweg.', 'Take the <b>boardwalk</b> between nodes 72–73.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 2.4 / 11 km · 🅿️ Parking Zundertseweg'
}))

C.append(mk.card(2296, 'Rucphense Bossen', {
 'tags': ['Noord-Brabant · tussen Rucphen en Roosendaal (tot aan de Belgische grens)', 'naaldbossen, heide en ijstijd-duinen van Natuurmonumenten · op de dekzandrug die eeuwenlang verstuifde — begin 20e eeuw bebost; wandelen, fietsen, ruiter- en mtb-routes door één geheel', 'list 86 · no. 4'],
 'loc': '📍 Rucphense Bossen, tussen Rucphen en Roosendaal (Postbaan, Rucphen) — wandel-, fiets-, ruiter- en mountainbikeroutes; combineer met Visdonk (kaart 2295) en de Rucphense Heide (2297); beheer Natuurmonumenten',
 'desc': 'Tussen <b>Rucphen</b> en <b>Roosendaal</b>, doorlopend tot aan de <b>Belgische grens</b>, ligt het grootste aaneengesloten bosgebied van deze hoek van Brabant: de <b>Rucphense Bossen</b> van <b>Natuurmonumenten</b> — al is “bossen” een onderbelichte naam voor wat er ligt. Op de <b>dekzandrug</b> hier schiep de wind in de <b>IJstijd</b> de <b>zandduinen</b> die je er nog steeds ziet; daarna was het eeuwenlang heide en <b>stuifzand</b>, tot de mensen begin <b>20e eeuw</b> de dennen plantten die vandaag de donkere kamers van het gebied vormen. Het resultaat is een natuurgebied dat per stap van karakter wisselt: <b>dichte naaldbossen</b> die in de zomer koel en donker zijn, <b>uitgestrekte zandvlakten</b> met bomen om in te klimmen, <b>loofbos</b>, <b>heidevelden</b> die in augustus paars kleuren en <b>graslanden</b> — een mozaïek dat per seizoen een andere gedaante heeft. Natuurmonumenten opent de laatste jaren <b>open plekken</b> in de dichte bossen, zodat er weer licht en ruimte komt voor nieuwe planten en dieren. Voor bezoekers is het gebied een sportpark van de natuurlijke soort: <b>wandel- en fietsroutes</b>, een <b>lange ruiterroute</b> van Roosendaal tot België, en een <b>mountainbikeroute</b> voor de waaghalzen — vrij wandelen op wegen en paden, honden welkom aangelijnd. Delen van de bossen doen bovendien dienst als <b>drinkwaterwingebied</b>: een stille dubbel functie die het gebied extra rust geeft.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–okt</b> (wandel- en mtb-seizoen), aug–sep (heide paars), sep–nov (paddenstoelen in het naaldbos)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — lichtstralen door de dennen.',
 'why': ['De <b>ijstijd-zandduinen</b> midden in het bos.', 'De <b>afwisseling</b> van naaldbos, zandvlakte, heide en grasland.', 'De <b>ruiter- en mtb-routes</b> door het hele gebied.', 'De <b>bebossing van begin 20e eeuw</b> als geschiedenis.', 'De <b>drinkwaterfunctie</b> als stille tweede taak.'],
 'phen': ['<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in de naaldbossen.', '<span class="months">Aug–sep</span> 💜 <b>Heidevelden paars</b> tussen het groen.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> onder de dennen.', '<span class="months">Jaarrond</span> 🏇 <b>Ruiter- en mtb-routes</b> in vol gebruik.'],
 'wild': ['🌲 Naaldbossen', '🏔️ Zandduinen', '💜 Heide', '🐎 Ruiterroutes', '💧 Drinkwaterwingebied'],
 'trail': ['Start bij de <b>Postbaan</b> en kies een wandel- of fietsroute.', 'Rijd de <b>ruiterroute</b> richting de Belgische grens.', 'Combineer met <b>Visdonk</b> (2295) en de <b>Rucphense Heide</b> (2297).'],
 'foot': '🐕 Honden aangelijnd welkom · 💶 Gratis · 🚶/🚲/🏇/🚵 Routes 5–40 km · 🅿️ Parkeerplaatsen aan de Postbaan'
}, {
 'tags': ['North Brabant · between Rucphen and Roosendaal (up to the Belgian border)', 'conifer woods, heath and Ice-Age dunes of the Nature Trust · on the cover-sand ridge that drifted for centuries — afforested in the early 20th century; walking, cycling, riding and mtb routes in one whole', 'list 86 · no. 4'],
 'loc': '📍 Rucphense Bossen, between Rucphen and Roosendaal (Postbaan, Rucphen) — walking, cycling, riding and mountain-bike routes; combine with Visdonk (card 2295) and the Rucphense Heide (2297); managed by Natuurmonumenten',
 'desc': 'Between <b>Rucphen</b> and <b>Roosendaal</b>, running on to the <b>Belgian border</b>, lies the largest continuous forest of this corner of Brabant: the <b>Rucphense Bossen</b> of the <b>Nature Trust</b> — though “woods” undersells what lies here. On the <b>cover-sand ridge</b> the wind built the <b>sand dunes</b> of the <b>Ice Age</b> still visible today; after that came centuries of heath and <b>drifting sand</b>, until people planted the pines of the early <b>20th century</b> that now form the area’s dark chambers. The result is a nature area changing character with every step: <b>dense conifer woods</b> cool and dark in summer, <b>wide sand flats</b> with trees to climb, <b>broadleaf wood</b>, <b>heath fields</b> turning purple in August and <b>grasslands</b> — a mosaic with a different face each season. In recent years the Trust has opened <b>clearings</b> in the dense woods, bringing light and space for new plants and animals. For visitors the area is a sports park of the natural kind: <b>walking and cycling routes</b>, a <b>long riding route</b> from Roosendaal to Belgium, and a <b>mountain-bike route</b> for the brave — free wandering on roads and paths, dogs welcome on lead. Parts of the woods also serve as a <b>drinking-water catchment</b>: a quiet second function giving the area extra silence.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Oct</b> (walking and mtb season), Aug–Sep (heather purple), Sep–Nov (fungi in the conifer wood)<br>\n    <b>Best time of day:</b> Morning — shafts of light through the pines.',
 'why': ['The <b>Ice-Age sand dunes</b> in the middle of the wood.', 'The <b>alternation</b> of conifer, sand flat, heath and grassland.', 'The <b>riding and mtb routes</b> through the whole area.', 'The <b>early-20th-century afforestation</b> as history.', 'The <b>drinking-water function</b> as quiet second role.'],
 'phen': ['<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the conifer woods.', '<span class="months">Aug–Sep</span> 💜 <b>Heath fields purple</b> between the green.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> under the pines.', '<span class="months">Year-round</span> 🏇 <b>Riding and mtb routes</b> in full use.'],
 'wild': ['🌲 Conifer woods', '🏔️ Sand dunes', '💜 Heath', '🐎 Riding routes', '💧 Water catchment'],
 'trail': ['Start at the <b>Postbaan</b> and choose a walking or cycling route.', 'Ride the <b>riding route</b> towards the Belgian border.', 'Combine with <b>Visdonk</b> (2295) and the <b>Rucphense Heide</b> (2297).'],
 'foot': '🐕 Dogs welcome on lead · 💶 Free · 🚶/🚲/🏇/🚵 Routes 5–40 km · 🅿️ Parking at the Postbaan'
}))

C.append(mk.card(2297, 'Rucphense Heide', {
 'tags': ['Noord-Brabant · bij Rucphen (tussen de Rucphense Bossen en de Zundertse landgoederen)', '450 ha restant van een ooit uitgestrekt heidelandschap · het open hart tussen de bossen — hier en daar vergrast, maar vol bloemen en de rust van het grote lichte land', 'list 86 · no. 5'],
 'loc': '📍 Rucphense Heide, ten zuiden van Rucphen tussen de Rucphense Bossen — paden en routes over en rond de heide; combineer met de Rucphense Bossen (kaart 2296) en de fietsroute naar de Oude Buisse Heide (2299)',
 'desc': 'Wie van Rucphen naar het zuiden kijkt, ziet het open land dat de streek eeuwenlang defineerde: de <b>Rucphense Heide</b>, ooit een uitgestrekt heidegebied waar de schapen van het hele dorp liepen, waarvan nog <b>± 450 hectare</b> over is — groot genoeg om de wind te horen, klein genoeg om te begrijpen wat er verdween. Want verdwijnen deed de heide: sinds de negentiende eeuw namen <b>ontginningen, bossen en landbouw</b> het grootste deel in, en wat rest is een mozaïek van <b>open heidevelden</b>, hier en daar <b>vergrast</b>, afgewisseld met bosranden, vennetjes en zandpaden. Juist dat half-open karakter maakt de heide waardevol: in de overgangen tussen hei, gras en bos broeden <b>roodborsttapuit en graspieper</b>, boven de vlakten zingt in het vroege voorjaar de <b>boomleeuwerik</b>, en in augustus kleurt de struikhei <b>paars</b> over honderden meters. De heide is het <b>open hart</b> tussen de Rucphense Bossen (kaart 2296) en de landgoederen van Zundert — wie de fietstocht “de schrijfster en de schilder” rijdt, kruist ze onderweg van de Oude Buisse Heide naar Visdonk, op een steenworp van het geboorteland van <b>Vincent van Gogh</b>. De heuvels van het stuifzand, de schapen van weleer en de stilte van het lichte land: de Rucphense Heide is de kaart van het oude Brabant dat bleef.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide paars), mrt–mei (boomleeuwerik en tapuiten), sep–okt (ochtendnevel over de hei)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — zang en nevel.',
 'why': ['Het <b>450 ha restant</b> van het grote heidelandschap.', 'De <b>boomleeuwerik</b> boven de vlakten.', 'De <b>openheid</b> als karakter van het oude Brabant.', 'De <b>ligging tussen bossen en landgoederen</b>.', 'De <b>Van Gogh-fietsroute</b> als moderne laag.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Boomleeuwerik en tapuit</b> in zang.', '<span class="months">Mei–aug</span> 🦋 <b>Heidevlinders</b> op de bloemen.', '<span class="months">Aug–sep</span> 💜 <b>Struikhei paars</b> over de vlakte.', '<span class="months">Sep–okt</span> 🌫️ <b>Ochtendnevel</b> over het open land.'],
 'wild': ['💜 Heide-restant', '🎵 Boomleeuwerik', '🌾 Open vlakten', '🚲 Van Gogh-route', '🏔️ Stuifzandheuvels'],
 'trail': ['Wandel of fiets de <b>heidepaden</b> tussen de bossen.', 'Combineer met de <b>Rucphense Bossen</b> (2296).', 'Rijd de <b>fietsroute “de schrijfster en de schilder”</b> naar Zundert.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶/🚲 Routetjes ± 4–12 km · ⚠️ Open land — zon en wind'
}, {
 'tags': ['North Brabant · near Rucphen (between the Rucphense Bossen and the Zundert estates)', '450-ha remnant of a once vast heath landscape · the open heart between the woods — partly overgrown with grass, but full of flowers and the silence of the great light land', 'list 86 · no. 5'],
 'loc': '📍 Rucphense Heide, south of Rucphen between the Rucphense Bossen — paths and routes over and around the heath; combine with the Rucphense Bossen (card 2296) and the cycle route to the Oude Buisse Heide (2299)',
 'desc': 'Looking south from Rucphen you see the open land that defined the region for centuries: the <b>Rucphense Heide</b>, once a vast heath where the whole village’s sheep walked, of which ± <b>450 hectares</b> remain — large enough to hear the wind, small enough to understand what disappeared. For disappear it did: from the nineteenth century <b>reclaiming, forestry and farming</b> took most of it, and what remains is a mosaic of <b>open heath fields</b>, here and there <b>grassed over</b>, alternating with wood edges, small pools and sand paths. Precisely that half-open character makes the heath valuable: in the transitions between heath, grass and wood <b>stonechat and meadow pipit</b> breed, above the plains the <b>wood lark</b> sings in early spring, and in August the ling turns <b>purple</b> for hundreds of metres. The heath is the <b>open heart</b> between the Rucphense Bossen (card 2296) and the estates of Zundert — cyclists on the “writer and painter” route cross it on the way from the Oude Buisse Heide to Visdonk, within a stone’s throw of <b>Vincent van Gogh</b>’s native country. The hills of drifting sand, the sheep of old and the silence of the light land: the Rucphense Heide is the card of the old Brabant that stayed.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heather purple), Mar–May (wood lark and stonechats), Sep–Oct (morning mist over the heath)<br>\n    <b>Best time of day:</b> Early morning — song and mist.',
 'why': ['The <b>450-ha remnant</b> of the great heath landscape.', 'The <b>wood lark</b> above the plains.', 'The <b>openness</b> as the character of old Brabant.', 'The <b>position between woods and estates</b>.', 'The <b>Van Gogh cycle route</b> as modern layer.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Wood lark and stonechat</b> in song.', '<span class="months">May–Aug</span> 🦋 <b>Heath butterflies</b> on the flowers.', '<span class="months">Aug–Sep</span> 💜 <b>Ling purple</b> across the plain.', '<span class="months">Sep–Oct</span> 🌫️ <b>Morning mist</b> over the open land.'],
 'wild': ['💜 Heath remnant', '🎵 Wood lark', '🌾 Open plains', '🚲 Van Gogh route', '🏔️ Sand hills'],
 'trail': ['Walk or cycle the <b>heath paths</b> between the woods.', 'Combine with the <b>Rucphense Bossen</b> (2296).', 'Ride the <b>“writer and painter” cycle route</b> to Zundert.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶/🚲 Routes ± 4–12 km · ⚠️ Open land — sun and wind'
}))

mk.insert(C, chunk='reserves-2235-2334.json')
mk.progress(2297)
mk.check()
