# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2312, 'Valkenberg', {
 'tags': ['Noord-Brabant · landgoed ten zuiden van Ulvenhout, in de uiterste westhoek van Gilze en Rijen (Chaamse beken-zone)', '220 ha particulier landgoed · met Hondsdonk en Luchtenburg één aaneengesloten landgoederenzone van ±561 ha — lanenstelsel uit ±1770, de Meeldreef met reusachtige bomen, en de Valkenbergse Ley die naar de Chaamse Beek stroomt', 'list 87 · no. 5'],
 'loc': '📍 Landgoed Valkenberg, einde Valkenburgseweg bij Ulvenhout (tussen Geersbroekseweg, Royaledreef en Chaamseweg) — opengesteld voor wandelaars ( behalve de directe omgeving van het landhuis); combineer met Hondsdonk (kaart 2311) en de Strijbeekse Heide (kaart 2310)',
 'desc': 'Verscholen in het bos tussen <b>Ulvenhout</b>, <b>Geersbroek</b> en de <b>Chaamseweg</b> ligt een van de grootste particuliere landgoederen van West-Brabant: <b>Valkenberg</b>, <b>220 hectare</b> groot, in een merkwaardige uitloper van de gemeente <b>Gilze en Rijen</b> die bij de herindeling van 1826 langs de beekjes werd getekend — dichter bij Ulvenhout en Bavel dan bij Gilze, maar daardoor des te groter. Het landgoed vormt samen met <b>Hondsdonk</b> (kaart 2311) en <b>Luchtenburg</b> één vrijwel aaneengesloten <b>landgoederenzone van ±561 hectare</b>, onderdeel van de <b>Chaamse beken-zone</b>, en grenst weer aan de <b>Strijbeekse Heide</b> — de groene keten die zuidelijk Breda verbindt. De vroegste vermelding van een eigenaar stamt uit <b>1420</b>: een zekere “joffrouw” Lijsbeth van Valkenberge, verder onbekend — de naam kan ook naar het golvende terrein en de <b>valkenjacht</b> verwijzen. Het huidige gezicht kreeg Valkenberg onder <b>Benjamin van der Borch</b>, die het in de late achttiende eeuw tot een <b>demonstratie-landgoed</b> omvormde: herbouw van het oude huis, nieuwe hoeves, een <b>Engelse tuin met grote en kleine vijver (1792)</b>, en het <b>lanenstelsel uit ±1770</b> dat nog altijd de hoofdas vormt — met de <b>Meeldreef</b> als hoogtepunt, omgeven door reusachtige bomen en aan weerszijden het ezelspad van het personeel. De familie Van der Borch vormde bovendien de geschiedenis van de hele zone: broer <b>Lucas</b> bezat <b>Hondsdonk</b> en kocht in 1802 ook <b>Luchtenburg</b> — alle drie de landgoederen in één hand — en via een erfelijke lijn met Baron Prisse van Hondsdonk is die band tot vandaag bewaard. Het bos is rijk gemengd — <b>eik, beuk, es, berk, larix en douglasspar</b> — en wordt doorsneden door de <b>Valkenbergse Ley</b>, die naar de <b>Chaamse Beek</b> stroomt; in het voorjaar kleuren <b>dotterbloem en bittere veldkers</b> de natte randen, en her en der staan een oude <b>vijver</b> en een in onbruik geraakte <b>ijskelder</b> te vertellen hoe een landgoed zichzelf voorheen koel hield.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–mei</b> (dotterbloemen in de beekranden), apr–jun (zangvogels in de lanen), sep–nov (herfstlicht op de Meeldreef)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — lichtval over de dreef.',
 'why': ['De <b>Meeldreef</b> met reusachtige bomen en ezelspaden.', 'De <b>landgoederenzone</b> met Hondsdonk en Luchtenburg (±561 ha).', 'De <b>Van der Borch-dynastie</b> over drie goederen.', 'De <b>Engelse tuin met vijvers (1792)</b>.', 'De <b>Valkenbergse Ley</b> richting Chaamse Beek.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌼 <b>Dotterbloem en bittere veldkers</b> aan de Ley.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het lanenstelsel.', '<span class="months">Jun–aug</span> 🦗 <b>Zomerschaduw</b> onder beuk en eik.', '<span class="months">Sep–nov</span> 🍂 <b>Herfstlicht</b> op de Meeldreef.'],
 'wild': ['🌳 220 ha landgoed', '🛤️ Lanen ±1770', '🌾 Chaamse beken-zone', '🏰 Van der Borch', '💧 Engelse tuin-vijvers'],
 'trail': ['Loop de <b>Meeldreef</b> met zijn reusachtige bomen en ezelspaden.', 'Volg de <b>Valkenbergse Ley</b> stroomafwaarts naar de Chaamse Beek.', 'Combineer met <b>Hondsdonk</b> (2311) en de <b>Strijbeekse Heide</b> (2310).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–8 km · ⚠️ Landhuis-omgeving niet opengesteld'
}, {
 'tags': ['North Brabant · estate south of Ulvenhout, in the far western corner of Gilze en Rijen (Chaamse beken-zone)', '220 ha private estate · with Hondsdonk and Luchtenburg one nearly unbroken estate zone of ±561 ha — lane system from ±1770, the Meeldreef with giant trees, and the Valkenbergse Ley flowing towards the Chaamse Beek', 'list 87 · no. 5'],
 'loc': '📍 Valkenberg estate, end of the Valkenburgseweg near Ulvenhout (between Geersbroekseweg, Royaledreef and Chaamseweg) — open to walkers (except the immediate surroundings of the country house); combine with Hondsdonk (card 2311) and the Strijbeekse Heide (card 2310)',
 'desc': 'Hidden in the wood between <b>Ulvenhout</b>, <b>Geersbroek</b> and the <b>Chaamseweg</b> lies one of the largest private estates of West Brabant: <b>Valkenberg</b>, <b>220 hectares</b>, in a curious salient of the municipality of <b>Gilze en Rijen</b> drawn along the streams in the 1826 reorganisation — closer to Ulvenhout and Bavel than to Gilze, and all the larger for it. Together with <b>Hondsdonk</b> (card 2311) and <b>Luchtenburg</b> the estate forms one nearly unbroken <b>estate zone of ±561 hectares</b>, part of the <b>Chaamse beken-zone</b>, bordering the <b>Strijbeekse Heide</b> — the green chain linking southern Breda. The earliest record of an owner dates from <b>1420</b>: a certain “joffrouw” Lijsbeth van Valkenberge, otherwise unknown — the name may equally refer to the rolling ground and the <b>falconry</b>. Valkenberg received its present face under <b>Benjamin van der Borch</b>, who turned it into a <b>demonstration estate</b> in the late eighteenth century: rebuilding the old house, adding farms, an <b>English garden with large and small ponds (1792)</b>, and the <b>lane system of ±1770</b> that still structures the whole — with the <b>Meeldreef</b> as climax, flanked by giant trees and the donkey paths once used by the staff. The Van der Borch family moreover shaped the whole zone’s history: brother <b>Lucas</b> owned <b>Hondsdonk</b> and bought <b>Luchtenburg</b> too in 1802 — all three estates in one hand — and through an hereditary line with Baron Prisse van Hondsdonk that bond survives today. The wood is richly mixed — <b>oak, beech, ash, birch, larch and Douglas fir</b> — and is crossed by the <b>Valkenbergse Ley</b>, flowing towards the <b>Chaamse Beek</b>; in spring <b>marsh marigold and bittercress</b> colour the wet edges, and here and there an old <b>pond</b> and a disused <b>ice cellar</b> tell how an estate once kept itself cool.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–May</b> (marsh marigolds at the stream edges), Apr–Jun (songbirds in the lanes), Sep–Nov (autumn light on the Meeldreef)<br>\n    <b>Best time of day:</b> Morning — light along the drive.',
 'why': ['The <b>Meeldreef</b> with giant trees and donkey paths.', 'The <b>estate zone</b> with Hondsdonk and Luchtenburg (±561 ha).', 'The <b>Van der Borch dynasty</b> over three estates.', 'The <b>English garden with ponds (1792)</b>.', 'The <b>Valkenbergse Ley</b> towards the Chaamse Beek.'],
 'phen': ['<span class="months">Mar–May</span> 🌼 <b>Marsh marigold and bittercress</b> at the Ley.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the lane system.', '<span class="months">Jun–Aug</span> 🦗 <b>Summer shade</b> under beech and oak.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn light</b> on the Meeldreef.'],
 'wild': ['🌳 220 ha estate', '🛤️ Lanes ±1770', '🌾 Chaamse beken-zone', '🏰 Van der Borch', '💧 English-garden ponds'],
 'trail': ['Walk the <b>Meeldreef</b> with its giant trees and donkey paths.', 'Follow the <b>Valkenbergse Ley</b> downstream to the Chaamse Beek.', 'Combine with <b>Hondsdonk</b> (2311) and the <b>Strijbeekse Heide</b> (2310).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–8 km · ⚠️ Country-house surroundings not open'
}))

mk.insert(C, after_id=2311, chunk='reserves-2235-2334.json')
mk.progress(2312)
mk.check()
