# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C1 = []

C1.append(mk.card(2333, 'Sonderen en Hoekvelden Oude Steeg', {
 'tags': ['Noord-Brabant · Oirschotse klei-coulissen bij de gehuchten Oude Steeg en Spoordonk (gem. Oirschot)', 'kleinschalig cultuurlandschap met poelen en houtwallen · het Oirschotse beekdalland van de Schoordingen en de Oude Steeg — grote ondiepe poelen als voortplantingswater, braamstruiken en zomen als leefgebied; onderdeel van het groene mozaïek rond De Mortelen (kaart 303)', 'list 88 · no. 4'],
 'loc': '📍 Gehucht Oude Steeg en de Schoordingen, ten zuidwesten van Oirschot (richting Spoordonk/Baest) — landweggetjes en knooppunten 91 e.o.; combineer met De Mortelen en Heerenbeek (kaart 303) en landgoed Baest',
 'desc': 'Wie door het <b>Oirschotse land</b> fietst, ziet het meteen: kleine <b>akkers</b> met een haag als afscheiding, <b>bos voor het brandhout</b>, gehuchten met een <b>wonderschone kapel</b> en koeien loom in de schaduw — het <b>coulissenlandschap</b> op de Oirschotse klei, waarin de natuur in harmonie met de cultuur leeft. De gehuchten <b>Oude Steeg</b> en de <b>Schoordingen</b>, met de Hoekvelden eromheen, vormen het hart daarvan: hier zijn — met name rond de Oude Steeg — zowel het <b>landbiotoop</b> (houtwallen met braamstruiken, zomen en mantels) als het <b>voortplantingsbiotoop</b> (grote, ondiepe <b>poelen</b>) weer rijkelijk aanwezig — een duo dat in het Oirschotse plan de amfibieën en kleine zoogdieren van het gebied moet dragen. Van daaruit lopen de lijnen door het groene mozaïek: langs het <b>Velders Bosch</b> naar de <b>Schutskuil</b>, en verder naar de <b>Mortelen</b> (kaart 303) en het <b>landgoed Baest</b> — het ene kleinschalige gebied na het andere, samen de groene long van Oirschot. Dit is natuur van de zachte hand: geen reservaat met hekken, maar een landschap dat boeren, bewoners en beheerders samen in stand houden — en dat juist daardoor zeldzaam is geworden in Brabant.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–jun</b> (amfibieën in de poelen), mei–jul (bramenbloei en zangvogels), sep–okt (paddenstoelen in de houtwallen)<br>\n    <b>Beste tijd van de dag:</b> Avond — koor in de poelen.',
 'why': ['De <b>poelen</b> als voortplantingswater voor amfibieën.', 'De <b>houtwallen en braamzomen</b> als leefgebied.', 'Het <b>coulissenlandschap</b> op de Oirschotse klei.', 'De <b>kapel</b> bij het gehucht als stiltepunt.', 'De <b>verbinding</b> met Mortelen en Baest.'],
 'phen': ['<span class="months">Mrt–jun</span> 🐸 <b>Amfibieënkoor</b> in de ondiepe poelen.', '<span class="months">Mei–jul</span> 🎶 <b>Zangvogels</b> in de braamzomen.', '<span class="months">Jun–sep</span> 🦋 <b>Vlinders</b> langs de hagen.', '<span class="months">Sep–okt</span> 🍄 <b>Paddenstoelen</b> in de oude wallen.'],
 'wild': ['🐸 Poelen', '🌳 Houtwallen', '🌾 Klei-coulissen', '⛪ Kapel bij het gehucht', '🔗 Mozaïek met Baest'],
 'trail': ['Wandel de <b>landweggetjes</b> tussen Oude Steeg, Schoordingen en Spoordonk.', 'Zoek de <b>poelen</b> en braamzomen van het amfibieën-beheer.', 'Combineer met <b>De Mortelen</b> (303) en <b>Baest</b>.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 4–10 km · ⚠️ Privé-erf — wegen en paden volgen'
}, {
 'tags': ['North Brabant · Oirschot clay hedgerow landscape near the Oude Steeg and Spoordonk hamlets (gem. Oirschot)', 'small-scale cultural landscape with pools and hedges · the Oirschot stream-land of the Schoordingen and the Oude Steeg — large shallow pools as breeding water, bramble bushes and herb fringes as habitat; part of the green mosaic around De Mortelen (card 303)', 'list 88 · no. 4'],
 'loc': '📍 Oude Steeg hamlet and the Schoordingen, south-west of Oirschot (towards Spoordonk/Baest) — country lanes and junctions around 91; combine with De Mortelen and Heerenbeek (card 303) and the Baest estate',
 'desc': 'Cycle through the <b>Oirschot countryside</b> and you see it at once: small <b>fields</b> with a hedge as fence, <b>wood for the firewood</b>, hamlets with a <b>wondrous chapel</b> and cattle lounging in the shade — the <b>hedgerow landscape</b> on the clay, where nature lives in harmony with cultivation. The hamlets of <b>Oude Steeg</b> and the <b>Schoordingen</b>, with the Hoekvelden around them, form its heart: here — especially around the Oude Steeg — both the <b>land habitat</b> (hedges with brambles, fringes and mantles) and the <b>breeding habitat</b> (large, shallow <b>pools</b>) are richly present — a duo meant in the Oirschot plan to carry the area’s amphibians and small mammals. From there the lines run on through the green mosaic: past the <b>Velders Bosch</b> to the <b>Schutskuil</b>, and onwards to the <b>Mortelen</b> (card 303) and the <b>Baest estate</b> — one small-scale area after another, together Oirschot’s green lung. This is nature of the gentle hand: no fenced reserve but a landscape farmers, residents and managers keep up together — and precisely thereby rare in Brabant.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jun</b> (amphibians in the pools), May–Jul (blooming hedges and songbirds), Sep–Oct (fungi in the hedges)<br>\n    <b>Best time of day:</b> Evening — chorus in the pools.',
 'why': ['The <b>pools</b> as breeding water for amphibians.', 'The <b>hedges and bramble fringes</b> as habitat.', 'The <b>hedgerow landscape</b> on the Oirschot clay.', 'The <b>chapel</b> at the hamlet as quiet point.', 'The <b>connection</b> with Mortelen and Baest.'],
 'phen': ['<span class="months">Mar–Jun</span> 🐸 <b>Amphibian chorus</b> in the shallow pools.', '<span class="months">May–Jul</span> 🎶 <b>Songbirds</b> in the bramble fringes.', '<span class="months">Jun–Sep</span> 🦋 <b>Butterflies</b> along the hedges.', '<span class="months">Sep–Oct</span> 🍄 <b>Fungi</b> in the old hedgerows.'],
 'wild': ['🐸 Pools', '🌳 Hedgerows', '🌾 Clay hedgerow landscape', '⛪ Chapel at the hamlet', '🔗 Mosaic with Baest'],
 'trail': ['Walk the <b>country lanes</b> between Oude Steeg, Schoordingen and Spoordonk.', 'Seek the <b>pools</b> and bramble fringes of the amphibian management.', 'Combine with <b>De Mortelen</b> (303) and <b>Baest</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 4–10 km · ⚠️ Private grounds — follow lanes and paths'
}))

C1.append(mk.card(2334, 'Nieuwe Heide', {
 'tags': ['Noord-Brabant · ten oosten van Best op de Midden-Brabantse dekzandrug (gem. Best)', '277 ha gemeentebos aangeplant in 1921–1930 · voormalig heide- en stuifzandgebied, nu grove den met het 15-ha Langven (klokjesgentiaan) en schapenbegrazing — met het Joe Mann Natuurtheater en Museum Bevrijdende Vleugens; 50-jarige transformatie richting soortenrijk loofbos', 'list 88 · no. 5'],
 'loc': '📍 Nieuwe Heide, ten oosten van Best tussen A2 en de Sonseweg (parkeerplaatsen aan de Sonseweg en bij het Joe Mann-theater) — padennet met trimbaan en mountainbikeroute; combineer met de Sonse Heide (kaart 2335) voor één groot bosgebied',
 'desc': 'Ten oosten van <b>Best</b>, op de <b>Midden-Brabantse dekzandrug</b>, ligt het bos dat “nieuw” was toen het aangelegd werd: de <b>Nieuwe Heide</b>, <b>277 hectare</b> gemeentebos, beplant in <b>1921–1930</b> met grove den op wat eerst een <b>heide- en stuifzandgebied</b> was — productiebos voor het mijnhout, zoals overal in Brabant. De tijd heeft het gebied twee keer herschreven. Eerst groeide er <b>recreatie</b> omheen: het <b>Joe Mann Natuurtheater</b> met zijn monumentale toegangspoort, het museum <b>Bevrijdende Vleugels</b>, een trimparcours en een mountainbikeroute uit 2000 — het alledaagse bos van Best. Daarna begon de grote omslag: gemeente Best en <b>Staatsbosbeheer</b> zetten samen met buurgemeente Son en Breugel een <b>50-jarige transformatie</b> in gang (besluit 2023) die het uniforme naaldbos — dat zichzelf met zijn dikke naaldlaag letterlijk <b>aan het vergiftigen</b> was — omvormt tot <b>soortenrijk loofbos</b> met inheemse dennen en eiken, nattere bosdelen en rustgebieden. In het uiterste zuidwesten ligt de natuurkern al klaar: het <b>Langven</b>, een <b>15 hectare groot vennencomplex</b> waar de <b>klokjesgentiaan</b> bloeit en <b>schapen</b> de heideresten kort houden. Wie hier over vijf jaar loopt, ziet de eerste veranderingen; over vijftig jaar een nieuw bos. Het Wilhelminakanaal snijdt het gebied doormidden — en verbindt het in één lijn met de <b>Sonse Heide</b> (kaart 2335) ten oosten.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–aug</b> (klokjesgentiaan en venbloei), apr–jun (zangvogels), sep–nov (herfst tussen de dennen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door de dennen aan de Sonseweg.',
 'why': ['De <b>50-jarige bostransformatie</b> als nationaal voorbeeld.', 'Het <b>Langven</b> met klokjesgentiaan en schapen.', 'Het <b>Joe Mann Natuurtheater</b> als cultuurplek.', 'De <b>dekzandrug</b> als ondergrond van heide en stuifzand.', 'De <b>eénheid met de Sonse Heide</b> over het kanaal.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Zangvogels</b> in het productiebos.', '<span class="months">Jul–aug</span> 💜 <b>Klokjesgentiaan</b> bij het Langven.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven de vennen.', '<span class="months">Sep–nov</span> 🍂 <b>Herfst</b> langs het Wilhelminakanaal.'],
 'wild': ['🌲 277 ha gemeentebos', '💜 Langven', '🎭 Joe Mann-theater', '🐑 Schapenbegrazing', '🔄 Transformatie 2070'],
 'trail': ['Wandel de <b>vennenroute</b> naar het <b>Langven</b> in het zuidwesten.', 'Bezoek het <b>Joe Mann Natuurtheater</b> en de monumentale poort.', 'Steek over naar de <b>Sonse Heide</b> (2335) voor de dubbelwandeling.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–12 km · 🅿️ Sonseweg / Joe Mann'
}, {
 'tags': ['North Brabant · east of Best on the Mid-Brabant cover-sand ridge (gem. Best)', '277-ha municipal wood planted 1921–1930 · former heath and drift-sand, now Scots pine with the 15-ha Langven pool (bell gentian) and sheep grazing — with the Joe Mann open-air theatre and Bevrijdende Vleugels museum; a 50-year transformation towards species-rich broadleaf wood', 'list 88 · no. 5'],
 'loc': '📍 Nieuwe Heide, east of Best between the A2 and the Sonseweg (car parks on the Sonseweg and at the Joe Mann theatre) — path network with fitness trail and mountain-bike route; combine with the Sonse Heide (card 2335) into one great wood',
 'desc': 'East of <b>Best</b>, on the <b>Mid-Brabant cover-sand ridge</b>, lies the wood that was “new” when planted: the <b>Nieuwe Heide</b>, <b>277 hectares</b> of municipal woodland, planted with Scots pine in <b>1921–1930</b> on what had been a <b>heath and drift-sand area</b> — production wood for the mines, as everywhere in Brabant. Time has rewritten the area twice. First <b>recreation</b> grew around it: the <b>Joe Mann open-air theatre</b> with its monumental gate, the <b>Bevrijdende Vleugels</b> museum, a fitness trail and a mountain-bike route of 2000 — Best’s everyday wood. Then the great turn began: the municipality and <b>Staatsbosbeheer</b>, with neighbouring Son en Breugel, launched a <b>50-year transformation</b> (decided 2023) converting the uniform conifer wood — literally <b>poisoning itself</b> with its thick needle layer — into <b>species-rich broadleaf woodland</b> with native pines and oaks, wetter compartments and quiet zones. In the far south-west the nature core is already there: the <b>Langven</b>, a <b>15-hectare pool complex</b> where the <b>bell gentian</b> flowers and <b>sheep</b> keep the heath remnants short. Walk here in five years and you see the first changes; in fifty, a new wood. The Wilhelminakanaal cuts the area in two — and links it in one line with the <b>Sonse Heide</b> (card 2335) to the east.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Aug</b> (bell gentian and pool flowering), Apr–Jun (songbirds), Sep–Nov (autumn among the pines)<br>\n    <b>Best time of day:</b> Morning — light through the pines on the Sonseweg.',
 'why': ['The <b>50-year wood transformation</b> as a national example.', 'The <b>Langven</b> with bell gentian and sheep.', 'The <b>Joe Mann open-air theatre</b> as cultural spot.', 'The <b>cover-sand ridge</b> as base of heath and drift sand.', 'The <b>unity with the Sonse Heide</b> across the canal.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Songbirds</b> in the production wood.', '<span class="months">Jul–Aug</span> 💜 <b>Bell gentian</b> at the Langven.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> above the pools.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn</b> along the Wilhelminakanaal.'],
 'wild': ['🌲 277 ha municipal wood', '💜 Langven', '🎭 Joe Mann theatre', '🐑 Sheep grazing', '🔄 Transformation 2070'],
 'trail': ['Walk the <b>pool route</b> to the <b>Langven</b> in the south-west.', 'Visit the <b>Joe Mann theatre</b> and its monumental gate.', 'Cross to the <b>Sonse Heide</b> (2335) for the double walk.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–12 km · 🅿️ Sonseweg / Joe Mann'
}))

mk.insert(C1, chunk='reserves-2235-2334.json')

C2 = []

C2.append(mk.card(2335, 'Sonsche Heide', {
 'tags': ['Noord-Brabant · ten westen van Son en Breugel (gem. Son en Breugel)', '± 300 ha gemeentelijk bos- en heidegebied in erfpacht bij Staatsbosbeheer · vormt met de Nieuwe Heide (kaart 2334) één aaneengesloten bosmassief — met het 34-ha natuurreservaat rond het Oud Meer: heide, grote stuifduinen, moeras en een groot ven; onderdeel van Van Gogh Nationaal Park', 'list 88 · no. 6'],
 'loc': '📍 Sonse Heide, ten westen van Son (bereikbaar via de Bestseweg / Sonseweg) — paden door bos en heide; combineer met de Nieuwe Heide (kaart 2334) en het Oud Meer-reservaat',
 'desc': 'Ten westen van <b>Son</b> ligt het bos dat samen met de <b>Nieuwe Heide</b> (kaart 2334) van Best één grote, aaneengesloten bosmassief vormt: de <b>Sonse Heide</b>, ± <b>300 hectare</b> gemeentelijk bezit, in <b>erfpacht bij Staatsbosbeheer</b> — net als bij de buren een oud productiebos van grove den met lariks en spar, en net als bij de buren in volle ommezwaai. Midden in het bos ligt de oude kern: een <b>34 hectare groot natuurreservaat</b> van heide, <b>grote stuifduinen</b>, moeras en het <b>Oud Meer</b> — een groot ven met daaromheen loofbossen van eik en berk en een ondergroei van struikgewas. Hier, in het rustigste deel, is de tijd van de heide bewaard gebleven; de A50 die in 2003 door het oosten werd gegraven, nam elders juist natuur weg. Sinds <b>2021</b> werken Best en Son en Breugel samen aan één <b>toekomstvisie</b> voor het hele massief — klimaatbestendigheid en biodiversiteit centraal, dezelfde 50-jarige transformatie richting gezond mengbos — en maakt het gebied deel uit van <b>Van Gogh Nationaal Park</b>, het groene hart van Het Groene Woud dat van Nuenen tot Eindhoven reikt. Wie de stilte zoekt, wandelt van het Joe Mann-theater over de kanaaldijk het bos in, en laat de buitenwereld binnen tien minuten achter zich.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Aug–sep</b> (heide bij het Oud Meer), apr–jun (zangvogels), okt–nov (herfst in het massief)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — nevel boven het Oud Meer.',
 'why': ['Het <b>34-ha reservaat</b> met heide, stuifduinen en Oud Meer.', 'De <b>éénheid met de Nieuwe Heide</b> als massief.', 'De <b>gezamenlijke toekomstvisie</b> met Best (2021).', 'De ligging in <b>Van Gogh Nationaal Park</b>.', 'De <b>grote stuifduinen</b> als reliëf in het bos.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Zangvogels</b> in het loofbos rond het Oud Meer.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven ven en moeras.', '<span class="months">Aug–sep</span> 💜 <b>Heide in bloei</b> in het reservaat.', '<span class="months">Okt–nov</span> 🍂 <b>Herfst</b> over het hele massief.'],
 'wild': ['🌲 300 ha massief', '💧 Oud Meer', '🏜️ Stuifduinen', '🎨 Van Gogh NP', '🤝 Eén visie met Best'],
 'trail': ['Wandel naar het <b>Oud Meer</b> en de stuifduinen van het reservaat.', 'Loop de <b>grens</b> met de Nieuwe Heide (2334) over de kanaaldijk.', 'Combineer met de <b>Van Gogh-routes</b> van het Nationaal Park.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 4–14 km · 🅿️ Bestseweg / Sonseweg'
}, {
 'tags': ['North Brabant · west of Son en Breugel (gem. Son en Breugel)', '± 300-ha municipal woodland and heath held on long lease by Staatsbosbeheer · forms one unbroken forest massif with the Nieuwe Heide (card 2334) — with the 34-ha reserve around the Oud Meer: heath, great drift dunes, marsh and a large pool; part of Van Gogh National Park', 'list 88 · no. 6'],
 'loc': '📍 Sonse Heide, west of Son (reached via the Bestseweg / Sonseweg) — paths through wood and heath; combine with the Nieuwe Heide (card 2334) and the Oud Meer reserve',
 'desc': 'West of <b>Son</b> lies the wood forming one great unbroken forest massif with Best’s <b>Nieuwe Heide</b> (card 2334): the <b>Sonse Heide</b>, ± <b>300 hectares</b> of municipal property on <b>long lease to Staatsbosbeheer</b> — like the neighbours an old production wood of Scots pine with larch and spruce, and like the neighbours in full turnaround. At its centre lies the old core: a <b>34-hectare nature reserve</b> of heath, <b>great drift dunes</b>, marsh and the <b>Oud Meer</b> — a large pool ringed by oak-and-birch woodland with a shrubby understorey. Here, in the quietest part, the age of the heath survived; the A50 cut through the east in 2003 took nature away instead. Since <b>2021</b> Best and Son en Breugel have worked on one <b>future vision</b> for the whole massif — climate resilience and biodiversity at the centre, the same 50-year transformation towards healthy mixed woodland — and the area belongs to <b>Van Gogh National Park</b>, the green heart of Het Groene Woud stretching from Nuenen to Eindhoven. For silence, walk from the Joe Mann theatre over the canal dike into the wood, and leave the outside world behind within ten minutes.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Aug–Sep</b> (heath by the Oud Meer), Apr–Jun (songbirds), Oct–Nov (autumn in the massif)<br>\n    <b>Best time of day:</b> Early morning — mist above the Oud Meer.',
 'why': ['The <b>34-ha reserve</b> with heath, drift dunes and Oud Meer.', 'The <b>unity with the Nieuwe Heide</b> as one massif.', 'The <b>joint future vision</b> with Best (2021).', 'The position in <b>Van Gogh National Park</b>.', 'The <b>great drift dunes</b> as relief in the wood.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Songbirds</b> in the Oud Meer oakwood.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> above pool and marsh.', '<span class="months">Aug–Sep</span> 💜 <b>Heath in flower</b> in the reserve.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> across the massif.'],
 'wild': ['🌲 300 ha massif', '💧 Oud Meer', '🏜️ Drift dunes', '🎨 Van Gogh NP', '🤝 One vision with Best'],
 'trail': ['Walk to the <b>Oud Meer</b> and the reserve’s drift dunes.', 'Follow the <b>boundary</b> with the Nieuwe Heide (2334) along the canal dike.', 'Combine with the National Park’s <b>Van Gogh routes</b>.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 4–14 km · 🅿️ Bestseweg / Sonseweg'
}))

C2.append(mk.card(2336, 'Dommelrode en Breugelsbroek', {
 'tags': ['Noord-Brabant · het Dommeldal bij Dommelrode en Breugel, gemeente Meierijstad (gem. Sint-Oedenrode)', 'stadslandschap aan de Dommel · de beek doorsnijdt Sint-Oedenrode — na het project Klimaatrobuust Beekdal (2025) breed uitlopend in groene oevers; beemden, bolle akkers en populieren van de klompenindustrie rond de gehuchten Dommelrode en Breugel', 'list 88 · no. 7'],
 'loc': '📍 Dommelrode en Breugel, ten zuiden van Sint-Oedenrode in het Dommeldal — dijkpaden en knooppunten; combineer met de Dommelbeemden en de uitkijktoren bij de Koos van Schaïkbrug',
 'desc': 'De <b>Dommel</b> — 95 kilometer van de Donderslagsche Heide in België naar de Dieze in Den Bosch — snijdt <b>Sint-Oedenrode</b> doormidden, en net ten zuiden van het dorp ligt het stuk waar stad en beek elkaar het dichtst naderen: de zone van <b>Dommelrode</b> en <b>Breugel</b>, oude nederzettingen op de hogere gronden langs de beek. Hier lag eeuwenlang het klassieke <b>Dommeldal</b>: <b>beemden</b> (wei- en hooilanden) vlak bij het water, <b>bolle akkers</b> op de hogere gronden verder weg, en overal <b>populieren</b> — massaal aangeplant voor de klompenindustrie die deze streek rijk maakte. De twintigste eeuw kanaliseerde en verdiepte, maar met het project <b>Klimaatrobuust Beekdal</b> (opgeleverd september <b>2025</b>) is de Dommel op grote schaal <b>verbreed</b>: bij veel water treedt ze nu veilig buiten haar oevers, en tegelijk werd een <b>ecologische verbindingszone</b> aangelegd — een groen lint dat natuurgebieden met elkaar verbindt. Voor wie loopt, is het dal nu op zijn mooist vanaf de <b>dijkpaden</b> en de <b>uitkijktoren</b> bij de Koos van Schaïkbrug: de <b>sterk meanderende beek</b> beneden, het kleinschalige agrarische land eromheen, en de kerktoren van Rooi (zoals de locals hun dorp noemen) als markant eindpunt. Het is de Dommel zoals Van Gogh haar in Brabant tekende — en tegelijk een klimaatproject van de 21e eeuw.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–jun</b> (weidevogels en voorjaarsbloei in de beemden), jun–sep (libellen), nov–feb (hoog water op de verbrede Dommel)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — nevel over de beemden.',
 'why': ['De <b>verbrede Dommel</b> van Klimaatrobuust Beekdal (2025).', 'De <b>beemden en bolle akkers</b> van het oude dal.', 'De <b>populieren</b> van de klompenindustrie.', 'De <b>ecologische verbindingszone</b> als groen lint.', 'De <b>uitkijktoren</b> op het meanderdal.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Weidevogels</b> in de beemden.', '<span class="months">Apr–jun</span> 🌼 <b>Dotterbloemen</b> langs de oevers.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven de ondiepen.', '<span class="months">Nov–feb</span> 💧 <b>Hoog water</b> in het verbrede dal.'],
 'wild': ['🌀 Meanderende Dommel', '🌾 Beemden', '🌳 Klompen-populieren', '🟢 Verbindingszone', '🗼 Uitkijktoren'],
 'trail': ['Loop de <b>dijkpaden</b> langs de verbrede Dommel bij Dommelrode.', 'Beklim de <b>uitkijktoren</b> bij de Koos van Schaïkbrug.', 'Combineer met de <b>Dommelbeemden</b> richting Boxtel.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 4–12 km · ⚠️ Hoogwater-delen soms blank'
}, {
 'tags': ['North Brabant · the Dommel valley at Dommelrode and Breugel, Meierijstad municipality (gem. Sint-Oedenrode)', 'riverside landscape on the Dommel · the stream bisects Sint-Oedenrode — after the Climate-Resilient Stream Valley project (2025) spreading wide into green banks; meads, bulging fields and the poplars of the clog industry around the Dommelrode and Breugel hamlets', 'list 88 · no. 7'],
 'loc': '📍 Dommelrode and Breugel, south of Sint-Oedenrode in the Dommel valley — dike paths and junctions; combine with the Dommelbeemden and the lookout tower by the Koos van Schaïk bridge',
 'desc': 'The <b>Dommel</b> — 95 kilometres from Belgium’s Donderslagsche Heide to the Dieze in Den Bosch — cuts <b>Sint-Oedenrode</b> in half, and just south of the village lies the stretch where town and stream come closest: the zone of <b>Dommelrode</b> and <b>Breugel</b>, old settlements on the higher ground along the stream. For centuries this was the classic <b>Dommel valley</b>: <b>meads</b> (grazing and hay land) near the water, <b>bulging fields</b> on the higher ground, and everywhere <b>poplars</b> — planted en masse for the clog industry that enriched this region. The twentieth century canalised and deepened, but with the <b>Climate-Resilient Stream Valley</b> project (delivered September <b>2025</b>) the Dommel has been <b>widened</b> at scale: in high water she now safely overflows her banks, and simultaneously an <b>ecological connecting zone</b> was laid out — a green ribbon linking nature areas. For walkers the valley is at its best from the <b>dike paths</b> and the <b>lookout tower</b> by the Koos van Schaïk bridge: the <b>strongly meandering stream</b> below, small-scale farmland around, and Rooi’s church tower (as locals call their village) as landmark finale. It is the Dommel as Van Gogh drew her in Brabant — and a 21st-century climate project at once.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Jun</b> (meadow birds and spring flowering in the meads), Jun–Sep (dragonflies), Nov–Feb (high water on the widened Dommel)<br>\n    <b>Best time of day:</b> Morning — mist over the meads.',
 'why': ['The <b>widened Dommel</b> of the climate-resilient project (2025).', 'The <b>meads and bulging fields</b> of the old valley.', 'The <b>poplars</b> of the clog industry.', 'The <b>ecological connecting zone</b> as green ribbon.', 'The <b>lookout tower</b> over the meander belt.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Meadow birds</b> in the meads.', '<span class="months">Apr–Jun</span> 🌼 <b>Marsh marigolds</b> along the banks.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> above the shallows.', '<span class="months">Nov–Feb</span> 💧 <b>High water</b> in the widened valley.'],
 'wild': ['🌀 Meandering Dommel', '🌾 Meads', '🌳 Clog-industry poplars', '🟢 Connecting zone', '🗼 Lookout tower'],
 'trail': ['Walk the <b>dike paths</b> along the widened Dommel at Dommelrode.', 'Climb the <b>lookout tower</b> by the Koos van Schaïk bridge.', 'Combine with the <b>Dommelbeemden</b> towards Boxtel.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 4–12 km · ⚠️ High-water sections occasionally flood'
}))

C2.append(mk.card(2337, 'Ruweeuwsels', {
 'tags': ['Noord-Brabant · bij Lieshout, ingeklemd tussen het Wilhelminakanaal en de Molenheide (gem. Laarbeek)', '20 ha broekbos van Brabants Landschap · middeleeuwse zuidwestgrens van het domein Lieshout — vochtig, voedselrijk loofbos met bosweitjes; populierenteelt tot ± 1950, nu bosanemonen-tapijten en grote muur; omvorming naar gevarieerd gemengd bos', 'list 88 · no. 8'],
 'loc': '📍 Ruweeuwsels (“Rawweuwsels” in het Lieshouts), ten zuidwesten van Lieshout tussen Wilhelminakanaal en Molenheide — smalle paden door het broekbos; combineer met de Molenheide-route (Hulsel–Reusel)',
 'desc': 'Tussen het <b>Wilhelminakanaal</b> en de <b>Molenheide</b>, ten zuidwesten van <b>Lieshout</b>, ligt een bosje dat de eeuwen heeft geteld: de <b>Ruweeuwsels</b> — in het Lieshouts uitgesproken als “Rawweuwsels” — nauwelijks <b>20 hectare</b>, maar in de <b>Middeleeuwen</b> al de zuidwestelijke begrenzing van het <b>domein Lieshout</b>: een plek die oud genoeg is om op kaarten van vóór de ontginningen te staan. Het reservaat bestaat voornamelijk uit <b>rijk loofhoutbos</b> — broekbos — met enkele <b>bosweitjes</b>: de grond is vochtig en voedselrijk, met een gradiënt van vochtig naar droog die het gebied in één wandeling al zijn gezichten toont. Het beboste verleden is recent genoeg om te lezen: van eind <b>19e eeuw tot ± 1950</b> werd hier <b>populierenteelt</b> bedreven, en na de Tweede Wereldoorlog vielen de meeste oude bomen — alleen enkele <b>oude beuken</b> herinneren nog aan die tijd. Tegenwoordig beheert <b>Brabants Landschap</b> het gebied en zet de populieren om in <b>gevarieerd gemengd bos</b>; vooral in het voorjaar is het resultaat al prachtig, met <b>tapijten van bosanemoon</b> en veel <b>grote muur</b> op de rijke bodem. Kleiner dan de beroemde gebieden eromheen — maar wie de stille Kempen zoekt, vindt hier het hart ervan, op tien minuten van het kanaal.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Mrt–apr</b> (bosanemonen-tapijt), apr–jun (zangvogels), sep–nov (herfst in het broekbos)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht door het vroege loof.',
 'why': ['De <b>middeleeuwse domeingrens</b> van Lieshout als leeftijd.', 'De <b>bosanemonen-tapijten</b> en grote muur.', 'Het <b>broekbos met bosweitjes</b> op rijke grond.', 'De <b>populieren-geschiedenis</b> tot ± 1950.', 'De <b>omvorming</b> naar gevarieerd gemengd bos.'],
 'phen': ['<span class="months">Mrt–apr</span> 🌸 <b>Bosanemonen</b> in tapijten.', '<span class="months">Apr–jun</span> 🎶 <b>Zangvogels</b> in het jonge loof.', '<span class="months">Jun–aug</span> 🦗 <b>Zomerschaduw</b> in de bosweitjes.', '<span class="months">Sep–nov</span> 🍂 <b>Herfst</b> tussen beuk en els.'],
 'wild': ['🌸 Bosanemonen', '🌳 Broekbos', '📜 Domein Lieshout', '🌾 Bosweitjes', '🔄 Omvorming bos'],
 'trail': ['Loop de <b>smalle paden</b> door het broekbos.', 'Zoek de <b>oude beuken</b> uit de populieren-tijd.', 'Combineer met de <b>Molenheide</b> ten zuiden.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 2–5 km · ⚠️ Vochtige paden — laarzen aanraden'
}, {
 'tags': ['North Brabant · near Lieshout, wedged between the Wilhelminakanaal and the Molenheide (gem. Laarbeek)', '20-ha alder carr of Brabants Landschap · medieval south-west boundary of the Lieshout domain — humid, nutrient-rich broadleaf wood with wood meadows; poplar growing until ± 1950, now carpets of wood anemones and wall lettuce; conversion to varied mixed woodland', 'list 88 · no. 8'],
 'loc': '📍 Ruweeuwsels (“Rawweuwsels” in Lieshout dialect), south-west of Lieshout between the Wilhelminakanaal and the Molenheide — narrow paths through the carr woodland; combine with the Molenheide route (Hulsel–Reusel)',
 'desc': 'Between the <b>Wilhelminakanaal</b> and the <b>Molenheide</b>, south-west of <b>Lieshout</b>, lies a wood that has counted the centuries: the <b>Ruweeuwsels</b> — “Rawweuwsels” in the Lieshout tongue — barely <b>20 hectares</b>, yet already in the <b>Middle Ages</b> the south-western boundary of the <b>Lieshout domain</b>: a place old enough to stand on maps from before the reclamations. The reserve consists mainly of <b>rich broadleaf woodland</b> — carr — with a few <b>wood meadows</b>: the ground is humid and nutrient-rich, with a gradient from wet to dry showing all its faces in a single walk. The wooded past is recent enough to read: from the late <b>19th century to ± 1950</b> <b>poplar growing</b> was practised here, and after the Second World War most old trees fell — only a few <b>old beeches</b> recall that era. Today <b>Brabants Landschap</b> manages the area and converts the poplars to <b>varied mixed woodland</b>; in spring especially, the result is already lovely, with <b>carpets of wood anemones</b> and much <b>wall lettuce</b> on the rich soil. Smaller than the famous areas around it — but for the silent Campine, this is its heart, ten minutes from the canal.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Mar–Apr</b> (wood-anemone carpet), Apr–Jun (songbirds), Sep–Nov (autumn in the carr)<br>\n    <b>Best time of day:</b> Morning — light through the early leaves.',
 'why': ['The <b>medieval domain boundary</b> of Lieshout as age.', 'The <b>wood-anemone carpets</b> and wall lettuce.', 'The <b>carr with wood meadows</b> on rich soil.', 'The <b>poplar history</b> up to ± 1950.', 'The <b>conversion</b> to varied mixed woodland.'],
 'phen': ['<span class="months">Mar–Apr</span> 🌸 <b>Wood anemones</b> in carpets.', '<span class="months">Apr–Jun</span> 🎶 <b>Songbirds</b> in the young foliage.', '<span class="months">Jun–Aug</span> 🦗 <b>Summer shade</b> in the wood meadows.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn</b> among beech and alder.'],
 'wild': ['🌸 Wood anemones', '🌳 Carr woodland', '📜 Lieshout domain', '🌾 Wood meadows', '🔄 Woodland conversion'],
 'trail': ['Walk the <b>narrow paths</b> through the carr wood.', 'Seek the <b>old beeches</b> from the poplar era.', 'Combine with the <b>Molenheide</b> to the south.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 2–5 km · ⚠️ Humid paths — boots advised'
}))

mk.insert(C2, chunk='reserves-2335-2434.json')
mk.progress(2337)
mk.check()
