# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2348, 'Neterselse Heide, De Beemden en Beersbroek', {
 'tags': ['Noord-Brabant · Neterselse Heide ten zuidwesten van Westelbeers, Beemden en Beersbroek in het dal van de Groote Beerze (gem. Bladel/Oirschot)', 'heide- en beekdalgebied van Brabants Landschap · in 2004 voor €1 gekocht van de gemeente Bladel; moeraswolfsklauw, beenbreek, klokjesgentiaan, witte snavelbies en zonnedauw op de natte hei; blauwe kiekendief, boomleeuwerik en roodborsttapuit; onderdeel van Natura 2000 Kempenland-West', 'list 88 · no. 20'],
 'loc': '📍 Neterselse Heide (Netersel, gem. Bladel) — parkeerplaats aan de Spreeuwelsedijk; verder de Beemden en het Beersbroek langs de Groote Beerze richting Westelbeers; combineer met de Landschotse Heide (kaart 2346) en het Dal van de Groote Beerze (kaart 2349)',
 'desc': 'Rond het kleine dorp <b>Netersel</b> ligt een van de stilste heidegebieden van Westelijk Brabant: de <b>Neterselse Heide</b>, in <b>2004 voor het symbolische bedrag van één euro</b> overgenomen door <b>Brabants Landschap</b> van de gemeente Bladel — die zo zeker wist dat de hei in goede handen kwam. Ten westen sluit de <b>Mispeleindse Heide</b> aan, ten oosten ligt de <b>Grijze Steen</b> in het dal van de <b>Groote Beerze</b> (kaart 2349), en zo vormt het geheel één groot open landschap van natte en droge heide met <b>vennen en graslandjes</b>. De natte delen zijn floristisch rijk: <b>moeraswolfsklauw</b> en <b>zonnedauw</b> op de venbodemmen, <b>beenbreek</b> en <b>klokjesgentiaan</b> in de sponzen, <b>witte snavelbies</b> op de kale natte zandplekken — planten die aan verlanding en kwel zijn aangepast en hier nog massaal voorkomen. Boven de hei cirkelt de <b>blauwe kiekendief</b>, zingt de <b>boomleeuwerik</b> zijn vluchtlied en laat de <b>roodborsttapuit</b> zich van de top van een jeneverbes vallen. In de beemden langs de Beerze liggen de <b>hooilanden</b> die het oude beekdal vasthouden, met de <b>15e-eeuwse kavels</b> van de buurtschappen <b>Dun, Hertgang en Coevoirt</b> — middeleeuwse ontginningen die nog steeds in het kaartbeeld te lezen zijn. Op de hei staat het <b>vijf-gemeenten-monument</b> (1996), opgericht waar vijf Brabantse gemeenten elkaar raakten. Wie hier in de vroege ochtend loopt, hoort niets dan wind, vogels en — als het stil genoeg is — de Beerze zelf.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jun–sep</b> (hei in bloei, kiekendieven), mrt–mei (tapuiten en boomleeuwerik), okt–mrt (winterse stilte)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — nevel over de natte hei.',
 'why': ['De <b>€1-aankoop</b> van 2004 als natuurbeschermingsverhaal.', 'De <b>natte-heiflora</b>: moeraswolfsklauw, zonnedauw, beenbreek.', 'De <b>blauwe kiekendief</b> boven de hei.', 'De <b>15e-eeuwse kavels</b> van Dun, Hertgang en Coevoirt.', 'Het <b>vijf-gemeenten-monument</b> (1996).'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Boomleeuwerik en roodborsttapuit</b> in zang.', '<span class="months">Mei–aug</span> 🦅 <b>Blauwe kiekendief</b> boven de hei.', '<span class="months">Jul–sep</span> 💜 <b>Struikhei</b> en <b>klokjesgentiaan</b>.', '<span class="months">Sep–okt</span> 🍂 <b>Ochtendnevel</b> over de vennen.'],
 'wild': ['💧 Natte heide', '🌿 Vleesetende zonnedauw', '🦅 Blauwe kiekendief', '📜 Middeleeuwse kavels', '🤝 Vijf gemeenten'],
 'trail': ['Loop vanaf Netersel de <b>hei</b> over naar de Mispeleindse kant.', 'Zoek de <b>hooilanden</b> in de beemden langs de Groote Beerze.', 'Vind het <b>vijf-gemeenten-monument</b> op de hei.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 4–12 km · 🅿️ Spreeuwelsedijk (Netersel)'
}, {
 'tags': ['North Brabant · Neterselse Heide south-west of Westelbeers, Beemden and Beersbroek in the Groote Beerze valley (gem. Bladel/Oirschot)', 'heath and stream-valley area of Brabants Landschap · bought for €1 from the municipality of Bladel in 2004; clubmoss, bog asphodel, gentian, white beak-sedge and sundew on the wet heath; hen harrier, wood lark and stonechat; part of Natura 2000 Kempenland-West', 'list 88 · no. 20'],
 'loc': '📍 Neterselse Heide (Netersel, gem. Bladel) — car park on the Spreeuwelsedijk; then the Beemden and Beersbroek along the Groote Beerze towards Westelbeers; combine with the Landschotse Heide (card 2346) and the Dal van de Groote Beerze (card 2349)',
 'desc': 'Around the small village of <b>Netersel</b> lies one of the quietest heaths of western Brabant: the <b>Neterselse Heide</b>, taken over in <b>2004 for the symbolic sum of one euro</b> by <b>Brabants Landschap</b> from the municipality of Bladel — which thus knew for certain the heath was in good hands. To the west the <b>Mispeleindse Heide</b> joins, to the east lies the <b>Grijze Steen</b> in the valley of the <b>Groote Beerze</b> (card 2349), together forming one great open landscape of wet and dry heath with <b>pools and small grasslands</b>. The wet parts are a flora perfume: <b>clubmoss</b> and <b>sundew</b> on the pool beds, <b>bog asphodel</b> and <b>marsh gentian</b> in the seepage zones, <b>white beak-sedge</b> on the bare wet sand — plants adapted to waterlogging and seepage, still abundant here. Above the heath the <b>hen harrier</b> circles, the <b>wood lark</b> sings its flight song and the <b>stonechat</b> drops from the top of a juniper. In the beemden along the Beerze lie the <b>hay meadows</b> holding the old valley, with the <b>15th-century fields</b> of the hamlets of <b>Dun, Hertgang and Coevoirt</b> — medieval reclamation still readable on the map. On the heath stands the <b>five-municipalities monument</b> (1996), raised where five Brabant municipalities once met. Walk here in the early morning and you hear nothing but wind, birds and — if it is quiet enough — the Beerze itself.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jun–Sep</b> (heath in flower, harriers), Mar–May (chats and wood lark), Oct–Mar (wintry silence)<br>\n    <b>Best time of day:</b> Early morning — mist over the wet heath.',
 'why': ['The <b>€1 purchase</b> of 2004 as a conservation story.', 'The <b>wet-heath flora</b>: clubmoss, sundew, bog asphodel.', 'The <b>hen harrier</b> above the heath.', 'The <b>15th-century fields</b> of Dun, Hertgang and Coevoirt.', 'The <b>five-municipalities monument</b> (1996).'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Wood lark and stonechat</b> in song.', '<span class="months">May–Aug</span> 🦅 <b>Hen harrier</b> over the heath.', '<span class="months">Jul–Sep</span> 💜 <b>Heather</b> and <b>marsh gentian</b>.', '<span class="months">Sep–Oct</span> 🍂 <b>Morning mist</b> over the pools.'],
 'wild': ['💧 Wet heath', '🌿 Carnivorous sundew', '🦅 Hen harrier', '📜 Medieval fields', '🤝 Five municipalities'],
 'trail': ['Walk from Netersel across the <b>heath</b> towards the Mispeleindse side.', 'Seek the <b>hay meadows</b> in the beemden along the Groote Beerze.', 'Find the <b>five-municipalities monument</b> on the heath.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 4–12 km · 🅿️ Spreeuwelsedijk (Netersel)'},
 n2k='🇪🇺 Onderdeel van Natura 2000 Kempenland-West (Habitatrichtlijngebied, ± 1.882 ha) — de Neterselse Heide vormt samen met de Mispeleindse en Landschotse Heide, de Roovertsche Heide, landgoed De Utrecht en de Groote Beerze de kern van dit Kampengebied; de natte heide en vennen zijn de dragende habitattypen.',
 n2k_en='🇪🇺 Part of Natura 2000 Kempenland-West (Habitats Directive site, ± 1,882 ha) — the Neterselse Heide forms the core of this Campine site together with the Mispeleindse and Landschotse Heide, the Roovertsche Heide, the De Utrecht estate and the Groote Beerze; its wet heath and pools are the carrying habitat types.'
))

C.append(mk.card(2349, 'Dal van de Groote Beerze', {
 'tags': ['Noord-Brabant · beekdal van de Groote Beerze tussen Bladel, Hapert en Westelbeers (gem. Bladel/Oirschot)', 'beheerseenheid van Brabants Landschap (298 ha) · Beersbroek en Steenselaarbeemden ten westen van de beek, de Grijze Steen ten oosten; dotterbloem, poelruit, brede orchis en blauwe knoop in de beemden; klein warkruid en moeraswolfsklauw bij de Grijze Steen; de beek zelf ligt binnen Natura 2000 Kempenland-West', 'list 88 · no. 21'],
 'loc': '📍 Dal van de Groote Beerze — wandelparking bij De Grijze Steen (Kapeldijk) of via Netersel; het beekdal loopt van Casteren tot Westelbeers; combineer met de Neterselse Heide (kaart 2348) en de Landschotse Heide (kaart 2346)',
 'desc': 'Tussen <b>Bladel</b>, <b>Hapert</b> en <b>Westelbeers</b> kronkelt de <b>Groote Beerze</b> door een beekdal dat Brabants Landschap als één beheerseenheid van <b>298 hectare</b> in stand houdt: het <b>Dal van de Groote Beerze</b>, bestaande uit het <b>Beersbroek</b> en de <b>Steenselaarbeemden</b> ten westen van de beek en het gebied <b>De Grijze Steen</b> ten oosten. De westelijke helft is een <b>kleinschalig cultuurlandschap</b>: hooilanden met <b>dotterbloem, poelruit, moerasviooltje, klein glidkruid, kleine valeriaan, brede orchis, blauwe knoop en Spaanse ruiter</b> — een schraalland-flora die hier bloeit omdat de beemden nooit werden “verbeterd”. De oostelijke helft, de Grijze Steen, bewaart een <b>heideveldje</b> met <b>klein warkruid, moeraswolfsklauw, zonnedauw en klokjesgentiaan</b>. De beek zelf onderging in <b>2021–2022</b> een grootschalige <b>herinrichting</b> door Brabants Landschap en waterschap De Dommel: een <b>nieuwe, meanderende loop</b> werd gegraven, de oude rechte gang gedempt, watergangen verlanden en er kwamen zelfs een <b>voorde</b> en nieuwe bruggen — alles om de <b>blauwgraslanden en beekbegeleidende bossen</b> van het Natura 2000-gebied te redden van verdroging. Wie nu loopt, ziet het herstel in volle gang: verse meanders, afgegraven terreinen die weer kwel worden, en de eerste moerasplanten die zich vestigen. Het is het jongste hoofdstuk van een dal dat al eeuwen de ader van de streek vormt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (dotterbloem en orchissen in de beemden), jun–sep (libellen boven de nieuwe meanders), okt–mrt (hoog water in het dal)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — nevel boven de beek.',
 'why': ['De <b>beheerseenheid</b> van 298 ha rond één beek.', 'De <b>schraalland-flora</b> van het Beersbroek.', 'De <b>herinrichting 2021–2022</b> met nieuwe meanders.', 'De <b>voorde</b> als zeldzaam pad-element.', 'De <b>blauwgraslanden</b> als Natura 2000-doel.'],
 'phen': ['<span class="months">Apr–mei</span> 🌼 <b>Dotterbloemen</b> in de beemden.', '<span class="months">Mei–jun</span> 🌸 <b>Brede orchis en blauwe knoop</b>.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven de nieuwe meanders.', '<span class="months">Okt–mrt</span> 💧 <b>Hoog water</b> in het brede dal.'],
 'wild': ['🌀 Meanderende beek', '🌼 Dotterbloembeemden', '🪨 De Grijze Steen', '💧 Blauwgraslanden', '🐴 Voorde'],
 'trail': ['Wandel door de <b>Beemden</b> langs de oude hooilanden.', 'Zoek de <b>nieuwe meanders en de voorde</b> bij de Grijze Steen.', 'Volg het dal van <b>Casteren tot Westelbeers</b> voor de lange variant.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–12 km · 🅿️ Kapeldijk / Netersel'
}, {
 'tags': ['North Brabant · Groote Beerze valley between Bladel, Hapert and Westelbeers (gem. Bladel/Oirschot)', 'management unit of Brabants Landschap (298 ha) · Beersbroek and Steenselaarbeemden west of the stream, the Grijze Steen east of it; marsh marigold, lesser meadow-rue, broad-leaved orchid and devil’s-bit in the water meadows; lesser marshwort and clubmoss at the Grijze Steen; the stream itself lies within Natura 2000 Kempenland-West', 'list 88 · no. 21'],
 'loc': '📍 Dal van de Groote Beerze — walking car park at De Grijze Steen (Kapeldijk) or via Netersel; the valley runs from Casteren to Westelbeers; combine with the Neterselse Heide (card 2348) and the Landschotse Heide (card 2346)',
 'desc': 'Between <b>Bladel</b>, <b>Hapert</b> and <b>Westelbeers</b> the <b>Groote Beerze</b> curls through a valley that Brabants Landschap maintains as a single management unit of <b>298 hectares</b>: the <b>Dal van de Groote Beerze</b>, made up of the <b>Beersbroek</b> and the <b>Steenselaarbeemden</b> west of the stream and the area of <b>De Grijze Steen</b> east of it. The western half is a <b>small-scale cultural landscape</b>: hay meadows with <b>marsh marigold, lesser meadow-rue, marsh violet, small valerian, broad-leaved orchid, devil’s-bit scabious and saw-wort</b> — a fen-meadow flora blooming here because the beemden were never “improved”. The eastern half, the Grijze Steen, keeps a <b>patch of heath</b> with <b>lesser water-parsnip, clubmoss, sundew and marsh gentian</b>. The stream itself underwent a large-scale <b>restoration</b> in <b>2021–2022</b> by Brabants Landschap and the De Dommel water board: a <b>new, meandering course</b> was dug, the old straight channel filled in, ditches left to silt up, and even a <b>ford</b> and new bridges appeared — all to save the <b>blue-grasslands and streamside woods</b> of the Natura 2000 site from desiccation. Walk here now and you see the recovery in full swing: fresh meanders, excavated ground turning back into seepage marsh, and the first marsh plants settling in. It is the youngest chapter of a valley that has been the region’s artery for centuries.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (marsh marigold and orchids in the meadows), Jun–Sep (dragonflies above the new meanders), Oct–Mar (high water in the valley)<br>\n    <b>Best time of day:</b> Morning — mist above the stream.',
 'why': ['The <b>298-ha management unit</b> around one stream.', 'The <b>fen-meadow flora</b> of the Beersbroek.', 'The <b>2021–2022 restoration</b> with new meanders.', 'The <b>ford</b> as a rare path element.', 'The <b>blue-grasslands</b> as Natura 2000 target.'],
 'phen': ['<span class="months">Apr–May</span> 🌼 <b>Marsh marigolds</b> in the meadows.', '<span class="months">May–Jun</span> 🌸 <b>Broad-leaved orchid and devil’s-bit</b>.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> above the new meanders.', '<span class="months">Oct–Mar</span> 💧 <b>High water</b> in the broad valley.'],
 'wild': ['🌀 Meandering stream', '🌼 Marigold meadows', '🪨 The Grijze Steen', '💧 Blue-grasslands', '🐴 Ford'],
 'trail': ['Walk through the <b>Beemden</b> along the old hay meadows.', 'Seek the <b>new meanders and the ford</b> at the Grijze Steen.', 'Follow the valley from <b>Casteren to Westelbeers</b> for the long variant.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–12 km · 🅿️ Kapeldijk / Netersel)'},
 n2k='🇪🇺 De Groote Beerze zelf ligt vanaf Hapert en Bladel tot de samenvloeiing met de Kleine Beerze binnen Natura 2000 Kempenland-West (Habitatrichtlijngebied, ± 1.882 ha), vooral vanwege de drijvende waterweegbree; ook de blauwgraslanden en alluviale bossen in het dal zijn Natura 2000-habitat.',
 n2k_en='🇪🇺 From Hapert and Bladel down to its confluence with the Kleine Beerze, the Groote Beerze itself lies within Natura 2000 Kempenland-West (Habitats Directive site, ± 1,882 ha), chiefly for its floating water-plantain; the blue-grasslands and alluvial woods of the valley are Natura 2000 habitat too.'
))

C.append(mk.card(2350, 'Gemeentebossen Hoogeloon', {
 'tags': ['Noord-Brabant · tussen Hoogeloon en Hapert, aan de bovenloop van de Kleine Beerze (gem. Bladel)', 'zeer oud bosgebied van de gemeente Bladel · al in de 16e eeuw in het bezit van de plaatselijke gemeenschap; oudste bomen van de gemeente (dennen van ±1850); de Kabouterberg op de Koebosch is een gereconstrueerde Romeinse grafheuvel; bijbehorende Romeinse villa-akker en de weer meanderende Kleine Beerze', 'list 88 · no. 22'],
 'loc': '📍 Gemeentebossen Hoogeloon — parkeerplaats bij de Koebosch (Kabouterberg) aan de weg Hoogeloon–Hapert; combineer met Heieinden (kaart 2351) en de Landschotse Heide (kaart 2346)',
 'desc': 'De <b>Gemeentebossen</b> van <b>Hoogeloon</b> behoren tot de oudste bossen van Brabant: al in de <b>16e eeuw</b> stonden ze op de kaart als bezit van de plaatselijke gemeenschap — een zeldzaam geval van bos dat nooit een heer, een klooster of een projectontwikkelaar toebehoorde, maar het dorp zelf. Dat verklaart de bijzondere samenstelling: naast productie-percelen zijn hier <b>oude loofbossen</b> met eeuwenoude structuur, en staan er de <b>oudste bomen van de gemeente Bladel</b> — dennen die rond <b>1850</b> werden aangeplant en nu tot de hoogste en dikste van de streek behoren. Het pronkstuk ligt in de <b>Koebosch</b>: de <b>Kabouterberg</b>, in de volksmond zo genoemd, is in werkelijkheid een <b>gereconstrueerde Romeinse grafheuvel</b> — een tumulus zoals de Romeinen die voor hun notabelen bouwden, hier in de vorige eeuw weer zichtbaar opgetrokken en geliefd bij kinderen (vandaar de naam). Rondom liggen de sporen van de <b>Romeinse villa</b> die hier ooit stond, met een <b>gereconstrueerde villa-akker</b> waar oude graanrassen en akkeronkruiden groeien zoals dat twee millennia geleden gebeurde. En door het geheel loopt de <b>Kleine Beerze</b>, die na jaren kanalisatie <b>weer meandert</b> door het dal — het bos sluit aan op Heieinden (kaart 2351) en de Landschotse Heide (kaart 2346). Wie de Kabouterberg beklimt op een herfstmorgen, kijkt uit over een bos dat de tijd heeft doorstaan — van Romeinse grafheuvel tot gemeenschapsbos van toen.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–mei</b> (voorjaarsflora in het oude bos), jun–sep (villa-akker in seizoen), sep–nov (paddenstoelen onder de oude dennen)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht tussen de oude stammen.',
 'why': ['Het <b>16e-eeuwse gemeenschapsbezit</b> als unicum.', 'De <b>oudste bomen</b> van de gemeente (±1850).', 'De <b>Kabouterberg</b> als Romeinse grafheuvel.', 'De <b>villa-akker</b> met oude graanrassen.', 'De <b>weer meanderende Kleine Beerze</b>.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌼 <b>Voorjaarsflora</b> in het oude bos.', '<span class="months">Jun–jul</span> 🌾 <b>Oude graanrassen</b> op de villa-akker.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> onder de dennen.', '<span class="months">Dec–feb</span> ❄️ <b>Kabouterberg</b> in winters licht.'],
 'wild': ['🌳 16e-eeuws bos', '🗼 Kabouterberg', '🏛️ Romeinse tijd', '🌾 Villa-akker', '💧 Meanderende Beerze'],
 'trail': ['Beklim de <b>Kabouterberg</b> in de Koebosch.', 'Bekijk de <b>villa-akker</b> met de oude rassen.', 'Volg de <b>Kleine Beerze</b> door het dal richting Heieinden (2351).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–8 km · 🅿️ Koebosch (Hoogeloon–Hapert)'
}, {
 'tags': ['North Brabant · between Hoogeloon and Hapert, on the upper Kleine Beerze (gem. Bladel)', 'very old woodland of the municipality of Bladel · already in the community’s possession in the 16th century; the municipality’s oldest trees (pines from ±1850); the Kabouterberg (“Gnome Hill”) in the Koebosch is a reconstructed Roman barrow; with a Roman villa field and the again-meandering Kleine Beerze', 'list 88 · no. 22'],
 'loc': '📍 Gemeentebossen Hoogeloon — car park at the Koebosch (Kabouterberg) on the Hoogeloon–Hapert road; combine with Heieinden (card 2351) and the Landschotse Heide (card 2346)',
 'desc': 'The <b>municipal woods</b> of <b>Hoogeloon</b> are among the oldest woods of Brabant: already in the <b>16th century</b> they appeared on the map as the property of the local community — a rare case of woodland that never belonged to a lord, a monastery or a developer, but to the village itself. That explains the remarkable composition: besides production stands there are <b>old deciduous woods</b> with centuries-old structure, and here stand the <b>oldest trees of the municipality of Bladel</b> — pines planted around <b>1850</b>, now among the tallest and thickest of the region. The showpiece lies in the <b>Koebosch</b>: the <b>Kabouterberg</b>, “Gnome Hill” in local speech, is in reality a <b>reconstructed Roman barrow</b> — a tumulus such as the Romans built for their notables, rebuilt to visibility in the last century and beloved of children (hence the name). Around it lie the traces of the <b>Roman villa</b> that once stood here, with a <b>reconstructed villa field</b> where old grain varieties and arable weeds grow as they did two millennia ago. And through it all runs the <b>Kleine Beerze</b>, which after years of canalisation <b>meanders again</b> through the valley — the wood links up with Heieinden (card 2351) and the Landschotse Heide (card 2346). Climb the Kabouterberg on an autumn morning and you look out over a woodland that has outlasted time — from Roman barrow to village-common forest.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–May</b> (spring flora in the old wood), Jun–Sep (villa field in season), Sep–Nov (fungi under the old pines)<br>\n    <b>Best time of day:</b> Morning — light between the old trunks.',
 'why': ['The <b>16th-century common ownership</b> as a unique case.', 'The municipality’s <b>oldest trees</b> (±1850).', 'The <b>Kabouterberg</b> as a Roman barrow.', 'The <b>villa field</b> with old grain varieties.', 'The <b>again-meandering Kleine Beerze</b>.'],
 'phen': ['<span class="months">Mar–May</span> 🌼 <b>Spring flora</b> in the old wood.', '<span class="months">Jun–Jul</span> 🌾 <b>Old grain varieties</b> on the villa field.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> under the pines.', '<span class="months">Dec–Feb</span> ❄️ <b>Kabouterberg</b> in winter light.'],
 'wild': ['🌳 16th-century wood', '🗼 Kabouterberg', '🏛️ Roman era', '🌾 Villa field', '💧 Meandering Beerze'],
 'trail': ['Climb the <b>Kabouterberg</b> in the Koebosch.', 'View the <b>villa field</b> with its old varieties.', 'Follow the <b>Kleine Beerze</b> through the valley towards Heieinden (2351).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–8 km · 🅿️ Koebosch (Hoogeloon–Hapert)'
}))

C.append(mk.card(2351, 'Heieinden', {
 'tags': ['Noord-Brabant · tussen Hoogeloon en de Landschotse Heide (gem. Bladel/Oirschot)', 'natuurgebied van bos, heideresten en landbouwgronden in de overgangsstrook van de Kempen · hier staat het monument voor de Amerikaanse onderduikers van de Tweede Wereldoorlog; verbinding tussen de Gemeentebossen Hoogeloon en de Landschotse Heide', 'list 88 · no. 23'],
 'loc': '📍 Heieinden, ten zuidwesten van de Landschotse Heide tussen Hoogeloon en Middelbeers — zandpaden door bos en heideresten; combineer met de Gemeentebossen Hoogeloon (kaart 2350) en de Landschotse Heide (kaart 2346)',
 'desc': 'De naam <b>Heieinden</b> zegt waar dit gebied ligt: aan het “einde” van de hei, de laatste strook waar het hoge zandland van de Kempen overgaat in de beekdalen van de Beerzen. Tussen <b>Hoogeloon</b> en de <b>Landschotse Heide</b> (kaart 2346) vormt het een <b>verbinder</b>: geen showgebied, maar juist daardom een van die stille stukken Brabant waar de wandelaar alleen is met bos, heideresten en akkerlanden die het oude mozaïek vasthouden. De waarde zit in de <b>overgang</b>: droge naaldbosranden waar <b>boomklevers en spechten</b> huizen, vochtige heidefragmenten met <b>libellen</b> in de zomer, en graanvelden waar de <b>hamsters van de vogelwereld</b> — kneu en veldleeuwerik — ’s winters voedsel zoeken. In dit gebied staat ook het <b>monument voor de Amerikaanse onderduikers</b> van de Tweede Wereldoorlog: neergestorte Amerikaanse vliegers die hier maandenlang verborgen werden gehouden door boerengezinnen uit de streek — een verhaal van verzet dat dieper zit dan de rust van het landschap doet vermoeden. Wie de lange verbinding loopt van de Gemeentebossen (kaart 2350) via Heieinden naar de Landschotse vennen, maakt de klassieke Kempen-traverse: van oud bos via stil overgangsland naar open hei met water — en Heieinden is precies het rustige middendeel dat die wandeling tot een geheel maakt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (zangvogels in de bosranden), jun–sep (libellen op de heidefragmenten), sep–okt (herfst in het overgangsland)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht over de overgangsstrook.',
 'why': ['De <b>overgangspositie</b> tussen bos en hei.', 'Het <b>Amerikaanse onderduikersmonument</b> uit de Tweede Wereldoorlog.', 'De <b>verbinding</b> Hoogeloon–Landschot.', 'De <b>stille rust</b> van het niet-showgebied.', 'Het <b>mozaïek</b> van bos, hei en akker.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Zangvogels</b> in de bosranden.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> op de heidefragmenten.', '<span class="months">Aug–sep</span> 💜 <b>Heideresten</b> in bloei.', '<span class="months">Sep–okt</span> 🍂 <b>Herfst</b> in het overgangsland.'],
 'wild': ['🔗 Verbinder', '🕊️ Oorlogsmonument', '🌳 Bosranden', '💜 Heideresten', '🍂 Stilte'],
 'trail': ['Loop de <b>verbinding</b> van de Gemeentebossen (2350) naar de Landschotse Heide (2346).', 'Zoek het <b>onderduikersmonument</b> in het gebied.', 'Wandel de <b>zandpaden</b> langs bos en akkerland.'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–10 km · 🚫 Geen echte parking — starten in Hoogeloon'
}, {
 'tags': ['North Brabant · between Hoogeloon and the Landschotse Heide (gem. Bladel/Oirschot)', 'nature area of wood, heath rests and farmland in the Campine transition zone · here stands the monument to the Second World War American airmen in hiding; link between the Gemeentebossen Hoogeloon and the Landschotse Heide', 'list 88 · no. 23'],
 'loc': '📍 Heieinden, south-west of the Landschotse Heide between Hoogeloon and Middelbeers — sand paths through wood and heath rests; combine with the Gemeentebossen Hoogeloon (card 2350) and the Landschotse Heide (card 2346)',
 'desc': 'The name <b>Heieinden</b> tells you where this area lies: at the “end” of the heath, the last strip where the high Campine sands give way to the Beerze valleys. Between <b>Hoogeloon</b> and the <b>Landschotse Heide</b> (card 2346) it forms a <b>connector</b>: no showpiece area, but precisely therefore one of those quiet pieces of Brabant where the walker is alone with wood, heath rests and arable fields holding on to the old mosaic. The value lies in the <b>transition</b>: dry conifer edges housing <b>nuthatches and woodpeckers</b>, humid heath fragments with <b>dragonflies</b> in summer, and cornfields where the <b>hamsters of the bird world</b> — corn bunting and skylark — search for food in winter. In this area also stands the <b>monument to the American airmen in hiding</b> of the Second World War: shot-down American flyers kept hidden here for months by farming families of the region — a story of resistance running deeper than the calm of the landscape suggests. Walk the long link from the Gemeentebossen (card 2350) via Heieinden to the Landschotse pools and you make the classic Campine traverse: from old wood through quiet transition land to open heath with water — and Heieinden is precisely the quiet middle section that makes that walk a whole.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (songbirds in the wood edges), Jun–Sep (dragonflies on the heath fragments), Sep–Oct (autumn in the transition land)<br>\n    <b>Best time of day:</b> Morning — light over the transition strip.',
 'why': ['The <b>transition position</b> between wood and heath.', 'The Second World War <b>airmen monument</b>.', 'The <b>link</b> Hoogeloon–Landschot.', 'The <b>quiet</b> of a non-showpiece area.', 'The <b>mosaic</b> of wood, heath and arable land.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Songbirds</b> in the wood edges.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> on the heath fragments.', '<span class="months">Aug–Sep</span> 💜 <b>Heath rests</b> in flower.', '<span class="months">Sep–Oct</span> 🍂 <b>Autumn</b> in the transition land.'],
 'wild': ['🔗 Connector', '🕊️ War monument', '🌳 Wood edges', '💜 Heath rests', '🍂 Quiet'],
 'trail': ['Walk the <b>link</b> from the Gemeentebossen (2350) to the Landschotse Heide (2346).', 'Seek the <b>airmen monument</b> in the area.', 'Wander the <b>sand paths</b> along wood and arable land.'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–10 km · 🚫 No real car park — start in Hoogeloon'
}))

C.append(mk.card(2352, 'Buikheide Oude Molen', {
 'tags': ['Noord-Brabant · ten westen van Wintelre en Vessem (gem. Eersel)', '520 ha bosgebied van de gemeente Eersel met het Grootmeer en Kleinmeer · Weichselien-vennen (ontstaan 116.000–11.700 jaar geleden) die nooit verzuurden — sinds 1990 beschermd natuurmonument met bijzondere plantengroei; rond de vennen gerood productiebos; grafheuvels bij Toterfout-Halfmijl aan de zuidrand', 'list 88 · no. 24'],
 'loc': '📍 Buikheide en Oude Molen — parkeerplaats aan de Merenweg (Wintelre), meteen uitzicht op het Grootmeer; 11,5 km rondwandeling Grootmeer–Kleinmeer; in het zuiden sluit het gebied aan op de grafheuvels van Toterfout-Halfmijl; combineer met de Oirschotse Heide (kaart 2355)',
 'desc': 'Ten westen van <b>Wintelre</b> ligt een bosgebied van <b>520 hectare</b> dat zijn naam ontleent aan twee gezichten: de <b>Buikheide</b>, het naaldbos dat op de oude hei werd aangeplant, en <b>Oude Molen</b>, de kern met de vennen. Hart van het gebied zijn het <b>Grootmeer</b> en het <b>Kleinmeer</b> — twee vennen die niet, zoals zoveel Kempische wateren, zijn verzuurd, en daardoor een <b>bijzondere plantengroei</b> bleven houden; in <b>1990</b> werden ze daarom aangewezen als <b>beschermd natuurmonument</b>. De vennen zijn oud: ze ontstonden in het <b>Weichselien</b>, de ijstijdperiode van 116.000 tot 11.700 jaar geleden, toen de wind laagtes in het zand blies die later met water vulden. De <b>waterstand</b> van vooral het Grootmeer <b>fluctueert sterk</b>: het meer kan bijna droogvallen en het water tot ver in het bos staan — een dynamiek die bij de bijzondere flora hoort. Rond de vennen werd het <b>productiebos gerood</b>, zodat een afwisselender begroeiingspatroon kon ontstaan; verderop wisselen eentonige dennenbossen zich af met open percelen en volgroeide <b>Amerikaanse eiken en fraaie sparren</b>. Ten noorden van de Merenweg is het nog stiller; wie de weg daar oversteekt, stuit op de open vlaktes van de <b>Oirschotse Heide</b> (kaart 2355). En in het zuiden, richting Vessem, liggen de beroemde <b>grafheuvels van Toterfout-Halfmijl</b> — de grootste grafheuvelgroep van Nederland. De klassieke wandeling (11,5 km) combineert het alles: meteen vanaf de parkeerplaats het Grootmeer, dan het bos in, langs akkers naar het Kleinmeer, en terug door het rustige noorden.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (venflora en voorjaarsbos), jun–sep (libellen boven de vennen), sep–nov (paddenstoelen in het productiebos)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — spiegelend Grootmeer.',
 'why': ['De <b>niet-verzuurde vennen</b> met hun bijzondere flora.', 'De <b>Weichselien-oudheid</b> van Grootmeer en Kleinmeer.', 'Het <b>beschermde natuurmonument</b> (1990).', 'De <b>sterk fluctuerende waterstand</b> van het Grootmeer.', 'De ligging bij de <b>grafheuvels van Toterfout-Halfmijl</b>.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌼 <b>Voorjaarsflora</b> rond de vennen.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> boven Groot- en Kleinmeer.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> in het productiebos.', '<span class="months">Dec–feb</span> ❄️ <b>Winters stilte</b> ten noorden van de Merenweg.'],
 'wild': ['💧 Twee vennen', '🧊 Weichselien', '🔒 Natuurmonument 1990', '🌳 Amerikaanse eiken', '🏛️ Grafheuvels nabij'],
 'trail': ['Loop de <b>rondwandeling</b> (11,5 km) Grootmeer–Kleinmeer vanaf de Merenweg.', 'Bekijk het <b>spiegelende Grootmeer</b> bij de parking.', 'Steek naar het noorden over naar de <b>Oirschotse Heide</b> (2355).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Rondwandeling 11,5 km · 🅿️ Merenweg (Wintelre)'
}, {
 'tags': ['North Brabant · west of Wintelre and Vessem (gem. Eersel)', '520-ha woodland of the municipality of Eersel with the Grootmeer and Kleinmeer · Weichselian fens (formed 116,000–11,700 years ago) that never acidified — protected nature monument since 1990 with special plant growth; production forest cleared around the fens; barrows of Toterfout-Halfmijl on the southern edge', 'list 88 · no. 24'],
 'loc': '📍 Buikheide and Oude Molen — car park on the Merenweg (Wintelre), with a view of the Grootmeer at once; 11.5-km round walk Grootmeer–Kleinmeer; to the south the area joins the Toterfout-Halfmijl barrows; combine with the Oirschotse Heide (card 2355)',
 'desc': 'West of <b>Wintelre</b> lies a woodland of <b>520 hectares</b> taking its name from two faces: the <b>Buikheide</b>, the conifer wood planted on the old heath, and <b>Oude Molen</b>, the core with the fens. The heart of the area is the <b>Grootmeer</b> and the <b>Kleinmeer</b> — two fens that, unlike so many Campine waters, never acidified, and thus kept a <b>special plant growth</b>; in <b>1990</b> they were therefore designated a <b>protected nature monument</b>. The fens are old: they formed in the <b>Weichselian</b>, the glacial period of 116,000 to 11,700 years ago, when the wind blew hollows into the sand that later filled with water. The <b>water level</b> of the Grootmeer especially <b>fluctuates strongly</b>: the lake can nearly dry out or stand with water far into the wood — a dynamics belonging to the special flora. Around the fens the <b>production forest was cleared</b>, allowing a more varied vegetation pattern; further on monotonous pine woods alternate with open stands and mature <b>American oaks and fine spruces</b>. North of the Merenweg it is quieter still; cross the road there and you meet the open flats of the <b>Oirschotse Heide</b> (card 2355). And to the south, towards Vessem, lie the famous <b>barrows of Toterfout-Halfmijl</b> — the largest barrow group of the Netherlands. The classic walk (11.5 km) combines it all: the Grootmeer straight from the car park, then into the wood, past fields to the Kleinmeer, and back through the quiet north.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (fen flora and spring wood), Jun–Sep (dragonflies above the fens), Sep–Nov (fungi in the production forest)<br>\n    <b>Best time of day:</b> Morning — mirroring Grootmeer.',
 'why': ['The <b>never-acidified fens</b> with their special flora.', 'The <b>Weichselian age</b> of the Grootmeer and Kleinmeer.', 'The <b>protected nature monument</b> (1990).', 'The <b>strongly fluctuating water level</b> of the Grootmeer.', 'The position by the <b>Toterfout-Halfmijl barrows</b>.'],
 'phen': ['<span class="months">Mar–May</span> 🌼 <b>Spring flora</b> around the fens.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> above the Groot- and Kleinmeer.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> in the production forest.', '<span class="months">Dec–Feb</span> ❄️ <b>Wintry silence</b> north of the Merenweg.'],
 'wild': ['💧 Two fens', '🧊 Weichselian', '🔒 1990 nature monument', '🌳 American oaks', '🏛️ Barrows nearby'],
 'trail': ['Walk the <b>round walk</b> (11.5 km) Grootmeer–Kleinmeer from the Merenweg.', 'View the <b>mirroring Grootmeer</b> by the car park.', 'Cross northwards to the <b>Oirschotse Heide</b> (2355).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Round walk 11.5 km · 🅿️ Merenweg (Wintelre)'
}))

mk.insert(C, chunk='reserves-2335-2434.json')
mk.progress(2352)
mk.check()
