# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk
C = []

C.append(mk.card(2358, 'Mirandolles Heike', {
 'tags': ['Noord-Brabant · langs de Gender ten zuiden van Eersel (gem. Eersel)', 'natuurgebied van Natuurmonumenten, geschonken in 1936–1939 door mejuffrouw Mirandolle · de freule die honderd jaar werd en Eersels heidegronden eerlijk onder de boeren deed verdelen; sinds 2020 verbonden met het kunst-natuurproject De Gender en het Domein bij Oogenlust', 'list 88 · no. 30'],
 'loc': '📍 Mirandolles Heike, langs de Gender ten zuiden van Eersel — start bij Oogenlust of vanaf het wandelnetwerk rond Eersel; combineer met de Knegelse Heide (kaart 2357) stroomopwaarts langs de Gender',
 'desc': 'Achter dit gebied gaat één van de opvallendste vrouwen van de Brabantse Kempen schuil: <b>mejuffrouw Mirandolle</b>, de <b>freule</b> die <b>honderd jaar</b> werd, van haar lange leven hooguit twintig zomers in <b>Eersel</b> doorbracht — en desondanks de streek blijvend vormde. Ze zag erop toe dat de <b>Eerselse heidegronden op een correcte manier onder de boeren verdeeld</b> werden, daarbij <b>oog houdend voor het behoud van de heide</b>, en tussen <b>1936 en 1939</b> schonk ze een groot deel van haar grondbezit aan <b>Natuurmonumenten</b>: sindsdien heet dat gebied <b>Mirandolles Heike</b>. Het ligt langs de <b>Gender</b>, de kleine beek die van Knegsel (kaart 2357) door Eersel naar Eindhoven stroomt en hier het landschap draineert tot een afwisseling van <b>hooilandjes, bosjes en heideresten</b>. Wie er nu loopt, ziet ook het jongste hoofdstuk: sinds <b>2020</b> werken Natuurmonumenten, de gemeente Eersel en landgoed-kunstenaars van <b>Oogenlust</b> aan het project <b>De Gender en het Domein</b> — een natuurlijk recreatiegebied waarin <b>kunst en natuur verbonden</b> worden, met ontwerpen van landschapsarchitecten en subsidie uit Mijn Mooi Brabant. Haar villa op <b>De Hees</b> werd na haar dood galerie (1969–2003); haar naam leeft voort in het heike dat ze de Kempen naliet — en in de verhalen van freules die, als ze voorbijkwamen, iedereen deden omkijken.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (hooilandbloei en vogels), jun–sep (kunstobjecten in het groen), okt–nov (herfst langs de Gender)<br>\n    <b>Beste tijd van de dag:</b> Middag — licht in de beekvallei.',
 'why': ['Het <b>freule-verhaal</b> van mejuffrouw Mirandolle (1936–1939).', 'De <b>Gender</b> als dragende beek.', 'Het <b>kunst-natuurproject</b> De Gender en het Domein (2020).', 'De <b>verscheidenheid</b> van hooiland, bos en heiderest.', 'De <b>verbinding</b> met Knegsel en Eersel.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Weide- en zangvogels</b> in de hooilanden.', '<span class="months">Mei–jun</span> 🌼 <b>Hooilandbloei</b> langs de Gender.', '<span class="months">Jun–sep</span> 🎨 <b>Kunst in het landschap</b>.', '<span class="months">Okt–nov</span> 🍂 <b>Herfst</b> in de beekvallei.'],
 'wild': ['👑 Freule Mirandolle', '💧 De Gender', '🎨 Kunst-natuur', '🌾 Hooilanden', '🌲 Bosjes en heideresten'],
 'trail': ['Start bij <b>Oogenlust</b> en volg de <b>kunst-route</b> langs de Gender.', 'Wandel stroomopwaarts naar <b>Knegsel</b> (2357).', 'Combineer met de <b>ommetjes van Eersel</b> (2364).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–8 km · 🅿️ Oogenlust / Eersel'
}, {
 'tags': ['North Brabant · along the Gender south of Eersel (gem. Eersel)', 'nature reserve of Natuurmonumenten, donated in 1936–1939 by Miss Mirandolle · the lady who turned a hundred and had Eersel’s heath fairly divided among the farmers; since 2020 linked to the art-nature project De Gender en het Domein at Oogenlust', 'list 88 · no. 30'],
 'loc': '📍 Mirandolles Heike, along the Gender south of Eersel — start at Oogenlust or from the walking network around Eersel; combine with the Knegse Heide (card 2357) upstream along the Gender',
 'desc': 'Behind this area hides one of the most remarkable women of the Brabant Campine: <b>Miss Mirandolle</b>, the <b>lady</b> who turned <b>a hundred years old</b>, spent at most twenty summers of her long life in <b>Eersel</b> — and shaped the region lastingly all the same. She oversaw the <b>fair division of Eersel’s heathlands among the farmers</b>, <b>keeping an eye on the preservation of the heath</b>, and between <b>1936 and 1939</b> she donated a large part of her land to <b>Natuurmonumenten</b>: since then the area has been called <b>Mirandolles Heike</b>. It lies along the <b>Gender</b>, the small stream flowing from Knegsel (card 2357) through Eersel towards Eindhoven, here draining the land into a mix of <b>hay meadows, copses and heath rests</b>. Walk here now and you also see the newest chapter: since <b>2020</b> Natuurmonumenten, the municipality of Eersel and the estate artists of <b>Oogenlust</b> have been developing the <b>De Gender en het Domein</b> project — a natural recreation area where <b>art and nature are tied together</b>, with designs by landscape architects and funding from Mijn Mooi Brabant. Her villa on <b>De Hees</b> became a gallery after her death (1969–2003); her name lives on in the heike she left the Campine — and in the tales of ladies at whom everyone looked up when she passed by.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow flowering and birds), Jun–Sep (art objects in the green), Oct–Nov (autumn along the Gender)<br>\n    <b>Best time of day:</b> Midday — light in the stream valley.',
 'why': ['The <b>lady’s story</b> of Miss Mirandolle (1936–1939).', 'The <b>Gender</b> as carrying stream.', 'The <b>art-nature project</b> De Gender en het Domein (2020).', 'The <b>variety</b> of meadow, wood and heath rest.', 'The <b>link</b> to Knegsel and Eersel.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Meadow and song birds</b> in the hay fields.', '<span class="months">May–Jun</span> 🌼 <b>Hay-meadow flowering</b> along the Gender.', '<span class="months">Jun–Sep</span> 🎨 <b>Art in the landscape</b>.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the stream valley.'],
 'wild': ['👑 Lady Mirandolle', '💧 The Gender', '🎨 Art-nature', '🌾 Hay meadows', '🌲 Copses and heath rests'],
 'trail': ['Start at <b>Oogenlust</b> and follow the <b>art route</b> along the Gender.', 'Walk upstream to <b>Knegsel</b> (2357).', 'Combine with the <b>loops of Eersel</b> (2364).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–8 km · 🅿️ Oogenlust / Eersel'
}))

C.append(mk.card(2359, 'Ten Vorsel', {
 'tags': ['Noord-Brabant · landgoed 2 km ten zuiden van Bladel, aan weerszijden van de Aa of Goorloop (gem. Bladel)', 'historisch landgoed van 230 ha, ontstaan rond 1100 · eeuwenlang bezit van de Abdij van Postel (1173 al een boerderij); nu eigendom van de Maatschappij van Welstand; akkers, weilanden en loof- en naaldbos; de Heksenboom (Boom van het Jaar 2019), een Franciscuskapel en een vleermuizenkelder', 'list 88 · no. 31'],
 'loc': '📍 Landgoed Ten Vorsel, ten zuiden van Bladel (Ten Vorsel 1a) — landgoedpaden langs de Aa of Goorloop; combineer met het Dal van de Groote Beerze (kaart 2349) en De Palts en Kroonvense Heide (kaart 2360)',
 'desc': 'Twee kilometer ten zuiden van <b>Bladel</b> ligt een landgoed dat teruggaat tot de vroegste geschreven geschiedenis van de Kempen: <b>Ten Vorsel</b>, <b>230 hectare</b> groot, ontstaan rond <b>1100</b> en al in <b>1173</b> in het bezit van de <b>Abdij van Postel</b> — de Norbertijnenabdij die aan de andere kant van de grens haar klokken luidt en hier al in de twaalfde eeuw een boerderij bezat. Eeuwenlang was het goed monnikenwerk; vandaag is het eigendom van de <b>Maatschappij van Welstand</b>, de klassieke Brabantse landgoedmaatschappij, en bestaat het uit <b>akkers en weilanden met stukken loof- en naaldbos</b>, doorkruist van landgoedpaden langs de <b>Aa of Goorloop</b> — de beek die samen met het Dalemstroompje de <b>Groote Beerze</b> vormt (kaart 2349) en hier nog smal en jong door het landschap meandert. Op het terrein staat de <b>Vorselse Molen</b>-accommodatie, genoemd naar de <b>watermolen</b> die hier ooit stond. De beroemdste bewoner staat aan de rand: de <b>Heksenboom</b>, een eeuwenoude boom waaronder volgens de legende van <b>De Gloeiige</b> — een vervloekte schéper uit Reusel, begin zeventiende eeuw — het gevloekte lichaam begraven ligt, en waarin de verhalen van de heks <b>Zwarte Kaat</b> spelen; in <b>2019</b> werd de boom verkozen tot <b>Nederlandse Boom van het Jaar</b>. Verder een <b>Franciscuskapel</b> en een <b>vleermuizenkelder</b>. Wie hier loopt, wandelt door negen eeuwen Kempense geschiedenis — van abdijbezit tot heksenlegende.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (weidebloei, lanen in blad), jun–aug (vleermuizen boven de kelder), okt–nov (herfst in het loofbos)<br>\n    <b>Beste tijd van de dag:</b> Avond — vleermuizen bij de kelder.',
 'why': ['De <b>abdij-geschiedenis</b> (Postel, 1173).', 'De <b>Aa of Goorloop</b> als jonge Beerze-bron.', 'De <b>Heksenboom</b> — Boom van het Jaar 2019.', 'De legende van <b>De Gloeiige</b> en Zwarte Kaat.', 'De <b>vleermuizenkelder</b> en de Franciscuskapel.'],
 'phen': ['<span class="months">Mrt–mei</span> 🎶 <b>Vogelzang</b> in bos en lanen.', '<span class="months">Mei–jun</span> 🌼 <b>Weidebloei</b> op de akkerlanden.', '<span class="months">Jun–aug</span> 🦇 <b>Vleermuizen</b> bij de kelder.', '<span class="months">Okt–nov</span> 🍂 <b>Herfst</b> in het loofbos.'],
 'wild': ['⛪ Abdijgeschiedenis', '🌳 Heksenboom', '💧 Aa of Goorloop', '🦇 Vleermuizenkelder', '🕯️ Franciscuskapel'],
 'trail': ['Wandel de <b>landgoedpaden</b> langs de Aa of Goorloop.', 'Zoek de <b>Heksenboom</b> aan de rand van het goed.', 'Combineer met het <b>Dal van de Groote Beerze</b> (2349).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 3–8 km · 🅿️ Ten Vorsel 1a / Bladel'
}, {
 'tags': ['North Brabant · estate 2 km south of Bladel, on both banks of the Aa of Goorloop (gem. Bladel)', 'historic estate of 230 ha, arising around 1100 · for centuries property of Postel Abbey (a farm already in 1173); now owned by the Maatschappij van Welstand; fields, meadows and deciduous and coniferous wood; the Witches’ Tree (Dutch Tree of the Year 2019), a Francis chapel and a bat cellar', 'list 88 · no. 31'],
 'loc': '📍 Landgoed Ten Vorsel, south of Bladel (Ten Vorsel 1a) — estate paths along the Aa of Goorloop; combine with the Dal van de Groote Beerze (card 2349) and De Palts en Kroonvense Heide (card 2360)',
 'desc': 'Two kilometres south of <b>Bladel</b> lies an estate reaching back to the earliest written history of the Campine: <b>Ten Vorsel</b>, <b>230 hectares</b>, arising around <b>1100</b> and already in <b>1173</b> in the possession of <b>Postel Abbey</b> — the Premonstratensian abbey ringing its bells across the border and holding a farm here as early as the twelfth century. For centuries the estate was monks’ work; today it belongs to the <b>Maatschappij van Welstand</b>, the classic Brabant estate company, and consists of <b>fields and meadows with stretches of deciduous and coniferous wood</b>, crossed by estate paths along the <b>Aa of Goorloop</b> — the stream that together with the Dalemstroompje forms the <b>Groote Beerze</b> (card 2349), here still narrow and young, meandering through the land. On the ground stands the <b>Vorselse Molen</b> accommodation, named after the <b>water mill</b> that once stood here. The most famous resident stands at the edge: the <b>Witches’ Tree</b>, a centuries-old tree under which, according to the legend of <b>De Gloeiige</b> — a cursed shepherd from Reusel, early seventeenth century — the damned body lies buried, and in which the tales of the witch <b>Zwarte Kaat</b> play; in <b>2019</b> the tree was voted <b>Dutch Tree of the Year</b>. Further on a <b>Francis chapel</b> and a <b>bat cellar</b>. Walk here and you walk through nine centuries of Campine history — from abbey property to witches’ legend.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (meadow flowering, lanes in leaf), Jun–Aug (bats above the cellar), Oct–Nov (autumn in the deciduous wood)<br>\n    <b>Best time of day:</b> Evening — bats at the cellar.',
 'why': ['The <b>abbey history</b> (Postel, 1173).', 'The <b>Aa of Goorloop</b> as young Beerze source.', 'The <b>Witches’ Tree</b> — Tree of the Year 2019.', 'The legend of <b>De Gloeiige</b> and Black Kaat.', 'The <b>bat cellar</b> and the Francis chapel.'],
 'phen': ['<span class="months">Mar–May</span> 🎶 <b>Birdsong</b> in wood and lanes.', '<span class="months">May–Jun</span> 🌼 <b>Meadow flowering</b> on the fields.', '<span class="months">Jun–Aug</span> 🦇 <b>Bats</b> at the cellar.', '<span class="months">Oct–Nov</span> 🍂 <b>Autumn</b> in the deciduous wood.'],
 'wild': ['⛪ Abbey history', '🌳 Witches’ Tree', '💧 Aa of Goorloop', '🦇 Bat cellar', '🕯️ Francis chapel'],
 'trail': ['Walk the <b>estate paths</b> along the Aa of Goorloop.', 'Seek the <b>Witches’ Tree</b> at the estate’s edge.', 'Combine with the <b>Dal van de Groote Beerze</b> (2349).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 3–8 km · 🅿️ Ten Vorsel 1a / Bladel'
}))

C.append(mk.card(2360, 'De Palts en Kroonvense Heide', {
 'tags': ['Noord-Brabant · ten zuiden van Bladel en Hapert, in Boswachterij De Kempen (gem. Bladel)', '508 ha bos- en natuurgebied van Staatsbosbeheer · naaldbossen uit begin twintigste eeuw op voormalige heide, afgewisseld met landbouw en heideresten; De Palts (De Pals) is deels bosreservaat met grove dennen uit 1882 — dubbelloof, dalkruid, rosse vleermuis, zwarte specht en gladde slang; thuishonk van de Kabouters van Kyrië in de verhalenwereld', 'list 88 · no. 32'],
 'loc': '📍 De Palts en Kroonvense Heide, ten zuiden van Bladel — start bij parkeerplaats De Pals (Staatsbosbeheer); combineer met het Landgoed Ten Vorsel (kaart 2359) en de Cartierheide (kaart 2362)',
 'desc': 'Ten zuiden van <b>Bladel</b> en <b>Hapert</b> ligt één van de grootste aaneengesloten boscomplexen van zuidelijk Brabant: <b>De Palts en de Kroonvense Heide</b> samen <b>508 hectare</b>, aan het begin van de twintigste eeuw geplant op wat toen <b>heide</b> was — en vandaag het hart van <b>Boswachterij De Kempen</b> van <b>Staatsbosbeheer</b>. Het zijn de klassieke Kempense naaldbossen, met productiepercelen, landbouwgronden en daartussen de heideresten die de oude naam dragen. Maar wie goed kijkt, vindt hier bos van een andere ouderdom: in <b>De Palts</b> (de “Pals”) staat een <b>bosreservaat</b> met <b>grove dennen die uit 1882 stammen</b> — bomen van bijna anderhalve eeuw, neergezet in de allereerste aanplantgolf, met een ondergroei van <b>dubbelloof</b> en <b>dalkruid</b>. Rond <b>2004</b> werden de exoten (met name Amerikaanse eik) verwijderd om het natuurlijke milieu te versterken. De bewoners zijn indrukwekkend: de <b>rosse vleermuis</b> en de <b>zwarte specht</b>, en — net als op de Cartierheide — de <b>gladde slang</b>, waarvoor hier ook monitoring rijtjes lopen; verder ree, konijn, haas en sinds kort ook steeds vaker <b>wilde zwijnen</b>. Bij de oude <b>zandvang</b> in Bladel werd een <b>sluis</b> gebouwd om het water hoog te houden. En in de verhalen van de streek is dit het rijk van de <b>Kabouters van Kyrië</b>: de boer die het niet meer aankon trok naar de Kroonvense Heide, waar <b>Kabouterkoning Kyrië</b> rondliep op zoek naar geneeskrachtige kruiden voor de zieke <b>Kabouterboom</b> — een vertelroute die kinderen hier vandaag nog laat zoeken.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (voorjaarsflora onder de oude dennen), jun–sep (libellen en insecten), sep–nov (paddenstoelen in het reservaat)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — licht in de dennenrijen van 1882.',
 'why': ['De <b>grove dennen van 1882</b> in het bosreservaat.', 'De <b>508 ha</b> als hart van Boswachterij De Kempen.', 'De <b>gladde slang</b> en zwarte specht als bewoners.', 'De <b>Kabouters van Kyrië</b> als vertelwereld.', 'De <b>sluis bij de zandvang</b> als waterhoeder.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌼 <b>Dubbelloof en dalkruid</b> in het reservaat.', '<span class="months">Apr–jun</span> 🎶 <b>Spechten</b> in de oude opstanden.', '<span class="months">Jun–sep</span> 🐉 <b>Libellen</b> bij de vochtige plekken.', '<span class="months">Sep–nov</span> 🍄 <b>Paddenstoelen</b> onder de dennen.'],
 'wild': ['🌲 Dennen van 1882', '🐍 Gladde slang', '🦇 Rosse vleermuis', '🧙 Kabouters van Kyrië', '💧 Sluis en zandvang'],
 'trail': ['Start bij <b>De Pals</b> en loop het <b>bosreservaat</b> in.', 'Volg de <b>paaltjesroutes</b> van Staatsbosbeheer.', 'Combineer met <b>Ten Vorsel</b> (2359) en de <b>Cartierheide</b> (2362).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Paaltjesroutes 3–10 km · 🅿️ De Pals (Staatsbosbeheer)'
}, {
 'tags': ['North Brabant · south of Bladel and Hapert, in Boswachterij De Kempen (gem. Bladel)', '508-ha woodland and nature area of Staatsbosbeheer · coniferous woods from the early twentieth century on former heath, alternating with farmland and heath rests; De Palts (De Pals) is partly forest reserve with Scots pines from 1882 — lily-of-the-valley, Solomon’s seal, parti-coloured bat, black woodpecker and smooth snake; home ground of the Gnomes of Kyrië tales', 'list 88 · no. 32'],
 'loc': '📍 De Palts en Kroonvense Heide, south of Bladel — start at the De Pals car park (Staatsbosbeheer); combine with Landgoed Ten Vorsel (card 2359) and the Cartierheide (card 2362)',
 'desc': 'South of <b>Bladel</b> and <b>Hapert</b> lies one of the largest continuous woodland complexes of southern Brabant: <b>De Palts and the Kroonvense Heide</b> together <b>508 hectares</b>, planted at the start of the twentieth century on what was then <b>heath</b> — today the heart of <b>Boswachterij De Kempen</b> of <b>Staatsbosbeheer</b>. These are the classic Campine conifer woods, with production stands, farmland and between them the heath rests carrying the old name. But look closely and you find wood of another age: in <b>De Palts</b> (the “Pals”) lies a <b>forest reserve</b> with <b>Scots pines dating from 1882</b> — trees of almost a century and a half, planted in the very first planting wave, with an undergrowth of <b>may lily</b> and <b>Solomon’s seal</b>. Around <b>2004</b> the exotics (above all American oak) were removed to strengthen the natural setting. The inhabitants are impressive: the <b>parti-coloured bat</b> and the <b>black woodpecker</b>, and — as on the Cartierheide — the <b>smooth snake</b>, its monitoring runs lying here too; further roe deer, rabbit, hare and of late ever more <b>wild boar</b>. By the old <b>sand trap</b> in Bladel a <b>sluice</b> was built to hold the water high. And in the region’s tales this is the realm of the <b>Gnomes of Kyrië</b>: the farmer who could no longer cope moved to the Kroonvense Heide, where <b>Gnome King Kyrië</b> walked about seeking healing herbs for the sick <b>Gnome Tree</b> — a tale trail that still has children searching here today.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (spring flora under the old pines), Jun–Sep (dragonflies and insects), Sep–Nov (fungi in the reserve)<br>\n    <b>Best time of day:</b> Morning — light in the 1882 pine rows.',
 'why': ['The <b>Scots pines of 1882</b> in the forest reserve.', 'The <b>508 ha</b> as the heart of Boswachterij De Kempen.', 'The <b>smooth snake</b> and black woodpecker as inhabitants.', 'The <b>Gnomes of Kyrië</b> as tale world.', 'The <b>sluice by the sand trap</b> as water keeper.'],
 'phen': ['<span class="months">Mar–May</span> 🌼 <b>May lily and Solomon’s seal</b> in the reserve.', '<span class="months">Apr–Jun</span> 🎶 <b>Woodpeckers</b> in the old stands.', '<span class="months">Jun–Sep</span> 🐉 <b>Dragonflies</b> at the wet spots.', '<span class="months">Sep–Nov</span> 🍄 <b>Fungi</b> under the pines.'],
 'wild': ['🌲 Pines of 1882', '🐍 Smooth snake', '🦇 Parti-coloured bat', '🧙 Gnomes of Kyrië', '💧 Sluice and sand trap'],
 'trail': ['Start at <b>De Pals</b> and walk into the <b>forest reserve</b>.', 'Follow the <b>marker-post routes</b> of Staatsbosbeheer.', 'Combine with <b>Ten Vorsel</b> (2359) and the <b>Cartierheide</b> (2362).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Post routes 3–10 km · 🅿️ De Pals (Staatsbosbeheer)'
}))

C.append(mk.card(2361, 'Gemeentebossen Reusel', {
 'tags': ['Noord-Brabant · rond Reusel: Peelse Heide in het zuiden, Turnhoutse Heide in het midden, Wellenseindse Heide in het noorden (gem. Reusel-De Mierden)', '± 1.000 ha bos en natuur in gemeentebezit · ontstaan bij de heideontginning begin twintigste eeuw; belangrijk infiltratiegebied voor het beekdal van de Reusel; het Panneven is de bijzondere parel met veenpluis, zonnedauw en moeraswolfsklauw; vijf spechtsoorten, boomleeuwerik en geelgors — de bossen grenzen aan Natura 2000 Kempenland-West maar horen er niet bij', 'list 88 · no. 33'],
 'loc': '📍 Gemeentebossen Reusel — start bij het dorp Reusel of bij de Panneven-paden; combineer met de Turnhoutse Heide (kaart 2330), Wellenseindse Heide (kaart 2329) en het Dal van de Reusel (kaart 2331)',
 'desc': 'De gemeente <b>Reusel-De Mierden</b> is met <b>± 1.000 hectare</b> bos en natuur één van de bosrijkste gemeenten van Brabant: drie grote complexen — de <b>Peelse Heide</b> in het zuiden, de <b>Turnhoutse Heide</b> in het midden en de <b>Wellenseindse Heide</b> in het noorden — die samen de groene rug van de gemeente vormen. De bossen ontstonden bij de <b>heideontginning van begin twintigste eeuw</b>: een <b>regelmatig padenpatroon</b> verraadt nog altijd de grootschalige, rationele aanpak van toen. Het bos staat op arme, droge gronden en is van nature <b>soortenarm</b> — maar de natuurterreinen die erin bewaard bleven zijn des te bijzonderder, en de gemeentebossen doen bovendien dienst als <b>infiltratiegebied voor het water dat het beekdal van de Reusel voedt</b>. De parel is het <b>Panneven</b>: een vencomplex waar bij de vennen <b>veenpluis, zonnedauw en moeraswolfsklauw</b> groeien. In de bossen leven <b>vijf soorten spechten</b>, van de <b>kleine bonte</b> tot de <b>zwarte specht</b>; op de heidevelden zingen <b>boomleeuwerik</b>, <b>roodborsttapuit</b> en <b>geelgors</b>. Curieus genoeg liggen de bossen <b>vlak tegen Natura 2000 Kempenland-West</b> aan (ter hoogte van bungalowpark Hertenwei) — maar ze maken er <b>geen deel van uit</b>: het is groen van eigen bodem, gevoerd door eigen beheer. Wie de drie complexen verbindt, wandelt van de Belgische grens tot aan de Reusel — door het bos dat een hele gemeente draagt.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Apr–jun</b> (spechten en heidevogels), jul–sep (venflora bij het Panneven), sep–nov (herfst in de dennen)<br>\n    <b>Beste tijd van de dag:</b> Vroege ochtend — spechten drummen.',
 'why': ['De <b>± 1.000 ha</b> gemeentebezit als unicum.', 'Het <b>Panneven</b> met veenpluis en zonnedauw.', 'De <b>vijf spechtsoorten</b>.', 'De <b>infiltratierol</b> voor het Reuseldal.', 'De <b>drie complexen</b> Peelse-Turnhoutse-Wellenseindse.'],
 'phen': ['<span class="months">Mrt–mei</span> 🪶 <b>Spechten</b> drummen in de bossen.', '<span class="months">Apr–jun</span> 🎶 <b>Boomleeuwerik en geelgors</b> op de heide.', '<span class="months">Jul–sep</span> 💜 <b>Venflora</b> bij het Panneven.', '<span class="months">Sep–nov</span> 🍂 <b>Herfst</b> in de dennenrijen.'],
 'wild': ['🏘️ Gemeentebezit', '💧 Panneven', '🪶 5 spechtsoorten', '💦 Infiltratiegebied', '🌲 Drie complexen'],
 'trail': ['Verbind de <b>Peelse</b>, <b>Turnhoutse</b> en <b>Wellenseindse Heide</b> in één tocht.', 'Zoek de <b>vennen</b> van het Panneven.', 'Combineer met het <b>Dal van de Reusel</b> (2331).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Routetjes 4–15 km · 🅿️ Reusel'
}, {
 'tags': ['North Brabant · around Reusel: Peelse Heide in the south, Turnhoutse Heide in the middle, Wellenseindse Heide in the north (gem. Reusel-De Mierden)', '± 1,000 ha of woodland and nature in municipal ownership · arising from the heath reclamation of the early twentieth century; key infiltration area for the Reusel valley; the Panneven is the special pearl with bog cotton, sundew and clubmoss; five woodpecker species, wood lark and yellowhammer — the woods border Natura 2000 Kempenland-West but are not part of it', 'list 88 · no. 33'],
 'loc': '📍 Gemeentebossen Reusel — start at the village of Reusel or by the Panneven paths; combine with the Turnhoutse Heide (card 2330), Wellenseindse Heide (card 2329) and the Dal van de Reusel (card 2331)',
 'desc': 'The municipality of <b>Reusel-De Mierden</b>, with <b>± 1,000 hectares</b> of woodland and nature, is one of Brabant’s most wooded municipalities: three great complexes — the <b>Peelse Heide</b> in the south, the <b>Turnhoutse Heide</b> in the middle and the <b>Wellenseindse Heide</b> in the north — together forming the municipality’s green backbone. The woods arose from the <b>heath reclamation of the early twentieth century</b>: a <b>regular path pattern</b> still betrays the large-scale, rational approach of the day. The wood stands on poor, dry soils and is by nature <b>species-poor</b> — but the nature terrains preserved within it are all the more special, and the municipal woods moreover serve as an <b>infiltration area for the water feeding the Reusel valley</b>. The pearl is the <b>Panneven</b>: a fen complex where <b>bog cotton, sundew and clubmoss</b> grow by the pools. The woods hold <b>five species of woodpecker</b>, from the <b>lesser spotted</b> to the <b>black woodpecker</b>; on the heath fields <b>wood lark</b>, <b>stonechat</b> and <b>yellowhammer</b> sing. Curiously the woods lie <b>right against Natura 2000 Kempenland-West</b> (by the Hertenwei bungalow park) — but they are <b>not part of it</b>: this is green of the municipality’s own soil, run by its own management. Link the three complexes and you walk from the Belgian border to the Reusel — through the wood that carries a whole municipality.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Apr–Jun</b> (woodpeckers and heath birds), Jul–Sep (fen flora at the Panneven), Sep–Nov (autumn in the pines)<br>\n    <b>Best time of day:</b> Early morning — woodpeckers drumming.',
 'why': ['The <b>± 1,000 ha</b> of municipal ownership as a rarity.', 'The <b>Panneven</b> with bog cotton and sundew.', 'The <b>five woodpecker species</b>.', 'The <b>infiltration role</b> for the Reusel valley.', 'The <b>three complexes</b> Peelse-Turnhoutse-Wellenseindse.'],
 'phen': ['<span class="months">Mar–May</span> 🪶 <b>Woodpeckers</b> drumming in the woods.', '<span class="months">Apr–Jun</span> 🎶 <b>Wood lark and yellowhammer</b> on the heath.', '<span class="months">Jul–Sep</span> 💜 <b>Fen flora</b> at the Panneven.', '<span class="months">Sep–Nov</span> 🍂 <b>Autumn</b> in the pine rows.'],
 'wild': ['🏘️ Municipal property', '💧 Panneven', '🪶 5 woodpecker species', '💦 Infiltration area', '🌲 Three complexes'],
 'trail': ['Link the <b>Peelse</b>, <b>Turnhoutse</b> and <b>Wellenseindse Heide</b> in one walk.', 'Seek the <b>Panneven fens</b>.', 'Combine with the <b>Dal van de Reusel</b> (2331).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Routes 4–15 km · 🅿️ Reusel'
}))

C.append(mk.card(2362, 'Cartierheide', {
 'tags': ['Noord-Brabant · tussen Eersel en de Belgische grens, ten zuiden van Weebosch (gem. Eersel/Bladel)', '172 ha heide- en bosgebied in Boswachterij De Kempen · ontkomen aan de ontginning dankzij baron de Cartier de Marchiennes (jachtterrein vanaf 1863) en in 1932 door zoon Emile aan Natuurmonumenten geschonken, beheerd door Staatsbosbeheer; het Dalems Stroompje (bovenloop 1994 hersteld), natte heide, berkenbroek en gagelstruweel; ronde zonnedauw, klokjesgentiaan, gladde slang, heikikker; blauwborst, klapekster en kruisbek', 'list 88 · no. 35'],
 'loc': '📍 Cartierheide, ten zuiden van Eersel — start bij Natuurpoort TerSpegelt (Postelseweg 88), de Trimbaan Eersel of parkeerplaats Postelseweg/Bredasebaan; boswachterspad 7,4 km; combineer met De Palts (kaart 2360) en de bossen van Eersel (kaart 2364)',
 'desc': 'In de driehoek <b>Weebosch–Eersel–Postel</b>, drie kilometer van de Belgische grens, ligt een heide die de grote ontginning van de Kempen nooit meemaakte: de <b>Cartierheide</b>, <b>172 hectare</b> midden in de bossen van Boswachterij De Kempen. De reden is aristocratisch: jonkheer <b>Emile de Cartier de Marchiennes</b> kocht in <b>1863</b> het ernaast gelegen goed <b>Duizels Hof</b> en gebruikte de heide als <b>jachtterrein</b> — en waar de baron jaagde, werd niet ontgonnen. Zijn zoon, ook <b>Emile</b>, schonk het gebied in <b>1932</b> aan <b>Natuurmonumenten</b>; vandaag beheert <b>Staatsbosbeheer</b> het met plaggen, maaien en begrazing. Rond <b>1950</b> werd de Cartierheide als natuurgebied aangewezen vanwege het <b>typisch Kempische landschap</b>. Dwars door het gebied loopt het <b>Dalems Stroompje</b> — de bovenloop die de Groote Beerze voedt en in <b>1994</b> werd hersteld — en eromheen liggen <b>natte heiden, berkenbroekbos en gagelstruweel</b>. De flora is klassiek Kempisch: <b>ronde zonnedauw</b>, <b>klokjesgentiaan</b>, struik- en dopheide; de fauna telt <b>gladde slang</b> (er wordt door RAVON-vrijwilligers gemonitor), <b>levendbarende hagedis</b>, <b>hazelworm</b> en <b>heikikker</b>. Wie goed zoekt vindt <b>blauwborst</b>, <b>tapuit</b>, <b>klapekster</b>, <b>kruisbek</b> en zelfs <b>kokmeeuw</b>. De streek vergeet bovendien haar <b>smokkelaars</b> niet: de oude smokkelpaden tussen Reusel, Eersel en Bergeijk starten hier, met drie Natuurpoorten (TerSpegelt, De Negende Zaeligheyt, De Brandtoren) als poortwachters. Het <b>boswachterspad</b> van 7,4 km leidt langs heide, vennen en het stroompje — met houten vlonderpaden over de natte stukken.',
 'meta': '<b>Beste seizoen &amp; piekmaanden:</b> <b>Jul–sep</b> (hei in bloei, reptielen actief), mrt–mei (gentianen en heikikkers), okt–mrt (winterse heidestilte)<br>\n    <b>Beste tijd van de dag:</b> Ochtend — dauw en vogelzang op de hei.',
 'why': ['De <b>barons-geschiedenis</b> die de hei redde (1863/1932).', 'Het <b>Dalems Stroompje</b> met het herstel van 1994.', 'De <b>gladde slang</b> als troeteldier van RAVON.', 'De <b>smokkelpaden</b> van weleer.', 'Het <b>boswachterspad</b> over vlonder en hei.'],
 'phen': ['<span class="months">Mrt–mei</span> 🌸 <b>Klokjesgentiaan</b> en zonnedauw.', '<span class="months">Mrt–jun</span> 🐸 <b>Heikikkers</b> in de plassen.', '<span class="months">Jul–sep</span> 💜 <b>Struik- en dophei</b> in volle bloei.', '<span class="months">Apr–sep</span> 🐍 <b>Gladde slang</b> zonnend op de plaggen.'],
 'wild': ['🦎 Gladde slang', '💧 Dalems Stroompje', '👑 Baron de Cartier', '🚶 Smokkelpaden', '🌸 Zonnedauw en gentiaan'],
 'trail': ['Loop het <b>boswachterspad</b> (7,4 km) langs hei en vlonderpaden.', 'Start bij <b>Natuurpoort TerSpegelt</b> of de Trimbaan Eersel.', 'Combineer met <b>De Palts</b> (2360) en de <b>Laarven</b> (2364).'],
 'foot': '🐕 Honden aangelijnd · 💶 Gratis · 🚶 Boswachterspad 7,4 km + paaltjesroutes · 🅿️ TerSpegelt / Postelseweg'
}, {
 'tags': ['North Brabant · between Eersel and the Belgian border, south of Weebosch (gem. Eersel/Bladel)', '172-ha heath and woodland area in Boswachterij De Kempen · escaped reclamation thanks to Baron de Cartier de Marchiennes (hunting ground from 1863) and donated to Natuurmonumenten by his son Emile in 1932, managed by Staatsbosbeheer; the Dalems Stroompje (upper course restored 1994), wet heath, birch bog and bog-myrtle scrub; round-leaved sundew, marsh gentian, smooth snake, moor frog; bluethroat, great grey shrike and crossbill', 'list 88 · no. 35'],
 'loc': '📍 Cartierheide, south of Eersel — start at Natuurpoort TerSpegelt (Postelseweg 88), the Trimbaan Eersel or the Postelseweg/Bredasebaan car park; forester’s path 7.4 km; combine with De Palts (card 2360) and the woods of Eersel (card 2364)',
 'desc': 'In the triangle <b>Weebosch–Eersel–Postel</b>, three kilometres from the Belgian border, lies a heath that escaped the reclamation that overtook the whole Campine: the <b>Cartierheide</b>, <b>172 hectares</b> amid the woods of Boswachterij De Kempen. The reason is aristocratic: Baron <b>Emile de Cartier de Marchiennes</b> bought the neighbouring <b>Duizels Hof</b> estate in <b>1863</b> and used the heath as his <b>hunting ground</b> — and where the baron hunted, nothing was reclaimed. His son, also <b>Emile</b>, donated the area to <b>Natuurmonumenten</b> in <b>1932</b>; today <b>Staatsbosbeheer</b> manages it with sod-cutting, mowing and grazing. Around <b>1950</b> the Cartierheide was designated a nature reserve for its <b>typically Campine landscape</b>. Through the area runs the <b>Dalems Stroompje</b> — the upper course feeding the Groote Beerze, restored in <b>1994</b> — and around it lie <b>wet heaths, birch bog woodland and bog-myrtle scrub</b>. The flora is classic Campine: <b>round-leaved sundew</b>, <b>marsh gentian</b>, ling and cross-leaved heath; the fauna counts the <b>smooth snake</b> (monitored by RAVON volunteers), the <b>viviparous lizard</b>, the <b>slow worm</b> and the <b>moor frog</b>. Look well and you find <b>bluethroat</b>, <b>stonechat</b>, <b>great grey shrike</b>, <b>crossbill</b> and even <b>Mediterranean gull</b>. The region does not forget its <b>smugglers</b> either: the old smuggling paths between Reusel, Eersel and Bergeijk start here, with three Nature Gates (TerSpegelt, De Negende Zaeligheyt, De Brandtoren) as gatekeepers. The <b>forester’s path</b> of 7.4 km leads along heath, fens and the streamlet — with wooden boardwalks over the wet stretches.',
 'meta': '<b>Best season &amp; peak months:</b> <b>Jul–Sep</b> (heath in flower, reptiles active), Mar–May (gentians and moor frogs), Oct–Mar (wintry heath silence)<br>\n    <b>Best time of day:</b> Morning — dew and birdsong on the heath.',
 'why': ['The <b>baron’s history</b> that saved the heath (1863/1932).', 'The <b>Dalems Stroompje</b> with its 1994 restoration.', 'The <b>smooth snake</b> as RAVON’s darling.', 'The <b>smuggling paths</b> of old.', 'The <b>forester’s path</b> over boardwalk and heath.'],
 'phen': ['<span class="months">Mar–May</span> 🌸 <b>Marsh gentian</b> and sundew.', '<span class="months">Mar–Jun</span> 🐸 <b>Moor frogs</b> in the pools.', '<span class="months">Jul–Sep</span> 💜 <b>Ling and cross-leaved heath</b> in full flower.', '<span class="months">Apr–Sep</span> 🐍 <b>Smooth snake</b> basking on the sods.'],
 'wild': ['🦎 Smooth snake', '💧 Dalems Stroompje', '👑 Baron de Cartier', '🚶 Smuggling paths', '🌸 Sundew and gentian'],
 'trail': ['Walk the <b>forester’s path</b> (7.4 km) along heath and boardwalks.', 'Start at <b>Natuurpoort TerSpegelt</b> or the Trimbaan Eersel.', 'Combine with <b>De Palts</b> (2360) and the <b>Laarven</b> (2364).'],
 'foot': '🐕 Dogs on lead · 💶 Free · 🚶 Forester’s path 7.4 km + post routes · 🅿️ TerSpegelt / Postelseweg'
}))

mk.insert(C, chunk='reserves-2335-2434.json')
mk.progress(2362)
mk.check()
