# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Hondswaard tot Hollanderbroek: Waaldijken, Rijnoevers en de stille Betuwe (2055–2074)</h3>
        <p class="post-meta">List 36 · Bommelerwaard, Heuvelrug-rand bij Rhenen, de Renkum–Wageningen–Arnhem-gordel en de Overbetuwe: Vuren, Brakel, Gameren, Poederoijen, Giessen, Rhenen, Wageningen, Heelsum, Bennekom, Doorwerth, Oosterbeek, Arnhem, Huissen, Hemmen, Valburg en Elst</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.074 van de 2.373 boekgebieden (87,4%)</b>. De reis begint in de Bommelerwaard, waar de Waal al richting Biesbosch ruist: de <b>Hondswaard</b> bij Vuren met het torenfort van 1845 op de hoge oever, het dubbeltje natuur van <b>Brakel</b> (Benedenwaarden met meestromende geul én de oude Boezem), en de <b>Gamerense Waard</b> — schoolvoorbeeld van rivierdynamiek met drie nevengeulen, waarvan één permanent meestroomt: iets wat langs de Waal alleen bij Beneden-Leeuwen, Opijnen en Gameren bestaat. De <b>Waarden van Poederoijen</b> vormen het waterland rond Slot Loevestein (Natura 2000 nr. 71), en <b>Fort Giessen</b> (1879) sluit de Nieuwe Hollandse Waterlinie aan de Altenase kant af tussen wilgen en grasland.</p>
        <p>Dan de grote sprong naar de Rijn. De <b>Stadsbossen van Rhenen</b> met de eeuwenoude <b>Lijstereng</b> vormen het bosfront van de Heuvelrug, en vervolgens volgt de hele linker-rivoier van de Nederrijn: de <b>Wageningse Uiterwaarden</b> (Bovenpolder, Natura 2000 <b>Rijntakken</b>), <b>Oranje Nassau’s Oord</b> met zijn koninklijke paleis van Willem III en het sanatorium van Kuipers, de <b>Jufferswaard</b> (al in 1372 als ‘Jonckfrouwenweert’ in leen gegeven), het villapark <b>Wilhelminapark</b> van Heelsum (1887), de stille <b>Cardanusgronden</b>, het waterkasteel <b>Doorwerth</b> uit de 13e eeuw, het oorlogsgetroffen landgoed <b>Duno en Jagershuis</b> (Market Garden, september 1944), de <b>Valkeniersbossen</b> van 1916 en tenslotte <b>Mariëndaal</b> met de Groene Bedstee — de beroemdste berceau van Nederland, ruim 300 meter haagbeuken uit ± 1856.</p>
        <p>De laatste vijf kaarten kruisen de Rijn de Betuwe in: <b>Meinerswijk</b>, de wilde uiterwaard tegenover het centrum van Arnhem vol beverburchten en Romeinse sporen (opnieuw Natura 2000 Rijntakken), <b>Huissense- en Roswaard</b> met een middeleeuwse hoefijzermeander en het Pannerdens Kanaal van 1701–1707, het ± 700 hectare grote landgoed <b>Hemmen</b> met kasteelruïne en Engels park, het open stroomruglandschap van <b>Lakemond</b> — het ‘insectendorp’ achter de Rijndijk — en het natte <b>Hollanderbroek</b> tussen Elst en Driel met zijn twee rondjes (Homoet en Kom) en het Icarusblauwtje. Volgende stop: het Rijk van Nijmegen.</p>
      </div>
      <div class="c-en">
        <h3>From Hondswaard to Hollanderbroek: Waal dikes, Rhine banks and the quiet Betuwe (2055–2074)</h3>
        <p class="post-meta">List 36 · Bommelerwaard, Heuvelrug edge at Rhenen, the Renkum–Wageningen–Arnhem belt and the Overbetuwe: Vuren, Brakel, Gameren, Poederoijen, Giessen, Rhenen, Wageningen, Heelsum, Bennekom, Doorwerth, Oosterbeek, Arnhem, Huissen, Hemmen, Valburg and Elst</p>
        <p>Another twenty cards, and the guide now counts <b>2,074 of the 2,373 book sites (87.4%)</b>. The journey begins in the Bommelerwaard, where the Waal is already rushing towards the Biesbosch: the <b>Hondswaard</b> at Vuren with its 1845 tower fort on the high bank, the twin nature of <b>Brakel</b> (Benedenwaarden with a flowing side channel and the old Boezem marsh), and the <b>Gamerense Waard</b> — a textbook example of living river dynamics with three side channels, one of which flows with the river all year: something found along the Waal only at Beneden-Leeuwen, Opijnen and Gameren. The <b>Waarden van Poederoijen</b> form the waterland around Loevestein Castle (Natura 2000 no. 71), and <b>Fort Giessen</b> (1879) closes the New Dutch Waterline on the Altena side amid willows and grassland.</p>
        <p>Then the great leap to the Rhine. The <b>town woods of Rhenen</b> with the centuries-old <b>Lijstereng</b> form the wooded front of the Heuvelrug, after which the whole left bank of the Nederrijn follows: the <b>Wageningen floodplains</b> (Bovenpolder, Natura 2000 <b>Rijntakken</b>), <b>Oranje Nassau’s Oord</b> with King Willem III’s palace and Kuipers’ sanatorium, the <b>Jufferswaard</b> (granted as a fief called ‘Jonckfrouwenweert’ as early as 1372), the villa <b>Wilhelminapark</b> at Heelsum (1887), the quiet <b>Cardanusgronden</b>, the 13th-century water castle <b>Doorwerth</b>, the war-scarred estate of <b>Duno and Jagershuis</b> (Market Garden, September 1944), the <b>Valkeniersbossen</b> of 1916 and finally <b>Mariëndaal</b> with the Groene Bedstee — the Netherlands’ most famous berceau, over 300 metres of hornbeam from ± 1856.</p>
        <p>The last five cards cross the Rhine into the Betuwe: <b>Meinerswijk</b>, the wild floodplain opposite the centre of Arnhem, full of beaver lodges and Roman traces (again Natura 2000 Rijntakken), <b>Huissense- en Roswaard</b> with a medieval horseshoe meander and the Pannerdens Kanaal of 1701–1707, the ± 700-hectare estate of <b>Hemmen</b> with its castle ruin and English park, the open stream-ridge landscape of <b>Lakemond</b> — the ‘insect village’ behind the Rhine dike — and the wet <b>Hollanderbroek</b> between Elst and Driel with its two loops (Homoet and Kom) and the common blue butterfly. Next stop: the Rijk van Nijmegen.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
