# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Veghel tot de Mookerheide: Land van Cuijk en de stuwwalrand (2173–2192)</h3>
        <p class="post-meta">Lists 80–81 · De Coevering en Logtenburg bij Veghel, Herperduin en de wijstgronden van de Maashorst, Keent en het Raamdal in de Grave-vlakte, Mill en Langenboom, en de heuvelgordel van Mookerschans, Herrendal, Mookerheide en Rivierduintjes</p>
        <p>Twintig kaarten deze keer, en de gids telt nu <b>2.192 van de 2.373 boekgebieden (92,4%)</b>. De opvallende ontdekking van deze batch: vrijwel geheel list 78 (West-Brabant) en de eerste negentien nummers van list 79 bleken al gedekt door eerdere lijsten — kaarten 218 t/m 239 en 982 e.v. — zodat de nieuwe kaarten beginnen bij de kleine bosnamen van Veghel en dan opzuilen naar het noordoosten: het <b>Land van Cuijk</b>.</p>
        <p>Daar wachtte echte stof. <b>Herperduin</b> (± 400 ha, gemeente Oss) maakt landelijk nieuws met zijn rigoureuze omvorming van productiebos naar natuurbos — met Tauros-runderen, Exmoorpony’s, het Groot Ganzenven en kleine zonnedauw. De <b>Wijstgronden</b> bij Uden laten zien waarom: daar kwelt ijzerrijk water langs de <b>Peelrandbreuk</b> omhoog en kleurt de bodem “wijst”-grijsgroen — levende geologie op de rand van De Maashorst. In de Grave-vlakte liggen het struingebied <b>Keent</b> (Brabants Landschap, met het gedenkteken van het vliegveld van 1927 en vrij rondlopende kuddes) en het <b>Raamdal</b> met de Broekse Wielen achter de ringdijk van 1664. <b>Mill en Langenboom</b> vertelt de transformatie van heide via zand- en grindwinning naar zwemmeer — met haaientanden en mammoetfossielen als verrassing in de bodem.</p>
        <p>De laatste reeks is de stuwwalrand zelf: de <b>Mookerschans</b> (zeventiende-eeuws, met hele en halve bastions en een uitkijktoren), het droogdal <b>Herrendal</b>, de <b>Mookerheide</b> van Natuurmonumenten (slagveld van 1574 waar Lodewijk en Hendrik van Nassau sneuvelden; jachtslot van 1904, nachtzwaluw, Schotse Hooglanders en sinds 2019 een natuurbegraafplaats) en de ± 3 hectare <b>Rivierduintjes</b> bij Plasmolen — het kleinste pareltje van de batch. Als natuurlijk slot de <b>Oeffelter Meent</b>: Natura 2000-gebied nr. 141 (NL2003035, ± 118 ha), de meent van de Kruisheren sinds ± 1400, thans het noordelijkste deel van de Unesco-Maasheggen met stroomdalgraslanden, nachtegaal en een nieuw wetland. Volgende batch: de rest van list 81 en verder naar Zeeuws-Vlaanderen en West-Brabant.</p>
      </div>
      <div class="c-en">
        <h3>From Veghel to the Mookerheide: Land van Cuijk and the moraine edge (2173–2192)</h3>
        <p class="post-meta">Lists 80–81 · De Coevering and Logtenburg at Veghel, Herperduin and the wijst grounds of the Maashorst, Keent and the Raamdal in the Grave plain, Mill and Langenboom, and the hill belt of Mookerschans, Herrendal, Mookerheide and Rivierduintjes</p>
        <p>Twenty cards this time, and the guide now counts <b>2,192 of the 2,373 book sites (92.4%)</b>. The striking discovery of this batch: nearly all of list 78 (West Brabant) and the first nineteen numbers of list 79 proved already covered by earlier lists — cards 218 to 239 and 982 onward — so the new cards begin with the small wood names of Veghel and then climb northeast into the <b>Land van Cuijk</b>.</p>
        <p>Real material was waiting there. <b>Herperduin</b> (± 400 ha, municipality of Oss) makes national news with its rigorous conversion of production forest to wild wood — with Tauros cattle, Exmoor ponies, the Groot Ganzenven and round-leaved sundew. The <b>Wijstgronden</b> near Uden show why the region is so special: there iron-rich water seeps up along the <b>Peel-edge fault</b> and stains the soil “wijst” grey-green — living geology on the rim of De Maashorst. In the Grave plain lie the roaming area of <b>Keent</b> (Brabant Landscape Trust, with the memorial of the 1927 airfield and free-roaming herds) and the <b>Raamdal</b> with the Broekse Wielen behind the 1664 ring dike. <b>Mill and Langenboom</b> tells the transformation from heath via sand and gravel winning to swimming lake — with shark teeth and mammoth fossils as a surprise in the soil.</p>
        <p>The last run is the moraine edge itself: the <b>Mookerschans</b> (seventeenth-century, with full and half bastions and a watchtower), the dry valley of the <b>Herrendal</b>, the <b>Mookerheide</b> of the Netherlands Nature Trust (battlefield of 1574 where Louis and Henry of Nassau fell; a 1904 hunting lodge, nightjar, Highland cattle and since 2019 a natural burial ground) and the ± 3 hectares of the <b>Rivierduintjes</b> at Plasmolen — the smallest jewel of the batch. Natural finale: the <b>Oeffelter Meent</b>, Natura 2000 site no. 141 (NL2003035, ± 118 ha), the common pasture of the Crutched Friars since ± 1400, now the northernmost part of the Unesco Maasheggen with stream-valley grasslands, nightingales and a new wetland. Next batch: the rest of list 81 and onward to Zeeuws-Vlaanderen and West Brabant.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #98 toegevoegd')
