# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Lievelderbroek tot De Zieppe: kwel, havezaten en Twentse landgoederen (1935–1954)</h3>
        <p class="post-meta">List 36 · Gelderland en Overijssel: Lievelde, Zieuwent, Groenlo, Winterswijk-Meddo, Boekelo, Enschede en Haaksbergen</p>
        <p>De reeks begint in het brongebied van de Lievelderbeek bij Lievelde. Het <b>Lievelderbroek</b> is het natte broekland tussen het <b>Lievelderveld</b> en de Koolmansdijk: kwelwater houdt de grond het hele jaar vochtig, en via de herstelde beek en de ecologische verbindingszone richting Korenburgerveen keren boomkikker en kamsalamander terug. Het SBB-terrein Lievelderveld voert de natuurherstelgeschiedenis: op ’t Grieze Veld werd eind vorige eeuw de rijke bovenlaag afgeschraapt, waarna het terrein samen met de Koolmansdijk en de Nijkampsheide binnen twee jaar 48 Rode-Lijstsoorten opleverde; wandelaars volgen er het ’t Griezeveldpad langs de Lievelder Schans uit 1627. <b>Mellinkmaat landschapselementen</b> blijkt op de moderne kaart de buurt “Verspreide huizen Mellinkmaat” tussen Zieuwent en Harreveld — een kampenlandschap van houtwallen en hagen, in de oude gids beschreven als een van de kleine natuurgebiedjes nabij Zieuwent. En de <b>Hallse Heide</b> bij Halle is een SBB-deelgebied waar de heide vooral als naam voortleeft: de 13 kilometer lange rondwandeling voert over kerkpaden langs de Veengoot naar Mariënvelde en terug via het Oude Schoolpad.</p>
        <p>Rond Groenlo en Winterswijk volgen bos en havezaten. Het <b>Reirinkbos</b> van Het Geldersch Landschap ligt deels op de circumvallatielinie van Groenlo: onder het elzenhakhout en de oude bosindicatoren sluimert het legerkamp van graaf Ernst Casimir uit 1627. Ten noorden van Winterswijk liggen drie verwante gebieden rond de Ratumse Beek: het <b>Bönnink</b> van Natuurmonumenten met herstelde beekloop, houtwallen, oude boomgaard en graanakkers vol korenbloemen; <b>Dottinkrade</b>, waar een voormalig productiebos van fijnspar en lariks wordt omgevormd tot natuurrijker loofbos met mispel, zoete kers en slanke sleutelbloem; en <b>Het Waliën</b> bij Huppel, de havezate uit 1570 waarvan sinds 1908 alleen de rijksmonumentale ruïne met schoorsteenfries rest — de naamgever van het beroemde Warnsveldse ’t Waliën.</p>
        <p>De Meddose hoek van Winterswijk levert een eigen verhaal op. Het <b>Bos te Meddo</b> is een SBNL-perceel van 4,9 hectare aan de Groenlose Slinge, in 1988 geschonken door Theodore Kraakman en rijk aan oude eiken van vóór de ruilverkaveling. <b>Gelderesch</b> is het scholtegoed met rijksmonumentale T-boerderij (1860) en spin- en weefhuis (1900), waar de routes Rondje Gelderesch en Het Meddose Veld starten. Het <b>Meddoscheveld</b> — het ooit meer dan 1.500 hectare grote Meddose Veld — werd in de twintigste eeuw ontgonnen tot open weide- en bouwland; veldnamen als Masterveld en Bonkeveen herinneren aan de heidetijd. De <b>Beurzerbeek</b> ten slotte is de herstelde bovenloop van de Slinge: in 1998–1999 werden oude beekarmen via een bypass verbonden, en ijsvogel, dodaars, geelgors en rosse vleermuis keerden terug. Ten westen daarvan ligt het <b>Vragenderveld</b> rond Vragender, waar de wandelroute langs de 15 meter hoge uitkijktoren over het levende hoogveen van het Vragenderveen voert.</p>
        <p>Dan springt de reeks de provinciegrens over naar Twente, rond Boekelo en Enschede. Het <b>Teesinkbos</b> is het bos van het voormalige landgoed Het Teesink van de familie Van Heek op de rand van de stuwwal — eeuwenoude bomen, een vijverpartij en jaarlijks het decor van Military Boekelo; de Rondje Boekelo-route voert erdoorheen en over landgoed <b>De Weele</b> (circa 45 hectare, villa uit 1912, haagbeuken- en meidoornhagen). <b>Het Rutbeek</b> aan de zuidkant van Enschede ontstond in de jaren zeventig uit zandwinning voor de snelwegen en wijken van de stad: nu een 120 hectare groot recreatie- en natuurpark met orchideeën, kranswieren, een populatie zandhagedis en de archeologische plek “Laag van Usselo”. De textielgeschiedenis bepaalt de laatste landgoederen: <b>Groot Brunink</b>, sinds 1341 bekend als Hof te Brunink en sinds 2013 deels beheerd door Landschap Overijssel, en <b>Smalenbroek</b>, waar de familie Ter Kuile rond 1900 een park met vijver door Pieter Wattez liet ontwerpen. Het <b>Aamsveen</b> ten slotte is het Natura 2000-hoogveen op de Duitse grens: een van de laatste levende hoogveengebieden van Nederland, waar Landschap Overijssel en Duitse partners met dammen en stuwen nieuw veenmos laten groeien. En <b>De Zieppe</b> bij Haaksbergen is geen natuur maar monument: de boerderij uit 1915 van textielfabrikant H. van Heek, met een unieke constructie van gewapend beton en spreuken over de Eerste Wereldoorlog in de balken — een bijzondere stopplaats langs de weg.</p>
      </div>
      <div class="c-en">
        <h3>From the Lievelderbroek to De Zieppe: seepage, manor houses and Twente estates (1935–1954)</h3>
        <p class="post-meta">List 36 · Gelderland and Overijssel: Lievelde, Zieuwent, Groenlo, Winterswijk-Meddo, Boekelo, Enschede and Haaksbergen</p>
        <p>The series begins in the headwater area of the Lievelderbeek near Lievelde. The <b>Lievelderbroek</b> is the wet fenland between the <b>Lievelderveld</b> and the Koolmansdijk: seepage water keeps the ground moist all year, and via the restored brook and the ecological corridor towards the Korenburgerveen the tree frog and the great crested newt are returning. The Staatsbosbeheer terrain of the Lievelderveld tells the story of nature restoration: on ’t Grieze Veld the rich top layer was scraped off at the end of the last century, after which the terrain, together with the Koolmansdijk and the Nijkampsheide, yielded 48 Red List species within two years; walkers follow the ’t Griezeveldpad past the Lievelder Schans from 1627. <b>Mellinkmaat landscape elements</b> turns out to be the “Verspreide huizen Mellinkmaat” neighbourhood between Zieuwent and Harreveld on the modern map — an enclosed-field landscape of hedgerows and hedges, described in the old guide as one of the small nature areas near Zieuwent. And the <b>Hallse Heide</b> near Halle is a Staatsbosbeheer sub-area where the heath lives on mainly as a name: the 13-kilometre circuit leads over church paths along the Veengoot to Mariënvelde and back via the Oude Schoolpad.</p>
        <p>Around Groenlo and Winterswijk follow woodland and manor houses. The <b>Reirinkbos</b> of Het Geldersch Landschap lies partly on the circumvallation line of Groenlo: under the alder coppice and the old-wood indicators slumbers the army camp of Count Ernst Casimir from 1627. North of Winterswijk lie three related areas around the Ratumse Beek: the <b>Bönnink</b> of Natuurmonumenten with its restored brook course, hedgerows, old orchard and cornfields full of cornflowers; <b>Dottinkrade</b>, where a former production forest of spruce and larch is being transformed into a more natural broadleaf wood with medlar, sweet cherry and oxlip; and <b>Het Waliën</b> near Huppel, the manor from 1570 of which only the nationally listed ruin with chimney frieze remains since 1908 — the namesake of the famous ’t Waliën near Warnsveld.</p>
        <p>The Meddo corner of Winterswijk offers a story of its own. The <b>Bos te Meddo</b> is an SBNL parcel of 4.9 hectares on the Groenlose Slinge, donated in 1988 by Theodore Kraakman and rich in old oaks from before the land consolidation. <b>Gelderesch</b> is the scholte estate with its nationally listed T-farmhouse (1860) and spinning and weaving house (1900), where the Rondje Gelderesch and Het Meddose Veld routes start. The <b>Meddoscheveld</b> — the once more than 1,500-hectare Meddose Veld — was reclaimed in the twentieth century into open pasture and arable land; field names such as Masterveld and Bonkeveen recall the heath era. The <b>Beurzerbeek</b>, finally, is the restored upper course of the Slinge: in 1998–1999 old brook arms were connected by a bypass, and kingfisher, little grebe, yellowhammer and greater noctule bat returned. West of it lies the <b>Vragenderveld</b> around Vragender, where the walking route passes the 15-metre-high observation tower over the living raised bog of the Vragenderveen.</p>
        <p>Then the series jumps across the provincial border into Twente, around Boekelo and Enschede. The <b>Teesinkbos</b> is the wood of the former Het Teesink estate of the Van Heek family on the edge of the ice-age ridge — centuries-old trees, a pond layout and each year the setting of Military Boekelo; the Rondje Boekelo route leads through it and over the <b>De Weele</b> estate (about 45 hectares, villa from 1912, hornbeam and hawthorn hedges). <b>Het Rutbeek</b> on the south side of Enschede arose in the 1970s from sand extraction for the city’s motorways and neighbourhoods: now a 120-hectare recreation and nature park with orchids, stoneworts, a sand lizard population and the archaeological site “Laag van Usselo”. The textile history shapes the last estates: <b>Groot Brunink</b>, known since 1341 as the Hof te Brunink and partly managed by Landschap Overijssel since 2013, and <b>Smalenbroek</b>, where the Ter Kuile family had a park with pond designed by Pieter Wattez around 1900. The <b>Aamsveen</b>, finally, is the Natura 2000 raised bog on the German border: one of the last living raised-bog areas of the Netherlands, where Landschap Overijssel and German partners let new sphagnum moss grow with dams and weirs. And <b>De Zieppe</b> near Haaksbergen is not nature but monument: the farm from 1915 of textile manufacturer H. van Heek, with a unique reinforced-concrete frame and mottoes about the First World War in its beams — a special stop along the road.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
