# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van het Soerense Broek naar de Vordense landgoederen (1855–1874)</h3>
        <p class="post-meta">List 36 · Gelderland: Dieren, Leuvenheim, Brummen, Zutphen, Eefde, Almen en Vorden</p>
        <p>Deze reeks begint in de IJsselvallei bij <b>Dieren</b>. Het <b>Soerense Broek</b> van Natuurmonumenten is een vochtig beekdal- en moerasgebied langs de Soerense Beek tussen Dieren, Spankeren en Leuvenheim, dat sinds 2002 is hersteld en wordt bekeken vanaf de Broekdijk — het terrein zelf mag niet worden betreden. Ten westen van Leuvenheim liggen de bospercelen van <b>De Kievit en Denk en Werk</b>: een naam uit de gids die in oude registers en het onderzoek van Wageningen University &amp; Research terugkeert als rust- en foerageergebied van edelherten. Daarachter ligt het landgoed <b>Den Bosch</b> van de Stilte-Stichting: ruim 238 hectare, waarvan zo’n 126 hectare bos en natuur, in de landgoederengordel Den Bosch–De Rees–De Wildbaan rond Leuvenheim. Dan de IJssel: <b>Bronkhorst</b>, sinds 1482 het kleinste stadje van Nederland, ligt beschut tegen de Bronkhorsterwaarden met hun weidevogels, en verder stroomafwaarts liggen de kronkelwaarden van <b>Cortenoever</b> tussen Brummen en Zutphen, waar Staatsbosbeheer de rivier weer ruimte gaf en de struinpaden tussen 15 maart en 15 juli gesloten zijn voor de kwartelkoning. Ten slotte <b>Bronsbergen</b> onder Zutphen: uiterwaarden, Fort Bronsbergen als startpunt van het Ommetje Bronsbergen en het Bronsbergermeer.</p>
        <p>Daarna verhuist de reeks naar de landgoederen op de rand van Eefde en Warnsveld. <b>Den Dam</b> is een wit achttiende-eeuws buitenhuis aan de Damlaan, vlak bij de sluizen van het Twentekanaal, nog altijd in handen van de familie Bosch van Rosenthal. <b>De Voorst</b> aan de Binnenweg 2 is het classicistische buitenhuis dat Arnold Joost van Keppel in 1695–1697 liet bouwen door de bouwmeesters van Het Loo; het park kreeg later een ontwerp van Leonard Springer, en rondwandelingen van 4 en 7 kilometer zijn opengesteld. <b>’t Velde en het Veldese Bos</b> vormen de havezate met landgoedbos ten noorden van de Berkel, waar het huis dienst doet als politieacademie en de bossen vrij wandelbaar zijn. En <b>Oud Berkenroede</b>? Dat kleine particuliere landgoed uit 1961 ten zuidwesten van Almen staat in de NSW-registers als ‘Aiking-Oud Berkenroede’ en ligt tussen de hekpijlers van de landgoedwandeling Eefde–Almen.</p>
        <p>De laatste tien kaarten liggen in de Graafschap tussen Almen, Vorden en Lochem. <b>De Ehze</b> is het GLK-landgoed aan de Hogenkampsweg waar het parkbos uitnodigt tot wandelen en de ijsvogel en rosse vleermuis zich thuis voelen. Even verderop ligt <b>Velhorst</b>, het landgoed van Natuurmonumenten met rododendrons, het kwetsbare Kienveen en de 16 kilometer lange Wandelroute Velhorst, die doorloopt naar <b>’t Waliën</b> — met zijn landhuis uit 1915 en de Springer-tuin — en het <b>Grote Veld</b>: ooit een zo groot heideveld dat je de torens van Warnsveld, Almen en Vorden kon zien, nu een circa 2.300 hectare groot bos- en heidegebied met de schaapskudde De Belhamel. Daartussen registreert de gids <b>Lacerta</b>, een opengesteld NSW-landgoed in Warnsveld zonder eigen bezoekerspagina. Rond Vorden liggen <b>Den Bramel</b> (de veertiende-eeuwse buitenplaats rond een privé kasteel), het parkbos <b>’t Enzerinck</b> met het gerestaureerde Grootvaders Huisje, het waterwingebied <b>Dennenwater</b> — ook wel Galgengoor — in de zuidoostpunt van het Grote Veld, het <b>Pinetum De Belten</b> met duizend genummerde coniferen en ten slotte <b>Oude Voorde</b>, een naam uit de gids die in moderne wandelgidsen als ‘Oud Voorden’ voortleeft. Van beekdal tot kronkelwaard, van havezate tot pinetum: de overgang van de IJsselvallei naar de Achterhoek in twintig hoofdstukken.</p>
      </div>
      <div class="c-en">
        <h3>From the Soerense Broek to the estates of Vorden (1855–1874)</h3>
        <p class="post-meta">List 36 · Gelderland: Dieren, Leuvenheim, Brummen, Zutphen, Eefde, Almen and Vorden</p>
        <p>This series begins in the IJssel valley near <b>Dieren</b>. The <b>Soerense Broek</b> of Natuurmonumenten is a wet brook-valley and marsh area along the Soerense Beek between Dieren, Spankeren and Leuvenheim, restored since 2002 and viewed from the Broekdijk — the terrain itself may not be entered. West of Leuvenheim lie the forest parcels of <b>De Kievit en Denk en Werk</b>: a name from the guide that recurs in old registers and in the research of Wageningen University &amp; Research as a resting and feeding area for red deer. Behind it lies the <b>Den Bosch</b> estate of the Stilte-Stichting: more than 238 hectares, of which some 126 hectares of forest and nature, in the estate belt of Den Bosch–De Rees–De Wildbaan around Leuvenheim. Then the IJssel: <b>Bronkhorst</b>, the smallest town of the Netherlands since 1482, lies sheltered against the Bronkhorsterwaarden floodplains with their meadow birds, and further downstream lie the winding floodplains of <b>Cortenoever</b> between Brummen and Zutphen, where Staatsbosbeheer gave the river room again and the scrambling paths are closed between 15 March and 15 July for the corncrake. Finally <b>Bronsbergen</b> below Zutphen: floodplains, Fort Bronsbergen as the starting point of the Ommetje Bronsbergen and the Bronsbergermeer lake.</p>
        <p>The series then moves to the estates on the edge of Eefde and Warnsveld. <b>Den Dam</b> is a white eighteenth-century country house on the Damlaan, close to the locks of the Twentekanaal, still owned by the Bosch van Rosenthal family. <b>De Voorst</b> on Binnenweg 2 is the classical country house that Arnold Joost van Keppel had built in 1695–1697 by the master builders of Het Loo; the park later received a design by Leonard Springer, and circular walks of 4 and 7 kilometres are open. <b>’t Velde and the Veldese Bos</b> form the manor with estate wood north of the Berkel, where the house serves as a police academy and the woods are freely walkable. And <b>Oud Berkenroede</b>? That small private estate from 1961 southwest of Almen is registered in the NSW lists as ‘Aiking-Oud Berkenroede’ and lies between the gate piers of the Eefde–Almen estate walk.</p>
        <p>The last ten cards lie in the Graafschap between Almen, Vorden and Lochem. <b>De Ehze</b> is the Geldersch Landschap estate on the Hogenkampsweg where the park wood invites you to walk and the kingfisher and noctule bat feel at home. A little further on lies <b>Velhorst</b>, the Natuurmonumenten estate with rhododendrons, the vulnerable Kienveen and the 16-kilometre Velhorst walking route, which continues to <b>’t Waliën</b> — with its country house from 1915 and the Springer garden — and the <b>Grote Veld</b>: once a heath field so large that you could see the towers of Warnsveld, Almen and Vorden, now a forest and heath area of some 2,300 hectares with the De Belhamel sheep flock. Between them the guide records <b>Lacerta</b>, an opened NSW estate in Warnsveld without a visitor page of its own. Around Vorden lie <b>Den Bramel</b> (the fourteenth-century country estate around a private castle), the park wood of <b>’t Enzerinck</b> with the restored Grootvaders Huisje, the water catchment area <b>Dennenwater</b> — also called Galgengoor — in the southeastern corner of the Grote Veld, the <b>Pinetum De Belten</b> with a thousand numbered conifers, and finally <b>Oude Voorde</b>, a name from the guide that lives on in modern walking guides as ‘Oud Voorden’. From brook valley to winding floodplain, from manor to pinetum: the transition from the IJssel valley to the Achterhoek in twenty chapters.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
