# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>De laatste 21: van Oostelbeers naar de Keersop — de gids is af</h3>
        <p class="post-meta">List 88 slot · Oostelbeerse Heide, ’s Heerenvijvers, Oirschotse Heide, De Schouwberg, Knegelse Heide, Mirandolles Heike, Ten Vorsel, De Palts en Kroonvense Heide, Gemeentebossen Reusel, Cartierheide, De Pan, Eersel, Einderheide, Gemeentebossen Waalre, Kanunnikesven, Groote Heide, Gemeentebossen Heeze, Valkenhorst en Heezerheide, Wandelpark De Grote Meer en Nederheide, Dommelse Bossen, Keersop en Run</p>
        <p>Dit is de laatste blog van deze gids — en met de slotbatch staat de teller op <b>2.373 van de 2.373 boekgebieden (100%)</b>. Alle gebieden uit het bronboek zijn nu tweetalig beschreven, van het eerste duin tot de laatste beek. (Twee dubbels gingen er ook in deze ronde af: “De Kempen” en “Dommeldal” stonden al eerder in de gids; de “De Pan” van Someren bleek kaart 83, dus de Pan van Maarheeze kreeg gewoon zijn eigen kaart.)</p>
        <p>De batch eindigde zoals de Kempen horen te eindigen: met landgoederen, vennen en beken. Het <b>Landgoed Ten Vorsel</b> bracht negen eeuwen geschiedenis — al in <b>1173</b> bezit van de <b>Abdij van Postel</b> — en de <b>Heksenboom</b>, in <b>2019</b> verkozen tot <b>Nederlandse Boom van het Jaar</b>. De <b>Cartierheide</b> (172 ha) bleek gered door een <b>baron</b> die er jaagde en in <b>1932</b> door zijn zoon aan Natuurmonumenten werd geschonken; er zwemt en zondigt er de <b>gladde slang</b>. De <b>Pan van Maarheeze</b> was het landgoed dat de <b>familie Philips</b> in <b>1928</b> kocht voor de “bleekneusjes”, met de <b>kleine ijsvogelvlinder</b> als troeteldier. Het <b>Kanunnikesven</b> op de Stratumse Heide herbergt een <b>drijvend hoogveeneiland</b> — één van de laatste van Brabant. En <b>mejuffrouw Mirandolle</b>, de freule die honderd jaar werd, schonk tussen 1936 en 1939 haar “Heike” aan Natuurmonumenten.</p>
        <p>Vier kaarten kregen <b>Natura 2000 Leenderbos, Groote Heide &amp; De Plateaux</b> als kader: de naamgevende <b>Groote Heide</b> zelf (ooit twintig kilometer aaneengesloten hei tussen Eindhoven en Achel), de <b>Gemeentebossen van Heeze</b> met de <b>Diepmeerven</b>, de <b>798-ha landgoederen-wig</b> van <b>Valkenhorst en Heezerheide</b>, en — helemaal op het eind — de <b>Keersopperbeemden</b> bij Dommelen, waar het laagste punt van het Keersopdal is afgegraven om het water de ruimte te geven. De allereerste kaart van deze gids begon bij een Poels en een Bergh; de laatste eindigt bij een bruggetje over de <b>Keersop</b>. <b>De gids is af — maar de Kempen niet.</b> Wie hem gebruikt, vindt nu alle 2.373 gebieden: van Waddenzee tot Zuid-Limburg, van duin tot ven, van productiebos tot hoogveeneiland. Wandelen maar.</p>
      </div>
      <div class="c-en">
        <h3>The last 21: from Oostelbeers to the Keersop — the guide is complete</h3>
        <p class="post-meta">List 88 finale · Oostelbeerse Heide, ’s Heerenvijvers, Oirschotse Heide, De Schouwberg, Knegse Heide, Mirandolles Heike, Ten Vorsel, De Palts en Kroonvense Heide, Gemeentebossen Reusel, Cartierheide, De Pan, Eersel, Einderheide, Gemeentebossen Waalre, Kanunnikesven, Groote Heide, Gemeentebossen Heeze, Valkenhorst en Heezerheide, Wandelpark De Grote Meer en Nederheide, Dommelse Bossen, Keersop en Run</p>
        <p>This is the guide’s last blog post — and with the final batch the counter stands at <b>2,373 of the 2,373 book sites (100%)</b>. Every area of the source book is now described bilingually, from the first dune to the last stream. (Two duplicates dropped off in this round too: “De Kempen” and “Dommeldal” already sat earlier in the guide; Someren’s “De Pan” proved to be card 83, so Maarheeze’s Pan simply got its own card.)</p>
        <p>The batch ended the way the Campine should end: with estates, fens and streams. <b>Landgoed Ten Vorsel</b> brought nine centuries of history — already in <b>1173</b> property of <b>Postel Abbey</b> — and the <b>Witches’ Tree</b>, voted <b>Dutch Tree of the Year</b> in <b>2019</b>. The <b>Cartierheide</b> (172 ha) turned out to be saved by a <b>baron</b> who hunted there, donated to Natuurmonumenten by his son in <b>1932</b>; the <b>smooth snake</b> still basks on its sods. Maarheeze’s <b>Pan</b> was the estate the <b>Philips family</b> bought in <b>1928</b> for the city’s “pale-cheeked children”, with the <b>white admiral</b> as its darling. The <b>Kanunnikesven</b> on the Stratumse Heide holds a <b>floating raised-bog island</b> — one of Brabant’s last. And <b>Miss Mirandolle</b>, the lady who turned a hundred, donated her “Heike” to Natuurmonumenten between 1936 and 1939.</p>
        <p>Four cards received <b>Natura 2000 Leenderbos, Groote Heide &amp; De Plateaux</b> as their frame: the name-giving <b>Groote Heide</b> itself (once twenty kilometres of unbroken heath between Eindhoven and Achel), the <b>Heeze municipal woods</b> with the <b>Diepmeerven</b>, the <b>798-ha estate wedge</b> of <b>Valkenhorst and Heezerheide</b>, and — at the very end — the <b>Keersopperbeemden</b> by Dommelen, where the lowest point of the Keersop valley was excavated to give the water room. The very first card of this guide began at a Poel and a Berg; the last ends at a little bridge over the <b>Keersop</b>. <b>The guide is finished — the Campine is not.</b> Anyone using it now finds all 2,373 areas: from the Wadden Sea to South Limburg, from dune to fen, from production forest to raised-bog island. Onward on foot.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #107 (slot) toegevoegd')
