# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van De Boggelaar naar Verwolde: kastelen, hei en Veluwezoom (1875–1894)</h3>
        <p class="post-meta">List 36 · Gelderland: Warnsveld, Vorden, Hengelo (Gld), Veluwezoom, De Steeg, Doesburg en Lochem</p>
        <p>Deze reeks begint waar de vorige eindigde: in de landgoederengordel rond Warnsveld en Vorden. <b>De Boggelaar</b> — in oude stukken Den Bocheler — is een buitenplaats die al in 1579–83 opduikt in een rentmeestersrekening; het huis werd in 1879 geveild voor afbraak, de huidige bewoning staat op de oude fundamenten en het omringende landgoed is vrij toegankelijk. <b>Hackfort</b> is sinds 1981 van Natuurmonumenten: rond het zeventiende-eeuwse huis bloeien een half miljoen voorjaarsbollen, draait de werkende watermolen nog en voert de rolstoelvriendelijke Kasteelroute van 1,5 kilometer langs de oude muren. En <b>Vorden</b> is het kasteel van het gelijknamige kastelendorp: al in de twaalfde eeuw vermeld, in 1315 voor het eerst verkocht, grotendeels zestiende-eeuws en sinds 2018 met audiotour en privévertrekken te bezoeken — omringd door acht kastelen en een linde van ruim 400 jaar oud.</p>
        <p>Ten oosten van Vorden ligt een van de mooiste cultuurlandschappen van de Achterhoek: het 278 hectare grote complex <b>Kieftskamp, Lindese Laak, Maalderink en Hissink</b>, dat Geldersch Landschap &amp; Kasteelen in 1975 verwierf. Het zijn geen adellijke havezaten maar een oud kampenlandschap: erven van stedelijke families, vaak al eeuwen bewoond. <b>Kieftskamp</b> is het sierlijke huis in Franse stijl uit 1776 — de naam verwijst naar de kievit, en in het rococoplafond keren de vogels terug. <b>Het Hissink</b> en <b>Het Maalderink</b> (als Maelrink al in 1402 bezit van het Stift Elten) zijn de oude hoeven in het landschap, met de <b>Lindese Laak</b> als natuurvriendelijk herstelde levensader waar zo’n 170 plantensoorten zijn geteld. Even verderop ligt het waterwingebied <b>’t Klooster</b> bij Hengelo: 62 hectare rustig bos van Vitens, met heideveldjes, jeneverbessen, een dassenfamilie en een ecologische akker waar zelfs de kleine parelmoervlinder is gezien.</p>
        <p>Daarna springt de gids de Veluwe op. De <b>Veluwezoom</b> is het oudste nationale park van Nederland: Natuurmonumenten kocht er in 1911 het eerste stuk grond en beheert er inmiddels ruim 5.000 hectare met het meeste reliëf van de Veluwe — de Posbank kijkt bij helder weer tot in Duitsland, en op de heide grazen Schotse hooglanders, IJslandse paarden en een schaapskudde. <b>Rozendaalse Veld</b> is de 542 hectare hoge heide met de 33 meter hoge brandtoren die tot 1978 dienst deed, en in de <b>Beekhuizense Bossen</b> — ooit ‘Gelders Arcadië’ — klatert de Beekhuizerbeek met sprengkoppen en watervalletjes richting de IJssel. Daar liggen de landgoederen op een rij: <b>Kasteel Biljoen</b> van de families Van Spaen en Lüps (sinds 2008 van GLK, met parkbos en cascades), <b>Hof te Dieren</b>, al in 838 als Theothorne vermeld en later jachtslot van stadhouder Willem III, dat in 1795 en opnieuw in de Tweede Wereldoorlog afbrandde en waar tussen de oude moestuinmuren nu de grootste ommuurde wijngaard van Nederland ligt, en <b>Landgoed Middachten</b> bij De Steeg: circa 900 hectare particulier bezit met in de zomer geopende tuinen en de oudste authentieke stallen van Nederland.</p>
        <p>Langs de rivier en terug de Achterhoek in besluit de reeks. De <b>Vaalwaard</b> bij Lathum is een uiterwaard die Natuurmonumenten exclusief voor vogels beheert — niet toegankelijk, maar prachtig te bekijken vanaf de dijk. De <b>Wallen van Doesburg</b> herinneren aan het vestingstelsel dat Menno van Coehoorn vanaf 1701 om de Hanzestad legde; de Lage en Hoge Linie zijn nu een groene gordel van wallen, grachten en rietkragen. In Hoog-Keppel diende <b>Kasteel Ulenpas</b> in het rampjaar 1672 zelfs als hoofdkwartier van Lodewijk XIV; het huis brandde in 1965 en de Ulenpasroute loopt door het opengestelde landgoed. Het <b>Hekenbroek</b> tussen Doesburg en Drempt is een nat vlinderbos langs de Rode Beek, <b>Enghuizen</b> bij Hummelo vertelt het verhaal van zadelleen, tabaksteelt en een oranjerie die nu voor kasteel speelt, en <b>Wassinkbrink</b> onder Zelhem is een naam uit de gids zonder eigen terrein: een buurtschap in het coulisselandschap die we met een eerlijk voorbehoud registreren. De reeks sluit af met <b>Verwolde</b> bij Laren: in 1776 in negen maanden gebouwd op middeleeuwse fundamenten, sinds 1977 van Geldersch Landschap &amp; Kasteelen en thuisbasis van de Dikke Boom, de dikste eik van Nederland. Van buitenplaats tot vogelwaard, van havezate tot heideveld: twintig hoofdstukken Gelders landschap.</p>
      </div>
      <div class="c-en">
        <h3>From De Boggelaar to Verwolde: castles, heath and the Veluwezoom (1875–1894)</h3>
        <p class="post-meta">List 36 · Gelderland: Warnsveld, Vorden, Hengelo (Gld), Veluwezoom, De Steeg, Doesburg and Lochem</p>
        <p>This series begins where the previous one ended: in the belt of estates around Warnsveld and Vorden. <b>De Boggelaar</b> — Den Bocheler in old records — is a country estate already appearing in 1579–83 in an estate account; the house was auctioned for demolition in 1879, the present dwelling stands on the old foundations and the surrounding estate is freely accessible. <b>Hackfort</b> has belonged to Natuurmonumenten since 1981: around the seventeenth-century house half a million spring bulbs bloom, the working watermill still turns and the wheelchair-friendly Kasteelroute of 1.5 kilometres leads along the old walls. And <b>Vorden</b> is the castle of the eponymous castle village: mentioned already in the twelfth century, first sold in 1315, largely sixteenth-century in shape and open since 2018 with an audio tour and private rooms — surrounded by eight castles and a lime tree of over 400 years old.</p>
        <p>East of Vorden lies one of the finest cultural landscapes of the Achterhoek: the 278-hectare complex of <b>Kieftskamp, Lindese Laak, Maalderink and Hissink</b>, acquired by Geldersch Landschap &amp; Kasteelen in 1975. These are not noble manors but an old kampen landscape: farmsteads of urban families, often inhabited for centuries. <b>Kieftskamp</b> is the graceful house in French style from 1776 — the name refers to the lapwing, and the birds return in the rococo ceiling. <b>Het Hissink</b> and <b>Het Maalderink</b> (recorded as Maelrink as early as 1402, property of the Elten monastery) are the old farmsteads in the landscape, with the <b>Lindese Laak</b> as a nature-friendly restored lifeline where some 170 plant species have been counted. A little further on lies the <b>’t Klooster</b> water catchment area near Hengelo: 62 hectares of quiet Vitens forest with heath plots, junipers, a family of badgers and an ecological field where even the silver-washed fritillary has been seen.</p>
        <p>The guide then climbs onto the Veluwe. The <b>Veluwezoom</b> is the oldest national park of the Netherlands: Natuurmonumenten bought its first piece of land there in 1911 and now manages more than 5,000 hectares with the most relief of the Veluwe — on a clear day the Posbank looks all the way to Germany, and Highland cattle, Icelandic horses and a sheep flock graze the heath. <b>Rozendaalse Veld</b> is the 542-hectare elevated heath with the 33-metre fire tower that served until 1978, and in the <b>Beekhuizense Bossen</b> — once ‘Gelders Arcadië’ — the Beekhuizerbeek babbles with spring heads and little waterfalls towards the IJssel. There the estates line up: <b>Biljoen Castle</b> of the Van Spaen and Lüps families (owned by GLK since 2008, with park wood and cascades), <b>Hof te Dieren</b>, mentioned as Theothorne as early as 838 and later the hunting castle of Stadtholder William III, which burned down in 1795 and again in the Second World War and now holds the largest walled vineyard of the Netherlands between its old kitchen-garden walls, and <b>Middachten Estate</b> near De Steeg: some 900 hectares of private property with gardens open in summer and the oldest authentic stables of the Netherlands.</p>
        <p>Along the river and back into the Achterhoek the series closes. The <b>Vaalwaard</b> near Lathum is a floodplain that Natuurmonumenten manages exclusively for birds — not accessible, but wonderful to watch from the dike. The <b>Wallen van Doesburg</b> recall the fortress system that Menno van Coehoorn laid around the Hanseatic town from 1701; the Lage and Hoge Linie are now a green belt of walls, moats and reed beds. At Hoog-Keppel, <b>Ulenpas Castle</b> even served as the headquarters of Louis XIV in the disaster year 1672; the house burned in 1965 and the Ulenpasroute runs through the opened estate. The <b>Hekenbroek</b> between Doesburg and Drempt is a wet butterfly forest along the Rode Beek, <b>Enghuizen</b> near Hummelo tells the story of a saddle fief, tobacco cultivation and an orangery now playing the part of the castle, and <b>Wassinkbrink</b> below Zelhem is a name from the guide without its own terrain: a hamlet in the small-scale landscape that we register with an honest caveat. The series ends with <b>Verwolde</b> near Laren: built in nine months in 1776 on medieval foundations, owned by Geldersch Landschap &amp; Kasteelen since 1977 and home to the Dikke Boom, the thickest oak of the Netherlands. From country estate to bird floodplain, from manor to heath field: twenty chapters of Gelders landscape.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
