# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van de Wal naar Saeftinghe: 2273–2292</h3>
        <p class="post-meta">List 85 vervolg · Zoomland, Lievensberg, Molenzicht, Wouwse Plantage, Groot Molenbeek, Markiezaat, Lindonk, Mattemburgh, Woensdrechtse Heide, Walse Duin, Kooiheide, Kortenhoef, Staartse Heide en Duinen, Noordpolder van Ossendrecht, Vluchtheuvel, Pottenbergen, Ossendrecht, Stoppelbergen, Verdronken Land van Saeftinghe en De Grote Putting</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.292 van de 2.373 boekgebieden (96,6%)</b>. List 85 voerde van de landgoederen boven Bergen op Zoom over de Brabantse Wal naar de Grenspark-heide van Huijbergen en Woensdrecht — en eindigde bij het grootste schor van Europa. (De boekscan noteerde “Ossendrecht” tweemaal, op dezelfde pagina; de tweede regel is als scan-duplicaat overgeslagen.)</p>
        <p>Bovenop de Wal waren de <b>landgoederen</b> het ritme van de reis: <b>Zoomland</b> (± 308 ha, gegroeid uit vier goederen van ± 1700, met de middeleeuwse turfplas <b>Zeezuiper</b> die sinds de watermaatregelen weer vol staat — visarend in april en september), de <b>Lievensberg</b> met zijn <b>heidetuin van 30 soorten</b>, <b>Groot Molenbeek</b> (al in een akte van <b>1291</b> genoemd, met een 300 jaar oude zilverlinde) en de <b>Wouwse Plantage</b> — in <b>1504</b> door Jan III van Glymes aangeplant als <b>eerste productiebos van Nederland</b>, nog vóór het Mastbos. Het <b>Markiezaat</b> bleek het natuursucces van de Deltawerken: sinds de <b>Markiezaatskade van 1984</b> een zoetwatermoeras van 1.846 ha — na Waddenzee en IJsselmeer ons <b>grootste wetland</b>, met de grootste lepelaarkolonie van het land. En <b>Mattemburgh</b> combineert een <b>top-5 stijltuin</b> met een bosreservaat waarin sinds <b>1885</b> geen kap meer is gedaan.</p>
        <p>In het <b>Grenspark Kalmthoutse Heide</b> stonden de heidekaarten in het teken van herstel: de <b>Kooiheide</b> waar Evides in 2018 het bos opende en de heide terugkeert, de <b>Staartse Heide</b> met zijn “grote verbindingszone” voor <b>nachtzwaluw en gladde slang</b>, en de <b>Kortenhoeff</b>-vennen met waterlobelia. Rond <b>Ossendrecht</b> sloten de Abdijbossen (<b>Vluchtheuvel</b> en het <b>waterwingebied Pottenbergen</b>) en de <b>Stoppelbergen</b> — het grootste <b>zeeden</b>areaal van de Brabantse bossen, met kuifmezen — de Wal-rand af. Het slotakkoord was Vlaams: het <b>Verdronken Land van Saeftinghe</b>, <b>3.580 ha grootste brakwaterschor van Europa</b> met waterbuffels op Baalhoek, en het oudland van <b>De Grote Putting</b>, dat in 2016 van 50 naar 176 ha groeide. Volgende batch: de rest van list 85 (Het Koegat) en list 86 — richting Brabantse binnenland.</p>
      </div>
      <div class="c-en">
        <h3>From the Wal to Saeftinghe: 2273–2292</h3>
        <p class="post-meta">List 85 continued · Zoomland, Lievensberg, Molenzicht, Wouwse Plantage, Groot Molenbeek, Markiezaat, Lindonk, Mattemburgh, Woensdrechtse Heide, Walse Duin, Kooiheide, Kortenhoef, Staartse Heide en Duinen, Noordpolder van Ossendrecht, Vluchtheuvel, Pottenbergen, Ossendrecht, Stoppelbergen, Verdronken Land van Saeftinghe and De Grote Putting</p>
        <p>Another twenty cards, and the guide now counts <b>2,292 of the 2,373 book sites (96.6%)</b>. List 85 led from the estates above Bergen op Zoom across the Brabantse Wal to the Grenspark heaths of Huijbergen and Woensdrecht — and ended at Europe’s largest marsh. (The book scan listed “Ossendrecht” twice on the same page; the second line was skipped as a scan duplicate.)</p>
        <p>Atop the Wal the <b>estates</b> set the rhythm: <b>Zoomland</b> (± 308 ha, grown from four estates of ± 1700, with the medieval peat lake <b>Zeezuiper</b> refilled since the water measures — osprey in April and September), the <b>Lievensberg</b> with its <b>heather garden of 30 species</b>, <b>Groot Molenbeek</b> (named in a charter of <b>1291</b>, with a 300-year-old silver linden) and the <b>Wouwse Plantage</b> — planted in <b>1504</b> by Jan III van Glymes as the <b>first production forest of the Netherlands</b>, even before the Mastbos. The <b>Markiezaat</b> proved the Delta Works’ nature success: since the <b>Markiezaatskade of 1984</b> a 1,846-ha freshwater marsh — after the Wadden Sea and the IJsselmeer our <b>largest wetland</b>, holding the country’s largest spoonbill colony. And <b>Mattemburgh</b> combines a <b>top-5 formal garden</b> with a forest reserve unmanaged since <b>1885</b>.</p>
        <p>In the <b>Grenspark Kalmthoutse Heide</b> the heath cards stood under the sign of restoration: the <b>Kooiheide</b> where Evides opened the wood in 2018 and heath returns, the <b>Staartse Heide</b> with its “great connecting zone” for <b>nightjar and smooth snake</b>, and the <b>Kortenhoeff</b> pools with water lobelia. Around <b>Ossendrecht</b> the Abdijbossen (<b>Vluchtheuvel</b> and the <b>Pottenbergen water catchment</b>) and the <b>Stoppelbergen</b> — the largest <b>maritime pine</b> area among the Brabant woods, with crested tits — closed the Wal edge. The finale was Flemish: the <b>Verdronken Land van Saeftinghe</b>, <b>3,580 ha, Europe’s largest brackish marsh</b>, with water buffalo on Baalhoek, and the old land of <b>De Grote Putting</b>, which grew from 50 to 176 ha in 2016. Next batch: the rest of list 85 (Het Koegat) and list 86 — towards the Brabant interior.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #103 toegevoegd')
