# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Beestmans tot Landfort: het Woold, het veen en de grens (2135–2152)</h3>
        <p class="post-meta">List 36 · De Haart en het Woold bij Winterswijk, het Wooldse Veen en de Kulverheide, de Wisch bij Terborg, de grensdorpen IJzerlo, De Heurne en Dinxperlo, en havezate Landfort bij Silvolde</p>
        <p>Achttien kaarten deze keer, en de gids telt nu <b>2.152 van de 2.373 boekgebieden (90,7%)</b>. De batch opent in de <b>Haart</b> met het NSW-goed <b>Beestmans</b> en loopt dan door naar het <b>Woold</b>, het mooiste scholtenlandschap van Winterswijk: het <b>Keunenhuis</b> (rijksmonumentale boerderij met daglonershuisje en waterput, sinds de aankoop door Natuurmonumenten weer één geheel met Bekendelle — en met een nul-afvalproeftuin in de schoppe), de GLK-scholtengoederen <b>Aarnink</b> (oude eiken én beroemde lange beuken), <b>De Haar</b> (met infopunt en orchideeënhooiland) en <b>Meerdink en Lammers</b> — Meerdink al vanaf ± 1300 tegenerscholtengoed, Lammers met heidevennetje, wilde taxus en de zeldzame rijsbes.</p>
        <p>Daaromheen: het gesloten <b>bosreservaat Het Rot</b> (alleen de randen, bij de Rondje Rot-wandeling), het <b>Veenhuis</b>-erf uit 1647 met zijn waterleiding door het Kienveen, de <b>Kulverheide</b> — het hoogste plateau van Winterswijk, waar de heide na elke kap terugkeert in het ontginningsbos — en als natuurlijke hoogtepunt Natura 2000-gebied <b>Wooldse Veen</b> (nr. 64): samen met het Duitse Burlo-Vardingholter Venn één hoogveen, met regenererende veenputten, gladde slang en de zeer zeldzame dansmug. Dan de statige kant: landgoed <b>Wisch</b> bij Terborg en havezate <b>Landfort</b> bij Silvolde — vijftiende-eeuws, vier generaties Luyken, door Canadese oorlogsschade in 1970 aan het Geldersch Landschap verkocht en nu door Stichting Erfgoed Landfort tot in de historische plantlijsten gerestaureerd.</p>
        <p>De slotslag is de grensstreek zelf: het erf-bosperceel <b>Idink</b>, landgoed <b>Wissink</b> (sinds 1861 van de familie Mensink), het es-dorp <b>IJzerlo</b> aan de Kruisdijk, het NSW-goed <b>Het Vels</b>, grensdorp <b>De Heurne</b> met zijn beeldbepalende eiken aan het Giebinkslat, de <b>Dinxperlo landschapselementen</b> rond het Hof te Dinxperlo van 1370, en tenslotte <b>Kluunpand en Sleebos</b> — twee percelen zo klein dat de gids eerlijk durft te zijn over het kleine. Volgende batch: Zeeland — de Manteling van Walcheren en de kust.</p>
      </div>
      <div class="c-en">
        <h3>From Beestmans to Landfort: the Woold, the bog and the border (2135–2152)</h3>
        <p class="post-meta">List 36 · The Haart and the Woold at Winterswijk, the Wooldse Veen and the Kulverheide, Wisch at Terborg, the border villages of IJzerlo, De Heurne and Dinxperlo, and Landfort havezate at Silvolde</p>
        <p>Eighteen cards this time, and the guide now counts <b>2,152 of the 2,373 book sites (90.7%)</b>. The batch opens in the <b>Haart</b> with the Beestmans Act estate and then moves into the <b>Woold</b>, Winterswijk’s finest scholten landscape: the <b>Keunenhuis</b> (a listed farm with day-labourers’ cottage and well, reunited with Bekendelle since Natuurmonumenten’s purchase — and with a zero-waste trial garden in the barn), the GLK scholten estates of <b>Aarnink</b> (old oaks and famous tall beeches), <b>De Haar</b> (information point and orchid hay meadow) and <b>Meerdink and Lammers</b> — Meerdink a counter-scholten estate from ± 1300, Lammers with a heath pool, wild yew and the rare cowberry.</p>
        <p>Around them: the closed <b>Rot forest reserve</b> (edges only, on the Rondje Rot walk), the <b>Veenhuis</b> farmyard of 1647 with its watercourse through the Kienveen, the <b>Kulverheide</b> — the highest plateau of Winterswijk, where heather returns after every felling — and as natural climax Natura 2000 site <b>Wooldse Veen</b> (no. 64): one raised bog with the German Burlo-Vardingholter Venn, with regenerating peat pits, smooth snake and the very rare non-biting midge. Then the stately side: the <b>Wisch</b> estate at Terborg and <b>Landfort</b> havezate at Silvolde — fifteenth-century, four Luyken generations, sold to the Geldersch Landschap in 1970 after Canadian war damage and now restored by the Landfort Heritage Foundation down to the historic plant lists.</p>
        <p>The closing run is the border country itself: the farmstead wood of <b>Idink</b>, <b>Wissink</b> estate (the Mensink family’s since 1861), the es-village of <b>IJzerlo</b> on the Kruisdijk, the <b>Het Vels</b> Act estate, the border village of <b>De Heurne</b> with its landmark oaks at the Giebinkslat, the <b>Dinxperlo landscape elements</b> around the 1370 Hof te Dinxperlo, and finally <b>Kluunpand and Sleebos</b> — two parcels so small the guide dares to be honest about the small things. Next batch: Zeeland — the Manteling of Walcheren and the coast.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #96 toegevoegd')
