# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Buurserzand tot de Grevelingen: grensvenen en het oude Goeree (1955–1974)</h3>
        <p class="post-meta">List 36 · Overijssel en Zuid-Holland: Buurse, Haaksbergen, Usselo, Boekelo en de kop van Goeree</p>
        <p>De reeks vervolgt de Twentse grensstreek rond Buurse en Haaksbergen. Het <b>Buurserzand</b> is het grote heide- en stuifzandgebied van Natuurmonumenten tussen Enschede en Haaksbergen — met jeneverbesstruiken die op sommige plaatsen naar schatting 150 jaar oud zijn, infopunt De Wakel in de voormalige werkschuur en wandelroutes van 3 tot 10 kilometer langs de Harrevelderschans en de herstelde Buurserbeek. Het <b>Witte Veen</b> tussen Buurse en de Duitse grens is het Natura 2000-hoogveen van Natuurmonumenten waar Schotse hooglanders de heide open houden en wandelaars vanaf de Duitse Haarmühle twee korte ommetjes lopen; samen met het <b>Haaksbergerveen</b> van Staatsbosbeheer — een van de best herstellende hoogveenrestanten van Nederland, met zes routes vanaf de Niekerkerweg — vormt het de levende kern van de grensoverschrijdende veenketen. Daarna volgen vier namen die de oude gids noteerde in deze zelfde grensstreek: <b>Bos bij de Duitse grens</b>, <b>De Smalbraak</b>, <b>Het Broeke</b> en <b>Boeyink, Kössink en De Elzen</b> zijn in moderne kaarten niet meer als zelfstandige terreinen terug te vinden — deze kaarten registreren ze eerlijk als namen uit de gids en wijzen de wandelaar naar het landschap dat er wél is: het Witte Veen, het Buurserzand, de landgoederen rond Usselo en Boekelo en de paden van het Haaksbergerveen. Ook <b>Muggenhoek</b>, de afsluiter van de Twentse reeks, leeft alleen nog als naam voort; de hedendaagse Muggenhoeken liggen elders in het land.</p>
        <p>Dan springt de reeks naar het eiland Goeree. De <b>Springertduinen</b> bij de Brouwersdam groeien sinds 2020 letterlijk mee met de zeespiegel: drie zandkerven laten de wind vers kalkrijk zand het duin in blazen, waar de nachtegaal in het struweel zingt. <b>Onland</b> — tegenwoordig D’Onlanden van Het Zuid-Hollands Landschap — is het afgegraven akkerveldje waar in het voorjaar vier orchideeënsoorten tegelijk paars bloeien, te bewonderen vanaf het fietspad aan de Groeneweg. De <b>Westduinen</b> zijn de “hobbelwei”: 160 hectare open duingrasland met kerkpaden, drinkpoelen voor het vee en de herfstschroeforchis. In de <b>Kleistee</b> wandel je door het laatste gave middeleeuwse wallenlandschap van het eiland, met schurvelingen, rode emmertarwe, winterputten voor vleermuizen en een oude moerbeiboom. De <b>Oude Stee</b> in Achthuizen is eerlijkheidshalve geen natuur maar een museumboerderij — en een poort naar de Slikken van Flakkee. De <b>Bosobjecten Goeree</b> van Staatsbosbeheer zijn de zeldzame groene eilanden van het eiland: Stellebos, het bos aan de Smalle Gooi en het Melissantsebos, waar nestbomen altijd gespaard blijven. De <b>Oost- en Middelduinen</b> tussen Ouddorp en Oostdijk zijn het oudste duinlandschap: binnenduinen van omstreeks 600 na Christus, vrijwel onveranderd, met de vochtige Westhoofdvallei en een 20 kilometer lange rondroute. De <b>Schans</b> ten zuiden van Ouddorp herrees uit de bouwput van de N57 en heeft een brakke gracht met de zeldzame steurgarnaal; de <b>Koudenhoek</b> is het vogelparadijs van een dertiende-eeuwse polder met kijkscherm aan de Koedijk en zeearenden in de winter. De <b>Preekhilpolder</b> en de <b>Oudelandse Zeedijk</b> zijn de bloemdijken achter de Grevelingen: acht zeggesoorten, drie orchideeën en een maaibeurt die pas in september komt. En de <b>Grevelingen</b> zelf is sinds 1971 het grootste zoute binnenmeer van Europa — helder water met oesterbanken, winterende zeearenden en een randnatuur die kwetsbaar is en bescherming verdient.</p>
      </div>
      <div class="c-en">
        <h3>From the Buurserzand to the Grevelingen: border bogs and old Goeree (1955–1974)</h3>
        <p class="post-meta">List 36 · Overijssel and Zuid-Holland: Buurse, Haaksbergen, Usselo, Boekelo and the head of Goeree</p>
        <p>The series continues in the Twente border region around Buurse and Haaksbergen. The <b>Buurserzand</b> is the large heathland and drifting-sand area of Natuurmonumenten between Enschede and Haaksbergen — with juniper shrubs estimated at 150 years old in places, the De Wakel visitor point in the former work shed and walking routes of 3 to 10 kilometres along the Harrevelderschans and the restored Buurserbeek. The <b>Witte Veen</b> between Buurse and the German border is the Natura 2000 raised bog of Natuurmonumenten where Scottish Highlanders keep the heath open and walkers take two short circuits from the German Haarmühle; together with the <b>Haaksbergerveen</b> of Staatsbosbeheer — one of the best-restoring raised-bog remnants of the Netherlands, with six routes from the Niekerkerweg — it forms the living core of the cross-border chain of bogs. Then follow four names that the old guide noted in this same border region: <b>Bos bij de Duitse grens</b>, <b>De Smalbraak</b>, <b>Het Broeke</b> and <b>Boeyink, Kössink en De Elzen</b> can no longer be found as separate terrains on modern maps — these cards honestly record them as names from the guide and point the walker to the landscape that does exist: the Witte Veen, the Buurserzand, the estates around Usselo and Boekelo and the paths of the Haaksbergerveen. <b>Muggenhoek</b>, the closing entry of the Twente series, also lives on as a name only; the present-day Muggenhoeken lie elsewhere in the country.</p>
        <p>Then the series jumps to the island of Goeree. The <b>Springertduinen</b> near the Brouwersdam have literally been growing with the sea level since 2020: three sand gaps let the wind blow fresh calcareous sand into the dunes, where the nightingale sings in the scrub. <b>Onland</b> — nowadays D’Onlanden of Het Zuid-Hollands Landschap — is the scraped-off former field where four orchid species bloom purple at once in spring, best viewed from the cycle path along the Groeneweg. The <b>Westduinen</b> are the “hobbelwei”: 160 hectares of open dune grassland with church paths, drinking pools for the cattle and the autumn lady’s-tresses. In the <b>Kleistee</b> you walk through the last intact medieval banked landscape of the island, with schurvelingen, red emmer wheat, winter pits for bats and an old mulberry tree. The <b>Oude Stee</b> in Achthuizen is, in all honesty, not nature but a museum farmstead — and a gateway to the Slikken van Flakkee. The <b>Bosobjecten Goeree</b> of Staatsbosbeheer are the rare green islands of the island: Stellebos, the wood along the Smalle Gooi and the Melissantsebos, where nest trees are always spared. The <b>Oost- en Middelduinen</b> between Ouddorp and Oostdijk are the oldest dune landscape: inland dunes from around 600 AD, virtually unchanged, with the moist Westhoofdvallei and a 20-kilometre circuit. The <b>De Schans</b> south of Ouddorp rose again from the construction pit of the N57 and has a brackish moat with the rare Atlantic ditch shrimp; the <b>Koudenhoek</b> is the bird paradise of a thirteenth-century polder with a viewing screen at the Koedijk and white-tailed eagles in winter. The <b>Preekhilpolder</b> and the <b>Oudelandse Zeedijk</b> are the flower dikes behind the Grevelingen: eight sedge species, three orchids and a mowing that only comes in September. And the <b>Grevelingen</b> itself has been the largest saline inland sea of Europe since 1971 — clear water with oyster beds, wintering white-tailed eagles and a fringe nature that is vulnerable and deserves protection.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
