# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Chaam naar de Reusel: 2313–2332</h3>
        <p class="post-meta">List 87 vervolg + slot + list 88 begin · Chaamse Beek, Kapellebos, Ooijevaarsnest, Regte Heide en Riels Hoefke, Halve Maan, Abcoven, Gemeentebossen Hilvarenbeek, Kerkeindseheide, Gemeentebossen Goirlesedijk, Gorp de Leij, Annanina’s Rust, Rovertse Heide, ’t Merkske, De Utrecht, Wellenseindse Heide, Dal van de Reusel, Turnhoutse Heide, Molenheide, Reuselse Moeren, Moergestels Broek en Reuselbeemden</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.332 van de 2.373 boekgebieden (98,3%)</b>. De reis volgde het water: van de <b>Chaamse Beek</b> — waar Natuurmonumenten de gekanaliseerde sloot weer laat slingeren — via de <b>Leij</b> bij Goirle naar de <b>Reusel</b>, die in dit deel van Brabant de hele gordel draagt. (Ook deze batch had een scan-dubbel: “Ulvenhoutsebos en Chaam” bleek al kaart 1008 — overgeslagen.)</p>
        <p>Bij <b>Goirle</b> lag het grootste cluster: het <b>876-ha complex van Regte Heide, Riels Hoefke, Ooijevaarsnest, Halve Maan en Nieuwkerk</b>, met <b>zeven grafheuvels uit de Midden-Bronstijd</b> en het <b>schijnvliegveld De Kiek</b> uit de Tweede Wereldoorlog, waar de bomkraters nog in het landschap liggen. Het <b>Abcoven</b> (41 ha) bleek klein maar fier: graslandjes met knotwilgen die <b>sinds 1996 met de hand gemaaid</b> worden. Bij Hilvarenbeek de landgoederenrij: <b>Gorp de Leij</b> (92-ha enclave van Brabants Landschap aan de meanderende Rovertse Leij), <b>Annanina’s Rust</b> — in <b>1899</b> gesticht door een Diessense notaris en genoemd naar zijn <b>Russische geliefde</b> — en de <b>Rovertse Heide</b>, die in <b>1903</b> door de <b>Oranjebond van Orde</b> werd gekocht voor een mislukte sociale ontginning en sinds <b>1976</b> weer honderd hectare open heide is. Aan de Belgische grens stroomt het <b>Merkske</b> — <b>16 km kronkelend, nooit gekanaliseerd</b>, de beek zelf de landsgrens — en ligt het <b>2.500-ha landgoed De Utrecht</b>, dat in <b>1898/99</b> door een levensverzekeraar als belegging werd ontgonnen met <b>stoomploegen</b> en <b>Zeeuwse pachters</b>.</p>
        <p>Het slotakkoord was de <b>Reusel</b>: in de jaren ’60 gekanaliseerd, maar in het <b>Land van de Hilver</b> sinds 2010 weer <b>hermeanderend</b> — <b>60 ha overbemeste bodem afgegraven</b>, de beek mag sinds 2020 grotendeels zelf haar loop bepalen, en het geheel groeide tot het <b>grootste weidevogelgebied van Noord-Brabant</b> (meer dan <b>80 paren grutto</b>). De <b>Reuselse Moeren</b> (152 ha hoogveenrestant met vogelkijkhut <b>De Kiekkaaste</b>) en de <b>Reuselbeemden</b> — de “Nieuwe” variant van de oude blauwgraslanden — completeerden het dal. Drie kaarten kregen <b>Natura 2000 Kempenland-West</b> als kader. Volgende batch: de rest van list 88 — van De Mortelen via Sonsche Heide naar de Dommel.</p>
      </div>
      <div class="c-en">
        <h3>From Chaam to the Reusel: 2313–2332</h3>
        <p class="post-meta">List 87 continued + finale + list 88 opening · Chaamse Beek, Kapellebos, Ooijevaarsnest, Regte Heide and Riels Hoefke, Halve Maan, Abcoven, Gemeentebossen Hilvarenbeek, Kerkeindseheide, Gemeentebossen Goirlesedijk, Gorp de Leij, Annanina’s Rust, Rovertse Heide, ’t Merkske, De Utrecht, Wellenseindse Heide, Dal van de Reusel, Turnhoutse Heide, Molenheide, Reuselse Moeren, Moergestels Broek and Reuselbeemden</p>
        <p>Another twenty cards, and the guide now counts <b>2,332 of the 2,373 book sites (98.3%)</b>. The journey followed the water: from the <b>Chaamse Beek</b> — where Natuurmonumenten lets the canalised ditch wind again — via the <b>Leij</b> at Goirle to the <b>Reusel</b>, which carries the whole belt in this part of Brabant. (This batch held a scan duplicate too: “Ulvenhoutsebos en Chaam” turned out to be card 1008 already — skipped.)</p>
        <p>Near <b>Goirle</b> lay the largest cluster: the <b>876-ha complex of Regte Heide, Riels Hoefke, Ooijevaarsnest, Halve Maan and Nieuwkerk</b>, with <b>seven burial mounds from the Middle Bronze Age</b> and the <b>De Kiek mock airfield</b> of the Second World War, its bomb craters still legible in the land. The <b>Abcoven</b> (41 ha) proved small but proud: pollard-willow grasslands <b>mown by hand since 1996</b>. Around Hilvarenbeek came the estate row: <b>Gorp de Leij</b> (a 92-ha Brabants Landschap enclave on the meandering Rovertse Leij), <b>Annanina’s Rust</b> — founded in <b>1899</b> by a Diessen notary and named after his <b>Russian beloved</b> — and the <b>Rovertse Heide</b>, bought in <b>1903</b> by the <b>Oranjebond van Orde</b> for a failed social reclamation and again a hundred hectares of open heath since <b>1976</b>. At the Belgian border flows the <b>Merkske</b> — <b>16 km of winding, never canalised</b>, the stream itself the national border — and lies the <b>2,500-ha De Utrecht estate</b>, reclaimed from <b>1898/99</b> by a life insurer as an investment, with <b>steam ploughs</b> and <b>Zeeland tenant farmers</b>.</p>
        <p>The finale was the <b>Reusel</b>: canalised in the 1960s, but in the <b>Land van de Hilver</b> re-meandering since 2010 — <b>60 ha of over-fertilised soil excavated</b>, the stream largely choosing its own course again since 2020, and the whole growing into <b>North Brabant’s largest meadow-bird area</b> (more than <b>80 pairs of godwits</b>). The <b>Reuselse Moeren</b> (152 ha of bog remnant with the <b>De Kiekkaaste</b> bird hide) and the <b>Reusel meads</b> — the “new” edition of the old blue-grasslands — completed the valley. Three cards received <b>Natura 2000 Kempenland-West</b> as their frame. Next batch: the rest of list 88 — from De Mortelen via Sonsche Heide to the Dommel.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #105 toegevoegd')
