# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van het Otterlose Bos naar het Bennekomse Bos (1775–1794)</h3>
        <p class="post-meta">List 36 · Gelderland en Utrecht: Otterlo, Ede, Loenen, Rheden, Terlet, Arnhem, Schaarsbergen, Veenendaal, Renkum en Bennekom</p>
        <p>Deze reeks begint in het <b>Otterlose Bos</b>, de oude bosgroeiplaats van zo’n 200 hectare in het noordwesten van De Hoge Veluwe: hier staat een van de laatste en grootste populaties inheemse wilde appels van de Veluwe, die het park sinds 2020 uit eigen pitten kweekt en met rasters terugplant. Even ten westen daarvan ligt <b>Planken Wambuis</b>, het 1.965 hectare grote Natuurmonumenten-gebied rond de herberg uit 1782 aan de hessenweg, met 430 hectare heide, 180 hectare stuifzand en de biologische akkers van Oud Reemst. Tussen Ede en Otterlo ligt de <b>Hindenkamp</b>: de wildweide waar edelherten, reeën en zwijnen in de schemering de bosrand verlaten — vanaf de overdekte wildkansel, die alleen onder leiding van een gids via het fluisterpad van Natuurcentrum De Ginkel is te bereiken. De <b>Noord- en Zuid-Ginkel</b> rondom herbergen de Ginkelse Heide, waar op 17 en 18 september 1944 bij de schaapskooi zo’n 1.900 Britse parachutisten landden tijdens Operatie Market Garden. En dan is er natuurlijk <b>Het Nationale Park De Hoge Veluwe</b>: 5.400 hectare bos, heide en stuifzand met het Kröller-Müller Museum, Jachthuis Sint Hubertus en 1.800 gratis witte fietsen.</p>
        <p>Ten oosten van de A50 strekt het <b>Delerwoud</b> zich uit, met 2.380 hectare een van de grootste stiltegebieden van de Veluwe — Natuurmonumenten redde het in 1967 met de campagne ‘Behoud het Deelerwoud’ en in de bronst klinkt het burlen er over de Grote en Kleine Heide. Het <b>Loenermark en Loenense Bos</b> vormen samen het grootste terrein van Geldersch Landschap &amp; Kasteelen: heide met jeneverbesstruwelen en stuifduinen rond het al in de vroege middeleeuwen genoemde Loenense Bos, waar de schaapskudde van Droefakkers met de herder graast. Ten zuiden daarvan ligt Nationaal Park <b>Veluwezoom</b>, in 1930 het eerste nationale park van Nederland, met de Posbank op het Herikhuizerveld en uitzicht over de IJsselvallei. De <b>Terletse Heide</b> bij zweefvliegveld Terlet ligt op een oud smeltwaterdal waar runderen en Schotse hooglanders de hei openhouden, en de <b>Arnhemsche Heide</b> ten noorden van Arnhem is de eeuwenoude gemeenschapsheide van de Arnhemse burgerij — nu grotendeels militair oefenterrein.</p>
        <p>Onder Arnhem ligt de <b>Kemperheide-Deelen</b>, waar op Buitenplaats Koningsweg de betonnen reuzen van Fliegerhorst Deelen nu ateliers en woningen zijn en het Veluws Rondje Schaarsbergen over heide en door bos loopt. Bij Veenendaal liggen dan de twee ‘Hellen’, restanten van de turfwinning in het Binnenveld: de <b>Blauwe Hel</b> en <b>De Hel</b>, samen 36 hectare drijvend trilveen, blauwgrasland en veenmosrietland met drie soorten orchideeën en geel schorpioenmos — te kwetsbaar om te betreden, te bekijken vanaf de Ketelweg en het fietspad langs de Grift. Even verderop ligt de <b>Bennekomse Meent</b>, een van de best bewaarde blauwgraslanden van Nederland, waar vrijwilligers sinds 1990 op een van de oudste vlinderroutes van het land tellen. Terug op de zandgrond wacht de <b>Sysselt</b> tussen Ede en Bennekom, het oude jachtbos van de hertog van Gelre met Het Paradijs, een dennenbos van 180 jaar op stuifheuvels.</p>
        <p>De reeks eindigt rond Bennekom en Renkum. <b>Hoekelum</b> is de 18e-eeuwse buitenplaats van Geldersch Landschap &amp; Kasteelen, met kasteel, vijverpartij, Engelse landschapstuin, sprengen en klompenpaden; de <b>Bennekomse Buurtheide</b> ernaast is een hersteld heidelandschap met eikenhakhout, Celtic Fields uit de ijzertijd en grafheuvels. De <b>Renkumse Beek</b> stroomt door het gelijknamige beekdal van de Veluwezoom naar de Nederrijn: een sprengenbeek waarvoor eeuwenlang sprengen in de helling werden gegraven om negen watermolens te laten draaien. Op landgoed <b>Quadenoord-Boschbeek</b> draait de gerestaureerde Quadenoordse molen sinds 2022 weer op water en maalt biologisch graan van eigen akkers. En rond het dorp zelf ligt het <b>Bennekomse Bos</b>: het losloopbos op de stuwwal met de Hullenberg, Dikkenberg en Dullenberg, kleine heideveldjes en uitzicht tot aan de beekdalen van Renkum.</p>
      </div>
      <div class="c-en">
        <h3>From the Otterlose Bos to the Bennekomse Bos (1775–1794)</h3>
        <p class="post-meta">List 36 · Gelderland and Utrecht: Otterlo, Ede, Loenen, Rheden, Terlet, Arnhem, Schaarsbergen, Veenendaal, Renkum and Bennekom</p>
        <p>This series begins in the <b>Otterlose Bos</b>, the ancient woodland site of some 200 hectares in the north-west of De Hoge Veluwe: it holds one of the last and largest populations of native wild apple on the Veluwe, which the park has been raising from its own pips since 2020 and planting back behind fences. Just west of it lies <b>Planken Wambuis</b>, Natuurmonumenten’s 1,965-hectare area around the inn from 1782 on the Hessenweg, with 430 hectares of heath, 180 hectares of drift sand and the organic fields of Oud Reemst. Between Ede and Otterlo lies the <b>Hindenkamp</b>: the game meadow where red deer, roe deer and boar leave the forest edge at dusk — seen from the covered game hide, which is only reachable with a guide via the whisper path from Nature Centre De Ginkel. The <b>Noord- and Zuid-Ginkel</b> around it hold the Ginkelse Heide, where on 17 and 18 September 1944 some 1,900 British paratroopers landed near the sheep fold during Operation Market Garden. And then there is, of course, <b>Het Nationale Park De Hoge Veluwe</b>: 5,400 hectares of forest, heath and drift sand with the Kröller-Müller Museum, Jachthuis Sint Hubertus and 1,800 free white bicycles.</p>
        <p>East of the A50 stretches the <b>Delerwoud</b>: at 2,380 hectares one of the largest silence areas of the Veluwe — Natuurmonumenten saved it in 1967 with the campaign ‘Behoud het Deelerwoud’, and during the rut the belling sounds over the Grote and Kleine Heide. The <b>Loenermark and Loenense Bos</b> together form the largest terrain of Geldersch Landschap &amp; Kasteelen: heath with juniper scrub and drift dunes around the Loenense Bos, already mentioned in the early Middle Ages, where the Droefakkers sheep flock grazes with its shepherd. South of it lies National Park <b>Veluwezoom</b>, the first national park of the Netherlands in 1930, with the Posbank on the Herikhuizerveld and views over the IJssel valley. The <b>Terletse Heide</b> by Terlet glider airfield lies on an old meltwater valley where cattle and Scottish Highland cattle keep the heath open, and the <b>Arnhemsche Heide</b> north of Arnhem is the centuries-old common heath of Arnhem’s citizens — now largely a military exercise area.</p>
        <p>Below Arnhem lies <b>Kemperheide-Deelen</b>, where on Buitenplaats Koningsweg the concrete giants of Fliegerhorst Deelen are now studios and homes, and the Veluws Rondje Schaarsbergen runs over heath and through forest. Near Veenendaal lie the two ‘Hellen’, remnants of the peat cutting in the Binnenveld: the <b>Blauwe Hel</b> and <b>De Hel</b>, together 36 hectares of floating quaking bog, fen meadow and Sphagnum reedland with three species of orchid and yellow starry feather-moss — too vulnerable to enter, best viewed from the Ketelweg and the cycle path along the Grift. Just beyond lies the <b>Bennekomse Meent</b>, one of the best-preserved fen meadows of the Netherlands, where volunteers have counted butterflies since 1990 on one of the country’s oldest monitoring routes. Back on the sandy soil waits the <b>Sysselt</b> between Ede and Bennekom, the old hunting forest of the Duke of Guelders with Het Paradijs, an 180-year-old pine forest on drift hills.</p>
        <p>The series ends around Bennekom and Renkum. <b>Hoekelum</b> is the 18th-century country estate of Geldersch Landschap &amp; Kasteelen, with castle, ponds, English landscape garden, spring streams and clompenpaden; the <b>Bennekomse Buurtheide</b> next to it is a restored heath landscape with oak coppice, Iron Age Celtic Fields and burial mounds. The <b>Renkumse Beek</b> flows through its valley from the Veluwezoom to the Lower Rhine: a spring stream for which sprengen were cut into the slope for centuries to keep nine water mills turning. On the <b>Quadenoord-Boschbeek</b> estate the restored Quadenoord mill has been turning on water again since 2022, grinding organic grain from its own fields. And around the village itself lies the <b>Bennekomse Bos</b>: the dog-walking forest on the ice-margin ridge with the Hullenberg, Dikkenberg and Dullenberg, small heath plots and views out to the Renkum stream valleys.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
