# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Ampsen naar de Needse Berg: kastelen, stuwwallen en boomkikkers (1895–1914)</h3>
        <p class="post-meta">List 36 · Gelderland en Overijssel: Lochem, Goor, Diepenheim, Hengevelde, Delden, Haaksbergen en Neede</p>
        <p>Na Verwolde trekt de gids de grensstreek van de Achterhoek en Twente in. <b>Ampsen</b> ten noorden van Lochem is een particulier landgoed van circa 680 hectare dat al in 1389 in de boeken staat: het witgepleisterde huis met de blauw-witte luiken staat op de derde bouwplaats, en de zandwegen door het coulisselandschap zijn vrij toegankelijk. Tussen Goor en Diepenheim ligt <b>Landgoed Weldam</b>, een van de best bewaarde kasteellandgoederen van Nederland: rond 1380 voor het eerst genoemd, in de zeventiende eeuw voorzien van zijn monumentale poort en grachten, en beroemd om de kasteeltuin die op werkdagen opengaat — eromheen lopen drie wandelroutes met gekleurde paaltjes. Het stadje Diepenheim levert een hele kastelenreeks op: <b>Westerflier</b> is de havezate aan de Schipbeek waar ook de Regge ontspringt, <b>Huis te Diepenheim</b> werd in 1648 door Berent Bentinck herbouwd en heeft een vrij toegankelijk Sterrebos, en <b>Nijenhuis</b>, sinds 1799 van de familie Schimmelpenninck, voert wandelaars langs de Molenbeek, de oude watermolen Den Haller en een parkbos in Engelse landschapsstijl.</p>
        <p>Daarna komt het Twentse coulisselandschap. <b>Groot-Boerman</b> en <b>Hengevelde</b> zijn namen die teruggaan op de oude hofsteden en het dorp tussen Markelo en Delden — in de Gids voor Twente uit 1917 heten Kagelink, Boerman en Damme al ‘eeuwenoude hofsteden’; een eigen terrein is er niet, maar de omgeving wandelt heerlijk via het Wandelnetwerk Twente, bijvoorbeeld langs de Bolscherbeek. <b>Twickel</b> bij Delden is met ruim 4.000 hectare het grootste particuliere landgoed van Nederland: rond het kasteel, waarvan de oudste vermelding uit 1347 stamt, loopt een kasteelwandeling van 4,5 kilometer, verderop draait de Noordmolen en langs de landgoedgrens slingert de historische Umfassungsweg. Het <b>Stepelerveld</b> tussen Beckum en Haaksbergen werd in 1984 door Natuurmonumenten gekocht van de erven Van Heek en ging in 1995 over naar landgoed Twickel: een bos-, heide- en vennengebied waar de paden langs heideveldjes, vennen en oude dennen voeren. Twee namen uit het register konden niet meer aan een terrein worden gekoppeld: <b>De Huttensmit en Koksbos</b>, door de gids beschreven als een vrij toegankelijk bos- en weilandengebied met een beek tussen Enschede en Haaksbergen, en <b>Trekop</b>, waarvoor geen enkele moderne bron een ligging geeft — beide zijn eerlijk als zodanig geregistreerd.</p>
        <p>De gids draait terug de Achterhoek in, naar de stuwwallen van Lochem. De <b>Paaschberg</b> tegen Lochem aan herbergt een watertoren, een openluchttheater en gidsgesteenten uit Scandinavië; het <b>Mariabos</b> aan de zuidrand van Lochem is een kwelrijk beekdalbos langs de Berkel; en <b>De Nettelhorst</b> toont de ruïne van een kasteel dat in 1875 werd afgebroken, met een bouwhuis uit 1760 en tussen 1994 en 2006 herstelde grachten — het bezit van stichting Twickel ligt verscholen in de buurtschap bij Lochem. <b>De Lochemse Berg</b> en <b>De Kale Berg</b> vormen samen de beboste stuwwal tussen Lochem en Barchem met de Belvédère-toren uit 1893, kwelplekken vol bijzondere planten en de Witte Wievenkoele waar de sage van Johanna en Herbert speelt. In het broekland van Berkelland ligt <b>het Roeterinksbroek</b> bij De Horst en Geesteren, ooit een van de laatste bolwerken van de boomkikker in de Achterhoek en onderdeel van de ecologische corridor richting het Wanninkhof.</p>
        <p>De reeks sluit af rond Neede. <b>Landgoed Wanninkhof</b> is een boerenlandgoed van 17 hectare met een monumentale Saksische hoeve uit 1797 en poelen vol boomkikkers, kamsalamanders en poelkikkers; het klompenpad Boereneschpad loopt er dwars overheen. De <b>Needse Berg</b>, een stuwwal van 35 meter, is een paradijs voor kinderen: de routes van Woudy de woudolifant voeren langs de speelplek Ordelmanskoele en de tien meter hoge observatietoren met uitzicht tot in Duitsland. En <b>Het Olthaar</b>, tussen de Needse Berg en het Needse Achterveld, is net als Trekop een naam uit de oude gids die we eerlijk registreren: vermoedelijk een oude ‘haar’ of zandrug, in moderne registers niet meer terug te vinden. Van havezate tot boomkikkerpoel, van kasteeltuin tot kinderwandelroute: twintig hoofdstukken uit het grensland van Achterhoek en Twente.</p>
      </div>
      <div class="c-en">
        <h3>From Ampsen to the Needse Berg: castles, push moraines and tree frogs (1895–1914)</h3>
        <p class="post-meta">List 36 · Gelderland and Overijssel: Lochem, Goor, Diepenheim, Hengevelde, Delden, Haaksbergen and Neede</p>
        <p>After Verwolde the guide enters the border region of the Achterhoek and Twente. <b>Ampsen</b>, north of Lochem, is a private estate of some 680 hectares that has been in the records since 1389: the white-plastered house with its blue-and-white shutters stands on the third house site, and the sandy lanes through the small-scale landscape are freely accessible. Between Goor and Diepenheim lies <b>Weldam Estate</b>, one of the best-preserved castle estates of the Netherlands: first mentioned around 1380, given its monumental gate and moats in the seventeenth century, and famous for the castle garden that opens on weekdays — around it run three walking routes with coloured posts. The little town of Diepenheim delivers a whole series of castles: <b>Westerflier</b> is the manor house on the Schipbeek where the Regge also rises, <b>Huis te Diepenheim</b> was rebuilt by Berent Bentinck in 1648 and has a freely accessible Sterrebos, and <b>Nijenhuis</b>, owned by the Schimmelpenninck family since 1799, leads walkers along the Molenbeek, the old Den Haller watermill and a park wood in the English landscape style.</p>
        <p>Then comes the Twente countryside. <b>Groot-Boerman</b> and <b>Hengevelde</b> are names going back to the old farmsteads and the village between Markelo and Delden — in the 1917 Guide to Twente, Kagelink, Boerman and Damme are already called ‘centuries-old homesteads’; there is no terrain of their own, but the surroundings walk beautifully via the Twente walking network, for instance along the Bolscherbeek. <b>Twickel</b> near Delden, with more than 4,000 hectares, is the largest private estate of the Netherlands: around the castle, whose oldest mention dates from 1347, runs a 4.5-kilometre castle walk, further on the Noordmolen still turns and along the estate boundary winds the historic Umfassungsweg. The <b>Stepelerveld</b> between Beckum and Haaksbergen was bought in 1984 by Natuurmonumenten from the Van Heek heirs and passed to Twickel estate in 1995: an area of wood, heath and pools whose paths lead past heath plots, pools and old pines. Two names from the register could no longer be linked to a terrain: <b>De Huttensmit en Koksbos</b>, described by the guide as a freely accessible area of wood and meadows with a brook between Enschede and Haaksbergen, and <b>Trekop</b>, for which no modern source gives a location — both are honestly registered as such.</p>
        <p>The guide turns back into the Achterhoek, towards the Lochem hills. The <b>Paaschberg</b> against Lochem hides a water tower, an open-air theatre and glacial indicator stones from Scandinavia; the <b>Mariabos</b> on the southern edge of Lochem is a seepage-rich brook-valley wood along the Berkel; and <b>De Nettelhorst</b> shows the ruin of a castle demolished in 1875, with a coach house from 1760 and moats restored between 1994 and 2006 — the Twickel foundation’s holding lies hidden in the hamlet near Lochem. The <b>Lochemse Berg</b> and the <b>Kale Berg</b> together form the wooded push moraine between Lochem and Barchem with the 1893 Belvédère tower, seepage spots full of special plants and the Witte Wievenkoele where the legend of Johanna and Herbert is set. In the fenland of Berkelland lies <b>the Roeterinksbroek</b> near De Horst and Geesteren, once one of the last strongholds of the tree frog in the Achterhoek and part of the ecological corridor towards Wanninkhof.</p>
        <p>The series closes around Neede. <b>Wanninkhof estate</b> is a 17-hectare farm estate with a monumental Low Saxon farmhouse from 1797 and pools full of tree frogs, great crested newts and pool frogs; the Boereneschpad clog path runs straight across it. The <b>Needse Berg</b>, a push moraine of 35 metres, is a paradise for children: the routes of Woudy the forest elephant lead past the Ordelmanskoele play area and the ten-metre-high observation tower with views as far as Germany. And <b>Het Olthaar</b>, between the Needse Berg and the Needse Achterveld, is like Trekop a name from the old guide that we register honestly: probably an old ‘haar’ or sandy ridge, no longer traceable in modern registers. From manor house to tree-frog pool, from castle garden to children’s walking route: twenty chapters from the borderland of the Achterhoek and Twente.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
