# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van de Oostereng naar Sonsbeek (1795–1814)</h3>
        <p class="post-meta">List 36 · Gelderland: Wageningen, Wolfheze, Oosterbeek, Arnhem en Rozendaal</p>
        <p>Deze reeks begint bij Wageningen en Bennekom met <b>Oostereng</b>: de 685 hectare grote boswachterij van Staatsbosbeheer op de grens van drie gemeenten, waar Leidse zeepzieders vanaf 1847 woeste grond beplantten voor boswol en waar in het bos het vergeten Arboretum Oostereng uit 1911 en grafheuvels van de klokbekercultuur liggen. Ten zuiden van de A12 volgen twee stille gebieden tussen Wolfheze en Papendal: <b>Lange Hut en Grijsoord</b>, waar de oude grenswal tussen Ede en Arnhem over de helling van het Papendal loopt en het Bommenlijntje uit 1941 nog te volgen is, en de <b>Reierscamp</b> bij Wolfheze, waar Natuurmonumenten sinds 2004 bijna 200 hectare landbouwgrond teruggeeft aan heide en waar in september 1944 honderden zweefvliegtuigen landden — het ecoduct Jac. P. Thijsse verbindt het gebied sinds 2012 met Planken Wambuis.</p>
        <p>In Arnhem-Noord liggen drie gemeentelijke natuurparels: de <b>Westerheide</b>, een hersteld, vlak heideveld met Veluwse heideschapen, de Cirkelweg en een schaapsdrift tussen twee wildwallen, de <b>Maasbergse bossen</b> met hun grenspaal uit 1932 en de monumentale boerderij De Groote Kweek, en <b>Berkenhove</b>, een stille bosperceelnaam aan de rand van de grote bossen. Verderop wacht <b>Wolfheze</b> met de kerkheuvel van het verdwenen Oud-Wolfheze, de monumentale Wodanseiken langs de Wolfhezerbeek en het Airborne-monument van 1944. Tussen Oosterbeek en Wolfheze liggen de landgoederen <b>Sonnenberg en Bilderberg</b>: bankier Van Tienhoven liet er in 1913 een villa bouwen in een tuin van Samuel Voorhoeve — het werd Hotel De Bilderberg, waar in 1954 de eerste Bilderbergconferentie werd gehouden, terwijl de open velden in september 1944 slagveld waren tijdens de Slag om Arnhem. De <b>Johannahoeve</b> ten noorden van Wolfheze gaf in 2020 de ruimte terug aan edelherten: de rasters gingen eruit en het heideherstel begon.</p>
        <p>In de landgoederengordel tussen Arnhem en Oosterbeek volgen <b>Lichtenbeek en Vijverberg</b>, met de monumentale siervazen uit 1750 van het afgebrande landhuis Lichtenbeek en de vijvers, sprengen en watervalletjes van De Vijverberg. Daarachter liggen <b>Warnsborn en Hoog Erf</b> van Geldersch Landschap &amp; Kasteelen: de naam verwijst naar een heldere bron uit 1428, rond hotel Groot Warnsborn liggen de tuin van H. Copijn, de romantische Klein-Zwitserland-zone en de lanenzesster van Hoog Erf. <b>Schaarsbergen</b> is het ontginningsdorp uit 1849 met het demobos van de gemeente Arnhem, en in de oksel van de A50 en A12 ligt de <b>Koningsheide</b>: na de grote bosbrand van 1976 weer volgroeid, met een diep droogdal — de slenk — en sinds 2020 een bosreservaat van 70 hectare naast het oerbos op <b>De Waterberg</b>, waar de gemeente in 2015 als eerste op de Veluwe 80 hectare aan de natuur teruggaf en waaruit het Openluchtmuseum is geboren. <b>Valkenhuizen</b> ten slotte herinnert met zijn naam aan het valkenhuis van de Arnhemse jachtcultuur.</p>
        <p>De reeks eindigt in de gemeente Rozendaal en Arnhem. Het <b>Rozendaalse Veld</b> is het uitgestrekte, stille heideveld van de noordelijke Veluwezoom, waar edelherten tussen Deelen en de stuwwal trekken. Ernaast liggen het kasteel- en parklandschap van <b>Landgoed Rosendaal</b> — Kasteel Rosendael met de grootste donjon van Nederland, de bedriegertjes en de schelpengalerij —, het dorp <b>Rozendaal</b>, de kleinste gemeente van Nederland, en <b>Rosendaal</b>, het oude bos rond het kasteel dat ook als Rozendaalse Bos bekendstaat. En in Arnhem zelf vormen <b>Sonsbeek, Zijpendaal en Gulden Bodem</b> de groene vinger van de Veluwe tot aan het centrum: langs de Sint-Jansbeek met zijn tien historische watermolens liggen de Grote Waterval uit 1826, de Belvédère, de Witte Watermolen en het Nederlands Watermuseum — de bakermat van Arnhem.</p>
      </div>
      <div class="c-en">
        <h3>From the Oostereng to Sonsbeek (1795–1814)</h3>
        <p class="post-meta">List 36 · Gelderland: Wageningen, Wolfheze, Oosterbeek, Arnhem and Rozendaal</p>
        <p>This series begins near Wageningen and Bennekom with <b>Oostereng</b>: the 685-hectare forest district of Staatsbosbeheer on the border of three municipalities, where Leiden soap boilers planted barren ground from 1847 for forest wool and where the forgotten Arboretum Oostereng from 1911 and Bell Beaker burial mounds lie in the woods. South of the A12 follow two quiet areas between Wolfheze and Papendal: <b>Lange Hut en Grijsoord</b>, where the old boundary wall between Ede and Arnhem runs over the slope of the Papendal and the 1941 Bommenlijntje can still be traced, and the <b>Reierscamp</b> near Wolfheze, where Natuurmonumenten has been returning almost 200 hectares of farmland to heath since 2004 and where hundreds of gliders landed in September 1944 — the Jac. P. Thijsse wildlife crossing has linked the area with Planken Wambuis since 2012.</p>
        <p>In Arnhem-Noord lie three municipal nature gems: the <b>Westerheide</b>, a restored, flat heath field with Veluwe heath sheep, the Cirkelweg and a sheep drift between two game walls; the <b>Maasbergse bossen</b> with their 1932 boundary post and the monumental De Groote Kweek farmstead; and <b>Berkenhove</b>, a quiet woodland-field name at the edge of the great forests. Further on waits <b>Wolfheze</b> with the church mound of vanished Oud-Wolfheze, the monumental Wodan oaks along the Wolfhezerbeek and the Airborne monument of 1944. Between Oosterbeek and Wolfheze lie the estates of <b>Sonnenberg and Bilderberg</b>: banker Van Tienhoven had a villa built there in 1913 in a garden by Samuel Voorhoeve — it became Hotel De Bilderberg, where the first Bilderberg Conference was held in 1954, while the open fields were a battlefield during the Battle of Arnhem in September 1944. The <b>Johannahoeve</b> north of Wolfheze gave the space back to red deer in 2020: the fences came down and the heath restoration began.</p>
        <p>In the estate belt between Arnhem and Oosterbeek follow <b>Lichtenbeek and Vijverberg</b>, with the monumental 1750 garden vases of the burnt-down Lichtenbeek manor and the ponds, spring streams and waterfalls of De Vijverberg. Behind them lie <b>Warnsborn and Hoog Erf</b> of Geldersch Landschap &amp; Kasteelen: the name refers to a clear spring from 1428, and around hotel Groot Warnsborn lie the garden of H. Copijn, the romantic Klein-Zwitserland zone and the six-pointed avenues of Hoog Erf. <b>Schaarsbergen</b> is the 1849 reclamation village with the municipality\u2019s demo forest, and in the fork of the A50 and A12 lies the <b>Koningsheide</b>: fully grown again after the great forest fire of 1976, with a deep dry valley — the slenk — and since 2020 a 70-hectare forest reserve next to the primeval forest on <b>De Waterberg</b>, where in 2015 the municipality was the first on the Veluwe to return 80 hectares to nature and from which the Open Air Museum was born. <b>Valkenhuizen</b>, finally, recalls in its name the falcon house of the Arnhem hunting culture.</p>
        <p>The series ends in the municipality of Rozendaal and Arnhem. The <b>Rozendaalse Veld</b> is the vast, silent heath field of the northern Veluwezoom, where red deer move between Deelen and the ice-margin ridge. Beside it lie the castle and park landscape of <b>Landgoed Rosendaal</b> — Rosendael Castle with the largest keep of the Netherlands, the trick fountains and the shell gallery —, the village of <b>Rozendaal</b>, the smallest municipality of the Netherlands, and <b>Rosendaal</b>, the ancient forest around the castle also known as the Rozendaalse Bos. And in Arnhem itself, <b>Sonsbeek, Zijpendaal and Gulden Bodem</b> form the green finger of the Veluwe reaching to the centre: along the Sint-Jansbeek with its ten historic water mills lie the Great Waterfall from 1826, the Belvédère, the Witte Watermolen and the Netherlands Water Museum — the cradle of Arnhem.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
