# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Oirschot naar de Buikheide: 2333–2352</h3>
        <p class="post-meta">List 88 vervolg · Sonderen en Hoekvelden Oude Steeg, Nieuwe Heide, Sonsche Heide, Dommelrode en Breugelsbroek, Ruweeuwsels, Heerendonk, Nuenen, Het Stuk, Turkaa, De Katschut, Spreeuwelse Heide, Kuikeindse Heide, Spekdonken en Molenbroek, Landschotse Heide, Donk, Neterselse Heide, Dal van de Groote Beerze, Gemeentebossen Hoogeloon, Heieinden, Buikheide Oude Molen</p>
        <p>Nog eens twintig kaarten, en de gids telt nu <b>2.352 van de 2.373 boekgebieden (99,1%)</b> — nog maar 21 te gaan. Deze batch volgde de rand van de Kempen: van de poelen en houtwallen bij <b>Oirschot</b> via het Van Gogh-land van <b>Nuenen</b> naar de vennen- en beekdalenlandschap rond <b>Westelbeers, Netersel en Hoogeloon</b>. (Twee scan-dubbels gingen er weer af: “De Mortelen en Heerenbeek” bleek kaart 303, “De Utrecht” stond al bij list 87.)</p>
        <p>Het noordelijke deel stond in het teken van <b>Van Gogh</b>: de <b>Sonsche Heide</b> (±300 ha, met het 34-ha reservaat rond het <b>Oud Meer</b>) is onderdeel van het <b>Van Gogh Nationaal Park</b>, en in <b>Nuenen</b> schilderde Vincent in <b>1883–1885</b> een kwart van zijn hele oeuvre — <b>Het Stuk</b> (143 ha) herbergt intussen een van de <b>oehoe-paren</b> van Brabant. De <b>Nieuwe Heide</b> bij Eersel kreeg het grootste toekomstplan: 277 ha bos die in <b>2023–2070</b> stap voor stap terug naar heide en ven. En het <b>Turkaa</b> bij Bladel bewees dat klein ook groot kan: ±10 ha met ijsvogelwand, vleermuizenkelder en belevingspad. Eén kaart kreeg het ⚠️-stempel: <b>De Katschut</b> is in geen enkele publieke bron te vinden en werd uit regionale context opgebouwd.</p>
        <p>Dan de Kempen-gordel zelf: de <b>Spreeuwelse Heide</b> bleek allang bos (alleen de naam herinnert aan de hei), de <b>Kuikeindse Heide</b> is de beboste helft van het complex, en in de <b>Spekdonken</b> graaft het project <b>De Levende Beerze</b> sinds 2022 een nieuwe kronkelende beek. De <b>Landschotse Heide</b> (239 ha, “de Keienhurk”) met vijf vennen, <b>±30 libellensoorten</b>, piramide-uitkijktoren (2014) en rolstoelpad kreeg <b>Natura 2000 Kempenland-West</b> — net als de <b>Neterselse Heide</b>, in <b>2004 voor €1</b> gekocht van de gemeente Bladel, en het <b>Dal van de Groote Beerze</b> (298 ha), waar de beek zelf binnen het Natura 2000-gebied ligt en in 2021–22 opnieuw ging meanderen — compleet met een <b>voorde</b>. De <b>Gemeentebossen Hoogeloon</b> brachten de diepste historie: al in de <b>16e eeuw</b> gemeenschapsbezit, met de <b>Kabouterberg</b> — een gereconstrueerde <b>Romeinse grafheuvel</b> — en een villa-akker met oude graanrassen. Slot: de <b>Buikheide</b> bij Wintelre met het <b>Grootmeer</b> en <b>Kleinmeer</b>, nooit verzuurde Weichselien-vennen en sinds 1990 beschermd natuurmonument, pal naast de grafheuvels van <b>Toterfout-Halfmijl</b>. Volgende batch: het slot van list 88 — de laatste 21 gebieden.</p>
      </div>
      <div class="c-en">
        <h3>From Oirschot to the Buikheide: 2333–2352</h3>
        <p class="post-meta">List 88 continued · Sonderen en Hoekvelden Oude Steeg, Nieuwe Heide, Sonsche Heide, Dommelrode en Breugelsbroek, Ruweeuwsels, Heerendonk, Nuenen, Het Stuk, Turkaa, De Katschut, Spreeuwelse Heide, Kuikeindse Heide, Spekdonken en Molenbroek, Landschotse Heide, Donk, Neterselse Heide, Dal van de Groote Beerze, Gemeentebossen Hoogeloon, Heieinden, Buikheide Oude Molen</p>
        <p>Another twenty cards, and the guide now counts <b>2,352 of the 2,373 book sites (99.1%)</b> — only 21 to go. This batch traced the edge of the Campine: from the ponds and hedgerows of <b>Oirschot</b> via Van Gogh’s <b>Nuenen</b> to the pool and stream-valley landscape around <b>Westelbeers, Netersel and Hoogeloon</b>. (Two scan duplicates dropped off again: “De Mortelen en Heerenbeek” proved to be card 303, “De Utrecht” already sat in list 87.)</p>
        <p>The northern part stood in the sign of <b>Van Gogh</b>: the <b>Sonsche Heide</b> (±300 ha, with the 34-ha reserve around the <b>Oud Meer</b>) belongs to the <b>Van Gogh National Park</b>, and in <b>Nuenen</b> Vincent painted a quarter of his entire oeuvre in <b>1883–1885</b> — <b>Het Stuk</b> (143 ha) now shelters one of Brabant’s <b>eagle-owl pairs</b>. The <b>Nieuwe Heide</b> near Eersel received the grandest future plan: 277 ha of woodland stepping back to heath and fen between <b>2023 and 2070</b>. And the <b>Turkaa</b> near Bladel proved small can be great: ±10 ha with a kingfisher screen, bat cellar and experience trail. One card got the ⚠️ stamp: <b>De Katschut</b> appears in no public source and was built up from regional context.</p>
        <p>Then the Campine belt itself: the <b>Spreeuwelse Heide</b> turned out to be woodland long ago (only the name remembers the heath), the <b>Kuikeindse Heide</b> is the afforested half of the complex, and in the <b>Spekdonken</b> the <b>Living Beerze</b> project has been digging a new winding stream since 2022. The <b>Landschotse Heide</b> (239 ha, “de Keienhurk”) with five pools, <b>±30 dragonfly species</b>, a pyramid lookout (2014) and a wheelchair path received <b>Natura 2000 Kempenland-West</b> — as did the <b>Neterselse Heide</b>, bought for <b>€1</b> from the municipality of Bladel in <b>2004</b>, and the <b>Dal van de Groote Beerze</b> (298 ha), where the stream itself lies inside the Natura 2000 site and began meandering again in 2021–22 — complete with a <b>ford</b>. The <b>Gemeentebossen Hoogeloon</b> brought the deepest history: common land since the <b>16th century</b>, with the <b>Kabouterberg</b> — a reconstructed <b>Roman barrow</b> — and a villa field of old grain varieties. Finale: the <b>Buikheide</b> near Wintelre with the <b>Grootmeer</b> and <b>Kleinmeer</b>, never-acidified Weichselian fens and a protected nature monument since 1990, right beside the <b>Toterfout-Halfmijl</b> barrows. Next batch: the finale of list 88 — the last 21 areas.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #106 toegevoegd')
