# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Zeeuwse kreken, klavers en een zeefort: 2213–2232</h3>
        <p class="post-meta">Lists 83–84 · Wallen van Retranchement, De Knokkert, Baarzandse Kreek, De Blikken, De Reep, Dijken Oostburg, Het Grote Gat, Aardenburgse havenpolder, de graslanden van de Oude Veerseweg, Zilveren Schor, het heggengebied van Arnemuiden, Goudplaat, Schenge, Sabbingedijk, de dijkbeemden, het Weel in de Heerenpolder, Deesche Watergang, Ter Hooge en Fort Rammekens</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.232 van de 2.373 boekgebieden (94,1%)</b> — de honderdste blogpost van dit project. Deze batch is geheel Zeeuws: van de Staats-Spaanse Linies in Zeeuws-Vlaanderen tot het oudste zeefort van Noordwest-Europa, en van verdronken polders op Walcheren tot een voormalige zandplaat in het Veerse Meer.</p>
        <p>In Zeeuws-Vlaanderen stonden de <b>Wallen van Retranchement</b> vooraan: het vestingwerk van Prins Maurits (1630–1640) met drie bastions en een natte veste, beroemd om <b>vier zeldzame klavers</b> — kleine rupsklaver, ruwe, gestreepte en onderaardse klaver — en in 2010 tot in detail gereconstrueerd. Daarnaast de kleine parels van de inundatiegeschiedenis: de <b>Baarzandse Kreek</b> (1585, hersteld met geld van Jacob Cats), <b>De Blikken</b> (45 ha, geïnundeerd 1583, herinpolderd 1613 — het getij schreef het kreekpatroon), <b>De Reep</b> (zijgeul van het Nieuwerhavense Gat, later havenvaart naar Oostburg) en <b>Het Grote Gat</b> (36 ha krekenstelsel met ijsvogel). Het <b>Bos van Erasmus</b> — De Knokkert bij Cadzand — bewaarde door traditionalistisch boerenwerk hakhout, meidoornhagen en drinkputten; de <b>Aardenburgse havenpolder</b> (uit de tijd van Napoleon) huisvest boomkikker en kamsalamander in de poelen bij de schansen.</p>
        <p>Walcheren en Beveland brachten evenveel variatie: de <b>graslanden van de Oude Veerseweg</b> (moernering, zoute kwel, lepelaars), het <b>heggengebied van Arnemuiden</b> (3,4 ha doolhof van meidoorn en sleedoorn, gered uit handen van de ruilverkaveling), <b>Zilveren Schor</b> (bebouwde schorren van na 1961 met wielewaal en baardmannetjes), <b>Goudplaat</b> (drooggevallen zandplaat met Przewalskipaarden), de <b>Schenge</b> (oude zeearm en verdronken dorp; Wolphaartsdijk was tot 1809 een eiland), het <b>Weel in de Heerenpolder</b> (getijdengeul, binnendijks sinds 1649), de <b>Deesche Watergang</b> (middeleeuwse Wijtvliet, ± 1190 bedijkt, met de zeldzame graslatyrus), <b>Ter Hooge</b> (de laatste buitenplaats van Walcheren, 200+ paddenstoelensoorten) en als slot <b>Fort Rammekens</b> (1547–1557, oudste zeefort van Noordwest-Europa) met het enige schor van Walcheren en de kreken van 1944. Volgende batch: de rest van list 84 (Bloemdijken Zuid-Beveland, Poelbos, spoorbaan Goes–Borsele en meer).</p>
      </div>
      <div class="c-en">
        <h3>Zeeland creeks, clovers and a sea fort: 2213–2232</h3>
        <p class="post-meta">Lists 83–84 · Wallen van Retranchement, De Knokkert, Baarzandse Kreek, De Blikken, De Reep, dikes of Oostburg, Het Grote Gat, Aardenburg haven polder, the Oude Veerseweg grasslands, Zilveren Schor, the Arnemuiden hedge area, Goudplaat, Schenge, Sabbingedijk, the dike meadows, the Weel in the Heerenpolder, Deesche Watergang, Ter Hooge and Fort Rammekens</p>
        <p>Another twenty cards, and the guide now counts <b>2,232 of the 2,373 book sites (94.1%)</b> — the hundredth blog post of this project. This batch is entirely Zeeland: from the State-Spanish Lines in Zeeuws-Vlaanderen to the oldest sea fort of Northwest Europe, and from drowned polders on Walcheren to a former sand plate in the Veerse Meer.</p>
        <p>In Zeeuws-Vlaanderen the <b>Wallen van Retranchement</b> led: Prince Maurice’s fortress (1630–1640) with three bastions and a wet moat, famed for <b>four rare clovers</b> — and reconstructed in detail in 2010. Beside it the small pearls of inundation history: the <b>Baarzandse Kreek</b> (1585, repaired with money from Jacob Cats), <b>De Blikken</b> (45 ha, inundated 1583, re-embanked 1613 — the tide wrote the creek pattern), <b>De Reep</b> (side channel of the Nieuwerhavense Gat, later the harbour run to Oostburg) and <b>Het Grote Gat</b> (36 ha of creek system with kingfisher). The <b>Forest of Erasmus</b> — De Knokkert near Cadzand — preserved coppice, hawthorn hedges and drinking wells through traditional farming; the <b>Aardenburg haven polder</b> (from the age of Napoleon) shelters tree frog and great crested newt in the pools by the sconces.</p>
        <p>Walcheren and Beveland brought equal variety: the <b>Oude Veerseweg grasslands</b> (peat digging, salt seepage, spoonbills), the <b>Arnemuiden hedge area</b> (3.4 ha labyrinth of hawthorn and blackthorn, rescued from land consolidation), <b>Zilveren Schor</b> (wooded marshes of after 1961 with golden oriole and bearded tits), <b>Goudplaat</b> (dried-out sand plate with Przewalski horses), the <b>Schenge</b> (old sea arm and drowned village; Wolphaartsdijk was an island until 1809), the <b>Weel in the Heerenpolder</b> (tidal channel embanked since 1649), the <b>Deesche Watergang</b> (medieval Wijtvliet, embanked ± 1190, with the rare grass vetchling), <b>Ter Hooge</b> (the last country seat of Walcheren, 200+ fungus species) and as finale <b>Fort Rammekens</b> (1547–1557, the oldest sea fort of Northwest Europe) with Walcheren’s only salt marsh and the creeks of 1944. Next batch: the rest of list 84 (flower dikes of Zuid-Beveland, Poelbos, the Goes–Borsele railway and more).</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #100 toegevoegd')
