# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van Hatertse Broek tot Aalten: het Rijk van Nijmegen en de Achterhoekse coulissen (2095–2114)</h3>
        <p class="post-meta">List 36 · Van de Nijmeegse zuidrand via Mook, Beek en de Duivelsberg naar Groesbeek en Malden — en dan de overkant van de Gelderse Poort: de Achterhoek van Winterswijk en Varsseveld tot Aalten</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.114 van de 2.373 boekgebieden (89,1%)</b>. Het eerste tientje volgt de rand van het Rijk van Nijmegen. In de stad zelf: het <b>Hatertse Broek</b> (45,5 ha GLK-stadsnatuur op oude broekgronden, voor insiders de Vogelzang, met das, vos, ree en daslook) en het <b>Hengstdal</b>, een langgerekt erosiedal uit de laatste ijstijd waar de zeer zeldzame <b>eikenzandbij</b> de doelsoort is. Dan landgoederen: <b>De Elshof</b> (± 1770, 28 morgen hoogland en 28 morgen broekland, het Stoppelaarsbos), de <b>Heerlijkheid Beek</b> met de <b>Kabouterboom</b> van 850 cm uit het begin van de 16e eeuw, <b>Heumensoord</b> (500 ha Natuurmonumenten met beukenlanen, rododendrons en een Romeinse wachtpost) en <b>Vier Perken en Westermeerwijk</b> — restant van het middeleeuwse Nederrijkswoud, met de percelen berkenhakkout van ± 1768 en een urnenveld.</p>
        <p>Aan de Duitse grens volgt het hoogste en meest geladen stuk: de <b>Duivelsberg</b>, 75,9 meter hoog, Duits tot de annexatie van 1949 en pas in 1963 definitief Nederlands, met de middeleeuwse motte bovenop; <b>Nederrijk</b>, het oerbosrestant dat tot de 15e eeuw één geheel vormde met de Reichswald en in 1916 door margarinefabrikant Jurgens werd gekocht; de <b>Groesbeekse bossen</b> met de Canadese erebegraafplaats van 2.617 graven aan de Zevenheuvelenweg van de Vierdaagse; en tot slot <b>Maldens Vlak</b>, ± 77 ha gemeentebos met sinds 1958 het zweefvliegveld midden tussen de bomen — das, ree en wilde zwijn als stille gebruikers.</p>
        <p>Dan de Achterhoek, van Winterswijk via Varsseveld naar Aalten: <b>Dennenoord</b> (gemeentelijk bos- en zwemterrein met het paviljoen dat voor tbc-lijders leeg bleef en het natuurzwembad ’t Walfort van 1934), het <b>Noorderbroek</b> waar de Boven Slinge door het wandelbos van Varsseveld stroomt, <b>Tandem-Vlaswinkel</b> met Canadese inscripties uit 1945 en lelietje-van-dalen, het particuliere <b>Hiddink</b> met zijn greppels, en het <b>Leemscherbos</b> met zijn eeuwenoude eiken en blauwe reigerkolonie. De sluitpost is Aalten: de <b>Vennebulten</b> (40 ha jeneverbes, heide en vennen op de Halserug, waar schaapherder Wisselink tot 1945 de heide hield en stichting De Vennemarke dat weer doet), het <b>Aaltense Goor</b> (200 ha coulissen van de 18e-eeuwse ontginning — in 2021 zelfs een flamingo), het NSW-landgoed <b>Eppink</b> aan de Romienendiek met hoogstamboomgaard, knechtenhuusken en pauwen, <b>Loohuis</b> van Natuurmonumenten (1927, twee bosplassen, rosse vleermuis, en de Ringkampsbulten als hoogste punt van Aalten) en ten slotte de <b>Aalten landschapselementen</b> — het netwerk van houtwallen, singels en poelen dat alles aaneenrijgt. Volgende batch: verder de Achterhoek in, vanaf het Walfort.</p>
      </div>
      <div class="c-en">
        <h3>From Hatertse Broek to Aalten: the Rijk van Nijmegen and the Achterhoek hedgerows (2095–2114)</h3>
        <p class="post-meta">List 36 · From the Nijmegen southern rim via Mook, Beek and the Duivelsberg to Groesbeek and Malden — and then beyond the Gelderse Poort: the Achterhoek from Winterswijk and Varsseveld to Aalten</p>
        <p>Another twenty cards, and the guide now counts <b>2,114 of the 2,373 book sites (89.1%)</b>. The first ten follow the rim of the Rijk van Nijmegen. In the city itself: the <b>Hatertse Broek</b> (45.5 ha of GLK urban nature on old brook soils, the Vogelzang to locals, with badger, fox, roe deer and wild garlic) and the <b>Hengstdal</b>, a long melt-water erosion valley from the last ice age where the very rare <b>oak sand bee</b> is the target species. Then the estates: <b>De Elshof</b> (± 1770, 28 morgen of high land and 28 of brook land, the Stoppelaarsbos), <b>Heerlijkheid Beek</b> with the <b>Kabouterboom</b> of 850 cm girth from the early 16th century, <b>Heumensoord</b> (500 ha of Natuurmonumenten with beech avenues, rhododendrons and a Roman watch post) and <b>Vier Perken en Westermeerwijk</b> — a remnant of the medieval Nederrijkswoud, with the 1768-ish birch-coppice parcels and an urnfield.</p>
        <p>At the German border comes the highest and most charged stretch: the <b>Duivelsberg</b>, 75.9 metres high, German until the 1949 annexation and only definitively Dutch in 1963, with the medieval motte on top; <b>Nederrijk</b>, the primeval-wood remnant that formed one whole with the Reichswald until the 15th century and was bought in 1916 by margarine manufacturer Jurgens; the <b>Groesbeek woods</b> with the Canadian war cemetery of 2,617 graves on the Four Days’ Zevenheuvelenweg; and finally <b>Maldens Vlak</b>, ± 77 ha of municipal woodland with the glider field among the trees since 1958 — badger, roe deer and wild boar as its silent users.</p>
        <p>Then the Achterhoek, from Winterswijk via Varsseveld to Aalten: <b>Dennenoord</b> (municipal wood and swimming ground with the pavilion that stayed empty waiting for TB patients and the 1934 ’t Walfort natural pool), the <b>Noorderbroek</b> where the Boven Slinge flows through Varsseveld’s walking wood, <b>Tandem-Vlaswinkel</b> with Canadian inscriptions from 1945 and lily-of-the-valley, the private <b>Hiddink</b> wood with its ditches, and the <b>Leemscherbos</b> with its centuries-old oaks and grey heron colony. The closing post is Aalten: the <b>Vennebulten</b> (40 ha of juniper, heather and pools on the Halserug, where shepherd Wisselink kept the heath until 1945 and the De Vennemarke foundation does so again), the <b>Aaltense Goor</b> (200 ha of hedgerows from the 18th-century reclamation — even a flamingo in 2021), the Eppink Nature Beauty Act estate on the Romienendiek with its standard orchard, servants’ cottage and peacocks, <b>Loohuis</b> of Natuurmonumenten (1927, two forest pools, brown long-eared bat, and the Ringkampsbulten as the highest point of Aalten) and finally the <b>Aalten landscape elements</b> — the network of hedgerows, belts and ponds stringing it all together. Next batch: deeper into the Achterhoek, starting at ’t Walfort.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #94 toegevoegd')
