# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van de Peel naar de Zeeuwse kust: 2193–2212</h3>
        <p class="post-meta">Lists 81 en 83 · Goorbos, Boscomplex Odiliapeel, Voskuilenheuvel, Sint Anthonisbos, Brestbosch en Sassekamp, Veghel en Erp, Het Leijnt, Gemeentebossen Lieshout, Het Hurkske, Gemertse Bos, De Sijp, Beestenveld, Radiobossen, Lactaria, Zwartwater, Ballonzuilbossen — en de eerste vier kaarten van Zeeland</p>
        <p>Weer twintig kaarten, en de gids telt nu <b>2.212 van de 2.373 boekgebieden (93,2%)</b>. Deze batch loopt van de kleine bosgordel bij Schaijk via de hart van de Peel naar de zilte kust van Zeeuws-Vlaanderen — een reis van veen, zand en zout in één middag.</p>
        <p>In de Peel stonden de verrassingen dicht op elkaar. Het <b>Boscomplex Odiliapeel</b> blijkt het bos van het verdwenen turfstadje <b>Terraveen</b> (1922) — met een WWII-bunker en -loopgraaf rond wat nu de vliegbasis Volkel is, het rolstoelvriendelijke <b>Jeanny van Kuppeveltpad</b> en de kettingzaagkunst van André van Boxtel. De <b>Radiobossen</b> bij Stevensbeek dragen het verhaal van <b>Radio Sambeek (1919)</b> in zich: een ontvangststation met zeven masten van 61,5 m voor de langegolfzenders van Bandoeng — de zender zelf moest 60 km verderop komen en werd Radio Kootwijk. <b>Lactaria</b> heet naar de proefboerderij van 1909 (725 ha) die uitgroeide tot Vredepeel — en toevallig naar de melkzwam. De <b>Ballonzuilbossen</b> bewaren de zuil die op 18 januari 1896 werd opgericht voor de ballon “La poste de Paris”, die in de natte heide neerkwam. En <b>De Sijp</b> is het landgoed dat bankier Ledeboer in 1895 kocht, met beukenlanen op een sikkelduin uit het Weichselien en de Augustehoeve van 1927.</p>
        <p>De Meierij leverde de stillere parels: het <b>Het Leijnt</b> bij Zijtaart met zijn schoolvoorbeeld van een natuurlijke bosrand (± 4 ha, 20–25 m zachte overgang), de <b>Gemeentebossen Lieshout</b> (158 ha) met het Torreven en het in 2019 herstelde Vossenbergven op de 10.000 jaar oude dekzandrug, en het <b>Hurkske</b> tussen Erp en Gemert met het licht kalkrijke <b>Rauwven</b> en zijn salamanders. Dan Zeeland: de <b>Kuststrook Walcheren</b> met de “Zeeuwse Rivièra”, het oudste bos van Walcheren en tienduizenden trekvogels; <b>Het Zwin en Kievittepolder</b> (Natura 2000) als oude zeearm naar Brugge; de <b>Oudelandse Polder</b> met de oudste inpolderingen van West-Europa; en de <b>Verdronken Zwarte Polder</b>, waar de dijkdoorbraak van 1802 een slufter met plankenpaden schiep. Volgende batch: Zeeland verder in (Vliedbergen, Wallen van Retranchement, De Knokkert en de Vlissingse en Middelburgse havennatuur).</p>
      </div>
      <div class="c-en">
        <h3>From the Peel to the Zeeland coast: 2193–2212</h3>
        <p class="post-meta">Lists 81 and 83 · Goorbos, Odiliapeel forest complex, Voskuilenheuvel, Sint Anthonisbos, Brestbosch and Sassekamp, Veghel and Erp, Het Leijnt, Lieshout municipal woods, Het Hurkske, Gemertse Bos, De Sijp, Beestenveld, Radiobossen, Lactaria, Zwartwater, Ballonzuilbossen — and the first four cards of Zeeland</p>
        <p>Another twenty cards, and the guide now counts <b>2,212 of the 2,373 book sites (93.2%)</b>. This batch runs from the small wood belt near Schaijk through the heart of the Peel to the salty coast of Zeeuws-Vlaanderen — a journey of bog, sand and salt in one afternoon.</p>
        <p>In the Peel the surprises came thick and fast. The <b>Odiliapeel forest complex</b> turns out to be the wood of the vanished peat town of <b>Terraveen</b> (1922) — with a WWII bunker and trench around what is now Volkel air base, the wheelchair-friendly <b>Jeanny van Kuppeveltpad</b> and the chainsaw art of André van Boxtel. The <b>Radiobossen</b> near Stevensbeek carry the story of <b>Radio Sambeek (1919)</b>: a receiving station with seven 61.5-m masts for the long-wave transmitters of Bandoeng — the transmitter itself had to stand 60 km away and became Radio Kootwijk. <b>Lactaria</b> is named after the 1909 model farm (725 ha) that grew into Vredepeel — and coincidentally after the milk cap fungus. The <b>Ballonzuilbossen</b> keep the pillar erected on 18 January 1896 for the balloon “La poste de Paris”, which came down in the wet heath. And <b>De Sijp</b> is the estate banker Ledeboer bought in 1895, with beech avenues on a Weichselian crescent dune and the 1927 Augustehoeve farm.</p>
        <p>The Meierij yielded the quieter jewels: <b>Het Leijnt</b> near Zijtaart with its textbook natural wood edge (± 4 ha, a 20–25 m soft transition), the <b>Lieshout municipal woods</b> (158 ha) with the Torreven and the Vossenbergven restored in 2019 on the 10,000-year-old cover-sand ridge, and <b>Het Hurkske</b> between Erp and Gemert with the slightly calcareous <b>Rauwven</b> and its newts. Then Zeeland: the <b>Walcheren coastal strip</b> with the “Zeeland Riviera”, the island’s oldest wood and tens of thousands of migrating birds; <b>Het Zwin and Kievittepolder</b> (Natura 2000) as the old sea arm to Bruges; the <b>Oudelandse Polder</b> with the oldest reclamations of Western Europe; and the <b>Drowned Black Polder</b>, where the 1802 dike breach created a slufter with boardwalks. Next batch: further into Zeeland (Vliedbergen, Wallen van Retranchement, De Knokkert and the harbour nature of Vlissingen and Middelburg).</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #99 toegevoegd')
