# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Van het Woudhuis naar Kasteel Oolde (1815–1834)</h3>
        <p class="post-meta">List 36 · Gelderland: Apeldoorn, Beekbergen, Klarenbeek, Voorst, Gorssel en Laren</p>
        <p>Deze reeks begint bij Apeldoorn met <b>Het Woudhuis</b>: een oud cultuurlandschap van rabatten en een ‘kamerlandschap’ met bloemrijke weilanden, meertjes en bruggetjes, waar het productiebos plaatsmaakt voor natuurbos. Via de <b>Beekbergse Beek</b>, die met haar heldere kwelwater hoog door het landschap slingert, komt u bij het beroemdste bosverhaal van Nederland: het <b>Beekbergerwoud</b>, waar achtduizend jaar bos stond tot op 10 juni 1871 de laatste boom werd geveld — Natuurmonumenten brengt sinds 2006 een nieuw, weelderig broekbos van circa 300 hectare terug. Ernaast ligt het <b>Lampenbroek</b>, het natte hooilanden- en houtwallenlandschap van de Beekberger Poort, de ecologische schakel tussen Veluwe en IJsseldal, dat tussen 2024 en 2026 is heringericht.</p>
        <p>In de landgoederengordel rond Klarenbeek en Voorst volgen <b>Landgoed Klarenbeek</b>, dat maar liefst tien rijksmonumenten telt en wordt doorkruist door het Klarenbeeksepad, en de witte buitenplaats <b>Ekeby</b> uit 2014 gerestaureerd. Verderop liggen het oude, mosrijke <b>Appense Bos</b> en het 500 hectare grote <b>Landgoed Beekzicht</b>, dat zich van het Appense Veld met zijn grafheuvels uitstrekt tot aan de IJssel. Dwars door dit landschap loopt de <b>Veluwse Bandijk</b>: het middeleeuwse dijkenstelsel tussen Wapenveld en Klarenbeek, waarvan de Appense Dijk rond 1435 bewaard bleef als wandelpad met schouwpaaltjes, kolken en bomendijk. Dan volgt het water: de <b>Wilperwaarden</b> — de Wilpse Klei — met kolken, meidoornhagen en winterganzen, de <b>Ravenswaarden</b> bij Gorssel, een van de best bewaarde kronkelwaarden van Nederland, en de vogelrijke <b>Rammelwaard</b> in de binnenbocht van de IJssel bij slot De Nijenbeek — alle drie deel van Natura 2000 Uiterwaarden IJssel. In de Achterhoek ligt <b>Het Zand</b>: het 375 hectare grote familiebos bij Zelhem, ooit markegrond, na de bosbrand van 1929 heringericht met bos, weiland en akker.</p>
        <p>Tussen Gorssel en Laren ten slotte liggen de landgoederen en heidevelden van de Achterhoekse rand: het bosgoed <b>Herwalt</b> met zijn rabattenbossen en slingerende paadjes, het kleine <b>Wogbos</b> ten zuiden van <b>Het Joppe</b> — het buurtschap met kasteel ’t Joppe uit circa 1740, Engelse landschapstuin, taxushagen, berceau en de V1-laan uit de Tweede Wereldoorlog — en de <b>Gorsselse Heide</b>, het voormalige militaire oefenterrein dat inwoners via de Marke Gorsselse Heide zelf herstellen en beheren. Daarachter liggen het waterrijke, bewust onbegaanbaar gehouden <b>Larense Broek</b> en <b>Kasteel Oolde</b> bij Laren, met de beroemde Copijn-zichtassen die dwars door een boom lopen. En <b>De Lange Oorden</b>? Die naam uit de gids is vooralsnog niet aan een terrein te koppelen — deze kaart registreert hem eerlijk, tussen de wél beschreven parels van de IJsselvallei en de Achterhoek.</p>
      </div>
      <div class="c-en">
        <h3>From Het Woudhuis to Kasteel Oolde (1815–1834)</h3>
        <p class="post-meta">List 36 · Gelderland: Apeldoorn, Beekbergen, Klarenbeek, Voorst, Gorssel and Laren</p>
        <p>This series begins near Apeldoorn with <b>Het Woudhuis</b>: an old cultural landscape of ridge-and-furrow beds and a ‘chamber landscape’ with flower-rich meadows, little lakes and footbridges, where production forest is making way for nature forest. Via the <b>Beekbergse Beek</b>, which winds high through the landscape on clear seepage water, you reach the most famous forest story of the Netherlands: the <b>Beekbergerwoud</b>, where forest stood for eight thousand years until 10 June 1871, when the last tree was felled — since 2006 Natuurmonumenten has been bringing back a new, lush wet forest of about 300 hectares. Beside it lies the <b>Lampenbroek</b>, the wet hay-meadow and hedgerow landscape of the Beekberger Poort, the ecological link between the Veluwe and the IJssel valley, redesigned between 2024 and 2026.</p>
        <p>In the estate belt around Klarenbeek and Voorst follow <b>Landgoed Klarenbeek</b>, which counts no fewer than ten listed monuments and is crossed by the Klarenbeeksepad farm trail, and the white country house <b>Ekeby</b>, restored in 2014. Further on lie the old, mossy <b>Appense Bos</b> and the 500-hectare <b>estate Beekzicht</b>, which stretches from the Appense Veld with its burial mounds to the IJssel. Straight through this landscape runs the <b>Veluwse Bandijk</b>: the medieval dike system between Wapenveld and Klarenbeek, of which the Appense Dijk from around 1435 survives as a walking path with inspection posts, breach pools and a tree dike. Then comes the water: the <b>Wilperwaarden</b> — the Wilpse Klei — with scour pools, hawthorn hedges and winter geese, the <b>Ravenswaarden</b> near Gorssel, one of the best-preserved scroll-meander floodplains of the Netherlands, and the bird-rich <b>Rammelwaard</b> in the inner bend of the IJssel near Nijenbeek castle — all three part of Natura 2000 Uiterwaarden IJssel. In the Achterhoek lies <b>Het Zand</b>: the 375-hectare family forest near Zelhem, once common marke land, redesigned after the forest fire of 1929 with forest, meadow and field.</p>
        <p>Finally, between Gorssel and Laren lie the estates and heath fields of the Achterhoek fringe: the wooded estate <b>Herwalt</b> with its ridge-and-furrow woods and winding paths, the small <b>Wogbos</b> south of <b>Het Joppe</b> — the hamlet with ’t Joppe castle from around 1740, English landscape garden, yew hedges, berceau and the V1 avenue from the Second World War — and the <b>Gorsselse Heide</b>, the former military training ground that residents restore and manage themselves through the Marke Gorsselse Heide. Behind them lie the water-rich, deliberately inaccessible <b>Larense Broek</b> and <b>Kasteel Oolde</b> near Laren, with the famous Copijn sight axes that run straight through a tree. And <b>De Lange Oorden</b>? That name from the guide cannot yet be linked to a site — this card registers it honestly, among the documented gems of the IJssel valley and the Achterhoek.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog toegevoegd')
