# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mk

post = '''<div class="post">
      <div class="c-nl">
        <h3>Manteling, bloemdijken en nieuwe Delta-natuur: Walcheren, Flakkee en Tholen (2153–2172)</h3>
        <p class="post-meta">List 75–77 · De Manteling van Walcheren en landgoed Zeeduin, de bloemdijken, kreken en bossen van Goeree-Overflakkee, Dijkwater en Steenzwaan op Schouwen, en het Tholen/Sint Philipsland van kreken, kooien en gorzen</p>
        <p>Twintig kaarten deze keer, en de gids telt nu <b>2.172 van de 2.373 boekgebieden (91,5%)</b>. De batch opent met een klassieker: <b>De Manteling van Walcheren</b> — Natura 2000-gebied nr. 117 (NL1000020, ± 735 ha), de buitenplaatsenzone waar de Middelburgse VOC-elite zomers woonde tussen lanen en duineiken die eind 18e eeuw als levende "mantel" werden aangeplant. Aan de zeekant staan de beroemde <b>"Zeeuwse bonsaiboompjes"</b>: eikenstruweel van tweehonderd jaar oud dat nauwelijks een halve meter hoog komt, geschoren door wind en zout. Ernaast <b>landgoed Zeeduin</b> (buitenplaats vanaf 1726, in 1829 verdubbeld met het middeleeuwse Duno van de Abdij van Middelburg) — en een verrassende primeur: tijdens de inundatie van 1944 ontsnapten damherten uit het hertenpark van Zeeduin, de voorouders van de kudde van vandaag.</p>
        <p>Dan het eiland Goeree-Overflakkee: de <b>bloemdijken van West en Oost</b> (oude zeedijken uit de 15e en 16e eeuw die Staatsbosbeheer met zorgzaam maaibeheer tot bloemlinten houdt — agrimonie, knoopkruid, aardaker, ratelaar), de <b>kreken</b> als geraamte van het polderland, de jonge <b>bosobjecten</b>, de <b>Blanke Slikken</b> aan de Krammer (waar in de winter zeearenden op ganzen jagen) en de <b>grasgorzen van het Haringvliet</b>. Op Schouwen volgen twee wateren met een gedeelde stamboom: het <b>Dijkwater</b> en de <b>Steenzwaan</b> — de laatste restanten van de Gouwe, de rivier die Schouwen en Duiveland scheidde tot de dammen van 1374 en 1610. Het <b>Krekengebied Ouwerkerk</b> bewaart de littekens van 1953 naast de caissons van de laatste dijksluiting.</p>
        <p>De slotslag is Tholen en Sint Philipsland: de <b>Bruintjeskreek</b> (brak, 7 ha, grens tussen twee polders van 1847), de <b>eendenkooi</b> aan de Noordweg, het <b>Stinkgat</b> met zijn vogelkijkhut en hoogwatervluchtplekken, het <b>Rammegors</b> dat van zoutschor naar graasland zwaaide, de <b>Slikken van de Heen</b> achter de Philipsdam van 1987 (zeearend, koniks, rode geuzen en een uitkijktoren van 23 meter), de <b>Plaat van de Vliet</b> onder de rotoren van windpark De Krammer, en de <b>Dintelse Gorzen</b> als oostelijke sluitsteen. Volgende batch: verder door Brabant en de Deltagordel.</p>
      </div>
      <div class="c-en">
        <h3>Manteling, flower dikes and new Delta nature: Walcheren, Flakkee and Tholen (2153–2172)</h3>
        <p class="post-meta">Lists 75–77 · The Manteling of Walcheren and Zeeduin estate, the flower dikes, creeks and woods of Goeree-Overflakkee, Dijkwater and Steenzwaan on Schouwen, and the Tholen/Sint Philipsland of creeks, decoys and gorsen</p>
        <p>Twenty cards this time, and the guide now counts <b>2,172 of the 2,373 book sites (91.5%)</b>. The batch opens with a classic: <b>the Manteling of Walcheren</b> — Natura 2000 site no. 117 (NL1000020, ± 735 ha), the country-house belt where the Middelburg VOC elite spent its summers among avenues and dune oaks planted in the late 18th century as a living “mantle”. On the seaward side stand the famous <b>“Zeeland bonsai trees”</b>: two-hundred-year-old oak scrub barely half a metre tall, shorn by wind and salt. Beside it <b>Zeeduin estate</b> (a country seat from 1726, doubled in 1829 with medieval Duno of Middelburg Abbey) — with a surprising first: during the 1944 inundation fallow deer escaped from Zeeduin’s deer park, ancestors of today’s herd.</p>
        <p>Then the island of Goeree-Overflakkee: the <b>flower dikes of West and East</b> (15th- and 16th-century sea defences that Staatsbosbeheer keeps as flower ribbons with careful mowing — agrimony, knapweed, tuberous pea, rattle), the <b>creeks</b> as the polder land’s skeleton, the young <b>woodland objects</b>, the <b>Blanke Slikken</b> on the Krammer (where sea eagles hunt geese in winter) and the <b>grazing marshes of the Haringvliet</b>. On Schouwen follow two waters with a shared family tree: the <b>Dijkwater</b> and the <b>Steenzwaan</b> — the last remnants of the Gouwe, the river that parted Schouwen and Duiveland until the dams of 1374 and 1610. The <b>Krekengebied Ouwerkerk</b> keeps the scars of 1953 beside the caissons of the final closure.</p>
        <p>The closing run is Tholen and Sint Philipsland: the <b>Bruintjeskreek</b> (brackish, 7 ha, boundary between two polders of 1847), the <b>duck decoy</b> on the Noordweg, the <b>Stinkgat</b> with its bird hide and high-tide roosts, the <b>Rammegors</b> that swung from salt marsh to grazing land, the <b>Slikken van de Heen</b> behind the 1987 Philipsdam (sea eagle, koniks, red geuzen and a 23-metre watchtower), the <b>Plaat van de Vliet</b> beneath the rotors of De Krammer wind farm, and the <b>Dintelse Gorzen</b> as eastern keystone. Next batch: onward through Brabant and the Delta works belt.</p>
      </div>
    </div>'''

mk.blog(post)
print('blog #97 toegevoegd')
